Chaste: OxygenBasedCellKiller< SPACE_DIM > Class Template Reference
OxygenBasedCellKiller< SPACE_DIM > Class Template Reference
#include <OxygenBasedCellKiller.hpp>
Public Member Functions
OxygenBasedCellKiller (AbstractCellPopulation< SPACE_DIM > *pCellPopulation)
void TestAndLabelSingleCellForApoptosis (CellPtr pCell)
virtual void TestAndLabelCellsForApoptosisOrDeath ()
void OutputCellKillerParameters (out_stream &rParamsFile)
Private Member Functions
template<class Archive>
void serialize (Archive &archive, const unsigned int version)
Friends
class boost::serialization::access
Detailed Description
template<unsigned SPACE_DIM>
class OxygenBasedCellKiller< SPACE_DIM >
Kills cells that have experienced a prolonged continuous period of hypoxia.
The non-dimensionalised oxygen concentration at which cells become hypoxic is optionally passed into the constructor.
Definition at line 44 of file OxygenBasedCellKiller.hpp.
Constructor & Destructor Documentation
template<unsigned SPACE_DIM> OxygenBasedCellKiller< SPACE_DIM >::OxygenBasedCellKiller (AbstractCellPopulation< SPACE_DIM > * pCellPopulation) [inline]
Constructor.
Parameters:
pCellPopulation pointer to the cell population.
Definition at line 32 of file OxygenBasedCellKiller.cpp.
Member Function Documentation
template<unsigned SPACE_DIM> template<class Archive> void OxygenBasedCellKiller< SPACE_DIM >::serialize (Archive & archive, const unsigned int version) [inline, private]
Serialize the object and its member variables.
Parameters:
archive the archive
version the current version of this class
Reimplemented from AbstractCellKiller< SPACE_DIM >.
Definition at line 50 of file OxygenBasedCellKiller.hpp.
template<unsigned SPACE_DIM> void OxygenBasedCellKiller< SPACE_DIM >::TestAndLabelSingleCellForApoptosis (CellPtr pCell) [inline]
Starts apoptosis if the cell has has been hypoxic for longer than some critical period, and it is currently hypoxic, and a random number is less than some probability of death (which scales linearly with the local oxygen concentration).
Parameters:
pCell the cell to test for apoptosis.
Definition at line 38 of file OxygenBasedCellKiller.cpp.
Referenced by OxygenBasedCellKiller< SPACE_DIM >::TestAndLabelCellsForApoptosisOrDeath().
template<unsigned SPACE_DIM> void OxygenBasedCellKiller< SPACE_DIM >::TestAndLabelCellsForApoptosisOrDeath () [inline, virtual]
Loop over cells and start apoptosis if the cell has been undergone a prolonged period of hypoxia.
Implements AbstractCellKiller< SPACE_DIM >.
Definition at line 47 of file OxygenBasedCellKiller.cpp.
References AbstractCellPopulation< DIM >::Begin(), AbstractCellPopulation< DIM >::End(), AbstractCellKiller< SPACE_DIM >::mpCellPopulation, and OxygenBasedCellKiller< SPACE_DIM >::TestAndLabelSingleCellForApoptosis().
template<unsigned DIM> void OxygenBasedCellKiller< DIM >::OutputCellKillerParameters (out_stream & rParamsFile) [inline, virtual]
Outputs cell killer parameters to file
As this method is pure virtual, it must be overridden in subclasses.
Parameters:
rParamsFile the file stream to which the parameters are output
Implements AbstractCellKiller< SPACE_DIM >.
Definition at line 58 of file OxygenBasedCellKiller.cpp.
References AbstractCellKiller< SPACE_DIM >::OutputCellKillerParameters().
Friends And Related Function Documentation
template<unsigned SPACE_DIM> friend class boost::serialization::access [friend]
Needed for serialization.
Reimplemented from AbstractCellKiller< SPACE_DIM >.
Definition at line 48 of file OxygenBasedCellKiller.hpp.
The documentation for this class was generated from the following files:
cell_based/src/population/killers/OxygenBasedCellKiller.hpp
cell_based/src/population/killers/OxygenBasedCellKiller.cpp