Chaste: VertexCryptBoundaryForce< DIM > Class Template Reference
VertexCryptBoundaryForce< DIM > Class Template Reference
#include <VertexCryptBoundaryForce.hpp>
Public Member Functions
VertexCryptBoundaryForce (double forceStrength=1.0)
~VertexCryptBoundaryForce ()
void AddForceContribution (std::vector< c_vector< double, DIM > > &rForces, AbstractCellPopulation< DIM > &rCellPopulation)
double GetForceStrength () const
void OutputForceParameters (out_stream &rParamsFile)
Private Member Functions
template<class Archive>
void serialize (Archive &archive, const unsigned int version)
Private Attributes
double mForceStrength
Friends
class TestVertexCryptBoundaryForce
class boost::serialization::access
Detailed Description
template<unsigned DIM>
class VertexCryptBoundaryForce< DIM >
A boundary force class for use in vertex-based crypt simulations to prevent cells moving below the bottom of the crypt (y=0).
The boundary force is taken to be zero for y>0, and proportional to y^2 for y<0 (hence is continuously differentiable at y=0). The constant of proportionality is given by the parameter mForceStrength, whose value is set in the constructor.
Definition at line 49 of file VertexCryptBoundaryForce.hpp.
Constructor & Destructor Documentation
template<unsigned DIM> VertexCryptBoundaryForce< DIM >::VertexCryptBoundaryForce (double forceStrength = 1.0) [inline]
Constructor.
Parameters:
forceStrength the force strength
Definition at line 33 of file VertexCryptBoundaryForce.cpp.
References VertexCryptBoundaryForce< DIM >::mForceStrength.
template<unsigned DIM> VertexCryptBoundaryForce< DIM >::~VertexCryptBoundaryForce () [inline]
Destructor.
Definition at line 42 of file VertexCryptBoundaryForce.cpp.
Member Function Documentation
template<unsigned DIM> template<class Archive> void VertexCryptBoundaryForce< DIM >::serialize (Archive & archive, const unsigned int version) [inline, private]
Serialize the object and its member variables.
Serialization of singleton objects must be done with care. Before the object is serialized via a pointer, it *MUST* be serialized directly, or an assertion will trip when a second instance of the class is created on de-serialization.
Parameters:
archive the archive
version the current version of this class
Reimplemented from AbstractForce< DIM >.
Definition at line 60 of file VertexCryptBoundaryForce.hpp.
References VertexCryptBoundaryForce< DIM >::mForceStrength.
template<unsigned DIM> void VertexCryptBoundaryForce< DIM >::AddForceContribution (std::vector< c_vector< double, DIM > > & rForces, AbstractCellPopulation< DIM > & rCellPopulation) [inline, virtual]
Overridden AddForceContribution() method.
Calculates the boundary force on each node in the vertex-based cell population.
Parameters:
rForces reference to vector of forces on nodes
rCellPopulation reference to the cell population
Implements AbstractForce< DIM >.
Definition at line 47 of file VertexCryptBoundaryForce.cpp.
References AbstractMesh< ELEMENT_DIM, SPACE_DIM >::GetNodeIteratorBegin(), AbstractMesh< ELEMENT_DIM, SPACE_DIM >::GetNodeIteratorEnd(), VertexCryptBoundaryForce< DIM >::mForceStrength, and VertexBasedCellPopulation< DIM >::rGetMesh().
template<unsigned DIM> double VertexCryptBoundaryForce< DIM >::GetForceStrength () const [inline]
Returns:
mForceStrength
Definition at line 72 of file VertexCryptBoundaryForce.cpp.
References VertexCryptBoundaryForce< DIM >::mForceStrength.
template<unsigned DIM> void VertexCryptBoundaryForce< DIM >::OutputForceParameters (out_stream & rParamsFile) [inline, virtual]
Outputs force parameters to file
As this method is pure virtual, it must be overridden in subclasses.
Parameters:
rParamsFile the file stream to which the parameters are output
Implements AbstractForce< DIM >.
Definition at line 78 of file VertexCryptBoundaryForce.cpp.
References VertexCryptBoundaryForce< DIM >::mForceStrength, and AbstractForce< DIM >::OutputForceParameters().
Friends And Related Function Documentation
template<unsigned DIM> friend class boost::serialization::access [friend]
Needed for serialization.
Reimplemented from AbstractForce< DIM >.
Definition at line 58 of file VertexCryptBoundaryForce.hpp.
Member Data Documentation
template<unsigned DIM> double VertexCryptBoundaryForce< DIM >::mForceStrength [private]
Parameter determining the strength of the force acting on nodes below y=0.
Definition at line 56 of file VertexCryptBoundaryForce.hpp.
Referenced by VertexCryptBoundaryForce< DIM >::AddForceContribution(), VertexCryptBoundaryForce< DIM >::GetForceStrength(), VertexCryptBoundaryForce< DIM >::OutputForceParameters(), VertexCryptBoundaryForce< DIM >::serialize(), and VertexCryptBoundaryForce< DIM >::VertexCryptBoundaryForce().
The documentation for this class was generated from the following files:
crypt/src/mechanics/VertexCryptBoundaryForce.hpp
crypt/src/mechanics/VertexCryptBoundaryForce.cpp