Chaste: BasicMonodomainSolver< ELEMENT_DIM, SPACE_DIM > Class Template Reference
BasicMonodomainSolver< ELEMENT_DIM, SPACE_DIM > Class Template Reference
#include <BasicMonodomainSolver.hpp>
Public Member Functions
BasicMonodomainSolver (AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM > *pMesh, MonodomainTissue< ELEMENT_DIM, SPACE_DIM > *pTissue, BoundaryConditionsContainer< ELEMENT_DIM, SPACE_DIM, 1 > *pBoundaryConditions, unsigned numQuadPoints=2)
virtual ~BasicMonodomainSolver ()
Protected Member Functions
void SetupLinearSystem (Vec currentSolution, bool computeMatrix)
Detailed Description
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM>
class BasicMonodomainSolver< ELEMENT_DIM, SPACE_DIM >
A simple Monodomain solver, which uses assembly to set up the right-hand-side (RHS) vector of the linear system to be solved. Much slower than MatrixBasedMonodomainSolver, which computes the RHS with a matrix-vector product.
Definition at line 43 of file BasicMonodomainSolver.hpp.
Constructor & Destructor Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> BasicMonodomainSolver< ELEMENT_DIM, SPACE_DIM >::BasicMonodomainSolver (AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM > * pMesh, MonodomainTissue< ELEMENT_DIM, SPACE_DIM > * pTissue, BoundaryConditionsContainer< ELEMENT_DIM, SPACE_DIM, 1 > * pBoundaryConditions, unsigned numQuadPoints = 2) [inline]
Constructor
Parameters:
pMesh pointer to the mesh
pTissue pointer to the tissue
pBoundaryConditions pointer to the boundary conditions
numQuadPoints number of quadrature points (defaults to 2)
Definition at line 70 of file BasicMonodomainSolver.cpp.
References AbstractCardiacTissue< ELEMENT_DIM, SPACE_DIM >::SetCacheReplication().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> virtual BasicMonodomainSolver< ELEMENT_DIM, SPACE_DIM >::~BasicMonodomainSolver () [inline, virtual]
Destructor
Definition at line 77 of file BasicMonodomainSolver.hpp.
Member Function Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void BasicMonodomainSolver< ELEMENT_DIM, SPACE_DIM >::SetupLinearSystem (Vec currentSolution, bool computeMatrix) [inline, protected, virtual]
Implemented SetupLinearSystem() method, which uses the MonodomainAssembler to assemble the LHS matrix if required, and uses the MonodomainAssembler to *assemble* the RHS vector. Much slower than doing matrix-based RHS setup, which is done in MatrixBasedMonodomainSolver
Parameters:
currentSolution Solution at current time
computeMatrix Whether to compute the matrix of the linear system
Implements AbstractLinearPdeSolver< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >.
Definition at line 34 of file BasicMonodomainSolver.cpp.
References LinearSystem::AssembleFinalLhsMatrix(), LinearSystem::AssembleRhsVector(), AbstractDynamicLinearPdeSolver< ELEMENT_DIM, SPACE_DIM, 1 >::mDt, AbstractMonodomainSolver< ELEMENT_DIM, SPACE_DIM >::mNumQuadPoints, AbstractMonodomainSolver< ELEMENT_DIM, SPACE_DIM >::mpBoundaryConditions, AbstractLinearPdeSolver< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::mpLinearSystem, AbstractLinearPdeSolver< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::mpMesh, AbstractMonodomainSolver< ELEMENT_DIM, SPACE_DIM >::mpMonodomainAssembler, AbstractMonodomainSolver< ELEMENT_DIM, SPACE_DIM >::mpMonodomainTissue, LinearSystem::rGetLhsMatrix(), and LinearSystem::rGetRhsVector().
The documentation for this class was generated from the following files:
heart/src/solver/electrics/BasicMonodomainSolver.hpp
heart/src/solver/electrics/BasicMonodomainSolver.cpp