Chaste: DiffusionMultipleCaUpdateRule< DIM > Class Template Reference
DiffusionMultipleCaUpdateRule< DIM > Class Template Reference
#include <DiffusionMultipleCaUpdateRule.hpp>
Public Member Functions
DiffusionMultipleCaUpdateRule ()
~DiffusionMultipleCaUpdateRule ()
double EvaluateProbability (unsigned currentNodeIndex, unsigned targetNodeIndex, MultipleCaBasedCellPopulation< DIM > &rCellPopulation, double dt, double deltaX)
double GetDiffusionParameter ()
void SetDiffusionParameter (double diffusionParameter)
void OutputUpdateRuleParameters (out_stream &rParamsFile)
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Private Attributes
double mDiffusionParameter
double mDt
Friends
class TestMultipleCaUpdateRules
class boost::serialization::access
Detailed Description
template<unsigned DIM>
class DiffusionMultipleCaUpdateRule< DIM >
A diffusion update rule for use in cell-based simulations using the cellular MultipleCa model.
The probability of moving to an adjacent lattice site is
D*delta_t/(2*delta_x*delta_x)
Where D is the mDiffusionParameter. delta_t is the timestep. delta_x is the separation of the two lattice sites.
Definition at line 63 of file DiffusionMultipleCaUpdateRule.hpp.
Constructor & Destructor Documentation
template<unsigned DIM> DiffusionMultipleCaUpdateRule< DIM >::DiffusionMultipleCaUpdateRule ()
Constructor.
Definition at line 39 of file DiffusionMultipleCaUpdateRule.cpp.
template<unsigned DIM> DiffusionMultipleCaUpdateRule< DIM >::~DiffusionMultipleCaUpdateRule ()
Destructor.
Definition at line 46 of file DiffusionMultipleCaUpdateRule.cpp.
Member Function Documentation
template<unsigned DIM> double DiffusionMultipleCaUpdateRule< DIM >::EvaluateProbability (unsigned currentNodeIndex, unsigned targetNodeIndex, MultipleCaBasedCellPopulation< DIM > & rCellPopulation, double dt, double deltaX) [virtual]
Calculate the probability of a given move.
Uses random diffusion to each neighbouring node, scaled according to distance.
Parameters:
currentNodeIndex The index of the current node/lattice site
targetNodeIndex The index of the target node/lattice site
rCellPopulation The cell population
dt is the time interval
deltaX defines the size of the lattice site
Returns:
The probability of the cell moving from the current node to the target node
Implements AbstractMultipleCaUpdateRule< DIM >.
Definition at line 51 of file DiffusionMultipleCaUpdateRule.cpp.
References MultipleCaBasedCellPopulation< DIM >::GetNode(), and MultipleCaBasedCellPopulation< DIM >::rGetMesh().
template<unsigned DIM> double DiffusionMultipleCaUpdateRule< DIM >::GetDiffusionParameter ()
Returns:
mDiffusionParameter
Definition at line 64 of file DiffusionMultipleCaUpdateRule.cpp.
template<unsigned DIM> void DiffusionMultipleCaUpdateRule< DIM >::OutputUpdateRuleParameters (out_stream & rParamsFile) [virtual]
Todo:
#2066 return the time step (mDt) defined in the calculation of the probability of a cell moving to a certain site
Todo:
#2066 define the time step (dt) defined in the calculation of the probability of a cell moving to a certain site
Overridden OutputUpdateRuleParameters() method.
Parameters:
rParamsFile the file stream to which the parameters are output
Implements AbstractMultipleCaUpdateRule< DIM >.
Definition at line 88 of file DiffusionMultipleCaUpdateRule.cpp.
References AbstractMultipleCaUpdateRule< DIM >::OutputUpdateRuleParameters().
template<unsigned DIM> template<class Archive > void DiffusionMultipleCaUpdateRule< DIM >::serialize (Archive & archive, const unsigned int version) [inline, private]
Serialize the object.
Parameters:
archive the archive
version the current version of this class
Reimplemented from AbstractMultipleCaUpdateRule< DIM >.
Definition at line 84 of file DiffusionMultipleCaUpdateRule.hpp.
References DiffusionMultipleCaUpdateRule< DIM >::mDiffusionParameter.
template<unsigned DIM> void DiffusionMultipleCaUpdateRule< DIM >::SetDiffusionParameter (double diffusionParameter)
Set mDiffusionParameter.
Parameters:
diffusionParameter the new value of mDiffusionParameter
Definition at line 70 of file DiffusionMultipleCaUpdateRule.cpp.
Friends And Related Function Documentation
template<unsigned DIM> friend class boost::serialization::access [friend]
Needed for serialization.
Reimplemented from AbstractMultipleCaUpdateRule< DIM >.
Definition at line 82 of file DiffusionMultipleCaUpdateRule.hpp.
Member Data Documentation
template<unsigned DIM> double DiffusionMultipleCaUpdateRule< DIM >::mDiffusionParameter [private]
Diffusion parameter for update rule. Set to the default value 0.5 in the constructor.
Todo:
provide units
Definition at line 74 of file DiffusionMultipleCaUpdateRule.hpp.
Referenced by DiffusionMultipleCaUpdateRule< DIM >::serialize().
template<unsigned DIM> double DiffusionMultipleCaUpdateRule< DIM >::mDt [private]
The timestep (units?) for this probability
Todo:
#2066
Definition at line 80 of file DiffusionMultipleCaUpdateRule.hpp.
The documentation for this class was generated from the following files:
cell_based/src/population/update_rules/DiffusionMultipleCaUpdateRule.hpp
cell_based/src/population/update_rules/DiffusionMultipleCaUpdateRule.cpp