Chaste: DeltaNotchOffLatticeSimulation< DIM > Class Template Reference
DeltaNotchOffLatticeSimulation< DIM > Class Template Reference
#include <DeltaNotchOffLatticeSimulation.hpp>
Public Member Functions
DeltaNotchOffLatticeSimulation (AbstractCellPopulation< DIM > &rCellPopulation, bool deleteCellPopulationInDestructor=false, bool initialiseCells=true)
~DeltaNotchOffLatticeSimulation ()
Public Attributes
out_stream mVizDeltaFile
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
void SetupSolve ()
void UpdateAtEndOfTimeStep ()
void UpdateCellData ()
Friends
class boost::serialization::access
Detailed Description
template<unsigned DIM>
class DeltaNotchOffLatticeSimulation< DIM >
Subclass of OffLatticeSimulation in which the mean levels of Delta in neighbouring cells are computed and stored in CellData for use in DeltaNotchOdeSystem in a centre-based cell population.
Definition at line 50 of file DeltaNotchOffLatticeSimulation.hpp.
Constructor & Destructor Documentation
template<unsigned DIM> DeltaNotchOffLatticeSimulation< DIM >::DeltaNotchOffLatticeSimulation (AbstractCellPopulation< DIM > & rCellPopulation, bool deleteCellPopulationInDestructor = false, bool initialiseCells = true)
Default constructor.
Parameters:
rCellPopulation A cell population facade class (contains a mesh and cells)
deleteCellPopulationInDestructor Whether to delete the cell population on destruction to free up memory (defaults to false)
initialiseCells whether to initialise cells (defaults to true, set to false when loading from an archive)
Definition at line 43 of file DeltaNotchOffLatticeSimulation.cpp.
template<unsigned DIM> DeltaNotchOffLatticeSimulation< DIM >::~DeltaNotchOffLatticeSimulation ()
Destructor.
Definition at line 51 of file DeltaNotchOffLatticeSimulation.cpp.
Member Function Documentation
template<unsigned DIM> template<class Archive > void DeltaNotchOffLatticeSimulation< DIM >::serialize (Archive & archive, const unsigned int version) [inline, private]
Archive the object and its member variables.
Parameters:
archive the archive
version the current version of this class
Reimplemented from OffLatticeSimulation< DIM >.
Definition at line 63 of file DeltaNotchOffLatticeSimulation.hpp.
template<unsigned DIM> void DeltaNotchOffLatticeSimulation< DIM >::SetupSolve () [private, virtual]
Overridden SetupSolve() method. Calls UpdateCellData().
Reimplemented from OffLatticeSimulation< DIM >.
Definition at line 56 of file DeltaNotchOffLatticeSimulation.cpp.
References OffLatticeSimulation< ELEMENT_DIM, SPACE_DIM >::SetupSolve().
template<unsigned DIM> void DeltaNotchOffLatticeSimulation< DIM >::UpdateAtEndOfTimeStep () [private, virtual]
Overridden UpdateAtEndOfTimeStep() method.
Reimplemented from AbstractCellBasedSimulation< ELEMENT_DIM, ELEMENT_DIM >.
Definition at line 63 of file DeltaNotchOffLatticeSimulation.cpp.
References AbstractCellBasedSimulation< ELEMENT_DIM, SPACE_DIM >::UpdateAtEndOfTimeStep().
template<unsigned DIM> void DeltaNotchOffLatticeSimulation< DIM >::UpdateCellData () [private]
Compute the volume of each cell in the population and store these in CellData.
Definition at line 70 of file DeltaNotchOffLatticeSimulation.cpp.
References AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::Begin(), DeltaNotchCellCycleModel::GetDelta(), VertexMesh< ELEMENT_DIM, SPACE_DIM >::GetNeighbouringElementIndices(), DeltaNotchCellCycleModel::GetNotch(), NEVER_REACHED, and VertexBasedCellPopulation< DIM >::rGetMesh().
Friends And Related Function Documentation
template<unsigned DIM> friend class boost::serialization::access [friend]
Needed for serialization.
Reimplemented from OffLatticeSimulation< DIM >.
Definition at line 55 of file DeltaNotchOffLatticeSimulation.hpp.
Member Data Documentation
template<unsigned DIM> out_stream DeltaNotchOffLatticeSimulation< DIM >::mVizDeltaFile
The file that the values of beta catenin is written out to.
Definition at line 86 of file DeltaNotchOffLatticeSimulation.hpp.
The documentation for this class was generated from the following files:
cell_based/src/simulation/DeltaNotchOffLatticeSimulation.hpp
cell_based/src/simulation/DeltaNotchOffLatticeSimulation.cpp