Chaste: MeshBasedCellPopulation< ELEMENT_DIM, SPACE_DIM >::SpringIterator Class Reference
MeshBasedCellPopulation< ELEMENT_DIM, SPACE_DIM >::SpringIterator Class Reference
#include <MeshBasedCellPopulation.hpp>
Public Member Functions
Node< SPACE_DIM > * GetNodeA ()
Node< SPACE_DIM > * GetNodeB ()
CellPtr GetCellA ()
CellPtr GetCellB ()
bool operator!= (const MeshBasedCellPopulation< ELEMENT_DIM, SPACE_DIM >::SpringIterator &rOther)
SpringIterator & operator++ ()
SpringIterator (MeshBasedCellPopulation< ELEMENT_DIM, SPACE_DIM > &rCellPopulation, typename MutableMesh< ELEMENT_DIM, SPACE_DIM >::EdgeIterator edgeIter)
Private Attributes
std::set< std::set< unsigned > > mSpringsVisited
MeshBasedCellPopulation
< ELEMENT_DIM, SPACE_DIM > & mrCellPopulation
MutableMesh< ELEMENT_DIM,
SPACE_DIM >::EdgeIterator mEdgeIter
Detailed Description
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM = ELEMENT_DIM>
class MeshBasedCellPopulation< ELEMENT_DIM, SPACE_DIM >::SpringIterator
Iterator over edges in the mesh, which correspond to springs between cells.
This class takes care of the logic to make sure that you consider each edge exactly once.
Definition at line 440 of file MeshBasedCellPopulation.hpp.
Constructor & Destructor Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> MeshBasedCellPopulation< ELEMENT_DIM, SPACE_DIM >::SpringIterator::SpringIterator (MeshBasedCellPopulation< ELEMENT_DIM, SPACE_DIM > & rCellPopulation, typename MutableMesh< ELEMENT_DIM, SPACE_DIM >::EdgeIterator edgeIter)
Constructor for a new iterator.
Parameters:
rCellPopulation the cell population
edgeIter iterator over edges in the mesh
Definition at line 914 of file MeshBasedCellPopulation.cpp.
References TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::EdgesEnd(), MeshBasedCellPopulation< ELEMENT_DIM, SPACE_DIM >::SpringIterator::mEdgeIter, and MeshBasedCellPopulation< ELEMENT_DIM, SPACE_DIM >::SpringIterator::mrCellPopulation.
Member Function Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> CellPtr MeshBasedCellPopulation< ELEMENT_DIM, SPACE_DIM >::SpringIterator::GetCellA ()
Get the cell at end A of the spring.
Definition at line 873 of file MeshBasedCellPopulation.cpp.
References AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::GetCellUsingLocationIndex().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> CellPtr MeshBasedCellPopulation< ELEMENT_DIM, SPACE_DIM >::SpringIterator::GetCellB ()
Get the cell at end B of the spring.
Definition at line 880 of file MeshBasedCellPopulation.cpp.
References AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::GetCellUsingLocationIndex().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> Node< SPACE_DIM > * MeshBasedCellPopulation< ELEMENT_DIM, SPACE_DIM >::SpringIterator::GetNodeA ()
Get a pointer to the node in the mesh at end A of the spring.
Definition at line 861 of file MeshBasedCellPopulation.cpp.
References MeshBasedCellPopulation< ELEMENT_DIM, SPACE_DIM >::SpringIterator::mEdgeIter.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> Node< SPACE_DIM > * MeshBasedCellPopulation< ELEMENT_DIM, SPACE_DIM >::SpringIterator::GetNodeB ()
Get a pointer to the node in the mesh at end B of the spring.
Definition at line 867 of file MeshBasedCellPopulation.cpp.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> bool MeshBasedCellPopulation< ELEMENT_DIM, SPACE_DIM >::SpringIterator::operator!= (const MeshBasedCellPopulation< ELEMENT_DIM, SPACE_DIM >::SpringIterator & rOther)
Comparison not-equal-to.
Parameters:
rOther SpringIterator with which comparison is made
Definition at line 887 of file MeshBasedCellPopulation.cpp.
References MeshBasedCellPopulation< ELEMENT_DIM, SPACE_DIM >::SpringIterator::mEdgeIter.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> MeshBasedCellPopulation< ELEMENT_DIM, SPACE_DIM >::SpringIterator & MeshBasedCellPopulation< ELEMENT_DIM, SPACE_DIM >::SpringIterator::operator++ ()
Prefix increment operator.
Definition at line 893 of file MeshBasedCellPopulation.cpp.
References AbstractCentreBasedCellPopulation< ELEMENT_DIM, SPACE_DIM >::IsGhostNode().
Member Data Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM = ELEMENT_DIM> MutableMesh<ELEMENT_DIM, SPACE_DIM>::EdgeIterator MeshBasedCellPopulation< ELEMENT_DIM, SPACE_DIM >::SpringIterator::mEdgeIter [private]
The edge iterator member.
Definition at line 493 of file MeshBasedCellPopulation.hpp.
Referenced by MeshBasedCellPopulation< ELEMENT_DIM, SPACE_DIM >::SpringIterator::GetNodeA(), MeshBasedCellPopulation< ELEMENT_DIM, SPACE_DIM >::SpringIterator::operator!=(), and MeshBasedCellPopulation< ELEMENT_DIM, SPACE_DIM >::SpringIterator::SpringIterator().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM = ELEMENT_DIM> MeshBasedCellPopulation<ELEMENT_DIM, SPACE_DIM>& MeshBasedCellPopulation< ELEMENT_DIM, SPACE_DIM >::SpringIterator::mrCellPopulation [private]
The cell population member.
Definition at line 490 of file MeshBasedCellPopulation.hpp.
Referenced by MeshBasedCellPopulation< ELEMENT_DIM, SPACE_DIM >::SpringIterator::SpringIterator().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM = ELEMENT_DIM> std::set<std::set<unsigned> > MeshBasedCellPopulation< ELEMENT_DIM, SPACE_DIM >::SpringIterator::mSpringsVisited [private]
Keep track of what edges have been visited.
Definition at line 487 of file MeshBasedCellPopulation.hpp.
The documentation for this class was generated from the following files:
cell_based/src/population/MeshBasedCellPopulation.hpp
cell_based/src/population/MeshBasedCellPopulation.cpp