Chaste: AbstractForce< ELEMENT_DIM, SPACE_DIM > Class Template Reference
AbstractForce< ELEMENT_DIM, SPACE_DIM > Class Template Reference
#include <AbstractForce.hpp>
Public Member Functions
AbstractForce ()
virtual ~AbstractForce ()
virtual void AddForceContribution (std::vector< c_vector< double, SPACE_DIM > > &rForces, AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM > &rCellPopulation)=0
void OutputForceInfo (out_stream &rParamsFile)
virtual void OutputForceParameters (out_stream &rParamsFile)=0
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Friends
class boost::serialization::access
Detailed Description
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM = ELEMENT_DIM>
class AbstractForce< ELEMENT_DIM, SPACE_DIM >
An abstract force class, for use in cell-based simulations.
Definition at line 49 of file AbstractForce.hpp.
Constructor & Destructor Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> AbstractForce< ELEMENT_DIM, SPACE_DIM >::AbstractForce ()
Default constructor.
Definition at line 39 of file AbstractForce.cpp.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> AbstractForce< ELEMENT_DIM, SPACE_DIM >::~AbstractForce () [virtual]
Destructor.
Definition at line 44 of file AbstractForce.cpp.
Member Function Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM = ELEMENT_DIM> virtual void AbstractForce< ELEMENT_DIM, SPACE_DIM >::AddForceContribution (std::vector< c_vector< double, SPACE_DIM > > & rForces, AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM > & rCellPopulation) [pure virtual]
Calculates the force on each node.
This method must be overridden in concrete classes.
Parameters:
rForces reference to vector of forces on nodes
rCellPopulation reference to the cell population
Implemented in AbstractTwoBodyInteractionForce< ELEMENT_DIM, SPACE_DIM >, and AbstractTwoBodyInteractionForce< ELEMENT_DIM, ELEMENT_DIM >.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void AbstractForce< ELEMENT_DIM, SPACE_DIM >::OutputForceInfo (out_stream & rParamsFile)
Outputs force used in the simulation to file and then calls OutputForceParameters to output all relevant parameters.
Parameters:
rParamsFile the file stream to which the parameters are output
Definition at line 49 of file AbstractForce.cpp.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void AbstractForce< ELEMENT_DIM, SPACE_DIM >::OutputForceParameters (out_stream & rParamsFile) [pure virtual]
Outputs force parameters to file
As this method is pure virtual, it must be overridden in subclasses.
Parameters:
rParamsFile the file stream to which the parameters are output
Implemented in AbstractTwoBodyInteractionForce< ELEMENT_DIM, SPACE_DIM >, BuskeAdhesiveForce< DIM >, BuskeCompressionForce< DIM >, BuskeElasticForce< DIM >, ChemotacticForce< DIM >, DiffusionForce< DIM >, GeneralisedLinearSpringForce< ELEMENT_DIM, SPACE_DIM >, NagaiHondaDifferentialAdhesionForce< DIM >, NagaiHondaForce< DIM >, RepulsionForce< DIM >, WelikyOsterForce< DIM >, CryptProjectionForce, LinearSpringWithVariableSpringConstantsForce< DIM >, VertexCryptBoundaryForce< DIM >, AbstractTwoBodyInteractionForce< DIM >, AbstractTwoBodyInteractionForce< ELEMENT_DIM, ELEMENT_DIM >, GeneralisedLinearSpringForce< DIM >, and GeneralisedLinearSpringForce< 2 >.
Definition at line 59 of file AbstractForce.cpp.
Referenced by VertexCryptBoundaryForce< DIM >::OutputForceParameters(), WelikyOsterForce< DIM >::OutputForceParameters(), NagaiHondaForce< DIM >::OutputForceParameters(), DiffusionForce< DIM >::OutputForceParameters(), ChemotacticForce< DIM >::OutputForceParameters(), BuskeCompressionForce< DIM >::OutputForceParameters(), and AbstractTwoBodyInteractionForce< ELEMENT_DIM, SPACE_DIM >::OutputForceParameters().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM = ELEMENT_DIM> template<class Archive > void AbstractForce< ELEMENT_DIM, SPACE_DIM >::serialize (Archive & archive, const unsigned int version) [inline, private]
Serialize the object.
Parameters:
archive the archive
version the current version of this class
Reimplemented in AbstractTwoBodyInteractionForce< ELEMENT_DIM, SPACE_DIM >, BuskeAdhesiveForce< DIM >, BuskeCompressionForce< DIM >, BuskeElasticForce< DIM >, ChemotacticForce< DIM >, DiffusionForce< DIM >, GeneralisedLinearSpringForce< ELEMENT_DIM, SPACE_DIM >, NagaiHondaDifferentialAdhesionForce< DIM >, NagaiHondaForce< DIM >, RepulsionForce< DIM >, WelikyOsterForce< DIM >, CryptProjectionForce, LinearSpringWithVariableSpringConstantsForce< DIM >, VertexCryptBoundaryForce< DIM >, AbstractTwoBodyInteractionForce< DIM >, AbstractTwoBodyInteractionForce< ELEMENT_DIM, ELEMENT_DIM >, GeneralisedLinearSpringForce< DIM >, and GeneralisedLinearSpringForce< 2 >.
Definition at line 60 of file AbstractForce.hpp.
Friends And Related Function Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM = ELEMENT_DIM> friend class boost::serialization::access [friend]
Needed for serialization.
Reimplemented in AbstractTwoBodyInteractionForce< ELEMENT_DIM, SPACE_DIM >, BuskeAdhesiveForce< DIM >, BuskeCompressionForce< DIM >, BuskeElasticForce< DIM >, ChemotacticForce< DIM >, DiffusionForce< DIM >, GeneralisedLinearSpringForce< ELEMENT_DIM, SPACE_DIM >, NagaiHondaDifferentialAdhesionForce< DIM >, NagaiHondaForce< DIM >, RepulsionForce< DIM >, WelikyOsterForce< DIM >, CryptProjectionForce, LinearSpringWithVariableSpringConstantsForce< DIM >, VertexCryptBoundaryForce< DIM >, AbstractTwoBodyInteractionForce< DIM >, AbstractTwoBodyInteractionForce< ELEMENT_DIM, ELEMENT_DIM >, GeneralisedLinearSpringForce< DIM >, and GeneralisedLinearSpringForce< 2 >.
Definition at line 52 of file AbstractForce.hpp.
The documentation for this class was generated from the following files:
cell_based/src/population/mechanics/AbstractForce.hpp
cell_based/src/population/mechanics/AbstractForce.cpp