Chaste: ExtendedBidomainAssembler< ELEMENT_DIM, SPACE_DIM > Class Template Reference
ExtendedBidomainAssembler< ELEMENT_DIM, SPACE_DIM > Class Template Reference
#include <ExtendedBidomainAssembler.hpp>
Public Member Functions
ExtendedBidomainAssembler (AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM > *pMesh, ExtendedBidomainTissue< SPACE_DIM > *pTissue, unsigned numQuadPoints=2)
~ExtendedBidomainAssembler ()
Protected Member Functions
virtual c_matrix< double,
3 *(ELEMENT_DIM+1),
3 *(ELEMENT_DIM+1)> ComputeMatrixTerm (c_vector< double, ELEMENT_DIM+1 > &rPhi, c_matrix< double, SPACE_DIM, ELEMENT_DIM+1 > &rGradPhi, ChastePoint< SPACE_DIM > &rX, c_vector< double, 3 > &rU, c_matrix< double, 3, SPACE_DIM > &rGradU, Element< ELEMENT_DIM, SPACE_DIM > *pElement)
Protected Attributes
ExtendedBidomainTissue
< SPACE_DIM > * mpExtendedBidomainTissue
HeartConfig * mpConfig
Detailed Description
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM>
class ExtendedBidomainAssembler< ELEMENT_DIM, SPACE_DIM >
This is a derived class of AbstractCardiacFeVolumeIntegralAssembler and takes care of assembling LHS for solution of the extended bidomain euqations
See Buist ML, Poh YC. An Extended Bidomain Framework Incorporating Multiple Cell Types. Biophysical Journal, Volume 99, Issue 1, 13-18, 7 July 2010.
Major differences with bidomain assembler:
there are two cells (instead of one)
extracellular stimulus is present
Definition at line 71 of file ExtendedBidomainAssembler.hpp.
Constructor & Destructor Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> ExtendedBidomainAssembler< ELEMENT_DIM, SPACE_DIM >::ExtendedBidomainAssembler (AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM > * pMesh, ExtendedBidomainTissue< SPACE_DIM > * pTissue, unsigned numQuadPoints = 2)
Constructor stores the mesh and pde and sets up boundary conditions.
Parameters:
pMesh pointer to the mesh
pTissue pointer to the tissue
numQuadPoints number of quadrature points (defaults to 2)
Definition at line 134 of file ExtendedBidomainAssembler.cpp.
References HeartConfig::Instance(), and ExtendedBidomainAssembler< ELEMENT_DIM, SPACE_DIM >::mpConfig.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> ExtendedBidomainAssembler< ELEMENT_DIM, SPACE_DIM >::~ExtendedBidomainAssembler ()
Destructor.
Definition at line 146 of file ExtendedBidomainAssembler.cpp.
Member Function Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> c_matrix< double, 3 *(ELEMENT_DIM+1), 3 *(ELEMENT_DIM+1)> ExtendedBidomainAssembler< ELEMENT_DIM, SPACE_DIM >::ComputeMatrixTerm (c_vector< double, ELEMENT_DIM+1 > & rPhi, c_matrix< double, SPACE_DIM, ELEMENT_DIM+1 > & rGradPhi, ChastePoint< SPACE_DIM > & rX, c_vector< double, 3 > & rU, c_matrix< double, 3, SPACE_DIM > & rGradU, Element< ELEMENT_DIM, SPACE_DIM > * pElement) [protected, virtual]
ComputeMatrixTerm()
This method is called by AssembleOnElement() and tells the assembler the contribution to add to the element stiffness matrix.
Parameters:
rPhi The basis functions, rPhi(i) = phi_i, i=1..numBases
rGradPhi Basis gradients, rGradPhi(i,j) = d(phi_j)/d(X_i)
rX The point in space
rU The unknown as a vector, u(i) = u_i
rGradU The gradient of the unknown as a matrix, rGradU(i,j) = d(u_i)/d(X_j)
pElement Pointer to the element
Definition at line 46 of file ExtendedBidomainAssembler.cpp.
References AbstractElement< ELEMENT_DIM, SPACE_DIM >::GetIndex(), and PdeSimulationTime::GetPdeTimeStep().
Member Data Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> HeartConfig* ExtendedBidomainAssembler< ELEMENT_DIM, SPACE_DIM >::mpConfig [protected]
Local cache of the configuration singleton instance
Definition at line 81 of file ExtendedBidomainAssembler.hpp.
Referenced by ExtendedBidomainAssembler< ELEMENT_DIM, SPACE_DIM >::ExtendedBidomainAssembler().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> ExtendedBidomainTissue<SPACE_DIM>* ExtendedBidomainAssembler< ELEMENT_DIM, SPACE_DIM >::mpExtendedBidomainTissue [protected]
The tissue for which we assemble the matrix
Definition at line 78 of file ExtendedBidomainAssembler.hpp.
The documentation for this class was generated from the following files:
heart/src/solver/electrics/extended_bidomain/ExtendedBidomainAssembler.hpp
heart/src/solver/electrics/extended_bidomain/ExtendedBidomainAssembler.cpp