Chaste: Hdf5ToVtkConverter< ELEMENT_DIM, SPACE_DIM > Class Template Reference
Hdf5ToVtkConverter< ELEMENT_DIM, SPACE_DIM > Class Template Reference
#include <Hdf5ToVtkConverter.hpp>
Inherits AbstractHdf5Converter< ELEMENT_DIM, SPACE_DIM >.
Public Member Functions
Hdf5ToVtkConverter (const FileFinder &rInputDirectory, const std::string &rFileBaseName, AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM > *pMesh, bool parallelVtk, bool usingOriginalNodeOrdering)
Detailed Description
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM>
class Hdf5ToVtkConverter< ELEMENT_DIM, SPACE_DIM >
This class converts from Hdf5 format to Vtk format. The output will be one .vtu file with separate vtkPointData for each time step.
Definition at line 46 of file Hdf5ToVtkConverter.hpp.
Constructor & Destructor Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> Hdf5ToVtkConverter< ELEMENT_DIM, SPACE_DIM >::Hdf5ToVtkConverter (const FileFinder & rInputDirectory, const std::string & rFileBaseName, AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM > * pMesh, bool parallelVtk, bool usingOriginalNodeOrdering) [inline]
Constructor, which does the conversion and writes the .vtu file.
Note:
This method is collective, and hence must be called by all processes.
Parameters:
rInputDirectory The input directory, relative to CHASTE_TEST_OUTPUT, where the .h5 file has been written
rFileBaseName The base name of the data file.
pMesh Pointer to the mesh.
parallelVtk When true, write with .pvtu and fragment meshes (only works for DistributedTetrahedralMesh)
usingOriginalNodeOrdering Whether HDF5 output was written using the original node ordering
Todo:
What if the mesh has been scaled, translated or rotated?
Definition at line 49 of file Hdf5ToVtkConverter.cpp.
References VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::AddPointData(), RelativeTo::ChasteTestOutput, DistributedVectorFactory::CreateVec(), PetscTools::Destroy(), AbstractMesh< ELEMENT_DIM, SPACE_DIM >::GetDistributedVectorFactory(), DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::GetNumLocalNodes(), AbstractMesh< ELEMENT_DIM, SPACE_DIM >::GetNumNodes(), FileFinder::GetRelativePath(), AbstractHdf5Converter< ELEMENT_DIM, SPACE_DIM >::mNumVariables, AbstractHdf5Converter< ELEMENT_DIM, SPACE_DIM >::MoveOntoNextDataset(), AbstractHdf5Converter< ELEMENT_DIM, SPACE_DIM >::mpMesh, AbstractHdf5Converter< ELEMENT_DIM, SPACE_DIM >::mpReader, AbstractHdf5Converter< ELEMENT_DIM, SPACE_DIM >::mRelativeSubdirectory, VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::SetParallelFiles(), VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::WriteFilesUsingMesh(), and AbstractMeshWriter< ELEMENT_DIM, SPACE_DIM >::WriteFilesUsingMeshReader().
The documentation for this class was generated from the following files:
pde/src/postprocessing/Hdf5ToVtkConverter.hpp
pde/src/postprocessing/Hdf5ToVtkConverter.cpp