Chaste: RandomCellKiller< DIM > Class Template Reference
RandomCellKiller< DIM > Class Template Reference
#include <RandomCellKiller.hpp>
Inherits AbstractCellKiller< DIM >.
Public Member Functions
RandomCellKiller (AbstractCellPopulation< DIM > *pCellPopulation, double probabilityOfDeathInAnHour)
double GetDeathProbabilityInAnHour () const
void CheckAndLabelSingleCellForApoptosis (CellPtr pCell)
void CheckAndLabelCellsForApoptosisOrDeath ()
void OutputCellKillerParameters (out_stream &rParamsFile)
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Private Attributes
double mProbabilityOfDeathInAnHour
Friends
class boost::serialization::access
Detailed Description
template<unsigned DIM>
class RandomCellKiller< DIM >
A cell killer that randomly kills cells based on the user set probability.
The probability passed into the constructor will be the probability of any cell dying whenever CheckAndLabelCellsForApoptosis() is called.
Note this does take into account time steps - the input probability is the probability that in an hour's worth of trying, the cell killer will have successfully killed a given cell. In the method CheckAndLabelSingleCellForApoptosis() this probability is used to calculate the probability that the cell is killed at a given time step.
We assume a constant time step and that there are an integer number (n = 1/dt) of time steps per hour. We also assume that this method is called every time step and that the probabilities of dying at different times are independent.
Definition at line 63 of file RandomCellKiller.hpp.
Constructor & Destructor Documentation
template<unsigned DIM> RandomCellKiller< DIM >::RandomCellKiller (AbstractCellPopulation< DIM > * pCellPopulation, double probabilityOfDeathInAnHour) [inline]
Default constructor.
Parameters:
pCellPopulation pointer to the cell population
probabilityOfDeathInAnHour probability that a cell is labelled for apoptosis in one hour's worth of trying
Definition at line 39 of file RandomCellKiller.cpp.
References EXCEPTION, and RandomCellKiller< DIM >::mProbabilityOfDeathInAnHour.
Member Function Documentation
template<unsigned DIM> void RandomCellKiller< DIM >::CheckAndLabelCellsForApoptosisOrDeath () [inline, virtual]
Loop over cells and start apoptosis randomly, based on the user-set probability.
Implements AbstractCellKiller< DIM >.
Definition at line 81 of file RandomCellKiller.cpp.
References AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::Begin(), RandomCellKiller< DIM >::CheckAndLabelSingleCellForApoptosis(), AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::End(), and AbstractCellKiller< DIM >::mpCellPopulation.
template<unsigned DIM> void RandomCellKiller< DIM >::CheckAndLabelSingleCellForApoptosis (CellPtr pCell) [inline]
Overridden method to test a given cell for apoptosis.
Parameters:
pCell the cell to test for apoptosis
Definition at line 56 of file RandomCellKiller.cpp.
References RandomNumberGenerator::Instance(), SimulationTime::Instance(), RandomCellKiller< DIM >::mProbabilityOfDeathInAnHour, and RandomNumberGenerator::ranf().
Referenced by RandomCellKiller< DIM >::CheckAndLabelCellsForApoptosisOrDeath().
template<unsigned DIM> double RandomCellKiller< DIM >::GetDeathProbabilityInAnHour () const [inline]
Returns:
mProbabilityOfDeathInAnHour.
Definition at line 50 of file RandomCellKiller.cpp.
References RandomCellKiller< DIM >::mProbabilityOfDeathInAnHour.
template<unsigned DIM> void RandomCellKiller< DIM >::OutputCellKillerParameters (out_stream & rParamsFile) [inline, virtual]
Overridden OutputCellKillerParameters() method.
Parameters:
rParamsFile the file stream to which the parameters are output
Implements AbstractCellKiller< DIM >.
Definition at line 92 of file RandomCellKiller.cpp.
References RandomCellKiller< DIM >::mProbabilityOfDeathInAnHour.
template<unsigned DIM> template<class Archive > void RandomCellKiller< DIM >::serialize (Archive & archive, const unsigned int version) [inline, private]
Archive the object.
Parameters:
archive the archive
version the current version of this class
Reimplemented from AbstractCellKiller< DIM >.
Definition at line 82 of file RandomCellKiller.hpp.
References SerializableSingleton< SINGLETON_CLASS >::GetSerializationWrapper(), and RandomNumberGenerator::Instance().
Friends And Related Function Documentation
template<unsigned DIM> friend class boost::serialization::access [friend]
Needed for serialization.
Reimplemented from AbstractCellKiller< DIM >.
Definition at line 74 of file RandomCellKiller.hpp.
Member Data Documentation
template<unsigned DIM> double RandomCellKiller< DIM >::mProbabilityOfDeathInAnHour [private]
Probability that in an hour's worth of trying, the cell killer will have successfully killed a given cell.
Definition at line 71 of file RandomCellKiller.hpp.
Referenced by RandomCellKiller< DIM >::CheckAndLabelSingleCellForApoptosis(), RandomCellKiller< DIM >::GetDeathProbabilityInAnHour(), RandomCellKiller< DIM >::OutputCellKillerParameters(), and RandomCellKiller< DIM >::RandomCellKiller().
The documentation for this class was generated from the following files:
cell_based/src/population/killers/RandomCellKiller.hpp
cell_based/src/population/killers/RandomCellKiller.cpp