Chaste: VertexMeshWriter< ELEMENT_DIM, SPACE_DIM > Class Template Reference
VertexMeshWriter< ELEMENT_DIM, SPACE_DIM > Class Template Reference
#include <VertexMeshWriter.hpp>
Inherits AbstractMeshWriter< ELEMENT_DIM, SPACE_DIM >.
Public Member Functions
VertexMeshWriter (const std::string &rDirectory, const std::string &rBaseName, const bool clearOutputDir=true)
~VertexMeshWriter ()
void WriteFilesUsingMesh (VertexMesh< ELEMENT_DIM, SPACE_DIM > &rMesh)
void WriteVtkUsingMesh (VertexMesh< ELEMENT_DIM, SPACE_DIM > &rMesh, std::string stamp="")
void MakeVtkMesh (VertexMesh< ELEMENT_DIM, SPACE_DIM > &rMesh)
void AddCellData (std::string dataName, std::vector< double > dataPayload)
void AddPointData (std::string dataName, std::vector< double > dataPayload)
std::vector< double > GetNextNode ()
ElementData GetNextElement ()
VertexElementData GetNextElementWithFaces ()
void WriteFiles ()
template<>
void WriteVtkUsingMesh (VertexMesh< 2, 2 > &rMesh, std::string stamp)
Private Attributes
VertexMesh< ELEMENT_DIM,
SPACE_DIM > * mpMesh
MeshWriterIterators
< ELEMENT_DIM, SPACE_DIM > * mpIters
NodeMap * mpNodeMap
unsigned mNodeMapCurrentIndex
vtkUnstructuredGrid * mpVtkUnstructedMesh
Detailed Description
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM>
class VertexMeshWriter< ELEMENT_DIM, SPACE_DIM >
A mesh writer class for vertex-based meshes.
Definition at line 71 of file VertexMeshWriter.hpp.
Constructor & Destructor Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> VertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::VertexMeshWriter (const std::string & rDirectory, const std::string & rBaseName, const bool clearOutputDir = true) [inline]
Constructor.
Parameters:
rDirectory reference to the output directory, relative to where Chaste output is stored
rBaseName reference to the base name for results files
clearOutputDir whether to clear the output directory prior to writing files
Definition at line 58 of file VertexMeshWriter.cpp.
References VertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::mpIters, and VertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::mpVtkUnstructedMesh.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> VertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::~VertexMeshWriter () [inline]
Destructor.
Definition at line 77 of file VertexMeshWriter.cpp.
References VertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::mpIters, VertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::mpNodeMap, and VertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::mpVtkUnstructedMesh.
Member Function Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void VertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::AddCellData (std::string dataName, std::vector< double > dataPayload) [inline]
Add data to a future VTK file.
Parameters:
dataName a tag to go into the VTK file
dataPayload a pay-load of length (number of elements)
Definition at line 350 of file VertexMeshWriter.cpp.
References VertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::mpVtkUnstructedMesh.
Referenced by VertexBasedCellPopulation< DIM >::WriteVtkResultsToFile(), MeshBasedCellPopulationWithGhostNodes< DIM >::WriteVtkResultsToFile(), and MeshBasedCellPopulation< ELEMENT_DIM, SPACE_DIM >::WriteVtkResultsToFile().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void VertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::AddPointData (std::string dataName, std::vector< double > dataPayload) [inline]
Add data to a future VTK file.
Parameters:
dataName a tag to go into the VTK file
dataPayload a pay-load of length (number of nodes)
Definition at line 367 of file VertexMeshWriter.cpp.
References VertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::mpVtkUnstructedMesh.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> ElementData VertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::GetNextElement () [inline, virtual]
Returns:
the data (indices/attributes) of the next element to be written to file
Todo:
Assert this method should only be called in 2D? (#1076/#1377)
Reimplemented from AbstractMeshWriter< ELEMENT_DIM, SPACE_DIM >.
Definition at line 179 of file VertexMeshWriter.cpp.
References NodeMap::GetNewIndex(), AbstractMeshWriter< ELEMENT_DIM, SPACE_DIM >::mNumElements, VertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::mpIters, VertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::mpMesh, VertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::mpNodeMap, and ElementData::NodeIndices.
Referenced by VertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::WriteFiles().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> VertexElementData VertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::GetNextElementWithFaces () [inline]
Returns:
the data (indices/attributes) of the next element to be written to file, including its faces. This method should only be called in 3D.
Todo:
Store face orientations? (#1076/#1377)
Definition at line 126 of file VertexMeshWriter.cpp.
References ElementData::AttributeValue, NodeMap::GetNewIndex(), AbstractMeshWriter< ELEMENT_DIM, SPACE_DIM >::mNumElements, VertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::mpIters, VertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::mpMesh, VertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::mpNodeMap, and ElementData::NodeIndices.
Referenced by VertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::WriteFiles().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> std::vector< double > VertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::GetNextNode () [inline, virtual]
Returns:
the coordinates of the next node to be written to file
Reimplemented from AbstractMeshWriter< ELEMENT_DIM, SPACE_DIM >.
Definition at line 99 of file VertexMeshWriter.cpp.
References AbstractMeshWriter< ELEMENT_DIM, SPACE_DIM >::mNumNodes, VertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::mpIters, and VertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::mpMesh.
Referenced by VertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::WriteFiles().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void VertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::MakeVtkMesh (VertexMesh< ELEMENT_DIM, SPACE_DIM > & rMesh) [inline]
Populate mpVtkUnstructedMesh using a vertex-based mesh. Called by WriteVtkUsingMesh().
Parameters:
rMesh reference to the vertex-based mesh
Definition at line 303 of file VertexMeshWriter.cpp.
References VertexMesh< ELEMENT_DIM, SPACE_DIM >::GetElementIteratorBegin(), VertexMesh< ELEMENT_DIM, SPACE_DIM >::GetElementIteratorEnd(), AbstractMesh< ELEMENT_DIM, SPACE_DIM >::GetNode(), VertexMesh< ELEMENT_DIM, SPACE_DIM >::GetNumNodes(), and VertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::mpVtkUnstructedMesh.
Referenced by VertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::WriteVtkUsingMesh().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void VertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::WriteFiles () [inline, virtual]
Write mesh data to files. This method must be overridden in concrete classes.
Todo:
Store face orientations? (#1076/#1377)
Implements AbstractMeshWriter< ELEMENT_DIM, SPACE_DIM >.
Definition at line 413 of file VertexMeshWriter.cpp.
References VertexElementData::AttributeValue, ElementData::AttributeValue, VertexElementData::Faces, VertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::GetNextElement(), VertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::GetNextElementWithFaces(), VertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::GetNextNode(), AbstractMeshWriter< ELEMENT_DIM, SPACE_DIM >::GetNumElements(), AbstractMeshWriter< ELEMENT_DIM, SPACE_DIM >::GetNumNodes(), ChasteBuildInfo::GetProvenanceString(), AbstractMeshWriter< ELEMENT_DIM, SPACE_DIM >::mBaseName, AbstractMeshWriter< ELEMENT_DIM, SPACE_DIM >::mpOutputFileHandler, VertexElementData::NodeIndices, ElementData::NodeIndices, and OutputFileHandler::OpenOutputFile().
Referenced by VertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::WriteFilesUsingMesh().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void VertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::WriteFilesUsingMesh (VertexMesh< ELEMENT_DIM, SPACE_DIM > & rMesh) [inline]
Todo:
Mesh should be const (#1076)
Write files using a mesh.
Parameters:
rMesh reference to the vertex-based mesh
Todo:
Mesh should be const (#1076)
Definition at line 385 of file VertexMeshWriter.cpp.
References VertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::mNodeMapCurrentIndex, AbstractMeshWriter< ELEMENT_DIM, SPACE_DIM >::mNumElements, AbstractMeshWriter< ELEMENT_DIM, SPACE_DIM >::mNumNodes, VertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::mpIters, VertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::mpMesh, AbstractMeshWriter< ELEMENT_DIM, SPACE_DIM >::mpMeshReader, VertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::mpNodeMap, NodeMap::SetNewIndex(), and VertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::WriteFiles().
Referenced by VertexMesh< DIM, DIM >::save().
template<> void VertexMeshWriter< 2, 2 >::WriteVtkUsingMesh (VertexMesh< 2, 2 > & rMesh, std::string stamp) [inline]
Write VTK file using a mesh.
Parameters:
rMesh reference to the vertex-based mesh
stamp is an optional stamp (like a time-stamp) to put into the name of the file
Definition at line 250 of file VertexMeshWriter.cpp.
References OutputFileHandler::GetOutputDirectoryFullPath(), VertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::MakeVtkMesh(), AbstractMeshWriter< ELEMENT_DIM, SPACE_DIM >::mBaseName, AbstractMeshWriter< ELEMENT_DIM, SPACE_DIM >::mpOutputFileHandler, and VertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::mpVtkUnstructedMesh.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void VertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::WriteVtkUsingMesh (VertexMesh< ELEMENT_DIM, SPACE_DIM > & rMesh, std::string stamp = "") [inline]
Write VTK file using a mesh.
Parameters:
rMesh reference to the vertex-based mesh
stamp is an optional stamp (like a time-stamp) to put into the name of the file
Definition at line 208 of file VertexMeshWriter.cpp.
References OutputFileHandler::GetOutputDirectoryFullPath(), VertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::MakeVtkMesh(), AbstractMeshWriter< ELEMENT_DIM, SPACE_DIM >::mBaseName, AbstractMeshWriter< ELEMENT_DIM, SPACE_DIM >::mpOutputFileHandler, and VertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::mpVtkUnstructedMesh.
Referenced by VertexBasedCellPopulation< DIM >::WriteVtkResultsToFile(), MeshBasedCellPopulationWithGhostNodes< DIM >::WriteVtkResultsToFile(), and MeshBasedCellPopulation< ELEMENT_DIM, SPACE_DIM >::WriteVtkResultsToFile().
Member Data Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> unsigned VertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::mNodeMapCurrentIndex [private]
What was the last index written to mpNodeMap ?
Definition at line 86 of file VertexMeshWriter.hpp.
Referenced by VertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::WriteFilesUsingMesh().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> MeshWriterIterators<ELEMENT_DIM,SPACE_DIM>* VertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::mpIters [private]
Iterators over the mesh
Definition at line 81 of file VertexMeshWriter.hpp.
Referenced by VertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::GetNextElement(), VertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::GetNextElementWithFaces(), VertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::GetNextNode(), VertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::VertexMeshWriter(), VertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::WriteFilesUsingMesh(), and VertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::~VertexMeshWriter().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> VertexMesh<ELEMENT_DIM,SPACE_DIM>* VertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::mpMesh [private]
If writing from a mesh object, the mesh to write to disk. Otherwise NULL.
Definition at line 78 of file VertexMeshWriter.hpp.
Referenced by VertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::GetNextElement(), VertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::GetNextElementWithFaces(), VertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::GetNextNode(), and VertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::WriteFilesUsingMesh().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> NodeMap* VertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::mpNodeMap [private]
Track deleted nodes so they don't get written
Definition at line 84 of file VertexMeshWriter.hpp.
Referenced by VertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::GetNextElement(), VertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::GetNextElementWithFaces(), VertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::WriteFilesUsingMesh(), and VertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::~VertexMeshWriter().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> vtkUnstructuredGrid* VertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::mpVtkUnstructedMesh [private]
Todo:
Merge into VtkMeshWriter (#1076)
Definition at line 91 of file VertexMeshWriter.hpp.
Referenced by VertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::AddCellData(), VertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::AddPointData(), VertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::MakeVtkMesh(), VertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::VertexMeshWriter(), VertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::WriteVtkUsingMesh(), and VertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::~VertexMeshWriter().
The documentation for this class was generated from the following files:
mesh/src/vertex/VertexMeshWriter.hpp
mesh/src/vertex/VertexMeshWriter.cpp