Chaste: AbstractMeshReader< ELEMENT_DIM, SPACE_DIM > Class Template Reference
AbstractMeshReader< ELEMENT_DIM, SPACE_DIM > Class Template Reference
#include <AbstractMeshReader.hpp>
Inherited by AbstractCachedMeshReader< ELEMENT_DIM, SPACE_DIM >, GmshMeshReader< ELEMENT_DIM, SPACE_DIM >, TrianglesMeshReader< ELEMENT_DIM, SPACE_DIM >, VertexMeshReader< ELEMENT_DIM, SPACE_DIM >, and VtkMeshReader< ELEMENT_DIM, SPACE_DIM >.
Classes
class ElementIterator
class NodeIterator
Public Member Functions
virtual unsigned GetNumElements () const =0
virtual unsigned GetNumNodes () const =0
virtual unsigned GetNumFaces () const =0
virtual unsigned GetNumCableElements () const
virtual unsigned GetNumElementAttributes () const
virtual unsigned GetNumFaceAttributes () const
virtual unsigned GetNumCableElementAttributes () const
virtual std::vector< double > GetNodeAttributes ()
unsigned GetNumEdges () const
virtual std::vector< double > GetNextNode ()=0
virtual void Reset ()=0
virtual ElementData GetNextElementData ()=0
virtual ElementData GetNextFaceData ()=0
virtual ElementData GetNextCableElementData ()
ElementData GetNextEdgeData ()
virtual std::vector< double > GetNode (unsigned index)
virtual ElementData GetElementData (unsigned index)
virtual ElementData GetFaceData (unsigned index)
ElementData GetEdgeData (unsigned index)
virtual std::vector< unsigned > GetContainingElementIndices (unsigned index)
virtual std::string GetMeshFileBaseName ()
virtual unsigned GetOrderOfElements ()
virtual unsigned GetOrderOfBoundaryElements ()
virtual bool GetReadContainingElementOfBoundaryElement ()
virtual bool IsFileFormatBinary ()
virtual bool HasNclFile ()
virtual bool HasNodePermutation ()
virtual const std::vector
< unsigned > & rGetNodePermutation ()
ElementIterator GetElementIteratorBegin ()
ElementIterator GetElementIteratorBegin (const std::set< unsigned > &rIndices)
ElementIterator GetElementIteratorEnd ()
NodeIterator GetNodeIteratorBegin ()
NodeIterator GetNodeIteratorBegin (const std::set< unsigned > &rIndices)
NodeIterator GetNodeIteratorEnd ()
Detailed Description
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM>
class AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >
An abstract mesh reader class. Reads output generated by a mesh generator and converts it to a standard format for use in constructing a finite element mesh structure.
A derived class TrianglesMeshReader exists for reading meshes generated by Triangles (in 2-d) and TetGen (in 3-d).
A derived class MemfemMeshReader reads 3D data from the Tulane University code
A derived class FemlabMeshReader reads 2D data from Femlab or Matlab PDEToolbox
Definition at line 71 of file AbstractMeshReader.hpp.
Member Function Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> std::vector< unsigned > AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::GetContainingElementIndices (unsigned index) [inline, virtual]
Normally throws an exception. When implemented by derived classes, returns a list of the elements that contain the node (only available for binary files).
Parameters:
index The global node index
Returns:
a vector of the node indices of the face (and any attribute/containment information, if there is any)
Reimplemented in TrianglesMeshReader< ELEMENT_DIM, SPACE_DIM >.
Definition at line 106 of file AbstractMeshReader.cpp.
References EXCEPTION.
Referenced by DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ComputeMeshPartitioning().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> ElementData AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::GetEdgeData (unsigned index) [inline]
Synonym of GetFaceData(index)
Parameters:
index The global edge index
Returns:
a vector of the node indices of the edge (and any attribute/containment information, if there is any)
Definition at line 100 of file AbstractMeshReader.cpp.
References AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::GetFaceData().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> ElementData AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::GetElementData (unsigned index) [inline, virtual]
Normally throws an exception. Only implemented for tetrahedral mesh reader of binary files.
Parameters:
index The global element index
Returns:
a vector of the node indices of the element (and any attribute information, if there is any)
Reimplemented in GmshMeshReader< ELEMENT_DIM, SPACE_DIM >, and TrianglesMeshReader< ELEMENT_DIM, SPACE_DIM >.
Definition at line 88 of file AbstractMeshReader.cpp.
References EXCEPTION.
Referenced by AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::ElementIterator::CacheData(), DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ComputeMeshPartitioning(), DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ParMetisLibraryNodeAndElementPartitioning(), and NodePartitioner< ELEMENT_DIM, SPACE_DIM >::PetscMatrixPartitioning().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::ElementIterator AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::GetElementIteratorBegin (const std::set< unsigned > & rIndices) [inline]
Returns:
an iterator over a set of elements whose indices are given
Parameters:
rIndices subset of indices
Note that, in the case of an ASCII mesh file, for efficiency this will actually start wherever the file pointer currently is. The user is responsible for resetting the reader prior to calling GetElementIteratorBegin().
Definition at line 191 of file AbstractMeshReader.cpp.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::ElementIterator AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::GetElementIteratorBegin () [inline]
Returns:
an iterator to the first element in the file.
Note that, in the case of an ASCII mesh file, for efficiency this will actually start wherever the file pointer currently is. The user is responsible for resetting the reader prior to calling GetElementIteratorBegin().
Definition at line 184 of file AbstractMeshReader.cpp.
Referenced by QuadraticMeshHelper< DIM >::AddInternalNodesToElements(), and DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructFromMeshReader().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::ElementIterator AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::GetElementIteratorEnd () [inline]
Returns:
an iterator to (one past the) end of the element data.
Definition at line 198 of file AbstractMeshReader.cpp.
References AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::GetNumElements().
Referenced by QuadraticMeshHelper< DIM >::AddInternalNodesToElements(), and DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructFromMeshReader().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> ElementData AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::GetFaceData (unsigned index) [inline, virtual]
Normally throws an exception. Only implemented for tetrahedral mesh reader of binary files.
Parameters:
index The global face index
Returns:
a vector of the node indices of the face (and any attribute/containment information, if there is any)
Reimplemented in GmshMeshReader< ELEMENT_DIM, SPACE_DIM >, and TrianglesMeshReader< ELEMENT_DIM, SPACE_DIM >.
Definition at line 94 of file AbstractMeshReader.cpp.
References EXCEPTION.
Referenced by AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::GetEdgeData().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> std::string AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::GetMeshFileBaseName () [inline, virtual]
Returns:
the base name (less any extension) for mesh files. Only implemented for some mesh types.
Reimplemented in TrianglesMeshReader< ELEMENT_DIM, SPACE_DIM >.
Definition at line 112 of file AbstractMeshReader.cpp.
Referenced by TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructFromMeshReader(), and DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructFromMeshReader().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> ElementData AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::GetNextCableElementData () [inline, virtual]
Returns:
a vector of the node indices of each cable element (and any attribute information, if there is any) in turn
Reimplemented in GmshMeshReader< ELEMENT_DIM, SPACE_DIM >, TrianglesMeshReader< ELEMENT_DIM, SPACE_DIM >, and VtkMeshReader< ELEMENT_DIM, SPACE_DIM >.
Definition at line 174 of file AbstractMeshReader.cpp.
References EXCEPTION.
Referenced by MixedDimensionMesh< ELEMENT_DIM, SPACE_DIM >::ConstructFromMeshReader().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> ElementData AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::GetNextEdgeData () [inline]
Returns:
a vector of the node indices of each edge (and any attribute/containment information, if there is any) in turn (synonym of GetNextFaceData())
Definition at line 75 of file AbstractMeshReader.cpp.
References AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::GetNextFaceData().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> virtual ElementData AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::GetNextElementData () [pure virtual]
Returns:
a vector of the node indices of each element (and any attribute information, if there is any) in turn
Implemented in AbstractCachedMeshReader< ELEMENT_DIM, SPACE_DIM >, GmshMeshReader< ELEMENT_DIM, SPACE_DIM >, TrianglesMeshReader< ELEMENT_DIM, SPACE_DIM >, VtkMeshReader< ELEMENT_DIM, SPACE_DIM >, VertexMeshReader< ELEMENT_DIM, SPACE_DIM >, and PottsMeshReader< SPACE_DIM >.
Referenced by AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::ElementIterator::CacheData(), DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ComputeMeshPartitioning(), TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructFromMeshReader(), PottsMesh< DIM >::ConstructFromMeshReader(), NodePartitioner< ELEMENT_DIM, SPACE_DIM >::MetisLibraryPartitioning(), DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ParMetisLibraryNodeAndElementPartitioning(), and NodePartitioner< ELEMENT_DIM, SPACE_DIM >::PetscMatrixPartitioning().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> virtual ElementData AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::GetNextFaceData () [pure virtual]
Returns:
a vector of the node indices of each face (and any attribute/containment information, if there is any) in turn
Implemented in AbstractCachedMeshReader< ELEMENT_DIM, SPACE_DIM >, GmshMeshReader< ELEMENT_DIM, SPACE_DIM >, TrianglesMeshReader< ELEMENT_DIM, SPACE_DIM >, VtkMeshReader< ELEMENT_DIM, SPACE_DIM >, VertexMeshReader< ELEMENT_DIM, SPACE_DIM >, and PottsMeshReader< SPACE_DIM >.
Referenced by QuadraticMeshHelper< DIM >::AddNodesToBoundaryElements(), TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructFromMeshReader(), DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructFromMeshReader(), and AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::GetNextEdgeData().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> virtual std::vector<double> AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::GetNextNode () [pure virtual]
Returns:
a vector of the coordinates of each node in turn
Implemented in AbstractCachedMeshReader< ELEMENT_DIM, SPACE_DIM >, GmshMeshReader< ELEMENT_DIM, SPACE_DIM >, TrianglesMeshReader< ELEMENT_DIM, SPACE_DIM >, VtkMeshReader< ELEMENT_DIM, SPACE_DIM >, VertexMeshReader< ELEMENT_DIM, SPACE_DIM >, and PottsMeshReader< SPACE_DIM >.
Referenced by AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::NodeIterator::CacheData(), TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructFromMeshReader(), DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructFromMeshReader(), PottsMesh< DIM >::ConstructFromMeshReader(), and NodePartitioner< ELEMENT_DIM, SPACE_DIM >::GeometricPartitioning().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> std::vector< double > AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::GetNode (unsigned index) [inline, virtual]
Normally throws an exception. Only implemented for tetrahedral mesh reader of binary files.
Parameters:
index The global node index
Returns:
a vector of the coordinates of the node
Reimplemented in GmshMeshReader< ELEMENT_DIM, SPACE_DIM >, and TrianglesMeshReader< ELEMENT_DIM, SPACE_DIM >.
Definition at line 82 of file AbstractMeshReader.cpp.
References EXCEPTION.
Referenced by AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::NodeIterator::CacheData().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> std::vector< double > AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::GetNodeAttributes () [inline, virtual]
Returns:
the vector of node attributes
an empty vector here. Over-ride in child classes if needed. Ideally, this method would be in AbstractCachedMeshReader (where it would return the cached attribuites) but TrianglesMeshReader (the class this method was created for) does not inherit from AbstractCachedMeshReader, so it needs to be here.
Reimplemented in GmshMeshReader< ELEMENT_DIM, SPACE_DIM >, and TrianglesMeshReader< ELEMENT_DIM, SPACE_DIM >.
Definition at line 66 of file AbstractMeshReader.cpp.
Referenced by TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructFromMeshReader(), and DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructFromMeshReader().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::NodeIterator AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::GetNodeIteratorBegin (const std::set< unsigned > & rIndices) [inline]
Returns:
an iterator over a set of nodes whose indices are given
Parameters:
rIndices subset of indices
Note that, in the case of an ASCII mesh file, for efficiency this will actually start wherever the file pointer currently is. The user is responsible for resetting the reader prior to calling GetNodeIteratorBegin().
Definition at line 288 of file AbstractMeshReader.cpp.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::NodeIterator AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::GetNodeIteratorBegin () [inline]
Returns:
an iterator to the first node in the file.
Note that, in the case of an ASCII mesh file, for efficiency this will actually start wherever the file pointer currently is. The user is responsible for resetting the reader prior to calling GetNodeIteratorBegin().
Definition at line 281 of file AbstractMeshReader.cpp.
Referenced by DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructFromMeshReader().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::NodeIterator AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::GetNodeIteratorEnd () [inline]
Returns:
an iterator to (one past the) end of the node data.
Definition at line 295 of file AbstractMeshReader.cpp.
References AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::GetNumNodes().
Referenced by DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructFromMeshReader().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> unsigned AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::GetNumCableElementAttributes () const [inline, virtual]
Returns:
the number of cable element attributes in the mesh
Reimplemented in GmshMeshReader< ELEMENT_DIM, SPACE_DIM >, TrianglesMeshReader< ELEMENT_DIM, SPACE_DIM >, and VtkMeshReader< ELEMENT_DIM, SPACE_DIM >.
Definition at line 168 of file AbstractMeshReader.cpp.
Referenced by MixedDimensionMesh< ELEMENT_DIM, SPACE_DIM >::ConstructFromMeshReader().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> unsigned AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::GetNumCableElements () const [inline, virtual]
Returns:
the number of cable elements in the mesh
Reimplemented in GmshMeshReader< ELEMENT_DIM, SPACE_DIM >, TrianglesMeshReader< ELEMENT_DIM, SPACE_DIM >, and VtkMeshReader< ELEMENT_DIM, SPACE_DIM >.
Definition at line 162 of file AbstractMeshReader.cpp.
Referenced by MixedDimensionMesh< ELEMENT_DIM, SPACE_DIM >::ConstructFromMeshReader().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> unsigned AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::GetNumEdges () const [inline]
Returns:
the number of edges in the mesh (synonym of GetNumFaces())
Reimplemented in VtkMeshReader< ELEMENT_DIM, SPACE_DIM >, and VertexMeshReader< ELEMENT_DIM, SPACE_DIM >.
Definition at line 52 of file AbstractMeshReader.cpp.
References AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::GetNumFaces().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> unsigned AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::GetNumElementAttributes () const [inline, virtual]
Returns:
the number of element attributes in the mesh
Reimplemented in GmshMeshReader< ELEMENT_DIM, SPACE_DIM >, TrianglesMeshReader< ELEMENT_DIM, SPACE_DIM >, VtkMeshReader< ELEMENT_DIM, SPACE_DIM >, VertexMeshReader< ELEMENT_DIM, SPACE_DIM >, and PottsMeshReader< SPACE_DIM >.
Definition at line 44 of file AbstractMeshReader.cpp.
Referenced by TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructFromMeshReader(), DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructFromMeshReader(), and PottsMesh< DIM >::ConstructFromMeshReader().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> virtual unsigned AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::GetNumElements () const [pure virtual]
Returns:
the number of elements in the mesh
Implemented in AbstractCachedMeshReader< ELEMENT_DIM, SPACE_DIM >, GmshMeshReader< ELEMENT_DIM, SPACE_DIM >, TrianglesMeshReader< ELEMENT_DIM, SPACE_DIM >, VtkMeshReader< ELEMENT_DIM, SPACE_DIM >, VertexMeshReader< ELEMENT_DIM, SPACE_DIM >, and PottsMeshReader< SPACE_DIM >.
Referenced by AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::ElementIterator::CacheData(), TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructFromMeshReader(), DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructFromMeshReader(), PottsMesh< DIM >::ConstructFromMeshReader(), AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::ElementIterator::dereference(), AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::ElementIterator::ElementIterator(), AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::GetElementIteratorEnd(), AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::ElementIterator::increment(), NodePartitioner< ELEMENT_DIM, SPACE_DIM >::MetisLibraryPartitioning(), DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ParMetisLibraryNodeAndElementPartitioning(), and NodePartitioner< ELEMENT_DIM, SPACE_DIM >::PetscMatrixPartitioning().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> unsigned AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::GetNumFaceAttributes () const [inline, virtual]
Returns:
the number of face attributes in the mesh
Reimplemented in GmshMeshReader< ELEMENT_DIM, SPACE_DIM >, TrianglesMeshReader< ELEMENT_DIM, SPACE_DIM >, and VtkMeshReader< ELEMENT_DIM, SPACE_DIM >.
Definition at line 58 of file AbstractMeshReader.cpp.
Referenced by TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructFromMeshReader(), and DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructFromMeshReader().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> virtual unsigned AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::GetNumFaces () const [pure virtual]
Returns:
the number of faces in the mesh (also has synonym GetNumEdges())
Implemented in AbstractCachedMeshReader< ELEMENT_DIM, SPACE_DIM >, GmshMeshReader< ELEMENT_DIM, SPACE_DIM >, TrianglesMeshReader< ELEMENT_DIM, SPACE_DIM >, VtkMeshReader< ELEMENT_DIM, SPACE_DIM >, VertexMeshReader< ELEMENT_DIM, SPACE_DIM >, and PottsMeshReader< SPACE_DIM >.
Referenced by TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructFromMeshReader(), DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructFromMeshReader(), and AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::GetNumEdges().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> virtual unsigned AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::GetNumNodes () const [pure virtual]
Returns:
the number of nodes in the mesh
Implemented in AbstractCachedMeshReader< ELEMENT_DIM, SPACE_DIM >, GmshMeshReader< ELEMENT_DIM, SPACE_DIM >, TrianglesMeshReader< ELEMENT_DIM, SPACE_DIM >, VtkMeshReader< ELEMENT_DIM, SPACE_DIM >, VertexMeshReader< ELEMENT_DIM, SPACE_DIM >, and PottsMeshReader< SPACE_DIM >.
Referenced by AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::NodeIterator::CacheData(), TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructFromMeshReader(), DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructFromMeshReader(), PottsMesh< DIM >::ConstructFromMeshReader(), AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::NodeIterator::dereference(), NodePartitioner< ELEMENT_DIM, SPACE_DIM >::GeometricPartitioning(), AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::GetNodeIteratorEnd(), AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::NodeIterator::increment(), NodePartitioner< ELEMENT_DIM, SPACE_DIM >::MetisLibraryPartitioning(), AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::NodeIterator::NodeIterator(), DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ParMetisLibraryNodeAndElementPartitioning(), and NodePartitioner< ELEMENT_DIM, SPACE_DIM >::PetscMatrixPartitioning().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> unsigned AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::GetOrderOfBoundaryElements () [inline, virtual]
Returns:
the expected order of the boundary element file (1=linear, 2=quadratic)
Reimplemented in GmshMeshReader< ELEMENT_DIM, SPACE_DIM >, and TrianglesMeshReader< ELEMENT_DIM, SPACE_DIM >.
Definition at line 124 of file AbstractMeshReader.cpp.
Referenced by QuadraticMeshHelper< DIM >::AddInternalNodesToBoundaryElements().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> unsigned AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::GetOrderOfElements () [inline, virtual]
Returns:
the expected order of the element file (1=linear, 2=quadratic)
Reimplemented in GmshMeshReader< ELEMENT_DIM, SPACE_DIM >, and TrianglesMeshReader< ELEMENT_DIM, SPACE_DIM >.
Definition at line 118 of file AbstractMeshReader.cpp.
Referenced by QuadraticMesh< DIM >::ConstructFromMeshReader().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> bool AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::GetReadContainingElementOfBoundaryElement () [inline, virtual]
Returns:
true if the boundary element file is linear, but contains information about neighbouring elements
Reimplemented in TrianglesMeshReader< ELEMENT_DIM, SPACE_DIM >.
Definition at line 130 of file AbstractMeshReader.cpp.
Referenced by QuadraticMeshHelper< DIM >::AddNodesToBoundaryElements().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> bool AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::HasNclFile () [inline, virtual]
Returns:
true if there is a node connectivity list (NCL) file available.
Note, this will always return false unless over-ridden by a derived class that is able to support NCL files.
Reimplemented in TrianglesMeshReader< ELEMENT_DIM, SPACE_DIM >.
Definition at line 142 of file AbstractMeshReader.cpp.
Referenced by DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ComputeMeshPartitioning().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> bool AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::HasNodePermutation () [inline, virtual]
Returns:
true if there is a node permutation applied.
Note, this will always return false unless over-ridden by a derived class that is able to support NCL files.
Reimplemented in TrianglesMeshReader< ELEMENT_DIM, SPACE_DIM >.
Definition at line 148 of file AbstractMeshReader.cpp.
Referenced by TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructFromMeshReader(), DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructFromMeshReader(), and PottsMesh< DIM >::ConstructFromMeshReader().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> bool AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::IsFileFormatBinary () [inline, virtual]
Returns:
true if reading binary files, false if reading ascii files.
Note, this will always return false unless over-ridden by a derived class that is able to support binary file formats.
Reimplemented in TrianglesMeshReader< ELEMENT_DIM, SPACE_DIM >.
Definition at line 136 of file AbstractMeshReader.cpp.
Referenced by AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::NodeIterator::CacheData(), AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::ElementIterator::CacheData(), DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructFromMeshReader(), DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ParMetisLibraryNodeAndElementPartitioning(), and NodePartitioner< ELEMENT_DIM, SPACE_DIM >::PetscMatrixPartitioning().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> virtual void AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::Reset () [pure virtual]
Resets pointers to beginning
Implemented in AbstractCachedMeshReader< ELEMENT_DIM, SPACE_DIM >, GmshMeshReader< ELEMENT_DIM, SPACE_DIM >, TrianglesMeshReader< ELEMENT_DIM, SPACE_DIM >, VtkMeshReader< ELEMENT_DIM, SPACE_DIM >, VertexMeshReader< ELEMENT_DIM, SPACE_DIM >, and PottsMeshReader< SPACE_DIM >.
Referenced by QuadraticMeshHelper< DIM >::AddInternalNodesToElements(), QuadraticMeshHelper< DIM >::AddNodesToBoundaryElements(), DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ComputeMeshPartitioning(), TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructFromMeshReader(), MixedDimensionMesh< ELEMENT_DIM, SPACE_DIM >::ConstructFromMeshReader(), DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructFromMeshReader(), PottsMesh< DIM >::ConstructFromMeshReader(), NodePartitioner< ELEMENT_DIM, SPACE_DIM >::MetisLibraryPartitioning(), DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ParMetisLibraryNodeAndElementPartitioning(), and NodePartitioner< ELEMENT_DIM, SPACE_DIM >::PetscMatrixPartitioning().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> const std::vector< unsigned > & AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::rGetNodePermutation () [inline, virtual]
Returns:
the node permutation if a node permutation has been applied to this reader (or an empty permutation)
Note, this will always throw an exception unless over-ridden by a derived class that is able to support NCL files.
Reimplemented in TrianglesMeshReader< ELEMENT_DIM, SPACE_DIM >.
Definition at line 154 of file AbstractMeshReader.cpp.
References EXCEPTION.
Referenced by DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructFromMeshReader().
The documentation for this class was generated from the following files:
mesh/src/reader/AbstractMeshReader.hpp
mesh/src/reader/AbstractMeshReader.cpp