Chaste: AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::ElementIterator Class Reference
AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::ElementIterator Class Reference
#include <AbstractMeshReader.hpp>
Inherits boost::iterator_facade< ElementIterator, const ElementData, boost::single_pass_traversal_tag >.
Public Member Functions
ElementIterator ()
ElementIterator (unsigned index, AbstractMeshReader *pReader)
ElementIterator (const std::set< unsigned > &rIndices, AbstractMeshReader *pReader)
unsigned GetIndex () const
Private Member Functions
void CacheData (unsigned index, bool firstRead=false)
void increment ()
bool equal (const ElementIterator &rOther) const
const ElementData & dereference () const
Private Attributes
unsigned mIndex
const std::set< unsigned > * mpIndices
std::set< unsigned >
::const_iterator mIndicesIterator
AbstractMeshReader * mpReader
ElementData mLastDataRead
Friends
class boost::iterator_core_access
Detailed Description
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM>
class AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::ElementIterator
An iterator class for element data.
Definition at line 231 of file AbstractMeshReader.hpp.
Constructor & Destructor Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::ElementIterator::ElementIterator () [inline]
Default constructor for an iterator that doesn't point to anything.
Definition at line 238 of file AbstractMeshReader.hpp.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::ElementIterator::ElementIterator (unsigned index, AbstractMeshReader * pReader) [inline]
Constructor for pointing to a specific item.
Note that, in the case of an ASCII mesh file, this will actually start wherever the file pointer currently is. The user is responsible for resetting the reader prior to creating an iterator.
Parameters:
index the index of the item to point at
pReader the mesh reader to iterate over
Definition at line 255 of file AbstractMeshReader.hpp.
References AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::ElementIterator::CacheData(), and AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::ElementIterator::mIndex.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::ElementIterator::ElementIterator (const std::set< unsigned > & rIndices, AbstractMeshReader * pReader) [inline]
Constructor for iterating over a subset of the items in the mesh.
Parameters:
rIndices a set of item indices over which to iterate
pReader the mesh reader to iterate over
Definition at line 204 of file AbstractMeshReader.cpp.
References AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::ElementIterator::CacheData(), AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::GetNumElements(), AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::ElementIterator::mIndex, AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::ElementIterator::mIndicesIterator, AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::ElementIterator::mpIndices, and AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::ElementIterator::mpReader.
Member Function Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::ElementIterator::CacheData (unsigned index, bool firstRead = false) [inline, private]
Read the pointed-at item data (if we're pointing at anything) and cache it within the iterator, for use in dereference.
Parameters:
index the item to read
firstRead Set to true in the constructor. This ensures that the line 0 is always read
Definition at line 249 of file AbstractMeshReader.cpp.
References AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::GetElementData(), AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::GetNextElementData(), AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::GetNumElements(), AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::IsFileFormatBinary(), AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::ElementIterator::mIndex, AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::ElementIterator::mLastDataRead, and AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::ElementIterator::mpReader.
Referenced by AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::ElementIterator::ElementIterator(), and AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::ElementIterator::increment().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> const ElementData& AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::ElementIterator::dereference () const [inline, private]
Dereference this iterator to get the data for the item pointed at.
Note that the returned reference is only valid for as long as this iterator is pointing at the item.
Returns:
reference
Definition at line 314 of file AbstractMeshReader.hpp.
References AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::GetNumElements(), AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::ElementIterator::mLastDataRead, and AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::ElementIterator::mpReader.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> bool AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::ElementIterator::equal (const ElementIterator & rOther) const [inline, private]
Returns:
true if two iterators point at the same item.
Parameters:
rOther the other iterator
Definition at line 302 of file AbstractMeshReader.hpp.
References AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::ElementIterator::mIndex.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> unsigned AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::ElementIterator::GetIndex () const [inline]
Returns:
the index of the item pointed at.
Definition at line 276 of file AbstractMeshReader.hpp.
References AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::ElementIterator::mIndex.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::ElementIterator::increment () [inline, private]
Increment the iterator to point at the next item in the file.
Definition at line 222 of file AbstractMeshReader.cpp.
References AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::ElementIterator::CacheData(), AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::GetNumElements(), AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::ElementIterator::mIndex, AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::ElementIterator::mIndicesIterator, AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::ElementIterator::mpIndices, and AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::ElementIterator::mpReader.
Member Data Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> unsigned AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::ElementIterator::mIndex [private]
The index of the item pointed at.
Definition at line 323 of file AbstractMeshReader.hpp.
Referenced by AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::ElementIterator::CacheData(), AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::ElementIterator::ElementIterator(), AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::ElementIterator::equal(), AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::ElementIterator::GetIndex(), and AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::ElementIterator::increment().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> std::set<unsigned>::const_iterator AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::ElementIterator::mIndicesIterator [private]
Iterator over the indices in that subset.
Definition at line 329 of file AbstractMeshReader.hpp.
Referenced by AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::ElementIterator::ElementIterator(), and AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::ElementIterator::increment().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> ElementData AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::ElementIterator::mLastDataRead [private]
Data for the last item read.
Definition at line 335 of file AbstractMeshReader.hpp.
Referenced by AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::ElementIterator::CacheData(), and AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::ElementIterator::dereference().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> const std::set<unsigned>* AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::ElementIterator::mpIndices [private]
The set which we're iterating over, if we are iterating over a subset of the items.
Definition at line 326 of file AbstractMeshReader.hpp.
Referenced by AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::ElementIterator::ElementIterator(), and AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::ElementIterator::increment().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> AbstractMeshReader* AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::ElementIterator::mpReader [private]
The mesh reader we're iterating over.
Definition at line 332 of file AbstractMeshReader.hpp.
Referenced by AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::ElementIterator::CacheData(), AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::ElementIterator::dereference(), AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::ElementIterator::ElementIterator(), and AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >::ElementIterator::increment().
The documentation for this class was generated from the following files:
mesh/src/reader/AbstractMeshReader.hpp
mesh/src/reader/AbstractMeshReader.cpp