Chaste: GmshMeshReader< ELEMENT_DIM, SPACE_DIM > Class Template Reference
GmshMeshReader< ELEMENT_DIM, SPACE_DIM > Class Template Reference
#include <GmshMeshReader.hpp>
Inherits AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >.
Public Member Functions
GmshMeshReader (std::string pathBaseName, unsigned orderOfElements=1, unsigned orderOfBoundaryElements=1)
~GmshMeshReader ()
unsigned GetNumElements () const
unsigned GetNumNodes () const
unsigned GetNumFaces () const
unsigned GetNumCableElements () const
unsigned GetNumElementAttributes () const
unsigned GetNumFaceAttributes () const
unsigned GetNumCableElementAttributes () const
unsigned GetOrderOfElements ()
unsigned GetOrderOfBoundaryElements ()
void Reset ()
std::vector< double > GetNextNode ()
ElementData GetNextElementData ()
ElementData GetNextFaceData ()
ElementData GetNextCableElementData ()
std::vector< double > GetNodeAttributes ()
std::vector< double > GetNode (unsigned index)
ElementData GetElementData (unsigned index)
ElementData GetFaceData (unsigned index)
Private Member Functions
void ReadHeaders ()
void ReadNodeHeader ()
void ReadElementHeader ()
void ReadFaceHeader ()
void OpenFiles ()
void CloseFiles ()
Private Attributes
std::string mFileName
std::ifstream mNodeFile
std::ifstream mElementFile
std::ifstream mFaceFile
double mVersionNumber
unsigned mFileType
unsigned mDataSize
unsigned mNumNodes
unsigned mNumElements
unsigned mNumFaces
unsigned mNumElementAttributes
unsigned mNumFaceAttributes
unsigned mOrderOfElements
unsigned mOrderOfBoundaryElements
unsigned mNodesPerElement
unsigned mNodesPerBoundaryElement
Detailed Description
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM>
class GmshMeshReader< ELEMENT_DIM, SPACE_DIM >
Class to enable reading of Gmsh format mesh files (see #2312).
Definition at line 68 of file GmshMeshReader.hpp.
Constructor & Destructor Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::GmshMeshReader (std::string pathBaseName, unsigned orderOfElements = 1, unsigned orderOfBoundaryElements = 1) [inline]
Constructor.
Parameters:
pathBaseName the base name of the files from which to read the mesh data (either absolute, or relative to the current directory)
orderOfElements the order of each element: 1 for linear, 2 for quadratic (defaults to 1)
orderOfBoundaryElements the order of each boundary element: 1 for linear, 2 for quadratic (defaults to 1. May or may not be different to orderOfElements
Definition at line 43 of file GmshMeshReader.cpp.
References GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::mNodesPerBoundaryElement, GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::mNodesPerElement, GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::mOrderOfBoundaryElements, GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::mOrderOfElements, GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::OpenFiles(), and GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::ReadHeaders().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::~GmshMeshReader () [inline]
Destructor
Definition at line 78 of file GmshMeshReader.cpp.
References GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::CloseFiles().
Member Function Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::CloseFiles () [inline, private]
Closes the .msh file descriptors
Definition at line 97 of file GmshMeshReader.cpp.
References GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::mElementFile, GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::mFaceFile, and GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::mNodeFile.
Referenced by GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::Reset(), and GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::~GmshMeshReader().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> ElementData GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::GetElementData (unsigned index) [inline, virtual]
Normally throws an exception. Only implemented for tetrahedral mesh reader of binary files.
Parameters:
index The global element index
Returns:
a vector of the node indices of the element (and any attribute information, if there is any)
Reimplemented from AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >.
Definition at line 454 of file GmshMeshReader.cpp.
References NEVER_REACHED.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> ElementData GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::GetFaceData (unsigned index) [inline, virtual]
Normally throws an exception. Only implemented for tetrahedral mesh reader of binary files.
Parameters:
index The global face index
Returns:
a vector of the node indices of the face (and any attribute/containment information, if there is any)
Reimplemented from AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >.
Definition at line 460 of file GmshMeshReader.cpp.
References NEVER_REACHED.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> ElementData GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::GetNextCableElementData () [inline, virtual]
Returns:
a vector of the node indices of each cable element (and any attribute information, if there is any) in turn
Reimplemented from AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >.
Definition at line 388 of file GmshMeshReader.cpp.
References NEVER_REACHED.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> ElementData GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::GetNextElementData () [inline, virtual]
Returns:
a vector of the nodes of each element (and any attribute information, if there is any) in turn
Implements AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >.
Definition at line 334 of file GmshMeshReader.cpp.
References ElementData::AttributeValue, GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::mElementFile, GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::mNodesPerElement, GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::mNumElementAttributes, and ElementData::NodeIndices.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> ElementData GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::GetNextFaceData () [inline, virtual]
Returns:
a vector of the nodes of each face in turn (synonym of GetNextEdgeData())
Implements AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >.
Definition at line 394 of file GmshMeshReader.cpp.
References ElementData::AttributeValue, GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::mFaceFile, GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::mNodesPerBoundaryElement, GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::mNumFaceAttributes, and ElementData::NodeIndices.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> std::vector< double > GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::GetNextNode () [inline, virtual]
Returns:
a vector of the coordinates of each node in turn
Implements AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >.
Definition at line 307 of file GmshMeshReader.cpp.
References GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::mNodeFile.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> std::vector< double > GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::GetNode (unsigned index) [inline, virtual]
Normally throws an exception. Only implemented for tetrahedral mesh reader of binary files.
Parameters:
index The global node index
Returns:
a vector of the coordinates of the node
Reimplemented from AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >.
Definition at line 448 of file GmshMeshReader.cpp.
References NEVER_REACHED.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> std::vector< double > GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::GetNodeAttributes () [inline, virtual]
Returns:
the vector of node attributes
Reimplemented from AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >.
Definition at line 328 of file GmshMeshReader.cpp.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> unsigned GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::GetNumCableElementAttributes () const [inline, virtual]
Returns:
the number of cable element attributes in the mesh
Reimplemented from AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >.
Definition at line 290 of file GmshMeshReader.cpp.
References NEVER_REACHED.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> unsigned GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::GetNumCableElements () const [inline, virtual]
Returns:
the number of cable elements in the mesh
Reimplemented from AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >.
Definition at line 259 of file GmshMeshReader.cpp.
References NEVER_REACHED.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> unsigned GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::GetNumElementAttributes () const [inline, virtual]
Returns:
the number of attributes in the mesh
Reimplemented from AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >.
Definition at line 278 of file GmshMeshReader.cpp.
References GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::mNumElementAttributes.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> unsigned GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::GetNumElements () const [inline, virtual]
Returns:
the number of elements in the mesh
Implements AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >.
Definition at line 241 of file GmshMeshReader.cpp.
References GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::mNumElements.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> unsigned GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::GetNumFaceAttributes () const [inline, virtual]
Returns:
the number of attributes in the mesh
Reimplemented from AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >.
Definition at line 284 of file GmshMeshReader.cpp.
References GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::mNumFaceAttributes.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> unsigned GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::GetNumFaces () const [inline, virtual]
Returns:
the number of faces in the mesh (synonym of GetNumEdges())
Implements AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >.
Definition at line 253 of file GmshMeshReader.cpp.
References GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::mNumFaces.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> unsigned GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::GetNumNodes () const [inline, virtual]
Returns:
the number of nodes in the mesh
Implements AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >.
Definition at line 247 of file GmshMeshReader.cpp.
References GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::mNumNodes.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> unsigned GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::GetOrderOfBoundaryElements () [inline, virtual]
Returns:
the expected order of the element file (1=linear, 2=quadratic)
Reimplemented from AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >.
Definition at line 272 of file GmshMeshReader.cpp.
References GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::mOrderOfBoundaryElements.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> unsigned GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::GetOrderOfElements () [inline, virtual]
*
Returns:
the expected order of the element file (1=linear, 2=quadratic)
Reimplemented from AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >.
Definition at line 266 of file GmshMeshReader.cpp.
References GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::mOrderOfElements.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::OpenFiles () [inline, private]
Opens the .msh file descriptors
Definition at line 84 of file GmshMeshReader.cpp.
References EXCEPTION, GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::mElementFile, GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::mFaceFile, GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::mFileName, and GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::mNodeFile.
Referenced by GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::GmshMeshReader(), and GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::Reset().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::ReadElementHeader () [inline, private]
Read the element header from the mesh file.
Definition at line 157 of file GmshMeshReader.cpp.
References GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::mElementFile, and GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::mNumElements.
Referenced by GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::ReadHeaders().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::ReadFaceHeader () [inline, private]
Read the face header from the mesh file.
Definition at line 199 of file GmshMeshReader.cpp.
References GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::mFaceFile, and GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::mNumFaces.
Referenced by GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::ReadHeaders().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::ReadHeaders () [inline, private]
Read all the header information from the mesh file.
Definition at line 106 of file GmshMeshReader.cpp.
References EXCEPTION, GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::mDataSize, GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::mFileType, GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::mNodeFile, GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::mVersionNumber, GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::ReadElementHeader(), GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::ReadFaceHeader(), and GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::ReadNodeHeader().
Referenced by GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::GmshMeshReader(), and GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::Reset().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::ReadNodeHeader () [inline, private]
Read the node header from the mesh file.
Definition at line 139 of file GmshMeshReader.cpp.
References GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::mNodeFile, and GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::mNumNodes.
Referenced by GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::ReadHeaders().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::Reset () [inline, virtual]
Resets pointers to beginning
Implements AbstractMeshReader< ELEMENT_DIM, SPACE_DIM >.
Definition at line 298 of file GmshMeshReader.cpp.
References GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::CloseFiles(), GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::OpenFiles(), and GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::ReadHeaders().
Member Data Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> unsigned GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::mDataSize [private]
The number of floating point numbers in the file
Definition at line 186 of file GmshMeshReader.hpp.
Referenced by GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::ReadHeaders().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> std::ifstream GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::mElementFile [private]
A file stream used to read the volume elements of the file.
Definition at line 182 of file GmshMeshReader.hpp.
Referenced by GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::CloseFiles(), GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::GetNextElementData(), GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::OpenFiles(), and GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::ReadElementHeader().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> std::ifstream GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::mFaceFile [private]
A file stream used to read the boundary elements of the file.
Definition at line 183 of file GmshMeshReader.hpp.
Referenced by GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::CloseFiles(), GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::GetNextFaceData(), GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::OpenFiles(), and GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::ReadFaceHeader().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> std::string GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::mFileName [private]
The name of the mesh file.
Definition at line 180 of file GmshMeshReader.hpp.
Referenced by GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::OpenFiles().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> unsigned GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::mFileType [private]
The type of the mesh file being read (should always be 0)
Definition at line 185 of file GmshMeshReader.hpp.
Referenced by GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::ReadHeaders().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> std::ifstream GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::mNodeFile [private]
A file stream used to read the node (and header) part of the file.
Definition at line 181 of file GmshMeshReader.hpp.
Referenced by GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::CloseFiles(), GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::GetNextNode(), GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::OpenFiles(), GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::ReadHeaders(), and GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::ReadNodeHeader().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> unsigned GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::mNodesPerBoundaryElement [private]
The number of nodes contained in each boundary element.
Definition at line 195 of file GmshMeshReader.hpp.
Referenced by GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::GetNextFaceData(), and GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::GmshMeshReader().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> unsigned GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::mNodesPerElement [private]
The number of nodes contained in each element.
Definition at line 194 of file GmshMeshReader.hpp.
Referenced by GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::GetNextElementData(), and GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::GmshMeshReader().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> unsigned GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::mNumElementAttributes [private]
Is the number of attributes stored for each element.
Definition at line 190 of file GmshMeshReader.hpp.
Referenced by GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::GetNextElementData(), and GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::GetNumElementAttributes().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> unsigned GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::mNumElements [private]
Number of elements in the mesh.
Definition at line 188 of file GmshMeshReader.hpp.
Referenced by GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::GetNumElements(), and GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::ReadElementHeader().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> unsigned GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::mNumFaceAttributes [private]
Is the number of attributes stored for each face.
Definition at line 191 of file GmshMeshReader.hpp.
Referenced by GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::GetNextFaceData(), and GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::GetNumFaceAttributes().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> unsigned GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::mNumFaces [private]
Number of faces in the mesh.
Definition at line 189 of file GmshMeshReader.hpp.
Referenced by GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::GetNumFaces(), and GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::ReadFaceHeader().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> unsigned GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::mNumNodes [private]
Number of nodes in the mesh.
Definition at line 187 of file GmshMeshReader.hpp.
Referenced by GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::GetNumNodes(), and GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::ReadNodeHeader().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> unsigned GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::mOrderOfBoundaryElements [private]
The order of each element (1 for linear, 2 for quadratic).
Definition at line 193 of file GmshMeshReader.hpp.
Referenced by GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::GetOrderOfBoundaryElements(), and GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::GmshMeshReader().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> unsigned GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::mOrderOfElements [private]
The order of each element (1 for linear, 2 for quadratic).
Definition at line 192 of file GmshMeshReader.hpp.
Referenced by GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::GetOrderOfElements(), and GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::GmshMeshReader().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> double GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::mVersionNumber [private]
The version number of the file.
Definition at line 184 of file GmshMeshReader.hpp.
Referenced by GmshMeshReader< ELEMENT_DIM, SPACE_DIM >::ReadHeaders().
The documentation for this class was generated from the following files:
mesh/src/reader/GmshMeshReader.hpp
mesh/src/reader/GmshMeshReader.cpp