Chaste: MeshalyzerMeshWriter< ELEMENT_DIM, SPACE_DIM > Class Template Reference
MeshalyzerMeshWriter< ELEMENT_DIM, SPACE_DIM > Class Template Reference
#include <MeshalyzerMeshWriter.hpp>
Inherits AbstractTetrahedralMeshWriter< ELEMENT_DIM, SPACE_DIM >.
Public Member Functions
MeshalyzerMeshWriter (const std::string &rDirectory, const std::string &rBaseName, const bool &rCleanDirectory=true, const bool &rSetCoolGraphics=false)
void WriteFiles ()
virtual ~MeshalyzerMeshWriter ()
Protected Member Functions
void CreateFilesWithHeaders ()
void AppendLocalDataToFiles ()
Private Member Functions
out_stream OpenNodeFile (bool append=false)
out_stream OpenElementFile (bool append=false)
out_stream OpenFaceFile (bool append=false)
void WriteMetaFile ()
void WriteFilesFooter ()
std::ios_base::openmode GetOpenMode (bool append)
Detailed Description
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM>
class MeshalyzerMeshWriter< ELEMENT_DIM, SPACE_DIM >
A concrete Meshalyzer mesh writer class.
Definition at line 46 of file MeshalyzerMeshWriter.hpp.
Constructor & Destructor Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> MeshalyzerMeshWriter< ELEMENT_DIM, SPACE_DIM >::MeshalyzerMeshWriter (const std::string & rDirectory, const std::string & rBaseName, const bool & rCleanDirectory = true, const bool & rSetCoolGraphics = false) [inline]
Constructor.
Parameters:
rDirectory the directory in which to write the mesh to file
rBaseName the base name of the files in which to write the mesh data
rCleanDirectory whether to clean the directory (defaults to true)
rSetCoolGraphics (defaults to false)
Definition at line 49 of file MeshalyzerMeshWriter.cpp.
References AbstractTetrahedralMeshWriter< ELEMENT_DIM, SPACE_DIM >::mIndexFromZero, and AbstractTetrahedralMeshWriter< ELEMENT_DIM, SPACE_DIM >::mWriteMetaFile.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> MeshalyzerMeshWriter< ELEMENT_DIM, SPACE_DIM >::~MeshalyzerMeshWriter () [inline, virtual]
Destructor.
Definition at line 189 of file MeshalyzerMeshWriter.cpp.
Member Function Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void MeshalyzerMeshWriter< ELEMENT_DIM, SPACE_DIM >::AppendLocalDataToFiles () [inline, protected, virtual]
Append local mesh data to output files.
Reimplemented from AbstractTetrahedralMeshWriter< ELEMENT_DIM, SPACE_DIM >.
Definition at line 308 of file MeshalyzerMeshWriter.cpp.
References AbstractTetrahedralMeshWriter< ELEMENT_DIM, SPACE_DIM >::mIndexFromZero, AbstractTetrahedralMeshWriter< ELEMENT_DIM, SPACE_DIM >::mNodesPerElement, AbstractTetrahedralMeshWriter< ELEMENT_DIM, SPACE_DIM >::mpDistributedMesh, MeshalyzerMeshWriter< ELEMENT_DIM, SPACE_DIM >::OpenElementFile(), MeshalyzerMeshWriter< ELEMENT_DIM, SPACE_DIM >::OpenFaceFile(), and MeshalyzerMeshWriter< ELEMENT_DIM, SPACE_DIM >::OpenNodeFile().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void MeshalyzerMeshWriter< ELEMENT_DIM, SPACE_DIM >::CreateFilesWithHeaders () [inline, protected, virtual]
Create output files and add headers.
Reimplemented from AbstractTetrahedralMeshWriter< ELEMENT_DIM, SPACE_DIM >.
Definition at line 263 of file MeshalyzerMeshWriter.cpp.
References AbstractMeshWriter< ELEMENT_DIM, SPACE_DIM >::GetNumBoundaryFaces(), AbstractMeshWriter< ELEMENT_DIM, SPACE_DIM >::GetNumElements(), AbstractMeshWriter< ELEMENT_DIM, SPACE_DIM >::GetNumNodes(), MeshalyzerMeshWriter< ELEMENT_DIM, SPACE_DIM >::OpenElementFile(), MeshalyzerMeshWriter< ELEMENT_DIM, SPACE_DIM >::OpenFaceFile(), MeshalyzerMeshWriter< ELEMENT_DIM, SPACE_DIM >::OpenNodeFile(), and MeshalyzerMeshWriter< ELEMENT_DIM, SPACE_DIM >::WriteMetaFile().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> std::ios_base::openmode MeshalyzerMeshWriter< ELEMENT_DIM, SPACE_DIM >::GetOpenMode (bool append) [inline, private]
Returns:
the mode to use when opening files.
Parameters:
append whether to append to the file, or overwrite it
Definition at line 213 of file MeshalyzerMeshWriter.cpp.
Referenced by MeshalyzerMeshWriter< ELEMENT_DIM, SPACE_DIM >::OpenElementFile(), MeshalyzerMeshWriter< ELEMENT_DIM, SPACE_DIM >::OpenFaceFile(), and MeshalyzerMeshWriter< ELEMENT_DIM, SPACE_DIM >::OpenNodeFile().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> out_stream MeshalyzerMeshWriter< ELEMENT_DIM, SPACE_DIM >::OpenElementFile (bool append = false) [inline, private]
Open the file element information is written to.
Returns:
file handler
Parameters:
append whether to append to the file, or overwrite it
Definition at line 235 of file MeshalyzerMeshWriter.cpp.
References MeshalyzerMeshWriter< ELEMENT_DIM, SPACE_DIM >::GetOpenMode(), AbstractMeshWriter< ELEMENT_DIM, SPACE_DIM >::mBaseName, AbstractMeshWriter< ELEMENT_DIM, SPACE_DIM >::mpOutputFileHandler, and OutputFileHandler::OpenOutputFile().
Referenced by MeshalyzerMeshWriter< ELEMENT_DIM, SPACE_DIM >::AppendLocalDataToFiles(), MeshalyzerMeshWriter< ELEMENT_DIM, SPACE_DIM >::CreateFilesWithHeaders(), MeshalyzerMeshWriter< ELEMENT_DIM, SPACE_DIM >::WriteFiles(), and MeshalyzerMeshWriter< ELEMENT_DIM, SPACE_DIM >::WriteFilesFooter().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> out_stream MeshalyzerMeshWriter< ELEMENT_DIM, SPACE_DIM >::OpenFaceFile (bool append = false) [inline, private]
Open the file face information is written to.
Returns:
file handler
Parameters:
append whether to append to the file, or overwrite it
Definition at line 256 of file MeshalyzerMeshWriter.cpp.
References MeshalyzerMeshWriter< ELEMENT_DIM, SPACE_DIM >::GetOpenMode(), AbstractMeshWriter< ELEMENT_DIM, SPACE_DIM >::mBaseName, AbstractMeshWriter< ELEMENT_DIM, SPACE_DIM >::mpOutputFileHandler, and OutputFileHandler::OpenOutputFile().
Referenced by MeshalyzerMeshWriter< ELEMENT_DIM, SPACE_DIM >::AppendLocalDataToFiles(), MeshalyzerMeshWriter< ELEMENT_DIM, SPACE_DIM >::CreateFilesWithHeaders(), MeshalyzerMeshWriter< ELEMENT_DIM, SPACE_DIM >::WriteFiles(), and MeshalyzerMeshWriter< ELEMENT_DIM, SPACE_DIM >::WriteFilesFooter().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> out_stream MeshalyzerMeshWriter< ELEMENT_DIM, SPACE_DIM >::OpenNodeFile (bool append = false) [inline, private]
Open the file node information is written to.
Returns:
file handler
Parameters:
append whether to append to the file, or overwrite it
Definition at line 228 of file MeshalyzerMeshWriter.cpp.
References MeshalyzerMeshWriter< ELEMENT_DIM, SPACE_DIM >::GetOpenMode(), AbstractMeshWriter< ELEMENT_DIM, SPACE_DIM >::mBaseName, AbstractMeshWriter< ELEMENT_DIM, SPACE_DIM >::mpOutputFileHandler, and OutputFileHandler::OpenOutputFile().
Referenced by MeshalyzerMeshWriter< ELEMENT_DIM, SPACE_DIM >::AppendLocalDataToFiles(), MeshalyzerMeshWriter< ELEMENT_DIM, SPACE_DIM >::CreateFilesWithHeaders(), MeshalyzerMeshWriter< ELEMENT_DIM, SPACE_DIM >::WriteFiles(), and MeshalyzerMeshWriter< ELEMENT_DIM, SPACE_DIM >::WriteFilesFooter().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void MeshalyzerMeshWriter< ELEMENT_DIM, SPACE_DIM >::WriteFiles () [inline, virtual]
Write mesh data to files.
Implements AbstractMeshWriter< ELEMENT_DIM, SPACE_DIM >.
Definition at line 73 of file MeshalyzerMeshWriter.cpp.
References ElementData::AttributeValue, AbstractTetrahedralMeshWriter< ELEMENT_DIM, SPACE_DIM >::GetNextBoundaryElement(), AbstractTetrahedralMeshWriter< ELEMENT_DIM, SPACE_DIM >::GetNextElement(), AbstractTetrahedralMeshWriter< ELEMENT_DIM, SPACE_DIM >::GetNextNode(), AbstractMeshWriter< ELEMENT_DIM, SPACE_DIM >::GetNumBoundaryFaces(), AbstractMeshWriter< ELEMENT_DIM, SPACE_DIM >::GetNumElements(), AbstractMeshWriter< ELEMENT_DIM, SPACE_DIM >::GetNumNodes(), ChasteBuildInfo::GetProvenanceString(), AbstractMeshWriter< ELEMENT_DIM, SPACE_DIM >::mBaseName, AbstractTetrahedralMeshWriter< ELEMENT_DIM, SPACE_DIM >::mIndexFromZero, ElementData::NodeIndices, MeshalyzerMeshWriter< ELEMENT_DIM, SPACE_DIM >::OpenElementFile(), MeshalyzerMeshWriter< ELEMENT_DIM, SPACE_DIM >::OpenFaceFile(), MeshalyzerMeshWriter< ELEMENT_DIM, SPACE_DIM >::OpenNodeFile(), and MeshalyzerMeshWriter< ELEMENT_DIM, SPACE_DIM >::WriteMetaFile().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void MeshalyzerMeshWriter< ELEMENT_DIM, SPACE_DIM >::WriteFilesFooter () [inline, private, virtual]
Append footers to output files.
Reimplemented from AbstractTetrahedralMeshWriter< ELEMENT_DIM, SPACE_DIM >.
Definition at line 395 of file MeshalyzerMeshWriter.cpp.
References ChasteBuildInfo::GetProvenanceString(), MeshalyzerMeshWriter< ELEMENT_DIM, SPACE_DIM >::OpenElementFile(), MeshalyzerMeshWriter< ELEMENT_DIM, SPACE_DIM >::OpenFaceFile(), and MeshalyzerMeshWriter< ELEMENT_DIM, SPACE_DIM >::OpenNodeFile().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void MeshalyzerMeshWriter< ELEMENT_DIM, SPACE_DIM >::WriteMetaFile () [inline, private]
Write the meta information file.
Definition at line 196 of file MeshalyzerMeshWriter.cpp.
References ChasteBuildInfo::GetProvenanceString(), AbstractMeshWriter< ELEMENT_DIM, SPACE_DIM >::mBaseName, AbstractMeshWriter< ELEMENT_DIM, SPACE_DIM >::mpOutputFileHandler, AbstractTetrahedralMeshWriter< ELEMENT_DIM, SPACE_DIM >::mWriteMetaFile, and OutputFileHandler::OpenOutputFile().
Referenced by MeshalyzerMeshWriter< ELEMENT_DIM, SPACE_DIM >::CreateFilesWithHeaders(), and MeshalyzerMeshWriter< ELEMENT_DIM, SPACE_DIM >::WriteFiles().
The documentation for this class was generated from the following files:
mesh/src/writer/MeshalyzerMeshWriter.hpp
mesh/src/writer/MeshalyzerMeshWriter.cpp