Chaste: BoundaryNodeWriter< ELEMENT_DIM, SPACE_DIM > Class Template Reference
BoundaryNodeWriter< ELEMENT_DIM, SPACE_DIM > Class Template Reference
#include <BoundaryNodeWriter.hpp>
Inherits AbstractCellPopulationWriter< ELEMENT_DIM, SPACE_DIM >.
Public Member Functions
BoundaryNodeWriter ()
void VisitAnyPopulation (AbstractCellPopulation< SPACE_DIM, SPACE_DIM > *pCellPopulation)
virtual void Visit (MeshBasedCellPopulation< ELEMENT_DIM, SPACE_DIM > *pCellPopulation)
virtual void Visit (CaBasedCellPopulation< SPACE_DIM > *pCellPopulation)
virtual void Visit (NodeBasedCellPopulation< SPACE_DIM > *pCellPopulation)
virtual void Visit (PottsBasedCellPopulation< SPACE_DIM > *pCellPopulation)
virtual void Visit (VertexBasedCellPopulation< SPACE_DIM > *pCellPopulation)
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Friends
class boost::serialization::access
Detailed Description
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM>
class BoundaryNodeWriter< ELEMENT_DIM, SPACE_DIM >
A class written using the visitor pattern for writing the boundary nodes of a population to file.
Definition at line 45 of file BoundaryNodeWriter.hpp.
Constructor & Destructor Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> BoundaryNodeWriter< ELEMENT_DIM, SPACE_DIM >::BoundaryNodeWriter () [inline]
Default constructor.
Definition at line 45 of file BoundaryNodeWriter.cpp.
Member Function Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> template<class Archive > void BoundaryNodeWriter< ELEMENT_DIM, SPACE_DIM >::serialize (Archive & archive, const unsigned int version) [inline, private]
Serialize the object and its member variables.
Parameters:
archive the archive
version the current version of this class
Reimplemented from AbstractCellPopulationWriter< ELEMENT_DIM, SPACE_DIM >.
Definition at line 57 of file BoundaryNodeWriter.hpp.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void BoundaryNodeWriter< ELEMENT_DIM, SPACE_DIM >::Visit (VertexBasedCellPopulation< SPACE_DIM > * pCellPopulation) [inline, virtual]
Visit the population and write whether each node is a boundary node.
Outputs a line of space-separated values of the form: [node 0 is boundary node] [node 1 is boundary node] ...
where [node 0 is boundary node] is 1 if node 0 is a boundary node and 0 if it is not, and so on. Here the indexing of nodes is as given by the NodeIterator.
This line is appended to the output written by AbstractCellBasedWriter, which is a single value [present simulation time], followed by a tab.
Parameters:
pCellPopulation a pointer to the VertexBasedCellPopulation to visit.
Implements AbstractCellPopulationWriter< ELEMENT_DIM, SPACE_DIM >.
Definition at line 97 of file BoundaryNodeWriter.cpp.
References BoundaryNodeWriter< ELEMENT_DIM, SPACE_DIM >::VisitAnyPopulation().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void BoundaryNodeWriter< ELEMENT_DIM, SPACE_DIM >::Visit (PottsBasedCellPopulation< SPACE_DIM > * pCellPopulation) [inline, virtual]
Visit the population and write whether each node is a boundary node.
Outputs a line of space-separated values of the form: [node 0 is boundary node] [node 1 is boundary node] ...
where [node 0 is boundary node] is 1 if node 0 is a boundary node and 0 if it is not, and so on. Here the indexing of nodes is as given by the NodeIterator.
This line is appended to the output written by AbstractCellBasedWriter, which is a single value [present simulation time], followed by a tab.
Parameters:
pCellPopulation a pointer to the PottsBasedCellPopulation to visit.
Implements AbstractCellPopulationWriter< ELEMENT_DIM, SPACE_DIM >.
Definition at line 91 of file BoundaryNodeWriter.cpp.
References BoundaryNodeWriter< ELEMENT_DIM, SPACE_DIM >::VisitAnyPopulation().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void BoundaryNodeWriter< ELEMENT_DIM, SPACE_DIM >::Visit (NodeBasedCellPopulation< SPACE_DIM > * pCellPopulation) [inline, virtual]
Visit the population and write whether each node is a boundary node.
Outputs a line of space-separated values of the form: [node 0 is boundary node] [node 1 is boundary node] ...
where [node 0 is boundary node] is 1 if node 0 is a boundary node and 0 if it is not, and so on. Here the indexing of nodes is as given by the NodeIterator.
This line is appended to the output written by AbstractCellBasedWriter, which is a single value [present simulation time], followed by a tab.
Parameters:
pCellPopulation a pointer to the NodeBasedCellPopulation to visit.
Implements AbstractCellPopulationWriter< ELEMENT_DIM, SPACE_DIM >.
Definition at line 85 of file BoundaryNodeWriter.cpp.
References BoundaryNodeWriter< ELEMENT_DIM, SPACE_DIM >::VisitAnyPopulation().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void BoundaryNodeWriter< ELEMENT_DIM, SPACE_DIM >::Visit (CaBasedCellPopulation< SPACE_DIM > * pCellPopulation) [inline, virtual]
Visit the population and write whether each node is a boundary node.
Outputs a line of space-separated values of the form: [node 0 is boundary node] [node 1 is boundary node] ...
where [node 0 is boundary node] is 1 if node 0 is a boundary node and 0 if it is not, and so on. Here the indexing of nodes is as given by the NodeIterator.
This line is appended to the output written by AbstractCellBasedWriter, which is a single value [present simulation time], followed by a tab.
Parameters:
pCellPopulation a pointer to the CaBasedCellPopulation to visit.
Implements AbstractCellPopulationWriter< ELEMENT_DIM, SPACE_DIM >.
Definition at line 79 of file BoundaryNodeWriter.cpp.
References BoundaryNodeWriter< ELEMENT_DIM, SPACE_DIM >::VisitAnyPopulation().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void BoundaryNodeWriter< ELEMENT_DIM, SPACE_DIM >::Visit (MeshBasedCellPopulation< ELEMENT_DIM, SPACE_DIM > * pCellPopulation) [inline, virtual]
Visit the population and write whether each node is a boundary node.
Outputs a line of space-separated values of the form: [node 0 is boundary node] [node 1 is boundary node] ...
where [node 0 is boundary node] is 1 if node 0 is a boundary node and 0 if it is not, and so on. Here the indexing of nodes is as given by the NodeIterator.
This line is appended to the output written by AbstractCellBasedWriter, which is a single value [present simulation time], followed by a tab.
Parameters:
pCellPopulation a pointer to the MeshBasedCellPopulation to visit.
Implements AbstractCellPopulationWriter< ELEMENT_DIM, SPACE_DIM >.
Definition at line 65 of file BoundaryNodeWriter.cpp.
References AbstractCellBasedWriter< ELEMENT_DIM, SPACE_DIM >::mpOutStream, and MeshBasedCellPopulation< ELEMENT_DIM, SPACE_DIM >::rGetMesh().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void BoundaryNodeWriter< ELEMENT_DIM, SPACE_DIM >::VisitAnyPopulation (AbstractCellPopulation< SPACE_DIM, SPACE_DIM > * pCellPopulation) [inline]
Visit the population and write the data.
Parameters:
pCellPopulation a pointer to the population to visit.
Definition at line 51 of file BoundaryNodeWriter.cpp.
References AbstractCellBasedWriter< ELEMENT_DIM, SPACE_DIM >::mpOutStream, and AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::rGetMesh().
Referenced by BoundaryNodeWriter< ELEMENT_DIM, SPACE_DIM >::Visit().
Friends And Related Function Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> friend class boost::serialization::access [friend]
Needed for serialization.
Reimplemented from AbstractCellPopulationWriter< ELEMENT_DIM, SPACE_DIM >.
Definition at line 49 of file BoundaryNodeWriter.hpp.
The documentation for this class was generated from the following files:
cell_based/src/population/writers/population_writers/BoundaryNodeWriter.hpp
cell_based/src/population/writers/population_writers/BoundaryNodeWriter.cpp