Chaste: boost::random::normal_distribution_v156< RealType > Class Template Reference
boost::random::normal_distribution_v156< RealType > Class Template Reference
#include <Boost156NormalDistribution.hpp>
Classes
class param_type
Public Types
typedef RealType input_type
typedef RealType result_type
Public Member Functions
normal_distribution_v156 (boost::mt19937 &engine_arg, const RealType &mean_arg=RealType(0.0), const RealType &sigma_arg=RealType(1.0))
normal_distribution_v156 (const param_type &parm)
RealType mean () const
RealType sigma () const
RealType min BOOST_PREVENT_MACRO_SUBSTITUTION () const
RealType max BOOST_PREVENT_MACRO_SUBSTITUTION () const
param_type param () const
void param (const param_type &parm)
void reset ()
template<class Engine >
result_type operator() (Engine &eng)
template<class URNG >
result_type operator() (URNG &urng, const param_type &parm)
BOOST_RANDOM_DETAIL_OSTREAM_OPERATOR (os, normal_distribution_v156, nd)
BOOST_RANDOM_DETAIL_ISTREAM_OPERATOR (is, normal_distribution_v156, nd)
BOOST_RANDOM_DETAIL_EQUALITY_OPERATOR (normal_distribution_v156, lhs, rhs)
Private Attributes
RealType _mean
RealType _sigma
boost::mt19937 & _engine
Detailed Description
template<class RealType = double>
class boost::random::normal_distribution_v156< RealType >
Instantiations of class template normal_distribution_v156 model a . Such a distribution produces random numbers x distributed with probability density function , where mean and sigma are the parameters of the distribution.
Definition at line 397 of file Boost156NormalDistribution.hpp.
Constructor & Destructor Documentation
template<class RealType = double> boost::random::normal_distribution_v156< RealType >::normal_distribution_v156 (boost::mt19937 & engine_arg, const RealType & mean_arg = RealType(0.0), const RealType & sigma_arg = RealType(1.0)) [inline, explicit]
Constructs a normal_distribution_v156 object. mean and sigma are the parameters for the distribution.
Requires: sigma >= 0
Definition at line 451 of file Boost156NormalDistribution.hpp.
Referenced by boost::random::normal_distribution_v156< RealType >::operator()().
template<class RealType = double> boost::random::normal_distribution_v156< RealType >::normal_distribution_v156 (const param_type & parm) [inline, explicit]
Constructs a normal_distribution_v156 object from its parameters.
Definition at line 463 of file Boost156NormalDistribution.hpp.
Member Function Documentation
template<class RealType = double> RealType max boost::random::normal_distribution_v156< RealType >::BOOST_PREVENT_MACRO_SUBSTITUTION () const [inline]
Returns the largest value that the distribution can produce.
Definition at line 476 of file Boost156NormalDistribution.hpp.
template<class RealType = double> RealType min boost::random::normal_distribution_v156< RealType >::BOOST_PREVENT_MACRO_SUBSTITUTION () const [inline]
Returns the smallest value that the distribution can produce.
Definition at line 473 of file Boost156NormalDistribution.hpp.
template<class RealType = double> boost::random::normal_distribution_v156< RealType >::BOOST_RANDOM_DETAIL_EQUALITY_OPERATOR (normal_distribution_v156< RealType > , lhs , rhs) [inline]
Returns true if the two instances of normal_distribution_v156 will return identical sequences of values given equal generators.
Definition at line 531 of file Boost156NormalDistribution.hpp.
template<class RealType = double> boost::random::normal_distribution_v156< RealType >::BOOST_RANDOM_DETAIL_ISTREAM_OPERATOR (is , normal_distribution_v156< RealType > , nd) [inline]
Reads a normal_distribution_v156 from a std::istream.
Definition at line 521 of file Boost156NormalDistribution.hpp.
template<class RealType = double> boost::random::normal_distribution_v156< RealType >::BOOST_RANDOM_DETAIL_OSTREAM_OPERATOR (os , normal_distribution_v156< RealType > , nd) [inline]
Writes a normal_distribution_v156 to a std::ostream.
Definition at line 514 of file Boost156NormalDistribution.hpp.
template<class RealType = double> RealType boost::random::normal_distribution_v156< RealType >::mean () const [inline]
Returns the mean of the distribution.
Definition at line 468 of file Boost156NormalDistribution.hpp.
References boost::random::normal_distribution_v156< RealType >::param_type::_mean.
template<class RealType = double> template<class URNG > result_type boost::random::normal_distribution_v156< RealType >::operator() (URNG & urng, const param_type & parm) [inline]
Returns a normal variate with parameters specified by param.
Definition at line 508 of file Boost156NormalDistribution.hpp.
References boost::random::normal_distribution_v156< RealType >::normal_distribution_v156().
template<class RealType = double> template<class Engine > result_type boost::random::normal_distribution_v156< RealType >::operator() (Engine & eng) [inline]
Returns a normal variate.
Definition at line 496 of file Boost156NormalDistribution.hpp.
References boost::random::normal_distribution_v156< RealType >::param_type::_mean.
template<class RealType = double> void boost::random::normal_distribution_v156< RealType >::param (const param_type & parm) [inline]
Sets the parameters of the distribution.
Definition at line 482 of file Boost156NormalDistribution.hpp.
References boost::random::normal_distribution_v156< RealType >::param_type::_mean, boost::random::normal_distribution_v156< RealType >::param_type::mean(), and boost::random::normal_distribution_v156< RealType >::param_type::sigma().
template<class RealType = double> param_type boost::random::normal_distribution_v156< RealType >::param () const [inline]
Returns the parameters of the distribution.
Definition at line 480 of file Boost156NormalDistribution.hpp.
References boost::random::normal_distribution_v156< RealType >::param_type::_mean, and boost::random::normal_distribution_v156< RealType >::param_type::param_type().
template<class RealType = double> void boost::random::normal_distribution_v156< RealType >::reset () [inline]
Effects: Subsequent uses of the distribution do not depend on values produced by any engine prior to invoking reset.
Definition at line 492 of file Boost156NormalDistribution.hpp.
template<class RealType = double> RealType boost::random::normal_distribution_v156< RealType >::sigma () const [inline]
Returns the standard deviation of the distribution.
Definition at line 470 of file Boost156NormalDistribution.hpp.
Member Data Documentation
template<class RealType = double> RealType boost::random::normal_distribution_v156< RealType >::_mean [private]
Returns true if the two instances of normal_distribution_v156 will return different sequences of values given equal generators.
Definition at line 543 of file Boost156NormalDistribution.hpp.
The documentation for this class was generated from the following file:
global/src/Boost156NormalDistribution.hpp