Chaste: DeltaNotchCellCycleModel Class Reference
DeltaNotchCellCycleModel Class Reference
#include <DeltaNotchCellCycleModel.hpp>
Inherits StochasticDurationGenerationBasedCellCycleModel, and CellCycleModelOdeHandler.
Public Member Functions
DeltaNotchCellCycleModel (boost::shared_ptr< AbstractCellCycleModelOdeSolver > pOdeSolver=boost::shared_ptr< AbstractCellCycleModelOdeSolver >())
AbstractCellCycleModel * CreateCellCycleModel ()
void Initialise ()
void SetInitialConditions (std::vector< double > initialConditions)
void UpdateCellCyclePhase ()
void UpdateDeltaNotch ()
double GetNotch ()
double GetDelta ()
double GetMeanNeighbouringDelta ()
virtual void OutputCellCycleModelParameters (out_stream &rParamsFile)
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Private Attributes
std::vector< double > mInitialConditions
Friends
class boost::serialization::access
Detailed Description
A subclass of StochasticDurationGenerationBasedCellCycleModel that includes a Delta-Notch ODE system.
For another example of a cell cycle model that is not *based on* an ODE system, but that includes an ODE system, see SingleOdeWntCellCycleModel (in Crypt).
Definition at line 55 of file DeltaNotchCellCycleModel.hpp.
Constructor & Destructor Documentation
DeltaNotchCellCycleModel::DeltaNotchCellCycleModel (boost::shared_ptr< AbstractCellCycleModelOdeSolver > pOdeSolver = boost::shared_ptr<AbstractCellCycleModelOdeSolver>())
Default constructor calls base class.
Parameters:
pOdeSolver An optional pointer to a cell-cycle model ODE solver object (allows the use of different ODE solvers)
Definition at line 44 of file DeltaNotchCellCycleModel.cpp.
References CellCycleModelOdeHandler::mpOdeSolver, and CellCycleModelOdeHandler::SetDt().
Referenced by CreateCellCycleModel().
Member Function Documentation
AbstractCellCycleModel * DeltaNotchCellCycleModel::CreateCellCycleModel () [virtual]
Overridden builder method to create new copies of this cell-cycle model.
Returns:
Returns a copy of the current cell cycle model.
Reimplemented from StochasticDurationGenerationBasedCellCycleModel.
Definition at line 62 of file DeltaNotchCellCycleModel.cpp.
References DeltaNotchCellCycleModel(), GetMeanNeighbouringDelta(), CellCycleModelOdeHandler::GetOdeSystem(), AbstractCellCycleModel::mBirthTime, AbstractCellCycleModel::mDimension, AbstractSimpleGenerationBasedCellCycleModel::mGeneration, CellCycleModelOdeHandler::mLastTime, AbstractSimpleGenerationBasedCellCycleModel::mMaxTransitGenerations, CellCycleModelOdeHandler::mpOdeSolver, CellCycleModelOdeHandler::mpOdeSystem, AbstractParameterisedSystem< VECTOR >::rGetStateVariables(), AbstractCellCycleModel::SetBirthTime(), AbstractCellCycleModel::SetDimension(), AbstractSimpleGenerationBasedCellCycleModel::SetGeneration(), CellCycleModelOdeHandler::SetLastTime(), AbstractSimpleGenerationBasedCellCycleModel::SetMaxTransitGenerations(), CellCycleModelOdeHandler::SetOdeSystem(), AbstractParameterisedSystem< VECTOR >::SetParameter(), and CellCycleModelOdeHandler::SetStateVariables().
double DeltaNotchCellCycleModel::GetDelta ()
Returns:
Returns the current Delta level in this cell.
Definition at line 137 of file DeltaNotchCellCycleModel.cpp.
References CellCycleModelOdeHandler::mpOdeSystem, and AbstractParameterisedSystem< VECTOR >::rGetStateVariables().
Referenced by DeltaNotchTrackingModifier< DIM >::UpdateCellData().
double DeltaNotchCellCycleModel::GetMeanNeighbouringDelta ()
Returns:
Get the current level of Delta neighbouring the cell.
Definition at line 144 of file DeltaNotchCellCycleModel.cpp.
References AbstractParameterisedSystem< VECTOR >::GetParameter(), and CellCycleModelOdeHandler::mpOdeSystem.
Referenced by CreateCellCycleModel().
double DeltaNotchCellCycleModel::GetNotch ()
Returns:
Returns the current Notch level in this cell.
Definition at line 130 of file DeltaNotchCellCycleModel.cpp.
References CellCycleModelOdeHandler::mpOdeSystem, and AbstractParameterisedSystem< VECTOR >::rGetStateVariables().
Referenced by DeltaNotchTrackingModifier< DIM >::UpdateCellData().
void DeltaNotchCellCycleModel::Initialise (void) [virtual]
Initialise the cell-cycle model at the start of a simulation.
This overridden method sets up a new Delta-Notch ODE system.
Reimplemented from AbstractSimpleCellCycleModel.
Definition at line 94 of file DeltaNotchCellCycleModel.cpp.
References AbstractParameterisedSystem< VECTOR >::GetInitialConditions(), AbstractCellCycleModel::mBirthTime, mInitialConditions, AbstractCellCycleModel::mpCell, CellCycleModelOdeHandler::mpOdeSystem, CellCycleModelOdeHandler::SetLastTime(), and AbstractParameterisedSystem< VECTOR >::SetStateVariables().
void DeltaNotchCellCycleModel::OutputCellCycleModelParameters (out_stream & rParamsFile) [virtual]
Outputs cell-cycle model parameters to file.
Parameters:
rParamsFile the file stream to which the parameters are output
Reimplemented from StochasticDurationGenerationBasedCellCycleModel.
Definition at line 151 of file DeltaNotchCellCycleModel.cpp.
template<class Archive > void DeltaNotchCellCycleModel::serialize (Archive & archive, const unsigned int version) [inline, private]
Archive the cell-cycle model and member variables.
Parameters:
archive the archive
version the current version of this class
Reimplemented from CellCycleModelOdeHandler.
Definition at line 68 of file DeltaNotchCellCycleModel.hpp.
void DeltaNotchCellCycleModel::SetInitialConditions (std::vector< double > initialConditions)
Set the initial conditions for delta, notch, mean_delta.
Parameters:
initialConditions are the initial conditions
Definition at line 115 of file DeltaNotchCellCycleModel.cpp.
References mInitialConditions.
void DeltaNotchCellCycleModel::UpdateCellCyclePhase () [virtual]
Overridden UpdateCellCyclePhase() method.
Reimplemented from AbstractSimpleCellCycleModel.
Definition at line 86 of file DeltaNotchCellCycleModel.cpp.
References SimulationTime::Instance(), CellCycleModelOdeHandler::SolveOdeToTime(), and UpdateDeltaNotch().
void DeltaNotchCellCycleModel::UpdateDeltaNotch ()
Update the current levels of Delta and Notch in the cell.
Definition at line 121 of file DeltaNotchCellCycleModel.cpp.
References AbstractCellCycleModel::mpCell, CellCycleModelOdeHandler::mpOdeSystem, and AbstractParameterisedSystem< VECTOR >::SetParameter().
Referenced by UpdateCellCyclePhase().
Friends And Related Function Documentation
friend class boost::serialization::access [friend]
Needed for serialization.
Reimplemented from CellCycleModelOdeHandler.
Definition at line 60 of file DeltaNotchCellCycleModel.hpp.
Member Data Documentation
std::vector<double> DeltaNotchCellCycleModel::mInitialConditions [private]
The initial condition for delta, notch, mean_delta
Definition at line 77 of file DeltaNotchCellCycleModel.hpp.
Referenced by Initialise(), and SetInitialConditions().
The documentation for this class was generated from the following files:
cell_based/src/population/cell/cycle/DeltaNotchCellCycleModel.hpp
cell_based/src/population/cell/cycle/DeltaNotchCellCycleModel.cpp