Chaste: PseudoEcgCalculator< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM > Class Template Reference
PseudoEcgCalculator< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM > Class Template Reference
#include <PseudoEcgCalculator.hpp>
Inherits AbstractFunctionalCalculator< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >.
Public Member Functions
PseudoEcgCalculator (AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM > &rMesh, const ChastePoint< SPACE_DIM > &rProbeElectrode, const FileFinder &rDirectory, std::string hdf5File, std::string variableName="V", unsigned timestepStride=1)
~PseudoEcgCalculator ()
void SetDiffusionCoefficient (double diffusionCoefficient)
void WritePseudoEcg ()
Private Member Functions
double GetIntegrand (ChastePoint< SPACE_DIM > &rX, c_vector< double, PROBLEM_DIM > &rU, c_matrix< double, PROBLEM_DIM, SPACE_DIM > &rGradU)
double ComputePseudoEcgAtOneTimeStep (unsigned timeStep)
bool ShouldSkipThisElement (Element< ELEMENT_DIM, SPACE_DIM > &rElement)
Private Attributes
Hdf5DataReader * mpDataReader
unsigned mNumberOfNodes
unsigned mNumTimeSteps
AbstractTetrahedralMesh
< ELEMENT_DIM, SPACE_DIM > & mrMesh
ChastePoint< SPACE_DIM > mProbeElectrode
double mDiffusionCoefficient
std::string mVariableName
unsigned mTimestepStride
Friends
class TestPseudoEcgCalculator
Detailed Description
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM, unsigned PROBLEM_DIM>
class PseudoEcgCalculator< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >
This class implements a pseudo-ECG calculator. It is a concrete class of AbstractFunctionalCalculator. The pseudo-ECG is defined as the integral over the mesh of the following integrand:
D * grad (solution) dot grad (1/r)
where D is a diffusion coefficient and r is the distance between a recording electrode and a given point in the mesh.
References for the formula that defines the pseudo-ECG:
Gima K, Rudy Y Circ Res (2002) 90:889-896 (equation 1) Baher et al. Am J Physiol (2007) 292:H180-H189 (equation 5)
Definition at line 71 of file PseudoEcgCalculator.hpp.
Constructor & Destructor Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM, unsigned PROBLEM_DIM> PseudoEcgCalculator< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::PseudoEcgCalculator (AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM > & rMesh, const ChastePoint< SPACE_DIM > & rProbeElectrode, const FileFinder & rDirectory, std::string hdf5File, std::string variableName = "V", unsigned timestepStride = 1) [inline]
Constructor
Parameters:
rMesh A reference to the mesh
rProbeElectrode The location of the recording electrode
rDirectory The directory where the simulation results are stored
hdf5File The file name where the simulation results are stored
variableName The name of the voltage variable (is V by default)
timestepStride The number of timesteps in a stride (so that we don't have to compute all the ECGs). This defaults to 1.
Definition at line 62 of file PseudoEcgCalculator.cpp.
References Hdf5DataReader::GetNumberOfRows(), Hdf5DataReader::GetVariableOverTime(), PseudoEcgCalculator< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::mDiffusionCoefficient, PseudoEcgCalculator< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::mNumberOfNodes, PseudoEcgCalculator< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::mNumTimeSteps, PseudoEcgCalculator< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::mpDataReader, PseudoEcgCalculator< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::mrMesh, and PseudoEcgCalculator< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::mVariableName.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM, unsigned PROBLEM_DIM> PseudoEcgCalculator< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::~PseudoEcgCalculator () [inline]
Destructor.
Definition at line 94 of file PseudoEcgCalculator.cpp.
References PseudoEcgCalculator< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::mpDataReader.
Member Function Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM, unsigned PROBLEM_DIM> double PseudoEcgCalculator< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::ComputePseudoEcgAtOneTimeStep (unsigned timeStep) [inline, private]
Calculates the pseudo-ECG and returns its value at the given time step.
Parameters:
timeStep the time step where we want to calculate the pseudo-ecg
Returns:
the pseudo ECG at the given time step.
Definition at line 107 of file PseudoEcgCalculator.cpp.
References AbstractFunctionalCalculator< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::Calculate(), PetscTools::CreateVec(), PetscTools::Destroy(), Hdf5DataReader::GetVariableOverNodes(), PseudoEcgCalculator< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::mNumberOfNodes, PseudoEcgCalculator< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::mpDataReader, PseudoEcgCalculator< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::mrMesh, and PseudoEcgCalculator< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::mVariableName.
Referenced by PseudoEcgCalculator< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::WritePseudoEcg().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM, unsigned PROBLEM_DIM> double PseudoEcgCalculator< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::GetIntegrand (ChastePoint< SPACE_DIM > & rX, c_vector< double, PROBLEM_DIM > & rU, c_matrix< double, PROBLEM_DIM, SPACE_DIM > & rGradU) [inline, private, virtual]
Returns:
the integrand. The pseudo-ECG is defined as the integral over the mesh of the following integrand:
D * grad (solution) dot grad (1/r)
Parameters:
rX The point in space
rU The unknown as a vector, u(i) = u_i
rGradU The gradient of the unknown as a matrix, rGradU(i,j) = d(u_i)/d(X_j)
Implements AbstractFunctionalCalculator< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >.
Definition at line 44 of file PseudoEcgCalculator.cpp.
References EXCEPTION, PseudoEcgCalculator< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::mDiffusionCoefficient, PseudoEcgCalculator< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::mProbeElectrode, and ChastePoint< DIM >::rGetLocation().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM, unsigned PROBLEM_DIM> void PseudoEcgCalculator< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::SetDiffusionCoefficient (double diffusionCoefficient) [inline]
Sets the value of the diffusion coefficient (D)
Parameters:
diffusionCoefficient The desired value of the diffusion coefficient
Definition at line 100 of file PseudoEcgCalculator.cpp.
References PseudoEcgCalculator< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::mDiffusionCoefficient.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM, unsigned PROBLEM_DIM> bool PseudoEcgCalculator< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::ShouldSkipThisElement (Element< ELEMENT_DIM, SPACE_DIM > & rElement) [inline, private, virtual]
Whether we should not calculate the Pseudo ECG on this element.
This method returns true if we are integrating voltage and the tissue element is in the bath.
Parameters:
rElement the element of interest
Returns:
whether we should skip this element.
Reimplemented from AbstractFunctionalCalculator< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >.
Definition at line 82 of file PseudoEcgCalculator.cpp.
References AbstractElement< ELEMENT_DIM, SPACE_DIM >::GetUnsignedAttribute(), HeartRegionCode::IsRegionBath(), and PseudoEcgCalculator< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::mVariableName.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM, unsigned PROBLEM_DIM> void PseudoEcgCalculator< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::WritePseudoEcg () [inline]
Calculates and writes the pseudo-ECG to file. the file will be named PseudoEcgFromElectrodeAt_x_y_z.dat, where x,y,z are replaced by the location of the electrode. It will contain one column of numbers, each being the pseudoECG at each time step. It will be created by the master processor into /output relaitive to where the output directory is set (by the HeartConfig or by default)
Definition at line 127 of file PseudoEcgCalculator.cpp.
References PetscTools::AmMaster(), PseudoEcgCalculator< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::ComputePseudoEcgAtOneTimeStep(), ChasteBuildInfo::GetProvenanceString(), Hdf5DataReader::GetUnlimitedDimensionValues(), ChastePoint< DIM >::GetWithDefault(), HeartConfig::Instance(), PseudoEcgCalculator< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::mNumTimeSteps, PseudoEcgCalculator< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::mpDataReader, PseudoEcgCalculator< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::mProbeElectrode, PseudoEcgCalculator< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::mTimestepStride, and OutputFileHandler::OpenOutputFile().
Referenced by PostProcessingWriter< ELEMENT_DIM, SPACE_DIM >::WritePostProcessingFiles().
Member Data Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM, unsigned PROBLEM_DIM> double PseudoEcgCalculator< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::mDiffusionCoefficient [private]
The diffusion coefficient D
Definition at line 82 of file PseudoEcgCalculator.hpp.
Referenced by PseudoEcgCalculator< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::GetIntegrand(), PseudoEcgCalculator< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::PseudoEcgCalculator(), and PseudoEcgCalculator< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::SetDiffusionCoefficient().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM, unsigned PROBLEM_DIM> unsigned PseudoEcgCalculator< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::mNumberOfNodes [private]
Number of nodes in the mesh (got from the data reader)
Definition at line 78 of file PseudoEcgCalculator.hpp.
Referenced by PseudoEcgCalculator< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::ComputePseudoEcgAtOneTimeStep(), and PseudoEcgCalculator< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::PseudoEcgCalculator().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM, unsigned PROBLEM_DIM> unsigned PseudoEcgCalculator< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::mNumTimeSteps [private]
Number of time steps in the simulation (got from the data reader)
Definition at line 79 of file PseudoEcgCalculator.hpp.
Referenced by PseudoEcgCalculator< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::PseudoEcgCalculator(), and PseudoEcgCalculator< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::WritePseudoEcg().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM, unsigned PROBLEM_DIM> Hdf5DataReader* PseudoEcgCalculator< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::mpDataReader [private]
An HDF5 reader from which to get the solution
Definition at line 77 of file PseudoEcgCalculator.hpp.
Referenced by PseudoEcgCalculator< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::ComputePseudoEcgAtOneTimeStep(), PseudoEcgCalculator< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::PseudoEcgCalculator(), PseudoEcgCalculator< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::WritePseudoEcg(), and PseudoEcgCalculator< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::~PseudoEcgCalculator().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM, unsigned PROBLEM_DIM> ChastePoint<SPACE_DIM> PseudoEcgCalculator< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::mProbeElectrode [private]
The point from where we want to calculate the pseudoECG
Definition at line 81 of file PseudoEcgCalculator.hpp.
Referenced by PseudoEcgCalculator< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::GetIntegrand(), and PseudoEcgCalculator< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::WritePseudoEcg().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM, unsigned PROBLEM_DIM> AbstractTetrahedralMesh<ELEMENT_DIM,SPACE_DIM>& PseudoEcgCalculator< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::mrMesh [private]
A mesh used by the calculator
Definition at line 80 of file PseudoEcgCalculator.hpp.
Referenced by PseudoEcgCalculator< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::ComputePseudoEcgAtOneTimeStep(), and PseudoEcgCalculator< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::PseudoEcgCalculator().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM, unsigned PROBLEM_DIM> unsigned PseudoEcgCalculator< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::mTimestepStride [private]
The number of timesteps in a stride (so that we don't have to compute all the ECGs). This defaults to 1.
Definition at line 84 of file PseudoEcgCalculator.hpp.
Referenced by PseudoEcgCalculator< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::WritePseudoEcg().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM, unsigned PROBLEM_DIM> std::string PseudoEcgCalculator< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::mVariableName [private]
the variable for which we want to calculate the pseudo ecg, defaults to "V"
Definition at line 83 of file PseudoEcgCalculator.hpp.
Referenced by PseudoEcgCalculator< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::ComputePseudoEcgAtOneTimeStep(), PseudoEcgCalculator< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::PseudoEcgCalculator(), and PseudoEcgCalculator< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::ShouldSkipThisElement().
The documentation for this class was generated from the following files:
heart/src/postprocessing/PseudoEcgCalculator.hpp
heart/src/postprocessing/PseudoEcgCalculator.cpp