Chaste: AveragedSourcePde< DIM > Class Template Reference
AveragedSourcePde< DIM > Class Template Reference
#include <AveragedSourcePde.hpp>
Inherits AbstractLinearEllipticPde< DIM, DIM >.
Inherited by VolumeDependentAveragedSourcePde< DIM >.
Public Member Functions
AveragedSourcePde (AbstractCellPopulation< DIM > &rCellPopulation, double coefficient=0.0)
const AbstractCellPopulation
< DIM > & rGetCellPopulation () const
double GetCoefficient () const
virtual void SetupSourceTerms (TetrahedralMesh< DIM, DIM > &rCoarseMesh, std::map< CellPtr, unsigned > *pCellPdeElementMap=NULL)
double ComputeConstantInUSourceTerm (const ChastePoint< DIM > &rX, Element< DIM, DIM > *pElement)
double ComputeLinearInUCoeffInSourceTerm (const ChastePoint< DIM > &rX, Element< DIM, DIM > *pElement)
c_matrix< double, DIM, DIM > ComputeDiffusionTerm (const ChastePoint< DIM > &rX)
double GetUptakeRateForElement (unsigned elementIndex)
Protected Attributes
AbstractCellPopulation< DIM > & mrCellPopulation
double mCoefficient
std::vector< double > mCellDensityOnCoarseElements
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Friends
class TestCellBasedPdes
class boost::serialization::access
Detailed Description
template<unsigned DIM>
class AveragedSourcePde< DIM >
A PDE which calculates the source term by adding the number of cells in the element containing that point and scaling by the element area.
Definition at line 52 of file AveragedSourcePde.hpp.
Constructor & Destructor Documentation
template<unsigned DIM> AveragedSourcePde< DIM >::AveragedSourcePde (AbstractCellPopulation< DIM > & rCellPopulation, double coefficient = 0.0) [inline]
Constructor.
Parameters:
rCellPopulation reference to the cell population
coefficient the coefficient of consumption of nutrient by cells (defaults to 0.0)
Definition at line 41 of file AveragedSourcePde.cpp.
Member Function Documentation
template<unsigned DIM> double AveragedSourcePde< DIM >::ComputeConstantInUSourceTerm (const ChastePoint< DIM > & rX, Element< DIM, DIM > * pElement) [inline]
Overridden ComputeConstantInUSourceTerm() method.
Parameters:
rX The point in space
pElement the element
Returns:
the constant in u part of the source term, i.e g(x) in Div(D Grad u) + f(x)u + g(x) = 0.
Definition at line 106 of file AveragedSourcePde.cpp.
template<unsigned DIM> c_matrix< double, DIM, DIM > AveragedSourcePde< DIM >::ComputeDiffusionTerm (const ChastePoint< DIM > & rX) [inline]
Overridden ComputeDiffusionTerm() method.
Parameters:
rX The point in space at which the diffusion term is computed
Returns:
a matrix.
Definition at line 119 of file AveragedSourcePde.cpp.
template<unsigned DIM> double AveragedSourcePde< DIM >::ComputeLinearInUCoeffInSourceTerm (const ChastePoint< DIM > & rX, Element< DIM, DIM > * pElement) [inline]
Overridden ComputeLinearInUCoeffInSourceTerm() method.
Parameters:
rX The point in space
pElement the element
Returns:
the coefficient of u in the linear part of the source term, i.e f(x) in Div(D Grad u) + f(x)u + g(x) = 0.
Definition at line 112 of file AveragedSourcePde.cpp.
References AbstractElement< ELEMENT_DIM, SPACE_DIM >::GetIndex(), AveragedSourcePde< DIM >::mCellDensityOnCoarseElements, and AveragedSourcePde< DIM >::mCoefficient.
template<unsigned DIM> double AveragedSourcePde< DIM >::GetCoefficient () const [inline]
Returns:
mCoefficient (used in archiving).
Definition at line 54 of file AveragedSourcePde.cpp.
References AveragedSourcePde< DIM >::mCoefficient.
template<unsigned DIM> double AveragedSourcePde< DIM >::GetUptakeRateForElement (unsigned elementIndex) [inline]
Returns:
the uptake rate.
Parameters:
elementIndex the element we wish to return the uptake rate for
Definition at line 125 of file AveragedSourcePde.cpp.
References AveragedSourcePde< DIM >::mCellDensityOnCoarseElements.
template<unsigned DIM> const AbstractCellPopulation< DIM > & AveragedSourcePde< DIM >::rGetCellPopulation () const [inline]
Returns:
const reference to the cell population (used in archiving).
Definition at line 48 of file AveragedSourcePde.cpp.
References AveragedSourcePde< DIM >::mrCellPopulation.
template<unsigned DIM> template<class Archive > void AveragedSourcePde< DIM >::serialize (Archive & archive, const unsigned int version) [inline, private]
Serialize the PDE and its member variables.
Parameters:
archive the archive
version the current version of this class
Reimplemented from AbstractLinearEllipticPde< DIM, DIM >.
Reimplemented in VolumeDependentAveragedSourcePde< DIM >.
Definition at line 67 of file AveragedSourcePde.hpp.
References AveragedSourcePde< DIM >::mCellDensityOnCoarseElements, and AveragedSourcePde< DIM >::mCoefficient.
template<unsigned DIM> void AveragedSourcePde< DIM >::SetupSourceTerms (TetrahedralMesh< DIM, DIM > & rCoarseMesh, std::map< CellPtr, unsigned > * pCellPdeElementMap = NULL) [inline, virtual]
Set up the source terms.
Parameters:
rCoarseMesh reference to the coarse mesh
pCellPdeElementMap optional pointer to the map from cells to coarse elements
Reimplemented in VolumeDependentAveragedSourcePde< DIM >.
Definition at line 60 of file AveragedSourcePde.cpp.
References AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::Begin(), AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::End(), AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::GetContainingElementIndex(), AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::GetElement(), AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::GetLocationOfCellCentre(), AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::GetNumElements(), AveragedSourcePde< DIM >::mCellDensityOnCoarseElements, and AveragedSourcePde< DIM >::mrCellPopulation.
Friends And Related Function Documentation
template<unsigned DIM> friend class boost::serialization::access [friend]
Needed for serialization.
Reimplemented from AbstractLinearEllipticPde< DIM, DIM >.
Reimplemented in VolumeDependentAveragedSourcePde< DIM >.
Definition at line 59 of file AveragedSourcePde.hpp.
Member Data Documentation
template<unsigned DIM> std::vector<double> AveragedSourcePde< DIM >::mCellDensityOnCoarseElements [protected]
Vector of averaged cell densities on elements of the coarse mesh.
Definition at line 83 of file AveragedSourcePde.hpp.
Referenced by AveragedSourcePde< DIM >::ComputeLinearInUCoeffInSourceTerm(), AveragedSourcePde< DIM >::GetUptakeRateForElement(), AveragedSourcePde< DIM >::serialize(), VolumeDependentAveragedSourcePde< DIM >::SetupSourceTerms(), and AveragedSourcePde< DIM >::SetupSourceTerms().
template<unsigned DIM> double AveragedSourcePde< DIM >::mCoefficient [protected]
Coefficient of consumption of nutrient by cells.
Definition at line 80 of file AveragedSourcePde.hpp.
Referenced by AveragedSourcePde< DIM >::ComputeLinearInUCoeffInSourceTerm(), AveragedSourcePde< DIM >::GetCoefficient(), and AveragedSourcePde< DIM >::serialize().
template<unsigned DIM> AbstractCellPopulation<DIM>& AveragedSourcePde< DIM >::mrCellPopulation [protected]
The cell population member.
Definition at line 77 of file AveragedSourcePde.hpp.
Referenced by AveragedSourcePde< DIM >::rGetCellPopulation(), VolumeDependentAveragedSourcePde< DIM >::SetupSourceTerms(), AveragedSourcePde< DIM >::SetupSourceTerms(), and VolumeDependentAveragedSourcePde< DIM >::VolumeDependentAveragedSourcePde().
The documentation for this class was generated from the following files:
cell_based/src/population/pdes/AveragedSourcePde.hpp
cell_based/src/population/pdes/AveragedSourcePde.cpp