Chaste: Identifiable Class Reference
Identifiable Class Reference
#include <Identifiable.hpp>
Inherited by AbstractCaUpdateRule< DIM >, AbstractCellBasedSimulation< ELEMENT_DIM, SPACE_DIM >, AbstractCellBasedSimulation< DIM >, AbstractCellBasedSimulation< ELEMENT_DIM, ELEMENT_DIM >, AbstractCellBasedSimulationModifier< ELEMENT_DIM, SPACE_DIM >, AbstractCellBasedSimulationModifier< DIM, DIM >, AbstractCellBasedWriter< ELEMENT_DIM, SPACE_DIM >, AbstractCellCycleModel, AbstractCellKiller< SPACE_DIM >, AbstractCellKiller< 2 >, AbstractCellKiller< DIM >, AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >, AbstractCellPopulation< DIM >, AbstractCellPopulation< DIM, DIM >, AbstractCellPopulation< ELEMENT_DIM, ELEMENT_DIM >, AbstractCellPopulation< SPACE_DIM >, AbstractCellPopulationBoundaryCondition< ELEMENT_DIM, SPACE_DIM >, AbstractCellPopulationBoundaryCondition< DIM >, AbstractCellProperty, AbstractForce< ELEMENT_DIM, SPACE_DIM >, AbstractForce< DIM >, AbstractForce< ELEMENT_DIM, ELEMENT_DIM >, AbstractIvpOdeSolver, AbstractPottsUpdateRule< DIM >, AbstractVertexBasedDivisionRule< SPACE_DIM >, CellBasedPdeHandler< DIM >, CellBasedPdeHandler< ELEMENT_DIM >, and CellBasedPdeHandler< SPACE_DIM >.
Public Member Functions
virtual ~Identifiable ()
std::string GetIdentifier () const
Private Member Functions
std::string TidyTemplatedExportIdentifier (std::string identifier) const
Detailed Description
"Mix-in" base class for any class that needs to provide a unique ID specifying what type the derived class is.
All you need to do to use this is inherit from this class at the base of your hierarchy, and provide a Boost Serialization export key for every concrete class. Also, any test in which the GetIdentifier method is used, even via the main cell_based code, must include CheckpointArchiveTypes.hpp or CellBasedSimulationArchiver.hpp as the first Chaste header included. Failure to do so will result in a segmentation fault.
Definition at line 60 of file Identifiable.hpp.
Constructor & Destructor Documentation
Identifiable::~Identifiable () [virtual]
Virtual destructor to make this class polymorphic.
Definition at line 89 of file Identifiable.cpp.
Member Function Documentation
std::string Identifiable::GetIdentifier () const
Returns:
the unique identifier of the concrete class.
This method uses Boost's serialization's extended_type_info and returns the identifier of the derived class (this is defined when the macro CHASTE_CLASS_EXPORT is invoked in each derived class, and is usually just the name of the class).
Note that you must include the header CheckpointArchiveTypes.hpp in any test suite that calls this method.
Definition at line 93 of file Identifiable.cpp.
References TidyTemplatedExportIdentifier().
Referenced by AbstractCellCycleModel::OutputCellCycleModelInfo(), AbstractCellKiller< DIM >::OutputCellKillerInfo(), AbstractCellPopulationBoundaryCondition< ELEMENT_DIM, SPACE_DIM >::OutputCellPopulationBoundaryConditionInfo(), AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::OutputCellPopulationInfo(), AbstractVertexBasedDivisionRule< SPACE_DIM >::OutputCellVertexBasedDivisionRuleInfo(), AbstractForce< ELEMENT_DIM, SPACE_DIM >::OutputForceInfo(), CellBasedPdeHandler< DIM >::OutputParameters(), AbstractCellBasedSimulationModifier< ELEMENT_DIM, SPACE_DIM >::OutputSimulationModifierInfo(), AbstractCellBasedSimulation< ELEMENT_DIM, SPACE_DIM >::OutputSimulationSetup(), AbstractPottsUpdateRule< DIM >::OutputUpdateRuleInfo(), AbstractCaUpdateRule< DIM >::OutputUpdateRuleInfo(), and AbstractOneStepIvpOdeSolver::Solve().
std::string Identifiable::TidyTemplatedExportIdentifier (std::string identifier) const [private]
Returns:
a name which is suitable for use as an XML element name Templated classes get Boost Serialization export keys that look like "pack<void (NameOfDerivedType< DIM >)>::type". This method converts it to a nice name suitable for use as an XML element name, i.e. of the form "NameOfDerivedType-DIM". Works for classes templated over any number of parameters, providing the values are allowable in XML element names.
Parameters:
identifier the identifier to tidy
Definition at line 46 of file Identifiable.cpp.
Referenced by GetIdentifier().
The documentation for this class was generated from the following files:
global/src/checkpointing/Identifiable.hpp
global/src/checkpointing/Identifiable.cpp