Chaste: ChastePoint< DIM > Class Template Reference
ChastePoint< DIM > Class Template Reference
#include <ChastePoint.hpp>
Public Member Functions
ChastePoint (double v1=0, double v2=0, double v3=0)
ChastePoint (std::vector< double > coords)
ChastePoint (c_vector< double, DIM > location)
c_vector< double, DIM > & rGetLocation ()
const c_vector< double, DIM > & rGetLocation () const
double operator[] (unsigned i) const
double GetWithDefault (unsigned i, double def=0.0) const
void SetCoordinate (unsigned i, double value)
bool IsSamePoint (const ChastePoint< DIM > &rPoint) const
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Private Attributes
c_vector< double, DIM > mLocation
Friends
class boost::serialization::access
Detailed Description
template<unsigned DIM>
class ChastePoint< DIM >
A ChastePoint class, templated over spatial dimension.
Definition at line 49 of file ChastePoint.hpp.
Constructor & Destructor Documentation
template<unsigned DIM> ChastePoint< DIM >::ChastePoint (double v1 = 0, double v2 = 0, double v3 = 0) [inline]
Create a Point object. There are 3 optional arguments, which can be used to specify the values of the first 3 dimensions, if present.
Point now uses a ublas vector to store its location. The rGetLocation method returns a reference to this vector. Use of this method together with ublas operations is the perfered way to use this class.
Parameters:
v1 the point's x-coordinate (defaults to 0)
v2 the point's y-coordinate (defaults to 0)
v3 the point's z-coordinate (defaults to 0)
Definition at line 44 of file ChastePoint.cpp.
References ChastePoint< DIM >::mLocation.
template<unsigned DIM> ChastePoint< DIM >::ChastePoint (std::vector< double > coords) [inline]
Create a Point object. This constructor takes a vector giving the coordinates of the point. The length of the vector must be at least the dimension of the point.
Parameters:
coords a std::vector storing the point's coordinates
Definition at line 61 of file ChastePoint.cpp.
References ChastePoint< DIM >::mLocation.
template<unsigned DIM> ChastePoint< DIM >::ChastePoint (c_vector< double, DIM > location) [inline]
Alternative constructor which takes in a c_vector.
Parameters:
location a c_vector storing the point's coordinates
Definition at line 70 of file ChastePoint.cpp.
Member Function Documentation
template<unsigned DIM> double ChastePoint< DIM >::GetWithDefault (unsigned i, double def = 0.0) const [inline]
Returns:
a co-ordinate, returning the default value if the co-ordinate doesn't exist.
Parameters:
i the co-ordinate to get
def the default value
Definition at line 95 of file ChastePoint.cpp.
References ChastePoint< DIM >::mLocation.
Referenced by PseudoEcgCalculator< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::WritePseudoEcg().
template<unsigned DIM> bool ChastePoint< DIM >::IsSamePoint (const ChastePoint< DIM > & rPoint) const [inline]
Checks whether one chaste point is the same as the one constructed
Parameters:
rPoint the point to be checked
Returns:
true if the are the same
Definition at line 115 of file ChastePoint.cpp.
References ChastePoint< DIM >::mLocation.
template<unsigned DIM> double ChastePoint< DIM >::operator[] (unsigned i) const [inline]
Returns:
the vector mLocation.
Parameters:
i the index of the vector to return
Definition at line 88 of file ChastePoint.cpp.
References ChastePoint< DIM >::mLocation.
template<unsigned DIM> const c_vector< double, DIM > & ChastePoint< DIM >::rGetLocation () const [inline]
Returns:
the location of the Point. Constant non-liberal variety.
Definition at line 82 of file ChastePoint.cpp.
References ChastePoint< DIM >::mLocation.
template<unsigned DIM> c_vector< double, DIM > & ChastePoint< DIM >::rGetLocation () [inline]
Returns:
the location of the Point.
Definition at line 76 of file ChastePoint.cpp.
References ChastePoint< DIM >::mLocation.
Referenced by AbstractFeCableIntegralAssembler< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM, CAN_ASSEMBLE_VECTOR, CAN_ASSEMBLE_MATRIX, INTERPOLATION_LEVEL >::AssembleOnCableElement(), AbstractFeVolumeIntegralAssembler< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM, CAN_ASSEMBLE_VECTOR, CAN_ASSEMBLE_MATRIX, INTERPOLATION_LEVEL >::AssembleOnElement(), AbstractFeSurfaceIntegralAssembler< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::AssembleOnSurfaceElement(), DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::CalculateBoundingBox(), AbstractFunctionalCalculator< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::CalculateOnElement(), Element< ELEMENT_DIM, SPACE_DIM >::CalculateXi(), AbstractNonlinearElasticitySolver< DIM >::GetElementCentroidStrain(), PseudoEcgCalculator< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::GetIntegrand(), DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::GetNearestNodeIndex(), AbstractMesh< ELEMENT_DIM, SPACE_DIM >::GetNearestNodeIndex(), Node< SPACE_DIM >::Node(), MutableMesh< ELEMENT_DIM, SPACE_DIM >::RefineElement(), Toroidal2dVertexMesh::SetNode(), Cylindrical2dVertexMesh::SetNode(), Cylindrical2dNodesOnlyMesh::SetNode(), Cylindrical2dMesh::SetNode(), Node< SPACE_DIM >::SetPoint(), and CellBasedPdeHandler< DIM >::UseCoarsePdeMesh().
template<unsigned DIM> template<class Archive > void ChastePoint< DIM >::serialize (Archive & archive, const unsigned int version) [inline, private]
Archive the member variables.
Parameters:
archive
version
Definition at line 60 of file ChastePoint.hpp.
template<unsigned DIM> void ChastePoint< DIM >::SetCoordinate (unsigned i, double value) [inline]
Set one of the coordinates of the Point.
Parameters:
i the index of the coordinate
value the value of the coordinate
Definition at line 108 of file ChastePoint.cpp.
References ChastePoint< DIM >::mLocation.
Referenced by Toroidal2dVertexMesh::SetNode(), Cylindrical2dVertexMesh::SetNode(), Cylindrical2dNodesOnlyMesh::SetNode(), and Cylindrical2dMesh::SetNode().
Friends And Related Function Documentation
template<unsigned DIM> friend class boost::serialization::access [friend]
Needed for serialization.
Definition at line 52 of file ChastePoint.hpp.
Member Data Documentation
template<unsigned DIM> c_vector<double, DIM> ChastePoint< DIM >::mLocation [private]
The location of the Point.
Definition at line 68 of file ChastePoint.hpp.
Referenced by ChastePoint< DIM >::ChastePoint(), ChastePoint< DIM >::GetWithDefault(), ChastePoint< DIM >::IsSamePoint(), ChastePoint< DIM >::operator[](), ChastePoint< DIM >::rGetLocation(), and ChastePoint< DIM >::SetCoordinate().
The documentation for this class was generated from the following files:
mesh/src/common/ChastePoint.hpp
mesh/src/common/ChastePoint.cpp