Chaste: boost::random::normal_distribution_v156< RealType >::param_type Class Reference
boost::random::normal_distribution_v156< RealType >::param_type Class Reference
Public Types
typedef normal_distribution_v156 distribution_type
Public Member Functions
param_type (RealType mean_arg=RealType(0.0), RealType sigma_arg=RealType(1.0))
RealType mean () const
RealType sigma () const
BOOST_RANDOM_DETAIL_OSTREAM_OPERATOR (os, param_type, parm)
BOOST_RANDOM_DETAIL_ISTREAM_OPERATOR (is, param_type, parm)
BOOST_RANDOM_DETAIL_EQUALITY_OPERATOR (param_type, lhs, rhs)
Private Attributes
RealType _mean
RealType _sigma
Detailed Description
template<class RealType = double>
class boost::random::normal_distribution_v156< RealType >::param_type
Definition at line 403 of file Boost156NormalDistribution.hpp.
Constructor & Destructor Documentation
template<class RealType = double> boost::random::normal_distribution_v156< RealType >::param_type::param_type (RealType mean_arg = RealType(0.0), RealType sigma_arg = RealType(1.0)) [inline, explicit]
Constructs a param_type with a given mean and standard deviation.
Requires: sigma >= 0
Definition at line 413 of file Boost156NormalDistribution.hpp.
Referenced by boost::random::normal_distribution_v156< RealType >::param().
Member Function Documentation
template<class RealType = double> boost::random::normal_distribution_v156< RealType >::param_type::BOOST_RANDOM_DETAIL_EQUALITY_OPERATOR (param_type , lhs , rhs) [inline]
Returns true if the two sets of parameters are the same.
Definition at line 434 of file Boost156NormalDistribution.hpp.
template<class RealType = double> boost::random::normal_distribution_v156< RealType >::param_type::BOOST_RANDOM_DETAIL_ISTREAM_OPERATOR (is , param_type , parm) [inline]
Reads a param_type from a std::istream.
Definition at line 430 of file Boost156NormalDistribution.hpp.
template<class RealType = double> boost::random::normal_distribution_v156< RealType >::param_type::BOOST_RANDOM_DETAIL_OSTREAM_OPERATOR (os , param_type , parm) [inline]
Writes a param_type to a std::ostream.
Definition at line 426 of file Boost156NormalDistribution.hpp.
template<class RealType = double> RealType boost::random::normal_distribution_v156< RealType >::param_type::mean () const [inline]
Returns the mean of the distribution.
Definition at line 420 of file Boost156NormalDistribution.hpp.
References boost::random::normal_distribution_v156< RealType >::param_type::_mean.
Referenced by boost::random::normal_distribution_v156< RealType >::param().
template<class RealType = double> RealType boost::random::normal_distribution_v156< RealType >::param_type::sigma () const [inline]
Returns the standard deviation of the distribution.
Definition at line 423 of file Boost156NormalDistribution.hpp.
Referenced by boost::random::normal_distribution_v156< RealType >::param().
Member Data Documentation
template<class RealType = double> RealType boost::random::normal_distribution_v156< RealType >::param_type::_mean [private]
Returns true if the two sets of parameters are the different.
Definition at line 441 of file Boost156NormalDistribution.hpp.
Referenced by boost::random::normal_distribution_v156< RealType >::mean(), boost::random::normal_distribution_v156< RealType >::param_type::mean(), boost::random::normal_distribution_v156< RealType >::operator()(), and boost::random::normal_distribution_v156< RealType >::param().
The documentation for this class was generated from the following file:
global/src/Boost156NormalDistribution.hpp