Chaste: AbstractCellBasedSimulationModifier< ELEMENT_DIM, SPACE_DIM > Class Template Reference
AbstractCellBasedSimulationModifier< ELEMENT_DIM, SPACE_DIM > Class Template Reference
#include <AbstractCellBasedSimulationModifier.hpp>
Inherits Identifiable.
Public Member Functions
AbstractCellBasedSimulationModifier ()
virtual ~AbstractCellBasedSimulationModifier ()
virtual void UpdateAtEndOfTimeStep (AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM > &rCellPopulation)
virtual void UpdateAtEndOfOutputTimeStep (AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM > &rCellPopulation)
virtual void SetupSolve (AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM > &rCellPopulation, std::string outputDirectory)
virtual void UpdateAtEndOfSolve (AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM > &rCellPopulation)
void OutputSimulationModifierInfo (out_stream &rParamsFile)
virtual void OutputSimulationModifierParameters (out_stream &rParamsFile)=0
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Friends
class boost::serialization::access
Detailed Description
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM = ELEMENT_DIM>
class AbstractCellBasedSimulationModifier< ELEMENT_DIM, SPACE_DIM >
An abstract modifier class (to implement setup, update and finalise methods), for use in cell-based simulations.
Definition at line 48 of file AbstractCellBasedSimulationModifier.hpp.
Constructor & Destructor Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> AbstractCellBasedSimulationModifier< ELEMENT_DIM, SPACE_DIM >::AbstractCellBasedSimulationModifier () [inline]
Default constructor.
Definition at line 39 of file AbstractCellBasedSimulationModifier.cpp.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> AbstractCellBasedSimulationModifier< ELEMENT_DIM, SPACE_DIM >::~AbstractCellBasedSimulationModifier () [inline, virtual]
Destructor.
Definition at line 44 of file AbstractCellBasedSimulationModifier.cpp.
Member Function Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void AbstractCellBasedSimulationModifier< ELEMENT_DIM, SPACE_DIM >::OutputSimulationModifierInfo (out_stream & rParamsFile) [inline]
Output the modifier type used in the simulation to file and then call OutputSimulationModifierParameters() to output all relevant parameters.
Parameters:
rParamsFile the file stream to which the parameters are output
Definition at line 49 of file AbstractCellBasedSimulationModifier.cpp.
References Identifiable::GetIdentifier(), and AbstractCellBasedSimulationModifier< ELEMENT_DIM, SPACE_DIM >::OutputSimulationModifierParameters().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void AbstractCellBasedSimulationModifier< ELEMENT_DIM, SPACE_DIM >::OutputSimulationModifierParameters (out_stream & rParamsFile) [inline, pure virtual]
Output any simulation modifier parameters to file.
As this method is pure virtual, it must be overridden in subclasses.
Parameters:
rParamsFile the file stream to which the parameters are output
Implemented in AbstractTargetAreaModifier< DIM >, DeltaNotchTrackingModifier< DIM >, FarhadifarTypeModifier< DIM >, SimpleTargetAreaModifier< DIM >, and VolumeTrackingModifier< DIM >.
Definition at line 58 of file AbstractCellBasedSimulationModifier.cpp.
Referenced by AbstractCellBasedSimulationModifier< ELEMENT_DIM, SPACE_DIM >::OutputSimulationModifierInfo().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM = ELEMENT_DIM> template<class Archive > void AbstractCellBasedSimulationModifier< ELEMENT_DIM, SPACE_DIM >::serialize (Archive & archive, const unsigned int version) [inline, private]
Serialize the object.
Parameters:
archive the archive
version the current version of this class
Reimplemented in AbstractTargetAreaModifier< DIM >, DeltaNotchTrackingModifier< DIM >, FarhadifarTypeModifier< DIM >, SimpleTargetAreaModifier< DIM >, and VolumeTrackingModifier< DIM >.
Definition at line 59 of file AbstractCellBasedSimulationModifier.hpp.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM = ELEMENT_DIM> virtual void AbstractCellBasedSimulationModifier< ELEMENT_DIM, SPACE_DIM >::SetupSolve (AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM > & rCellPopulation, std::string outputDirectory) [inline, virtual]
Specify what to do in the simulation before the start of the time loop.
Parameters:
rCellPopulation reference to the cell population
outputDirectory the output directory, relative to where Chaste output is stored
Definition at line 99 of file AbstractCellBasedSimulationModifier.hpp.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM = ELEMENT_DIM> virtual void AbstractCellBasedSimulationModifier< ELEMENT_DIM, SPACE_DIM >::UpdateAtEndOfOutputTimeStep (AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM > & rCellPopulation) [inline, virtual]
Specify what to do in the simulation at the end of each output timestep.
Parameters:
rCellPopulation reference to the cell population
Definition at line 89 of file AbstractCellBasedSimulationModifier.hpp.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM = ELEMENT_DIM> virtual void AbstractCellBasedSimulationModifier< ELEMENT_DIM, SPACE_DIM >::UpdateAtEndOfSolve (AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM > & rCellPopulation) [inline, virtual]
Specify what to do in the simulation at the end of each time loop.
Parameters:
rCellPopulation reference to the cell population
Definition at line 108 of file AbstractCellBasedSimulationModifier.hpp.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM = ELEMENT_DIM> virtual void AbstractCellBasedSimulationModifier< ELEMENT_DIM, SPACE_DIM >::UpdateAtEndOfTimeStep (AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM > & rCellPopulation) [inline, virtual]
Specify what to do in the simulation at the end of each timestep.
Parameters:
rCellPopulation reference to the cell population
Definition at line 80 of file AbstractCellBasedSimulationModifier.hpp.
Friends And Related Function Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM = ELEMENT_DIM> friend class boost::serialization::access [friend]
Needed for serialization.
Reimplemented in AbstractTargetAreaModifier< DIM >, DeltaNotchTrackingModifier< DIM >, FarhadifarTypeModifier< DIM >, SimpleTargetAreaModifier< DIM >, and VolumeTrackingModifier< DIM >.
Definition at line 51 of file AbstractCellBasedSimulationModifier.hpp.
The documentation for this class was generated from the following files:
cell_based/src/simulation/modifiers/AbstractCellBasedSimulationModifier.hpp
cell_based/src/simulation/modifiers/AbstractCellBasedSimulationModifier.cpp