Chaste: AbstractCaUpdateRule< DIM > Class Template Reference
AbstractCaUpdateRule< DIM > Class Template Reference
#include <AbstractCaUpdateRule.hpp>
Inherits Identifiable.
Inherited by DiffusionCaUpdateRule< DIM >.
Public Member Functions
AbstractCaUpdateRule ()
virtual ~AbstractCaUpdateRule ()
virtual double EvaluateProbability (unsigned currentNodeIndex, unsigned targetNodeIndex, CaBasedCellPopulation< DIM > &rCellPopulation, double dt, double deltaX, CellPtr cell)=0
void OutputUpdateRuleInfo (out_stream &rParamsFile)
virtual void OutputUpdateRuleParameters (out_stream &rParamsFile)=0
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Friends
class boost::serialization::access
Detailed Description
template<unsigned DIM>
class AbstractCaUpdateRule< DIM >
An abstract CA update rule class, for use in cell-based simulations using the cellular automota model.
Definition at line 52 of file AbstractCaUpdateRule.hpp.
Constructor & Destructor Documentation
template<unsigned DIM> AbstractCaUpdateRule< DIM >::AbstractCaUpdateRule () [inline]
Default constructor.
Definition at line 39 of file AbstractCaUpdateRule.cpp.
template<unsigned DIM> AbstractCaUpdateRule< DIM >::~AbstractCaUpdateRule () [inline, virtual]
Destructor.
Definition at line 44 of file AbstractCaUpdateRule.cpp.
Member Function Documentation
template<unsigned DIM> virtual double AbstractCaUpdateRule< DIM >::EvaluateProbability (unsigned currentNodeIndex, unsigned targetNodeIndex, CaBasedCellPopulation< DIM > & rCellPopulation, double dt, double deltaX, CellPtr cell) [pure virtual]
Calculate the probability of a given move.
Uses random diffusion to each neighbouring node, scaled according to distance.
Parameters:
currentNodeIndex The index of the current node/lattice site
targetNodeIndex The index of the target node/lattice site
rCellPopulation The cell population
dt is the time interval
deltaX defines the size of the lattice site
cell a pointer to the cell (needed if more than one cell per lattice site
Returns:
The probability of the cell moving from the current node to the target node
Implemented in DiffusionCaUpdateRule< DIM >.
template<unsigned DIM> void AbstractCaUpdateRule< DIM >::OutputUpdateRuleInfo (out_stream & rParamsFile) [inline]
Output update rule to file. Call OutputUpdateRuleParameters() to output all member variables to file.
Parameters:
rParamsFile a file stream
Definition at line 49 of file AbstractCaUpdateRule.cpp.
References Identifiable::GetIdentifier(), and AbstractCaUpdateRule< DIM >::OutputUpdateRuleParameters().
template<unsigned DIM> void AbstractCaUpdateRule< DIM >::OutputUpdateRuleParameters (out_stream & rParamsFile) [inline, pure virtual]
Output update rule parameters to file.
As this method is pure virtual, it must be overridden in subclasses.
Parameters:
rParamsFile a file stream
Implemented in DiffusionCaUpdateRule< DIM >.
Definition at line 59 of file AbstractCaUpdateRule.cpp.
Referenced by AbstractCaUpdateRule< DIM >::OutputUpdateRuleInfo().
template<unsigned DIM> template<class Archive > void AbstractCaUpdateRule< DIM >::serialize (Archive & archive, const unsigned int version) [inline, private]
Boost Serialization method for archiving/checkpointing. Archives the object and its member variables.
Parameters:
archive The boost archive.
version The current version of this class.
Reimplemented in DiffusionCaUpdateRule< DIM >.
Definition at line 64 of file AbstractCaUpdateRule.hpp.
Friends And Related Function Documentation
template<unsigned DIM> friend class boost::serialization::access [friend]
Needed for serialization.
Reimplemented in DiffusionCaUpdateRule< DIM >.
Definition at line 55 of file AbstractCaUpdateRule.hpp.
The documentation for this class was generated from the following files:
cell_based/src/population/update_rules/AbstractCaUpdateRule.hpp
cell_based/src/population/update_rules/AbstractCaUpdateRule.cpp