Chaste: PdeSimulationTime Class Reference
PdeSimulationTime Class Reference
#include <PdeSimulationTime.hpp>
Static Public Member Functions
static void SetTime (double time)
static double GetTime ()
static void SetPdeTimeStepAndNextTime (double timestep, double next_time)
static double GetPdeTimeStep ()
static double GetNextTime ()
static double GetPdeTimeStepInverse ()
Static Private Attributes
static double mTime
static double mPdeTimeStep
static double mNextTime
static double mPdeTimeStepInverse
Detailed Description
Todo:
Integrate with other time stepping classes or remove? A small convenience class providing a consistent global time to the PDE solver classes.
This isn't technically a singleton, as it's implemented with static data and methods.
Definition at line 47 of file PdeSimulationTime.hpp.
Member Function Documentation
double PdeSimulationTime::GetNextTime () [static]
Returns:
the next time (time after time-step has been made).
Definition at line 74 of file PdeSimulationTime.cpp.
References mNextTime.
Referenced by OperatorSplittingMonodomainSolver< ELEMENT_DIM, SPACE_DIM >::FollowingSolveLinearSystem(), LinearParabolicPdeSystemWithCoupledOdeSystemSolver< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::PrepareForSetupLinearSystem(), MonodomainSolver< ELEMENT_DIM, SPACE_DIM >::PrepareForSetupLinearSystem(), AbstractExtendedBidomainSolver< ELEMENT_DIM, SPACE_DIM >::PrepareForSetupLinearSystem(), and AbstractBidomainSolver< ELEMENT_DIM, SPACE_DIM >::PrepareForSetupLinearSystem().
double PdeSimulationTime::GetPdeTimeStep () [static]
Returns:
the current PDE timestep.
Definition at line 64 of file PdeSimulationTime.cpp.
References mPdeTimeStep.
Referenced by ExtendedBidomainAssembler< ELEMENT_DIM, SPACE_DIM >::ComputeMatrixTerm(), OperatorSplittingMonodomainSolver< ELEMENT_DIM, SPACE_DIM >::FollowingSolveLinearSystem(), LinearParabolicPdeSystemWithCoupledOdeSystemSolver< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::PrepareForSetupLinearSystem(), OperatorSplittingMonodomainSolver< ELEMENT_DIM, SPACE_DIM >::PrepareForSetupLinearSystem(), and ExtendedBidomainSolver< ELEM_DIM, SPACE_DIM >::SetupLinearSystem().
double PdeSimulationTime::GetPdeTimeStepInverse () [static]
Returns:
1/dt.
Definition at line 69 of file PdeSimulationTime.cpp.
References mPdeTimeStepInverse.
Referenced by SimpleLinearParabolicSolver< ELEMENT_DIM, SPACE_DIM >::ComputeMatrixTerm(), LinearParabolicPdeSystemWithCoupledOdeSystemSolver< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::ComputeMatrixTerm(), MonodomainAssembler< ELEMENT_DIM, SPACE_DIM >::ComputeMatrixTerm(), BidomainAssembler< ELEMENT_DIM, SPACE_DIM >::ComputeMatrixTerm(), SimpleLinearParabolicSolver< ELEMENT_DIM, SPACE_DIM >::ComputeVectorTerm(), LinearParabolicPdeSystemWithCoupledOdeSystemSolver< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::ComputeVectorTerm(), OperatorSplittingMonodomainSolver< ELEMENT_DIM, SPACE_DIM >::SetupLinearSystem(), MonodomainSolver< ELEMENT_DIM, SPACE_DIM >::SetupLinearSystem(), and BidomainSolver< ELEMENT_DIM, SPACE_DIM >::SetupLinearSystem().
double PdeSimulationTime::GetTime () [static]
Returns:
the current time.
Definition at line 51 of file PdeSimulationTime.cpp.
References mTime.
Referenced by OperatorSplittingMonodomainSolver< ELEMENT_DIM, SPACE_DIM >::FollowingSolveLinearSystem(), StimulusBoundaryCondition< SPACE_DIM >::GetValue(), LinearParabolicPdeSystemWithCoupledOdeSystemSolver< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::PrepareForSetupLinearSystem(), OperatorSplittingMonodomainSolver< ELEMENT_DIM, SPACE_DIM >::PrepareForSetupLinearSystem(), MonodomainSolver< ELEMENT_DIM, SPACE_DIM >::PrepareForSetupLinearSystem(), AbstractExtendedBidomainSolver< ELEMENT_DIM, SPACE_DIM >::PrepareForSetupLinearSystem(), and AbstractBidomainSolver< ELEMENT_DIM, SPACE_DIM >::PrepareForSetupLinearSystem().
void PdeSimulationTime::SetPdeTimeStepAndNextTime (double timestep, double next_time) [static]
Set the current PDE timestep.
The method checks that next_time ~= mTime + timestep
Parameters:
timestep the current timestep
next_time the next time (as given by the PDE time stepper).
Definition at line 56 of file PdeSimulationTime.cpp.
References mNextTime, mPdeTimeStep, mPdeTimeStepInverse, and mTime.
Referenced by AbstractDynamicLinearPdeSolver< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::Solve().
void PdeSimulationTime::SetTime (double time) [static]
Set the current time.
Parameters:
time the current time
Definition at line 46 of file PdeSimulationTime.cpp.
References mTime.
Referenced by AbstractDynamicLinearPdeSolver< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::Solve().
Member Data Documentation
double PdeSimulationTime::mNextTime [static, private]
The next time (from the original PDE time-stepper). mNextTime ~= mTime + mPdeTimeStep. Note that this is stored explicitly because if we do the addition then the answer will be off by mTime*DBL_EPSILON.
Definition at line 92 of file PdeSimulationTime.hpp.
Referenced by GetNextTime(), and SetPdeTimeStepAndNextTime().
double PdeSimulationTime::mPdeTimeStep [static, private]
The timestep used in the PDE solve.
Definition at line 85 of file PdeSimulationTime.hpp.
Referenced by GetPdeTimeStep(), and SetPdeTimeStepAndNextTime().
double PdeSimulationTime::mPdeTimeStepInverse [static, private]
1/dt.
Definition at line 95 of file PdeSimulationTime.hpp.
Referenced by GetPdeTimeStepInverse(), and SetPdeTimeStepAndNextTime().
double PdeSimulationTime::mTime [static, private]
The current time.
Definition at line 82 of file PdeSimulationTime.hpp.
Referenced by GetTime(), SetPdeTimeStepAndNextTime(), and SetTime().
The documentation for this class was generated from the following files:
pde/src/common/PdeSimulationTime.hpp
pde/src/common/PdeSimulationTime.cpp