Chaste: QuadraturePointsGroup< DIM > Class Template Reference
QuadraturePointsGroup< DIM > Class Template Reference
#include <QuadraturePointsGroup.hpp>
Public Member Functions
QuadraturePointsGroup (AbstractTetrahedralMesh< DIM, DIM > &rMesh, GaussianQuadratureRule< DIM > &rQuadRule)
c_vector< double, DIM > & rGet (unsigned elementIndex, unsigned quadIndex)
c_vector< double, DIM > & rGet (unsigned i)
unsigned GetNumElements () const
unsigned GetNumQuadPointsPerElement () const
unsigned Size () const
Private Attributes
std::vector< c_vector< double,
DIM > > data
unsigned mNumElements
unsigned mNumQuadPointsPerElement
Detailed Description
template<unsigned DIM>
class QuadraturePointsGroup< DIM >
A simple class which takes in a mesh and a quadrature rule, and collects all the quadrature points in physical space (rather than in natural element coordinates) together in one data structure, for access.
In a distributed mesh, a set of quad points can still be accessed for a given element but then any missing data is marked with DOUBLE_UNSET
Definition at line 54 of file QuadraturePointsGroup.hpp.
Constructor & Destructor Documentation
template<unsigned DIM> QuadraturePointsGroup< DIM >::QuadraturePointsGroup (AbstractTetrahedralMesh< DIM, DIM > & rMesh, GaussianQuadratureRule< DIM > & rQuadRule) [inline]
Constructor takes in a mesh and a rule and computes and stores all the quad points in physical space.
Parameters:
rMesh
rQuadRule
Definition at line 40 of file QuadraturePointsGroup.cpp.
References QuadraturePointsGroup< DIM >::data, DOUBLE_UNSET, AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::GetElementIteratorBegin(), AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::GetElementIteratorEnd(), AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::GetNumElements(), GaussianQuadratureRule< ELEMENT_DIM >::GetNumQuadPoints(), QuadraturePointsGroup< DIM >::mNumElements, QuadraturePointsGroup< DIM >::mNumQuadPointsPerElement, and GaussianQuadratureRule< ELEMENT_DIM >::rGetQuadPoint().
Member Function Documentation
template<unsigned DIM> unsigned QuadraturePointsGroup< DIM >::GetNumElements () const [inline]
Returns:
number of elements in the mesh that was given in the constructor
Definition at line 98 of file QuadraturePointsGroup.cpp.
References QuadraturePointsGroup< DIM >::mNumElements.
template<unsigned DIM> unsigned QuadraturePointsGroup< DIM >::GetNumQuadPointsPerElement () const [inline]
Returns:
number of quad points per element in the rule that was given in the constructor
Definition at line 104 of file QuadraturePointsGroup.cpp.
References QuadraturePointsGroup< DIM >::mNumQuadPointsPerElement.
template<unsigned DIM> c_vector< double, DIM > & QuadraturePointsGroup< DIM >::rGet (unsigned i) [inline]
Returns:
the i-th stored quadrature point.
Parameters:
i
Definition at line 91 of file QuadraturePointsGroup.cpp.
References QuadraturePointsGroup< DIM >::data, QuadraturePointsGroup< DIM >::mNumElements, and QuadraturePointsGroup< DIM >::mNumQuadPointsPerElement.
template<unsigned DIM> c_vector< double, DIM > & QuadraturePointsGroup< DIM >::rGet (unsigned elementIndex, unsigned quadIndex) [inline]
Returns:
a stored quadrature point by element index and quad index in the element.
Parameters:
elementIndex
quadIndex
Definition at line 83 of file QuadraturePointsGroup.cpp.
References QuadraturePointsGroup< DIM >::data, QuadraturePointsGroup< DIM >::mNumElements, and QuadraturePointsGroup< DIM >::mNumQuadPointsPerElement.
Referenced by FineCoarseMeshPair< DIM >::ComputeFineElementsAndWeightsForCoarseQuadPoints().
template<unsigned DIM> unsigned QuadraturePointsGroup< DIM >::Size () const [inline]
Returns:
total size, i.e. total number of quad points, i.e. num_elem times num_quad_points_per_elem
Definition at line 110 of file QuadraturePointsGroup.cpp.
References QuadraturePointsGroup< DIM >::mNumElements, and QuadraturePointsGroup< DIM >::mNumQuadPointsPerElement.
Referenced by FineCoarseMeshPair< DIM >::ComputeFineElementsAndWeightsForCoarseQuadPoints().
Member Data Documentation
template<unsigned DIM> std::vector<c_vector<double,DIM> > QuadraturePointsGroup< DIM >::data [private]
The quadrature points in physical space
Definition at line 59 of file QuadraturePointsGroup.hpp.
Referenced by QuadraturePointsGroup< DIM >::QuadraturePointsGroup(), and QuadraturePointsGroup< DIM >::rGet().
template<unsigned DIM> unsigned QuadraturePointsGroup< DIM >::mNumElements [private]
Number of elements in given mesh
Definition at line 62 of file QuadraturePointsGroup.hpp.
Referenced by QuadraturePointsGroup< DIM >::GetNumElements(), QuadraturePointsGroup< DIM >::QuadraturePointsGroup(), QuadraturePointsGroup< DIM >::rGet(), and QuadraturePointsGroup< DIM >::Size().
template<unsigned DIM> unsigned QuadraturePointsGroup< DIM >::mNumQuadPointsPerElement [private]
Number of quad points per element in given rule
Definition at line 65 of file QuadraturePointsGroup.hpp.
Referenced by QuadraturePointsGroup< DIM >::GetNumQuadPointsPerElement(), QuadraturePointsGroup< DIM >::QuadraturePointsGroup(), QuadraturePointsGroup< DIM >::rGet(), and QuadraturePointsGroup< DIM >::Size().
The documentation for this class was generated from the following files:
pde/src/common/QuadraturePointsGroup.hpp
pde/src/common/QuadraturePointsGroup.cpp