Chaste: VtkNonlinearElasticitySolutionWriter< DIM > Class Template Reference
VtkNonlinearElasticitySolutionWriter< DIM > Class Template Reference
#include <VtkNonlinearElasticitySolutionWriter.hpp>
Public Member Functions
VtkNonlinearElasticitySolutionWriter (AbstractNonlinearElasticitySolver< DIM > &rSolver)
void SetWriteElementWiseStrains (StrainType strainType)
void Write ()
Private Attributes
AbstractNonlinearElasticitySolver
< DIM > * mpSolver
bool mWriteElementWiseStrains
StrainType mElementWiseStrainType
std::vector< c_matrix< double,
DIM, DIM > > mTensorData
Friends
class TestVtkNonlinearElasticitySolutionWriter
Detailed Description
template<unsigned DIM>
class VtkNonlinearElasticitySolutionWriter< DIM >
Class for write mechanics solutions to .vtu file (for visualisation in Paraview), including displacement, pressure if incompressible simulation, different strains, and (in future) stresses.
Definition at line 48 of file VtkNonlinearElasticitySolutionWriter.hpp.
Constructor & Destructor Documentation
template<unsigned DIM> VtkNonlinearElasticitySolutionWriter< DIM >::VtkNonlinearElasticitySolutionWriter (AbstractNonlinearElasticitySolver< DIM > & rSolver) [inline]
Constructor
Parameters:
rSolver mechanics solver which performed the calculation
Definition at line 74 of file VtkNonlinearElasticitySolutionWriter.hpp.
Member Function Documentation
template<unsigned DIM> void VtkNonlinearElasticitySolutionWriter< DIM >::SetWriteElementWiseStrains (StrainType strainType) [inline]
Set write strains for each element. Can write any of: F = dx/dX, C = F^T F, E = 1/2 (C-I)
Parameters:
strainType Which strain to write, choose one of: DEFORMATION_GRADIENT_F, DEFORMATION_TENSOR_C, LAGRANGE_STRAIN_E
Definition at line 84 of file VtkNonlinearElasticitySolutionWriter.hpp.
References VtkNonlinearElasticitySolutionWriter< DIM >::mElementWiseStrainType, and VtkNonlinearElasticitySolutionWriter< DIM >::mWriteElementWiseStrains.
template<unsigned DIM> void VtkNonlinearElasticitySolutionWriter< DIM >::Write () [inline]
Write the .vtu file
Definition at line 40 of file VtkNonlinearElasticitySolutionWriter.cpp.
References VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::AddCellData(), VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::AddPointData(), VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::AddTensorCellData(), EXCEPTION, VtkNonlinearElasticitySolutionWriter< DIM >::mElementWiseStrainType, VtkNonlinearElasticitySolutionWriter< DIM >::mpSolver, VtkNonlinearElasticitySolutionWriter< DIM >::mTensorData, VtkNonlinearElasticitySolutionWriter< DIM >::mWriteElementWiseStrains, NEVER_REACHED, and VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::WriteFilesUsingMesh().
Member Data Documentation
template<unsigned DIM> StrainType VtkNonlinearElasticitySolutionWriter< DIM >::mElementWiseStrainType [private]
What type of strain to write for each element, from: F = dx/dX, C = F^T F, E = 1/2 (C-I)
Definition at line 58 of file VtkNonlinearElasticitySolutionWriter.hpp.
Referenced by VtkNonlinearElasticitySolutionWriter< DIM >::SetWriteElementWiseStrains(), and VtkNonlinearElasticitySolutionWriter< DIM >::Write().
template<unsigned DIM> AbstractNonlinearElasticitySolver<DIM>* VtkNonlinearElasticitySolutionWriter< DIM >::mpSolver [private]
Pointer to the mechanics solver which performed the calculation
Definition at line 54 of file VtkNonlinearElasticitySolutionWriter.hpp.
Referenced by VtkNonlinearElasticitySolutionWriter< DIM >::Write().
template<unsigned DIM> std::vector<c_matrix<double,DIM,DIM> > VtkNonlinearElasticitySolutionWriter< DIM >::mTensorData [private]
Tensor data to be written to the .vtu file. This is a member variable only for testing reasons.
Definition at line 61 of file VtkNonlinearElasticitySolutionWriter.hpp.
Referenced by VtkNonlinearElasticitySolutionWriter< DIM >::Write().
template<unsigned DIM> bool VtkNonlinearElasticitySolutionWriter< DIM >::mWriteElementWiseStrains [private]
Whether to write strains for each element
Definition at line 56 of file VtkNonlinearElasticitySolutionWriter.hpp.
Referenced by VtkNonlinearElasticitySolutionWriter< DIM >::SetWriteElementWiseStrains(), and VtkNonlinearElasticitySolutionWriter< DIM >::Write().
The documentation for this class was generated from the following files:
continuum_mechanics/src/solver/VtkNonlinearElasticitySolutionWriter.hpp
continuum_mechanics/src/solver/VtkNonlinearElasticitySolutionWriter.cpp