Chaste: AbstractMesh< ELEMENT_DIM, SPACE_DIM > Class Template Reference
AbstractMesh< ELEMENT_DIM, SPACE_DIM > Class Template Reference
#include <AbstractMesh.hpp>
Inherits boost::noncopyable.
Inherited by AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >, AbstractTetrahedralMesh< DIM, DIM >, AbstractTetrahedralMesh< ELEMENT_DIM, ELEMENT_DIM >, AbstractTetrahedralMesh< SPACE_DIM, SPACE_DIM >, VertexMesh< ELEMENT_DIM, SPACE_DIM >, VertexMesh< DIM, DIM >, and VertexMesh< ELEMENT_DIM, ELEMENT_DIM >.
Classes
class NodeIterator
Public Types
typedef std::vector< Node
< SPACE_DIM >
* >::const_iterator BoundaryNodeIterator
Public Member Functions
NodeIterator GetNodeIteratorBegin (bool skipDeletedNodes=true)
NodeIterator GetNodeIteratorEnd ()
AbstractMesh ()
virtual ~AbstractMesh ()
virtual unsigned GetNumNodes () const
unsigned GetNumBoundaryNodes () const
virtual unsigned GetNumAllNodes () const
unsigned GetNumNodeAttributes () const
Node< SPACE_DIM > * GetNode (unsigned index) const
virtual Node< SPACE_DIM > * GetNodeOrHaloNode (unsigned index) const
Node< SPACE_DIM > * GetNodeFromPrePermutationIndex (unsigned index) const
virtual void ReadNodesPerProcessorFile (const std::string &rNodesPerProcessorFile)
virtual DistributedVectorFactory * GetDistributedVectorFactory ()
virtual void SetDistributedVectorFactory (DistributedVectorFactory *pFactory)
virtual void PermuteNodes ()
BoundaryNodeIterator GetBoundaryNodeIteratorBegin () const
BoundaryNodeIterator GetBoundaryNodeIteratorEnd () const
std::string GetMeshFileBaseName () const
bool IsMeshOnDisk () const
const std::vector< unsigned > & rGetNodePermutation () const
virtual c_vector< double,
SPACE_DIM > GetVectorFromAtoB (const c_vector< double, SPACE_DIM > &rLocationA, const c_vector< double, SPACE_DIM > &rLocationB)
double GetDistanceBetweenNodes (unsigned indexA, unsigned indexB)
virtual double GetWidth (const unsigned &rDimension) const
virtual ChasteCuboid< SPACE_DIM > CalculateBoundingBox () const
virtual unsigned GetNearestNodeIndex (const ChastePoint< SPACE_DIM > &rTestPoint)
virtual void Scale (const double xFactor=1.0, const double yFactor=1.0, const double zFactor=1.0)
void Translate (const c_vector< double, SPACE_DIM > &rDisplacement)
void Translate (const double xMovement=0.0, const double yMovement=0.0, const double zMovement=0.0)
void Rotate (c_matrix< double, SPACE_DIM, SPACE_DIM > rotationMatrix)
void Rotate (c_vector< double, 3 > axis, double angle)
void RotateX (const double theta)
void RotateY (const double theta)
void RotateZ (const double theta)
void Rotate (double theta)
virtual void RefreshMesh ()
bool IsMeshChanging () const
unsigned CalculateMaximumContainingElementsPerProcess () const
void SetMeshHasChangedSinceLoading ()
Protected Member Functions
virtual void SetElementOwnerships ()
ChasteCuboid< SPACE_DIM > CalculateBoundingBox (const std::vector< Node< SPACE_DIM > * > &rNodes) const
Protected Attributes
std::vector< Node< SPACE_DIM > * > mNodes
std::vector< Node< SPACE_DIM > * > mBoundaryNodes
DistributedVectorFactory * mpDistributedVectorFactory
std::vector< unsigned > mNodePermutation
std::string mMeshFileBaseName
bool mMeshChangesDuringSimulation
Private Member Functions
virtual unsigned SolveNodeMapping (unsigned index) const =0
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Friends
class TestDistributedTetrahedralMesh
class NodesOnlyMesh
class QuadraticMeshHelper
class boost::serialization::access
Detailed Description
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM>
class AbstractMesh< ELEMENT_DIM, SPACE_DIM >
Abstract base class for all meshes.
Definition at line 60 of file AbstractMesh.hpp.
Member Typedef Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> typedef std::vector<Node<SPACE_DIM> *>::const_iterator AbstractMesh< ELEMENT_DIM, SPACE_DIM >::BoundaryNodeIterator
Definition of boundary node Iterator type.
Definition at line 143 of file AbstractMesh.hpp.
Constructor & Destructor Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> AbstractMesh< ELEMENT_DIM, SPACE_DIM >::AbstractMesh () [inline]
Constructor.
Definition at line 44 of file AbstractMesh.cpp.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> AbstractMesh< ELEMENT_DIM, SPACE_DIM >::~AbstractMesh () [inline, virtual]
Virtual destructor, since this class has virtual methods.
Definition at line 52 of file AbstractMesh.cpp.
References AbstractMesh< ELEMENT_DIM, SPACE_DIM >::mNodes, and AbstractMesh< ELEMENT_DIM, SPACE_DIM >::mpDistributedVectorFactory.
Member Function Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> ChasteCuboid< SPACE_DIM > AbstractMesh< ELEMENT_DIM, SPACE_DIM >::CalculateBoundingBox () const [inline, virtual]
Calculate the bounding box (width extremes for all dimensions of the mesh). Overridden in distributed case
Returns:
The minimum and maximum co-ordinates of any node in each dimension
Reimplemented in DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >, and DistributedTetrahedralMesh< DIM, DIM >.
Definition at line 273 of file AbstractMesh.cpp.
References AbstractMesh< ELEMENT_DIM, SPACE_DIM >::mNodes.
Referenced by AbstractMesh< ELEMENT_DIM, SPACE_DIM >::GetWidth(), NodesOnlyMesh< SPACE_DIM >::SetUpBoxCollection(), and Cylindrical2dMesh::UpdateTopAndBottom().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> ChasteCuboid< SPACE_DIM > AbstractMesh< ELEMENT_DIM, SPACE_DIM >::CalculateBoundingBox (const std::vector< Node< SPACE_DIM > * > & rNodes) const [inline, protected]
Calculate a bounding box from a set of nodes. A generalised version of the public CalculateBoundingBox method.
Parameters:
rNodes the list of nodes to calculate the bounding box for.
Returns:
the bounding box in the form of a ChasteCuboid.
Todo:
#1322 use a const version of NodeIterator here
Definition at line 223 of file AbstractMesh.cpp.
Referenced by CellBasedPdeHandlerOnCuboid< DIM >::ConstructBoundaryConditionsContainer(), Electrodes< DIM >::Electrodes(), CellBasedPdeHandler< DIM >::OpenResultsFiles(), and FineCoarseMeshPair< DIM >::SetUpBoxes().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> unsigned AbstractMesh< ELEMENT_DIM, SPACE_DIM >::CalculateMaximumContainingElementsPerProcess () const [inline]
Returns:
Iterates through local nodes and finds the maximum number of containing elements for all locally owned nodes Useful for determining FEM matrix fill.
Definition at line 480 of file AbstractMesh.cpp.
References AbstractMesh< ELEMENT_DIM, SPACE_DIM >::mNodes.
Referenced by AbstractTetrahedralMeshWriter< ELEMENT_DIM, SPACE_DIM >::WriteNclFile().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> AbstractMesh< ELEMENT_DIM, SPACE_DIM >::BoundaryNodeIterator AbstractMesh< ELEMENT_DIM, SPACE_DIM >::GetBoundaryNodeIteratorBegin () const [inline]
Returns:
a pointer to the first boundary node in the mesh.
Definition at line 165 of file AbstractMesh.cpp.
References AbstractMesh< ELEMENT_DIM, SPACE_DIM >::mBoundaryNodes.
Referenced by CellBasedPdeHandlerOnCuboid< DIM >::ConstructBoundaryConditionsContainer(), CellBasedPdeHandler< DIM >::ConstructBoundaryConditionsContainer(), BoundaryConditionsContainer< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::DefineConstantDirichletOnMeshBoundary(), and PapillaryFibreCalculator::GetRadiusVectorForOneElement().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> AbstractMesh< ELEMENT_DIM, SPACE_DIM >::BoundaryNodeIterator AbstractMesh< ELEMENT_DIM, SPACE_DIM >::GetBoundaryNodeIteratorEnd () const [inline]
Returns:
a pointer to *one past* the last boundary node in the mesh (for consistency with STL iterators).
Definition at line 171 of file AbstractMesh.cpp.
References AbstractMesh< ELEMENT_DIM, SPACE_DIM >::mBoundaryNodes.
Referenced by CellBasedPdeHandlerOnCuboid< DIM >::ConstructBoundaryConditionsContainer(), CellBasedPdeHandler< DIM >::ConstructBoundaryConditionsContainer(), BoundaryConditionsContainer< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::DefineConstantDirichletOnMeshBoundary(), and PapillaryFibreCalculator::GetRadiusVectorForOneElement().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> double AbstractMesh< ELEMENT_DIM, SPACE_DIM >::GetDistanceBetweenNodes (unsigned indexA, unsigned indexB) [inline]
Return the distance between two nodes.
This method calls GetVectorFromAtoB(), which is overridden in some daughter classes (e.g. Cylindrical2dMesh).
Parameters:
indexA a node index
indexB a node index
Returns:
distance between two nodes.
Definition at line 208 of file AbstractMesh.cpp.
References AbstractMesh< ELEMENT_DIM, SPACE_DIM >::GetVectorFromAtoB(), and AbstractMesh< ELEMENT_DIM, SPACE_DIM >::mNodes.
Referenced by MutableVertexMesh< ELEMENT_DIM, SPACE_DIM >::CheckForSwapsFromShortEdges(), VertexMesh< ELEMENT_DIM, SPACE_DIM >::GetEdgeLength(), VertexMesh< ELEMENT_DIM, SPACE_DIM >::GetNextEdgeGradientOfElementAtNode(), VertexMesh< ELEMENT_DIM, SPACE_DIM >::GetPreviousEdgeGradientOfElementAtNode(), VertexMesh< ELEMENT_DIM, SPACE_DIM >::GetSurfaceAreaOfElement(), MutableMesh< ELEMENT_DIM, SPACE_DIM >::SplitLongEdges(), and HeterotypicBoundaryLengthWriter< ELEMENT_DIM, SPACE_DIM >::Visit().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> DistributedVectorFactory * AbstractMesh< ELEMENT_DIM, SPACE_DIM >::GetDistributedVectorFactory () [inline, virtual]
Returns:
the DistributedVectorFactory.
Definition at line 132 of file AbstractMesh.cpp.
References AbstractMesh< ELEMENT_DIM, SPACE_DIM >::GetNumNodes(), PetscTools::IsParallel(), AbstractMesh< ELEMENT_DIM, SPACE_DIM >::mpDistributedVectorFactory, and AbstractMesh< ELEMENT_DIM, SPACE_DIM >::SetElementOwnerships().
Referenced by AbstractContinuumMechanicsSolver< DIM >::AllocateMatrixMemory(), HeartGeometryInformation< SPACE_DIM >::CalculateBoundingBoxOfSurface(), AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::CalculateDesignatedOwnershipOfBoundaryElement(), MixedDimensionMesh< ELEMENT_DIM, SPACE_DIM >::CalculateDesignatedOwnershipOfCableElement(), AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::CalculateDesignatedOwnershipOfElement(), AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::CalculateNodeExchange(), ElectrodesStimulusFactory< DIM >::CheckForElectrodesIntersection(), NodePartitioner< ELEMENT_DIM, SPACE_DIM >::DumbPartitioning(), HeartConfigRelatedCellFactory< SPACE_DIM >::FillInCellularTransmuralAreas(), Hdf5ToTxtConverter< ELEMENT_DIM, SPACE_DIM >::Hdf5ToTxtConverter(), Hdf5ToVtkConverter< ELEMENT_DIM, SPACE_DIM >::Hdf5ToVtkConverter(), AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::SetElementOwnerships(), CardiacElectroMechanicsProblem< DIM, ELEC_PROB_DIM >::Solve(), and VoltageInterpolaterOntoMechanicsMesh< DIM >::VoltageInterpolaterOntoMechanicsMesh().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> std::string AbstractMesh< ELEMENT_DIM, SPACE_DIM >::GetMeshFileBaseName () const [inline]
Returns:
mMeshFileBaseName.
Definition at line 177 of file AbstractMesh.cpp.
References EXCEPTION, AbstractMesh< ELEMENT_DIM, SPACE_DIM >::IsMeshOnDisk(), and AbstractMesh< ELEMENT_DIM, SPACE_DIM >::mMeshFileBaseName.
Referenced by AbstractTetrahedralMesh< SPACE_DIM, SPACE_DIM >::save().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> unsigned AbstractMesh< ELEMENT_DIM, SPACE_DIM >::GetNearestNodeIndex (const ChastePoint< SPACE_DIM > & rTestPoint) [inline, virtual]
GetNearestNodeIndex iterates through all nodes in the mesh and returns the global index with the smallest distance to the provided point.
This method is overridden in the distributed case to return the global node index.
This method uses GetVectorFromAtoB distance and hence may return a correct solution in non-Euclidean space, but only if this method is overridden in a subclass (see e.g. Cylindrical2dMesh for an example of this).
Parameters:
rTestPoint reference to the point
Returns:
node index
Reimplemented in DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >, and DistributedTetrahedralMesh< DIM, DIM >.
Definition at line 281 of file AbstractMesh.cpp.
References AbstractMesh< ELEMENT_DIM, SPACE_DIM >::GetVectorFromAtoB(), AbstractMesh< ELEMENT_DIM, SPACE_DIM >::mNodes, and ChastePoint< DIM >::rGetLocation().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> Node< SPACE_DIM > * AbstractMesh< ELEMENT_DIM, SPACE_DIM >::GetNode (unsigned index) const [inline]
Get the node with a given index in the mesh.
Parameters:
index the global index of the node
Returns:
a pointer to the node.
Definition at line 93 of file AbstractMesh.cpp.
References AbstractMesh< ELEMENT_DIM, SPACE_DIM >::mNodes, and AbstractMesh< ELEMENT_DIM, SPACE_DIM >::SolveNodeMapping().
Referenced by AbstractContinuumMechanicsSolver< DIM >::AddIdentityBlockForDummyPressureVariables(), AbstractNonlinearElasticitySolver< DIM >::AssembleOnBoundaryElement(), IncompressibleNonlinearElasticitySolver< DIM >::AssembleOnElement(), CompressibleNonlinearElasticitySolver< DIM >::AssembleOnElement(), HeartGeometryInformation< SPACE_DIM >::CalculateBoundingBoxOfSurface(), ElectrodesStimulusFactory< DIM >::CheckForElectrodesIntersection(), MutableMesh< ELEMENT_DIM, SPACE_DIM >::CheckIsVoronoi(), FineCoarseMeshPair< DIM >::ComputeCoarseElementsForFineNodes(), ElectrodesStimulusFactory< DIM >::ComputeElectrodeTotalFlux(), FineCoarseMeshPair< DIM >::ComputeFineElementsAndWeightsForCoarseNodes(), CellBasedPdeHandler< DIM >::ConstructBoundaryConditionsContainer(), AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructFromMesh(), QuadraticMesh< DIM >::CountVertices(), ExtendedBidomainTissue< SPACE_DIM >::CreateGGapConductivities(), PottsBasedCellPopulation< DIM >::CreateMutableMesh(), MutableMesh< ELEMENT_DIM, SPACE_DIM >::DeleteElement(), NodesOnlyMesh< SPACE_DIM >::DeleteNode(), CardiacElectroMechanicsProblem< DIM, ELEC_PROB_DIM >::DetermineWatchedNodes(), ExtendedBidomainTissue< SPACE_DIM >::ExtendedBidomainTissue(), CryptCellsGenerator< CELL_CYCLE_MODEL >::Generate(), HoneycombMeshGenerator::GetCircularMesh(), CaBasedCellPopulation< DIM >::GetLocationOfCellCentre(), Toroidal2dVertexMesh::GetMeshForVtk(), Cylindrical2dVertexMesh::GetMeshForVtk(), DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::GetNearestNodeIndex(), VertexMesh< ELEMENT_DIM, SPACE_DIM >::GetNeighbouringNodeIndices(), PottsBasedCellPopulation< DIM >::GetNode(), CaBasedCellPopulation< DIM >::GetNode(), CaBasedCellPopulation< DIM >::GetNodeCorrespondingToCell(), AbstractMesh< ELEMENT_DIM, SPACE_DIM >::GetNodeFromPrePermutationIndex(), NodesOnlyMesh< SPACE_DIM >::GetNodeOrHaloNode(), AbstractMesh< ELEMENT_DIM, SPACE_DIM >::GetNodeOrHaloNode(), NonlinearElasticityTools< DIM >::GetNodesByComponentValue(), PapillaryFibreCalculator::GetRadiusVectorForOneElement(), VertexBasedCellPopulation< DIM >::GetTetrahedralMeshUsingVertexMesh(), VertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::MakeVtkMesh(), MutableVertexMesh< ELEMENT_DIM, SPACE_DIM >::PerformIntersectionSwap(), MutableVertexMesh< ELEMENT_DIM, SPACE_DIM >::PerformNodeMerge(), MutableVertexMesh< ELEMENT_DIM, SPACE_DIM >::PerformT2Swap(), MutableMesh< ELEMENT_DIM, SPACE_DIM >::RescaleMeshFromBoundaryNode(), AbstractNonlinearElasticitySolver< DIM >::rGetSpatialSolution(), SolidMechanicsProblemDefinition< DIM >::SetFixedNodes(), NodeBasedCellPopulation< DIM >::SetNode(), Cylindrical2dNodesOnlyMesh::SetNode(), MutableMesh< ELEMENT_DIM, SPACE_DIM >::SplitLongEdges(), PottsBasedCellPopulation< DIM >::UpdateCellLocations(), CellBasedPdeHandler< DIM >::UseCoarsePdeMesh(), Cylindrical2dMesh::UseTheseElementsToDecideMeshing(), MutableVertexMesh< ELEMENT_DIM, SPACE_DIM >::WidenEdgeOrCorrectIntersectionLocationIfNecessary(), AbstractContinuumMechanicsSolver< DIM >::WriteCurrentPressureSolution(), CellBasedPdeHandler< DIM >::WritePdeSolution(), DiscreteSystemForceCalculator::WriteResultsToFile(), and CaBasedCellPopulation< DIM >::WriteVtkResultsToFile().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> Node< SPACE_DIM > * AbstractMesh< ELEMENT_DIM, SPACE_DIM >::GetNodeFromPrePermutationIndex (unsigned index) const [inline]
Get the node with a given index in the mesh, prior to any node permutation being applied. For non-permuted meshes, this will have the same effect as GetNode.
This method is intended for use by the archiving code, to enable checkpoint migration, so that we can load the correct cells and boundary conditions after the mesh has been re-partitioned.
If unsure, use GetNode in preference to this method!
Parameters:
index the global index of the node prior to a permutation being applied
Returns:
a pointer to the node
Definition at line 106 of file AbstractMesh.cpp.
References AbstractMesh< ELEMENT_DIM, SPACE_DIM >::GetNode(), and AbstractMesh< ELEMENT_DIM, SPACE_DIM >::mNodePermutation.
Referenced by BoundaryConditionsContainer< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::MergeFromArchive().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> AbstractMesh< ELEMENT_DIM, SPACE_DIM >::NodeIterator AbstractMesh< ELEMENT_DIM, SPACE_DIM >::GetNodeIteratorBegin (bool skipDeletedNodes = true) [inline]
Returns:
an iterator to the first node in the mesh.
Parameters:
skipDeletedNodes whether to include deleted nodes
Definition at line 526 of file AbstractMesh.hpp.
Referenced by AbstractCentreBasedCellPopulation< ELEMENT_DIM, SPACE_DIM >::AbstractCentreBasedCellPopulation(), VertexCryptBoundaryForce< DIM >::AddForceContribution(), NodesOnlyMesh< SPACE_DIM >::AddNodesToBoxes(), AbstractContinuumMechanicsSolver< DIM >::AllocateMatrixMemory(), NodesOnlyMesh< SPACE_DIM >::CalculateNodesOutsideLocalDomain(), MutableVertexMesh< ELEMENT_DIM, SPACE_DIM >::CheckForIntersections(), ElectrodesStimulusFactory< DIM >::ComputeElectrodeTotalFlux(), Cylindrical2dMesh::CreateMirrorNodes(), Electrodes< DIM >::Electrodes(), NodesOnlyMesh< SPACE_DIM >::IsANodeCloseToDomainBoundary(), NodeBasedCellPopulationWithParticles< DIM >::NodeBasedCellPopulationWithParticles(), VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::SetParallelFiles(), NodeVelocityWriter< ELEMENT_DIM, SPACE_DIM >::Visit(), XdmfMeshWriter< ELEMENT_DIM, SPACE_DIM >::WriteFilesUsingMesh(), VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::WriteFilesUsingMesh(), PottsMeshWriter< SPACE_DIM >::WriteFilesUsingMesh(), and AbstractTetrahedralMeshWriter< ELEMENT_DIM, SPACE_DIM >::WriteNclFile().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> AbstractMesh< ELEMENT_DIM, SPACE_DIM >::NodeIterator AbstractMesh< ELEMENT_DIM, SPACE_DIM >::GetNodeIteratorEnd () [inline]
Returns:
an iterator to one past the last node in the mesh.
Definition at line 533 of file AbstractMesh.hpp.
References AbstractMesh< ELEMENT_DIM, SPACE_DIM >::mNodes.
Referenced by VertexCryptBoundaryForce< DIM >::AddForceContribution(), NodesOnlyMesh< SPACE_DIM >::AddNodesToBoxes(), AbstractContinuumMechanicsSolver< DIM >::AllocateMatrixMemory(), NodesOnlyMesh< SPACE_DIM >::CalculateNodesOutsideLocalDomain(), MutableVertexMesh< ELEMENT_DIM, SPACE_DIM >::CheckForIntersections(), ElectrodesStimulusFactory< DIM >::ComputeElectrodeTotalFlux(), Cylindrical2dMesh::CreateMirrorNodes(), Electrodes< DIM >::Electrodes(), NodesOnlyMesh< SPACE_DIM >::IsANodeCloseToDomainBoundary(), NodeBasedCellPopulationWithParticles< DIM >::NodeBasedCellPopulationWithParticles(), VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::SetParallelFiles(), NodeVelocityWriter< ELEMENT_DIM, SPACE_DIM >::Visit(), XdmfMeshWriter< ELEMENT_DIM, SPACE_DIM >::WriteFilesUsingMesh(), VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::WriteFilesUsingMesh(), PottsMeshWriter< SPACE_DIM >::WriteFilesUsingMesh(), and AbstractTetrahedralMeshWriter< ELEMENT_DIM, SPACE_DIM >::WriteNclFile().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> Node< SPACE_DIM > * AbstractMesh< ELEMENT_DIM, SPACE_DIM >::GetNodeOrHaloNode (unsigned index) const [inline, virtual]
Get the node with a given index in the mesh (synonym of GetNode() unless overridden in a distributed mesh).
Parameters:
index the global index of the node
Returns:
a pointer to the node.
Reimplemented in DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >, NodesOnlyMesh< SPACE_DIM >, DistributedTetrahedralMesh< DIM, DIM >, NodesOnlyMesh< DIM >, and NodesOnlyMesh< 2 >.
Definition at line 100 of file AbstractMesh.cpp.
References AbstractMesh< ELEMENT_DIM, SPACE_DIM >::GetNode().
Referenced by QuadraticMeshHelper< DIM >::AddInternalNodesToElements(), and AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::CheckOutwardNormals().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> unsigned AbstractMesh< ELEMENT_DIM, SPACE_DIM >::GetNumAllNodes () const [inline, virtual]
Returns:
the total number of nodes (including those marked as deleted).
Reimplemented in DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >, and DistributedTetrahedralMesh< DIM, DIM >.
Definition at line 78 of file AbstractMesh.cpp.
References AbstractMesh< ELEMENT_DIM, SPACE_DIM >::mNodes.
Referenced by TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ExportToMesher(), HoneycombMeshGenerator::GetCircularMesh(), AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::GetMaximumNodeIndex(), TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::PermuteNodes(), MutableMesh< ELEMENT_DIM, SPACE_DIM >::ReIndex(), MutableMesh< ELEMENT_DIM, SPACE_DIM >::ReMesh(), Cylindrical2dMesh::ReMesh(), AbstractMesh< ELEMENT_DIM, SPACE_DIM >::Rotate(), AbstractMesh< ELEMENT_DIM, SPACE_DIM >::Translate(), Cylindrical2dMesh::UseTheseElementsToDecideMeshing(), PottsMeshWriter< SPACE_DIM >::WriteFilesUsingMesh(), and AbstractTetrahedralMeshWriter< ELEMENT_DIM, SPACE_DIM >::WriteNclFile().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> unsigned AbstractMesh< ELEMENT_DIM, SPACE_DIM >::GetNumBoundaryNodes () const [inline]
Returns:
the number of boundary nodes in the mesh.
Definition at line 72 of file AbstractMesh.cpp.
References AbstractMesh< ELEMENT_DIM, SPACE_DIM >::mBoundaryNodes.
Referenced by BoundaryConditionsContainer< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::DefineConstantDirichletOnMeshBoundary().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> unsigned AbstractMesh< ELEMENT_DIM, SPACE_DIM >::GetNumNodeAttributes () const [inline]
Returns:
the number of attributes on each node. Note, this implementation assumes that all nodes have the same number of attributes so that the first node in the container is indicative of the others.
Definition at line 84 of file AbstractMesh.cpp.
References AbstractMesh< ELEMENT_DIM, SPACE_DIM >::mNodes.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> unsigned AbstractMesh< ELEMENT_DIM, SPACE_DIM >::GetNumNodes () const [inline, virtual]
Returns:
the number of nodes that are actually in use.
Overridden in MutableMesh and DistributedTetrahedralMesh.
Reimplemented in DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >, MutableMesh< ELEMENT_DIM, SPACE_DIM >, NodesOnlyMesh< SPACE_DIM >, MutableVertexMesh< ELEMENT_DIM, SPACE_DIM >, VertexMesh< ELEMENT_DIM, SPACE_DIM >, PottsMesh< DIM >, DistributedTetrahedralMesh< DIM, DIM >, MutableMesh< ELEMENT_DIM, ELEMENT_DIM >, MutableMesh< 2, 2 >, MutableMesh< DIM, DIM >, MutableMesh< SPACE_DIM, SPACE_DIM >, NodesOnlyMesh< DIM >, NodesOnlyMesh< 2 >, MutableVertexMesh< 2, 2 >, MutableVertexMesh< DIM, DIM >, VertexMesh< ELEMENT_DIM, ELEMENT_DIM >, VertexMesh< DIM, DIM >, and PottsMesh< SPACE_DIM >.
Definition at line 66 of file AbstractMesh.cpp.
References AbstractMesh< ELEMENT_DIM, SPACE_DIM >::mNodes.
Referenced by AbstractContinuumMechanicsSolver< DIM >::AbstractContinuumMechanicsSolver(), CaBasedCellPopulation< DIM >::AddCell(), AbstractContinuumMechanicsSolver< DIM >::AddIdentityBlockForDummyPressureVariables(), CaBasedCellPopulation< DIM >::CaBasedCellPopulation(), AbstractFunctionalCalculator< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::Calculate(), CardiacElectroMechProbRegularGeom< DIM >::CardiacElectroMechProbRegularGeom(), ElectrodesStimulusFactory< DIM >::CheckForElectrodesIntersection(), CmguiDeformedSolutionsWriter< DIM >::CmguiDeformedSolutionsWriter(), FineCoarseMeshPair< DIM >::ComputeCoarseElementsForFineNodes(), ElectrodesStimulusFactory< DIM >::ComputeElectrodeTotalFlux(), FineCoarseMeshPair< DIM >::ComputeFineElementsAndWeightsForCoarseNodes(), CuboidMeshConstructor< ELEMENT_DIM, SPACE_DIM >::Construct(), QuadraticMesh< DIM >::ConstructCuboid(), QuadraticMesh< DIM >::ConstructFromLinearMeshReader(), AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructFromMesh(), QuadraticMesh< DIM >::ConstructRectangularMesh(), CmguiDeformedSolutionsWriter< DIM >::ConvertOutput(), QuadraticMesh< DIM >::CountVertices(), PottsBasedCellPopulation< DIM >::CreateMutableMesh(), HeartGeometryInformation< SPACE_DIM >::DetermineLayerForEachNode(), CardiacElectroMechanicsProblem< DIM, ELEC_PROB_DIM >::DetermineWatchedNodes(), ContinuumMechanicsNeumannBcsAssembler< DIM >::DoAssemble(), AbstractContinuumMechanicsAssembler< DIM, CAN_ASSEMBLE_VECTOR, CAN_ASSEMBLE_MATRIX >::DoAssemble(), NodePartitioner< ELEMENT_DIM, SPACE_DIM >::DumbPartitioning(), TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ExportToMesher(), HeartConfigRelatedCellFactory< SPACE_DIM >::FillInCellularTransmuralAreas(), CryptCellsGenerator< CELL_CYCLE_MODEL >::Generate(), SolidMechanicsProblemDefinition< DIM >::GetCompressibleMaterialLaw(), AbstractMesh< ELEMENT_DIM, SPACE_DIM >::GetDistributedVectorFactory(), SolidMechanicsProblemDefinition< DIM >::GetIncompressibleMaterialLaw(), NonlinearElasticityTools< DIM >::GetNodesByComponentValue(), PottsBasedCellPopulation< DIM >::GetNumNodes(), CaBasedCellPopulation< DIM >::GetNumNodes(), AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::GetNumVertices(), Hdf5ToTxtConverter< ELEMENT_DIM, SPACE_DIM >::Hdf5ToTxtConverter(), Hdf5ToVtkConverter< ELEMENT_DIM, SPACE_DIM >::Hdf5ToVtkConverter(), CardiacElectroMechanicsProblem< DIM, ELEC_PROB_DIM >::Initialise(), TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::PermuteNodes(), TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ReadNodesPerProcessorFile(), AbstractContinuumMechanicsSolver< DIM >::rGetPressures(), StokesFlowSolver< DIM >::rGetSpatialSolution(), AbstractNonlinearElasticitySolver< DIM >::rGetSpatialSolution(), ContinuumMechanicsProblemDefinition< DIM >::SetZeroDirichletNodes(), CardiacElectroMechanicsProblem< DIM, ELEC_PROB_DIM >::Solve(), CellBasedPdeHandler< DIM >::SolvePdeAndWriteResultsToFile(), StreeterFibreGenerator< SPACE_DIM >::StreeterFibreGenerator(), PottsBasedCellPopulation< DIM >::UpdateCellLocations(), CellBasedPdeHandler< DIM >::UseCoarsePdeMesh(), VoltageInterpolaterOntoMechanicsMesh< DIM >::VoltageInterpolaterOntoMechanicsMesh(), CmguiDeformedSolutionsWriter< DIM >::WriteDeformationPositions(), XdmfMeshWriter< ELEMENT_DIM, SPACE_DIM >::WriteFilesUsingMesh(), HeartGeometryInformation< SPACE_DIM >::WriteLayerForEachNode(), AbstractTetrahedralMeshWriter< ELEMENT_DIM, SPACE_DIM >::WriteNclFile(), CellBasedPdeHandler< DIM >::WritePdeSolution(), DiscreteSystemForceCalculator::WriteResultsToFile(), and CaBasedCellPopulation< DIM >::WriteVtkResultsToFile().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> c_vector< double, SPACE_DIM > AbstractMesh< ELEMENT_DIM, SPACE_DIM >::GetVectorFromAtoB (const c_vector< double, SPACE_DIM > & rLocationA, const c_vector< double, SPACE_DIM > & rLocationB) [inline, virtual]
Returns:
a vector between two points in space.
This method is overridden in some daughter classes (e.g. Cylindrical2dMesh).
Parameters:
rLocationA a c_vector of coordinates
rLocationB a c_vector of coordinates
Returns:
c_vector from location A to location B.
Reimplemented in VertexMesh< ELEMENT_DIM, SPACE_DIM >, VertexMesh< ELEMENT_DIM, ELEMENT_DIM >, and VertexMesh< DIM, DIM >.
Definition at line 200 of file AbstractMesh.cpp.
Referenced by CryptStatistics::CellIsInSection(), CryptStatistics::CellIsInSectionPeriodic(), AbstractMesh< ELEMENT_DIM, SPACE_DIM >::GetDistanceBetweenNodes(), AbstractMesh< ELEMENT_DIM, SPACE_DIM >::GetNearestNodeIndex(), NodeBasedCellPopulation< DIM >::GetNeighbouringNodeIndices(), NodeBasedCellPopulation< DIM >::GetVolumeOfCell(), and MutableMesh< ELEMENT_DIM, SPACE_DIM >::SplitEdge().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> double AbstractMesh< ELEMENT_DIM, SPACE_DIM >::GetWidth (const unsigned & rDimension) const [inline, virtual]
Calculate the 'width' of any dimension of the mesh.
This method is overridden in some daughter classes (e.g. Cylindrical2dMesh).
Parameters:
rDimension a dimension (0,1 or 2)
Returns:
The maximum distance between any nodes in this dimension.
Reimplemented in NodesOnlyMesh< SPACE_DIM >, Cylindrical2dVertexMesh, Toroidal2dVertexMesh, Cylindrical2dMesh, Cylindrical2dNodesOnlyMesh, NodesOnlyMesh< DIM >, and NodesOnlyMesh< 2 >.
Definition at line 216 of file AbstractMesh.cpp.
References AbstractMesh< ELEMENT_DIM, SPACE_DIM >::CalculateBoundingBox(), and AbstractMesh< ELEMENT_DIM, SPACE_DIM >::mNodes.
Referenced by CryptStatistics::CellIsInSectionPeriodic(), CryptStatistics::GetCryptSection(), PottsBasedCellPopulation< DIM >::GetWidth(), and CaBasedCellPopulation< DIM >::GetWidth().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> bool AbstractMesh< ELEMENT_DIM, SPACE_DIM >::IsMeshChanging () const [inline]
Returns:
Whether the mesh changes (used in archiving).
Definition at line 474 of file AbstractMesh.cpp.
References AbstractMesh< ELEMENT_DIM, SPACE_DIM >::mMeshChangesDuringSimulation.
Referenced by PottsMeshWriter< SPACE_DIM >::GetNextElement(), and PottsMeshWriter< SPACE_DIM >::WriteFilesUsingMesh().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> bool AbstractMesh< ELEMENT_DIM, SPACE_DIM >::IsMeshOnDisk () const [inline]
Get whether this mesh was read from file.
Returns:
whether this mesh was read from file
Definition at line 188 of file AbstractMesh.cpp.
References AbstractMesh< ELEMENT_DIM, SPACE_DIM >::mMeshFileBaseName.
Referenced by AbstractMesh< ELEMENT_DIM, SPACE_DIM >::GetMeshFileBaseName(), and AbstractTetrahedralMesh< SPACE_DIM, SPACE_DIM >::save().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void AbstractMesh< ELEMENT_DIM, SPACE_DIM >::PermuteNodes () [inline, virtual]
Permute the nodes so that they appear in a different order in mNodes (and their mIndex's are altered accordingly).
Reimplemented in TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >, TetrahedralMesh< DIM, DIM >, and TetrahedralMesh< 3, 3 >.
Definition at line 159 of file AbstractMesh.cpp.
References NEVER_REACHED.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void AbstractMesh< ELEMENT_DIM, SPACE_DIM >::ReadNodesPerProcessorFile (const std::string & rNodesPerProcessorFile) [inline, virtual]
Read in the number of nodes per processor from file.
Parameters:
rNodesPerProcessorFile the name of the file
Reimplemented in TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >, TetrahedralMesh< DIM, DIM >, and TetrahedralMesh< 3, 3 >.
Definition at line 119 of file AbstractMesh.cpp.
References NEVER_REACHED.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void AbstractMesh< ELEMENT_DIM, SPACE_DIM >::RefreshMesh () [inline, virtual]
This method allows the mesh properties to be re-calculated after one or more nodes have been moved.
Reimplemented in TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >, TetrahedralMesh< DIM, DIM >, and TetrahedralMesh< 3, 3 >.
Definition at line 469 of file AbstractMesh.cpp.
Referenced by AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructCuboid(), AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructFromMesh(), AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructLinearMesh(), AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructRectangularMesh(), AbstractMesh< ELEMENT_DIM, SPACE_DIM >::Rotate(), AbstractMesh< ELEMENT_DIM, SPACE_DIM >::Scale(), and AbstractMesh< ELEMENT_DIM, SPACE_DIM >::Translate().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> const std::vector< unsigned > & AbstractMesh< ELEMENT_DIM, SPACE_DIM >::rGetNodePermutation () const [inline]
Returns:
mNodePermutation.
When empty (most meshes) there is no node permutation When non-empty (parallel distributed meshes) then for a given original_index mNodePermutation[original_index] holds the new assigned index of that node in memory
Definition at line 194 of file AbstractMesh.cpp.
References AbstractMesh< ELEMENT_DIM, SPACE_DIM >::mNodePermutation.
Referenced by QuadraticMeshHelper< DIM >::AddInternalNodesToElements(), HeartGeometryInformation< SPACE_DIM >::GetNodesAtSurface(), AbstractTetrahedralMesh< SPACE_DIM, SPACE_DIM >::save(), and AbstractTetrahedralMeshWriter< ELEMENT_DIM, SPACE_DIM >::WriteNclFile().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void AbstractMesh< ELEMENT_DIM, SPACE_DIM >::Rotate (double theta) [inline]
Rotating a 2D mesh equates that rotation around the z-axis.
Parameters:
theta is the angle of rotation in radians
Definition at line 463 of file AbstractMesh.cpp.
References AbstractMesh< ELEMENT_DIM, SPACE_DIM >::RotateZ().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void AbstractMesh< ELEMENT_DIM, SPACE_DIM >::Rotate (c_vector< double, 3 > axis, double angle) [inline]
Do an angle axis rotation.
Parameters:
axis is the axis of rotation (does not need to be normalised)
angle is the angle of rotation in radians
Definition at line 386 of file AbstractMesh.cpp.
References AbstractMesh< ELEMENT_DIM, SPACE_DIM >::Rotate().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void AbstractMesh< ELEMENT_DIM, SPACE_DIM >::Rotate (c_matrix< double, SPACE_DIM, SPACE_DIM > rotationMatrix) [inline]
Do a general mesh rotation with a positive determinant orthonormal rotation matrix. This is the rotation method that actually does the work.
Parameters:
rotationMatrix is a Ublas rotation matrix of the correct form
Definition at line 372 of file AbstractMesh.cpp.
References AbstractMesh< ELEMENT_DIM, SPACE_DIM >::GetNumAllNodes(), AbstractMesh< ELEMENT_DIM, SPACE_DIM >::mNodes, and AbstractMesh< ELEMENT_DIM, SPACE_DIM >::RefreshMesh().
Referenced by AbstractMesh< ELEMENT_DIM, SPACE_DIM >::Rotate(), AbstractMesh< ELEMENT_DIM, SPACE_DIM >::RotateX(), AbstractMesh< ELEMENT_DIM, SPACE_DIM >::RotateY(), and AbstractMesh< ELEMENT_DIM, SPACE_DIM >::RotateZ().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void AbstractMesh< ELEMENT_DIM, SPACE_DIM >::RotateX (const double theta) [inline]
Rotate the mesh about the x-axis.
Parameters:
theta is the angle of rotation in radians
Definition at line 411 of file AbstractMesh.cpp.
References EXCEPTION, and AbstractMesh< ELEMENT_DIM, SPACE_DIM >::Rotate().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void AbstractMesh< ELEMENT_DIM, SPACE_DIM >::RotateY (const double theta) [inline]
Rotate the mesh about the y-axis.
Parameters:
theta is the angle of rotation in radians
Definition at line 427 of file AbstractMesh.cpp.
References EXCEPTION, and AbstractMesh< ELEMENT_DIM, SPACE_DIM >::Rotate().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void AbstractMesh< ELEMENT_DIM, SPACE_DIM >::RotateZ (const double theta) [inline]
Rotate the mesh about the z-axis.
Parameters:
theta is the angle of rotation in radians
Definition at line 445 of file AbstractMesh.cpp.
References EXCEPTION, and AbstractMesh< ELEMENT_DIM, SPACE_DIM >::Rotate().
Referenced by AbstractMesh< ELEMENT_DIM, SPACE_DIM >::Rotate().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void AbstractMesh< ELEMENT_DIM, SPACE_DIM >::Scale (const double xFactor = 1.0, const double yFactor = 1.0, const double zFactor = 1.0) [inline, virtual]
Scale the mesh.
Parameters:
xFactor is the scale in the x-direction (defaults to 1.0)
yFactor is the scale in the y-direction (defaults to 1.0)
zFactor is the scale in the z-direction (defaults to 1.0)
Reimplemented in DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >, Cylindrical2dVertexMesh, and DistributedTetrahedralMesh< DIM, DIM >.
Definition at line 315 of file AbstractMesh.cpp.
References AbstractMesh< ELEMENT_DIM, SPACE_DIM >::mNodes, and AbstractMesh< ELEMENT_DIM, SPACE_DIM >::RefreshMesh().
Referenced by AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructRegularSlabMesh().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> template<class Archive > void AbstractMesh< ELEMENT_DIM, SPACE_DIM >::serialize (Archive & archive, const unsigned int version) [inline, private]
Serialize the mesh.
Parameters:
archive the archive
version the current version of this class
Reimplemented in DistributedQuadraticMesh< DIM >, DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >, MixedDimensionMesh< ELEMENT_DIM, SPACE_DIM >, NodesOnlyMesh< SPACE_DIM >, NonCachedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >, QuadraticMesh< DIM >, TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >, Cylindrical2dVertexMesh, MutableVertexMesh< ELEMENT_DIM, SPACE_DIM >, Toroidal2dVertexMesh, Cylindrical2dMesh, Cylindrical2dNodesOnlyMesh, DistributedTetrahedralMesh< DIM, DIM >, NodesOnlyMesh< DIM >, NodesOnlyMesh< 2 >, TetrahedralMesh< DIM, DIM >, TetrahedralMesh< 3, 3 >, MutableVertexMesh< 2, 2 >, and MutableVertexMesh< DIM, DIM >.
Definition at line 87 of file AbstractMesh.hpp.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void AbstractMesh< ELEMENT_DIM, SPACE_DIM >::SetDistributedVectorFactory (DistributedVectorFactory * pFactory) [inline, virtual]
Set method for mpDistributedVectorFactory. Must be called before the mesh is used for anything. This only actually impacts the DistributedTetrahedralMesh subclass, in which the supplied factory is then used to specify the node distribution among the processes.
Parameters:
pFactory a factory to use for this mesh
Reimplemented in DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >, and DistributedTetrahedralMesh< DIM, DIM >.
Definition at line 145 of file AbstractMesh.cpp.
References EXCEPTION, PetscTools::GetNumProcs(), DistributedVectorFactory::GetNumProcs(), and AbstractMesh< ELEMENT_DIM, SPACE_DIM >::mpDistributedVectorFactory.
Referenced by AbstractTetrahedralMesh< SPACE_DIM, SPACE_DIM >::load().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void AbstractMesh< ELEMENT_DIM, SPACE_DIM >::SetElementOwnerships () [inline, protected, virtual]
Does nothing. Used in derived classes which have elements
Reimplemented in AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >, DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >, AbstractTetrahedralMesh< ELEMENT_DIM, ELEMENT_DIM >, AbstractTetrahedralMesh< DIM, DIM >, AbstractTetrahedralMesh< SPACE_DIM, SPACE_DIM >, and DistributedTetrahedralMesh< DIM, DIM >.
Definition at line 126 of file AbstractMesh.cpp.
Referenced by AbstractMesh< ELEMENT_DIM, SPACE_DIM >::GetDistributedVectorFactory().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void AbstractMesh< ELEMENT_DIM, SPACE_DIM >::SetMeshHasChangedSinceLoading () [inline]
Set whether the mesh has been modified since it was read from file. This prevents the archiving code just blithely storing the original, unmodified, mesh.
Definition at line 495 of file AbstractMesh.cpp.
References AbstractMesh< ELEMENT_DIM, SPACE_DIM >::mMeshFileBaseName.
Referenced by CylindricalHoneycombMeshGenerator::CylindricalHoneycombMeshGenerator(), VertexBasedCellPopulation< DIM >::GetTetrahedralMeshUsingVertexMesh(), HoneycombMeshGenerator::HoneycombMeshGenerator(), and NodesOnlyMesh< SPACE_DIM >::ReMesh().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> virtual unsigned AbstractMesh< ELEMENT_DIM, SPACE_DIM >::SolveNodeMapping (unsigned index) const [private, pure virtual]
Pure virtual solve node mapping method. For a node with a given global index, get the local index used by this process.
Overridden in TetrahedralMesh DistributedTetrahedralMesh and Vertex Mesh classes.
Parameters:
index the global index of the node
Returns:
local index
Implemented in DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >, NodesOnlyMesh< SPACE_DIM >, TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >, VertexMesh< ELEMENT_DIM, SPACE_DIM >, PottsMesh< DIM >, DistributedTetrahedralMesh< DIM, DIM >, NodesOnlyMesh< DIM >, NodesOnlyMesh< 2 >, TetrahedralMesh< DIM, DIM >, TetrahedralMesh< 3, 3 >, VertexMesh< ELEMENT_DIM, ELEMENT_DIM >, VertexMesh< DIM, DIM >, and PottsMesh< SPACE_DIM >.
Referenced by AbstractMesh< ELEMENT_DIM, SPACE_DIM >::GetNode().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void AbstractMesh< ELEMENT_DIM, SPACE_DIM >::Translate (const double xMovement = 0.0, const double yMovement = 0.0, const double zMovement = 0.0) [inline]
Translate the mesh given the coordinate displacements separately.
Parameters:
xMovement is the x-displacement (defaults to 0.0)
yMovement is the y-displacement (defaults to 0.0)
zMovement is the z-displacement (defaults to 0.0)
Definition at line 337 of file AbstractMesh.cpp.
References AbstractMesh< ELEMENT_DIM, SPACE_DIM >::Translate().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void AbstractMesh< ELEMENT_DIM, SPACE_DIM >::Translate (const c_vector< double, SPACE_DIM > & rDisplacement) [inline]
Translate the mesh given the displacement vector. This is the translation method that actually does the work.
Parameters:
rDisplacement is a translation vector of the correct size
Definition at line 358 of file AbstractMesh.cpp.
References AbstractMesh< ELEMENT_DIM, SPACE_DIM >::GetNumAllNodes(), AbstractMesh< ELEMENT_DIM, SPACE_DIM >::mNodes, and AbstractMesh< ELEMENT_DIM, SPACE_DIM >::RefreshMesh().
Referenced by HoneycombMeshGenerator::GetCircularMesh(), AbstractMesh< ELEMENT_DIM, SPACE_DIM >::Translate(), and CellBasedPdeHandler< DIM >::UseCoarsePdeMesh().
Friends And Related Function Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> friend class boost::serialization::access [friend]
Needed for serialization.
Reimplemented in AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >, DistributedQuadraticMesh< DIM >, DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >, MixedDimensionMesh< ELEMENT_DIM, SPACE_DIM >, MutableMesh< ELEMENT_DIM, SPACE_DIM >, NodesOnlyMesh< SPACE_DIM >, NonCachedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >, QuadraticMesh< DIM >, TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >, Cylindrical2dVertexMesh, MutableVertexMesh< ELEMENT_DIM, SPACE_DIM >, Toroidal2dVertexMesh, VertexMesh< ELEMENT_DIM, SPACE_DIM >, Cylindrical2dMesh, Cylindrical2dNodesOnlyMesh, PottsMesh< DIM >, AbstractTetrahedralMesh< ELEMENT_DIM, ELEMENT_DIM >, AbstractTetrahedralMesh< DIM, DIM >, AbstractTetrahedralMesh< SPACE_DIM, SPACE_DIM >, DistributedTetrahedralMesh< DIM, DIM >, MutableMesh< ELEMENT_DIM, ELEMENT_DIM >, MutableMesh< 2, 2 >, MutableMesh< DIM, DIM >, MutableMesh< SPACE_DIM, SPACE_DIM >, NodesOnlyMesh< DIM >, NodesOnlyMesh< 2 >, TetrahedralMesh< DIM, DIM >, TetrahedralMesh< 3, 3 >, MutableVertexMesh< 2, 2 >, MutableVertexMesh< DIM, DIM >, VertexMesh< ELEMENT_DIM, ELEMENT_DIM >, VertexMesh< DIM, DIM >, and PottsMesh< SPACE_DIM >.
Definition at line 79 of file AbstractMesh.hpp.
Member Data Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> std::vector<Node<SPACE_DIM> *> AbstractMesh< ELEMENT_DIM, SPACE_DIM >::mBoundaryNodes [protected]
Vector of pointers to boundary nodes in the mesh.
Definition at line 99 of file AbstractMesh.hpp.
Referenced by QuadraticMeshHelper< DIM >::AddNodeToBoundaryElement(), TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::Clear(), DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructCuboid(), AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructCuboid(), AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructFromMesh(), TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructFromMeshReader(), DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructFromMeshReader(), DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructLinearMesh(), AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructLinearMesh(), DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructRectangularMesh(), AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructRectangularMesh(), MutableMesh< ELEMENT_DIM, SPACE_DIM >::DeleteBoundaryNodeAt(), AbstractMesh< ELEMENT_DIM, SPACE_DIM >::GetBoundaryNodeIteratorBegin(), AbstractMesh< ELEMENT_DIM, SPACE_DIM >::GetBoundaryNodeIteratorEnd(), AbstractMesh< ELEMENT_DIM, SPACE_DIM >::GetNumBoundaryNodes(), TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ImportFromMesher(), QuadraticMesh< DIM >::MakeNewInternalNode(), and MutableMesh< ELEMENT_DIM, SPACE_DIM >::ReMesh().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> bool AbstractMesh< ELEMENT_DIM, SPACE_DIM >::mMeshChangesDuringSimulation [protected]
Whether this mesh changes during simulation (used to know whether to write a new one to file)
Definition at line 120 of file AbstractMesh.hpp.
Referenced by AbstractMesh< ELEMENT_DIM, SPACE_DIM >::IsMeshChanging(), MutableMesh< ELEMENT_DIM, SPACE_DIM >::MutableMesh(), MutableVertexMesh< ELEMENT_DIM, SPACE_DIM >::MutableVertexMesh(), AbstractTetrahedralMesh< SPACE_DIM, SPACE_DIM >::save(), AbstractMesh< SPACE_DIM, SPACE_DIM >::serialize(), and VertexMesh< ELEMENT_DIM, SPACE_DIM >::VertexMesh().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> std::string AbstractMesh< ELEMENT_DIM, SPACE_DIM >::mMeshFileBaseName [protected]
If the mesh is constructed from file using a MeshReader, this member variable stores the base name of these files.
Definition at line 115 of file AbstractMesh.hpp.
Referenced by TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructFromMeshReader(), DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructFromMeshReader(), AbstractMesh< ELEMENT_DIM, SPACE_DIM >::GetMeshFileBaseName(), AbstractMesh< ELEMENT_DIM, SPACE_DIM >::IsMeshOnDisk(), and AbstractMesh< ELEMENT_DIM, SPACE_DIM >::SetMeshHasChangedSinceLoading().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> std::vector<unsigned> AbstractMesh< ELEMENT_DIM, SPACE_DIM >::mNodePermutation [protected]
Vector containing node permutation information. When empty (most meshes) there is no node permutation When non-empty (parallel distributed meshes) then for a given original_index mNodePermutation[original_index] holds the new assigned index of that node in memory
Definition at line 109 of file AbstractMesh.hpp.
Referenced by DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ComputeMeshPartitioning(), MixedDimensionMesh< ELEMENT_DIM, SPACE_DIM >::ConstructFromMeshReader(), DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructFromMeshReader(), AbstractMesh< ELEMENT_DIM, SPACE_DIM >::GetNodeFromPrePermutationIndex(), DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ParMetisLibraryNodeAndElementPartitioning(), TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::PermuteNodes(), DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ReorderNodes(), and AbstractMesh< ELEMENT_DIM, SPACE_DIM >::rGetNodePermutation().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> std::vector<Node<SPACE_DIM> *> AbstractMesh< ELEMENT_DIM, SPACE_DIM >::mNodes [protected]
Vector of pointers to nodes in the mesh.
Definition at line 96 of file AbstractMesh.hpp.
Referenced by MutableVertexMesh< ELEMENT_DIM, SPACE_DIM >::AddNode(), MutableMesh< ELEMENT_DIM, SPACE_DIM >::AddNode(), NodesOnlyMesh< SPACE_DIM >::AddNodeWithFixedIndex(), NodesOnlyMesh< SPACE_DIM >::CalculateBoundaryNodePairs(), AbstractMesh< ELEMENT_DIM, SPACE_DIM >::CalculateBoundingBox(), NodesOnlyMesh< SPACE_DIM >::CalculateInteriorNodePairs(), AbstractMesh< ELEMENT_DIM, SPACE_DIM >::CalculateMaximumContainingElementsPerProcess(), AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::CalculateMaximumNodeConnectivityPerProcess(), VertexMesh< ELEMENT_DIM, SPACE_DIM >::Clear(), TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::Clear(), QuadraticMesh< DIM >::ConstructCuboid(), DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructCuboid(), AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructCuboid(), AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructFromMesh(), TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructFromMeshReader(), NodesOnlyMesh< SPACE_DIM >::ConstructFromMeshReader(), DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructFromMeshReader(), QuadraticMesh< DIM >::ConstructLinearMesh(), DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructLinearMesh(), AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructLinearMesh(), NodesOnlyMesh< SPACE_DIM >::ConstructNodesWithoutMesh(), QuadraticMesh< DIM >::ConstructRectangularMesh(), DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructRectangularMesh(), AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructRectangularMesh(), Cylindrical2dMesh::CreateMirrorNodes(), Cylindrical2dMesh::Cylindrical2dMesh(), MutableMesh< ELEMENT_DIM, SPACE_DIM >::DeleteBoundaryNodeAt(), NodesOnlyMesh< SPACE_DIM >::DeleteNode(), MutableMesh< ELEMENT_DIM, SPACE_DIM >::DeleteNode(), MutableVertexMesh< ELEMENT_DIM, SPACE_DIM >::DeleteNodePriorToReMesh(), MutableMesh< ELEMENT_DIM, SPACE_DIM >::DeleteNodePriorToReMesh(), MutableVertexMesh< ELEMENT_DIM, SPACE_DIM >::DivideEdge(), TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ExportToMesher(), VertexMesh< ELEMENT_DIM, SPACE_DIM >::GenerateVerticesFromElementCircumcentres(), TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::GetAngleBetweenNodes(), AbstractMesh< ELEMENT_DIM, SPACE_DIM >::GetDistanceBetweenNodes(), AbstractMesh< ELEMENT_DIM, SPACE_DIM >::GetNearestNodeIndex(), AbstractMesh< ELEMENT_DIM, SPACE_DIM >::GetNode(), AbstractMesh< ELEMENT_DIM, SPACE_DIM >::GetNodeIteratorEnd(), DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::GetNodeOrHaloNode(), AbstractMesh< ELEMENT_DIM, SPACE_DIM >::GetNumAllNodes(), DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::GetNumLocalNodes(), AbstractMesh< ELEMENT_DIM, SPACE_DIM >::GetNumNodeAttributes(), VertexMesh< ELEMENT_DIM, SPACE_DIM >::GetNumNodes(), MutableVertexMesh< ELEMENT_DIM, SPACE_DIM >::GetNumNodes(), NodesOnlyMesh< SPACE_DIM >::GetNumNodes(), MutableMesh< ELEMENT_DIM, SPACE_DIM >::GetNumNodes(), AbstractMesh< ELEMENT_DIM, SPACE_DIM >::GetNumNodes(), AbstractMesh< ELEMENT_DIM, SPACE_DIM >::GetWidth(), MutableVertexMesh< ELEMENT_DIM, SPACE_DIM >::IdentifySwapType(), TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ImportFromMesher(), AbstractMesh< ELEMENT_DIM, SPACE_DIM >::NodeIterator::IsAtEnd(), MutableMesh< SPACE_DIM, SPACE_DIM >::load(), QuadraticMesh< DIM >::MakeNewInternalNode(), MutableMesh< ELEMENT_DIM, SPACE_DIM >::MoveMergeNode(), MutableMesh< ELEMENT_DIM, SPACE_DIM >::MutableMesh(), MutableVertexMesh< ELEMENT_DIM, SPACE_DIM >::MutableVertexMesh(), AbstractMesh< ELEMENT_DIM, SPACE_DIM >::NodeIterator::NodeIterator(), MutableVertexMesh< ELEMENT_DIM, SPACE_DIM >::PerformIntersectionSwap(), MutableVertexMesh< ELEMENT_DIM, SPACE_DIM >::PerformNodeMerge(), MutableVertexMesh< ELEMENT_DIM, SPACE_DIM >::PerformT3Swap(), TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::PermuteNodes(), Cylindrical2dMesh::ReconstructCylindricalMesh(), MutableMesh< ELEMENT_DIM, SPACE_DIM >::RefineElement(), DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::RegisterNode(), MutableMesh< ELEMENT_DIM, SPACE_DIM >::ReIndex(), MutableMesh< ELEMENT_DIM, SPACE_DIM >::ReMesh(), Cylindrical2dMesh::ReMesh(), MutableVertexMesh< ELEMENT_DIM, SPACE_DIM >::RemoveDeletedNodes(), NodesOnlyMesh< SPACE_DIM >::RemoveDeletedNodes(), DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ReorderNodes(), MutableMesh< ELEMENT_DIM, SPACE_DIM >::RescaleMeshFromBoundaryNode(), NodesOnlyMesh< SPACE_DIM >::ResizeBoxCollection(), AbstractMesh< ELEMENT_DIM, SPACE_DIM >::Rotate(), MutableMesh< SPACE_DIM, SPACE_DIM >::save(), AbstractMesh< ELEMENT_DIM, SPACE_DIM >::Scale(), MutableVertexMesh< ELEMENT_DIM, SPACE_DIM >::SetNode(), MutableMesh< ELEMENT_DIM, SPACE_DIM >::SetNode(), VertexMesh< ELEMENT_DIM, SPACE_DIM >::SolveNodeMapping(), TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::SolveNodeMapping(), MutableMesh< ELEMENT_DIM, SPACE_DIM >::SplitEdge(), AbstractMesh< ELEMENT_DIM, SPACE_DIM >::Translate(), NodesOnlyMesh< SPACE_DIM >::UpdateNodeIndices(), VertexMesh< ELEMENT_DIM, SPACE_DIM >::VertexMesh(), and AbstractMesh< ELEMENT_DIM, SPACE_DIM >::~AbstractMesh().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> DistributedVectorFactory* AbstractMesh< ELEMENT_DIM, SPACE_DIM >::mpDistributedVectorFactory [protected]
DistributedVectorFactory capable of reproducing the given number of nodes owned by each processor.
Definition at line 102 of file AbstractMesh.hpp.
Referenced by DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructCuboid(), DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructFromMeshReader(), DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructLinearMesh(), DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructRectangularMesh(), AbstractMesh< ELEMENT_DIM, SPACE_DIM >::GetDistributedVectorFactory(), AbstractTetrahedralMesh< SPACE_DIM, SPACE_DIM >::load(), TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ReadNodesPerProcessorFile(), MutableMesh< ELEMENT_DIM, SPACE_DIM >::ReMesh(), AbstractMesh< SPACE_DIM, SPACE_DIM >::serialize(), AbstractMesh< ELEMENT_DIM, SPACE_DIM >::SetDistributedVectorFactory(), and AbstractMesh< ELEMENT_DIM, SPACE_DIM >::~AbstractMesh().
The documentation for this class was generated from the following files:
mesh/src/common/AbstractMesh.hpp
mesh/src/common/AbstractMesh.cpp