Chaste: BidomainCorrectionTermAssembler< ELEM_DIM, SPACE_DIM > Class Template Reference
BidomainCorrectionTermAssembler< ELEM_DIM, SPACE_DIM > Class Template Reference
#include <BidomainCorrectionTermAssembler.hpp>
Inherits AbstractCorrectionTermAssembler< ELEM_DIM, SPACE_DIM, 2 >.
Public Member Functions
BidomainCorrectionTermAssembler (AbstractTetrahedralMesh< ELEM_DIM, SPACE_DIM > *pMesh, BidomainTissue< SPACE_DIM > *pTissue)
Protected Member Functions
c_vector< double, 2 *(ELEM_DIM+1)> ComputeVectorTerm (c_vector< double, ELEM_DIM+1 > &rPhi, c_matrix< double, SPACE_DIM, ELEM_DIM+1 > &rGradPhi, ChastePoint< SPACE_DIM > &rX, c_vector< double, 2 > &rU, c_matrix< double, 2, SPACE_DIM > &rGradU, Element< ELEM_DIM, SPACE_DIM > *pElement)
Protected Attributes
HeartConfig * mpConfig
Detailed Description
template<unsigned ELEM_DIM, unsigned SPACE_DIM>
class BidomainCorrectionTermAssembler< ELEM_DIM, SPACE_DIM >
An assembler which computes the correction term to add to the RHS vector if using state variable interpolation (SVI), as well as determining which elements should be corrected on. The formula to determine which elements SVI is used is delta Iionic > TOL, where delta Iionic is the max difference between nodal ionic values, and TOL is chosen conservatively to be 1uA/cm^2^. See wiki page ChasteGuides/StateVariableInterpolation for more details.
Definition at line 53 of file BidomainCorrectionTermAssembler.hpp.
Constructor & Destructor Documentation
template<unsigned ELEM_DIM, unsigned SPACE_DIM> BidomainCorrectionTermAssembler< ELEM_DIM, SPACE_DIM >::BidomainCorrectionTermAssembler (AbstractTetrahedralMesh< ELEM_DIM, SPACE_DIM > * pMesh, BidomainTissue< SPACE_DIM > * pTissue) [inline]
Constructor
Parameters:
pMesh pointer to the mesh
pTissue pointer to the PDE
Definition at line 42 of file BidomainCorrectionTermAssembler.cpp.
References HeartConfig::GetUseStateVariableInterpolation(), HeartConfig::Instance(), and BidomainCorrectionTermAssembler< ELEM_DIM, SPACE_DIM >::mpConfig.
Member Function Documentation
template<unsigned ELEM_DIM, unsigned SPACE_DIM> c_vector< double, 2 *(ELEM_DIM+1)> BidomainCorrectionTermAssembler< ELEM_DIM, SPACE_DIM >::ComputeVectorTerm (c_vector< double, ELEM_DIM+1 > & rPhi, c_matrix< double, SPACE_DIM, ELEM_DIM+1 > & rGradPhi, ChastePoint< SPACE_DIM > & rX, c_vector< double, 2 > & rU, c_matrix< double, 2, SPACE_DIM > & rGradU, Element< ELEM_DIM, SPACE_DIM > * pElement) [inline, protected]
This method is called by AssembleOnElement and tells the assembler the contribution to add to the element stiffness vector.
Parameters:
rPhi The basis functions, rPhi(i) = phi_i, i=1..numBases
rGradPhi Basis gradients, rGradPhi(i,j) = d(phi_j)/d(X_i)
rX The point in space
rU The unknown as a vector, u(i) = u_i
rGradU The gradient of the unknown as a matrix, rGradU(i,j) = d(u_i)/d(X_j)
pElement Pointer to the element
Returns:
stencil matrix
Definition at line 52 of file BidomainCorrectionTermAssembler.cpp.
References AbstractCardiacCellInterface::GetIIonic(), AbstractElement< ELEMENT_DIM, SPACE_DIM >::GetNodeGlobalIndex(), HeartConfig::GetSurfaceAreaToVolumeRatio(), AbstractCorrectionTermAssembler< ELEM_DIM, SPACE_DIM, 2 >::mIionicInterp, AbstractCardiacFeVolumeIntegralAssembler< ELEM_DIM, SPACE_DIM, PROBLEM_DIM, true, false, CARDIAC >::mpCardiacTissue, BidomainCorrectionTermAssembler< ELEM_DIM, SPACE_DIM >::mpConfig, and AbstractCorrectionTermAssembler< ELEM_DIM, SPACE_DIM, 2 >::mStateVariablesAtQuadPoint.
Member Data Documentation
template<unsigned ELEM_DIM, unsigned SPACE_DIM> HeartConfig* BidomainCorrectionTermAssembler< ELEM_DIM, SPACE_DIM >::mpConfig [protected]
Local cache of the configuration singleton instance
Reimplemented from AbstractCardiacFeVolumeIntegralAssembler< ELEM_DIM, SPACE_DIM, PROBLEM_DIM, true, false, CARDIAC >.
Definition at line 58 of file BidomainCorrectionTermAssembler.hpp.
Referenced by BidomainCorrectionTermAssembler< ELEM_DIM, SPACE_DIM >::BidomainCorrectionTermAssembler(), and BidomainCorrectionTermAssembler< ELEM_DIM, SPACE_DIM >::ComputeVectorTerm().
The documentation for this class was generated from the following files:
heart/src/solver/electrics/bidomain/BidomainCorrectionTermAssembler.hpp
heart/src/solver/electrics/bidomain/BidomainCorrectionTermAssembler.cpp