Chaste: heart/src/fortests/SimpleBathProblemSetup.hpp File Reference
SimpleBathProblemSetup.hpp File Reference
#include "AbstractCardiacCellFactory.hpp"
#include "SimpleStimulus.hpp"
#include "LuoRudy1991.hpp"
#include "HeartRegionCodes.hpp"
Classes
class BathCellFactory< DIM, CELLTYPE >
Functions
template<class MeshType >
void SetCircularTissueIn2dMesh (MeshType *pMesh, double centreX, double centreY, double radius)
template<class MeshType >
MeshType * Load2dMeshAndSetCircularTissue (const std::string &rMeshPath, double centreX, double centreY, double radius)
template<>
DistributedTetrahedralMesh< 2, 2 > * Load2dMeshAndSetCircularTissue (const std::string &rMeshPath, double centreX, double centreY, double radius)
Detailed Description
Some helper classes and functions for setting up a simple bath problem for testing.
Definition in file SimpleBathProblemSetup.hpp.
Function Documentation
template<> DistributedTetrahedralMesh<2,2>* Load2dMeshAndSetCircularTissue (const std::string & rMeshPath, double centreX, double centreY, double radius) [inline]
Specialization for a parallel mesh.
Parameters:
rMeshPath relative path to the mesh
centreX X co-ord of tissue centre
centreY Y co-ord of tissue centre
radius radius of tissue
Returns:
the new mesh
Definition at line 173 of file SimpleBathProblemSetup.hpp.
References DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructFromMeshReader(), and SetCircularTissueIn2dMesh().
template<class MeshType > MeshType* Load2dMeshAndSetCircularTissue (const std::string & rMeshPath, double centreX, double centreY, double radius) [inline]
Load a 2d mesh, and set everything outside a central circle to be bath.
Parameters:
rMeshPath relative path to the mesh
centreX X co-ord of tissue centre
centreY Y co-ord of tissue centre
radius radius of tissue
Returns:
the new mesh
Definition at line 151 of file SimpleBathProblemSetup.hpp.
References SetCircularTissueIn2dMesh().
template<class MeshType > void SetCircularTissueIn2dMesh (MeshType * pMesh, double centreX, double centreY, double radius) [inline]
Set everything outside a central circle in the given 2d mesh to be bath.
Parameters:
pMesh the mesh
centreX X co-ord of tissue centre
centreY Y co-ord of tissue centre
radius radius of tissue
Definition at line 124 of file SimpleBathProblemSetup.hpp.
References HeartRegionCode::GetValidBathId().
Referenced by Load2dMeshAndSetCircularTissue().