Chaste: VolumeDependentAveragedSourcePde< DIM > Class Template Reference
VolumeDependentAveragedSourcePde< DIM > Class Template Reference
#include <VolumeDependentAveragedSourcePde.hpp>
Public Member Functions
VolumeDependentAveragedSourcePde (AbstractCellPopulation< DIM > &rCellPopulation, double coefficient=0.0)
void SetupSourceTerms (TetrahedralMesh< DIM, DIM > &rCoarseMesh, std::map< CellPtr, unsigned > *pCellPdeElementMap=NULL)
Public Member Functions inherited from AveragedSourcePde< DIM >
AveragedSourcePde (AbstractCellPopulation< DIM > &rCellPopulation, double coefficient=0.0)
const AbstractCellPopulation
< DIM > & rGetCellPopulation () const
double GetCoefficient () const
double ComputeConstantInUSourceTerm (const ChastePoint< DIM > &rX, Element< DIM, DIM > *pElement)
double ComputeLinearInUCoeffInSourceTerm (const ChastePoint< DIM > &rX, Element< DIM, DIM > *pElement)
c_matrix< double, DIM, DIM > ComputeDiffusionTerm (const ChastePoint< DIM > &rX)
double GetUptakeRateForElement (unsigned elementIndex)
Public Member Functions inherited from AbstractLinearEllipticPde< DIM, DIM >
AbstractLinearEllipticPde ()
virtual ~AbstractLinearEllipticPde ()
virtual double ComputeConstantInUSourceTerm (const ChastePoint< SPACE_DIM > &rX, Element< ELEMENT_DIM, SPACE_DIM > *pElement)=0
virtual double ComputeLinearInUCoeffInSourceTerm (const ChastePoint< SPACE_DIM > &rX, Element< ELEMENT_DIM, SPACE_DIM > *pElement)=0
virtual c_matrix< double,
SPACE_DIM, SPACE_DIM > ComputeDiffusionTerm (const ChastePoint< SPACE_DIM > &rX)=0
virtual double ComputeConstantInUSourceTermAtNode (const Node< SPACE_DIM > &rNode)
virtual double ComputeLinearInUCoeffInSourceTermAtNode (const Node< SPACE_DIM > &rNode)
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Private Attributes
NodeBasedCellPopulation< DIM > * mpStaticCastCellPopulation
Friends
class TestCellBasedPdes
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from AveragedSourcePde< DIM >
AbstractCellPopulation< DIM > & mrCellPopulation
double mCoefficient
std::vector< double > mCellDensityOnCoarseElements
Detailed Description
template<unsigned DIM>
class VolumeDependentAveragedSourcePde< DIM >
A PDE which calculates the source term by adding the number of cells in the element containing that point and scaling by the element area.
Definition at line 52 of file VolumeDependentAveragedSourcePde.hpp.
Constructor & Destructor Documentation
template<unsigned DIM> VolumeDependentAveragedSourcePde< DIM >::VolumeDependentAveragedSourcePde (AbstractCellPopulation< DIM > & rCellPopulation, double coefficient = 0.0)
Constructor.
Parameters
rCellPopulation reference to the cell population
coefficient the coefficient of consumption of nutrient by cells (defaults to 0.0)
Definition at line 40 of file VolumeDependentAveragedSourcePde.cpp.
References VolumeDependentAveragedSourcePde< DIM >::mpStaticCastCellPopulation, and AveragedSourcePde< DIM >::mrCellPopulation.
Member Function Documentation
template<unsigned DIM> template<class Archive > void VolumeDependentAveragedSourcePde< DIM >::serialize (Archive & archive, const unsigned int version) inline private
Serialize the PDE and its member variables.
Parameters
archive the archive
version the current version of this class
Definition at line 67 of file VolumeDependentAveragedSourcePde.hpp.
template<unsigned DIM> void VolumeDependentAveragedSourcePde< DIM >::SetupSourceTerms (TetrahedralMesh< DIM, DIM > & rCoarseMesh, std::map< CellPtr, unsigned > * pCellPdeElementMap = NULL) virtual
Set up the source terms.
Parameters
rCoarseMesh reference to the coarse mesh
pCellPdeElementMap optional pointer to the map from cells to coarse elements
Reimplemented from AveragedSourcePde< DIM >.
Definition at line 48 of file VolumeDependentAveragedSourcePde.cpp.
References AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::Begin(), AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::GetContainingElementIndex(), AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::GetElement(), AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::GetNumElements(), and Node< SPACE_DIM >::GetRadius().
Friends And Related Function Documentation
template<unsigned DIM> friend class boost::serialization::access friend
Needed for serialization.
Definition at line 59 of file VolumeDependentAveragedSourcePde.hpp.
Member Data Documentation
template<unsigned DIM> NodeBasedCellPopulation<DIM>* VolumeDependentAveragedSourcePde< DIM >::mpStaticCastCellPopulation private
Static cast of the NodeBasedCellPopulation.
Definition at line 73 of file VolumeDependentAveragedSourcePde.hpp.
Referenced by VolumeDependentAveragedSourcePde< DIM >::VolumeDependentAveragedSourcePde().
The documentation for this class was generated from the following files:
cell_based/src/population/pdes/VolumeDependentAveragedSourcePde.hpp
cell_based/src/population/pdes/VolumeDependentAveragedSourcePde.cpp