Chaste: CellVolumesWriter< ELEMENT_DIM, SPACE_DIM > Class Template Reference
CellVolumesWriter< ELEMENT_DIM, SPACE_DIM > Class Template Reference
#include <CellVolumesWriter.hpp>
Public Member Functions
CellVolumesWriter ()
double GetCellDataForVtkOutput (CellPtr pCell, AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM > *pCellPopulation)
virtual void VisitCell (CellPtr pCell, AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM > *pCellPopulation)
Public Member Functions inherited from AbstractCellWriter< ELEMENT_DIM, SPACE_DIM >
AbstractCellWriter (const std::string &rFileName)
void SetVtkCellDataName (std::string vtkCellDataName)
std::string GetVtkCellDataName ()
Public Member Functions inherited from AbstractCellBasedWriter< ELEMENT_DIM, SPACE_DIM >
AbstractCellBasedWriter (const std::string &rFileName)
virtual ~AbstractCellBasedWriter ()
void CloseFile ()
virtual void OpenOutputFile (OutputFileHandler &rOutputFileHandler)
void OpenOutputFileForAppend (OutputFileHandler &rOutputFileHandler)
virtual void WriteTimeStamp ()
virtual void WriteNewline ()
void SetFileName (std::string fileName)
std::string GetFileName ()
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Friends
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from AbstractCellWriter< ELEMENT_DIM, SPACE_DIM >
std::string mVtkCellDataName
Protected Attributes inherited from AbstractCellBasedWriter< ELEMENT_DIM, SPACE_DIM >
std::string mFileName
out_stream mpOutStream
Detailed Description
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM>
class CellVolumesWriter< ELEMENT_DIM, SPACE_DIM >
A class written using the visitor pattern for writing cell volumes (in 3D, or areas in 2D) to file.
The output file is called cellareas.dat by default. If VTK is switched on, then the writer also specifies the VTK output for each cell, which is stored in the VTK cell data "Cell areas" by default.
Definition at line 51 of file CellVolumesWriter.hpp.
Constructor & Destructor Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> CellVolumesWriter< ELEMENT_DIM, SPACE_DIM >::CellVolumesWriter ()
Default constructor.
Definition at line 40 of file CellVolumesWriter.cpp.
References AbstractCellWriter< ELEMENT_DIM, SPACE_DIM >::mVtkCellDataName.
Member Function Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> double CellVolumesWriter< ELEMENT_DIM, SPACE_DIM >::GetCellDataForVtkOutput (CellPtr pCell, AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM > * pCellPopulation) virtual
Overridden GetCellDataForVtkOutput() method.
Get a double associated with a cell. This method reduces duplication of code between the methods VisitCell() and AddVtkData().
Parameters
pCell a cell
pCellPopulation a pointer to the cell population owning the cell
Returns
data associated with the cell
Implements AbstractCellWriter< ELEMENT_DIM, SPACE_DIM >.
Definition at line 47 of file CellVolumesWriter.cpp.
References AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::GetVolumeOfCell().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> template<class Archive > void CellVolumesWriter< ELEMENT_DIM, SPACE_DIM >::serialize (Archive & archive, const unsigned int version) inline private
Serialize the object and its member variables.
Parameters
archive the archive
version the current version of this class
Definition at line 63 of file CellVolumesWriter.hpp.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void CellVolumesWriter< ELEMENT_DIM, SPACE_DIM >::VisitCell (CellPtr pCell, AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM > * pCellPopulation) virtual
Overridden VisitCell() method.
Visit a cell and write its volume (or area in 2-D).
Outputs a line of space-separated values of the form: ...[location index] [cell id] [x-pos] [y-pos] [z-pos] [cell volume/area] ... with [y-pos] and [z-pos] included for 2 and 3 dimensional simulations, respectively.
This is appended to the output written by AbstractCellBasedWriter, which is a single value [present simulation time], followed by a tab.
Parameters
pCell a cell
pCellPopulation a pointer to the cell population owning the cell
Implements AbstractCellWriter< ELEMENT_DIM, SPACE_DIM >.
Definition at line 54 of file CellVolumesWriter.cpp.
References AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::GetLocationIndexUsingCell(), AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::GetLocationOfCellCentre(), and AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::GetVolumeOfCell().
Friends And Related Function Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> friend class boost::serialization::access friend
Needed for serialization.
Definition at line 55 of file CellVolumesWriter.hpp.
The documentation for this class was generated from the following files:
cell_based/src/writers/cell_writers/CellVolumesWriter.hpp
cell_based/src/writers/cell_writers/CellVolumesWriter.cpp