Chaste: CellMLToSharedLibraryConverter Class Reference
CellMLToSharedLibraryConverter Class Reference
#include <CellMLToSharedLibraryConverter.hpp>
Public Member Functions
CellMLToSharedLibraryConverter (bool preserveGeneratedSources=false, std::string component="heart")
DynamicCellModelLoaderPtr Convert (const FileFinder &rFilePath, bool isCollective=true)
Static Public Member Functions
static void CreateOptionsFile (const OutputFileHandler &rHandler, const std::string &rModelName, const std::vector< std::string > &rArgs, const std::string &rExtraXml="")
Private Member Functions
void ConvertCellmlToSo (const std::string &rCellmlFullPath, const std::string &rCellmlFolder)
Private Attributes
bool mPreserveGeneratedSources
std::string mComponentName
Static Private Attributes
static const std::string msSoSuffix = "so"
Friends
class TestDynamicallyLoadedCellModels
Detailed Description
This class encapsulates all the complexity needed to generate a loadable module from a CellML file.
Definition at line 50 of file CellMLToSharedLibraryConverter.hpp.
Constructor & Destructor Documentation
CellMLToSharedLibraryConverter::CellMLToSharedLibraryConverter (bool preserveGeneratedSources = false, std::string component = "heart")
Create a converter.
Parameters
preserveGeneratedSources whether to save copies of generated C++ source files in the directory containing the .cellml file.
component the name of the Chaste component (or project) in which to build the loadable module (if required). Allows projects to have specialised base classes for dynamically loaded cell models.
Definition at line 71 of file CellMLToSharedLibraryConverter.cpp.
Member Function Documentation
DynamicCellModelLoaderPtr CellMLToSharedLibraryConverter::Convert (const FileFinder & rFilePath, bool isCollective = true)
Returns
a loadable module from the given file, and return a loader for it. The file can be a .so, in which case there isn't much to do, just create the loader. The interesting case comes when it is a .cellml file. If the file has any other extension, an exception is thrown.
Parameters
rFilePath the model to load
isCollective whether this method is being called collectively. If it is not, then we require the .so to already exist, rather than trying to avoid race conditions.
Note
If you do not pass isCollective=false, must be called collectively.
Definition at line 78 of file CellMLToSharedLibraryConverter.cpp.
References RelativeTo::Absolute, ConvertCellmlToSo(), EXCEPTION, FileFinder::Exists(), FileFinder::GetAbsolutePath(), DynamicModelLoaderRegistry::GetLoader(), DynamicModelLoaderRegistry::Instance(), FileFinder::IsNewerThan(), msSoSuffix, and FileFinder::SetPath().
Referenced by HeartConfigRelatedCellFactory< SPACE_DIM >::LoadDynamicModel().
void CellMLToSharedLibraryConverter::ConvertCellmlToSo (const std::string & rCellmlFullPath, const std::string & rCellmlFolder) private
Helper method performing the actual conversion of a .cellml file to a .so.
Note
Must be called collectively.
Parameters
rCellmlFullPath full path to the .cellml file
rCellmlFolder folder containing the CellML file, with trailing slash
todo: #2656 - ignoring all cmake-specific code, revise after cmake transition
todo: #2656 - ignoring all cmake-specific code, revise after cmake transition
Definition at line 142 of file CellMLToSharedLibraryConverter.cpp.
References RelativeTo::Absolute, PetscTools::AmMaster(), ChasteBuildDirName(), RelativeTo::ChasteBuildRoot, ChasteBuildType(), FileFinder::CopyTo(), FileFinder::DangerousRemove(), EXCEPT_IF_NOT, EXCEPTION, FileFinder::Exists(), EXPECT0, FileFinder::FindMatches(), FileFinder::GetAbsolutePath(), FileFinder::GetLeafNameNoExtension(), Exception::GetMessage(), FileFinder::GetParent(), IGNORE_RET, FileFinder::IsDir(), FileFinder::IsPathSet(), mComponentName, mPreserveGeneratedSources, msSoSuffix, PetscTools::ReplicateException(), and FileFinder::SetPath().
Referenced by Convert().
void CellMLToSharedLibraryConverter::CreateOptionsFile (const OutputFileHandler & rHandler, const std::string & rModelName, const std::vector< std::string > & rArgs, const std::string & rExtraXml = "") static
Create a PyCml options file for the given model.
Parameters
rHandler where to create the file
rModelName base name of the model file (which will be "rModelName.cellml")
rArgs extra command-line arguments for the model conversion
rExtraXml any extra XML to go in the config file (e.g. LT settings)
Definition at line 278 of file CellMLToSharedLibraryConverter.cpp.
References PetscTools::AmMaster(), PetscTools::Barrier(), and OutputFileHandler::OpenOutputFile().
Friends And Related Function Documentation
friend class TestDynamicallyLoadedCellModels friend
Test gets access to the msSoSuffix variable
Definition at line 54 of file CellMLToSharedLibraryConverter.hpp.
Member Data Documentation
std::string CellMLToSharedLibraryConverter::mComponentName private
Which component to build the loadable module in.
Definition at line 112 of file CellMLToSharedLibraryConverter.hpp.
Referenced by ConvertCellmlToSo().
bool CellMLToSharedLibraryConverter::mPreserveGeneratedSources private
Whether to save copies of generated C++ source files.
Definition at line 109 of file CellMLToSharedLibraryConverter.hpp.
Referenced by ConvertCellmlToSo().
const std::string CellMLToSharedLibraryConverter::msSoSuffix = "so" static private
The .so suffix is nearly always "so" (as you might expect). On Mac OSX this is redefined to "dylib"
Set the .so suffix
Definition at line 115 of file CellMLToSharedLibraryConverter.hpp.
Referenced by Convert(), and ConvertCellmlToSo().
The documentation for this class was generated from the following files:
heart/src/odes/CellMLToSharedLibraryConverter.hpp
heart/src/odes/CellMLToSharedLibraryConverter.cpp