Chaste: AbstractSimpleGenerationBasedCellCycleModel Class Reference
AbstractSimpleGenerationBasedCellCycleModel Class Reference
#include <AbstractSimpleGenerationBasedCellCycleModel.hpp>
Public Member Functions
AbstractSimpleGenerationBasedCellCycleModel ()
virtual ~AbstractSimpleGenerationBasedCellCycleModel ()
void ResetForDivision ()
void InitialiseDaughterCell ()
void SetGeneration (unsigned generation)
unsigned GetGeneration () const
void SetMaxTransitGenerations (unsigned maxTransitGenerations)
unsigned GetMaxTransitGenerations () const
virtual void OutputCellCycleModelParameters (out_stream &rParamsFile)
Public Member Functions inherited from AbstractSimpleCellCycleModel
AbstractSimpleCellCycleModel ()
virtual ~AbstractSimpleCellCycleModel ()
virtual void UpdateCellCyclePhase ()
virtual void Initialise ()
Public Member Functions inherited from AbstractCellCycleModel
AbstractCellCycleModel ()
virtual ~AbstractCellCycleModel ()
void SetCell (CellPtr pCell)
CellPtr GetCell ()
virtual void SetBirthTime (double birthTime)
void SetDimension (unsigned dimension)
unsigned GetDimension ()
double GetBirthTime () const
double GetAge ()
virtual bool ReadyToDivide ()
virtual AbstractCellCycleModel * CreateCellCycleModel ()=0
CellCyclePhase GetCurrentCellCyclePhase ()
virtual double GetG1Duration ()
double GetStemCellG1Duration ()
double GetTransitCellG1Duration ()
double GetSG2MDuration ()
virtual double GetSDuration ()
virtual double GetG2Duration ()
virtual double GetMDuration ()
virtual void SetStemCellG1Duration (double stemCellG1Duration)
virtual void SetTransitCellG1Duration (double transitCellG1Duration)
void SetSDuration (double sDuration)
void SetG2Duration (double g2Duration)
void SetMDuration (double mDuration)
virtual double GetAverageTransitCellCycleTime ()
virtual double GetAverageStemCellCycleTime ()
virtual bool CanCellTerminallyDifferentiate ()
double GetMinimumGapDuration ()
void SetMinimumGapDuration (double minimumGapDuration)
void OutputCellCycleModelInfo (out_stream &rParamsFile)
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Protected Attributes
unsigned mGeneration
unsigned mMaxTransitGenerations
Protected Attributes inherited from AbstractCellCycleModel
CellPtr mpCell
double mBirthTime
CellCyclePhase mCurrentCellCyclePhase
double mG1Duration
bool mReadyToDivide
unsigned mDimension
double mMinimumGapDuration
double mStemCellG1Duration
double mTransitCellG1Duration
double mSDuration
double mG2Duration
double mMDuration
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Friends
class boost::serialization::access
Additional Inherited Members
Protected Member Functions inherited from AbstractSimpleCellCycleModel
virtual void SetG1Duration ()
Detailed Description
This class contains all the things common to simple generation-based cell cycle models, i.e. models in which the length of cell cycle phases are determined when the cell-cycle model is created, rather than evaluated 'on the fly' by ODEs and suchlike, and in which each cell has a 'generation'.
N.B. Whether or not the cell should actually divide may depend on Wnt / Oxygen etc. in subclasses.
Definition at line 54 of file AbstractSimpleGenerationBasedCellCycleModel.hpp.
Constructor & Destructor Documentation
AbstractSimpleGenerationBasedCellCycleModel::AbstractSimpleGenerationBasedCellCycleModel ()
Default constructor - creates an AbstractSimpleCellCycleModel.
Definition at line 41 of file AbstractSimpleGenerationBasedCellCycleModel.cpp.
AbstractSimpleGenerationBasedCellCycleModel::~AbstractSimpleGenerationBasedCellCycleModel () virtual
Destructor.
Definition at line 48 of file AbstractSimpleGenerationBasedCellCycleModel.cpp.
Member Function Documentation
unsigned AbstractSimpleGenerationBasedCellCycleModel::GetGeneration () const
Returns
the cell's generation.
Definition at line 110 of file AbstractSimpleGenerationBasedCellCycleModel.cpp.
References mGeneration.
unsigned AbstractSimpleGenerationBasedCellCycleModel::GetMaxTransitGenerations () const
Returns
mMaxTransitGenerations
Definition at line 120 of file AbstractSimpleGenerationBasedCellCycleModel.cpp.
References mMaxTransitGenerations.
void AbstractSimpleGenerationBasedCellCycleModel::InitialiseDaughterCell () virtual
Set the new cell's G1 duration once it has been created after division. The duration will be based on cell type.
Reimplemented from AbstractSimpleCellCycleModel.
Definition at line 77 of file AbstractSimpleGenerationBasedCellCycleModel.cpp.
References AbstractSimpleCellCycleModel::InitialiseDaughterCell(), mGeneration, mMaxTransitGenerations, and AbstractCellCycleModel::mpCell.
void AbstractSimpleGenerationBasedCellCycleModel::OutputCellCycleModelParameters (out_stream & rParamsFile) virtual
Outputs cell cycle model parameters to file.
Parameters
rParamsFile the file stream to which the parameters are output
Reimplemented from AbstractSimpleCellCycleModel.
Reimplemented in ExponentiallyDistributedStochasticDurationGenerationBasedCellCycleModel, StochasticDurationGenerationBasedCellCycleModel, and FixedDurationGenerationBasedCellCycleModel.
Definition at line 125 of file AbstractSimpleGenerationBasedCellCycleModel.cpp.
References mMaxTransitGenerations, and AbstractSimpleCellCycleModel::OutputCellCycleModelParameters().
Referenced by FixedDurationGenerationBasedCellCycleModel::OutputCellCycleModelParameters(), StochasticDurationGenerationBasedCellCycleModel::OutputCellCycleModelParameters(), and ExponentiallyDistributedStochasticDurationGenerationBasedCellCycleModel::OutputCellCycleModelParameters().
void AbstractSimpleGenerationBasedCellCycleModel::ResetForDivision () virtual
Overridden ResetForDivision() method.
Reimplemented from AbstractSimpleCellCycleModel.
Definition at line 52 of file AbstractSimpleGenerationBasedCellCycleModel.cpp.
References mGeneration, mMaxTransitGenerations, AbstractCellCycleModel::mpCell, and AbstractSimpleCellCycleModel::ResetForDivision().
template<class Archive > void AbstractSimpleGenerationBasedCellCycleModel::serialize (Archive & archive, const unsigned int version) inline private
Archive the cell-cycle model.
Parameters
archive the archive
version the current version of this class
Definition at line 67 of file AbstractSimpleGenerationBasedCellCycleModel.hpp.
References mGeneration, and mMaxTransitGenerations.
void AbstractSimpleGenerationBasedCellCycleModel::SetGeneration (unsigned generation)
Sets the cell's generation.
Parameters
generation the cell's generation
Definition at line 105 of file AbstractSimpleGenerationBasedCellCycleModel.cpp.
References mGeneration.
Referenced by FixedDurationGenerationBasedCellCycleModel::CreateCellCycleModel(), StochasticDurationGenerationBasedCellCycleModel::CreateCellCycleModel(), and ExponentiallyDistributedStochasticDurationGenerationBasedCellCycleModel::CreateCellCycleModel().
void AbstractSimpleGenerationBasedCellCycleModel::SetMaxTransitGenerations (unsigned maxTransitGenerations)
Set mMaxTransitGenerations.
Parameters
maxTransitGenerations the new value of mMaxTransitGenerations
Definition at line 115 of file AbstractSimpleGenerationBasedCellCycleModel.cpp.
References mMaxTransitGenerations.
Referenced by FixedDurationGenerationBasedCellCycleModel::CreateCellCycleModel(), StochasticDurationGenerationBasedCellCycleModel::CreateCellCycleModel(), and ExponentiallyDistributedStochasticDurationGenerationBasedCellCycleModel::CreateCellCycleModel().
Friends And Related Function Documentation
friend class boost::serialization::access friend
Needed for serialization.
Definition at line 59 of file AbstractSimpleGenerationBasedCellCycleModel.hpp.
Member Data Documentation
unsigned AbstractSimpleGenerationBasedCellCycleModel::mGeneration protected
The generation of this cell (cells with a StemCellProliferativeType have a generation of 0)
Definition at line 77 of file AbstractSimpleGenerationBasedCellCycleModel.hpp.
Referenced by FixedDurationGenerationBasedCellCycleModel::CreateCellCycleModel(), StochasticDurationGenerationBasedCellCycleModel::CreateCellCycleModel(), ExponentiallyDistributedStochasticDurationGenerationBasedCellCycleModel::CreateCellCycleModel(), GetGeneration(), InitialiseDaughterCell(), ResetForDivision(), serialize(), and SetGeneration().
unsigned AbstractSimpleGenerationBasedCellCycleModel::mMaxTransitGenerations protected
How many generations a transit cell lives for before becoming fully differentiated.
Definition at line 80 of file AbstractSimpleGenerationBasedCellCycleModel.hpp.
Referenced by FixedDurationGenerationBasedCellCycleModel::CreateCellCycleModel(), StochasticDurationGenerationBasedCellCycleModel::CreateCellCycleModel(), ExponentiallyDistributedStochasticDurationGenerationBasedCellCycleModel::CreateCellCycleModel(), GetMaxTransitGenerations(), InitialiseDaughterCell(), OutputCellCycleModelParameters(), ResetForDivision(), serialize(), and SetMaxTransitGenerations().
The documentation for this class was generated from the following files:
cell_based/src/cell/cycle/AbstractSimpleGenerationBasedCellCycleModel.hpp
cell_based/src/cell/cycle/AbstractSimpleGenerationBasedCellCycleModel.cpp