Chaste: AbstractTargetAreaModifier< DIM > Class Template Reference
AbstractTargetAreaModifier< DIM > Class Template Reference abstract
#include <AbstractTargetAreaModifier.hpp>
Public Member Functions
AbstractTargetAreaModifier ()
virtual ~AbstractTargetAreaModifier ()
virtual void UpdateAtEndOfTimeStep (AbstractCellPopulation< DIM, DIM > &rCellPopulation)
virtual void SetupSolve (AbstractCellPopulation< DIM, DIM > &rCellPopulation, std::string outputDirectory)
double GetReferenceTargetArea ()
void SetReferenceTargetArea (double referenceTargetArea)
void UpdateTargetAreas (AbstractCellPopulation< DIM, DIM > &rCellPopulation)
virtual void UpdateTargetAreaOfCell (const CellPtr pCell)=0
virtual void OutputSimulationModifierParameters (out_stream &rParamsFile)
Public Member Functions inherited from AbstractCellBasedSimulationModifier< DIM, DIM >
AbstractCellBasedSimulationModifier ()
virtual ~AbstractCellBasedSimulationModifier ()
virtual void UpdateAtEndOfTimeStep (AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM > &rCellPopulation)
virtual void UpdateAtEndOfOutputTimeStep (AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM > &rCellPopulation)
virtual void SetupSolve (AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM > &rCellPopulation, std::string outputDirectory)
virtual void UpdateAtEndOfSolve (AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM > &rCellPopulation)
void OutputSimulationModifierInfo (out_stream &rParamsFile)
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Protected Attributes
double mReferenceTargetArea
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Friends
class boost::serialization::access
Detailed Description
template<unsigned DIM>
class AbstractTargetAreaModifier< DIM >
A modifier class in which the target area property of each cell is updated. It is used to implement growth in vertex-based simulations.
Definition at line 49 of file AbstractTargetAreaModifier.hpp.
Constructor & Destructor Documentation
template<unsigned DIM> AbstractTargetAreaModifier< DIM >::AbstractTargetAreaModifier ()
Default constructor.
Definition at line 39 of file AbstractTargetAreaModifier.cpp.
template<unsigned DIM> AbstractTargetAreaModifier< DIM >::~AbstractTargetAreaModifier () virtual
Destructor.
Definition at line 46 of file AbstractTargetAreaModifier.cpp.
Member Function Documentation
template<unsigned DIM> double AbstractTargetAreaModifier< DIM >::GetReferenceTargetArea ()
Get the reference target area.
Returns
the reference target area.
Definition at line 86 of file AbstractTargetAreaModifier.cpp.
template<unsigned DIM> void AbstractTargetAreaModifier< DIM >::OutputSimulationModifierParameters (out_stream & rParamsFile) virtual
Overridden OutputSimulationModifierParameters() method. Output any simulation modifier parameters to file.
Parameters
rParamsFile the file stream to which the parameters are output
Implements AbstractCellBasedSimulationModifier< DIM, DIM >.
Reimplemented in FarhadifarTypeModifier< DIM >, and SimpleTargetAreaModifier< DIM >.
Definition at line 99 of file AbstractTargetAreaModifier.cpp.
References AbstractCellBasedSimulationModifier< ELEMENT_DIM, SPACE_DIM >::OutputSimulationModifierParameters().
Referenced by SimpleTargetAreaModifier< DIM >::OutputSimulationModifierParameters(), and FarhadifarTypeModifier< DIM >::OutputSimulationModifierParameters().
template<unsigned DIM> template<class Archive > void AbstractTargetAreaModifier< DIM >::serialize (Archive & archive, const unsigned int version) inline private
Boost Serialization method for archiving/checkpointing. Archives the object and its member variables.
Parameters
archive The boost archive.
version The current version of this class.
Definition at line 61 of file AbstractTargetAreaModifier.hpp.
References AbstractTargetAreaModifier< DIM >::mReferenceTargetArea.
template<unsigned DIM> void AbstractTargetAreaModifier< DIM >::SetReferenceTargetArea (double referenceTargetArea)
Set the reference target area. The standard value is 1.0.
Parameters
referenceTargetArea the new value of mReferenceTargetArea
Definition at line 92 of file AbstractTargetAreaModifier.cpp.
template<unsigned DIM> void AbstractTargetAreaModifier< DIM >::SetupSolve (AbstractCellPopulation< DIM, DIM > & rCellPopulation, std::string outputDirectory) virtual
Overridden SetupSolve() method.
Specify what to do in the simulation before the start of the time loop.
Parameters
rCellPopulation reference to the cell population
outputDirectory the output directory, relative to where Chaste output is stored
Definition at line 57 of file AbstractTargetAreaModifier.cpp.
References EXCEPTION.
template<unsigned DIM> void AbstractTargetAreaModifier< DIM >::UpdateAtEndOfTimeStep (AbstractCellPopulation< DIM, DIM > & rCellPopulation) virtual
Overridden UpdateAtEndOfTimeStep() method.
Specify what to do in the simulation at the end of each time step.
Parameters
rCellPopulation reference to the cell population
Definition at line 51 of file AbstractTargetAreaModifier.cpp.
template<unsigned DIM> virtual void AbstractTargetAreaModifier< DIM >::UpdateTargetAreaOfCell (const CellPtr pCell) pure virtual
Helper method to update the target area property of an individual cell. This method has to be overwritten in child classes.
Parameters
pCell pointer to the cell
Implemented in FarhadifarTypeModifier< DIM >, and SimpleTargetAreaModifier< DIM >.
template<unsigned DIM> void AbstractTargetAreaModifier< DIM >::UpdateTargetAreas (AbstractCellPopulation< DIM, DIM > & rCellPopulation)
Helper method to update the target area property of all cells in the population.
Parameters
rCellPopulation reference to the cell population
Definition at line 72 of file AbstractTargetAreaModifier.cpp.
References AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::rGetCells().
Friends And Related Function Documentation
template<unsigned DIM> friend class boost::serialization::access friend
Needed for serialization.
Definition at line 52 of file AbstractTargetAreaModifier.hpp.
Member Data Documentation
template<unsigned DIM> double AbstractTargetAreaModifier< DIM >::mReferenceTargetArea protected
A reference area. Usually this is the target area of mature cells in the population.
Definition at line 72 of file AbstractTargetAreaModifier.hpp.
Referenced by AbstractTargetAreaModifier< DIM >::serialize().
The documentation for this class was generated from the following files:
cell_based/src/simulation/modifiers/AbstractTargetAreaModifier.hpp
cell_based/src/simulation/modifiers/AbstractTargetAreaModifier.cpp