Chaste: AbstractCellBasedWriter< ELEMENT_DIM, SPACE_DIM > Class Template Reference
AbstractCellBasedWriter< ELEMENT_DIM, SPACE_DIM > Class Template Reference
#include <AbstractCellBasedWriter.hpp>
Public Member Functions
AbstractCellBasedWriter (const std::string &rFileName)
virtual ~AbstractCellBasedWriter ()
void CloseFile ()
virtual void OpenOutputFile (OutputFileHandler &rOutputFileHandler)
void OpenOutputFileForAppend (OutputFileHandler &rOutputFileHandler)
virtual void WriteTimeStamp ()
virtual void WriteNewline ()
void SetFileName (std::string fileName)
std::string GetFileName ()
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Protected Attributes
std::string mFileName
out_stream mpOutStream
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Friends
class boost::serialization::access
Detailed Description
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM>
class AbstractCellBasedWriter< ELEMENT_DIM, SPACE_DIM >
Abstract class for a writer that takes data from an AbstractCellPopulation and writes it to file.
Definition at line 48 of file AbstractCellBasedWriter.hpp.
Constructor & Destructor Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> AbstractCellBasedWriter< ELEMENT_DIM, SPACE_DIM >::AbstractCellBasedWriter (const std::string & rFileName)
Constructor.
Parameters
rFileName the name of the file to write to.
Definition at line 39 of file AbstractCellBasedWriter.cpp.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> AbstractCellBasedWriter< ELEMENT_DIM, SPACE_DIM >::~AbstractCellBasedWriter () virtual
Virtual destructor.
Definition at line 45 of file AbstractCellBasedWriter.cpp.
Member Function Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void AbstractCellBasedWriter< ELEMENT_DIM, SPACE_DIM >::CloseFile ()
Close mpOutStream.
Definition at line 50 of file AbstractCellBasedWriter.cpp.
Referenced by AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::CloseRoundRobinWritersFiles(), and AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::CloseWritersFiles().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> std::string AbstractCellBasedWriter< ELEMENT_DIM, SPACE_DIM >::GetFileName ()
Returns
the output file name.
Definition at line 86 of file AbstractCellBasedWriter.cpp.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void AbstractCellBasedWriter< ELEMENT_DIM, SPACE_DIM >::OpenOutputFile (OutputFileHandler & rOutputFileHandler) virtual
Open mpOutStream for writing.
Parameters
rOutputFileHandler handler for the directory in which to open this file.
Definition at line 56 of file AbstractCellBasedWriter.cpp.
References OutputFileHandler::OpenOutputFile().
Referenced by AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::OpenWritersFiles().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void AbstractCellBasedWriter< ELEMENT_DIM, SPACE_DIM >::OpenOutputFileForAppend (OutputFileHandler & rOutputFileHandler)
Open mpOutStream for appending.
Parameters
rOutputFileHandler handler for the directory in which to open this file.
Definition at line 62 of file AbstractCellBasedWriter.cpp.
References OutputFileHandler::OpenOutputFile().
Referenced by AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::OpenRoundRobinWritersFilesForAppend(), and AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::WriteResultsToFiles().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> template<class Archive > void AbstractCellBasedWriter< ELEMENT_DIM, SPACE_DIM >::serialize (Archive & archive, const unsigned int version) inline private
Serialize the object.
Parameters
archive the archive
version the current version of this class
Definition at line 61 of file AbstractCellBasedWriter.hpp.
References AbstractCellBasedWriter< ELEMENT_DIM, SPACE_DIM >::mFileName.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void AbstractCellBasedWriter< ELEMENT_DIM, SPACE_DIM >::SetFileName (std::string fileName)
Set the output file name. This method allows the user to change mFileName from its default value, which is set in each subclass's constructor.
Parameters
fileName the output file name
Definition at line 80 of file AbstractCellBasedWriter.cpp.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void AbstractCellBasedWriter< ELEMENT_DIM, SPACE_DIM >::WriteNewline () virtual
Add a newline character to mpOutStream.
Definition at line 74 of file AbstractCellBasedWriter.cpp.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void AbstractCellBasedWriter< ELEMENT_DIM, SPACE_DIM >::WriteTimeStamp () virtual
Write the current time stamp to mpOutStream.
Definition at line 68 of file AbstractCellBasedWriter.cpp.
References SimulationTime::GetTime(), and SimulationTime::Instance().
Friends And Related Function Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> friend class boost::serialization::access friend
Needed for serialization.
Definition at line 53 of file AbstractCellBasedWriter.hpp.
Member Data Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> std::string AbstractCellBasedWriter< ELEMENT_DIM, SPACE_DIM >::mFileName protected
The name of the output file.
Definition at line 69 of file AbstractCellBasedWriter.hpp.
Referenced by AbstractCellBasedWriter< ELEMENT_DIM, SPACE_DIM >::serialize().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> out_stream AbstractCellBasedWriter< ELEMENT_DIM, SPACE_DIM >::mpOutStream protected
An output stream for writing data.
Definition at line 72 of file AbstractCellBasedWriter.hpp.
The documentation for this class was generated from the following files:
cell_based/src/writers/AbstractCellBasedWriter.hpp
cell_based/src/writers/AbstractCellBasedWriter.cpp