Chaste: CellBetaCateninWriter< ELEMENT_DIM, SPACE_DIM > Class Template Reference
CellBetaCateninWriter< ELEMENT_DIM, SPACE_DIM > Class Template Reference
#include <CellBetaCateninWriter.hpp>
Public Member Functions
CellBetaCateninWriter ()
double GetCellDataForVtkOutput (CellPtr pCell, AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM > *pCellPopulation)
virtual void VisitCell (CellPtr pCell, AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM > *pCellPopulation)
Public Member Functions inherited from AbstractCellWriter< ELEMENT_DIM, SPACE_DIM >
AbstractCellWriter (const std::string &rFileName)
void SetVtkCellDataName (std::string vtkCellDataName)
std::string GetVtkCellDataName ()
Public Member Functions inherited from AbstractCellBasedWriter< ELEMENT_DIM, SPACE_DIM >
AbstractCellBasedWriter (const std::string &rFileName)
virtual ~AbstractCellBasedWriter ()
void CloseFile ()
virtual void OpenOutputFile (OutputFileHandler &rOutputFileHandler)
void OpenOutputFileForAppend (OutputFileHandler &rOutputFileHandler)
virtual void WriteTimeStamp ()
virtual void WriteNewline ()
void SetFileName (std::string fileName)
std::string GetFileName ()
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Friends
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from AbstractCellWriter< ELEMENT_DIM, SPACE_DIM >
std::string mVtkCellDataName
Protected Attributes inherited from AbstractCellBasedWriter< ELEMENT_DIM, SPACE_DIM >
std::string mFileName
out_stream mpOutStream
Detailed Description
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM>
class CellBetaCateninWriter< ELEMENT_DIM, SPACE_DIM >
A class written using the visitor pattern for writing cell beta catenin levels to file.
Definition at line 46 of file CellBetaCateninWriter.hpp.
Constructor & Destructor Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> CellBetaCateninWriter< ELEMENT_DIM, SPACE_DIM >::CellBetaCateninWriter ()
Default constructor.
Definition at line 40 of file CellBetaCateninWriter.cpp.
References AbstractCellWriter< ELEMENT_DIM, SPACE_DIM >::mVtkCellDataName.
Member Function Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> double CellBetaCateninWriter< ELEMENT_DIM, SPACE_DIM >::GetCellDataForVtkOutput (CellPtr pCell, AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM > * pCellPopulation) virtual
Overridden GetCellDataForVtkOutput() method.
Get a double associated with a cell. This method reduces duplication of code between the methods VisitCell() and AddVtkData().
In this overridden method, since we are only able to output one double for each cell, we choose to output the cytoplasmic beta catenin concentration. Thus, at present, the membrane-bound and nuclear beta catenin concentrations cannot be visualized as VTK output. If this were required, it would be straightforward to implement within the current framework, for example by defined two new writer classes.
Parameters
pCell a cell
pCellPopulation a pointer to the cell population owning the cell
Returns
data associated with the cell
Implements AbstractCellWriter< ELEMENT_DIM, SPACE_DIM >.
Definition at line 47 of file CellBetaCateninWriter.cpp.
References AbstractVanLeeuwen2009WntSwatCellCycleModel::GetCytoplasmicBetaCateninLevel().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> template<class Archive > void CellBetaCateninWriter< ELEMENT_DIM, SPACE_DIM >::serialize (Archive & archive, const unsigned int version) inline private
Serialize the object and its member variables.
Parameters
archive the archive
version the current version of this class
Definition at line 58 of file CellBetaCateninWriter.hpp.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void CellBetaCateninWriter< ELEMENT_DIM, SPACE_DIM >::VisitCell (CellPtr pCell, AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM > * pCellPopulation) virtual
Overridden VisitCell() method. Visit a cell and write its data.
Parameters
pCell the cell to write
pCellPopulation a pointer to the cell population owning the cell.
Implements AbstractCellWriter< ELEMENT_DIM, SPACE_DIM >.
Definition at line 56 of file CellBetaCateninWriter.cpp.
References AbstractVanLeeuwen2009WntSwatCellCycleModel::GetCytoplasmicBetaCateninLevel(), AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::GetLocationIndexUsingCell(), AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::GetLocationOfCellCentre(), AbstractVanLeeuwen2009WntSwatCellCycleModel::GetMembraneBoundBetaCateninLevel(), and AbstractVanLeeuwen2009WntSwatCellCycleModel::GetNuclearBetaCateninLevel().
Friends And Related Function Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> friend class boost::serialization::access friend
Needed for serialization.
Definition at line 50 of file CellBetaCateninWriter.hpp.
The documentation for this class was generated from the following files:
crypt/src/writers/CellBetaCateninWriter.hpp
crypt/src/writers/CellBetaCateninWriter.cpp