Chaste: StochasticDurationGenerationBasedCellCycleModel Class Reference
StochasticDurationGenerationBasedCellCycleModel Class Reference
#include <StochasticDurationGenerationBasedCellCycleModel.hpp>
Public Member Functions
StochasticDurationGenerationBasedCellCycleModel ()
AbstractCellCycleModel * CreateCellCycleModel ()
virtual void OutputCellCycleModelParameters (out_stream &rParamsFile)
Public Member Functions inherited from AbstractSimpleGenerationBasedCellCycleModel
AbstractSimpleGenerationBasedCellCycleModel ()
virtual ~AbstractSimpleGenerationBasedCellCycleModel ()
void ResetForDivision ()
void InitialiseDaughterCell ()
void SetGeneration (unsigned generation)
unsigned GetGeneration () const
void SetMaxTransitGenerations (unsigned maxTransitGenerations)
unsigned GetMaxTransitGenerations () const
Public Member Functions inherited from AbstractSimpleCellCycleModel
AbstractSimpleCellCycleModel ()
virtual ~AbstractSimpleCellCycleModel ()
virtual void UpdateCellCyclePhase ()
virtual void Initialise ()
Public Member Functions inherited from AbstractCellCycleModel
AbstractCellCycleModel ()
virtual ~AbstractCellCycleModel ()
void SetCell (CellPtr pCell)
CellPtr GetCell ()
virtual void SetBirthTime (double birthTime)
void SetDimension (unsigned dimension)
unsigned GetDimension ()
double GetBirthTime () const
double GetAge ()
virtual bool ReadyToDivide ()
CellCyclePhase GetCurrentCellCyclePhase ()
virtual double GetG1Duration ()
double GetStemCellG1Duration ()
double GetTransitCellG1Duration ()
double GetSG2MDuration ()
virtual double GetSDuration ()
virtual double GetG2Duration ()
virtual double GetMDuration ()
virtual void SetStemCellG1Duration (double stemCellG1Duration)
virtual void SetTransitCellG1Duration (double transitCellG1Duration)
void SetSDuration (double sDuration)
void SetG2Duration (double g2Duration)
void SetMDuration (double mDuration)
virtual double GetAverageTransitCellCycleTime ()
virtual double GetAverageStemCellCycleTime ()
virtual bool CanCellTerminallyDifferentiate ()
double GetMinimumGapDuration ()
void SetMinimumGapDuration (double minimumGapDuration)
void OutputCellCycleModelInfo (out_stream &rParamsFile)
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Protected Member Functions
void SetG1Duration ()
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Friends
class TestSimpleCellCycleModels
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from AbstractSimpleGenerationBasedCellCycleModel
unsigned mGeneration
unsigned mMaxTransitGenerations
Protected Attributes inherited from AbstractCellCycleModel
CellPtr mpCell
double mBirthTime
CellCyclePhase mCurrentCellCyclePhase
double mG1Duration
bool mReadyToDivide
unsigned mDimension
double mMinimumGapDuration
double mStemCellG1Duration
double mTransitCellG1Duration
double mSDuration
double mG2Duration
double mMDuration
Detailed Description
A stochastic cell-cycle model employed by Meineke et al (2001) in their off-lattice model of the intestinal crypt (doi:10.1046/j.0960-7722.2001.00216.x).
Definition at line 46 of file StochasticDurationGenerationBasedCellCycleModel.hpp.
Constructor & Destructor Documentation
StochasticDurationGenerationBasedCellCycleModel::StochasticDurationGenerationBasedCellCycleModel ()
Constructor - just a default, mBirthTime is now set in the AbstractCellCycleModel class. mG1Duration is set very high, it is set for the individual cells when InitialiseDaughterCell is called
Definition at line 42 of file StochasticDurationGenerationBasedCellCycleModel.cpp.
Referenced by CreateCellCycleModel().
Member Function Documentation
AbstractCellCycleModel * StochasticDurationGenerationBasedCellCycleModel::CreateCellCycleModel () virtual
Overridden builder method to create new copies of this cell-cycle model.
Returns
new cell-cycle model
Implements AbstractCellCycleModel.
Definition at line 46 of file StochasticDurationGenerationBasedCellCycleModel.cpp.
References AbstractCellCycleModel::mBirthTime, AbstractCellCycleModel::mG2Duration, AbstractSimpleGenerationBasedCellCycleModel::mGeneration, AbstractSimpleGenerationBasedCellCycleModel::mMaxTransitGenerations, AbstractCellCycleModel::mMDuration, AbstractCellCycleModel::mMinimumGapDuration, AbstractCellCycleModel::mSDuration, AbstractCellCycleModel::mStemCellG1Duration, AbstractCellCycleModel::mTransitCellG1Duration, AbstractCellCycleModel::SetBirthTime(), AbstractCellCycleModel::SetG2Duration(), AbstractSimpleGenerationBasedCellCycleModel::SetGeneration(), AbstractSimpleGenerationBasedCellCycleModel::SetMaxTransitGenerations(), AbstractCellCycleModel::SetMDuration(), AbstractCellCycleModel::SetMinimumGapDuration(), AbstractCellCycleModel::SetSDuration(), AbstractCellCycleModel::SetStemCellG1Duration(), AbstractCellCycleModel::SetTransitCellG1Duration(), and StochasticDurationGenerationBasedCellCycleModel().
void StochasticDurationGenerationBasedCellCycleModel::OutputCellCycleModelParameters (out_stream & rParamsFile) virtual
Outputs cell cycle model parameters to file.
Parameters
rParamsFile the file stream to which the parameters are output
Reimplemented from AbstractSimpleGenerationBasedCellCycleModel.
Definition at line 105 of file StochasticDurationGenerationBasedCellCycleModel.cpp.
References AbstractSimpleGenerationBasedCellCycleModel::OutputCellCycleModelParameters().
template<class Archive > void StochasticDurationGenerationBasedCellCycleModel::serialize (Archive & archive, const unsigned int version) inline private
Archive the cell-cycle model and random number generator, never used directly - boost uses this.
Parameters
archive the archive
version the current version of this class
Definition at line 61 of file StochasticDurationGenerationBasedCellCycleModel.hpp.
References SerializableSingleton< SINGLETON_CLASS >::GetSerializationWrapper(), and RandomNumberGenerator::Instance().
void StochasticDurationGenerationBasedCellCycleModel::SetG1Duration () protected virtual
Stochastically set the G1 duration. Called on cell creation at the start of a simulation, and for both parent and daughter cells at cell division.
Reimplemented from AbstractSimpleCellCycleModel.
Definition at line 81 of file StochasticDurationGenerationBasedCellCycleModel.cpp.
References AbstractCellCycleModel::GetStemCellG1Duration(), AbstractCellCycleModel::GetTransitCellG1Duration(), RandomNumberGenerator::Instance(), AbstractCellCycleModel::mG1Duration, AbstractCellCycleModel::mpCell, NEVER_REACHED, and RandomNumberGenerator::ranf().
Friends And Related Function Documentation
friend class boost::serialization::access friend
Needed for serialization.
Definition at line 53 of file StochasticDurationGenerationBasedCellCycleModel.hpp.
The documentation for this class was generated from the following files:
cell_based/src/cell/cycle/StochasticDurationGenerationBasedCellCycleModel.hpp
cell_based/src/cell/cycle/StochasticDurationGenerationBasedCellCycleModel.cpp