Chaste: StochasticDurationCellCycleModel Class Reference
StochasticDurationCellCycleModel Class Reference
#include <StochasticDurationCellCycleModel.hpp>
Public Member Functions
StochasticDurationCellCycleModel ()
void SetG1Duration ()
AbstractCellCycleModel * CreateCellCycleModel ()
virtual void OutputCellCycleModelParameters (out_stream &rParamsFile)
Public Member Functions inherited from AbstractSimpleCellCycleModel
AbstractSimpleCellCycleModel ()
virtual ~AbstractSimpleCellCycleModel ()
virtual void ResetForDivision ()
virtual void UpdateCellCyclePhase ()
void InitialiseDaughterCell ()
virtual void Initialise ()
Public Member Functions inherited from AbstractCellCycleModel
AbstractCellCycleModel ()
virtual ~AbstractCellCycleModel ()
void SetCell (CellPtr pCell)
CellPtr GetCell ()
virtual void SetBirthTime (double birthTime)
void SetDimension (unsigned dimension)
unsigned GetDimension ()
double GetBirthTime () const
double GetAge ()
virtual bool ReadyToDivide ()
CellCyclePhase GetCurrentCellCyclePhase ()
virtual double GetG1Duration ()
double GetStemCellG1Duration ()
double GetTransitCellG1Duration ()
double GetSG2MDuration ()
virtual double GetSDuration ()
virtual double GetG2Duration ()
virtual double GetMDuration ()
virtual void SetStemCellG1Duration (double stemCellG1Duration)
virtual void SetTransitCellG1Duration (double transitCellG1Duration)
void SetSDuration (double sDuration)
void SetG2Duration (double g2Duration)
void SetMDuration (double mDuration)
virtual double GetAverageTransitCellCycleTime ()
virtual double GetAverageStemCellCycleTime ()
virtual bool CanCellTerminallyDifferentiate ()
double GetMinimumGapDuration ()
void SetMinimumGapDuration (double minimumGapDuration)
void OutputCellCycleModelInfo (out_stream &rParamsFile)
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Friends
class TestSimpleCellCycleModels
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from AbstractCellCycleModel
CellPtr mpCell
double mBirthTime
CellCyclePhase mCurrentCellCyclePhase
double mG1Duration
bool mReadyToDivide
unsigned mDimension
double mMinimumGapDuration
double mStemCellG1Duration
double mTransitCellG1Duration
double mSDuration
double mG2Duration
double mMDuration
Detailed Description
A stochastic cell-cycle model where cells divide with a stochastic G1 phase duration.
For proliferative cells, the G1 phase duration is drawn from a uniform distribution on [T, T+2], where the parameter T depends on cell proliferative type as follows: if the cell has StemCellProliferativeType, then T is given by GetStemCellG1Duration(); and if the cell has TransitCellProliferativeType, then T is given by GetTransitCellG1Duration().
If the cell has DifferentiatedCellProliferativeType, then the G1 phase duration is set to be infinite, so that the cell will never divide.
Definition at line 54 of file StochasticDurationCellCycleModel.hpp.
Constructor & Destructor Documentation
StochasticDurationCellCycleModel::StochasticDurationCellCycleModel ()
Constructor - just a default, mBirthTime is now set in the AbstractCellCycleModel class. mG1Duration is set very high, it is set for the individual cells when InitialiseDaughterCell is called
Definition at line 42 of file StochasticDurationCellCycleModel.cpp.
Referenced by CreateCellCycleModel().
Member Function Documentation
AbstractCellCycleModel * StochasticDurationCellCycleModel::CreateCellCycleModel () virtual
Overridden builder method to create new copies of this cell-cycle model.
Returns
new cell-cycle model
Implements AbstractCellCycleModel.
Definition at line 47 of file StochasticDurationCellCycleModel.cpp.
References AbstractCellCycleModel::mBirthTime, AbstractCellCycleModel::mG2Duration, AbstractCellCycleModel::mMDuration, AbstractCellCycleModel::mMinimumGapDuration, AbstractCellCycleModel::mSDuration, AbstractCellCycleModel::mStemCellG1Duration, AbstractCellCycleModel::mTransitCellG1Duration, AbstractCellCycleModel::SetBirthTime(), AbstractCellCycleModel::SetG2Duration(), AbstractCellCycleModel::SetMDuration(), AbstractCellCycleModel::SetMinimumGapDuration(), AbstractCellCycleModel::SetSDuration(), AbstractCellCycleModel::SetStemCellG1Duration(), AbstractCellCycleModel::SetTransitCellG1Duration(), and StochasticDurationCellCycleModel().
void StochasticDurationCellCycleModel::OutputCellCycleModelParameters (out_stream & rParamsFile) virtual
Outputs cell cycle model parameters to file.
Parameters
rParamsFile the file stream to which the parameters are output
Reimplemented from AbstractSimpleCellCycleModel.
Definition at line 102 of file StochasticDurationCellCycleModel.cpp.
References AbstractSimpleCellCycleModel::OutputCellCycleModelParameters().
template<class Archive > void StochasticDurationCellCycleModel::serialize (Archive & archive, const unsigned int version) inline private
Archive the cell-cycle model and random number generator, never used directly - boost uses this.
Parameters
archive the archive
version the current version of this class
Definition at line 69 of file StochasticDurationCellCycleModel.hpp.
References SerializableSingleton< SINGLETON_CLASS >::GetSerializationWrapper(), and RandomNumberGenerator::Instance().
void StochasticDurationCellCycleModel::SetG1Duration () virtual
Overridden SetG1Duration Method to add stochastic cell cycle times
Reimplemented from AbstractSimpleCellCycleModel.
Definition at line 80 of file StochasticDurationCellCycleModel.cpp.
References AbstractCellCycleModel::GetStemCellG1Duration(), AbstractCellCycleModel::GetTransitCellG1Duration(), RandomNumberGenerator::Instance(), AbstractCellCycleModel::mG1Duration, AbstractCellCycleModel::mpCell, NEVER_REACHED, and RandomNumberGenerator::ranf().
Friends And Related Function Documentation
friend class boost::serialization::access friend
Needed for serialization.
Definition at line 61 of file StochasticDurationCellCycleModel.hpp.
The documentation for this class was generated from the following files:
cell_based/src/cell/cycle/StochasticDurationCellCycleModel.hpp
cell_based/src/cell/cycle/StochasticDurationCellCycleModel.cpp