Chaste: AbstractSimpleCellCycleModel Class Reference
AbstractSimpleCellCycleModel Class Reference
#include <AbstractSimpleCellCycleModel.hpp>
Public Member Functions
AbstractSimpleCellCycleModel ()
virtual ~AbstractSimpleCellCycleModel ()
virtual void ResetForDivision ()
virtual void UpdateCellCyclePhase ()
void InitialiseDaughterCell ()
virtual void Initialise ()
virtual void OutputCellCycleModelParameters (out_stream &rParamsFile)
Public Member Functions inherited from AbstractCellCycleModel
AbstractCellCycleModel ()
virtual ~AbstractCellCycleModel ()
void SetCell (CellPtr pCell)
CellPtr GetCell ()
virtual void SetBirthTime (double birthTime)
void SetDimension (unsigned dimension)
unsigned GetDimension ()
double GetBirthTime () const
double GetAge ()
virtual bool ReadyToDivide ()
virtual AbstractCellCycleModel * CreateCellCycleModel ()=0
CellCyclePhase GetCurrentCellCyclePhase ()
virtual double GetG1Duration ()
double GetStemCellG1Duration ()
double GetTransitCellG1Duration ()
double GetSG2MDuration ()
virtual double GetSDuration ()
virtual double GetG2Duration ()
virtual double GetMDuration ()
virtual void SetStemCellG1Duration (double stemCellG1Duration)
virtual void SetTransitCellG1Duration (double transitCellG1Duration)
void SetSDuration (double sDuration)
void SetG2Duration (double g2Duration)
void SetMDuration (double mDuration)
virtual double GetAverageTransitCellCycleTime ()
virtual double GetAverageStemCellCycleTime ()
virtual bool CanCellTerminallyDifferentiate ()
double GetMinimumGapDuration ()
void SetMinimumGapDuration (double minimumGapDuration)
void OutputCellCycleModelInfo (out_stream &rParamsFile)
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Protected Member Functions
virtual void SetG1Duration ()
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Friends
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from AbstractCellCycleModel
CellPtr mpCell
double mBirthTime
CellCyclePhase mCurrentCellCyclePhase
double mG1Duration
bool mReadyToDivide
unsigned mDimension
double mMinimumGapDuration
double mStemCellG1Duration
double mTransitCellG1Duration
double mSDuration
double mG2Duration
double mMDuration
Detailed Description
This class contains all the functionality shared by 'simple' cell-cycle models, where the duration of each cell cycle phase is determined when the cell-cycle model is created. Note that whether or not the cell should actually divide may still depend on further conditions in subclasses; for example, the cell may only divide if the local concentration of a signalling molecule is sufficiently high/
This class of cell-cycle models is distinct from 'ODE-based' cell-cycle models, where the duration of one or more cell cycle phases are evaluated 'on the fly' as the cell ages, according to a system of ordinary differential equations (ODEs) governing (for example) the concentrations of key intracellular proteins.
Definition at line 57 of file AbstractSimpleCellCycleModel.hpp.
Constructor & Destructor Documentation
AbstractSimpleCellCycleModel::AbstractSimpleCellCycleModel ()
Default constructor - creates an AbstractSimpleCellCycleModel.
Definition at line 42 of file AbstractSimpleCellCycleModel.cpp.
AbstractSimpleCellCycleModel::~AbstractSimpleCellCycleModel () virtual
Destructor.
Definition at line 46 of file AbstractSimpleCellCycleModel.cpp.
Member Function Documentation
void AbstractSimpleCellCycleModel::Initialise (void) virtual
See AbstractCellCycleModel::Initialise()
Reimplemented from AbstractCellCycleModel.
Reimplemented in SingleOdeWntCellCycleModel, and StochasticOxygenBasedCellCycleModel.
Definition at line 50 of file AbstractSimpleCellCycleModel.cpp.
References SetG1Duration().
Referenced by StochasticOxygenBasedCellCycleModel::Initialise(), and SingleOdeWntCellCycleModel::Initialise().
void AbstractSimpleCellCycleModel::InitialiseDaughterCell () virtual
Set the new cell's G1 duration once it has been created after division. The duration will be based on cell type.
Reimplemented from AbstractCellCycleModel.
Reimplemented in SimpleWntCellCycleModel, AbstractSimpleGenerationBasedCellCycleModel, and StochasticOxygenBasedCellCycleModel.
Definition at line 55 of file AbstractSimpleCellCycleModel.cpp.
References AbstractCellCycleModel::InitialiseDaughterCell(), and SetG1Duration().
Referenced by StochasticOxygenBasedCellCycleModel::InitialiseDaughterCell(), AbstractSimpleGenerationBasedCellCycleModel::InitialiseDaughterCell(), and SimpleWntCellCycleModel::InitialiseDaughterCell().
void AbstractSimpleCellCycleModel::OutputCellCycleModelParameters (out_stream & rParamsFile) virtual
Outputs cell cycle model parameters to file.
Parameters
rParamsFile the file stream to which the parameters are output
Implements AbstractCellCycleModel.
Reimplemented in SimpleWntCellCycleModel, SimpleOxygenBasedCellCycleModel, ContactInhibitionCellCycleModel, ExponentiallyDistributedStochasticDurationGenerationBasedCellCycleModel, SingleOdeWntCellCycleModel, AbstractSimpleGenerationBasedCellCycleModel, GammaDistributedStochasticDurationCellCycleModel, StochasticOxygenBasedCellCycleModel, StochasticDurationCellCycleModel, StochasticDurationGenerationBasedCellCycleModel, and FixedDurationGenerationBasedCellCycleModel.
Definition at line 117 of file AbstractSimpleCellCycleModel.cpp.
References AbstractCellCycleModel::OutputCellCycleModelParameters().
Referenced by StochasticDurationCellCycleModel::OutputCellCycleModelParameters(), GammaDistributedStochasticDurationCellCycleModel::OutputCellCycleModelParameters(), AbstractSimpleGenerationBasedCellCycleModel::OutputCellCycleModelParameters(), ContactInhibitionCellCycleModel::OutputCellCycleModelParameters(), SimpleOxygenBasedCellCycleModel::OutputCellCycleModelParameters(), and SimpleWntCellCycleModel::OutputCellCycleModelParameters().
void AbstractSimpleCellCycleModel::ResetForDivision () virtual
See AbstractCellCycleModel::ResetForDivision()
Reimplemented from AbstractCellCycleModel.
Reimplemented in StochasticOxygenBasedCellCycleModel, and AbstractSimpleGenerationBasedCellCycleModel.
Definition at line 83 of file AbstractSimpleCellCycleModel.cpp.
References SimulationTime::GetTime(), SimulationTime::Instance(), AbstractCellCycleModel::mBirthTime, AbstractCellCycleModel::ResetForDivision(), and SetG1Duration().
Referenced by AbstractSimpleGenerationBasedCellCycleModel::ResetForDivision(), and StochasticOxygenBasedCellCycleModel::ResetForDivision().
template<class Archive > void AbstractSimpleCellCycleModel::serialize (Archive & archive, const unsigned int version) inline private
Archive the cell-cycle model.
Parameters
archive the archive
version the current version of this class
Definition at line 70 of file AbstractSimpleCellCycleModel.hpp.
void AbstractSimpleCellCycleModel::SetG1Duration () protected virtual
Subclasses can override this function if they wish, this just allocates the default values for each of the different cell types' G1 durations as defined in AbstractCellCycleModel.
Reimplemented in SimpleWntCellCycleModel, ExponentiallyDistributedStochasticDurationGenerationBasedCellCycleModel, GammaDistributedStochasticDurationCellCycleModel, StochasticDurationCellCycleModel, and StochasticDurationGenerationBasedCellCycleModel.
Definition at line 61 of file AbstractSimpleCellCycleModel.cpp.
References AbstractCellCycleModel::GetStemCellG1Duration(), AbstractCellCycleModel::GetTransitCellG1Duration(), AbstractCellCycleModel::mG1Duration, AbstractCellCycleModel::mpCell, and NEVER_REACHED.
Referenced by Initialise(), InitialiseDaughterCell(), and ResetForDivision().
void AbstractSimpleCellCycleModel::UpdateCellCyclePhase () virtual
Default UpdateCellCyclePhase() method for a simple cell-cycle model.
Can be overridden if they should do something more subtle.
Implements AbstractCellCycleModel.
Reimplemented in SimpleWntCellCycleModel, SingleOdeWntCellCycleModel, SimpleOxygenBasedCellCycleModel, and ContactInhibitionCellCycleModel.
Definition at line 90 of file AbstractSimpleCellCycleModel.cpp.
References AbstractCellCycleModel::GetAge(), AbstractCellCycleModel::GetG2Duration(), AbstractCellCycleModel::GetMDuration(), AbstractCellCycleModel::GetSDuration(), AbstractCellCycleModel::mCurrentCellCyclePhase, AbstractCellCycleModel::mG1Duration, and AbstractCellCycleModel::mpCell.
Referenced by SimpleOxygenBasedCellCycleModel::UpdateCellCyclePhase(), SingleOdeWntCellCycleModel::UpdateCellCyclePhase(), and SimpleWntCellCycleModel::UpdateCellCyclePhase().
Friends And Related Function Documentation
friend class boost::serialization::access friend
Needed for serialization.
Definition at line 62 of file AbstractSimpleCellCycleModel.hpp.
The documentation for this class was generated from the following files:
cell_based/src/cell/cycle/AbstractSimpleCellCycleModel.hpp
cell_based/src/cell/cycle/AbstractSimpleCellCycleModel.cpp