Chaste: FarhadifarTypeModifier< DIM > Class Template Reference
FarhadifarTypeModifier< DIM > Class Template Reference
#include <FarhadifarTypeModifier.hpp>
Public Member Functions
FarhadifarTypeModifier ()
virtual ~FarhadifarTypeModifier ()
void UpdateTargetAreaOfCell (const CellPtr pCell)
void OutputSimulationModifierParameters (out_stream &rParamsFile)
Public Member Functions inherited from AbstractTargetAreaModifier< DIM >
AbstractTargetAreaModifier ()
virtual ~AbstractTargetAreaModifier ()
virtual void UpdateAtEndOfTimeStep (AbstractCellPopulation< DIM, DIM > &rCellPopulation)
virtual void SetupSolve (AbstractCellPopulation< DIM, DIM > &rCellPopulation, std::string outputDirectory)
double GetReferenceTargetArea ()
void SetReferenceTargetArea (double referenceTargetArea)
void UpdateTargetAreas (AbstractCellPopulation< DIM, DIM > &rCellPopulation)
Public Member Functions inherited from AbstractCellBasedSimulationModifier< DIM, DIM >
AbstractCellBasedSimulationModifier ()
virtual ~AbstractCellBasedSimulationModifier ()
virtual void UpdateAtEndOfTimeStep (AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM > &rCellPopulation)
virtual void UpdateAtEndOfOutputTimeStep (AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM > &rCellPopulation)
virtual void SetupSolve (AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM > &rCellPopulation, std::string outputDirectory)
virtual void UpdateAtEndOfSolve (AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM > &rCellPopulation)
void OutputSimulationModifierInfo (out_stream &rParamsFile)
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Friends
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from AbstractTargetAreaModifier< DIM >
double mReferenceTargetArea
Detailed Description
template<unsigned DIM>
class FarhadifarTypeModifier< DIM >
A modifier class in which the target area property of each cell is updated. It is used to implement growth in vertex-based simulations. The precise growth rule is that proposed by:
Farhadifar et al. 2007. The influence of cell mechanics, cell-cell interactions, and proliferation on epithelial packing. Current Biology 17(24):2095-2104. http://dx.doi.org/10.1016/j.cub.2007.11.049
Todo:
Consider renaming as FarhadifarTargetAreaModifier for clarity
Definition at line 58 of file FarhadifarTypeModifier.hpp.
Constructor & Destructor Documentation
template<unsigned DIM> FarhadifarTypeModifier< DIM >::FarhadifarTypeModifier ()
Default constructor.
Definition at line 39 of file FarhadifarTypeModifier.cpp.
template<unsigned DIM> FarhadifarTypeModifier< DIM >::~FarhadifarTypeModifier () virtual
Destructor.
Definition at line 45 of file FarhadifarTypeModifier.cpp.
Member Function Documentation
template<unsigned DIM> void FarhadifarTypeModifier< DIM >::OutputSimulationModifierParameters (out_stream & rParamsFile) virtual
Overridden OutputSimulationModifierParameters() method. Output any simulation modifier parameters to file.
Parameters
rParamsFile the file stream to which the parameters are output
Reimplemented from AbstractTargetAreaModifier< DIM >.
Definition at line 100 of file FarhadifarTypeModifier.cpp.
References AbstractTargetAreaModifier< DIM >::OutputSimulationModifierParameters().
template<unsigned DIM> template<class Archive > void FarhadifarTypeModifier< DIM >::serialize (Archive & archive, const unsigned int version) inline private
Boost Serialization method for archiving/checkpointing. Archives the object and its member variables.
Parameters
archive The boost archive.
version The current version of this class.
Definition at line 70 of file FarhadifarTypeModifier.hpp.
template<unsigned DIM> void FarhadifarTypeModifier< DIM >::UpdateTargetAreaOfCell (const CellPtr pCell) virtual
Helper method to update the target area property of an individual cell.
Parameters
pCell pointer to a cell
Todo:
: which cells are apoptotic? if they get apoptotic during G2-phase then this line has to be changed
At division, daughter cells inherit the cell data array from the mother cell. Here, we assign the target area that we want daughter cells to have to cells that we know to divide in this time step.
Todo:
This is a little hack that we might want to clean up in the future.
Implements AbstractTargetAreaModifier< DIM >.
Definition at line 50 of file FarhadifarTypeModifier.cpp.
References AbstractCellCycleModel::GetG1Duration(), AbstractCellCycleModel::GetG2Duration(), AbstractCellCycleModel::GetMDuration(), AbstractCellCycleModel::GetSDuration(), SimulationTime::GetTime(), and SimulationTime::Instance().
Friends And Related Function Documentation
template<unsigned DIM> friend class boost::serialization::access friend
Needed for serialization.
Definition at line 61 of file FarhadifarTypeModifier.hpp.
The documentation for this class was generated from the following files:
cell_based/src/simulation/modifiers/FarhadifarTypeModifier.hpp
cell_based/src/simulation/modifiers/FarhadifarTypeModifier.cpp