Chaste: OdeSystemForCoupledHeatEquationWithSource Class Reference
OdeSystemForCoupledHeatEquationWithSource Class Reference
#include <OdeSystemForCoupledHeatEquationWithSource.hpp>
Public Member Functions
OdeSystemForCoupledHeatEquationWithSource (double a)
void EvaluateYDerivatives (double time, const std::vector< double > &rY, std::vector< double > &rDY)
double GetA ()
Public Member Functions inherited from AbstractOdeSystemForCoupledPdeSystem
AbstractOdeSystemForCoupledPdeSystem (unsigned numberOfStateVariables=0, unsigned pdeSolutionSize=0)
std::vector< double > & rGetPdeSolution ()
void SetPdeSolution (std::vector< double > pdeSolution)
unsigned GetPdeSolutionSize ()
Public Member Functions inherited from AbstractOdeSystem
AbstractOdeSystem (unsigned numberOfStateVariables)
virtual ~AbstractOdeSystem ()
virtual bool CalculateStoppingEvent (double time, const std::vector< double > &rY)
virtual double CalculateRootFunction (double time, const std::vector< double > &rY)
bool GetUseAnalyticJacobian ()
const std::vector< double > & rGetConstStateVariables () const
Public Member Functions inherited from AbstractParameterisedSystem< std::vector< double > >
AbstractParameterisedSystem (unsigned numberOfStateVariables)
std::vector< double > & rGetStateVariables ()
std::vector< double > GetStateVariables ()
void SetStateVariables (const std::vector< double > &rStateVariables)
double GetStateVariable (unsigned index) const
double GetStateVariable (const std::string &rName) const
void SetStateVariable (unsigned index, double newValue)
void SetStateVariable (const std::string &rName, double newValue)
virtual void VerifyStateVariables ()
void SetDefaultInitialConditions (const std::vector< double > &rInitialConditions)
void SetDefaultInitialCondition (unsigned index, double initialCondition)
std::vector< double > GetInitialConditions () const
void ResetToInitialConditions ()
double GetParameter (unsigned index) const
double GetParameter (const std::string &rName) const
void SetParameter (const std::string &rName, double value)
void SetParameter (unsigned index, double value)
double GetAnyVariable (unsigned index, double time=0.0, std::vector< double > *pDerivedQuantities=NULL)
double GetAnyVariable (const std::string &rName, double time=0.0, std::vector< double > *pDerivedQuantities=NULL)
void SetAnyVariable (unsigned index, double value)
void SetAnyVariable (const std::string &rName, double value)
virtual std::vector< double > ComputeDerivedQuantities (double time, const std::vector< double > &rState)
std::vector< double > ComputeDerivedQuantitiesFromCurrentState (double time)
Public Member Functions inherited from AbstractUntemplatedParameterisedSystem
AbstractUntemplatedParameterisedSystem (unsigned numberOfStateVariables)
virtual ~AbstractUntemplatedParameterisedSystem ()
boost::shared_ptr< const
AbstractOdeSystemInformation > GetSystemInformation () const
std::string GetSystemName () const
unsigned GetNumberOfAttributes () const
bool HasAttribute (const std::string &rName) const
double GetAttribute (const std::string &rName) const
unsigned GetNumberOfStateVariables () const
const std::vector< std::string > & rGetStateVariableNames () const
const std::vector< std::string > & rGetStateVariableUnits () const
unsigned GetStateVariableIndex (const std::string &rName) const
bool HasStateVariable (const std::string &rName) const
std::string GetStateVariableUnits (unsigned index) const
unsigned GetNumberOfParameters () const
const std::vector< std::string > & rGetParameterNames () const
const std::vector< std::string > & rGetParameterUnits () const
unsigned GetParameterIndex (const std::string &rName) const
bool HasParameter (const std::string &rName) const
std::string GetParameterUnits (unsigned index) const
unsigned GetNumberOfDerivedQuantities () const
const std::vector< std::string > & rGetDerivedQuantityNames () const
const std::vector< std::string > & rGetDerivedQuantityUnits () const
unsigned GetDerivedQuantityIndex (const std::string &rName) const
bool HasDerivedQuantity (const std::string &rName) const
std::string GetDerivedQuantityUnits (unsigned index) const
unsigned GetAnyVariableIndex (const std::string &rName) const
bool HasAnyVariable (const std::string &rName) const
std::string GetAnyVariableUnits (unsigned index) const
std::string GetAnyVariableUnits (const std::string &rName) const
Private Attributes
double mA
Additional Inherited Members
Protected Member Functions inherited from AbstractParameterisedSystem< std::vector< double > >
std::string DumpState (const std::string &rMessage)
std::string DumpState (const std::string &rMessage, std::vector< double >Y)
std::string DumpState (const std::string &rMessage, std::vector< double >Y, double time)
void CheckParametersOnLoad (const std::vector< double > &rParameters, const std::vector< std::string > &rParameterNames)
Protected Attributes inherited from AbstractOdeSystemForCoupledPdeSystem
std::vector< double > mPdeSolution
unsigned mPdeSolutionSize
Protected Attributes inherited from AbstractOdeSystem
bool mUseAnalyticJacobian
Protected Attributes inherited from AbstractParameterisedSystem< std::vector< double > >
std::vector< double > mStateVariables
std::vector< double > mParameters
Protected Attributes inherited from AbstractUntemplatedParameterisedSystem
unsigned mNumberOfStateVariables
boost::shared_ptr
< AbstractOdeSystemInformation > mpSystemInfo
Detailed Description
An ODE system given by
dv/dt = a*v, v(0) = 1,
that 'couples' with (although in this case, is actually independent of) the heat equation with source term
u_t = del^2 u + v,
which is defined in the separate class HeatEquationWithSourceForCoupledOdeSystem.
Definition at line 53 of file OdeSystemForCoupledHeatEquationWithSource.hpp.
Constructor & Destructor Documentation
OdeSystemForCoupledHeatEquationWithSource::OdeSystemForCoupledHeatEquationWithSource (double a) inline
Constructor.
Parameters
a the value of the parameter mA
Definition at line 67 of file OdeSystemForCoupledHeatEquationWithSource.hpp.
References AbstractParameterisedSystem< std::vector< double > >::GetInitialConditions(), OdeSystemInformation< ODE_SYSTEM >::Instance(), AbstractUntemplatedParameterisedSystem::mpSystemInfo, and AbstractParameterisedSystem< std::vector< double > >::SetStateVariables().
Member Function Documentation
void OdeSystemForCoupledHeatEquationWithSource::EvaluateYDerivatives (double time, const std::vector< double > & rY, std::vector< double > & rDY) inline virtual
Method to evaluate the derivatives of the system.
Parameters
time the current time
rY the current values of the state variables
rDY storage for the derivatives of the system; will be filled in on return
Implements AbstractOdeSystem.
Definition at line 82 of file OdeSystemForCoupledHeatEquationWithSource.hpp.
References mA.
double OdeSystemForCoupledHeatEquationWithSource::GetA () inline
Returns
mA
Definition at line 90 of file OdeSystemForCoupledHeatEquationWithSource.hpp.
References mA.
Member Data Documentation
double OdeSystemForCoupledHeatEquationWithSource::mA private
A parameter for use in the ODE system.
Definition at line 58 of file OdeSystemForCoupledHeatEquationWithSource.hpp.
Referenced by EvaluateYDerivatives(), and GetA().
The documentation for this class was generated from the following file:
ode/src/fortests/OdeSystemForCoupledHeatEquationWithSource.hpp