Chaste: VanLeeuwen2009WntSwatCellCycleModelHypothesisTwo Class Reference
VanLeeuwen2009WntSwatCellCycleModelHypothesisTwo Class Reference
#include <VanLeeuwen2009WntSwatCellCycleModelHypothesisTwo.hpp>
Public Member Functions
VanLeeuwen2009WntSwatCellCycleModelHypothesisTwo (boost::shared_ptr< AbstractCellCycleModelOdeSolver > pOdeSolver=boost::shared_ptr< AbstractCellCycleModelOdeSolver >())
void InitialiseOdeSystem (double wntConcentration, boost::shared_ptr< AbstractCellMutationState > pMutationState)
AbstractCellCycleModel * CreateCellCycleModel ()
virtual void OutputCellCycleModelParameters (out_stream &rParamsFile)
Private Member Functions
template<class Archive>
void serialize (Archive &archive, const unsigned int version)
Friends
class boost::serialization::access
Detailed Description
Concrete Van Leeuwen 2009 cell-cycle model, using hypothesis two (see paper).
Definition at line 37 of file VanLeeuwen2009WntSwatCellCycleModelHypothesisTwo.hpp.
Constructor & Destructor Documentation
VanLeeuwen2009WntSwatCellCycleModelHypothesisTwo::VanLeeuwen2009WntSwatCellCycleModelHypothesisTwo (boost::shared_ptr< AbstractCellCycleModelOdeSolver > pOdeSolver = boost::shared_ptr<AbstractCellCycleModelOdeSolver>())
Default constructor calls base class.
Parameters:
pOdeSolver An optional pointer to a cell-cycle model ODE solver object (allows the use of different ODE solvers)
Definition at line 31 of file VanLeeuwen2009WntSwatCellCycleModelHypothesisTwo.cpp.
References CellCycleModelOdeSolver< CELL_CYCLE_MODEL, ODE_SOLVER >::Instance(), CellCycleModelOdeHandler::mpOdeSolver, and CellCycleModelOdeHandler::SetDt().
Referenced by CreateCellCycleModel().
Member Function Documentation
template<class Archive> void VanLeeuwen2009WntSwatCellCycleModelHypothesisTwo::serialize (Archive & archive, const unsigned int version) [inline, private]
Archive the cell-cycle model, never used directly - boost uses this.
Parameters:
archive the archive
version the current version of this class
Reimplemented from AbstractVanLeeuwen2009WntSwatCellCycleModel.
Definition at line 44 of file VanLeeuwen2009WntSwatCellCycleModelHypothesisTwo.hpp.
void VanLeeuwen2009WntSwatCellCycleModelHypothesisTwo::InitialiseOdeSystem (double wntConcentration, boost::shared_ptr< AbstractCellMutationState > pMutationState) [virtual]
Overloaded method which allocates the ODE system using HYPOTHESIS TWO.
Parameters:
wntConcentration Wnt concentration
pMutationState Mutation state
Implements AbstractVanLeeuwen2009WntSwatCellCycleModel.
Definition at line 50 of file VanLeeuwen2009WntSwatCellCycleModelHypothesisTwo.cpp.
References CellCycleModelOdeHandler::mpOdeSystem.
Referenced by CreateCellCycleModel().
AbstractCellCycleModel * VanLeeuwen2009WntSwatCellCycleModelHypothesisTwo::CreateCellCycleModel () [virtual]
Overridden builder method to create new copies of this cell-cycle model.
Implements AbstractCellCycleModel.
Definition at line 55 of file VanLeeuwen2009WntSwatCellCycleModelHypothesisTwo.cpp.
References AbstractWntOdeBasedCellCycleModel::GetWntLevel(), InitialiseOdeSystem(), AbstractCellCycleModel::mBirthTime, AbstractCellCycleModel::mCellProliferativeType, AbstractCellCycleModel::mDimension, AbstractOdeBasedCellCycleModel::mDivideTime, AbstractOdeBasedCellCycleModel::mFinishedRunningOdes, AbstractCellCycleModel::mG2Duration, AbstractOdeBasedCellCycleModel::mG2PhaseStartTime, CellCycleModelOdeHandler::mLastTime, AbstractCellCycleModel::mMDuration, AbstractCellCycleModel::mMinimumGapDuration, AbstractCellCycleModel::mpCell, CellCycleModelOdeHandler::mpOdeSolver, CellCycleModelOdeHandler::mpOdeSystem, AbstractCellCycleModel::mSDuration, AbstractCellCycleModel::mStemCellG1Duration, AbstractCellCycleModel::mTransitCellG1Duration, AbstractParameterisedSystem< VECTOR >::rGetStateVariables(), AbstractOdeBasedCellCycleModel::SetBirthTime(), AbstractCellCycleModel::SetCellProliferativeType(), AbstractCellCycleModel::SetDimension(), AbstractOdeBasedCellCycleModel::SetDivideTime(), AbstractOdeBasedCellCycleModel::SetFinishedRunningOdes(), AbstractCellCycleModel::SetG2Duration(), AbstractOdeBasedCellCycleModel::SetG2PhaseStartTime(), CellCycleModelOdeHandler::SetLastTime(), AbstractCellCycleModel::SetMDuration(), AbstractCellCycleModel::SetMinimumGapDuration(), AbstractCellCycleModel::SetSDuration(), CellCycleModelOdeHandler::SetStateVariables(), AbstractCellCycleModel::SetStemCellG1Duration(), AbstractCellCycleModel::SetTransitCellG1Duration(), and VanLeeuwen2009WntSwatCellCycleModelHypothesisTwo().
void VanLeeuwen2009WntSwatCellCycleModelHypothesisTwo::OutputCellCycleModelParameters (out_stream & rParamsFile) [virtual]
Outputs cell-cycle model parameters to file.
Parameters:
rParamsFile the file stream to which the parameters are output
Reimplemented from AbstractVanLeeuwen2009WntSwatCellCycleModel.
Definition at line 98 of file VanLeeuwen2009WntSwatCellCycleModelHypothesisTwo.cpp.
References AbstractVanLeeuwen2009WntSwatCellCycleModel::OutputCellCycleModelParameters().
Friends And Related Function Documentation
friend class boost::serialization::access [friend]
Needed for serialization.
Reimplemented from AbstractVanLeeuwen2009WntSwatCellCycleModel.
Definition at line 42 of file VanLeeuwen2009WntSwatCellCycleModelHypothesisTwo.hpp.
The documentation for this class was generated from the following files:
crypt/src/cell/cycle/VanLeeuwen2009WntSwatCellCycleModelHypothesisTwo.hpp
crypt/src/cell/cycle/VanLeeuwen2009WntSwatCellCycleModelHypothesisTwo.cpp