Chaste: AbstractMonodomainSolver< ELEMENT_DIM, SPACE_DIM > Class Template Reference
AbstractMonodomainSolver< ELEMENT_DIM, SPACE_DIM > Class Template Reference
#include <AbstractMonodomainSolver.hpp>
Public Member Functions
void PrepareForSetupLinearSystem (Vec currentSolution)
virtual void InitialiseForSolve (Vec initialSolution)
AbstractMonodomainSolver (AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM > *pMesh, MonodomainTissue< ELEMENT_DIM, SPACE_DIM > *pTissue, BoundaryConditionsContainer< ELEMENT_DIM, SPACE_DIM, 1 > *pBoundaryConditions, unsigned numQuadPoints=2)
virtual ~AbstractMonodomainSolver ()
Protected Attributes
BoundaryConditionsContainer
< ELEMENT_DIM, SPACE_DIM, 1 > * mpBoundaryConditions
MonodomainTissue< ELEMENT_DIM,
SPACE_DIM > * mpMonodomainTissue
MonodomainAssembler
< ELEMENT_DIM, SPACE_DIM > * mpMonodomainAssembler
unsigned mNumQuadPoints
Detailed Description
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM>
class AbstractMonodomainSolver< ELEMENT_DIM, SPACE_DIM >
Abstract Monodomain class containing some common functionality Inherits from AbstractDynamicLinearPdeSolver so child classes must implement SetupLinearSystem()
Definition at line 43 of file AbstractMonodomainSolver.hpp.
Constructor & Destructor Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> AbstractMonodomainSolver< ELEMENT_DIM, SPACE_DIM >::AbstractMonodomainSolver (AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM > * pMesh, MonodomainTissue< ELEMENT_DIM, SPACE_DIM > * pTissue, BoundaryConditionsContainer< ELEMENT_DIM, SPACE_DIM, 1 > * pBoundaryConditions, unsigned numQuadPoints = 2) [inline]
Constructor
Parameters:
pMesh pointer to the mesh
pTissue pointer to the tissue
pBoundaryConditions pointer to the boundary conditions
numQuadPoints number of quadrature points (defaults to 2)
Definition at line 105 of file AbstractMonodomainSolver.cpp.
References AbstractDynamicLinearPdeSolver< ELEMENT_DIM, SPACE_DIM, 1 >::mMatrixIsConstant, and AbstractMonodomainSolver< ELEMENT_DIM, SPACE_DIM >::mpMonodomainAssembler.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> AbstractMonodomainSolver< ELEMENT_DIM, SPACE_DIM >::~AbstractMonodomainSolver () [inline, virtual]
Destructor - just deletes assembler
Definition at line 124 of file AbstractMonodomainSolver.cpp.
References AbstractMonodomainSolver< ELEMENT_DIM, SPACE_DIM >::mpMonodomainAssembler.
Member Function Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void AbstractMonodomainSolver< ELEMENT_DIM, SPACE_DIM >::PrepareForSetupLinearSystem (Vec currentSolution) [inline, virtual]
Overloaded PrepareForSetupLinearSystem() methods which gets the cell models to solve themselves
Parameters:
currentSolution solution at current time
Reimplemented from AbstractLinearPdeSolver< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >.
Definition at line 66 of file AbstractMonodomainSolver.cpp.
References PdeSimulationTime::GetPdeTimeStep(), PdeSimulationTime::GetTime(), and AbstractMonodomainSolver< ELEMENT_DIM, SPACE_DIM >::mpMonodomainTissue.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void AbstractMonodomainSolver< ELEMENT_DIM, SPACE_DIM >::InitialiseForSolve (Vec initialSolution) [inline, virtual]
Overloaded InitialiseForSolve
Parameters:
initialSolution initial solution
Reimplemented from AbstractLinearPdeSolver< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >.
Reimplemented in MatrixBasedMonodomainSolver< ELEMENT_DIM, SPACE_DIM >.
Definition at line 76 of file AbstractMonodomainSolver.cpp.
References AbstractLinearPdeSolver< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::InitialiseForSolve(), HeartConfig::Instance(), AbstractLinearPdeSolver< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::mpLinearSystem, LinearSystem::SetAbsoluteTolerance(), LinearSystem::SetKspType(), LinearSystem::SetMatrixIsSymmetric(), LinearSystem::SetPcType(), LinearSystem::SetRelativeTolerance(), and LinearSystem::SetUseFixedNumberIterations().
Referenced by MatrixBasedMonodomainSolver< ELEMENT_DIM, SPACE_DIM >::InitialiseForSolve().
Member Data Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> BoundaryConditionsContainer<ELEMENT_DIM,SPACE_DIM,1>* AbstractMonodomainSolver< ELEMENT_DIM, SPACE_DIM >::mpBoundaryConditions [protected]
Boundary conditions
Definition at line 48 of file AbstractMonodomainSolver.hpp.
Referenced by MatrixBasedMonodomainSolver< ELEMENT_DIM, SPACE_DIM >::SetupLinearSystem(), and BasicMonodomainSolver< ELEMENT_DIM, SPACE_DIM >::SetupLinearSystem().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> MonodomainTissue<ELEMENT_DIM,SPACE_DIM>* AbstractMonodomainSolver< ELEMENT_DIM, SPACE_DIM >::mpMonodomainTissue [protected]
Monodomain tissue class (collection of cells, and conductivities)
Definition at line 51 of file AbstractMonodomainSolver.hpp.
Referenced by MatrixBasedMonodomainSolver< ELEMENT_DIM, SPACE_DIM >::MatrixBasedMonodomainSolver(), AbstractMonodomainSolver< ELEMENT_DIM, SPACE_DIM >::PrepareForSetupLinearSystem(), MatrixBasedMonodomainSolver< ELEMENT_DIM, SPACE_DIM >::SetupLinearSystem(), and BasicMonodomainSolver< ELEMENT_DIM, SPACE_DIM >::SetupLinearSystem().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> MonodomainAssembler<ELEMENT_DIM,SPACE_DIM>* AbstractMonodomainSolver< ELEMENT_DIM, SPACE_DIM >::mpMonodomainAssembler [protected]
The monodomain assembler, used to set up the LHS matrix; and RHS vector for BasicMonodomainSolver (but not MatrixBasedMonodomainSolver)
Definition at line 57 of file AbstractMonodomainSolver.hpp.
Referenced by AbstractMonodomainSolver< ELEMENT_DIM, SPACE_DIM >::AbstractMonodomainSolver(), MatrixBasedMonodomainSolver< ELEMENT_DIM, SPACE_DIM >::SetupLinearSystem(), BasicMonodomainSolver< ELEMENT_DIM, SPACE_DIM >::SetupLinearSystem(), and AbstractMonodomainSolver< ELEMENT_DIM, SPACE_DIM >::~AbstractMonodomainSolver().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> unsigned AbstractMonodomainSolver< ELEMENT_DIM, SPACE_DIM >::mNumQuadPoints [protected]
Number of quadrature points per dimension (only saved so it can be passed to the assembler
Definition at line 63 of file AbstractMonodomainSolver.hpp.
Referenced by MatrixBasedMonodomainSolver< ELEMENT_DIM, SPACE_DIM >::MatrixBasedMonodomainSolver(), MatrixBasedMonodomainSolver< ELEMENT_DIM, SPACE_DIM >::SetupLinearSystem(), and BasicMonodomainSolver< ELEMENT_DIM, SPACE_DIM >::SetupLinearSystem().
The documentation for this class was generated from the following files:
heart/src/solver/electrics/AbstractMonodomainSolver.hpp
heart/src/solver/electrics/AbstractMonodomainSolver.cpp