Chaste: WelikyOsterForce< DIM > Class Template Reference
WelikyOsterForce< DIM > Class Template Reference
#include <WelikyOsterForce.hpp>
Public Member Functions
WelikyOsterForce ()
~WelikyOsterForce ()
void AddForceContribution (std::vector< c_vector< double, DIM > > &rForces, AbstractCellPopulation< DIM > &rCellPopulation)
double GetWelikyOsterAreaParameter ()
double GetWelikyOsterPerimeterParameter ()
void SetWelikyOsterAreaParameter (double welikyOsterAreaParameter)
void SetWelikyOsterPerimeterParameter (double welikyOsterPerimeterParameter)
void OutputForceParameters (out_stream &rParamsFile)
Private Member Functions
template<class Archive>
void serialize (Archive &archive, const unsigned int version)
Private Attributes
double mWelikyOsterAreaParameter
double mWelikyOsterPerimeterParameter
Friends
class TestForces
class boost::serialization::access
Detailed Description
template<unsigned DIM>
class WelikyOsterForce< DIM >
A force class for use in vertex-based simulations, based on a mechanical model proposed by M. Weliky and G. Oster ("The mechanical basis of cell rearrangement. I. Epithelial morphogenesis during Fundulus epiboly", Development 109:373-386).
The default values for the two model parameter member variables are our own best estimates, since they are not given in the Weliky & Oster paper.
Definition at line 48 of file WelikyOsterForce.hpp.
Constructor & Destructor Documentation
template<unsigned DIM> WelikyOsterForce< DIM >::WelikyOsterForce () [inline]
Constructor.
Definition at line 31 of file WelikyOsterForce.cpp.
template<unsigned DIM> WelikyOsterForce< DIM >::~WelikyOsterForce () [inline]
Destructor.
Definition at line 39 of file WelikyOsterForce.cpp.
Member Function Documentation
template<unsigned DIM> template<class Archive> void WelikyOsterForce< DIM >::serialize (Archive & archive, const unsigned int version) [inline, private]
Serialize the object and its member variables.
Serialization of singleton objects must be done with care. Before the object is serialized via a pointer, it *MUST* be serialized directly, or an assertion will trip when a second instance of the class is created on de-serialization.
Parameters:
archive the archive
version the current version of this class
Reimplemented from AbstractForce< DIM >.
Definition at line 66 of file WelikyOsterForce.hpp.
References WelikyOsterForce< DIM >::mWelikyOsterAreaParameter, and WelikyOsterForce< DIM >::mWelikyOsterPerimeterParameter.
template<unsigned DIM> void WelikyOsterForce< DIM >::AddForceContribution (std::vector< c_vector< double, DIM > > & rForces, AbstractCellPopulation< DIM > & rCellPopulation) [inline, virtual]
Overridden AddForceContribution() method.
Calculates the force on each node in the vertex-based cell population based on the Weliky Oster model.
Parameters:
rForces reference to vector of forces on nodes
rCellPopulation reference to the cell population
Implements AbstractForce< DIM >.
Definition at line 44 of file WelikyOsterForce.cpp.
References EXCEPTION, VertexMesh< ELEMENT_DIM, SPACE_DIM >::GetElementIteratorBegin(), VertexMesh< ELEMENT_DIM, SPACE_DIM >::GetElementIteratorEnd(), VertexMesh< ELEMENT_DIM, SPACE_DIM >::GetSurfaceAreaOfElement(), VertexMesh< ELEMENT_DIM, SPACE_DIM >::GetVectorFromAtoB(), VertexMesh< ELEMENT_DIM, SPACE_DIM >::GetVolumeOfElement(), WelikyOsterForce< DIM >::GetWelikyOsterAreaParameter(), WelikyOsterForce< DIM >::GetWelikyOsterPerimeterParameter(), and VertexBasedCellPopulation< DIM >::rGetMesh().
template<unsigned DIM> double WelikyOsterForce< DIM >::GetWelikyOsterAreaParameter () [inline]
Returns:
mWelikyOsterAreaParameter.
Definition at line 120 of file WelikyOsterForce.cpp.
References WelikyOsterForce< DIM >::mWelikyOsterAreaParameter.
Referenced by WelikyOsterForce< DIM >::AddForceContribution().
template<unsigned DIM> double WelikyOsterForce< DIM >::GetWelikyOsterPerimeterParameter () [inline]
Returns:
mWelikyOsterPerimeterParameter.
Definition at line 126 of file WelikyOsterForce.cpp.
References WelikyOsterForce< DIM >::mWelikyOsterPerimeterParameter.
Referenced by WelikyOsterForce< DIM >::AddForceContribution().
template<unsigned DIM> void WelikyOsterForce< DIM >::SetWelikyOsterAreaParameter (double welikyOsterAreaParameter) [inline]
Set mWelikyOsterAreaParameter.
Parameters:
welikyOsterAreaParameter the new value of mWelikyOsterAreaParameter
Definition at line 132 of file WelikyOsterForce.cpp.
References WelikyOsterForce< DIM >::mWelikyOsterAreaParameter.
template<unsigned DIM> void WelikyOsterForce< DIM >::SetWelikyOsterPerimeterParameter (double welikyOsterPerimeterParameter) [inline]
Set mWelikyOsterPerimeterParameter.
Parameters:
welikyOsterPerimeterParameter the new value of mWlikyOsterPerimeterParameter
Definition at line 138 of file WelikyOsterForce.cpp.
References WelikyOsterForce< DIM >::mWelikyOsterPerimeterParameter.
template<unsigned DIM> void WelikyOsterForce< DIM >::OutputForceParameters (out_stream & rParamsFile) [inline, virtual]
Overridden OutputForceParameters() method.
Parameters:
rParamsFile the file stream to which the parameters are output
Implements AbstractForce< DIM >.
Definition at line 144 of file WelikyOsterForce.cpp.
References WelikyOsterForce< DIM >::mWelikyOsterAreaParameter, WelikyOsterForce< DIM >::mWelikyOsterPerimeterParameter, and AbstractForce< DIM >::OutputForceParameters().
Friends And Related Function Documentation
template<unsigned DIM> friend class boost::serialization::access [friend]
Needed for serialization.
Reimplemented from AbstractForce< DIM >.
Definition at line 64 of file WelikyOsterForce.hpp.
Member Data Documentation
template<unsigned DIM> double WelikyOsterForce< DIM >::mWelikyOsterAreaParameter [private]
Area parameter. Has units of kg (cell size at equilibrium rest length)^2 s^-2.
Definition at line 57 of file WelikyOsterForce.hpp.
Referenced by WelikyOsterForce< DIM >::GetWelikyOsterAreaParameter(), WelikyOsterForce< DIM >::OutputForceParameters(), WelikyOsterForce< DIM >::serialize(), and WelikyOsterForce< DIM >::SetWelikyOsterAreaParameter().
template<unsigned DIM> double WelikyOsterForce< DIM >::mWelikyOsterPerimeterParameter [private]
Perimeter parameter. Has units of kg s^-2 (cell size at equilibrium rest length)^-1.
Definition at line 62 of file WelikyOsterForce.hpp.
Referenced by WelikyOsterForce< DIM >::GetWelikyOsterPerimeterParameter(), WelikyOsterForce< DIM >::OutputForceParameters(), WelikyOsterForce< DIM >::serialize(), and WelikyOsterForce< DIM >::SetWelikyOsterPerimeterParameter().
The documentation for this class was generated from the following files:
cell_based/src/population/mechanics/WelikyOsterForce.hpp
cell_based/src/population/mechanics/WelikyOsterForce.cpp