Chaste: NagaiHondaForce< DIM > Class Template Reference
NagaiHondaForce< DIM > Class Template Reference
#include <NagaiHondaForce.hpp>
Public Member Functions
NagaiHondaForce ()
~NagaiHondaForce ()
void AddForceContribution (std::vector< c_vector< double, DIM > > &rForces, AbstractCellPopulation< DIM > &rCellPopulation)
virtual double GetAdhesionParameter (Node< DIM > *pNodeA, Node< DIM > *pNodeB, VertexBasedCellPopulation< DIM > &rVertexCellPopulation)
double GetNagaiHondaDeformationEnergyParameter ()
double GetNagaiHondaMembraneSurfaceEnergyParameter ()
double GetNagaiHondaCellCellAdhesionEnergyParameter ()
double GetNagaiHondaCellBoundaryAdhesionEnergyParameter ()
void SetNagaiHondaDeformationEnergyParameter (double nagaiHondaDeformationEnergyParameter)
void SetNagaiHondaMembraneSurfaceEnergyParameter (double nagaiHondaMembraneSurfaceEnergyParameter)
void SetNagaiHondaCellCellAdhesionEnergyParameter (double nagaiHondaCellCellAdhesionEnergyEnergyParameter)
void SetNagaiHondaCellBoundaryAdhesionEnergyParameter (double nagaiHondaCellBoundaryAdhesionEnergyParameter)
double GetTargetAreaOfCell (const CellPtr pCell) const
double GetMatureCellTargetArea () const
void SetMatureCellTargetArea (double matureCellTargetArea)
void OutputForceParameters (out_stream &rParamsFile)
Private Member Functions
template<class Archive>
void serialize (Archive &archive, const unsigned int version)
Private Attributes
double mNagaiHondaDeformationEnergyParameter
double mNagaiHondaMembraneSurfaceEnergyParameter
double mNagaiHondaCellCellAdhesionEnergyParameter
double mNagaiHondaCellBoundaryAdhesionEnergyParameter
double mMatureCellTargetArea
Friends
class TestForces
class boost::serialization::access
Detailed Description
template<unsigned DIM>
class NagaiHondaForce< DIM >
A force class for use in vertex-based simulations, based on a mechanical model proposed by T. Nagai and H. Honda ("A dynamic cell model for the formation of epithelial tissues", Philosophical Magazine Part B 81:699-719).
Each of the model parameter member variables are rescaled such that mDampingConstantNormal takes the default value 1, whereas Nagai and Honda (who denote the parameter by nu) take the value 0.01.
Definition at line 50 of file NagaiHondaForce.hpp.
Constructor & Destructor Documentation
template<unsigned DIM> NagaiHondaForce< DIM >::NagaiHondaForce () [inline]
Constructor.
Definition at line 31 of file NagaiHondaForce.cpp.
template<unsigned DIM> NagaiHondaForce< DIM >::~NagaiHondaForce () [inline]
Destructor.
Definition at line 42 of file NagaiHondaForce.cpp.
Member Function Documentation
template<unsigned DIM> template<class Archive> void NagaiHondaForce< DIM >::serialize (Archive & archive, const unsigned int version) [inline, private]
Serialize the object and its member variables.
Serialization of singleton objects must be done with care. Before the object is serialized via a pointer, it *MUST* be serialized directly, or an assertion will trip when a second instance of the class is created on de-serialization.
Parameters:
archive the archive
version the current version of this class
Reimplemented from AbstractForce< DIM >.
Definition at line 83 of file NagaiHondaForce.hpp.
References NagaiHondaForce< DIM >::mMatureCellTargetArea, NagaiHondaForce< DIM >::mNagaiHondaCellBoundaryAdhesionEnergyParameter, NagaiHondaForce< DIM >::mNagaiHondaCellCellAdhesionEnergyParameter, NagaiHondaForce< DIM >::mNagaiHondaDeformationEnergyParameter, and NagaiHondaForce< DIM >::mNagaiHondaMembraneSurfaceEnergyParameter.
template<unsigned DIM> void NagaiHondaForce< DIM >::AddForceContribution (std::vector< c_vector< double, DIM > > & rForces, AbstractCellPopulation< DIM > & rCellPopulation) [inline, virtual]
Overridden AddForceContribution() method.
Calculates the force on each node in the vertex-based cell population based on the Nagai Honda model.
Parameters:
rForces reference to vector of forces on nodes
rCellPopulation reference to the cell population
Implements AbstractForce< DIM >.
Definition at line 47 of file NagaiHondaForce.cpp.
References EXCEPTION, NagaiHondaForce< DIM >::GetAdhesionParameter(), VertexMesh< ELEMENT_DIM, SPACE_DIM >::GetAreaGradientOfElementAtNode(), AbstractCellPopulation< DIM >::GetCellUsingLocationIndex(), VertexBasedCellPopulation< DIM >::GetElement(), AbstractElement< ELEMENT_DIM, SPACE_DIM >::GetIndex(), NagaiHondaForce< DIM >::GetNagaiHondaDeformationEnergyParameter(), NagaiHondaForce< DIM >::GetNagaiHondaMembraneSurfaceEnergyParameter(), VertexMesh< ELEMENT_DIM, SPACE_DIM >::GetNextEdgeGradientOfElementAtNode(), AbstractElement< ELEMENT_DIM, SPACE_DIM >::GetNode(), VertexBasedCellPopulation< DIM >::GetNode(), VertexElement< ELEMENT_DIM, SPACE_DIM >::GetNodeLocalIndex(), AbstractElement< ELEMENT_DIM, SPACE_DIM >::GetNumNodes(), VertexBasedCellPopulation< DIM >::GetNumNodes(), VertexMesh< ELEMENT_DIM, SPACE_DIM >::GetPerimeterGradientOfElementAtNode(), VertexMesh< ELEMENT_DIM, SPACE_DIM >::GetPreviousEdgeGradientOfElementAtNode(), VertexMesh< ELEMENT_DIM, SPACE_DIM >::GetSurfaceAreaOfElement(), NagaiHondaForce< DIM >::GetTargetAreaOfCell(), VertexMesh< ELEMENT_DIM, SPACE_DIM >::GetVolumeOfElement(), and VertexBasedCellPopulation< DIM >::rGetMesh().
template<unsigned DIM> double NagaiHondaForce< DIM >::GetAdhesionParameter (Node< DIM > * pNodeA, Node< DIM > * pNodeB, VertexBasedCellPopulation< DIM > & rVertexCellPopulation) [inline, virtual]
Get the adhesion parameter for the edge between two given nodes.
Parameters:
pNodeA one node
pNodeB the other node
rVertexCellPopulation reference to the cell population
Returns:
the adhesion parameter for this edge.
Definition at line 164 of file NagaiHondaForce.cpp.
References NagaiHondaForce< DIM >::GetNagaiHondaCellBoundaryAdhesionEnergyParameter(), NagaiHondaForce< DIM >::GetNagaiHondaCellCellAdhesionEnergyParameter(), and Node< SPACE_DIM >::rGetContainingElementIndices().
Referenced by NagaiHondaForce< DIM >::AddForceContribution().
template<unsigned DIM> double NagaiHondaForce< DIM >::GetNagaiHondaDeformationEnergyParameter () [inline]
Returns:
mNagaiHondaDeformationEnergyParameter
Definition at line 193 of file NagaiHondaForce.cpp.
References NagaiHondaForce< DIM >::mNagaiHondaDeformationEnergyParameter.
Referenced by NagaiHondaForce< DIM >::AddForceContribution().
template<unsigned DIM> double NagaiHondaForce< DIM >::GetNagaiHondaMembraneSurfaceEnergyParameter () [inline]
Returns:
mNagaiHondaMembraneSurfaceEnergyParameter
Definition at line 199 of file NagaiHondaForce.cpp.
References NagaiHondaForce< DIM >::mNagaiHondaMembraneSurfaceEnergyParameter.
Referenced by NagaiHondaForce< DIM >::AddForceContribution().
template<unsigned DIM> double NagaiHondaForce< DIM >::GetNagaiHondaCellCellAdhesionEnergyParameter () [inline]
Returns:
mCellCellAdhesionEnergyParameter
Definition at line 205 of file NagaiHondaForce.cpp.
References NagaiHondaForce< DIM >::mNagaiHondaCellCellAdhesionEnergyParameter.
Referenced by NagaiHondaForce< DIM >::GetAdhesionParameter().
template<unsigned DIM> double NagaiHondaForce< DIM >::GetNagaiHondaCellBoundaryAdhesionEnergyParameter () [inline]
Returns:
mNagaiHondaCellBoundaryAdhesionEnergyParameter
Definition at line 211 of file NagaiHondaForce.cpp.
References NagaiHondaForce< DIM >::mNagaiHondaCellBoundaryAdhesionEnergyParameter.
Referenced by NagaiHondaForce< DIM >::GetAdhesionParameter().
template<unsigned DIM> void NagaiHondaForce< DIM >::SetNagaiHondaDeformationEnergyParameter (double nagaiHondaDeformationEnergyParameter) [inline]
Set mNagaiHondaDeformationEnergyParameter.
Parameters:
nagaiHondaDeformationEnergyParameter the new value of mNagaiHondaDeformationEnergyParameter
Definition at line 217 of file NagaiHondaForce.cpp.
References NagaiHondaForce< DIM >::mNagaiHondaDeformationEnergyParameter.
template<unsigned DIM> void NagaiHondaForce< DIM >::SetNagaiHondaMembraneSurfaceEnergyParameter (double nagaiHondaMembraneSurfaceEnergyParameter) [inline]
Set mNagaiHondaMembraneSurfaceEnergyParameter.
Parameters:
nagaiHondaMembraneSurfaceEnergyParameter the new value of mNagaiHondaMembraneSurfaceEnergyParameter
Definition at line 223 of file NagaiHondaForce.cpp.
References NagaiHondaForce< DIM >::mNagaiHondaMembraneSurfaceEnergyParameter.
template<unsigned DIM> void NagaiHondaForce< DIM >::SetNagaiHondaCellCellAdhesionEnergyParameter (double nagaiHondaCellCellAdhesionEnergyEnergyParameter) [inline]
Set mNagaiHondaCellCellAdhesionEnergyParameter.
Parameters:
nagaiHondaCellCellAdhesionEnergyEnergyParameter the new value of mNagaiHondaCellCellAdhesionEnergyParameter
Definition at line 229 of file NagaiHondaForce.cpp.
References NagaiHondaForce< DIM >::mNagaiHondaCellCellAdhesionEnergyParameter.
template<unsigned DIM> void NagaiHondaForce< DIM >::SetNagaiHondaCellBoundaryAdhesionEnergyParameter (double nagaiHondaCellBoundaryAdhesionEnergyParameter) [inline]
Set mNagaiHondaCellBoundaryAdhesionEnergyParameter.
Parameters:
nagaiHondaCellBoundaryAdhesionEnergyParameter the new value of mNagaiHondaCellBoundaryAdhesionEnergyParameter
Definition at line 235 of file NagaiHondaForce.cpp.
References NagaiHondaForce< DIM >::mNagaiHondaCellBoundaryAdhesionEnergyParameter.
template<unsigned DIM> double NagaiHondaForce< DIM >::GetTargetAreaOfCell (const CellPtr pCell) const [inline]
Get the target area of a given cell. This grows linearly from 0.5*A to A during the G1 phase of the cell cycle, then remains at A for the rest of the cell cycle, where A denotes the member variable mMatureCellTargetArea.
Parameters:
pCell the cell
Returns:
the cell's target area
Definition at line 241 of file NagaiHondaForce.cpp.
References SimulationTime::GetTime(), SimulationTime::Instance(), and NagaiHondaForce< DIM >::mMatureCellTargetArea.
Referenced by NagaiHondaForce< DIM >::AddForceContribution().
template<unsigned DIM> double NagaiHondaForce< DIM >::GetMatureCellTargetArea () const [inline]
Returns:
mMatureCellTargetArea
Definition at line 286 of file NagaiHondaForce.cpp.
References NagaiHondaForce< DIM >::mMatureCellTargetArea.
template<unsigned DIM> void NagaiHondaForce< DIM >::SetMatureCellTargetArea (double matureCellTargetArea) [inline]
Set mMatureCellTargetArea.
Parameters:
matureCellTargetArea the new value of mMatureCellTargetArea
Definition at line 292 of file NagaiHondaForce.cpp.
References NagaiHondaForce< DIM >::mMatureCellTargetArea.
template<unsigned DIM> void NagaiHondaForce< DIM >::OutputForceParameters (out_stream & rParamsFile) [inline, virtual]
Overridden OutputForceParameters() method.
Parameters:
rParamsFile the file stream to which the parameters are output
Implements AbstractForce< DIM >.
Definition at line 299 of file NagaiHondaForce.cpp.
References NagaiHondaForce< DIM >::mMatureCellTargetArea, NagaiHondaForce< DIM >::mNagaiHondaCellBoundaryAdhesionEnergyParameter, NagaiHondaForce< DIM >::mNagaiHondaCellCellAdhesionEnergyParameter, NagaiHondaForce< DIM >::mNagaiHondaDeformationEnergyParameter, NagaiHondaForce< DIM >::mNagaiHondaMembraneSurfaceEnergyParameter, and AbstractForce< DIM >::OutputForceParameters().
Friends And Related Function Documentation
template<unsigned DIM> friend class boost::serialization::access [friend]
Needed for serialization.
Reimplemented from AbstractForce< DIM >.
Definition at line 81 of file NagaiHondaForce.hpp.
Member Data Documentation
template<unsigned DIM> double NagaiHondaForce< DIM >::mNagaiHondaDeformationEnergyParameter [private]
Cell deformation energy parameter. Has units of kg s^-2 (cell size at equilibrium rest length)^-1.
Definition at line 59 of file NagaiHondaForce.hpp.
Referenced by NagaiHondaForce< DIM >::GetNagaiHondaDeformationEnergyParameter(), NagaiHondaForce< DIM >::OutputForceParameters(), NagaiHondaForce< DIM >::serialize(), and NagaiHondaForce< DIM >::SetNagaiHondaDeformationEnergyParameter().
template<unsigned DIM> double NagaiHondaForce< DIM >::mNagaiHondaMembraneSurfaceEnergyParameter [private]
Cell membrane energy parameter. Has units of kg (cell size at equilibrium rest length) s^-2.
Definition at line 64 of file NagaiHondaForce.hpp.
Referenced by NagaiHondaForce< DIM >::GetNagaiHondaMembraneSurfaceEnergyParameter(), NagaiHondaForce< DIM >::OutputForceParameters(), NagaiHondaForce< DIM >::serialize(), and NagaiHondaForce< DIM >::SetNagaiHondaMembraneSurfaceEnergyParameter().
template<unsigned DIM> double NagaiHondaForce< DIM >::mNagaiHondaCellCellAdhesionEnergyParameter [private]
Cell-cell adhesion energy parameter. Has has units of kg (cell size at equilibrium rest length)^2 s^-2.
Definition at line 69 of file NagaiHondaForce.hpp.
Referenced by NagaiHondaForce< DIM >::GetNagaiHondaCellCellAdhesionEnergyParameter(), NagaiHondaForce< DIM >::OutputForceParameters(), NagaiHondaForce< DIM >::serialize(), and NagaiHondaForce< DIM >::SetNagaiHondaCellCellAdhesionEnergyParameter().
template<unsigned DIM> double NagaiHondaForce< DIM >::mNagaiHondaCellBoundaryAdhesionEnergyParameter [private]
Cell-boundary adhesion energy parameter. Has units of kg (cell size at equilibrium rest length)^2 s^-2.
Definition at line 74 of file NagaiHondaForce.hpp.
Referenced by NagaiHondaForce< DIM >::GetNagaiHondaCellBoundaryAdhesionEnergyParameter(), NagaiHondaForce< DIM >::OutputForceParameters(), NagaiHondaForce< DIM >::serialize(), and NagaiHondaForce< DIM >::SetNagaiHondaCellBoundaryAdhesionEnergyParameter().
template<unsigned DIM> double NagaiHondaForce< DIM >::mMatureCellTargetArea [private]
Non-dimensional target area of a mature (fully-grown) Cell.
Definition at line 79 of file NagaiHondaForce.hpp.
Referenced by NagaiHondaForce< DIM >::GetMatureCellTargetArea(), NagaiHondaForce< DIM >::GetTargetAreaOfCell(), NagaiHondaForce< DIM >::OutputForceParameters(), NagaiHondaForce< DIM >::serialize(), and NagaiHondaForce< DIM >::SetMatureCellTargetArea().
The documentation for this class was generated from the following files:
cell_based/src/population/mechanics/NagaiHondaForce.hpp
cell_based/src/population/mechanics/NagaiHondaForce.cpp