Chaste: VertexElement< 1, SPACE_DIM > Class Template Reference
VertexElement< 1, SPACE_DIM > Class Template Reference
#include <VertexElement.hpp>
Public Member Functions
VertexElement (unsigned index, const std::vector< Node< SPACE_DIM > * > &rNodes)
virtual ~VertexElement ()
unsigned GetNumFaces () const
void UpdateNode (const unsigned &rIndex, Node< SPACE_DIM > *pNode)
void RegisterWithNodes ()
void MarkAsDeleted ()
void ResetIndex (unsigned index)
void DeleteNode (const unsigned &rIndex)
void AddNode (const unsigned &rIndex, Node< SPACE_DIM > *pNode)
unsigned GetNodeLocalIndex (unsigned globalIndex) const
VertexElement< 0, SPACE_DIM > * GetFace (unsigned index) const
bool FaceIsOrientatedClockwise (unsigned index) const
bool IsElementOnBoundary () const
Detailed Description
template<unsigned SPACE_DIM>
class VertexElement< 1, SPACE_DIM >
Specialization for 1d elements so we don't get errors from Boost on some compilers.
Definition at line 241 of file VertexElement.hpp.
Constructor & Destructor Documentation
template<unsigned SPACE_DIM> VertexElement< 1, SPACE_DIM >::VertexElement (unsigned index, const std::vector< Node< SPACE_DIM > * > & rNodes) [inline]
Constructor which takes in a vector of nodes.
Parameters:
index the index of the element in the mesh
rNodes the nodes owned by the element
Specialization for 1d elements so we don't get errors from Boost on some compilers.
Definition at line 286 of file VertexElement.cpp.
References AbstractElement< ELEMENT_DIM, SPACE_DIM >::mNodes.
template<unsigned SPACE_DIM> VertexElement< 1, SPACE_DIM >::~VertexElement () [inline, virtual]
Virtual destructor, since this class has virtual methods.
Definition at line 295 of file VertexElement.cpp.
Member Function Documentation
template<unsigned SPACE_DIM> unsigned VertexElement< 1, SPACE_DIM >::GetNumFaces () const [inline]
Get the number of faces owned by this element.
Definition at line 300 of file VertexElement.cpp.
template<unsigned SPACE_DIM> void VertexElement< 1, SPACE_DIM >::UpdateNode (const unsigned & rIndex, Node< SPACE_DIM > * pNode) [inline, virtual]
Update node at the given index.
Parameters:
rIndex is an local index to which node to change
pNode is a pointer to the replacement node
Implements AbstractElement< 1, SPACE_DIM >.
Definition at line 339 of file VertexElement.cpp.
References AbstractElement< ELEMENT_DIM, SPACE_DIM >::mIndex, and AbstractElement< ELEMENT_DIM, SPACE_DIM >::mNodes.
template<unsigned SPACE_DIM> void VertexElement< 1, SPACE_DIM >::RegisterWithNodes () [inline, virtual]
Overridden RegisterWithNodes() method.
Informs all nodes forming this element that they are in this element.
Implements AbstractElement< 1, SPACE_DIM >.
Definition at line 306 of file VertexElement.cpp.
References AbstractElement< ELEMENT_DIM, SPACE_DIM >::mIndex, and AbstractElement< ELEMENT_DIM, SPACE_DIM >::mNodes.
template<unsigned SPACE_DIM> void VertexElement< 1, SPACE_DIM >::MarkAsDeleted () [inline, virtual]
Overridden MarkAsDeleted() method.
Mark an element as having been removed from the mesh. Also notify nodes in the element that it has been removed.
Implements AbstractElement< 1, SPACE_DIM >.
Definition at line 315 of file VertexElement.cpp.
References AbstractElement< ELEMENT_DIM, SPACE_DIM >::GetNumNodes(), AbstractElement< ELEMENT_DIM, SPACE_DIM >::mIndex, AbstractElement< ELEMENT_DIM, SPACE_DIM >::mIsDeleted, and AbstractElement< ELEMENT_DIM, SPACE_DIM >::mNodes.
template<unsigned SPACE_DIM> void VertexElement< 1, SPACE_DIM >::ResetIndex (unsigned index) [inline]
Reset the global index of the element and update its nodes.
Parameters:
index the new global index
Definition at line 328 of file VertexElement.cpp.
References AbstractElement< ELEMENT_DIM, SPACE_DIM >::GetNumNodes(), AbstractElement< ELEMENT_DIM, SPACE_DIM >::mIndex, AbstractElement< ELEMENT_DIM, SPACE_DIM >::mNodes, and VertexElement< ELEMENT_DIM, SPACE_DIM >::RegisterWithNodes().
template<unsigned SPACE_DIM> void VertexElement< 1, SPACE_DIM >::DeleteNode (const unsigned & rIndex) [inline]
Delete a node with given local index.
Parameters:
rIndex is the local index of the node to remove
Definition at line 354 of file VertexElement.cpp.
References AbstractElement< ELEMENT_DIM, SPACE_DIM >::mIndex, and AbstractElement< ELEMENT_DIM, SPACE_DIM >::mNodes.
template<unsigned SPACE_DIM> void VertexElement< 1, SPACE_DIM >::AddNode (const unsigned & rIndex, Node< SPACE_DIM > * pNode) [inline]
Add a node to the element between nodes at rIndex and rIndex+1.
Parameters:
rIndex the local index of the node after which the new node is added
pNode a pointer to the new node
Definition at line 366 of file VertexElement.cpp.
References AbstractElement< ELEMENT_DIM, SPACE_DIM >::mIndex, and AbstractElement< ELEMENT_DIM, SPACE_DIM >::mNodes.
template<unsigned SPACE_DIM> unsigned VertexElement< 1, SPACE_DIM >::GetNodeLocalIndex (unsigned globalIndex) const [inline]
Calculate the local index of a node given a global index if node is not contained in element return UINT_MAX
Parameters:
globalIndex the global index of the node in the mesh
Returns:
local_index.
Definition at line 378 of file VertexElement.cpp.
References AbstractElement< ELEMENT_DIM, SPACE_DIM >::GetNodeGlobalIndex(), and AbstractElement< ELEMENT_DIM, SPACE_DIM >::mNodes.
template<unsigned SPACE_DIM> VertexElement< 0, SPACE_DIM > * VertexElement< 1, SPACE_DIM >::GetFace (unsigned index) const [inline]
Parameters:
index the global index of a specified face
Returns:
a pointer to the face
Definition at line 392 of file VertexElement.cpp.
template<unsigned SPACE_DIM> bool VertexElement< 1, SPACE_DIM >::FaceIsOrientatedClockwise (unsigned index) const [inline]
Get whether the face with a given index is oriented clockwise.
Parameters:
index the index of the face
Definition at line 398 of file VertexElement.cpp.
template<unsigned SPACE_DIM> bool VertexElement< 1, SPACE_DIM >::IsElementOnBoundary () const [inline]
Get whether or not the element is on the boundary by seeing if contains boundary nodes.
Returns:
whether or not the element is on the boundary.
Definition at line 404 of file VertexElement.cpp.
References AbstractElement< ELEMENT_DIM, SPACE_DIM >::GetNode(), and AbstractElement< ELEMENT_DIM, SPACE_DIM >::mNodes.
The documentation for this class was generated from the following files:
mesh/src/vertex/VertexElement.hpp
mesh/src/vertex/VertexElement.cpp