Chaste: FaberRudy2000Version3 Class Reference
FaberRudy2000Version3 Class Reference
Inherits AbstractCardiacCell.
Public Member Functions
FaberRudy2000Version3 (boost::shared_ptr< AbstractIvpOdeSolver > pSolver, boost::shared_ptr< AbstractStimulusFunction > pIntracellularStimulus)
~FaberRudy2000Version3 (void)
void SetScaleFactorGks (double sfgks)
void SetScaleFactorIto (double sfito)
void SetScaleFactorGkr (double sfgkr)
double GetIIonic ()
void EvaluateYDerivatives (double var_environment__time, const std::vector< double > &rY, std::vector< double > &rDY)
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Private Attributes
double mScaleFactorGks
double mScaleFactorIto
double mScaleFactorGkr
Friends
class boost::serialization::access
Detailed Description
Definition at line 24 of file FaberRudy2000Version3.hpp.
Constructor & Destructor Documentation
FaberRudy2000Version3::FaberRudy2000Version3 (boost::shared_ptr< AbstractIvpOdeSolver > pSolver, boost::shared_ptr< AbstractStimulusFunction > pIntracellularStimulus)
Constructor
Parameters:
pSolver is a pointer to the ODE solver
pIntracellularStimulus is a pointer to the intracellular stimulus
Definition at line 21 of file FaberRudy2000Version3.cpp.
References AbstractCardiacCell::Init(), AbstractOdeSystem::mpSystemInfo, mScaleFactorGkr, mScaleFactorGks, and mScaleFactorIto.
FaberRudy2000Version3::~FaberRudy2000Version3 (void)
Destructor
Definition at line 34 of file FaberRudy2000Version3.cpp.
Member Function Documentation
void FaberRudy2000Version3::EvaluateYDerivatives (double var_environment__time, const std::vector< double > & rY, std::vector< double > & rDY) [virtual]
Evaluate the derivatives of the state variables
Parameters:
var_Environment__time the current time, in milliseconds
rY current values of the state variables
rDY to be filled in with derivatives
Implements AbstractOdeSystem.
Definition at line 301 of file FaberRudy2000Version3.cpp.
References AbstractCardiacCell::GetStimulus(), mScaleFactorGkr, mScaleFactorGks, mScaleFactorIto, and AbstractCardiacCell::mSetVoltageDerivativeToZero.
double FaberRudy2000Version3::GetIIonic () [virtual]
Calculates the ionic current
Returns:
the total ionic current
Implements AbstractCardiacCell.
Definition at line 56 of file FaberRudy2000Version3.cpp.
References mScaleFactorGkr, mScaleFactorGks, mScaleFactorIto, and AbstractOdeSystem::rGetStateVariables().
template<class Archive > void FaberRudy2000Version3::serialize (Archive & archive, const unsigned int version) [inline, private]
Archive the member variables.
Parameters:
archive
version
Reimplemented from AbstractCardiacCell.
Definition at line 43 of file FaberRudy2000Version3.hpp.
void FaberRudy2000Version3::SetScaleFactorGkr (double sfgkr)
Set the scale factor for Gkr (might be useful for simulating LQT2)
Parameters:
sfgkr
Definition at line 50 of file FaberRudy2000Version3.cpp.
References mScaleFactorGkr.
Referenced by HeartConfigRelatedCellFactory< SPACE_DIM >::CreateCellWithIntracellularStimulus().
void FaberRudy2000Version3::SetScaleFactorGks (double sfgks)
Set the scale factor for Gks
Parameters:
sfgks
Definition at line 38 of file FaberRudy2000Version3.cpp.
References mScaleFactorGks.
Referenced by HeartConfigRelatedCellFactory< SPACE_DIM >::CreateCellWithIntracellularStimulus().
void FaberRudy2000Version3::SetScaleFactorIto (double sfito)
Set the scale factor for Ito
Parameters:
sfito
Definition at line 44 of file FaberRudy2000Version3.cpp.
References mScaleFactorIto.
Referenced by HeartConfigRelatedCellFactory< SPACE_DIM >::CreateCellWithIntracellularStimulus().
Friends And Related Function Documentation
friend class boost::serialization::access [friend]
Needed for serialization.
Reimplemented from AbstractCardiacCell.
Definition at line 35 of file FaberRudy2000Version3.hpp.
Member Data Documentation
double FaberRudy2000Version3::mScaleFactorGkr [private]
Scale factor for Gkr
Definition at line 32 of file FaberRudy2000Version3.hpp.
Referenced by EvaluateYDerivatives(), FaberRudy2000Version3(), GetIIonic(), and SetScaleFactorGkr().
double FaberRudy2000Version3::mScaleFactorGks [private]
Scale factor for Gks
Definition at line 28 of file FaberRudy2000Version3.hpp.
Referenced by EvaluateYDerivatives(), FaberRudy2000Version3(), GetIIonic(), and SetScaleFactorGks().
double FaberRudy2000Version3::mScaleFactorIto [private]
Scale factor for Gto
Definition at line 30 of file FaberRudy2000Version3.hpp.
Referenced by EvaluateYDerivatives(), FaberRudy2000Version3(), GetIIonic(), and SetScaleFactorIto().
The documentation for this class was generated from the following files:
/tmp/release_2.0/heart/src/odes/ionicmodels/FaberRudy2000Version3.hpp
/tmp/release_2.0/heart/src/odes/ionicmodels/FaberRudy2000Version3.cpp