Chaste: FaberRudy2000Version3Optimised Class Reference
FaberRudy2000Version3Optimised Class Reference
Inherits AbstractCardiacCell.
Public Member Functions
FaberRudy2000Version3Optimised (boost::shared_ptr< AbstractIvpOdeSolver > pSolver, boost::shared_ptr< AbstractStimulusFunction > pIntracellularStimulus)
double GetIIonic ()
void EvaluateYDerivatives (double var_environment__time, const std::vector< double > &rY, std::vector< double > &rDY)
Public Attributes
unsigned _table_index_0
double _factor_0
Detailed Description
Definition at line 322 of file FaberRudy2000Version3Optimised.hpp.
Member Function Documentation
void FaberRudy2000Version3Optimised::EvaluateYDerivatives (double time, const std::vector< double > & rY, std::vector< double > & rDY) [virtual]
Method to evaluate the derivatives of the system.
Parameters:
time the current time
rY the current values of the state variables
rDY storage for the derivatives of the system; will be filled in on return
Implements AbstractOdeSystem.
Definition at line 363 of file FaberRudy2000Version3Optimised.cpp.
References AbstractOdeSystem::DumpState(), AbstractCardiacCell::GetStimulus(), and AbstractCardiacCell::mSetVoltageDerivativeToZero.
double FaberRudy2000Version3Optimised::GetIIonic () [virtual]
Computes the total current flowing through the cell membrane, using the current values of the state variables.
Implements AbstractCardiacCell.
Definition at line 271 of file FaberRudy2000Version3Optimised.cpp.
References AbstractOdeSystem::DumpState(), and AbstractOdeSystem::rGetStateVariables().
The documentation for this class was generated from the following files:
/tmp/release_2.0/heart/src/odes/ionicmodels/FaberRudy2000Version3Optimised.hpp
/tmp/release_2.0/heart/src/odes/ionicmodels/FaberRudy2000Version3Optimised.cpp