Chaste: AbstractTissue< DIM >::Iterator Class Reference
AbstractTissue< DIM >::Iterator Class Reference
#include <AbstractTissue.hpp>
Public Member Functions
TissueCell & operator* ()
TissueCell * operator-> ()
bool operator!= (const AbstractTissue< DIM >::Iterator &rOther)
Iterator & operator++ ()
Iterator (AbstractTissue &rTissue, std::list< TissueCell >::iterator cellIter)
virtual ~Iterator ()
Private Member Functions
virtual bool IsRealCell ()
bool IsAtEnd ()
Private Attributes
AbstractTissue & mrTissue
std::list< TissueCell >::iterator mCellIter
Detailed Description
template<unsigned DIM>
class AbstractTissue< DIM >::Iterator
Iterator class allows one to iterate over cells in the tissue. Dereferencing the iterator will give you the current cell. There are also methods to get the node representing this cell, and the location of that node.
Definition at line 467 of file AbstractTissue.hpp.
Constructor & Destructor Documentation
template<unsigned DIM> AbstractTissue< DIM >::Iterator::Iterator (AbstractTissue & rTissue, std::list< TissueCell >::iterator cellIter) [inline]
Constructor for a new iterator.
Parameters:
rTissue the tissue
cellIter iterator over list of cells
Definition at line 605 of file AbstractTissue.hpp.
References AbstractTissue< DIM >::Iterator::IsRealCell(), AbstractTissue< DIM >::Iterator::mCellIter, AbstractTissue< DIM >::Iterator::mrTissue, and AbstractTissue< DIM >::rGetCells().
template<unsigned DIM> virtual AbstractTissue< DIM >::Iterator::~Iterator () [inline, virtual]
The iterator must have a virtual destructor.
Definition at line 505 of file AbstractTissue.hpp.
Member Function Documentation
template<unsigned DIM> bool AbstractTissue< DIM >::Iterator::IsAtEnd () [inline, private]
Private helper function saying whether we're at the end of the cells.
Definition at line 599 of file AbstractTissue.hpp.
References AbstractTissue< DIM >::Iterator::mCellIter, AbstractTissue< DIM >::Iterator::mrTissue, and AbstractTissue< DIM >::rGetCells().
Referenced by AbstractTissue< DIM >::Iterator::operator*(), AbstractTissue< DIM >::Iterator::operator++(), and AbstractTissue< DIM >::Iterator::operator->().
template<unsigned DIM> bool AbstractTissue< DIM >::Iterator::IsRealCell () [inline, private, virtual]
Private helper function which tells us if we're pointing at a real cell. Assumes we are within range (i.e. not at End).
Real cells are not deleted.
Definition at line 593 of file AbstractTissue.hpp.
References AbstractTissue< DIM >::IsCellAssociatedWithADeletedLocation(), AbstractTissue< DIM >::Iterator::mCellIter, and AbstractTissue< DIM >::Iterator::mrTissue.
Referenced by AbstractTissue< DIM >::Iterator::Iterator(), and AbstractTissue< DIM >::Iterator::operator++().
template<unsigned DIM> bool AbstractTissue< DIM >::Iterator::operator!= (const AbstractTissue< DIM >::Iterator & rOther) [inline]
Comparison not-equal-to.
Parameters:
rOther iterator with which comparison is made
Definition at line 575 of file AbstractTissue.hpp.
References AbstractTissue< DIM >::Iterator::mCellIter.
template<unsigned DIM> TissueCell & AbstractTissue< DIM >::Iterator::operator* () [inline]
Dereference the iterator giving you a *reference* to the current cell. Make sure to use a reference for the result to avoid copying cells unnecessarily.
Definition at line 561 of file AbstractTissue.hpp.
References AbstractTissue< DIM >::Iterator::IsAtEnd(), and AbstractTissue< DIM >::Iterator::mCellIter.
template<unsigned DIM> AbstractTissue< DIM >::Iterator & AbstractTissue< DIM >::Iterator::operator++ () [inline]
Prefix increment operator.
Definition at line 581 of file AbstractTissue.hpp.
References AbstractTissue< DIM >::Iterator::IsAtEnd(), AbstractTissue< DIM >::Iterator::IsRealCell(), and AbstractTissue< DIM >::Iterator::mCellIter.
template<unsigned DIM> TissueCell * AbstractTissue< DIM >::Iterator::operator-> () [inline]
Member access from a pointer.
Definition at line 568 of file AbstractTissue.hpp.
References AbstractTissue< DIM >::Iterator::IsAtEnd().
Member Data Documentation
template<unsigned DIM> std::list<TissueCell>::iterator AbstractTissue< DIM >::Iterator::mCellIter [private]
Cell iterator member.
Definition at line 527 of file AbstractTissue.hpp.
Referenced by AbstractTissue< DIM >::Iterator::IsAtEnd(), AbstractTissue< DIM >::Iterator::IsRealCell(), AbstractTissue< DIM >::Iterator::Iterator(), AbstractTissue< DIM >::Iterator::operator!=(), AbstractTissue< DIM >::Iterator::operator*(), and AbstractTissue< DIM >::Iterator::operator++().
template<unsigned DIM> AbstractTissue& AbstractTissue< DIM >::Iterator::mrTissue [private]
The tissue member.
Definition at line 524 of file AbstractTissue.hpp.
Referenced by AbstractTissue< DIM >::Iterator::IsAtEnd(), AbstractTissue< DIM >::Iterator::IsRealCell(), and AbstractTissue< DIM >::Iterator::Iterator().
The documentation for this class was generated from the following file:
/tmp/release_2.0/cell_based/src/tissue/AbstractTissue.hpp