Chaste: Cellluo_rudy_1991FromCellMLOpt Class Reference
Cellluo_rudy_1991FromCellMLOpt Class Reference
Inherits AbstractCardiacCell.
Public Member Functions
double Get_membrane__I_stim ()
double Get_membrane__i_Na ()
double Get_membrane__i_si ()
double Get_membrane__i_K ()
double Get_membrane__i_K1 ()
double Get_membrane__i_Kp ()
double Get_membrane__i_b ()
Cellluo_rudy_1991FromCellMLOpt (boost::shared_ptr< AbstractIvpOdeSolver > pSolver, boost::shared_ptr< AbstractStimulusFunction > pIntracellularStimulus)
void VerifyStateVariables ()
double GetIIonic ()
void EvaluateYDerivatives (double var_environment__time, const std::vector< double > &rY, std::vector< double > &rDY)
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Private Attributes
double var_membrane__I_stim
double var_membrane__i_Na
double var_membrane__i_si
double var_membrane__i_K
double var_membrane__i_K1
double var_membrane__i_Kp
double var_membrane__i_b
Friends
class boost::serialization::access
Detailed Description
Definition at line 21 of file luo_rudy_1991Opt.hpp.
Member Function Documentation
void Cellluo_rudy_1991FromCellMLOpt::EvaluateYDerivatives (double time, const std::vector< double > & rY, std::vector< double > & rDY) [virtual]
Method to evaluate the derivatives of the system.
Parameters:
time the current time
rY the current values of the state variables
rDY storage for the derivatives of the system; will be filled in on return
Implements AbstractOdeSystem.
Definition at line 265 of file luo_rudy_1991Opt.cpp.
References AbstractOdeSystem::DumpState(), AbstractCardiacCell::GetStimulus(), and AbstractCardiacCell::mSetVoltageDerivativeToZero.
double Cellluo_rudy_1991FromCellMLOpt::GetIIonic () [virtual]
Computes the total current flowing through the cell membrane, using the current values of the state variables.
Implements AbstractCardiacCell.
Definition at line 219 of file luo_rudy_1991Opt.cpp.
References AbstractOdeSystem::DumpState(), and AbstractOdeSystem::rGetStateVariables().
template<class Archive > void Cellluo_rudy_1991FromCellMLOpt::serialize (Archive & archive, const unsigned int version) [inline, private]
Archive the member variables.
Parameters:
archive
version
Reimplemented from AbstractCardiacCell.
Definition at line 25 of file luo_rudy_1991Opt.hpp.
void Cellluo_rudy_1991FromCellMLOpt::VerifyStateVariables () [virtual]
Empty method which can be over-ridden in concrete cell class which should go through the current state vector and go range checking on the values (eg check that concentrations are positive and gating variables are between zero and one). This method is called in the ComputeExceptVoltage method.
Reimplemented from AbstractCardiacCell.
Definition at line 216 of file luo_rudy_1991Opt.cpp.
Friends And Related Function Documentation
friend class boost::serialization::access [friend]
Needed for serialization.
Reimplemented from AbstractCardiacCell.
Definition at line 23 of file luo_rudy_1991Opt.hpp.
The documentation for this class was generated from the following files:
/tmp/release_2.0/heart/src/odes/cellml/luo_rudy_1991Opt.hpp
/tmp/release_2.0/heart/src/odes/cellml/luo_rudy_1991Opt.cpp