Chaste: AbstractCellCentreBasedTissue< DIM > Class Template Reference
AbstractCellCentreBasedTissue< DIM > Class Template Reference
#include <AbstractCellCentreBasedTissue.hpp>
Inherits AbstractTissue< DIM >.
Inherited by MeshBasedTissue< DIM >, MeshBasedTissue< 1 >, MeshBasedTissue< 2 >, and NodeBasedTissue< DIM >.
Public Member Functions
AbstractCellCentreBasedTissue (std::vector< TissueCell > &rCells, const std::vector< unsigned > locationIndices=std::vector< unsigned >())
c_vector< double, DIM > GetLocationOfCellCentre (TissueCell &rCell)
Node< DIM > * GetNodeCorrespondingToCell (TissueCell &rCell)
TissueCell * AddCell (TissueCell &rNewCell, const c_vector< double, DIM > &rCellDivisionVector, TissueCell *pParentCell=NULL)
bool IsCellAssociatedWithADeletedLocation (TissueCell &rCell)
virtual void UpdateNodeLocations (const std::vector< c_vector< double, DIM > > &rNodeForces, double dt)
virtual double GetDampingConstant (unsigned nodeIndex)
void GenerateCellResults (unsigned locationIndex, std::vector< unsigned > &rCellProliferativeTypeCounter, std::vector< unsigned > &rCellCyclePhaseCounter)
virtual void GenerateCellResultsAndWriteToFiles ()
virtual bool IsGhostNode (unsigned index)
Protected Member Functions
AbstractCellCentreBasedTissue ()
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Friends
class boost::serialization::access
Detailed Description
template<unsigned DIM>
class AbstractCellCentreBasedTissue< DIM >
An abstract facade class encapsulating a cell-centre based tissue, in which each cell corresponds to a Node.
Definition at line 41 of file AbstractCellCentreBasedTissue.hpp.
Constructor & Destructor Documentation
template<unsigned DIM> AbstractCellCentreBasedTissue< DIM >::AbstractCellCentreBasedTissue () [inline, protected]
Constructor for use by archiving - doesn't take in cells, since these are dealt with by the serialize method.
Definition at line 40 of file AbstractCellCentreBasedTissue.cpp.
template<unsigned DIM> AbstractCellCentreBasedTissue< DIM >::AbstractCellCentreBasedTissue (std::vector< TissueCell > & rCells, const std::vector< unsigned > locationIndices = std::vector<unsigned>()) [inline]
Default constructor.
Parameters:
rCells a vector of cells
locationIndices an optional vector of location indices that correspond to real cells
Definition at line 32 of file AbstractCellCentreBasedTissue.cpp.
Member Function Documentation
template<unsigned DIM> TissueCell * AbstractCellCentreBasedTissue< DIM >::AddCell (TissueCell & rNewCell, const c_vector< double, DIM > & rCellDivisionVector, TissueCell * pParentCell = NULL) [inline, virtual]
Add a new cell to the tissue.
Parameters:
rNewCell the cell to add
rCellDivisionVector the position in space at which to put it
pParentCell pointer to a parent cell (if required)
Returns:
address of cell as it appears in the cell list
Implements AbstractTissue< DIM >.
Reimplemented in MeshBasedTissue< DIM >, MeshBasedTissueWithGhostNodes< DIM >, MeshBasedTissue< 1 >, MeshBasedTissue< 2 >, and MeshBasedTissueWithGhostNodes< 2 >.
Definition at line 61 of file AbstractCellCentreBasedTissue.cpp.
References AbstractTissue< DIM >::AddNode(), AbstractTissue< DIM >::GetNumNodes(), AbstractTissue< DIM >::mCellLocationMap, AbstractTissue< DIM >::mCells, and AbstractTissue< DIM >::mLocationCellMap.
template<unsigned DIM> void AbstractCellCentreBasedTissue< DIM >::GenerateCellResults (unsigned locationIndex, std::vector< unsigned > & rCellProliferativeTypeCounter, std::vector< unsigned > & rCellCyclePhaseCounter) [inline, virtual]
Overridden GenerateCellResults() method. Generate results for a given cell in the current tissue state to output files.
Parameters:
locationIndex location index of the cell
rCellProliferativeTypeCounter cell type counter
rCellCyclePhaseCounter cell cycle phase counter
Reimplemented from AbstractTissue< DIM >.
Definition at line 135 of file AbstractCellCentreBasedTissue.cpp.
References AbstractCellCentreBasedTissue< DIM >::IsGhostNode(), and AbstractTissue< DIM >::mpVizCellProliferativeTypesFile.
Referenced by AbstractCellCentreBasedTissue< DIM >::GenerateCellResultsAndWriteToFiles().
template<unsigned DIM> void AbstractCellCentreBasedTissue< DIM >::GenerateCellResultsAndWriteToFiles () [inline, virtual]
Overridden GenerateCellResultsAndWriteToFiles() method.
Implements AbstractTissue< DIM >.
Definition at line 153 of file AbstractCellCentreBasedTissue.cpp.
References AbstractCellCentreBasedTissue< DIM >::GenerateCellResults(), AbstractTissue< DIM >::GetNode(), AbstractTissue< DIM >::GetNumNodes(), AbstractTissue< DIM >::mCellCyclePhaseCount, AbstractTissue< DIM >::mCellProliferativeTypeCount, AbstractTissue< DIM >::mLocationCellMap, and AbstractTissue< DIM >::WriteCellResultsToFiles().
template<unsigned DIM> double AbstractCellCentreBasedTissue< DIM >::GetDampingConstant (unsigned nodeIndex) [inline, virtual]
Overridden GetDampingConstant() method.
Get the damping constant for the cell associated with this node, i.e. d in drdt = F/d.
If the cell is wild-type, then the normal damping constant is returned. If the cell has a mutation, then the mutant damping constant is returned.
Note that by default, the normal and mutant damping constants are the same. To alter the damping constant for mutant cells, call the method TissueConfig::SetDampingConstantMutant().
Parameters:
nodeIndex the global index of this node
Returns:
the damping constant at the TissueCell associated with this node
Implements AbstractTissue< DIM >.
Reimplemented in MeshBasedTissue< DIM >, MeshBasedTissue< 1 >, and MeshBasedTissue< 2 >.
Definition at line 113 of file AbstractCellCentreBasedTissue.cpp.
References TissueConfig::GetDampingConstantMutant(), TissueConfig::GetDampingConstantNormal(), TissueCell::GetMutationState(), TissueConfig::Instance(), and AbstractTissue< DIM >::rGetCellUsingLocationIndex().
Referenced by AbstractCellCentreBasedTissue< DIM >::UpdateNodeLocations().
template<unsigned DIM> c_vector< double, DIM > AbstractCellCentreBasedTissue< DIM >::GetLocationOfCellCentre (TissueCell & rCell) [inline, virtual]
Overridden GetLocationOfCellCentre() method. Find where a given cell is in space.
Parameters:
rCell the cell
Returns:
the location of the node corresponding to this cell.
Implements AbstractTissue< DIM >.
Definition at line 47 of file AbstractCellCentreBasedTissue.cpp.
References AbstractCellCentreBasedTissue< DIM >::GetNodeCorrespondingToCell().
Referenced by CryptSimulation2d::CalculateCellDivisionVector(), CryptSimulation1d::CalculateCellDivisionVector(), CryptStatistics::GetCryptSection(), CryptSimulation2d::SetBottomCellAncestors(), CryptSimulation2d::WriteBetaCatenin(), MeshBasedTissue< DIM >::WriteCellAreaResultsToFile(), and MeshBasedTissue< DIM >::WriteVoronoiResultsToFile().
template<unsigned DIM> Node< DIM > * AbstractCellCentreBasedTissue< DIM >::GetNodeCorrespondingToCell (TissueCell & rCell) [inline]
Get a pointer to the node corresponding to a given cell.
Parameters:
rCell the cell
Returns:
address of the node
Definition at line 54 of file AbstractCellCentreBasedTissue.cpp.
References AbstractTissue< DIM >::GetNode(), and AbstractTissue< DIM >::mCellLocationMap.
Referenced by CryptSimulation2d::ApplyTissueBoundaryConditions(), CryptSimulation1d::ApplyTissueBoundaryConditions(), AbstractCellCentreBasedTissue< DIM >::GetLocationOfCellCentre(), AbstractCellCentreBasedTissue< DIM >::IsCellAssociatedWithADeletedLocation(), NodeBasedTissue< DIM >::RemoveDeadCells(), and MeshBasedTissue< DIM >::Update().
template<unsigned DIM> bool AbstractCellCentreBasedTissue< DIM >::IsCellAssociatedWithADeletedLocation (TissueCell & rCell) [inline, virtual]
Overridden IsCellAssociatedWithADeletedLocation() method.
Parameters:
rCell the cell
Returns:
whether a given cell is associated with a deleted node.
Implements AbstractTissue< DIM >.
Definition at line 80 of file AbstractCellCentreBasedTissue.cpp.
References AbstractCellCentreBasedTissue< DIM >::GetNodeCorrespondingToCell().
template<unsigned DIM> bool AbstractCellCentreBasedTissue< DIM >::IsGhostNode (unsigned index) [inline, virtual]
Find if a given node is a ghost node. The method always returns false but is overridden in MeshBasedTissueWithGhostNodes.
Parameters:
index the global index of a specified node
Returns:
whether the node is a ghost node
Reimplemented in MeshBasedTissueWithGhostNodes< DIM >, and MeshBasedTissueWithGhostNodes< 2 >.
Definition at line 128 of file AbstractCellCentreBasedTissue.cpp.
Referenced by AbstractCellCentreBasedTissue< DIM >::GenerateCellResults().
template<unsigned DIM> template<class Archive > void AbstractCellCentreBasedTissue< DIM >::serialize (Archive & archive, const unsigned int version) [inline, private]
Serialize the object and its member variables.
Parameters:
archive the archive
version the current version of this class
Reimplemented from AbstractTissue< DIM >.
Reimplemented in MeshBasedTissue< DIM >, MeshBasedTissueWithGhostNodes< DIM >, NodeBasedTissue< DIM >, MeshBasedTissue< 1 >, MeshBasedTissue< 2 >, and MeshBasedTissueWithGhostNodes< 2 >.
Definition at line 53 of file AbstractCellCentreBasedTissue.hpp.
template<unsigned DIM> void AbstractCellCentreBasedTissue< DIM >::UpdateNodeLocations (const std::vector< c_vector< double, DIM > > & rNodeForces, double dt) [inline, virtual]
Overridden UpdateNodeLocations() method.
Parameters:
rNodeForces a vector containing the force on each node in the tissue
dt the time step
Implements AbstractTissue< DIM >.
Reimplemented in MeshBasedTissueWithGhostNodes< DIM >, and MeshBasedTissueWithGhostNodes< 2 >.
Definition at line 87 of file AbstractCellCentreBasedTissue.cpp.
References AbstractTissue< DIM >::Begin(), AbstractTissue< DIM >::End(), AbstractCellCentreBasedTissue< DIM >::GetDampingConstant(), AbstractTissue< DIM >::GetNode(), AbstractTissue< DIM >::mCellLocationMap, and AbstractTissue< DIM >::SetNode().
Friends And Related Function Documentation
template<unsigned DIM> friend class boost::serialization::access [friend]
Needed for serialization.
Reimplemented from AbstractTissue< DIM >.
Reimplemented in MeshBasedTissue< DIM >, MeshBasedTissueWithGhostNodes< DIM >, NodeBasedTissue< DIM >, MeshBasedTissue< 1 >, MeshBasedTissue< 2 >, and MeshBasedTissueWithGhostNodes< 2 >.
Definition at line 45 of file AbstractCellCentreBasedTissue.hpp.
The documentation for this class was generated from the following files:
/tmp/release_2.0/cell_based/src/tissue/AbstractCellCentreBasedTissue.hpp
/tmp/release_2.0/cell_based/src/tissue/AbstractCellCentreBasedTissue.cpp