Chaste: BidomainWithBathRhsMatrixAssembler< DIM > Class Template Reference
BidomainWithBathRhsMatrixAssembler< DIM > Class Template Reference
#include <BidomainWithBathMatrixBasedAssembler.hpp>
Inherits AbstractLinearAssembler< DIM, DIM, 2, false, BidomainWithBathRhsMatrixAssembler< DIM > >.
Public Member Functions
virtual c_matrix< double,
2 *(DIM+1), 2 *(DIM+1)> ComputeMatrixTerm (c_vector< double, DIM+1 > &rPhi, c_matrix< double, DIM, DIM+1 > &rGradPhi, ChastePoint< DIM > &rX, c_vector< double, 2 > &rU, c_matrix< double, 2, DIM > &rGradU, Element< DIM, DIM > *pElement)
virtual c_vector< double,
2 *(DIM+1)> ComputeVectorTerm (c_vector< double, DIM+1 > &rPhi, c_matrix< double, DIM, DIM+1 > &rGradPhi, ChastePoint< DIM > &rX, c_vector< double, 2 > &rU, c_matrix< double, 2, DIM > &rGradU, Element< DIM, DIM > *pElement)
virtual c_vector< double, 2 *DIM > ComputeVectorSurfaceTerm (const BoundaryElement< DIM-1, DIM > &rSurfaceElement, c_vector< double, DIM > &rPhi, ChastePoint< DIM > &rX)
BidomainWithBathRhsMatrixAssembler (AbstractTetrahedralMesh< DIM, DIM > *pMesh)
~BidomainWithBathRhsMatrixAssembler ()
Mat * GetMatrix ()
Static Public Attributes
static const unsigned E_DIM = DIM
static const unsigned S_DIM = DIM
static const unsigned P_DIM = 2u
Detailed Description
template<unsigned DIM>
class BidomainWithBathRhsMatrixAssembler< DIM >
BidomainWithBathRhsMatrixAssembler
This class only exists to construct a matrix, the matrix which is used to assemble the RHS in monodomain problems. Therefore, although it inherits from the assembler hierachy, it is not an assembler for any particular PDE problem, it is just used to assemble one matrix. Therefore only ConstructMatrixTerm is properly implemented.
The matrix that is constructed is in fact the mass matrix for a 2-unknown problem. ie ***IF*** the unknowns were ordered [V1 V2 .. V_N phi_e1 ... phi_eN ], the matrix would be [M 0] [0 0] where M_ij = integral over TISSUE elements phi_i phi_j dV, where phi_k is the k-th basis function
Todo:
#1063 make this class inherit from BidomainRhsMatrixAssembler
Definition at line 57 of file BidomainWithBathMatrixBasedAssembler.hpp.
Constructor & Destructor Documentation
template<unsigned DIM> BidomainWithBathRhsMatrixAssembler< DIM >::BidomainWithBathRhsMatrixAssembler (AbstractTetrahedralMesh< DIM, DIM > * pMesh) [inline]
Constructor takes in a mesh and calls AssembleSystem to construct the matrix.
Parameters:
pMesh Pointer to a mesh
Definition at line 100 of file BidomainWithBathMatrixBasedAssembler.cpp.
References AbstractStaticAssembler< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM, NON_HEART, BidomainWithBathRhsMatrixAssembler< DIM > >::AssembleSystem(), AbstractAssembler< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::mpBoundaryConditions, AbstractStaticAssembler< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM, NON_HEART, BidomainWithBathRhsMatrixAssembler< DIM > >::mpLinearSystem, and AbstractStaticAssembler< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM, NON_HEART, BidomainWithBathRhsMatrixAssembler< DIM > >::mpMesh.
template<unsigned DIM> BidomainWithBathRhsMatrixAssembler< DIM >::~BidomainWithBathRhsMatrixAssembler () [inline]
Destructor.
Definition at line 119 of file BidomainWithBathMatrixBasedAssembler.cpp.
References AbstractAssembler< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::mpBoundaryConditions.
Member Function Documentation
template<unsigned DIM> c_matrix< double, 2 *(DIM+1), 2 *(DIM+1)> BidomainWithBathRhsMatrixAssembler< DIM >::ComputeMatrixTerm (c_vector< double, DIM+1 > & rPhi, c_matrix< double, DIM, DIM+1 > & rGradPhi, ChastePoint< DIM > & rX, c_vector< double, 2 > & rU, c_matrix< double, 2, DIM > & rGradU, Element< DIM, DIM > * pElement) [inline, virtual]
Integrand in matrix definition integral (see class documentation).
Parameters:
rPhi The basis functions, rPhi(i) = phi_i, i=1..numBases
rGradPhi Basis gradients, rGradPhi(i,j) = d(phi_j)/d(X_i)
rX The point in space
rU The unknown as a vector, u(i) = u_i
rGradU The gradient of the unknown as a matrix, rGradU(i,j) = d(u_i)/d(X_j)
pElement Pointer to the element
Definition at line 42 of file BidomainWithBathMatrixBasedAssembler.cpp.
References HeartRegionCode::BATH, and AbstractElement< ELEMENT_DIM, SPACE_DIM >::GetRegion().
template<unsigned DIM> c_vector< double, 2 *DIM > BidomainWithBathRhsMatrixAssembler< DIM >::ComputeVectorSurfaceTerm (const BoundaryElement< DIM-1, DIM > & rSurfaceElement, c_vector< double, DIM > & rPhi, ChastePoint< DIM > & rX) [inline, virtual]
The term arising from boundary conditions to be added to the element stiffness vector - except this class is only used fpr constructing a matrix so this is never called.
Parameters:
rSurfaceElement the element which is being considered.
rPhi The basis functions, rPhi(i) = phi_i, i=1..numBases
rX The point in space
Definition at line 87 of file BidomainWithBathMatrixBasedAssembler.cpp.
template<unsigned DIM> c_vector< double, 2 *(DIM+1)> BidomainWithBathRhsMatrixAssembler< DIM >::ComputeVectorTerm (c_vector< double, DIM+1 > & rPhi, c_matrix< double, DIM, DIM+1 > & rGradPhi, ChastePoint< DIM > & rX, c_vector< double, 2 > & rU, c_matrix< double, 2, DIM > & rGradU, Element< DIM, DIM > * pElement) [inline, virtual]
The term to be added to the element stiffness vector - except this class is only used for constructing a matrix so this is never called.
Parameters:
rPhi The basis functions, rPhi(i) = phi_i, i=1..numBases
rGradPhi Basis gradients, rGradPhi(i,j) = d(phi_j)/d(X_i)
rX The point in space
rU The unknown as a vector, u(i) = u_i
rGradU The gradient of the unknown as a matrix, rGradU(i,j) = d(u_i)/d(X_j)
pElement Pointer to the element
Definition at line 70 of file BidomainWithBathMatrixBasedAssembler.cpp.
template<unsigned DIM> Mat * BidomainWithBathRhsMatrixAssembler< DIM >::GetMatrix () [inline]
Allow access to the matrix
Definition at line 125 of file BidomainWithBathMatrixBasedAssembler.cpp.
References AbstractStaticAssembler< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM, NON_HEART, BidomainWithBathRhsMatrixAssembler< DIM > >::mpLinearSystem, and LinearSystem::rGetLhsMatrix().
Referenced by BidomainWithBathMatrixBasedAssembler< ELEMENT_DIM, SPACE_DIM >::BidomainWithBathMatrixBasedAssembler().
Member Data Documentation
template<unsigned DIM> const unsigned BidomainWithBathRhsMatrixAssembler< DIM >::E_DIM = DIM [static]
The element dimension (to save typing).
Definition at line 63 of file BidomainWithBathMatrixBasedAssembler.hpp.
template<unsigned DIM> const unsigned BidomainWithBathRhsMatrixAssembler< DIM >::P_DIM = 2u [static]
The problem dimension (to save typing).
Definition at line 65 of file BidomainWithBathMatrixBasedAssembler.hpp.
template<unsigned DIM> const unsigned BidomainWithBathRhsMatrixAssembler< DIM >::S_DIM = DIM [static]
The space dimension (to save typing).
Definition at line 64 of file BidomainWithBathMatrixBasedAssembler.hpp.
The documentation for this class was generated from the following files:
/tmp/release_2.0/heart/src/solver/BidomainWithBathMatrixBasedAssembler.hpp
/tmp/release_2.0/heart/src/solver/BidomainWithBathMatrixBasedAssembler.cpp