Chaste: CML_luo_rudy_1991_pe_lut_be Class Reference
CML_luo_rudy_1991_pe_lut_be Class Reference
Inherits AbstractBackwardEulerCardiacCell< 1 >.
Public Member Functions
double Get_membrane__I_stim ()
double Get_membrane__i_Na ()
double Get_membrane__i_si ()
double Get_membrane__i_K ()
double Get_membrane__i_K1 ()
double Get_membrane__i_Kp ()
double Get_membrane__i_b ()
CML_luo_rudy_1991_pe_lut_be (boost::shared_ptr< AbstractIvpOdeSolver >, boost::shared_ptr< AbstractStimulusFunction > pIntracellularStimulus)
void VerifyStateVariables ()
double GetIIonic ()
void ComputeResidual (double var_environment__time, const double rCurrentGuess[1], double rResidual[1])
void ComputeJacobian (double var_environment__time, const double rCurrentGuess[1], double rJacobian[1][1])
Protected Member Functions
void UpdateTransmembranePotential (double var_environment__time)
void ComputeOneStepExceptVoltage (double var_environment__time)
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Private Attributes
double var_membrane__I_stim
double var_membrane__i_Na
double var_membrane__i_si
double var_membrane__i_K
double var_membrane__i_K1
double var_membrane__i_Kp
double var_membrane__i_b
unsigned _table_index_0
double _factor_0
double * _lt_0_row
Friends
class boost::serialization::access
Detailed Description
Definition at line 21 of file luo_rudy_1991BackwardEuler.hpp.
Member Function Documentation
void CML_luo_rudy_1991_pe_lut_be::ComputeOneStepExceptVoltage (double tStart) [protected, virtual]
Compute the values of all state variables, except the voltage, using backward Euler, for one timestep from tStart.
Note:
This method must be provided by subclasses.
Parameters:
tStart start of this timestep
Implements AbstractBackwardEulerCardiacCell< 1 >.
Definition at line 349 of file luo_rudy_1991BackwardEuler.cpp.
References AbstractOdeSystem::DumpState(), AbstractCardiacCell::mDt, AbstractOdeSystem::rGetStateVariables(), and CardiacNewtonSolver< SIZE >::Solve().
double CML_luo_rudy_1991_pe_lut_be::GetIIonic () [virtual]
Computes the total current flowing through the cell membrane, using the current values of the state variables.
Implements AbstractCardiacCell.
Definition at line 219 of file luo_rudy_1991BackwardEuler.cpp.
References AbstractOdeSystem::DumpState(), and AbstractOdeSystem::rGetStateVariables().
template<class Archive > void CML_luo_rudy_1991_pe_lut_be::serialize (Archive & archive, const unsigned int version) [inline, private]
Archive the member variables.
Parameters:
archive
version
Reimplemented from AbstractBackwardEulerCardiacCell< 1 >.
Definition at line 25 of file luo_rudy_1991BackwardEuler.hpp.
void CML_luo_rudy_1991_pe_lut_be::UpdateTransmembranePotential (double time) [protected, virtual]
Perform a forward Euler step to update the transmembrane potential.
Note:
This method must be provided by subclasses.
Parameters:
time start of this timestep
Implements AbstractBackwardEulerCardiacCell< 1 >.
Definition at line 299 of file luo_rudy_1991BackwardEuler.cpp.
References AbstractOdeSystem::DumpState(), AbstractCardiacCell::GetStimulus(), AbstractCardiacCell::mDt, and AbstractOdeSystem::rGetStateVariables().
void CML_luo_rudy_1991_pe_lut_be::VerifyStateVariables () [virtual]
Empty method which can be over-ridden in concrete cell class which should go through the current state vector and go range checking on the values (eg check that concentrations are positive and gating variables are between zero and one). This method is called in the ComputeExceptVoltage method.
Reimplemented from AbstractCardiacCell.
Definition at line 216 of file luo_rudy_1991BackwardEuler.cpp.
Friends And Related Function Documentation
friend class boost::serialization::access [friend]
Needed for serialization.
Reimplemented from AbstractBackwardEulerCardiacCell< 1 >.
Definition at line 23 of file luo_rudy_1991BackwardEuler.hpp.
The documentation for this class was generated from the following files:
/tmp/release_2.0/heart/src/odes/cellml/luo_rudy_1991BackwardEuler.hpp
/tmp/release_2.0/heart/src/odes/cellml/luo_rudy_1991BackwardEuler.cpp