Chaste: TissueSimulationArchiver< DIM, SIM > Class Template Reference
TissueSimulationArchiver< DIM, SIM > Class Template Reference
#include <TissueSimulationArchiver.hpp>
Static Public Member Functions
static SIM * Load (const std::string &rArchiveDirectory, const double &rTimeStamp)
static void Save (SIM *pSim)
Detailed Description
template<unsigned DIM, class SIM>
class TissueSimulationArchiver< DIM, SIM >
TissueSimulationArchiver handles the checkpointing (saving and loading) of all the various TissueSimulation objects. It has no explicit constructor (just uses a default one) and no member variables.
Definition at line 51 of file TissueSimulationArchiver.hpp.
Member Function Documentation
template<unsigned DIM, class SIM > SIM * TissueSimulationArchiver< DIM, SIM >::Load (const std::string & rArchiveDirectory, const double & rTimeStamp) [inline, static]
Loads a saved tissue simulation to run further.
Parameters:
rArchiveDirectory the name of the simulation to load (specified originally by simulation.SetOutputDirectory("wherever");)
rTimeStamp the time at which to load the simulation (this must be one of the times at which simulation.Save() was called)
Find the right archive (and mesh) to load. The files are contained within the 'archive' folder in rArchiveDirectory, with the archive itself called 'tissue_sim_at_time_`rTimeStamp`.arch'. The path to this file is returned.
The path to the mesh is stored in ArchiveLocationInfo for use by the Tissue de-serialization routines.
Definition at line 82 of file TissueSimulationArchiver.hpp.
References OutputFileHandler::GetChasteTestOutputDirectory(), ArchiveOpener< Archive, Stream >::GetCommonArchive(), SimulationTime::Instance(), SimulationTime::IsStartTimeSetUp(), and ArchiveLocationInfo::SetMeshPathname().
template<unsigned DIM, class SIM > void TissueSimulationArchiver< DIM, SIM >::Save (SIM * pSim) [inline, static]
Saves the whole tissue simulation for restarting later.
Puts it in the archive folder under the simulation's OutputDirectory, in the file "tissue_sim_at_time_<SIMULATION TIME>.arch". The mesh is written to files in the same folder.
First archives simulation time (and other singletons, if used) then the simulation itself.
Parameters:
pSim pointer to the simulation
Definition at line 134 of file TissueSimulationArchiver.hpp.
References SimulationTime::GetTime(), SimulationTime::Instance(), SimulationTime::IsStartTimeSetUp(), and ArchiveLocationInfo::SetMeshFilename().
The documentation for this class was generated from the following file:
/tmp/release_2.0/cell_based/src/simulation/TissueSimulationArchiver.hpp