Chaste: BackwardEulerNobleVargheseKohlNoble1998 Class Reference
BackwardEulerNobleVargheseKohlNoble1998 Class Reference
Inherits AbstractBackwardEulerCardiacCell< 12 >.
Public Member Functions
BackwardEulerNobleVargheseKohlNoble1998 (boost::shared_ptr< AbstractIvpOdeSolver >, boost::shared_ptr< AbstractStimulusFunction > pIntracellularStimulus)
BackwardEulerNobleVargheseKohlNoble1998 (boost::shared_ptr< AbstractStimulusFunction > pIntracellularStimulus)
void VerifyGatingVariables ()
void VerifyStateVariables ()
double GetIIonic ()
void ComputeResidual (double var_environment__time, const double rCurrentGuess[12], double rResidual[12])
void ComputeJacobian (double var_environment__time, const double rCurrentGuess[12], double rJacobian[12][12])
Protected Member Functions
void UpdateTransmembranePotential (double var_environment__time)
void ComputeOneStepExceptVoltage (double var_environment__time)
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
void MakeVars ()
Friends
class TestFastSlowBackwardEulerNoble98
class boost::serialization::access
Detailed Description
Definition at line 20 of file BackwardEulerNobleVargheseKohlNoble1998.hpp.
Member Function Documentation
void BackwardEulerNobleVargheseKohlNoble1998::ComputeOneStepExceptVoltage (double tStart) [protected, virtual]
Compute the values of all state variables, except the voltage, using backward Euler, for one timestep from tStart.
Note:
This method must be provided by subclasses.
Parameters:
tStart start of this timestep
Implements AbstractBackwardEulerCardiacCell< 12 >.
Definition at line 965 of file BackwardEulerNobleVargheseKohlNoble1998.cpp.
References AbstractCardiacCell::mDt, AbstractOdeSystem::rGetStateVariables(), and CardiacNewtonSolver< SIZE >::Solve().
double BackwardEulerNobleVargheseKohlNoble1998::GetIIonic () [virtual]
Computes the total current flowing through the cell membrane, using the current values of the state variables.
Todo:
we need to + Check this scaling + Ask JonC to amend PyCml if necessary + Check other cell models
The return value has to be scaled to match the units required by the mono/bidomain equations. The cell model ionic current is in nano Amps, we require micro Amps/cm^2. The cell density factor was calculated using the Cm=0.000095microF from the cell model and Cm=1.0microF/cm^2 from the mono/bidomain equations.
Implements AbstractCardiacCell.
Definition at line 103 of file BackwardEulerNobleVargheseKohlNoble1998.cpp.
References AbstractOdeSystem::rGetStateVariables().
template<class Archive > void BackwardEulerNobleVargheseKohlNoble1998::serialize (Archive & archive, const unsigned int version) [inline, private]
Archive the member variables.
Parameters:
archive
version
Reimplemented from AbstractBackwardEulerCardiacCell< 12 >.
Definition at line 34 of file BackwardEulerNobleVargheseKohlNoble1998.hpp.
void BackwardEulerNobleVargheseKohlNoble1998::UpdateTransmembranePotential (double time) [protected, virtual]
Perform a forward Euler step to update the transmembrane potential.
Note:
This method must be provided by subclasses.
Parameters:
time start of this timestep
Implements AbstractBackwardEulerCardiacCell< 12 >.
Definition at line 784 of file BackwardEulerNobleVargheseKohlNoble1998.cpp.
References AbstractCardiacCell::GetStimulus(), AbstractCardiacCell::mDt, and AbstractOdeSystem::rGetStateVariables().
void BackwardEulerNobleVargheseKohlNoble1998::VerifyStateVariables () [virtual]
Empty method which can be over-ridden in concrete cell class which should go through the current state vector and go range checking on the values (eg check that concentrations are positive and gating variables are between zero and one). This method is called in the ComputeExceptVoltage method.
Reimplemented from AbstractCardiacCell.
Definition at line 76 of file BackwardEulerNobleVargheseKohlNoble1998.cpp.
References AbstractOdeSystem::rGetStateVariables().
Friends And Related Function Documentation
friend class boost::serialization::access [friend]
Needed for serialization.
Reimplemented from AbstractBackwardEulerCardiacCell< 12 >.
Definition at line 26 of file BackwardEulerNobleVargheseKohlNoble1998.hpp.
The documentation for this class was generated from the following files:
/tmp/release_2.0/heart/src/odes/ionicmodels/BackwardEulerNobleVargheseKohlNoble1998.hpp
/tmp/release_2.0/heart/src/odes/ionicmodels/BackwardEulerNobleVargheseKohlNoble1998.cpp