Chaste: OrthotropicConductivityTensors< SPACE_DIM > Class Template Reference
OrthotropicConductivityTensors< SPACE_DIM > Class Template Reference
#include <OrthotropicConductivityTensors.hpp>
Inherits AbstractConductivityTensors< SPACE_DIM >.
Public Member Functions
void Init () throw (Exception)
Private Member Functions
void ReadOrientationMatrixFromFile (c_matrix< double, SPACE_DIM, SPACE_DIM > &orientMatrix)
Detailed Description
template<unsigned SPACE_DIM>
class OrthotropicConductivityTensors< SPACE_DIM >
This class provides an abstraction for the definition of constant/non-constant difussion tensors associated to the different elements of the mesh.
After instanciating the class any of SetFibreOrientationFile() or SetNonConstantConductivities() (or both) can be called to implement fiber orientation or heterogeneous conductivity into the tensors, respectively. If none of them is called a constant tensor (with constant conductivies) will be generated for all the elements of the mesh.
Init() should be called to actually create the tensors.
Initial values for conductivity from "Laminar Arrangement of Ventricular Myocytes Influences Electrical Behavior of the Heart", Hooks et al. 2007
Definition at line 53 of file OrthotropicConductivityTensors.hpp.
Member Function Documentation
template<unsigned SPACE_DIM> void OrthotropicConductivityTensors< SPACE_DIM >::Init () throw (Exception) [inline, virtual]
Computes the tensors based in all the info set
Implements AbstractConductivityTensors< SPACE_DIM >.
Definition at line 54 of file OrthotropicConductivityTensors.cpp.
References AbstractConductivityTensors< SPACE_DIM >::CloseFibreOrientationFile(), AbstractConductivityTensors< SPACE_DIM >::GetNumElementsFromFile(), AbstractConductivityTensors< SPACE_DIM >::mConstantConductivities, AbstractConductivityTensors< SPACE_DIM >::mInitialised, AbstractConductivityTensors< SPACE_DIM >::mNumElements, AbstractConductivityTensors< SPACE_DIM >::mpNonConstantConductivities, AbstractConductivityTensors< SPACE_DIM >::mTensors, AbstractConductivityTensors< SPACE_DIM >::mUseFibreOrientation, AbstractConductivityTensors< SPACE_DIM >::mUseNonConstantConductivities, AbstractConductivityTensors< SPACE_DIM >::OpenFibreOrientationFile(), and OrthotropicConductivityTensors< SPACE_DIM >::ReadOrientationMatrixFromFile().
template<unsigned SPACE_DIM> void OrthotropicConductivityTensors< SPACE_DIM >::ReadOrientationMatrixFromFile (c_matrix< double, SPACE_DIM, SPACE_DIM > & orientMatrix) [inline, private]
Reads a line from the Conductivity Tensor file (see base class) and interprets it as a SPACE_DIM*SPACE_DIM tensor
Parameters:
orientMatrix matrix into which to read the tensor
Definition at line 33 of file OrthotropicConductivityTensors.cpp.
References AbstractConductivityTensors< SPACE_DIM >::CloseFibreOrientationFile(), and AbstractConductivityTensors< SPACE_DIM >::GetTokensAtNextLine().
Referenced by OrthotropicConductivityTensors< SPACE_DIM >::Init().
The documentation for this class was generated from the following files:
/tmp/release_2.0/heart/src/problem/OrthotropicConductivityTensors.hpp
/tmp/release_2.0/heart/src/problem/OrthotropicConductivityTensors.cpp