Chaste: BackwardEulerFoxModel2002Modified Class Reference
BackwardEulerFoxModel2002Modified Class Reference
#include <BackwardEulerFoxModel2002Modified.hpp>
Inherits AbstractBackwardEulerCardiacCell< 3 >.
Public Member Functions
BackwardEulerFoxModel2002Modified (boost::shared_ptr< AbstractStimulusFunction > pIntracellularStimulus)
BackwardEulerFoxModel2002Modified (boost::shared_ptr< AbstractIvpOdeSolver >, boost::shared_ptr< AbstractStimulusFunction > pIntracellularStimulus)
double GetIIonic ()
void ComputeResidual (double var_environment__time, const double rCurrentGuess[3], double rResidual[3])
void ComputeJacobian (double var_environment__time, const double rCurrentGuess[3], double rJacobian[3][3])
Protected Member Functions
void UpdateTransmembranePotential (double var_environment__time)
void ComputeOneStepExceptVoltage (double var_environment__time)
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Friends
class boost::serialization::access
Detailed Description
Generated from CellML, and P_Ca parameter modified.
Definition at line 23 of file BackwardEulerFoxModel2002Modified.hpp.
Constructor & Destructor Documentation
BackwardEulerFoxModel2002Modified::BackwardEulerFoxModel2002Modified (boost::shared_ptr< AbstractIvpOdeSolver > , boost::shared_ptr< AbstractStimulusFunction > pIntracellularStimulus)
Alternative constructor with the same signature as forwards Euler models.
Definition at line 32 of file BackwardEulerFoxModel2002Modified.cpp.
References AbstractCardiacCell::Init(), and AbstractOdeSystem::mpSystemInfo.
Member Function Documentation
void BackwardEulerFoxModel2002Modified::ComputeOneStepExceptVoltage (double tStart) [protected, virtual]
Compute the values of all state variables, except the voltage, using backward Euler, for one timestep from tStart.
Note:
This method must be provided by subclasses.
Parameters:
tStart start of this timestep
Implements AbstractBackwardEulerCardiacCell< 3 >.
Definition at line 559 of file BackwardEulerFoxModel2002Modified.cpp.
References AbstractCardiacCell::mDt, AbstractOdeSystem::rGetStateVariables(), and CardiacNewtonSolver< SIZE >::Solve().
double BackwardEulerFoxModel2002Modified::GetIIonic () [virtual]
Computes the total current flowing through the cell membrane, using the current values of the state variables.
Implements AbstractCardiacCell.
Definition at line 42 of file BackwardEulerFoxModel2002Modified.cpp.
References AbstractOdeSystem::rGetStateVariables().
template<class Archive > void BackwardEulerFoxModel2002Modified::serialize (Archive & archive, const unsigned int version) [inline, private]
Archive the member variables.
Parameters:
archive
version
Reimplemented from AbstractBackwardEulerCardiacCell< 3 >.
Definition at line 35 of file BackwardEulerFoxModel2002Modified.hpp.
void BackwardEulerFoxModel2002Modified::UpdateTransmembranePotential (double time) [protected, virtual]
Perform a forward Euler step to update the transmembrane potential.
Note:
This method must be provided by subclasses.
Parameters:
time start of this timestep
Implements AbstractBackwardEulerCardiacCell< 3 >.
Definition at line 376 of file BackwardEulerFoxModel2002Modified.cpp.
References AbstractCardiacCell::GetStimulus(), AbstractCardiacCell::mDt, and AbstractOdeSystem::rGetStateVariables().
Friends And Related Function Documentation
friend class boost::serialization::access [friend]
Needed for serialization.
Reimplemented from AbstractBackwardEulerCardiacCell< 3 >.
Definition at line 27 of file BackwardEulerFoxModel2002Modified.hpp.
The documentation for this class was generated from the following files:
/tmp/release_2.0/heart/src/odes/ionicmodels/BackwardEulerFoxModel2002Modified.hpp
/tmp/release_2.0/heart/src/odes/ionicmodels/BackwardEulerFoxModel2002Modified.cpp