Chaste: BackwardEulerTenTusscher2006 Class Reference
BackwardEulerTenTusscher2006 Class Reference
Inherits AbstractBackwardEulerCardiacCell< 7 >.
Public Member Functions
double Get_membrane__i_Stim ()
double Get_membrane__i_K1 ()
double Get_membrane__i_to ()
double Get_membrane__i_Kr ()
double Get_membrane__i_Ks ()
double Get_membrane__i_CaL ()
double Get_membrane__i_NaK ()
double Get_membrane__i_Na ()
double Get_membrane__i_b_Na ()
double Get_membrane__i_NaCa ()
double Get_membrane__i_b_Ca ()
double Get_membrane__i_p_K ()
double Get_membrane__i_p_Ca ()
BackwardEulerTenTusscher2006 (boost::shared_ptr< AbstractIvpOdeSolver >, boost::shared_ptr< AbstractStimulusFunction > pIntracellularStimulus)
void VerifyStateVariables ()
double GetIIonic ()
void ComputeResidual (double var_environment__time, const double rCurrentGuess[7], double rResidual[7])
void ComputeJacobian (double var_environment__time, const double rCurrentGuess[7], double rJacobian[7][7])
Protected Member Functions
void UpdateTransmembranePotential (double var_environment__time)
void ComputeOneStepExceptVoltage (double var_environment__time)
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Private Attributes
double var_membrane__i_Stim
double var_membrane__i_K1
double var_membrane__i_to
double var_membrane__i_Kr
double var_membrane__i_Ks
double var_membrane__i_CaL
double var_membrane__i_NaK
double var_membrane__i_Na
double var_membrane__i_b_Na
double var_membrane__i_NaCa
double var_membrane__i_b_Ca
double var_membrane__i_p_K
double var_membrane__i_p_Ca
unsigned _table_index_0
double _factor_0
double * _lt_0_row
Friends
class boost::serialization::access
Detailed Description
Definition at line 26 of file BackwardEulerTenTusscher2006.hpp.
Member Function Documentation
void BackwardEulerTenTusscher2006::ComputeOneStepExceptVoltage (double tStart) [protected, virtual]
Compute the values of all state variables, except the voltage, using backward Euler, for one timestep from tStart.
Note:
This method must be provided by subclasses.
Parameters:
tStart start of this timestep
Implements AbstractBackwardEulerCardiacCell< 7 >.
Definition at line 681 of file BackwardEulerTenTusscher2006.cpp.
References AbstractOdeSystem::DumpState(), AbstractCardiacCell::mDt, AbstractOdeSystem::rGetStateVariables(), and CardiacNewtonSolver< SIZE >::Solve().
double BackwardEulerTenTusscher2006::GetIIonic () [virtual]
Computes the total current flowing through the cell membrane, using the current values of the state variables.
Implements AbstractCardiacCell.
Definition at line 327 of file BackwardEulerTenTusscher2006.cpp.
References AbstractOdeSystem::DumpState(), and AbstractOdeSystem::rGetStateVariables().
template<class Archive > void BackwardEulerTenTusscher2006::serialize (Archive & archive, const unsigned int version) [inline, private]
Archive the member variables.
Parameters:
archive
version
Reimplemented from AbstractBackwardEulerCardiacCell< 7 >.
Definition at line 30 of file BackwardEulerTenTusscher2006.hpp.
void BackwardEulerTenTusscher2006::UpdateTransmembranePotential (double time) [protected, virtual]
Perform a forward Euler step to update the transmembrane potential.
Note:
This method must be provided by subclasses.
Parameters:
time start of this timestep
Implements AbstractBackwardEulerCardiacCell< 7 >.
Definition at line 592 of file BackwardEulerTenTusscher2006.cpp.
References AbstractOdeSystem::DumpState(), AbstractCardiacCell::GetStimulus(), AbstractCardiacCell::mDt, and AbstractOdeSystem::rGetStateVariables().
void BackwardEulerTenTusscher2006::VerifyStateVariables () [virtual]
Empty method which can be over-ridden in concrete cell class which should go through the current state vector and go range checking on the values (eg check that concentrations are positive and gating variables are between zero and one). This method is called in the ComputeExceptVoltage method.
Reimplemented from AbstractCardiacCell.
Definition at line 324 of file BackwardEulerTenTusscher2006.cpp.
Friends And Related Function Documentation
friend class boost::serialization::access [friend]
Needed for serialization.
Reimplemented from AbstractBackwardEulerCardiacCell< 7 >.
Definition at line 28 of file BackwardEulerTenTusscher2006.hpp.
The documentation for this class was generated from the following files:
/tmp/release_2.0/heart/src/odes/ionicmodels/BackwardEulerTenTusscher2006.hpp
/tmp/release_2.0/heart/src/odes/ionicmodels/BackwardEulerTenTusscher2006.cpp