Chaste: CuboidMeshConstructor< ELEMENT_DIM, SPACE_DIM > Class Template Reference
CuboidMeshConstructor< ELEMENT_DIM, SPACE_DIM > Class Template Reference
#include <CuboidMeshConstructor.hpp>
Public Member Functions
void Construct (AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM > &rMesh, unsigned meshRefinementNum, double meshWidth)
double GetWidth ()
unsigned GetNumElements ()
unsigned GetNumNodes ()
Private Member Functions
void ConstructHyperCube (AbstractTetrahedralMesh< 1, SPACE_DIM > &rMesh, unsigned width)
void ConstructHyperCube (AbstractTetrahedralMesh< 2, 2 > &rMesh, unsigned width)
void ConstructHyperCube (AbstractTetrahedralMesh< 3, 3 > &rMesh, unsigned width)
Private Attributes
double mMeshWidth
unsigned mNumElements
unsigned mNumNodes
Detailed Description
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM = ELEMENT_DIM>
class CuboidMeshConstructor< ELEMENT_DIM, SPACE_DIM >
Helper class for constructing cuboidal meshes.
Definition at line 43 of file CuboidMeshConstructor.hpp.
Member Function Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void CuboidMeshConstructor< ELEMENT_DIM, SPACE_DIM >::Construct (AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM > & rMesh, unsigned meshRefinementNum, double meshWidth) [inline]
Construct the mesh.
Parameters:
rMesh Input a blank mesh in which to construct the result
meshRefinementNum Index for the mesh starting at 0 (4 elements in each space dimension)
meshWidth Width of the mesh (in cm)
(used to return a path to the mesh stored on the disk)
Definition at line 58 of file CuboidMeshConstructor.cpp.
References CuboidMeshConstructor< ELEMENT_DIM, SPACE_DIM >::ConstructHyperCube(), AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::GetNumElements(), AbstractMesh< ELEMENT_DIM, SPACE_DIM >::GetNumNodes(), CuboidMeshConstructor< ELEMENT_DIM, SPACE_DIM >::mMeshWidth, CuboidMeshConstructor< ELEMENT_DIM, SPACE_DIM >::mNumElements, CuboidMeshConstructor< ELEMENT_DIM, SPACE_DIM >::mNumNodes, and AbstractMesh< ELEMENT_DIM, SPACE_DIM >::Scale().
Referenced by AbstractConvergenceTester< CELL, CARDIAC_PROBLEM, DIM, PROBLEM_DIM >::Converge().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void CuboidMeshConstructor< ELEMENT_DIM, SPACE_DIM >::ConstructHyperCube (AbstractTetrahedralMesh< 3, 3 > & rMesh, unsigned width) [inline, private]
Construct a three-dimensional cuboidal mesh.
Parameters:
rMesh The mesh
width Width of the mesh in terms of number of elements in each space dimension
Definition at line 52 of file CuboidMeshConstructor.cpp.
References AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructCuboid().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void CuboidMeshConstructor< ELEMENT_DIM, SPACE_DIM >::ConstructHyperCube (AbstractTetrahedralMesh< 2, 2 > & rMesh, unsigned width) [inline, private]
Construct a two-dimensional rectangular mesh.
Parameters:
rMesh The mesh
width Width of the mesh in terms of number of elements in each space dimension
Definition at line 46 of file CuboidMeshConstructor.cpp.
References AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructRectangularMesh().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void CuboidMeshConstructor< ELEMENT_DIM, SPACE_DIM >::ConstructHyperCube (AbstractTetrahedralMesh< 1, SPACE_DIM > & rMesh, unsigned width) [inline, private]
Construct a one-dimensional linear mesh.
Parameters:
rMesh The mesh
width Width of the mesh in terms of number of elements in each space dimension
Definition at line 40 of file CuboidMeshConstructor.cpp.
References AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructLinearMesh().
Referenced by CuboidMeshConstructor< ELEMENT_DIM, SPACE_DIM >::Construct().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> unsigned CuboidMeshConstructor< ELEMENT_DIM, SPACE_DIM >::GetNumElements () [inline]
Get the number of elements in the mesh.
Definition at line 82 of file CuboidMeshConstructor.cpp.
References CuboidMeshConstructor< ELEMENT_DIM, SPACE_DIM >::mNumElements.
Referenced by AbstractConvergenceTester< CELL, CARDIAC_PROBLEM, DIM, PROBLEM_DIM >::Converge().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> unsigned CuboidMeshConstructor< ELEMENT_DIM, SPACE_DIM >::GetNumNodes () [inline]
Get the number of nodes in the mesh.
Definition at line 88 of file CuboidMeshConstructor.cpp.
References CuboidMeshConstructor< ELEMENT_DIM, SPACE_DIM >::mNumNodes.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> double CuboidMeshConstructor< ELEMENT_DIM, SPACE_DIM >::GetWidth () [inline]
Get the width of the mesh.
Definition at line 76 of file CuboidMeshConstructor.cpp.
References CuboidMeshConstructor< ELEMENT_DIM, SPACE_DIM >::mMeshWidth.
Referenced by AbstractConvergenceTester< CELL, CARDIAC_PROBLEM, DIM, PROBLEM_DIM >::Converge().
Member Data Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM = ELEMENT_DIM> double CuboidMeshConstructor< ELEMENT_DIM, SPACE_DIM >::mMeshWidth [private]
Width of the mesh.
Definition at line 71 of file CuboidMeshConstructor.hpp.
Referenced by CuboidMeshConstructor< ELEMENT_DIM, SPACE_DIM >::Construct(), and CuboidMeshConstructor< ELEMENT_DIM, SPACE_DIM >::GetWidth().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM = ELEMENT_DIM> unsigned CuboidMeshConstructor< ELEMENT_DIM, SPACE_DIM >::mNumElements [private]
Number of elements in the mesh.
Definition at line 72 of file CuboidMeshConstructor.hpp.
Referenced by CuboidMeshConstructor< ELEMENT_DIM, SPACE_DIM >::Construct(), and CuboidMeshConstructor< ELEMENT_DIM, SPACE_DIM >::GetNumElements().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM = ELEMENT_DIM> unsigned CuboidMeshConstructor< ELEMENT_DIM, SPACE_DIM >::mNumNodes [private]
Number of nodes in the mesh.
Definition at line 73 of file CuboidMeshConstructor.hpp.
Referenced by CuboidMeshConstructor< ELEMENT_DIM, SPACE_DIM >::Construct(), and CuboidMeshConstructor< ELEMENT_DIM, SPACE_DIM >::GetNumNodes().
The documentation for this class was generated from the following files:
/tmp/release_2.0/mesh/src/utilities/CuboidMeshConstructor.hpp
/tmp/release_2.0/mesh/src/utilities/CuboidMeshConstructor.cpp