Chaste: CML_noble_varghese_kohl_noble_1998_basic_pe_lut Class Reference
CML_noble_varghese_kohl_noble_1998_basic_pe_lut Class Reference
Inherits AbstractCardiacCell.
Public Member Functions
double Get_membrane__i_K1 ()
double Get_membrane__i_to ()
double Get_membrane__i_Kr ()
double Get_membrane__i_Ks ()
double Get_membrane__i_Ca_L_K_cyt ()
double Get_membrane__i_Ca_L_K_ds ()
double Get_membrane__i_NaK ()
double Get_membrane__i_Na ()
double Get_membrane__i_b_Na ()
double Get_membrane__i_p_Na ()
double Get_membrane__i_Ca_L_Na_cyt ()
double Get_membrane__i_Ca_L_Na_ds ()
double Get_membrane__i_NaCa_cyt ()
double Get_membrane__i_NaCa_ds ()
double Get_membrane__i_Ca_L_Ca_cyt ()
double Get_membrane__i_Ca_L_Ca_ds ()
double Get_membrane__i_b_Ca ()
double Get_membrane__i_Stim ()
CML_noble_varghese_kohl_noble_1998_basic_pe_lut (boost::shared_ptr< AbstractIvpOdeSolver > pSolver, boost::shared_ptr< AbstractStimulusFunction > pIntracellularStimulus)
double GetIIonic ()
void EvaluateYDerivatives (double var_environment__time, const std::vector< double > &rY, std::vector< double > &rDY)
Public Attributes
unsigned _table_index_0
double _factor_0
Private Attributes
double var_membrane__i_K1
double var_membrane__i_to
double var_membrane__i_Kr
double var_membrane__i_Ks
double var_membrane__i_Ca_L_K_cyt
double var_membrane__i_Ca_L_K_ds
double var_membrane__i_NaK
double var_membrane__i_Na
double var_membrane__i_b_Na
double var_membrane__i_p_Na
double var_membrane__i_Ca_L_Na_cyt
double var_membrane__i_Ca_L_Na_ds
double var_membrane__i_NaCa_cyt
double var_membrane__i_NaCa_ds
double var_membrane__i_Ca_L_Ca_cyt
double var_membrane__i_Ca_L_Ca_ds
double var_membrane__i_b_Ca
double var_membrane__i_Stim
Detailed Description
Definition at line 471 of file NobleVargheseKohlNoble1998Optimised.hpp.
Member Function Documentation
void CML_noble_varghese_kohl_noble_1998_basic_pe_lut::EvaluateYDerivatives (double time, const std::vector< double > & rY, std::vector< double > & rDY) [inline, virtual]
Method to evaluate the derivatives of the system.
Parameters:
time the current time
rY the current values of the state variables
rDY storage for the derivatives of the system; will be filled in on return
Implements AbstractOdeSystem.
Definition at line 702 of file NobleVargheseKohlNoble1998Optimised.hpp.
References AbstractOdeSystem::DumpState(), AbstractCardiacCell::GetStimulus(), and AbstractCardiacCell::mSetVoltageDerivativeToZero.
double CML_noble_varghese_kohl_noble_1998_basic_pe_lut::GetIIonic () [inline, virtual]
Computes the total current flowing through the cell membrane, using the current values of the state variables.
Todo:
we need to + Check this scaling + Ask JonC to amend PyCml if necessary + Check other cell models
The return value has to be scaled to match the units required by the mono/bidomain equations. The cell model ionic current is in nano Amps, we require micro Amps/cm^2. The cell density factor was calculated using the Cm=0.000095microF from the cell model and Cm=1.0microF/cm^2 from the mono/bidomain equations.
Implements AbstractCardiacCell.
Definition at line 603 of file NobleVargheseKohlNoble1998Optimised.hpp.
References AbstractOdeSystem::DumpState(), and AbstractOdeSystem::rGetStateVariables().
The documentation for this class was generated from the following file:
/tmp/release_2.0/heart/src/odes/ionicmodels/NobleVargheseKohlNoble1998Optimised.hpp