Chaste: AbstractOdeSystem Class Reference
AbstractOdeSystem Class Reference
#include <AbstractOdeSystem.hpp>
Inherited by AbstractCardiacCell, AbstractOdeBasedContractionModel, AbstractOdeSystemWithAnalyticJacobian, CombinedOdeSystem, Mirams2010WntOdeSystem, VanLeeuwen2009WntSwatCellCycleOdeSystem, and WntCellCycleOdeSystem.
Public Member Functions
AbstractOdeSystem (unsigned numberOfStateVariables=0)
virtual ~AbstractOdeSystem ()
virtual void EvaluateYDerivatives (double time, const std::vector< double > &rY, std::vector< double > &rDY)=0
unsigned GetNumberOfStateVariables () const
unsigned GetNumberOfParameters () const
double GetParameter (unsigned index) const
void SetParameter (unsigned index, double value)
const std::vector< std::string > & rGetParameterNames () const
const std::vector< std::string > & rGetParameterUnits () const
void SetInitialConditions (const std::vector< double > &rInitialConditions)
void SetInitialConditionsComponent (unsigned index, double initialCondition)
std::vector< double > GetInitialConditions () const
void SetStateVariables (const std::vector< double > &rStateVariables)
void SetStateVariable (unsigned stateVariable, double newValue)
std::vector< double > & rGetStateVariables ()
const std::vector< std::string > & rGetVariableNames () const
const std::vector< std::string > & rGetVariableUnits () const
virtual bool CalculateStoppingEvent (double time, const std::vector< double > &rY)
virtual double CalculateRootFunction (double time, const std::vector< double > &rY)
bool GetUseAnalyticJacobian ()
unsigned GetStateVariableNumberByName (const std::string name) const
double GetStateVariableValueByNumber (unsigned varNumber) const
std::string GetStateVariableUnitsByNumber (unsigned varNumber) const
boost::shared_ptr< const
AbstractOdeSystemInformation > GetSystemInformation () const
Protected Member Functions
std::string DumpState (const std::string &rMessage, std::vector< double > Y=std::vector< double >())
Protected Attributes
unsigned mNumberOfStateVariables
std::vector< double > mStateVariables
std::vector< double > mParameters
boost::shared_ptr
< AbstractOdeSystemInformation > mpSystemInfo
bool mUseAnalyticJacobian
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Friends
class TestAbstractOdeSystem
class boost::serialization::access
Detailed Description
Abstract OdeSystem class.
Sets up variables and functions for a general ODE system.
ODE systems are specified primarily by the EvaluateYDerivatives method, which calculates the right-hand side of the system.
Instances can store their state internally in the mStateVariables vector (see GetNumberOfStateVariables, SetStateVariables and rGetStateVariables), although this is not essential - the vector may be empty, although in this case AbstractIvpOdeSolver::SolveAndUpdateStateVariable may not be used to solve the system.
ODE systems may also have a vector of parameters, which can be accessed through the GetParameter and SetParameter methods.
Information about what the parameters and state variables represent is provided by a subclass of AbstractOdeSystemInformation. Various wrapper methods (e.g. rGetVariableNames) are provided in this class to access this information.
There are two more advanced facilities available for subclass authors. An analytic form for the Jacobian matrix of the system may be provided, in which case you must subclass AbstractOdeSystemWithAnalyticJacobian. The GetUseAnalyticJacobian method will test whether this is the case.
Also, subclasses may define a condition at which ODE solvers should stop prematurely. For the Chaste solvers this is done by overriding CalculateStoppingEvent; if the more advanced CVODE solvers are being used then implement CalculateRootFunction instead to detect the stopping time more accurately.
Definition at line 77 of file AbstractOdeSystem.hpp.
Constructor & Destructor Documentation
AbstractOdeSystem::AbstractOdeSystem (unsigned numberOfStateVariables = 0)
Constructor.
Parameters:
numberOfStateVariables the number of state variables in the ODE system (defaults to 0)
Definition at line 33 of file AbstractOdeSystem.cpp.
AbstractOdeSystem::~AbstractOdeSystem () [virtual]
Virtual destructor since we have virtual methods.
Definition at line 39 of file AbstractOdeSystem.cpp.
Member Function Documentation
double AbstractOdeSystem::CalculateRootFunction (double time, const std::vector< double > & rY) [virtual]
An alternative approach to stopping events; currently only useful with CVODE. CVODE can search for roots (zeros) of this function while solving the ODE system, and home in on them to find sign transitions to high precision.
The default implementation here fakes a root function using CalculateStoppingEvent.
Parameters:
time the current time
rY the current values of the state variables
Reimplemented in VanLeeuwen2009WntSwatCellCycleOdeSystem, WntCellCycleOdeSystem, and TysonNovak2001OdeSystem.
Definition at line 167 of file AbstractOdeSystem.cpp.
References CalculateStoppingEvent().
bool AbstractOdeSystem::CalculateStoppingEvent (double time, const std::vector< double > & rY) [virtual]
CalculateStoppingEvent() - can be overloaded if the ODE is to be solved only until a particular event (for example, only until the y value becomes negative.
After each timestep the solver will call this method on the ODE to see if it should stop there. By default, false is returned here.
Parameters:
time the current time
rY the current values of the state variables
Reimplemented in VanLeeuwen2009WntSwatCellCycleOdeSystem, WntCellCycleOdeSystem, and TysonNovak2001OdeSystem.
Definition at line 42 of file AbstractOdeSystem.cpp.
Referenced by CalculateRootFunction(), RungeKuttaFehlbergIvpOdeSolver::InternalSolve(), AbstractOneStepIvpOdeSolver::InternalSolve(), RungeKuttaFehlbergIvpOdeSolver::Solve(), and AbstractOneStepIvpOdeSolver::Solve().
std::string AbstractOdeSystem::DumpState (const std::string & rMessage, std::vector< double > Y = std::vector<double>()) [protected]
Used to include extra debugging information in exception messages. For example, EXCEPTION(DumpState("Gating variable out of range"));
Parameters:
rMessage the exception message
Y the values of the state variables (optional input argument)
Definition at line 47 of file AbstractOdeSystem.cpp.
References rGetStateVariables(), and rGetVariableNames().
Referenced by BackwardEulerTenTusscher2006::ComputeOneStepExceptVoltage(), CML_luo_rudy_1991_pe_lut_be::ComputeOneStepExceptVoltage(), CML_noble_varghese_kohl_noble_1998_basic_pe_lut::EvaluateYDerivatives(), FoxModel2002Modified::EvaluateYDerivatives(), FaberRudy2000Version3Optimised::EvaluateYDerivatives(), Cellluo_rudy_1991FromCellMLOpt::EvaluateYDerivatives(), CML_noble_varghese_kohl_noble_1998_basic_pe_lut::GetIIonic(), FaberRudy2000Version3Optimised::GetIIonic(), BackwardEulerTenTusscher2006::GetIIonic(), Cellluo_rudy_1991FromCellMLOpt::GetIIonic(), CML_luo_rudy_1991_pe_lut_be::GetIIonic(), BackwardEulerTenTusscher2006::UpdateTransmembranePotential(), CML_luo_rudy_1991_pe_lut_be::UpdateTransmembranePotential(), TenTusscher2006OdeSystem::VerifyStateVariables(), LuoRudyIModel1991OdeSystem::VerifyStateVariables(), and DiFrancescoNoble1985OdeSystem::VerifyStateVariables().
virtual void AbstractOdeSystem::EvaluateYDerivatives (double time, const std::vector< double > & rY, std::vector< double > & rDY) [pure virtual]
Method to evaluate the derivatives of the system.
Parameters:
time the current time
rY the current values of the state variables
rDY storage for the derivatives of the system; will be filled in on return
Implemented in AbstractBackwardEulerCardiacCell< SIZE >, Cellluo_rudy_1991FromCellML, Cellluo_rudy_1991FromCellMLOpt, FakeBathCell, DiFrancescoNoble1985OdeSystem, FaberRudy2000Version3, FaberRudy2000Version3Optimised, FitzHughNagumo1961OdeSystem, FoxModel2002Modified, HodgkinHuxleySquidAxon1952OriginalOdeSystem, LuoRudyIModel1991OdeSystem, Mahajan2008OdeSystem, Maleckar2009OdeSystem, CML_noble_varghese_kohl_noble_1998_basic, CML_noble_varghese_kohl_noble_1998_basic_pe_lut, CellShannon2004FromCellML, TenTusscher2006OdeSystem, Kerchoffs2003ContractionModel, Nash2004ContractionModel, NhsContractionModel, CombinedOdeSystem, Mirams2010WntOdeSystem, VanLeeuwen2009WntSwatCellCycleOdeSystem, WntCellCycleOdeSystem, TysonNovak2001OdeSystem, AbstractBackwardEulerCardiacCell< 12 >, AbstractBackwardEulerCardiacCell< 1 >, AbstractBackwardEulerCardiacCell< 15 >, AbstractBackwardEulerCardiacCell< 3 >, and AbstractBackwardEulerCardiacCell< 7 >.
Referenced by RungeKuttaFehlbergIvpOdeSolver::CalculateNextYValue(), RungeKutta4IvpOdeSolver::CalculateNextYValue(), RungeKutta2IvpOdeSolver::CalculateNextYValue(), HeunIvpOdeSolver::CalculateNextYValue(), EulerIvpOdeSolver::CalculateNextYValue(), and BackwardEulerIvpOdeSolver::ComputeResidual().
std::vector< double > AbstractOdeSystem::GetInitialConditions () const
Get the initial conditions for the ODE system.
Definition at line 119 of file AbstractOdeSystem.cpp.
References mpSystemInfo.
Referenced by CombinedOdeSystem::CombinedOdeSystem(), AbstractCardiacCell::Init(), WntCellCycleModel::Initialise(), SingleOdeWntCellCycleModel::Initialise(), AbstractVanLeeuwen2009WntSwatCellCycleModel::Initialise(), NhsContractionModel::NhsContractionModel(), TysonNovakCellCycleModel::ResetForDivision(), AbstractWntOdeBasedCellCycleModel::ResetForDivision(), and TysonNovakCellCycleModel::TysonNovakCellCycleModel().
unsigned AbstractOdeSystem::GetNumberOfParameters () const
Get the number of parameters.
Definition at line 71 of file AbstractOdeSystem.cpp.
References mParameters.
unsigned AbstractOdeSystem::GetNumberOfStateVariables () const
Get the number of state variables in the ODE system.
Returns:
mNumberOfStateVariables
Definition at line 65 of file AbstractOdeSystem.cpp.
References mNumberOfStateVariables.
Referenced by RungeKuttaFehlbergIvpOdeSolver::CalculateNextYValue(), RungeKutta4IvpOdeSolver::CalculateNextYValue(), RungeKutta2IvpOdeSolver::CalculateNextYValue(), HeunIvpOdeSolver::CalculateNextYValue(), EulerIvpOdeSolver::CalculateNextYValue(), BackwardEulerIvpOdeSolver::CalculateNextYValue(), RungeKuttaFehlbergIvpOdeSolver::InternalSolve(), RungeKuttaFehlbergIvpOdeSolver::Solve(), AbstractOneStepIvpOdeSolver::Solve(), AbstractIvpOdeSolver::SolveAndUpdateStateVariable(), and AbstractOdeBasedCellCycleModel::UpdateCellCyclePhase().
double AbstractOdeSystem::GetParameter (unsigned index) const
Get the value of a given parameter.
Parameters:
index the index of the parameter
Definition at line 76 of file AbstractOdeSystem.cpp.
References mParameters.
unsigned AbstractOdeSystem::GetStateVariableNumberByName (const std::string name) const
This method is used to establish a state variable's position within the vector of state variables of an ODE system. This number can then be used with the methods GetStateVariableValueByNumber and GetStateVariableUnitsByNumber.
Parameters:
name the name of a state variable.
Returns:
the state variable's position within the vector of state variables associated with the ODE system.
Definition at line 178 of file AbstractOdeSystem.cpp.
References mpSystemInfo.
std::string AbstractOdeSystem::GetStateVariableUnitsByNumber (unsigned varNumber) const
Get the units of a state variable given its index in the ODE system.
Parameters:
varNumber a state variable's position within the vector of state variables associated with the ODE system.
Returns:
the units of the state variable.
Definition at line 190 of file AbstractOdeSystem.cpp.
References mNumberOfStateVariables, and mpSystemInfo.
double AbstractOdeSystem::GetStateVariableValueByNumber (unsigned varNumber) const
Get the value of a state variable given its index in the ODE system.
Parameters:
varNumber a state variable's position within the vector of state variables associated with the ODE system.
Returns:
the current value of the state variable.
Definition at line 184 of file AbstractOdeSystem.cpp.
References mNumberOfStateVariables, and mStateVariables.
boost::shared_ptr< const AbstractOdeSystemInformation > AbstractOdeSystem::GetSystemInformation () const
Get the object which provides information about this ODE system.
Definition at line 161 of file AbstractOdeSystem.cpp.
References mpSystemInfo.
Referenced by AbstractOneStepIvpOdeSolver::Solve().
bool AbstractOdeSystem::GetUseAnalyticJacobian ()
Get whether an analytic Jacobian is used.
Returns:
mUseAnalyticJacobian
Definition at line 173 of file AbstractOdeSystem.cpp.
References mUseAnalyticJacobian.
Referenced by BackwardEulerIvpOdeSolver::ComputeJacobian().
const std::vector< std::string > & AbstractOdeSystem::rGetParameterNames () const
Get the names of the parameters in the ODE system.
Definition at line 86 of file AbstractOdeSystem.cpp.
References mpSystemInfo.
const std::vector< std::string > & AbstractOdeSystem::rGetParameterUnits () const
Get the units of the parameters in the ODE system.
Definition at line 92 of file AbstractOdeSystem.cpp.
References mpSystemInfo.
std::vector< double > & AbstractOdeSystem::rGetStateVariables ()
Get the values of the state variables in the ODE system.
Definition at line 144 of file AbstractOdeSystem.cpp.
References mStateVariables.
Referenced by WntCellCycleModel::ChangeCellProliferativeTypeDueToCurrentBetaCateninLevel(), AbstractVanLeeuwen2009WntSwatCellCycleModel::ChangeCellProliferativeTypeDueToCurrentBetaCateninLevel(), AbstractCardiacCell::Compute(), AbstractBackwardEulerCardiacCell< SIZE >::Compute(), BackwardEulerLuoRudyIModel1991::ComputeJacobian(), BackwardEulerTenTusscher2006::ComputeOneStepExceptVoltage(), BackwardEulerNobleVargheseKohlNoble1998::ComputeOneStepExceptVoltage(), BackwardEulerMahajanModel2008::ComputeOneStepExceptVoltage(), BackwardEulerLuoRudyIModel1991::ComputeOneStepExceptVoltage(), BackwardEulerFoxModel2002Modified::ComputeOneStepExceptVoltage(), CML_luo_rudy_1991_pe_lut_be::ComputeOneStepExceptVoltage(), BackwardEulerLuoRudyIModel1991::ComputeResidual(), DumpState(), FakeBathCell::FakeBathCell(), Nash2004ContractionModel::GetActiveTension(), SingleOdeWntCellCycleModel::GetBetaCateninConcentration(), AbstractVanLeeuwen2009WntSwatCellCycleModel::GetCytoplasmicBetaCateninLevel(), CellShannon2004FromCellML::GetIIonic(), CML_noble_varghese_kohl_noble_1998_basic_pe_lut::GetIIonic(), CML_noble_varghese_kohl_noble_1998_basic::GetIIonic(), Maleckar2009OdeSystem::GetIIonic(), Mahajan2008OdeSystem::GetIIonic(), FoxModel2002Modified::GetIIonic(), FaberRudy2000Version3Optimised::GetIIonic(), FaberRudy2000Version3::GetIIonic(), BackwardEulerTenTusscher2006::GetIIonic(), BackwardEulerNobleVargheseKohlNoble1998::GetIIonic(), BackwardEulerMahajanModel2008::GetIIonic(), BackwardEulerFoxModel2002Modified::GetIIonic(), Cellluo_rudy_1991FromCellMLOpt::GetIIonic(), CML_luo_rudy_1991_pe_lut_be::GetIIonic(), Cellluo_rudy_1991FromCellML::GetIIonic(), AbstractVanLeeuwen2009WntSwatCellCycleModel::GetMembraneBoundBetaCateninLevel(), AbstractVanLeeuwen2009WntSwatCellCycleModel::GetNuclearBetaCateninLevel(), AbstractOdeBasedCellCycleModel::GetProteinConcentrations(), AbstractCardiacCell::GetVoltage(), SingleOdeWntCellCycleModel::load(), TysonNovakCellCycleModel::ResetForDivision(), AbstractWntOdeBasedCellCycleModel::ResetForDivision(), SingleOdeWntCellCycleModel::save(), AbstractOdeBasedCellCycleModel::serialize(), AbstractOdeBasedCellCycleModel::SetProteinConcentrationsForTestsOnly(), AbstractCardiacCell::SetVoltage(), SingleOdeWntCellCycleModel::SingleOdeWntCellCycleModel(), AbstractIvpOdeSolver::SolveAndUpdateStateVariable(), WntCellCycleModel::SolveOdeToTime(), AbstractVanLeeuwen2009WntSwatCellCycleModel::SolveOdeToTime(), SingleOdeWntCellCycleModel::UpdateBetaCateninLevel(), AbstractOdeBasedCellCycleModel::UpdateCellCyclePhase(), BackwardEulerTenTusscher2006::UpdateTransmembranePotential(), BackwardEulerNobleVargheseKohlNoble1998::UpdateTransmembranePotential(), BackwardEulerMahajanModel2008::UpdateTransmembranePotential(), BackwardEulerLuoRudyIModel1991::UpdateTransmembranePotential(), BackwardEulerFoxModel2002Modified::UpdateTransmembranePotential(), CML_luo_rudy_1991_pe_lut_be::UpdateTransmembranePotential(), TenTusscher2006OdeSystem::VerifyStateVariables(), LuoRudyIModel1991OdeSystem::VerifyStateVariables(), DiFrancescoNoble1985OdeSystem::VerifyStateVariables(), BackwardEulerNobleVargheseKohlNoble1998::VerifyStateVariables(), BackwardEulerLuoRudyIModel1991::VerifyStateVariables(), and WntCellCycleModel::WntCellCycleModel().
const std::vector< std::string > & AbstractOdeSystem::rGetVariableNames () const
Get the names of the state variables in the ODE system.
Definition at line 149 of file AbstractOdeSystem.cpp.
References mpSystemInfo.
Referenced by DumpState(), and FoxModel2002Modified::EvaluateYDerivatives().
const std::vector< std::string > & AbstractOdeSystem::rGetVariableUnits () const
Get the units of the state variables in the ODE system.
Definition at line 155 of file AbstractOdeSystem.cpp.
References mpSystemInfo.
template<class Archive > void AbstractOdeSystem::serialize (Archive & archive, const unsigned int version) [inline, private]
Archive the member variables.
Parameters:
archive the archive
version the current version of this class
Reimplemented in AbstractBackwardEulerCardiacCell< SIZE >, AbstractCardiacCell, Cellluo_rudy_1991FromCellML, CML_luo_rudy_1991_pe_lut_be, Cellluo_rudy_1991FromCellMLOpt, FakeBathCell, BackwardEulerFoxModel2002Modified, BackwardEulerLuoRudyIModel1991, BackwardEulerMahajanModel2008, BackwardEulerNobleVargheseKohlNoble1998, BackwardEulerTenTusscher2006, FaberRudy2000Version3, LuoRudyIModel1991OdeSystem, Maleckar2009OdeSystem, CML_noble_varghese_kohl_noble_1998_basic, CellShannon2004FromCellML, AbstractBackwardEulerCardiacCell< 12 >, AbstractBackwardEulerCardiacCell< 1 >, AbstractBackwardEulerCardiacCell< 15 >, AbstractBackwardEulerCardiacCell< 3 >, and AbstractBackwardEulerCardiacCell< 7 >.
Definition at line 91 of file AbstractOdeSystem.hpp.
References mNumberOfStateVariables, mParameters, mStateVariables, and mUseAnalyticJacobian.
void AbstractOdeSystem::SetInitialConditions (const std::vector< double > & rInitialConditions)
Set the initial conditions for the ODE system.
Parameters:
rInitialConditions vector containing initial values for the state variables
Definition at line 99 of file AbstractOdeSystem.cpp.
References mNumberOfStateVariables, and mpSystemInfo.
void AbstractOdeSystem::SetInitialConditionsComponent (unsigned index, double initialCondition)
Set the initial condition one state variable.
Parameters:
index the index of the state variable in the system
initialCondition the initial value for the state variable
Definition at line 109 of file AbstractOdeSystem.cpp.
References mNumberOfStateVariables, and mpSystemInfo.
Referenced by Mirams2010WntOdeSystem::Mirams2010WntOdeSystem(), VanLeeuwen2009WntSwatCellCycleOdeSystem::VanLeeuwen2009WntSwatCellCycleOdeSystem(), and WntCellCycleOdeSystem::WntCellCycleOdeSystem().
void AbstractOdeSystem::SetParameter (unsigned index, double value)
Set the value of a given parameter.
Parameters:
index the index of the parameter
value the value
Definition at line 81 of file AbstractOdeSystem.cpp.
References mParameters.
void AbstractOdeSystem::SetStateVariable (unsigned stateVariable, double newValue)
Set the value of a single state variable in the ODE system.
Parameters:
stateVariable index of the state variable to be set
newValue new value of the state variable
Definition at line 134 of file AbstractOdeSystem.cpp.
References mNumberOfStateVariables, and mStateVariables.
void AbstractOdeSystem::SetStateVariables (const std::vector< double > & rStateVariables)
Set the values of the state variables in the ODE system.
Parameters:
rStateVariables vector containing values for the state variables
Definition at line 125 of file AbstractOdeSystem.cpp.
References mNumberOfStateVariables, and mStateVariables.
Referenced by CombinedOdeSystem::CombinedOdeSystem(), AbstractCardiacCell::Init(), WntCellCycleModel::Initialise(), SingleOdeWntCellCycleModel::Initialise(), AbstractVanLeeuwen2009WntSwatCellCycleModel::Initialise(), NhsContractionModel::NhsContractionModel(), TysonNovakCellCycleModel::ResetForDivision(), AbstractOdeBasedCellCycleModel::SetProteinConcentrationsForTestsOnly(), and TysonNovakCellCycleModel::TysonNovakCellCycleModel().
Friends And Related Function Documentation
friend class boost::serialization::access [friend]
Needed for serialization.
Reimplemented in AbstractBackwardEulerCardiacCell< SIZE >, AbstractCardiacCell, Cellluo_rudy_1991FromCellML, CML_luo_rudy_1991_pe_lut_be, Cellluo_rudy_1991FromCellMLOpt, FakeBathCell, BackwardEulerFoxModel2002Modified, BackwardEulerLuoRudyIModel1991, BackwardEulerMahajanModel2008, BackwardEulerNobleVargheseKohlNoble1998, BackwardEulerTenTusscher2006, FaberRudy2000Version3, LuoRudyIModel1991OdeSystem, Maleckar2009OdeSystem, CML_noble_varghese_kohl_noble_1998_basic, CellShannon2004FromCellML, AbstractBackwardEulerCardiacCell< 12 >, AbstractBackwardEulerCardiacCell< 1 >, AbstractBackwardEulerCardiacCell< 15 >, AbstractBackwardEulerCardiacCell< 3 >, and AbstractBackwardEulerCardiacCell< 7 >.
Definition at line 82 of file AbstractOdeSystem.hpp.
Member Data Documentation
unsigned AbstractOdeSystem::mNumberOfStateVariables [protected]
The number of state variables in the ODE system.
Definition at line 106 of file AbstractOdeSystem.hpp.
Referenced by AbstractCardiacCell::AbstractCardiacCell(), CombinedOdeSystem::CombinedOdeSystem(), GetNumberOfStateVariables(), GetStateVariableUnitsByNumber(), GetStateVariableValueByNumber(), serialize(), SetInitialConditions(), SetInitialConditionsComponent(), SetStateVariable(), and SetStateVariables().
std::vector<double> AbstractOdeSystem::mParameters [protected]
Vector containing parameters.
Definition at line 112 of file AbstractOdeSystem.hpp.
Referenced by GetNumberOfParameters(), GetParameter(), serialize(), and SetParameter().
boost::shared_ptr<AbstractOdeSystemInformation> AbstractOdeSystem::mpSystemInfo [protected]
Information about the concrete ODE system class.
Subclasses need to set this in their constructor to point to an instance of a suitable class. See for example the OdeSystemInformation class.
Definition at line 120 of file AbstractOdeSystem.hpp.
Referenced by BackwardEulerFoxModel2002Modified::BackwardEulerFoxModel2002Modified(), CombinedOdeSystem::CombinedOdeSystem(), AbstractBackwardEulerCardiacCell< SIZE >::Compute(), DiFrancescoNoble1985OdeSystem::DiFrancescoNoble1985OdeSystem(), FaberRudy2000Version3::FaberRudy2000Version3(), FakeBathCell::FakeBathCell(), FitzHughNagumo1961OdeSystem::FitzHughNagumo1961OdeSystem(), FoxModel2002Modified::FoxModel2002Modified(), GetInitialConditions(), GetStateVariableNumberByName(), GetStateVariableUnitsByNumber(), GetSystemInformation(), HodgkinHuxleySquidAxon1952OriginalOdeSystem::HodgkinHuxleySquidAxon1952OriginalOdeSystem(), BackwardEulerLuoRudyIModel1991::Init(), Kerchoffs2003ContractionModel::Kerchoffs2003ContractionModel(), LuoRudyIModel1991OdeSystem::LuoRudyIModel1991OdeSystem(), Mahajan2008OdeSystem::Mahajan2008OdeSystem(), Maleckar2009OdeSystem::Maleckar2009OdeSystem(), Mirams2010WntOdeSystem::Mirams2010WntOdeSystem(), Nash2004ContractionModel::Nash2004ContractionModel(), NhsContractionModel::NhsContractionModel(), rGetParameterNames(), rGetParameterUnits(), rGetVariableNames(), rGetVariableUnits(), SetInitialConditions(), SetInitialConditionsComponent(), TenTusscher2006OdeSystem::TenTusscher2006OdeSystem(), TysonNovak2001OdeSystem::TysonNovak2001OdeSystem(), VanLeeuwen2009WntSwatCellCycleOdeSystem::VanLeeuwen2009WntSwatCellCycleOdeSystem(), and WntCellCycleOdeSystem::WntCellCycleOdeSystem().
std::vector<double> AbstractOdeSystem::mStateVariables [protected]
Vector containing the current values of the state variables.
Definition at line 109 of file AbstractOdeSystem.hpp.
Referenced by NhsContractionModel::GetActiveTension(), Kerchoffs2003ContractionModel::GetActiveTension(), NhsContractionModel::GetCalciumTroponinValue(), TenTusscher2006OdeSystem::GetIIonic(), LuoRudyIModel1991OdeSystem::GetIIonic(), HodgkinHuxleySquidAxon1952OriginalOdeSystem::GetIIonic(), FitzHughNagumo1961OdeSystem::GetIIonic(), DiFrancescoNoble1985OdeSystem::GetIIonic(), BackwardEulerLuoRudyIModel1991::GetIIonic(), LuoRudyIModel1991OdeSystem::GetIntracellularCalciumConcentration(), BackwardEulerLuoRudyIModel1991::GetIntracellularCalciumConcentration(), GetStateVariableValueByNumber(), Kerchoffs2003ContractionModel::Kerchoffs2003ContractionModel(), Nash2004ContractionModel::Nash2004ContractionModel(), rGetStateVariables(), NhsModelWithBackwardSolver::RunDoNotUpdate(), AbstractOdeBasedContractionModel::RunDoNotUpdate(), serialize(), SetStateVariable(), SetStateVariables(), and AbstractOdeBasedContractionModel::UpdateStateVariables().
bool AbstractOdeSystem::mUseAnalyticJacobian [protected]
Whether to use an analytic Jacobian.
Definition at line 123 of file AbstractOdeSystem.hpp.
Referenced by AbstractOdeSystemWithAnalyticJacobian::AbstractOdeSystemWithAnalyticJacobian(), GetUseAnalyticJacobian(), and serialize().
The documentation for this class was generated from the following files:
/tmp/release_2.0/ode/src/common/AbstractOdeSystem.hpp
/tmp/release_2.0/ode/src/common/AbstractOdeSystem.cpp