Chaste: BidomainWithBathMatrixBasedAssembler< ELEMENT_DIM, SPACE_DIM > Class Template Reference
BidomainWithBathMatrixBasedAssembler< ELEMENT_DIM, SPACE_DIM > Class Template Reference
#include <BidomainWithBathMatrixBasedAssembler.hpp>
Inherits BidomainMatrixBasedAssembler< ELEMENT_DIM, SPACE_DIM >, and BidomainWithBathAssembler< ELEMENT_DIM, SPACE_DIM >.
Public Member Functions
BidomainWithBathMatrixBasedAssembler (AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM > *pMesh, BidomainPde< SPACE_DIM > *pPde, BoundaryConditionsContainer< ELEMENT_DIM, SPACE_DIM, 2 > *pBcc, unsigned numQuadPoints=2)
~BidomainWithBathMatrixBasedAssembler ()
void ConstructVectorForMatrixBasedRhsAssembly (Vec existingSolution)
Protected Attributes
BidomainWithBathRhsMatrixAssembler
< SPACE_DIM > * mpBidomainWithBathRhsMatrixAssembler
Detailed Description
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM>
class BidomainWithBathMatrixBasedAssembler< ELEMENT_DIM, SPACE_DIM >
Assemble with matrix-based system in the presence of a perfusing bath
Definition at line 139 of file BidomainWithBathMatrixBasedAssembler.hpp.
Constructor & Destructor Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> BidomainWithBathMatrixBasedAssembler< ELEMENT_DIM, SPACE_DIM >::BidomainWithBathMatrixBasedAssembler (AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM > * pMesh, BidomainPde< SPACE_DIM > * pPde, BoundaryConditionsContainer< ELEMENT_DIM, SPACE_DIM, 2 > * pBcc, unsigned numQuadPoints = 2) [inline]
Constructor calls base constructor and creates and stores rhs-matrix.
Parameters:
pMesh pointer to the mesh
pPde pointer to the PDE
pBcc pointer to the boundary conditions
numQuadPoints number of quadrature points (defaults to 2)
Todo:
#1063 at this point we'll have a BidomainWithBathRhsMatrixAssembler object and a BidomainRhsMatrixAssembler object in memory. This is a waste of memory since both construct and store a matrix for RHS assembly.
Definition at line 135 of file BidomainWithBathMatrixBasedAssembler.cpp.
References BidomainWithBathRhsMatrixAssembler< DIM >::GetMatrix(), BidomainWithBathMatrixBasedAssembler< ELEMENT_DIM, SPACE_DIM >::mpBidomainWithBathRhsMatrixAssembler, and AbstractDynamicAssemblerMixin< ELEMENT_DIM, SPACE_DIM, 2 >::mpMatrixForMatrixBasedRhsAssembly.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> BidomainWithBathMatrixBasedAssembler< ELEMENT_DIM, SPACE_DIM >::~BidomainWithBathMatrixBasedAssembler () [inline]
Destructor.
Definition at line 155 of file BidomainWithBathMatrixBasedAssembler.cpp.
References BidomainWithBathMatrixBasedAssembler< ELEMENT_DIM, SPACE_DIM >::mpBidomainWithBathRhsMatrixAssembler.
Member Function Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void BidomainWithBathMatrixBasedAssembler< ELEMENT_DIM, SPACE_DIM >::ConstructVectorForMatrixBasedRhsAssembly (Vec existingSolution) [inline, virtual]
This constructs the vector z such that b (in Ax=b) is given by Bz = b. See main class documentation.
Parameters:
existingSolution
Reimplemented from BidomainMatrixBasedAssembler< ELEMENT_DIM, SPACE_DIM >.
Definition at line 162 of file BidomainWithBathMatrixBasedAssembler.cpp.
References HeartRegionCode::BATH, DistributedVector::Begin(), DistributedVectorFactory::CreateDistributedVector(), DistributedVector::End(), HeartConfig::GetCapacitance(), HeartConfig::GetSurfaceAreaToVolumeRatio(), HeartConfig::Instance(), AbstractDynamicAssemblerMixin< ELEMENT_DIM, SPACE_DIM, 2 >::mDtInverse, BidomainDg0Assembler< ELEMENT_DIM, SPACE_DIM >::mpBidomainPde, AbstractStaticAssembler< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM, NON_HEART, BidomainDg0Assembler< ELEMENT_DIM, SPACE_DIM > >::mpMesh, AbstractDynamicAssemblerMixin< ELEMENT_DIM, SPACE_DIM, 2 >::mVectorForMatrixBasedRhsAssembly, and DistributedVector::Restore().
Member Data Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> BidomainWithBathRhsMatrixAssembler<SPACE_DIM>* BidomainWithBathMatrixBasedAssembler< ELEMENT_DIM, SPACE_DIM >::mpBidomainWithBathRhsMatrixAssembler [protected]
Todo:
#1063 Once BidomainWithBathRhsMatrixAssembler inherits from BidomainRhsMatrixAssembler we'll be able to reuse the pointer in BidomainMatrixBasedAssembler
Definition at line 145 of file BidomainWithBathMatrixBasedAssembler.hpp.
Referenced by BidomainWithBathMatrixBasedAssembler< ELEMENT_DIM, SPACE_DIM >::BidomainWithBathMatrixBasedAssembler(), and BidomainWithBathMatrixBasedAssembler< ELEMENT_DIM, SPACE_DIM >::~BidomainWithBathMatrixBasedAssembler().
The documentation for this class was generated from the following files:
/tmp/release_2.0/heart/src/solver/BidomainWithBathMatrixBasedAssembler.hpp
/tmp/release_2.0/heart/src/solver/BidomainWithBathMatrixBasedAssembler.cpp