Chaste: AbstractVanLeeuwen2009WntSwatCellCycleModel Class Reference
AbstractVanLeeuwen2009WntSwatCellCycleModel Class Reference
#include <AbstractVanLeeuwen2009WntSwatCellCycleModel.hpp>
Inherits AbstractWntOdeBasedCellCycleModel.
Inherited by VanLeeuwen2009WntSwatCellCycleModelHypothesisOne, and VanLeeuwen2009WntSwatCellCycleModelHypothesisTwo.
Public Member Functions
AbstractVanLeeuwen2009WntSwatCellCycleModel ()
AbstractVanLeeuwen2009WntSwatCellCycleModel (const AbstractVanLeeuwen2009WntSwatCellCycleModel &rOtherModel)
void Initialise ()
bool SolveOdeToTime (double currentTime)
double GetMembraneBoundBetaCateninLevel ()
double GetCytoplasmicBetaCateninLevel ()
double GetNuclearBetaCateninLevel ()
virtual void InitialiseOdeSystem (double wntConcentration, boost::shared_ptr< AbstractCellMutationState > pMutationState)=0
Private Member Functions
template<class Archive >
void save (Archive &archive, const unsigned int version) const
template<class Archive >
void load (Archive &archive, const unsigned int version)
void ChangeCellProliferativeTypeDueToCurrentBetaCateninLevel ()
Friends
class boost::serialization::access
Detailed Description
Wnt-dependent cell cycle model.
Note that this class uses C++'s default copying semantics, and so doesn't implement a copy constructor or operator=.
Definition at line 52 of file AbstractVanLeeuwen2009WntSwatCellCycleModel.hpp.
Constructor & Destructor Documentation
AbstractVanLeeuwen2009WntSwatCellCycleModel::AbstractVanLeeuwen2009WntSwatCellCycleModel ()
Default constructor.
Definition at line 32 of file AbstractVanLeeuwen2009WntSwatCellCycleModel.cpp.
AbstractVanLeeuwen2009WntSwatCellCycleModel::AbstractVanLeeuwen2009WntSwatCellCycleModel (const AbstractVanLeeuwen2009WntSwatCellCycleModel & rOtherModel)
Copy constructor.
Creates an appropriate copy of our ODE system too.
Parameters:
rOtherModel the instance being copied.
Definition at line 38 of file AbstractVanLeeuwen2009WntSwatCellCycleModel.cpp.
References AbstractOdeBasedCellCycleModel::mpOdeSystem.
Member Function Documentation
void AbstractVanLeeuwen2009WntSwatCellCycleModel::ChangeCellProliferativeTypeDueToCurrentBetaCateninLevel () [private, virtual]
Called by Initialise() and UpdateCellProliferativeType() only. Updates the mpCell::mCellProliferativeType to match mpOdeSystem's beta-catenin levels
This carries out the work for UpdateCellProliferativeType(); But does not check the current time so it can be used by the initialise method.
Implements AbstractWntOdeBasedCellCycleModel.
Definition at line 48 of file AbstractVanLeeuwen2009WntSwatCellCycleModel.cpp.
References AbstractCellCycleModel::mpCell, AbstractOdeBasedCellCycleModel::mpOdeSystem, AbstractOdeSystem::rGetStateVariables(), and TissueCell::SetCellProliferativeType().
Referenced by Initialise().
double AbstractVanLeeuwen2009WntSwatCellCycleModel::GetCytoplasmicBetaCateninLevel ()
Returns:
the level of cytoplasmic beta-catenin (including ubiquitinated - awaiting degradation)
Definition at line 113 of file AbstractVanLeeuwen2009WntSwatCellCycleModel.cpp.
References AbstractOdeBasedCellCycleModel::mpOdeSystem, and AbstractOdeSystem::rGetStateVariables().
Referenced by CryptSimulation2d::WriteBetaCatenin().
double AbstractVanLeeuwen2009WntSwatCellCycleModel::GetMembraneBoundBetaCateninLevel ()
Returns:
the level of membrane bound beta-catenin. To be used in cell-cell adhesion calculations.
Definition at line 107 of file AbstractVanLeeuwen2009WntSwatCellCycleModel.cpp.
References AbstractOdeBasedCellCycleModel::mpOdeSystem, and AbstractOdeSystem::rGetStateVariables().
Referenced by LinearSpringWithVariableSpringConstantsForce< DIM >::VariableSpringConstantMultiplicationFactor(), and CryptSimulation2d::WriteBetaCatenin().
double AbstractVanLeeuwen2009WntSwatCellCycleModel::GetNuclearBetaCateninLevel ()
Returns:
the level of nuclear beta-catenin. To be used in transcription
Definition at line 121 of file AbstractVanLeeuwen2009WntSwatCellCycleModel.cpp.
References AbstractOdeBasedCellCycleModel::mpOdeSystem, and AbstractOdeSystem::rGetStateVariables().
Referenced by CryptSimulation2d::WriteBetaCatenin().
void AbstractVanLeeuwen2009WntSwatCellCycleModel::Initialise (void) [virtual]
See AbstractCellCycleModel::Initialise()
In this case we set up a new ODE system for a daughter cell.
Reimplemented from AbstractCellCycleModel.
Definition at line 69 of file AbstractVanLeeuwen2009WntSwatCellCycleModel.cpp.
References ChangeCellProliferativeTypeDueToCurrentBetaCateninLevel(), AbstractOdeSystem::GetInitialConditions(), TissueCell::GetMutationState(), AbstractWntOdeBasedCellCycleModel::GetWntLevel(), InitialiseOdeSystem(), AbstractCellCycleModel::mpCell, AbstractOdeBasedCellCycleModel::mpOdeSystem, and AbstractOdeSystem::SetStateVariables().
virtual void AbstractVanLeeuwen2009WntSwatCellCycleModel::InitialiseOdeSystem (double wntConcentration, boost::shared_ptr< AbstractCellMutationState > pMutationState) [pure virtual]
Pure virtual method to be implemented in concrete classes, which should should allocate the mOdeSystem variable using the appropriate hypothesis (one or two).
Parameters:
wntConcentration Wnt concentration
pMutationState Mutation state
Implemented in VanLeeuwen2009WntSwatCellCycleModelHypothesisOne, and VanLeeuwen2009WntSwatCellCycleModelHypothesisTwo.
Referenced by Initialise(), and load().
template<class Archive > void AbstractVanLeeuwen2009WntSwatCellCycleModel::load (Archive & archive, const unsigned int version) [inline, private]
Load the cell cycle model and ODE system from archive.
Parameters:
archive the archive
version the archive version
Definition at line 80 of file AbstractVanLeeuwen2009WntSwatCellCycleModel.hpp.
References InitialiseOdeSystem(), and AbstractOdeBasedCellCycleModel::mpOdeSystem.
template<class Archive > void AbstractVanLeeuwen2009WntSwatCellCycleModel::save (Archive & archive, const unsigned int version) const [inline, private]
Archive the cell cycle model and ODE system.
Parameters:
archive the archive
version the archive version
Definition at line 65 of file AbstractVanLeeuwen2009WntSwatCellCycleModel.hpp.
References AbstractOdeBasedCellCycleModel::mpOdeSystem.
bool AbstractVanLeeuwen2009WntSwatCellCycleModel::SolveOdeToTime (double currentTime) [virtual]
Solve the ODE to the current time.
Parameters:
currentTime the current time
Returns:
Whether a stopping event occurred.
Implements AbstractOdeBasedCellCycleModel.
Definition at line 84 of file AbstractVanLeeuwen2009WntSwatCellCycleModel.cpp.
References TissueCell::GetMutationState(), SimulationTime::GetTimeStep(), AbstractWntOdeBasedCellCycleModel::GetWntLevel(), SimulationTime::Instance(), AbstractOdeBasedCellCycleModel::mLastTime, AbstractCellCycleModel::mpCell, AbstractOdeBasedCellCycleModel::mpOdeSystem, AbstractWntOdeBasedCellCycleModel::msSolver, AbstractOdeSystem::rGetStateVariables(), AbstractIvpOdeSolver::SolveAndUpdateStateVariable(), AbstractIvpOdeSolver::StoppingEventOccurred(), and AbstractWntOdeBasedCellCycleModel::UpdateCellProliferativeType().
Friends And Related Function Documentation
friend class boost::serialization::access [friend]
Needed for serialization.
Reimplemented from AbstractWntOdeBasedCellCycleModel.
Reimplemented in VanLeeuwen2009WntSwatCellCycleModelHypothesisOne, and VanLeeuwen2009WntSwatCellCycleModelHypothesisTwo.
Definition at line 57 of file AbstractVanLeeuwen2009WntSwatCellCycleModel.hpp.
The documentation for this class was generated from the following files:
/tmp/release_2.0/cell_based/src/crypt/cell/cycle/AbstractVanLeeuwen2009WntSwatCellCycleModel.hpp
/tmp/release_2.0/cell_based/src/crypt/cell/cycle/AbstractVanLeeuwen2009WntSwatCellCycleModel.cpp