Chaste: CryptStatistics Class Reference
CryptStatistics Class Reference
#include <CryptStatistics.hpp>
Inherits AbstractCryptStatistics.
Public Member Functions
CryptStatistics (MeshBasedTissue< 2 > &rCrypt)
virtual ~CryptStatistics ()
std::vector< TissueCell * > GetCryptSection (double xBottom=DBL_MAX, double xTop=DBL_MAX, double yTop=TissueConfig::Instance()->GetCryptLength()+2.0, bool periodic=false)
std::vector< TissueCell * > GetCryptSectionPeriodic (double xBottom=DBL_MAX, double xTop=DBL_MAX, double yTop=TissueConfig::Instance()->GetCryptLength()+2.0)
Protected Member Functions
bool CellIsInSection (double xBottom, double xTop, double yTop, const c_vector< double, 2 > &rCellPosition, double widthOfSection=0.5)
bool CellIsInSectionPeriodic (double xBottom, double xTop, double yTop, const c_vector< double, 2 > &rCellPosition, double widthOfSection=1.0)
Detailed Description
Concrete statistics class for the cylindrical crypt model.
Definition at line 36 of file CryptStatistics.hpp.
Constructor & Destructor Documentation
CryptStatistics::CryptStatistics (MeshBasedTissue< 2 > & rCrypt) [inline]
Constructor
Parameters:
rCrypt The crypt
Definition at line 80 of file CryptStatistics.hpp.
virtual CryptStatistics::~CryptStatistics () [inline, virtual]
Free any memory allocated by the constructor
Definition at line 86 of file CryptStatistics.hpp.
Member Function Documentation
bool CryptStatistics::CellIsInSection (double xBottom, double xTop, double yTop, const c_vector< double, 2 > & rCellPosition, double widthOfSection = 0.5) [protected]
Method computing the perpendicular distance from the cell to the line from (xBottom, 0) to (xTop, yTop), and returning if the distance is within the specified width to the section (defaults to 0.5).
Parameters:
xBottom the x coordinate of the bottom of the line
xTop the x coordinate of the top of the line
yTop the y coordinate of the top of the line
rCellPosition the location of the cell centre
widthOfSection the width of the line
Returns:
whether the cell is in the section
Definition at line 43 of file CryptStatistics.cpp.
References AbstractMesh< ELEMENT_DIM, SPACE_DIM >::GetVectorFromAtoB(), AbstractCryptStatistics::mrCrypt, and MeshBasedTissue< DIM >::rGetMesh().
Referenced by GetCryptSection().
bool CryptStatistics::CellIsInSectionPeriodic (double xBottom, double xTop, double yTop, const c_vector< double, 2 > & rCellPosition, double widthOfSection = 1.0) [protected]
Method computing the perpendicular distance from the cell to the line from (xBottom, 0) to (xTop, yTop), taking into account periodicity, and returning if the distance is within the specified width to the section (defaults to 1.0). Done by considering the two possible lines and checking if cells are within range.
Parameters:
xBottom the x coordinate of the bottom of the line
xTop the x coordinate of the top of the line
yTop the y coordinate of the top of the line
rCellPosition the location of the cell centre
widthOfSection the width of the line
Returns:
whether the cell is in the section
Definition at line 66 of file CryptStatistics.cpp.
References TissueConfig::GetCryptWidth(), AbstractMesh< ELEMENT_DIM, SPACE_DIM >::GetVectorFromAtoB(), TissueConfig::Instance(), AbstractCryptStatistics::mrCrypt, and MeshBasedTissue< DIM >::rGetMesh().
Referenced by GetCryptSection().
std::vector< TissueCell * > CryptStatistics::GetCryptSection (double xBottom = DBL_MAX, double xTop = DBL_MAX, double yTop = TissueConfig::Instance()->GetCryptLength() + 2.0, bool periodic = false)
Get all cells within a cell width of the section defined as the line between points (xBottom,0) and (xTop,yTop)
Periodicity can be taken into account (if xTop and xBottom are more than half a crypt width apart then a more realistic section will be across the periodic boundary), using the final parameter. This obviously requires the mesh to be cylindrical.
Parameters:
xBottom the x coordinate of the bottom of the line (defaults to a random number U[0,crypt_width])
xTop the x coordinate of the top of the line (defaults to a random number U[0,crypt_width])
yTop the y coordinate of the top of the line (defaults to crypt_length +2, to get the cells near the top)
periodic whether periodicity is accounted for (defaults to false)
Returns:
an ordered list of pointes to TissueCells from the bottom to the top of the crypt.
Note that placing calls to functions with side-effects (eg. changing the random seed) in the default arguments is DANGEROUS. There is no guarantee that the compiler will execute these in a sensible order. It appears that Intel goes left-to-right and Gcc goes right-to-left.
Definition at line 117 of file CryptStatistics.cpp.
References AbstractTissue< DIM >::Begin(), CellIsInSection(), CellIsInSectionPeriodic(), AbstractTissue< DIM >::End(), TissueConfig::GetCryptWidth(), AbstractCellCentreBasedTissue< DIM >::GetLocationOfCellCentre(), TissueConfig::Instance(), RandomNumberGenerator::Instance(), AbstractCryptStatistics::mrCrypt, and RandomNumberGenerator::ranf().
Referenced by GetCryptSectionPeriodic().
std::vector< TissueCell * > CryptStatistics::GetCryptSectionPeriodic (double xBottom = DBL_MAX, double xTop = DBL_MAX, double yTop = TissueConfig::Instance()->GetCryptLength() + 2.0)
Get all cells with a cell width of the line defined by the points (xBottom,0) and (xTop,yTop), taking into account periodicity
If xTop and xBottom are more than half a crypt width apart then a more realistic section will be across the periodic boundary.
Note that placing calls to functions with side-effects (eg. changing the random seed) in the default arguments is DANGEROUS. There is no guarantee that the compiler will execute these in a sensible order. It appears that Intel goes left-to-right and Gcc goes right-to-left.
Parameters:
xBottom the x coordinate of the bottom of the line (defaults to a random number U[0,crypt_width])
xTop the x coordinate of the top of the line (defaults to a random number U[0,crypt_width])
yTop the y coordinate of the top of the line (defaults to crypt_length +2, to get the cells near the top)
Returns:
an ordered list of pointes to TissueCells from the bottom to the top of the crypt.
Definition at line 180 of file CryptStatistics.cpp.
References GetCryptSection().
The documentation for this class was generated from the following files:
/tmp/release_2.0/cell_based/src/crypt/statistics/CryptStatistics.hpp
/tmp/release_2.0/cell_based/src/crypt/statistics/CryptStatistics.cpp