Chaste: TissueConfig Class Reference
TissueConfig Class Reference
#include <TissueConfig.hpp>
Public Member Functions
double GetStemCellG1Duration ()
double GetTransitCellG1Duration ()
double GetHepaOneCellG1Duration ()
double GetMinimumGapDuration ()
double GetSG2MDuration ()
double GetSDuration ()
double GetG2Duration ()
double GetMDuration ()
unsigned GetMaxTransitGenerations ()
double GetCryptLength ()
double GetCryptWidth ()
double GetSpringStiffness ()
double GetMechanicsCutOffLength ()
double GetDampingConstantNormal ()
double GetDampingConstantMutant ()
double GetBetaCatSpringScaler ()
double GetApoptosisTime ()
double GetDivisionRestingSpringLength ()
double GetDivisionSeparation ()
double GetHepaOneCellHypoxicConcentration ()
double GetHepaOneCellQuiescentConcentration ()
double GetWntTransitThreshold ()
double GetWntStemThreshold ()
double GetWntLabelledThreshold ()
double GetWntConcentrationParameter ()
double GetCriticalHypoxicDuration ()
double GetCryptProjectionParameterA ()
double GetCryptProjectionParameterB ()
double GetApoptoticSpringTensionStiffness ()
double GetApoptoticSpringCompressionStiffness ()
double GetWntChemotaxisStrength ()
double GetSymmetricDivisionProbability ()
double GetAreaBasedDampingConstantParameter ()
double GetMatureCellTargetArea ()
double GetDeformationEnergyParameter ()
double GetMembraneSurfaceEnergyParameter ()
double GetCellCellAdhesionEnergyParameter ()
double GetCellBoundaryAdhesionEnergyParameter ()
double GetWelikyOsterAreaParameter ()
double GetWelikyOsterPerimeterParameter ()
bool GetOutputCellIdData ()
bool GetOutputCellMutationStates ()
bool GetOutputCellAncestors ()
bool GetOutputCellProliferativeTypes ()
bool GetOutputCellVariables ()
bool GetOutputCellCyclePhases ()
bool GetOutputCellAges ()
bool GetOutputCellAreas ()
bool GetOutputVoronoiData ()
bool GetOutputTissueAreas ()
bool GetOutputNodeVelocities ()
void SetStemCellG1Duration (double)
void SetTransitCellG1Duration (double)
void SetHepaOneCellG1Duration (double)
void SetMinimumGapDuration (double)
void SetSDuration (double)
void SetG2Duration (double)
void SetMDuration (double)
void SetMaxTransitGenerations (unsigned)
void SetCryptLength (double)
void SetCryptWidth (double)
void SetSpringStiffness (double)
void SetMechanicsCutOffLength (double)
void SetDampingConstantNormal (double)
void SetDampingConstantMutant (double)
void SetBetaCatSpringScaler (double)
void SetApoptosisTime (double)
void SetDivisionRestingSpringLength (double)
void SetDivisionSeparation (double)
void SetHepaOneCellHypoxicConcentration (double)
void SetHepaOneCellQuiescentConcentration (double)
void SetWntTransitThreshold (double)
void SetWntStemThreshold (double)
void SetWntLabelledThreshold (double)
void SetWntConcentrationParameter (double)
void SetCriticalHypoxicDuration (double)
void SetHepaOneParameters ()
void SetCryptProjectionParameterA (double)
void SetCryptProjectionParameterB (double)
void SetApoptoticSpringTensionStiffness (double)
void SetApoptoticSpringCompressionStiffness (double)
void SetWntChemotaxisStrength (double)
void SetSymmetricDivisionProbability (double)
void SetAreaBasedDampingConstantParameter (double)
void SetMatureCellTargetArea (double)
void SetDeformationEnergyParameter (double)
void SetMembraneSurfaceEnergyParameter (double)
void SetCellCellAdhesionEnergyParameter (double)
void SetCellBoundaryAdhesionEnergyParameter (double)
void SetWelikyOsterAreaParameter (double)
void SetWelikyOsterPerimeterParameter (double)
void SetOutputCellIdData (bool)
void SetOutputCellMutationStates (bool)
void SetOutputCellAncestors (bool)
void SetOutputCellProliferativeTypes (bool)
void SetOutputCellVariables (bool)
void SetOutputCellCyclePhases (bool)
void SetOutputCellAges (bool)
void SetOutputCellAreas (bool)
void SetOutputVoronoiData (bool)
void SetOutputTissueAreas (bool)
void SetOutputNodeVelocities (bool)
void Reset ()
Static Public Member Functions
static TissueConfig * Instance ()
Protected Member Functions
TissueConfig ()
TissueConfig (const TissueConfig &)
TissueConfig & operator= (const TissueConfig &)
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Private Attributes
double mStemCellG1Duration
double mTransitCellG1Duration
double mHepaOneCellG1Duration
double mMinimumGapDuration
double mSDuration
double mG2Duration
double mMDuration
unsigned mMaxTransitGenerations
double mCryptLength
double mCryptWidth
double mSpringStiffness
double mMechanicsCutOffLength
double mDampingConstantNormal
double mDampingConstantMutant
double mBetaCatSpringScaler
double mApoptosisTime
double mDivisionSeparation
double mDivisionRestingSpringLength
double mHepaOneCellHypoxicConcentration
double mHepaOneCellQuiescentConcentration
double mWntTransitThreshold
double mWntStemThreshold
double mWntLabelledThreshold
double mWntConcentrationParameter
double mCriticalHypoxicDuration
double mCryptProjectionParameterA
double mCryptProjectionParameterB
double mApoptoticSpringTensionStiffness
double mApoptoticSpringCompressionStiffness
double mWntChemotaxisStrength
double mSymmetricDivisionProbability
double mAreaBasedDampingConstantParameter
double mMatureCellTargetArea
double mDeformationEnergyParameter
double mMembraneSurfaceEnergyParameter
double mCellCellAdhesionEnergyParameter
double mCellBoundaryAdhesionEnergyParameter
double mWelikyOsterAreaParameter
double mWelikyOsterPerimeterParameter
bool mOutputCellIdData
bool mOutputCellMutationStates
bool mOutputCellAncestors
bool mOutputCellProliferativeTypes
bool mOutputCellVariables
bool mOutputCellCyclePhases
bool mOutputCellAges
bool mOutputCellAreas
bool mOutputVoronoiData
bool mOutputTissueAreas
bool mOutputNodeVelocities
Static Private Attributes
static TissueConfig * mpInstance = NULL
Friends
class boost::serialization::access
Detailed Description
A special singleton class which holds all of the parameters used in simulations.
Because this is a singleton class it can be called from whichever part of the code needs to find out a parameter value, the structure is quite simple with default values given upon initialisation and Set() and Get() methods for each parameter.
For details of each parameter refer to the member variable documentation for this class rather than the Get() and Set() function descriptions.
Definition at line 45 of file TissueConfig.hpp.
Constructor & Destructor Documentation
TissueConfig::TissueConfig () [protected]
Default constructor.
Definition at line 41 of file TissueConfig.cpp.
References mpInstance, and Reset().
TissueConfig::TissueConfig (const TissueConfig &) [protected]
Copy constructor.
Member Function Documentation
double TissueConfig::GetApoptosisTime ()
Returns:
mApoptosisTime
Definition at line 237 of file TissueConfig.cpp.
References mApoptosisTime.
Referenced by GeneralisedLinearSpringForce< DIM >::CalculateForceBetweenNodes(), CryptSimulation2d::OutputParameters(), and TissueCell::StartApoptosis().
double TissueConfig::GetApoptoticSpringCompressionStiffness ()
Returns:
mApoptoticSpringCompressionStiffness
Definition at line 289 of file TissueConfig.cpp.
References mApoptoticSpringCompressionStiffness.
Referenced by CryptSimulation2d::OutputParameters(), and LinearSpringWithVariableSpringConstantsForce< DIM >::VariableSpringConstantMultiplicationFactor().
double TissueConfig::GetApoptoticSpringTensionStiffness ()
Returns:
mApoptoticSpringTensionStiffness
Definition at line 285 of file TissueConfig.cpp.
References mApoptoticSpringTensionStiffness.
Referenced by CryptSimulation2d::OutputParameters(), and LinearSpringWithVariableSpringConstantsForce< DIM >::VariableSpringConstantMultiplicationFactor().
double TissueConfig::GetAreaBasedDampingConstantParameter ()
Returns:
mAreaBasedDampingConstantParameter
Definition at line 301 of file TissueConfig.cpp.
References mAreaBasedDampingConstantParameter.
Referenced by MeshBasedTissue< DIM >::GetDampingConstant(), and CryptSimulation2d::OutputParameters().
double TissueConfig::GetBetaCatSpringScaler ()
Returns:
mBetaCatSpringScaler
Definition at line 233 of file TissueConfig.cpp.
References mBetaCatSpringScaler.
Referenced by CryptSimulation2d::OutputParameters(), and LinearSpringWithVariableSpringConstantsForce< DIM >::VariableSpringConstantMultiplicationFactor().
double TissueConfig::GetCellBoundaryAdhesionEnergyParameter ()
Returns:
mCellBoundaryAdhesionEnergyParameter
Definition at line 321 of file TissueConfig.cpp.
References mCellBoundaryAdhesionEnergyParameter.
Referenced by CryptSimulation2d::OutputParameters().
double TissueConfig::GetCellCellAdhesionEnergyParameter ()
Returns:
mCellCellAdhesionEnergyParameter
Definition at line 317 of file TissueConfig.cpp.
References mCellCellAdhesionEnergyParameter.
Referenced by CryptSimulation2d::OutputParameters().
double TissueConfig::GetCriticalHypoxicDuration ()
Returns:
mCriticalHypoxicDuration
Definition at line 273 of file TissueConfig.cpp.
References mCriticalHypoxicDuration.
Referenced by CryptSimulation2d::OutputParameters().
double TissueConfig::GetCryptLength ()
Returns:
mCryptLength
Definition at line 209 of file TissueConfig.cpp.
References mCryptLength.
Referenced by WntConcentration< DIM >::GetWntGradient(), WntConcentration< DIM >::GetWntLevel(), CryptSimulation2d::OutputParameters(), and SloughingCellKiller< DIM >::TestAndLabelCellsForApoptosisOrDeath().
double TissueConfig::GetCryptProjectionParameterA ()
Returns:
mCryptProjectionParameterA
Definition at line 277 of file TissueConfig.cpp.
References mCryptProjectionParameterA.
Referenced by CryptSimulation2d::OutputParameters().
double TissueConfig::GetCryptProjectionParameterB ()
Returns:
mCryptProjectionParameterB
Definition at line 281 of file TissueConfig.cpp.
References mCryptProjectionParameterB.
Referenced by CryptSimulation2d::OutputParameters().
double TissueConfig::GetCryptWidth ()
Returns:
mCryptWidth
Definition at line 213 of file TissueConfig.cpp.
References mCryptWidth.
Referenced by CryptStatistics::CellIsInSectionPeriodic(), CryptStatistics::GetCryptSection(), CryptSimulation2d::OutputParameters(), and SloughingCellKiller< DIM >::TestAndLabelCellsForApoptosisOrDeath().
double TissueConfig::GetDampingConstantMutant ()
Returns:
mDampingConstantMutant
Definition at line 229 of file TissueConfig.cpp.
References mDampingConstantMutant.
Referenced by AbstractCellCentreBasedTissue< DIM >::GetDampingConstant(), and CryptSimulation2d::OutputParameters().
double TissueConfig::GetDampingConstantNormal ()
Returns:
mDampingConstantNormal
Definition at line 225 of file TissueConfig.cpp.
References mDampingConstantNormal.
Referenced by AbstractCellCentreBasedTissue< DIM >::GetDampingConstant(), CryptSimulation2d::OutputParameters(), and MeshBasedTissueWithGhostNodes< DIM >::UpdateGhostPositions().
double TissueConfig::GetDeformationEnergyParameter ()
Returns:
mDeformationEnergyParameter
Definition at line 309 of file TissueConfig.cpp.
References mDeformationEnergyParameter.
Referenced by CryptSimulation2d::OutputParameters().
double TissueConfig::GetDivisionRestingSpringLength ()
Returns:
mDivisionRestingSpringLength
Definition at line 241 of file TissueConfig.cpp.
References mDivisionRestingSpringLength.
Referenced by GeneralisedLinearSpringForce< DIM >::CalculateForceBetweenNodes().
double TissueConfig::GetDivisionSeparation ()
Returns:
mDivisionSeparation
Definition at line 245 of file TissueConfig.cpp.
References mDivisionSeparation.
Referenced by TissueSimulation< DIM >::CalculateCellDivisionVector(), CryptSimulation2d::CalculateCellDivisionVector(), and CryptSimulation1d::CalculateCellDivisionVector().
double TissueConfig::GetG2Duration ()
Returns:
mG2Duration
Definition at line 197 of file TissueConfig.cpp.
References mG2Duration.
Referenced by AbstractCellCycleModel::GetG2Duration(), CryptSimulation2d::OutputParameters(), and StochasticWntCellCycleModel::SetG2Duration().
double TissueConfig::GetHepaOneCellG1Duration ()
Returns:
mHepaOneCellG1Duration
Definition at line 181 of file TissueConfig.cpp.
References mHepaOneCellG1Duration.
Referenced by CryptSimulation2d::OutputParameters().
double TissueConfig::GetHepaOneCellHypoxicConcentration ()
Returns:
mHepaOneCellHypoxicConcentration
Definition at line 249 of file TissueConfig.cpp.
References mHepaOneCellHypoxicConcentration.
Referenced by CryptSimulation2d::OutputParameters().
double TissueConfig::GetHepaOneCellQuiescentConcentration ()
Returns:
mHepaOneCellQuiescentConcentration
Definition at line 253 of file TissueConfig.cpp.
References mHepaOneCellQuiescentConcentration.
Referenced by CryptSimulation2d::OutputParameters().
double TissueConfig::GetMatureCellTargetArea ()
Returns:
mMatureCellTargetArea
Definition at line 305 of file TissueConfig.cpp.
References mMatureCellTargetArea.
unsigned TissueConfig::GetMaxTransitGenerations ()
Returns:
mMaxTransitGenerations
Definition at line 205 of file TissueConfig.cpp.
References mMaxTransitGenerations.
Referenced by CryptSimulation2d::OutputParameters().
double TissueConfig::GetMDuration ()
Returns:
mMDuration
Definition at line 201 of file TissueConfig.cpp.
References mMDuration.
Referenced by GeneralisedLinearSpringForce< DIM >::CalculateForceBetweenNodes(), AbstractCellCycleModel::GetMDuration(), and CryptSimulation2d::OutputParameters().
double TissueConfig::GetMechanicsCutOffLength ()
Returns:
mMechanicsCutOffLength
Definition at line 221 of file TissueConfig.cpp.
References mMechanicsCutOffLength.
Referenced by GeneralisedLinearSpringForce< DIM >::CalculateForceBetweenNodes(), AbstractTwoBodyInteractionForce< DIM >::GetCutoffPoint(), CryptSimulation2d::OutputParameters(), and NodeBasedTissue< DIM >::Update().
double TissueConfig::GetMembraneSurfaceEnergyParameter ()
Returns:
mMembraneSurfaceEnergyParameter
Definition at line 313 of file TissueConfig.cpp.
References mMembraneSurfaceEnergyParameter.
Referenced by CryptSimulation2d::OutputParameters().
double TissueConfig::GetMinimumGapDuration ()
Returns:
mMinimumGapDuration
Definition at line 185 of file TissueConfig.cpp.
References mMinimumGapDuration.
Referenced by CryptSimulation2d::OutputParameters(), SimpleWntCellCycleModel::SetG1Duration(), and StochasticWntCellCycleModel::SetG2Duration().
bool TissueConfig::GetOutputCellAges ()
Returns:
mOutputCellAges
Definition at line 357 of file TissueConfig.cpp.
References mOutputCellAges.
Referenced by AbstractTissue< DIM >::CloseOutputFiles(), AbstractTissue< DIM >::CreateOutputFiles(), AbstractTissue< DIM >::GenerateCellResults(), CryptSimulation2d::OutputParameters(), AbstractTissue< DIM >::WriteCellResultsToFiles(), and AbstractTissue< DIM >::WriteResultsToFiles().
bool TissueConfig::GetOutputCellAncestors ()
Returns:
mOutputCellAncestors
Definition at line 341 of file TissueConfig.cpp.
References mOutputCellAncestors.
Referenced by AbstractTissue< DIM >::CloseOutputFiles(), AbstractTissue< DIM >::CreateOutputFiles(), AbstractTissue< DIM >::GenerateCellResults(), CryptSimulation2d::OutputParameters(), AbstractTissue< DIM >::WriteCellResultsToFiles(), and AbstractTissue< DIM >::WriteResultsToFiles().
bool TissueConfig::GetOutputCellAreas ()
Returns:
mOutputCellAreas
Definition at line 361 of file TissueConfig.cpp.
References mOutputCellAreas.
Referenced by CryptSimulation2d::OutputParameters().
bool TissueConfig::GetOutputCellCyclePhases ()
Returns:
mOutputCellCyclePhases
Definition at line 353 of file TissueConfig.cpp.
References mOutputCellCyclePhases.
Referenced by AbstractTissue< DIM >::CloseOutputFiles(), AbstractTissue< DIM >::CreateOutputFiles(), AbstractTissue< DIM >::GenerateCellResults(), CryptSimulation2d::OutputParameters(), AbstractTissue< DIM >::WriteCellResultsToFiles(), and AbstractTissue< DIM >::WriteResultsToFiles().
bool TissueConfig::GetOutputCellIdData ()
Returns:
mOutputCellIdData
Definition at line 333 of file TissueConfig.cpp.
References mOutputCellIdData.
Referenced by AbstractTissue< DIM >::CloseOutputFiles(), AbstractTissue< DIM >::CreateOutputFiles(), CryptSimulation2d::OutputParameters(), and AbstractTissue< DIM >::WriteResultsToFiles().
bool TissueConfig::GetOutputCellMutationStates ()
Returns:
mOutputCellMutationStates
Definition at line 337 of file TissueConfig.cpp.
References mOutputCellMutationStates.
Referenced by AbstractTissue< DIM >::CloseOutputFiles(), AbstractTissue< DIM >::CreateOutputFiles(), AbstractTissue< DIM >::GenerateCellResults(), CryptSimulation2d::OutputParameters(), AbstractTissue< DIM >::WriteCellResultsToFiles(), and AbstractTissue< DIM >::WriteResultsToFiles().
bool TissueConfig::GetOutputCellProliferativeTypes ()
Returns:
mOutputCellProliferativeTypes
Definition at line 345 of file TissueConfig.cpp.
References mOutputCellProliferativeTypes.
Referenced by AbstractTissue< DIM >::CloseOutputFiles(), AbstractTissue< DIM >::CreateOutputFiles(), AbstractTissue< DIM >::GenerateCellResults(), CryptSimulation2d::OutputParameters(), AbstractTissue< DIM >::WriteCellResultsToFiles(), and AbstractTissue< DIM >::WriteResultsToFiles().
bool TissueConfig::GetOutputCellVariables ()
Returns:
mOutputCellVariables
Definition at line 349 of file TissueConfig.cpp.
References mOutputCellVariables.
Referenced by AbstractTissue< DIM >::CloseOutputFiles(), AbstractTissue< DIM >::CreateOutputFiles(), AbstractTissue< DIM >::GenerateCellResults(), CryptSimulation2d::OutputParameters(), AbstractTissue< DIM >::WriteCellResultsToFiles(), and AbstractTissue< DIM >::WriteResultsToFiles().
bool TissueConfig::GetOutputNodeVelocities ()
Returns:
mOutputNodeVelocities
Definition at line 373 of file TissueConfig.cpp.
References mOutputNodeVelocities.
Referenced by CryptSimulation2d::OutputParameters().
bool TissueConfig::GetOutputTissueAreas ()
Returns:
mOutputTissueAreas
Definition at line 369 of file TissueConfig.cpp.
References mOutputTissueAreas.
Referenced by CryptSimulation2d::OutputParameters().
bool TissueConfig::GetOutputVoronoiData ()
Returns:
mOutputVoronoiData
Definition at line 365 of file TissueConfig.cpp.
References mOutputVoronoiData.
Referenced by CryptSimulation2d::OutputParameters().
double TissueConfig::GetSDuration ()
Returns:
mSDuration
Definition at line 193 of file TissueConfig.cpp.
References mSDuration.
Referenced by AbstractCellCycleModel::GetSDuration(), and CryptSimulation2d::OutputParameters().
double TissueConfig::GetSG2MDuration ()
Returns:
mSDuration + mG2Duration + mMDuration
Definition at line 189 of file TissueConfig.cpp.
References mG2Duration, mMDuration, and mSDuration.
Referenced by AbstractCellCycleModel::GetAverageStemCellCycleTime(), AbstractCellCycleModel::GetAverageTransitCellCycleTime(), and CryptSimulation2d::OutputParameters().
double TissueConfig::GetSpringStiffness ()
Returns:
mSpringStiffness
Definition at line 217 of file TissueConfig.cpp.
References mSpringStiffness.
Referenced by MeshBasedTissueWithGhostNodes< DIM >::CalculateForceBetweenNodes(), GeneralisedLinearSpringForce< DIM >::CalculateForceBetweenNodes(), CryptSimulation2d::OutputParameters(), and LinearSpringWithVariableSpringConstantsForce< DIM >::VariableSpringConstantMultiplicationFactor().
double TissueConfig::GetStemCellG1Duration ()
Returns:
mStemCellG1Duration
Definition at line 173 of file TissueConfig.cpp.
References mStemCellG1Duration.
Referenced by AbstractCellCycleModel::GetAverageStemCellCycleTime(), CryptSimulation2d::OutputParameters(), AbstractSimpleCellCycleModel::SetG1Duration(), and SimpleWntCellCycleModel::SetG1Duration().
double TissueConfig::GetSymmetricDivisionProbability ()
Returns:
mSymmetricDivisionProbability
Definition at line 297 of file TissueConfig.cpp.
References mSymmetricDivisionProbability.
Referenced by CryptSimulation2d::OutputParameters().
double TissueConfig::GetTransitCellG1Duration ()
Returns:
mTransitCellG1Duration
Definition at line 177 of file TissueConfig.cpp.
References mTransitCellG1Duration.
Referenced by AbstractCellCycleModel::GetAverageTransitCellCycleTime(), CryptSimulation2d::OutputParameters(), AbstractSimpleCellCycleModel::SetG1Duration(), and SimpleWntCellCycleModel::SetG1Duration().
double TissueConfig::GetWelikyOsterAreaParameter ()
Returns:
mWelikyOsterAreaParameter.
Definition at line 325 of file TissueConfig.cpp.
References mWelikyOsterAreaParameter.
Referenced by CryptSimulation2d::OutputParameters().
double TissueConfig::GetWelikyOsterPerimeterParameter ()
Returns:
mWelikyOsterPerimeterParameter.
Definition at line 329 of file TissueConfig.cpp.
References mWelikyOsterPerimeterParameter.
Referenced by CryptSimulation2d::OutputParameters().
double TissueConfig::GetWntChemotaxisStrength ()
Returns:
mWntChemotaxisStrength
Definition at line 293 of file TissueConfig.cpp.
References mWntChemotaxisStrength.
Referenced by CryptSimulation2d::OutputParameters().
double TissueConfig::GetWntConcentrationParameter ()
Returns:
mWntConcentrationParameter
Definition at line 269 of file TissueConfig.cpp.
References mWntConcentrationParameter.
Referenced by WntConcentration< DIM >::GetWntGradient(), WntConcentration< DIM >::GetWntLevel(), and CryptSimulation2d::OutputParameters().
double TissueConfig::GetWntLabelledThreshold ()
Returns:
mWntLabelledThreshold
Definition at line 265 of file TissueConfig.cpp.
References mWntLabelledThreshold.
Referenced by CryptSimulation2d::OutputParameters(), and SimpleWntCellCycleModel::UpdateCellCyclePhase().
double TissueConfig::GetWntStemThreshold ()
Returns:
mWntStemThreshold
Definition at line 261 of file TissueConfig.cpp.
References mWntStemThreshold.
Referenced by CryptSimulation2d::OutputParameters(), and SimpleWntCellCycleModel::UpdateCellCyclePhase().
double TissueConfig::GetWntTransitThreshold ()
Returns:
mWntTransitThreshold
Definition at line 257 of file TissueConfig.cpp.
References mWntTransitThreshold.
Referenced by CryptSimulation2d::OutputParameters(), and SimpleWntCellCycleModel::UpdateCellCyclePhase().
TissueConfig * TissueConfig::Instance () [static]
Call this method to access the global parameters holder.
Returns:
a single instance of the class
Definition at line 32 of file TissueConfig.cpp.
References mpInstance.
Referenced by TissueSimulation< DIM >::CalculateCellDivisionVector(), CryptSimulation2d::CalculateCellDivisionVector(), CryptSimulation1d::CalculateCellDivisionVector(), MeshBasedTissueWithGhostNodes< DIM >::CalculateForceBetweenNodes(), GeneralisedLinearSpringForce< DIM >::CalculateForceBetweenNodes(), CryptStatistics::CellIsInSectionPeriodic(), MeshBasedTissue< DIM >::CloseOutputFiles(), AbstractTissue< DIM >::CloseOutputFiles(), MeshBasedTissue< DIM >::CreateOutputFiles(), AbstractTissue< DIM >::CreateOutputFiles(), CryptSimulation1d::CryptSimulation1d(), AbstractTissue< DIM >::GenerateCellResults(), AbstractCellCycleModel::GetAverageStemCellCycleTime(), AbstractCellCycleModel::GetAverageTransitCellCycleTime(), AbstractTissue< DIM >::GetCellMutationStateCount(), CryptStatistics::GetCryptSection(), AbstractTwoBodyInteractionForce< DIM >::GetCutoffPoint(), MeshBasedTissue< DIM >::GetDampingConstant(), AbstractCellCentreBasedTissue< DIM >::GetDampingConstant(), AbstractCellCycleModel::GetG2Duration(), AbstractCellCycleModel::GetMDuration(), AbstractCellCycleModel::GetSDuration(), HoneycombMeshGenerator::HoneycombMeshGenerator(), AbstractSimpleGenerationBasedCellCycleModel::InitialiseDaughterCell(), CryptSimulation2d::OutputParameters(), AbstractSimpleGenerationBasedCellCycleModel::ResetForDivision(), AbstractTissue< DIM >::rGetCellCyclePhaseCount(), AbstractTissue< DIM >::rGetCellProliferativeTypeCount(), AbstractForce< DIM >::serialize(), AbstractCellCycleModel::serialize(), TissueSimulation< 2 >::serialize(), SloughingCellKiller< DIM >::serialize(), AbstractSimpleCellCycleModel::SetG1Duration(), SimpleWntCellCycleModel::SetG1Duration(), StochasticWntCellCycleModel::SetG2Duration(), AbstractCellBasedTestSuite::setUp(), TissueSimulation< DIM >::Solve(), TissueCell::StartApoptosis(), SloughingCellKiller< DIM >::TestAndLabelCellsForApoptosisOrDeath(), TissueSimulation< DIM >::TissueSimulation(), NodeBasedTissue< DIM >::Update(), MeshBasedTissue< DIM >::Update(), SimpleWntCellCycleModel::UpdateCellCyclePhase(), MeshBasedTissueWithGhostNodes< DIM >::UpdateGhostPositions(), TissueSimulation< DIM >::UpdateNodePositions(), AbstractTwoBodyInteractionForce< DIM >::UseCutoffPoint(), LinearSpringWithVariableSpringConstantsForce< DIM >::VariableSpringConstantMultiplicationFactor(), AbstractTissue< DIM >::WriteCellResultsToFiles(), MeshBasedTissue< DIM >::WriteResultsToFiles(), and AbstractTissue< DIM >::WriteResultsToFiles().
TissueConfig& TissueConfig::operator= (const TissueConfig &) [protected]
Overloaded assignment operator.
void TissueConfig::Reset ()
Reset all parameters to their defaults
mStemCellG1Duration has units of hours mTransitCellG1Duration has units of hours mHepaOneCellG1Duration has units of hours mMinimumGapDuration has units of hours mSDuration has units of hours mG2Duration has units of hours mMDuration has units of hours mMaxTransitGenerations has no units mCryptWidth has units of cell size at equilibrium rest length mCryptLength has units of cell size at equilibrium rest length mSpringStiffness has units of N/m = kg s^-2 mMechanicsCutOffLength has units of cell size at equilibrium rest length mDampingConstantNormal has units of kg s^-1 mDampingConstantMutant has units of kg s^-1 mBetaCatSpringScaler has no units mApoptosisTime has units of hours mDivisionRestingSpringLength has units of cell size at equilibrium rest length mDivisionSeparation has units of cell size at equilibrium rest length mHepaOneCellHypoxicConcentration has no units mHepaOneCellQuiescentConcentration has no units mWntTransitThreshold has no units mWntStemThreshold has no units mWntLabelledThreshold has no units mWntConcentrationParameter has no units (proportion of mCryptLength) mCriticalHypoxicDuration has units of hours mCryptProjectionParameterA has no units mCryptProjectionParameterB has no units mApoptoticSpringTensionStiffness has the same units as mSpringStiffness mApoptoticSpringCompressionStiffness has the same units as mSpringStiffness mWntChemotaxisStrength has no units mSymmetricDivisionProbability has no units mAreaBasedDampingConstantParameter has no units mMatureCellTargetArea has no units mDeformationEnergyParameter has ? units
Todo:
Fix this comment (see also #1294) mMembraneSurfaceEnergyParameter has ? units
Fix this comment (see also #1294) mCellCellAdhesionEnergyParameter has ? units
Fix this comment (see also #1294) mCellBoundaryAdhesionEnergyParameter has ? units
Fix this comment (see also #1294) mWelikyOsterAreaParameter has ? units
Fix this comment (see also #1294) mWelikyOsterPerimeterParameter has ? units
Fix this comment (see also #1294)
The following two parameters are used in vertex-based tissue simulations based on the mechanical model proposed by M. Weliky and G. Oster ("The mechanical basis of cell rearrangement. I. Epithelial morphogenesis during Fundulus epiboly", Development 109:373-386). Their default values are our estimates, since they are not given in the Weliky & Oster paper.
Definition at line 90 of file TissueConfig.cpp.
References mApoptosisTime, mApoptoticSpringCompressionStiffness, mApoptoticSpringTensionStiffness, mAreaBasedDampingConstantParameter, mBetaCatSpringScaler, mCellBoundaryAdhesionEnergyParameter, mCellCellAdhesionEnergyParameter, mCriticalHypoxicDuration, mCryptLength, mCryptProjectionParameterA, mCryptProjectionParameterB, mCryptWidth, mDampingConstantMutant, mDampingConstantNormal, mDeformationEnergyParameter, mDivisionRestingSpringLength, mDivisionSeparation, mG2Duration, mHepaOneCellG1Duration, mHepaOneCellHypoxicConcentration, mHepaOneCellQuiescentConcentration, mMatureCellTargetArea, mMaxTransitGenerations, mMDuration, mMechanicsCutOffLength, mMembraneSurfaceEnergyParameter, mMinimumGapDuration, mOutputCellAges, mOutputCellAncestors, mOutputCellAreas, mOutputCellCyclePhases, mOutputCellIdData, mOutputCellMutationStates, mOutputCellProliferativeTypes, mOutputCellVariables, mOutputNodeVelocities, mOutputTissueAreas, mOutputVoronoiData, mSDuration, mSpringStiffness, mStemCellG1Duration, mSymmetricDivisionProbability, mTransitCellG1Duration, mWelikyOsterAreaParameter, mWelikyOsterPerimeterParameter, mWntChemotaxisStrength, mWntConcentrationParameter, mWntLabelledThreshold, mWntStemThreshold, and mWntTransitThreshold.
Referenced by AbstractCellBasedTestSuite::setUp(), and TissueConfig().
template<class Archive > void TissueConfig::serialize (Archive & archive, const unsigned int version) [inline, private]
As with other singleton classes, ensure the instance of this class is serialized directly before being serialized via a pointer.
Parameters:
archive the archive
version the current version of this class
Definition at line 780 of file TissueConfig.hpp.
References mApoptosisTime, mApoptoticSpringCompressionStiffness, mApoptoticSpringTensionStiffness, mAreaBasedDampingConstantParameter, mBetaCatSpringScaler, mCellBoundaryAdhesionEnergyParameter, mCellCellAdhesionEnergyParameter, mCriticalHypoxicDuration, mCryptLength, mCryptProjectionParameterA, mCryptProjectionParameterB, mCryptWidth, mDampingConstantMutant, mDampingConstantNormal, mDeformationEnergyParameter, mG2Duration, mHepaOneCellG1Duration, mHepaOneCellHypoxicConcentration, mHepaOneCellQuiescentConcentration, mMatureCellTargetArea, mMaxTransitGenerations, mMDuration, mMechanicsCutOffLength, mMembraneSurfaceEnergyParameter, mMinimumGapDuration, mOutputCellAges, mOutputCellAncestors, mOutputCellAreas, mOutputCellCyclePhases, mOutputCellIdData, mOutputCellMutationStates, mOutputCellProliferativeTypes, mOutputCellVariables, mOutputNodeVelocities, mOutputTissueAreas, mOutputVoronoiData, mSDuration, mSpringStiffness, mStemCellG1Duration, mSymmetricDivisionProbability, mTransitCellG1Duration, mWelikyOsterAreaParameter, mWelikyOsterPerimeterParameter, mWntChemotaxisStrength, mWntConcentrationParameter, mWntLabelledThreshold, mWntStemThreshold, and mWntTransitThreshold.
void TissueConfig::SetApoptosisTime (double apoptosisTime)
Set mApoptosisTime.
Definition at line 457 of file TissueConfig.cpp.
References mApoptosisTime.
void TissueConfig::SetApoptoticSpringCompressionStiffness (double apoptoticSpringCompressionStiffness)
Set mApoptoticSpringCompressionStiffness.
Definition at line 535 of file TissueConfig.cpp.
References mApoptoticSpringCompressionStiffness.
void TissueConfig::SetApoptoticSpringTensionStiffness (double apoptoticSpringTensionStiffness)
Set mApoptoticSpringTensionStiffness.
Definition at line 530 of file TissueConfig.cpp.
References mApoptoticSpringTensionStiffness.
void TissueConfig::SetAreaBasedDampingConstantParameter (double areaBasedDampingConstantParameter)
Set mAreaBasedDampingConstantParameter.
Definition at line 551 of file TissueConfig.cpp.
References mAreaBasedDampingConstantParameter.
void TissueConfig::SetBetaCatSpringScaler (double betaCatSpringScaler)
Set mBetaCatSpringScaler.
Definition at line 452 of file TissueConfig.cpp.
References mBetaCatSpringScaler.
void TissueConfig::SetCellBoundaryAdhesionEnergyParameter (double cellBoundaryAdhesionEnergyParameter)
Set mCellBoundaryAdhesionEnergyParameter.
Definition at line 573 of file TissueConfig.cpp.
References mCellBoundaryAdhesionEnergyParameter.
void TissueConfig::SetCellCellAdhesionEnergyParameter (double cellCellAdhesionEnergyParameter)
Set mCellCellAdhesionEnergyParameter.
Definition at line 569 of file TissueConfig.cpp.
References mCellCellAdhesionEnergyParameter.
void TissueConfig::SetCriticalHypoxicDuration (double criticalHypoxicDuration)
Set mCriticalHypoxicDuration.
Definition at line 511 of file TissueConfig.cpp.
References mCriticalHypoxicDuration.
void TissueConfig::SetCryptLength (double cryptLength)
Set mCryptLength.
Definition at line 421 of file TissueConfig.cpp.
References mCryptLength.
Referenced by HoneycombMeshGenerator::HoneycombMeshGenerator().
void TissueConfig::SetCryptProjectionParameterA (double cryptProjectionParameterA)
Set mCryptProjectionParameterA.
Definition at line 520 of file TissueConfig.cpp.
References mCryptProjectionParameterA.
void TissueConfig::SetCryptProjectionParameterB (double cryptProjectionParameterB)
Set mCryptProjectionParameterB.
Definition at line 525 of file TissueConfig.cpp.
References mCryptProjectionParameterB.
void TissueConfig::SetCryptWidth (double cryptWidth)
Set mCryptWidth.
Definition at line 426 of file TissueConfig.cpp.
References mCryptWidth.
Referenced by HoneycombMeshGenerator::HoneycombMeshGenerator().
void TissueConfig::SetDampingConstantMutant (double dampingConstantMutant)
Set mDampingConstantMutant.
Definition at line 447 of file TissueConfig.cpp.
References mDampingConstantMutant.
void TissueConfig::SetDampingConstantNormal (double dampingConstantNormal)
Set mDampingConstantNormal.
Definition at line 442 of file TissueConfig.cpp.
References mDampingConstantNormal.
void TissueConfig::SetDeformationEnergyParameter (double deformationEnergyParameter)
Set mDeformationEnergyParameter.
Definition at line 561 of file TissueConfig.cpp.
References mDeformationEnergyParameter.
void TissueConfig::SetDivisionRestingSpringLength (double divisionRestingSpringLength)
Set mDivisionRestingSpringLength.
Definition at line 462 of file TissueConfig.cpp.
References mDivisionRestingSpringLength.
void TissueConfig::SetDivisionSeparation (double divisionSeparation)
Set mDivisionSeparation.
Definition at line 469 of file TissueConfig.cpp.
References mDivisionSeparation.
void TissueConfig::SetG2Duration (double G2Duration)
Set mG2Duration.
Definition at line 407 of file TissueConfig.cpp.
References mG2Duration.
void TissueConfig::SetHepaOneCellG1Duration (double hepaOneCellG1Duration)
Set mHepaOneCellG1Duration.
Definition at line 392 of file TissueConfig.cpp.
References mHepaOneCellG1Duration.
void TissueConfig::SetHepaOneCellHypoxicConcentration (double hepaOneCellHypoxicConcentration)
Set mHepaOneCellHypoxicConcentration.
Definition at line 475 of file TissueConfig.cpp.
References mHepaOneCellHypoxicConcentration.
void TissueConfig::SetHepaOneCellQuiescentConcentration (double hepaOneCellQuiescentConcentration)
Set mHepaOneCellQuiescentConcentration.
Definition at line 481 of file TissueConfig.cpp.
References mHepaOneCellQuiescentConcentration.
void TissueConfig::SetHepaOneParameters ()
Set mHepaOneParameters.
Definition at line 516 of file TissueConfig.cpp.
References mHepaOneCellG1Duration, and mStemCellG1Duration.
void TissueConfig::SetMatureCellTargetArea (double matureCellTargetArea)
Set mMatureCellTargetArea.
Definition at line 556 of file TissueConfig.cpp.
References mMatureCellTargetArea.
void TissueConfig::SetMaxTransitGenerations (unsigned maxTransitGens)
Set mMaxTransitGenerations.
Definition at line 417 of file TissueConfig.cpp.
References mMaxTransitGenerations.
void TissueConfig::SetMDuration (double MDuration)
Set mMDuration.
Definition at line 412 of file TissueConfig.cpp.
References mMDuration.
void TissueConfig::SetMechanicsCutOffLength (double mechanicsCutOffLength)
Set mMechanicsCutOffLength.
Definition at line 436 of file TissueConfig.cpp.
References mMechanicsCutOffLength.
Referenced by AbstractTwoBodyInteractionForce< DIM >::UseCutoffPoint().
void TissueConfig::SetMembraneSurfaceEnergyParameter (double membraneSurfaceEnergyParameter)
Set mMembraneSurfaceEnergyParameter.
Definition at line 565 of file TissueConfig.cpp.
References mMembraneSurfaceEnergyParameter.
void TissueConfig::SetMinimumGapDuration (double minimumGapDuration)
Set mMinimumGapDuration.
Definition at line 397 of file TissueConfig.cpp.
References mMinimumGapDuration.
void TissueConfig::SetOutputCellAges (bool outputCellAges)
Set mOutputCellAges.
Definition at line 609 of file TissueConfig.cpp.
References mOutputCellAges.
void TissueConfig::SetOutputCellAncestors (bool outputCellAncestors)
Set mOutputCellAncestors.
Definition at line 593 of file TissueConfig.cpp.
References mOutputCellAncestors.
void TissueConfig::SetOutputCellAreas (bool outputCellAreas)
Set mOutputCellAreas.
Definition at line 613 of file TissueConfig.cpp.
References mOutputCellAreas.
void TissueConfig::SetOutputCellCyclePhases (bool outputCellCyclePhases)
Set mOutputCellCyclePhases.
Definition at line 605 of file TissueConfig.cpp.
References mOutputCellCyclePhases.
void TissueConfig::SetOutputCellIdData (bool writeCellIdData)
Set mOutputCellIdData.
Definition at line 585 of file TissueConfig.cpp.
References mOutputCellIdData.
void TissueConfig::SetOutputCellMutationStates (bool outputCellMutationStates)
Set mOutputCellMutationStates.
Definition at line 589 of file TissueConfig.cpp.
References mOutputCellMutationStates.
void TissueConfig::SetOutputCellProliferativeTypes (bool outputCellProliferativeTypes)
Set mOutputCellProliferativeTypes.
Definition at line 597 of file TissueConfig.cpp.
References mOutputCellProliferativeTypes.
void TissueConfig::SetOutputCellVariables (bool outputCellVariables)
Set mOutputCellVariables.
Definition at line 601 of file TissueConfig.cpp.
References mOutputCellVariables.
void TissueConfig::SetOutputNodeVelocities (bool outputNodeVelocities)
Set mOutputNodeVelocities.
Definition at line 625 of file TissueConfig.cpp.
References mOutputNodeVelocities.
void TissueConfig::SetOutputTissueAreas (bool outputTissueAreas)
Set mOutputTissueAreas.
Definition at line 621 of file TissueConfig.cpp.
References mOutputTissueAreas.
void TissueConfig::SetOutputVoronoiData (bool outputVoronoiData)
Set mOutputVoronoiData.
Definition at line 617 of file TissueConfig.cpp.
References mOutputVoronoiData.
void TissueConfig::SetSDuration (double SDuration)
Set mSDuration.
Definition at line 402 of file TissueConfig.cpp.
References mSDuration.
void TissueConfig::SetSpringStiffness (double springStiffness)
Set mSpringStiffness.
Definition at line 431 of file TissueConfig.cpp.
References mSpringStiffness.
Referenced by CryptSimulation1d::CryptSimulation1d().
void TissueConfig::SetStemCellG1Duration (double stemCellG1Duration)
Set mStemCellG1Duration.
Definition at line 382 of file TissueConfig.cpp.
References mStemCellG1Duration.
void TissueConfig::SetSymmetricDivisionProbability (double symmetricDivisionProbability)
Set mSymmetricDivisionProbability.
Definition at line 545 of file TissueConfig.cpp.
References mSymmetricDivisionProbability.
void TissueConfig::SetTransitCellG1Duration (double transitCellG1Duration)
Set mTransitCellG1Duration.
Definition at line 387 of file TissueConfig.cpp.
References mTransitCellG1Duration.
void TissueConfig::SetWelikyOsterAreaParameter (double welikyOsterAreaParameter)
Set mWelikyOsterAreaParameter.
Definition at line 577 of file TissueConfig.cpp.
References mWelikyOsterAreaParameter.
void TissueConfig::SetWelikyOsterPerimeterParameter (double welikyOsterPerimeterParameter)
Set mWelikyOsterPerimeterParameter.
Definition at line 581 of file TissueConfig.cpp.
References mWelikyOsterPerimeterParameter.
void TissueConfig::SetWntChemotaxisStrength (double wntChemotaxisStrength)
Set mWntChemotaxisStrength.
Definition at line 540 of file TissueConfig.cpp.
References mWntChemotaxisStrength.
void TissueConfig::SetWntConcentrationParameter (double top)
Set mWntConcentrationParameter.
Definition at line 505 of file TissueConfig.cpp.
References mWntConcentrationParameter.
void TissueConfig::SetWntLabelledThreshold (double wntThreshold)
Set mWntLabelledThreshold.
Definition at line 499 of file TissueConfig.cpp.
References mWntLabelledThreshold.
void TissueConfig::SetWntStemThreshold (double wntThreshold)
Set mWntStemThreshold.
Definition at line 493 of file TissueConfig.cpp.
References mWntStemThreshold.
void TissueConfig::SetWntTransitThreshold (double wntThreshold)
Set mWntTransitThreshold.
Definition at line 487 of file TissueConfig.cpp.
References mWntTransitThreshold.
Friends And Related Function Documentation
friend class boost::serialization::access [friend]
Needed for serialization.
Definition at line 770 of file TissueConfig.hpp.
Member Data Documentation
double TissueConfig::mApoptosisTime [private]
The time it takes for a cell to fully undergo apoptosis
Definition at line 587 of file TissueConfig.hpp.
Referenced by GetApoptosisTime(), Reset(), serialize(), and SetApoptosisTime().
double TissueConfig::mApoptoticSpringCompressionStiffness [private]
Non-dimensionalized 'stiffness' of a apoptotic cell under compression.
Definition at line 666 of file TissueConfig.hpp.
Referenced by GetApoptoticSpringCompressionStiffness(), Reset(), serialize(), and SetApoptoticSpringCompressionStiffness().
double TissueConfig::mApoptoticSpringTensionStiffness [private]
Non-dimensionalized 'stiffness' of a apoptotic cell under tension.
Definition at line 661 of file TissueConfig.hpp.
Referenced by GetApoptoticSpringTensionStiffness(), Reset(), serialize(), and SetApoptoticSpringTensionStiffness().
double TissueConfig::mAreaBasedDampingConstantParameter [private]
Non-dimensional parameter d0 for use in area-based damping constant calculations.
Definition at line 681 of file TissueConfig.hpp.
Referenced by GetAreaBasedDampingConstantParameter(), Reset(), serialize(), and SetAreaBasedDampingConstantParameter().
double TissueConfig::mBetaCatSpringScaler [private]
Scaling factor for beta catenin to spring strength
Definition at line 582 of file TissueConfig.hpp.
Referenced by GetBetaCatSpringScaler(), Reset(), serialize(), and SetBetaCatSpringScaler().
double TissueConfig::mCellBoundaryAdhesionEnergyParameter [private]
Cell-boundary adhesion energy parameter. For use in Nagai and Honda type vertex-based models.
Definition at line 711 of file TissueConfig.hpp.
Referenced by GetCellBoundaryAdhesionEnergyParameter(), Reset(), serialize(), and SetCellBoundaryAdhesionEnergyParameter().
double TissueConfig::mCellCellAdhesionEnergyParameter [private]
Cell-cell adhesion energy parameter. For use in Nagai and Honda type vertex-based models.
Definition at line 705 of file TissueConfig.hpp.
Referenced by GetCellCellAdhesionEnergyParameter(), Reset(), serialize(), and SetCellCellAdhesionEnergyParameter().
double TissueConfig::mCriticalHypoxicDuration [private]
Non-dimensionalized critical hypoxic duration.
Definition at line 644 of file TissueConfig.hpp.
Referenced by GetCriticalHypoxicDuration(), Reset(), serialize(), and SetCriticalHypoxicDuration().
double TissueConfig::mCryptLength [private]
The length of the crypt, non-dimensionalised with cell length. This parameter determines when cells are sloughed from the crypt.
Definition at line 543 of file TissueConfig.hpp.
Referenced by GetCryptLength(), Reset(), serialize(), and SetCryptLength().
double TissueConfig::mCryptProjectionParameterA [private]
Parameter a, for use in crypt projection simulations, in which the crypt surface is given in cylindrical polar coordinates by z = a*r^b.
Definition at line 650 of file TissueConfig.hpp.
Referenced by GetCryptProjectionParameterA(), Reset(), serialize(), and SetCryptProjectionParameterA().
double TissueConfig::mCryptProjectionParameterB [private]
Parameter b, for use in crypt projection simulations, in which the crypt surface is given in cylindrical polar coordinates by z = a*r^b.
Definition at line 656 of file TissueConfig.hpp.
Referenced by GetCryptProjectionParameterB(), Reset(), serialize(), and SetCryptProjectionParameterB().
double TissueConfig::mCryptWidth [private]
The width of the crypt, non-dimensionalised with cell length. This determines when cells are sloughed from the crypt in 2D.
Definition at line 549 of file TissueConfig.hpp.
Referenced by GetCryptWidth(), Reset(), serialize(), and SetCryptWidth().
double TissueConfig::mDampingConstantMutant [private]
Damping constant for mutant cells.
Definition at line 577 of file TissueConfig.hpp.
Referenced by GetDampingConstantMutant(), Reset(), serialize(), and SetDampingConstantMutant().
double TissueConfig::mDampingConstantNormal [private]
Damping constant for normal cells. Represented by the parameter eta in the model by Meineke et al (2001) in their off-lattice model of the intestinal crypt (doi:10.1046/j.0960-7722.2001.00216.x).
Definition at line 572 of file TissueConfig.hpp.
Referenced by GetDampingConstantNormal(), Reset(), serialize(), and SetDampingConstantNormal().
double TissueConfig::mDeformationEnergyParameter [private]
Cell deformation energy parameter. For use in Nagai and Honda type vertex-based models.
Definition at line 693 of file TissueConfig.hpp.
Referenced by GetDeformationEnergyParameter(), Reset(), serialize(), and SetDeformationEnergyParameter().
double TissueConfig::mDivisionRestingSpringLength [private]
Initial resting spring length after cell division. The value of thiis parameter should be larger than mDivisionSeparation, because of pressure from neighbouring springs.
Definition at line 599 of file TissueConfig.hpp.
Referenced by GetDivisionRestingSpringLength(), Reset(), and SetDivisionRestingSpringLength().
double TissueConfig::mDivisionSeparation [private]
Initial separation placement of mother/daughter cells at birth
Definition at line 592 of file TissueConfig.hpp.
Referenced by GetDivisionSeparation(), Reset(), and SetDivisionSeparation().
double TissueConfig::mG2Duration [private]
Duration of G2 phase for all cell types.
Definition at line 527 of file TissueConfig.hpp.
Referenced by GetG2Duration(), GetSG2MDuration(), Reset(), serialize(), and SetG2Duration().
double TissueConfig::mHepaOneCellG1Duration [private]
Duration of G1 phase for HEPA-1 cells, for use in monolayer/spheroid simulations. May be used as a mean duration for stochastic cell cycle models.
Definition at line 510 of file TissueConfig.hpp.
Referenced by GetHepaOneCellG1Duration(), Reset(), serialize(), SetHepaOneCellG1Duration(), and SetHepaOneParameters().
double TissueConfig::mHepaOneCellHypoxicConcentration [private]
Non-dimensionalized oxygen concentration below which HEPA-1 cells are considered to be hypoxic. A prolonged period of hypoxia causes the cell to become apoptotic.
Definition at line 606 of file TissueConfig.hpp.
Referenced by GetHepaOneCellHypoxicConcentration(), Reset(), serialize(), and SetHepaOneCellHypoxicConcentration().
double TissueConfig::mHepaOneCellQuiescentConcentration [private]
Non-dimensionalized oxygen concentration below which HEPA-1 cells are considered to be quiescent and slow their progress through the G1 phase of the cell cycle.
Definition at line 613 of file TissueConfig.hpp.
Referenced by GetHepaOneCellQuiescentConcentration(), Reset(), serialize(), and SetHepaOneCellQuiescentConcentration().
double TissueConfig::mMatureCellTargetArea [private]
Non-dimensional target area of a mature (fully-grown) TissueCell. For use in vertex-based models.
Definition at line 687 of file TissueConfig.hpp.
Referenced by GetMatureCellTargetArea(), Reset(), serialize(), and SetMatureCellTargetArea().
unsigned TissueConfig::mMaxTransitGenerations [private]
How many generations a transit cell lives for before becoming fully differentiated.
Definition at line 537 of file TissueConfig.hpp.
Referenced by GetMaxTransitGenerations(), Reset(), serialize(), and SetMaxTransitGenerations().
double TissueConfig::mMDuration [private]
Duration of M phase for all cell types.
Definition at line 532 of file TissueConfig.hpp.
Referenced by GetMDuration(), GetSG2MDuration(), Reset(), serialize(), and SetMDuration().
double TissueConfig::mMechanicsCutOffLength [private]
Mechanics cut off length. Used in NodeBasedTissue.
Definition at line 564 of file TissueConfig.hpp.
Referenced by GetMechanicsCutOffLength(), Reset(), serialize(), and SetMechanicsCutOffLength().
double TissueConfig::mMembraneSurfaceEnergyParameter [private]
Cell membrane energy parameter. For use in Nagai and Honda type vertex-based models.
Definition at line 699 of file TissueConfig.hpp.
Referenced by GetMembraneSurfaceEnergyParameter(), Reset(), serialize(), and SetMembraneSurfaceEnergyParameter().
double TissueConfig::mMinimumGapDuration [private]
Minimum possbile duration of either of the gap phases (G1 or G2). Used to guarantee a strictly positive duration in cell cycle models that use normal random deviates for G1 or G2 phases.
Definition at line 517 of file TissueConfig.hpp.
Referenced by GetMinimumGapDuration(), Reset(), serialize(), and SetMinimumGapDuration().
bool TissueConfig::mOutputCellAges [private]
Whether to write the cell ages to a file.
Definition at line 755 of file TissueConfig.hpp.
Referenced by GetOutputCellAges(), Reset(), serialize(), and SetOutputCellAges().
bool TissueConfig::mOutputCellAncestors [private]
Whether to output the ancestor of each cell to a visualizer file.
Definition at line 738 of file TissueConfig.hpp.
Referenced by GetOutputCellAncestors(), Reset(), serialize(), and SetOutputCellAncestors().
bool TissueConfig::mOutputCellAreas [private]
Whether to write the cell areas to a file.
Definition at line 758 of file TissueConfig.hpp.
Referenced by GetOutputCellAreas(), Reset(), serialize(), and SetOutputCellAreas().
bool TissueConfig::mOutputCellCyclePhases [private]
Whether to write the cell cycle phases to a file.
Definition at line 752 of file TissueConfig.hpp.
Referenced by GetOutputCellCyclePhases(), Reset(), serialize(), and SetOutputCellCyclePhases().
bool TissueConfig::mOutputCellIdData [private]
Whether to write cell ID data to file.
Definition at line 726 of file TissueConfig.hpp.
Referenced by GetOutputCellIdData(), Reset(), serialize(), and SetOutputCellIdData().
bool TissueConfig::mOutputCellMutationStates [private]
Whether to count the number of each cell mutation state and output to file.
Definition at line 732 of file TissueConfig.hpp.
Referenced by GetOutputCellMutationStates(), Reset(), serialize(), and SetOutputCellMutationStates().
bool TissueConfig::mOutputCellProliferativeTypes [private]
Whether to count the number of each cell type and output to file.
Definition at line 744 of file TissueConfig.hpp.
Referenced by GetOutputCellProliferativeTypes(), Reset(), serialize(), and SetOutputCellProliferativeTypes().
bool TissueConfig::mOutputCellVariables [private]
Whether to write the cell variables to a file.
Definition at line 749 of file TissueConfig.hpp.
Referenced by GetOutputCellVariables(), Reset(), serialize(), and SetOutputCellVariables().
bool TissueConfig::mOutputNodeVelocities [private]
Whether to write the node velocities to a file.
Definition at line 767 of file TissueConfig.hpp.
Referenced by GetOutputNodeVelocities(), Reset(), serialize(), and SetOutputNodeVelocities().
bool TissueConfig::mOutputTissueAreas [private]
Whether to write the tissue areas to file.
Definition at line 764 of file TissueConfig.hpp.
Referenced by GetOutputTissueAreas(), Reset(), serialize(), and SetOutputTissueAreas().
bool TissueConfig::mOutputVoronoiData [private]
Whether to write cell area and perimeter information to file.
Definition at line 761 of file TissueConfig.hpp.
Referenced by GetOutputVoronoiData(), Reset(), serialize(), and SetOutputVoronoiData().
TissueConfig * TissueConfig::mpInstance = NULL [static, private]
The single instance of the class
Definition at line 491 of file TissueConfig.hpp.
Referenced by Instance(), and TissueConfig().
double TissueConfig::mSDuration [private]
Duration of S phase for all cell types.
Definition at line 522 of file TissueConfig.hpp.
Referenced by GetSDuration(), GetSG2MDuration(), Reset(), serialize(), and SetSDuration().
double TissueConfig::mSpringStiffness [private]
Spring stiffness.
Represented by the parameter mu in the model by Meineke et al (2001) in their off-lattice model of the intestinal crypt (doi:10.1046/j.0960-7722.2001.00216.x).
Definition at line 558 of file TissueConfig.hpp.
Referenced by GetSpringStiffness(), Reset(), serialize(), and SetSpringStiffness().
double TissueConfig::mStemCellG1Duration [private]
Duration of G1 phase for stem cells. May be used as a mean duration for stochastic cell cycle models.
Definition at line 498 of file TissueConfig.hpp.
Referenced by GetStemCellG1Duration(), Reset(), serialize(), SetHepaOneParameters(), and SetStemCellG1Duration().
double TissueConfig::mSymmetricDivisionProbability [private]
Probability of symmetric division.
Definition at line 676 of file TissueConfig.hpp.
Referenced by GetSymmetricDivisionProbability(), Reset(), serialize(), and SetSymmetricDivisionProbability().
double TissueConfig::mTransitCellG1Duration [private]
Duration of G1 phase for transit cells. May be used as a mean duration for stochastic cell cycle models.
Definition at line 504 of file TissueConfig.hpp.
Referenced by GetTransitCellG1Duration(), Reset(), serialize(), and SetTransitCellG1Duration().
double TissueConfig::mWelikyOsterAreaParameter [private]
Area parameter. For use in Weliky and Oster type vertex-based models.
Definition at line 717 of file TissueConfig.hpp.
Referenced by GetWelikyOsterAreaParameter(), Reset(), serialize(), and SetWelikyOsterAreaParameter().
double TissueConfig::mWelikyOsterPerimeterParameter [private]
Perimeter parameter. For use in Weliky and Oster type vertex-based models.
Definition at line 723 of file TissueConfig.hpp.
Referenced by GetWelikyOsterPerimeterParameter(), Reset(), serialize(), and SetWelikyOsterPerimeterParameter().
double TissueConfig::mWntChemotaxisStrength [private]
Strength of Wnt-based chemotactic force.
Definition at line 671 of file TissueConfig.hpp.
Referenced by GetWntChemotaxisStrength(), Reset(), serialize(), and SetWntChemotaxisStrength().
double TissueConfig::mWntConcentrationParameter [private]
For LINEAR or RADIAL The proportion of the crypt that has a Wnt gradient. The Wnt concentration goes from one at the base to zero at this height up the crypt.
For EXPONENTIAL The parameter lambda in the Wnt concentration Wnt = exp (- height / lambda)
Definition at line 639 of file TissueConfig.hpp.
Referenced by GetWntConcentrationParameter(), Reset(), serialize(), and SetWntConcentrationParameter().
double TissueConfig::mWntLabelledThreshold [private]
Non-dimensionalized Wnt threshold, above which labelled cells progress through the cell cycle.
Definition at line 628 of file TissueConfig.hpp.
Referenced by GetWntLabelledThreshold(), Reset(), serialize(), and SetWntLabelledThreshold().
double TissueConfig::mWntStemThreshold [private]
Non-dimensionalized Wnt threshold, above which cells behave as stem cells.
Definition at line 623 of file TissueConfig.hpp.
Referenced by GetWntStemThreshold(), Reset(), serialize(), and SetWntStemThreshold().
double TissueConfig::mWntTransitThreshold [private]
Non-dimensionalized Wnt threshold, above which cells progress through the cell cycle.
Definition at line 618 of file TissueConfig.hpp.
Referenced by GetWntTransitThreshold(), Reset(), serialize(), and SetWntTransitThreshold().
The documentation for this class was generated from the following files:
/tmp/release_2.0/cell_based/src/common/TissueConfig.hpp
/tmp/release_2.0/cell_based/src/common/TissueConfig.cpp