Chaste: FoxModel2002Modified Class Reference
FoxModel2002Modified Class Reference
#include <FoxModel2002Modified.hpp>
Inherits AbstractCardiacCell.
Public Member Functions
FoxModel2002Modified (boost::shared_ptr< AbstractIvpOdeSolver > pSolver, boost::shared_ptr< AbstractStimulusFunction > pIntracellularStimulus)
~FoxModel2002Modified (void)
double GetIIonic ()
void EvaluateYDerivatives (double var_environment__time, const std::vector< double > &rY, std::vector< double > &rDY)
Detailed Description
Generated from CellML, and P_Ca parameter modified.
Definition at line 24 of file FoxModel2002Modified.hpp.
Constructor & Destructor Documentation
FoxModel2002Modified::FoxModel2002Modified (boost::shared_ptr< AbstractIvpOdeSolver > pSolver, boost::shared_ptr< AbstractStimulusFunction > pIntracellularStimulus)
Constructor
Parameters:
pSolver is a pointer to the ODE solver
pIntracellularStimulus is a pointer to the intracellular stimulus
Generated from CellML, and P_Ca parameter modified.
Definition at line 24 of file FoxModel2002Modified.cpp.
References AbstractCardiacCell::Init(), and AbstractOdeSystem::mpSystemInfo.
FoxModel2002Modified::~FoxModel2002Modified (void)
Destructor
Definition at line 34 of file FoxModel2002Modified.cpp.
Member Function Documentation
void FoxModel2002Modified::EvaluateYDerivatives (double var_environment__time, const std::vector< double > & rY, std::vector< double > & rDY) [virtual]
Evaluate the derivatives of the state variables
Parameters:
var_Environment__time the current time, in milliseconds
rY current values of the state variables
rDY to be filled in with derivatives
Implements AbstractOdeSystem.
Definition at line 218 of file FoxModel2002Modified.cpp.
References AbstractOdeSystem::DumpState(), AbstractCardiacCell::GetStimulus(), AbstractCardiacCell::mSetVoltageDerivativeToZero, and AbstractOdeSystem::rGetVariableNames().
double FoxModel2002Modified::GetIIonic () [virtual]
Calculates the ionic current
Returns:
the total ionic current
Implements AbstractCardiacCell.
Definition at line 39 of file FoxModel2002Modified.cpp.
References AbstractOdeSystem::rGetStateVariables().
The documentation for this class was generated from the following files:
/tmp/release_2.0/heart/src/odes/ionicmodels/FoxModel2002Modified.hpp
/tmp/release_2.0/heart/src/odes/ionicmodels/FoxModel2002Modified.cpp