Chaste: BackwardEulerMahajanModel2008 Class Reference
BackwardEulerMahajanModel2008 Class Reference
Inherits AbstractBackwardEulerCardiacCell< 15 >.
Public Member Functions
BackwardEulerMahajanModel2008 (boost::shared_ptr< AbstractIvpOdeSolver >, boost::shared_ptr< AbstractStimulusFunction > pIntracellularStimulus)
void VerifyStateVariables ()
double GetIIonic ()
void ComputeResidual (double var_environment__time, const double rCurrentGuess[15], double rResidual[15])
void ComputeJacobian (double var_environment__time, const double rCurrentGuess[15], double rJacobian[15][15])
void UpdateTransmembranePotential (double var_Environment__time)
void ComputeOneStepExceptVoltage (double var_Environment__time)
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Friends
class boost::serialization::access
Detailed Description
Definition at line 21 of file BackwardEulerMahajanModel2008.hpp.
Member Function Documentation
void BackwardEulerMahajanModel2008::ComputeOneStepExceptVoltage (double tStart) [virtual]
Compute the values of all state variables, except the voltage, using backward Euler, for one timestep from tStart.
Note:
This method must be provided by subclasses.
Parameters:
tStart start of this timestep
Implements AbstractBackwardEulerCardiacCell< 15 >.
Definition at line 879 of file BackwardEulerMahajanModel2008.cpp.
References AbstractCardiacCell::mDt, AbstractOdeSystem::rGetStateVariables(), and CardiacNewtonSolver< SIZE >::Solve().
double BackwardEulerMahajanModel2008::GetIIonic () [virtual]
Computes the total current flowing through the cell membrane, using the current values of the state variables.
Implements AbstractCardiacCell.
Definition at line 40 of file BackwardEulerMahajanModel2008.cpp.
References AbstractOdeSystem::rGetStateVariables().
template<class Archive > void BackwardEulerMahajanModel2008::serialize (Archive & archive, const unsigned int version) [inline, private]
Archive the member variables.
Parameters:
archive
version
Reimplemented from AbstractBackwardEulerCardiacCell< 15 >.
Definition at line 25 of file BackwardEulerMahajanModel2008.hpp.
void BackwardEulerMahajanModel2008::UpdateTransmembranePotential (double time) [virtual]
Perform a forward Euler step to update the transmembrane potential.
Note:
This method must be provided by subclasses.
Parameters:
time start of this timestep
Implements AbstractBackwardEulerCardiacCell< 15 >.
Definition at line 710 of file BackwardEulerMahajanModel2008.cpp.
References AbstractCardiacCell::GetStimulus(), AbstractCardiacCell::mDt, and AbstractOdeSystem::rGetStateVariables().
void BackwardEulerMahajanModel2008::VerifyStateVariables () [virtual]
Empty method which can be over-ridden in concrete cell class which should go through the current state vector and go range checking on the values (eg check that concentrations are positive and gating variables are between zero and one). This method is called in the ComputeExceptVoltage method.
Reimplemented from AbstractCardiacCell.
Definition at line 37 of file BackwardEulerMahajanModel2008.cpp.
Friends And Related Function Documentation
friend class boost::serialization::access [friend]
Needed for serialization.
Reimplemented from AbstractBackwardEulerCardiacCell< 15 >.
Definition at line 23 of file BackwardEulerMahajanModel2008.hpp.
The documentation for this class was generated from the following files:
/tmp/release_2.0/heart/src/odes/ionicmodels/BackwardEulerMahajanModel2008.hpp
/tmp/release_2.0/heart/src/odes/ionicmodels/BackwardEulerMahajanModel2008.cpp