Chaste: DifferentialAdhesionPottsUpdateRule< DIM > Class Template Reference
DifferentialAdhesionPottsUpdateRule< DIM > Class Template Reference
#include <DifferentialAdhesionPottsUpdateRule.hpp>
Inherits AdhesionPottsUpdateRule< DIM >.
Public Member Functions
DifferentialAdhesionPottsUpdateRule ()
~DifferentialAdhesionPottsUpdateRule ()
virtual double GetCellCellAdhesionEnergy (CellPtr pCellA, CellPtr pCellB)
virtual double GetCellBoundaryAdhesionEnergy (CellPtr pCell)
double GetLabelledCellLabelledCellAdhesionEnergyParameter ()
double GetLabelledCellCellAdhesionEnergyParameter ()
double GetLabelledCellBoundaryAdhesionEnergyParameter ()
void SetLabelledCellLabelledCellAdhesionEnergyParameter (double labelledCellLabelledCellAdhesionEnergyParameter)
void SetLabelledCellCellAdhesionEnergyParameter (double labelledCellCellAdhesionEnergyParameter)
void SetLabelledCellBoundaryAdhesionEnergyParameter (double labelledCellBoundaryAdhesionEnergyParameter)
void OutputUpdateRuleParameters (out_stream &rParamsFile)
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Private Attributes
double mLabelledCellLabelledCellAdhesionEnergyParameter
double mLabelledCellCellAdhesionEnergyParameter
double mLabelledCellBoundaryAdhesionEnergyParameter
Friends
class TestPottsUpdateRules
class boost::serialization::access
Detailed Description
template<unsigned DIM>
class DifferentialAdhesionPottsUpdateRule< DIM >
An adhesion update rule for use in cell-based simulations using the cellular Potts model. This rule implements differential adhesion between unlabelled and labelled cells
Definition at line 46 of file DifferentialAdhesionPottsUpdateRule.hpp.
Constructor & Destructor Documentation
template<unsigned DIM> DifferentialAdhesionPottsUpdateRule< DIM >::DifferentialAdhesionPottsUpdateRule () [inline]
Constructor.
Definition at line 32 of file DifferentialAdhesionPottsUpdateRule.cpp.
template<unsigned DIM> DifferentialAdhesionPottsUpdateRule< DIM >::~DifferentialAdhesionPottsUpdateRule () [inline]
Destructor.
Definition at line 41 of file DifferentialAdhesionPottsUpdateRule.cpp.
Member Function Documentation
template<unsigned DIM> double DifferentialAdhesionPottsUpdateRule< DIM >::GetCellBoundaryAdhesionEnergy (CellPtr pCell) [inline, virtual]
Overridden GetCellBoundaryAdhesionEnergy method to implement differential adhesion.
Parameters:
pCell pointer to the cell
Returns:
Cell boundary interaction adhesion energy for the cell
Reimplemented from AdhesionPottsUpdateRule< DIM >.
Definition at line 64 of file DifferentialAdhesionPottsUpdateRule.cpp.
References AdhesionPottsUpdateRule< DIM >::GetCellBoundaryAdhesionEnergyParameter(), and DifferentialAdhesionPottsUpdateRule< DIM >::GetLabelledCellBoundaryAdhesionEnergyParameter().
template<unsigned DIM> double DifferentialAdhesionPottsUpdateRule< DIM >::GetCellCellAdhesionEnergy (CellPtr pCellA, CellPtr pCellB) [inline, virtual]
Overridden GetCellCellAdhesionEnergy method to implement differential adhesion.
Parameters:
pCellA pointer to the 1st cell
pCellB pointer to the 2nd cell
Returns:
The cell cell interaction adhesion energy between the two cells
Reimplemented from AdhesionPottsUpdateRule< DIM >.
Definition at line 47 of file DifferentialAdhesionPottsUpdateRule.cpp.
References AdhesionPottsUpdateRule< DIM >::GetCellCellAdhesionEnergyParameter(), DifferentialAdhesionPottsUpdateRule< DIM >::GetLabelledCellCellAdhesionEnergyParameter(), and DifferentialAdhesionPottsUpdateRule< DIM >::GetLabelledCellLabelledCellAdhesionEnergyParameter().
template<unsigned DIM> double DifferentialAdhesionPottsUpdateRule< DIM >::GetLabelledCellBoundaryAdhesionEnergyParameter () [inline]
Returns:
mLabelledCellBoundaryAdhesionEnergyParameter
Definition at line 90 of file DifferentialAdhesionPottsUpdateRule.cpp.
References DifferentialAdhesionPottsUpdateRule< DIM >::mLabelledCellBoundaryAdhesionEnergyParameter.
Referenced by DifferentialAdhesionPottsUpdateRule< DIM >::GetCellBoundaryAdhesionEnergy().
template<unsigned DIM> double DifferentialAdhesionPottsUpdateRule< DIM >::GetLabelledCellCellAdhesionEnergyParameter () [inline]
Returns:
mLabelledCellCellAdhesionEnergyParameter
Definition at line 84 of file DifferentialAdhesionPottsUpdateRule.cpp.
References DifferentialAdhesionPottsUpdateRule< DIM >::mLabelledCellCellAdhesionEnergyParameter.
Referenced by DifferentialAdhesionPottsUpdateRule< DIM >::GetCellCellAdhesionEnergy().
template<unsigned DIM> double DifferentialAdhesionPottsUpdateRule< DIM >::GetLabelledCellLabelledCellAdhesionEnergyParameter () [inline]
Returns:
mLabelledCellLabelledCellAdhesionEnergyParameter
Definition at line 78 of file DifferentialAdhesionPottsUpdateRule.cpp.
References DifferentialAdhesionPottsUpdateRule< DIM >::mLabelledCellLabelledCellAdhesionEnergyParameter.
Referenced by DifferentialAdhesionPottsUpdateRule< DIM >::GetCellCellAdhesionEnergy().
template<unsigned DIM> void DifferentialAdhesionPottsUpdateRule< DIM >::OutputUpdateRuleParameters (out_stream & rParamsFile) [inline, virtual]
Overridden OutputUpdateRuleParameters() method.
Parameters:
rParamsFile the file stream to which the parameters are output
Reimplemented from AdhesionPottsUpdateRule< DIM >.
Definition at line 115 of file DifferentialAdhesionPottsUpdateRule.cpp.
References DifferentialAdhesionPottsUpdateRule< DIM >::mLabelledCellBoundaryAdhesionEnergyParameter, DifferentialAdhesionPottsUpdateRule< DIM >::mLabelledCellCellAdhesionEnergyParameter, and DifferentialAdhesionPottsUpdateRule< DIM >::mLabelledCellLabelledCellAdhesionEnergyParameter.
template<unsigned DIM> template<class Archive > void DifferentialAdhesionPottsUpdateRule< DIM >::serialize (Archive & archive, const unsigned int version) [inline, private]
Serialize the object.
Parameters:
archive the archive
version the current version of this class
Reimplemented from AdhesionPottsUpdateRule< DIM >.
Definition at line 75 of file DifferentialAdhesionPottsUpdateRule.hpp.
References DifferentialAdhesionPottsUpdateRule< DIM >::mLabelledCellBoundaryAdhesionEnergyParameter, DifferentialAdhesionPottsUpdateRule< DIM >::mLabelledCellCellAdhesionEnergyParameter, and DifferentialAdhesionPottsUpdateRule< DIM >::mLabelledCellLabelledCellAdhesionEnergyParameter.
template<unsigned DIM> void DifferentialAdhesionPottsUpdateRule< DIM >::SetLabelledCellBoundaryAdhesionEnergyParameter (double labelledCellBoundaryAdhesionEnergyParameter) [inline]
Set mLabelledCellBoundaryAdhesionEnergyParameter.
Parameters:
labelledCellBoundaryAdhesionEnergyParameter the new value of mLabelledCellBoundaryAdhesionEnergyParameter
Definition at line 108 of file DifferentialAdhesionPottsUpdateRule.cpp.
References DifferentialAdhesionPottsUpdateRule< DIM >::mLabelledCellBoundaryAdhesionEnergyParameter.
template<unsigned DIM> void DifferentialAdhesionPottsUpdateRule< DIM >::SetLabelledCellCellAdhesionEnergyParameter (double labelledCellCellAdhesionEnergyParameter) [inline]
Set mLabelledCellCellAdhesionEnergyParameter.
Parameters:
labelledCellCellAdhesionEnergyParameter the new value of mLabelledCelldCellAdhesionEnergyParameter
Definition at line 102 of file DifferentialAdhesionPottsUpdateRule.cpp.
References DifferentialAdhesionPottsUpdateRule< DIM >::mLabelledCellCellAdhesionEnergyParameter.
template<unsigned DIM> void DifferentialAdhesionPottsUpdateRule< DIM >::SetLabelledCellLabelledCellAdhesionEnergyParameter (double labelledCellLabelledCellAdhesionEnergyParameter) [inline]
Set mLabelledCellLabelledCellAdhesionEnergyParameter.
Parameters:
labelledCellLabelledCellAdhesionEnergyParameter the new value of mLabelledCellLabelledCellAdhesionEnergyParameter
Definition at line 96 of file DifferentialAdhesionPottsUpdateRule.cpp.
References DifferentialAdhesionPottsUpdateRule< DIM >::mLabelledCellLabelledCellAdhesionEnergyParameter.
Friends And Related Function Documentation
template<unsigned DIM> friend class boost::serialization::access [friend]
Needed for serialization.
Reimplemented from AdhesionPottsUpdateRule< DIM >.
Definition at line 73 of file DifferentialAdhesionPottsUpdateRule.hpp.
Member Data Documentation
template<unsigned DIM> double DifferentialAdhesionPottsUpdateRule< DIM >::mLabelledCellBoundaryAdhesionEnergyParameter [private]
LabelledCell-boundary adhesion energy parameter. Set to the default value 0.2 in the constructor.
Todo:
provide units
Definition at line 71 of file DifferentialAdhesionPottsUpdateRule.hpp.
Referenced by DifferentialAdhesionPottsUpdateRule< DIM >::GetLabelledCellBoundaryAdhesionEnergyParameter(), DifferentialAdhesionPottsUpdateRule< DIM >::OutputUpdateRuleParameters(), DifferentialAdhesionPottsUpdateRule< DIM >::serialize(), and DifferentialAdhesionPottsUpdateRule< DIM >::SetLabelledCellBoundaryAdhesionEnergyParameter().
template<unsigned DIM> double DifferentialAdhesionPottsUpdateRule< DIM >::mLabelledCellCellAdhesionEnergyParameter [private]
LablledCell-cell adhesion energy parameter. Set to the default value 0.1 in the constructor.
Todo:
provide units
Definition at line 64 of file DifferentialAdhesionPottsUpdateRule.hpp.
Referenced by DifferentialAdhesionPottsUpdateRule< DIM >::GetLabelledCellCellAdhesionEnergyParameter(), DifferentialAdhesionPottsUpdateRule< DIM >::OutputUpdateRuleParameters(), DifferentialAdhesionPottsUpdateRule< DIM >::serialize(), and DifferentialAdhesionPottsUpdateRule< DIM >::SetLabelledCellCellAdhesionEnergyParameter().
template<unsigned DIM> double DifferentialAdhesionPottsUpdateRule< DIM >::mLabelledCellLabelledCellAdhesionEnergyParameter [private]
LabelledCell-LabelledCell adhesion energy parameter. Set to the default value 0.1 in the constructor.
Todo:
provide units
Definition at line 57 of file DifferentialAdhesionPottsUpdateRule.hpp.
Referenced by DifferentialAdhesionPottsUpdateRule< DIM >::GetLabelledCellLabelledCellAdhesionEnergyParameter(), DifferentialAdhesionPottsUpdateRule< DIM >::OutputUpdateRuleParameters(), DifferentialAdhesionPottsUpdateRule< DIM >::serialize(), and DifferentialAdhesionPottsUpdateRule< DIM >::SetLabelledCellLabelledCellAdhesionEnergyParameter().
The documentation for this class was generated from the following files:
cell_based/src/population/update_rules/DifferentialAdhesionPottsUpdateRule.hpp
cell_based/src/population/update_rules/DifferentialAdhesionPottsUpdateRule.cpp