Chaste: BidomainTissue< SPACE_DIM > Class Template Reference
BidomainTissue< SPACE_DIM > Class Template Reference
#include <BidomainTissue.hpp>
Inherits AbstractCardiacTissue< SPACE_DIM >.
Public Member Functions
BidomainTissue (AbstractCardiacCellFactory< SPACE_DIM > *pCellFactory, bool exchangeHalos=false)
BidomainTissue (AbstractTetrahedralMesh< SPACE_DIM, SPACE_DIM > *pMesh)
~BidomainTissue ()
const c_matrix< double,
SPACE_DIM, SPACE_DIM > & rGetExtracellularConductivityTensor (unsigned elementIndex)
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
void CreateExtracellularConductivityTensors ()
Private Attributes
AbstractConductivityTensors
< SPACE_DIM, SPACE_DIM > * mpExtracellularConductivityTensors
Friends
class TestBidomainTissue
class boost::serialization::access
Detailed Description
template<unsigned SPACE_DIM>
class BidomainTissue< SPACE_DIM >
BidomainTissue class.
See documentation for AbstractCardiacTissue. This class also has extracellular conductivity tensors.
Definition at line 53 of file BidomainTissue.hpp.
Constructor & Destructor Documentation
template<unsigned SPACE_DIM> BidomainTissue< SPACE_DIM >::BidomainTissue (AbstractCardiacCellFactory< SPACE_DIM > * pCellFactory, bool exchangeHalos = false) [inline]
Constructor sets up extracellular conductivity tensors.
Parameters:
pCellFactory factory to pass on to the base class constructor
exchangeHalos used in state-variable interpolation. Defaults to false.
Definition at line 38 of file BidomainTissue.cpp.
References BidomainTissue< SPACE_DIM >::CreateExtracellularConductivityTensors().
template<unsigned SPACE_DIM> BidomainTissue< SPACE_DIM >::BidomainTissue (AbstractTetrahedralMesh< SPACE_DIM, SPACE_DIM > * pMesh) [inline]
Archiving constructor
Parameters:
pMesh a pointer to the AbstractTetrahedral mesh (recovered from archive).
Definition at line 47 of file BidomainTissue.cpp.
References BidomainTissue< SPACE_DIM >::CreateExtracellularConductivityTensors().
template<unsigned SPACE_DIM> BidomainTissue< SPACE_DIM >::~BidomainTissue () [inline]
Destructor
Definition at line 159 of file BidomainTissue.cpp.
References BidomainTissue< SPACE_DIM >::mpExtracellularConductivityTensors.
Member Function Documentation
template<unsigned SPACE_DIM> void BidomainTissue< SPACE_DIM >::CreateExtracellularConductivityTensors () [inline, private]
Convenience method for extracellular conductivity tensors creation
Definition at line 54 of file BidomainTissue.cpp.
References RelativeTo::AbsoluteOrCwd, FileFinder::Exists(), HeartConfig::GetConductivityHeterogeneities(), HeartConfig::GetConductivityHeterogeneitiesProvided(), HeartConfig::GetConductivityMedia(), HeartConfig::GetExtracellularConductivities(), HeartConfig::GetLoadMesh(), AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::GetNumLocalElements(), AbstractConductivityTensors< ELEMENT_DIM, SPACE_DIM >::Init(), HeartConfig::Instance(), HeartConfig::IsMeshProvided(), AbstractCardiacTissue< SPACE_DIM >::mFibreFilePathNoExtension, AbstractCardiacTissue< SPACE_DIM >::mpConfig, BidomainTissue< SPACE_DIM >::mpExtracellularConductivityTensors, AbstractCardiacTissue< SPACE_DIM >::mpMesh, NEVER_REACHED, PetscTools::ReplicateException(), AbstractConductivityTensors< ELEMENT_DIM, SPACE_DIM >::SetConstantConductivities(), AbstractConductivityTensors< ELEMENT_DIM, SPACE_DIM >::SetFibreOrientationFile(), and AbstractConductivityTensors< ELEMENT_DIM, SPACE_DIM >::SetNonConstantConductivities().
Referenced by BidomainTissue< SPACE_DIM >::BidomainTissue().
template<unsigned SPACE_DIM> const c_matrix< double, SPACE_DIM, SPACE_DIM > & BidomainTissue< SPACE_DIM >::rGetExtracellularConductivityTensor (unsigned elementIndex) [inline, virtual]
Get the extracellular conductivity tensor for the given element
Parameters:
elementIndex index of the element of interest
Reimplemented from AbstractCardiacTissue< SPACE_DIM >.
Definition at line 169 of file BidomainTissue.cpp.
References AbstractCardiacTissue< SPACE_DIM >::mpConductivityModifier, BidomainTissue< SPACE_DIM >::mpExtracellularConductivityTensors, and AbstractConductivityModifier< ELEMENT_DIM, SPACE_DIM >::rGetModifiedConductivityTensor().
template<unsigned SPACE_DIM> template<class Archive > void BidomainTissue< SPACE_DIM >::serialize (Archive & archive, const unsigned int version) [inline, private]
Archive the member variables.
Parameters:
archive
version
Definition at line 67 of file BidomainTissue.hpp.
Friends And Related Function Documentation
template<unsigned SPACE_DIM> friend class boost::serialization::access [friend]
Needed for serialization.
Reimplemented from AbstractCardiacTissue< SPACE_DIM >.
Definition at line 59 of file BidomainTissue.hpp.
Member Data Documentation
template<unsigned SPACE_DIM> AbstractConductivityTensors<SPACE_DIM,SPACE_DIM>* BidomainTissue< SPACE_DIM >::mpExtracellularConductivityTensors [private]
Extracellular conductivity tensors.
Definition at line 74 of file BidomainTissue.hpp.
Referenced by BidomainTissue< SPACE_DIM >::CreateExtracellularConductivityTensors(), BidomainTissue< SPACE_DIM >::rGetExtracellularConductivityTensor(), and BidomainTissue< SPACE_DIM >::~BidomainTissue().
The documentation for this class was generated from the following files:
heart/src/tissue/BidomainTissue.hpp
heart/src/tissue/BidomainTissue.cpp