Chaste: VolumeTrackedOffLatticeSimulation< DIM > Class Template Reference
VolumeTrackedOffLatticeSimulation< DIM > Class Template Reference
#include <VolumeTrackedOffLatticeSimulation.hpp>
Inherits OffLatticeSimulation< DIM >.
Public Member Functions
VolumeTrackedOffLatticeSimulation (AbstractCellPopulation< DIM > &rCellPopulation, bool deleteCellPopulationInDestructor=false, bool initialiseCells=true)
~VolumeTrackedOffLatticeSimulation ()
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
void PostSolve ()
Friends
class boost::serialization::access
Detailed Description
template<unsigned DIM>
class VolumeTrackedOffLatticeSimulation< DIM >
Subclass of OffLatticeSimulation in which the volume of the cells is used in a CellWiseData structure for contact inhibition below a threshold volume. Works only with MeshBasedPopulation and a VertexBasedPopulation at the moment.
Definition at line 45 of file VolumeTrackedOffLatticeSimulation.hpp.
Constructor & Destructor Documentation
template<unsigned DIM> VolumeTrackedOffLatticeSimulation< DIM >::VolumeTrackedOffLatticeSimulation (AbstractCellPopulation< DIM > & rCellPopulation, bool deleteCellPopulationInDestructor = false, bool initialiseCells = true) [inline]
Default constructor.
Parameters:
rCellPopulation A cell population facade class (contains a mesh and cells)
deleteCellPopulationInDestructor Whether to delete the cell population on destruction to free up memory (defaults to false)
initialiseCells whether to initialise cells (defaults to true, set to false when loading from an archive)
Definition at line 35 of file VolumeTrackedOffLatticeSimulation.cpp.
References EXCEPTION.
template<unsigned DIM> VolumeTrackedOffLatticeSimulation< DIM >::~VolumeTrackedOffLatticeSimulation () [inline]
Destructor.
Definition at line 47 of file VolumeTrackedOffLatticeSimulation.cpp.
Member Function Documentation
template<unsigned DIM> void VolumeTrackedOffLatticeSimulation< DIM >::PostSolve () [inline, private, virtual]
Overridden PostSolve() method.
Reimplemented from AbstractCellBasedSimulation< DIM >.
Definition at line 52 of file VolumeTrackedOffLatticeSimulation.cpp.
References MeshBasedCellPopulation< DIM >::CreateVoronoiTessellation(), VertexMesh< ELEMENT_DIM, SPACE_DIM >::GetVolumeOfElement(), MeshBasedCellPopulation< DIM >::GetVolumeOfVoronoiElement(), AbstractCellBasedSimulation< DIM >::mrCellPopulation, and VertexBasedCellPopulation< DIM >::rGetMesh().
template<unsigned DIM> template<class Archive > void VolumeTrackedOffLatticeSimulation< DIM >::serialize (Archive & archive, const unsigned int version) [inline, private]
Archive the object and its member variables.
Parameters:
archive the archive
version the current version of this class
Reimplemented from OffLatticeSimulation< DIM >.
Definition at line 58 of file VolumeTrackedOffLatticeSimulation.hpp.
Friends And Related Function Documentation
template<unsigned DIM> friend class boost::serialization::access [friend]
Needed for serialization.
Reimplemented from OffLatticeSimulation< DIM >.
Definition at line 50 of file VolumeTrackedOffLatticeSimulation.hpp.
The documentation for this class was generated from the following files:
cell_based/src/simulation/VolumeTrackedOffLatticeSimulation.hpp
cell_based/src/simulation/VolumeTrackedOffLatticeSimulation.cpp