Chaste: AbstractLinearEllipticPde< ELEMENT_DIM, SPACE_DIM > Class Template Reference
AbstractLinearEllipticPde< ELEMENT_DIM, SPACE_DIM > Class Template Reference
#include <AbstractLinearEllipticPde.hpp>
Public Member Functions
AbstractLinearEllipticPde ()
virtual ~AbstractLinearEllipticPde ()
virtual double ComputeConstantInUSourceTerm (const ChastePoint< SPACE_DIM > &rX, Element< ELEMENT_DIM, SPACE_DIM > *pElement)=0
virtual double ComputeLinearInUCoeffInSourceTerm (const ChastePoint< SPACE_DIM > &rX, Element< ELEMENT_DIM, SPACE_DIM > *pElement)=0
virtual c_matrix< double,
SPACE_DIM, SPACE_DIM > ComputeDiffusionTerm (const ChastePoint< SPACE_DIM > &rX)=0
virtual double ComputeConstantInUSourceTermAtNode (const Node< SPACE_DIM > &rNode)
virtual double ComputeLinearInUCoeffInSourceTermAtNode (const Node< SPACE_DIM > &rNode)
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Friends
class boost::serialization::access
Detailed Description
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM>
class AbstractLinearEllipticPde< ELEMENT_DIM, SPACE_DIM >
AbstractLinearEllipticPde class.
A general PDE of the form: 0 = Grad.(DiffusionTerm(x)*Grad(u)) + ComputeConstantInUSourceTerm(x) + ComputeLinearInUCoeffInSourceTerm(x, u)
Parabolic PDEs are be derived from this (AbstractLinearParabolicPde)
Definition at line 52 of file AbstractLinearEllipticPde.hpp.
Constructor & Destructor Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> AbstractLinearEllipticPde< ELEMENT_DIM, SPACE_DIM >::AbstractLinearEllipticPde () [inline]
Constructor.
Definition at line 74 of file AbstractLinearEllipticPde.hpp.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> virtual AbstractLinearEllipticPde< ELEMENT_DIM, SPACE_DIM >::~AbstractLinearEllipticPde () [inline, virtual]
Destructor.
Definition at line 80 of file AbstractLinearEllipticPde.hpp.
Member Function Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> virtual double AbstractLinearEllipticPde< ELEMENT_DIM, SPACE_DIM >::ComputeConstantInUSourceTerm (const ChastePoint< SPACE_DIM > & rX, Element< ELEMENT_DIM, SPACE_DIM > * pElement) [pure virtual]
Compute the constant in u part of the source term, i.e g(x) in Div(D Grad u) + f(x)u + g(x) = 0, at a given point.
Parameters:
rX The point in space
pElement The element
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> double AbstractLinearEllipticPde< ELEMENT_DIM, SPACE_DIM >::ComputeConstantInUSourceTermAtNode (const Node< SPACE_DIM > & rNode) [inline, virtual]
Compute the constant in u part of the source term, i.e g(x) in Div(D Grad u) + f(x)u + g(x) = 0, at a given node.
Parameters:
rNode the node
Definition at line 134 of file AbstractLinearEllipticPde.hpp.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> virtual c_matrix<double, SPACE_DIM, SPACE_DIM> AbstractLinearEllipticPde< ELEMENT_DIM, SPACE_DIM >::ComputeDiffusionTerm (const ChastePoint< SPACE_DIM > & rX) [pure virtual]
Compute the diffusion term at a given point. The diffusion tensor should be symmetric and positive definite
Parameters:
rX The point in space at which the diffusion term is computed.
Returns:
A matrix.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> virtual double AbstractLinearEllipticPde< ELEMENT_DIM, SPACE_DIM >::ComputeLinearInUCoeffInSourceTerm (const ChastePoint< SPACE_DIM > & rX, Element< ELEMENT_DIM, SPACE_DIM > * pElement) [pure virtual]
Compute the coefficient of u in the linear part of the source term, i.e f(x) in Div(D Grad u) + f(x)u + g(x) = 0, at a given point in space.
Parameters:
rX The point in space
pElement
Referenced by AbstractLinearEllipticPde< ELEMENT_DIM, SPACE_DIM >::ComputeLinearInUCoeffInSourceTermAtNode().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> double AbstractLinearEllipticPde< ELEMENT_DIM, SPACE_DIM >::ComputeLinearInUCoeffInSourceTermAtNode (const Node< SPACE_DIM > & rNode) [inline, virtual]
Compute the coefficient of u in the linear part of the source term, i.e f(x) in Div(D Grad u) + f(x)u + g(x) = 0, at a given node.
Parameters:
rNode the node
Definition at line 140 of file AbstractLinearEllipticPde.hpp.
References AbstractLinearEllipticPde< ELEMENT_DIM, SPACE_DIM >::ComputeLinearInUCoeffInSourceTerm(), and Node< SPACE_DIM >::GetPoint().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> template<class Archive > void AbstractLinearEllipticPde< ELEMENT_DIM, SPACE_DIM >::serialize (Archive & archive, const unsigned int version) [inline, private]
Serialize the PDE object.
Parameters:
archive the archive
version the current version of this class
Reimplemented in AveragedSourcePde< DIM >, CellwiseSourcePde< DIM >, SimpleUniformSourcePde< DIM >, and VolumeDependentAveragedSourcePde< DIM >.
Definition at line 65 of file AbstractLinearEllipticPde.hpp.
Friends And Related Function Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> friend class boost::serialization::access [friend]
Needed for serialization.
Reimplemented in AveragedSourcePde< DIM >, CellwiseSourcePde< DIM >, SimpleUniformSourcePde< DIM >, and VolumeDependentAveragedSourcePde< DIM >.
Definition at line 57 of file AbstractLinearEllipticPde.hpp.
The documentation for this class was generated from the following file:
pde/src/problem/AbstractLinearEllipticPde.hpp