Chaste: VoltageInterpolaterOntoMechanicsMesh< DIM > Class Template Reference
VoltageInterpolaterOntoMechanicsMesh< DIM > Class Template Reference
#include <VoltageInterpolaterOntoMechanicsMesh.hpp>
Public Member Functions
VoltageInterpolaterOntoMechanicsMesh (TetrahedralMesh< DIM, DIM > &rElectricsMesh, QuadraticMesh< DIM > &rMechanicsMesh, std::vector< std::string > &rVariableNames, std::string directory, std::string inputFileNamePrefix)
Detailed Description
template<unsigned DIM>
class VoltageInterpolaterOntoMechanicsMesh< DIM >
Very simple one-method class which can be used to convert the voltage from an electrics (or electromechanics) simulation onto a coarser mechanics mesh, by interpolation. The class outputs a HDF5 file corresponding to nodes on the mechanics mesh, and converts it to CMGUI output.
Definition at line 52 of file VoltageInterpolaterOntoMechanicsMesh.hpp.
Constructor & Destructor Documentation
VoltageInterpolaterOntoMechanicsMesh()
template<unsigned DIM> VoltageInterpolaterOntoMechanicsMesh< DIM >::VoltageInterpolaterOntoMechanicsMesh (TetrahedralMesh< DIM, DIM > & rElectricsMesh, QuadraticMesh< DIM > & rMechanicsMesh, std::vector< std::string > & rVariableNames, std::string directory, std::string inputFileNamePrefix)
Constructor, also the main method of the class
Parameters
rElectricsMesh The electrics mesh
rMechanicsMesh The mechanics mesh
rVariableNames vector of names of variables contained in the input h5 file and that you want to be interpolated.
directory Directory the voltage file is in
inputFileNamePrefix Filename (without ".h5") of the electrics solution HDF5 file
Definition at line 46 of file VoltageInterpolaterOntoMechanicsMesh.cpp.
References Hdf5DataWriter::AdvanceAlongUnlimitedDimension(), RelativeTo::ChasteTestOutput, FineCoarseMeshPair< DIM >::ComputeFineElementsAndWeightsForCoarseNodes(), DistributedVectorFactory::CreateVec(), PetscTools::CreateVec(), Hdf5DataWriter::DefineFixedDimension(), Hdf5DataWriter::DefineUnlimitedDimension(), Hdf5DataWriter::DefineVariable(), PetscTools::Destroy(), Hdf5DataWriter::EndDefineMode(), AbstractMesh< ELEMENT_DIM, SPACE_DIM >::GetDistributedVectorFactory(), AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::GetElement(), AbstractElement< ELEMENT_DIM, SPACE_DIM >::GetNodeGlobalIndex(), AbstractElement< ELEMENT_DIM, SPACE_DIM >::GetNumNodes(), AbstractMesh< ELEMENT_DIM, SPACE_DIM >::GetNumNodes(), HeartConfig::GetOutputDirectory(), Hdf5DataReader::GetUnlimitedDimensionValues(), Hdf5DataReader::GetVariableOverNodes(), HeartConfig::Instance(), Hdf5DataWriter::PutUnlimitedVariable(), Hdf5DataWriter::PutVector(), FineCoarseMeshPair< DIM >::rGetElementsAndWeights(), HeartConfig::SetOutputDirectory(), and FineCoarseMeshPair< DIM >::SetUpBoxesOnFineMesh().
The documentation for this class was generated from the following files:
heart/src/postprocessing/VoltageInterpolaterOntoMechanicsMesh.hpp
heart/src/postprocessing/VoltageInterpolaterOntoMechanicsMesh.cpp