Chaste: AlwaysDivideCellCycleModel Class Reference
AlwaysDivideCellCycleModel Class Reference
#include <AlwaysDivideCellCycleModel.hpp>
Public Member Functions
AlwaysDivideCellCycleModel ()
bool ReadyToDivide ()
AbstractCellCycleModel * CreateCellCycleModel ()
double GetAverageTransitCellCycleTime ()
double GetAverageStemCellCycleTime ()
void OutputCellCycleModelParameters (out_stream &rParamsFile)
Public Member Functions inherited from AbstractCellCycleModel
AbstractCellCycleModel ()
virtual ~AbstractCellCycleModel ()
void SetCell (CellPtr pCell)
virtual void Initialise ()
virtual void InitialiseDaughterCell ()
CellPtr GetCell ()
virtual void SetBirthTime (double birthTime)
void SetDimension (unsigned dimension)
unsigned GetDimension () const
double GetBirthTime () const
double GetAge ()
virtual void ResetForDivision ()
virtual bool CanCellTerminallyDifferentiate ()
void OutputCellCycleModelInfo (out_stream &rParamsFile)
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Friends
class boost::serialization::access
Additional Inherited Members
Protected Member Functions inherited from AbstractCellCycleModel
AbstractCellCycleModel (const AbstractCellCycleModel &rModel)
Protected Attributes inherited from AbstractCellCycleModel
CellPtr mpCell
double mBirthTime
bool mReadyToDivide
unsigned mDimension
Detailed Description
A 'dummy' cell-cycle model class that can be used in simulations featuring constant cell proliferation.
Definition at line 45 of file AlwaysDivideCellCycleModel.hpp.
Constructor & Destructor Documentation
AlwaysDivideCellCycleModel()
AlwaysDivideCellCycleModel::AlwaysDivideCellCycleModel ()
Default constructor.
Definition at line 38 of file AlwaysDivideCellCycleModel.cpp.
References AbstractCellCycleModel::mReadyToDivide.
Referenced by CreateCellCycleModel().
Member Function Documentation
CreateCellCycleModel()
AbstractCellCycleModel * AlwaysDivideCellCycleModel::CreateCellCycleModel () virtual
Overridden builder method to create new copies of this cell-cycle model.
Returns
new cell-cycle model
Implements AbstractCellCycleModel.
Definition at line 50 of file AlwaysDivideCellCycleModel.cpp.
References AlwaysDivideCellCycleModel().
GetAverageStemCellCycleTime()
double AlwaysDivideCellCycleModel::GetAverageStemCellCycleTime () virtual
Overridden GetAverageStemCellCycleTime() method.
Returns
DBL_MAX
Implements AbstractCellCycleModel.
Definition at line 61 of file AlwaysDivideCellCycleModel.cpp.
GetAverageTransitCellCycleTime()
double AlwaysDivideCellCycleModel::GetAverageTransitCellCycleTime () virtual
Overridden GetAverageTransitCellCycleTime() method.
Returns
DBL_MAX
Implements AbstractCellCycleModel.
Definition at line 56 of file AlwaysDivideCellCycleModel.cpp.
OutputCellCycleModelParameters()
void AlwaysDivideCellCycleModel::OutputCellCycleModelParameters (out_stream & rParamsFile) virtual
Overridden OutputCellCycleModelParameters() method.
Parameters
rParamsFile the file stream to which the parameters are output
Implements AbstractCellCycleModel.
Definition at line 66 of file AlwaysDivideCellCycleModel.cpp.
References AbstractCellCycleModel::OutputCellCycleModelParameters().
ReadyToDivide()
bool AlwaysDivideCellCycleModel::ReadyToDivide () virtual
Overridden ReadyToDivide() method.
Returns
true
Implements AbstractCellCycleModel.
Definition at line 44 of file AlwaysDivideCellCycleModel.cpp.
serialize()
template<class Archive > void AlwaysDivideCellCycleModel::serialize (Archive & archive, const unsigned int version) inline private
Archive the cell-cycle model.
Parameters
archive the archive
version the current version of this class
Definition at line 58 of file AlwaysDivideCellCycleModel.hpp.
Friends And Related Symbol Documentation
boost::serialization::access
friend class boost::serialization::access friend
Needed for serialization.
Definition at line 50 of file AlwaysDivideCellCycleModel.hpp.
The documentation for this class was generated from the following files:
cell_based/src/cell/cycle/AlwaysDivideCellCycleModel.hpp
cell_based/src/cell/cycle/AlwaysDivideCellCycleModel.cpp