Chaste: ImmersedBoundaryLinearInteractionForce< DIM > Class Template Reference
ImmersedBoundaryLinearInteractionForce< DIM > Class Template Reference
#include <ImmersedBoundaryLinearInteractionForce.hpp>
Public Member Functions
ImmersedBoundaryLinearInteractionForce ()
virtual ~ImmersedBoundaryLinearInteractionForce ()
void AddImmersedBoundaryForceContribution (std::vector< std::pair< Node< DIM > *, Node< DIM > * > > &rNodePairs, ImmersedBoundaryCellPopulation< DIM > &rCellPopulation)
void OutputImmersedBoundaryForceParameters (out_stream &rParamsFile)
double GetSpringConst () const
void SetSpringConst (double springConst)
double GetRestLength () const
void SetRestLength (double restLength)
double GetLaminaSpringConstMult () const
void SetLaminaSpringConstMult (double laminaSpringConstMult)
double GetLaminaRestLengthMult () const
void SetLaminaRestLengthMult (double laminaRestLengthMult)
Public Member Functions inherited from AbstractImmersedBoundaryForce< DIM >
AbstractImmersedBoundaryForce ()
virtual ~AbstractImmersedBoundaryForce ()
bool GetAdditiveNormalNoise () const
void SetAdditiveNormalNoise (bool additiveNormalNoise)
double GetNormalNoiseMean () const
void SetNormalNoiseMean (double normalNoiseMean)
double GetNormalNoiseStdDev () const
void SetNormalNoiseStdDev (double normalNoiseStdDev)
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Private Attributes
double mSpringConst
double mRestLength
double mLaminaSpringConstMult
double mLaminaRestLengthMult
Friends
class boost::serialization::access
Additional Inherited Members
Protected Member Functions inherited from AbstractImmersedBoundaryForce< DIM >
void AddNormalNoiseToNodes (ImmersedBoundaryCellPopulation< DIM > &rCellPopulation)
Protected Attributes inherited from AbstractImmersedBoundaryForce< DIM >
bool mAdditiveNormalNoise
double mNormalNoiseMean
double mNormalNoiseStdDev
Detailed Description
template<unsigned DIM>
class ImmersedBoundaryLinearInteractionForce< DIM >
A force class for use in immersed boundary simulations. This force implements elastic links between nodes in adjacent immersed boundaries.
Definition at line 54 of file ImmersedBoundaryLinearInteractionForce.hpp.
Constructor & Destructor Documentation
ImmersedBoundaryLinearInteractionForce()
template<unsigned DIM> ImmersedBoundaryLinearInteractionForce< DIM >::ImmersedBoundaryLinearInteractionForce ()
Constructor.
Definition at line 40 of file ImmersedBoundaryLinearInteractionForce.cpp.
~ImmersedBoundaryLinearInteractionForce()
template<unsigned DIM> ImmersedBoundaryLinearInteractionForce< DIM >::~ImmersedBoundaryLinearInteractionForce () virtual
Destructor.
Definition at line 50 of file ImmersedBoundaryLinearInteractionForce.cpp.
Member Function Documentation
AddImmersedBoundaryForceContribution()
template<unsigned DIM> void ImmersedBoundaryLinearInteractionForce< DIM >::AddImmersedBoundaryForceContribution (std::vector< std::pair< Node< DIM > *, Node< DIM > * > > & rNodePairs, ImmersedBoundaryCellPopulation< DIM > & rCellPopulation) virtual
Overridden AddImmersedBoundaryForceContribution() method. Calculates the force on each node in the immersed boundary cell population as a result of cell-cell interactions.
Parameters
rNodePairs reference to a vector set of node pairs between which to contribute the force
rCellPopulation reference to the cell population
Implements AbstractImmersedBoundaryForce< DIM >.
Definition at line 55 of file ImmersedBoundaryLinearInteractionForce.cpp.
References Node< SPACE_DIM >::AddAppliedForceContribution(), Node< SPACE_DIM >::ContainingElementsBegin(), ImmersedBoundaryMesh< ELEMENT_DIM, SPACE_DIM >::GetAverageNodeSpacingOfElement(), ImmersedBoundaryMesh< ELEMENT_DIM, SPACE_DIM >::GetAverageNodeSpacingOfLamina(), ImmersedBoundaryCellPopulation< DIM >::GetInteractionDistance(), ImmersedBoundaryCellPopulation< DIM >::GetIntrinsicSpacing(), Node< SPACE_DIM >::GetRegion(), ImmersedBoundaryMesh< ELEMENT_DIM, SPACE_DIM >::GetVectorFromAtoB(), ImmersedBoundaryMesh< ELEMENT_DIM, SPACE_DIM >::NodesInDifferentElementOrLamina(), Node< SPACE_DIM >::rGetLocation(), and ImmersedBoundaryCellPopulation< DIM >::rGetMesh().
GetLaminaRestLengthMult()
template<unsigned DIM> double ImmersedBoundaryLinearInteractionForce< DIM >::GetLaminaRestLengthMult () const
Returns
mLaminaRestLengthMult
Definition at line 177 of file ImmersedBoundaryLinearInteractionForce.cpp.
GetLaminaSpringConstMult()
template<unsigned DIM> double ImmersedBoundaryLinearInteractionForce< DIM >::GetLaminaSpringConstMult () const
Returns
mLaminaSpringConstMult
Definition at line 164 of file ImmersedBoundaryLinearInteractionForce.cpp.
GetRestLength()
template<unsigned DIM> double ImmersedBoundaryLinearInteractionForce< DIM >::GetRestLength () const
Returns
mRestLength
Definition at line 152 of file ImmersedBoundaryLinearInteractionForce.cpp.
GetSpringConst()
template<unsigned DIM> double ImmersedBoundaryLinearInteractionForce< DIM >::GetSpringConst () const
Returns
mSpringConst
Definition at line 139 of file ImmersedBoundaryLinearInteractionForce.cpp.
OutputImmersedBoundaryForceParameters()
template<unsigned DIM> void ImmersedBoundaryLinearInteractionForce< DIM >::OutputImmersedBoundaryForceParameters (out_stream & rParamsFile) virtual
Overridden OutputImmersedBoundaryForceParameters() method.
Parameters
rParamsFile the file stream to which the parameters are output
Implements AbstractImmersedBoundaryForce< DIM >.
Definition at line 126 of file ImmersedBoundaryLinearInteractionForce.cpp.
References AbstractImmersedBoundaryForce< DIM >::OutputImmersedBoundaryForceParameters().
serialize()
template<unsigned DIM> template<class Archive > void ImmersedBoundaryLinearInteractionForce< DIM >::serialize (Archive & archive, const unsigned int version) inline private
Boost Serialization method for archiving/checkpointing. Archives the object and its member variables.
Parameters
archive The boost archive.
version The current version of this class.
Definition at line 67 of file ImmersedBoundaryLinearInteractionForce.hpp.
References ImmersedBoundaryLinearInteractionForce< DIM >::mLaminaRestLengthMult, ImmersedBoundaryLinearInteractionForce< DIM >::mLaminaSpringConstMult, ImmersedBoundaryLinearInteractionForce< DIM >::mRestLength, and ImmersedBoundaryLinearInteractionForce< DIM >::mSpringConst.
SetLaminaRestLengthMult()
template<unsigned DIM> void ImmersedBoundaryLinearInteractionForce< DIM >::SetLaminaRestLengthMult (double laminaRestLengthMult)
Set mLaminaRestLengthMult.
Parameters
laminaRestLengthMult the new value of mLaminaRestLengthMult
Definition at line 183 of file ImmersedBoundaryLinearInteractionForce.cpp.
SetLaminaSpringConstMult()
template<unsigned DIM> void ImmersedBoundaryLinearInteractionForce< DIM >::SetLaminaSpringConstMult (double laminaSpringConstMult)
Set mLaminaSpringConstMult.
Parameters
laminaSpringConstMult the new value of mLaminaSpringConstMult
Definition at line 170 of file ImmersedBoundaryLinearInteractionForce.cpp.
SetRestLength()
template<unsigned DIM> void ImmersedBoundaryLinearInteractionForce< DIM >::SetRestLength (double restLength)
Set mRestLength.
Parameters
restLength the new value of mRestLength
Definition at line 158 of file ImmersedBoundaryLinearInteractionForce.cpp.
SetSpringConst()
template<unsigned DIM> void ImmersedBoundaryLinearInteractionForce< DIM >::SetSpringConst (double springConst)
Set mSpringConst.
Parameters
springConst the new value of mSpringConst
Definition at line 145 of file ImmersedBoundaryLinearInteractionForce.cpp.
Friends And Related Symbol Documentation
boost::serialization::access
template<unsigned DIM> friend class boost::serialization::access friend
Definition at line 58 of file ImmersedBoundaryLinearInteractionForce.hpp.
Member Data Documentation
mLaminaRestLengthMult
template<unsigned DIM> double ImmersedBoundaryLinearInteractionForce< DIM >::mLaminaRestLengthMult private
Multiplicative factor to change equilibrium length of interactions involving a lamina node. Initialised to 1.0 in constructor.
Definition at line 98 of file ImmersedBoundaryLinearInteractionForce.hpp.
Referenced by ImmersedBoundaryLinearInteractionForce< DIM >::serialize().
mLaminaSpringConstMult
template<unsigned DIM> double ImmersedBoundaryLinearInteractionForce< DIM >::mLaminaSpringConstMult private
Multiplicative factor to change strength of interactions involving a lamina node. Initialised to 1.0 in constructor.
Definition at line 92 of file ImmersedBoundaryLinearInteractionForce.hpp.
Referenced by ImmersedBoundaryLinearInteractionForce< DIM >::serialize().
mRestLength
template<unsigned DIM> double ImmersedBoundaryLinearInteractionForce< DIM >::mRestLength private
The basic rest length associated with interactions, as a fraction of cell population's interaction distance. Initialised to 0.25 in constructor.
Definition at line 86 of file ImmersedBoundaryLinearInteractionForce.hpp.
Referenced by ImmersedBoundaryLinearInteractionForce< DIM >::serialize().
mSpringConst
template<unsigned DIM> double ImmersedBoundaryLinearInteractionForce< DIM >::mSpringConst private
The basic spring constant associated with interactions. Initialised to 1e3 in constructor.
Definition at line 80 of file ImmersedBoundaryLinearInteractionForce.hpp.
Referenced by ImmersedBoundaryLinearInteractionForce< DIM >::serialize().
The documentation for this class was generated from the following files:
cell_based/src/population/forces/ImmersedBoundaryLinearInteractionForce.hpp
cell_based/src/population/forces/ImmersedBoundaryLinearInteractionForce.cpp