Chaste: VanLeeuwen2009WntSwatCellCycleModelHypothesisOne Class Reference
VanLeeuwen2009WntSwatCellCycleModelHypothesisOne Class Reference
#include <VanLeeuwen2009WntSwatCellCycleModelHypothesisOne.hpp>
Public Member Functions
VanLeeuwen2009WntSwatCellCycleModelHypothesisOne (boost::shared_ptr< AbstractCellCycleModelOdeSolver > pOdeSolver=boost::shared_ptr< AbstractCellCycleModelOdeSolver >())
void InitialiseOdeSystem (double wntConcentration, boost::shared_ptr< AbstractCellMutationState > pMutationState)
AbstractCellCycleModel * CreateCellCycleModel ()
virtual void OutputCellCycleModelParameters (out_stream &rParamsFile)
Public Member Functions inherited from AbstractVanLeeuwen2009WntSwatCellCycleModel
AbstractVanLeeuwen2009WntSwatCellCycleModel (boost::shared_ptr< AbstractCellCycleModelOdeSolver > pOdeSolver=boost::shared_ptr< AbstractCellCycleModelOdeSolver >())
void Initialise ()
double GetMembraneBoundBetaCateninLevel ()
double GetCytoplasmicBetaCateninLevel ()
double GetNuclearBetaCateninLevel ()
Public Member Functions inherited from AbstractWntOdeBasedCellCycleModel
AbstractWntOdeBasedCellCycleModel (boost::shared_ptr< AbstractCellCycleModelOdeSolver > pOdeSolver=boost::shared_ptr< AbstractCellCycleModelOdeSolver >())
virtual ~AbstractWntOdeBasedCellCycleModel ()
void ResetForDivision ()
void UpdateCellProliferativeType ()
double GetAverageTransitCellCycleTime ()
double GetAverageStemCellCycleTime ()
virtual bool CanCellTerminallyDifferentiate ()
Public Member Functions inherited from AbstractOdeBasedPhaseBasedCellCycleModel
AbstractOdeBasedPhaseBasedCellCycleModel (double lastTime=SimulationTime::Instance() ->GetTime(), boost::shared_ptr< AbstractCellCycleModelOdeSolver > pOdeSolver=boost::shared_ptr< AbstractCellCycleModelOdeSolver >())
virtual ~AbstractOdeBasedPhaseBasedCellCycleModel ()
double GetOdeStopTime ()
void SetBirthTime (double birthTime)
Public Member Functions inherited from AbstractPhaseBasedCellCycleModel
AbstractPhaseBasedCellCycleModel ()
virtual ~AbstractPhaseBasedCellCycleModel ()
virtual bool ReadyToDivide ()
CellCyclePhase GetCurrentCellCyclePhase () const
virtual double GetG1Duration () const
double GetStemCellG1Duration () const
double GetTransitCellG1Duration () const
double GetSG2MDuration () const
virtual double GetSDuration () const
virtual double GetG2Duration () const
virtual double GetMDuration () const
virtual void SetStemCellG1Duration (double stemCellG1Duration)
virtual void SetTransitCellG1Duration (double transitCellG1Duration)
void SetSDuration (double sDuration)
void SetG2Duration (double g2Duration)
void SetMDuration (double mDuration)
double GetMinimumGapDuration () const
void SetMinimumGapDuration (double minimumGapDuration)
Public Member Functions inherited from AbstractCellCycleModel
AbstractCellCycleModel ()
virtual ~AbstractCellCycleModel ()
void SetCell (CellPtr pCell)
virtual void InitialiseDaughterCell ()
CellPtr GetCell ()
void SetDimension (unsigned dimension)
unsigned GetDimension () const
double GetBirthTime () const
double GetAge ()
void OutputCellCycleModelInfo (out_stream &rParamsFile)
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Public Member Functions inherited from CellCycleModelOdeHandler
CellCycleModelOdeHandler (double lastTime=SimulationTime::Instance() ->GetTime(), boost::shared_ptr< AbstractCellCycleModelOdeSolver > pOdeSolver=boost::shared_ptr< AbstractCellCycleModelOdeSolver >())
virtual ~CellCycleModelOdeHandler ()
AbstractOdeSystem * GetOdeSystem () const
void SetOdeSystem (AbstractOdeSystem *pOdeSystem)
const boost::shared_ptr< AbstractCellCycleModelOdeSolver > GetOdeSolver () const
void SetLastTime (double lastTime)
double GetDt ()
void SetDt (double timeStep)
void SetStateVariables (const std::vector< double > &rStateVariables)
std::vector< double > GetProteinConcentrations () const
void SetProteinConcentrationsForTestsOnly (double lastTime, std::vector< double > proteinConcentrations)
Protected Member Functions
VanLeeuwen2009WntSwatCellCycleModelHypothesisOne (const VanLeeuwen2009WntSwatCellCycleModelHypothesisOne &rModel)
Protected Member Functions inherited from AbstractVanLeeuwen2009WntSwatCellCycleModel
AbstractVanLeeuwen2009WntSwatCellCycleModel (const AbstractVanLeeuwen2009WntSwatCellCycleModel &rModel)
Protected Member Functions inherited from AbstractWntOdeBasedCellCycleModel
double GetWntLevel () const
void UpdateCellCyclePhase ()
AbstractWntOdeBasedCellCycleModel (const AbstractWntOdeBasedCellCycleModel &rModel)
Protected Member Functions inherited from AbstractOdeBasedPhaseBasedCellCycleModel
AbstractOdeBasedPhaseBasedCellCycleModel (const AbstractOdeBasedPhaseBasedCellCycleModel &rModel)
Protected Member Functions inherited from AbstractPhaseBasedCellCycleModel
AbstractPhaseBasedCellCycleModel (const AbstractPhaseBasedCellCycleModel &rModel)
Protected Member Functions inherited from AbstractCellCycleModel
AbstractCellCycleModel (const AbstractCellCycleModel &rModel)
Protected Member Functions inherited from CellCycleModelOdeHandler
CellCycleModelOdeHandler (const CellCycleModelOdeHandler &rHandler)
bool SolveOdeToTime (double currentTime)
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Friends
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from AbstractOdeBasedPhaseBasedCellCycleModel
double mDivideTime
double mG2PhaseStartTime
Protected Attributes inherited from AbstractPhaseBasedCellCycleModel
CellCyclePhase mCurrentCellCyclePhase
double mG1Duration
double mMinimumGapDuration
double mStemCellG1Duration
double mTransitCellG1Duration
double mSDuration
double mG2Duration
double mMDuration
Protected Attributes inherited from AbstractCellCycleModel
CellPtr mpCell
double mBirthTime
bool mReadyToDivide
unsigned mDimension
Protected Attributes inherited from CellCycleModelOdeHandler
double mDt
AbstractOdeSystem * mpOdeSystem
boost::shared_ptr< AbstractCellCycleModelOdeSolver > mpOdeSolver
double mLastTime
bool mFinishedRunningOdes
Detailed Description
Concrete Van Leeuwen 2009 cell-cycle model, using hypothesis one (see paper).
Definition at line 44 of file VanLeeuwen2009WntSwatCellCycleModelHypothesisOne.hpp.
Constructor & Destructor Documentation
VanLeeuwen2009WntSwatCellCycleModelHypothesisOne() [1/2]
VanLeeuwen2009WntSwatCellCycleModelHypothesisOne::VanLeeuwen2009WntSwatCellCycleModelHypothesisOne (const VanLeeuwen2009WntSwatCellCycleModelHypothesisOne & rModel) protected
Protected copy-constructor for use by CreateCellCycleModel. The only way for external code to create a copy of a cell cycle model is by calling that method, to ensure that a model of the correct subclass is created. This copy-constructor helps subclasses to ensure that all member variables are correctly copied when this happens.
This method is called by child classes to set member variables for a daughter cell upon cell division. Note that the parent cell cycle model will have had ResetForDivision() called just before CreateCellCycleModel() is called, so performing an exact copy of the parent is suitable behaviour. Any daughter-cell-specific initialisation can be done in InitialiseDaughterCell().
Parameters
rModel the cell cycle model to copy.
Definition at line 57 of file VanLeeuwen2009WntSwatCellCycleModelHypothesisOne.cpp.
References CellCycleModelOdeHandler::GetOdeSystem(), AbstractWntOdeBasedCellCycleModel::GetWntLevel(), InitialiseOdeSystem(), AbstractCellCycleModel::mpCell, AbstractParameterisedSystem< VECTOR >::rGetStateVariables(), and CellCycleModelOdeHandler::SetStateVariables().
VanLeeuwen2009WntSwatCellCycleModelHypothesisOne() [2/2]
VanLeeuwen2009WntSwatCellCycleModelHypothesisOne::VanLeeuwen2009WntSwatCellCycleModelHypothesisOne (boost::shared_ptr< AbstractCellCycleModelOdeSolver > pOdeSolver = boost::shared_ptr<AbstractCellCycleModelOdeSolver>())
Default constructor calls base class.
Parameters
pOdeSolver An optional pointer to a cell-cycle model ODE solver object (allows the use of different ODE solvers)
Definition at line 38 of file VanLeeuwen2009WntSwatCellCycleModelHypothesisOne.cpp.
References CellCycleModelOdeSolver< CELL_CYCLE_MODEL, ODE_SOLVER >::Instance(), CellCycleModelOdeHandler::mpOdeSolver, and CellCycleModelOdeHandler::SetDt().
Member Function Documentation
CreateCellCycleModel()
AbstractCellCycleModel * VanLeeuwen2009WntSwatCellCycleModelHypothesisOne::CreateCellCycleModel () virtual
Overridden builder method to create new copies of this cell-cycle model.
Returns
the new cell-cycle model
Implements AbstractCellCycleModel.
Definition at line 84 of file VanLeeuwen2009WntSwatCellCycleModelHypothesisOne.cpp.
InitialiseOdeSystem()
void VanLeeuwen2009WntSwatCellCycleModelHypothesisOne::InitialiseOdeSystem (double wntConcentration, boost::shared_ptr< AbstractCellMutationState > pMutationState) virtual
Overloaded method which allocates the ODE system using HYPOTHESIS ONE.
Parameters
wntConcentration Wnt concentration
pMutationState Mutation state
Implements AbstractVanLeeuwen2009WntSwatCellCycleModel.
Definition at line 79 of file VanLeeuwen2009WntSwatCellCycleModelHypothesisOne.cpp.
References CellCycleModelOdeHandler::mpOdeSystem.
Referenced by VanLeeuwen2009WntSwatCellCycleModelHypothesisOne().
OutputCellCycleModelParameters()
void VanLeeuwen2009WntSwatCellCycleModelHypothesisOne::OutputCellCycleModelParameters (out_stream & rParamsFile) virtual
Overridden OutputCellCycleModelParameters() method.
Parameters
rParamsFile the file stream to which the parameters are output
Reimplemented from AbstractVanLeeuwen2009WntSwatCellCycleModel.
Definition at line 89 of file VanLeeuwen2009WntSwatCellCycleModelHypothesisOne.cpp.
References AbstractVanLeeuwen2009WntSwatCellCycleModel::OutputCellCycleModelParameters().
serialize()
template<class Archive > void VanLeeuwen2009WntSwatCellCycleModelHypothesisOne::serialize (Archive & archive, const unsigned int version) inline private
Boost Serialization method for archiving/checkpointing. Archives the object and its member variables.
Parameters
archive The boost archive.
version The current version of this class.
Definition at line 57 of file VanLeeuwen2009WntSwatCellCycleModelHypothesisOne.hpp.
Friends And Related Symbol Documentation
boost::serialization::access
friend class boost::serialization::access friend
Definition at line 48 of file VanLeeuwen2009WntSwatCellCycleModelHypothesisOne.hpp.
The documentation for this class was generated from the following files:
crypt/src/cell/cycle/VanLeeuwen2009WntSwatCellCycleModelHypothesisOne.hpp
crypt/src/cell/cycle/VanLeeuwen2009WntSwatCellCycleModelHypothesisOne.cpp