Chaste: DiffusionCaUpdateRule< DIM > Class Template Reference
DiffusionCaUpdateRule< DIM > Class Template Reference
#include <DiffusionCaUpdateRule.hpp>
Public Member Functions
DiffusionCaUpdateRule ()
~DiffusionCaUpdateRule ()
double EvaluateProbability (unsigned currentNodeIndex, unsigned targetNodeIndex, CaBasedCellPopulation< DIM > &rCellPopulation, double dt, double deltaX, CellPtr cell)
double GetDiffusionParameter ()
void SetDiffusionParameter (double diffusionParameter)
void OutputUpdateRuleParameters (out_stream &rParamsFile)
Public Member Functions inherited from AbstractCaUpdateRule< DIM >
AbstractCaUpdateRule ()
virtual ~AbstractCaUpdateRule ()
Public Member Functions inherited from AbstractUpdateRule< DIM >
AbstractUpdateRule ()
virtual ~AbstractUpdateRule ()
void OutputUpdateRuleInfo (out_stream &rParamsFile)
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Private Attributes
double mDiffusionParameter
Friends
class TestCaUpdateRules
class boost::serialization::access
Detailed Description
template<unsigned DIM>
class DiffusionCaUpdateRule< DIM >
A diffusion update rule for use in cell-based simulations using the cellular CA model.
The probability of moving to an adjacent lattice site is
D*delta_t/(2*delta_x*delta_x)
Where D is the mDiffusionParameter. delta_t is the timestep. delta_x is the separation of the two lattice sites.
Definition at line 58 of file DiffusionCaUpdateRule.hpp.
Constructor & Destructor Documentation
DiffusionCaUpdateRule()
template<unsigned DIM> DiffusionCaUpdateRule< DIM >::DiffusionCaUpdateRule ()
Constructor.
Definition at line 39 of file DiffusionCaUpdateRule.cpp.
~DiffusionCaUpdateRule()
template<unsigned DIM> DiffusionCaUpdateRule< DIM >::~DiffusionCaUpdateRule ()
Destructor.
Definition at line 46 of file DiffusionCaUpdateRule.cpp.
Member Function Documentation
EvaluateProbability()
template<unsigned DIM> double DiffusionCaUpdateRule< DIM >::EvaluateProbability (unsigned currentNodeIndex, unsigned targetNodeIndex, CaBasedCellPopulation< DIM > & rCellPopulation, double dt, double deltaX, CellPtr cell) virtual
Calculate the probability of a given move.
Uses random diffusion to each neighbouring node, scaled according to distance.
Parameters
currentNodeIndex The index of the current node/lattice site
targetNodeIndex The index of the target node/lattice site
rCellPopulation The cell population
dt is the time interval
deltaX defines the size of the lattice site
cell a pointer to the cell (needed if more than one cell per lattice site
Returns
The probability of the cell moving from the current node to the target node
Implements AbstractCaUpdateRule< DIM >.
Definition at line 51 of file DiffusionCaUpdateRule.cpp.
References CaBasedCellPopulation< DIM >::GetNode(), Node< SPACE_DIM >::rGetLocation(), and CaBasedCellPopulation< DIM >::rGetMesh().
GetDiffusionParameter()
template<unsigned DIM> double DiffusionCaUpdateRule< DIM >::GetDiffusionParameter ()
Returns
mDiffusionParameter
Definition at line 65 of file DiffusionCaUpdateRule.cpp.
OutputUpdateRuleParameters()
template<unsigned DIM> void DiffusionCaUpdateRule< DIM >::OutputUpdateRuleParameters (out_stream & rParamsFile) virtual
Overridden OutputUpdateRuleParameters() method.
Parameters
rParamsFile the file stream to which the parameters are output
Reimplemented from AbstractCaUpdateRule< DIM >.
Definition at line 77 of file DiffusionCaUpdateRule.cpp.
References AbstractCaUpdateRule< DIM >::OutputUpdateRuleParameters().
serialize()
template<unsigned DIM> template<class Archive > void DiffusionCaUpdateRule< DIM >::serialize (Archive & archive, const unsigned int version) inline private
Boost Serialization method for archiving/checkpointing. Archives the object and its member variables.
Parameters
archive The boost archive.
version The current version of this class.
Definition at line 80 of file DiffusionCaUpdateRule.hpp.
References DiffusionCaUpdateRule< DIM >::mDiffusionParameter.
SetDiffusionParameter()
template<unsigned DIM> void DiffusionCaUpdateRule< DIM >::SetDiffusionParameter (double diffusionParameter)
Set mDiffusionParameter.
Parameters
diffusionParameter the new value of mDiffusionParameter
Definition at line 71 of file DiffusionCaUpdateRule.cpp.
Friends And Related Symbol Documentation
boost::serialization::access
template<unsigned DIM> friend class boost::serialization::access friend
Definition at line 71 of file DiffusionCaUpdateRule.hpp.
TestCaUpdateRules
template<unsigned DIM> friend class TestCaUpdateRules friend
Definition at line 60 of file DiffusionCaUpdateRule.hpp.
Member Data Documentation
mDiffusionParameter
template<unsigned DIM> double DiffusionCaUpdateRule< DIM >::mDiffusionParameter private
Diffusion parameter for update rule. Set to the default value 0.5 in the constructor.
Todo:
provide units
Definition at line 69 of file DiffusionCaUpdateRule.hpp.
Referenced by DiffusionCaUpdateRule< DIM >::serialize().
The documentation for this class was generated from the following files:
cell_based/src/population/update_rules/DiffusionCaUpdateRule.hpp
cell_based/src/population/update_rules/DiffusionCaUpdateRule.cpp