Chaste: DeltaNotchInteriorSrnModel Class Reference
DeltaNotchInteriorSrnModel Class Reference
#include <DeltaNotchInteriorSrnModel.hpp>
Public Member Functions
DeltaNotchInteriorSrnModel (boost::shared_ptr< AbstractCellCycleModelOdeSolver > pOdeSolver=boost::shared_ptr< AbstractCellCycleModelOdeSolver >())
virtual AbstractSrnModel * CreateSrnModel ()
virtual void ResetForDivision ()
virtual void Initialise ()
virtual void SimulateToCurrentTime ()
void UpdateDeltaNotch ()
double GetNotch ()
void SetNotch (double value)
double GetDelta ()
void SetDelta (double value)
double GetTotalEdgeDelta ()
double GetTotalEdgeNotch ()
virtual void OutputSrnModelParameters (out_stream &rParamsFile)
virtual void AddShrunkEdgeToInterior (AbstractSrnModel *pShrunkEdgeSrn)
Public Member Functions inherited from AbstractOdeSrnModel
AbstractOdeSrnModel (unsigned stateSize, boost::shared_ptr< AbstractCellCycleModelOdeSolver > pOdeSolver=boost::shared_ptr< AbstractCellCycleModelOdeSolver >())
virtual ~AbstractOdeSrnModel ()
void SetInitialConditions (std::vector< double > initialConditions)
virtual void ScaleSrnVariables (const double theta)
Public Member Functions inherited from AbstractSrnModel
AbstractSrnModel ()
virtual ~AbstractSrnModel ()
virtual void SetCell (CellPtr pCell)
virtual void InitialiseDaughterCell ()
CellPtr GetCell ()
void SetSimulatedToTime (double simulatedToTime)
double GetSimulatedToTime () const
void OutputSrnModelInfo (out_stream &rParamsFile)
void SetEdgeLocalIndex (unsigned index)
unsigned GetEdgeLocalIndex ()
bool HasEdgeModel () const
void SetEdgeModelIndicator (const bool isEdgeModel)
virtual void AddSrnQuantities (AbstractSrnModel *pOtherSrn, const double scale=1.0)
virtual void AddShrunkEdgeSrn (AbstractSrnModel *pShrunkEdgeSrn)
virtual void AddMergedEdgeSrn (AbstractSrnModel *pMergedEdgeSrn)
virtual void SplitEdgeSrn (const double relativePosition)
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Public Member Functions inherited from CellCycleModelOdeHandler
CellCycleModelOdeHandler (double lastTime=SimulationTime::Instance() ->GetTime(), boost::shared_ptr< AbstractCellCycleModelOdeSolver > pOdeSolver=boost::shared_ptr< AbstractCellCycleModelOdeSolver >())
virtual ~CellCycleModelOdeHandler ()
AbstractOdeSystem * GetOdeSystem () const
void SetOdeSystem (AbstractOdeSystem *pOdeSystem)
const boost::shared_ptr< AbstractCellCycleModelOdeSolver > GetOdeSolver () const
void SetLastTime (double lastTime)
double GetDt ()
void SetDt (double timeStep)
void SetStateVariables (const std::vector< double > &rStateVariables)
std::vector< double > GetProteinConcentrations () const
void SetProteinConcentrationsForTestsOnly (double lastTime, std::vector< double > proteinConcentrations)
Protected Member Functions
DeltaNotchInteriorSrnModel (const DeltaNotchInteriorSrnModel &rModel)
Protected Member Functions inherited from AbstractOdeSrnModel
void Initialise (AbstractOdeSystem *pOdeSystem)
AbstractOdeSrnModel (const AbstractOdeSrnModel &rModel)
Protected Member Functions inherited from AbstractSrnModel
AbstractSrnModel (const AbstractSrnModel &rModel)
Protected Member Functions inherited from CellCycleModelOdeHandler
CellCycleModelOdeHandler (const CellCycleModelOdeHandler &rHandler)
bool SolveOdeToTime (double currentTime)
virtual void AdjustOdeParameters (double currentTime)
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Friends
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from AbstractOdeSrnModel
std::vector< double > mInitialConditions
unsigned mStateSize
Protected Attributes inherited from AbstractSrnModel
CellPtr mpCell
double mSimulatedToTime
unsigned mEdgeLocalIndex = UNSIGNED_UNSET
bool mIsEdgeBasedModel = false
Protected Attributes inherited from CellCycleModelOdeHandler
double mDt
AbstractOdeSystem * mpOdeSystem
boost::shared_ptr< AbstractCellCycleModelOdeSolver > mpOdeSolver
double mLastTime
bool mFinishedRunningOdes
Detailed Description
A subclass of AbstractOdeSrnModel that includes a Delta-Notch ODE system in the sub-cellular reaction network. This class represents model describing cytoplasmic (interior, nuclear) concentration of Delta Notch. Together with DeltaNotchEdgeSrn, this class can model feedback between cytoplasmic and junctional concentration, and cell-cell communication via edge (junctional) concentrations.
Definition at line 53 of file DeltaNotchInteriorSrnModel.hpp.
Constructor & Destructor Documentation
DeltaNotchInteriorSrnModel() [1/2]
DeltaNotchInteriorSrnModel::DeltaNotchInteriorSrnModel (const DeltaNotchInteriorSrnModel & rModel) protected
Protected copy-constructor for use by CreateSrnModel(). The only way for external code to create a copy of a SRN model is by calling that method, to ensure that a model of the correct subclass is created.
This copy-constructor helps subclasses to ensure that all member variables are correctly copied when this happens.
This method is called by child classes to set member variables for a daughter cell upon cell division. Note that the parent SRN model will have had ResetForDivision() called just before CreateSrnModel() is called, so performing an exact copy of the parent is suitable behaviour. Any daughter-cell-specific initialisation can be done in InitialiseDaughterCell().
Parameters
rModel the SRN model to copy.
Definition at line 57 of file DeltaNotchInteriorSrnModel.cpp.
References AbstractUntemplatedParameterisedSystem::GetNumberOfParameters(), CellCycleModelOdeHandler::GetOdeSystem(), AbstractParameterisedSystem< VECTOR >::GetParameter(), CellCycleModelOdeHandler::mpOdeSystem, AbstractParameterisedSystem< VECTOR >::rGetStateVariables(), CellCycleModelOdeHandler::SetOdeSystem(), and AbstractParameterisedSystem< VECTOR >::SetParameter().
DeltaNotchInteriorSrnModel() [2/2]
DeltaNotchInteriorSrnModel::DeltaNotchInteriorSrnModel (boost::shared_ptr< AbstractCellCycleModelOdeSolver > pOdeSolver = boost::shared_ptr<AbstractCellCycleModelOdeSolver>())
Default constructor calls base class.
Parameters
pOdeSolver An optional pointer to a cell-cycle model ODE solver object (allows the use of different ODE solvers)
Definition at line 39 of file DeltaNotchInteriorSrnModel.cpp.
References CellCycleModelOdeSolver< CELL_CYCLE_MODEL, ODE_SOLVER >::Instance(), CellCycleModelOdeHandler::mpOdeSolver, and CellCycleModelOdeHandler::SetDt().
Member Function Documentation
AddShrunkEdgeToInterior()
void DeltaNotchInteriorSrnModel::AddShrunkEdgeToInterior (AbstractSrnModel * pShrunkEdgeSrn) virtual
Sets how much of Delta/Notch is returned back to interior after a junction is shrunk Override the method to reflect user-define assumptions
Parameters
pShrunkEdgeSrn Pointer to an SRN model
Reimplemented from AbstractSrnModel.
Definition at line 168 of file DeltaNotchInteriorSrnModel.cpp.
References GetDelta(), DeltaNotchEdgeSrnModel::GetNotch(), GetNotch(), SetDelta(), and SetNotch().
CreateSrnModel()
AbstractSrnModel * DeltaNotchInteriorSrnModel::CreateSrnModel () virtual
Overridden builder method to create new copies of this SRN model.
Returns
a copy of the current SRN model.
Implements AbstractSrnModel.
Definition at line 84 of file DeltaNotchInteriorSrnModel.cpp.
GetDelta()
double DeltaNotchInteriorSrnModel::GetDelta ()
Returns
the current Delta level in this cell.
Definition at line 135 of file DeltaNotchInteriorSrnModel.cpp.
References CellCycleModelOdeHandler::mpOdeSystem, and AbstractParameterisedSystem< VECTOR >::rGetStateVariables().
Referenced by AddShrunkEdgeToInterior().
GetNotch()
double DeltaNotchInteriorSrnModel::GetNotch ()
Returns
the current Notch level in this cell.
Definition at line 122 of file DeltaNotchInteriorSrnModel.cpp.
References CellCycleModelOdeHandler::mpOdeSystem, and AbstractParameterisedSystem< VECTOR >::rGetStateVariables().
Referenced by AddShrunkEdgeToInterior().
GetTotalEdgeDelta()
double DeltaNotchInteriorSrnModel::GetTotalEdgeDelta ()
Returns
the current total level of Delta in the edges.
Definition at line 148 of file DeltaNotchInteriorSrnModel.cpp.
References AbstractParameterisedSystem< VECTOR >::GetParameter(), and CellCycleModelOdeHandler::mpOdeSystem.
GetTotalEdgeNotch()
double DeltaNotchInteriorSrnModel::GetTotalEdgeNotch ()
Returns
total edge notch
Definition at line 155 of file DeltaNotchInteriorSrnModel.cpp.
References AbstractParameterisedSystem< VECTOR >::GetParameter(), and CellCycleModelOdeHandler::mpOdeSystem.
Initialise()
void DeltaNotchInteriorSrnModel::Initialise () virtual
Initialise the SRN model at the start of a simulation.
This overridden method sets up a new Delta-Notch ODE system for cell interior.
Reimplemented from AbstractOdeSrnModel.
Definition at line 105 of file DeltaNotchInteriorSrnModel.cpp.
References AbstractOdeSrnModel::Initialise().
OutputSrnModelParameters()
void DeltaNotchInteriorSrnModel::OutputSrnModelParameters (out_stream & rParamsFile) virtual
Parameters
rParamsFile the file stream to which the parameters are output
Reimplemented from AbstractOdeSrnModel.
Definition at line 162 of file DeltaNotchInteriorSrnModel.cpp.
References AbstractOdeSrnModel::OutputSrnModelParameters().
ResetForDivision()
void DeltaNotchInteriorSrnModel::ResetForDivision () virtual
Overriden ResetForDivision() method for custom cell division mitosis
Reimplemented from AbstractOdeSrnModel.
Definition at line 89 of file DeltaNotchInteriorSrnModel.cpp.
References AbstractSrnModel::mpCell, CellCycleModelOdeHandler::mpOdeSystem, and AbstractOdeSrnModel::ScaleSrnVariables().
serialize()
template<class Archive > void DeltaNotchInteriorSrnModel::serialize (Archive & archive, const unsigned int version) inline private
Archive the SRN model and member variables.
Parameters
archive the archive
version the current version of this class
Definition at line 66 of file DeltaNotchInteriorSrnModel.hpp.
SetDelta()
void DeltaNotchInteriorSrnModel::SetDelta (double value)
Set the delta level in this edge
Parameters
value
Definition at line 142 of file DeltaNotchInteriorSrnModel.cpp.
References CellCycleModelOdeHandler::mpOdeSystem, and AbstractParameterisedSystem< VECTOR >::rGetStateVariables().
Referenced by AddShrunkEdgeToInterior().
SetNotch()
void DeltaNotchInteriorSrnModel::SetNotch (double value)
Set the notch level in this edge
Parameters
value
Definition at line 129 of file DeltaNotchInteriorSrnModel.cpp.
References CellCycleModelOdeHandler::mpOdeSystem, and AbstractParameterisedSystem< VECTOR >::rGetStateVariables().
Referenced by AddShrunkEdgeToInterior().
SimulateToCurrentTime()
void DeltaNotchInteriorSrnModel::SimulateToCurrentTime () virtual
Overridden SimulateToTime() method for custom behaviour.
Reimplemented from AbstractOdeSrnModel.
Definition at line 96 of file DeltaNotchInteriorSrnModel.cpp.
References AbstractOdeSrnModel::SimulateToCurrentTime(), and UpdateDeltaNotch().
UpdateDeltaNotch()
void DeltaNotchInteriorSrnModel::UpdateDeltaNotch ()
Updates model parameters, such as total edge concnetration of Delta/Notch, via processing data from CellData()() object
Definition at line 110 of file DeltaNotchInteriorSrnModel.cpp.
References AbstractSrnModel::mpCell, CellCycleModelOdeHandler::mpOdeSystem, and AbstractParameterisedSystem< VECTOR >::SetParameter().
Referenced by SimulateToCurrentTime().
Friends And Related Symbol Documentation
boost::serialization::access
friend class boost::serialization::access friend
Needed for serialization.
Definition at line 58 of file DeltaNotchInteriorSrnModel.hpp.
The documentation for this class was generated from the following files:
cell_based/src/cell/srn/DeltaNotchInteriorSrnModel.hpp
cell_based/src/cell/srn/DeltaNotchInteriorSrnModel.cpp