Chaste: CellsGenerator< CELL_CYCLE_MODEL, DIM > Class Template Reference
CellsGenerator< CELL_CYCLE_MODEL, DIM > Class Template Reference
#include <CellsGenerator.hpp>
Public Member Functions
void GenerateBasic (std::vector< CellPtr > &rCells, unsigned numCells, const std::vector< unsigned > locationIndices=std::vector< unsigned >(), boost::shared_ptr< AbstractCellProperty > pCellProliferativeType=boost::shared_ptr< AbstractCellProperty >())
void GenerateBasicRandom (std::vector< CellPtr > &rCells, unsigned numCells, boost::shared_ptr< AbstractCellProperty > pCellProliferativeType=boost::shared_ptr< AbstractCellProperty >())
void GenerateGivenLocationIndices (std::vector< CellPtr > &rCells, const std::vector< unsigned > locationIndices, boost::shared_ptr< AbstractCellProperty > pCellProliferativeType=boost::shared_ptr< AbstractCellProperty >())
Detailed Description
template<class CELL_CYCLE_MODEL, unsigned DIM>
class CellsGenerator< CELL_CYCLE_MODEL, DIM >
A helper class for generating a vector of cells for a given mesh.
It is templated over types of cell-cycle model and spatial dimension.
Definition at line 52 of file CellsGenerator.hpp.
Member Function Documentation
GenerateBasic()
template<class CELL_CYCLE_MODEL , unsigned DIM> void CellsGenerator< CELL_CYCLE_MODEL, DIM >::GenerateBasic (std::vector< CellPtr > & rCells, unsigned numCells, const std::vector< unsigned > locationIndices = std::vector<unsigned>(), boost::shared_ptr< AbstractCellProperty > pCellProliferativeType = boost::shared_ptr<AbstractCellProperty>())
Fills a vector of cells with a specified cell-cycle model, to match a given number of cells. Gives them birth times of 0 for node 0, -1 for node 1, -2 for node 2 etc...
Parameters
rCells An empty vector of cells to fill up.
numCells The number of cells to generate.
locationIndices is used when a birth-time hint is needed for individual cell. Defaults to an empty vector – otherwise must be of length numCells
pCellProliferativeType the cell proliferative type to give each cell (defaults to StemCellProliferativeType)
Definition at line 98 of file CellsGenerator.hpp.
References EXCEPTION, and CellPropertyRegistry::Instance().
GenerateBasicRandom()
template<class CELL_CYCLE_MODEL , unsigned DIM> void CellsGenerator< CELL_CYCLE_MODEL, DIM >::GenerateBasicRandom (std::vector< CellPtr > & rCells, unsigned numCells, boost::shared_ptr< AbstractCellProperty > pCellProliferativeType = boost::shared_ptr<AbstractCellProperty>())
Fills a vector of cells with a specified cell-cycle model, to match a given number of cells. Gives cells a random birth time drawn uniformly from 0 to the AverageStemCellCycleTime.
Parameters
rCells An empty vector of cells to fill up.
numCells The number of cells to generate.
pCellProliferativeType the cell proliferative type to give each cell (defaults to StemCellProliferativeType)
Definition at line 149 of file CellsGenerator.hpp.
References CellPropertyRegistry::Instance(), RandomNumberGenerator::Instance(), and RandomNumberGenerator::ranf().
GenerateGivenLocationIndices()
template<class CELL_CYCLE_MODEL , unsigned DIM> void CellsGenerator< CELL_CYCLE_MODEL, DIM >::GenerateGivenLocationIndices (std::vector< CellPtr > & rCells, const std::vector< unsigned > locationIndices, boost::shared_ptr< AbstractCellProperty > pCellProliferativeType = boost::shared_ptr<AbstractCellProperty>())
Fills a vector of cells with birth times to match a given vector of location indices.
Parameters
rCells An empty vector of cells to fill up.
locationIndices The indices of the cell population to assign real cells to.
pCellProliferativeType the cell proliferative type to give each cell (defaults to StemCellProliferativeType)
Definition at line 188 of file CellsGenerator.hpp.
References CellPropertyRegistry::Clear(), and CellPropertyRegistry::Instance().
The documentation for this class was generated from the following file:
cell_based/src/cell/CellsGenerator.hpp