Chaste: T2SwapCellKiller< DIM > Class Template Reference
T2SwapCellKiller< DIM > Class Template Reference
#include <T2SwapCellKiller.hpp>
Public Member Functions
T2SwapCellKiller (AbstractCellPopulation< DIM > *pCellPopulation)
void CheckAndLabelCellsForApoptosisOrDeath ()
void OutputCellKillerParameters (out_stream &rParamsFile)
Public Member Functions inherited from AbstractCellKiller< DIM >
AbstractCellKiller (AbstractCellPopulation< SPACE_DIM > *pCellPopulation)
virtual ~AbstractCellKiller ()
const AbstractCellPopulation< SPACE_DIM > * GetCellPopulation () const
void OutputCellKillerInfo (out_stream &rParamsFile)
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Friends
class TestT2SwapCellKiller
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from AbstractCellKiller< DIM >
AbstractCellPopulation< SPACE_DIM > * mpCellPopulation
Detailed Description
template<unsigned DIM>
class T2SwapCellKiller< DIM >
This killer performs T2Swaps and kills the corresponding cells. In contrast to other cell killers it carries out vertex rearrangements. The killer is automatically added to OffLatticeSimulations that use a VertexBasedCellPopulation. To inhibit T2 swaps from happening in a simulation the user needs to set the threshold for T2 swaps in the MutableVertexMesh to 0, using the method SetT2Threshold().
Definition at line 54 of file T2SwapCellKiller.hpp.
Constructor & Destructor Documentation
T2SwapCellKiller()
template<unsigned DIM> T2SwapCellKiller< DIM >::T2SwapCellKiller (AbstractCellPopulation< DIM > * pCellPopulation)
Default constructor.
Parameters
pCellPopulation pointer to the cell population
Definition at line 40 of file T2SwapCellKiller.cpp.
References EXCEPTION, and AbstractCellKiller< DIM >::mpCellPopulation.
Member Function Documentation
CheckAndLabelCellsForApoptosisOrDeath()
template<unsigned DIM> void T2SwapCellKiller< DIM >::CheckAndLabelCellsForApoptosisOrDeath () virtual
Overridden CheckAndLabelCellsForApoptosisOrDeath() method.
Loop over cells and kill them if they are ready for a T2 swap.
Implements AbstractCellKiller< DIM >.
Definition at line 51 of file T2SwapCellKiller.cpp.
References SimulationTime::GetTime(), and SimulationTime::Instance().
OutputCellKillerParameters()
template<unsigned DIM> void T2SwapCellKiller< DIM >::OutputCellKillerParameters (out_stream & rParamsFile) virtual
Overridden OutputCellKillerParameters() method.
Parameters
rParamsFile the file stream to which the parameters are output
Implements AbstractCellKiller< DIM >.
Definition at line 113 of file T2SwapCellKiller.cpp.
References AbstractCellKiller< SPACE_DIM >::OutputCellKillerParameters().
serialize()
template<unsigned DIM> template<class Archive > void T2SwapCellKiller< DIM >::serialize (Archive & archive, const unsigned int version) inline private
Archive the object.
Parameters
archive the archive
version the current version of this class
Definition at line 70 of file T2SwapCellKiller.hpp.
Friends And Related Symbol Documentation
boost::serialization::access
template<unsigned DIM> friend class boost::serialization::access friend
Needed for serialization.
Definition at line 62 of file T2SwapCellKiller.hpp.
TestT2SwapCellKiller
template<unsigned DIM> friend class TestT2SwapCellKiller friend
Definition at line 57 of file T2SwapCellKiller.hpp.
The documentation for this class was generated from the following files:
cell_based/src/population/killers/T2SwapCellKiller.hpp
cell_based/src/population/killers/T2SwapCellKiller.cpp