Chaste: BernoulliTrialCellCycleModel Class Reference
BernoulliTrialCellCycleModel Class Reference
#include <BernoulliTrialCellCycleModel.hpp>
Public Member Functions
BernoulliTrialCellCycleModel ()
virtual bool ReadyToDivide ()
AbstractCellCycleModel * CreateCellCycleModel ()
void SetDivisionProbability (double divisionProbability)
double GetDivisionProbability ()
void SetMinimumDivisionAge (double minimumDivisionAge)
double GetMinimumDivisionAge ()
double GetAverageTransitCellCycleTime ()
double GetAverageStemCellCycleTime ()
virtual void OutputCellCycleModelParameters (out_stream &rParamsFile)
Public Member Functions inherited from AbstractCellCycleModel
AbstractCellCycleModel ()
virtual ~AbstractCellCycleModel ()
void SetCell (CellPtr pCell)
virtual void Initialise ()
virtual void InitialiseDaughterCell ()
CellPtr GetCell ()
virtual void SetBirthTime (double birthTime)
void SetDimension (unsigned dimension)
unsigned GetDimension () const
double GetBirthTime () const
double GetAge ()
virtual void ResetForDivision ()
virtual bool CanCellTerminallyDifferentiate ()
void OutputCellCycleModelInfo (out_stream &rParamsFile)
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Protected Member Functions
BernoulliTrialCellCycleModel (const BernoulliTrialCellCycleModel &rModel)
Protected Member Functions inherited from AbstractCellCycleModel
AbstractCellCycleModel (const AbstractCellCycleModel &rModel)
Protected Attributes
double mDivisionProbability
double mMinimumDivisionAge
Protected Attributes inherited from AbstractCellCycleModel
CellPtr mpCell
double mBirthTime
bool mReadyToDivide
unsigned mDimension
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Friends
class boost::serialization::access
Detailed Description
Simple cell-cycle model where mature non-differentiated cells have a specified probability of dividing per hour.
The class includes two parameters: the first, mDivisionProbability, defines the probability of dividing per hour; the second, mMinimumDivisionAge, defines a minimum age at which cells may divide.
Definition at line 50 of file BernoulliTrialCellCycleModel.hpp.
Constructor & Destructor Documentation
BernoulliTrialCellCycleModel() [1/2]
BernoulliTrialCellCycleModel::BernoulliTrialCellCycleModel (const BernoulliTrialCellCycleModel & rModel) protected
Protected copy-constructor for use by CreateCellCycleModel.
The only way for external code to create a copy of a cell cycle model is by calling that method, to ensure that a model of the correct subclass is created. This copy-constructor helps subclasses to ensure that all member variables are correctly copied when this happens.
This method is called by child classes to set member variables for a daughter cell upon cell division. Note that the parent cell cycle model will have had ResetForDivision() called just before CreateCellCycleModel() is called, so performing an exact copy of the parent is suitable behaviour. Any daughter-cell-specific initialisation can be done in InitialiseDaughterCell().
Parameters
rModel the cell cycle model to copy.
Definition at line 46 of file BernoulliTrialCellCycleModel.cpp.
BernoulliTrialCellCycleModel() [2/2]
BernoulliTrialCellCycleModel::BernoulliTrialCellCycleModel ()
Constructor.
Definition at line 39 of file BernoulliTrialCellCycleModel.cpp.
Referenced by CreateCellCycleModel().
Member Function Documentation
CreateCellCycleModel()
AbstractCellCycleModel * BernoulliTrialCellCycleModel::CreateCellCycleModel () virtual
Overridden builder method to create new instances of the cell-cycle model.
Returns
new cell-cycle model
Implements AbstractCellCycleModel.
Definition at line 81 of file BernoulliTrialCellCycleModel.cpp.
References BernoulliTrialCellCycleModel().
GetAverageStemCellCycleTime()
double BernoulliTrialCellCycleModel::GetAverageStemCellCycleTime () virtual
Overridden GetAverageStemCellCycleTime() method.
Returns
the average cell cycle time for cells of stem proliferative type
Implements AbstractCellCycleModel.
Definition at line 111 of file BernoulliTrialCellCycleModel.cpp.
References mDivisionProbability.
GetAverageTransitCellCycleTime()
double BernoulliTrialCellCycleModel::GetAverageTransitCellCycleTime () virtual
Overridden GetAverageTransitCellCycleTime() method.
Returns
the average cell cycle time for cells of transit proliferative type
Implements AbstractCellCycleModel.
Definition at line 106 of file BernoulliTrialCellCycleModel.cpp.
References mDivisionProbability.
GetDivisionProbability()
double BernoulliTrialCellCycleModel::GetDivisionProbability ()
Get mDivisionProbability.
Returns
mDivisionProbability
Definition at line 91 of file BernoulliTrialCellCycleModel.cpp.
References mDivisionProbability.
GetMinimumDivisionAge()
double BernoulliTrialCellCycleModel::GetMinimumDivisionAge ()
Get mMinimumDivisionAge.
Returns
mMinimumDivisionAge
Definition at line 101 of file BernoulliTrialCellCycleModel.cpp.
References mMinimumDivisionAge.
OutputCellCycleModelParameters()
void BernoulliTrialCellCycleModel::OutputCellCycleModelParameters (out_stream & rParamsFile) virtual
Overridden OutputCellCycleModelParameters() method.
Parameters
rParamsFile the file stream to which the parameters are output
Implements AbstractCellCycleModel.
Definition at line 116 of file BernoulliTrialCellCycleModel.cpp.
References mDivisionProbability, mMinimumDivisionAge, and AbstractCellCycleModel::OutputCellCycleModelParameters().
ReadyToDivide()
bool BernoulliTrialCellCycleModel::ReadyToDivide () virtual
Overridden ReadyToDivide() method.
If the cell's age is greater than mMinimumDivisionAge, then we draw a uniform random number r ~ U[0,1]. If r < mDivisionProbability*dt, where dt is the simulation time step, then the cell is ready to divide and we return true. Otherwise, the cell is not yet ready to divide and we return false.
Returns
whether the cell is ready to divide.
Implements AbstractCellCycleModel.
Definition at line 59 of file BernoulliTrialCellCycleModel.cpp.
References AbstractCellCycleModel::GetAge(), SimulationTime::GetTimeStep(), SimulationTime::Instance(), RandomNumberGenerator::Instance(), mDivisionProbability, mMinimumDivisionAge, AbstractCellCycleModel::mpCell, AbstractCellCycleModel::mReadyToDivide, and RandomNumberGenerator::ranf().
serialize()
template<class Archive > void BernoulliTrialCellCycleModel::serialize (Archive & archive, const unsigned int version) inline private
Boost Serialization method for archiving/checkpointing
Parameters
archive The boost archive.
version The current version of this class.
Definition at line 62 of file BernoulliTrialCellCycleModel.hpp.
References SerializableSingleton< SINGLETON_CLASS >::GetSerializationWrapper(), RandomNumberGenerator::Instance(), mDivisionProbability, and mMinimumDivisionAge.
SetDivisionProbability()
void BernoulliTrialCellCycleModel::SetDivisionProbability (double divisionProbability)
Set the value of mDivisionProbability.
Parameters
divisionProbability the new value of mDivisionProbability
Definition at line 86 of file BernoulliTrialCellCycleModel.cpp.
References mDivisionProbability.
SetMinimumDivisionAge()
void BernoulliTrialCellCycleModel::SetMinimumDivisionAge (double minimumDivisionAge)
Set the value of mMinimumDivisionAge.
Parameters
minimumDivisionAge the new value of mMinimumDivisionAge
Definition at line 96 of file BernoulliTrialCellCycleModel.cpp.
References mMinimumDivisionAge.
Friends And Related Symbol Documentation
boost::serialization::access
friend class boost::serialization::access friend
Definition at line 54 of file BernoulliTrialCellCycleModel.hpp.
Member Data Documentation
mDivisionProbability
double BernoulliTrialCellCycleModel::mDivisionProbability protected
Probability of dividing per hour. Defaults to 0.1.
Definition at line 79 of file BernoulliTrialCellCycleModel.hpp.
Referenced by GetAverageStemCellCycleTime(), GetAverageTransitCellCycleTime(), GetDivisionProbability(), OutputCellCycleModelParameters(), ReadyToDivide(), serialize(), and SetDivisionProbability().
mMinimumDivisionAge
double BernoulliTrialCellCycleModel::mMinimumDivisionAge protected
Minimum age of a cell at which it may divide. Defaults to 1 hour.
Definition at line 85 of file BernoulliTrialCellCycleModel.hpp.
Referenced by GetMinimumDivisionAge(), OutputCellCycleModelParameters(), ReadyToDivide(), serialize(), and SetMinimumDivisionAge().
The documentation for this class was generated from the following files:
cell_based/src/cell/cycle/BernoulliTrialCellCycleModel.hpp
cell_based/src/cell/cycle/BernoulliTrialCellCycleModel.cpp