Chaste: SlidingBoundaryCondition< DIM > Class Template Reference
SlidingBoundaryCondition< DIM > Class Template Reference
#include <SlidingBoundaryCondition.hpp>
Public Member Functions
SlidingBoundaryCondition (AbstractCellPopulation< DIM > *pCellPopulation, double threshold=0.8)
double GetThreshold () const
void ImposeBoundaryCondition (const std::map< Node< DIM > *, c_vector< double, DIM > > &rOldLocations)
bool VerifyBoundaryCondition ()
void OutputCellPopulationBoundaryConditionParameters (out_stream &rParamsFile)
Public Member Functions inherited from AbstractCellPopulationBoundaryCondition< DIM >
AbstractCellPopulationBoundaryCondition (AbstractCellPopulation< ELEMENT_DIM, ELEMENT_DIM > *pCellPopulation)
virtual ~AbstractCellPopulationBoundaryCondition ()
virtual void ImposeBoundaryCondition (const std::map< Node< ELEMENT_DIM > *, c_vector< double, ELEMENT_DIM > > &rOldLocations)=0
const AbstractCellPopulation< ELEMENT_DIM, ELEMENT_DIM > * GetCellPopulation () const
void OutputCellPopulationBoundaryConditionInfo (out_stream &rParamsFile)
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Private Attributes
double mThreshold
Friends
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from AbstractCellPopulationBoundaryCondition< DIM >
AbstractCellPopulation< ELEMENT_DIM, ELEMENT_DIM > * mpCellPopulation
Detailed Description
template<unsigned DIM>
class SlidingBoundaryCondition< DIM >
A boundary condition class that prevents nodes lying with a threshold distance from the left-hand boundary to move in the x direction, but which allows them to 'slide' along this boundary.
Definition at line 51 of file SlidingBoundaryCondition.hpp.
Constructor & Destructor Documentation
SlidingBoundaryCondition()
template<unsigned DIM> SlidingBoundaryCondition< DIM >::SlidingBoundaryCondition (AbstractCellPopulation< DIM > * pCellPopulation, double threshold = 0.8)
Constructor.
Parameters
pCellPopulation pointer to the cell population
threshold maximum distance from left-hand boundary at which condition is imposed on nodes (defaults to 0.8)
Definition at line 41 of file SlidingBoundaryCondition.cpp.
Member Function Documentation
GetThreshold()
template<unsigned DIM> double SlidingBoundaryCondition< DIM >::GetThreshold () const
Returns
mThreshold.
Definition at line 49 of file SlidingBoundaryCondition.cpp.
ImposeBoundaryCondition()
template<unsigned DIM> void SlidingBoundaryCondition< DIM >::ImposeBoundaryCondition (const std::map< Node< DIM > *, c_vector< double, DIM > > & rOldLocations)
Overridden ImposeBoundaryCondition() method.
Apply the cell population boundary condition.
Parameters
rOldLocations the node locations before the boundary condition are applied
Todo:
Move this to constructor. If this is in the constructor then Exception always throws.
Definition at line 55 of file SlidingBoundaryCondition.cpp.
References EXCEPTION, Node< SPACE_DIM >::IsBoundaryNode(), Node< SPACE_DIM >::rGetLocation(), ChasteCuboid< SPACE_DIM >::rGetLowerCorner(), and Node< SPACE_DIM >::rGetModifiableLocation().
OutputCellPopulationBoundaryConditionParameters()
template<unsigned DIM> void SlidingBoundaryCondition< DIM >::OutputCellPopulationBoundaryConditionParameters (out_stream & rParamsFile) virtual
Overridden OutputCellPopulationBoundaryConditionParameters() method. Output cell population boundary condition parameters to file.
Parameters
rParamsFile the file stream to which the parameters are output
Implements AbstractCellPopulationBoundaryCondition< DIM >.
Definition at line 93 of file SlidingBoundaryCondition.cpp.
References AbstractCellPopulationBoundaryCondition< ELEMENT_DIM, SPACE_DIM >::OutputCellPopulationBoundaryConditionParameters().
serialize()
template<unsigned DIM> template<class Archive > void SlidingBoundaryCondition< DIM >::serialize (Archive & archive, const unsigned int version) inline private
Serialize the object and its member variables.
Parameters
archive the archive
version the current version of this class
Definition at line 70 of file SlidingBoundaryCondition.hpp.
VerifyBoundaryCondition()
template<unsigned DIM> bool SlidingBoundaryCondition< DIM >::VerifyBoundaryCondition () virtual
Overridden VerifyBoundaryCondition() method. Verify the boundary condition has been applied. This is called after ImposeBoundaryCondition() to ensure the condition is still satisfied.
Returns
whether the boundary conditions are satisfied.
Implements AbstractCellPopulationBoundaryCondition< DIM >.
Definition at line 86 of file SlidingBoundaryCondition.cpp.
Friends And Related Symbol Documentation
boost::serialization::access
template<unsigned DIM> friend class boost::serialization::access friend
Needed for serialization.
Definition at line 62 of file SlidingBoundaryCondition.hpp.
Member Data Documentation
mThreshold
template<unsigned DIM> double SlidingBoundaryCondition< DIM >::mThreshold private
Maximum distance from left-hand boundary at which condition is imposed on nodes. Initialised to 0.8 in constructor.
Definition at line 59 of file SlidingBoundaryCondition.hpp.
The documentation for this class was generated from the following files:
cell_based/src/population/boundary_conditions/SlidingBoundaryCondition.hpp
cell_based/src/population/boundary_conditions/SlidingBoundaryCondition.cpp