Chaste: TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::EdgeIterator Class Reference
TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::EdgeIterator Class Reference
#include <TetrahedralMesh.hpp>
Public Member Functions
Node< SPACE_DIM > * GetNodeA ()
Node< SPACE_DIM > * GetNodeB ()
bool operator!= (const typename TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::EdgeIterator &rOther)
EdgeIterator & operator++ ()
EdgeIterator (TetrahedralMesh &rMesh, unsigned elemIndex)
Private Attributes
std::set< std::pair< unsigned, unsigned > > mEdgesVisited
TetrahedralMesh & mrMesh
unsigned mElemIndex
unsigned mNodeALocalIndex
unsigned mNodeBLocalIndex
Detailed Description
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM>
class TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::EdgeIterator
Iterator over edges in the mesh.
This class takes care of the logic to make sure that you consider each edge exactly once.
Definition at line 331 of file TetrahedralMesh.hpp.
Constructor & Destructor Documentation
EdgeIterator()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::EdgeIterator::EdgeIterator (TetrahedralMesh & rMesh, unsigned elemIndex)
Constructor for a new edge iterator.
Parameters
rMesh The mesh
elemIndex An element index
Definition at line 595 of file TetrahedralMesh.cpp.
References AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::GetElement(), AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::GetNumAllElements(), TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::EdgeIterator::mEdgesVisited, TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::EdgeIterator::mElemIndex, TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::EdgeIterator::mNodeALocalIndex, TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::EdgeIterator::mNodeBLocalIndex, and TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::EdgeIterator::mrMesh.
Member Function Documentation
GetNodeA()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> Node< SPACE_DIM > * TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::EdgeIterator::GetNodeA ()
Returns
a pointer to the node in the mesh at end A of the edge.
Definition at line 515 of file TetrahedralMesh.cpp.
References TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::EdgesEnd(), AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::GetElement(), AbstractElement< ELEMENT_DIM, SPACE_DIM >::GetNode(), TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::EdgeIterator::mElemIndex, TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::EdgeIterator::mNodeALocalIndex, and TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::EdgeIterator::mrMesh.
GetNodeB()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> Node< SPACE_DIM > * TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::EdgeIterator::GetNodeB ()
Returns
a pointer to the node in the mesh at end B of the edge.
Definition at line 523 of file TetrahedralMesh.cpp.
References AbstractElement< ELEMENT_DIM, SPACE_DIM >::GetNode().
operator!=()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> bool TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::EdgeIterator::operator!= (const typename TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::EdgeIterator & rOther)
Returns
comparison not-equal-to.
Parameters
rOther edge iterator with which comparison is made
Definition at line 531 of file TetrahedralMesh.cpp.
References TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::EdgeIterator::mElemIndex, TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::EdgeIterator::mNodeALocalIndex, and TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::EdgeIterator::mNodeBLocalIndex.
operator++()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::EdgeIterator & TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::EdgeIterator::operator++ ()
Prefix increment operator.
Returns
reference to incremented object
Definition at line 537 of file TetrahedralMesh.cpp.
References AbstractElement< ELEMENT_DIM, SPACE_DIM >::GetNodeGlobalIndex().
Member Data Documentation
mEdgesVisited
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> std::set< std::pair<unsigned, unsigned> > TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::EdgeIterator::mEdgesVisited private
Keep track of what edges have been visited. Each edge is stored as a pair of ordered indices.
Definition at line 369 of file TetrahedralMesh.hpp.
Referenced by TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::EdgeIterator::EdgeIterator().
mElemIndex
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> unsigned TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::EdgeIterator::mElemIndex private
Element index.
Definition at line 373 of file TetrahedralMesh.hpp.
Referenced by TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::EdgeIterator::EdgeIterator(), TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::EdgeIterator::GetNodeA(), and TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::EdgeIterator::operator!=().
mNodeALocalIndex
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> unsigned TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::EdgeIterator::mNodeALocalIndex private
Index of one node on the edge.
Definition at line 374 of file TetrahedralMesh.hpp.
Referenced by TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::EdgeIterator::EdgeIterator(), TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::EdgeIterator::GetNodeA(), and TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::EdgeIterator::operator!=().
mNodeBLocalIndex
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> unsigned TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::EdgeIterator::mNodeBLocalIndex private
Index of the other node on the edge.
Definition at line 375 of file TetrahedralMesh.hpp.
Referenced by TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::EdgeIterator::EdgeIterator(), and TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::EdgeIterator::operator!=().
mrMesh
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> TetrahedralMesh& TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::EdgeIterator::mrMesh private
The mesh.
Definition at line 371 of file TetrahedralMesh.hpp.
Referenced by TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::EdgeIterator::EdgeIterator(), and TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::EdgeIterator::GetNodeA().
The documentation for this class was generated from the following files:
mesh/src/common/TetrahedralMesh.hpp
mesh/src/common/TetrahedralMesh.cpp