Chaste: DiFrancescoNoble1985OdeSystem Class Reference
DiFrancescoNoble1985OdeSystem Class Reference
#include <DiFrancescoNoble1985OdeSystem.hpp>
Public Member Functions
DiFrancescoNoble1985OdeSystem (AbstractIvpOdeSolver *pSolver, AbstractStimulusFunction *pIntracellularStimulus)
~DiFrancescoNoble1985OdeSystem ()
void EvaluateYDerivatives (double time, const std::vector< double > &rY, std::vector< double > &rDY)
double GetIIonic ()
Private Member Functions
void VerifyStateVariables ()
Private Attributes
double Vi
double Vup
double Vrel
double Ve
double Vcell
double RToNF
Static Private Attributes
static const double membrane_C = 75
static const double radius = 0.05
static const double length = 2
static const double V_e_ratio = 0.1
static const double R = 8314.472
static const double T = 310
static const double F = 96485.3415
static const double g_fna = 3
static const double g_fk = 3
static const double g_na_b = 0.18
static const double g_ca_b = 0.02
static const double g_na = 750.0
static const double g_k1 = 920
static double const g_to = 0.28
static const double I_P = 125
static const double i_kmax = 180
static const double k_naca = 0.02
static const double P_si = 15.0
static const double Nao = 140
static const double Cao = 2
static const double Kb = 4
static const double Kmf = 45
static const double Km1 = 210
static const double Kmto = 10
static const double KmK = 1
static const double KmNa = 40
static const double Kmf2 = 0.001
static const double KmCa = 0.001
static const double Km_Ca = 0.0005
static const double n_naca = 3
static const double gamma = 0.5
static const double d_naca = 0.001
static const double rCa = 2.0
static const double tau_up = 0.025
static const double tau_rep = 2
static const double tau_rel = 0.05
static const double Ca_up_max = 5
static const double pf = 0.0007
static const double Vecs = 0.05
Detailed Description
This class sets up the DifrancescoNoble1985 equations. In this version of the model the time is in milliseconds (unlike the paper).
Definition at line 39 of file DiFrancescoNoble1985OdeSystem.hpp.
Constructor & Destructor Documentation
DiFrancescoNoble1985OdeSystem::~DiFrancescoNoble1985OdeSystem (void)
Destructor
Definition at line 58 of file DiFrancescoNoble1985OdeSystem.cpp.
Member Function Documentation
void DiFrancescoNoble1985OdeSystem::VerifyStateVariables () [private, virtual]
Range-checking on the current values of the state variables. Make sure all gating variables have are within zero and one, and all concentrations are positive
Reimplemented from AbstractCardiacCell.
Definition at line 365 of file DiFrancescoNoble1985OdeSystem.cpp.
References AbstractOdeSystem::DumpState().
Referenced by EvaluateYDerivatives().
void DiFrancescoNoble1985OdeSystem::EvaluateYDerivatives (double time, const std::vector< double > & rY, std::vector< double > & rDY) [virtual]
Fill in a vector representing the RHS of the LuoRudyIModel1991OdeSystem system of Odes at each time step, y' = [y1' ... yn']. Some ODE solver will call this function repeatedly to solve for y = [y1 ... yn].
Parameters:
time the current time, in milliseconds
rY current values of the state variables
rDY to be filled in with derivatives
Implements AbstractOdeSystem.
Definition at line 71 of file DiFrancescoNoble1985OdeSystem.cpp.
References VerifyStateVariables().
double DiFrancescoNoble1985OdeSystem::GetIIonic () [virtual]
Computes the total current flowing through the cell membrane, using the current values of the state variables.
Implements AbstractCardiacCell.
Definition at line 286 of file DiFrancescoNoble1985OdeSystem.cpp.
The documentation for this class was generated from the following files:
/tmp/release_1/heart/src/odes/DiFrancescoNoble1985OdeSystem.hpp
/tmp/release_1/heart/src/odes/DiFrancescoNoble1985OdeSystem.cpp