Chaste: SimpleWntCellCycleModelCellsGenerator< DIM > Class Template Reference
SimpleWntCellCycleModelCellsGenerator< DIM > Class Template Reference
#include <SimpleWntCellCycleModelCellsGenerator.hpp>
Public Member Functions
AbstractCellCycleModel * CreateCellCycleModel ()
double GetTypicalTransitCellCycleTime ()
double GetTypicalStemCellCycleTime ()
Detailed Description
template<unsigned DIM>
class SimpleWntCellCycleModelCellsGenerator< DIM >
A helper class for generating a vector of cells with SimpleWntCellCycleModels for a given mesh.
Definition at line 39 of file SimpleWntCellCycleModelCellsGenerator.hpp.
Member Function Documentation
template<unsigned DIM> AbstractCellCycleModel * SimpleWntCellCycleModelCellsGenerator< DIM >::CreateCellCycleModel () [inline, virtual]
Returns:
a pointer to a new SimpleWntCellCycleModel.
Implements AbstractCellsGenerator< DIM >.
Definition at line 32 of file SimpleWntCellCycleModelCellsGenerator.cpp.
template<unsigned DIM> double SimpleWntCellCycleModelCellsGenerator< DIM >::GetTypicalTransitCellCycleTime () [inline, virtual]
Returns:
default cell cycle time for a transit cell.
Implements AbstractCellsGenerator< DIM >.
Definition at line 39 of file SimpleWntCellCycleModelCellsGenerator.cpp.
References CancerParameters::GetSG2MDuration(), CancerParameters::GetTransitCellG1Duration(), and CancerParameters::Instance().
template<unsigned DIM> double SimpleWntCellCycleModelCellsGenerator< DIM >::GetTypicalStemCellCycleTime () [inline, virtual]
Returns:
default cell cycle time for a transit cell.
Implements AbstractCellsGenerator< DIM >.
Definition at line 47 of file SimpleWntCellCycleModelCellsGenerator.cpp.
References CancerParameters::GetSG2MDuration(), CancerParameters::GetStemCellG1Duration(), and CancerParameters::Instance().
The documentation for this class was generated from the following files:
/tmp/release_1/cancer/src/tissue/cell/SimpleWntCellCycleModelCellsGenerator.hpp
/tmp/release_1/cancer/src/tissue/cell/SimpleWntCellCycleModelCellsGenerator.cpp