Chaste: MeshBasedTissue< DIM >::SpringIterator Class Reference
MeshBasedTissue< DIM >::SpringIterator Class Reference
#include <MeshBasedTissue.hpp>
Public Member Functions
Node< DIM > * GetNodeA ()
Node< DIM > * GetNodeB ()
TissueCell & rGetCellA ()
TissueCell & rGetCellB ()
bool operator!= (const SpringIterator &other)
SpringIterator & operator++ ()
SpringIterator (MeshBasedTissue &rTissue, typename MutableMesh< DIM, DIM >::EdgeIterator edgeIter)
Private Attributes
std::set< std::set< unsigned > > mSpringsVisited
MeshBasedTissue & mrTissue
MutableMesh< DIM, DIM >
::EdgeIterator mEdgeIter
Detailed Description
template<unsigned DIM>
class MeshBasedTissue< DIM >::SpringIterator
Iterator over edges in the mesh, which correspond to springs between cells.
This class takes care of the logic to make sure that you consider each edge exactly once.
Definition at line 401 of file MeshBasedTissue.hpp.
Constructor & Destructor Documentation
template<unsigned DIM> MeshBasedTissue< DIM >::SpringIterator::SpringIterator (MeshBasedTissue & rTissue, typename MutableMesh< DIM, DIM >::EdgeIterator edgeIter) [inline]
Constructor for a new iterator.
Parameters:
rTissue the tissue
edgeIter iterator over edges in the mesh
Definition at line 636 of file MeshBasedTissue.cpp.
References MeshBasedTissue< DIM >::IsGhostNode(), MeshBasedTissue< DIM >::SpringIterator::mEdgeIter, MeshBasedTissue< DIM >::mrMesh, and MeshBasedTissue< DIM >::SpringIterator::mrTissue.
Member Function Documentation
template<unsigned DIM> Node< DIM > * MeshBasedTissue< DIM >::SpringIterator::GetNodeA () [inline]
Get a pointer to the node in the mesh at end A of the spring.
Definition at line 583 of file MeshBasedTissue.cpp.
References MeshBasedTissue< DIM >::SpringIterator::mEdgeIter.
template<unsigned DIM> Node< DIM > * MeshBasedTissue< DIM >::SpringIterator::GetNodeB () [inline]
Get a pointer to the node in the mesh at end B of the spring.
Definition at line 589 of file MeshBasedTissue.cpp.
References MeshBasedTissue< DIM >::SpringIterator::mEdgeIter.
template<unsigned DIM> TissueCell & MeshBasedTissue< DIM >::SpringIterator::rGetCellA () [inline]
Get a *reference* to the cell at end A of the spring.
Definition at line 595 of file MeshBasedTissue.cpp.
References MeshBasedTissue< DIM >::SpringIterator::mEdgeIter, MeshBasedTissue< DIM >::SpringIterator::mrTissue, AbstractTissue< DIM >::rGetCellUsingLocationIndex(), and MeshBasedTissue< DIM >::SpringsEnd().
template<unsigned DIM> TissueCell & MeshBasedTissue< DIM >::SpringIterator::rGetCellB () [inline]
Get a *reference* to the cell at end B of the spring.
Definition at line 602 of file MeshBasedTissue.cpp.
References MeshBasedTissue< DIM >::SpringIterator::mEdgeIter, MeshBasedTissue< DIM >::SpringIterator::mrTissue, AbstractTissue< DIM >::rGetCellUsingLocationIndex(), and MeshBasedTissue< DIM >::SpringsEnd().
template<unsigned DIM> bool MeshBasedTissue< DIM >::SpringIterator::operator!= (const SpringIterator & other)
Comparison not-equal-to.
Parameters:
other SpringIterator with which comparison is made
template<unsigned DIM> MeshBasedTissue< DIM >::SpringIterator & MeshBasedTissue< DIM >::SpringIterator::operator++ () [inline]
Prefix increment operator.
Definition at line 615 of file MeshBasedTissue.cpp.
References MeshBasedTissue< DIM >::IsGhostNode(), MeshBasedTissue< DIM >::SpringIterator::mEdgeIter, MeshBasedTissue< DIM >::SpringIterator::mrTissue, and MeshBasedTissue< DIM >::SpringsEnd().
Member Data Documentation
template<unsigned DIM> std::set<std::set<unsigned> > MeshBasedTissue< DIM >::SpringIterator::mSpringsVisited [private]
Keep track of what edges have been visited.
Definition at line 448 of file MeshBasedTissue.hpp.
template<unsigned DIM> MeshBasedTissue& MeshBasedTissue< DIM >::SpringIterator::mrTissue [private]
The tissue member.
Definition at line 451 of file MeshBasedTissue.hpp.
Referenced by MeshBasedTissue< DIM >::SpringIterator::operator++(), MeshBasedTissue< DIM >::SpringIterator::rGetCellA(), MeshBasedTissue< DIM >::SpringIterator::rGetCellB(), and MeshBasedTissue< DIM >::SpringIterator::SpringIterator().
template<unsigned DIM> MutableMesh<DIM, DIM>::EdgeIterator MeshBasedTissue< DIM >::SpringIterator::mEdgeIter [private]
The edge iterator member.
Definition at line 454 of file MeshBasedTissue.hpp.
Referenced by MeshBasedTissue< DIM >::SpringIterator::GetNodeA(), MeshBasedTissue< DIM >::SpringIterator::GetNodeB(), MeshBasedTissue< DIM >::SpringIterator::operator++(), MeshBasedTissue< DIM >::SpringIterator::rGetCellA(), MeshBasedTissue< DIM >::SpringIterator::rGetCellB(), and MeshBasedTissue< DIM >::SpringIterator::SpringIterator().
The documentation for this class was generated from the following files:
/tmp/release_1/cancer/src/tissue/MeshBasedTissue.hpp
/tmp/release_1/cancer/src/tissue/MeshBasedTissue.cpp