Chaste: LuoRudyIModel1991OdeSystem Class Reference
LuoRudyIModel1991OdeSystem Class Reference
#include <LuoRudyIModel1991OdeSystem.hpp>
Public Member Functions
LuoRudyIModel1991OdeSystem (AbstractIvpOdeSolver *pSolver, AbstractStimulusFunction *pIntracellularStimulus)
~LuoRudyIModel1991OdeSystem ()
void EvaluateYDerivatives (double time, const std::vector< double > &rY, std::vector< double > &rDY)
double GetIIonic ()
double GetIntracellularCalciumConcentration ()
Private Member Functions
void VerifyStateVariables ()
Private Attributes
double fast_sodium_current_E_Na
Static Private Attributes
static const double membrane_C = 1.0
static const double membrane_F = 96484.6
static const double membrane_R = 8314
static const double membrane_T = 310.0
static const double background_current_E_b = -59.87
static const double background_current_g_b = 0.03921
static const double fast_sodium_current_g_Na = 23.0
static const double ionic_concentrations_Ki = 145.0
static const double ionic_concentrations_Ko = 5.4
static const double ionic_concentrations_Nai = 18.0
static const double ionic_concentrations_Nao = 140.0
static const double plateau_potassium_current_g_Kp = 0.0183
static const double time_dependent_potassium_current_PR_NaK = 0.01833
Detailed Description
This class sets up the LuoRudyIModel1991OdeSystem system of equations.
Definition at line 38 of file LuoRudyIModel1991OdeSystem.hpp.
Constructor & Destructor Documentation
LuoRudyIModel1991OdeSystem::LuoRudyIModel1991OdeSystem (AbstractIvpOdeSolver * pSolver, AbstractStimulusFunction * pIntracellularStimulus)
Constructor
Definition at line 38 of file LuoRudyIModel1991OdeSystem.cpp.
References fast_sodium_current_E_Na, AbstractCardiacCell::Init(), OdeSystemInformation< ODE_SYSTEM >::Instance(), and AbstractOdeSystem::mpSystemInfo.
LuoRudyIModel1991OdeSystem::~LuoRudyIModel1991OdeSystem (void)
Destructor
Definition at line 54 of file LuoRudyIModel1991OdeSystem.cpp.
Member Function Documentation
void LuoRudyIModel1991OdeSystem::VerifyStateVariables () [private, virtual]
Range-checking on the current values of the state variables. Make sure all gating variables have are within zero and one, and all concentrations are positive
Reimplemented from AbstractCardiacCell.
Definition at line 257 of file LuoRudyIModel1991OdeSystem.cpp.
References AbstractOdeSystem::DumpState().
void LuoRudyIModel1991OdeSystem::EvaluateYDerivatives (double time, const std::vector< double > & rY, std::vector< double > & rDY) [virtual]
Fill in a vector representing the RHS of the LuoRudyIModel1991OdeSystem system of Odes at each time step, y' = [y1' ... yn']. Some ODE solver will call this function repeatedly to solve for y = [y1 ... yn].
Parameters:
time the current time, in milliseconds
rY current values of the state variables
rDY to be filled in with derivatives
Implements AbstractOdeSystem.
Definition at line 72 of file LuoRudyIModel1991OdeSystem.cpp.
References fast_sodium_current_E_Na, and membrane_C.
double LuoRudyIModel1991OdeSystem::GetIIonic () [virtual]
Computes the total current flowing through the cell membrane, using the current values of the state variables.
Implements AbstractCardiacCell.
Definition at line 201 of file LuoRudyIModel1991OdeSystem.cpp.
References fast_sodium_current_E_Na.
double LuoRudyIModel1991OdeSystem::GetIntracellularCalciumConcentration () [virtual]
[Ca_i] is needed for mechanics, so we explcitly have a Get method (rather than use a get by name type method, to avoid inefficiency when using different cells types of cells). This method by defaults throws an exception, so should be implemented in the concrete class if IntracellularCalciumConcentration is one of the state variables
Reimplemented from AbstractCardiacCell.
Definition at line 58 of file LuoRudyIModel1991OdeSystem.cpp.
Member Data Documentation
const double LuoRudyIModel1991OdeSystem::membrane_C = 1.0 [static, private]
Constants for the LuoRudyIModel1991OdeSystem model
Definition at line 43 of file LuoRudyIModel1991OdeSystem.hpp.
Referenced by EvaluateYDerivatives().
double LuoRudyIModel1991OdeSystem::fast_sodium_current_E_Na [private]
Another parameter, which is a function of the above
Definition at line 58 of file LuoRudyIModel1991OdeSystem.hpp.
Referenced by EvaluateYDerivatives(), GetIIonic(), and LuoRudyIModel1991OdeSystem().
The documentation for this class was generated from the following files:
/tmp/release_1/heart/src/odes/LuoRudyIModel1991OdeSystem.hpp
/tmp/release_1/heart/src/odes/LuoRudyIModel1991OdeSystem.cpp