Chaste: CancerParameters Class Reference
CancerParameters Class Reference
#include <CancerParameters.hpp>
Public Member Functions
double GetStemCellG1Duration ()
double GetTransitCellG1Duration ()
double GetHepaOneCellG1Duration ()
double GetMinimumGapDuration ()
double GetSG2MDuration ()
double GetSDuration ()
double GetG2Duration ()
double GetMDuration ()
unsigned GetMaxTransitGenerations ()
double GetCryptLength ()
double GetCryptWidth ()
double GetSpringStiffness ()
double GetDampingConstantNormal ()
double GetDampingConstantMutant ()
double GetBetaCatSpringScaler ()
double GetApoptosisTime ()
double GetDivisionRestingSpringLength ()
double GetDivisionSeparation ()
double GetHepaOneCellHypoxicConcentration ()
double GetHepaOneCellQuiescentConcentration ()
double GetWntTransitThreshold ()
double GetWntStemThreshold ()
double GetTopOfLinearWntConcentration ()
double GetCriticalHypoxicDuration ()
double GetCryptProjectionParameterA ()
double GetCryptProjectionParameterB ()
double GetApoptoticSpringTensionStiffness ()
double GetApoptoticSpringCompressionStiffness ()
double GetWntChemotaxisStrength ()
double GetSymmetricDivisionProbability ()
double GetAreaBasedDampingConstantParameter ()
double GetMatureCellTargetArea ()
double GetDeformationEnergyParameter ()
double GetMembraneSurfaceEnergyParameter ()
double GetCellCellAdhesionEnergyParameter ()
double GetCellBoundaryAdhesionEnergyParameter ()
void SetStemCellG1Duration (double)
void SetTransitCellG1Duration (double)
void SetHepaOneCellG1Duration (double)
void SetMinimumGapDuration (double)
void SetSDuration (double)
void SetG2Duration (double)
void SetMDuration (double)
void SetMaxTransitGenerations (unsigned)
void SetCryptLength (double)
void SetCryptWidth (double)
void SetSpringStiffness (double)
void SetDampingConstantNormal (double)
void SetDampingConstantMutant (double)
void SetBetaCatSpringScaler (double)
void SetApoptosisTime (double)
void SetDivisionRestingSpringLength (double)
void SetDivisionSeparation (double)
void SetHepaOneCellHypoxicConcentration (double)
void SetHepaOneCellQuiescentConcentration (double)
void SetWntTransitThreshold (double)
void SetWntStemThreshold (double)
void SetTopOfLinearWntConcentration (double)
void SetCriticalHypoxicDuration (double)
void SetHepaOneParameters ()
void SetCryptProjectionParameterA (double)
void SetCryptProjectionParameterB (double)
void SetApoptoticSpringTensionStiffness (double)
void SetApoptoticSpringCompressionStiffness (double)
void SetWntChemotaxisStrength (double)
void SetSymmetricDivisionProbability (double)
void SetAreaBasedDampingConstantParameter (double)
void SetMatureCellTargetArea (double)
void SetDeformationEnergyParameter (double)
void SetMembraneSurfaceEnergyParameter (double)
void SetCellCellAdhesionEnergyParameter (double)
void SetCellBoundaryAdhesionEnergyParameter (double)
void Reset ()
Static Public Member Functions
static CancerParameters * Instance ()
Protected Member Functions
CancerParameters ()
CancerParameters (const CancerParameters &)
CancerParameters & operator= (const CancerParameters &)
Private Member Functions
template<class Archive>
void serialize (Archive &archive, const unsigned int version)
Private Attributes
double mStemCellG1Duration
double mTransitCellG1Duration
double mHepaOneCellG1Duration
double mMinimumGapDuration
double mSDuration
double mG2Duration
double mMDuration
unsigned mMaxTransitGenerations
double mCryptLength
double mCryptWidth
double mSpringStiffness
double mDampingConstantNormal
double mDampingConstantMutant
double mBetaCatSpringScaler
double mApoptosisTime
double mDivisionSeparation
double mDivisionRestingSpringLength
double mHepaOneCellHypoxicConcentration
double mHepaOneCellQuiescentConcentration
double mWntTransitThreshold
double mWntStemThreshold
double mTopOfLinearWntConcentration
double mCriticalHypoxicDuration
double mCryptProjectionParameterA
double mCryptProjectionParameterB
double mApoptoticSpringTensionStiffness
double mApoptoticSpringCompressionStiffness
double mWntChemotaxisStrength
double mSymmetricDivisionProbability
double mAreaBasedDampingConstantParameter
double mMatureCellTargetArea
double mDeformationEnergyParameter
double mMembraneSurfaceEnergyParameter
double mCellCellAdhesionEnergyParameter
double mCellBoundaryAdhesionEnergyParameter
Static Private Attributes
static CancerParameters * mpInstance = NULL
Friends
class boost::serialization::access
Detailed Description
A special singleton class which holds all of the parameters used in the cancer simulations
Because this is a singleton class it can be called from whichever part of the code needs to find out a parameter value, the structure is quite simple with default values given upon initialisation and Set() and Get() methods for each parameter.
For details of each parameter refer to the member variable documentation for this class rather than the Get() and Set() function descriptions.
Definition at line 44 of file CancerParameters.hpp.
Constructor & Destructor Documentation
CancerParameters::CancerParameters () [protected]
Default constructor.
Definition at line 41 of file CancerParameters.cpp.
References mpInstance, and Reset().
CancerParameters::CancerParameters (const CancerParameters &) [protected]
Copy constructor.
Member Function Documentation
CancerParameters * CancerParameters::Instance () [static]
Call this method to access the global parameters holder.
Returns:
a single instance of the class
Definition at line 32 of file CancerParameters.cpp.
References mpInstance.
Referenced by TissueSimulation< DIM >::CalculateDividingCellCentreLocations(), CryptSimulation2d::CalculateDividingCellCentreLocations(), MeshBasedTissueWithGhostNodes< DIM >::CalculateForceBetweenNodes(), GeneralisedLinearSpringForce< DIM >::CalculateForceBetweenNodes(), CryptStatistics::CellIsInSectionPeriodic(), CryptStatistics::GetCryptSection(), MeshBasedTissue< DIM >::GetDampingConstant(), AbstractCellCentreBasedTissue< DIM >::GetDampingConstant(), AbstractCellCycleModel::GetG2Duration(), AbstractCellCycleModel::GetMDuration(), AbstractCellCycleModel::GetSDuration(), StochasticDurationGenerationBasedCellCycleModelCellsGenerator< DIM >::GetTypicalStemCellCycleTime(), SimpleWntCellCycleModelCellsGenerator< DIM >::GetTypicalStemCellCycleTime(), FixedDurationGenerationBasedCellCycleModelCellsGenerator< DIM >::GetTypicalStemCellCycleTime(), StochasticDurationGenerationBasedCellCycleModelCellsGenerator< DIM >::GetTypicalTransitCellCycleTime(), SimpleWntCellCycleModelCellsGenerator< DIM >::GetTypicalTransitCellCycleTime(), FixedDurationGenerationBasedCellCycleModelCellsGenerator< DIM >::GetTypicalTransitCellCycleTime(), WntConcentration::GetWntGradient(), WntConcentration::GetWntLevel(), HoneycombMeshGenerator::HoneycombMeshGenerator(), AbstractSimpleGenerationBasedCellCycleModel::InitialiseDaughterCell(), AbstractSimpleGenerationBasedCellCycleModel::ResetForDivision(), TissueSimulation< 2 >::serialize(), SloughingCellKiller::serialize(), WntConcentration::serialize(), AbstractCellCycleModel::serialize(), SimpleWntCellCycleModel::SetG1Duration(), AbstractSimpleCellCycleModel::SetG1Duration(), StochasticWntCellCycleModel::SetG2Duration(), AbstractCancerTestSuite::setUp(), TissueCell::StartApoptosis(), SloughingCellKiller::TestAndLabelCellsForApoptosisOrDeath(), TissueSimulation< DIM >::TissueSimulation(), SimpleWntCellCycleModel::UpdateCellCyclePhase(), MeshBasedTissueWithGhostNodes< DIM >::UpdateGhostPositions(), and LinearSpringWithVariableSpringConstantsForce< DIM >::VariableSpringConstantMultiplicationFactor().
double CancerParameters::GetStemCellG1Duration ()
Returns:
mStemCellG1Duration
Definition at line 135 of file CancerParameters.cpp.
References mStemCellG1Duration.
Referenced by StochasticDurationGenerationBasedCellCycleModelCellsGenerator< DIM >::GetTypicalStemCellCycleTime(), SimpleWntCellCycleModelCellsGenerator< DIM >::GetTypicalStemCellCycleTime(), FixedDurationGenerationBasedCellCycleModelCellsGenerator< DIM >::GetTypicalStemCellCycleTime(), SimpleWntCellCycleModel::SetG1Duration(), and AbstractSimpleCellCycleModel::SetG1Duration().
double CancerParameters::GetTransitCellG1Duration ()
Returns:
mTransitCellG1Duration
Definition at line 139 of file CancerParameters.cpp.
References mTransitCellG1Duration.
Referenced by StochasticDurationGenerationBasedCellCycleModelCellsGenerator< DIM >::GetTypicalTransitCellCycleTime(), SimpleWntCellCycleModelCellsGenerator< DIM >::GetTypicalTransitCellCycleTime(), FixedDurationGenerationBasedCellCycleModelCellsGenerator< DIM >::GetTypicalTransitCellCycleTime(), SimpleWntCellCycleModel::SetG1Duration(), and AbstractSimpleCellCycleModel::SetG1Duration().
double CancerParameters::GetHepaOneCellG1Duration ()
Returns:
mHepaOneCellG1Duration
Definition at line 143 of file CancerParameters.cpp.
References mHepaOneCellG1Duration.
double CancerParameters::GetMinimumGapDuration ()
Returns:
mMinimumGapDuration
Definition at line 147 of file CancerParameters.cpp.
References mMinimumGapDuration.
Referenced by SimpleWntCellCycleModel::SetG1Duration(), and StochasticWntCellCycleModel::SetG2Duration().
double CancerParameters::GetSG2MDuration ()
Returns:
mSDuration + mG2Duration + mMDuration
Definition at line 151 of file CancerParameters.cpp.
References mG2Duration, mMDuration, and mSDuration.
Referenced by StochasticDurationGenerationBasedCellCycleModelCellsGenerator< DIM >::GetTypicalStemCellCycleTime(), SimpleWntCellCycleModelCellsGenerator< DIM >::GetTypicalStemCellCycleTime(), FixedDurationGenerationBasedCellCycleModelCellsGenerator< DIM >::GetTypicalStemCellCycleTime(), StochasticDurationGenerationBasedCellCycleModelCellsGenerator< DIM >::GetTypicalTransitCellCycleTime(), SimpleWntCellCycleModelCellsGenerator< DIM >::GetTypicalTransitCellCycleTime(), and FixedDurationGenerationBasedCellCycleModelCellsGenerator< DIM >::GetTypicalTransitCellCycleTime().
double CancerParameters::GetSDuration ()
Returns:
mSDuration
Definition at line 155 of file CancerParameters.cpp.
References mSDuration.
Referenced by AbstractCellCycleModel::GetSDuration().
double CancerParameters::GetG2Duration ()
Returns:
mG2Duration
Definition at line 159 of file CancerParameters.cpp.
References mG2Duration.
Referenced by AbstractCellCycleModel::GetG2Duration(), and StochasticWntCellCycleModel::SetG2Duration().
double CancerParameters::GetMDuration ()
Returns:
mMDuration
Definition at line 163 of file CancerParameters.cpp.
References mMDuration.
Referenced by GeneralisedLinearSpringForce< DIM >::CalculateForceBetweenNodes(), and AbstractCellCycleModel::GetMDuration().
unsigned CancerParameters::GetMaxTransitGenerations ()
Returns:
mMaxTransitGenerations
Definition at line 167 of file CancerParameters.cpp.
References mMaxTransitGenerations.
double CancerParameters::GetCryptLength ()
Returns:
mCryptLength
Definition at line 171 of file CancerParameters.cpp.
References mCryptLength.
Referenced by WntConcentration::GetWntGradient(), WntConcentration::GetWntLevel(), and SloughingCellKiller::TestAndLabelCellsForApoptosisOrDeath().
double CancerParameters::GetCryptWidth ()
Returns:
mCryptWidth
Definition at line 175 of file CancerParameters.cpp.
References mCryptWidth.
Referenced by CryptStatistics::CellIsInSectionPeriodic(), CryptStatistics::GetCryptSection(), and SloughingCellKiller::TestAndLabelCellsForApoptosisOrDeath().
double CancerParameters::GetSpringStiffness ()
Returns:
mSpringStiffness
Definition at line 179 of file CancerParameters.cpp.
References mSpringStiffness.
Referenced by MeshBasedTissueWithGhostNodes< DIM >::CalculateForceBetweenNodes(), GeneralisedLinearSpringForce< DIM >::CalculateForceBetweenNodes(), and LinearSpringWithVariableSpringConstantsForce< DIM >::VariableSpringConstantMultiplicationFactor().
double CancerParameters::GetDampingConstantNormal ()
Returns:
mDampingConstantNormal
Definition at line 183 of file CancerParameters.cpp.
References mDampingConstantNormal.
Referenced by AbstractCellCentreBasedTissue< DIM >::GetDampingConstant(), and MeshBasedTissueWithGhostNodes< DIM >::UpdateGhostPositions().
double CancerParameters::GetDampingConstantMutant ()
Returns:
mDampingConstantMutant
Definition at line 187 of file CancerParameters.cpp.
References mDampingConstantMutant.
Referenced by AbstractCellCentreBasedTissue< DIM >::GetDampingConstant().
double CancerParameters::GetBetaCatSpringScaler ()
Returns:
mBetaCatSpringScaler
Definition at line 191 of file CancerParameters.cpp.
References mBetaCatSpringScaler.
Referenced by LinearSpringWithVariableSpringConstantsForce< DIM >::VariableSpringConstantMultiplicationFactor().
double CancerParameters::GetApoptosisTime ()
Returns:
mApoptosisTime
Definition at line 195 of file CancerParameters.cpp.
References mApoptosisTime.
Referenced by GeneralisedLinearSpringForce< DIM >::CalculateForceBetweenNodes(), and TissueCell::StartApoptosis().
double CancerParameters::GetDivisionRestingSpringLength ()
Returns:
mDivisionRestingSpringLength
Definition at line 199 of file CancerParameters.cpp.
References mDivisionRestingSpringLength.
Referenced by GeneralisedLinearSpringForce< DIM >::CalculateForceBetweenNodes().
double CancerParameters::GetDivisionSeparation ()
Returns:
mDivisionSeparation
Definition at line 203 of file CancerParameters.cpp.
References mDivisionSeparation.
Referenced by TissueSimulation< DIM >::CalculateDividingCellCentreLocations(), and CryptSimulation2d::CalculateDividingCellCentreLocations().
double CancerParameters::GetHepaOneCellHypoxicConcentration ()
Returns:
mHepaOneCellHypoxicConcentration
Definition at line 207 of file CancerParameters.cpp.
References mHepaOneCellHypoxicConcentration.
double CancerParameters::GetHepaOneCellQuiescentConcentration ()
Returns:
mHepaOneCellQuiescentConcentration
Definition at line 211 of file CancerParameters.cpp.
References mHepaOneCellQuiescentConcentration.
double CancerParameters::GetWntTransitThreshold ()
Returns:
mWntTransitThreshold
Definition at line 215 of file CancerParameters.cpp.
References mWntTransitThreshold.
Referenced by SimpleWntCellCycleModel::UpdateCellCyclePhase().
double CancerParameters::GetWntStemThreshold ()
Returns:
mWntStemThreshold
Definition at line 219 of file CancerParameters.cpp.
References mWntStemThreshold.
Referenced by SimpleWntCellCycleModel::UpdateCellCyclePhase().
double CancerParameters::GetTopOfLinearWntConcentration ()
Returns:
mTopOfLinearWntConcentration
Definition at line 223 of file CancerParameters.cpp.
References mTopOfLinearWntConcentration.
Referenced by WntConcentration::GetWntGradient(), and WntConcentration::GetWntLevel().
double CancerParameters::GetCriticalHypoxicDuration ()
Returns:
mCriticalHypoxicDuration
Definition at line 227 of file CancerParameters.cpp.
References mCriticalHypoxicDuration.
double CancerParameters::GetCryptProjectionParameterA ()
Returns:
mCryptProjectionParameterA
Definition at line 231 of file CancerParameters.cpp.
References mCryptProjectionParameterA.
Referenced by WntConcentration::GetWntGradient(), and WntConcentration::GetWntLevel().
double CancerParameters::GetCryptProjectionParameterB ()
Returns:
mCryptProjectionParameterB
Definition at line 235 of file CancerParameters.cpp.
References mCryptProjectionParameterB.
Referenced by WntConcentration::GetWntGradient(), and WntConcentration::GetWntLevel().
double CancerParameters::GetApoptoticSpringTensionStiffness ()
Returns:
mApoptoticSpringTensionStiffness
Definition at line 239 of file CancerParameters.cpp.
References mApoptoticSpringTensionStiffness.
Referenced by LinearSpringWithVariableSpringConstantsForce< DIM >::VariableSpringConstantMultiplicationFactor().
double CancerParameters::GetApoptoticSpringCompressionStiffness ()
Returns:
mApoptoticSpringCompressionStiffness
Definition at line 243 of file CancerParameters.cpp.
References mApoptoticSpringCompressionStiffness.
Referenced by LinearSpringWithVariableSpringConstantsForce< DIM >::VariableSpringConstantMultiplicationFactor().
double CancerParameters::GetWntChemotaxisStrength ()
Returns:
mWntChemotaxisStrength
Definition at line 247 of file CancerParameters.cpp.
References mWntChemotaxisStrength.
double CancerParameters::GetSymmetricDivisionProbability ()
Returns:
mSymmetricDivisionProbability
Definition at line 251 of file CancerParameters.cpp.
References mSymmetricDivisionProbability.
double CancerParameters::GetAreaBasedDampingConstantParameter ()
Returns:
mAreaBasedDampingConstantParameter
Definition at line 255 of file CancerParameters.cpp.
References mAreaBasedDampingConstantParameter.
Referenced by MeshBasedTissue< DIM >::GetDampingConstant().
double CancerParameters::GetMatureCellTargetArea ()
Returns:
mMatureCellTargetArea
Definition at line 259 of file CancerParameters.cpp.
References mMatureCellTargetArea.
double CancerParameters::GetDeformationEnergyParameter ()
Returns:
mDeformationEnergyParameter
Definition at line 263 of file CancerParameters.cpp.
References mDeformationEnergyParameter.
double CancerParameters::GetMembraneSurfaceEnergyParameter ()
Returns:
mMembraneSurfaceEnergyParameter
Definition at line 267 of file CancerParameters.cpp.
References mMembraneSurfaceEnergyParameter.
double CancerParameters::GetCellCellAdhesionEnergyParameter ()
Returns:
mCellCellAdhesionEnergyParameter
Definition at line 271 of file CancerParameters.cpp.
References mCellCellAdhesionEnergyParameter.
double CancerParameters::GetCellBoundaryAdhesionEnergyParameter ()
Returns:
mCellBoundaryAdhesionEnergyParameter
Definition at line 275 of file CancerParameters.cpp.
References mCellBoundaryAdhesionEnergyParameter.
void CancerParameters::SetStemCellG1Duration (double stemCellG1Duration)
Set mStemCellG1Duration.
Definition at line 284 of file CancerParameters.cpp.
References mStemCellG1Duration.
void CancerParameters::SetTransitCellG1Duration (double transitCellG1Duration)
Set mTransitCellG1Duration.
Definition at line 289 of file CancerParameters.cpp.
References mTransitCellG1Duration.
void CancerParameters::SetHepaOneCellG1Duration (double hepaOneCellG1Duration)
Set mHepaOneCellG1Duration.
Definition at line 294 of file CancerParameters.cpp.
References mHepaOneCellG1Duration.
void CancerParameters::SetMinimumGapDuration (double minimumGapDuration)
Set mMinimumGapDuration.
Definition at line 299 of file CancerParameters.cpp.
References mMinimumGapDuration.
void CancerParameters::SetSDuration (double SDuration)
Set mSDuration.
Definition at line 304 of file CancerParameters.cpp.
References mSDuration.
void CancerParameters::SetG2Duration (double G2Duration)
Set mG2Duration.
Definition at line 309 of file CancerParameters.cpp.
References mG2Duration.
void CancerParameters::SetMDuration (double MDuration)
Set mMDuration.
Definition at line 314 of file CancerParameters.cpp.
References mMDuration.
void CancerParameters::SetMaxTransitGenerations (unsigned maxTransitGens)
Set mMaxTransitGenerations.
Definition at line 319 of file CancerParameters.cpp.
References mMaxTransitGenerations.
void CancerParameters::SetCryptLength (double cryptLength)
Set mCryptLength.
Definition at line 323 of file CancerParameters.cpp.
References mCryptLength.
Referenced by HoneycombMeshGenerator::HoneycombMeshGenerator().
void CancerParameters::SetCryptWidth (double cryptWidth)
Set mCryptWidth.
Definition at line 328 of file CancerParameters.cpp.
References mCryptWidth.
Referenced by HoneycombMeshGenerator::HoneycombMeshGenerator().
void CancerParameters::SetSpringStiffness (double springStiffness)
Set mSpringStiffness.
Definition at line 333 of file CancerParameters.cpp.
References mSpringStiffness.
void CancerParameters::SetDampingConstantNormal (double dampingConstantNormal)
Set mDampingConstantNormal.
Definition at line 338 of file CancerParameters.cpp.
References mDampingConstantNormal.
void CancerParameters::SetDampingConstantMutant (double dampingConstantMutant)
Set mDampingConstantMutant.
Definition at line 343 of file CancerParameters.cpp.
References mDampingConstantMutant.
void CancerParameters::SetBetaCatSpringScaler (double betaCatSpringScaler)
Set mBetaCatSpringScaler.
Definition at line 348 of file CancerParameters.cpp.
References mBetaCatSpringScaler.
void CancerParameters::SetApoptosisTime (double apoptosisTime)
Set mApoptosisTime.
Definition at line 353 of file CancerParameters.cpp.
References mApoptosisTime.
void CancerParameters::SetDivisionRestingSpringLength (double divisionRestingSpringLength)
Set mDivisionRestingSpringLength.
Definition at line 358 of file CancerParameters.cpp.
References mDivisionRestingSpringLength.
void CancerParameters::SetDivisionSeparation (double divisionSeparation)
Set mDivisionSeparation.
Definition at line 365 of file CancerParameters.cpp.
References mDivisionSeparation.
void CancerParameters::SetHepaOneCellHypoxicConcentration (double hepaOneCellHypoxicConcentration)
Set mHepaOneCellHypoxicConcentration.
Definition at line 371 of file CancerParameters.cpp.
References mHepaOneCellHypoxicConcentration.
void CancerParameters::SetHepaOneCellQuiescentConcentration (double hepaOneCellQuiescentConcentration)
Set mHepaOneCellQuiescentConcentration.
Definition at line 377 of file CancerParameters.cpp.
References mHepaOneCellQuiescentConcentration.
void CancerParameters::SetWntTransitThreshold (double wntThreshold)
Set mWntTransitThreshold.
Definition at line 383 of file CancerParameters.cpp.
References mWntTransitThreshold.
void CancerParameters::SetWntStemThreshold (double wntThreshold)
Set mWntStemThreshold.
Definition at line 389 of file CancerParameters.cpp.
References mWntStemThreshold.
void CancerParameters::SetTopOfLinearWntConcentration (double top)
Set mTopOfLinearWntConcentration.
Definition at line 395 of file CancerParameters.cpp.
References mTopOfLinearWntConcentration.
void CancerParameters::SetCriticalHypoxicDuration (double criticalHypoxicDuration)
Set mCriticalHypoxicDuration.
Definition at line 401 of file CancerParameters.cpp.
References mCriticalHypoxicDuration.
void CancerParameters::SetHepaOneParameters ()
Set mHepaOneParameters.
Definition at line 406 of file CancerParameters.cpp.
References mHepaOneCellG1Duration, and mStemCellG1Duration.
void CancerParameters::SetCryptProjectionParameterA (double cryptProjectionParameterA)
Set mCryptProjectionParameterA.
Definition at line 410 of file CancerParameters.cpp.
References mCryptProjectionParameterA.
void CancerParameters::SetCryptProjectionParameterB (double cryptProjectionParameterB)
Set mCryptProjectionParameterB.
Definition at line 415 of file CancerParameters.cpp.
References mCryptProjectionParameterB.
void CancerParameters::SetApoptoticSpringTensionStiffness (double apoptoticSpringTensionStiffness)
Set mApoptoticSpringTensionStiffness.
Definition at line 420 of file CancerParameters.cpp.
References mApoptoticSpringTensionStiffness.
void CancerParameters::SetApoptoticSpringCompressionStiffness (double apoptoticSpringCompressionStiffness)
Set mApoptoticSpringCompressionStiffness.
Definition at line 425 of file CancerParameters.cpp.
References mApoptoticSpringCompressionStiffness.
void CancerParameters::SetWntChemotaxisStrength (double wntChemotaxisStrength)
Set mWntChemotaxisStrength.
Definition at line 430 of file CancerParameters.cpp.
References mWntChemotaxisStrength.
void CancerParameters::SetSymmetricDivisionProbability (double symmetricDivisionProbability)
Set mSymmetricDivisionProbability.
Definition at line 435 of file CancerParameters.cpp.
References mSymmetricDivisionProbability.
void CancerParameters::SetAreaBasedDampingConstantParameter (double areaBasedDampingConstantParameter)
Set mAreaBasedDampingConstantParameter.
Definition at line 441 of file CancerParameters.cpp.
References mAreaBasedDampingConstantParameter.
void CancerParameters::SetMatureCellTargetArea (double matureCellTargetArea)
Set mMatureCellTargetArea.
Definition at line 446 of file CancerParameters.cpp.
References mMatureCellTargetArea.
void CancerParameters::SetDeformationEnergyParameter (double deformationEnergyParameter)
Set mDeformationEnergyParameter.
Definition at line 451 of file CancerParameters.cpp.
References mDeformationEnergyParameter.
void CancerParameters::SetMembraneSurfaceEnergyParameter (double membraneSurfaceEnergyParameter)
Set mMembraneSurfaceEnergyParameter.
Definition at line 455 of file CancerParameters.cpp.
References mMembraneSurfaceEnergyParameter.
void CancerParameters::SetCellCellAdhesionEnergyParameter (double cellCellAdhesionEnergyParameter)
Set mCellCellAdhesionEnergyParameter.
Definition at line 459 of file CancerParameters.cpp.
References mCellCellAdhesionEnergyParameter.
void CancerParameters::SetCellBoundaryAdhesionEnergyParameter (double cellBoundaryAdhesionEnergyParameter)
Set mCellBoundaryAdhesionEnergyParameter.
Definition at line 463 of file CancerParameters.cpp.
References mCellBoundaryAdhesionEnergyParameter.
void CancerParameters::Reset ()
Reset all parameters to their defaults
mStemCellG1Duration has units of hours mTransitCellG1Duration has units of hours mHepaOneCellG1Duration has units of hours mMinimumGapDuration has units of hours mSDuration has units of hours mG2Duration has units of hours mMDuration has units of hours mMaxTransitGenerations has no units mCryptWidth has units of cell size at equilibrium rest length mCryptLength has units of cell size at equilibrium rest length mSpringStiffness has units of N/m = kg s^-2 mDampingConstantNormal has units of kg s^-1 mDampingConstantMutant has units of kg s^-1 mBetaCatSpringScaler has no units mApoptosisTime has units of hours mDivisionRestingSpringLength has units of cell size at equilibrium rest length mDivisionSeparation has units of cell size at equilibrium rest length mHepaOneCellHypoxicConcentration has no units mHepaOneCellQuiescentConcentration has no units mWntTransitThreshold has no units mWntStemThreshold has no units mTopOfLinearWntConcentration has no units (proportion of mCryptLength) mCriticalHypoxicDuration has units of hours mCryptProjectionParameterA has no units mCryptProjectionParameterB has no units mApoptoticSpringTensionStiffness has the same units as mSpringStiffness mApoptoticSpringCompressionStiffness has the same units as mSpringStiffness mWntChemotaxisStrength has no units mSymmetricDivisionProbability has no units mAreaBasedDampingConstantParameter has no units mMatureCellTargetArea has no units mDeformationEnergyParameter has ? units mMembraneSurfaceEnergyParameter has ? units mCellCellAdhesionEnergyParameter has ? units mCellBoundaryAdhesionEnergyParameter has ? units
Definition at line 86 of file CancerParameters.cpp.
References mApoptosisTime, mApoptoticSpringCompressionStiffness, mApoptoticSpringTensionStiffness, mAreaBasedDampingConstantParameter, mBetaCatSpringScaler, mCellBoundaryAdhesionEnergyParameter, mCellCellAdhesionEnergyParameter, mCriticalHypoxicDuration, mCryptLength, mCryptProjectionParameterA, mCryptProjectionParameterB, mCryptWidth, mDampingConstantMutant, mDampingConstantNormal, mDeformationEnergyParameter, mDivisionRestingSpringLength, mDivisionSeparation, mG2Duration, mHepaOneCellG1Duration, mHepaOneCellHypoxicConcentration, mHepaOneCellQuiescentConcentration, mMatureCellTargetArea, mMaxTransitGenerations, mMDuration, mMembraneSurfaceEnergyParameter, mMinimumGapDuration, mSDuration, mSpringStiffness, mStemCellG1Duration, mSymmetricDivisionProbability, mTopOfLinearWntConcentration, mTransitCellG1Duration, mWntChemotaxisStrength, mWntStemThreshold, and mWntTransitThreshold.
Referenced by CancerParameters(), and AbstractCancerTestSuite::setUp().
CancerParameters& CancerParameters::operator= (const CancerParameters &) [protected]
Overloaded assignement operator.
template<class Archive> void CancerParameters::serialize (Archive & archive, const unsigned int version) [inline, private]
As with other singleton classes, ensure the instance of this class is serialized directly before being serialized via a pointer.
Parameters:
archive
version
Definition at line 582 of file CancerParameters.hpp.
References mApoptosisTime, mApoptoticSpringCompressionStiffness, mApoptoticSpringTensionStiffness, mAreaBasedDampingConstantParameter, mBetaCatSpringScaler, mCellBoundaryAdhesionEnergyParameter, mCellCellAdhesionEnergyParameter, mCriticalHypoxicDuration, mCryptLength, mCryptProjectionParameterA, mCryptProjectionParameterB, mCryptWidth, mDampingConstantMutant, mDampingConstantNormal, mDeformationEnergyParameter, mG2Duration, mHepaOneCellG1Duration, mHepaOneCellHypoxicConcentration, mHepaOneCellQuiescentConcentration, mMatureCellTargetArea, mMaxTransitGenerations, mMDuration, mMembraneSurfaceEnergyParameter, mMinimumGapDuration, mSDuration, mSpringStiffness, mStemCellG1Duration, mSymmetricDivisionProbability, mTopOfLinearWntConcentration, mTransitCellG1Duration, mWntChemotaxisStrength, mWntStemThreshold, and mWntTransitThreshold.
Friends And Related Function Documentation
friend class boost::serialization::access [friend]
Needed for serialization.
Definition at line 572 of file CancerParameters.hpp.
Member Data Documentation
CancerParameters * CancerParameters::mpInstance = NULL [static, private]
The single instance of the class
Definition at line 370 of file CancerParameters.hpp.
Referenced by CancerParameters(), and Instance().
double CancerParameters::mStemCellG1Duration [private]
Duration of G1 phase for stem cells. May be used as a mean duration for stochastic cell cycle models.
Definition at line 377 of file CancerParameters.hpp.
Referenced by GetStemCellG1Duration(), Reset(), serialize(), SetHepaOneParameters(), and SetStemCellG1Duration().
double CancerParameters::mTransitCellG1Duration [private]
Duration of G1 phase for transit cells. May be used as a mean duration for stochastic cell cycle models.
Definition at line 383 of file CancerParameters.hpp.
Referenced by GetTransitCellG1Duration(), Reset(), serialize(), and SetTransitCellG1Duration().
double CancerParameters::mHepaOneCellG1Duration [private]
Duration of G1 phase for HEPA-1 cells, for use in monolayer/spheroid simulations. May be used as a mean duration for stochastic cell cycle models.
Definition at line 389 of file CancerParameters.hpp.
Referenced by GetHepaOneCellG1Duration(), Reset(), serialize(), SetHepaOneCellG1Duration(), and SetHepaOneParameters().
double CancerParameters::mMinimumGapDuration [private]
Minimum possbile duration of either of the gap phases (G1 or G2). Used to guarantee a strictly positive duration in cell cycle models that use normal random deviates for G1 or G2 phases.
Definition at line 396 of file CancerParameters.hpp.
Referenced by GetMinimumGapDuration(), Reset(), serialize(), and SetMinimumGapDuration().
double CancerParameters::mSDuration [private]
Duration of S phase for all cell types.
Definition at line 401 of file CancerParameters.hpp.
Referenced by GetSDuration(), GetSG2MDuration(), Reset(), serialize(), and SetSDuration().
double CancerParameters::mG2Duration [private]
Duration of G2 phase for all cell types.
Definition at line 406 of file CancerParameters.hpp.
Referenced by GetG2Duration(), GetSG2MDuration(), Reset(), serialize(), and SetG2Duration().
double CancerParameters::mMDuration [private]
Duration of M phase for all cell types.
Definition at line 411 of file CancerParameters.hpp.
Referenced by GetMDuration(), GetSG2MDuration(), Reset(), serialize(), and SetMDuration().
unsigned CancerParameters::mMaxTransitGenerations [private]
How many generations a transit cell lives for before becoming fully differentiated.
Definition at line 416 of file CancerParameters.hpp.
Referenced by GetMaxTransitGenerations(), Reset(), serialize(), and SetMaxTransitGenerations().
double CancerParameters::mCryptLength [private]
The length of the crypt, non-dimensionalised with cell length. This parameter determines when cells are sloughed from the crypt.
Definition at line 422 of file CancerParameters.hpp.
Referenced by GetCryptLength(), Reset(), serialize(), and SetCryptLength().
double CancerParameters::mCryptWidth [private]
The width of the crypt, non-dimensionalised with cell length. This determines when cells are sloughed from the crypt in 2D.
Definition at line 428 of file CancerParameters.hpp.
Referenced by GetCryptWidth(), Reset(), serialize(), and SetCryptWidth().
double CancerParameters::mSpringStiffness [private]
Spring stiffness. Represented by the parameter mu in the model by Meineke et al (2001).
Definition at line 434 of file CancerParameters.hpp.
Referenced by GetSpringStiffness(), Reset(), serialize(), and SetSpringStiffness().
double CancerParameters::mDampingConstantNormal [private]
Damping constant for normal cells. Represented by the parameter eta in the model by Meineke et al (2001).
Definition at line 440 of file CancerParameters.hpp.
Referenced by GetDampingConstantNormal(), Reset(), serialize(), and SetDampingConstantNormal().
double CancerParameters::mDampingConstantMutant [private]
Damping constant for mutant cells.
Definition at line 445 of file CancerParameters.hpp.
Referenced by GetDampingConstantMutant(), Reset(), serialize(), and SetDampingConstantMutant().
double CancerParameters::mBetaCatSpringScaler [private]
Scaling factor for beta catenin to spring strength
Definition at line 450 of file CancerParameters.hpp.
Referenced by GetBetaCatSpringScaler(), Reset(), serialize(), and SetBetaCatSpringScaler().
double CancerParameters::mApoptosisTime [private]
The time it takes for a cell to fully undergo apoptosis
Definition at line 455 of file CancerParameters.hpp.
Referenced by GetApoptosisTime(), Reset(), serialize(), and SetApoptosisTime().
double CancerParameters::mDivisionSeparation [private]
Initial separation placement of mother/daughter cells at birth
Definition at line 460 of file CancerParameters.hpp.
Referenced by GetDivisionSeparation(), Reset(), and SetDivisionSeparation().
double CancerParameters::mDivisionRestingSpringLength [private]
Initial resting spring length after cell division. The value of thiis parameter should be larger than mDivisionSeparation, because of pressure from neighbouring springs.
Definition at line 467 of file CancerParameters.hpp.
Referenced by GetDivisionRestingSpringLength(), Reset(), and SetDivisionRestingSpringLength().
double CancerParameters::mHepaOneCellHypoxicConcentration [private]
Non-dimensionalized oxygen concentration below which HEPA-1 cells are considered to be hypoxic. A prolonged period of hypoxia causes the cell to become apoptotic.
Definition at line 474 of file CancerParameters.hpp.
Referenced by GetHepaOneCellHypoxicConcentration(), Reset(), serialize(), and SetHepaOneCellHypoxicConcentration().
double CancerParameters::mHepaOneCellQuiescentConcentration [private]
Non-dimensionalized oxygen concentration below which HEPA-1 cells are considered to be quiescent and slow their progress through the G1 phase of the cell cycle.
Definition at line 481 of file CancerParameters.hpp.
Referenced by GetHepaOneCellQuiescentConcentration(), Reset(), serialize(), and SetHepaOneCellQuiescentConcentration().
double CancerParameters::mWntTransitThreshold [private]
Non-dimensionalized Wnt threshold, above which cells progress through the cell cycle.
Definition at line 486 of file CancerParameters.hpp.
Referenced by GetWntTransitThreshold(), Reset(), serialize(), and SetWntTransitThreshold().
double CancerParameters::mWntStemThreshold [private]
Non-dimensionalized Wnt threshold, above which cells behave as stem cells.
Definition at line 491 of file CancerParameters.hpp.
Referenced by GetWntStemThreshold(), Reset(), serialize(), and SetWntStemThreshold().
double CancerParameters::mTopOfLinearWntConcentration [private]
The proportion of the crypt that has a Wnt gradient. The Wnt concentration goes to zero at this height up the crypt.
Definition at line 497 of file CancerParameters.hpp.
Referenced by GetTopOfLinearWntConcentration(), Reset(), serialize(), and SetTopOfLinearWntConcentration().
double CancerParameters::mCriticalHypoxicDuration [private]
Non-dimensionalized critical hypoxic duration.
Definition at line 502 of file CancerParameters.hpp.
Referenced by GetCriticalHypoxicDuration(), Reset(), serialize(), and SetCriticalHypoxicDuration().
double CancerParameters::mCryptProjectionParameterA [private]
Parameter a, for use in crypt projection simulations, in which the crypt surface is given in cylindrical polar coordinates by z = a*r^b.
Definition at line 508 of file CancerParameters.hpp.
Referenced by GetCryptProjectionParameterA(), Reset(), serialize(), and SetCryptProjectionParameterA().
double CancerParameters::mCryptProjectionParameterB [private]
Parameter b, for use in crypt projection simulations, in which the crypt surface is given in cylindrical polar coordinates by z = a*r^b.
Definition at line 514 of file CancerParameters.hpp.
Referenced by GetCryptProjectionParameterB(), Reset(), serialize(), and SetCryptProjectionParameterB().
double CancerParameters::mApoptoticSpringTensionStiffness [private]
Non-dimensionalized 'stiffness' of a apoptotic cell under tension.
Definition at line 519 of file CancerParameters.hpp.
Referenced by GetApoptoticSpringTensionStiffness(), Reset(), serialize(), and SetApoptoticSpringTensionStiffness().
double CancerParameters::mApoptoticSpringCompressionStiffness [private]
Non-dimensionalized 'stiffness' of a apoptotic cell under compression.
Definition at line 524 of file CancerParameters.hpp.
Referenced by GetApoptoticSpringCompressionStiffness(), Reset(), serialize(), and SetApoptoticSpringCompressionStiffness().
double CancerParameters::mWntChemotaxisStrength [private]
Strength of Wnt-based chemotactic force.
Definition at line 529 of file CancerParameters.hpp.
Referenced by GetWntChemotaxisStrength(), Reset(), serialize(), and SetWntChemotaxisStrength().
double CancerParameters::mSymmetricDivisionProbability [private]
Probability of symmetric division.
Definition at line 534 of file CancerParameters.hpp.
Referenced by GetSymmetricDivisionProbability(), Reset(), serialize(), and SetSymmetricDivisionProbability().
double CancerParameters::mAreaBasedDampingConstantParameter [private]
Non-dimensional parameter d0 for use in area-based damping constant calculations.
Definition at line 539 of file CancerParameters.hpp.
Referenced by GetAreaBasedDampingConstantParameter(), Reset(), serialize(), and SetAreaBasedDampingConstantParameter().
double CancerParameters::mMatureCellTargetArea [private]
Non-dimensional target area of a mature (fully-grown) TissueCell. For use in vertex-based models.
Definition at line 545 of file CancerParameters.hpp.
Referenced by GetMatureCellTargetArea(), Reset(), serialize(), and SetMatureCellTargetArea().
double CancerParameters::mDeformationEnergyParameter [private]
Cell deformation energy parameter. For use in vertex-based models.
Definition at line 551 of file CancerParameters.hpp.
Referenced by GetDeformationEnergyParameter(), Reset(), serialize(), and SetDeformationEnergyParameter().
double CancerParameters::mMembraneSurfaceEnergyParameter [private]
Cell membrane energy parameter. For use in vertex-based models.
Definition at line 557 of file CancerParameters.hpp.
Referenced by GetMembraneSurfaceEnergyParameter(), Reset(), serialize(), and SetMembraneSurfaceEnergyParameter().
double CancerParameters::mCellCellAdhesionEnergyParameter [private]
Cell-cell adhesion energy parameter. For use in vertex-based models.
Definition at line 563 of file CancerParameters.hpp.
Referenced by GetCellCellAdhesionEnergyParameter(), Reset(), serialize(), and SetCellCellAdhesionEnergyParameter().
double CancerParameters::mCellBoundaryAdhesionEnergyParameter [private]
Cell-boundary adhesion energy parameter. For use in vertex-based models.
Definition at line 569 of file CancerParameters.hpp.
Referenced by GetCellBoundaryAdhesionEnergyParameter(), Reset(), serialize(), and SetCellBoundaryAdhesionEnergyParameter().
The documentation for this class was generated from the following files:
/tmp/release_1/cancer/src/common/CancerParameters.hpp
/tmp/release_1/cancer/src/common/CancerParameters.cpp