Chaste: StochasticDurationGenerationBasedCellCycleModelCellsGenerator< DIM > Class Template Reference
StochasticDurationGenerationBasedCellCycleModelCellsGenerator< DIM > Class Template Reference
#include <StochasticDurationGenerationBasedCellCycleModelCellsGenerator.hpp>
Public Member Functions
AbstractCellCycleModel * CreateCellCycleModel ()
double GetTypicalTransitCellCycleTime ()
double GetTypicalStemCellCycleTime ()
virtual bool CellsCanDifferentiate ()
Detailed Description
template<unsigned DIM>
class StochasticDurationGenerationBasedCellCycleModelCellsGenerator< DIM >
A helper class for generating a vector of cells with StochasticDurationGenerationBasedCellCycleModels for a given mesh.
Definition at line 39 of file StochasticDurationGenerationBasedCellCycleModelCellsGenerator.hpp.
Member Function Documentation
template<unsigned DIM> AbstractCellCycleModel * StochasticDurationGenerationBasedCellCycleModelCellsGenerator< DIM >::CreateCellCycleModel () [inline, virtual]
Returns:
a pointer to a new StochasticDurationGenerationBasedCellCycleModel.
Implements AbstractCellsGenerator< DIM >.
Definition at line 32 of file StochasticDurationGenerationBasedCellCycleModelCellsGenerator.cpp.
template<unsigned DIM> double StochasticDurationGenerationBasedCellCycleModelCellsGenerator< DIM >::GetTypicalTransitCellCycleTime () [inline, virtual]
Returns:
default cell cycle time for a transit cell.
Implements AbstractCellsGenerator< DIM >.
Definition at line 39 of file StochasticDurationGenerationBasedCellCycleModelCellsGenerator.cpp.
References CancerParameters::GetSG2MDuration(), CancerParameters::GetTransitCellG1Duration(), and CancerParameters::Instance().
template<unsigned DIM> double StochasticDurationGenerationBasedCellCycleModelCellsGenerator< DIM >::GetTypicalStemCellCycleTime () [inline, virtual]
Returns:
default cell cycle time for a transit cell.
Implements AbstractCellsGenerator< DIM >.
Definition at line 47 of file StochasticDurationGenerationBasedCellCycleModelCellsGenerator.cpp.
References CancerParameters::GetSG2MDuration(), CancerParameters::GetStemCellG1Duration(), and CancerParameters::Instance().
template<unsigned DIM> bool StochasticDurationGenerationBasedCellCycleModelCellsGenerator< DIM >::CellsCanDifferentiate () [inline, virtual]
Returns:
true (cells can always differentiate).
Reimplemented from AbstractCellsGenerator< DIM >.
Definition at line 55 of file StochasticDurationGenerationBasedCellCycleModelCellsGenerator.cpp.
The documentation for this class was generated from the following files:
/tmp/release_1/cancer/src/tissue/cell/StochasticDurationGenerationBasedCellCycleModelCellsGenerator.hpp
/tmp/release_1/cancer/src/tissue/cell/StochasticDurationGenerationBasedCellCycleModelCellsGenerator.cpp