Chaste: MeshBasedTissue< DIM > Class Template Reference
MeshBasedTissue< DIM > Class Template Reference
#include <MeshBasedTissue.hpp>
Public Member Functions
MeshBasedTissue (MutableMesh< DIM, DIM > &rMesh, const std::vector< TissueCell > &rCells, const std::vector< unsigned > locationIndices=std::vector< unsigned >(), bool deleteMesh=false, bool validate=true)
MeshBasedTissue (MutableMesh< DIM, DIM > &rMesh)
~MeshBasedTissue ()
MutableMesh< DIM, DIM > & rGetMesh ()
const MutableMesh< DIM, DIM > & rGetMesh () const
bool GetWriteVoronoiData ()
bool GetWriteTissueAreas ()
bool UseAreaBasedDampingConstant ()
void SetWriteVoronoiData (bool writeVoronoiData, bool followLoggedCell)
unsigned AddNode (Node< DIM > *pNewNode)
void SetNode (unsigned nodeIndex, ChastePoint< DIM > &rNewLocation)
virtual bool IsGhostNode (unsigned index)
double GetDampingConstant (unsigned nodeIndex)
void SetWriteTissueAreas (bool writeTissueAreas)
void SetAreaBasedDampingConstant (bool useAreaBasedDampingConstant)
virtual unsigned RemoveDeadCells ()
virtual TissueCell * AddCell (TissueCell &rNewCell, c_vector< double, DIM > newLocation, TissueCell *pParentCell=NULL)
void WriteMeshToFile (const std::string &rArchiveDirectory, const std::string &rMeshFileName)
void CreateOutputFiles (const std::string &rDirectory, bool rCleanOutputDirectory, bool outputCellMutationStates, bool outputCellTypes, bool outputCellVariables, bool outputCellCyclePhases, bool outputCellAncestors)
void CloseOutputFiles (bool outputCellMutationStates, bool outputCellTypes, bool outputCellVariables, bool outputCellCyclePhases, bool outputCellAncestors)
void WriteResultsToFiles (bool outputCellMutationStates, bool outputCellTypes, bool outputCellVariables, bool outputCellCyclePhases, bool outputCellAncestors)
virtual void Update ()
Node< DIM > * GetNode (unsigned index)
unsigned GetNumNodes ()
void SetBottomCellAncestors ()
void WriteVoronoiResultsToFile ()
void WriteTissueAreaResultsToFile ()
void CreateVoronoiTessellation ()
VoronoiTessellation< DIM > & rGetVoronoiTessellation ()
SpringIterator SpringsBegin ()
SpringIterator SpringsEnd ()
void CheckTissueCellPointers ()
bool IsMarkedSpring (TissueCell &, TissueCell &)
void MarkSpring (TissueCell &, TissueCell &)
void UnmarkSpring (TissueCell &, TissueCell &)
template<>
void CreateVoronoiTessellation ()
Protected Member Functions
std::set< TissueCell * > CreateCellPair (TissueCell &, TissueCell &)
template<class Archive>
void serialize (Archive &archive, const unsigned int version)
virtual void UpdateGhostNodesAfterReMesh (NodeMap &rMap)
virtual void Validate ()
Protected Attributes
MutableMesh< DIM, DIM > & mrMesh
VoronoiTessellation< DIM > * mpVoronoiTessellation
bool mDeleteMesh
std::set< std::set< TissueCell * > > mMarkedSprings
bool mWriteVoronoiData
bool mFollowLoggedCell
bool mWriteTissueAreas
out_stream mpElementFile
out_stream mpVoronoiFile
out_stream mpTissueAreasFile
bool mUseAreaBasedDampingConstant
Friends
class TestMeshBasedTissue
class boost::serialization::access
Classes
class SpringIterator
Detailed Description
template<unsigned DIM>
class MeshBasedTissue< DIM >
A facade class encapsulating a mesh-based 'tissue'
Contains a group of cells and maintains the associations between cells and nodes in the mesh.
Definition at line 51 of file MeshBasedTissue.hpp.
Constructor & Destructor Documentation
template<unsigned DIM> MeshBasedTissue< DIM >::MeshBasedTissue (MutableMesh< DIM, DIM > & rMesh, const std::vector< TissueCell > & rCells, const std::vector< unsigned > locationIndices = std::vector<unsigned>(), bool deleteMesh = false, bool validate = true) [inline]
Create a new tissue facade from a mesh and collection of cells.
There must be precisely 1 cell for each node of the mesh.
Parameters:
rMesh a mutable tetrahedral mesh
rCells TissueCells corresponding to the nodes of the mesh
locationIndices an optional vector of location indices that correspond to real cells
deleteMesh set to true if you want the tissue to free the mesh memory on destruction
validate whether to validate the tissue
Definition at line 33 of file MeshBasedTissue.cpp.
References AbstractTissue< DIM >::mCells, MeshBasedTissue< DIM >::mrMesh, AbstractTissue< DIM >::mTissueContainsMesh, and MeshBasedTissue< DIM >::Validate().
template<unsigned DIM> MeshBasedTissue< DIM >::MeshBasedTissue (MutableMesh< DIM, DIM > & rMesh) [inline]
Constructor for use by the de-serializer.
Parameters:
rMesh a mutable tetrahedral mesh.
Definition at line 59 of file MeshBasedTissue.cpp.
References MeshBasedTissue< DIM >::mDeleteMesh, MeshBasedTissue< DIM >::mpVoronoiTessellation, and AbstractTissue< DIM >::mTissueContainsMesh.
template<unsigned DIM> MeshBasedTissue< DIM >::~MeshBasedTissue () [inline]
Destructor.
Definition at line 68 of file MeshBasedTissue.cpp.
References MeshBasedTissue< DIM >::mDeleteMesh, MeshBasedTissue< DIM >::mpVoronoiTessellation, and MeshBasedTissue< DIM >::mrMesh.
Member Function Documentation
template<unsigned DIM> std::set< TissueCell * > MeshBasedTissue< DIM >::CreateCellPair (TissueCell & rCell1, TissueCell & rCell2) [inline, protected]
Helper method used by the spring marking routines
Definition at line 767 of file MeshBasedTissue.cpp.
Referenced by MeshBasedTissue< DIM >::IsMarkedSpring(), MeshBasedTissue< DIM >::MarkSpring(), and MeshBasedTissue< DIM >::UnmarkSpring().
template<unsigned DIM> template<class Archive> void MeshBasedTissue< DIM >::serialize (Archive & archive, const unsigned int version) [inline, protected]
Serialize the facade.
Note that serialization of the mesh and cells is handled by load/save_construct_data.
Note also that member data related to writers is not saved - output must be set up again by the caller after a restart.
Parameters:
archive
version
Reimplemented from AbstractCellCentreBasedTissue< DIM >.
Reimplemented in MeshBasedTissueWithGhostNodes< DIM >, and MeshBasedTissueWithGhostNodes< 2 >.
Definition at line 118 of file MeshBasedTissue.hpp.
template<unsigned DIM> void MeshBasedTissue< DIM >::UpdateGhostNodesAfterReMesh (NodeMap & rMap) [inline, protected, virtual]
Update mIsGhostNode if required by a remesh.
Parameters:
rMap A map between node indices before and after remesh
Reimplemented in MeshBasedTissueWithGhostNodes< DIM >, and MeshBasedTissueWithGhostNodes< 2 >.
Definition at line 377 of file MeshBasedTissue.cpp.
Referenced by MeshBasedTissue< DIM >::Update().
template<unsigned DIM> void MeshBasedTissue< DIM >::Validate () [inline, protected, virtual]
Check consistency of our internal data structures. Each node must have a cell associated with it.
Implements AbstractTissue< DIM >.
Reimplemented in MeshBasedTissueWithGhostNodes< DIM >, and MeshBasedTissueWithGhostNodes< 2 >.
Definition at line 156 of file MeshBasedTissue.cpp.
References AbstractTissue< DIM >::Begin(), AbstractTissue< DIM >::End(), AbstractTissue< DIM >::GetLocationIndexUsingCell(), and MeshBasedTissue< DIM >::GetNumNodes().
Referenced by MeshBasedTissue< DIM >::MeshBasedTissue(), and MeshBasedTissue< DIM >::Update().
template<unsigned DIM> MutableMesh< DIM, DIM > & MeshBasedTissue< DIM >::rGetMesh () [inline]
Returns:
reference to mrMesh.
Definition at line 178 of file MeshBasedTissue.cpp.
References MeshBasedTissue< DIM >::mrMesh.
Referenced by CryptStatistics::CellIsInSection(), CryptStatistics::CellIsInSectionPeriodic(), and CryptSimulation2d::WriteVisualizerSetupFile().
template<unsigned DIM> const MutableMesh< DIM, DIM > & MeshBasedTissue< DIM >::rGetMesh () const [inline]
Returns:
const reference to mrMesh (used in archiving).
Definition at line 184 of file MeshBasedTissue.cpp.
References MeshBasedTissue< DIM >::mrMesh.
template<unsigned DIM> bool MeshBasedTissue< DIM >::GetWriteVoronoiData () [inline]
Returns:
mWriteVoronoiData.
Definition at line 463 of file MeshBasedTissue.cpp.
References MeshBasedTissue< DIM >::mWriteVoronoiData.
Referenced by MeshBasedTissue< DIM >::Update().
template<unsigned DIM> bool MeshBasedTissue< DIM >::GetWriteTissueAreas () [inline]
Returns:
mWriteTissueAreas.
Definition at line 469 of file MeshBasedTissue.cpp.
References MeshBasedTissue< DIM >::mWriteTissueAreas.
Referenced by MeshBasedTissue< DIM >::Update().
template<unsigned DIM> bool MeshBasedTissue< DIM >::UseAreaBasedDampingConstant () [inline]
Returns:
mUseAreaBasedDampingConstant.
Definition at line 78 of file MeshBasedTissue.cpp.
References MeshBasedTissue< DIM >::mUseAreaBasedDampingConstant.
Referenced by MeshBasedTissue< DIM >::Update().
template<unsigned DIM> void MeshBasedTissue< DIM >::SetWriteVoronoiData (bool writeVoronoiData, bool followLoggedCell) [inline]
Get method for mWriteVoronoiData and mFollowLoggedCell.
Parameters:
writeVoronoiData whether to output cell area and perimeter information
followLoggedCell whether to follow only the logged cell if writing Voronoi data
Definition at line 362 of file MeshBasedTissue.cpp.
References MeshBasedTissue< DIM >::mFollowLoggedCell, and MeshBasedTissue< DIM >::mWriteVoronoiData.
template<unsigned DIM> unsigned MeshBasedTissue< DIM >::AddNode (Node< DIM > * pNewNode) [inline, virtual]
Overridden AddNode() method.
Add a new node to the tissue.
Parameters:
pNewNode pointer to the new node
Returns:
global index of new node in tissue
Implements AbstractTissue< DIM >.
Definition at line 91 of file MeshBasedTissue.cpp.
References MeshBasedTissue< DIM >::mrMesh.
template<unsigned DIM> void MeshBasedTissue< DIM >::SetNode (unsigned nodeIndex, ChastePoint< DIM > & rNewLocation) [inline, virtual]
Overridden SetNode() method.
Move the node with a given index to a new point in space.
Parameters:
nodeIndex the index of the node to be moved
rNewLocation the new target location of the node
Implements AbstractTissue< DIM >.
Definition at line 97 of file MeshBasedTissue.cpp.
References MeshBasedTissue< DIM >::mrMesh.
template<unsigned DIM> bool MeshBasedTissue< DIM >::IsGhostNode (unsigned index) [inline, virtual]
Find if a given node is a ghost node. The method always returns false but is overridden in MeshBasedTissueWithGhostNodes.
Parameters:
index the global index of a specified node
Returns:
whether the node is a ghost node
Reimplemented from AbstractTissue< DIM >.
Reimplemented in MeshBasedTissueWithGhostNodes< DIM >, and MeshBasedTissueWithGhostNodes< 2 >.
Definition at line 103 of file MeshBasedTissue.cpp.
Referenced by MeshBasedTissue< DIM >::SpringIterator::operator++(), and MeshBasedTissue< DIM >::SpringIterator::SpringIterator().
template<unsigned DIM> double MeshBasedTissue< DIM >::GetDampingConstant (unsigned nodeIndex) [inline, virtual]
Overridden GetDampingConstant() method that includes the case of a cell-area-based damping constant.
Parameters:
nodeIndex the global index of this node
Returns:
the damping constant for the given TissueCell.
We use a linear dependence of the form
new_damping_const = old_damping_const * (d0+d1*A)
where d0, d1 are parameters, A is the cell's area, and old_damping_const is the damping constant if not using mUseAreaBasedDampingConstant
Compute the parameter d1 such that d0+A*d1=1, where A is the equilibrium area of a cell (this is equal to sqrt(3)/4, which is a third of the area of a regular hexagon of edge length 1)
The cell area should not be too large - the next assertion is to avoid getting an infinite cell area, which may occur if area-based viscosity is chosen in the absence of ghost nodes.
Reimplemented from AbstractCellCentreBasedTissue< DIM >.
Definition at line 109 of file MeshBasedTissue.cpp.
References CancerParameters::GetAreaBasedDampingConstantParameter(), AbstractCellCentreBasedTissue< DIM >::GetDampingConstant(), CancerParameters::Instance(), MeshBasedTissue< DIM >::mUseAreaBasedDampingConstant, and MeshBasedTissue< DIM >::rGetVoronoiTessellation().
template<unsigned DIM> void MeshBasedTissue< DIM >::SetWriteTissueAreas (bool writeTissueAreas) [inline]
Set method for mWriteTissueAreas.
Parameters:
writeTissueAreas whether to output tissue area data
Definition at line 370 of file MeshBasedTissue.cpp.
References MeshBasedTissue< DIM >::mWriteTissueAreas.
template<unsigned DIM> void MeshBasedTissue< DIM >::SetAreaBasedDampingConstant (bool useAreaBasedDampingConstant) [inline]
Set method for mUseAreaBasedDampingConstant.
Parameters:
useAreaBasedDampingConstant whether to use a viscosity that is linear in the cell area, rather than constant
Definition at line 84 of file MeshBasedTissue.cpp.
References MeshBasedTissue< DIM >::mUseAreaBasedDampingConstant.
template<unsigned DIM> unsigned MeshBasedTissue< DIM >::RemoveDeadCells () [inline, virtual]
Remove all cells that are labelled as dead.
Note that this now calls MutableMesh::DeleteNodePriorToReMesh() and therefore a ReMesh(map) must be called before any element information is used.
Note also that after calling this method the tissue will be in an inconsistent state until Update() is called! So don't try iterating over cells or anything like that.
Returns:
number of cells removed.
Implements AbstractTissue< DIM >.
Definition at line 190 of file MeshBasedTissue.cpp.
References AbstractTissue< DIM >::mCellLocationMap, AbstractTissue< DIM >::mCells, AbstractTissue< DIM >::mLocationCellMap, MeshBasedTissue< DIM >::mMarkedSprings, and MeshBasedTissue< DIM >::mrMesh.
template<unsigned DIM> TissueCell * MeshBasedTissue< DIM >::AddCell (TissueCell & rNewCell, c_vector< double, DIM > newLocation, TissueCell * pParentCell = NULL) [inline, virtual]
Overridden AddCell() method.
Add a new cell to the tissue and update mIsGhostNode.
Parameters:
rNewCell the cell to add
newLocation the position in space at which to put it
pParentCell pointer to a parent cell (if required)
Returns:
address of cell as it appears in the cell list (internal of this method uses a copy constructor along the way)
Reimplemented from AbstractCellCentreBasedTissue< DIM >.
Reimplemented in MeshBasedTissueWithGhostNodes< DIM >, and MeshBasedTissueWithGhostNodes< 2 >.
Definition at line 382 of file MeshBasedTissue.cpp.
References AbstractCellCentreBasedTissue< DIM >::AddCell(), and MeshBasedTissue< DIM >::MarkSpring().
Referenced by MeshBasedTissueWithGhostNodes< DIM >::AddCell().
template<unsigned DIM> void MeshBasedTissue< DIM >::WriteMeshToFile (const std::string & rArchiveDirectory, const std::string & rMeshFileName) [inline, virtual]
Overridden WriteMeshToFile() method. For use by the TissueSimulationArchiver.
Parameters:
rArchiveDirectory directory in which archive is stored
rMeshFileName base name for mesh files
Reimplemented from AbstractTissue< DIM >.
Definition at line 399 of file MeshBasedTissue.cpp.
References MeshBasedTissue< DIM >::mrMesh.
template<unsigned DIM> void MeshBasedTissue< DIM >::CreateOutputFiles (const std::string & rDirectory, bool rCleanOutputDirectory, bool outputCellMutationStates, bool outputCellTypes, bool outputCellVariables, bool outputCellCyclePhases, bool outputCellAncestors) [inline, virtual]
Overridden CreateOutputFiles() method.
Parameters:
rDirectory pathname of the output directory, relative to where Chaste output is stored
rCleanOutputDirectory whether to delete the contents of the output directory prior to output file creation
outputCellMutationStates whether to create a cell mutation state results file
outputCellTypes whether to create a cell type results file
outputCellVariables whether to create a cell-cycle variable results file
outputCellCyclePhases whether to create a cell-cycle phase results file
outputCellAncestors whether to create a cell ancestor results file
Reimplemented from AbstractTissue< DIM >.
Definition at line 409 of file MeshBasedTissue.cpp.
References AbstractTissue< DIM >::CreateOutputFiles(), MeshBasedTissue< DIM >::mpElementFile, MeshBasedTissue< DIM >::mpTissueAreasFile, MeshBasedTissue< DIM >::mpVoronoiFile, MeshBasedTissue< DIM >::mWriteTissueAreas, MeshBasedTissue< DIM >::mWriteVoronoiData, and OutputFileHandler::OpenOutputFile().
template<unsigned DIM> void MeshBasedTissue< DIM >::CloseOutputFiles (bool outputCellMutationStates, bool outputCellTypes, bool outputCellVariables, bool outputCellCyclePhases, bool outputCellAncestors) [inline, virtual]
Overridden CloseOutputFiles() method.
Parameters:
outputCellMutationStates whether a cell mutation state results file is open
outputCellTypes whether a cell type results file is open
outputCellVariables whether a cell-cycle variable results file is open
outputCellCyclePhases whether a cell-cycle phase results file is open
outputCellAncestors whether a cell ancestor results file is open
Reimplemented from AbstractTissue< DIM >.
Definition at line 439 of file MeshBasedTissue.cpp.
References AbstractTissue< DIM >::CloseOutputFiles(), MeshBasedTissue< DIM >::mpElementFile, MeshBasedTissue< DIM >::mpTissueAreasFile, MeshBasedTissue< DIM >::mpVoronoiFile, MeshBasedTissue< DIM >::mWriteTissueAreas, and MeshBasedTissue< DIM >::mWriteVoronoiData.
template<unsigned DIM> void MeshBasedTissue< DIM >::WriteResultsToFiles (bool outputCellMutationStates, bool outputCellTypes, bool outputCellVariables, bool outputCellCyclePhases, bool outputCellAncestors) [inline, virtual]
Overridden WriteResultsToFiles() method.
Parameters:
outputCellMutationStates whether to output cell mutation state results
outputCellTypes whether to output cell type results
outputCellVariables whether to output cell-cycle variable results
outputCellCyclePhases whether to output cell-cycle phase results
outputCellAncestors whether to output cell ancestor results
Reimplemented from AbstractCellCentreBasedTissue< DIM >.
Definition at line 475 of file MeshBasedTissue.cpp.
References SimulationTime::GetTime(), SimulationTime::Instance(), MeshBasedTissue< DIM >::mpElementFile, MeshBasedTissue< DIM >::mpVoronoiTessellation, MeshBasedTissue< DIM >::mrMesh, MeshBasedTissue< DIM >::mWriteTissueAreas, MeshBasedTissue< DIM >::mWriteVoronoiData, AbstractCellCentreBasedTissue< DIM >::WriteResultsToFiles(), MeshBasedTissue< DIM >::WriteTissueAreaResultsToFile(), and MeshBasedTissue< DIM >::WriteVoronoiResultsToFile().
template<unsigned DIM> void MeshBasedTissue< DIM >::Update () [inline, virtual]
Overridden Update() method. Fixes up the mappings between cells and nodes.
Implements AbstractTissue< DIM >.
Definition at line 248 of file MeshBasedTissue.cpp.
References GenericEventHandler< 9, CancerEventHandler >::BeginEvent(), Node< SPACE_DIM >::ContainingElementsBegin(), Node< SPACE_DIM >::ContainingElementsEnd(), MeshBasedTissue< DIM >::CreateVoronoiTessellation(), GenericEventHandler< 9, CancerEventHandler >::EndEvent(), AbstractCellCentreBasedTissue< DIM >::GetNodeCorrespondingToCell(), MeshBasedTissue< DIM >::GetWriteTissueAreas(), MeshBasedTissue< DIM >::GetWriteVoronoiData(), AbstractTissue< DIM >::mCellLocationMap, AbstractTissue< DIM >::mCells, AbstractTissue< DIM >::mLocationCellMap, MeshBasedTissue< DIM >::mMarkedSprings, MeshBasedTissue< DIM >::mrMesh, Node< SPACE_DIM >::rGetContainingElementIndices(), MeshBasedTissue< DIM >::UpdateGhostNodesAfterReMesh(), MeshBasedTissue< DIM >::UseAreaBasedDampingConstant(), and MeshBasedTissue< DIM >::Validate().
template<unsigned DIM> Node< DIM > * MeshBasedTissue< DIM >::GetNode (unsigned index) [inline, virtual]
Overridden GetNode() method.
Parameters:
index global index of the specified Node
Returns:
pointer to the Node with given index.
Implements AbstractTissue< DIM >.
Definition at line 337 of file MeshBasedTissue.cpp.
References MeshBasedTissue< DIM >::mrMesh.
Referenced by MeshBasedTissueWithGhostNodes< DIM >::CalculateForceBetweenNodes(), MeshBasedTissueWithGhostNodes< DIM >::MeshBasedTissueWithGhostNodes(), and MeshBasedTissueWithGhostNodes< DIM >::UpdateGhostPositions().
template<unsigned DIM> unsigned MeshBasedTissue< DIM >::GetNumNodes () [inline, virtual]
Overridden GetNumNodes() method.
Returns:
the number of nodes in the tissue.
Implements AbstractTissue< DIM >.
Definition at line 343 of file MeshBasedTissue.cpp.
References MeshBasedTissue< DIM >::mrMesh.
Referenced by MeshBasedTissueWithGhostNodes< DIM >::AddCell(), MeshBasedTissueWithGhostNodes< DIM >::MeshBasedTissueWithGhostNodes(), MeshBasedTissueWithGhostNodes< DIM >::UpdateGhostNodesAfterReMesh(), MeshBasedTissueWithGhostNodes< DIM >::UpdateGhostPositions(), MeshBasedTissueWithGhostNodes< DIM >::Validate(), and MeshBasedTissue< DIM >::Validate().
template<unsigned DIM> void MeshBasedTissue< DIM >::SetBottomCellAncestors () [inline]
Sets the Ancestor index of all the cells at the bottom in order, can be used to trace clonal populations.
Definition at line 349 of file MeshBasedTissue.cpp.
References AbstractTissue< DIM >::Begin(), AbstractTissue< DIM >::End(), and AbstractCellCentreBasedTissue< DIM >::GetNodeCorrespondingToCell().
template<unsigned DIM> void MeshBasedTissue< DIM >::WriteVoronoiResultsToFile () [inline]
Write current results to mpVoronoiFile.
Definition at line 521 of file MeshBasedTissue.cpp.
References AbstractTissue< DIM >::Begin(), AbstractTissue< DIM >::End(), AbstractCellCentreBasedTissue< DIM >::GetLocationOfCellCentre(), SimulationTime::GetTime(), SimulationTime::Instance(), AbstractTissue< DIM >::mCellLocationMap, MeshBasedTissue< DIM >::mFollowLoggedCell, MeshBasedTissue< DIM >::mpVoronoiFile, and MeshBasedTissue< DIM >::rGetVoronoiTessellation().
Referenced by MeshBasedTissue< DIM >::WriteResultsToFiles().
template<unsigned DIM> void MeshBasedTissue< DIM >::WriteTissueAreaResultsToFile () [inline]
Write current results to mpTissueAreasFile.
Definition at line 551 of file MeshBasedTissue.cpp.
References AbstractTissue< DIM >::Begin(), AbstractTissue< DIM >::End(), SimulationTime::GetTime(), SimulationTime::Instance(), AbstractTissue< DIM >::mCellLocationMap, MeshBasedTissue< DIM >::mpTissueAreasFile, MeshBasedTissue< DIM >::mrMesh, and MeshBasedTissue< DIM >::rGetVoronoiTessellation().
Referenced by MeshBasedTissue< DIM >::WriteResultsToFiles().
template<unsigned DIM> void MeshBasedTissue< DIM >::CreateVoronoiTessellation () [inline]
Get a reference to a Voronoi tessellation of the mesh.
Definition at line 666 of file MeshBasedTissue.cpp.
References MeshBasedTissue< DIM >::mpVoronoiTessellation, and MeshBasedTissue< DIM >::mrMesh.
Referenced by MeshBasedTissue< DIM >::Update().
template<unsigned DIM> VoronoiTessellation< DIM > & MeshBasedTissue< DIM >::rGetVoronoiTessellation () [inline]
Returns:
mpVoronoiTessellation.
Definition at line 680 of file MeshBasedTissue.cpp.
References MeshBasedTissue< DIM >::mpVoronoiTessellation.
Referenced by MeshBasedTissue< DIM >::GetDampingConstant(), MeshBasedTissue< DIM >::WriteTissueAreaResultsToFile(), and MeshBasedTissue< DIM >::WriteVoronoiResultsToFile().
template<unsigned DIM> MeshBasedTissue< DIM >::SpringIterator MeshBasedTissue< DIM >::SpringsBegin () [inline]
Returns:
iterator pointing to the first spring in the tissue
Definition at line 654 of file MeshBasedTissue.cpp.
References MeshBasedTissue< DIM >::mrMesh.
template<unsigned DIM> MeshBasedTissue< DIM >::SpringIterator MeshBasedTissue< DIM >::SpringsEnd () [inline]
Returns:
iterator pointing to one past the last spring in the tissue
Definition at line 660 of file MeshBasedTissue.cpp.
References MeshBasedTissue< DIM >::mrMesh.
Referenced by MeshBasedTissue< DIM >::SpringIterator::operator++(), MeshBasedTissue< DIM >::SpringIterator::rGetCellA(), and MeshBasedTissue< DIM >::SpringIterator::rGetCellB().
template<unsigned DIM> void MeshBasedTissue< DIM >::CheckTissueCellPointers () [inline]
Helper method for use in debugging.
Definition at line 687 of file MeshBasedTissue.cpp.
References AbstractCellCycleModel::GetCell(), TissueCell::GetCellCycleModel(), TissueCell::IsDead(), AbstractTissue< DIM >::mCellLocationMap, AbstractTissue< DIM >::mCells, MeshBasedTissue< DIM >::mMarkedSprings, and AbstractTissue< DIM >::rGetCellUsingLocationIndex().
template<unsigned DIM> bool MeshBasedTissue< DIM >::IsMarkedSpring (TissueCell & rCell1, TissueCell & rCell2) [inline]
Returns:
whether the spring between two given cells is marked.
Definition at line 776 of file MeshBasedTissue.cpp.
References MeshBasedTissue< DIM >::CreateCellPair(), and MeshBasedTissue< DIM >::mMarkedSprings.
template<unsigned DIM> void MeshBasedTissue< DIM >::MarkSpring (TissueCell & rCell1, TissueCell & rCell2) [inline]
Mark the spring between the given cells.
Definition at line 783 of file MeshBasedTissue.cpp.
References MeshBasedTissue< DIM >::CreateCellPair(), and MeshBasedTissue< DIM >::mMarkedSprings.
Referenced by MeshBasedTissue< DIM >::AddCell().
template<unsigned DIM> void MeshBasedTissue< DIM >::UnmarkSpring (TissueCell & rCell1, TissueCell & rCell2) [inline]
Stop marking the spring between the given cells.
Definition at line 790 of file MeshBasedTissue.cpp.
References MeshBasedTissue< DIM >::CreateCellPair(), and MeshBasedTissue< DIM >::mMarkedSprings.
Friends And Related Function Documentation
template<unsigned DIM> friend class boost::serialization::access [friend]
Needed for serialization.
Reimplemented from AbstractCellCentreBasedTissue< DIM >.
Reimplemented in MeshBasedTissueWithGhostNodes< DIM >, and MeshBasedTissueWithGhostNodes< 2 >.
Definition at line 105 of file MeshBasedTissue.hpp.
Member Data Documentation
template<unsigned DIM> MutableMesh<DIM, DIM>& MeshBasedTissue< DIM >::mrMesh [protected]
Reference to the mesh.
Definition at line 58 of file MeshBasedTissue.hpp.
Referenced by MeshBasedTissue< DIM >::AddNode(), MeshBasedTissueWithGhostNodes< DIM >::CalculateForceBetweenNodes(), MeshBasedTissue< DIM >::CreateVoronoiTessellation(), MeshBasedTissue< DIM >::GetNode(), MeshBasedTissue< DIM >::GetNumNodes(), MeshBasedTissue< DIM >::MeshBasedTissue(), MeshBasedTissue< DIM >::RemoveDeadCells(), MeshBasedTissue< DIM >::rGetMesh(), MeshBasedTissueWithGhostNodes< DIM >::SetGhostNodes(), MeshBasedTissue< DIM >::SetNode(), MeshBasedTissue< DIM >::SpringIterator::SpringIterator(), MeshBasedTissue< DIM >::SpringsBegin(), MeshBasedTissue< DIM >::SpringsEnd(), MeshBasedTissue< DIM >::Update(), MeshBasedTissueWithGhostNodes< DIM >::UpdateGhostPositions(), MeshBasedTissue< DIM >::WriteMeshToFile(), MeshBasedTissue< DIM >::WriteResultsToFiles(), MeshBasedTissue< DIM >::WriteTissueAreaResultsToFile(), and MeshBasedTissue< DIM >::~MeshBasedTissue().
template<unsigned DIM> VoronoiTessellation<DIM>* MeshBasedTissue< DIM >::mpVoronoiTessellation [protected]
Pointer to a Voronoi tessellation object. Used to calculate cell area and perimeter information if required.
Definition at line 64 of file MeshBasedTissue.hpp.
Referenced by MeshBasedTissue< DIM >::CreateVoronoiTessellation(), MeshBasedTissue< DIM >::MeshBasedTissue(), MeshBasedTissue< DIM >::rGetVoronoiTessellation(), MeshBasedTissue< 2 >::serialize(), MeshBasedTissue< DIM >::WriteResultsToFiles(), and MeshBasedTissue< DIM >::~MeshBasedTissue().
template<unsigned DIM> bool MeshBasedTissue< DIM >::mDeleteMesh [protected]
Whether to delete the mesh when we are destroyed. Needed if this tissue has been de-serialized.
Definition at line 70 of file MeshBasedTissue.hpp.
Referenced by MeshBasedTissue< DIM >::MeshBasedTissue(), and MeshBasedTissue< DIM >::~MeshBasedTissue().
template<unsigned DIM> std::set<std::set<TissueCell*> > MeshBasedTissue< DIM >::mMarkedSprings [protected]
Special springs that we want to keep track of for some reason. Currently used to track cells in the process of dividing (which are represented as two cells joined by a shorter spring).
Definition at line 77 of file MeshBasedTissue.hpp.
Referenced by MeshBasedTissue< DIM >::CheckTissueCellPointers(), MeshBasedTissue< DIM >::IsMarkedSpring(), MeshBasedTissue< DIM >::MarkSpring(), MeshBasedTissue< DIM >::RemoveDeadCells(), MeshBasedTissue< 2 >::serialize(), MeshBasedTissue< DIM >::UnmarkSpring(), and MeshBasedTissue< DIM >::Update().
template<unsigned DIM> bool MeshBasedTissue< DIM >::mWriteVoronoiData [protected]
Whether to print out cell area and perimeter information.
Definition at line 80 of file MeshBasedTissue.hpp.
Referenced by MeshBasedTissue< DIM >::CloseOutputFiles(), MeshBasedTissue< DIM >::CreateOutputFiles(), MeshBasedTissue< DIM >::GetWriteVoronoiData(), MeshBasedTissue< 2 >::serialize(), MeshBasedTissue< DIM >::SetWriteVoronoiData(), and MeshBasedTissue< DIM >::WriteResultsToFiles().
template<unsigned DIM> bool MeshBasedTissue< DIM >::mFollowLoggedCell [protected]
Whether to follow only the logged cell if writing Voronoi data.
Definition at line 83 of file MeshBasedTissue.hpp.
Referenced by MeshBasedTissue< 2 >::serialize(), MeshBasedTissue< DIM >::SetWriteVoronoiData(), and MeshBasedTissue< DIM >::WriteVoronoiResultsToFile().
template<unsigned DIM> bool MeshBasedTissue< DIM >::mWriteTissueAreas [protected]
Whether to print out tissue areas.
Definition at line 86 of file MeshBasedTissue.hpp.
Referenced by MeshBasedTissue< DIM >::CloseOutputFiles(), MeshBasedTissue< DIM >::CreateOutputFiles(), MeshBasedTissue< DIM >::GetWriteTissueAreas(), MeshBasedTissue< 2 >::serialize(), MeshBasedTissue< DIM >::SetWriteTissueAreas(), and MeshBasedTissue< DIM >::WriteResultsToFiles().
template<unsigned DIM> out_stream MeshBasedTissue< DIM >::mpElementFile [protected]
Results file for elements.
Definition at line 89 of file MeshBasedTissue.hpp.
Referenced by MeshBasedTissue< DIM >::CloseOutputFiles(), MeshBasedTissue< DIM >::CreateOutputFiles(), and MeshBasedTissue< DIM >::WriteResultsToFiles().
template<unsigned DIM> out_stream MeshBasedTissue< DIM >::mpVoronoiFile [protected]
Results file for Voronoi data.
Definition at line 92 of file MeshBasedTissue.hpp.
Referenced by MeshBasedTissue< DIM >::CloseOutputFiles(), MeshBasedTissue< DIM >::CreateOutputFiles(), and MeshBasedTissue< DIM >::WriteVoronoiResultsToFile().
template<unsigned DIM> out_stream MeshBasedTissue< DIM >::mpTissueAreasFile [protected]
Results file for tissue area data.
Definition at line 95 of file MeshBasedTissue.hpp.
Referenced by MeshBasedTissue< DIM >::CloseOutputFiles(), MeshBasedTissue< DIM >::CreateOutputFiles(), and MeshBasedTissue< DIM >::WriteTissueAreaResultsToFile().
template<unsigned DIM> bool MeshBasedTissue< DIM >::mUseAreaBasedDampingConstant [protected]
Whether to use a viscosity that is linear in the cell area, rather than constant.
Definition at line 101 of file MeshBasedTissue.hpp.
Referenced by MeshBasedTissue< DIM >::GetDampingConstant(), MeshBasedTissue< 2 >::serialize(), MeshBasedTissue< DIM >::SetAreaBasedDampingConstant(), and MeshBasedTissue< DIM >::UseAreaBasedDampingConstant().
The documentation for this class was generated from the following files:
/tmp/release_1/cancer/src/tissue/MeshBasedTissue.hpp
/tmp/release_1/cancer/src/tissue/MeshBasedTissue.cpp