Chaste: IngeWntSwatCellCycleModel Class Reference
IngeWntSwatCellCycleModel Class Reference
#include <IngeWntSwatCellCycleModel.hpp>
Public Member Functions
IngeWntSwatCellCycleModel (unsigned hypothesis)
IngeWntSwatCellCycleModel (const unsigned &rHypothesis, AbstractOdeSystem *pParentOdeSystem, const CellMutationState &rMutationState, double birthTime, double lastTime, bool inSG2MPhase, bool readyToDivide, double divideTime)
IngeWntSwatCellCycleModel (const unsigned &rHypothesis, const std::vector< double > &rParentProteinConcentrations, const CellMutationState &rMutationState)
AbstractCellCycleModel * CreateDaughterCellCycleModel ()
void Initialise ()
bool SolveOdeToTime (double currentTime)
double GetMembraneBoundBetaCateninLevel ()
double GetCytoplasmicBetaCateninLevel ()
double GetNuclearBetaCateninLevel ()
unsigned GetHypothesis () const
Private Member Functions
template<class Archive>
void serialize (Archive &archive, const unsigned int version)
void ChangeCellTypeDueToCurrentBetaCateninLevel ()
Private Attributes
unsigned mHypothesis
Friends
class boost::serialization::access
Detailed Description
Wnt-dependent cell cycle model.
Note that this class uses C++'s default copying semantics, and so doesn't implement a copy constructor or operator=.
Definition at line 52 of file IngeWntSwatCellCycleModel.hpp.
Constructor & Destructor Documentation
IngeWntSwatCellCycleModel::IngeWntSwatCellCycleModel (unsigned hypothesis) [inline]
Default constructor.
Parameters:
hypothesis Hypothesis number (1 or 2), concerning the nature of the interactions modelled by the cell cycle ODE system.
Definition at line 99 of file IngeWntSwatCellCycleModel.hpp.
References mHypothesis.
Referenced by CreateDaughterCellCycleModel().
IngeWntSwatCellCycleModel::IngeWntSwatCellCycleModel (const unsigned & rHypothesis, AbstractOdeSystem * pParentOdeSystem, const CellMutationState & rMutationState, double birthTime, double lastTime, bool inSG2MPhase, bool readyToDivide, double divideTime)
A private constructor for daughter cells called by the CreateDaughterCellCycleModel function (which can be called by TissueCell::CommonCopy() and isn't necessarily being born.
Parameters:
rHypothesis which model hypothesis to use (1 or 2)
pParentOdeSystem to copy the state of.
rMutationState the mutation state of the cell (used by ODEs)
birthTime the simulation time when the cell divided (birth time of parent cell)
lastTime last time the cell cycle model was evaluated
inSG2MPhase whether the cell is in S-G2-M (not evaluating ODEs and just waiting)
readyToDivide whether the cell is ready to divide
divideTime if in the future this is the time at which the cell is going to divide
Definition at line 32 of file IngeWntSwatCellCycleModel.cpp.
References SimulationTime::Instance(), AbstractCellCycleModel::mBirthTime, AbstractOdeBasedCellCycleModel::mDivideTime, AbstractOdeBasedCellCycleModel::mFinishedRunningOdes, mHypothesis, AbstractOdeBasedCellCycleModel::mpOdeSystem, AbstractCellCycleModel::mReadyToDivide, and AbstractOdeSystem::rGetStateVariables().
IngeWntSwatCellCycleModel::IngeWntSwatCellCycleModel (const unsigned & rHypothesis, const std::vector< double > & rParentProteinConcentrations, const CellMutationState & rMutationState)
A 'private' constructor for archiving.
Parameters:
rHypothesis which model hypothesis to use (1 or 2)
rParentProteinConcentrations a std::vector of doubles of the protein concentrations (see IngeWntSwatCellCycleOdeSystem)
rMutationState the mutation state of the cell (used by ODEs)
Definition at line 69 of file IngeWntSwatCellCycleModel.cpp.
References mHypothesis, AbstractOdeBasedCellCycleModel::mpOdeSystem, and AbstractOdeSystem::rGetStateVariables().
Member Function Documentation
template<class Archive> void IngeWntSwatCellCycleModel::serialize (Archive & archive, const unsigned int version) [inline, private]
Archive the cell cycle model and ODE system, never used directly - boost uses this.
Parameters:
archive
version
Reimplemented from AbstractWntOdeBasedCellCycleModel.
Definition at line 65 of file IngeWntSwatCellCycleModel.hpp.
References AbstractOdeBasedCellCycleModel::mpOdeSystem.
void IngeWntSwatCellCycleModel::ChangeCellTypeDueToCurrentBetaCateninLevel () [private, virtual]
Called by Initialise() and UpdateCellType() only. Updates the mpCell::mCellType to match mpOdeSystem's beta-catenin levels
This carries out the work for UpdateCellType(); But does not check the current time so it can be used by the initialise method.
Implements AbstractWntOdeBasedCellCycleModel.
Definition at line 101 of file IngeWntSwatCellCycleModel.cpp.
References AbstractCellCycleModel::mpCell, AbstractOdeBasedCellCycleModel::mpOdeSystem, AbstractOdeSystem::rGetStateVariables(), and TissueCell::SetCellType().
Referenced by Initialise().
AbstractCellCycleModel * IngeWntSwatCellCycleModel::CreateDaughterCellCycleModel () [virtual]
Returns a new IngeWntSwatCellCycleModel created with the correct initial conditions.
Should be called just after the parent cell cycle model has been Reset().
We call a cheeky version of the constructor which makes the new cell cycle model the same as the old one - not a dividing copy at this time, unless the parent cell has just divided.
Implements AbstractCellCycleModel.
Definition at line 81 of file IngeWntSwatCellCycleModel.cpp.
References TissueCell::GetMutationState(), IngeWntSwatCellCycleModel(), AbstractCellCycleModel::mBirthTime, AbstractOdeBasedCellCycleModel::mDivideTime, AbstractOdeBasedCellCycleModel::mFinishedRunningOdes, mHypothesis, AbstractOdeBasedCellCycleModel::mLastTime, AbstractCellCycleModel::mpCell, AbstractOdeBasedCellCycleModel::mpOdeSystem, and AbstractCellCycleModel::mReadyToDivide.
void IngeWntSwatCellCycleModel::Initialise (void) [virtual]
See AbstractCellCycleModel::Initialise()
In this case we set up a new ODE system for a daughter cell.
Reimplemented from AbstractCellCycleModel.
Definition at line 122 of file IngeWntSwatCellCycleModel.cpp.
References ChangeCellTypeDueToCurrentBetaCateninLevel(), AbstractOdeSystem::GetInitialConditions(), TissueCell::GetMutationState(), WntConcentration::Instance(), mHypothesis, AbstractCellCycleModel::mpCell, AbstractOdeBasedCellCycleModel::mpOdeSystem, and AbstractOdeSystem::SetStateVariables().
bool IngeWntSwatCellCycleModel::SolveOdeToTime (double currentTime) [virtual]
Solve the ODE to the current time.
Parameters:
currentTime the current time
Returns:
Whether a stopping event occurred.
Implements AbstractOdeBasedCellCycleModel.
Definition at line 133 of file IngeWntSwatCellCycleModel.cpp.
References TissueCell::GetMutationState(), SimulationTime::GetTimeStep(), WntConcentration::GetWntLevel(), WntConcentration::Instance(), SimulationTime::Instance(), AbstractOdeBasedCellCycleModel::mLastTime, AbstractCellCycleModel::mpCell, AbstractOdeBasedCellCycleModel::mpOdeSystem, AbstractWntOdeBasedCellCycleModel::msSolver, AbstractOdeSystem::rGetStateVariables(), AbstractIvpOdeSolver::SolveAndUpdateStateVariable(), AbstractIvpOdeSolver::StoppingEventOccurred(), and AbstractWntOdeBasedCellCycleModel::UpdateCellType().
double IngeWntSwatCellCycleModel::GetMembraneBoundBetaCateninLevel ()
Returns:
the level of membrane bound beta-catenin. To be used in cell-cell adhesion calculations.
Definition at line 156 of file IngeWntSwatCellCycleModel.cpp.
References AbstractOdeBasedCellCycleModel::mpOdeSystem, and AbstractOdeSystem::rGetStateVariables().
Referenced by LinearSpringWithVariableSpringConstantsForce< DIM >::VariableSpringConstantMultiplicationFactor(), and CryptSimulation2d::WriteBetaCatenin().
double IngeWntSwatCellCycleModel::GetCytoplasmicBetaCateninLevel ()
Returns:
the level of cytoplasmic beta-catenin (including ubiquitinated - awaiting degradation)
Definition at line 162 of file IngeWntSwatCellCycleModel.cpp.
References AbstractOdeBasedCellCycleModel::mpOdeSystem, and AbstractOdeSystem::rGetStateVariables().
Referenced by CryptSimulation2d::WriteBetaCatenin().
double IngeWntSwatCellCycleModel::GetNuclearBetaCateninLevel ()
Returns:
the level of nuclear beta-catenin. To be used in transcription
Definition at line 170 of file IngeWntSwatCellCycleModel.cpp.
References AbstractOdeBasedCellCycleModel::mpOdeSystem, and AbstractOdeSystem::rGetStateVariables().
Referenced by CryptSimulation2d::WriteBetaCatenin().
unsigned IngeWntSwatCellCycleModel::GetHypothesis () const
Returns:
mHypothesis.
Definition at line 179 of file IngeWntSwatCellCycleModel.cpp.
References mHypothesis.
Friends And Related Function Documentation
friend class boost::serialization::access [friend]
Needed for serialization.
Reimplemented from AbstractWntOdeBasedCellCycleModel.
Definition at line 57 of file IngeWntSwatCellCycleModel.hpp.
Member Data Documentation
unsigned IngeWntSwatCellCycleModel::mHypothesis [private]
Hypothesis number (1 or 2), concerning the nature of the interactions modelled by the cell cycle ODE system.
Definition at line 89 of file IngeWntSwatCellCycleModel.hpp.
Referenced by CreateDaughterCellCycleModel(), GetHypothesis(), IngeWntSwatCellCycleModel(), and Initialise().
The documentation for this class was generated from the following files:
/tmp/release_1/cancer/src/tissue/cell/cycle/IngeWntSwatCellCycleModel.hpp
/tmp/release_1/cancer/src/tissue/cell/cycle/IngeWntSwatCellCycleModel.cpp