Chaste: BackwardEulerLuoRudyIModel1991 Class Reference
BackwardEulerLuoRudyIModel1991 Class Reference
#include <BackwardEulerLuoRudyIModel1991.hpp>
Public Member Functions
BackwardEulerLuoRudyIModel1991 (AbstractStimulusFunction *pIntracellularStimulus)
BackwardEulerLuoRudyIModel1991 (AbstractIvpOdeSolver *pSolver, AbstractStimulusFunction *pIntracellularStimulus)
~BackwardEulerLuoRudyIModel1991 ()
void Init ()
void ComputeResidual (const double rCurrentGuess[1], double rResidual[1])
void ComputeJacobian (const double rCurrentGuess[1], double rJacobian[1][1])
double GetIIonic ()
void VerifyStateVariables ()
double GetIntracellularCalciumConcentration ()
Protected Member Functions
void ComputeOneStepExceptVoltage (double tStart)
void UpdateTransmembranePotential (double time)
Private Attributes
double fast_sodium_current_E_Na
Static Private Attributes
static const double membrane_C = 1.0
static const double membrane_F = 96484.6
static const double membrane_R = 8314
static const double membrane_T = 310.0
static const double background_current_E_b = -59.87
static const double background_current_g_b = 0.03921
static const double fast_sodium_current_g_Na = 23.0
static const double ionic_concentrations_Ki = 145.0
static const double ionic_concentrations_Ko = 5.4
static const double ionic_concentrations_Nai = 18.0
static const double ionic_concentrations_Nao = 140.0
static const double plateau_potassium_current_g_Kp = 0.0183
static const double time_dependent_potassium_current_PR_NaK = 0.01833
Detailed Description
This class sets up the Luo-Rudy I 1991 system of equations, and solves them using a decoupled backward Euler approach.
Definition at line 40 of file BackwardEulerLuoRudyIModel1991.hpp.
Constructor & Destructor Documentation
BackwardEulerLuoRudyIModel1991::BackwardEulerLuoRudyIModel1991 (AbstractStimulusFunction * pIntracellularStimulus)
Constructor
Definition at line 41 of file BackwardEulerLuoRudyIModel1991.cpp.
References Init().
BackwardEulerLuoRudyIModel1991::BackwardEulerLuoRudyIModel1991 (AbstractIvpOdeSolver * pSolver, AbstractStimulusFunction * pIntracellularStimulus)
Constructor with the same signature as the forward cell models
Definition at line 52 of file BackwardEulerLuoRudyIModel1991.cpp.
References Init().
BackwardEulerLuoRudyIModel1991::~BackwardEulerLuoRudyIModel1991 (void)
Destructor
Definition at line 64 of file BackwardEulerLuoRudyIModel1991.cpp.
Member Function Documentation
void BackwardEulerLuoRudyIModel1991::Init () [virtual]
Initialise the cell: set our state variables to the initial conditions, set model parameters to their default values.
Initialise the cell: set our state variables to the initial conditions (done here), set model parameters to their default values (done by subclasses).
Reimplemented from AbstractCardiacCell.
Definition at line 69 of file BackwardEulerLuoRudyIModel1991.cpp.
References fast_sodium_current_E_Na, AbstractCardiacCell::Init(), OdeSystemInformation< ODE_SYSTEM >::Instance(), and AbstractOdeSystem::mpSystemInfo.
Referenced by BackwardEulerLuoRudyIModel1991().
void BackwardEulerLuoRudyIModel1991::ComputeOneStepExceptVoltage (double tStart) [protected, virtual]
Compute the values of all state variables except the voltage for one timestep.
Implements AbstractBackwardEulerCardiacCell< 1 >.
Definition at line 176 of file BackwardEulerLuoRudyIModel1991.cpp.
References CardiacNewtonSolver< SIZE >::Instance(), and CardiacNewtonSolver< SIZE >::Solve().
void BackwardEulerLuoRudyIModel1991::UpdateTransmembranePotential (double time) [protected, virtual]
Perform a forward Euler step to update the transmembrane potential.
Implements AbstractBackwardEulerCardiacCell< 1 >.
Definition at line 124 of file BackwardEulerLuoRudyIModel1991.cpp.
References fast_sodium_current_E_Na, and membrane_C.
double BackwardEulerLuoRudyIModel1991::GetIIonic () [virtual]
Compute the ionic current at the current instant in time (i.e. using the current values of the state variables).
Implements AbstractCardiacCell.
Definition at line 336 of file BackwardEulerLuoRudyIModel1991.cpp.
References fast_sodium_current_E_Na.
void BackwardEulerLuoRudyIModel1991::VerifyStateVariables () [virtual]
Check that none of the gating variables have gone out of range. Throws an Exception if any have.
Reimplemented from AbstractCardiacCell.
Definition at line 394 of file BackwardEulerLuoRudyIModel1991.cpp.
double BackwardEulerLuoRudyIModel1991::GetIntracellularCalciumConcentration () [virtual]
[Ca_i] is needed for mechanics, so we explcitly have a Get method (rather than use a get by name type method, to avoid inefficiency when using different cells types of cells). This method by defaults throws an exception, so should be implemented in the concrete class if IntracellularCalciumConcentration is one of the state variables
Reimplemented from AbstractCardiacCell.
Definition at line 118 of file BackwardEulerLuoRudyIModel1991.cpp.
Member Data Documentation
const double BackwardEulerLuoRudyIModel1991::membrane_C = 1.0 [static, private]
Constants for the LuoRudyIModel1991OdeSystem model
Definition at line 46 of file BackwardEulerLuoRudyIModel1991.hpp.
Referenced by UpdateTransmembranePotential().
double BackwardEulerLuoRudyIModel1991::fast_sodium_current_E_Na [private]
another parameter, which is a function of the above
Definition at line 61 of file BackwardEulerLuoRudyIModel1991.hpp.
Referenced by GetIIonic(), Init(), and UpdateTransmembranePotential().
The documentation for this class was generated from the following files:
/tmp/release_1/heart/src/odes/BackwardEulerLuoRudyIModel1991.hpp
/tmp/release_1/heart/src/odes/BackwardEulerLuoRudyIModel1991.cpp