Chaste: ChasteCuboid< SPACE_DIM > Class Template Reference
ChasteCuboid< SPACE_DIM > Class Template Reference
#include <ChasteCuboid.hpp>
Inherits AbstractChasteRegion< SPACE_DIM >.
Public Member Functions
ChasteCuboid (ChastePoint< SPACE_DIM > &rLowerPoint, ChastePoint< SPACE_DIM > &rUpperPoint)
bool DoesContain (const ChastePoint< SPACE_DIM > &rPointToCheck) const
const ChastePoint< SPACE_DIM > & rGetUpperCorner () const
const ChastePoint< SPACE_DIM > & rGetLowerCorner () const
double GetWidth (unsigned rDimension) const
unsigned GetLongestAxis () const
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Private Attributes
ChastePoint< SPACE_DIM > mLowerCorner
ChastePoint< SPACE_DIM > mUpperCorner
Friends
class boost::serialization::access
Detailed Description
template<unsigned SPACE_DIM>
class ChasteCuboid< SPACE_DIM >
This class defines a 3D cuboid and provides a method to check if a given point is contained in the volume.
Definition at line 51 of file ChasteCuboid.hpp.
Constructor & Destructor Documentation
template<unsigned SPACE_DIM> ChasteCuboid< SPACE_DIM >::ChasteCuboid (ChastePoint< SPACE_DIM > & rLowerPoint, ChastePoint< SPACE_DIM > & rUpperPoint) [inline]
The cuboid is defined by any of its two space-diagonal opposite corners.
Parameters:
rLowerPoint Lower vertex of the cuboid.
rUpperPoint Upper vertex of the cuboid.
Definition at line 40 of file ChasteCuboid.cpp.
References EXCEPTION, ChasteCuboid< SPACE_DIM >::mLowerCorner, and ChasteCuboid< SPACE_DIM >::mUpperCorner.
Member Function Documentation
template<unsigned SPACE_DIM> bool ChasteCuboid< SPACE_DIM >::DoesContain (const ChastePoint< SPACE_DIM > & rPointToCheck) const [inline, virtual]
Returns:
true if a given point is contained in the cuboid.
Parameters:
rPointToCheck Point to be checked to be contained in the cuboid.
Implements AbstractChasteRegion< SPACE_DIM >.
Definition at line 54 of file ChasteCuboid.cpp.
References ChasteCuboid< SPACE_DIM >::mLowerCorner, and ChasteCuboid< SPACE_DIM >::mUpperCorner.
template<unsigned SPACE_DIM> unsigned ChasteCuboid< SPACE_DIM >::GetLongestAxis () const [inline]
Returns:
the longest axis of the cuboid (<SPACE_DIM). In the case where there's a tie, then any of the longest axes are returned.
Definition at line 87 of file ChasteCuboid.cpp.
References ChasteCuboid< SPACE_DIM >::mLowerCorner, and ChasteCuboid< SPACE_DIM >::mUpperCorner.
template<unsigned SPACE_DIM> double ChasteCuboid< SPACE_DIM >::GetWidth (unsigned rDimension) const [inline]
Parameters:
rDimension dimension
Returns:
the width in a particular dimension
Definition at line 80 of file ChasteCuboid.cpp.
References ChasteCuboid< SPACE_DIM >::mLowerCorner, and ChasteCuboid< SPACE_DIM >::mUpperCorner.
Referenced by CellBasedPdeHandler< DIM >::OpenResultsFiles(), FineCoarseMeshPair< DIM >::SetUpBoxes(), and CellBasedPdeHandler< DIM >::UseCoarsePdeMesh().
template<unsigned SPACE_DIM> const ChastePoint< SPACE_DIM > & ChasteCuboid< SPACE_DIM >::rGetLowerCorner () const [inline]
Returns:
the lower vertex of the cuboid
Definition at line 74 of file ChasteCuboid.cpp.
References ChasteCuboid< SPACE_DIM >::mLowerCorner.
Referenced by DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::CalculateBoundingBox(), CellBasedPdeHandlerOnCuboid< DIM >::ConstructBoundaryConditionsContainer(), Electrodes< DIM >::Electrodes(), NodePartitioner< ELEMENT_DIM, SPACE_DIM >::GeometricPartitioning(), NodesOnlyMesh< SPACE_DIM >::SetUpBoxCollection(), FineCoarseMeshPair< DIM >::SetUpBoxes(), Cylindrical2dMesh::UpdateTopAndBottom(), and CellBasedPdeHandler< DIM >::UseCoarsePdeMesh().
template<unsigned SPACE_DIM> const ChastePoint< SPACE_DIM > & ChasteCuboid< SPACE_DIM >::rGetUpperCorner () const [inline]
Returns:
the upper vertex of the cuboid
Definition at line 68 of file ChasteCuboid.cpp.
References ChasteCuboid< SPACE_DIM >::mUpperCorner.
Referenced by DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::CalculateBoundingBox(), CellBasedPdeHandlerOnCuboid< DIM >::ConstructBoundaryConditionsContainer(), Electrodes< DIM >::Electrodes(), NodePartitioner< ELEMENT_DIM, SPACE_DIM >::GeometricPartitioning(), NodesOnlyMesh< SPACE_DIM >::SetUpBoxCollection(), FineCoarseMeshPair< DIM >::SetUpBoxes(), Cylindrical2dMesh::UpdateTopAndBottom(), and CellBasedPdeHandler< DIM >::UseCoarsePdeMesh().
template<unsigned SPACE_DIM> template<class Archive > void ChasteCuboid< SPACE_DIM >::serialize (Archive & archive, const unsigned int version) [inline, private]
Archive the member variables.
Parameters:
archive
version
Reimplemented from AbstractChasteRegion< SPACE_DIM >.
Definition at line 62 of file ChasteCuboid.hpp.
Friends And Related Function Documentation
template<unsigned SPACE_DIM> friend class boost::serialization::access [friend]
Needed for serialization.
Reimplemented from AbstractChasteRegion< SPACE_DIM >.
Definition at line 54 of file ChasteCuboid.hpp.
Member Data Documentation
template<unsigned SPACE_DIM> ChastePoint<SPACE_DIM> ChasteCuboid< SPACE_DIM >::mLowerCorner [private]
Lower vertex of the cuboid.
Definition at line 69 of file ChasteCuboid.hpp.
Referenced by ChasteCuboid< SPACE_DIM >::ChasteCuboid(), ChasteCuboid< SPACE_DIM >::DoesContain(), ChasteCuboid< SPACE_DIM >::GetLongestAxis(), ChasteCuboid< SPACE_DIM >::GetWidth(), and ChasteCuboid< SPACE_DIM >::rGetLowerCorner().
template<unsigned SPACE_DIM> ChastePoint<SPACE_DIM> ChasteCuboid< SPACE_DIM >::mUpperCorner [private]
Upper vertex of the cuboid. The space-diagonal opposite corner of mLowerCorner.
Definition at line 72 of file ChasteCuboid.hpp.
Referenced by ChasteCuboid< SPACE_DIM >::ChasteCuboid(), ChasteCuboid< SPACE_DIM >::DoesContain(), ChasteCuboid< SPACE_DIM >::GetLongestAxis(), ChasteCuboid< SPACE_DIM >::GetWidth(), and ChasteCuboid< SPACE_DIM >::rGetUpperCorner().
The documentation for this class was generated from the following files:
mesh/src/utilities/ChasteCuboid.hpp
mesh/src/utilities/ChasteCuboid.cpp