Chaste: CellPopulationElementWriter< ELEMENT_DIM, SPACE_DIM > Class Template Reference
CellPopulationElementWriter< ELEMENT_DIM, SPACE_DIM > Class Template Reference
#include <CellPopulationElementWriter.hpp>
Inherits AbstractCellPopulationWriter< ELEMENT_DIM, SPACE_DIM >.
Public Member Functions
CellPopulationElementWriter ()
virtual void Visit (MeshBasedCellPopulation< ELEMENT_DIM, SPACE_DIM > *pCellPopulation)
virtual void Visit (CaBasedCellPopulation< SPACE_DIM > *pCellPopulation)
virtual void Visit (NodeBasedCellPopulation< SPACE_DIM > *pCellPopulation)
virtual void Visit (PottsBasedCellPopulation< SPACE_DIM > *pCellPopulation)
virtual void Visit (VertexBasedCellPopulation< SPACE_DIM > *pCellPopulation)
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Friends
class boost::serialization::access
Detailed Description
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM>
class CellPopulationElementWriter< ELEMENT_DIM, SPACE_DIM >
A class written using the visitor pattern for writing population elements from a cell population to file.
Definition at line 45 of file CellPopulationElementWriter.hpp.
Constructor & Destructor Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> CellPopulationElementWriter< ELEMENT_DIM, SPACE_DIM >::CellPopulationElementWriter () [inline]
Default constructor.
Definition at line 45 of file CellPopulationElementWriter.cpp.
Member Function Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> template<class Archive > void CellPopulationElementWriter< ELEMENT_DIM, SPACE_DIM >::serialize (Archive & archive, const unsigned int version) [inline, private]
Serialize the object and its member variables.
Parameters:
archive the archive
version the current version of this class
Reimplemented from AbstractCellPopulationWriter< ELEMENT_DIM, SPACE_DIM >.
Definition at line 57 of file CellPopulationElementWriter.hpp.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void CellPopulationElementWriter< ELEMENT_DIM, SPACE_DIM >::Visit (VertexBasedCellPopulation< SPACE_DIM > * pCellPopulation) [inline, virtual]
Visit the population and write the data.
Parameters:
pCellPopulation a pointer to the VertexBasedCellPopulation to visit.
Implements AbstractCellPopulationWriter< ELEMENT_DIM, SPACE_DIM >.
Definition at line 135 of file CellPopulationElementWriter.cpp.
References AbstractCellPopulation< ELEMENT_DIM, ELEMENT_DIM >::Begin(), AbstractCellPopulation< ELEMENT_DIM, ELEMENT_DIM >::End(), AbstractCellPopulation< ELEMENT_DIM, ELEMENT_DIM >::GetCellUsingLocationIndex(), VertexMesh< ELEMENT_DIM, SPACE_DIM >::GetElement(), VertexBasedCellPopulation< DIM >::GetElement(), AbstractCellPopulation< ELEMENT_DIM, ELEMENT_DIM >::GetLocationIndexUsingCell(), AbstractElement< ELEMENT_DIM, SPACE_DIM >::GetNodeGlobalIndex(), AbstractElement< ELEMENT_DIM, SPACE_DIM >::GetNumNodes(), AbstractCellPopulation< ELEMENT_DIM, ELEMENT_DIM >::IsCellAttachedToLocationIndex(), AbstractCellBasedWriter< ELEMENT_DIM, SPACE_DIM >::mpOutStream, and VertexBasedCellPopulation< DIM >::rGetMesh().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void CellPopulationElementWriter< ELEMENT_DIM, SPACE_DIM >::Visit (PottsBasedCellPopulation< SPACE_DIM > * pCellPopulation) [inline, virtual]
Visit the population and write the data.
Parameters:
pCellPopulation a pointer to the PottsBasedCellPopulation to visit.
Implements AbstractCellPopulationWriter< ELEMENT_DIM, SPACE_DIM >.
Definition at line 99 of file CellPopulationElementWriter.cpp.
References AbstractCellPopulation< DIM >::Begin(), AbstractCellPopulation< DIM >::End(), AbstractCellPopulation< DIM >::GetCellUsingLocationIndex(), PottsBasedCellPopulation< DIM >::GetElement(), AbstractCellPopulation< DIM >::GetLocationIndexUsingCell(), AbstractElement< ELEMENT_DIM, SPACE_DIM >::GetNodeGlobalIndex(), AbstractElement< ELEMENT_DIM, SPACE_DIM >::GetNumNodes(), AbstractCellPopulation< DIM >::IsCellAttachedToLocationIndex(), AbstractCellBasedWriter< ELEMENT_DIM, SPACE_DIM >::mpOutStream, and PottsBasedCellPopulation< DIM >::rGetMesh().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void CellPopulationElementWriter< ELEMENT_DIM, SPACE_DIM >::Visit (NodeBasedCellPopulation< SPACE_DIM > * pCellPopulation) [inline, virtual]
Visit the population and write the data.
Parameters:
pCellPopulation a pointer to the NodeBasedCellPopulation to visit.
Implements AbstractCellPopulationWriter< ELEMENT_DIM, SPACE_DIM >.
Definition at line 94 of file CellPopulationElementWriter.cpp.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void CellPopulationElementWriter< ELEMENT_DIM, SPACE_DIM >::Visit (CaBasedCellPopulation< SPACE_DIM > * pCellPopulation) [inline, virtual]
Visit the population and write the data.
Parameters:
pCellPopulation a pointer to the CaBasedCellPopulation to visit.
Implements AbstractCellPopulationWriter< ELEMENT_DIM, SPACE_DIM >.
Definition at line 89 of file CellPopulationElementWriter.cpp.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void CellPopulationElementWriter< ELEMENT_DIM, SPACE_DIM >::Visit (MeshBasedCellPopulation< ELEMENT_DIM, SPACE_DIM > * pCellPopulation) [inline, virtual]
Visit the population and write the data.
Parameters:
pCellPopulation a pointer to the MeshBasedCellPopulation to visit.
Implements AbstractCellPopulationWriter< ELEMENT_DIM, SPACE_DIM >.
Definition at line 51 of file CellPopulationElementWriter.cpp.
References AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::GetCellUsingLocationIndex(), MeshBasedCellPopulation< ELEMENT_DIM, SPACE_DIM >::GetNode(), AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::IsCellAttachedToLocationIndex(), AbstractCellBasedWriter< ELEMENT_DIM, SPACE_DIM >::mpOutStream, and MeshBasedCellPopulation< ELEMENT_DIM, SPACE_DIM >::rGetMesh().
Friends And Related Function Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> friend class boost::serialization::access [friend]
Needed for serialization.
Reimplemented from AbstractCellPopulationWriter< ELEMENT_DIM, SPACE_DIM >.
Definition at line 49 of file CellPopulationElementWriter.hpp.
The documentation for this class was generated from the following files:
cell_based/src/population/writers/population_writers/CellPopulationElementWriter.hpp
cell_based/src/population/writers/population_writers/CellPopulationElementWriter.cpp