Chaste: HeartRegionCode Class Reference
HeartRegionCode Class Reference
#include <HeartRegionCodes.hpp>
Static Public Member Functions
static HeartRegionType GetValidTissueId ()
static HeartRegionType GetValidBathId ()
static bool IsRegionTissue (HeartRegionType regionId)
static bool IsRegionBath (HeartRegionType regionId)
Private Member Functions
HeartRegionCode ()
HeartRegionCode (const HeartRegionCode &)
HeartRegionCode & operator= (const HeartRegionCode &)
Detailed Description
Codes that can be used to annotate regions of a cardiac mesh.
See Node::GetRegion, Node::SetRegion, AbstractElement::GetUnsignedAttribute, AbstractElement::SetAttribute.
Note: these constants are set explicitly to be of type unsigned, so as to match the above methods. Hence why we use a class instead of an enum - you can't (until C++0x) specify the underlying type of an enum.
Definition at line 52 of file HeartRegionCodes.hpp.
Constructor & Destructor Documentation
HeartRegionCode::HeartRegionCode () [private]
No instances of this class should be created.
HeartRegionCode::HeartRegionCode (const HeartRegionCode &) [private]
No instances of this class should be created.
Member Function Documentation
HeartRegionType HeartRegionCode::GetValidBathId () [static]
Returns:
a valid bath identifier
Definition at line 47 of file HeartRegionCodes.cpp.
References HeartConfig::Instance(), and HeartConfig::rGetBathIdentifiers().
Referenced by BidomainProblem< DIM >::AnalyseMeshForBath(), AbstractCardiacMechanicsSolver< ELASTICITY_SOLVER, DIM >::Initialise(), and SetCircularTissueIn2dMesh().
HeartRegionType HeartRegionCode::GetValidTissueId () [static]
Returns:
a valid tissue identifier
Definition at line 40 of file HeartRegionCodes.cpp.
References HeartConfig::Instance(), and HeartConfig::rGetTissueIdentifiers().
Referenced by BidomainProblem< DIM >::AnalyseMeshForBath().
bool HeartRegionCode::IsRegionBath (HeartRegionType regionId) [static]
Returns:
For a given region identifier, determines whether it is a bath identifier
Parameters:
regionId region identifier
Definition at line 59 of file HeartRegionCodes.cpp.
References HeartConfig::Instance().
Referenced by BidomainProblem< DIM >::AnalyseMeshForBath(), ExtendedBidomainMassMatrixAssembler< DIM >::ComputeMatrixTerm(), BidomainWithBathAssembler< ELEMENT_DIM, SPACE_DIM >::ComputeMatrixTerm(), BidomainMassMatrixAssembler< DIM >::ComputeMatrixTerm(), AbstractCardiacCellFactory< ELEMENT_DIM, SPACE_DIM >::CreateCardiacCellForNode(), BidomainProblem< DIM >::CreateInitialCondition(), AbstractBidomainSolver< ELEMENT_DIM, SPACE_DIM >::FinaliseForBath(), HeartConfig::GetBathConductivity(), AbstractBidomainSolver< ELEMENT_DIM, SPACE_DIM >::InitialiseForSolve(), BidomainSolver< ELEMENT_DIM, SPACE_DIM >::SetupLinearSystem(), PseudoEcgCalculator< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::ShouldSkipThisElement(), and AbstractCardiacProblem< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::WriteExtraVariablesOneStep().
bool HeartRegionCode::IsRegionTissue (HeartRegionType regionId) [static]
Returns:
For a given region identifier, determines whether it is a tissue identifier
Parameters:
regionId region identifier
Definition at line 54 of file HeartRegionCodes.cpp.
References HeartConfig::Instance().
Referenced by BidomainProblem< DIM >::AnalyseMeshForBath(), and BathCellFactory< DIM, CELLTYPE >::CreateCardiacCellForTissueNode().
HeartRegionCode& HeartRegionCode::operator= (const HeartRegionCode &) [private]
No instances of this class should be created.
Returns:
reference by language convention
The documentation for this class was generated from the following files:
heart/src/problem/HeartRegionCodes.hpp
heart/src/problem/HeartRegionCodes.cpp