Chaste: DistributedVectorFactory Class Reference
DistributedVectorFactory Class Reference
#include <DistributedVectorFactory.hpp>
Public Member Functions
DistributedVectorFactory (Vec vec)
DistributedVectorFactory (unsigned size, PetscInt local=PETSC_DECIDE)
DistributedVectorFactory (DistributedVectorFactory *pOriginalFactory)
DistributedVectorFactory (unsigned lo, unsigned hi, unsigned size, unsigned numProcs=PetscTools::GetNumProcs())
~DistributedVectorFactory ()
Vec CreateVec ()
Vec CreateVec (unsigned stride)
DistributedVector CreateDistributedVector (Vec vec)
bool IsGlobalIndexLocal (unsigned globalIndex)
unsigned GetLocalOwnership () const
unsigned GetHigh () const
unsigned GetLow () const
unsigned GetProblemSize () const
unsigned GetNumProcs () const
DistributedVectorFactory * GetOriginalFactory ()
void SetOriginalFactory (DistributedVectorFactory *pOriginalFactory)
void SetFromFactory (DistributedVectorFactory *pFactory)
std::vector< unsigned > & rGetGlobalLows ()
Static Public Member Functions
static void SetCheckNumberOfProcessesOnLoad (bool checkNumberOfProcessesOnLoad=true)
static bool CheckNumberOfProcessesOnLoad ()
Private Member Functions
void CheckForPetsc ()
void CalculateOwnership (Vec vec)
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Private Attributes
unsigned mLo
unsigned mHi
unsigned mProblemSize
unsigned mNumProcs
bool mPetscStatusKnown
std::vector< unsigned > mGlobalLows
DistributedVectorFactory * mpOriginalFactory
Static Private Attributes
static bool msCheckNumberOfProcessesOnLoad = true
Friends
class boost::serialization::access
Detailed Description
Factory for creating PETSc vectors distributed across processes.
Replacement for the vector creation portions of DistributedVector (which was implemented using static methods and data), the factory class allows several patterns of PETSc vector length (and distributions among processes) to co-exist.
All vectors created by a factory instance will have the same base size and parallelisation pattern.
Definition at line 57 of file DistributedVectorFactory.hpp.
Constructor & Destructor Documentation
DistributedVectorFactory::DistributedVectorFactory (Vec vec)
Set the problem with an existing PETSc vector -- must have stride=1.
Parameters:
vec is a PETSc vector which we want to use as the pattern for future vectors produced by this factory
Definition at line 81 of file DistributedVectorFactory.cpp.
References CalculateOwnership().
DistributedVectorFactory::DistributedVectorFactory (unsigned size, PetscInt local = PETSC_DECIDE)
Set the problem size specifying distribution over local processor.
Parameters:
size the problem size
local defaults to PETSc's default
Definition at line 88 of file DistributedVectorFactory.cpp.
References CalculateOwnership(), CheckForPetsc(), CreateVec(), and PetscTools::Destroy().
DistributedVectorFactory::DistributedVectorFactory (DistributedVectorFactory * pOriginalFactory)
Constructor for use in archiving. Note that this constructor is only called when the number of processes is different from the original. Therefore, the orignal local node ownership cannot be used, and a new even partition will be applied.
Parameters:
pOriginalFactory see mpOriginalFactory
Definition at line 100 of file DistributedVectorFactory.cpp.
References CalculateOwnership(), CreateVec(), PetscTools::Destroy(), GetProblemSize(), and mpOriginalFactory.
DistributedVectorFactory::DistributedVectorFactory (unsigned lo, unsigned hi, unsigned size, unsigned numProcs = PetscTools::GetNumProcs())
Constructor intended for use in archiving. Allows complete manual specification of the factory.
Parameters:
lo first index owned by this process
hi one beyond last index owned by this process
size total size of vectors
numProcs the number of processes expected (defaults to the current number)
Definition at line 116 of file DistributedVectorFactory.cpp.
References CheckForPetsc().
DistributedVectorFactory::~DistributedVectorFactory ()
Destructor deletes mpOriginalFactory if it exists.
Definition at line 129 of file DistributedVectorFactory.cpp.
References mpOriginalFactory.
Member Function Documentation
void DistributedVectorFactory::CalculateOwnership (Vec vec) [private]
Helper method for the constructors.
Parameters:
vec the sample PETSc vector from which to calculate ownerships
Definition at line 44 of file DistributedVectorFactory.cpp.
References CheckForPetsc(), GetNumProcs(), mGlobalLows, mHi, mLo, mNumProcs, mPetscStatusKnown, and mProblemSize.
Referenced by DistributedVectorFactory().
void DistributedVectorFactory::CheckForPetsc () [private]
Double check (in debug code) that PETSc has been initialised properly.
Definition at line 134 of file DistributedVectorFactory.cpp.
References mPetscStatusKnown.
Referenced by CalculateOwnership(), and DistributedVectorFactory().
static bool DistributedVectorFactory::CheckNumberOfProcessesOnLoad () [inline, static]
Determine whether, when loading an instance from an archive, to check that the current number of processes matches that used in creating the archive.
Returns:
true when check is required
Definition at line 247 of file DistributedVectorFactory.hpp.
References msCheckNumberOfProcessesOnLoad.
DistributedVector DistributedVectorFactory::CreateDistributedVector (Vec vec)
Create a distributed vector which wraps a given petsc vector.
Parameters:
vec is the vector
Returns:
the distributed vector
Definition at line 183 of file DistributedVectorFactory.cpp.
Referenced by BoundaryConditionsContainer< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::ApplyDirichletToNonlinearResidual(), ExtendedBidomainProblem< DIM >::CreateInitialCondition(), AbstractCardiacProblem< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::CreateInitialCondition(), AbstractExtendedBidomainSolver< ELEMENT_DIM, SPACE_DIM >::GenerateNullBasis(), AbstractBidomainSolver< ELEMENT_DIM, SPACE_DIM >::GenerateNullBasis(), ParallelColumnDataWriter::PutVectorStripe(), OperatorSplittingMonodomainSolver< ELEMENT_DIM, SPACE_DIM >::SetupLinearSystem(), MonodomainSolver< ELEMENT_DIM, SPACE_DIM >::SetupLinearSystem(), ExtendedBidomainSolver< ELEM_DIM, SPACE_DIM >::SetupLinearSystem(), BidomainSolver< ELEMENT_DIM, SPACE_DIM >::SetupLinearSystem(), ExtendedBidomainTissue< SPACE_DIM >::SolveCellSystems(), AbstractCardiacTissue< ELEMENT_DIM, SPACE_DIM >::SolveCellSystems(), and PostProcessingWriter< ELEMENT_DIM, SPACE_DIM >::WriteOutputDataToHdf5().
Vec DistributedVectorFactory::CreateVec (unsigned stride)
Create a striped PETSc vector of size: stride * problem size.
Parameters:
stride
Returns:
new PETSc vector
Definition at line 160 of file DistributedVectorFactory.cpp.
References mHi, mLo, and mProblemSize.
Vec DistributedVectorFactory::CreateVec ()
Create a PETSc vector of the problem size.
Returns:
new PETSc vector
Definition at line 154 of file DistributedVectorFactory.cpp.
References mHi, mLo, and mProblemSize.
Referenced by AbstractContinuumMechanicsSolver< DIM >::AllocateMatrixMemory(), ExtendedBidomainProblem< DIM >::CreateInitialCondition(), AbstractCardiacProblem< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::CreateInitialCondition(), DistributedVectorFactory(), AbstractExtendedBidomainSolver< ELEMENT_DIM, SPACE_DIM >::GenerateNullBasis(), AbstractBidomainSolver< ELEMENT_DIM, SPACE_DIM >::GenerateNullBasis(), Hdf5ToTxtConverter< ELEMENT_DIM, SPACE_DIM >::Hdf5ToTxtConverter(), Hdf5ToVtkConverter< ELEMENT_DIM, SPACE_DIM >::Hdf5ToVtkConverter(), ParallelColumnDataWriter::PutVectorStripe(), CardiacElectroMechanicsProblem< DIM, ELEC_PROB_DIM >::Solve(), Hdf5ToMeshalyzerConverter< ELEMENT_DIM, SPACE_DIM >::Write(), Hdf5ToCmguiConverter< ELEMENT_DIM, SPACE_DIM >::Write(), and PostProcessingWriter< ELEMENT_DIM, SPACE_DIM >::WriteOutputDataToHdf5().
unsigned DistributedVectorFactory::GetHigh () const [inline]
Returns:
mHi - The next index above the top one owned by the process.
Definition at line 202 of file DistributedVectorFactory.hpp.
References mHi.
Referenced by AbstractCardiacTissue< ELEMENT_DIM, SPACE_DIM >::AbstractCardiacTissue(), DistributedBoxCollection< DIM >::CalculateNumberOfNodesInEachStrip(), DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructCuboid(), DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructLinearMesh(), DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructRectangularMesh(), CardiacSimulation::CreateAndRun(), Hdf5DataWriter::DefineFixedDimension(), DistributedBoxCollection< DIM >::DistributedBoxCollection(), DistributedVector::DistributedVector(), NodePartitioner< ELEMENT_DIM, SPACE_DIM >::DumbPartitioning(), ExtendedBidomainTissue< SPACE_DIM >::ExtendedBidomainTissue(), AbstractCardiacTissue< ELEMENT_DIM, SPACE_DIM >::GetCardiacCell(), DistributedBoxCollection< DIM >::GetNumLocalRows(), DistributedBoxCollection< DIM >::GetNumRowsOfBoxes(), AbstractCardiacTissue< ELEMENT_DIM, SPACE_DIM >::GetPurkinjeCell(), ExtendedBidomainTissue< SPACE_DIM >::ReplicateAdditionalCaches(), AbstractCardiacTissue< ELEMENT_DIM, SPACE_DIM >::ReplicateCaches(), AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::SetElementOwnerships(), SetFromFactory(), DistributedBoxCollection< DIM >::SetupHaloBoxes(), DistributedBoxCollection< DIM >::SetupLocalBoxesHalfOnly(), and CardiacElectroMechanicsProblem< DIM, ELEC_PROB_DIM >::Solve().
unsigned DistributedVectorFactory::GetLocalOwnership () const [inline]
Returns:
The number of elements in the vector owned by the local process.
Definition at line 194 of file DistributedVectorFactory.hpp.
References mHi, and mLo.
Referenced by AbstractCardiacTissue< ELEMENT_DIM, SPACE_DIM >::AbstractCardiacTissue(), DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructCuboid(), DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructLinearMesh(), DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructRectangularMesh(), ExtendedBidomainTissue< SPACE_DIM >::CreateGGapConductivities(), Hdf5DataWriter::DefineFixedDimension(), ExtendedBidomainTissue< SPACE_DIM >::ExtendedBidomainTissue(), Hdf5DataWriter::Hdf5DataWriter(), AbstractCardiacTissue< SPACE_DIM >::load(), AbstractCardiacTissue< SPACE_DIM >::LoadCardiacCells(), and AbstractCardiacTissue< SPACE_DIM >::save().
unsigned DistributedVectorFactory::GetLow () const [inline]
Returns:
mLo - The lowest index owned by the process.
Definition at line 210 of file DistributedVectorFactory.hpp.
References mLo.
Referenced by AbstractCardiacTissue< ELEMENT_DIM, SPACE_DIM >::AbstractCardiacTissue(), DistributedBoxCollection< DIM >::CalculateNumberOfNodesInEachStrip(), DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructCuboid(), DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructLinearMesh(), DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructRectangularMesh(), CardiacSimulation::CreateAndRun(), ExtendedBidomainTissue< SPACE_DIM >::CreateGGapConductivities(), Hdf5DataWriter::DefineFixedDimension(), DistributedBoxCollection< DIM >::DistributedBoxCollection(), DistributedVector::DistributedVector(), NodePartitioner< ELEMENT_DIM, SPACE_DIM >::DumbPartitioning(), ExtendedBidomainTissue< SPACE_DIM >::ExtendedBidomainTissue(), AbstractCardiacTissue< ELEMENT_DIM, SPACE_DIM >::GetCardiacCell(), AbstractCardiacTissue< ELEMENT_DIM, SPACE_DIM >::GetCardiacCellOrHaloCell(), ExtendedBidomainTissue< SPACE_DIM >::GetCardiacSecondCell(), ExtendedBidomainTissue< SPACE_DIM >::GetExtracellularStimulus(), DistributedBoxCollection< DIM >::GetNumLocalRows(), DistributedBoxCollection< DIM >::GetNumRowsOfBoxes(), AbstractCardiacTissue< ELEMENT_DIM, SPACE_DIM >::GetPurkinjeCell(), AbstractCardiacTissue< SPACE_DIM >::load(), AbstractCardiacTissue< SPACE_DIM >::LoadCardiacCells(), ExtendedBidomainTissue< SPACE_DIM >::ReplicateAdditionalCaches(), AbstractCardiacTissue< ELEMENT_DIM, SPACE_DIM >::ReplicateCaches(), AbstractCardiacTissue< SPACE_DIM >::save(), AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::SetElementOwnerships(), SetFromFactory(), DistributedBoxCollection< DIM >::SetupHaloBoxes(), DistributedBoxCollection< DIM >::SetupLocalBoxesHalfOnly(), CardiacElectroMechanicsProblem< DIM, ELEC_PROB_DIM >::Solve(), and AbstractCardiacTissue< ELEMENT_DIM, SPACE_DIM >::SolveCellSystems().
unsigned DistributedVectorFactory::GetNumProcs () const [inline]
Returns:
mNumProcs - how many processes this factory is expecting.
Definition at line 226 of file DistributedVectorFactory.hpp.
References mNumProcs.
Referenced by CalculateOwnership(), AbstractTetrahedralMesh< SPACE_DIM, SPACE_DIM >::load(), AbstractCardiacProblem< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::LoadExtraArchive(), CardiacSimulationArchiver< PROBLEM_CLASS >::Migrate(), rGetGlobalLows(), AbstractMesh< ELEMENT_DIM, SPACE_DIM >::SetDistributedVectorFactory(), and SetFromFactory().
DistributedVectorFactory* DistributedVectorFactory::GetOriginalFactory () [inline]
If msCheckNumberOfProcessesOnLoad is not set, and this factory was loaded from an archive, then return a factory with the settings from the archive, which may not be the same as ours - if running on a different number of processes from the original, we will have used PETSC_DECIDE to set the local ownership on load.
Returns:
the original factory
Definition at line 259 of file DistributedVectorFactory.hpp.
References mpOriginalFactory.
Referenced by AbstractTetrahedralMesh< SPACE_DIM, SPACE_DIM >::load(), AbstractCardiacProblem< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::LoadExtraArchive(), and CardiacSimulationArchiver< PROBLEM_CLASS >::Migrate().
unsigned DistributedVectorFactory::GetProblemSize () const [inline]
Returns:
The number of elements in (normal) vectors created by CreateVec().
Definition at line 218 of file DistributedVectorFactory.hpp.
References mProblemSize.
Referenced by AbstractCardiacTissue< ELEMENT_DIM, SPACE_DIM >::AbstractCardiacTissue(), DistributedVector::DistributedVector(), DistributedVectorFactory(), NodePartitioner< ELEMENT_DIM, SPACE_DIM >::DumbPartitioning(), ExtendedBidomainTissue< SPACE_DIM >::ExtendedBidomainTissue(), AbstractCardiacTissue< SPACE_DIM >::load(), and SetFromFactory().
bool DistributedVectorFactory::IsGlobalIndexLocal (unsigned globalIndex)
Test if the given global index is owned by the current process, i.e. is local to it.
Parameters:
globalIndex a global index
Returns:
true if the global index can be accessed by this process
Definition at line 149 of file DistributedVectorFactory.cpp.
References mHi, and mLo.
Referenced by HeartGeometryInformation< SPACE_DIM >::CalculateBoundingBoxOfSurface(), ElectrodesStimulusFactory< DIM >::CheckForElectrodesIntersection(), HeartConfigRelatedCellFactory< SPACE_DIM >::FillInCellularTransmuralAreas(), AbstractCardiacTissue< ELEMENT_DIM, SPACE_DIM >::GetCardiacCellOrHaloCell(), AbstractCardiacTissue< SPACE_DIM >::LoadCardiacCells(), and CardiacElectroMechanicsProblem< DIM, ELEC_PROB_DIM >::Solve().
std::vector< unsigned > & DistributedVectorFactory::rGetGlobalLows ()
Returns:
the mLo value from each process in a vector. This is calculated on the first call and cached for later use.
Definition at line 189 of file DistributedVectorFactory.cpp.
References PetscTools::GetNumProcs(), GetNumProcs(), mGlobalLows, and mLo.
Referenced by AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::CalculateNodeExchange().
template<class Archive > void DistributedVectorFactory::serialize (Archive & archive, const unsigned int version) [inline, private]
Archive the member variables.
Parameters:
archive the archive
version the current version of this class
Definition at line 115 of file DistributedVectorFactory.hpp.
static void DistributedVectorFactory::SetCheckNumberOfProcessesOnLoad (bool checkNumberOfProcessesOnLoad = true) [inline, static]
Set whether, when loading an instance from an archive, to check that the current number of processes matches that used in creating the archive.
Parameters:
checkNumberOfProcessesOnLoad
Definition at line 237 of file DistributedVectorFactory.hpp.
References msCheckNumberOfProcessesOnLoad.
Referenced by CardiacSimulationArchiver< PROBLEM_CLASS >::Migrate().
void DistributedVectorFactory::SetFromFactory (DistributedVectorFactory * pFactory)
Set mLo and mHi from another vector factory. Used by archiving.
Parameters:
pFactory the factory to set from.
Definition at line 66 of file DistributedVectorFactory.cpp.
References EXCEPTION, GetHigh(), GetLow(), GetNumProcs(), GetProblemSize(), mGlobalLows, mHi, mLo, mNumProcs, and mProblemSize.
Referenced by AbstractTetrahedralMesh< SPACE_DIM, SPACE_DIM >::load().
void DistributedVectorFactory::SetOriginalFactory (DistributedVectorFactory * pOriginalFactory) [inline]
Set method for mpOriginalFactory, used by archiving (load_construct_data).
Parameters:
pOriginalFactory see mpOriginalFactory
Definition at line 268 of file DistributedVectorFactory.hpp.
References mpOriginalFactory.
Friends And Related Function Documentation
friend class boost::serialization::access [friend]
Needed for serialization.
Definition at line 106 of file DistributedVectorFactory.hpp.
Member Data Documentation
std::vector<unsigned> DistributedVectorFactory::mGlobalLows [private]
A cached vector of mLo values from each process.
Definition at line 79 of file DistributedVectorFactory.hpp.
Referenced by CalculateOwnership(), rGetGlobalLows(), and SetFromFactory().
unsigned DistributedVectorFactory::mHi [private]
One above the last entry owned by the current processor.
Definition at line 67 of file DistributedVectorFactory.hpp.
Referenced by CalculateOwnership(), CreateVec(), GetHigh(), GetLocalOwnership(), IsGlobalIndexLocal(), and SetFromFactory().
unsigned DistributedVectorFactory::mLo [private]
The first entry owned by the current processor.
Definition at line 64 of file DistributedVectorFactory.hpp.
Referenced by CalculateOwnership(), CreateVec(), GetLocalOwnership(), GetLow(), IsGlobalIndexLocal(), rGetGlobalLows(), and SetFromFactory().
unsigned DistributedVectorFactory::mNumProcs [private]
How many processes this factory is expecting.
Definition at line 73 of file DistributedVectorFactory.hpp.
Referenced by CalculateOwnership(), GetNumProcs(), and SetFromFactory().
bool DistributedVectorFactory::mPetscStatusKnown [private]
Whether we've checked that PETSc is initialised.
Definition at line 76 of file DistributedVectorFactory.hpp.
Referenced by CalculateOwnership(), and CheckForPetsc().
DistributedVectorFactory* DistributedVectorFactory::mpOriginalFactory [private]
If this instance was loaded from an archive, this points to a factory with the settings from the archive, which may not be the same as this instance.
Definition at line 91 of file DistributedVectorFactory.hpp.
Referenced by DistributedVectorFactory(), GetOriginalFactory(), SetOriginalFactory(), and ~DistributedVectorFactory().
unsigned DistributedVectorFactory::mProblemSize [private]
The problem size, i.e. the number of nodes in the mesh (the number of unknowns may be larger in a Stripe).
Definition at line 70 of file DistributedVectorFactory.hpp.
Referenced by CalculateOwnership(), CreateVec(), GetProblemSize(), and SetFromFactory().
bool DistributedVectorFactory::msCheckNumberOfProcessesOnLoad = true [static, private]
Whether, when loading an instance from an archive, to check that the current number of processes matches that used in creating the archive.
Definition at line 85 of file DistributedVectorFactory.hpp.
Referenced by CheckNumberOfProcessesOnLoad(), and SetCheckNumberOfProcessesOnLoad().
The documentation for this class was generated from the following files:
global/src/parallel/DistributedVectorFactory.hpp
global/src/parallel/DistributedVectorFactory.cpp