Chaste: AbstractPottsUpdateRule< DIM > Class Template Reference
AbstractPottsUpdateRule< DIM > Class Template Reference
#include <AbstractPottsUpdateRule.hpp>
Inherits Identifiable.
Inherited by AdhesionPottsUpdateRule< DIM >, ChemotaxisPottsUpdateRule< DIM >, SurfaceAreaConstraintPottsUpdateRule< DIM >, and VolumeConstraintPottsUpdateRule< DIM >.
Public Member Functions
AbstractPottsUpdateRule ()
virtual ~AbstractPottsUpdateRule ()
virtual double EvaluateHamiltonianContribution (unsigned currentNodeIndex, unsigned targetNodeIndex, PottsBasedCellPopulation< DIM > &rCellPopulation)=0
void OutputUpdateRuleInfo (out_stream &rParamsFile)
virtual void OutputUpdateRuleParameters (out_stream &rParamsFile)=0
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Friends
class boost::serialization::access
Detailed Description
template<unsigned DIM>
class AbstractPottsUpdateRule< DIM >
An abstract Potts update rule class, for use in cell-based simulations using the cellular Potts model.
Definition at line 52 of file AbstractPottsUpdateRule.hpp.
Constructor & Destructor Documentation
template<unsigned DIM> AbstractPottsUpdateRule< DIM >::AbstractPottsUpdateRule () [inline]
Default constructor.
Definition at line 39 of file AbstractPottsUpdateRule.cpp.
template<unsigned DIM> AbstractPottsUpdateRule< DIM >::~AbstractPottsUpdateRule () [inline, virtual]
Destructor.
Definition at line 44 of file AbstractPottsUpdateRule.cpp.
Member Function Documentation
template<unsigned DIM> virtual double AbstractPottsUpdateRule< DIM >::EvaluateHamiltonianContribution (unsigned currentNodeIndex, unsigned targetNodeIndex, PottsBasedCellPopulation< DIM > & rCellPopulation) [pure virtual]
Calculate the contribution to the Hamiltonian.
Parameters:
currentNodeIndex The index of the current node/lattice site
targetNodeIndex The index of the target node/lattice site
rCellPopulation The cell population
Returns:
The difference in the Hamiltonian with the configuration of the target node having the same spin as the current node with the current configuration. i.e H_1-H_0
Implemented in AdhesionPottsUpdateRule< DIM >, ChemotaxisPottsUpdateRule< DIM >, SurfaceAreaConstraintPottsUpdateRule< DIM >, and VolumeConstraintPottsUpdateRule< DIM >.
template<unsigned DIM> void AbstractPottsUpdateRule< DIM >::OutputUpdateRuleInfo (out_stream & rParamsFile) [inline]
Output update rule to file. Call OutputUpdateRuleParameters() to output all member variables to file.
Parameters:
rParamsFile a file stream
Definition at line 49 of file AbstractPottsUpdateRule.cpp.
References Identifiable::GetIdentifier(), and AbstractPottsUpdateRule< DIM >::OutputUpdateRuleParameters().
template<unsigned DIM> void AbstractPottsUpdateRule< DIM >::OutputUpdateRuleParameters (out_stream & rParamsFile) [inline, pure virtual]
Output update rule parameters to file.
As this method is pure virtual, it must be overridden in subclasses.
Parameters:
rParamsFile a file stream
Implemented in AdhesionPottsUpdateRule< DIM >, ChemotaxisPottsUpdateRule< DIM >, DifferentialAdhesionPottsUpdateRule< DIM >, SurfaceAreaConstraintPottsUpdateRule< DIM >, and VolumeConstraintPottsUpdateRule< DIM >.
Definition at line 59 of file AbstractPottsUpdateRule.cpp.
Referenced by AbstractPottsUpdateRule< DIM >::OutputUpdateRuleInfo().
template<unsigned DIM> template<class Archive > void AbstractPottsUpdateRule< DIM >::serialize (Archive & archive, const unsigned int version) [inline, private]
Boost Serialization method for archiving/checkpointing. Archives the object and its member variables.
Parameters:
archive The boost archive.
version The current version of this class.
Reimplemented in AdhesionPottsUpdateRule< DIM >, ChemotaxisPottsUpdateRule< DIM >, DifferentialAdhesionPottsUpdateRule< DIM >, SurfaceAreaConstraintPottsUpdateRule< DIM >, and VolumeConstraintPottsUpdateRule< DIM >.
Definition at line 64 of file AbstractPottsUpdateRule.hpp.
Friends And Related Function Documentation
template<unsigned DIM> friend class boost::serialization::access [friend]
Needed for serialization.
Reimplemented in AdhesionPottsUpdateRule< DIM >, ChemotaxisPottsUpdateRule< DIM >, DifferentialAdhesionPottsUpdateRule< DIM >, SurfaceAreaConstraintPottsUpdateRule< DIM >, and VolumeConstraintPottsUpdateRule< DIM >.
Definition at line 55 of file AbstractPottsUpdateRule.hpp.
The documentation for this class was generated from the following files:
cell_based/src/population/update_rules/AbstractPottsUpdateRule.hpp
cell_based/src/population/update_rules/AbstractPottsUpdateRule.cpp