Chaste: AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::Iterator Class Reference
AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::Iterator Class Reference
#include <AbstractCellPopulation.hpp>
Public Member Functions
CellPtr operator* ()
CellPtr operator-> ()
bool operator!= (const typename AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::Iterator &rOther)
Iterator & operator++ ()
Iterator (AbstractCellPopulation &rCellPopulation, std::list< CellPtr >::iterator cellIter)
virtual ~Iterator ()
Private Member Functions
virtual bool IsRealCell ()
bool IsAtEnd ()
Private Attributes
AbstractCellPopulation & mrCellPopulation
std::list< CellPtr >::iterator mCellIter
Detailed Description
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM = ELEMENT_DIM>
class AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::Iterator
Iterator class allows one to iterate over cells in the cell population. Dereferencing the iterator will give you the current cell. There are also methods to get the node representing this cell, and the location of that node.
Definition at line 668 of file AbstractCellPopulation.hpp.
Constructor & Destructor Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::Iterator::Iterator (AbstractCellPopulation & rCellPopulation, std::list< CellPtr >::iterator cellIter) [inline]
Constructor for a new iterator.
Parameters:
rCellPopulation the cell population
cellIter iterator over list of cells
Definition at line 799 of file AbstractCellPopulation.hpp.
References AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::Iterator::IsRealCell(), AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::Iterator::mCellIter, AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::Iterator::mrCellPopulation, and AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::rGetCells().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM = ELEMENT_DIM> virtual AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::Iterator::~Iterator () [inline, virtual]
The iterator must have a virtual destructor.
Definition at line 710 of file AbstractCellPopulation.hpp.
Member Function Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> bool AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::Iterator::IsAtEnd () [inline, private]
Private helper function.
Returns:
whether we're at the end of the cells.
Definition at line 793 of file AbstractCellPopulation.hpp.
References AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::Iterator::mCellIter, AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::Iterator::mrCellPopulation, and AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::rGetCells().
Referenced by AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::Iterator::operator++(), and AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::Iterator::operator->().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> bool AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::Iterator::IsRealCell () [inline, private, virtual]
Private helper function.
Returns:
whether we're pointing at a real cell. Assumes we are within range (i.e. not at End).
Real cells are not deleted.
Definition at line 787 of file AbstractCellPopulation.hpp.
References AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::IsCellAssociatedWithADeletedLocation(), AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::Iterator::mCellIter, and AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::Iterator::mrCellPopulation.
Referenced by AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::Iterator::Iterator(), and AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::Iterator::operator++().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> bool AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::Iterator::operator!= (const typename AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::Iterator & rOther) [inline]
Comparison not-equal-to.
Parameters:
rOther iterator with which comparison is made
Returns:
not-equal
Definition at line 769 of file AbstractCellPopulation.hpp.
References AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::Iterator::mCellIter.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> CellPtr AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::Iterator::operator* () [inline]
Dereference the iterator giving you a pointer to the current cell.
Returns:
reference
Definition at line 755 of file AbstractCellPopulation.hpp.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::Iterator & AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::Iterator::operator++ () [inline]
Prefix increment operator.
Returns:
incremented object
Definition at line 775 of file AbstractCellPopulation.hpp.
References AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::Iterator::IsAtEnd(), AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::Iterator::IsRealCell(), and AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::Iterator::mCellIter.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> CellPtr AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::Iterator::operator-> () [inline]
Unusually for an iterator over a collection of pointers, this method allows you to access the object pointed at, rather than the pointer itself.
Returns:
pointer
Definition at line 762 of file AbstractCellPopulation.hpp.
References AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::Iterator::IsAtEnd(), and AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::Iterator::mCellIter.
Member Data Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM = ELEMENT_DIM> std::list<CellPtr>::iterator AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::Iterator::mCellIter [private]
Cell iterator member.
Definition at line 734 of file AbstractCellPopulation.hpp.
Referenced by AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::Iterator::IsAtEnd(), AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::Iterator::IsRealCell(), AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::Iterator::Iterator(), AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::Iterator::operator!=(), AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::Iterator::operator++(), and AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::Iterator::operator->().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM = ELEMENT_DIM> AbstractCellPopulation& AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::Iterator::mrCellPopulation [private]
The cell population member.
Definition at line 731 of file AbstractCellPopulation.hpp.
Referenced by AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::Iterator::IsAtEnd(), AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::Iterator::IsRealCell(), and AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::Iterator::Iterator().
The documentation for this class was generated from the following file:
cell_based/src/population/AbstractCellPopulation.hpp