Chaste: FibreWriter< DIM > Class Template Reference
FibreWriter< DIM > Class Template Reference
#include <FibreWriter.hpp>
Public Member Functions
FibreWriter (const std::string &rDirectory, const std::string &rBaseName, const bool clearOutputDir=true)
~FibreWriter ()
void WriteAllAxi (const std::vector< c_vector< double, DIM > > &fibres)
void WriteAllOrtho (const std::vector< c_vector< double, DIM > > &fibres, const std::vector< c_vector< double, DIM > > &second, const std::vector< c_vector< double, DIM > > &third)
void SetWriteFileAsBinary ()
Private Member Functions
out_stream OpenFileAndWriteHeader (const std::string &rFileName, unsigned numItems)
Private Attributes
OutputFileHandler * mpOutputFileHandler
std::string mBaseName
bool mFileIsBinary
Detailed Description
template<unsigned DIM>
class FibreWriter< DIM >
A class for writing .axi files (files which define the fibre direction for each element) and .ortho files (files which define the fibre, sheet and normal directions for each element.
Definition at line 53 of file FibreWriter.hpp.
Constructor & Destructor Documentation
template<unsigned DIM> FibreWriter< DIM >::FibreWriter (const std::string & rDirectory, const std::string & rBaseName, const bool clearOutputDir = true) [inline]
Create a new FibreWriter.
Parameters:
rDirectory the directory in which to write the fibre to file
rBaseName the base name of the files in which to write the fibre data
clearOutputDir whether to clean the directory (defaults to true)
Definition at line 40 of file FibreWriter.cpp.
References FibreWriter< DIM >::mpOutputFileHandler.
template<unsigned DIM> FibreWriter< DIM >::~FibreWriter () [inline]
Destructor
Definition at line 50 of file FibreWriter.cpp.
References FibreWriter< DIM >::mpOutputFileHandler.
Member Function Documentation
template<unsigned DIM> out_stream FibreWriter< DIM >::OpenFileAndWriteHeader (const std::string & rFileName, unsigned numItems) [inline, private]
Open a fibre file for writing and write the header line.
Parameters:
rFileName The path and name of the file to create
numItems The number of items (~ number of elements)
Returns:
an outstream pointer to the open file.
Definition at line 124 of file FibreWriter.cpp.
References FibreWriter< DIM >::mFileIsBinary, FibreWriter< DIM >::mpOutputFileHandler, and OutputFileHandler::OpenOutputFile().
Referenced by FibreWriter< DIM >::WriteAllAxi(), and FibreWriter< DIM >::WriteAllOrtho().
template<unsigned DIM> void FibreWriter< DIM >::SetWriteFileAsBinary () [inline]
Switch to write binary fibre file
(set to write ascii files in the constructor)
Definition at line 144 of file FibreWriter.cpp.
References FibreWriter< DIM >::mFileIsBinary.
Referenced by FibreConverter::Convert().
template<unsigned DIM> void FibreWriter< DIM >::WriteAllAxi (const std::vector< c_vector< double, DIM > > & fibres) [inline]
Writes all axisymmetric vectors to the file.
Parameters:
fibres a vector of fibre direction vectors
Definition at line 56 of file FibreWriter.cpp.
References ChasteBuildInfo::GetProvenanceString(), FibreWriter< DIM >::mBaseName, FibreWriter< DIM >::mFileIsBinary, and FibreWriter< DIM >::OpenFileAndWriteHeader().
Referenced by FibreConverter::Convert().
template<unsigned DIM> void FibreWriter< DIM >::WriteAllOrtho (const std::vector< c_vector< double, DIM > > & fibres, const std::vector< c_vector< double, DIM > > & second, const std::vector< c_vector< double, DIM > > & third) [inline]
Writes all orthonormal tensors to the file.
Parameters:
fibres a vector of longitudial fibre direction vectors
second a vector of transverse vectors (orthogonal to fibres)
third a vector of normal vectors (orthogonal to others)
Definition at line 82 of file FibreWriter.cpp.
References ChasteBuildInfo::GetProvenanceString(), FibreWriter< DIM >::mBaseName, FibreWriter< DIM >::mFileIsBinary, and FibreWriter< DIM >::OpenFileAndWriteHeader().
Referenced by FibreConverter::Convert().
Member Data Documentation
template<unsigned DIM> std::string FibreWriter< DIM >::mBaseName [private]
Base name for the input files
Definition at line 58 of file FibreWriter.hpp.
Referenced by FibreWriter< DIM >::WriteAllAxi(), and FibreWriter< DIM >::WriteAllOrtho().
template<unsigned DIM> bool FibreWriter< DIM >::mFileIsBinary [private]
Whether all data is to be written as binary
Definition at line 59 of file FibreWriter.hpp.
Referenced by FibreWriter< DIM >::OpenFileAndWriteHeader(), FibreWriter< DIM >::SetWriteFileAsBinary(), FibreWriter< DIM >::WriteAllAxi(), and FibreWriter< DIM >::WriteAllOrtho().
template<unsigned DIM> OutputFileHandler* FibreWriter< DIM >::mpOutputFileHandler [private]
Output file handler
Definition at line 56 of file FibreWriter.hpp.
Referenced by FibreWriter< DIM >::FibreWriter(), FibreWriter< DIM >::OpenFileAndWriteHeader(), and FibreWriter< DIM >::~FibreWriter().
The documentation for this class was generated from the following files:
heart/src/io/FibreWriter.hpp
heart/src/io/FibreWriter.cpp