Chaste: ParallelCellsGenerator< CELL_CYCLE_MODEL, DIM > Class Template Reference
ParallelCellsGenerator< CELL_CYCLE_MODEL, DIM > Class Template Reference
#include <ParallelCellsGenerator.hpp>
Public Member Functions
void GenerateParallelCells (std::string archivePath, std::vector< CellPtr > &cells, NodesOnlyMesh< DIM > &mesh, boost::shared_ptr< AbstractCellProperty > pCellProliferativeType=boost::shared_ptr< AbstractCellProperty >())
Private Member Functions
c_vector< double, 2 *DIM > GetArchiveBoundingBox (std::string archivePath)
Friends
class TestParallelCellsGenerator
Detailed Description
template<class CELL_CYCLE_MODEL, unsigned DIM>
class ParallelCellsGenerator< CELL_CYCLE_MODEL, DIM >
A helper class for generating a vector of cells and a NodesOnlyMesh from an archive file without loading all cells to memory on each processor.
Definition at line 50 of file ParallelCellsGenerator.hpp.
Member Function Documentation
template<class CELL_CYCLE_MODEL , unsigned DIM> void ParallelCellsGenerator< CELL_CYCLE_MODEL, DIM >::GenerateParallelCells (std::string archivePath, std::vector< CellPtr > & cells, NodesOnlyMesh< DIM > & mesh, boost::shared_ptr< AbstractCellProperty > pCellProliferativeType = boost::shared_ptr<AbstractCellProperty>()) [inline]
Generate nodes and cells for a given decomposition of space, dictated by mesh.
Parameters:
archivePath the name of the file containing the cell locations
cells a reference to an empty vector into which cells can be inserted.
mesh a reference to the mesh that will store the nodes.
pCellProliferativeType the proliferative type of the cells.
Definition at line 82 of file ParallelCellsGenerator.hpp.
References NodesOnlyMesh< SPACE_DIM >::AddNode(), ParallelCellsGenerator< CELL_CYCLE_MODEL, DIM >::GetArchiveBoundingBox(), NodesOnlyMesh< SPACE_DIM >::GetMaximumInteractionDistance(), NodesOnlyMesh< SPACE_DIM >::GetMaximumNodeIndex(), CellPropertyRegistry::Instance(), NodesOnlyMesh< SPACE_DIM >::IsOwned(), NodesOnlyMesh< SPACE_DIM >::ReMesh(), and NodesOnlyMesh< SPACE_DIM >::SetInitialBoxCollection().
template<class CELL_CYCLE_MODEL , unsigned DIM> c_vector< double, 2 *DIM > ParallelCellsGenerator< CELL_CYCLE_MODEL, DIM >::GetArchiveBoundingBox (std::string archivePath) [inline, private]
Calculate the bounding box of all positions in the archive path.
Parameters:
archivePath the path to the cell location archive.
Returns:
the bounding box in format [xmin, xmax...].
Definition at line 145 of file ParallelCellsGenerator.hpp.
References EXCEPTION.
Referenced by ParallelCellsGenerator< CELL_CYCLE_MODEL, DIM >::GenerateParallelCells().
The documentation for this class was generated from the following file:
cell_based/src/population/cell/ParallelCellsGenerator.hpp