Chaste: ApoptoticCellKiller< SPACE_DIM > Class Template Reference
ApoptoticCellKiller< SPACE_DIM > Class Template Reference
#include <ApoptoticCellKiller.hpp>
Inherits AbstractCellKiller< SPACE_DIM >.
Public Member Functions
ApoptoticCellKiller (AbstractCellPopulation< SPACE_DIM > *pCellPopulation)
void CheckAndLabelSingleCellForApoptosis (CellPtr pCell)
virtual void CheckAndLabelCellsForApoptosisOrDeath ()
void OutputCellKillerParameters (out_stream &rParamsFile)
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Friends
class boost::serialization::access
Detailed Description
template<unsigned SPACE_DIM>
class ApoptoticCellKiller< SPACE_DIM >
A cell killer object that kills cells that have been specified using the ApoptoticCellProperty.
Definition at line 48 of file ApoptoticCellKiller.hpp.
Constructor & Destructor Documentation
template<unsigned SPACE_DIM> ApoptoticCellKiller< SPACE_DIM >::ApoptoticCellKiller (AbstractCellPopulation< SPACE_DIM > * pCellPopulation) [inline]
Constructor.
Parameters:
pCellPopulation pointer to the cell population.
Definition at line 40 of file ApoptoticCellKiller.cpp.
Member Function Documentation
template<unsigned SPACE_DIM> void ApoptoticCellKiller< SPACE_DIM >::CheckAndLabelCellsForApoptosisOrDeath () [inline, virtual]
Loop over cells and call CheckAndLabelSingleCellForApoptosis() on each cell.
Implements AbstractCellKiller< SPACE_DIM >.
Definition at line 55 of file ApoptoticCellKiller.cpp.
References AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::Begin(), ApoptoticCellKiller< SPACE_DIM >::CheckAndLabelSingleCellForApoptosis(), AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::End(), and AbstractCellKiller< SPACE_DIM >::mpCellPopulation.
template<unsigned SPACE_DIM> void ApoptoticCellKiller< SPACE_DIM >::CheckAndLabelSingleCellForApoptosis (CellPtr pCell) [inline]
Starts apoptosis if the cell has been given the ApoptoticCellProperty.
Parameters:
pCell the cell to test for apoptosis.
Definition at line 46 of file ApoptoticCellKiller.cpp.
Referenced by ApoptoticCellKiller< SPACE_DIM >::CheckAndLabelCellsForApoptosisOrDeath().
template<unsigned DIM> void ApoptoticCellKiller< DIM >::OutputCellKillerParameters (out_stream & rParamsFile) [inline, virtual]
Overridden OutputCellKillerParameters() method.
Parameters:
rParamsFile the file stream to which the parameters are output
Implements AbstractCellKiller< SPACE_DIM >.
Definition at line 66 of file ApoptoticCellKiller.cpp.
template<unsigned SPACE_DIM> template<class Archive > void ApoptoticCellKiller< SPACE_DIM >::serialize (Archive & archive, const unsigned int version) [inline, private]
Boost Serialization method for archiving/checkpointing. Archives the object and its member variables.
Parameters:
archive The boost archive.
version The current version of this class.
Reimplemented from AbstractCellKiller< SPACE_DIM >.
Definition at line 61 of file ApoptoticCellKiller.hpp.
Friends And Related Function Documentation
template<unsigned SPACE_DIM> friend class boost::serialization::access [friend]
Needed for serialization.
Reimplemented from AbstractCellKiller< SPACE_DIM >.
Definition at line 52 of file ApoptoticCellKiller.hpp.
The documentation for this class was generated from the following files:
cell_based/src/population/killers/ApoptoticCellKiller.hpp
cell_based/src/population/killers/ApoptoticCellKiller.cpp