Chaste: VtkMeshWriter< ELEMENT_DIM, SPACE_DIM > Class Template Reference
VtkMeshWriter< ELEMENT_DIM, SPACE_DIM > Class Template Reference
#include <VtkMeshWriter.hpp>
Inherits AbstractTetrahedralMeshWriter< ELEMENT_DIM, SPACE_DIM >.
Public Member Functions
VtkMeshWriter (const std::string &rDirectory, const std::string &rBaseName, const bool &rCleanDirectory=true)
void WriteFiles ()
void AddCellData (std::string name, std::vector< double > data)
void AddCellData (std::string name, std::vector< c_vector< double, SPACE_DIM > > data)
void AddTensorCellData (std::string name, std::vector< c_vector< double, SPACE_DIM *(SPACE_DIM+1)/2 > > data)
void AddTensorCellData (std::string name, std::vector< c_matrix< double, SPACE_DIM, SPACE_DIM > > data)
void AddPointData (std::string name, std::vector< double > data)
void AddPointData (std::string name, std::vector< c_vector< double, SPACE_DIM > > data)
void AddTensorPointData (std::string name, std::vector< c_matrix< double, SPACE_DIM, SPACE_DIM > > data)
void SetParallelFiles (AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM > &rMesh)
void WriteFilesUsingMesh (AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM > &rMesh, bool keepOriginalElementIndexing=true)
void AddProvenance (std::string fileName)
virtual ~VtkMeshWriter ()
Private Member Functions
void MakeVtkMesh ()
void AugmentCellData ()
Private Attributes
bool mWriteParallelFiles
std::map< unsigned, unsigned > mGlobalToNodeIndexMap
std::vector< std::vector
< unsigned > > mNodesToSendPerProcess
std::vector< std::vector
< unsigned > > mNodesToReceivePerProcess
NodesOnlyMesh< SPACE_DIM > * mpNodesOnlyMesh
vtkUnstructuredGrid * mpVtkUnstructedMesh
Detailed Description
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM>
class VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >
VtkMeshWriter
Writes a mesh in VTK .vtu format (that's an XML-based, data compressed unstructured mesh)
Definition at line 71 of file VtkMeshWriter.hpp.
Constructor & Destructor Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::VtkMeshWriter (const std::string & rDirectory, const std::string & rBaseName, const bool & rCleanDirectory = true) [inline]
Constructor.
Parameters:
rDirectory the directory in which to write the mesh to file
rBaseName the base name of the files in which to write the mesh data
rCleanDirectory whether to clean the directory (defaults to true)
Definition at line 51 of file VtkMeshWriter.cpp.
References AbstractTetrahedralMeshWriter< ELEMENT_DIM, SPACE_DIM >::mIndexFromZero, and VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::mpVtkUnstructedMesh.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::~VtkMeshWriter () [inline, virtual]
Destructor.
Definition at line 64 of file VtkMeshWriter.cpp.
References VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::mpVtkUnstructedMesh.
Member Function Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::AddCellData (std::string name, std::vector< c_vector< double, SPACE_DIM > > data) [inline]
Add a vector data field to each element (known as "cell" in VTK).
Parameters:
name is a meaningful name with which to annotate the data
data is the data which should appear in the same order as the element numbering The length of the data vector is assumed to match the number of elements in the mesh. Checking cannot be done at this stage since the data is associated with an empty VTK mesh structure.
Definition at line 260 of file VtkMeshWriter.cpp.
References VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::mpVtkUnstructedMesh.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::AddCellData (std::string name, std::vector< double > data) [inline]
Add a scalar data field to each element (known as "cell" in VTK).
Parameters:
name is a meaningful name with which to annotate the data
data is the data which should appear in the same order as the element numbering The length of the data vector is assumed to match the number of elements in the mesh. Checking cannot be done at this stage since the data is associated with an empty VTK mesh structure.
Definition at line 212 of file VtkMeshWriter.cpp.
References VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::mpVtkUnstructedMesh.
Referenced by VentilationProblem::AddDataToVtk(), AbstractContinuumMechanicsSolver< DIM >::CreateVtkOutput(), VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::MakeVtkMesh(), VtkNonlinearElasticitySolutionWriter< DIM >::Write(), and VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::WriteFilesUsingMesh().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::AddPointData (std::string name, std::vector< c_vector< double, SPACE_DIM > > data) [inline]
Add a vector data field to each node (known as "point" in VTK).
Parameters:
name is a meaningful name with which to annotate the data
data is the data which should appear in the same order as the node numbering The length of the data vector is assumed to match the number of nodes in the mesh Checking cannot be done at this stage since the data is associated with an empty VTK mesh structure.
Definition at line 431 of file VtkMeshWriter.cpp.
References PetscTools::GetMyRank(), PetscTools::GetNumProcs(), VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::mGlobalToNodeIndexMap, VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::mNodesToReceivePerProcess, VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::mNodesToSendPerProcess, AbstractTetrahedralMeshWriter< ELEMENT_DIM, SPACE_DIM >::mpDistributedMesh, VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::mpVtkUnstructedMesh, VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::mWriteParallelFiles, and UNUSED_OPT.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::AddPointData (std::string name, std::vector< double > data) [inline]
Add a scalar data field to each node (known as "point" in VTK).
Parameters:
name is a meaningful name with which to annotate the data
data is the data which should appear in the same order as the node numbering The length of the data vector is assumed to match the number of nodes in the mesh Checking cannot be done at this stage since the data is associated with an empty VTK mesh structure.
Definition at line 357 of file VtkMeshWriter.cpp.
References PetscTools::GetMyRank(), PetscTools::GetNumProcs(), VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::mGlobalToNodeIndexMap, VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::mNodesToReceivePerProcess, VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::mNodesToSendPerProcess, AbstractTetrahedralMeshWriter< ELEMENT_DIM, SPACE_DIM >::mpDistributedMesh, VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::mpVtkUnstructedMesh, VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::mWriteParallelFiles, and UNUSED_OPT.
Referenced by VentilationProblem::AddDataToVtk(), AbstractContinuumMechanicsSolver< DIM >::CreateVtkOutput(), Hdf5ToVtkConverter< ELEMENT_DIM, SPACE_DIM >::Hdf5ToVtkConverter(), VtkNonlinearElasticitySolutionWriter< DIM >::Write(), CellBasedPdeHandler< DIM >::WritePdeSolution(), and LinearParabolicPdeSystemWithCoupledOdeSystemSolver< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::WriteVtkResultsToFile().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::AddProvenance (std::string fileName) [inline]
Add Chaste provenance data to a VTK file as an XML comment string
Parameters:
fileName is the file name relative to mpOutputFileHandler The file is assumed have been written to and to be closed - so that it can safely be appended to.
Definition at line 173 of file VtkMeshWriter.cpp.
References ChasteBuildInfo::GetProvenanceString(), AbstractMeshWriter< ELEMENT_DIM, SPACE_DIM >::mpOutputFileHandler, and OutputFileHandler::OpenOutputFile().
Referenced by VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::WriteFiles(), and VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::WriteFilesUsingMesh().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::AddTensorCellData (std::string name, std::vector< c_matrix< double, SPACE_DIM, SPACE_DIM > > data) [inline]
Add a tensor data field to each element (known as "cell" in VTK).
Parameters:
name is a meaningful name with which to annotate the data
data is the data which should appear in the same order as the element numbering The length of the data vector is assumed to match the number of elements in the mesh. Checking cannot be done at this stage since the data is associated with an empty VTK mesh structure.
Definition at line 320 of file VtkMeshWriter.cpp.
References VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::mpVtkUnstructedMesh.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::AddTensorCellData (std::string name, std::vector< c_vector< double, SPACE_DIM *(SPACE_DIM+1)/2 > > data) [inline]
Add a symmetric tensor data field to each element (known as "cell" in VTK).
Parameters:
name is a meaningful name with which to annotate the data
data is the data which should appear in the same order as the element numbering The length of the data vector is assumed to match the number of elements in the mesh. The data vector represents the lower half of the tensor Checking cannot be done at this stage since the data is associated with an empty VTK mesh structure.
Definition at line 284 of file VtkMeshWriter.cpp.
References VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::mpVtkUnstructedMesh.
Referenced by VtkNonlinearElasticitySolutionWriter< DIM >::Write().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::AddTensorPointData (std::string name, std::vector< c_matrix< double, SPACE_DIM, SPACE_DIM > > data) [inline]
Add a tensor data field to each point.
Parameters:
name is a meaningful name with which to annotate the data
data is the data which should appear in the same order as the node numbering The length of the data vector is assumed to match the number of nodes in the mesh Checking cannot be done at this stage since the data is associated with an empty VTK mesh structure.
Definition at line 515 of file VtkMeshWriter.cpp.
References VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::mpVtkUnstructedMesh.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::AugmentCellData () [inline, private]
At the time of adding VTK cell data, it is assumed that there is one piece of data for each element in the original mesh. If the mesh is mixed-dimension (elements and cable elements) the VTK mesh makes no distinction between the two types of cells. All data associated with cells must be the same length as the overall number of cells. This method inspects each cell data component and adds dummy data to cover the cable elements.
Definition at line 227 of file VtkMeshWriter.cpp.
References AbstractMeshWriter< ELEMENT_DIM, SPACE_DIM >::GetNumCableElements(), AbstractMeshWriter< ELEMENT_DIM, SPACE_DIM >::GetNumElements(), AbstractTetrahedralMeshWriter< ELEMENT_DIM, SPACE_DIM >::mpDistributedMesh, AbstractTetrahedralMeshWriter< ELEMENT_DIM, SPACE_DIM >::mpMixedMesh, VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::mpVtkUnstructedMesh, and VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::mWriteParallelFiles.
Referenced by VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::MakeVtkMesh(), and VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::WriteFilesUsingMesh().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::MakeVtkMesh () [inline, private]
Private helper method which copies the mesh details into the waiting VTK mesh structure. Called by WriteFiles().
Todo:
#2351 Temporary workaround for parallel writer
Definition at line 70 of file VtkMeshWriter.cpp.
References VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::AddCellData(), ElementData::AttributeValue, VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::AugmentCellData(), AbstractTetrahedralMeshWriter< ELEMENT_DIM, SPACE_DIM >::GetNextBoundaryElement(), AbstractTetrahedralMeshWriter< ELEMENT_DIM, SPACE_DIM >::GetNextCableElement(), AbstractTetrahedralMeshWriter< ELEMENT_DIM, SPACE_DIM >::GetNextElement(), AbstractTetrahedralMeshWriter< ELEMENT_DIM, SPACE_DIM >::GetNextNode(), AbstractMeshWriter< ELEMENT_DIM, SPACE_DIM >::GetNumBoundaryFaces(), AbstractMeshWriter< ELEMENT_DIM, SPACE_DIM >::GetNumCableElements(), AbstractMeshWriter< ELEMENT_DIM, SPACE_DIM >::GetNumElements(), AbstractMeshWriter< ELEMENT_DIM, SPACE_DIM >::GetNumNodes(), VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::mpVtkUnstructedMesh, and ElementData::NodeIndices.
Referenced by VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::WriteFiles().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::SetParallelFiles (AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM > & rMesh) [inline]
Should be called to enable files to be written in parallel (i.e. a .pvtu file and .vtu files for each process's sub-mesh).
Parameters:
rMesh the mesh (must be a DistributedTetrahedralMesh)
Definition at line 551 of file VtkMeshWriter.cpp.
References EXCEPTION, AbstractMesh< ELEMENT_DIM, SPACE_DIM >::GetNodeIteratorBegin(), AbstractMesh< ELEMENT_DIM, SPACE_DIM >::GetNodeIteratorEnd(), PetscTools::IsSequential(), VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::mGlobalToNodeIndexMap, VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::mNodesToReceivePerProcess, VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::mNodesToSendPerProcess, AbstractTetrahedralMeshWriter< ELEMENT_DIM, SPACE_DIM >::mpDistributedMesh, VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::mpNodesOnlyMesh, and VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::mWriteParallelFiles.
Referenced by Hdf5ToVtkConverter< ELEMENT_DIM, SPACE_DIM >::Hdf5ToVtkConverter().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::WriteFiles () [inline, virtual]
Write mesh data to files.
Implements AbstractMeshWriter< ELEMENT_DIM, SPACE_DIM >.
Definition at line 184 of file VtkMeshWriter.cpp.
References VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::AddProvenance(), OutputFileHandler::GetOutputDirectoryFullPath(), VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::MakeVtkMesh(), AbstractMeshWriter< ELEMENT_DIM, SPACE_DIM >::mBaseName, AbstractMeshWriter< ELEMENT_DIM, SPACE_DIM >::mpOutputFileHandler, and VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::mpVtkUnstructedMesh.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::WriteFilesUsingMesh (AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM > & rMesh, bool keepOriginalElementIndexing = true) [inline, virtual]
Write files. Overrides the method implemented in AbstractTetrahedralMeshWriter, which concentrates mesh data onto a single file in order to output a monolithic file. For VTK, a DistributedTetrahedralMesh in parallel is instead written out as a set of .vtu files (one for each sub-mesh) and a .pvtu file that provides the visualizer with information about them.
Parameters:
rMesh the mesh
keepOriginalElementIndexing Whether to write the mesh with the same element ordering. Optimisations can be applied if this is not needed.
Todo:
#1322 Mesh should really be const!
Todo:
#1322 Mesh should be const
Todo:
This ought to look exactly like the other MakeVtkMesh
Add to the main file
Todo:
#1494 Do we need a barrier?
Reimplemented from AbstractTetrahedralMeshWriter< ELEMENT_DIM, SPACE_DIM >.
Definition at line 601 of file VtkMeshWriter.cpp.
References VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::AddCellData(), VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::AddProvenance(), PetscTools::AmMaster(), VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::AugmentCellData(), AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::GetElementIteratorBegin(), AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::GetElementIteratorEnd(), PetscTools::GetMyRank(), AbstractMesh< ELEMENT_DIM, SPACE_DIM >::GetNodeIteratorBegin(), AbstractMesh< ELEMENT_DIM, SPACE_DIM >::GetNodeIteratorEnd(), DistributedTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::GetNumLocalElements(), PetscTools::GetNumProcs(), OutputFileHandler::GetOutputDirectoryFullPath(), PetscTools::IsSequential(), AbstractMeshWriter< ELEMENT_DIM, SPACE_DIM >::mBaseName, VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::mGlobalToNodeIndexMap, AbstractTetrahedralMeshWriter< ELEMENT_DIM, SPACE_DIM >::mpDistributedMesh, AbstractTetrahedralMeshWriter< ELEMENT_DIM, SPACE_DIM >::mpMixedMesh, VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::mpNodesOnlyMesh, AbstractMeshWriter< ELEMENT_DIM, SPACE_DIM >::mpOutputFileHandler, VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::mpVtkUnstructedMesh, and VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::mWriteParallelFiles.
Referenced by AbstractContinuumMechanicsSolver< DIM >::CreateVtkOutput(), Hdf5ToVtkConverter< ELEMENT_DIM, SPACE_DIM >::Hdf5ToVtkConverter(), VentilationProblem::Solve(), VtkNonlinearElasticitySolutionWriter< DIM >::Write(), CellBasedPdeHandler< DIM >::WritePdeSolution(), and VentilationProblem::WriteVtk().
Member Data Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> std::map<unsigned, unsigned> VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::mGlobalToNodeIndexMap [private]
Map a global node index into a local index (into mNodes and mHaloNodes as if they were concatenated)
Definition at line 79 of file VtkMeshWriter.hpp.
Referenced by VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::AddPointData(), VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::SetParallelFiles(), and VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::WriteFilesUsingMesh().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> std::vector<std::vector<unsigned> > VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::mNodesToReceivePerProcess [private]
Used to communicate node-wise halo data
Definition at line 82 of file VtkMeshWriter.hpp.
Referenced by VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::AddPointData(), and VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::SetParallelFiles().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> std::vector<std::vector<unsigned> > VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::mNodesToSendPerProcess [private]
Used to communicate node-wise halo data
Definition at line 81 of file VtkMeshWriter.hpp.
Referenced by VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::AddPointData(), and VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::SetParallelFiles().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> NodesOnlyMesh<SPACE_DIM>* VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::mpNodesOnlyMesh [private]
A pointer to a NodesOnlyMesh to write to file, created by dynamic cast
Definition at line 85 of file VtkMeshWriter.hpp.
Referenced by VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::SetParallelFiles(), and VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::WriteFilesUsingMesh().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> vtkUnstructuredGrid* VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::mpVtkUnstructedMesh [private]
A VTK mesh data structure. Created at construction, has data associated with it by AddCellData and AddCellPoint, then is filled with mesh geometry by MakeVtkMesh() in WriteFiles().
Definition at line 93 of file VtkMeshWriter.hpp.
Referenced by VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::AddCellData(), VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::AddPointData(), VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::AddTensorCellData(), VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::AddTensorPointData(), VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::AugmentCellData(), VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::MakeVtkMesh(), VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::VtkMeshWriter(), VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::WriteFiles(), VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::WriteFilesUsingMesh(), and VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::~VtkMeshWriter().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> bool VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::mWriteParallelFiles [private]
Whether to write parallel (.pvtu + .vtu for each process) files, defaults to false
Definition at line 77 of file VtkMeshWriter.hpp.
Referenced by VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::AddPointData(), VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::AugmentCellData(), VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::SetParallelFiles(), and VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::WriteFilesUsingMesh().
The documentation for this class was generated from the following files:
mesh/src/writer/VtkMeshWriter.hpp
mesh/src/writer/VtkMeshWriter.cpp