Chaste: CellwiseSourcePde< DIM > Class Template Reference
CellwiseSourcePde< DIM > Class Template Reference
#include <CellwiseSourcePde.hpp>
Inherits AbstractLinearEllipticPde< DIM, DIM >.
Public Member Functions
CellwiseSourcePde (AbstractCellPopulation< DIM, DIM > &rCellPopulation, double coefficient=0.0)
const AbstractCellPopulation
< DIM > & rGetCellPopulation () const
double GetCoefficient () const
virtual double ComputeConstantInUSourceTerm (const ChastePoint< DIM > &rX, Element< DIM, DIM > *pElement)
virtual double ComputeLinearInUCoeffInSourceTerm (const ChastePoint< DIM > &rX, Element< DIM, DIM > *pElement)
virtual double ComputeLinearInUCoeffInSourceTermAtNode (const Node< DIM > &rNode)
virtual c_matrix< double, DIM,
DIM > ComputeDiffusionTerm (const ChastePoint< DIM > &rX)
Protected Attributes
AbstractCellPopulation< DIM,
DIM > & mrCellPopulation
double mCoefficient
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Friends
class TestCellBasedPdes
class boost::serialization::access
Detailed Description
template<unsigned DIM>
class CellwiseSourcePde< DIM >
A PDE which has a source at each non-apoptotic cell.
Definition at line 49 of file CellwiseSourcePde.hpp.
Constructor & Destructor Documentation
template<unsigned DIM> CellwiseSourcePde< DIM >::CellwiseSourcePde (AbstractCellPopulation< DIM, DIM > & rCellPopulation, double coefficient = 0.0) [inline]
Constructor.
Parameters:
rCellPopulation reference to the cell population
coefficient the coefficient of consumption of nutrient by cells (defaults to 0.0)
Definition at line 41 of file CellwiseSourcePde.cpp.
Member Function Documentation
template<unsigned DIM> double CellwiseSourcePde< DIM >::ComputeConstantInUSourceTerm (const ChastePoint< DIM > & rX, Element< DIM, DIM > * pElement) [inline, virtual]
Overridden ComputeConstantInUSourceTerm() method.
Parameters:
rX The point in space
pElement The element
Returns:
the constant in u part of the source term, i.e g(x) in Div(D Grad u) + f(x)u + g(x) = 0.
Definition at line 60 of file CellwiseSourcePde.cpp.
template<unsigned DIM> c_matrix< double, DIM, DIM > CellwiseSourcePde< DIM >::ComputeDiffusionTerm (const ChastePoint< DIM > & rX) [inline, virtual]
Overridden ComputeDiffusionTerm() method.
Parameters:
rX The point in space at which the diffusion term is computed
Returns:
a matrix.
Definition at line 93 of file CellwiseSourcePde.cpp.
template<unsigned DIM> double CellwiseSourcePde< DIM >::ComputeLinearInUCoeffInSourceTerm (const ChastePoint< DIM > & rX, Element< DIM, DIM > * pElement) [inline, virtual]
Overridden ComputeLinearInUCoeffInSourceTerm() method.
Parameters:
rX The point in space
pElement the element
Returns:
the coefficient of u in the linear part of the source term, i.e f(x) in Div(D Grad u) + f(x)u + g(x) = 0.
Definition at line 66 of file CellwiseSourcePde.cpp.
References NEVER_REACHED.
template<unsigned DIM> double CellwiseSourcePde< DIM >::ComputeLinearInUCoeffInSourceTermAtNode (const Node< DIM > & rNode) [inline, virtual]
Overridden ComputeLinearInUCoeffInSourceTermAtNode() method.
Parameters:
rNode reference to the node
Returns:
the coefficient of u in the linear part of the source term, i.e f(x) in Div(D Grad u) + f(x)u + g(x) = 0.
Definition at line 73 of file CellwiseSourcePde.cpp.
References AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::GetCellUsingLocationIndex(), Node< SPACE_DIM >::GetIndex(), AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::IsCellAttachedToLocationIndex(), CellwiseSourcePde< DIM >::mCoefficient, and CellwiseSourcePde< DIM >::mrCellPopulation.
template<unsigned DIM> double CellwiseSourcePde< DIM >::GetCoefficient () const [inline]
Returns:
mCoefficient (used in archiving).
Definition at line 54 of file CellwiseSourcePde.cpp.
References CellwiseSourcePde< DIM >::mCoefficient.
template<unsigned DIM> const AbstractCellPopulation< DIM, DIM > & CellwiseSourcePde< DIM >::rGetCellPopulation () const [inline]
Returns:
const reference to the cell population (used in archiving).
Definition at line 48 of file CellwiseSourcePde.cpp.
References CellwiseSourcePde< DIM >::mrCellPopulation.
template<unsigned DIM> template<class Archive > void CellwiseSourcePde< DIM >::serialize (Archive & archive, const unsigned int version) [inline, private]
Serialize the PDE and its member variables.
Parameters:
archive the archive
version the current version of this class
Reimplemented from AbstractLinearEllipticPde< DIM, DIM >.
Definition at line 64 of file CellwiseSourcePde.hpp.
References CellwiseSourcePde< DIM >::mCoefficient.
Friends And Related Function Documentation
template<unsigned DIM> friend class boost::serialization::access [friend]
Needed for serialization.
Reimplemented from AbstractLinearEllipticPde< DIM, DIM >.
Definition at line 56 of file CellwiseSourcePde.hpp.
Member Data Documentation
template<unsigned DIM> double CellwiseSourcePde< DIM >::mCoefficient [protected]
Coefficient of consumption of nutrient by cells.
Definition at line 76 of file CellwiseSourcePde.hpp.
Referenced by CellwiseSourcePde< DIM >::ComputeLinearInUCoeffInSourceTermAtNode(), CellwiseSourcePde< DIM >::GetCoefficient(), and CellwiseSourcePde< DIM >::serialize().
template<unsigned DIM> AbstractCellPopulation<DIM, DIM>& CellwiseSourcePde< DIM >::mrCellPopulation [protected]
The cell population member.
Definition at line 73 of file CellwiseSourcePde.hpp.
Referenced by CellwiseSourcePde< DIM >::ComputeLinearInUCoeffInSourceTermAtNode(), and CellwiseSourcePde< DIM >::rGetCellPopulation().
The documentation for this class was generated from the following files:
cell_based/src/population/pdes/CellwiseSourcePde.hpp
cell_based/src/population/pdes/CellwiseSourcePde.cpp