Chaste: GammaDistributedStochasticDurationCellCycleModel Class Reference
GammaDistributedStochasticDurationCellCycleModel Class Reference
#include <GammaDistributedStochasticDurationCellCycleModel.hpp>
Inherits AbstractSimpleCellCycleModel.
Public Member Functions
GammaDistributedStochasticDurationCellCycleModel ()
void SetG1Duration ()
AbstractCellCycleModel * CreateCellCycleModel ()
void SetShape (double shape)
void SetScale (double scale)
double GetShape ()
double GetScale ()
virtual void OutputCellCycleModelParameters (out_stream &rParamsFile)
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Private Attributes
double mShape
double mScale
Friends
class TestSimpleCellCycleModels
class boost::serialization::access
Detailed Description
A stochastic cell-cycle model where cells keep dividing with a stochastic G1 duration drawn from a gamma distribution with specified shape and scale parameters.
Definition at line 46 of file GammaDistributedStochasticDurationCellCycleModel.hpp.
Constructor & Destructor Documentation
GammaDistributedStochasticDurationCellCycleModel::GammaDistributedStochasticDurationCellCycleModel ()
Constructor.
Definition at line 42 of file GammaDistributedStochasticDurationCellCycleModel.cpp.
Referenced by CreateCellCycleModel().
Member Function Documentation
AbstractCellCycleModel * GammaDistributedStochasticDurationCellCycleModel::CreateCellCycleModel () [virtual]
Overridden builder method to create new copies of this cell-cycle model.
Returns:
a pointer to the GammaDistributedStochasticDurationCellCycleModel created.
Implements AbstractCellCycleModel.
Definition at line 49 of file GammaDistributedStochasticDurationCellCycleModel.cpp.
References GammaDistributedStochasticDurationCellCycleModel(), AbstractCellCycleModel::mBirthTime, AbstractCellCycleModel::mG2Duration, AbstractCellCycleModel::mMDuration, AbstractCellCycleModel::mMinimumGapDuration, mScale, AbstractCellCycleModel::mSDuration, mShape, AbstractCellCycleModel::mStemCellG1Duration, AbstractCellCycleModel::mTransitCellG1Duration, AbstractCellCycleModel::SetBirthTime(), AbstractCellCycleModel::SetG2Duration(), AbstractCellCycleModel::SetMDuration(), AbstractCellCycleModel::SetMinimumGapDuration(), SetScale(), AbstractCellCycleModel::SetSDuration(), SetShape(), AbstractCellCycleModel::SetStemCellG1Duration(), and AbstractCellCycleModel::SetTransitCellG1Duration().
double GammaDistributedStochasticDurationCellCycleModel::GetScale ()
Returns:
mScale.
Definition at line 117 of file GammaDistributedStochasticDurationCellCycleModel.cpp.
References mScale.
double GammaDistributedStochasticDurationCellCycleModel::GetShape ()
Returns:
mShape.
Definition at line 112 of file GammaDistributedStochasticDurationCellCycleModel.cpp.
References mShape.
void GammaDistributedStochasticDurationCellCycleModel::OutputCellCycleModelParameters (out_stream & rParamsFile) [virtual]
Overridden OutputCellCycleModelParameters() method.
Parameters:
rParamsFile the file stream to which the parameters are output
Reimplemented from AbstractSimpleCellCycleModel.
Definition at line 122 of file GammaDistributedStochasticDurationCellCycleModel.cpp.
References mScale, and mShape.
template<class Archive > void GammaDistributedStochasticDurationCellCycleModel::serialize (Archive & archive, const unsigned int version) [inline, private]
Archive the cell-cycle model and random number generator, never used directly - boost uses this.
Parameters:
archive the archive
version the current version of this class
Reimplemented from AbstractSimpleCellCycleModel.
Definition at line 67 of file GammaDistributedStochasticDurationCellCycleModel.hpp.
References SerializableSingleton< SINGLETON_CLASS >::GetSerializationWrapper(), RandomNumberGenerator::Instance(), mScale, and mShape.
void GammaDistributedStochasticDurationCellCycleModel::SetG1Duration () [virtual]
Overridden SetG1Duration().
Reimplemented from AbstractSimpleCellCycleModel.
Definition at line 84 of file GammaDistributedStochasticDurationCellCycleModel.cpp.
References RandomNumberGenerator::GammaRandomDeviate(), RandomNumberGenerator::Instance(), AbstractCellCycleModel::mG1Duration, AbstractCellCycleModel::mpCell, mScale, mShape, and NEVER_REACHED.
void GammaDistributedStochasticDurationCellCycleModel::SetScale (double scale)
Returns:
mScale.
Parameters:
scale the value of the scale parameter
Definition at line 107 of file GammaDistributedStochasticDurationCellCycleModel.cpp.
References mScale.
Referenced by CreateCellCycleModel().
void GammaDistributedStochasticDurationCellCycleModel::SetShape (double shape)
Set mShape.
Parameters:
shape the value of the shape parameter
Definition at line 102 of file GammaDistributedStochasticDurationCellCycleModel.cpp.
References mShape.
Referenced by CreateCellCycleModel().
Friends And Related Function Documentation
friend class boost::serialization::access [friend]
Needed for serialization.
Reimplemented from AbstractSimpleCellCycleModel.
Definition at line 59 of file GammaDistributedStochasticDurationCellCycleModel.hpp.
Member Data Documentation
double GammaDistributedStochasticDurationCellCycleModel::mScale [private]
The scale parameter of the gamma distribution. This must be a positive real number.
Definition at line 56 of file GammaDistributedStochasticDurationCellCycleModel.hpp.
Referenced by CreateCellCycleModel(), GetScale(), OutputCellCycleModelParameters(), serialize(), SetG1Duration(), and SetScale().
double GammaDistributedStochasticDurationCellCycleModel::mShape [private]
The shape parameter of the gamma distribution. This must be a positive real number.
Definition at line 53 of file GammaDistributedStochasticDurationCellCycleModel.hpp.
Referenced by CreateCellCycleModel(), GetShape(), OutputCellCycleModelParameters(), serialize(), SetG1Duration(), and SetShape().
The documentation for this class was generated from the following files:
cell_based/src/population/cell/cycle/GammaDistributedStochasticDurationCellCycleModel.hpp
cell_based/src/population/cell/cycle/GammaDistributedStochasticDurationCellCycleModel.cpp