Chaste: DiffusionForce< DIM > Class Template Reference
DiffusionForce< DIM > Class Template Reference
#include <DiffusionForce.hpp>
Inherits AbstractForce< DIM >.
Public Member Functions
DiffusionForce ()
~DiffusionForce ()
void SetDiffusionConstant (double diffusionConstant)
void SetAbsoluteTemperature (double absoluteTemperature)
void SetViscosity (double viscosity)
void SetCutOffLength (double cutOffLength)
double GetDiffusionConstant ()
double GetAbsoluteTemperature ()
double GetViscosity ()
double GetDiffusionScalingConstant ()
double GetCutOffLength ()
void AddForceContribution (AbstractCellPopulation< DIM > &rCellPopulation)
void OutputForceParameters (out_stream &rParamsFile)
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Private Attributes
double mDiffusionConstant
double mAbsoluteTemperature
double mViscosity
double mMechanicsCutOffLength
Static Private Attributes
static const double msBoltzmannConstant = 1.3806488e-23
Friends
class boost::serialization::access
Detailed Description
template<unsigned DIM>
class DiffusionForce< DIM >
A force class to model diffusion.
Definition at line 50 of file DiffusionForce.hpp.
Constructor & Destructor Documentation
template<unsigned DIM> DiffusionForce< DIM >::DiffusionForce () [inline]
Constructor.
Definition at line 44 of file DiffusionForce.cpp.
template<unsigned DIM> DiffusionForce< DIM >::~DiffusionForce () [inline]
Destructor.
Definition at line 54 of file DiffusionForce.cpp.
Member Function Documentation
template<unsigned DIM> void DiffusionForce< DIM >::AddForceContribution (AbstractCellPopulation< DIM > & rCellPopulation) [inline]
Overridden AddForceContribution() method.
Parameters:
rCellPopulation reference to the tissue
Definition at line 117 of file DiffusionForce.cpp.
References Node< SPACE_DIM >::AddAppliedForceContribution(), AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::Begin(), AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::End(), DiffusionForce< DIM >::GetDiffusionScalingConstant(), AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::GetLocationIndexUsingCell(), AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::GetNode(), Node< SPACE_DIM >::GetRadius(), SimulationTime::GetTimeStep(), RandomNumberGenerator::Instance(), SimulationTime::Instance(), and RandomNumberGenerator::StandardNormalRandomDeviate().
template<unsigned DIM> double DiffusionForce< DIM >::GetAbsoluteTemperature () [inline]
Get the absolute temperature.
Returns:
mAbsoluteTemperature
Definition at line 92 of file DiffusionForce.cpp.
References DiffusionForce< DIM >::mAbsoluteTemperature.
template<unsigned DIM> double DiffusionForce< DIM >::GetCutOffLength () [inline]
Get the cutoff length.
Returns:
mCutOffLenght
Definition at line 66 of file DiffusionForce.cpp.
References DiffusionForce< DIM >::mMechanicsCutOffLength.
template<unsigned DIM> double DiffusionForce< DIM >::GetDiffusionConstant () [inline]
Get the diffusion coefficient.
Returns:
mDiffusionConstant
Definition at line 79 of file DiffusionForce.cpp.
References DiffusionForce< DIM >::mDiffusionConstant.
template<unsigned DIM> double DiffusionForce< DIM >::GetDiffusionScalingConstant () [inline]
Calculate the scaling of the diffusion constant
Returns:
the scaled diffusion constant.
Definition at line 111 of file DiffusionForce.cpp.
References DiffusionForce< DIM >::mAbsoluteTemperature, DiffusionForce< DIM >::msBoltzmannConstant, and DiffusionForce< DIM >::mViscosity.
Referenced by DiffusionForce< DIM >::AddForceContribution().
template<unsigned DIM> double DiffusionForce< DIM >::GetViscosity () [inline]
Get the viscosity.
Returns:
mViscosity
Definition at line 105 of file DiffusionForce.cpp.
References DiffusionForce< DIM >::mViscosity.
template<unsigned DIM> void DiffusionForce< DIM >::OutputForceParameters (out_stream & rParamsFile) [inline, virtual]
Overridden OutputForceParameters() method.
Parameters:
rParamsFile the file stream to which the parameters are output
Implements AbstractForce< DIM >.
Definition at line 165 of file DiffusionForce.cpp.
References DiffusionForce< DIM >::mDiffusionConstant, and DiffusionForce< DIM >::mMechanicsCutOffLength.
template<unsigned DIM> template<class Archive > void DiffusionForce< DIM >::serialize (Archive & archive, const unsigned int version) [inline, private]
Boost Serialization method for archiving/checkpointing. Archives the object and its member variables.
Parameters:
archive The boost archive.
version The current version of this class.
Reimplemented from AbstractForce< DIM >.
Definition at line 93 of file DiffusionForce.hpp.
References DiffusionForce< DIM >::mAbsoluteTemperature, DiffusionForce< DIM >::mDiffusionConstant, DiffusionForce< DIM >::mMechanicsCutOffLength, and DiffusionForce< DIM >::mViscosity.
template<unsigned DIM> void DiffusionForce< DIM >::SetAbsoluteTemperature (double absoluteTemperature) [inline]
Set the absolute temperature, which affects the diffusion constant.
Parameters:
absoluteTemperature the temperature in Kelvin
Definition at line 85 of file DiffusionForce.cpp.
References DiffusionForce< DIM >::mAbsoluteTemperature.
template<unsigned DIM> void DiffusionForce< DIM >::SetCutOffLength (double cutOffLength) [inline]
Use a cutoff point, i.e. specify zero force if two cells are greater than the cutoff distance apart.
Parameters:
cutOffLength the cutoff to use
Definition at line 59 of file DiffusionForce.cpp.
References DiffusionForce< DIM >::mMechanicsCutOffLength.
template<unsigned DIM> void DiffusionForce< DIM >::SetDiffusionConstant (double diffusionConstant) [inline]
Set the diffusion constant for the cells.
Parameters:
diffusionConstant the diffusion constant to use
Definition at line 72 of file DiffusionForce.cpp.
References DiffusionForce< DIM >::mDiffusionConstant.
template<unsigned DIM> void DiffusionForce< DIM >::SetViscosity (double viscosity) [inline]
Set the media viscosity (dynamic), which affects the diffusion constant.
Parameters:
viscosity the viscosity
Definition at line 98 of file DiffusionForce.cpp.
References DiffusionForce< DIM >::mViscosity.
Friends And Related Function Documentation
template<unsigned DIM> friend class boost::serialization::access [friend]
Archiving.
Reimplemented from AbstractForce< DIM >.
Definition at line 84 of file DiffusionForce.hpp.
Member Data Documentation
template<unsigned DIM> double DiffusionForce< DIM >::mAbsoluteTemperature [private]
Absolute temperature (in Kelvin).
Definition at line 62 of file DiffusionForce.hpp.
Referenced by DiffusionForce< DIM >::GetAbsoluteTemperature(), DiffusionForce< DIM >::GetDiffusionScalingConstant(), DiffusionForce< DIM >::serialize(), and DiffusionForce< DIM >::SetAbsoluteTemperature().
template<unsigned DIM> double DiffusionForce< DIM >::mDiffusionConstant [private]
Diffusion constant.
Definition at line 57 of file DiffusionForce.hpp.
Referenced by DiffusionForce< DIM >::GetDiffusionConstant(), DiffusionForce< DIM >::OutputForceParameters(), DiffusionForce< DIM >::serialize(), and DiffusionForce< DIM >::SetDiffusionConstant().
template<unsigned DIM> double DiffusionForce< DIM >::mMechanicsCutOffLength [private]
Mechanics cut off length.
Definition at line 74 of file DiffusionForce.hpp.
Referenced by DiffusionForce< DIM >::GetCutOffLength(), DiffusionForce< DIM >::OutputForceParameters(), DiffusionForce< DIM >::serialize(), and DiffusionForce< DIM >::SetCutOffLength().
template<unsigned DIM> const double DiffusionForce< DIM >::msBoltzmannConstant = 1.3806488e-23 [inline, static, private]
The boltzmann constant
Definition at line 79 of file DiffusionForce.hpp.
Referenced by DiffusionForce< DIM >::GetDiffusionScalingConstant().
template<unsigned DIM> double DiffusionForce< DIM >::mViscosity [private]
Viscosity of media. We assume that this is measured in units of kg microns^(-1) h^(-1), and that cell diameters are scaled with a characteristic length of 1 micron.
Definition at line 69 of file DiffusionForce.hpp.
Referenced by DiffusionForce< DIM >::GetDiffusionScalingConstant(), DiffusionForce< DIM >::GetViscosity(), DiffusionForce< DIM >::serialize(), and DiffusionForce< DIM >::SetViscosity().
The documentation for this class was generated from the following files:
cell_based/src/population/mechanics/DiffusionForce.hpp
cell_based/src/population/mechanics/DiffusionForce.cpp