Chaste: AbstractTimeAdaptivityController Class Reference
AbstractTimeAdaptivityController Class Reference abstract
#include <AbstractTimeAdaptivityController.hpp>
Public Member Functions
AbstractTimeAdaptivityController (double minimumTimeStep, double maximumTimeStep)
virtual ~AbstractTimeAdaptivityController ()
double GetNextTimeStep (double currentTime, Vec currentSolution)
Private Member Functions
virtual double ComputeTimeStep (double currentTime, Vec currentSolution)=0
Private Attributes
double mMinimumTimeStep
double mMaximumTimeStep
Detailed Description
Abstract class for defining rules for adaptive time-stepping.
Definition at line 45 of file AbstractTimeAdaptivityController.hpp.
Constructor & Destructor Documentation
AbstractTimeAdaptivityController()
AbstractTimeAdaptivityController::AbstractTimeAdaptivityController (double minimumTimeStep, double maximumTimeStep) inline
Constructor.
Parameters
minimumTimeStep minimum timestep to be used
maximumTimeStep maximum timestep to be used
Definition at line 73 of file AbstractTimeAdaptivityController.hpp.
~AbstractTimeAdaptivityController()
virtual AbstractTimeAdaptivityController::~AbstractTimeAdaptivityController () inline virtual
Destructor.
Definition at line 83 of file AbstractTimeAdaptivityController.hpp.
Member Function Documentation
ComputeTimeStep()
virtual double AbstractTimeAdaptivityController::ComputeTimeStep (double currentTime, Vec currentSolution) private pure virtual
Returns
the timestep based on the current solution and current time. Doesn't need to be checked to be between the minimum and maximum timesteps.
Parameters
currentTime current time
currentSolution current solution
Referenced by GetNextTimeStep().
GetNextTimeStep()
double AbstractTimeAdaptivityController::GetNextTimeStep (double currentTime, Vec currentSolution) inline
Returns
the actual timestep to be used.
Parameters
currentTime current time
currentSolution current solution
Definition at line 93 of file AbstractTimeAdaptivityController.hpp.
References ComputeTimeStep(), mMaximumTimeStep, and mMinimumTimeStep.
Referenced by AbstractDynamicLinearPdeSolver< ELEMENT_DIM, SPACE_DIM, 2 >::Solve().
Member Data Documentation
mMaximumTimeStep
double AbstractTimeAdaptivityController::mMaximumTimeStep private
Maximum timestep to be used
Definition at line 53 of file AbstractTimeAdaptivityController.hpp.
Referenced by GetNextTimeStep().
mMinimumTimeStep
double AbstractTimeAdaptivityController::mMinimumTimeStep private
Minimum timestep to be used
Definition at line 50 of file AbstractTimeAdaptivityController.hpp.
Referenced by GetNextTimeStep().
The documentation for this class was generated from the following file:
pde/src/common/AbstractTimeAdaptivityController.hpp