Chaste: IsolatedLabelledCellKiller< DIM > Class Template Reference
IsolatedLabelledCellKiller< DIM > Class Template Reference
#include <IsolatedLabelledCellKiller.hpp>
Public Member Functions
IsolatedLabelledCellKiller (AbstractCellPopulation< DIM > *pCellPopulation)
void CheckAndLabelCellsForApoptosisOrDeath ()
void OutputCellKillerParameters (out_stream &rParamsFile)
Public Member Functions inherited from AbstractCellKiller< DIM >
AbstractCellKiller (AbstractCellPopulation< SPACE_DIM > *pCellPopulation)
virtual ~AbstractCellKiller ()
const AbstractCellPopulation< SPACE_DIM > * GetCellPopulation () const
void OutputCellKillerInfo (out_stream &rParamsFile)
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Friends
class TestCellKillers
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from AbstractCellKiller< DIM >
AbstractCellPopulation< SPACE_DIM > * mpCellPopulation
Detailed Description
template<unsigned DIM>
class IsolatedLabelledCellKiller< DIM >
A cell killer that kills any cell: 1. that has the CellLabel property; 2. is not the only cell to have the CellLabel property; 3. shares no edges with any other cell with the CellLabel property.
Works for a VertexBasedCellPopulation only.
Definition at line 54 of file IsolatedLabelledCellKiller.hpp.
Constructor & Destructor Documentation
IsolatedLabelledCellKiller()
template<unsigned DIM> IsolatedLabelledCellKiller< DIM >::IsolatedLabelledCellKiller (AbstractCellPopulation< DIM > * pCellPopulation)
Default constructor.
Parameters
pCellPopulation pointer to a cell population
Definition at line 41 of file IsolatedLabelledCellKiller.cpp.
References EXCEPTION.
Referenced by IsolatedLabelledCellKiller< DIM >::serialize().
Member Function Documentation
CheckAndLabelCellsForApoptosisOrDeath()
template<unsigned DIM> void IsolatedLabelledCellKiller< DIM >::CheckAndLabelCellsForApoptosisOrDeath () virtual
Kills any isolated cells with the CellLabel property (unless there is only one such cell in the population).
Implements AbstractCellKiller< DIM >.
Definition at line 51 of file IsolatedLabelledCellKiller.cpp.
References AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::Begin(), AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::End(), AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::GetCellPropertyRegistry(), AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::GetCellUsingLocationIndex(), AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::GetLocationIndexUsingCell(), VertexMesh< ELEMENT_DIM, SPACE_DIM >::GetNeighbouringElementIndices(), and AbstractCellKiller< DIM >::mpCellPopulation.
Referenced by IsolatedLabelledCellKiller< DIM >::serialize().
OutputCellKillerParameters()
template<unsigned DIM> void IsolatedLabelledCellKiller< DIM >::OutputCellKillerParameters (out_stream & rParamsFile) virtual
Overridden OutputCellKillerParameters() method.
Parameters
rParamsFile the file stream to which the parameters are output
Implements AbstractCellKiller< DIM >.
Definition at line 97 of file IsolatedLabelledCellKiller.cpp.
References EXPORT_TEMPLATE_CLASS_SAME_DIMS, and AbstractCellKiller< SPACE_DIM >::OutputCellKillerParameters().
Referenced by IsolatedLabelledCellKiller< DIM >::serialize().
serialize()
template<unsigned DIM> template<class Archive > void IsolatedLabelledCellKiller< DIM >::serialize (Archive & archive, const unsigned int version) inline private
Archive the object.
Parameters
archive the archive
version the current version of this class
Definition at line 68 of file IsolatedLabelledCellKiller.hpp.
References IsolatedLabelledCellKiller< DIM >::CheckAndLabelCellsForApoptosisOrDeath(), EXPORT_TEMPLATE_CLASS_SAME_DIMS, IsolatedLabelledCellKiller< DIM >::IsolatedLabelledCellKiller(), and IsolatedLabelledCellKiller< DIM >::OutputCellKillerParameters().
Friends And Related Function Documentation
boost::serialization::access
template<unsigned DIM> friend class boost::serialization::access friend
Needed for serialization.
Definition at line 60 of file IsolatedLabelledCellKiller.hpp.
The documentation for this class was generated from the following files:
cell_based/src/population/killers/IsolatedLabelledCellKiller.hpp
cell_based/src/population/killers/IsolatedLabelledCellKiller.cpp