Chaste: AbstractCaSwitchingUpdateRule< DIM > Class Template Reference
AbstractCaSwitchingUpdateRule< DIM > Class Template Reference abstract
#include <AbstractCaSwitchingUpdateRule.hpp>
Public Member Functions
AbstractCaSwitchingUpdateRule ()
virtual ~AbstractCaSwitchingUpdateRule ()
virtual double EvaluateSwitchingProbability (unsigned currentNodeIndex, unsigned neighbourNodeIndex, CaBasedCellPopulation< DIM > &rCellPopulation, double dt, double deltaX)=0
virtual void OutputUpdateRuleParameters (out_stream &rParamsFile)
Public Member Functions inherited from AbstractUpdateRule< DIM >
AbstractUpdateRule ()
virtual ~AbstractUpdateRule ()
void OutputUpdateRuleInfo (out_stream &rParamsFile)
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Friends
class boost::serialization::access
Detailed Description
template<unsigned DIM>
class AbstractCaSwitchingUpdateRule< DIM >
An abstract CA 'switching' update rule class, for use in CA simulations.
Definition at line 49 of file AbstractCaSwitchingUpdateRule.hpp.
Constructor & Destructor Documentation
AbstractCaSwitchingUpdateRule()
template<unsigned DIM> AbstractCaSwitchingUpdateRule< DIM >::AbstractCaSwitchingUpdateRule ()
Default constructor.
Definition at line 39 of file AbstractCaSwitchingUpdateRule.cpp.
Referenced by AbstractCaSwitchingUpdateRule< DIM >::serialize().
~AbstractCaSwitchingUpdateRule()
template<unsigned DIM> AbstractCaSwitchingUpdateRule< DIM >::~AbstractCaSwitchingUpdateRule () virtual
Destructor.
Definition at line 45 of file AbstractCaSwitchingUpdateRule.cpp.
Referenced by AbstractCaSwitchingUpdateRule< DIM >::serialize().
Member Function Documentation
EvaluateSwitchingProbability()
template<unsigned DIM> virtual double AbstractCaSwitchingUpdateRule< DIM >::EvaluateSwitchingProbability (unsigned currentNodeIndex, unsigned neighbourNodeIndex, CaBasedCellPopulation< DIM > & rCellPopulation, double dt, double deltaX) pure virtual
Calculate the probability of a given switch.
Parameters
currentNodeIndex The index of the current node/lattice site
neighbourNodeIndex The index of the neighbour node/lattice site
rCellPopulation The cell population
dt is the time interval
deltaX defines the size of the lattice site
Returns
The probability of the cells associated to the current node and the target node switching.
Implemented in RandomCaSwitchingUpdateRule< DIM >.
Referenced by AbstractCaSwitchingUpdateRule< DIM >::serialize().
OutputUpdateRuleParameters()
template<unsigned DIM> void AbstractCaSwitchingUpdateRule< DIM >::OutputUpdateRuleParameters (out_stream & rParamsFile) virtual
Overridden OutputUpdateRuleParameters() method.
Parameters
rParamsFile a file stream
Implements AbstractUpdateRule< DIM >.
Reimplemented in RandomCaSwitchingUpdateRule< DIM >.
Definition at line 50 of file AbstractCaSwitchingUpdateRule.cpp.
References AbstractUpdateRule< DIM >::OutputUpdateRuleParameters().
Referenced by RandomCaSwitchingUpdateRule< DIM >::OutputUpdateRuleParameters(), and AbstractCaSwitchingUpdateRule< DIM >::serialize().
serialize()
template<unsigned DIM> template<class Archive > void AbstractCaSwitchingUpdateRule< DIM >::serialize (Archive & archive, const unsigned int version) inline private
Boost Serialization method for archiving/checkpointing. Archives the object and its member variables.
Parameters
archive The boost archive.
version The current version of this class.
Definition at line 61 of file AbstractCaSwitchingUpdateRule.hpp.
References AbstractCaSwitchingUpdateRule< DIM >::AbstractCaSwitchingUpdateRule(), AbstractCaSwitchingUpdateRule< DIM >::EvaluateSwitchingProbability(), AbstractCaSwitchingUpdateRule< DIM >::OutputUpdateRuleParameters(), and AbstractCaSwitchingUpdateRule< DIM >::~AbstractCaSwitchingUpdateRule().
Friends And Related Function Documentation
boost::serialization::access
template<unsigned DIM> friend class boost::serialization::access friend
Needed for serialization.
Definition at line 52 of file AbstractCaSwitchingUpdateRule.hpp.
The documentation for this class was generated from the following files:
cell_based/src/population/update_rules/AbstractCaSwitchingUpdateRule.hpp
cell_based/src/population/update_rules/AbstractCaSwitchingUpdateRule.cpp