Chaste: MonodomainPurkinjeProblem< ELEMENT_DIM, SPACE_DIM > Class Template Reference
MonodomainPurkinjeProblem< ELEMENT_DIM, SPACE_DIM > Class Template Reference
#include <MonodomainPurkinjeProblem.hpp>
Public Member Functions
MonodomainPurkinjeProblem (AbstractPurkinjeCellFactory< ELEMENT_DIM, SPACE_DIM > *pCellFactory)
MonodomainPurkinjeProblem ()
virtual ~MonodomainPurkinjeProblem ()
void WriteInfo (double time)
virtual void DefineWriterColumns (bool extending)
virtual void WriteOneStep (double time, Vec voltageVec)
Public Member Functions inherited from AbstractCardiacProblem< ELEMENT_DIM, SPACE_DIM, 2 >
AbstractCardiacProblem (AbstractCardiacCellFactory< ELEMENT_DIM, SPACE_DIM > *pCellFactory)
AbstractCardiacProblem ()
virtual ~AbstractCardiacProblem ()
void Initialise ()
void SetNodesPerProcessorFilename (const std::string &rFilename)
void SetBoundaryConditionsContainer (BccType pBcc)
virtual void PreSolveChecks ()
void SetMesh (AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM > *pMesh)
void PrintOutput (bool rPrintOutput)
void SetWriteInfo (bool writeInfo=true)
Vec GetSolution ()
DistributedVector GetSolutionDistributedVector ()
double GetCurrentTime ()
AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM > & rGetMesh ()
AbstractCardiacTissue< ELEMENT_DIM, SPACE_DIM > * GetTissue ()
void Solve ()
void CloseFilesAndPostProcess ()
void DefineExtraVariablesWriterColumns (bool extending)
void WriteExtraVariablesOneStep ()
bool InitialiseWriter ()
void SetUseHdf5DataWriterCache (bool useCache=true)
void SetHdf5DataWriterTargetChunkSizeAndAlignment (hsize_t size)
void SetOutputNodes (std::vector< unsigned > &rNodesToOutput)
Hdf5DataReader GetDataReader ()
virtual void AtBeginningOfTimestep (double time)
virtual void OnEndOfTimestep (double time)
virtual void SetUpAdditionalStoppingTimes (std::vector< double > &rAdditionalStoppingTimes)
void SetUseTimeAdaptivityController (bool useAdaptivity, AbstractTimeAdaptivityController *pController=NULL)
void LoadExtraArchive (Archive &archive, unsigned version)
virtual bool GetHasBath ()
virtual void SetElectrodes ()
void AddOutputModifier (boost::shared_ptr< AbstractOutputModifier > pOutputModifier)
Public Member Functions inherited from AbstractUntemplatedCardiacProblem
virtual ~AbstractUntemplatedCardiacProblem ()
Protected Member Functions
AbstractCardiacTissue< ELEMENT_DIM, SPACE_DIM > * CreateCardiacTissue ()
AbstractDynamicLinearPdeSolver< ELEMENT_DIM, SPACE_DIM, 2 > * CreateSolver ()
virtual void CreateMeshFromHeartConfig ()
Vec CreateInitialCondition ()
Protected Attributes
unsigned mPurkinjeVoltageColumnId
Protected Attributes inherited from AbstractCardiacProblem< ELEMENT_DIM, SPACE_DIM, 2 >
std::string mMeshFilename
bool mAllocatedMemoryForMesh
bool mWriteInfo
bool mPrintOutput
std::vector< unsigned > mNodesToOutput
unsigned mVoltageColumnId
std::vector< unsigned > mExtraVariablesId
unsigned mTimeColumnId
unsigned mNodeColumnId
AbstractCardiacTissue< ELEMENT_DIM, SPACE_DIM > * mpCardiacTissue
BccType mpBoundaryConditionsContainer
BccType mpDefaultBoundaryConditionsContainer
AbstractDynamicLinearPdeSolver< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM > * mpSolver
AbstractCardiacCellFactory< ELEMENT_DIM, SPACE_DIM > * mpCellFactory
AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM > * mpMesh
Vec mSolution
double mCurrentTime
AbstractTimeAdaptivityController * mpTimeAdaptivityController
Hdf5DataWriter * mpWriter
bool mUseHdf5DataWriterCache
hsize_t mHdf5DataWriterChunkSizeAndAlignment
std::vector< boost::shared_ptr< AbstractOutputModifier > > mOutputModifiers
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Friends
class boost::serialization::access
Detailed Description
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM = ELEMENT_DIM>
class MonodomainPurkinjeProblem< ELEMENT_DIM, SPACE_DIM >
Class which specifies and solves a monodomain problem with Purkinje fibres.
Definition at line 51 of file MonodomainPurkinjeProblem.hpp.
Constructor & Destructor Documentation
MonodomainPurkinjeProblem() [1/2]
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> MonodomainPurkinjeProblem< ELEMENT_DIM, SPACE_DIM >::MonodomainPurkinjeProblem (AbstractPurkinjeCellFactory< ELEMENT_DIM, SPACE_DIM > * pCellFactory)
Constructor
Parameters
pCellFactory user defined cell factory which shows how the tissue should create cells.
Definition at line 93 of file MonodomainPurkinjeProblem.cpp.
MonodomainPurkinjeProblem() [2/2]
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> MonodomainPurkinjeProblem< ELEMENT_DIM, SPACE_DIM >::MonodomainPurkinjeProblem ()
Constructor just used for archiving
Definition at line 102 of file MonodomainPurkinjeProblem.cpp.
~MonodomainPurkinjeProblem()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> MonodomainPurkinjeProblem< ELEMENT_DIM, SPACE_DIM >::~MonodomainPurkinjeProblem () virtual
Destructor
Definition at line 110 of file MonodomainPurkinjeProblem.cpp.
Member Function Documentation
CreateCardiacTissue()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> AbstractCardiacTissue< ELEMENT_DIM, SPACE_DIM > * MonodomainPurkinjeProblem< ELEMENT_DIM, SPACE_DIM >::CreateCardiacTissue () protected virtual
Returns
newly created our tissue object.
Implements AbstractCardiacProblem< ELEMENT_DIM, SPACE_DIM, 2 >.
Definition at line 43 of file MonodomainPurkinjeProblem.cpp.
References HeartConfig::GetUseStateVariableInterpolation(), and HeartConfig::Instance().
CreateInitialCondition()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> Vec MonodomainPurkinjeProblem< ELEMENT_DIM, SPACE_DIM >::CreateInitialCondition () protected virtual
Overridden method which creates initial condition using Purkinje initial voltages as well.
Returns
newly created initial condition
Reimplemented from AbstractCardiacProblem< ELEMENT_DIM, SPACE_DIM, 2 >.
Definition at line 70 of file MonodomainPurkinjeProblem.cpp.
References AbstractCardiacProblem< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::CreateInitialCondition().
CreateMeshFromHeartConfig()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void MonodomainPurkinjeProblem< ELEMENT_DIM, SPACE_DIM >::CreateMeshFromHeartConfig () protected virtual
Returns
newly created suitable (MixedDimensionMesh) mesh for monodomain problems with Purkinje.
Reimplemented from AbstractCardiacProblem< ELEMENT_DIM, SPACE_DIM, 2 >.
Definition at line 63 of file MonodomainPurkinjeProblem.cpp.
References HeartConfig::GetMeshPartitioning(), and HeartConfig::Instance().
CreateSolver()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> AbstractDynamicLinearPdeSolver< ELEMENT_DIM, SPACE_DIM, 2 > * MonodomainPurkinjeProblem< ELEMENT_DIM, SPACE_DIM >::CreateSolver () protected virtual
Returns
newly created suitable solver for monodomain problems with Purkinje.
Todo:
#2017 give a nice error
Implements AbstractCardiacProblem< ELEMENT_DIM, SPACE_DIM, 2 >.
Definition at line 50 of file MonodomainPurkinjeProblem.cpp.
References EXCEPT_IF_NOT, and HeartConfig::Instance().
DefineWriterColumns()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void MonodomainPurkinjeProblem< ELEMENT_DIM, SPACE_DIM >::DefineWriterColumns (bool extending) virtual
Define what variables are written to the primary results file.
Parameters
extending whether we are extending an existing results file
Reimplemented from AbstractCardiacProblem< ELEMENT_DIM, SPACE_DIM, 2 >.
Definition at line 153 of file MonodomainPurkinjeProblem.cpp.
References AbstractCardiacProblem< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::DefineExtraVariablesWriterColumns(), Hdf5DataWriter::DefineVariable(), AbstractCardiacProblem< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::DefineWriterColumns(), Hdf5DataWriter::GetVariableByName(), MonodomainPurkinjeProblem< ELEMENT_DIM, SPACE_DIM >::mPurkinjeVoltageColumnId, and AbstractCardiacProblem< ELEMENT_DIM, SPACE_DIM, 2 >::mpWriter.
serialize()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM = ELEMENT_DIM> template<class Archive > void MonodomainPurkinjeProblem< ELEMENT_DIM, SPACE_DIM >::serialize (Archive & archive, const unsigned int version) inline private
Archive the member variables.
Parameters
archive
version
Todo:
Serialization of Purkinje problems is untested
Definition at line 63 of file MonodomainPurkinjeProblem.hpp.
References NEVER_REACHED.
WriteInfo()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void MonodomainPurkinjeProblem< ELEMENT_DIM, SPACE_DIM >::WriteInfo (double time) virtual
Print out time and max/min voltage values at current time.
Parameters
time the current time
Implements AbstractCardiacProblem< ELEMENT_DIM, SPACE_DIM, 2 >.
Definition at line 116 of file MonodomainPurkinjeProblem.cpp.
References PetscTools::AmMaster(), and AbstractCardiacProblem< ELEMENT_DIM, SPACE_DIM, 2 >::mSolution.
WriteOneStep()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void MonodomainPurkinjeProblem< ELEMENT_DIM, SPACE_DIM >::WriteOneStep (double time, Vec voltageVec) virtual
Write one timestep of output data to the primary results file. Adds the Purkinje transmembrane potential to the results.
Parameters
time the current time
voltageVec the solution vector to write
Implements AbstractCardiacProblem< ELEMENT_DIM, SPACE_DIM, 2 >.
Definition at line 169 of file MonodomainPurkinjeProblem.cpp.
References EXPORT_TEMPLATE_CLASS2, MonodomainPurkinjeProblem< ELEMENT_DIM, SPACE_DIM >::mPurkinjeVoltageColumnId, AbstractCardiacProblem< ELEMENT_DIM, SPACE_DIM, 2 >::mpWriter, AbstractCardiacProblem< ELEMENT_DIM, SPACE_DIM, 2 >::mVoltageColumnId, Hdf5DataWriter::PutStripedVector(), Hdf5DataWriter::PutUnlimitedVariable(), and AbstractCardiacProblem< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::WriteExtraVariablesOneStep().
Friends And Related Function Documentation
boost::serialization::access
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM = ELEMENT_DIM> friend class boost::serialization::access friend
Needed for serialization.
Definition at line 55 of file MonodomainPurkinjeProblem.hpp.
Member Data Documentation
mPurkinjeVoltageColumnId
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM = ELEMENT_DIM> unsigned MonodomainPurkinjeProblem< ELEMENT_DIM, SPACE_DIM >::mPurkinjeVoltageColumnId protected
Used by the writer.
Definition at line 75 of file MonodomainPurkinjeProblem.hpp.
Referenced by MonodomainPurkinjeProblem< ELEMENT_DIM, SPACE_DIM >::DefineWriterColumns(), and MonodomainPurkinjeProblem< ELEMENT_DIM, SPACE_DIM >::WriteOneStep().
The documentation for this class was generated from the following files:
heart/src/problem/MonodomainPurkinjeProblem.hpp
heart/src/problem/MonodomainPurkinjeProblem.cpp