Chaste: BidomainProblem< DIM > Class Template Reference
BidomainProblem< DIM > Class Template Reference
#include <BidomainProblem.hpp>
Public Member Functions
BidomainProblem (AbstractCardiacCellFactory< DIM > *pCellFactory, bool hasBath=false)
BidomainProblem ()
void SetFixedExtracellularPotentialNodes (std::vector< unsigned > nodes)
void SetNodeForAverageOfPhiZeroed (unsigned node)
BidomainTissue< DIM > * GetBidomainTissue ()
void WriteInfo (double time)
virtual void DefineWriterColumns (bool extending)
virtual void WriteOneStep (double time, Vec voltageVec)
void PreSolveChecks ()
void AtBeginningOfTimestep (double time)
void OnEndOfTimestep (double time)
void SetUpAdditionalStoppingTimes (std::vector< double > &rAdditionalStoppingTimes)
template<class Archive >
void LoadExtraArchiveForBidomain (Archive &archive, unsigned version)
bool GetHasBath ()
void SetElectrodes ()
Public Member Functions inherited from AbstractCardiacProblem< DIM, DIM, 2 >
AbstractCardiacProblem (AbstractCardiacCellFactory< ELEMENT_DIM, SPACE_DIM > *pCellFactory)
AbstractCardiacProblem ()
virtual ~AbstractCardiacProblem ()
void Initialise ()
void SetNodesPerProcessorFilename (const std::string &rFilename)
void SetBoundaryConditionsContainer (BccType pBcc)
void SetMesh (AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM > *pMesh)
void PrintOutput (bool rPrintOutput)
void SetWriteInfo (bool writeInfo=true)
Vec GetSolution ()
DistributedVector GetSolutionDistributedVector ()
double GetCurrentTime ()
AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM > & rGetMesh ()
AbstractCardiacTissue< ELEMENT_DIM, SPACE_DIM > * GetTissue ()
void Solve ()
void CloseFilesAndPostProcess ()
void DefineExtraVariablesWriterColumns (bool extending)
void WriteExtraVariablesOneStep ()
bool InitialiseWriter ()
void SetUseHdf5DataWriterCache (bool useCache=true)
void SetHdf5DataWriterTargetChunkSizeAndAlignment (hsize_t size)
void SetOutputNodes (std::vector< unsigned > &rNodesToOutput)
Hdf5DataReader GetDataReader ()
void SetUseTimeAdaptivityController (bool useAdaptivity, AbstractTimeAdaptivityController *pController=NULL)
void LoadExtraArchive (Archive &archive, unsigned version)
void AddOutputModifier (boost::shared_ptr< AbstractOutputModifier > pOutputModifier)
Public Member Functions inherited from AbstractUntemplatedCardiacProblem
virtual ~AbstractUntemplatedCardiacProblem ()
Protected Member Functions
Vec CreateInitialCondition ()
void AnalyseMeshForBath ()
virtual AbstractCardiacTissue< DIM > * CreateCardiacTissue ()
virtual AbstractDynamicLinearPdeSolver< DIM, DIM, 2 > * CreateSolver ()
Protected Member Functions inherited from AbstractCardiacProblem< DIM, DIM, 2 >
virtual void CreateMeshFromHeartConfig ()
Protected Attributes
BidomainTissue< DIM > * mpBidomainTissue
std::vector< unsigned > mFixedExtracellularPotentialNodes
unsigned mExtracelluarColumnId
unsigned mRowForAverageOfPhiZeroed
bool mHasBath
boost::shared_ptr< Electrodes< DIM > > mpElectrodes
AbstractBidomainSolver< DIM, DIM > * mpSolver
Protected Attributes inherited from AbstractCardiacProblem< DIM, DIM, 2 >
std::string mMeshFilename
bool mAllocatedMemoryForMesh
bool mWriteInfo
bool mPrintOutput
std::vector< unsigned > mNodesToOutput
unsigned mVoltageColumnId
std::vector< unsigned > mExtraVariablesId
unsigned mTimeColumnId
unsigned mNodeColumnId
AbstractCardiacTissue< ELEMENT_DIM, SPACE_DIM > * mpCardiacTissue
BccType mpBoundaryConditionsContainer
BccType mpDefaultBoundaryConditionsContainer
AbstractDynamicLinearPdeSolver< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM > * mpSolver
AbstractCardiacCellFactory< ELEMENT_DIM, SPACE_DIM > * mpCellFactory
AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM > * mpMesh
Vec mSolution
double mCurrentTime
AbstractTimeAdaptivityController * mpTimeAdaptivityController
Hdf5DataWriter * mpWriter
bool mUseHdf5DataWriterCache
hsize_t mHdf5DataWriterChunkSizeAndAlignment
std::vector< boost::shared_ptr< AbstractOutputModifier > > mOutputModifiers
Private Member Functions
template<class Archive >
void save (Archive &archive, const unsigned int version) const
template<class Archive >
void load (Archive &archive, const unsigned int version)
Friends
class boost::serialization::access
class TestPCTwoLevelsBlockDiagonal
class TestBidomainWithBathProblem
class TestCardiacSimulationArchiver
Detailed Description
template<unsigned DIM>
class BidomainProblem< DIM >
Class which specifies and solves a bidomain problem.
The solution vector is of the form: (V_1, phi_1, V_2, phi_2, ......, V_N, phi_N), where V_j is the voltage at node j and phi_j is the extracellular potential at node j.
Definition at line 809 of file AbstractCardiacProblem.hpp.
Constructor & Destructor Documentation
BidomainProblem() [1/2]
template<unsigned DIM> BidomainProblem< DIM >::BidomainProblem (AbstractCardiacCellFactory< DIM > * pCellFactory, bool hasBath = false)
Constructor
Parameters
pCellFactory User defined cell factory which shows how the pde should create cells.
hasBath Whether the simulation has a bath (if this is true, all elements with attribute = 1 will be set to be bath elements (the rest should have attribute = 0)).
Definition at line 164 of file BidomainProblem.cpp.
References BidomainProblem< DIM >::mFixedExtracellularPotentialNodes.
BidomainProblem() [2/2]
template<unsigned DIM> BidomainProblem< DIM >::BidomainProblem ()
Constructor just used for archiving
Definition at line 175 of file BidomainProblem.cpp.
References BidomainProblem< DIM >::mFixedExtracellularPotentialNodes.
Member Function Documentation
AnalyseMeshForBath()
template<unsigned DIM> void BidomainProblem< DIM >::AnalyseMeshForBath () protected
Annotate bath nodes with the correct region code, if a bath is present. Will throw if mHasBath is set but no bath is present in the mesh.
Definition at line 45 of file BidomainProblem.cpp.
References AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::GetElementIteratorBegin(), AbstractMesh< ELEMENT_DIM, SPACE_DIM >::GetNodeIteratorBegin(), AbstractElement< ELEMENT_DIM, SPACE_DIM >::GetUnsignedAttribute(), HeartRegionCode::GetValidBathId(), and HeartRegionCode::IsRegionTissue().
Referenced by BidomainProblem< DIM >::load().
AtBeginningOfTimestep()
template<unsigned DIM> void BidomainProblem< DIM >::AtBeginningOfTimestep (double time) virtual
Called at beginning of each time step in the main time-loop in AbstractCardiacProblem::Solve(). Overloaded here to switch on the electrodes (if there are any).
Parameters
time the current time
Todo:
#1159 #1324 heart/src/problem/AbstractCardiacProblem.hpp:657 expects both pointing at the same place when unarchiving
Reimplemented from AbstractCardiacProblem< DIM, DIM, 2 >.
Definition at line 296 of file BidomainProblem.cpp.
References AbstractLinearPdeSolver< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::GetLinearSystem(), AbstractCardiacProblem< DIM, DIM, 2 >::mpBoundaryConditionsContainer, AbstractCardiacProblem< DIM, DIM, 2 >::mpDefaultBoundaryConditionsContainer, BidomainProblem< DIM >::mpElectrodes, BidomainProblem< DIM >::mpSolver, LinearSystem::RemoveNullSpace(), and AbstractBidomainSolver< ELEMENT_DIM, SPACE_DIM >::ResetBoundaryConditionsContainer().
CreateCardiacTissue()
template<unsigned DIM> AbstractCardiacTissue< DIM > * BidomainProblem< DIM >::CreateCardiacTissue () protected virtual
Returns
a newly created bidomain PDE object
Implements AbstractCardiacProblem< DIM, DIM, 2 >.
Definition at line 125 of file BidomainProblem.cpp.
References HeartConfig::GetUseStateVariableInterpolation(), and HeartConfig::Instance().
CreateInitialCondition()
template<unsigned DIM> Vec BidomainProblem< DIM >::CreateInitialCondition () protected virtual
Create normal initial condition but overwrite V to zero for bath nodes, if there are any.
Returns
the newly created intial conditions vector
Reimplemented from AbstractCardiacProblem< DIM, DIM, 2 >.
Definition at line 100 of file BidomainProblem.cpp.
References AbstractCardiacProblem< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::CreateInitialCondition().
CreateSolver()
template<unsigned DIM> AbstractDynamicLinearPdeSolver< DIM, DIM, 2 > * BidomainProblem< DIM >::CreateSolver () protected virtual
Returns
a newly created suitable bidomain solver
Implements AbstractCardiacProblem< DIM, DIM, 2 >.
Definition at line 133 of file BidomainProblem.cpp.
References AbstractBidomainSolver< ELEMENT_DIM, SPACE_DIM >::SetFixedExtracellularPotentialNodes().
Referenced by BidomainProblem< DIM >::OnEndOfTimestep().
DefineWriterColumns()
template<unsigned DIM> void BidomainProblem< DIM >::DefineWriterColumns (bool extending) virtual
Define what variables are written to the primary results file. Adds the extracellular potential.
Parameters
extending whether we are extending an existing results file
Reimplemented from AbstractCardiacProblem< DIM, DIM, 2 >.
Definition at line 233 of file BidomainProblem.cpp.
References AbstractCardiacProblem< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::DefineExtraVariablesWriterColumns(), Hdf5DataWriter::DefineVariable(), AbstractCardiacProblem< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::DefineWriterColumns(), Hdf5DataWriter::GetVariableByName(), BidomainProblem< DIM >::mExtracelluarColumnId, and AbstractCardiacProblem< DIM, DIM, 2 >::mpWriter.
GetBidomainTissue()
template<unsigned DIM> BidomainTissue< DIM > * BidomainProblem< DIM >::GetBidomainTissue ()
Returns
the pde. Can only be called after Initialise()
Definition at line 202 of file BidomainProblem.cpp.
References BidomainProblem< DIM >::mpBidomainTissue.
GetHasBath()
template<unsigned DIM> bool BidomainProblem< DIM >::GetHasBath () virtual
Returns
whether this is a bidomain problem with bath or not
Reimplemented from AbstractCardiacProblem< DIM, DIM, 2 >.
Definition at line 383 of file BidomainProblem.cpp.
References EXPORT_TEMPLATE_CLASS_SAME_DIMS, and BidomainProblem< DIM >::mHasBath.
load()
template<unsigned DIM> template<class Archive > void BidomainProblem< DIM >::load (Archive & archive, const unsigned int version) inline private
Load the member variables from an archive.
Parameters
archive
version
Definition at line 97 of file BidomainProblem.hpp.
References BidomainProblem< DIM >::AnalyseMeshForBath(), BidomainProblem< DIM >::mHasBath, BidomainProblem< DIM >::mpBidomainTissue, BidomainProblem< DIM >::mpElectrodes, and BidomainProblem< DIM >::mRowForAverageOfPhiZeroed.
LoadExtraArchiveForBidomain()
template<unsigned DIM> template<class Archive > void BidomainProblem< DIM >::LoadExtraArchiveForBidomain (Archive & archive, unsigned version)
Used when loading a set of archives written by a parallel simulation onto a single process. Loads data from the given process-specific archive (written by a non-master process) and merges it into our data.
Parameters
archive the archive to load
version the archive file version
Note
The process-specific archives currently contain the following data. If the layout changes, then this method will need to be altered, since it hard-codes knowledge of the order in which things are archived.
Stuff known by AbstractCardiacProblem
mpElectrodes->mpBoundaryConditionsContainer
This gets called by AbstractCardiacProblem::LoadExtraArchive when it's done the generic stuff.
Todo:
#1159 sanity check that the contents of p_bcc and mpElectrodes->GetBoundaryConditionsContainer() match.
Definition at line 299 of file BidomainProblem.hpp.
References AbstractCardiacProblem< DIM, DIM, 2 >::mpBoundaryConditionsContainer, BidomainProblem< DIM >::mpElectrodes, and AbstractCardiacProblem< DIM, DIM, 2 >::mpMesh.
Referenced by AbstractCardiacProblem< ELEMENT_DIM, SPACE_DIM, 2 >::LoadExtraArchive().
OnEndOfTimestep()
template<unsigned DIM> void BidomainProblem< DIM >::OnEndOfTimestep (double time) virtual
Called at end of each time step in the main time-loop in AbstractCardiacProblem::Solve(). Overloaded here to switch off the electrodes (if there are any).
Parameters
time the current time
Reimplemented from AbstractCardiacProblem< DIM, DIM, 2 >.
Definition at line 337 of file BidomainProblem.cpp.
References BidomainProblem< DIM >::CreateSolver(), HeartConfig::Instance(), AbstractCardiacProblem< DIM, DIM, 2 >::mpBoundaryConditionsContainer, AbstractCardiacProblem< DIM, DIM, 2 >::mpDefaultBoundaryConditionsContainer, BidomainProblem< DIM >::mpElectrodes, AbstractCardiacProblem< DIM, DIM, 2 >::mpMesh, BidomainProblem< DIM >::mpSolver, AbstractBidomainSolver< ELEMENT_DIM, SPACE_DIM >::ResetBoundaryConditionsContainer(), and AbstractDynamicLinearPdeSolver< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::SetTimeStep().
PreSolveChecks()
template<unsigned DIM> void BidomainProblem< DIM >::PreSolveChecks () virtual
Performs a series of checks before solving. Checks that a suitable method of resolving the singularity is being used.
Reimplemented from AbstractCardiacProblem< DIM, DIM, 2 >.
Definition at line 259 of file BidomainProblem.cpp.
References EXCEPTION, HeartConfig::GetUseRelativeTolerance(), HeartConfig::Instance(), BidomainProblem< DIM >::mFixedExtracellularPotentialNodes, BidomainProblem< DIM >::mRowForAverageOfPhiZeroed, and AbstractCardiacProblem< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::PreSolveChecks().
save()
template<unsigned DIM> template<class Archive > void BidomainProblem< DIM >::save (Archive & archive, const unsigned int version) const inline private
Save the member variables to an archive.
Parameters
archive
version
Definition at line 80 of file BidomainProblem.hpp.
References BidomainProblem< DIM >::mHasBath, BidomainProblem< DIM >::mpBidomainTissue, BidomainProblem< DIM >::mpElectrodes, and BidomainProblem< DIM >::mRowForAverageOfPhiZeroed.
SetElectrodes()
template<unsigned DIM> void BidomainProblem< DIM >::SetElectrodes () virtual
Set an electrode object (which provides boundary conditions). Only valid if there is a bath.
Reimplemented from AbstractCardiacProblem< DIM, DIM, 2 >.
Definition at line 279 of file BidomainProblem.cpp.
References HeartConfig::Instance(), BidomainProblem< DIM >::mHasBath, BidomainProblem< DIM >::mpElectrodes, and AbstractCardiacProblem< DIM, DIM, 2 >::mpMesh.
SetFixedExtracellularPotentialNodes()
template<unsigned DIM> void BidomainProblem< DIM >::SetFixedExtracellularPotentialNodes (std::vector< unsigned > nodes)
Set the nodes at which phi_e (the extracellular potential) is fixed to zero. This does not necessarily have to be called. If it is not, phi_e is only defined up to a constant.
Parameters
nodes the nodes to be fixed.
Note
currently, the value of phi_e at the fixed nodes cannot be set to be anything other than zero.
Definition at line 184 of file BidomainProblem.cpp.
References BidomainProblem< DIM >::mFixedExtracellularPotentialNodes.
SetNodeForAverageOfPhiZeroed()
template<unsigned DIM> void BidomainProblem< DIM >::SetNodeForAverageOfPhiZeroed (unsigned node)
Set which row of the linear system should be used to enforce the condition that the average of phi_e is zero. If not called, this condition will not be used.
Parameters
node the mesh node index giving the row at which to impose the constraint
Definition at line 196 of file BidomainProblem.cpp.
References BidomainProblem< DIM >::mRowForAverageOfPhiZeroed.
SetUpAdditionalStoppingTimes()
template<unsigned DIM> void BidomainProblem< DIM >::SetUpAdditionalStoppingTimes (std::vector< double > & rAdditionalStoppingTimes) virtual
Method to fill in a vector of additional stopping times consisting of the times when the electrodes are to be turned on and off
Parameters
rAdditionalStoppingTimes reference to vector that will contain the on and off times for the electrodes
Reimplemented from AbstractCardiacProblem< DIM, DIM, 2 >.
Definition at line 373 of file BidomainProblem.cpp.
References BidomainProblem< DIM >::mpElectrodes.
WriteInfo()
template<unsigned DIM> void BidomainProblem< DIM >::WriteInfo (double time) virtual
Print out time and max/min voltage/phi_e values at current time.
Parameters
time current time.
Implements AbstractCardiacProblem< DIM, DIM, 2 >.
Definition at line 209 of file BidomainProblem.cpp.
References PetscTools::AmMaster(), and AbstractCardiacProblem< DIM, DIM, 2 >::mSolution.
WriteOneStep()
template<unsigned DIM> void BidomainProblem< DIM >::WriteOneStep (double time, Vec voltageVec) virtual
Write one timestep of output data to the primary results file. Adds the extracellular potential to the results.
Parameters
time the current time
voltageVec the solution vector to write
Implements AbstractCardiacProblem< DIM, DIM, 2 >.
Definition at line 248 of file BidomainProblem.cpp.
References BidomainProblem< DIM >::mExtracelluarColumnId, AbstractCardiacProblem< DIM, DIM, 2 >::mpWriter, AbstractCardiacProblem< DIM, DIM, 2 >::mVoltageColumnId, Hdf5DataWriter::PutStripedVector(), Hdf5DataWriter::PutUnlimitedVariable(), and AbstractCardiacProblem< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::WriteExtraVariablesOneStep().
Friends And Related Function Documentation
boost::serialization::access
template<unsigned DIM> friend class boost::serialization::access friend
Needed for serialization.
Definition at line 68 of file BidomainProblem.hpp.
Member Data Documentation
mExtracelluarColumnId
template<unsigned DIM> unsigned BidomainProblem< DIM >::mExtracelluarColumnId protected
Used by the writer
Definition at line 124 of file BidomainProblem.hpp.
Referenced by BidomainProblem< DIM >::DefineWriterColumns(), and BidomainProblem< DIM >::WriteOneStep().
mFixedExtracellularPotentialNodes
template<unsigned DIM> std::vector<unsigned> BidomainProblem< DIM >::mFixedExtracellularPotentialNodes protected
Nodes at which the extracellular voltage is fixed to zero (replicated)
Definition at line 122 of file BidomainProblem.hpp.
Referenced by BidomainProblem< DIM >::BidomainProblem(), BidomainProblem< DIM >::PreSolveChecks(), and BidomainProblem< DIM >::SetFixedExtracellularPotentialNodes().
mHasBath
template<unsigned DIM> bool BidomainProblem< DIM >::mHasBath protected
Whether the mesh has a bath, ie whether this is a bath simulation
Definition at line 132 of file BidomainProblem.hpp.
Referenced by BidomainProblem< DIM >::GetHasBath(), BidomainProblem< DIM >::load(), BidomainProblem< DIM >::save(), and BidomainProblem< DIM >::SetElectrodes().
mpBidomainTissue
template<unsigned DIM> BidomainTissue<DIM>* BidomainProblem< DIM >::mpBidomainTissue protected
The bidomain PDE
Definition at line 119 of file BidomainProblem.hpp.
Referenced by BidomainProblem< DIM >::GetBidomainTissue(), BidomainProblem< DIM >::load(), and BidomainProblem< DIM >::save().
mpElectrodes
template<unsigned DIM> boost::shared_ptr<Electrodes<DIM> > BidomainProblem< DIM >::mpElectrodes protected
Electrodes used to provide a shock
Definition at line 135 of file BidomainProblem.hpp.
Referenced by BidomainProblem< DIM >::AtBeginningOfTimestep(), BidomainProblem< DIM >::load(), BidomainProblem< DIM >::LoadExtraArchiveForBidomain(), BidomainProblem< DIM >::OnEndOfTimestep(), BidomainProblem< DIM >::save(), BidomainProblem< DIM >::SetElectrodes(), and BidomainProblem< DIM >::SetUpAdditionalStoppingTimes().
mpSolver
template<unsigned DIM> AbstractBidomainSolver<DIM,DIM>* BidomainProblem< DIM >::mpSolver protected
We need to save the solver that is being used to be able to switch off the electrodes (by adding default boundary conditions to the solver)
Definition at line 155 of file BidomainProblem.hpp.
Referenced by BidomainProblem< DIM >::AtBeginningOfTimestep(), and BidomainProblem< DIM >::OnEndOfTimestep().
mRowForAverageOfPhiZeroed
template<unsigned DIM> unsigned BidomainProblem< DIM >::mRowForAverageOfPhiZeroed protected
Another method of resolving the singularity in the bidomain equations. Specifies a row of the matrix at which to impose an extra condition.
Definition at line 129 of file BidomainProblem.hpp.
Referenced by BidomainProblem< DIM >::load(), BidomainProblem< DIM >::PreSolveChecks(), BidomainProblem< DIM >::save(), and BidomainProblem< DIM >::SetNodeForAverageOfPhiZeroed().
The documentation for this class was generated from the following files:
heart/src/problem/AbstractCardiacProblem.hpp
heart/src/problem/BidomainProblem.hpp
heart/src/problem/BidomainProblem.cpp