Chaste: HeunIvpOdeSolver Class Reference
HeunIvpOdeSolver Class Reference
#include <HeunIvpOdeSolver.hpp>
Public Member Functions
HeunIvpOdeSolver ()
Public Member Functions inherited from AbstractOneStepIvpOdeSolver
virtual OdeSolution Solve (AbstractOdeSystem *pAbstractOdeSystem, std::vector< double > &rYValues, double startTime, double endTime, double timeStep, double timeSampling)
virtual void Solve (AbstractOdeSystem *pAbstractOdeSystem, std::vector< double > &rYValues, double startTime, double endTime, double timeStep)
virtual ~AbstractOneStepIvpOdeSolver ()
Public Member Functions inherited from AbstractIvpOdeSolver
virtual void SolveAndUpdateStateVariable (AbstractOdeSystem *pAbstractOdeSystem, double startTime, double endTime, double timeStep)
bool StoppingEventOccurred ()
double GetStoppingTime ()
AbstractIvpOdeSolver ()
virtual ~AbstractIvpOdeSolver ()
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Protected Member Functions
void CalculateNextYValue (AbstractOdeSystem *pAbstractOdeSystem, double timeStep, double time, std::vector< double > &rCurrentYValues, std::vector< double > &rNextYValues)
Protected Member Functions inherited from AbstractOneStepIvpOdeSolver
virtual void InternalSolve (AbstractOdeSystem *pAbstractOdeSystem, std::vector< double > &rCurrentYValues, std::vector< double > &rWorkingMemory, double startTime, double endTime, double timeStep)
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Friends
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from AbstractIvpOdeSolver
bool mStoppingEventOccurred
double mStoppingTime
Detailed Description
A concrete one step ODE solver class that employs the Heun 2nd order solver.
Definition at line 48 of file HeunIvpOdeSolver.hpp.
Constructor & Destructor Documentation
HeunIvpOdeSolver()
HeunIvpOdeSolver::HeunIvpOdeSolver () inline
Constructor.
Definition at line 89 of file HeunIvpOdeSolver.hpp.
References CHASTE_CLASS_EXPORT.
Member Function Documentation
CalculateNextYValue()
void HeunIvpOdeSolver::CalculateNextYValue (AbstractOdeSystem * pAbstractOdeSystem, double timeStep, double time, std::vector< double > & rCurrentYValues, std::vector< double > & rNextYValues) protected virtual
Calculate the solution to the ODE system at the next timestep.
Parameters
pAbstractOdeSystem the ODE system to solve
timeStep dt
time the current time
rCurrentYValues the current (initial) state
rNextYValues the state at the next timestep
Implements AbstractOneStepIvpOdeSolver.
Definition at line 41 of file HeunIvpOdeSolver.cpp.
References AbstractUntemplatedParameterisedSystem::GetNumberOfStateVariables().
Referenced by serialize().
serialize()
template<class Archive > void HeunIvpOdeSolver::serialize (Archive & archive, const unsigned int version) inline private
Archive the abstract IVP Solver, never used directly - boost uses this.
Parameters
archive the archive
version the current version of this class
Definition at line 61 of file HeunIvpOdeSolver.hpp.
References CalculateNextYValue().
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Needed for serialization.
Definition at line 53 of file HeunIvpOdeSolver.hpp.
The documentation for this class was generated from the following files:
ode/src/solver/HeunIvpOdeSolver.hpp
ode/src/solver/HeunIvpOdeSolver.cpp