Chaste: CellCycleModelOdeSolver< CELL_CYCLE_MODEL, BackwardEulerIvpOdeSolver > Class Template Reference
CellCycleModelOdeSolver< CELL_CYCLE_MODEL, BackwardEulerIvpOdeSolver > Class Template Reference
#include <CellCycleModelOdeSolver.hpp>
Public Member Functions
bool IsSetUp ()
void Initialise ()
void Reset ()
Public Member Functions inherited from AbstractCellCycleModelOdeSolver
AbstractCellCycleModelOdeSolver ()
virtual ~AbstractCellCycleModelOdeSolver ()
void SolveAndUpdateStateVariable (AbstractOdeSystem *pAbstractOdeSystem, double startTime, double endTime, double timeStep)
bool StoppingEventOccurred ()
double GetStoppingTime ()
void SetSizeOfOdeSystem (unsigned sizeOfOdeSystem)
unsigned GetSizeOfOdeSystem ()
void CheckForStoppingEvents ()
void SetMaxSteps (long int numSteps)
void SetTolerances (double relTol=1e-4, double absTol=1e-6)
virtual bool IsAdaptive ()
Static Public Member Functions
static boost::shared_ptr< CellCycleModelOdeSolver< CELL_CYCLE_MODEL, BackwardEulerIvpOdeSolver > > Instance ()
Private Member Functions
CellCycleModelOdeSolver ()
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Static Private Attributes
static boost::shared_ptr< CellCycleModelOdeSolver< CELL_CYCLE_MODEL, BackwardEulerIvpOdeSolver > > mpInstance
Friends
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from AbstractCellCycleModelOdeSolver
boost::shared_ptr< AbstractIvpOdeSolver > mpOdeSolver
unsigned mSizeOfOdeSystem
Detailed Description
template<class CELL_CYCLE_MODEL>
class CellCycleModelOdeSolver< CELL_CYCLE_MODEL, BackwardEulerIvpOdeSolver >
Specialization for BackwardEulerIvpOdeSolver, whose constructor requires an argument.
Definition at line 171 of file CellCycleModelOdeSolver.hpp.
Constructor & Destructor Documentation
CellCycleModelOdeSolver()
template<class CELL_CYCLE_MODEL > CellCycleModelOdeSolver< CELL_CYCLE_MODEL, BackwardEulerIvpOdeSolver >::CellCycleModelOdeSolver () private
Default constructor. Not user accessible; to obtain an instance of this class use the Instance method.
Definition at line 213 of file CellCycleModelOdeSolver.hpp.
Member Function Documentation
Initialise()
template<class CELL_CYCLE_MODEL > void CellCycleModelOdeSolver< CELL_CYCLE_MODEL, BackwardEulerIvpOdeSolver >::Initialise (void) virtual
Initialise the ODE solver.
Implements AbstractCellCycleModelOdeSolver.
Definition at line 235 of file CellCycleModelOdeSolver.hpp.
References EXCEPTION, AbstractCellCycleModelOdeSolver::mpOdeSolver, AbstractCellCycleModelOdeSolver::mSizeOfOdeSystem, and UNSIGNED_UNSET.
Instance()
template<class CELL_CYCLE_MODEL > boost::shared_ptr< CellCycleModelOdeSolver< CELL_CYCLE_MODEL, BackwardEulerIvpOdeSolver > > CellCycleModelOdeSolver< CELL_CYCLE_MODEL, BackwardEulerIvpOdeSolver >::Instance () static
Returns
a pointer to the singleton instance, creating it if necessary.
Definition at line 219 of file CellCycleModelOdeSolver.hpp.
References CellCycleModelOdeSolver< CELL_CYCLE_MODEL, ODE_SOLVER >::mpInstance.
IsSetUp()
template<class CELL_CYCLE_MODEL > bool CellCycleModelOdeSolver< CELL_CYCLE_MODEL, BackwardEulerIvpOdeSolver >::IsSetUp () virtual
Returns
whether the instance in existence and fully set up.
Implements AbstractCellCycleModelOdeSolver.
Definition at line 229 of file CellCycleModelOdeSolver.hpp.
References AbstractCellCycleModelOdeSolver::mpOdeSolver, AbstractCellCycleModelOdeSolver::mSizeOfOdeSystem, and UNSIGNED_UNSET.
Reset()
template<class CELL_CYCLE_MODEL > void CellCycleModelOdeSolver< CELL_CYCLE_MODEL, BackwardEulerIvpOdeSolver >::Reset () virtual
Reset the instance.
Implements AbstractCellCycleModelOdeSolver.
Definition at line 245 of file CellCycleModelOdeSolver.hpp.
References AbstractCellCycleModelOdeSolver::mpOdeSolver, AbstractCellCycleModelOdeSolver::mSizeOfOdeSystem, and UNSIGNED_UNSET.
serialize()
template<class CELL_CYCLE_MODEL > template<class Archive > void CellCycleModelOdeSolver< CELL_CYCLE_MODEL, BackwardEulerIvpOdeSolver >::serialize (Archive & archive, const unsigned int version) inline private
Archive the cell-cycle model, never used directly - boost uses this.
Parameters
archive the archive
version the current version of this class
Definition at line 189 of file CellCycleModelOdeSolver.hpp.
References CellCycleModelOdeSolver< CELL_CYCLE_MODEL, ODE_SOLVER >::Initialise(), CellCycleModelOdeSolver< CELL_CYCLE_MODEL, ODE_SOLVER >::Instance(), CellCycleModelOdeSolver< CELL_CYCLE_MODEL, ODE_SOLVER >::IsSetUp(), CellCycleModelOdeSolver< CELL_CYCLE_MODEL, ODE_SOLVER >::mpInstance, and CellCycleModelOdeSolver< CELL_CYCLE_MODEL, ODE_SOLVER >::Reset().
Friends And Related Function Documentation
boost::serialization::access
template<class CELL_CYCLE_MODEL > friend class boost::serialization::access friend
Needed for serialization.
Definition at line 181 of file CellCycleModelOdeSolver.hpp.
Member Data Documentation
mpInstance
template<class CELL_CYCLE_MODEL > boost::shared_ptr< CellCycleModelOdeSolver< CELL_CYCLE_MODEL, BackwardEulerIvpOdeSolver > > CellCycleModelOdeSolver< CELL_CYCLE_MODEL, BackwardEulerIvpOdeSolver >::mpInstance static private
The single instance of this class, for this ODE_SOLVER.
Definition at line 175 of file CellCycleModelOdeSolver.hpp.
The documentation for this class was generated from the following file:
cell_based/src/cell/cycle/CellCycleModelOdeSolver.hpp