Chaste: CryptShovingCaBasedDivisionRule Class Reference
CryptShovingCaBasedDivisionRule Class Reference
#include <CryptShovingCaBasedDivisionRule.hpp>
Public Member Functions
CryptShovingCaBasedDivisionRule ()
virtual ~CryptShovingCaBasedDivisionRule ()
bool IsNodeOnBase (unsigned NodeIndex, PottsMesh< 2 > *pPottsMesh)
virtual bool IsRoomToDivide (CellPtr pParentCell, CaBasedCellPopulation< 2 > &rCellPopulation)
virtual unsigned CalculateDaughterNodeIndex (CellPtr pNewCell, CellPtr pParentCell, CaBasedCellPopulation< 2 > &rCellPopulation)
Public Member Functions inherited from AbstractCaBasedDivisionRule< 2 >
AbstractCaBasedDivisionRule ()
virtual ~AbstractCaBasedDivisionRule ()
virtual bool IsRoomToDivide (CellPtr pParentCell, CaBasedCellPopulation< SPACE_DIM > &rCellPopulation)=0
virtual unsigned CalculateDaughterNodeIndex (CellPtr pNewCell, CellPtr pParentCell, CaBasedCellPopulation< SPACE_DIM > &rCellPopulation)=0
void OutputCellCaBasedDivisionRuleInfo (out_stream &rParamsFile)
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Friends
class boost::serialization::access
Additional Inherited Members
Protected Member Functions inherited from AbstractCaBasedDivisionRule< 2 >
virtual void OutputCellCaBasedDivisionRuleParameters (out_stream &rParamsFile)
Detailed Description
A division rule for CA-based cell populations to say how cells divide. Here they can divide in a 'north-east' or 'west' direction, as in model 3 of the following paper:
Loeffler et al (1986). Intestinal cell proliferation. I. A comprehensive model of steady‐state proliferation in the crypt. Cell Proliferation 19(6):627-645.
Definition at line 57 of file CryptShovingCaBasedDivisionRule.hpp.
Constructor & Destructor Documentation
CryptShovingCaBasedDivisionRule()
CryptShovingCaBasedDivisionRule::CryptShovingCaBasedDivisionRule () inline
Default constructor.
Definition at line 79 of file CryptShovingCaBasedDivisionRule.hpp.
~CryptShovingCaBasedDivisionRule()
virtual CryptShovingCaBasedDivisionRule::~CryptShovingCaBasedDivisionRule () inline virtual
Empty destructor.
Definition at line 84 of file CryptShovingCaBasedDivisionRule.hpp.
References CalculateDaughterNodeIndex(), CHASTE_CLASS_EXPORT, IsNodeOnBase(), and IsRoomToDivide().
Member Function Documentation
CalculateDaughterNodeIndex()
unsigned CryptShovingCaBasedDivisionRule::CalculateDaughterNodeIndex (CellPtr pNewCell, CellPtr pParentCell, CaBasedCellPopulation< 2 > & rCellPopulation) virtual
Return the index for the Daughter node. This method can be used to move cells out of the way as necessary.
Here cells divide East North or west and move the occupying cells North.
Parameters
pNewCell The cell to new cell
pParentCell The parent cell
rCellPopulation The CA-based cell population
Returns
the node index for the daughter cell.
Definition at line 74 of file CryptShovingCaBasedDivisionRule.cpp.
References AbstractCellPopulation< DIM >::GetLocationIndexUsingCell(), PottsMesh< DIM >::GetVonNeumannNeighbouringNodeIndices(), RandomNumberGenerator::Instance(), IsNodeOnBase(), RandomNumberGenerator::randMod(), and CaBasedCellPopulation< DIM >::rGetMesh().
Referenced by ~CryptShovingCaBasedDivisionRule().
IsNodeOnBase()
bool CryptShovingCaBasedDivisionRule::IsNodeOnBase (unsigned NodeIndex, PottsMesh< 2 > * pPottsMesh)
Helper method to see if cells are on the base of the crypt or not Also throws exception if cells reach the top boundary of the crypt.
Parameters
NodeIndex The node of interest
pPottsMesh The mesh containing the nodes
Returns
if the site is available.
Definition at line 40 of file CryptShovingCaBasedDivisionRule.cpp.
References EXCEPTION, PottsMesh< DIM >::GetVonNeumannNeighbouringNodeIndices(), and NEVER_REACHED.
Referenced by CalculateDaughterNodeIndex(), and ~CryptShovingCaBasedDivisionRule().
IsRoomToDivide()
bool CryptShovingCaBasedDivisionRule::IsRoomToDivide (CellPtr pParentCell, CaBasedCellPopulation< 2 > & rCellPopulation) virtual
Return whether there is room to divide at all.
Parameters
pParentCell The cell to divide
rCellPopulation The CA-based cell population
Returns
if the site is available.
Definition at line 69 of file CryptShovingCaBasedDivisionRule.cpp.
Referenced by ~CryptShovingCaBasedDivisionRule().
serialize()
template<class Archive > void CryptShovingCaBasedDivisionRule::serialize (Archive & archive, const unsigned int version) inline private
Serialize the object and its member variables.
Parameters
archive the archive
version the current version of this class
Definition at line 69 of file CryptShovingCaBasedDivisionRule.hpp.
The documentation for this class was generated from the following files:
crypt/src/division_rules/CryptShovingCaBasedDivisionRule.hpp
crypt/src/division_rules/CryptShovingCaBasedDivisionRule.cpp