Chaste: CellBasedSimulationArchiver< ELEMENT_DIM, SIM, SPACE_DIM > Class Template Reference
CellBasedSimulationArchiver< ELEMENT_DIM, SIM, SPACE_DIM > Class Template Reference
#include <CellBasedSimulationArchiver.hpp>
Static Public Member Functions
static SIM * Load (const std::string &rArchiveDirectory, const double &rTimeStamp)
static void Save (SIM *pSim)
Detailed Description
template<unsigned ELEMENT_DIM, class SIM, unsigned SPACE_DIM = ELEMENT_DIM>
class CellBasedSimulationArchiver< ELEMENT_DIM, SIM, SPACE_DIM >
CellBasedSimulationArchiver handles the checkpointing (saving and loading) of all the various AbstractCellBasedSimulation objects. It has no explicit constructor (just uses a default one) and no member variables.
Definition at line 59 of file CellBasedSimulationArchiver.hpp.
Member Function Documentation
Load()
template<unsigned ELEMENT_DIM, class SIM , unsigned SPACE_DIM> SIM * CellBasedSimulationArchiver< ELEMENT_DIM, SIM, SPACE_DIM >::Load (const std::string & rArchiveDirectory, const double & rTimeStamp) static
Loads a saved cell-based simulation to run further.
Returns
the unarchived simulation object
Parameters
rArchiveDirectory the name of the simulation to load (specified originally by simulation.SetOutputDirectory("wherever");)
rTimeStamp the time at which to load the simulation (this must be one of the times at which simulation.Save() was called)
Find the right archive (and mesh) to load. The files are contained within the 'archive' folder in rArchiveDirectory, with the archive itself called 'cell_population_sim_at_time_`rTimeStamp`.arch'. The path to this file is returned.
The path to the mesh is stored in ArchiveLocationInfo for use by the CellPopulation de-serialization routines.
Definition at line 90 of file CellBasedSimulationArchiver.hpp.
References RelativeTo::ChasteTestOutput, ArchiveOpener< Archive, Stream >::GetCommonArchive(), and ArchiveLocationInfo::SetMeshPathname().
Save()
template<unsigned ELEMENT_DIM, class SIM , unsigned SPACE_DIM> void CellBasedSimulationArchiver< ELEMENT_DIM, SIM, SPACE_DIM >::Save (SIM * pSim) static
Saves the whole cell-based simulation for restarting later.
Puts it in the archive folder under the simulation's OutputDirectory, in the file "cell_population_sim_at_time_<SIMULATION TIME>.arch". The mesh is written to files in the same folder.
First archives simulation time (and other singletons, if used) then the simulation itself.
Parameters
pSim pointer to the simulation
Definition at line 118 of file CellBasedSimulationArchiver.hpp.
References RelativeTo::ChasteTestOutput, SimulationTime::GetTime(), SimulationTime::Instance(), SimulationTime::IsStartTimeSetUp(), and ArchiveLocationInfo::SetMeshFilename().
The documentation for this class was generated from the following file:
cell_based/src/simulation/CellBasedSimulationArchiver.hpp