Chaste: VolumeConstraintPottsUpdateRule< DIM > Class Template Reference
VolumeConstraintPottsUpdateRule< DIM > Class Template Reference
#include <VolumeConstraintPottsUpdateRule.hpp>
Public Member Functions
VolumeConstraintPottsUpdateRule ()
~VolumeConstraintPottsUpdateRule ()
double EvaluateHamiltonianContribution (unsigned currentNodeIndex, unsigned targetNodeIndex, PottsBasedCellPopulation< DIM > &rCellPopulation)
double GetDeformationEnergyParameter ()
void SetDeformationEnergyParameter (double deformationEnergyParameter)
double GetMatureCellTargetVolume () const
void SetMatureCellTargetVolume (double matureCellTargetVolume)
void OutputUpdateRuleParameters (out_stream &rParamsFile)
Public Member Functions inherited from AbstractPottsUpdateRule< DIM >
AbstractPottsUpdateRule ()
virtual ~AbstractPottsUpdateRule ()
Public Member Functions inherited from AbstractUpdateRule< DIM >
AbstractUpdateRule ()
virtual ~AbstractUpdateRule ()
void OutputUpdateRuleInfo (out_stream &rParamsFile)
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Private Attributes
double mDeformationEnergyParameter
double mMatureCellTargetVolume
Friends
class TestPottsUpdateRules
class boost::serialization::access
Detailed Description
template<unsigned DIM>
class VolumeConstraintPottsUpdateRule< DIM >
A volume constraint update rule class for use in Potts based simulations.
Note this currently assumes cells don't grow, i.e the target volume is constant for each cell over time.
Definition at line 52 of file VolumeConstraintPottsUpdateRule.hpp.
Constructor & Destructor Documentation
VolumeConstraintPottsUpdateRule()
template<unsigned DIM> VolumeConstraintPottsUpdateRule< DIM >::VolumeConstraintPottsUpdateRule ()
Constructor.
Todo:
Default values don't apply in 3D.
Definition at line 39 of file VolumeConstraintPottsUpdateRule.cpp.
Referenced by VolumeConstraintPottsUpdateRule< DIM >::serialize().
~VolumeConstraintPottsUpdateRule()
template<unsigned DIM> VolumeConstraintPottsUpdateRule< DIM >::~VolumeConstraintPottsUpdateRule ()
Destructor.
Definition at line 48 of file VolumeConstraintPottsUpdateRule.cpp.
Referenced by VolumeConstraintPottsUpdateRule< DIM >::serialize().
Member Function Documentation
EvaluateHamiltonianContribution()
template<unsigned DIM> double VolumeConstraintPottsUpdateRule< DIM >::EvaluateHamiltonianContribution (unsigned currentNodeIndex, unsigned targetNodeIndex, PottsBasedCellPopulation< DIM > & rCellPopulation) virtual
Overridden EvaluateHamiltonianContribution() method
Uses sum_elements alpha (V_i - V_i^T)^2.
Parameters
currentNodeIndex The index of the current node/lattice site
targetNodeIndex The index of the target node/lattice site
rCellPopulation The cell population
Returns
The difference in the Hamiltonian with the configuration of the target node having the same spin as the current node with the current configuration. i.e H_1-H_0
Implements AbstractPottsUpdateRule< DIM >.
Definition at line 53 of file VolumeConstraintPottsUpdateRule.cpp.
References EXCEPTION, PottsBasedCellPopulation< DIM >::GetNode(), VolumeConstraintPottsUpdateRule< DIM >::mDeformationEnergyParameter, VolumeConstraintPottsUpdateRule< DIM >::mMatureCellTargetVolume, and PottsBasedCellPopulation< DIM >::rGetMesh().
Referenced by VolumeConstraintPottsUpdateRule< DIM >::serialize().
GetDeformationEnergyParameter()
template<unsigned DIM> double VolumeConstraintPottsUpdateRule< DIM >::GetDeformationEnergyParameter ()
Returns
mDeformationEnergyParameter
Definition at line 102 of file VolumeConstraintPottsUpdateRule.cpp.
References VolumeConstraintPottsUpdateRule< DIM >::mDeformationEnergyParameter.
Referenced by VolumeConstraintPottsUpdateRule< DIM >::serialize().
GetMatureCellTargetVolume()
template<unsigned DIM> double VolumeConstraintPottsUpdateRule< DIM >::GetMatureCellTargetVolume () const
Returns
mMatureCellTargetVolume
Definition at line 114 of file VolumeConstraintPottsUpdateRule.cpp.
References VolumeConstraintPottsUpdateRule< DIM >::mMatureCellTargetVolume.
Referenced by VolumeConstraintPottsUpdateRule< DIM >::serialize().
OutputUpdateRuleParameters()
template<unsigned DIM> void VolumeConstraintPottsUpdateRule< DIM >::OutputUpdateRuleParameters (out_stream & rParamsFile) virtual
Overridden OutputUpdateRuleParameters() method.
Parameters
rParamsFile the file stream to which the parameters are output
Reimplemented from AbstractPottsUpdateRule< DIM >.
Definition at line 127 of file VolumeConstraintPottsUpdateRule.cpp.
References EXPORT_TEMPLATE_CLASS_SAME_DIMS, VolumeConstraintPottsUpdateRule< DIM >::mDeformationEnergyParameter, VolumeConstraintPottsUpdateRule< DIM >::mMatureCellTargetVolume, and AbstractPottsUpdateRule< DIM >::OutputUpdateRuleParameters().
Referenced by VolumeConstraintPottsUpdateRule< DIM >::serialize().
serialize()
template<unsigned DIM> template<class Archive > void VolumeConstraintPottsUpdateRule< DIM >::serialize (Archive & archive, const unsigned int version) inline private
Boost Serialization method for archiving/checkpointing. Archives the object and its member variables.
Parameters
archive The boost archive.
version The current version of this class.
Definition at line 81 of file VolumeConstraintPottsUpdateRule.hpp.
References VolumeConstraintPottsUpdateRule< DIM >::EvaluateHamiltonianContribution(), EXPORT_TEMPLATE_CLASS_SAME_DIMS, VolumeConstraintPottsUpdateRule< DIM >::GetDeformationEnergyParameter(), VolumeConstraintPottsUpdateRule< DIM >::GetMatureCellTargetVolume(), VolumeConstraintPottsUpdateRule< DIM >::mDeformationEnergyParameter, VolumeConstraintPottsUpdateRule< DIM >::mMatureCellTargetVolume, VolumeConstraintPottsUpdateRule< DIM >::OutputUpdateRuleParameters(), VolumeConstraintPottsUpdateRule< DIM >::SetDeformationEnergyParameter(), VolumeConstraintPottsUpdateRule< DIM >::SetMatureCellTargetVolume(), VolumeConstraintPottsUpdateRule< DIM >::VolumeConstraintPottsUpdateRule(), and VolumeConstraintPottsUpdateRule< DIM >::~VolumeConstraintPottsUpdateRule().
SetDeformationEnergyParameter()
template<unsigned DIM> void VolumeConstraintPottsUpdateRule< DIM >::SetDeformationEnergyParameter (double deformationEnergyParameter)
Set mDeformationEnergyParameter.
Parameters
deformationEnergyParameter the new value of mDeformationEnergyParameter
Definition at line 108 of file VolumeConstraintPottsUpdateRule.cpp.
References VolumeConstraintPottsUpdateRule< DIM >::mDeformationEnergyParameter.
Referenced by VolumeConstraintPottsUpdateRule< DIM >::serialize().
SetMatureCellTargetVolume()
template<unsigned DIM> void VolumeConstraintPottsUpdateRule< DIM >::SetMatureCellTargetVolume (double matureCellTargetVolume)
Set mMatureCellTargetVolume.
Parameters
matureCellTargetVolume the new value of mMatureCellTargetVolume
Definition at line 120 of file VolumeConstraintPottsUpdateRule.cpp.
References VolumeConstraintPottsUpdateRule< DIM >::mMatureCellTargetVolume.
Referenced by VolumeConstraintPottsUpdateRule< DIM >::serialize().
Member Data Documentation
mDeformationEnergyParameter
template<unsigned DIM> double VolumeConstraintPottsUpdateRule< DIM >::mDeformationEnergyParameter private
Cell deformation energy parameter. Set to the default value 0.5 in the constructor.
Todo:
provide units
Definition at line 63 of file VolumeConstraintPottsUpdateRule.hpp.
Referenced by VolumeConstraintPottsUpdateRule< DIM >::EvaluateHamiltonianContribution(), VolumeConstraintPottsUpdateRule< DIM >::GetDeformationEnergyParameter(), VolumeConstraintPottsUpdateRule< DIM >::OutputUpdateRuleParameters(), VolumeConstraintPottsUpdateRule< DIM >::serialize(), and VolumeConstraintPottsUpdateRule< DIM >::SetDeformationEnergyParameter().
mMatureCellTargetVolume
template<unsigned DIM> double VolumeConstraintPottsUpdateRule< DIM >::mMatureCellTargetVolume private
Non-dimensional target volume of a mature (fully-grown) cell, given in number of lattice sites. Set to the default value 16 in the constructor.
Definition at line 70 of file VolumeConstraintPottsUpdateRule.hpp.
Referenced by VolumeConstraintPottsUpdateRule< DIM >::EvaluateHamiltonianContribution(), VolumeConstraintPottsUpdateRule< DIM >::GetMatureCellTargetVolume(), VolumeConstraintPottsUpdateRule< DIM >::OutputUpdateRuleParameters(), VolumeConstraintPottsUpdateRule< DIM >::serialize(), and VolumeConstraintPottsUpdateRule< DIM >::SetMatureCellTargetVolume().
The documentation for this class was generated from the following files:
cell_based/src/population/update_rules/VolumeConstraintPottsUpdateRule.hpp
cell_based/src/population/update_rules/VolumeConstraintPottsUpdateRule.cpp