Chaste: CellMutationStatesWriter< ELEMENT_DIM, SPACE_DIM > Class Template Reference
CellMutationStatesWriter< ELEMENT_DIM, SPACE_DIM > Class Template Reference
#include <CellMutationStatesWriter.hpp>
Public Member Functions
CellMutationStatesWriter ()
double GetCellDataForVtkOutput (CellPtr pCell, AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM > *pCellPopulation)
virtual void VisitCell (CellPtr pCell, AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM > *pCellPopulation)
Public Member Functions inherited from AbstractCellWriter< ELEMENT_DIM, SPACE_DIM >
AbstractCellWriter (const std::string &rFileName)
virtual c_vector< double, SPACE_DIM > GetVectorCellDataForVtkOutput (CellPtr pCell, AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM > *pCellPopulation)
bool GetOutputScalarData ()
bool GetOutputVectorData ()
void SetVtkCellDataName (std::string vtkCellDataName)
void SetVtkVectorCellDataName (std::string vtkCellDataName)
std::string GetVtkCellDataName ()
std::string GetVtkVectorCellDataName ()
Public Member Functions inherited from AbstractCellBasedWriter< ELEMENT_DIM, SPACE_DIM >
AbstractCellBasedWriter (const std::string &rFileName)
virtual ~AbstractCellBasedWriter ()
void CloseFile ()
virtual void OpenOutputFile (OutputFileHandler &rOutputFileHandler)
void OpenOutputFileForAppend (OutputFileHandler &rOutputFileHandler)
virtual void WriteTimeStamp ()
virtual void WriteNewline ()
void SetFileName (std::string fileName)
std::string GetFileName ()
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Friends
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from AbstractCellWriter< ELEMENT_DIM, SPACE_DIM >
bool mOutputScalarData
bool mOutputVectorData
std::string mVtkCellDataName
std::string mVtkVectorCellDataName
Protected Attributes inherited from AbstractCellBasedWriter< ELEMENT_DIM, SPACE_DIM >
std::string mFileName
out_stream mpOutStream
Detailed Description
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM>
class CellMutationStatesWriter< ELEMENT_DIM, SPACE_DIM >
A class written using the visitor pattern for writing cell mutation states to file.
The output file is called results.vizmutationstates by default. If VTK is switched on, then the writer also specifies the VTK output for each cell, which is stored in the VTK cell data "Mutation states" by default.
Definition at line 51 of file CellMutationStatesWriter.hpp.
Constructor & Destructor Documentation
CellMutationStatesWriter()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> CellMutationStatesWriter< ELEMENT_DIM, SPACE_DIM >::CellMutationStatesWriter ()
Default constructor.
Definition at line 42 of file CellMutationStatesWriter.cpp.
References AbstractCellWriter< ELEMENT_DIM, SPACE_DIM >::mVtkCellDataName.
Referenced by CellMutationStatesWriter< ELEMENT_DIM, SPACE_DIM >::serialize().
Member Function Documentation
GetCellDataForVtkOutput()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> double CellMutationStatesWriter< ELEMENT_DIM, SPACE_DIM >::GetCellDataForVtkOutput (CellPtr pCell, AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM > * pCellPopulation) virtual
Get a double associated with a cell. This method reduces duplication of code between the methods VisitCell() and AddVtkData().
By default this method returns a DOUBLE_UNSET, but it may be overridden in subclasses
Parameters
pCell a cell
pCellPopulation a pointer to the cell population owning the cell.
Returns
data associated with the cell
Reimplemented from AbstractCellWriter< ELEMENT_DIM, SPACE_DIM >.
Definition at line 49 of file CellMutationStatesWriter.cpp.
References CellPropertyCollection::GetProperties(), CellPropertyCollection::GetProperty(), and CellPropertyCollection::GetSize().
Referenced by CellMutationStatesWriter< ELEMENT_DIM, SPACE_DIM >::serialize().
serialize()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> template<class Archive > void CellMutationStatesWriter< ELEMENT_DIM, SPACE_DIM >::serialize (Archive & archive, const unsigned int version) inline private
Serialize the object and its member variables.
Parameters
archive the archive
version the current version of this class
Definition at line 63 of file CellMutationStatesWriter.hpp.
References CellMutationStatesWriter< ELEMENT_DIM, SPACE_DIM >::CellMutationStatesWriter(), EXPORT_TEMPLATE_CLASS_ALL_DIMS, CellMutationStatesWriter< ELEMENT_DIM, SPACE_DIM >::GetCellDataForVtkOutput(), and CellMutationStatesWriter< ELEMENT_DIM, SPACE_DIM >::VisitCell().
VisitCell()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void CellMutationStatesWriter< ELEMENT_DIM, SPACE_DIM >::VisitCell (CellPtr pCell, AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM > * pCellPopulation) virtual
Overridden VisitCell() method.
Visit a cell and write its mutation state, as given by this property's member mColour.
Outputs a line of space-separated values of the form: ...[cell mutation state] ...
This is appended to the output written by AbstractCellBasedWriter, which is a single value [present simulation time], followed by a tab.
Parameters
pCell a cell
pCellPopulation a pointer to the cell population owning the cell
Todo:
split these all off as cell label not mutation states (see #2534)
Implements AbstractCellWriter< ELEMENT_DIM, SPACE_DIM >.
Definition at line 66 of file CellMutationStatesWriter.cpp.
References EXPORT_TEMPLATE_CLASS_ALL_DIMS, CellPropertyCollection::GetProperties(), CellPropertyCollection::GetProperty(), CellPropertyCollection::GetSize(), and AbstractCellBasedWriter< ELEMENT_DIM, SPACE_DIM >::mpOutStream.
Referenced by CellMutationStatesWriter< ELEMENT_DIM, SPACE_DIM >::serialize().
Friends And Related Function Documentation
boost::serialization::access
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> friend class boost::serialization::access friend
Needed for serialization.
Definition at line 55 of file CellMutationStatesWriter.hpp.
The documentation for this class was generated from the following files:
cell_based/src/writers/cell_writers/CellMutationStatesWriter.hpp
cell_based/src/writers/cell_writers/CellMutationStatesWriter.cpp