Chaste: FixedG1GenerationalCellCycleModel Class Reference
FixedG1GenerationalCellCycleModel Class Reference
#include <FixedG1GenerationalCellCycleModel.hpp>
Public Member Functions
FixedG1GenerationalCellCycleModel ()
AbstractCellCycleModel * CreateCellCycleModel ()
virtual void OutputCellCycleModelParameters (out_stream &rParamsFile)
Public Member Functions inherited from AbstractSimpleGenerationalCellCycleModel
AbstractSimpleGenerationalCellCycleModel ()
virtual ~AbstractSimpleGenerationalCellCycleModel ()
void ResetForDivision ()
void InitialiseDaughterCell ()
void SetGeneration (unsigned generation)
unsigned GetGeneration () const
void SetMaxTransitGenerations (unsigned maxTransitGenerations)
unsigned GetMaxTransitGenerations () const
Public Member Functions inherited from AbstractSimplePhaseBasedCellCycleModel
AbstractSimplePhaseBasedCellCycleModel ()
virtual ~AbstractSimplePhaseBasedCellCycleModel ()
virtual void UpdateCellCyclePhase ()
void InitialiseDaughterCell ()
virtual void Initialise ()
Public Member Functions inherited from AbstractPhaseBasedCellCycleModel
AbstractPhaseBasedCellCycleModel ()
virtual ~AbstractPhaseBasedCellCycleModel ()
virtual bool ReadyToDivide ()
CellCyclePhase GetCurrentCellCyclePhase () const
virtual double GetG1Duration () const
double GetStemCellG1Duration () const
double GetTransitCellG1Duration () const
double GetSG2MDuration () const
virtual double GetSDuration () const
virtual double GetG2Duration () const
virtual double GetMDuration () const
virtual void SetStemCellG1Duration (double stemCellG1Duration)
virtual void SetTransitCellG1Duration (double transitCellG1Duration)
void SetSDuration (double sDuration)
void SetG2Duration (double g2Duration)
void SetMDuration (double mDuration)
virtual double GetAverageTransitCellCycleTime ()
virtual double GetAverageStemCellCycleTime ()
double GetMinimumGapDuration () const
void SetMinimumGapDuration (double minimumGapDuration)
Public Member Functions inherited from AbstractCellCycleModel
AbstractCellCycleModel ()
virtual ~AbstractCellCycleModel ()
void SetCell (CellPtr pCell)
CellPtr GetCell ()
virtual void SetBirthTime (double birthTime)
void SetDimension (unsigned dimension)
unsigned GetDimension () const
double GetBirthTime () const
double GetAge ()
virtual bool CanCellTerminallyDifferentiate ()
void OutputCellCycleModelInfo (out_stream &rParamsFile)
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Protected Member Functions
FixedG1GenerationalCellCycleModel (const FixedG1GenerationalCellCycleModel &rModel)
Protected Member Functions inherited from AbstractSimpleGenerationalCellCycleModel
AbstractSimpleGenerationalCellCycleModel (const AbstractSimpleGenerationalCellCycleModel &rModel)
Protected Member Functions inherited from AbstractSimplePhaseBasedCellCycleModel
virtual void SetG1Duration ()
AbstractSimplePhaseBasedCellCycleModel (const AbstractSimplePhaseBasedCellCycleModel &rModel)
Protected Member Functions inherited from AbstractPhaseBasedCellCycleModel
AbstractPhaseBasedCellCycleModel (const AbstractPhaseBasedCellCycleModel &rModel)
Protected Member Functions inherited from AbstractCellCycleModel
AbstractCellCycleModel (const AbstractCellCycleModel &rModel)
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Friends
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from AbstractSimpleGenerationalCellCycleModel
unsigned mGeneration
unsigned mMaxTransitGenerations
Protected Attributes inherited from AbstractPhaseBasedCellCycleModel
CellCyclePhase mCurrentCellCyclePhase
double mG1Duration
double mMinimumGapDuration
double mStemCellG1Duration
double mTransitCellG1Duration
double mSDuration
double mG2Duration
double mMDuration
Protected Attributes inherited from AbstractCellCycleModel
CellPtr mpCell
double mBirthTime
bool mReadyToDivide
unsigned mDimension
Detailed Description
Fixed cell-cycle model.
Cell cycle time is deterministic for stem and transit cells (with values StemCellG1Duration + SG2MDuration and TransitCellG1Duration + SG2MDuration (values found in AbstractCellCycleModel))
Definition at line 48 of file FixedG1GenerationalCellCycleModel.hpp.
Constructor & Destructor Documentation
FixedG1GenerationalCellCycleModel() [1/2]
FixedG1GenerationalCellCycleModel::FixedG1GenerationalCellCycleModel (const FixedG1GenerationalCellCycleModel & rModel) protected
Protected copy-constructor for use by CreateCellCycleModel. The only way for external code to create a copy of a cell cycle model is by calling that method, to ensure that a model of the correct subclass is created. This copy-constructor helps subclasses to ensure that all member variables are correctly copied when this happens.
This method is called by child classes to set member variables for a daughter cell upon cell division. Note that the parent cell cycle model will have had ResetForDivision() called just before CreateCellCycleModel() is called, so performing an exact copy of the parent is suitable behaviour. Any daughter-cell-specific initialisation can be done in InitialiseDaughterCell().
Parameters
rModel the cell cycle model to copy.
Definition at line 42 of file FixedG1GenerationalCellCycleModel.cpp.
FixedG1GenerationalCellCycleModel() [2/2]
FixedG1GenerationalCellCycleModel::FixedG1GenerationalCellCycleModel ()
Default constructor. Note that mBirthTime is set in AbstractCellCycleModel() and mG1Duration is set in AbstractSimplePhaseBasedCellCycleModel().
Definition at line 38 of file FixedG1GenerationalCellCycleModel.cpp.
Referenced by CreateCellCycleModel(), and serialize().
Member Function Documentation
CreateCellCycleModel()
AbstractCellCycleModel * FixedG1GenerationalCellCycleModel::CreateCellCycleModel () virtual
Overridden builder method to create new copies of this cell-cycle model.
Returns
new cell-cycle model
Implements AbstractCellCycleModel.
Definition at line 59 of file FixedG1GenerationalCellCycleModel.cpp.
References FixedG1GenerationalCellCycleModel().
Referenced by serialize().
OutputCellCycleModelParameters()
void FixedG1GenerationalCellCycleModel::OutputCellCycleModelParameters (out_stream & rParamsFile) virtual
Overridden OutputCellCycleModelParameters() method.
Parameters
rParamsFile the file stream to which the parameters are output
Reimplemented from AbstractSimpleGenerationalCellCycleModel.
Definition at line 64 of file FixedG1GenerationalCellCycleModel.cpp.
References CHASTE_CLASS_EXPORT, and AbstractSimpleGenerationalCellCycleModel::OutputCellCycleModelParameters().
Referenced by serialize().
serialize()
template<class Archive > void FixedG1GenerationalCellCycleModel::serialize (Archive & archive, const unsigned int version) inline private
Archive the cell-cycle model, never used directly - boost uses this.
Parameters
archive the archive
version the current version of this class
Definition at line 61 of file FixedG1GenerationalCellCycleModel.hpp.
References CHASTE_CLASS_EXPORT, CreateCellCycleModel(), FixedG1GenerationalCellCycleModel(), and OutputCellCycleModelParameters().
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Needed for serialization.
Definition at line 53 of file FixedG1GenerationalCellCycleModel.hpp.
The documentation for this class was generated from the following files:
cell_based/src/cell/cycle/FixedG1GenerationalCellCycleModel.hpp
cell_based/src/cell/cycle/FixedG1GenerationalCellCycleModel.cpp