Chaste: AbstractUpdateRule< DIM > Class Template Reference
AbstractUpdateRule< DIM > Class Template Reference abstract
#include <AbstractUpdateRule.hpp>
Public Member Functions
AbstractUpdateRule ()
virtual ~AbstractUpdateRule ()
void OutputUpdateRuleInfo (out_stream &rParamsFile)
virtual void OutputUpdateRuleParameters (out_stream &rParamsFile)=0
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Friends
class boost::serialization::access
Detailed Description
template<unsigned DIM>
class AbstractUpdateRule< DIM >
An abstract update rule class, for use in on-lattice cell-based simulations.
Definition at line 48 of file AbstractUpdateRule.hpp.
Constructor & Destructor Documentation
AbstractUpdateRule()
template<unsigned DIM> AbstractUpdateRule< DIM >::AbstractUpdateRule ()
Default constructor.
Definition at line 39 of file AbstractUpdateRule.cpp.
Referenced by AbstractUpdateRule< DIM >::serialize().
~AbstractUpdateRule()
template<unsigned DIM> AbstractUpdateRule< DIM >::~AbstractUpdateRule () virtual
Destructor.
Definition at line 44 of file AbstractUpdateRule.cpp.
Referenced by AbstractUpdateRule< DIM >::serialize().
Member Function Documentation
OutputUpdateRuleInfo()
template<unsigned DIM> void AbstractUpdateRule< DIM >::OutputUpdateRuleInfo (out_stream & rParamsFile)
Output update rule to file. Call OutputUpdateRuleParameters() to output all member variables to file.
Parameters
rParamsFile a file stream
Definition at line 49 of file AbstractUpdateRule.cpp.
Referenced by AbstractUpdateRule< DIM >::serialize().
OutputUpdateRuleParameters()
template<unsigned DIM> void AbstractUpdateRule< DIM >::OutputUpdateRuleParameters (out_stream & rParamsFile) pure virtual
Output update rule parameters to file.
As this method is pure virtual, it must be overridden in subclasses.
Parameters
rParamsFile a file stream
Implemented in DifferentialAdhesionPottsUpdateRule< DIM >, AdhesionPottsUpdateRule< DIM >, SurfaceAreaConstraintPottsUpdateRule< DIM >, VolumeConstraintPottsUpdateRule< DIM >, DiffusionCaUpdateRule< DIM >, RandomCaSwitchingUpdateRule< DIM >, AbstractCaUpdateRule< DIM >, ChemotaxisPottsUpdateRule< DIM >, AbstractPottsUpdateRule< DIM >, and AbstractCaSwitchingUpdateRule< DIM >.
Definition at line 59 of file AbstractUpdateRule.cpp.
Referenced by AbstractCaSwitchingUpdateRule< DIM >::OutputUpdateRuleParameters(), AbstractPottsUpdateRule< DIM >::OutputUpdateRuleParameters(), AbstractCaUpdateRule< DIM >::OutputUpdateRuleParameters(), and AbstractUpdateRule< DIM >::serialize().
serialize()
template<unsigned DIM> template<class Archive > void AbstractUpdateRule< DIM >::serialize (Archive & archive, const unsigned int version) inline private
Boost Serialization method for archiving/checkpointing. Archives the object and its member variables.
Parameters
archive The boost archive.
version The current version of this class.
Definition at line 60 of file AbstractUpdateRule.hpp.
References AbstractUpdateRule< DIM >::AbstractUpdateRule(), AbstractUpdateRule< DIM >::OutputUpdateRuleInfo(), AbstractUpdateRule< DIM >::OutputUpdateRuleParameters(), TEMPLATED_CLASS_IS_ABSTRACT_1_UNSIGNED, and AbstractUpdateRule< DIM >::~AbstractUpdateRule().
Friends And Related Function Documentation
boost::serialization::access
template<unsigned DIM> friend class boost::serialization::access friend
Needed for serialization.
Definition at line 51 of file AbstractUpdateRule.hpp.
The documentation for this class was generated from the following files:
cell_based/src/population/update_rules/AbstractUpdateRule.hpp
cell_based/src/population/update_rules/AbstractUpdateRule.cpp