Chaste: CellMutationStatesCountWriter< ELEMENT_DIM, SPACE_DIM > Class Template Reference
CellMutationStatesCountWriter< ELEMENT_DIM, SPACE_DIM > Class Template Reference
#include <CellMutationStatesCountWriter.hpp>
Public Member Functions
CellMutationStatesCountWriter ()
virtual void WriteHeader (AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM > *pCellPopulation)
void VisitAnyPopulation (AbstractCellPopulation< SPACE_DIM, SPACE_DIM > *pCellPopulation)
virtual void Visit (MeshBasedCellPopulation< ELEMENT_DIM, SPACE_DIM > *pCellPopulation)
virtual void Visit (CaBasedCellPopulation< SPACE_DIM > *pCellPopulation)
virtual void Visit (NodeBasedCellPopulation< SPACE_DIM > *pCellPopulation)
virtual void Visit (PottsBasedCellPopulation< SPACE_DIM > *pCellPopulation)
virtual void Visit (VertexBasedCellPopulation< SPACE_DIM > *pCellPopulation)
Public Member Functions inherited from AbstractCellPopulationCountWriter< ELEMENT_DIM, SPACE_DIM >
AbstractCellPopulationCountWriter (const std::string &rFileName)
Public Member Functions inherited from AbstractCellBasedWriter< ELEMENT_DIM, SPACE_DIM >
AbstractCellBasedWriter (const std::string &rFileName)
virtual ~AbstractCellBasedWriter ()
void CloseFile ()
virtual void OpenOutputFile (OutputFileHandler &rOutputFileHandler)
void OpenOutputFileForAppend (OutputFileHandler &rOutputFileHandler)
virtual void WriteTimeStamp ()
virtual void WriteNewline ()
void SetFileName (std::string fileName)
std::string GetFileName ()
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Friends
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from AbstractCellBasedWriter< ELEMENT_DIM, SPACE_DIM >
std::string mFileName
out_stream mpOutStream
Detailed Description
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM>
class CellMutationStatesCountWriter< ELEMENT_DIM, SPACE_DIM >
A class written using the visitor pattern for writing cell mutations states from a cell population to file.
The output file is called cellmutationstates.dat by default.
Definition at line 49 of file CellMutationStatesCountWriter.hpp.
Constructor & Destructor Documentation
CellMutationStatesCountWriter()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> CellMutationStatesCountWriter< ELEMENT_DIM, SPACE_DIM >::CellMutationStatesCountWriter ()
Default constructor.
Definition at line 46 of file CellMutationStatesCountWriter.cpp.
Referenced by CellMutationStatesCountWriter< ELEMENT_DIM, SPACE_DIM >::serialize().
Member Function Documentation
serialize()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> template<class Archive > void CellMutationStatesCountWriter< ELEMENT_DIM, SPACE_DIM >::serialize (Archive & archive, const unsigned int version) inline private
Serialize the object and its member variables.
Parameters
archive the archive
version the current version of this class
Definition at line 61 of file CellMutationStatesCountWriter.hpp.
References CellMutationStatesCountWriter< ELEMENT_DIM, SPACE_DIM >::CellMutationStatesCountWriter(), EXPORT_TEMPLATE_CLASS_ALL_DIMS, CellMutationStatesCountWriter< ELEMENT_DIM, SPACE_DIM >::Visit(), CellMutationStatesCountWriter< ELEMENT_DIM, SPACE_DIM >::VisitAnyPopulation(), and CellMutationStatesCountWriter< ELEMENT_DIM, SPACE_DIM >::WriteHeader().
Visit() [1/5]
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void CellMutationStatesCountWriter< ELEMENT_DIM, SPACE_DIM >::Visit (MeshBasedCellPopulation< ELEMENT_DIM, SPACE_DIM > * pCellPopulation) virtual
Visit the population and write the number of cells in the population that have each mutation state.
Outputs a line of tab-separated values of the form: [num mutation state 0] [num mutation state 1] [num mutation state 2] ...
where [num mutation state 0] denotes the number of cells in the population that have the mutation state with index 0 in the registry of cell properties, and so on. These counts are computed through the cell population method GetCellMutationStateCount(). The ordering of mutation states is usually specified by the cell population method SetDefaultCellMutationStateAndProliferativeTypeOrdering().
This line is appended to the output written by AbstractCellBasedWriter, which is a single value [present simulation time], followed by a tab.
Parameters
pCellPopulation a pointer to the MeshBasedCellPopulation to visit.
Implements AbstractCellPopulationCountWriter< ELEMENT_DIM, SPACE_DIM >.
Definition at line 89 of file CellMutationStatesCountWriter.cpp.
References PetscTools::AmMaster(), and AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::GetCellMutationStateCount().
Referenced by CellMutationStatesCountWriter< ELEMENT_DIM, SPACE_DIM >::serialize().
Visit() [2/5]
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void CellMutationStatesCountWriter< ELEMENT_DIM, SPACE_DIM >::Visit (CaBasedCellPopulation< SPACE_DIM > * pCellPopulation) virtual
Visit the population and write the number of cells in the population that have each mutation state.
Outputs a line of tab-separated values of the form: [num mutation state 0] [num mutation state 1] [num mutation state 2] ...
where [num mutation state 0] denotes the number of cells in the population that have the mutation state with index 0 in the registry of cell properties, and so on. These counts are computed through the cell population method GetCellMutationStateCount(). The ordering of mutation states is usually specified by the cell population method SetDefaultCellMutationStateAndProliferativeTypeOrdering().
This line is appended to the output written by AbstractCellBasedWriter, which is a single value [present simulation time], followed by a tab.
Parameters
pCellPopulation a pointer to the CaBasedCellPopulation to visit.
Implements AbstractCellPopulationCountWriter< ELEMENT_DIM, SPACE_DIM >.
Definition at line 103 of file CellMutationStatesCountWriter.cpp.
References CellMutationStatesCountWriter< ELEMENT_DIM, SPACE_DIM >::VisitAnyPopulation().
Visit() [3/5]
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void CellMutationStatesCountWriter< ELEMENT_DIM, SPACE_DIM >::Visit (NodeBasedCellPopulation< SPACE_DIM > * pCellPopulation) virtual
Visit the population and write the number of cells in the population that have each mutation state.
Outputs a line of tab-separated values of the form: [num mutation state 0] [num mutation state 1] [num mutation state 2] ...
where [num mutation state 0] denotes the number of cells in the population that have the mutation state with index 0 in the registry of cell properties, and so on. These counts are computed through the cell population method GetCellMutationStateCount(). The ordering of mutation states is usually specified by the cell population method SetDefaultCellMutationStateAndProliferativeTypeOrdering().
This line is appended to the output written by AbstractCellBasedWriter, which is a single value [present simulation time], followed by a tab.
Parameters
pCellPopulation a pointer to the NodeBasedCellPopulation to visit.
Implements AbstractCellPopulationCountWriter< ELEMENT_DIM, SPACE_DIM >.
Definition at line 109 of file CellMutationStatesCountWriter.cpp.
References CellMutationStatesCountWriter< ELEMENT_DIM, SPACE_DIM >::VisitAnyPopulation().
Visit() [4/5]
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void CellMutationStatesCountWriter< ELEMENT_DIM, SPACE_DIM >::Visit (PottsBasedCellPopulation< SPACE_DIM > * pCellPopulation) virtual
Visit the population and write the number of cells in the population that have each mutation state.
Outputs a line of tab-separated values of the form: [num mutation state 0] [num mutation state 1] [num mutation state 2] ...
where [num mutation state 0] denotes the number of cells in the population that have the mutation state with index 0 in the registry of cell properties, and so on. These counts are computed through the cell population method GetCellMutationStateCount(). The ordering of mutation states is usually specified by the cell population method SetDefaultCellMutationStateAndProliferativeTypeOrdering().
This line is appended to the output written by AbstractCellBasedWriter, which is a single value [present simulation time], followed by a tab.
Parameters
pCellPopulation a pointer to the PottsBasedCellPopulation to visit.
Implements AbstractCellPopulationCountWriter< ELEMENT_DIM, SPACE_DIM >.
Definition at line 115 of file CellMutationStatesCountWriter.cpp.
References CellMutationStatesCountWriter< ELEMENT_DIM, SPACE_DIM >::VisitAnyPopulation().
Visit() [5/5]
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void CellMutationStatesCountWriter< ELEMENT_DIM, SPACE_DIM >::Visit (VertexBasedCellPopulation< SPACE_DIM > * pCellPopulation) virtual
Visit the population and write the number of cells in the population that have each mutation state.
Outputs a line of tab-separated values of the form: [num mutation state 0] [num mutation state 1] [num mutation state 2] ...
where [num mutation state 0] denotes the number of cells in the population that have the mutation state with index 0 in the registry of cell properties, and so on. These counts are computed through the cell population method GetCellMutationStateCount(). The ordering of mutation states is usually specified by the cell population method SetDefaultCellMutationStateAndProliferativeTypeOrdering().
This line is appended to the output written by AbstractCellBasedWriter, which is a single value [present simulation time], followed by a tab.
Parameters
pCellPopulation a pointer to the VertexBasedCellPopulation to visit.
Implements AbstractCellPopulationCountWriter< ELEMENT_DIM, SPACE_DIM >.
Definition at line 121 of file CellMutationStatesCountWriter.cpp.
References EXPORT_TEMPLATE_CLASS_ALL_DIMS, and CellMutationStatesCountWriter< ELEMENT_DIM, SPACE_DIM >::VisitAnyPopulation().
VisitAnyPopulation()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void CellMutationStatesCountWriter< ELEMENT_DIM, SPACE_DIM >::VisitAnyPopulation (AbstractCellPopulation< SPACE_DIM, SPACE_DIM > * pCellPopulation)
A general method for writing to any population.
Parameters
pCellPopulation the population to write
Definition at line 75 of file CellMutationStatesCountWriter.cpp.
References PetscTools::AmMaster(), and AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::GetCellMutationStateCount().
Referenced by CellMutationStatesCountWriter< ELEMENT_DIM, SPACE_DIM >::serialize(), and CellMutationStatesCountWriter< ELEMENT_DIM, SPACE_DIM >::Visit().
WriteHeader()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void CellMutationStatesCountWriter< ELEMENT_DIM, SPACE_DIM >::WriteHeader (AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM > * pCellPopulation) virtual
Overridden WriteHeader() method.
Write the header to file.
Parameters
pCellPopulation a pointer to the population to be written.
Reimplemented from AbstractCellPopulationCountWriter< ELEMENT_DIM, SPACE_DIM >.
Definition at line 52 of file CellMutationStatesCountWriter.cpp.
References PetscTools::AmMaster(), AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::GetCellPropertyRegistry(), AbstractCellBasedWriter< ELEMENT_DIM, SPACE_DIM >::mpOutStream, and AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::SetDefaultCellMutationStateAndProliferativeTypeOrdering().
Referenced by CellMutationStatesCountWriter< ELEMENT_DIM, SPACE_DIM >::serialize().
Friends And Related Function Documentation
boost::serialization::access
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> friend class boost::serialization::access friend
Needed for serialization.
Definition at line 53 of file CellMutationStatesCountWriter.hpp.
The documentation for this class was generated from the following files:
cell_based/src/writers/population_count_writers/CellMutationStatesCountWriter.hpp
cell_based/src/writers/population_count_writers/CellMutationStatesCountWriter.cpp