Chaste: StreeterFibreGenerator< SPACE_DIM > Class Template Reference
StreeterFibreGenerator< SPACE_DIM > Class Template Reference
#include <StreeterFibreGenerator.hpp>
Public Member Functions
StreeterFibreGenerator (AbstractTetrahedralMesh< SPACE_DIM, SPACE_DIM > &rMesh)
~StreeterFibreGenerator ()
void SetSurfaceFiles (const std::string &rEpicardiumFile, const std::string &rRightVentricleFile, const std::string &rLeftVentricleFile, bool indexFromZero)
void SetApexToBase (const c_vector< double, SPACE_DIM > &apexToBase)
void SetApexToBase (unsigned axis)
void SetLogInfo (bool logInfo=true)
Public Member Functions inherited from AbstractPerElementWriter< SPACE_DIM, SPACE_DIM, SPACE_DIM *SPACE_DIM >
AbstractPerElementWriter (AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM > *pMesh)
void WriteData (OutputFileHandler &rHandler, const std::string &rFileName)
void SetWriteFileAsBinary (bool binary=true)
virtual ~AbstractPerElementWriter ()
Protected Member Functions
void Visit (Element< SPACE_DIM, SPACE_DIM > *pElement, unsigned localElementIndex, c_vector< double, SPACE_DIM *SPACE_DIM > &rData)
void WriteHeaderOnMaster ()
void PreWriteCalculations (OutputFileHandler &rOutputDirectory)
Protected Member Functions inherited from AbstractPerElementWriter< SPACE_DIM, SPACE_DIM, SPACE_DIM *SPACE_DIM >
virtual void Visit (Element< ELEMENT_DIM, SPACE_DIM > *pElement, unsigned localElementIndex, c_vector< double, DATA_SIZE > &rData)=0
virtual void WriteElementOnMaster (const c_vector< double, DATA_SIZE > &rData)
Private Member Functions
double GetAveragedThicknessLocalNode (const unsigned nodeIndex, const std::vector< double > &wallThickness) const
double GetFibreMaxAngle (const c_vector< HeartRegionType, SPACE_DIM+1 > &nodesRegionsForElement) const
Private Attributes
HeartGeometryInformation< SPACE_DIM > * mpGeometryInfo
c_vector< double, SPACE_DIM > mApexToBase
std::vector< double > mWallThickness
std::vector< double > mAveragedWallThickness
bool mLogInfo
Additional Inherited Members
Protected Attributes inherited from AbstractPerElementWriter< SPACE_DIM, SPACE_DIM, SPACE_DIM *SPACE_DIM >
AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM > * mpMesh
out_stream mpMasterFile
Detailed Description
template<unsigned SPACE_DIM>
class StreeterFibreGenerator< SPACE_DIM >
Generate fibre in a ventricular mesh using the description in Streeter DD, Jr, Spotnitz HM, Patel DP, Ross J, Jr, Sonnenblick EH. Fiber orientation in the canine left ventricle during diastole and systole. Circ Res. 1969 Mar;24(3):339–347.
Formulae used to generate the fibre orientations are in A Comparison of Monodomain and Bidomain Reaction-Diffusion Models for Action Potential Propagation in the Human Heart Mark Potse, Bruno Dubé, Jacques Richer, Alain Vinet, and Ramesh M. Gulrajani IEEE Trans. Biomed. Eng. 53(12):2425-2435, 2006.
Output file format: The first line indicates the number of elements. Each of the following lines contain SPACE_DIM vectors of SPACE_DIM elements for the direction of the myofibre, the transverse to it in the plane of the myocyte laminae and the normal to this laminae.
Definition at line 64 of file StreeterFibreGenerator.hpp.
Constructor & Destructor Documentation
StreeterFibreGenerator()
template<unsigned SPACE_DIM> StreeterFibreGenerator< SPACE_DIM >::StreeterFibreGenerator (AbstractTetrahedralMesh< SPACE_DIM, SPACE_DIM > & rMesh)
Constructor
Parameters
rMesh Reference to the tetrahedral mesh of the ventricles.
Definition at line 149 of file StreeterFibreGenerator.cpp.
References AbstractMesh< ELEMENT_DIM, SPACE_DIM >::GetNumNodes(), StreeterFibreGenerator< SPACE_DIM >::mAveragedWallThickness, StreeterFibreGenerator< SPACE_DIM >::mWallThickness, and Citations::Register().
~StreeterFibreGenerator()
template<unsigned SPACE_DIM> StreeterFibreGenerator< SPACE_DIM >::~StreeterFibreGenerator ()
Destructor
Definition at line 163 of file StreeterFibreGenerator.cpp.
References StreeterFibreGenerator< SPACE_DIM >::mpGeometryInfo.
Member Function Documentation
GetAveragedThicknessLocalNode()
template<unsigned SPACE_DIM> double StreeterFibreGenerator< SPACE_DIM >::GetAveragedThicknessLocalNode (const unsigned nodeIndex, const std::vector< double > & wallThickness) const private
Compute the wall thickness of a given node based on a neighbourhood average of its thickness and of those in the forward star.
Parameters
nodeIndex The index of the node in question
wallThickness vector of thickness of all nodes in node index order
Returns
Neighbourhood average thickness (will return 0 if the node is not local to this process)
Definition at line 62 of file StreeterFibreGenerator.cpp.
References Node< SPACE_DIM >::ContainingElementsBegin(), Node< SPACE_DIM >::ContainingElementsEnd(), Node< SPACE_DIM >::GetIndex(), AbstractElement< ELEMENT_DIM, SPACE_DIM >::GetNode(), and AbstractElement< ELEMENT_DIM, SPACE_DIM >::GetNumNodes().
Referenced by StreeterFibreGenerator< SPACE_DIM >::PreWriteCalculations().
GetFibreMaxAngle()
template<unsigned SPACE_DIM> double StreeterFibreGenerator< SPACE_DIM >::GetFibreMaxAngle (const c_vector< HeartRegionType, SPACE_DIM+1 > & nodesRegionsForElement) const private
R is the maximum angle between the fibre and the v axis (heart region dependant)
Parameters
nodesRegionsForElement is a small vector containing the region tags of the element's nodes
Returns
Pi/4 (if the element is in RV), Pi/3 otherwise
Definition at line 111 of file StreeterFibreGenerator.cpp.
PreWriteCalculations()
template<unsigned SPACE_DIM> void StreeterFibreGenerator< SPACE_DIM >::PreWriteCalculations (OutputFileHandler & rOutputDirectory) protected virtual
Does calculations to generate an orthotropic fibre orientation model of the ventricular mesh provided. In particular - populates the member variables mWallThickness and mAveragedWallThickness.
Also writes these to file if SetLogInfo() has been called.
Assumes that the base-apex axis is x. Based on Streeter 1969 and Potse 2006
Parameters
rOutputDirectory Handler for output directory
Reimplemented from AbstractPerElementWriter< SPACE_DIM, SPACE_DIM, SPACE_DIM *SPACE_DIM >.
Definition at line 187 of file StreeterFibreGenerator.cpp.
References PetscTools::AmMaster(), EXCEPTION, StreeterFibreGenerator< SPACE_DIM >::GetAveragedThicknessLocalNode(), StreeterFibreGenerator< SPACE_DIM >::mApexToBase, StreeterFibreGenerator< SPACE_DIM >::mAveragedWallThickness, StreeterFibreGenerator< SPACE_DIM >::mLogInfo, StreeterFibreGenerator< SPACE_DIM >::mpGeometryInfo, AbstractPerElementWriter< SPACE_DIM, SPACE_DIM, SPACE_DIM *SPACE_DIM >::mpMesh, StreeterFibreGenerator< SPACE_DIM >::mWallThickness, NEVER_REACHED, and OutputFileHandler::OpenOutputFile().
SetApexToBase() [1/2]
template<unsigned SPACE_DIM> void StreeterFibreGenerator< SPACE_DIM >::SetApexToBase (const c_vector< double, SPACE_DIM > & apexToBase)
Set the direction from apex to base
Parameters
apexToBase is a non-zero vector. It will be stored in normalised form
Definition at line 447 of file StreeterFibreGenerator.cpp.
References EXCEPTION, and StreeterFibreGenerator< SPACE_DIM >::mApexToBase.
SetApexToBase() [2/2]
template<unsigned SPACE_DIM> void StreeterFibreGenerator< SPACE_DIM >::SetApexToBase (unsigned axis)
Set the direction from apex to base
Parameters
axis is the Cartesian axis from apex to base.
Definition at line 458 of file StreeterFibreGenerator.cpp.
SetLogInfo()
template<unsigned SPACE_DIM> void StreeterFibreGenerator< SPACE_DIM >::SetLogInfo (bool logInfo = true)
Tells the WriteData method to output extra debug info on nodes in particular regions, and wall thicknesses.
Parameters
logInfo whether or not to write log files.
Definition at line 469 of file StreeterFibreGenerator.cpp.
References StreeterFibreGenerator< SPACE_DIM >::mLogInfo.
SetSurfaceFiles()
template<unsigned SPACE_DIM> void StreeterFibreGenerator< SPACE_DIM >::SetSurfaceFiles (const std::string & rEpicardiumFile, const std::string & rRightVentricleFile, const std::string & rLeftVentricleFile, bool indexFromZero)
Uses the names of files defining the different surfaces of the mesh to construct the geometry information class File formats: list of nodes, either one per line or multiple (e.g. nodes in each boundary element on surface).
Parameters
rEpicardiumFile Epicardium surface nodes (global indices).
rRightVentricleFile Right Ventricle surface nodes (global indices).
rLeftVentricleFile Left Ventricle surface nodes (global indices).
indexFromZero Are the nodes in the original mesh file/surface files indexed from 0?
If either rRightVentricleFile or rLeftVentricleFile are the empty string, then it is assumed that this is a wedge preparation for left or right ventricle, respectively. That is, the ventricle with a non-empty string. If both are empty strings then throws exception in HeartGeometryInformation.
Definition at line 169 of file StreeterFibreGenerator.cpp.
References StreeterFibreGenerator< SPACE_DIM >::mpGeometryInfo, and AbstractPerElementWriter< SPACE_DIM, SPACE_DIM, SPACE_DIM *SPACE_DIM >::mpMesh.
Visit()
template<unsigned SPACE_DIM> void StreeterFibreGenerator< SPACE_DIM >::Visit (Element< SPACE_DIM, SPACE_DIM > * pElement, unsigned localElementIndex, c_vector< double, SPACE_DIM *SPACE_DIM > & rData) protected
Associate an element with a fibre direction.
This is only called (by abstract class) on processes which own pElement.
Parameters
pElement a locally-owned element for which to calculate or lookup some data
localElementIndex the index of pElement in the local vector.
rData the double-precision data to write to file (output from the method). Gives Fibre x 3 (space dim), sheet(3), normal(3) in one vector.
Definition at line 314 of file StreeterFibreGenerator.cpp.
References AbstractElement< ELEMENT_DIM, SPACE_DIM >::GetNode(), StreeterFibreGenerator< SPACE_DIM >::mAveragedWallThickness, StreeterFibreGenerator< SPACE_DIM >::mpGeometryInfo, and StreeterFibreGenerator< SPACE_DIM >::mWallThickness.
WriteHeaderOnMaster()
template<unsigned SPACE_DIM> void StreeterFibreGenerator< SPACE_DIM >::WriteHeaderOnMaster () protected virtual
Overridden method to write the header line.
Reimplemented from AbstractPerElementWriter< SPACE_DIM, SPACE_DIM, SPACE_DIM *SPACE_DIM >.
Definition at line 180 of file StreeterFibreGenerator.cpp.
References AbstractPerElementWriter< SPACE_DIM, SPACE_DIM, SPACE_DIM *SPACE_DIM >::mpMasterFile, and AbstractPerElementWriter< SPACE_DIM, SPACE_DIM, SPACE_DIM *SPACE_DIM >::mpMesh.
Member Data Documentation
mApexToBase
template<unsigned SPACE_DIM> c_vector<double, SPACE_DIM> StreeterFibreGenerator< SPACE_DIM >::mApexToBase private
Normalised direction from apex to base
Definition at line 69 of file StreeterFibreGenerator.hpp.
Referenced by StreeterFibreGenerator< SPACE_DIM >::PreWriteCalculations(), and StreeterFibreGenerator< SPACE_DIM >::SetApexToBase().
mAveragedWallThickness
template<unsigned SPACE_DIM> std::vector<double> StreeterFibreGenerator< SPACE_DIM >::mAveragedWallThickness private
Wall thickness at each node, smoothed by averaging over local nodes by GetAveragedThicknessLocalNode().
Definition at line 93 of file StreeterFibreGenerator.hpp.
Referenced by StreeterFibreGenerator< SPACE_DIM >::PreWriteCalculations(), StreeterFibreGenerator< SPACE_DIM >::StreeterFibreGenerator(), and StreeterFibreGenerator< SPACE_DIM >::Visit().
mLogInfo
template<unsigned SPACE_DIM> bool StreeterFibreGenerator< SPACE_DIM >::mLogInfo private
Whether to write Streeter generation log files for regions and wall thicknesses
Definition at line 96 of file StreeterFibreGenerator.hpp.
Referenced by StreeterFibreGenerator< SPACE_DIM >::PreWriteCalculations(), and StreeterFibreGenerator< SPACE_DIM >::SetLogInfo().
mpGeometryInfo
template<unsigned SPACE_DIM> HeartGeometryInformation<SPACE_DIM>* StreeterFibreGenerator< SPACE_DIM >::mpGeometryInfo private
Provides a method to calculate the relative position of a node with respect to two (or three) given surfaces
Definition at line 67 of file StreeterFibreGenerator.hpp.
Referenced by StreeterFibreGenerator< SPACE_DIM >::PreWriteCalculations(), StreeterFibreGenerator< SPACE_DIM >::SetSurfaceFiles(), StreeterFibreGenerator< SPACE_DIM >::Visit(), and StreeterFibreGenerator< SPACE_DIM >::~StreeterFibreGenerator().
mWallThickness
template<unsigned SPACE_DIM> std::vector<double> StreeterFibreGenerator< SPACE_DIM >::mWallThickness private
Wall thickness at each node in the mesh.
Definition at line 90 of file StreeterFibreGenerator.hpp.
Referenced by StreeterFibreGenerator< SPACE_DIM >::PreWriteCalculations(), StreeterFibreGenerator< SPACE_DIM >::StreeterFibreGenerator(), and StreeterFibreGenerator< SPACE_DIM >::Visit().
The documentation for this class was generated from the following files:
heart/src/problem/StreeterFibreGenerator.hpp
heart/src/problem/StreeterFibreGenerator.cpp