Chaste: AbstractCellBasedWithTimingsTestSuite Class Reference
AbstractCellBasedWithTimingsTestSuite Class Reference
#include <AbstractCellBasedWithTimingsTestSuite.hpp>
Protected Member Functions
void setUp ()
void tearDown ()
Protected Member Functions inherited from AbstractCellBasedTestSuite
void setUp ()
void tearDown ()
Detailed Description
This class provides setUp and tearDown methods that time each test, and then do all the regular singleton cleaning via AbstractCellBasedTestSuite.
Note that the subclasses of CxxTest::TestSuite need to have names that end with the characters "TestSuite", due to our hack of cxxtest (see r3168 and #593).
Definition at line 53 of file AbstractCellBasedWithTimingsTestSuite.hpp.
Member Function Documentation
setUp()
void AbstractCellBasedWithTimingsTestSuite::setUp () inline protected
Overridden setUp() method. Resets the timer and calls method on parent class.
Definition at line 59 of file AbstractCellBasedWithTimingsTestSuite.hpp.
References Timer::Reset(), and AbstractCellBasedTestSuite::setUp().
tearDown()
void AbstractCellBasedWithTimingsTestSuite::tearDown () inline protected
Overridden teardown() method. Prints the amount of time the test took, and calls method on parent class.
Definition at line 68 of file AbstractCellBasedWithTimingsTestSuite.hpp.
References Timer::Print(), and AbstractCellBasedTestSuite::tearDown().
The documentation for this class was generated from the following file:
cell_based/src/fortests/AbstractCellBasedWithTimingsTestSuite.hpp