Chaste: AbstractCellMutationState Class Reference
AbstractCellMutationState Class Reference
#include <AbstractCellMutationState.hpp>
Public Member Functions
AbstractCellMutationState (unsigned colour)
virtual ~AbstractCellMutationState ()
unsigned GetColour () const
Public Member Functions inherited from AbstractCellProperty
AbstractCellProperty ()
virtual ~AbstractCellProperty ()
template<class CLASS >
bool IsType () const
template<class BASECLASS >
bool IsSubType () const
bool IsSame (const AbstractCellProperty *pOther) const
bool IsSame (boost::shared_ptr< const AbstractCellProperty > pOther) const
void IncrementCellCount ()
void DecrementCellCount ()
unsigned GetCellCount () const
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
AbstractCellMutationState ()
Private Attributes
unsigned mColour
Friends
class boost::serialization::access
Detailed Description
Base class for cell mutation states.
Each Cell has a (shared pointer to a) mutation state instance, which will be an instance of a subclass of this class. When setting up a CellBasedSimulation, the user must specify a list of AbstractCellMutationState instances, which represent the possible mutations that can occur in the simulation (including WildTypeCellMutationState). This provides a registry of available mutation states, and cells will point to one of these objects.
The mutation state objects keep track of the number of cells in a given mutation state, as well as what colour should be used by the visualizer to display cells in each state.
Definition at line 58 of file AbstractCellMutationState.hpp.
Constructor & Destructor Documentation
AbstractCellMutationState() [1/2]
AbstractCellMutationState::AbstractCellMutationState () private
Default constructor needs to be defined for archiving, but never actually used, since subclasses call the normal constructor.
Definition at line 40 of file AbstractCellMutationState.cpp.
References NEVER_REACHED.
Referenced by serialize().
AbstractCellMutationState() [2/2]
AbstractCellMutationState::AbstractCellMutationState (unsigned colour)
Constructor.
Parameters
colour what colour cells with this mutation state should be in the visualizer
Definition at line 47 of file AbstractCellMutationState.cpp.
~AbstractCellMutationState()
AbstractCellMutationState::~AbstractCellMutationState () virtual
Virtual destructor, to make this class polymorphic.
Definition at line 53 of file AbstractCellMutationState.cpp.
Referenced by serialize().
Member Function Documentation
GetColour()
unsigned AbstractCellMutationState::GetColour () const
Returns
mColour.
Definition at line 57 of file AbstractCellMutationState.cpp.
References mColour.
Referenced by serialize().
serialize()
template<class Archive > void AbstractCellMutationState::serialize (Archive & archive, const unsigned int version) inline private
Archive the member variables.
Parameters
archive the archive
version the current version of this class
Definition at line 76 of file AbstractCellMutationState.hpp.
References AbstractCellMutationState(), GetColour(), mColour, and ~AbstractCellMutationState().
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Needed for serialization.
Definition at line 68 of file AbstractCellMutationState.hpp.
Member Data Documentation
mColour
unsigned AbstractCellMutationState::mColour private
Colour for use by visualizer.
Definition at line 65 of file AbstractCellMutationState.hpp.
Referenced by GetColour(), and serialize().
The documentation for this class was generated from the following files:
cell_based/src/cell/properties/mutations/AbstractCellMutationState.hpp
cell_based/src/cell/properties/mutations/AbstractCellMutationState.cpp