Chaste: AbstractMesh< ELEMENT_DIM, SPACE_DIM >::NodeIterator Class Reference
AbstractMesh< ELEMENT_DIM, SPACE_DIM >::NodeIterator Class Reference
#include <AbstractMesh.hpp>
Public Member Functions
Node< SPACE_DIM > & operator* ()
Node< SPACE_DIM > * operator-> ()
bool operator!= (const typename AbstractMesh< ELEMENT_DIM, SPACE_DIM >::NodeIterator &rOther)
NodeIterator & operator++ ()
NodeIterator (AbstractMesh< ELEMENT_DIM, SPACE_DIM > &rMesh, typename std::vector< Node< SPACE_DIM > *>::iterator nodeIter, bool skipDeletedNodes=true)
Private Member Functions
bool IsAtEnd ()
bool IsAllowedNode ()
Private Attributes
AbstractMesh & mrMesh
std::vector< Node< SPACE_DIM > * >::iterator mNodeIter
bool mSkipDeletedNodes
Detailed Description
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM>
class AbstractMesh< ELEMENT_DIM, SPACE_DIM >::NodeIterator
A smart iterator over the nodes in the mesh.
Definition at line 458 of file AbstractMesh.hpp.
Constructor & Destructor Documentation
NodeIterator()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> AbstractMesh< ELEMENT_DIM, SPACE_DIM >::NodeIterator::NodeIterator (AbstractMesh< ELEMENT_DIM, SPACE_DIM > & rMesh, typename std::vector< Node< SPACE_DIM > *>::iterator nodeIter, bool skipDeletedNodes = true)
Constructor for a new iterator.
This should not be called directly by user code; use the mesh methods AbstractMesh::GetNodeIteratorBegin and AbstractMesh::GetNodeIteratorEnd instead.
Parameters
rMesh the mesh to iterator over
nodeIter where to start iterating
skipDeletedNodes whether to include deleted nodes
Definition at line 576 of file AbstractMesh.hpp.
References AbstractMesh< ELEMENT_DIM, SPACE_DIM >::NodeIterator::IsAllowedNode(), AbstractMesh< ELEMENT_DIM, SPACE_DIM >::NodeIterator::mNodeIter, AbstractMesh< ELEMENT_DIM, SPACE_DIM >::mNodes, and AbstractMesh< ELEMENT_DIM, SPACE_DIM >::NodeIterator::mrMesh.
Referenced by AbstractMesh< SPACE_DIM, SPACE_DIM >::GetNodeIteratorBegin(), and AbstractMesh< SPACE_DIM, SPACE_DIM >::GetNodeIteratorEnd().
Member Function Documentation
IsAllowedNode()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> bool AbstractMesh< ELEMENT_DIM, SPACE_DIM >::NodeIterator::IsAllowedNode () inline private
Helper method to say if we're allowed to point at this node.
Returns
true if allowed
Definition at line 606 of file AbstractMesh.hpp.
References AbstractMesh< ELEMENT_DIM, SPACE_DIM >::NodeIterator::mSkipDeletedNodes.
Referenced by AbstractMesh< ELEMENT_DIM, SPACE_DIM >::NodeIterator::NodeIterator(), and AbstractMesh< ELEMENT_DIM, SPACE_DIM >::NodeIterator::operator++().
IsAtEnd()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> bool AbstractMesh< ELEMENT_DIM, SPACE_DIM >::NodeIterator::IsAtEnd () inline private
Helper method to say when we're at the end.
Returns
true if at end
Definition at line 600 of file AbstractMesh.hpp.
References AbstractMesh< ELEMENT_DIM, SPACE_DIM >::NodeIterator::mNodeIter, AbstractMesh< ELEMENT_DIM, SPACE_DIM >::mNodes, and AbstractMesh< ELEMENT_DIM, SPACE_DIM >::NodeIterator::mrMesh.
Referenced by AbstractMesh< ELEMENT_DIM, SPACE_DIM >::NodeIterator::operator*(), AbstractMesh< ELEMENT_DIM, SPACE_DIM >::NodeIterator::operator++(), and AbstractMesh< ELEMENT_DIM, SPACE_DIM >::NodeIterator::operator->().
operator!=()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> bool AbstractMesh< ELEMENT_DIM, SPACE_DIM >::NodeIterator::operator!= (const typename AbstractMesh< ELEMENT_DIM, SPACE_DIM >::NodeIterator & rOther) inline
Returns
Comparison not-equal-to.
Parameters
rOther iterator with which comparison is made
Definition at line 558 of file AbstractMesh.hpp.
References AbstractMesh< ELEMENT_DIM, SPACE_DIM >::NodeIterator::mNodeIter.
operator*()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> Node< SPACE_DIM > & AbstractMesh< ELEMENT_DIM, SPACE_DIM >::NodeIterator::operator* () inline
Dereference the iterator giving you a *reference* to the current node.
Returns
reference Make sure to use a reference for the result to avoid copying nodes unnecessarily.
Definition at line 544 of file AbstractMesh.hpp.
References AbstractMesh< ELEMENT_DIM, SPACE_DIM >::NodeIterator::IsAtEnd(), and AbstractMesh< ELEMENT_DIM, SPACE_DIM >::NodeIterator::mNodeIter.
operator++()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> AbstractMesh< ELEMENT_DIM, SPACE_DIM >::NodeIterator & AbstractMesh< ELEMENT_DIM, SPACE_DIM >::NodeIterator::operator++ () inline
Prefix increment operator.
Returns
incremented object
Definition at line 564 of file AbstractMesh.hpp.
References AbstractMesh< ELEMENT_DIM, SPACE_DIM >::NodeIterator::IsAllowedNode(), AbstractMesh< ELEMENT_DIM, SPACE_DIM >::NodeIterator::IsAtEnd(), and AbstractMesh< ELEMENT_DIM, SPACE_DIM >::NodeIterator::mNodeIter.
operator->()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> Node< SPACE_DIM > * AbstractMesh< ELEMENT_DIM, SPACE_DIM >::NodeIterator::operator-> () inline
Member access from a pointer.
Returns
pointer
Definition at line 551 of file AbstractMesh.hpp.
References AbstractMesh< ELEMENT_DIM, SPACE_DIM >::NodeIterator::IsAtEnd(), and AbstractMesh< ELEMENT_DIM, SPACE_DIM >::NodeIterator::mNodeIter.
Member Data Documentation
mNodeIter
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> std::vector<Node<SPACE_DIM> *>::iterator AbstractMesh< ELEMENT_DIM, SPACE_DIM >::NodeIterator::mNodeIter private
The actual node iterator.
Definition at line 505 of file AbstractMesh.hpp.
Referenced by AbstractMesh< ELEMENT_DIM, SPACE_DIM >::NodeIterator::IsAtEnd(), AbstractMesh< ELEMENT_DIM, SPACE_DIM >::NodeIterator::NodeIterator(), AbstractMesh< ELEMENT_DIM, SPACE_DIM >::NodeIterator::operator!=(), AbstractMesh< ELEMENT_DIM, SPACE_DIM >::NodeIterator::operator*(), AbstractMesh< ELEMENT_DIM, SPACE_DIM >::NodeIterator::operator++(), and AbstractMesh< ELEMENT_DIM, SPACE_DIM >::NodeIterator::operator->().
mrMesh
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> AbstractMesh& AbstractMesh< ELEMENT_DIM, SPACE_DIM >::NodeIterator::mrMesh private
The mesh we're iterating over.
Definition at line 502 of file AbstractMesh.hpp.
Referenced by AbstractMesh< ELEMENT_DIM, SPACE_DIM >::NodeIterator::IsAtEnd(), and AbstractMesh< ELEMENT_DIM, SPACE_DIM >::NodeIterator::NodeIterator().
mSkipDeletedNodes
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> bool AbstractMesh< ELEMENT_DIM, SPACE_DIM >::NodeIterator::mSkipDeletedNodes private
Whether to skip deleted nodes.
Definition at line 508 of file AbstractMesh.hpp.
Referenced by AbstractMesh< ELEMENT_DIM, SPACE_DIM >::NodeIterator::IsAllowedNode().
The documentation for this class was generated from the following file:
mesh/src/common/AbstractMesh.hpp