Chaste: GammaG1CellCycleModel Class Reference
GammaG1CellCycleModel Class Reference
#include <GammaG1CellCycleModel.hpp>
Public Member Functions
GammaG1CellCycleModel ()
void SetG1Duration ()
AbstractCellCycleModel * CreateCellCycleModel ()
void SetShape (double shape)
void SetScale (double scale)
double GetShape () const
double GetScale () const
virtual void OutputCellCycleModelParameters (out_stream &rParamsFile)
Public Member Functions inherited from AbstractSimplePhaseBasedCellCycleModel
AbstractSimplePhaseBasedCellCycleModel ()
virtual ~AbstractSimplePhaseBasedCellCycleModel ()
virtual void ResetForDivision ()
virtual void UpdateCellCyclePhase ()
void InitialiseDaughterCell ()
virtual void Initialise ()
Public Member Functions inherited from AbstractPhaseBasedCellCycleModel
AbstractPhaseBasedCellCycleModel ()
virtual ~AbstractPhaseBasedCellCycleModel ()
virtual bool ReadyToDivide ()
CellCyclePhase GetCurrentCellCyclePhase () const
virtual double GetG1Duration () const
double GetStemCellG1Duration () const
double GetTransitCellG1Duration () const
double GetSG2MDuration () const
virtual double GetSDuration () const
virtual double GetG2Duration () const
virtual double GetMDuration () const
virtual void SetStemCellG1Duration (double stemCellG1Duration)
virtual void SetTransitCellG1Duration (double transitCellG1Duration)
void SetSDuration (double sDuration)
void SetG2Duration (double g2Duration)
void SetMDuration (double mDuration)
virtual double GetAverageTransitCellCycleTime ()
virtual double GetAverageStemCellCycleTime ()
double GetMinimumGapDuration () const
void SetMinimumGapDuration (double minimumGapDuration)
Public Member Functions inherited from AbstractCellCycleModel
AbstractCellCycleModel ()
virtual ~AbstractCellCycleModel ()
void SetCell (CellPtr pCell)
CellPtr GetCell ()
virtual void SetBirthTime (double birthTime)
void SetDimension (unsigned dimension)
unsigned GetDimension () const
double GetBirthTime () const
double GetAge ()
virtual bool CanCellTerminallyDifferentiate ()
void OutputCellCycleModelInfo (out_stream &rParamsFile)
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Protected Member Functions
GammaG1CellCycleModel (const GammaG1CellCycleModel &rModel)
Protected Member Functions inherited from AbstractSimplePhaseBasedCellCycleModel
AbstractSimplePhaseBasedCellCycleModel (const AbstractSimplePhaseBasedCellCycleModel &rModel)
Protected Member Functions inherited from AbstractPhaseBasedCellCycleModel
AbstractPhaseBasedCellCycleModel (const AbstractPhaseBasedCellCycleModel &rModel)
Protected Member Functions inherited from AbstractCellCycleModel
AbstractCellCycleModel (const AbstractCellCycleModel &rModel)
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Private Attributes
double mShape
double mScale
Friends
class TestSimpleCellCycleModels
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from AbstractPhaseBasedCellCycleModel
CellCyclePhase mCurrentCellCyclePhase
double mG1Duration
double mMinimumGapDuration
double mStemCellG1Duration
double mTransitCellG1Duration
double mSDuration
double mG2Duration
double mMDuration
Protected Attributes inherited from AbstractCellCycleModel
CellPtr mpCell
double mBirthTime
bool mReadyToDivide
unsigned mDimension
Detailed Description
A stochastic cell-cycle model where cells keep dividing with a stochastic G1 duration drawn from a gamma distribution with specified shape and scale parameters.
Definition at line 46 of file GammaG1CellCycleModel.hpp.
Constructor & Destructor Documentation
GammaG1CellCycleModel() [1/2]
GammaG1CellCycleModel::GammaG1CellCycleModel (const GammaG1CellCycleModel & rModel) protected
Protected copy-constructor for use by CreateCellCycleModel. The only way for external code to create a copy of a cell cycle model is by calling that method, to ensure that a model of the correct subclass is created. This copy-constructor helps subclasses to ensure that all member variables are correctly copied when this happens.
This method is called by child classes to set member variables for a daughter cell upon cell division. Note that the parent cell cycle model will have had ResetForDivision() called just before CreateCellCycleModel() is called, so performing an exact copy of the parent is suitable behaviour. Any daughter-cell-specific initialisation can be done in InitialiseDaughterCell().
Parameters
rModel the cell cycle model to copy.
Definition at line 48 of file GammaG1CellCycleModel.cpp.
GammaG1CellCycleModel() [2/2]
GammaG1CellCycleModel::GammaG1CellCycleModel ()
Constructor.
Definition at line 41 of file GammaG1CellCycleModel.cpp.
Referenced by CreateCellCycleModel(), and serialize().
Member Function Documentation
CreateCellCycleModel()
AbstractCellCycleModel * GammaG1CellCycleModel::CreateCellCycleModel () virtual
Overridden builder method to create new copies of this cell-cycle model.
Returns
a pointer to the GammaG1CellCycleModel created.
Implements AbstractCellCycleModel.
Definition at line 69 of file GammaG1CellCycleModel.cpp.
References GammaG1CellCycleModel().
Referenced by serialize().
GetScale()
double GammaG1CellCycleModel::GetScale () const
Returns
mScale.
Definition at line 107 of file GammaG1CellCycleModel.cpp.
References mScale.
Referenced by serialize().
GetShape()
double GammaG1CellCycleModel::GetShape () const
Returns
mShape.
Definition at line 102 of file GammaG1CellCycleModel.cpp.
References mShape.
Referenced by serialize().
OutputCellCycleModelParameters()
void GammaG1CellCycleModel::OutputCellCycleModelParameters (out_stream & rParamsFile) virtual
Overridden OutputCellCycleModelParameters() method.
Parameters
rParamsFile the file stream to which the parameters are output
Reimplemented from AbstractSimplePhaseBasedCellCycleModel.
Definition at line 112 of file GammaG1CellCycleModel.cpp.
References CHASTE_CLASS_EXPORT, mScale, mShape, and AbstractSimplePhaseBasedCellCycleModel::OutputCellCycleModelParameters().
Referenced by serialize().
serialize()
template<class Archive > void GammaG1CellCycleModel::serialize (Archive & archive, const unsigned int version) inline private
Archive the cell-cycle model and random number generator, never used directly - boost uses this.
Parameters
archive the archive
version the current version of this class
Definition at line 67 of file GammaG1CellCycleModel.hpp.
References CHASTE_CLASS_EXPORT, CreateCellCycleModel(), GammaG1CellCycleModel(), GetScale(), SerializableSingleton< SINGLETON_CLASS >::GetSerializationWrapper(), GetShape(), RandomNumberGenerator::Instance(), mScale, mShape, OutputCellCycleModelParameters(), SetG1Duration(), SetScale(), and SetShape().
SetG1Duration()
void GammaG1CellCycleModel::SetG1Duration () virtual
Overridden SetG1Duration().
Reimplemented from AbstractSimplePhaseBasedCellCycleModel.
Definition at line 74 of file GammaG1CellCycleModel.cpp.
References RandomNumberGenerator::GammaRandomDeviate(), RandomNumberGenerator::Instance(), AbstractPhaseBasedCellCycleModel::mG1Duration, AbstractCellCycleModel::mpCell, mScale, mShape, and NEVER_REACHED.
Referenced by serialize().
SetScale()
void GammaG1CellCycleModel::SetScale (double scale)
Returns
mScale.
Parameters
scale the value of the scale parameter
Definition at line 97 of file GammaG1CellCycleModel.cpp.
References mScale.
Referenced by serialize().
SetShape()
void GammaG1CellCycleModel::SetShape (double shape)
Set mShape.
Parameters
shape the value of the shape parameter
Definition at line 92 of file GammaG1CellCycleModel.cpp.
References mShape.
Referenced by serialize().
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Needed for serialization.
Definition at line 59 of file GammaG1CellCycleModel.hpp.
Member Data Documentation
mScale
double GammaG1CellCycleModel::mScale private
The scale parameter of the gamma distribution. This must be a positive real number.
Definition at line 56 of file GammaG1CellCycleModel.hpp.
Referenced by GetScale(), OutputCellCycleModelParameters(), serialize(), SetG1Duration(), and SetScale().
mShape
double GammaG1CellCycleModel::mShape private
The shape parameter of the gamma distribution. This must be a positive real number.
Definition at line 53 of file GammaG1CellCycleModel.hpp.
Referenced by GetShape(), OutputCellCycleModelParameters(), serialize(), SetG1Duration(), and SetShape().
The documentation for this class was generated from the following files:
cell_based/src/cell/cycle/GammaG1CellCycleModel.hpp
cell_based/src/cell/cycle/GammaG1CellCycleModel.cpp