Chaste: AbstractCentreBasedDivisionRule< ELEMENT_DIM, SPACE_DIM > Class Template Reference
AbstractCentreBasedDivisionRule< ELEMENT_DIM, SPACE_DIM > Class Template Reference abstract
#include <AbstractCentreBasedDivisionRule.hpp>
Public Member Functions
AbstractCentreBasedDivisionRule ()
virtual ~AbstractCentreBasedDivisionRule ()
virtual std::pair< c_vector< double, SPACE_DIM >, c_vector< double, SPACE_DIM > > CalculateCellDivisionVector (CellPtr pParentCell, AbstractCentreBasedCellPopulation< ELEMENT_DIM, SPACE_DIM > &rCellPopulation)=0
void OutputCellCentreBasedDivisionRuleInfo (out_stream &rParamsFile)
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Protected Member Functions
virtual void OutputCellCentreBasedDivisionRuleParameters (out_stream &rParamsFile)
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Friends
class boost::serialization::access
Detailed Description
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM = ELEMENT_DIM>
class AbstractCentreBasedDivisionRule< ELEMENT_DIM, SPACE_DIM >
An abstract cell division rule for use in centre-based simulations.
The purpose of this class is to return the locations of the two daughters of a dividing cell.
Definition at line 42 of file AbstractCentreBasedCellPopulation.hpp.
Constructor & Destructor Documentation
AbstractCentreBasedDivisionRule()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> AbstractCentreBasedDivisionRule< ELEMENT_DIM, SPACE_DIM >::AbstractCentreBasedDivisionRule ()
Default constructor.
Definition at line 39 of file AbstractCentreBasedDivisionRule.cpp.
Referenced by AbstractCentreBasedDivisionRule< ELEMENT_DIM, SPACE_DIM >::serialize().
~AbstractCentreBasedDivisionRule()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> AbstractCentreBasedDivisionRule< ELEMENT_DIM, SPACE_DIM >::~AbstractCentreBasedDivisionRule () virtual
Empty destructor.
Definition at line 44 of file AbstractCentreBasedDivisionRule.cpp.
Referenced by AbstractCentreBasedDivisionRule< ELEMENT_DIM, SPACE_DIM >::serialize().
Member Function Documentation
CalculateCellDivisionVector()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM = ELEMENT_DIM> virtual std::pair<c_vector<double, SPACE_DIM>, c_vector<double, SPACE_DIM> > AbstractCentreBasedDivisionRule< ELEMENT_DIM, SPACE_DIM >::CalculateCellDivisionVector (CellPtr pParentCell, AbstractCentreBasedCellPopulation< ELEMENT_DIM, SPACE_DIM > & rCellPopulation) pure virtual
Return a pair of vectors used to position the daughters of a dividing cell.
As this method is pure virtual, it must be overridden in subclasses.
Parameters
pParentCell The cell to divide
rCellPopulation The centre-based cell population
Returns
the two daughter cell positions.
Implemented in FixedCentreBasedDivisionRule< ELEMENT_DIM, SPACE_DIM >, RandomDirectionCentreBasedDivisionRule< ELEMENT_DIM, SPACE_DIM >, and CryptCentreBasedDivisionRule< ELEMENT_DIM, SPACE_DIM >.
Referenced by AbstractCentreBasedDivisionRule< ELEMENT_DIM, SPACE_DIM >::serialize().
OutputCellCentreBasedDivisionRuleInfo()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void AbstractCentreBasedDivisionRule< ELEMENT_DIM, SPACE_DIM >::OutputCellCentreBasedDivisionRuleInfo (out_stream & rParamsFile)
Output the name of the concrete class and call OutputCellCentreBasedDivisionRuleParameters().
Parameters
rParamsFile The stream of the parameter file
Definition at line 49 of file AbstractCentreBasedDivisionRule.cpp.
Referenced by AbstractCentreBasedDivisionRule< ELEMENT_DIM, SPACE_DIM >::serialize().
OutputCellCentreBasedDivisionRuleParameters()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void AbstractCentreBasedDivisionRule< ELEMENT_DIM, SPACE_DIM >::OutputCellCentreBasedDivisionRuleParameters (out_stream & rParamsFile) protected virtual
Output any parameters associated with the division rule. Currently empty since this class has no member variables. Should be overridden by any child classes that have parameters.
Parameters
rParamsFile The stream of the parameter file
Definition at line 59 of file AbstractCentreBasedDivisionRule.cpp.
Referenced by AbstractCentreBasedDivisionRule< ELEMENT_DIM, SPACE_DIM >::serialize().
serialize()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM = ELEMENT_DIM> template<class Archive > void AbstractCentreBasedDivisionRule< ELEMENT_DIM, SPACE_DIM >::serialize (Archive & archive, const unsigned int version) inline private
Serialize the object and its member variables.
Parameters
archive the archive
version the current version of this class
Definition at line 66 of file AbstractCentreBasedDivisionRule.hpp.
References AbstractCentreBasedDivisionRule< ELEMENT_DIM, SPACE_DIM >::AbstractCentreBasedDivisionRule(), AbstractCentreBasedDivisionRule< ELEMENT_DIM, SPACE_DIM >::CalculateCellDivisionVector(), AbstractCentreBasedDivisionRule< ELEMENT_DIM, SPACE_DIM >::OutputCellCentreBasedDivisionRuleInfo(), AbstractCentreBasedDivisionRule< ELEMENT_DIM, SPACE_DIM >::OutputCellCentreBasedDivisionRuleParameters(), and AbstractCentreBasedDivisionRule< ELEMENT_DIM, SPACE_DIM >::~AbstractCentreBasedDivisionRule().
The documentation for this class was generated from the following files:
cell_based/src/population/AbstractCentreBasedCellPopulation.hpp
cell_based/src/population/division_rules/AbstractCentreBasedDivisionRule.hpp
cell_based/src/population/division_rules/AbstractCentreBasedDivisionRule.cpp