Chaste: Node< SPACE_DIM >::ContainingElementIterator Class Reference
Node< SPACE_DIM >::ContainingElementIterator Class Reference
#include <Node.hpp>
Public Member Functions
ContainingElementIterator (std::set< unsigned >::const_iterator indexIterator)
const unsigned & operator* () const
bool operator!= (const ContainingElementIterator &rOther) const
bool operator== (const ContainingElementIterator &rOther) const
ContainingElementIterator & operator++ ()
Private Attributes
std::set< unsigned >::const_iterator mIndexIterator
Detailed Description
template<unsigned SPACE_DIM>
class Node< SPACE_DIM >::ContainingElementIterator
An iterator over the indices of elements which contain this node.
Definition at line 432 of file Node.hpp.
Constructor & Destructor Documentation
ContainingElementIterator()
template<unsigned SPACE_DIM> Node< SPACE_DIM >::ContainingElementIterator::ContainingElementIterator (std::set< unsigned >::const_iterator indexIterator) inline
Constructor for a new ContainingElementIterator.
Parameters
indexIterator an index iterator
Definition at line 440 of file Node.hpp.
Referenced by Node< SPACE_DIM >::ContainingElementsBegin(), and Node< SPACE_DIM >::ContainingElementsEnd().
Member Function Documentation
operator!=()
template<unsigned SPACE_DIM> bool Node< SPACE_DIM >::ContainingElementIterator::operator!= (const ContainingElementIterator & rOther) const inline
Returns
Comparison not-equal-to.
Parameters
rOther ContainingElementIterator with which comparison is made
Definition at line 456 of file Node.hpp.
References Node< SPACE_DIM >::ContainingElementIterator::mIndexIterator.
Referenced by Node< SPACE_DIM >::ContainingElementIterator::operator==(), and Node< SPACE_DIM >::ContainingBoundaryElementIterator::operator==().
operator*()
template<unsigned SPACE_DIM> const unsigned& Node< SPACE_DIM >::ContainingElementIterator::operator* () const inline
Prefix dereference operator.
Returns
reference
Definition at line 447 of file Node.hpp.
References Node< SPACE_DIM >::ContainingElementIterator::mIndexIterator.
operator++()
template<unsigned SPACE_DIM> ContainingElementIterator& Node< SPACE_DIM >::ContainingElementIterator::operator++ () inline
Prefix increment operator.
Returns
reference to incremented object
Definition at line 473 of file Node.hpp.
References Node< SPACE_DIM >::ContainingElementIterator::mIndexIterator.
operator==()
template<unsigned SPACE_DIM> bool Node< SPACE_DIM >::ContainingElementIterator::operator== (const ContainingElementIterator & rOther) const inline
Returns
Comparison equal-to.
Parameters
rOther ContainingElementIterator with which comparison is made
Definition at line 465 of file Node.hpp.
References Node< SPACE_DIM >::ContainingElementIterator::operator!=().
Member Data Documentation
mIndexIterator
template<unsigned SPACE_DIM> std::set<unsigned>::const_iterator Node< SPACE_DIM >::ContainingElementIterator::mIndexIterator private
Element index iterator.
Definition at line 479 of file Node.hpp.
Referenced by Node< SPACE_DIM >::ContainingElementIterator::operator!=(), Node< SPACE_DIM >::ContainingBoundaryElementIterator::operator!=(), Node< SPACE_DIM >::ContainingElementIterator::operator*(), Node< SPACE_DIM >::ContainingBoundaryElementIterator::operator*(), Node< SPACE_DIM >::ContainingElementIterator::operator++(), and Node< SPACE_DIM >::ContainingBoundaryElementIterator::operator++().
The documentation for this class was generated from the following file:
mesh/src/common/Node.hpp