Chaste: AbstractWntOdeBasedCellCycleModel Class Reference
AbstractWntOdeBasedCellCycleModel Class Reference abstract
#include <AbstractWntOdeBasedCellCycleModel.hpp>
Public Member Functions
AbstractWntOdeBasedCellCycleModel (boost::shared_ptr< AbstractCellCycleModelOdeSolver > pOdeSolver=boost::shared_ptr< AbstractCellCycleModelOdeSolver >())
virtual ~AbstractWntOdeBasedCellCycleModel ()
void ResetForDivision ()
void UpdateCellProliferativeType ()
virtual void ChangeCellProliferativeTypeDueToCurrentBetaCateninLevel ()=0
double GetAverageTransitCellCycleTime ()
double GetAverageStemCellCycleTime ()
virtual bool CanCellTerminallyDifferentiate ()
virtual void OutputCellCycleModelParameters (out_stream &rParamsFile)
Public Member Functions inherited from AbstractOdeBasedPhaseBasedCellCycleModel
AbstractOdeBasedPhaseBasedCellCycleModel (double lastTime=SimulationTime::Instance() ->GetTime(), boost::shared_ptr< AbstractCellCycleModelOdeSolver > pOdeSolver=boost::shared_ptr< AbstractCellCycleModelOdeSolver >())
virtual ~AbstractOdeBasedPhaseBasedCellCycleModel ()
double GetOdeStopTime ()
void SetBirthTime (double birthTime)
Public Member Functions inherited from AbstractPhaseBasedCellCycleModel
AbstractPhaseBasedCellCycleModel ()
virtual ~AbstractPhaseBasedCellCycleModel ()
virtual bool ReadyToDivide ()
CellCyclePhase GetCurrentCellCyclePhase () const
virtual double GetG1Duration () const
double GetStemCellG1Duration () const
double GetTransitCellG1Duration () const
double GetSG2MDuration () const
virtual double GetSDuration () const
virtual double GetG2Duration () const
virtual double GetMDuration () const
virtual void SetStemCellG1Duration (double stemCellG1Duration)
virtual void SetTransitCellG1Duration (double transitCellG1Duration)
void SetSDuration (double sDuration)
void SetG2Duration (double g2Duration)
void SetMDuration (double mDuration)
double GetMinimumGapDuration () const
void SetMinimumGapDuration (double minimumGapDuration)
Public Member Functions inherited from AbstractCellCycleModel
AbstractCellCycleModel ()
virtual ~AbstractCellCycleModel ()
void SetCell (CellPtr pCell)
virtual void Initialise ()
virtual void InitialiseDaughterCell ()
CellPtr GetCell ()
void SetDimension (unsigned dimension)
unsigned GetDimension () const
double GetBirthTime () const
double GetAge ()
virtual AbstractCellCycleModel * CreateCellCycleModel ()=0
void OutputCellCycleModelInfo (out_stream &rParamsFile)
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Public Member Functions inherited from CellCycleModelOdeHandler
CellCycleModelOdeHandler (double lastTime=SimulationTime::Instance() ->GetTime(), boost::shared_ptr< AbstractCellCycleModelOdeSolver > pOdeSolver=boost::shared_ptr< AbstractCellCycleModelOdeSolver >())
virtual ~CellCycleModelOdeHandler ()
AbstractOdeSystem * GetOdeSystem () const
void SetOdeSystem (AbstractOdeSystem *pOdeSystem)
const boost::shared_ptr< AbstractCellCycleModelOdeSolver > GetOdeSolver () const
void SetLastTime (double lastTime)
double GetDt ()
void SetDt (double timeStep)
void SetStateVariables (const std::vector< double > &rStateVariables)
std::vector< double > GetProteinConcentrations () const
void SetProteinConcentrationsForTestsOnly (double lastTime, std::vector< double > proteinConcentrations)
Protected Member Functions
double GetWntLevel () const
void UpdateCellCyclePhase ()
AbstractWntOdeBasedCellCycleModel (const AbstractWntOdeBasedCellCycleModel &rModel)
Protected Member Functions inherited from AbstractOdeBasedPhaseBasedCellCycleModel
AbstractOdeBasedPhaseBasedCellCycleModel (const AbstractOdeBasedPhaseBasedCellCycleModel &rModel)
Protected Member Functions inherited from AbstractPhaseBasedCellCycleModel
AbstractPhaseBasedCellCycleModel (const AbstractPhaseBasedCellCycleModel &rModel)
Protected Member Functions inherited from AbstractCellCycleModel
AbstractCellCycleModel (const AbstractCellCycleModel &rModel)
Protected Member Functions inherited from CellCycleModelOdeHandler
CellCycleModelOdeHandler (const CellCycleModelOdeHandler &rHandler)
bool SolveOdeToTime (double currentTime)
virtual void AdjustOdeParameters (double currentTime)
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Friends
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from AbstractOdeBasedPhaseBasedCellCycleModel
double mDivideTime
double mG2PhaseStartTime
Protected Attributes inherited from AbstractPhaseBasedCellCycleModel
CellCyclePhase mCurrentCellCyclePhase
double mG1Duration
double mMinimumGapDuration
double mStemCellG1Duration
double mTransitCellG1Duration
double mSDuration
double mG2Duration
double mMDuration
Protected Attributes inherited from AbstractCellCycleModel
CellPtr mpCell
double mBirthTime
bool mReadyToDivide
unsigned mDimension
Protected Attributes inherited from CellCycleModelOdeHandler
double mDt
AbstractOdeSystem * mpOdeSystem
boost::shared_ptr< AbstractCellCycleModelOdeSolver > mpOdeSolver
double mLastTime
bool mFinishedRunningOdes
Detailed Description
This class contains all the things common to the Wnt cell cycle ODE based models, the resetting method and updating of cell types etc.
The concrete models all need to operate with a WntConcentration singleton object.
These models have a constant length M phase, run ODEs to decide when to finish G1 phase, then add time for S and G2 phases (in some classes, random periods of time). The CellProliferativeType is updated dependent on the concentration of beta-catenin (given by one of the ODEs).
Definition at line 58 of file AbstractWntOdeBasedCellCycleModel.hpp.
Constructor & Destructor Documentation
AbstractWntOdeBasedCellCycleModel() [1/2]
AbstractWntOdeBasedCellCycleModel::AbstractWntOdeBasedCellCycleModel (const AbstractWntOdeBasedCellCycleModel & rModel) protected
Protected copy-constructor for use by CreateCellCycleModel. The only way for external code to create a copy of a cell cycle model is by calling that method, to ensure that a model of the correct subclass is created. This copy-constructor helps subclasses to ensure that all member variables are correctly copied when this happens.
This method is called by child classes to set member variables for a daughter cell upon cell division. Note that the parent cell cycle model will have had ResetForDivision() called just before CreateCellCycleModel() is called, so performing an exact copy of the parent is suitable behaviour. Any daughter-cell-specific initialisation can be done in InitialiseDaughterCell().
Parameters
rModel the cell cycle model to copy.
Definition at line 47 of file AbstractWntOdeBasedCellCycleModel.cpp.
Referenced by serialize().
AbstractWntOdeBasedCellCycleModel() [2/2]
AbstractWntOdeBasedCellCycleModel::AbstractWntOdeBasedCellCycleModel (boost::shared_ptr< AbstractCellCycleModelOdeSolver > pOdeSolver = boost::shared_ptr<AbstractCellCycleModelOdeSolver>())
Default constructor.
Parameters
pOdeSolver An optional pointer to a cell-cycle model ODE solver object (allows the use of different ODE solvers)
Definition at line 38 of file AbstractWntOdeBasedCellCycleModel.cpp.
~AbstractWntOdeBasedCellCycleModel()
AbstractWntOdeBasedCellCycleModel::~AbstractWntOdeBasedCellCycleModel () virtual
Destructor.
Definition at line 43 of file AbstractWntOdeBasedCellCycleModel.cpp.
Referenced by serialize().
Member Function Documentation
CanCellTerminallyDifferentiate()
bool AbstractWntOdeBasedCellCycleModel::CanCellTerminallyDifferentiate () virtual
Overridden CanCellTerminallyDifferentiate() method.
Returns
whether cell can terminally differentiate
Reimplemented from AbstractCellCycleModel.
Definition at line 141 of file AbstractWntOdeBasedCellCycleModel.cpp.
Referenced by serialize().
ChangeCellProliferativeTypeDueToCurrentBetaCateninLevel()
virtual void AbstractWntOdeBasedCellCycleModel::ChangeCellProliferativeTypeDueToCurrentBetaCateninLevel () pure virtual
Change cell type to reflect current levels of beta-catenin.
As this method is pure virtual, it must be overridden in subclasses.
Implemented in WntCellCycleModel, and AbstractVanLeeuwen2009WntSwatCellCycleModel.
Referenced by serialize(), and UpdateCellProliferativeType().
GetAverageStemCellCycleTime()
double AbstractWntOdeBasedCellCycleModel::GetAverageStemCellCycleTime () virtual
Overridden GetAverageStemCellCycleTime() method.
Returns
time
Reimplemented from AbstractPhaseBasedCellCycleModel.
Definition at line 136 of file AbstractWntOdeBasedCellCycleModel.cpp.
Referenced by serialize().
GetAverageTransitCellCycleTime()
double AbstractWntOdeBasedCellCycleModel::GetAverageTransitCellCycleTime () virtual
Overridden GetAverageTransitCellCycleTime() method.
Returns
time
Reimplemented from AbstractPhaseBasedCellCycleModel.
Definition at line 131 of file AbstractWntOdeBasedCellCycleModel.cpp.
Referenced by serialize().
GetWntLevel()
double AbstractWntOdeBasedCellCycleModel::GetWntLevel () const protected
Returns
the Wnt level experienced by the cell.
Definition at line 65 of file AbstractWntOdeBasedCellCycleModel.cpp.
References WntConcentration< DIM >::GetWntLevel(), WntConcentration< DIM >::Instance(), AbstractCellCycleModel::mDimension, AbstractCellCycleModel::mpCell, and NEVER_REACHED.
Referenced by AbstractVanLeeuwen2009WntSwatCellCycleModel::AdjustOdeParameters(), WntCellCycleModel::AdjustOdeParameters(), AbstractVanLeeuwen2009WntSwatCellCycleModel::Initialise(), WntCellCycleModel::Initialise(), serialize(), VanLeeuwen2009WntSwatCellCycleModelHypothesisOne::VanLeeuwen2009WntSwatCellCycleModelHypothesisOne(), VanLeeuwen2009WntSwatCellCycleModelHypothesisTwo::VanLeeuwen2009WntSwatCellCycleModelHypothesisTwo(), and WntCellCycleModel::WntCellCycleModel().
OutputCellCycleModelParameters()
void AbstractWntOdeBasedCellCycleModel::OutputCellCycleModelParameters (out_stream & rParamsFile) virtual
Overridden OutputCellCycleModelParameters() method.
Parameters
rParamsFile the file stream to which the parameters are output
Reimplemented from AbstractOdeBasedPhaseBasedCellCycleModel.
Reimplemented in StochasticWntCellCycleModel, AbstractVanLeeuwen2009WntSwatCellCycleModel, WntCellCycleModel, VanLeeuwen2009WntSwatCellCycleModelHypothesisTwo, and VanLeeuwen2009WntSwatCellCycleModelHypothesisOne.
Definition at line 146 of file AbstractWntOdeBasedCellCycleModel.cpp.
References AbstractOdeBasedPhaseBasedCellCycleModel::OutputCellCycleModelParameters().
Referenced by WntCellCycleModel::OutputCellCycleModelParameters(), AbstractVanLeeuwen2009WntSwatCellCycleModel::OutputCellCycleModelParameters(), and serialize().
ResetForDivision()
void AbstractWntOdeBasedCellCycleModel::ResetForDivision () virtual
Resets the Wnt Model to the start of the cell cycle (this model does not cycle naturally) Cells are given a new birth time and cell cycle proteins are reset. Note that the Wnt pathway proteins maintain their current values.
Should only be called by the Cell::Divide() method.
Reimplemented from AbstractOdeBasedPhaseBasedCellCycleModel.
Reimplemented in StochasticWntCellCycleModel.
Definition at line 97 of file AbstractWntOdeBasedCellCycleModel.cpp.
References AbstractParameterisedSystem< VECTOR >::GetInitialConditions(), CellCycleModelOdeHandler::mpOdeSystem, and AbstractOdeBasedPhaseBasedCellCycleModel::ResetForDivision().
Referenced by StochasticWntCellCycleModel::ResetForDivision(), and serialize().
serialize()
template<class Archive > void AbstractWntOdeBasedCellCycleModel::serialize (Archive & archive, const unsigned int version) inline private
Archive the cell-cycle model, never used directly - boost uses this.
Parameters
archive the archive
version the current version of this class
Definition at line 71 of file AbstractWntOdeBasedCellCycleModel.hpp.
References AbstractWntOdeBasedCellCycleModel(), CanCellTerminallyDifferentiate(), ChangeCellProliferativeTypeDueToCurrentBetaCateninLevel(), CLASS_IS_ABSTRACT, GetAverageStemCellCycleTime(), GetAverageTransitCellCycleTime(), GetWntLevel(), OutputCellCycleModelParameters(), ResetForDivision(), UpdateCellCyclePhase(), UpdateCellProliferativeType(), and ~AbstractWntOdeBasedCellCycleModel().
UpdateCellCyclePhase()
void AbstractWntOdeBasedCellCycleModel::UpdateCellCyclePhase () protected virtual
Call base class UpdateCellCyclePhase, then UpdateCellProliferativeType.
Reimplemented from AbstractOdeBasedPhaseBasedCellCycleModel.
Definition at line 113 of file AbstractWntOdeBasedCellCycleModel.cpp.
References AbstractOdeBasedPhaseBasedCellCycleModel::GetOdeStopTime(), SimulationTime::Instance(), CellCycleModelOdeHandler::mLastTime, AbstractOdeBasedPhaseBasedCellCycleModel::UpdateCellCyclePhase(), and UpdateCellProliferativeType().
Referenced by serialize().
UpdateCellProliferativeType()
void AbstractWntOdeBasedCellCycleModel::UpdateCellProliferativeType ()
Updates the current cell type to reflect whether the beta-catenin level has dropped low enough to make it stop dividing. This should only be called when the cell-cycle model has been evaluated to the current time, or it may give misleading results.
Definition at line 124 of file AbstractWntOdeBasedCellCycleModel.cpp.
References ChangeCellProliferativeTypeDueToCurrentBetaCateninLevel(), AbstractCellCycleModel::mpCell, and CellCycleModelOdeHandler::mpOdeSystem.
Referenced by serialize(), and UpdateCellCyclePhase().
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Needed for serialization.
Definition at line 63 of file AbstractWntOdeBasedCellCycleModel.hpp.
The documentation for this class was generated from the following files:
crypt/src/cell/cycle/AbstractWntOdeBasedCellCycleModel.hpp
crypt/src/cell/cycle/AbstractWntOdeBasedCellCycleModel.cpp