Chaste: RandomNumberGenerator Class Reference
RandomNumberGenerator Class Reference
#include <RandomNumberGenerator.hpp>
Public Member Functions
double StandardNormalRandomDeviate ()
double NormalRandomDeviate (double mean, double stdDev)
double ranf ()
double GammaRandomDeviate (double shape, double scale)
double ExponentialRandomDeviate (double scale)
unsigned randMod (unsigned base)
template<class T >
void Shuffle (std::vector< boost::shared_ptr< T > > &rValues)
void Shuffle (unsigned num, std::vector< unsigned > &rValues)
void Reseed (unsigned seed)
Public Member Functions inherited from SerializableSingleton< RandomNumberGenerator >
SerializableSingleton< RandomNumberGenerator > * GetSerializationWrapper () const
Static Public Member Functions
static RandomNumberGenerator * Instance ()
static void Destroy ()
Protected Member Functions
RandomNumberGenerator ()
Private Member Functions
template<class Archive >
void save (Archive &archive, const unsigned int version) const
template<class Archive >
void load (Archive &archive, const unsigned int version)
Private Attributes
boost::mt19937 mMersenneTwisterGenerator
boost::variate_generator< boost::mt19937 &, boost::uniform_real<> > mGenerateUnitReal
boost::variate_generator< boost::mt19937 &, boost::random::normal_distribution_v165<> > mGenerateStandardNormal
Static Private Attributes
static RandomNumberGenerator * mpInstance = nullptr
Friends
class boost::serialization::access
Detailed Description
A special singleton class allowing one to generate different types of random number in a consistent way across platforms and different versions of compilers, standard libraries, and our dependencies. As a result Chaste developers should always use this class to get random numbers rather than accessing C/C++/boost methods directly.
This class is a singleton and an instance should be retrieved with: RandomNumberGenerator* p_gen = RandomNumberGenerator::Instance();
Note for developers that might want to change this class!:
We use boost random number library for random number generation under the hood http://www.boost.org/doc/libs/1_65_0/doc/html/boost_random.html
Generally boost is consistent between our supported versions (listed on https://chaste.cs.ox.ac.uk/trac/wiki/InstallGuides/DependencyVersions) but on a couple of occasions boost has broken backwards compatibility between random numbers for a given seed.
To get around this, we have copied a minimal set of boost's more recent random include headers into the folder global/src/random
If the user is on a recent version of boost, the boost libraries/includes are used by default, if the user is on an older version of boost some of the Chaste copies of newer boost distributions in global/src/random are used instead to give consistent random numbers across boost versions.
Definition at line 81 of file RandomNumberGenerator.hpp.
Constructor & Destructor Documentation
RandomNumberGenerator()
RandomNumberGenerator::RandomNumberGenerator () protected
Protected constructor. Use Instance() to access the random number generator.
Definition at line 47 of file RandomNumberGenerator.cpp.
Referenced by Instance(), and load().
Member Function Documentation
Destroy()
void RandomNumberGenerator::Destroy () static
Destroy the current instance of the random number generator. The next call to Instance will create a new instance and re-seed. This method *must* be called before program exit, to avoid a memory leak.
Definition at line 68 of file RandomNumberGenerator.cpp.
References mpInstance.
Referenced by AbstractCellBasedTestSuite::tearDown().
ExponentialRandomDeviate()
double RandomNumberGenerator::ExponentialRandomDeviate (double scale)
Returns
Generate a random number from an exponential distribution with specified scale parameter.
Parameters
scale The scale parameter of the exponential distribution from which the random number is drawn, often named lambda
Definition at line 138 of file RandomNumberGenerator.cpp.
References mMersenneTwisterGenerator.
Referenced by load(), and ExponentialG1GenerationalCellCycleModel::SetG1Duration().
GammaRandomDeviate()
double RandomNumberGenerator::GammaRandomDeviate (double shape, double scale)
Returns
Generate a random number from a gamma distribution with specified shape and scale parameters.
Parameters
shape the shape parameter of the gamma distribution from which the random number is drawn
scale the scale parameter of the gamma distribution from which the random number is drawn
Definition at line 124 of file RandomNumberGenerator.cpp.
References mMersenneTwisterGenerator.
Referenced by load(), and GammaG1CellCycleModel::SetG1Duration().
Instance()
RandomNumberGenerator * RandomNumberGenerator::Instance () static
Returns
a pointer to the random number generator object. The object is created the first time this method is called.
Definition at line 59 of file RandomNumberGenerator.cpp.
References mpInstance, and RandomNumberGenerator().
Referenced by AbstractCellBasedSimulation< DIM >::AbstractCellBasedSimulation(), RandomDirectionVertexBasedDivisionRule< SPACE_DIM >::CalculateCellDivisionVector(), CryptCentreBasedDivisionRule< ELEMENT_DIM, SPACE_DIM >::CalculateCellDivisionVector(), RandomDirectionCentreBasedDivisionRule< ELEMENT_DIM, SPACE_DIM >::CalculateCellDivisionVector(), CryptVertexBasedDivisionRule< SPACE_DIM >::CalculateCellDivisionVector(), CryptShovingCaBasedDivisionRule::CalculateDaughterNodeIndex(), RandomCellKiller< DIM >::CheckAndLabelSingleCellForApoptosis(), MutableVertexMesh< DIM, DIM >::CheckForRosettes(), CryptCellsGenerator< CELL_CYCLE_MODEL >::Generate(), StochasticOxygenBasedCellCycleModel::GenerateStochasticG2Duration(), StochasticWntCellCycleModel::GenerateStochasticG2Duration(), CryptStatistics::GetCryptSection(), CryptSimulationBoundaryCondition< DIM >::ImposeBoundaryCondition(), MutableVertexMesh< DIM, DIM >::PerformProtorosetteResolution(), MutableVertexMesh< DIM, DIM >::PerformRosetteRankDecrease(), TetrahedralMesh< 3, 3 >::PermuteNodes(), BernoulliTrialCellCycleModel::ReadyToDivide(), SimpleWntCellCycleModel::serialize(), StochasticOxygenBasedCellCycleModel::serialize(), UniformG1GenerationalCellCycleModel::serialize(), StochasticWntCellCycleModel::serialize(), GammaG1CellCycleModel::serialize(), UniformCellCycleModel::serialize(), ExponentialG1GenerationalCellCycleModel::serialize(), RandomCellKiller< DIM >::serialize(), AbstractCellBasedSimulation< DIM >::serialize(), UniformCellCycleModel::SetCellCycleDuration(), UniformG1GenerationalCellCycleModel::SetG1Duration(), ExponentialG1GenerationalCellCycleModel::SetG1Duration(), GammaG1CellCycleModel::SetG1Duration(), SimpleWntCellCycleModel::SetG1Duration(), AbstractCellBasedTestSuite::setUp(), PottsBasedCellPopulation< DIM >::UpdateCellLocations(), and SimpleOxygenBasedCellCycleModel::UpdateHypoxicDuration().
load()
template<class Archive > void RandomNumberGenerator::load (Archive & archive, const unsigned int version) inline private
Load the RandomNumberGenerator and its member variables.
Note
do not serialize this singleton directly. Instead, serialize the object returned by GetSerializationWrapper().
Parameters
archive the archive
version the current version of this class
Definition at line 140 of file RandomNumberGenerator.hpp.
References ExponentialRandomDeviate(), GammaRandomDeviate(), mMersenneTwisterGenerator, NormalRandomDeviate(), randMod(), RandomNumberGenerator(), ranf(), and StandardNormalRandomDeviate().
NormalRandomDeviate()
double RandomNumberGenerator::NormalRandomDeviate (double mean, double stdDev)
Returns
Generate a random number from a normal distribution with given mean and standard deviation.
Parameters
mean the mean of the normal distribution from which the random number is drawn
stdDev the standard deviation of the normal distribution from which the random number is drawn
Definition at line 119 of file RandomNumberGenerator.cpp.
References StandardNormalRandomDeviate().
Referenced by StochasticOxygenBasedCellCycleModel::GenerateStochasticG2Duration(), StochasticWntCellCycleModel::GenerateStochasticG2Duration(), load(), and SimpleWntCellCycleModel::SetG1Duration().
randMod()
unsigned RandomNumberGenerator::randMod (unsigned base)
Returns
Generate a random number modulo base (i.e. an integer within the range [0, base) == [0,1,..,base-1]).
Parameters
base the order of the field of positive integers from which the random number is drawn. This should be no greater than INT_MAX
Definition at line 77 of file RandomNumberGenerator.cpp.
Referenced by CryptShovingCaBasedDivisionRule::CalculateDaughterNodeIndex(), load(), MutableVertexMesh< DIM, DIM >::PerformProtorosetteResolution(), and MutableVertexMesh< DIM, DIM >::PerformRosetteRankDecrease().
ranf()
double RandomNumberGenerator::ranf ()
Returns
Generate a uniform random number in (0,1].
Definition at line 109 of file RandomNumberGenerator.cpp.
References mGenerateUnitReal.
Referenced by RandomDirectionVertexBasedDivisionRule< SPACE_DIM >::CalculateCellDivisionVector(), CryptCentreBasedDivisionRule< ELEMENT_DIM, SPACE_DIM >::CalculateCellDivisionVector(), CryptVertexBasedDivisionRule< SPACE_DIM >::CalculateCellDivisionVector(), RandomDirectionCentreBasedDivisionRule< ELEMENT_DIM, SPACE_DIM >::CalculateCellDivisionVector(), RandomCellKiller< DIM >::CheckAndLabelSingleCellForApoptosis(), CryptStatistics::GetCryptSection(), CryptSimulationBoundaryCondition< DIM >::ImposeBoundaryCondition(), load(), BernoulliTrialCellCycleModel::ReadyToDivide(), UniformCellCycleModel::SetCellCycleDuration(), UniformG1GenerationalCellCycleModel::SetG1Duration(), and SimpleOxygenBasedCellCycleModel::UpdateHypoxicDuration().
Reseed()
void RandomNumberGenerator::Reseed (unsigned seed)
Reseed the random number generator.
Parameters
seed the new seed
Definition at line 153 of file RandomNumberGenerator.cpp.
References mGenerateStandardNormal, mGenerateUnitReal, and mMersenneTwisterGenerator.
Referenced by AbstractCellBasedTestSuite::setUp().
save()
template<class Archive > void RandomNumberGenerator::save (Archive & archive, const unsigned int version) const inline private
Save the RandomNumberGenerator and its member variables.
Note
do not serialize this singleton directly. Instead, serialize the object returned by GetSerializationWrapper().
Parameters
archive the archive
version the current version of this class
Definition at line 112 of file RandomNumberGenerator.hpp.
References mMersenneTwisterGenerator.
Shuffle() [1/2]
template<class T > void RandomNumberGenerator::Shuffle (std::vector< boost::shared_ptr< T > > & rValues) inline
Produce a permutation of the integers and non-empty std::vector, using the Knuth-algorithm (also called the Fisher-Yates algorithm), a linear time unbiased method. The values are shuffled in place.
Parameters
rValues the initial values and the output permutation of shuffled values. Must be non-empty
Definition at line 214 of file RandomNumberGenerator.hpp.
Referenced by TetrahedralMesh< 3, 3 >::PermuteNodes(), and PottsBasedCellPopulation< DIM >::UpdateCellLocations().
Shuffle() [2/2]
void RandomNumberGenerator::Shuffle (unsigned num, std::vector< unsigned > & rValues)
Produce a permutation of the integers 0,1,..,num-1, using the Knuth-algorithm (also called the Fisher-Yates algorithm), a linear time unbiased method. The shuffled values are returned in rValues, which doesn't need to be correctly-sized when passed in.
Parameters
num the number of integers to shuffle
rValues the output permutation of shuffled values (any initial values ignored)
Definition at line 164 of file RandomNumberGenerator.cpp.
StandardNormalRandomDeviate()
double RandomNumberGenerator::StandardNormalRandomDeviate ()
Returns
a random number from the normal distribution with mean 0 and standard distribution 1.
Definition at line 114 of file RandomNumberGenerator.cpp.
References mGenerateStandardNormal.
Referenced by load(), and NormalRandomDeviate().
Member Data Documentation
mGenerateStandardNormal
boost::variate_generator<boost::mt19937&, boost::random::normal_distribution_v165<> > RandomNumberGenerator::mGenerateStandardNormal private
An adaptor to a standard normal distribution.
Definition at line 94 of file RandomNumberGenerator.hpp.
Referenced by Reseed(), and StandardNormalRandomDeviate().
mGenerateUnitReal
boost::variate_generator<boost::mt19937&, boost::uniform_real<> > RandomNumberGenerator::mGenerateUnitReal private
An adaptor to a unit interval distribution.
Definition at line 90 of file RandomNumberGenerator.hpp.
Referenced by ranf(), and Reseed().
mMersenneTwisterGenerator
boost::mt19937 RandomNumberGenerator::mMersenneTwisterGenerator private
The main random number generator.
Definition at line 85 of file RandomNumberGenerator.hpp.
Referenced by ExponentialRandomDeviate(), GammaRandomDeviate(), load(), Reseed(), and save().
mpInstance
RandomNumberGenerator * RandomNumberGenerator::mpInstance = nullptr static private
Pointer to the single instance.
Definition at line 99 of file RandomNumberGenerator.hpp.
Referenced by Destroy(), and Instance().
The documentation for this class was generated from the following files:
global/src/RandomNumberGenerator.hpp
global/src/RandomNumberGenerator.cpp