Chaste: AbstractCellPopulationWriter< ELEMENT_DIM, SPACE_DIM > Class Template Reference
AbstractCellPopulationWriter< ELEMENT_DIM, SPACE_DIM > Class Template Reference abstract
#include <AbstractCellPopulationWriter.hpp>
Public Member Functions
AbstractCellPopulationWriter (const std::string &rFileName)
virtual void WriteHeader (AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM > *pCellPopulation)
virtual void Visit (MeshBasedCellPopulation< ELEMENT_DIM, SPACE_DIM > *pCellPopulation)=0
virtual void Visit (CaBasedCellPopulation< SPACE_DIM > *pCellPopulation)=0
virtual void Visit (NodeBasedCellPopulation< SPACE_DIM > *pCellPopulation)=0
virtual void Visit (PottsBasedCellPopulation< SPACE_DIM > *pCellPopulation)=0
virtual void Visit (VertexBasedCellPopulation< SPACE_DIM > *pCellPopulation)=0
Public Member Functions inherited from AbstractCellBasedWriter< ELEMENT_DIM, SPACE_DIM >
AbstractCellBasedWriter (const std::string &rFileName)
virtual ~AbstractCellBasedWriter ()
void CloseFile ()
virtual void OpenOutputFile (OutputFileHandler &rOutputFileHandler)
void OpenOutputFileForAppend (OutputFileHandler &rOutputFileHandler)
virtual void WriteTimeStamp ()
virtual void WriteNewline ()
void SetFileName (std::string fileName)
std::string GetFileName ()
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Friends
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from AbstractCellBasedWriter< ELEMENT_DIM, SPACE_DIM >
std::string mFileName
out_stream mpOutStream
Detailed Description
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM>
class AbstractCellPopulationWriter< ELEMENT_DIM, SPACE_DIM >
Abstract class for a writer that takes information from an AbstractCellPopulation and writes it to file.
The key difference between this class and AbstractCellPopulationCountWriter is that writers inheriting from this class ARE compatible with a RoundRobin loop. For such writers, each process can write its part of the information without knowing anything about the other processes as long as they are not interfering with the writing itself.
Definition at line 60 of file AbstractCellPopulationWriter.hpp.
Constructor & Destructor Documentation
AbstractCellPopulationWriter()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> AbstractCellPopulationWriter< ELEMENT_DIM, SPACE_DIM >::AbstractCellPopulationWriter (const std::string & rFileName)
Default constructor.
Parameters
rFileName the name of the file to write to.
Definition at line 41 of file AbstractCellPopulationWriter.cpp.
Referenced by AbstractCellPopulationWriter< ELEMENT_DIM, SPACE_DIM >::serialize().
Member Function Documentation
serialize()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> template<class Archive > void AbstractCellPopulationWriter< ELEMENT_DIM, SPACE_DIM >::serialize (Archive & archive, const unsigned int version) inline private
Serialize the object and its member variables.
Parameters
archive the archive
version the current version of this class
Definition at line 72 of file AbstractCellPopulationWriter.hpp.
References AbstractCellPopulationWriter< ELEMENT_DIM, SPACE_DIM >::AbstractCellPopulationWriter(), AbstractCellPopulationWriter< ELEMENT_DIM, SPACE_DIM >::Visit(), and AbstractCellPopulationWriter< ELEMENT_DIM, SPACE_DIM >::WriteHeader().
Visit() [1/5]
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> virtual void AbstractCellPopulationWriter< ELEMENT_DIM, SPACE_DIM >::Visit (MeshBasedCellPopulation< ELEMENT_DIM, SPACE_DIM > * pCellPopulation) pure virtual
Visit the population and write the data.
As this method is pure virtual, it must be overridden in subclasses.
Parameters
pCellPopulation a pointer to the MeshBasedCellPopulation to visit.
Implemented in CellPopulationAdjacencyMatrixWriter< ELEMENT_DIM, SPACE_DIM >, RadialCellDataDistributionWriter< ELEMENT_DIM, SPACE_DIM >, BoundaryNodeWriter< ELEMENT_DIM, SPACE_DIM >, HeterotypicBoundaryLengthWriter< ELEMENT_DIM, SPACE_DIM >, NodeLocationWriter< ELEMENT_DIM, SPACE_DIM >, NodeVelocityWriter< ELEMENT_DIM, SPACE_DIM >, CellPopulationAreaWriter< ELEMENT_DIM, SPACE_DIM >, VoronoiDataWriter< ELEMENT_DIM, SPACE_DIM >, CellPopulationElementWriter< ELEMENT_DIM, SPACE_DIM >, VertexIntersectionSwapLocationsWriter< ELEMENT_DIM, SPACE_DIM >, VertexT1SwapLocationsWriter< ELEMENT_DIM, SPACE_DIM >, VertexT2SwapLocationsWriter< ELEMENT_DIM, SPACE_DIM >, and VertexT3SwapLocationsWriter< ELEMENT_DIM, SPACE_DIM >.
Referenced by AbstractCellPopulationWriter< ELEMENT_DIM, SPACE_DIM >::serialize().
Visit() [2/5]
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> virtual void AbstractCellPopulationWriter< ELEMENT_DIM, SPACE_DIM >::Visit (CaBasedCellPopulation< SPACE_DIM > * pCellPopulation) pure virtual
Visit the population and write the data.
As this method is pure virtual, it must be overridden in subclasses.
Parameters
pCellPopulation a pointer to the CaBasedCellPopulation to visit.
Implemented in CellPopulationAdjacencyMatrixWriter< ELEMENT_DIM, SPACE_DIM >, RadialCellDataDistributionWriter< ELEMENT_DIM, SPACE_DIM >, BoundaryNodeWriter< ELEMENT_DIM, SPACE_DIM >, NodeLocationWriter< ELEMENT_DIM, SPACE_DIM >, HeterotypicBoundaryLengthWriter< ELEMENT_DIM, SPACE_DIM >, CellPopulationAreaWriter< ELEMENT_DIM, SPACE_DIM >, NodeVelocityWriter< ELEMENT_DIM, SPACE_DIM >, VoronoiDataWriter< ELEMENT_DIM, SPACE_DIM >, CellPopulationElementWriter< ELEMENT_DIM, SPACE_DIM >, VertexIntersectionSwapLocationsWriter< ELEMENT_DIM, SPACE_DIM >, VertexT1SwapLocationsWriter< ELEMENT_DIM, SPACE_DIM >, VertexT2SwapLocationsWriter< ELEMENT_DIM, SPACE_DIM >, and VertexT3SwapLocationsWriter< ELEMENT_DIM, SPACE_DIM >.
Visit() [3/5]
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> virtual void AbstractCellPopulationWriter< ELEMENT_DIM, SPACE_DIM >::Visit (NodeBasedCellPopulation< SPACE_DIM > * pCellPopulation) pure virtual
Visit the population and write the data.
As this method is pure virtual, it must be overridden in subclasses.
Parameters
pCellPopulation a pointer to the NodeBasedCellPopulation to visit.
Implemented in CellPopulationAdjacencyMatrixWriter< ELEMENT_DIM, SPACE_DIM >, RadialCellDataDistributionWriter< ELEMENT_DIM, SPACE_DIM >, BoundaryNodeWriter< ELEMENT_DIM, SPACE_DIM >, NodeLocationWriter< ELEMENT_DIM, SPACE_DIM >, HeterotypicBoundaryLengthWriter< ELEMENT_DIM, SPACE_DIM >, CellPopulationAreaWriter< ELEMENT_DIM, SPACE_DIM >, NodeVelocityWriter< ELEMENT_DIM, SPACE_DIM >, VoronoiDataWriter< ELEMENT_DIM, SPACE_DIM >, CellPopulationElementWriter< ELEMENT_DIM, SPACE_DIM >, VertexIntersectionSwapLocationsWriter< ELEMENT_DIM, SPACE_DIM >, VertexT1SwapLocationsWriter< ELEMENT_DIM, SPACE_DIM >, VertexT2SwapLocationsWriter< ELEMENT_DIM, SPACE_DIM >, and VertexT3SwapLocationsWriter< ELEMENT_DIM, SPACE_DIM >.
Visit() [4/5]
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> virtual void AbstractCellPopulationWriter< ELEMENT_DIM, SPACE_DIM >::Visit (PottsBasedCellPopulation< SPACE_DIM > * pCellPopulation) pure virtual
Visit the population and write the data.
As this method is pure virtual, it must be overridden in subclasses.
Parameters
pCellPopulation a pointer to the PottsBasedCellPopulation to visit.
Implemented in CellPopulationAdjacencyMatrixWriter< ELEMENT_DIM, SPACE_DIM >, RadialCellDataDistributionWriter< ELEMENT_DIM, SPACE_DIM >, BoundaryNodeWriter< ELEMENT_DIM, SPACE_DIM >, NodeLocationWriter< ELEMENT_DIM, SPACE_DIM >, HeterotypicBoundaryLengthWriter< ELEMENT_DIM, SPACE_DIM >, CellPopulationAreaWriter< ELEMENT_DIM, SPACE_DIM >, NodeVelocityWriter< ELEMENT_DIM, SPACE_DIM >, CellPopulationElementWriter< ELEMENT_DIM, SPACE_DIM >, VoronoiDataWriter< ELEMENT_DIM, SPACE_DIM >, VertexIntersectionSwapLocationsWriter< ELEMENT_DIM, SPACE_DIM >, VertexT1SwapLocationsWriter< ELEMENT_DIM, SPACE_DIM >, VertexT2SwapLocationsWriter< ELEMENT_DIM, SPACE_DIM >, and VertexT3SwapLocationsWriter< ELEMENT_DIM, SPACE_DIM >.
Visit() [5/5]
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> virtual void AbstractCellPopulationWriter< ELEMENT_DIM, SPACE_DIM >::Visit (VertexBasedCellPopulation< SPACE_DIM > * pCellPopulation) pure virtual
Visit the population and write the data.
As this method is pure virtual, it must be overridden in subclasses.
Parameters
pCellPopulation a pointer to the VertexBasedCellPopulation to visit.
Implemented in CellPopulationAdjacencyMatrixWriter< ELEMENT_DIM, SPACE_DIM >, BoundaryNodeWriter< ELEMENT_DIM, SPACE_DIM >, NodeLocationWriter< ELEMENT_DIM, SPACE_DIM >, RadialCellDataDistributionWriter< ELEMENT_DIM, SPACE_DIM >, HeterotypicBoundaryLengthWriter< ELEMENT_DIM, SPACE_DIM >, CellPopulationAreaWriter< ELEMENT_DIM, SPACE_DIM >, NodeVelocityWriter< ELEMENT_DIM, SPACE_DIM >, CellPopulationElementWriter< ELEMENT_DIM, SPACE_DIM >, VertexIntersectionSwapLocationsWriter< ELEMENT_DIM, SPACE_DIM >, VertexT1SwapLocationsWriter< ELEMENT_DIM, SPACE_DIM >, VertexT2SwapLocationsWriter< ELEMENT_DIM, SPACE_DIM >, VertexT3SwapLocationsWriter< ELEMENT_DIM, SPACE_DIM >, and VoronoiDataWriter< ELEMENT_DIM, SPACE_DIM >.
WriteHeader()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void AbstractCellPopulationWriter< ELEMENT_DIM, SPACE_DIM >::WriteHeader (AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM > * pCellPopulation) virtual
Write the header to file.
Parameters
pCellPopulation a pointer to the population to be written.
Definition at line 47 of file AbstractCellPopulationWriter.cpp.
Referenced by AbstractCellPopulationWriter< ELEMENT_DIM, SPACE_DIM >::serialize().
Friends And Related Function Documentation
boost::serialization::access
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> friend class boost::serialization::access friend
Needed for serialization.
Definition at line 64 of file AbstractCellPopulationWriter.hpp.
The documentation for this class was generated from the following files:
cell_based/src/writers/population_writers/AbstractCellPopulationWriter.hpp
cell_based/src/writers/population_writers/AbstractCellPopulationWriter.cpp