Chaste: Alarcon2004OxygenBasedCellCycleOdeSystem Class Reference
Alarcon2004OxygenBasedCellCycleOdeSystem Class Reference
#include <Alarcon2004OxygenBasedCellCycleOdeSystem.hpp>
Public Member Functions
Alarcon2004OxygenBasedCellCycleOdeSystem (double oxygenConcentration, bool isLabelled, std::vector< double > stateVariables=std::vector< double >())
~Alarcon2004OxygenBasedCellCycleOdeSystem ()
void Init ()
void EvaluateYDerivatives (double time, const std::vector< double > &rY, std::vector< double > &rDY)
bool CalculateStoppingEvent (double time, const std::vector< double > &rY)
void SetIsLabelled (bool isLabelled)
bool IsLabelled () const
double GetOxygenConcentration () const
Public Member Functions inherited from AbstractOdeSystem
AbstractOdeSystem (unsigned numberOfStateVariables)
virtual ~AbstractOdeSystem ()
virtual double CalculateRootFunction (double time, const std::vector< double > &rY)
bool GetUseAnalyticJacobian ()
const std::vector< double > & rGetConstStateVariables () const
Public Member Functions inherited from AbstractParameterisedSystem< std::vector< double > >
AbstractParameterisedSystem (unsigned numberOfStateVariables)
std::vector< double > & rGetStateVariables ()
std::vector< double > GetStateVariables ()
void SetStateVariables (const std::vector< double > &rStateVariables)
double GetStateVariable (unsigned index) const
double GetStateVariable (const std::string &rName) const
void SetStateVariable (unsigned index, double newValue)
void SetStateVariable (const std::string &rName, double newValue)
virtual void VerifyStateVariables ()
void SetDefaultInitialConditions (const std::vector< double > &rInitialConditions)
void SetDefaultInitialCondition (unsigned index, double initialCondition)
std::vector< double > GetInitialConditions () const
void ResetToInitialConditions ()
double GetParameter (unsigned index) const
double GetParameter (const std::string &rName) const
void SetParameter (const std::string &rName, double value)
void SetParameter (unsigned index, double value)
double GetAnyVariable (unsigned index, double time=0.0, std::vector< double > *pDerivedQuantities=NULL)
double GetAnyVariable (const std::string &rName, double time=0.0, std::vector< double > *pDerivedQuantities=NULL)
void SetAnyVariable (unsigned index, double value)
void SetAnyVariable (const std::string &rName, double value)
virtual std::vector< double > ComputeDerivedQuantities (double time, const std::vector< double > &rState)
std::vector< double > ComputeDerivedQuantitiesFromCurrentState (double time)
Public Member Functions inherited from AbstractUntemplatedParameterisedSystem
AbstractUntemplatedParameterisedSystem (unsigned numberOfStateVariables)
virtual ~AbstractUntemplatedParameterisedSystem ()
boost::shared_ptr< const AbstractOdeSystemInformation > GetSystemInformation () const
std::string GetSystemName () const
unsigned GetNumberOfAttributes () const
bool HasAttribute (const std::string &rName) const
double GetAttribute (const std::string &rName) const
unsigned GetNumberOfStateVariables () const
const std::vector< std::string > & rGetStateVariableNames () const
const std::vector< std::string > & rGetStateVariableUnits () const
unsigned GetStateVariableIndex (const std::string &rName) const
bool HasStateVariable (const std::string &rName) const
std::string GetStateVariableUnits (unsigned index) const
unsigned GetNumberOfParameters () const
const std::vector< std::string > & rGetParameterNames () const
const std::vector< std::string > & rGetParameterUnits () const
unsigned GetParameterIndex (const std::string &rName) const
bool HasParameter (const std::string &rName) const
std::string GetParameterUnits (unsigned index) const
unsigned GetNumberOfDerivedQuantities () const
const std::vector< std::string > & rGetDerivedQuantityNames () const
const std::vector< std::string > & rGetDerivedQuantityUnits () const
unsigned GetDerivedQuantityIndex (const std::string &rName) const
bool HasDerivedQuantity (const std::string &rName) const
std::string GetDerivedQuantityUnits (unsigned index) const
unsigned GetAnyVariableIndex (const std::string &rName) const
bool HasAnyVariable (const std::string &rName) const
std::string GetAnyVariableUnits (unsigned index) const
std::string GetAnyVariableUnits (const std::string &rName) const
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Private Attributes
double ma1
double ma2
double ma3
double ma4
double mb3
double mb4
double mc1
double mc2
double md1
double md2
double mJ3
double mJ4
double mEta
double mMstar
double mB
double mxThreshold
double myThreshold
double mOxygenConcentration
bool mIsLabelled
Friends
class boost::serialization::access
Additional Inherited Members
Protected Member Functions inherited from AbstractParameterisedSystem< std::vector< double > >
std::string DumpState (const std::string &rMessage)
std::string DumpState (const std::string &rMessage, std::vector< double > Y)
std::string DumpState (const std::string &rMessage, std::vector< double > Y, double time)
void CheckParametersOnLoad (const std::vector< double > &rParameters, const std::vector< std::string > &rParameterNames)
Protected Attributes inherited from AbstractOdeSystem
bool mUseAnalyticJacobian
Protected Attributes inherited from AbstractParameterisedSystem< std::vector< double > >
std::vector< double > mStateVariables
std::vector< double > mParameters
Protected Attributes inherited from AbstractUntemplatedParameterisedSystem
unsigned mNumberOfStateVariables
boost::shared_ptr< AbstractOdeSystemInformation > mpSystemInfo
Detailed Description
Represents the Alarcon et al. (2004) system of ODEs (see ticket #461). [doi:10.1016/j.jtbi.2004.04.016]
The variables are
0. x = Cdh1-APC complexes 1. y = cyclin-CDK 2. z = p27 3. m = mass 4. u = RBNP 5. P = oxygen concentration
Definition at line 59 of file Alarcon2004OxygenBasedCellCycleOdeSystem.hpp.
Constructor & Destructor Documentation
Alarcon2004OxygenBasedCellCycleOdeSystem()
Alarcon2004OxygenBasedCellCycleOdeSystem::Alarcon2004OxygenBasedCellCycleOdeSystem (double oxygenConcentration, bool isLabelled, std::vector< double > stateVariables = std::vector<double>())
Constructor.
Parameters
oxygenConcentration is a non-dimensional oxygen concentration value between 0 and 1
isLabelled whether the cell associated with this cell cycle ODE system is labelled (this affects the ODE system)
stateVariables optional initial conditions for state variables (only used in archiving)
State variables
0. x = Cdh1-APC complexes 1. y = cyclin-CDK 2. z = p27 3. m = mass 4. u = RBNP 5. oxygenConcentration
Definition at line 39 of file Alarcon2004OxygenBasedCellCycleOdeSystem.cpp.
References Init(), ma1, mc1, mIsLabelled, mMstar, AbstractUntemplatedParameterisedSystem::mpSystemInfo, mxThreshold, myThreshold, AbstractParameterisedSystem< std::vector< double > >::SetDefaultInitialCondition(), and AbstractParameterisedSystem< std::vector< double > >::SetStateVariables().
Referenced by serialize().
~Alarcon2004OxygenBasedCellCycleOdeSystem()
Alarcon2004OxygenBasedCellCycleOdeSystem::~Alarcon2004OxygenBasedCellCycleOdeSystem ()
Destructor.
Definition at line 86 of file Alarcon2004OxygenBasedCellCycleOdeSystem.cpp.
Referenced by serialize().
Member Function Documentation
CalculateStoppingEvent()
bool Alarcon2004OxygenBasedCellCycleOdeSystem::CalculateStoppingEvent (double time, const std::vector< double > & rY) virtual
Calculate whether the conditions for the cell cycle to finish have been met.
Parameters
time at which to calculate whether the stopping event has occurred
rY value of the solution vector used to evaluate the RHS.
Returns
whether or not stopping conditions have been met
Reimplemented from AbstractOdeSystem.
Definition at line 158 of file Alarcon2004OxygenBasedCellCycleOdeSystem.cpp.
References mxThreshold, and myThreshold.
Referenced by serialize().
EvaluateYDerivatives()
void Alarcon2004OxygenBasedCellCycleOdeSystem::EvaluateYDerivatives (double time, const std::vector< double > & rY, std::vector< double > & rDY) virtual
Compute the RHS of the Alarcon et al. (2004) system of ODEs.
Returns a vector representing the RHS of the ODEs at each time step, y' = [y1' ... yn']. An ODE solver will call this function repeatedly to solve for y = [y1 ... yn].
Parameters
time used to evaluate the RHS.
rY value of the solution vector used to evaluate the RHS.
rDY filled in with the resulting derivatives (using Alarcons et al. (2004) system of equations).
Implements AbstractOdeSystem.
Definition at line 109 of file Alarcon2004OxygenBasedCellCycleOdeSystem.cpp.
Referenced by serialize().
GetOxygenConcentration()
double Alarcon2004OxygenBasedCellCycleOdeSystem::GetOxygenConcentration () const
Returns
mOxygenConcentration.
Definition at line 203 of file Alarcon2004OxygenBasedCellCycleOdeSystem.cpp.
References CHASTE_CLASS_EXPORT, and mOxygenConcentration.
Referenced by serialize().
Init()
void Alarcon2004OxygenBasedCellCycleOdeSystem::Init ()
Initialise parameter values.
Definition at line 91 of file Alarcon2004OxygenBasedCellCycleOdeSystem.cpp.
References ma2, ma3, ma4, mB, mb3, mb4, mc2, md1, md2, mEta, mJ3, mJ4, and mMstar.
Referenced by Alarcon2004OxygenBasedCellCycleOdeSystem(), and serialize().
IsLabelled()
bool Alarcon2004OxygenBasedCellCycleOdeSystem::IsLabelled () const
Returns
mIsLabelled.
Definition at line 198 of file Alarcon2004OxygenBasedCellCycleOdeSystem.cpp.
References mIsLabelled.
Referenced by serialize().
serialize()
template<class Archive > void Alarcon2004OxygenBasedCellCycleOdeSystem::serialize (Archive & archive, const unsigned int version) inline private
Serialize the object and its member variables.
Parameters
archive the archive
version the current version of this class
Definition at line 116 of file Alarcon2004OxygenBasedCellCycleOdeSystem.hpp.
References Alarcon2004OxygenBasedCellCycleOdeSystem(), CalculateStoppingEvent(), CHASTE_CLASS_EXPORT, EvaluateYDerivatives(), GetOxygenConcentration(), Init(), IsLabelled(), SetIsLabelled(), and ~Alarcon2004OxygenBasedCellCycleOdeSystem().
SetIsLabelled()
void Alarcon2004OxygenBasedCellCycleOdeSystem::SetIsLabelled (bool isLabelled)
Set mIsLabelled.
Parameters
isLabelled whether the cell associated with this cell cycle ODE system is labelled (this affects the ODE system)
Definition at line 193 of file Alarcon2004OxygenBasedCellCycleOdeSystem.cpp.
References mIsLabelled.
Referenced by serialize().
Member Data Documentation
ma1
double Alarcon2004OxygenBasedCellCycleOdeSystem::ma1 private
Constants for the Alarcon et al. (2004) modelDimensionless parameter a_1.
Definition at line 68 of file Alarcon2004OxygenBasedCellCycleOdeSystem.hpp.
Referenced by Alarcon2004OxygenBasedCellCycleOdeSystem().
ma2
double Alarcon2004OxygenBasedCellCycleOdeSystem::ma2 private
Dimensionless parameter a_2.
Definition at line 70 of file Alarcon2004OxygenBasedCellCycleOdeSystem.hpp.
Referenced by Init().
ma3
double Alarcon2004OxygenBasedCellCycleOdeSystem::ma3 private
Dimensionless parameter a_3.
Definition at line 72 of file Alarcon2004OxygenBasedCellCycleOdeSystem.hpp.
Referenced by Init().
ma4
double Alarcon2004OxygenBasedCellCycleOdeSystem::ma4 private
Dimensionless parameter a_4.
Definition at line 74 of file Alarcon2004OxygenBasedCellCycleOdeSystem.hpp.
Referenced by Init().
mB
double Alarcon2004OxygenBasedCellCycleOdeSystem::mB private
Dimensionless parameter B.
Definition at line 96 of file Alarcon2004OxygenBasedCellCycleOdeSystem.hpp.
Referenced by Init().
mb3
double Alarcon2004OxygenBasedCellCycleOdeSystem::mb3 private
Dimensionless parameter b_3.
Definition at line 76 of file Alarcon2004OxygenBasedCellCycleOdeSystem.hpp.
Referenced by Init().
mb4
double Alarcon2004OxygenBasedCellCycleOdeSystem::mb4 private
Dimensionless parameter b_4.
Definition at line 78 of file Alarcon2004OxygenBasedCellCycleOdeSystem.hpp.
Referenced by Init().
mc1
double Alarcon2004OxygenBasedCellCycleOdeSystem::mc1 private
Dimensionless parameter c_1.
Definition at line 80 of file Alarcon2004OxygenBasedCellCycleOdeSystem.hpp.
Referenced by Alarcon2004OxygenBasedCellCycleOdeSystem().
mc2
double Alarcon2004OxygenBasedCellCycleOdeSystem::mc2 private
Dimensionless parameter c_2.
Definition at line 82 of file Alarcon2004OxygenBasedCellCycleOdeSystem.hpp.
Referenced by Init().
md1
double Alarcon2004OxygenBasedCellCycleOdeSystem::md1 private
Dimensionless parameter d_1.
Definition at line 84 of file Alarcon2004OxygenBasedCellCycleOdeSystem.hpp.
Referenced by Init().
md2
double Alarcon2004OxygenBasedCellCycleOdeSystem::md2 private
Dimensionless parameter d_2.
Definition at line 86 of file Alarcon2004OxygenBasedCellCycleOdeSystem.hpp.
Referenced by Init().
mEta
double Alarcon2004OxygenBasedCellCycleOdeSystem::mEta private
Dimensionless parameter eta.
Definition at line 92 of file Alarcon2004OxygenBasedCellCycleOdeSystem.hpp.
Referenced by Init().
mIsLabelled
bool Alarcon2004OxygenBasedCellCycleOdeSystem::mIsLabelled private
Whether the cell associated with this cell cycle ODE system is labelled (this affects the ODE system).
Definition at line 106 of file Alarcon2004OxygenBasedCellCycleOdeSystem.hpp.
Referenced by Alarcon2004OxygenBasedCellCycleOdeSystem(), IsLabelled(), and SetIsLabelled().
mJ3
double Alarcon2004OxygenBasedCellCycleOdeSystem::mJ3 private
Dimensionless parameter J_3.
Definition at line 88 of file Alarcon2004OxygenBasedCellCycleOdeSystem.hpp.
Referenced by Init().
mJ4
double Alarcon2004OxygenBasedCellCycleOdeSystem::mJ4 private
Dimensionless parameter J_4.
Definition at line 90 of file Alarcon2004OxygenBasedCellCycleOdeSystem.hpp.
Referenced by Init().
mMstar
double Alarcon2004OxygenBasedCellCycleOdeSystem::mMstar private
Dimensionless parameter m_star.
Definition at line 94 of file Alarcon2004OxygenBasedCellCycleOdeSystem.hpp.
Referenced by Alarcon2004OxygenBasedCellCycleOdeSystem(), and Init().
mOxygenConcentration
double Alarcon2004OxygenBasedCellCycleOdeSystem::mOxygenConcentration private
The oxygen concentration (this affects the ODE system).
Definition at line 103 of file Alarcon2004OxygenBasedCellCycleOdeSystem.hpp.
Referenced by GetOxygenConcentration().
mxThreshold
double Alarcon2004OxygenBasedCellCycleOdeSystem::mxThreshold private
Dimensionless parameter x_THR.
Definition at line 98 of file Alarcon2004OxygenBasedCellCycleOdeSystem.hpp.
Referenced by Alarcon2004OxygenBasedCellCycleOdeSystem(), and CalculateStoppingEvent().
myThreshold
double Alarcon2004OxygenBasedCellCycleOdeSystem::myThreshold private
Dimensionless parameter y_THR.
Definition at line 100 of file Alarcon2004OxygenBasedCellCycleOdeSystem.hpp.
Referenced by Alarcon2004OxygenBasedCellCycleOdeSystem(), and CalculateStoppingEvent().
The documentation for this class was generated from the following files:
cell_based/src/odes/Alarcon2004OxygenBasedCellCycleOdeSystem.hpp
cell_based/src/odes/Alarcon2004OxygenBasedCellCycleOdeSystem.cpp