Chaste: Goldbeter1991OdeSystem Class Reference
Goldbeter1991OdeSystem Class Reference
#include <Goldbeter1991OdeSystem.hpp>
Public Member Functions
Goldbeter1991OdeSystem (std::vector< double > stateVariables=std::vector< double >())
~Goldbeter1991OdeSystem ()
void EvaluateYDerivatives (double time, const std::vector< double > &rY, std::vector< double > &rDY)
Public Member Functions inherited from AbstractOdeSystem
AbstractOdeSystem (unsigned numberOfStateVariables)
virtual ~AbstractOdeSystem ()
virtual bool CalculateStoppingEvent (double time, const std::vector< double > &rY)
virtual double CalculateRootFunction (double time, const std::vector< double > &rY)
bool GetUseAnalyticJacobian ()
const std::vector< double > & rGetConstStateVariables () const
Public Member Functions inherited from AbstractParameterisedSystem< std::vector< double > >
AbstractParameterisedSystem (unsigned numberOfStateVariables)
std::vector< double > & rGetStateVariables ()
std::vector< double > GetStateVariables ()
void SetStateVariables (const std::vector< double > &rStateVariables)
double GetStateVariable (unsigned index) const
double GetStateVariable (const std::string &rName) const
void SetStateVariable (unsigned index, double newValue)
void SetStateVariable (const std::string &rName, double newValue)
virtual void VerifyStateVariables ()
void SetDefaultInitialConditions (const std::vector< double > &rInitialConditions)
void SetDefaultInitialCondition (unsigned index, double initialCondition)
std::vector< double > GetInitialConditions () const
void ResetToInitialConditions ()
double GetParameter (unsigned index) const
double GetParameter (const std::string &rName) const
void SetParameter (const std::string &rName, double value)
void SetParameter (unsigned index, double value)
double GetAnyVariable (unsigned index, double time=0.0, std::vector< double > *pDerivedQuantities=NULL)
double GetAnyVariable (const std::string &rName, double time=0.0, std::vector< double > *pDerivedQuantities=NULL)
void SetAnyVariable (unsigned index, double value)
void SetAnyVariable (const std::string &rName, double value)
virtual std::vector< double > ComputeDerivedQuantities (double time, const std::vector< double > &rState)
std::vector< double > ComputeDerivedQuantitiesFromCurrentState (double time)
Public Member Functions inherited from AbstractUntemplatedParameterisedSystem
AbstractUntemplatedParameterisedSystem (unsigned numberOfStateVariables)
virtual ~AbstractUntemplatedParameterisedSystem ()
boost::shared_ptr< const AbstractOdeSystemInformation > GetSystemInformation () const
std::string GetSystemName () const
unsigned GetNumberOfAttributes () const
bool HasAttribute (const std::string &rName) const
double GetAttribute (const std::string &rName) const
unsigned GetNumberOfStateVariables () const
const std::vector< std::string > & rGetStateVariableNames () const
const std::vector< std::string > & rGetStateVariableUnits () const
unsigned GetStateVariableIndex (const std::string &rName) const
bool HasStateVariable (const std::string &rName) const
std::string GetStateVariableUnits (unsigned index) const
unsigned GetNumberOfParameters () const
const std::vector< std::string > & rGetParameterNames () const
const std::vector< std::string > & rGetParameterUnits () const
unsigned GetParameterIndex (const std::string &rName) const
bool HasParameter (const std::string &rName) const
std::string GetParameterUnits (unsigned index) const
unsigned GetNumberOfDerivedQuantities () const
const std::vector< std::string > & rGetDerivedQuantityNames () const
const std::vector< std::string > & rGetDerivedQuantityUnits () const
unsigned GetDerivedQuantityIndex (const std::string &rName) const
bool HasDerivedQuantity (const std::string &rName) const
std::string GetDerivedQuantityUnits (unsigned index) const
unsigned GetAnyVariableIndex (const std::string &rName) const
bool HasAnyVariable (const std::string &rName) const
std::string GetAnyVariableUnits (unsigned index) const
std::string GetAnyVariableUnits (const std::string &rName) const
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Friends
class boost::serialization::access
Additional Inherited Members
Protected Member Functions inherited from AbstractParameterisedSystem< std::vector< double > >
std::string DumpState (const std::string &rMessage)
std::string DumpState (const std::string &rMessage, std::vector< double > Y)
std::string DumpState (const std::string &rMessage, std::vector< double > Y, double time)
void CheckParametersOnLoad (const std::vector< double > &rParameters, const std::vector< std::string > &rParameterNames)
Protected Attributes inherited from AbstractOdeSystem
bool mUseAnalyticJacobian
Protected Attributes inherited from AbstractParameterisedSystem< std::vector< double > >
std::vector< double > mStateVariables
std::vector< double > mParameters
Protected Attributes inherited from AbstractUntemplatedParameterisedSystem
unsigned mNumberOfStateVariables
boost::shared_ptr< AbstractOdeSystemInformation > mpSystemInfo
Detailed Description
Goldbeter 1991 System
Definition at line 51 of file Goldbeter1991OdeSystem.hpp.
Constructor & Destructor Documentation
Goldbeter1991OdeSystem()
Goldbeter1991OdeSystem::Goldbeter1991OdeSystem (std::vector< double > stateVariables = std::vector<double>())
Todo:
extract model parameters as member variables
Default constructor.
Parameters
stateVariables optional initial conditions for state variables (only used in archiving)
The state variables are as follows:
0 - C (Cyclin) 1 - M (CDC-2 Kinase) 2 - X (Cyclin Protease)
Definition at line 39 of file Goldbeter1991OdeSystem.cpp.
References AbstractUntemplatedParameterisedSystem::mpSystemInfo, and AbstractParameterisedSystem< std::vector< double > >::SetStateVariables().
Referenced by serialize().
~Goldbeter1991OdeSystem()
Goldbeter1991OdeSystem::~Goldbeter1991OdeSystem ()
Destructor.
Definition at line 62 of file Goldbeter1991OdeSystem.cpp.
Referenced by serialize().
Member Function Documentation
EvaluateYDerivatives()
void Goldbeter1991OdeSystem::EvaluateYDerivatives (double time, const std::vector< double > & rY, std::vector< double > & rDY) virtual
Compute the RHS of the Collier et al. system of ODEs.
Returns a vector representing the RHS of the ODEs at each time step, y' = [y1' ... yn']. An ODE solver will call this function repeatedly to solve for y = [y1 ... yn].
Parameters
time used to evaluate the RHS.
rY value of the solution vector used to evaluate the RHS.
rDY filled in with the resulting derivatives (using Collier et al. system of equations).
Implements AbstractOdeSystem.
Definition at line 66 of file Goldbeter1991OdeSystem.cpp.
Referenced by serialize().
serialize()
template<class Archive > void Goldbeter1991OdeSystem::serialize (Archive & archive, const unsigned int version) inline private
Serialize the object and its member variables.
Parameters
archive the archive
version the current version of this class
Definition at line 63 of file Goldbeter1991OdeSystem.hpp.
References CHASTE_CLASS_EXPORT, EvaluateYDerivatives(), Goldbeter1991OdeSystem(), and ~Goldbeter1991OdeSystem().
The documentation for this class was generated from the following files:
cell_based/src/odes/Goldbeter1991OdeSystem.hpp
cell_based/src/odes/Goldbeter1991OdeSystem.cpp