Chaste: Alarcon2004OxygenBasedCellCycleModel Class Reference
Alarcon2004OxygenBasedCellCycleModel Class Reference
#include <Alarcon2004OxygenBasedCellCycleModel.hpp>
Public Member Functions
Alarcon2004OxygenBasedCellCycleModel (boost::shared_ptr< AbstractCellCycleModelOdeSolver > pOdeSolver=boost::shared_ptr< AbstractCellCycleModelOdeSolver >())
virtual void ResetForDivision ()
AbstractCellCycleModel * CreateCellCycleModel ()
void Initialise ()
virtual void OutputCellCycleModelParameters (out_stream &rParamsFile)
Public Member Functions inherited from AbstractOdeBasedPhaseBasedCellCycleModel
AbstractOdeBasedPhaseBasedCellCycleModel (double lastTime=SimulationTime::Instance() ->GetTime(), boost::shared_ptr< AbstractCellCycleModelOdeSolver > pOdeSolver=boost::shared_ptr< AbstractCellCycleModelOdeSolver >())
virtual ~AbstractOdeBasedPhaseBasedCellCycleModel ()
virtual void UpdateCellCyclePhase ()
double GetOdeStopTime ()
void SetBirthTime (double birthTime)
Public Member Functions inherited from AbstractPhaseBasedCellCycleModel
AbstractPhaseBasedCellCycleModel ()
virtual ~AbstractPhaseBasedCellCycleModel ()
virtual bool ReadyToDivide ()
CellCyclePhase GetCurrentCellCyclePhase () const
virtual double GetG1Duration () const
double GetStemCellG1Duration () const
double GetTransitCellG1Duration () const
double GetSG2MDuration () const
virtual double GetSDuration () const
virtual double GetG2Duration () const
virtual double GetMDuration () const
virtual void SetStemCellG1Duration (double stemCellG1Duration)
virtual void SetTransitCellG1Duration (double transitCellG1Duration)
void SetSDuration (double sDuration)
void SetG2Duration (double g2Duration)
void SetMDuration (double mDuration)
virtual double GetAverageTransitCellCycleTime ()
virtual double GetAverageStemCellCycleTime ()
double GetMinimumGapDuration () const
void SetMinimumGapDuration (double minimumGapDuration)
Public Member Functions inherited from AbstractCellCycleModel
AbstractCellCycleModel ()
virtual ~AbstractCellCycleModel ()
void SetCell (CellPtr pCell)
virtual void InitialiseDaughterCell ()
CellPtr GetCell ()
void SetDimension (unsigned dimension)
unsigned GetDimension () const
double GetBirthTime () const
double GetAge ()
virtual bool CanCellTerminallyDifferentiate ()
void OutputCellCycleModelInfo (out_stream &rParamsFile)
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Public Member Functions inherited from CellCycleModelOdeHandler
CellCycleModelOdeHandler (double lastTime=SimulationTime::Instance() ->GetTime(), boost::shared_ptr< AbstractCellCycleModelOdeSolver > pOdeSolver=boost::shared_ptr< AbstractCellCycleModelOdeSolver >())
virtual ~CellCycleModelOdeHandler ()
AbstractOdeSystem * GetOdeSystem () const
void SetOdeSystem (AbstractOdeSystem *pOdeSystem)
const boost::shared_ptr< AbstractCellCycleModelOdeSolver > GetOdeSolver () const
void SetLastTime (double lastTime)
double GetDt ()
void SetDt (double timeStep)
void SetStateVariables (const std::vector< double > &rStateVariables)
std::vector< double > GetProteinConcentrations () const
void SetProteinConcentrationsForTestsOnly (double lastTime, std::vector< double > proteinConcentrations)
Protected Member Functions
Alarcon2004OxygenBasedCellCycleModel (const Alarcon2004OxygenBasedCellCycleModel &rModel)
Protected Member Functions inherited from AbstractOdeBasedPhaseBasedCellCycleModel
AbstractOdeBasedPhaseBasedCellCycleModel (const AbstractOdeBasedPhaseBasedCellCycleModel &rModel)
Protected Member Functions inherited from AbstractPhaseBasedCellCycleModel
AbstractPhaseBasedCellCycleModel (const AbstractPhaseBasedCellCycleModel &rModel)
Protected Member Functions inherited from AbstractCellCycleModel
AbstractCellCycleModel (const AbstractCellCycleModel &rModel)
Protected Member Functions inherited from CellCycleModelOdeHandler
CellCycleModelOdeHandler (const CellCycleModelOdeHandler &rHandler)
bool SolveOdeToTime (double currentTime)
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
void AdjustOdeParameters (double currentTime)
Friends
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from AbstractOdeBasedPhaseBasedCellCycleModel
double mDivideTime
double mG2PhaseStartTime
Protected Attributes inherited from AbstractPhaseBasedCellCycleModel
CellCyclePhase mCurrentCellCyclePhase
double mG1Duration
double mMinimumGapDuration
double mStemCellG1Duration
double mTransitCellG1Duration
double mSDuration
double mG2Duration
double mMDuration
Protected Attributes inherited from AbstractCellCycleModel
CellPtr mpCell
double mBirthTime
bool mReadyToDivide
unsigned mDimension
Protected Attributes inherited from CellCycleModelOdeHandler
double mDt
AbstractOdeSystem * mpOdeSystem
boost::shared_ptr< AbstractCellCycleModelOdeSolver > mpOdeSolver
double mLastTime
bool mFinishedRunningOdes
Detailed Description
Oxygen-dependent ODE-based cell-cycle model.
Published by Alarcon et al. (doi:10.1016/j.jtbi.2004.04.016).
Definition at line 52 of file Alarcon2004OxygenBasedCellCycleModel.hpp.
Constructor & Destructor Documentation
Alarcon2004OxygenBasedCellCycleModel() [1/2]
Alarcon2004OxygenBasedCellCycleModel::Alarcon2004OxygenBasedCellCycleModel (const Alarcon2004OxygenBasedCellCycleModel & rModel) protected
Protected copy-constructor for use by CreateCellCycleModel. The only way for external code to create a copy of a cell cycle model is by calling that method, to ensure that a model of the correct subclass is created. This copy-constructor helps subclasses to ensure that all member variables are correctly copied when this happens.
This method is called by child classes to set member variables for a daughter cell upon cell division. Note that the parent cell cycle model will have had ResetForDivision() called just before CreateCellCycleModel() is called, so performing an exact copy of the parent is suitable behaviour. Any daughter-cell-specific initialisation can be done in InitialiseDaughterCell().
Parameters
rModel the cell cycle model to copy.
Definition at line 51 of file Alarcon2004OxygenBasedCellCycleModel.cpp.
References CellCycleModelOdeHandler::GetOdeSystem(), AbstractCellCycleModel::mpCell, AbstractParameterisedSystem< VECTOR >::rGetStateVariables(), CellCycleModelOdeHandler::SetOdeSystem(), and CellCycleModelOdeHandler::SetStateVariables().
Referenced by CreateCellCycleModel(), and serialize().
Alarcon2004OxygenBasedCellCycleModel() [2/2]
Alarcon2004OxygenBasedCellCycleModel::Alarcon2004OxygenBasedCellCycleModel (boost::shared_ptr< AbstractCellCycleModelOdeSolver > pOdeSolver = boost::shared_ptr<AbstractCellCycleModelOdeSolver>())
Default constructor.
Parameters
pOdeSolver An optional pointer to a cell-cycle model ODE solver object (allows the use of different ODE solvers)
Definition at line 40 of file Alarcon2004OxygenBasedCellCycleModel.cpp.
References CellCycleModelOdeSolver< CELL_CYCLE_MODEL, ODE_SOLVER >::Instance(), CellCycleModelOdeHandler::mpOdeSolver, and CellCycleModelOdeHandler::SetDt().
Member Function Documentation
AdjustOdeParameters()
void Alarcon2004OxygenBasedCellCycleModel::AdjustOdeParameters (double currentTime) private virtual
Adjust any ODE parameters needed before solving until currentTime.
Parameters
currentTime the time up to which the system will be solved.
Reimplemented from CellCycleModelOdeHandler.
Definition at line 105 of file Alarcon2004OxygenBasedCellCycleModel.cpp.
References AbstractCellCycleModel::mpCell, CellCycleModelOdeHandler::mpOdeSystem, and AbstractParameterisedSystem< VECTOR >::rGetStateVariables().
Referenced by serialize().
CreateCellCycleModel()
AbstractCellCycleModel * Alarcon2004OxygenBasedCellCycleModel::CreateCellCycleModel () virtual
Overridden builder method to create new copies of this cell-cycle model.
Returns
new cell-cycle model
Implements AbstractCellCycleModel.
Definition at line 74 of file Alarcon2004OxygenBasedCellCycleModel.cpp.
References Alarcon2004OxygenBasedCellCycleModel().
Referenced by serialize().
Initialise()
void Alarcon2004OxygenBasedCellCycleModel::Initialise (void) virtual
Initialise the cell-cycle model at the start of a simulation.
This overridden method sets up a new ODE system.
Reimplemented from AbstractCellCycleModel.
Definition at line 93 of file Alarcon2004OxygenBasedCellCycleModel.cpp.
References AbstractCellCycleModel::Initialise(), AbstractCellCycleModel::mpCell, and CellCycleModelOdeHandler::mpOdeSystem.
Referenced by serialize().
OutputCellCycleModelParameters()
void Alarcon2004OxygenBasedCellCycleModel::OutputCellCycleModelParameters (out_stream & rParamsFile) virtual
Overridden OutputCellCycleModelParameters() method.
Parameters
rParamsFile the file stream to which the parameters are output
Reimplemented from AbstractOdeBasedPhaseBasedCellCycleModel.
Definition at line 115 of file Alarcon2004OxygenBasedCellCycleModel.cpp.
References CHASTE_CLASS_EXPORT, and AbstractOdeBasedPhaseBasedCellCycleModel::OutputCellCycleModelParameters().
Referenced by serialize().
ResetForDivision()
void Alarcon2004OxygenBasedCellCycleModel::ResetForDivision () virtual
Resets the oxygen-based model to the start of the cell cycle (this model does not cycle naturally). Cells are given a new birth time and cell cycle proteins are reset. Note that the oxygen concentration maintains its current value.
Should only be called by the Cell Divide() method.
Reimplemented from AbstractOdeBasedPhaseBasedCellCycleModel.
Definition at line 79 of file Alarcon2004OxygenBasedCellCycleModel.cpp.
References AbstractParameterisedSystem< VECTOR >::GetInitialConditions(), CellCycleModelOdeHandler::mpOdeSystem, and AbstractOdeBasedPhaseBasedCellCycleModel::ResetForDivision().
Referenced by serialize().
serialize()
template<class Archive > void Alarcon2004OxygenBasedCellCycleModel::serialize (Archive & archive, const unsigned int version) inline private
Archive the cell-cycle model and ODE system.
Parameters
archive the archive
version the archive version
Definition at line 65 of file Alarcon2004OxygenBasedCellCycleModel.hpp.
References AdjustOdeParameters(), Alarcon2004OxygenBasedCellCycleModel(), CHASTE_CLASS_EXPORT, CreateCellCycleModel(), Initialise(), OutputCellCycleModelParameters(), and ResetForDivision().
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Needed for serialization.
Definition at line 57 of file Alarcon2004OxygenBasedCellCycleModel.hpp.
The documentation for this class was generated from the following files:
cell_based/src/cell/cycle/Alarcon2004OxygenBasedCellCycleModel.hpp
cell_based/src/cell/cycle/Alarcon2004OxygenBasedCellCycleModel.cpp