Chaste: CellId Class Reference
CellId Class Reference
#include <CellId.hpp>
Public Member Functions
CellId ()
virtual ~CellId ()
void AssignCellId ()
unsigned GetMaxCellId () const
unsigned GetCellId () const
Public Member Functions inherited from AbstractCellProperty
AbstractCellProperty ()
virtual ~AbstractCellProperty ()
template<class CLASS >
bool IsType () const
template<class BASECLASS >
bool IsSubType () const
bool IsSame (const AbstractCellProperty *pOther) const
bool IsSame (boost::shared_ptr< const AbstractCellProperty > pOther) const
void IncrementCellCount ()
void DecrementCellCount ()
unsigned GetCellCount () const
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Static Public Member Functions
static void ResetMaxCellId ()
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Private Attributes
unsigned mCellId
Static Private Attributes
static unsigned mMaxCellId = 0
Friends
class boost::serialization::access
Detailed Description
Cell id class.
Each Cell owns a CellPropertyCollection, which may include a shared pointer to an object of this type. When a Cell divides a new object is created with the new cell id.
The CellId object that stores the value of a the cell identifier.
Definition at line 57 of file CellId.hpp.
Constructor & Destructor Documentation
CellId()
CellId::CellId ()
Constructor.
This doesn't do anything and AssignCellId must be called before doing anything
Definition at line 41 of file CellId.cpp.
References mCellId, and UNSIGNED_UNSET.
Referenced by serialize().
~CellId()
CellId::~CellId () virtual
Destructor.
Definition at line 47 of file CellId.cpp.
Referenced by serialize().
Member Function Documentation
AssignCellId()
void CellId::AssignCellId ()
This assigns the cell id to be the maximum current cell id. It then increments mMaxCellId.
Definition at line 51 of file CellId.cpp.
References PetscTools::GetMyRank(), PetscTools::GetNumProcs(), mCellId, and mMaxCellId.
Referenced by serialize().
GetCellId()
unsigned CellId::GetCellId () const
Returns
mCellId.
Definition at line 57 of file CellId.cpp.
References EXCEPTION, mCellId, and UNSIGNED_UNSET.
Referenced by Cell::GetCellId(), and serialize().
GetMaxCellId()
unsigned CellId::GetMaxCellId () const
Returns
the maximum value of the cell identifier
Definition at line 66 of file CellId.cpp.
References EXCEPTION, mCellId, mMaxCellId, and UNSIGNED_UNSET.
Referenced by serialize().
ResetMaxCellId()
void CellId::ResetMaxCellId () static
Reset the maximum cell id to zero.
Definition at line 75 of file CellId.cpp.
References CHASTE_CLASS_EXPORT, and mMaxCellId.
Referenced by serialize(), and AbstractCellBasedTestSuite::setUp().
serialize()
template<class Archive > void CellId::serialize (Archive & archive, const unsigned int version) inline private
Archive the member variables.
Parameters
archive the archive
version the current version of this class
Definition at line 78 of file CellId.hpp.
References AssignCellId(), CellId(), CHASTE_CLASS_EXPORT, GetCellId(), GetMaxCellId(), PetscTools::IsParallel(), mCellId, mMaxCellId, ResetMaxCellId(), and ~CellId().
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Needed for serialization.
Definition at line 70 of file CellId.hpp.
Member Data Documentation
mCellId
unsigned CellId::mCellId private
Cell Id
Definition at line 64 of file CellId.hpp.
Referenced by AssignCellId(), CellId(), GetCellId(), GetMaxCellId(), and serialize().
mMaxCellId
unsigned CellId::mMaxCellId = 0 static private
maximum cell identifier.
Definition at line 67 of file CellId.hpp.
Referenced by AssignCellId(), GetMaxCellId(), ResetMaxCellId(), and serialize().
The documentation for this class was generated from the following files:
cell_based/src/cell/properties/CellId.hpp
cell_based/src/cell/properties/CellId.cpp