Chaste: SimpleTargetAreaModifier< DIM > Class Template Reference
SimpleTargetAreaModifier< DIM > Class Template Reference
#include <SimpleTargetAreaModifier.hpp>
Public Member Functions
SimpleTargetAreaModifier ()
virtual ~SimpleTargetAreaModifier ()
virtual void UpdateTargetAreaOfCell (const CellPtr pCell)
double GetGrowthDuration ()
void SetGrowthDuration (double growthDuration)
void OutputSimulationModifierParameters (out_stream &rParamsFile)
Public Member Functions inherited from AbstractTargetAreaModifier< DIM >
AbstractTargetAreaModifier ()
virtual ~AbstractTargetAreaModifier ()
virtual void UpdateAtEndOfTimeStep (AbstractCellPopulation< DIM, DIM > &rCellPopulation)
virtual void SetupSolve (AbstractCellPopulation< DIM, DIM > &rCellPopulation, std::string outputDirectory)
double GetReferenceTargetArea ()
void SetReferenceTargetArea (double referenceTargetArea)
void UpdateTargetAreas (AbstractCellPopulation< DIM, DIM > &rCellPopulation)
Public Member Functions inherited from AbstractCellBasedSimulationModifier< DIM, DIM >
AbstractCellBasedSimulationModifier ()
virtual ~AbstractCellBasedSimulationModifier ()
virtual void UpdateAtEndOfTimeStep (AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM > &rCellPopulation)=0
virtual void UpdateAtEndOfOutputTimeStep (AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM > &rCellPopulation)
virtual void SetupSolve (AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM > &rCellPopulation, std::string outputDirectory)=0
virtual void UpdateAtEndOfSolve (AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM > &rCellPopulation)
void OutputSimulationModifierInfo (out_stream &rParamsFile)
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Private Attributes
double mGrowthDuration
Friends
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from AbstractTargetAreaModifier< DIM >
double mReferenceTargetArea
Detailed Description
template<unsigned DIM>
class SimpleTargetAreaModifier< DIM >
A target area modifier class in which the target area of a cell grows linearly, up to mReferenceTargetArea, over a prescribed duration.
If used with a phase-based cell-cycle model (such as FixedG1GenerationalCellCycleModel), the target area of a cell increases linearly from the value 0.5*mReferenceTargetArea up to mReferenceTargetArea over the course of the cell's G1 phase.
If used with a non-phase-based cell-cycle model, the target area of a cell increases linearly from the value 0.5*mReferenceTargetArea up to mReferenceTargetArea while the cell's age is less than mGrowthDuration.
Here mReferenceTargetArea and mGrowthDuration are settable member variables. The default value of mReferenceTargetArea is 1.0 and the default value of mGrowthDuration is DOUBLE_UNSET.
Note that if mGrowthDuration is set by the user, then this value is are used to prescribe target area growth as described earlier, regardless of whether a phase-based cell-cycle model is present.
Definition at line 63 of file SimpleTargetAreaModifier.hpp.
Constructor & Destructor Documentation
SimpleTargetAreaModifier()
template<unsigned DIM> SimpleTargetAreaModifier< DIM >::SimpleTargetAreaModifier ()
Default constructor.
Definition at line 41 of file SimpleTargetAreaModifier.cpp.
~SimpleTargetAreaModifier()
template<unsigned DIM> SimpleTargetAreaModifier< DIM >::~SimpleTargetAreaModifier () virtual
Destructor.
Definition at line 48 of file SimpleTargetAreaModifier.cpp.
Member Function Documentation
GetGrowthDuration()
template<unsigned DIM> double SimpleTargetAreaModifier< DIM >::GetGrowthDuration ()
Returns
mGrowthDuration
Definition at line 124 of file SimpleTargetAreaModifier.cpp.
References SimpleTargetAreaModifier< DIM >::mGrowthDuration.
OutputSimulationModifierParameters()
template<unsigned DIM> void SimpleTargetAreaModifier< DIM >::OutputSimulationModifierParameters (out_stream & rParamsFile) virtual
Overridden OutputSimulationModifierParameters() method. Output any simulation modifier parameters to file.
Parameters
rParamsFile the file stream to which the parameters are output
Reimplemented from AbstractTargetAreaModifier< DIM >.
Definition at line 137 of file SimpleTargetAreaModifier.cpp.
References EXPORT_TEMPLATE_CLASS_SAME_DIMS, SimpleTargetAreaModifier< DIM >::mGrowthDuration, and AbstractTargetAreaModifier< DIM >::OutputSimulationModifierParameters().
serialize()
template<unsigned DIM> template<class Archive > void SimpleTargetAreaModifier< DIM >::serialize (Archive & archive, const unsigned int version) inline private
Boost Serialization method for archiving/checkpointing. Archives the object and its member variables.
Parameters
archive The boost archive.
version The current version of this class.
Definition at line 75 of file SimpleTargetAreaModifier.hpp.
References SimpleTargetAreaModifier< DIM >::mGrowthDuration.
SetGrowthDuration()
template<unsigned DIM> void SimpleTargetAreaModifier< DIM >::SetGrowthDuration (double growthDuration)
Set mGrowthDuration.
Parameters
growthDuration the new value of mGrowthDuration
Definition at line 130 of file SimpleTargetAreaModifier.cpp.
References SimpleTargetAreaModifier< DIM >::mGrowthDuration.
UpdateTargetAreaOfCell()
template<unsigned DIM> void SimpleTargetAreaModifier< DIM >::UpdateTargetAreaOfCell (const CellPtr pCell) virtual
Overridden UpdateTargetAreaOfCell() method.
Parameters
pCell pointer to the cell
At division, daughter cells inherit the cell data array from the mother cell. Here, we assign the target area that we want daughter cells to have to cells that we know to divide in this time step.
Todo:
This is a little hack that we might want to clean up in the future.
Implements AbstractTargetAreaModifier< DIM >.
Definition at line 53 of file SimpleTargetAreaModifier.cpp.
References DOUBLE_UNSET, EXCEPTION, AbstractPhaseBasedCellCycleModel::GetG1Duration(), SimulationTime::GetTime(), AbstractPhaseBasedCellCycleModel::GetTransitCellG1Duration(), SimulationTime::Instance(), SimpleTargetAreaModifier< DIM >::mGrowthDuration, and AbstractTargetAreaModifier< DIM >::mReferenceTargetArea.
Friends And Related Function Documentation
boost::serialization::access
template<unsigned DIM> friend class boost::serialization::access friend
Needed for serialization.
Definition at line 66 of file SimpleTargetAreaModifier.hpp.
Member Data Documentation
mGrowthDuration
template<unsigned DIM> double SimpleTargetAreaModifier< DIM >::mGrowthDuration private
The duration that a cell's target area to increase from 0.5*mReferenceTargetArea to mReferenceTargetArea at the start of its cell cycle. Defaults to DOUBLE_UNSET. If this variable is set using SetGrowthDuration(), then it is used regardless of whether a phase-based cell-cycle model is used.
Definition at line 87 of file SimpleTargetAreaModifier.hpp.
Referenced by SimpleTargetAreaModifier< DIM >::GetGrowthDuration(), SimpleTargetAreaModifier< DIM >::OutputSimulationModifierParameters(), SimpleTargetAreaModifier< DIM >::serialize(), SimpleTargetAreaModifier< DIM >::SetGrowthDuration(), and SimpleTargetAreaModifier< DIM >::UpdateTargetAreaOfCell().
The documentation for this class was generated from the following files:
cell_based/src/simulation/modifiers/SimpleTargetAreaModifier.hpp
cell_based/src/simulation/modifiers/SimpleTargetAreaModifier.cpp