Chaste: BuskeAdhesiveForce< DIM > Class Template Reference
BuskeAdhesiveForce< DIM > Class Template Reference
#include <BuskeAdhesiveForce.hpp>
Public Member Functions
BuskeAdhesiveForce ()
double GetAdhesionEnergyParameter ()
void SetAdhesionEnergyParameter (double adhesionEnergyParameter)
c_vector< double, DIM > CalculateForceBetweenNodes (unsigned nodeAGlobalIndex, unsigned nodeBGlobalIndex, AbstractCellPopulation< DIM > &rCellPopulation)
double GetMagnitudeOfForce (double distanceBetweenNodes, double radiusOfCellOne, double radiusOfCellTwo)
virtual void OutputForceParameters (out_stream &rParamsFile)
Public Member Functions inherited from AbstractTwoBodyInteractionForce< DIM >
AbstractTwoBodyInteractionForce ()
bool GetUseCutOffLength ()
void SetCutOffLength (double cutOffLength)
double GetCutOffLength ()
virtual c_vector< double, ELEMENT_DIM > CalculateForceBetweenNodes (unsigned nodeAGlobalIndex, unsigned nodeBGlobalIndex, AbstractCellPopulation< ELEMENT_DIM, ELEMENT_DIM > &rCellPopulation)=0
void AddForceContribution (AbstractCellPopulation< ELEMENT_DIM, ELEMENT_DIM > &rCellPopulation)
virtual void WriteDataToVisualizerSetupFile (out_stream &pVizSetupFile)
Public Member Functions inherited from AbstractForce< ELEMENT_DIM, ELEMENT_DIM >
AbstractForce ()
virtual ~AbstractForce ()
virtual void AddForceContribution (AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM > &rCellPopulation)=0
void OutputForceInfo (out_stream &rParamsFile)
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Private Attributes
double mAdhesionEnergyParameter
Friends
class TestForcesNotForRelease
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from AbstractTwoBodyInteractionForce< DIM >
bool mUseCutOffLength
double mMechanicsCutOffLength
Detailed Description
template<unsigned DIM>
class BuskeAdhesiveForce< DIM >
A force law employed by Buske et al (2011) in their overlapping spheres model of the intestinal crypt (doi:10.1371/journal.pcbi.1001045).
Length is scaled by natural length.
Todo:
does this mean natural radius of a cell? If so at what age? (#1764) Time is in hours.
Definition at line 52 of file BuskeAdhesiveForce.hpp.
Constructor & Destructor Documentation
BuskeAdhesiveForce()
template<unsigned DIM> BuskeAdhesiveForce< DIM >::BuskeAdhesiveForce ()
Constructor.
Definition at line 39 of file BuskeAdhesiveForce.cpp.
Member Function Documentation
CalculateForceBetweenNodes()
template<unsigned DIM> c_vector< double, DIM > BuskeAdhesiveForce< DIM >::CalculateForceBetweenNodes (unsigned nodeAGlobalIndex, unsigned nodeBGlobalIndex, AbstractCellPopulation< DIM > & rCellPopulation)
Returns
the force between two nodes.
Note that this assumes they are connected and is called by rCalculateVelocitiesOfEachNode()
Parameters
nodeAGlobalIndex index of one neighbouring node
nodeBGlobalIndex index of the other neighbouring node
rCellPopulation the cell population
Definition at line 58 of file BuskeAdhesiveForce.cpp.
References AbstractTwoBodyInteractionForce< DIM >::GetCutOffLength(), BuskeAdhesiveForce< DIM >::GetMagnitudeOfForce(), AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::GetNode(), Node< SPACE_DIM >::GetRadius(), AbstractTwoBodyInteractionForce< DIM >::mUseCutOffLength, and Node< SPACE_DIM >::rGetLocation().
GetAdhesionEnergyParameter()
template<unsigned DIM> double BuskeAdhesiveForce< DIM >::GetAdhesionEnergyParameter ()
Returns
mAdhesionEnergyParameter.
Definition at line 46 of file BuskeAdhesiveForce.cpp.
References BuskeAdhesiveForce< DIM >::mAdhesionEnergyParameter.
GetMagnitudeOfForce()
template<unsigned DIM> double BuskeAdhesiveForce< DIM >::GetMagnitudeOfForce (double distanceBetweenNodes, double radiusOfCellOne, double radiusOfCellTwo)
Returns
Calculated magnitude of the force between two nodes that are a given distance apart and are associated with given cell radii.
Parameters
distanceBetweenNodes the distance between two nodes
radiusOfCellOne radius of a cell
radiusOfCellTwo radius of a cell
Definition at line 107 of file BuskeAdhesiveForce.cpp.
References BuskeAdhesiveForce< DIM >::mAdhesionEnergyParameter.
Referenced by BuskeAdhesiveForce< DIM >::CalculateForceBetweenNodes().
OutputForceParameters()
template<unsigned DIM> void BuskeAdhesiveForce< DIM >::OutputForceParameters (out_stream & rParamsFile) virtual
Overridden OutputForceParameters() method.
Parameters
rParamsFile the file stream to which the parameters are output
Reimplemented from AbstractTwoBodyInteractionForce< DIM >.
Definition at line 124 of file BuskeAdhesiveForce.cpp.
References EXPORT_TEMPLATE_CLASS_SAME_DIMS, BuskeAdhesiveForce< DIM >::mAdhesionEnergyParameter, and AbstractTwoBodyInteractionForce< ELEMENT_DIM, SPACE_DIM >::OutputForceParameters().
serialize()
template<unsigned DIM> template<class Archive > void BuskeAdhesiveForce< DIM >::serialize (Archive & archive, const unsigned int version) inline private
Archive the object and its member variables.
Parameters
archive the archive
version the current version of this class
Definition at line 66 of file BuskeAdhesiveForce.hpp.
References BuskeAdhesiveForce< DIM >::mAdhesionEnergyParameter.
SetAdhesionEnergyParameter()
template<unsigned DIM> void BuskeAdhesiveForce< DIM >::SetAdhesionEnergyParameter (double adhesionEnergyParameter)
Set mAdhesionEnergyParameter.
Parameters
adhesionEnergyParameter the new value of mAdhesionEnergyParameter
Definition at line 52 of file BuskeAdhesiveForce.cpp.
References BuskeAdhesiveForce< DIM >::mAdhesionEnergyParameter.
Friends And Related Function Documentation
boost::serialization::access
template<unsigned DIM> friend class boost::serialization::access friend
Needed for serialization.
Definition at line 58 of file BuskeAdhesiveForce.hpp.
Member Data Documentation
mAdhesionEnergyParameter
template<unsigned DIM> double BuskeAdhesiveForce< DIM >::mAdhesionEnergyParameter private
Adhesion energy parameter.
Represented by the parameter epsilon in the model by Buske et al (2011) in their off-lattice model of the intestinal crypt (doi:10.1371/journal.pcbi.1001045).
Definition at line 79 of file BuskeAdhesiveForce.hpp.
Referenced by BuskeAdhesiveForce< DIM >::GetAdhesionEnergyParameter(), BuskeAdhesiveForce< DIM >::GetMagnitudeOfForce(), BuskeAdhesiveForce< DIM >::OutputForceParameters(), BuskeAdhesiveForce< DIM >::serialize(), and BuskeAdhesiveForce< DIM >::SetAdhesionEnergyParameter().
The documentation for this class was generated from the following files:
cell_based/src/population/forces/BuskeAdhesiveForce.hpp
cell_based/src/population/forces/BuskeAdhesiveForce.cpp