Chaste: ChemotaxisPottsUpdateRule< DIM > Class Template Reference
ChemotaxisPottsUpdateRule< DIM > Class Template Reference
#include <ChemotaxisPottsUpdateRule.hpp>
Public Member Functions
ChemotaxisPottsUpdateRule ()
~ChemotaxisPottsUpdateRule ()
double EvaluateHamiltonianContribution (unsigned currentNodeIndex, unsigned targetNodeIndex, PottsBasedCellPopulation< DIM > &rCellPopulation)
void OutputUpdateRuleParameters (out_stream &rParamsFile)
Public Member Functions inherited from AbstractPottsUpdateRule< DIM >
AbstractPottsUpdateRule ()
virtual ~AbstractPottsUpdateRule ()
Public Member Functions inherited from AbstractUpdateRule< DIM >
AbstractUpdateRule ()
virtual ~AbstractUpdateRule ()
void OutputUpdateRuleInfo (out_stream &rParamsFile)
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Friends
class TestPottsUpdateRules
class boost::serialization::access
Detailed Description
template<unsigned DIM>
class ChemotaxisPottsUpdateRule< DIM >
A simple update rule class to represent simple chemotaxis in the positive x y z direction for use in Potts based simulations.
Note this currently assumes cells don't grow, i.e the target volume is constant for each cell over time.
Definition at line 52 of file ChemotaxisPottsUpdateRule.hpp.
Constructor & Destructor Documentation
ChemotaxisPottsUpdateRule()
template<unsigned DIM> ChemotaxisPottsUpdateRule< DIM >::ChemotaxisPottsUpdateRule ()
Constructor.
Definition at line 39 of file ChemotaxisPottsUpdateRule.cpp.
Referenced by ChemotaxisPottsUpdateRule< DIM >::serialize().
~ChemotaxisPottsUpdateRule()
template<unsigned DIM> ChemotaxisPottsUpdateRule< DIM >::~ChemotaxisPottsUpdateRule ()
Destructor.
Definition at line 45 of file ChemotaxisPottsUpdateRule.cpp.
Referenced by ChemotaxisPottsUpdateRule< DIM >::serialize().
Member Function Documentation
EvaluateHamiltonianContribution()
template<unsigned DIM> double ChemotaxisPottsUpdateRule< DIM >::EvaluateHamiltonianContribution (unsigned currentNodeIndex, unsigned targetNodeIndex, PottsBasedCellPopulation< DIM > & rCellPopulation) virtual
Overridden EvaluateHamiltonianContribution() method
Assigns a greater propensity for moving in an increasing x, y (and z) direction.
Parameters
currentNodeIndex The index of the current node/lattice site
targetNodeIndex The index of the target node/lattice site
rCellPopulation The cell population
Returns
The difference in the Hamiltonian with the configuration of the target node having the same spin as the current node with the current configuration. i.e H_1-H_0
Implements AbstractPottsUpdateRule< DIM >.
Definition at line 50 of file ChemotaxisPottsUpdateRule.cpp.
References PottsBasedCellPopulation< DIM >::GetNode().
Referenced by ChemotaxisPottsUpdateRule< DIM >::serialize().
OutputUpdateRuleParameters()
template<unsigned DIM> void ChemotaxisPottsUpdateRule< DIM >::OutputUpdateRuleParameters (out_stream & rParamsFile) virtual
Overridden OutputUpdateRuleParameters() method.
Parameters
rParamsFile the file stream to which the parameters are output
Reimplemented from AbstractPottsUpdateRule< DIM >.
Definition at line 78 of file ChemotaxisPottsUpdateRule.cpp.
References EXPORT_TEMPLATE_CLASS_SAME_DIMS, and AbstractPottsUpdateRule< DIM >::OutputUpdateRuleParameters().
Referenced by ChemotaxisPottsUpdateRule< DIM >::serialize().
serialize()
template<unsigned DIM> template<class Archive > void ChemotaxisPottsUpdateRule< DIM >::serialize (Archive & archive, const unsigned int version) inline private
Boost Serialization method for archiving/checkpointing. Archives the object and its member variables.
Parameters
archive The boost archive.
version The current version of this class.
Definition at line 67 of file ChemotaxisPottsUpdateRule.hpp.
References ChemotaxisPottsUpdateRule< DIM >::ChemotaxisPottsUpdateRule(), ChemotaxisPottsUpdateRule< DIM >::EvaluateHamiltonianContribution(), EXPORT_TEMPLATE_CLASS_SAME_DIMS, ChemotaxisPottsUpdateRule< DIM >::OutputUpdateRuleParameters(), and ChemotaxisPottsUpdateRule< DIM >::~ChemotaxisPottsUpdateRule().
The documentation for this class was generated from the following files:
cell_based/src/population/update_rules/ChemotaxisPottsUpdateRule.hpp
cell_based/src/population/update_rules/ChemotaxisPottsUpdateRule.cpp