Chaste: RegularStimulusZeroNetCharge Class Reference
RegularStimulusZeroNetCharge Class Reference
#include <RegularStimulusZeroNetCharge.hpp>
Public Member Functions
RegularStimulusZeroNetCharge (double magnitudeOfStimulus, double duration, double period, double startTime, double stopTime=DBL_MAX)
double GetStimulus (double time)
Public Member Functions inherited from RegularStimulus
RegularStimulus (double magnitudeOfStimulus, double duration, double period, double startTime, double stopTime=DBL_MAX)
double GetPeriod ()
double GetMagnitude ()
double GetDuration ()
double GetStartTime ()
void SetMagnitude (double magnitude)
void SetPeriod (double period)
void SetDuration (double duration)
void SetStartTime (double startTime)
void SetStopTime (double stopTime)
Public Member Functions inherited from AbstractStimulusFunction
virtual ~AbstractStimulusFunction ()
virtual void Clear ()
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Friends
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from RegularStimulus
double mMagnitudeOfStimulus
double mDuration
double mPeriod
double mStartTime
double mStopTime
Detailed Description
Provides a periodic square-wave stimulus, where the total net charge is zero for every stimulus.
i.e., -------- | | | | -------- | ------------- | | | | --------
<————> Duration
Definition at line 60 of file RegularStimulusZeroNetCharge.hpp.
Constructor & Destructor Documentation
RegularStimulusZeroNetCharge()
RegularStimulusZeroNetCharge::RegularStimulusZeroNetCharge (double magnitudeOfStimulus, double duration, double period, double startTime, double stopTime = DBL_MAX)
Create a new stimulus.
Parameters
magnitudeOfStimulus The size of the stimulus, both positive and negative
duration How long the stimulus is applied for (time positive + time negative)
period The time between square waves being applied
startTime The time at which the first wave is applied
stopTime The time the stimulus is removed (defaults to DBL_MAX if omitted)
Definition at line 40 of file RegularStimulusZeroNetCharge.cpp.
Referenced by serialize().
Member Function Documentation
GetStimulus()
double RegularStimulusZeroNetCharge::GetStimulus (double time) virtual
Get the magnitude of stimulus at time 'time'. Re-implemented from parent class RegulsrStimulus.
Parameters
time The current time
Returns
Magnitude of stimulus at time 'time'.
Reimplemented from RegularStimulus.
Definition at line 46 of file RegularStimulusZeroNetCharge.cpp.
References CHASTE_CLASS_EXPORT, RegularStimulus::mDuration, RegularStimulus::mMagnitudeOfStimulus, RegularStimulus::mPeriod, RegularStimulus::mStartTime, and RegularStimulus::mStopTime.
Referenced by serialize().
serialize()
template<class Archive > void RegularStimulusZeroNetCharge::serialize (Archive & archive, const unsigned int version) inline private
Archive the simple stimulus, never used directly - boost uses this.
Parameters
archive
version
Definition at line 72 of file RegularStimulusZeroNetCharge.hpp.
References CHASTE_CLASS_EXPORT, GetStimulus(), and RegularStimulusZeroNetCharge().
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Needed for serialization.
Definition at line 64 of file RegularStimulusZeroNetCharge.hpp.
The documentation for this class was generated from the following files:
heart/src/stimulus/RegularStimulusZeroNetCharge.hpp
heart/src/stimulus/RegularStimulusZeroNetCharge.cpp