Chaste: FakeBathCell Class Reference
FakeBathCell Class Reference
#include <FakeBathCell.hpp>
Public Member Functions
FakeBathCell (boost::shared_ptr< AbstractIvpOdeSolver > pSolver, boost::shared_ptr< AbstractStimulusFunction > pIntracellularStimulus)
~FakeBathCell ()
void EvaluateYDerivatives (double time, const std::vector< double > &rY, std::vector< double > &rDY)
double GetIIonic (const std::vector< double > *pStateVariables=NULL)
void ComputeExceptVoltage (double tStart, double tEnd)
double GetIntracellularCalciumConcentration ()
Public Member Functions inherited from AbstractCardiacCell
AbstractCardiacCell (boost::shared_ptr< AbstractIvpOdeSolver > pOdeSolver, unsigned numberOfStateVariables, unsigned voltageIndex, boost::shared_ptr< AbstractStimulusFunction > pIntracellularStimulus)
virtual ~AbstractCardiacCell ()
void Init ()
void SetTimestep (double dt)
virtual void SolveAndUpdateState (double tStart, double tEnd)
virtual OdeSolution Compute (double tStart, double tEnd, double tSamp=0.0)
void SetVoltage (double voltage)
double GetVoltage ()
unsigned GetNumberOfStateVariables () const
unsigned GetNumberOfParameters () const
std::vector< double > GetStdVecStateVariables ()
const std::vector< std::string > & rGetStateVariableNames () const
void SetStateVariables (const std::vector< double > &rVariables)
void SetStateVariable (unsigned index, double newValue)
void SetStateVariable (const std::string &rName, double newValue)
double GetAnyVariable (const std::string &rName, double time=0.0)
double GetParameter (const std::string &rParameterName)
double GetParameter (unsigned parameterIndex)
void SetParameter (const std::string &rParameterName, double value)
virtual void SetState (CellModelState state)
virtual void SetSlowValues (const std::vector< double > &rSlowValues)
virtual void GetSlowValues (std::vector< double > &rSlowValues)
virtual bool IsFastOnly ()
virtual void AdjustOutOfRangeSlowValues (std::vector< double > &rSlowValues)
virtual unsigned GetNumSlowValues ()
Public Member Functions inherited from AbstractCardiacCellInterface
AbstractCardiacCellInterface (boost::shared_ptr< AbstractIvpOdeSolver > pOdeSolver, unsigned voltageIndex, boost::shared_ptr< AbstractStimulusFunction > pIntracellularStimulus)
virtual ~AbstractCardiacCellInterface ()
unsigned GetVoltageIndex ()
void SetStimulusFunction (boost::shared_ptr< AbstractStimulusFunction > pStimulus)
double GetStimulus (double time)
void SetIntracellularStimulusFunction (boost::shared_ptr< AbstractStimulusFunction > pStimulus)
double GetIntracellularStimulus (double time)
double GetIntracellularAreaStimulus (double time)
void SetUsedInTissueSimulation (bool tissue=true)
virtual boost::shared_ptr< RegularStimulus > UseCellMLDefaultStimulus ()
bool HasCellMLDefaultStimulus ()
virtual AbstractLookupTableCollection * GetLookupTableCollection ()
boost::shared_ptr< AbstractStimulusFunction > GetStimulusFunction ()
const boost::shared_ptr< AbstractStimulusFunction > GetStimulusFunction () const
const boost::shared_ptr< AbstractIvpOdeSolver > GetSolver () const
void SetSolver (boost::shared_ptr< AbstractIvpOdeSolver > pSolver)
virtual void SetVoltageDerivativeToZero (bool clamp=true)
void SetFixedVoltage (double voltage)
virtual void SetStretch (double stretch)
Public Member Functions inherited from AbstractOdeSystem
AbstractOdeSystem (unsigned numberOfStateVariables)
virtual ~AbstractOdeSystem ()
virtual bool CalculateStoppingEvent (double time, const std::vector< double > &rY)
virtual double CalculateRootFunction (double time, const std::vector< double > &rY)
bool GetUseAnalyticJacobian ()
const std::vector< double > & rGetConstStateVariables () const
Public Member Functions inherited from AbstractParameterisedSystem< std::vector< double > >
AbstractParameterisedSystem (unsigned numberOfStateVariables)
std::vector< double > & rGetStateVariables ()
std::vector< double > GetStateVariables ()
void SetStateVariables (const std::vector< double > &rStateVariables)
double GetStateVariable (unsigned index) const
double GetStateVariable (const std::string &rName) const
void SetStateVariable (unsigned index, double newValue)
void SetStateVariable (const std::string &rName, double newValue)
virtual void VerifyStateVariables ()
void SetDefaultInitialConditions (const std::vector< double > &rInitialConditions)
void SetDefaultInitialCondition (unsigned index, double initialCondition)
std::vector< double > GetInitialConditions () const
void ResetToInitialConditions ()
double GetParameter (unsigned index) const
double GetParameter (const std::string &rName) const
void SetParameter (const std::string &rName, double value)
void SetParameter (unsigned index, double value)
double GetAnyVariable (unsigned index, double time=0.0, std::vector< double > *pDerivedQuantities=NULL)
double GetAnyVariable (const std::string &rName, double time=0.0, std::vector< double > *pDerivedQuantities=NULL)
void SetAnyVariable (unsigned index, double value)
void SetAnyVariable (const std::string &rName, double value)
virtual std::vector< double > ComputeDerivedQuantities (double time, const std::vector< double > &rState)
std::vector< double > ComputeDerivedQuantitiesFromCurrentState (double time)
Public Member Functions inherited from AbstractUntemplatedParameterisedSystem
AbstractUntemplatedParameterisedSystem (unsigned numberOfStateVariables)
virtual ~AbstractUntemplatedParameterisedSystem ()
boost::shared_ptr< const AbstractOdeSystemInformation > GetSystemInformation () const
std::string GetSystemName () const
unsigned GetNumberOfAttributes () const
bool HasAttribute (const std::string &rName) const
double GetAttribute (const std::string &rName) const
unsigned GetNumberOfStateVariables () const
const std::vector< std::string > & rGetStateVariableNames () const
const std::vector< std::string > & rGetStateVariableUnits () const
unsigned GetStateVariableIndex (const std::string &rName) const
bool HasStateVariable (const std::string &rName) const
std::string GetStateVariableUnits (unsigned index) const
unsigned GetNumberOfParameters () const
const std::vector< std::string > & rGetParameterNames () const
const std::vector< std::string > & rGetParameterUnits () const
unsigned GetParameterIndex (const std::string &rName) const
bool HasParameter (const std::string &rName) const
std::string GetParameterUnits (unsigned index) const
unsigned GetNumberOfDerivedQuantities () const
const std::vector< std::string > & rGetDerivedQuantityNames () const
const std::vector< std::string > & rGetDerivedQuantityUnits () const
unsigned GetDerivedQuantityIndex (const std::string &rName) const
bool HasDerivedQuantity (const std::string &rName) const
std::string GetDerivedQuantityUnits (unsigned index) const
unsigned GetAnyVariableIndex (const std::string &rName) const
bool HasAnyVariable (const std::string &rName) const
std::string GetAnyVariableUnits (unsigned index) const
std::string GetAnyVariableUnits (const std::string &rName) const
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Friends
class boost::serialization::access
Additional Inherited Members
Protected Member Functions inherited from AbstractParameterisedSystem< std::vector< double > >
std::string DumpState (const std::string &rMessage)
std::string DumpState (const std::string &rMessage, std::vector< double > Y)
std::string DumpState (const std::string &rMessage, std::vector< double > Y, double time)
void CheckParametersOnLoad (const std::vector< double > &rParameters, const std::vector< std::string > &rParameterNames)
Protected Attributes inherited from AbstractCardiacCell
double mDt
Protected Attributes inherited from AbstractCardiacCellInterface
unsigned mVoltageIndex
boost::shared_ptr< AbstractIvpOdeSolver > mpOdeSolver
boost::shared_ptr< AbstractStimulusFunction > mpIntracellularStimulus
bool mSetVoltageDerivativeToZero
bool mIsUsedInTissue
bool mHasDefaultStimulusFromCellML
double mFixedVoltage
Protected Attributes inherited from AbstractOdeSystem
bool mUseAnalyticJacobian
Protected Attributes inherited from AbstractParameterisedSystem< std::vector< double > >
std::vector< double > mStateVariables
std::vector< double > mParameters
Protected Attributes inherited from AbstractUntemplatedParameterisedSystem
unsigned mNumberOfStateVariables
boost::shared_ptr< AbstractOdeSystemInformation > mpSystemInfo
Detailed Description
This class represents a fake cell for use within the bath of a bidomain simulation.
Note
Note that only a portion of the normal functionality of a cardiac cell is actually redefined in this class. If further calls to cardiac cells are later added to the simulation process, additional overrides may need to be added here.
Definition at line 52 of file FakeBathCell.hpp.
Constructor & Destructor Documentation
FakeBathCell()
FakeBathCell::FakeBathCell (boost::shared_ptr< AbstractIvpOdeSolver > pSolver, boost::shared_ptr< AbstractStimulusFunction > pIntracellularStimulus)
Constructor uses the same signature as normal cells, for convenience.
Parameters
pSolver unused
pIntracellularStimulus unused
Definition at line 39 of file FakeBathCell.cpp.
References AbstractCardiacCell::Init(), OdeSystemInformation< ODE_SYSTEM >::Instance(), and AbstractUntemplatedParameterisedSystem::mpSystemInfo.
Referenced by serialize().
~FakeBathCell()
FakeBathCell::~FakeBathCell ()
Destructor; does nothing.
Definition at line 47 of file FakeBathCell.cpp.
Referenced by serialize().
Member Function Documentation
ComputeExceptVoltage()
void FakeBathCell::ComputeExceptVoltage (double tStart, double tEnd) virtual
There isn't really a cell here, so we override this method to do nothing.
Parameters
tStart unused
tEnd unused
Reimplemented from AbstractCardiacCell.
Definition at line 63 of file FakeBathCell.cpp.
Referenced by serialize().
EvaluateYDerivatives()
void FakeBathCell::EvaluateYDerivatives (double time, const std::vector< double > & rY, std::vector< double > & rDY) virtual
This method is pure in a base class, so we need it, but we never use it. It has an empty body.
Parameters
time unused
rY unused
rDY unused
Implements AbstractOdeSystem.
Definition at line 52 of file FakeBathCell.cpp.
References NEVER_REACHED.
Referenced by serialize().
GetIIonic()
double FakeBathCell::GetIIonic (const std::vector< double > * pStateVariables = NULL) virtual
Fake cells have no transmembrane currents, so this method always returns 0.
Parameters
pStateVariables unused
Returns
zero
Implements AbstractCardiacCellInterface.
Definition at line 58 of file FakeBathCell.cpp.
Referenced by serialize().
GetIntracellularCalciumConcentration()
double FakeBathCell::GetIntracellularCalciumConcentration () virtual
There is really no calcium here, so we override this method to return a dummy value (0) Implementing this with a dummy implementation is needed by mechanics
Returns
always zero
Reimplemented from AbstractCardiacCellInterface.
Definition at line 67 of file FakeBathCell.cpp.
Referenced by serialize().
serialize()
template<class Archive > void FakeBathCell::serialize (Archive & archive, const unsigned int version) inline private
Archive this cell. Just calls the base class version.
Parameters
archive
version
Definition at line 64 of file FakeBathCell.hpp.
References CHASTE_CLASS_EXPORT, ComputeExceptVoltage(), EvaluateYDerivatives(), FakeBathCell(), GetIIonic(), GetIntracellularCalciumConcentration(), AbstractUntemplatedParameterisedSystem::mNumberOfStateVariables, and ~FakeBathCell().
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Needed for serialization.
Definition at line 56 of file FakeBathCell.hpp.
The documentation for this class was generated from the following files:
heart/src/odes/ionicmodels/FakeBathCell.hpp
heart/src/odes/ionicmodels/FakeBathCell.cpp