Chaste: CellAppliedForceWriter< ELEMENT_DIM, SPACE_DIM > Class Template Reference
CellAppliedForceWriter< ELEMENT_DIM, SPACE_DIM > Class Template Reference
#include <CellAppliedForceWriter.hpp>
Public Member Functions
CellAppliedForceWriter ()
c_vector< double, SPACE_DIM > GetVectorCellDataForVtkOutput (CellPtr pCell, AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM > *pCellPopulation)
virtual void VisitCell (CellPtr pCell, AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM > *pCellPopulation)
Public Member Functions inherited from AbstractCellWriter< ELEMENT_DIM, SPACE_DIM >
AbstractCellWriter (const std::string &rFileName)
virtual double GetCellDataForVtkOutput (CellPtr pCell, AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM > *pCellPopulation)
bool GetOutputScalarData ()
bool GetOutputVectorData ()
void SetVtkCellDataName (std::string vtkCellDataName)
void SetVtkVectorCellDataName (std::string vtkCellDataName)
std::string GetVtkCellDataName ()
std::string GetVtkVectorCellDataName ()
Public Member Functions inherited from AbstractCellBasedWriter< ELEMENT_DIM, SPACE_DIM >
AbstractCellBasedWriter (const std::string &rFileName)
virtual ~AbstractCellBasedWriter ()
void CloseFile ()
virtual void OpenOutputFile (OutputFileHandler &rOutputFileHandler)
void OpenOutputFileForAppend (OutputFileHandler &rOutputFileHandler)
virtual void WriteTimeStamp ()
virtual void WriteNewline ()
void SetFileName (std::string fileName)
std::string GetFileName ()
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Friends
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from AbstractCellWriter< ELEMENT_DIM, SPACE_DIM >
bool mOutputScalarData
bool mOutputVectorData
std::string mVtkCellDataName
std::string mVtkVectorCellDataName
Protected Attributes inherited from AbstractCellBasedWriter< ELEMENT_DIM, SPACE_DIM >
std::string mFileName
out_stream mpOutStream
Detailed Description
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM>
class CellAppliedForceWriter< ELEMENT_DIM, SPACE_DIM >
A class written using the visitor pattern for writing the applied force on each cell to file. This class is designed for use with a NodeBasedCellPopulation (or its subclasses) only; if used with other cell populations, the writer will output DOUBLE_UNSET for each component of cell's applied force.
The output file is called cellappliedforce.dat by default. If VTK is switched on, then the writer also specifies the VTK output for each cell, which is stored in the VTK cell data "Cell applied force" by default.
Definition at line 54 of file CellAppliedForceWriter.hpp.
Constructor & Destructor Documentation
CellAppliedForceWriter()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> CellAppliedForceWriter< ELEMENT_DIM, SPACE_DIM >::CellAppliedForceWriter ()
Default constructor.
Definition at line 41 of file CellAppliedForceWriter.cpp.
References AbstractCellWriter< ELEMENT_DIM, SPACE_DIM >::mOutputScalarData, AbstractCellWriter< ELEMENT_DIM, SPACE_DIM >::mOutputVectorData, and AbstractCellWriter< ELEMENT_DIM, SPACE_DIM >::mVtkVectorCellDataName.
Referenced by CellAppliedForceWriter< ELEMENT_DIM, SPACE_DIM >::serialize().
Member Function Documentation
GetVectorCellDataForVtkOutput()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> c_vector< double, SPACE_DIM > CellAppliedForceWriter< ELEMENT_DIM, SPACE_DIM >::GetVectorCellDataForVtkOutput (CellPtr pCell, AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM > * pCellPopulation) virtual
Overridden GetVectorCellDataForVtkOutput() method.
Get a c_vector associated with a cell. This method reduces duplication of code between the methods VisitCell() and AddVtkData().
Parameters
pCell a cell
pCellPopulation a pointer to the cell population owning the cell.
Returns
data associated with the cell
Reimplemented from AbstractCellWriter< ELEMENT_DIM, SPACE_DIM >.
Definition at line 50 of file CellAppliedForceWriter.cpp.
References DOUBLE_UNSET, AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::GetLocationIndexUsingCell(), and AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::GetNode().
Referenced by CellAppliedForceWriter< ELEMENT_DIM, SPACE_DIM >::serialize(), and CellAppliedForceWriter< ELEMENT_DIM, SPACE_DIM >::VisitCell().
serialize()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> template<class Archive > void CellAppliedForceWriter< ELEMENT_DIM, SPACE_DIM >::serialize (Archive & archive, const unsigned int version) inline private
Serialize the object and its member variables.
Parameters
archive the archive
version the current version of this class
Definition at line 68 of file CellAppliedForceWriter.hpp.
References CellAppliedForceWriter< ELEMENT_DIM, SPACE_DIM >::CellAppliedForceWriter(), EXPORT_TEMPLATE_CLASS_ALL_DIMS, CellAppliedForceWriter< ELEMENT_DIM, SPACE_DIM >::GetVectorCellDataForVtkOutput(), and CellAppliedForceWriter< ELEMENT_DIM, SPACE_DIM >::VisitCell().
VisitCell()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void CellAppliedForceWriter< ELEMENT_DIM, SPACE_DIM >::VisitCell (CellPtr pCell, AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM > * pCellPopulation) virtual
Overridden VisitCell() method.
Visit a cell and write its applied force.
Outputs a line of space-separated values of the form: ...[location index] [cell id] [x-pos] [y-pos] [z-pos] [x-force] [y-force] [z-force] ... with [y-<>] and [z-<>] included for 2 and 3 dimensional simulations, respectively.
This is appended to the output written by AbstractCellBasedWriter, which is a single value [present simulation time], followed by a tab.
Parameters
pCell a cell
pCellPopulation a pointer to the cell population owning the cell
Implements AbstractCellWriter< ELEMENT_DIM, SPACE_DIM >.
Definition at line 64 of file CellAppliedForceWriter.cpp.
References AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::GetLocationIndexUsingCell(), AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::GetLocationOfCellCentre(), CellAppliedForceWriter< ELEMENT_DIM, SPACE_DIM >::GetVectorCellDataForVtkOutput(), and AbstractCellBasedWriter< ELEMENT_DIM, SPACE_DIM >::mpOutStream.
Referenced by CellAppliedForceWriter< ELEMENT_DIM, SPACE_DIM >::serialize().
Friends And Related Function Documentation
boost::serialization::access
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> friend class boost::serialization::access friend
Needed for serialization.
Definition at line 59 of file CellAppliedForceWriter.hpp.
The documentation for this class was generated from the following files:
cell_based/src/writers/cell_writers/CellAppliedForceWriter.hpp
cell_based/src/writers/cell_writers/CellAppliedForceWriter.cpp