Chaste: RandomDirectionCentreBasedDivisionRule< ELEMENT_DIM, SPACE_DIM > Class Template Reference
RandomDirectionCentreBasedDivisionRule< ELEMENT_DIM, SPACE_DIM > Class Template Reference
#include <RandomDirectionCentreBasedDivisionRule.hpp>
Public Member Functions
RandomDirectionCentreBasedDivisionRule ()
virtual ~RandomDirectionCentreBasedDivisionRule ()
virtual std::pair< c_vector< double, SPACE_DIM >, c_vector< double, SPACE_DIM > > CalculateCellDivisionVector (CellPtr pParentCell, AbstractCentreBasedCellPopulation< ELEMENT_DIM, SPACE_DIM > &rCellPopulation)
Public Member Functions inherited from AbstractCentreBasedDivisionRule< ELEMENT_DIM, SPACE_DIM >
AbstractCentreBasedDivisionRule ()
virtual ~AbstractCentreBasedDivisionRule ()
void OutputCellCentreBasedDivisionRuleInfo (out_stream &rParamsFile)
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Friends
class boost::serialization::access
Additional Inherited Members
Protected Member Functions inherited from AbstractCentreBasedDivisionRule< ELEMENT_DIM, SPACE_DIM >
virtual void OutputCellCentreBasedDivisionRuleParameters (out_stream &rParamsFile)
Detailed Description
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM = ELEMENT_DIM>
class RandomDirectionCentreBasedDivisionRule< ELEMENT_DIM, SPACE_DIM >
A class to generate two daughter cell positions, located a distance AbstractCentreBasedCellPopulation::mMeinekeDivisionSeparation apart, along a random axis. The midpoint between the two daughter cell positions corresponds to the parent cell's position.
Definition at line 55 of file RandomDirectionCentreBasedDivisionRule.hpp.
Constructor & Destructor Documentation
RandomDirectionCentreBasedDivisionRule()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM = ELEMENT_DIM> RandomDirectionCentreBasedDivisionRule< ELEMENT_DIM, SPACE_DIM >::RandomDirectionCentreBasedDivisionRule () inline
Default constructor.
Definition at line 76 of file RandomDirectionCentreBasedDivisionRule.hpp.
~RandomDirectionCentreBasedDivisionRule()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM = ELEMENT_DIM> virtual RandomDirectionCentreBasedDivisionRule< ELEMENT_DIM, SPACE_DIM >::~RandomDirectionCentreBasedDivisionRule () inline virtual
Empty destructor.
Definition at line 83 of file RandomDirectionCentreBasedDivisionRule.hpp.
References RandomDirectionCentreBasedDivisionRule< ELEMENT_DIM, SPACE_DIM >::CalculateCellDivisionVector(), and EXPORT_TEMPLATE_CLASS_ALL_DIMS.
Member Function Documentation
CalculateCellDivisionVector()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> std::pair< c_vector< double, SPACE_DIM >, c_vector< double, SPACE_DIM > > RandomDirectionCentreBasedDivisionRule< ELEMENT_DIM, SPACE_DIM >::CalculateCellDivisionVector (CellPtr pParentCell, AbstractCentreBasedCellPopulation< ELEMENT_DIM, SPACE_DIM > & rCellPopulation) virtual
Overridden CalculateCellDivisionVector() method.
Parameters
pParentCell The cell to divide
rCellPopulation The centre-based cell population
Returns
the two daughter cell positions.
Implements AbstractCentreBasedDivisionRule< ELEMENT_DIM, SPACE_DIM >.
Definition at line 40 of file RandomDirectionCentreBasedDivisionRule.cpp.
References AbstractCentreBasedCellPopulation< ELEMENT_DIM, SPACE_DIM >::GetMeinekeDivisionSeparation(), RandomNumberGenerator::Instance(), and RandomNumberGenerator::ranf().
Referenced by RandomDirectionCentreBasedDivisionRule< ELEMENT_DIM, SPACE_DIM >::~RandomDirectionCentreBasedDivisionRule().
serialize()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM = ELEMENT_DIM> template<class Archive > void RandomDirectionCentreBasedDivisionRule< ELEMENT_DIM, SPACE_DIM >::serialize (Archive & archive, const unsigned int version) inline private
Serialize the object and its member variables.
Parameters
archive the archive
version the current version of this class
Definition at line 66 of file RandomDirectionCentreBasedDivisionRule.hpp.
The documentation for this class was generated from the following files:
cell_based/src/population/division_rules/RandomDirectionCentreBasedDivisionRule.hpp
cell_based/src/population/division_rules/RandomDirectionCentreBasedDivisionRule.cpp