Chaste: ShortAxisVertexBasedDivisionRule< SPACE_DIM > Class Template Reference
ShortAxisVertexBasedDivisionRule< SPACE_DIM > Class Template Reference
#include <ShortAxisVertexBasedDivisionRule.hpp>
Public Member Functions
ShortAxisVertexBasedDivisionRule ()
virtual ~ShortAxisVertexBasedDivisionRule ()
virtual c_vector< double, SPACE_DIM > CalculateCellDivisionVector (CellPtr pParentCell, VertexBasedCellPopulation< SPACE_DIM > &rCellPopulation)
Public Member Functions inherited from AbstractVertexBasedDivisionRule< SPACE_DIM >
AbstractVertexBasedDivisionRule ()
virtual ~AbstractVertexBasedDivisionRule ()
void OutputCellVertexBasedDivisionRuleInfo (out_stream &rParamsFile)
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Friends
class boost::serialization::access
Additional Inherited Members
Protected Member Functions inherited from AbstractVertexBasedDivisionRule< SPACE_DIM >
virtual void OutputCellVertexBasedDivisionRuleParameters (out_stream &rParamsFile)
Detailed Description
template<unsigned SPACE_DIM>
class ShortAxisVertexBasedDivisionRule< SPACE_DIM >
A class to generate the short axis of a cell for vertex-based cell populations, to be used in cell division. This is the default rule that is used in most of the vertex-based simulations.
The short axis is the eigenvector associated with the largest eigenvalue of the moment of inertia of the cell's polygon.
Definition at line 58 of file ShortAxisVertexBasedDivisionRule.hpp.
Constructor & Destructor Documentation
ShortAxisVertexBasedDivisionRule()
template<unsigned SPACE_DIM> ShortAxisVertexBasedDivisionRule< SPACE_DIM >::ShortAxisVertexBasedDivisionRule () inline
Default constructor.
Definition at line 79 of file ShortAxisVertexBasedDivisionRule.hpp.
~ShortAxisVertexBasedDivisionRule()
template<unsigned SPACE_DIM> virtual ShortAxisVertexBasedDivisionRule< SPACE_DIM >::~ShortAxisVertexBasedDivisionRule () inline virtual
Empty destructor.
Definition at line 86 of file ShortAxisVertexBasedDivisionRule.hpp.
References ShortAxisVertexBasedDivisionRule< SPACE_DIM >::CalculateCellDivisionVector(), and EXPORT_TEMPLATE_CLASS_SAME_DIMS.
Member Function Documentation
CalculateCellDivisionVector()
template<unsigned SPACE_DIM> c_vector< double, SPACE_DIM > ShortAxisVertexBasedDivisionRule< SPACE_DIM >::CalculateCellDivisionVector (CellPtr pParentCell, VertexBasedCellPopulation< SPACE_DIM > & rCellPopulation) virtual
Overridden CalculateCellDivisionVector() method.
Return the short axis of the existing cell, which will be used to form the boundary between the daughter cells.
Parameters
pParentCell The cell to divide
rCellPopulation The vertex-based cell population
Returns
the division vector.
Implements AbstractVertexBasedDivisionRule< SPACE_DIM >.
Definition at line 39 of file ShortAxisVertexBasedDivisionRule.cpp.
References EXPORT_TEMPLATE_CLASS_SAME_DIMS, AbstractCellPopulation< ELEMENT_DIM, ELEMENT_DIM >::GetLocationIndexUsingCell(), VertexMesh< ELEMENT_DIM, SPACE_DIM >::GetShortAxisOfElement(), and VertexBasedCellPopulation< DIM >::rGetMesh().
Referenced by ShortAxisVertexBasedDivisionRule< SPACE_DIM >::~ShortAxisVertexBasedDivisionRule().
serialize()
template<unsigned SPACE_DIM> template<class Archive > void ShortAxisVertexBasedDivisionRule< SPACE_DIM >::serialize (Archive & archive, const unsigned int version) inline private
Serialize the object and its member variables.
Parameters
archive the archive
version the current version of this class
Definition at line 69 of file ShortAxisVertexBasedDivisionRule.hpp.
The documentation for this class was generated from the following files:
cell_based/src/population/division_rules/ShortAxisVertexBasedDivisionRule.hpp
cell_based/src/population/division_rules/ShortAxisVertexBasedDivisionRule.cpp