Chaste: PlaneBasedCellKiller< DIM > Class Template Reference
PlaneBasedCellKiller< DIM > Class Template Reference
#include <PlaneBasedCellKiller.hpp>
Public Member Functions
PlaneBasedCellKiller (AbstractCellPopulation< DIM > *pCellPopulation, c_vector< double, DIM > point, c_vector< double, DIM > normal)
const c_vector< double, DIM > & rGetPointOnPlane () const
const c_vector< double, DIM > & rGetNormalToPlane () const
virtual void CheckAndLabelCellsForApoptosisOrDeath ()
void OutputCellKillerParameters (out_stream &rParamsFile)
Public Member Functions inherited from AbstractCellKiller< DIM >
AbstractCellKiller (AbstractCellPopulation< SPACE_DIM > *pCellPopulation)
virtual ~AbstractCellKiller ()
const AbstractCellPopulation< SPACE_DIM > * GetCellPopulation () const
void OutputCellKillerInfo (out_stream &rParamsFile)
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Private Attributes
c_vector< double, DIM > mPointOnPlane
c_vector< double, DIM > mNormalToPlane
Friends
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from AbstractCellKiller< DIM >
AbstractCellPopulation< SPACE_DIM > * mpCellPopulation
Detailed Description
template<unsigned DIM>
class PlaneBasedCellKiller< DIM >
A cell killer that kills cells if they are outside the domain. defined by a point, mPointOnPlane, and an outward pointing normal, mNormalToPlane. Works for all CellPopulations.
Definition at line 51 of file PlaneBasedCellKiller.hpp.
Constructor & Destructor Documentation
PlaneBasedCellKiller()
template<unsigned DIM> PlaneBasedCellKiller< DIM >::PlaneBasedCellKiller (AbstractCellPopulation< DIM > * pCellPopulation, c_vector< double, DIM > point, c_vector< double, DIM > normal)
Default constructor.
Parameters
pCellPopulation pointer to a cell population
point point on the plane which nodes cannot cross
normal the outward pointing unit normal to the boundary plane
Definition at line 39 of file PlaneBasedCellKiller.cpp.
References PlaneBasedCellKiller< DIM >::mNormalToPlane.
Referenced by PlaneBasedCellKiller< DIM >::serialize().
Member Function Documentation
CheckAndLabelCellsForApoptosisOrDeath()
template<unsigned DIM> void PlaneBasedCellKiller< DIM >::CheckAndLabelCellsForApoptosisOrDeath () virtual
Loops over cells and kills cells outside boundary.
Implements AbstractCellKiller< DIM >.
Definition at line 62 of file PlaneBasedCellKiller.cpp.
References AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::Begin(), AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::End(), AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::GetLocationOfCellCentre(), PlaneBasedCellKiller< DIM >::mNormalToPlane, AbstractCellKiller< DIM >::mpCellPopulation, and PlaneBasedCellKiller< DIM >::mPointOnPlane.
Referenced by PlaneBasedCellKiller< DIM >::serialize().
OutputCellKillerParameters()
template<unsigned DIM> void PlaneBasedCellKiller< DIM >::OutputCellKillerParameters (out_stream & rParamsFile) virtual
Overridden OutputCellKillerParameters() method.
Parameters
rParamsFile the file stream to which the parameters are output
Implements AbstractCellKiller< DIM >.
Definition at line 78 of file PlaneBasedCellKiller.cpp.
Referenced by PlaneBasedCellKiller< DIM >::serialize().
rGetNormalToPlane()
template<unsigned DIM> const c_vector< double, DIM > & PlaneBasedCellKiller< DIM >::rGetNormalToPlane () const
Returns
mNormalToPlane.
Definition at line 56 of file PlaneBasedCellKiller.cpp.
References PlaneBasedCellKiller< DIM >::mNormalToPlane.
Referenced by PlaneBasedCellKiller< DIM >::serialize().
rGetPointOnPlane()
template<unsigned DIM> const c_vector< double, DIM > & PlaneBasedCellKiller< DIM >::rGetPointOnPlane () const
Returns
mPointOnPlane.
Definition at line 50 of file PlaneBasedCellKiller.cpp.
References PlaneBasedCellKiller< DIM >::mPointOnPlane.
Referenced by PlaneBasedCellKiller< DIM >::serialize().
serialize()
template<unsigned DIM> template<class Archive > void PlaneBasedCellKiller< DIM >::serialize (Archive & archive, const unsigned int version) inline private
Archive the object.
Parameters
archive the archive
version the current version of this class
Definition at line 74 of file PlaneBasedCellKiller.hpp.
References PlaneBasedCellKiller< DIM >::CheckAndLabelCellsForApoptosisOrDeath(), EXPORT_TEMPLATE_CLASS_SAME_DIMS, PlaneBasedCellKiller< DIM >::OutputCellKillerParameters(), PlaneBasedCellKiller< DIM >::PlaneBasedCellKiller(), PlaneBasedCellKiller< DIM >::rGetNormalToPlane(), and PlaneBasedCellKiller< DIM >::rGetPointOnPlane().
Friends And Related Function Documentation
boost::serialization::access
template<unsigned DIM> friend class boost::serialization::access friend
Needed for serialization.
Definition at line 66 of file PlaneBasedCellKiller.hpp.
Member Data Documentation
mNormalToPlane
template<unsigned DIM> c_vector<double, DIM> PlaneBasedCellKiller< DIM >::mNormalToPlane private
The outward pointing unit normal to the boundary plane.
Definition at line 63 of file PlaneBasedCellKiller.hpp.
Referenced by PlaneBasedCellKiller< DIM >::CheckAndLabelCellsForApoptosisOrDeath(), PlaneBasedCellKiller< DIM >::PlaneBasedCellKiller(), and PlaneBasedCellKiller< DIM >::rGetNormalToPlane().
mPointOnPlane
template<unsigned DIM> c_vector<double, DIM> PlaneBasedCellKiller< DIM >::mPointOnPlane private
A point on the plane which nodes cannot cross.
Definition at line 58 of file PlaneBasedCellKiller.hpp.
Referenced by PlaneBasedCellKiller< DIM >::CheckAndLabelCellsForApoptosisOrDeath(), and PlaneBasedCellKiller< DIM >::rGetPointOnPlane().
The documentation for this class was generated from the following files:
cell_based/src/population/killers/PlaneBasedCellKiller.hpp
cell_based/src/population/killers/PlaneBasedCellKiller.cpp