Chaste: SloughingCellKiller< DIM > Class Template Reference
SloughingCellKiller< DIM > Class Template Reference
#include <SloughingCellKiller.hpp>
Public Member Functions
SloughingCellKiller (AbstractCellPopulation< DIM > *pCrypt, double sloughHeight, bool sloughSides=false, double sloughWidth=10.0)
virtual ~SloughingCellKiller ()
bool GetSloughSides () const
double GetSloughHeight () const
double GetSloughWidth () const
virtual void CheckAndLabelCellsForApoptosisOrDeath ()
void OutputCellKillerParameters (out_stream &rParamsFile)
Public Member Functions inherited from AbstractCellKiller< DIM >
AbstractCellKiller (AbstractCellPopulation< SPACE_DIM > *pCellPopulation)
virtual ~AbstractCellKiller ()
const AbstractCellPopulation< SPACE_DIM > * GetCellPopulation () const
void OutputCellKillerInfo (out_stream &rParamsFile)
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Private Attributes
bool mSloughSides
double mSloughHeight
double mSloughWidth
Friends
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from AbstractCellKiller< DIM >
AbstractCellPopulation< SPACE_DIM > * mpCellPopulation
Detailed Description
template<unsigned DIM>
class SloughingCellKiller< DIM >
A cell killer that kills cells if they are outside the domain. The domain is assumed to start at x=0 and y=0. By default only cells are sloughed if y>mSloughLength. To slough the sides call the constructor with the appropriate parameter.
Definition at line 51 of file SloughingCellKiller.hpp.
Constructor & Destructor Documentation
template<unsigned DIM> SloughingCellKiller< DIM >::SloughingCellKiller (AbstractCellPopulation< DIM > * pCrypt, double sloughHeight, bool sloughSides = false, double sloughWidth = 10.0)
Default constructor.
Parameters
pCrypt pointer to a cell population
sloughHeight the height at which to slough from the domain
sloughSides whether to slough cells at the side of the domain
sloughWidth the width of the domain (note slough on left and right)
Definition at line 40 of file SloughingCellKiller.cpp.
References SloughingCellKiller< DIM >::mSloughHeight, and SloughingCellKiller< DIM >::mSloughWidth.
Referenced by SloughingCellKiller< DIM >::serialize().
template<unsigned DIM> virtual SloughingCellKiller< DIM >::~SloughingCellKiller () inline virtual
Destructor
Definition at line 102 of file SloughingCellKiller.hpp.
References SloughingCellKiller< DIM >::CheckAndLabelCellsForApoptosisOrDeath(), EXPORT_TEMPLATE_CLASS_SAME_DIMS, AbstractCellKiller< DIM >::GetCellPopulation(), SloughingCellKiller< DIM >::GetSloughHeight(), SloughingCellKiller< DIM >::GetSloughSides(), SloughingCellKiller< DIM >::GetSloughWidth(), and SloughingCellKiller< DIM >::OutputCellKillerParameters().
Member Function Documentation
template<unsigned DIM> void SloughingCellKiller< DIM >::CheckAndLabelCellsForApoptosisOrDeath () virtual
Loops over cells and kills cells outside boundary.
Implements AbstractCellKiller< DIM >.
Definition at line 70 of file SloughingCellKiller.cpp.
References AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::Begin(), AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::End(), EXCEPTION, AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::GetLocationOfCellCentre(), AbstractCellKiller< DIM >::mpCellPopulation, SloughingCellKiller< DIM >::mSloughHeight, SloughingCellKiller< DIM >::mSloughSides, SloughingCellKiller< DIM >::mSloughWidth, and NEVER_REACHED.
Referenced by SloughingCellKiller< DIM >::~SloughingCellKiller().
template<unsigned DIM> double SloughingCellKiller< DIM >::GetSloughHeight () const
Returns
mSloughHeight.
Definition at line 58 of file SloughingCellKiller.cpp.
References SloughingCellKiller< DIM >::mSloughHeight.
Referenced by SloughingCellKiller< DIM >::~SloughingCellKiller().
template<unsigned DIM> bool SloughingCellKiller< DIM >::GetSloughSides () const
Returns
mSloughSides.
Definition at line 52 of file SloughingCellKiller.cpp.
References SloughingCellKiller< DIM >::mSloughSides.
Referenced by SloughingCellKiller< DIM >::~SloughingCellKiller().
template<unsigned DIM> double SloughingCellKiller< DIM >::GetSloughWidth () const
Returns
mSloughWidth.
Definition at line 64 of file SloughingCellKiller.cpp.
References SloughingCellKiller< DIM >::mSloughWidth.
Referenced by SloughingCellKiller< DIM >::~SloughingCellKiller().
template<unsigned DIM> void SloughingCellKiller< DIM >::OutputCellKillerParameters (out_stream & rParamsFile) virtual
Outputs cell killer parameters to file
As this method is pure virtual, it must be overridden in subclasses.
Parameters
rParamsFile the file stream to which the parameters are output
Implements AbstractCellKiller< DIM >.
Definition at line 119 of file SloughingCellKiller.cpp.
References EXPORT_TEMPLATE_CLASS_SAME_DIMS, SloughingCellKiller< DIM >::mSloughHeight, SloughingCellKiller< DIM >::mSloughSides, SloughingCellKiller< DIM >::mSloughWidth, and AbstractCellKiller< SPACE_DIM >::OutputCellKillerParameters().
Referenced by SloughingCellKiller< DIM >::~SloughingCellKiller().
template<unsigned DIM> template<class Archive > void SloughingCellKiller< DIM >::serialize (Archive & archive, const unsigned int version) inline private
Archive the object.
Parameters
archive the archive
version the current version of this class
Definition at line 79 of file SloughingCellKiller.hpp.
References SloughingCellKiller< DIM >::SloughingCellKiller().
Friends And Related Function Documentation
template<unsigned DIM> friend class boost::serialization::access friend
Needed for serialization.
Definition at line 71 of file SloughingCellKiller.hpp.
Member Data Documentation
template<unsigned DIM> double SloughingCellKiller< DIM >::mSloughHeight private
The height of the domain, non-dimensionalised with cell length. This parameter determines when cells are sloughed from the domain.
Definition at line 62 of file SloughingCellKiller.hpp.
Referenced by SloughingCellKiller< DIM >::CheckAndLabelCellsForApoptosisOrDeath(), SloughingCellKiller< DIM >::GetSloughHeight(), SloughingCellKiller< DIM >::OutputCellKillerParameters(), and SloughingCellKiller< DIM >::SloughingCellKiller().
template<unsigned DIM> bool SloughingCellKiller< DIM >::mSloughSides private
Whether cells should be sloughed from the sides of the crypt.
Definition at line 56 of file SloughingCellKiller.hpp.
Referenced by SloughingCellKiller< DIM >::CheckAndLabelCellsForApoptosisOrDeath(), SloughingCellKiller< DIM >::GetSloughSides(), and SloughingCellKiller< DIM >::OutputCellKillerParameters().
template<unsigned DIM> double SloughingCellKiller< DIM >::mSloughWidth private
The width of the domain, non-dimensionalised with cell length. This determines when cells are sloughed from sides of the domain in 2D.
Definition at line 68 of file SloughingCellKiller.hpp.
Referenced by SloughingCellKiller< DIM >::CheckAndLabelCellsForApoptosisOrDeath(), SloughingCellKiller< DIM >::GetSloughWidth(), SloughingCellKiller< DIM >::OutputCellKillerParameters(), and SloughingCellKiller< DIM >::SloughingCellKiller().
The documentation for this class was generated from the following files:
crypt/src/killers/SloughingCellKiller.hpp
crypt/src/killers/SloughingCellKiller.cpp