Chaste: CryptProjectionStatistics Class Reference
CryptProjectionStatistics Class Reference
#include <CryptProjectionStatistics.hpp>
Public Member Functions
CryptProjectionStatistics (MeshBasedCellPopulation< 2 > &rCrypt)
std::vector< CellPtr > GetCryptSection (double angle=DBL_MAX)
Public Member Functions inherited from AbstractCryptStatistics
AbstractCryptStatistics (MeshBasedCellPopulation< 2 > &rCrypt)
virtual ~AbstractCryptStatistics ()
void LabelSPhaseCells ()
void LabelAllCellsAsHealthy ()
std::vector< bool > AreCryptSectionCellsLabelled (std::vector< CellPtr > &rCryptSection)
Private Member Functions
bool CellIsInSection (double angle, const c_vector< double, 2 > &rCellPosition, double widthOfSection=0.6)
Additional Inherited Members
Protected Attributes inherited from AbstractCryptStatistics
MeshBasedCellPopulation< 2 > & mrCrypt
Detailed Description
Concrete statistics class for the crypt projection model.
Definition at line 44 of file CryptProjectionStatistics.hpp.
Constructor & Destructor Documentation
CryptProjectionStatistics::CryptProjectionStatistics (MeshBasedCellPopulation< 2 > & rCrypt)
Constructor.
Parameters
rCrypt The crypt
Definition at line 47 of file CryptProjectionStatistics.cpp.
Member Function Documentation
bool CryptProjectionStatistics::CellIsInSection (double angle, const c_vector< double, 2 > & rCellPosition, double widthOfSection = 0.6) private
CellIsInSection method.
Parameters
angle The angle between the crypt section and the x axis in the projection
rCellPosition The vector of a cell's position
widthOfSection The width of the section
Returns
whether the cell is in the section
Definition at line 52 of file CryptProjectionStatistics.cpp.
Referenced by GetCryptSection().
std::vector< CellPtr > CryptProjectionStatistics::GetCryptSection (double angle = DBL_MAX)
GetCryptSection method. Takes in an angle from the interval (-pi, pi].
Parameters
angle The angle between the crypt section and the x axis in the projection
Returns
all cells in the section
Definition at line 64 of file CryptProjectionStatistics.cpp.
References AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::Begin(), CellIsInSection(), AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::End(), AbstractCentreBasedCellPopulation< ELEMENT_DIM, SPACE_DIM >::GetLocationOfCellCentre(), RandomNumberGenerator::Instance(), AbstractCryptStatistics::mrCrypt, and RandomNumberGenerator::ranf().
The documentation for this class was generated from the following files:
crypt/src/statistics/CryptProjectionStatistics.hpp
crypt/src/statistics/CryptProjectionStatistics.cpp