Chaste: NagaiHondaDifferentialAdhesionForce< DIM > Class Template Reference
NagaiHondaDifferentialAdhesionForce< DIM > Class Template Reference
#include <NagaiHondaDifferentialAdhesionForce.hpp>
Public Member Functions
NagaiHondaDifferentialAdhesionForce ()
virtual ~NagaiHondaDifferentialAdhesionForce ()
virtual double GetAdhesionParameter (Node< DIM > *pNodeA, Node< DIM > *pNodeB, VertexBasedCellPopulation< DIM > &rVertexCellPopulation)
double GetNagaiHondaLabelledCellCellAdhesionEnergyParameter ()
double GetNagaiHondaLabelledCellLabelledCellAdhesionEnergyParameter ()
double GetNagaiHondaLabelledCellBoundaryAdhesionEnergyParameter ()
void SetNagaiHondaLabelledCellCellAdhesionEnergyParameter (double labelledCellCellAdhesionEnergyParameter)
void SetNagaiHondaLabelledCellLabelledCellAdhesionEnergyParameter (double labelledCellLabelledCellAdhesionEnergyParameter)
void SetNagaiHondaLabelledCellBoundaryAdhesionEnergyParameter (double labelledCellBoundaryAdhesionEnergyParameter)
void OutputForceParameters (out_stream &rParamsFile)
Public Member Functions inherited from NagaiHondaForce< DIM >
NagaiHondaForce ()
virtual ~NagaiHondaForce ()
virtual void AddForceContribution (AbstractCellPopulation< DIM > &rCellPopulation)
double GetNagaiHondaDeformationEnergyParameter ()
double GetNagaiHondaMembraneSurfaceEnergyParameter ()
double GetNagaiHondaCellCellAdhesionEnergyParameter ()
double GetNagaiHondaCellBoundaryAdhesionEnergyParameter ()
void SetNagaiHondaDeformationEnergyParameter (double nagaiHondaDeformationEnergyParameter)
void SetNagaiHondaMembraneSurfaceEnergyParameter (double nagaiHondaMembraneSurfaceEnergyParameter)
void SetNagaiHondaCellCellAdhesionEnergyParameter (double nagaiHondaCellCellAdhesionEnergyEnergyParameter)
void SetNagaiHondaCellBoundaryAdhesionEnergyParameter (double nagaiHondaCellBoundaryAdhesionEnergyParameter)
void OutputForceParameters (out_stream &rParamsFile)
Public Member Functions inherited from AbstractForce< DIM >
AbstractForce ()
virtual ~AbstractForce ()
virtual void AddForceContribution (AbstractCellPopulation< ELEMENT_DIM, ELEMENT_DIM > &rCellPopulation)=0
void OutputForceInfo (out_stream &rParamsFile)
virtual void WriteDataToVisualizerSetupFile (out_stream &pVizSetupFile)
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Private Attributes
double mNagaiHondaLabelledCellLabelledCellAdhesionEnergyParameter
double mNagaiHondaLabelledCellCellAdhesionEnergyParameter
double mNagaiHondaLabelledCellBoundaryAdhesionEnergyParameter
Friends
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from NagaiHondaForce< DIM >
double mNagaiHondaDeformationEnergyParameter
double mNagaiHondaMembraneSurfaceEnergyParameter
double mNagaiHondaCellCellAdhesionEnergyParameter
double mNagaiHondaCellBoundaryAdhesionEnergyParameter
Detailed Description
template<unsigned DIM>
class NagaiHondaDifferentialAdhesionForce< DIM >
A force class for use in vertex-based simulations, based on a model model proposed by T. Nagai and H. Honda ("A dynamic cell model for the formation of epithelial tissues", Philosophical Magazine Part B 81:699-719) to include differential adhesion between normal and labelled cells. To include differential adhesion we override the GetAdhesionParameter() method.
Each of the model parameter member variables are rescaled such that mDampingConstantNormal takes the default value 1, whereas Nagai and Honda (who denote the parameter by nu) take the value 0.01.
Definition at line 59 of file NagaiHondaDifferentialAdhesionForce.hpp.
Constructor & Destructor Documentation
template<unsigned DIM> NagaiHondaDifferentialAdhesionForce< DIM >::NagaiHondaDifferentialAdhesionForce ()
Constructor.
Definition at line 40 of file NagaiHondaDifferentialAdhesionForce.cpp.
Referenced by NagaiHondaDifferentialAdhesionForce< DIM >::serialize().
template<unsigned DIM> NagaiHondaDifferentialAdhesionForce< DIM >::~NagaiHondaDifferentialAdhesionForce () virtual
Destructor.
Definition at line 49 of file NagaiHondaDifferentialAdhesionForce.cpp.
Referenced by NagaiHondaDifferentialAdhesionForce< DIM >::serialize().
Member Function Documentation
template<unsigned DIM> double NagaiHondaDifferentialAdhesionForce< DIM >::GetAdhesionParameter (Node< DIM > * pNodeA, Node< DIM > * pNodeB, VertexBasedCellPopulation< DIM > & rVertexCellPopulation) virtual
Overridden GetAdhesionParameter() method.
Get the adhesion parameter for the edge between two given nodes. Depends on the type of cells attached to the elements.
Parameters
pNodeA one node
pNodeB the other node
rVertexCellPopulation reference to the cell population
Returns
the adhesion parameter for this edge.
Reimplemented from NagaiHondaForce< DIM >.
Definition at line 54 of file NagaiHondaDifferentialAdhesionForce.cpp.
References AbstractCellPopulation< ELEMENT_DIM, ELEMENT_DIM >::GetCellUsingLocationIndex(), NagaiHondaForce< DIM >::GetNagaiHondaCellBoundaryAdhesionEnergyParameter(), NagaiHondaForce< DIM >::GetNagaiHondaCellCellAdhesionEnergyParameter(), NagaiHondaDifferentialAdhesionForce< DIM >::GetNagaiHondaLabelledCellBoundaryAdhesionEnergyParameter(), NagaiHondaDifferentialAdhesionForce< DIM >::GetNagaiHondaLabelledCellCellAdhesionEnergyParameter(), NagaiHondaDifferentialAdhesionForce< DIM >::GetNagaiHondaLabelledCellLabelledCellAdhesionEnergyParameter(), and Node< SPACE_DIM >::rGetContainingElementIndices().
Referenced by NagaiHondaDifferentialAdhesionForce< DIM >::serialize().
template<unsigned DIM> double NagaiHondaDifferentialAdhesionForce< DIM >::GetNagaiHondaLabelledCellBoundaryAdhesionEnergyParameter ()
Returns
mNagaiHondaLabelledCellBoundaryAdhesionEnergyParameter
Definition at line 143 of file NagaiHondaDifferentialAdhesionForce.cpp.
References NagaiHondaDifferentialAdhesionForce< DIM >::mNagaiHondaLabelledCellBoundaryAdhesionEnergyParameter.
Referenced by NagaiHondaDifferentialAdhesionForce< DIM >::GetAdhesionParameter(), and NagaiHondaDifferentialAdhesionForce< DIM >::serialize().
template<unsigned DIM> double NagaiHondaDifferentialAdhesionForce< DIM >::GetNagaiHondaLabelledCellCellAdhesionEnergyParameter ()
Returns
mNagaiHondaLabelledCellCellAdhesionEnergyParameter
Definition at line 131 of file NagaiHondaDifferentialAdhesionForce.cpp.
References NagaiHondaDifferentialAdhesionForce< DIM >::mNagaiHondaLabelledCellCellAdhesionEnergyParameter.
Referenced by NagaiHondaDifferentialAdhesionForce< DIM >::GetAdhesionParameter(), and NagaiHondaDifferentialAdhesionForce< DIM >::serialize().
template<unsigned DIM> double NagaiHondaDifferentialAdhesionForce< DIM >::GetNagaiHondaLabelledCellLabelledCellAdhesionEnergyParameter ()
Returns
mNagaiHondaLabelledCellLabelledCellAdhesionEnergyParameter
Definition at line 137 of file NagaiHondaDifferentialAdhesionForce.cpp.
References NagaiHondaDifferentialAdhesionForce< DIM >::mNagaiHondaLabelledCellLabelledCellAdhesionEnergyParameter.
Referenced by NagaiHondaDifferentialAdhesionForce< DIM >::GetAdhesionParameter(), and NagaiHondaDifferentialAdhesionForce< DIM >::serialize().
template<unsigned DIM> void NagaiHondaDifferentialAdhesionForce< DIM >::OutputForceParameters (out_stream & rParamsFile) virtual
Overridden OutputForceParameters() method.
Parameters
rParamsFile the file stream to which the parameters are output
Implements AbstractForce< DIM >.
Definition at line 167 of file NagaiHondaDifferentialAdhesionForce.cpp.
References EXPORT_TEMPLATE_CLASS_SAME_DIMS, NagaiHondaDifferentialAdhesionForce< DIM >::mNagaiHondaLabelledCellBoundaryAdhesionEnergyParameter, NagaiHondaDifferentialAdhesionForce< DIM >::mNagaiHondaLabelledCellCellAdhesionEnergyParameter, NagaiHondaDifferentialAdhesionForce< DIM >::mNagaiHondaLabelledCellLabelledCellAdhesionEnergyParameter, and NagaiHondaForce< DIM >::OutputForceParameters().
Referenced by NagaiHondaDifferentialAdhesionForce< DIM >::serialize().
template<unsigned DIM> template<class Archive > void NagaiHondaDifferentialAdhesionForce< DIM >::serialize (Archive & archive, const unsigned int version) inline private
Boost Serialization method for archiving/checkpointing. Archives the object and its member variables.
Parameters
archive The boost archive.
version The current version of this class.
Definition at line 93 of file NagaiHondaDifferentialAdhesionForce.hpp.
References EXPORT_TEMPLATE_CLASS_SAME_DIMS, NagaiHondaDifferentialAdhesionForce< DIM >::GetAdhesionParameter(), NagaiHondaDifferentialAdhesionForce< DIM >::GetNagaiHondaLabelledCellBoundaryAdhesionEnergyParameter(), NagaiHondaDifferentialAdhesionForce< DIM >::GetNagaiHondaLabelledCellCellAdhesionEnergyParameter(), NagaiHondaDifferentialAdhesionForce< DIM >::GetNagaiHondaLabelledCellLabelledCellAdhesionEnergyParameter(), NagaiHondaDifferentialAdhesionForce< DIM >::mNagaiHondaLabelledCellBoundaryAdhesionEnergyParameter, NagaiHondaDifferentialAdhesionForce< DIM >::mNagaiHondaLabelledCellCellAdhesionEnergyParameter, NagaiHondaDifferentialAdhesionForce< DIM >::mNagaiHondaLabelledCellLabelledCellAdhesionEnergyParameter, NagaiHondaDifferentialAdhesionForce< DIM >::NagaiHondaDifferentialAdhesionForce(), NagaiHondaDifferentialAdhesionForce< DIM >::OutputForceParameters(), NagaiHondaDifferentialAdhesionForce< DIM >::SetNagaiHondaLabelledCellBoundaryAdhesionEnergyParameter(), NagaiHondaDifferentialAdhesionForce< DIM >::SetNagaiHondaLabelledCellCellAdhesionEnergyParameter(), NagaiHondaDifferentialAdhesionForce< DIM >::SetNagaiHondaLabelledCellLabelledCellAdhesionEnergyParameter(), and NagaiHondaDifferentialAdhesionForce< DIM >::~NagaiHondaDifferentialAdhesionForce().
template<unsigned DIM> void NagaiHondaDifferentialAdhesionForce< DIM >::SetNagaiHondaLabelledCellBoundaryAdhesionEnergyParameter (double labelledCellBoundaryAdhesionEnergyParameter)
Set mNagaiHondaLabelledCellBoundaryAdhesionEnergyParameter.
Parameters
labelledCellBoundaryAdhesionEnergyParameter the new value of mNagaiHondaLabelledCellBoundaryAdhesionEnergyParameter
Definition at line 161 of file NagaiHondaDifferentialAdhesionForce.cpp.
References NagaiHondaDifferentialAdhesionForce< DIM >::mNagaiHondaLabelledCellBoundaryAdhesionEnergyParameter.
Referenced by NagaiHondaDifferentialAdhesionForce< DIM >::serialize().
template<unsigned DIM> void NagaiHondaDifferentialAdhesionForce< DIM >::SetNagaiHondaLabelledCellCellAdhesionEnergyParameter (double labelledCellCellAdhesionEnergyParameter)
Set mNagaiHondaLabelledCellCellAdhesionEnergyParameter.
Parameters
labelledCellCellAdhesionEnergyParameter the new value of mNagaiHondaLabelledCellCellAdhesionEnergyParameter
Definition at line 149 of file NagaiHondaDifferentialAdhesionForce.cpp.
References NagaiHondaDifferentialAdhesionForce< DIM >::mNagaiHondaLabelledCellCellAdhesionEnergyParameter.
Referenced by NagaiHondaDifferentialAdhesionForce< DIM >::serialize().
template<unsigned DIM> void NagaiHondaDifferentialAdhesionForce< DIM >::SetNagaiHondaLabelledCellLabelledCellAdhesionEnergyParameter (double labelledCellLabelledCellAdhesionEnergyParameter)
Set mNagaiHondaLabelledCellLabelledCellAdhesionEnergyParameter.
Parameters
labelledCellLabelledCellAdhesionEnergyParameter the new value of mNagaiHondaLabelledCellLabelledCellAdhesionEnergyParameter
Definition at line 155 of file NagaiHondaDifferentialAdhesionForce.cpp.
References NagaiHondaDifferentialAdhesionForce< DIM >::mNagaiHondaLabelledCellLabelledCellAdhesionEnergyParameter.
Referenced by NagaiHondaDifferentialAdhesionForce< DIM >::serialize().
Member Data Documentation
template<unsigned DIM> double NagaiHondaDifferentialAdhesionForce< DIM >::mNagaiHondaLabelledCellBoundaryAdhesionEnergyParameter private
Cell-boundary adhesion energy parameter for labelled cells. Has units of kg (cell size at equilibrium rest length)^2 s^-2. Takes the default value 1.0.
Definition at line 82 of file NagaiHondaDifferentialAdhesionForce.hpp.
Referenced by NagaiHondaDifferentialAdhesionForce< DIM >::GetNagaiHondaLabelledCellBoundaryAdhesionEnergyParameter(), NagaiHondaDifferentialAdhesionForce< DIM >::OutputForceParameters(), NagaiHondaDifferentialAdhesionForce< DIM >::serialize(), and NagaiHondaDifferentialAdhesionForce< DIM >::SetNagaiHondaLabelledCellBoundaryAdhesionEnergyParameter().
template<unsigned DIM> double NagaiHondaDifferentialAdhesionForce< DIM >::mNagaiHondaLabelledCellCellAdhesionEnergyParameter private
Cell-cell adhesion energy parameter for labelled and non-labelled cells. Has has units of kg (cell size at equilibrium rest length)^2 s^-2. Takes the default value 1.0.
Definition at line 75 of file NagaiHondaDifferentialAdhesionForce.hpp.
Referenced by NagaiHondaDifferentialAdhesionForce< DIM >::GetNagaiHondaLabelledCellCellAdhesionEnergyParameter(), NagaiHondaDifferentialAdhesionForce< DIM >::OutputForceParameters(), NagaiHondaDifferentialAdhesionForce< DIM >::serialize(), and NagaiHondaDifferentialAdhesionForce< DIM >::SetNagaiHondaLabelledCellCellAdhesionEnergyParameter().
template<unsigned DIM> double NagaiHondaDifferentialAdhesionForce< DIM >::mNagaiHondaLabelledCellLabelledCellAdhesionEnergyParameter private
Cell-cell adhesion energy parameter for two labelled cells. Has units of kg (cell size at equilibrium rest length)^2 s^-2. Takes the default value 1.0.
Definition at line 68 of file NagaiHondaDifferentialAdhesionForce.hpp.
Referenced by NagaiHondaDifferentialAdhesionForce< DIM >::GetNagaiHondaLabelledCellLabelledCellAdhesionEnergyParameter(), NagaiHondaDifferentialAdhesionForce< DIM >::OutputForceParameters(), NagaiHondaDifferentialAdhesionForce< DIM >::serialize(), and NagaiHondaDifferentialAdhesionForce< DIM >::SetNagaiHondaLabelledCellLabelledCellAdhesionEnergyParameter().
The documentation for this class was generated from the following files:
cell_based/src/population/forces/NagaiHondaDifferentialAdhesionForce.hpp
cell_based/src/population/forces/NagaiHondaDifferentialAdhesionForce.cpp