Chaste: boost::random::gamma_distribution_v165< RealType >::param_type Class Reference
boost::random::gamma_distribution_v165< RealType >::param_type Class Reference
Public Types
typedef gamma_distribution_v165 distribution_type
Public Member Functions
param_type (const RealType &alpha_arg=RealType(1.0), const RealType &beta_arg=RealType(1.0))
RealType alpha () const
RealType beta () const
Private Attributes
RealType _alpha
RealType _beta
Friends
template<class CharT , class Traits >
std::basic_ostream< CharT, Traits > & operator<< (std::basic_ostream< CharT, Traits > &os, const param_type &parm)
template<class CharT , class Traits >
std::basic_istream< CharT, Traits > & operator>> (std::basic_istream< CharT, Traits > &is, param_type &parm)
bool operator== (const param_type &lhs, const param_type &rhs)
bool operator!= (const param_type &lhs, const param_type &rhs)
Detailed Description
template<class RealType = double>
class boost::random::gamma_distribution_v165< RealType >::param_type
Definition at line 65 of file Boost165GammaDistribution.hpp.
Constructor & Destructor Documentation
template<class RealType = double> boost::random::gamma_distribution_v165< RealType >::param_type::param_type (const RealType & alpha_arg = RealType(1.0), const RealType & beta_arg = RealType(1.0)) inline
Constructs a param_type object from the "alpha" and "beta" parameters.
Requires: alpha > 0 && beta > 0
Definition at line 76 of file Boost165GammaDistribution.hpp.
Referenced by boost::random::gamma_distribution_v165< RealType >::param().
Member Function Documentation
template<class RealType = double> RealType boost::random::gamma_distribution_v165< RealType >::param_type::alpha () const inline
Returns the "alpha" parameter of the distribution.
Definition at line 83 of file Boost165GammaDistribution.hpp.
Referenced by boost::random::gamma_distribution_v165< RealType >::param().
template<class RealType = double> RealType boost::random::gamma_distribution_v165< RealType >::param_type::beta () const inline
Returns the "beta" parameter of the distribution.
Definition at line 85 of file Boost165GammaDistribution.hpp.
Referenced by boost::random::gamma_distribution_v165< RealType >::param().
Friends And Related Function Documentation
template<class RealType = double> bool operator!= (const param_type & lhs, const param_type & rhs) friend
Returns true if the two sets fo parameters are different.
Definition at line 114 of file Boost165GammaDistribution.hpp.
template<class RealType = double> template<class CharT , class Traits > std::basic_ostream<CharT, Traits>& operator<< (std::basic_ostream< CharT, Traits > & os, const param_type & parm) friend
Writes the parameters to a std::ostream.
Definition at line 91 of file Boost165GammaDistribution.hpp.
template<class RealType = double> bool operator== (const param_type & lhs, const param_type & rhs) friend
Returns true if the two sets of parameters are the same.
Definition at line 109 of file Boost165GammaDistribution.hpp.
template<class RealType = double> template<class CharT , class Traits > std::basic_istream<CharT, Traits>& operator>> (std::basic_istream< CharT, Traits > & is, param_type & parm) friend
Reads the parameters from a std::istream.
Definition at line 101 of file Boost165GammaDistribution.hpp.
The documentation for this class was generated from the following file:
global/src/random/Boost165GammaDistribution.hpp