Chaste: QuadraticBasisFunction< ELEMENT_DIM > Class Template Reference
QuadraticBasisFunction< ELEMENT_DIM > Class Template Reference
#include <QuadraticBasisFunction.hpp>
Static Public Member Functions
static double ComputeBasisFunction (const ChastePoint< ELEMENT_DIM > &rPoint, unsigned basisIndex)
static c_vector< double, ELEMENT_DIM > ComputeBasisFunctionDerivative (const ChastePoint< ELEMENT_DIM > &rPoint, unsigned basisIndex)
static void ComputeBasisFunctions (const ChastePoint< ELEMENT_DIM > &rPoint, c_vector< double,(ELEMENT_DIM+1)*(ELEMENT_DIM+2)/2 > &rReturnValue)
static void ComputeBasisFunctionDerivatives (const ChastePoint< ELEMENT_DIM > &rPoint, c_matrix< double, ELEMENT_DIM,(ELEMENT_DIM+1)*(ELEMENT_DIM+2)/2 > &rReturnValue)
static void ComputeTransformedBasisFunctionDerivatives (const ChastePoint< ELEMENT_DIM > &rPoint, const c_matrix< double, ELEMENT_DIM, ELEMENT_DIM > &rInverseJacobian, c_matrix< double, ELEMENT_DIM,(ELEMENT_DIM+1)*(ELEMENT_DIM+2)/2 > &rReturnValue)
Detailed Description
template<unsigned ELEMENT_DIM>
class QuadraticBasisFunction< ELEMENT_DIM >
Quadratic basis functions for the finite element method, computed on a canonical element.
Definition at line 46 of file QuadraticBasisFunction.hpp.
Member Function Documentation
template<unsigned ELEMENT_DIM> double QuadraticBasisFunction< ELEMENT_DIM >::ComputeBasisFunction (const ChastePoint< ELEMENT_DIM > & rPoint, unsigned basisIndex) static
Compute a basis function at a point within an element.
Parameters
rPoint The point at which to compute the basis function. The results are undefined if this is not within the canonical element.
basisIndex Which basis function to compute. This is a local index within a canonical element.
Returns
The value of the basis function.
Definition at line 78 of file QuadraticBasisFunction.cpp.
References NEVER_REACHED.
Referenced by QuadraticBasisFunction< ELEMENT_DIM >::ComputeBasisFunctions(), and QuadraticBasisFunction< 0 >::ComputeBasisFunctions().
template<unsigned ELEMENT_DIM> c_vector< double, ELEMENT_DIM > QuadraticBasisFunction< ELEMENT_DIM >::ComputeBasisFunctionDerivative (const ChastePoint< ELEMENT_DIM > & rPoint, unsigned basisIndex) static
Compute the derivative of a basis function at a point within an canonical element.
Parameters
rPoint The point at which to compute the basis function. The results are undefined if this is not within the canonical element.
basisIndex Which basis function to compute. This is a local index within a canonical element.
Returns
The derivative of the basis function. This is a vector (c_vector instance) giving the derivative along each axis.
Definition at line 190 of file QuadraticBasisFunction.cpp.
References NEVER_REACHED.
Referenced by QuadraticBasisFunction< ELEMENT_DIM >::ComputeBasisFunctionDerivatives().
template<unsigned ELEMENT_DIM> void QuadraticBasisFunction< ELEMENT_DIM >::ComputeBasisFunctionDerivatives (const ChastePoint< ELEMENT_DIM > & rPoint, c_matrix< double, ELEMENT_DIM,(ELEMENT_DIM+1)*(ELEMENT_DIM+2)/2 > & rReturnValue) static
Compute the derivatives of all basis functions at a point within an element.
Parameters
rPoint The point at which to compute the basis functions. The results are undefined if this is not within the canonical element.
rReturnValue The derivatives of the basis functions, in local index order. Each column of the matrix gives the derivative along each axis.
Definition at line 343 of file QuadraticBasisFunction.cpp.
References QuadraticBasisFunction< ELEMENT_DIM >::ComputeBasisFunctionDerivative().
Referenced by QuadraticBasisFunction< ELEMENT_DIM >::ComputeTransformedBasisFunctionDerivatives().
template<unsigned ELEMENT_DIM> void QuadraticBasisFunction< ELEMENT_DIM >::ComputeBasisFunctions (const ChastePoint< ELEMENT_DIM > & rPoint, c_vector< double,(ELEMENT_DIM+1)*(ELEMENT_DIM+2)/2 > & rReturnValue) static
Compute all basis functions at a point within an element.
Parameters
rPoint The point at which to compute the basis functions. The results are undefined if this is not within the canonical element.
rReturnValue The values of the basis functions, in local index order.
Definition at line 322 of file QuadraticBasisFunction.cpp.
References QuadraticBasisFunction< ELEMENT_DIM >::ComputeBasisFunction().
Referenced by ContinuumMechanicsNeumannBcsAssembler< DIM >::AssembleOnBoundaryElement(), AbstractNonlinearElasticitySolver< DIM >::AssembleOnBoundaryElement(), AbstractNonlinearElasticitySolver< DIM >::AssembleOnBoundaryElementForPressureOnDeformedBc(), IncompressibleNonlinearElasticitySolver< DIM >::AssembleOnElement(), CompressibleNonlinearElasticitySolver< DIM >::AssembleOnElement(), and AbstractContinuumMechanicsAssembler< DIM, CAN_ASSEMBLE_VECTOR, CAN_ASSEMBLE_MATRIX >::AssembleOnElement().
template<unsigned ELEMENT_DIM> void QuadraticBasisFunction< ELEMENT_DIM >::ComputeTransformedBasisFunctionDerivatives (const ChastePoint< ELEMENT_DIM > & rPoint, const c_matrix< double, ELEMENT_DIM, ELEMENT_DIM > & rInverseJacobian, c_matrix< double, ELEMENT_DIM,(ELEMENT_DIM+1)*(ELEMENT_DIM+2)/2 > & rReturnValue) static
Compute the derivatives of all basis functions at a point within an element. This method will transform the results, for use within gaussian quadrature for example.
Parameters
rPoint The point at which to compute the basis functions. The results are undefined if this is not within the canonical element.
rInverseJacobian The inverse of the Jacobian matrix mapping the real element into the canonical element.
rReturnValue The derivatives of the basis functions, in local index order. Each entry is a vector (VectorDouble instance) giving the derivative along each axis.
Definition at line 369 of file QuadraticBasisFunction.cpp.
References QuadraticBasisFunction< ELEMENT_DIM >::ComputeBasisFunctionDerivatives().
Referenced by AbstractNonlinearElasticitySolver< DIM >::AssembleOnBoundaryElementForPressureOnDeformedBc(), IncompressibleNonlinearElasticitySolver< DIM >::AssembleOnElement(), CompressibleNonlinearElasticitySolver< DIM >::AssembleOnElement(), AbstractContinuumMechanicsAssembler< DIM, CAN_ASSEMBLE_VECTOR, CAN_ASSEMBLE_MATRIX >::AssembleOnElement(), and AbstractNonlinearElasticitySolver< DIM >::GetElementCentroidStrain().
The documentation for this class was generated from the following files:
pde/src/solver/QuadraticBasisFunction.hpp
pde/src/solver/QuadraticBasisFunction.cpp