Chaste: ShovingCaBasedDivisionRule< SPACE_DIM > Class Template Reference
ShovingCaBasedDivisionRule< SPACE_DIM > Class Template Reference
#include <ShovingCaBasedDivisionRule.hpp>
Public Member Functions
ShovingCaBasedDivisionRule ()
virtual ~ShovingCaBasedDivisionRule ()
void IsNodeOnBoundary (unsigned numNeighbours)
virtual bool IsRoomToDivide (CellPtr pParentCell, CaBasedCellPopulation< SPACE_DIM > &rCellPopulation)
virtual unsigned CalculateDaughterNodeIndex (CellPtr pNewCell, CellPtr pParentCell, CaBasedCellPopulation< SPACE_DIM > &rCellPopulation)
Public Member Functions inherited from AbstractCaBasedDivisionRule< SPACE_DIM >
AbstractCaBasedDivisionRule ()
virtual ~AbstractCaBasedDivisionRule ()
void OutputCellCaBasedDivisionRuleInfo (out_stream &rParamsFile)
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Friends
class boost::serialization::access
Additional Inherited Members
Protected Member Functions inherited from AbstractCaBasedDivisionRule< SPACE_DIM >
virtual void OutputCellCaBasedDivisionRuleParameters (out_stream &rParamsFile)
Detailed Description
template<unsigned SPACE_DIM>
class ShovingCaBasedDivisionRule< SPACE_DIM >
A division rule for CA-based cell populations that specifies how cells divide. Here they can divide in any direction and shove other cells out of the way in that direction.
Definition at line 54 of file ShovingCaBasedDivisionRule.hpp.
Constructor & Destructor Documentation
template<unsigned SPACE_DIM> ShovingCaBasedDivisionRule< SPACE_DIM >::ShovingCaBasedDivisionRule () inline
Default constructor.
Definition at line 76 of file ShovingCaBasedDivisionRule.hpp.
template<unsigned SPACE_DIM> virtual ShovingCaBasedDivisionRule< SPACE_DIM >::~ShovingCaBasedDivisionRule () inline virtual
Empty destructor.
Definition at line 81 of file ShovingCaBasedDivisionRule.hpp.
References ShovingCaBasedDivisionRule< SPACE_DIM >::CalculateDaughterNodeIndex(), EXPORT_TEMPLATE_CLASS_SAME_DIMS, ShovingCaBasedDivisionRule< SPACE_DIM >::IsNodeOnBoundary(), and ShovingCaBasedDivisionRule< SPACE_DIM >::IsRoomToDivide().
Member Function Documentation
template<unsigned SPACE_DIM> unsigned ShovingCaBasedDivisionRule< SPACE_DIM >::CalculateDaughterNodeIndex (CellPtr pNewCell, CellPtr pParentCell, CaBasedCellPopulation< SPACE_DIM > & rCellPopulation) virtual
Return the index for the daughter node. This method can be used to move cells out of the way as necessary.
Parameters
pNewCell The cell to new cell
pParentCell The parent cell
rCellPopulation The CA-based cell population
Returns
the node index for the daughter cell.
Implements AbstractCaBasedDivisionRule< SPACE_DIM >.
Definition at line 68 of file ShovingCaBasedDivisionRule.cpp.
References CaBasedCellPopulation< DIM >::EvaluateDivisionPropensity(), EXPORT_TEMPLATE_CLASS_SAME_DIMS, AbstractCellPopulation< DIM >::GetCellUsingLocationIndex(), AbstractCellPopulation< DIM >::GetLocationIndexUsingCell(), PottsMesh< DIM >::GetMooreNeighbouringNodeIndices(), RandomNumberGenerator::Instance(), CaBasedCellPopulation< DIM >::IsSiteAvailable(), AbstractCellPopulation< DIM >::MoveCellInLocationMap(), RandomNumberGenerator::ranf(), CaBasedCellPopulation< DIM >::rGetMesh(), and UNSIGNED_UNSET.
Referenced by ShovingCaBasedDivisionRule< SPACE_DIM >::~ShovingCaBasedDivisionRule().
template<unsigned SPACE_DIM> void ShovingCaBasedDivisionRule< SPACE_DIM >::IsNodeOnBoundary (unsigned numNeighbours)
Helper method to see if cells are on the boundary of the domain. Throws exception if cells boundary of the domain.
Parameters
numNeighbours the number of neighbours of the node.
Definition at line 40 of file ShovingCaBasedDivisionRule.cpp.
References EXCEPTION, and NEVER_REACHED.
Referenced by ShovingCaBasedDivisionRule< SPACE_DIM >::~ShovingCaBasedDivisionRule().
template<unsigned SPACE_DIM> bool ShovingCaBasedDivisionRule< SPACE_DIM >::IsRoomToDivide (CellPtr pParentCell, CaBasedCellPopulation< SPACE_DIM > & rCellPopulation) virtual
Return whether there is room to divide at all.
Parameters
pParentCell The cell to divide
rCellPopulation The CA-based cell population
Returns
if the site is available.
Implements AbstractCaBasedDivisionRule< SPACE_DIM >.
Definition at line 62 of file ShovingCaBasedDivisionRule.cpp.
Referenced by ShovingCaBasedDivisionRule< SPACE_DIM >::~ShovingCaBasedDivisionRule().
template<unsigned SPACE_DIM> template<class Archive > void ShovingCaBasedDivisionRule< SPACE_DIM >::serialize (Archive & archive, const unsigned int version) inline private
Serialize the object and its member variables.
Parameters
archive the archive
version the current version of this class
Definition at line 66 of file ShovingCaBasedDivisionRule.hpp.
The documentation for this class was generated from the following files:
cell_based/src/population/division_rules/ShovingCaBasedDivisionRule.hpp
cell_based/src/population/division_rules/ShovingCaBasedDivisionRule.cpp