Chaste: AbstractUntemplatedParameterisedSystem Class Reference
AbstractUntemplatedParameterisedSystem Class Reference abstract
#include <AbstractUntemplatedParameterisedSystem.hpp>
Public Member Functions
AbstractUntemplatedParameterisedSystem (unsigned numberOfStateVariables)
virtual ~AbstractUntemplatedParameterisedSystem ()
boost::shared_ptr< const AbstractOdeSystemInformation > GetSystemInformation () const
std::string GetSystemName () const
unsigned GetNumberOfAttributes () const
bool HasAttribute (const std::string &rName) const
double GetAttribute (const std::string &rName) const
unsigned GetNumberOfStateVariables () const
const std::vector< std::string > & rGetStateVariableNames () const
const std::vector< std::string > & rGetStateVariableUnits () const
unsigned GetStateVariableIndex (const std::string &rName) const
bool HasStateVariable (const std::string &rName) const
std::string GetStateVariableUnits (unsigned index) const
virtual void ResetToInitialConditions ()=0
unsigned GetNumberOfParameters () const
const std::vector< std::string > & rGetParameterNames () const
const std::vector< std::string > & rGetParameterUnits () const
unsigned GetParameterIndex (const std::string &rName) const
bool HasParameter (const std::string &rName) const
std::string GetParameterUnits (unsigned index) const
unsigned GetNumberOfDerivedQuantities () const
const std::vector< std::string > & rGetDerivedQuantityNames () const
const std::vector< std::string > & rGetDerivedQuantityUnits () const
unsigned GetDerivedQuantityIndex (const std::string &rName) const
bool HasDerivedQuantity (const std::string &rName) const
std::string GetDerivedQuantityUnits (unsigned index) const
unsigned GetAnyVariableIndex (const std::string &rName) const
bool HasAnyVariable (const std::string &rName) const
std::string GetAnyVariableUnits (unsigned index) const
std::string GetAnyVariableUnits (const std::string &rName) const
Protected Attributes
unsigned mNumberOfStateVariables
boost::shared_ptr< AbstractOdeSystemInformation > mpSystemInfo
Detailed Description
This class is an untemplated base class for AbstractParameterisedSystem, containing those methods which don't require knowledge of the vector type, in order to make it easier to move between templated and generic parts of the codebase. In particular it holds the AbstractOdeSystemInformation pointer, and methods to access this object to provide information about the ODE system, such as state variable/parameter names and units.
Definition at line 53 of file AbstractUntemplatedParameterisedSystem.hpp.
Constructor & Destructor Documentation
AbstractUntemplatedParameterisedSystem::AbstractUntemplatedParameterisedSystem (unsigned numberOfStateVariables)
Constructor.
Parameters
numberOfStateVariables the number of state variables in the ODE system
Definition at line 43 of file AbstractUntemplatedParameterisedSystem.cpp.
AbstractUntemplatedParameterisedSystem::~AbstractUntemplatedParameterisedSystem () virtual
Make this class polymorphic.
Definition at line 48 of file AbstractUntemplatedParameterisedSystem.cpp.
Member Function Documentation
unsigned AbstractUntemplatedParameterisedSystem::GetAnyVariableIndex (const std::string & rName) const
Returns
the index of a variable, whether a state variable, parameter, or derived quantity, with the given name. The returned index is suitable for use with GetAnyVariableUnits, GetAnyVariable, etc.
Parameters
rName the name of a variable
Definition at line 136 of file AbstractUntemplatedParameterisedSystem.cpp.
References GetSystemInformation().
Referenced by AbstractParameterisedSystem< VECTOR >::GetAnyVariable(), GetAnyVariableUnits(), and AbstractParameterisedSystem< VECTOR >::SetAnyVariable().
std::string AbstractUntemplatedParameterisedSystem::GetAnyVariableUnits (unsigned index) const
Returns
the units of a variable, whether a state variable, parameter, or derived quantity, given its index as returned by GetAnyVariableIndex.
Parameters
index an index from GetAnyVariableIndex.
Returns
the units of the variable.
Definition at line 146 of file AbstractUntemplatedParameterisedSystem.cpp.
References GetSystemInformation().
Referenced by GetAnyVariableUnits().
std::string AbstractUntemplatedParameterisedSystem::GetAnyVariableUnits (const std::string & rName) const
Returns
the units of a variable, whether a state variable, parameter, or derived quantity, given its index as returned by GetAnyVariableIndex.
Parameters
rName the name of any variable in the model.
Returns
the units of the variable.
Definition at line 151 of file AbstractUntemplatedParameterisedSystem.cpp.
References GetAnyVariableIndex(), and GetAnyVariableUnits().
double AbstractUntemplatedParameterisedSystem::GetAttribute (const std::string & rName) const
Returns
the value of a named attribute.
Parameters
rName the attribute name.
Definition at line 201 of file AbstractUntemplatedParameterisedSystem.cpp.
References GetSystemInformation().
unsigned AbstractUntemplatedParameterisedSystem::GetDerivedQuantityIndex (const std::string & rName) const
Returns
the index of a derived quantity, given its name.
Parameters
rName the name of a derived quantity.
Definition at line 175 of file AbstractUntemplatedParameterisedSystem.cpp.
References GetSystemInformation().
std::string AbstractUntemplatedParameterisedSystem::GetDerivedQuantityUnits (unsigned index) const
Returns
the units of a derived quantity.
Parameters
index an index from GetDerivedQuantityIndex.
Returns
the units of the variable.
Definition at line 185 of file AbstractUntemplatedParameterisedSystem.cpp.
References GetSystemInformation().
unsigned AbstractUntemplatedParameterisedSystem::GetNumberOfAttributes () const
Returns
the number of named attributes that this system has.
Definition at line 191 of file AbstractUntemplatedParameterisedSystem.cpp.
References GetSystemInformation().
unsigned AbstractUntemplatedParameterisedSystem::GetNumberOfDerivedQuantities () const
Returns
the number of derived quantities.
Definition at line 160 of file AbstractUntemplatedParameterisedSystem.cpp.
References GetSystemInformation().
Referenced by AbstractParameterisedSystem< VECTOR >::GetAnyVariable(), and OdeSolution::rGetDerivedQuantities().
unsigned AbstractUntemplatedParameterisedSystem::GetNumberOfParameters () const
Returns
the number of parameters.
Definition at line 102 of file AbstractUntemplatedParameterisedSystem.cpp.
References GetSystemInformation().
Referenced by AbstractCvodeCell::GetNumberOfParameters(), AbstractCardiacCell::GetNumberOfParameters(), and OdeSolution::rGetParameters().
unsigned AbstractUntemplatedParameterisedSystem::GetNumberOfStateVariables () const
Returns
the number of state variables in the ODE system.
mNumberOfStateVariables
Definition at line 68 of file AbstractUntemplatedParameterisedSystem.cpp.
References mNumberOfStateVariables.
Referenced by HeunIvpOdeSolver::CalculateNextYValue(), RungeKutta2IvpOdeSolver::CalculateNextYValue(), RungeKutta4IvpOdeSolver::CalculateNextYValue(), RKC21IvpOdeSolver::CalculateNextYValue(), EulerIvpOdeSolver::CalculateNextYValue(), GRL1IvpOdeSolver::CalculateNextYValue(), GRL2IvpOdeSolver::CalculateNextYValue(), RungeKuttaFehlbergIvpOdeSolver::CalculateNextYValue(), BackwardEulerIvpOdeSolver::CalculateNextYValue(), AbstractCvodeCell::GetNumberOfStateVariables(), AbstractCardiacCell::GetNumberOfStateVariables(), RungeKuttaFehlbergIvpOdeSolver::InternalSolve(), AbstractOdeBasedCellCycleModel::ReadyToDivide(), AbstractCvodeSystem::RecordStoppingPoint(), CvodeAdaptor::SetupCvode(), AbstractCvodeSystem::SetupCvode(), AbstractOneStepIvpOdeSolver::Solve(), RungeKuttaFehlbergIvpOdeSolver::Solve(), AbstractIvpOdeSolver::SolveAndUpdateStateVariable(), and AbstractOdeBasedPhaseBasedCellCycleModel::UpdateCellCyclePhase().
unsigned AbstractUntemplatedParameterisedSystem::GetParameterIndex (const std::string & rName) const
This method is used to establish a parameter's position within the vector of parameters of an ODE system. This number can then be used with the methods GetParameterUnits and GetParameter.
Parameters
rName the name of a parameter
Returns
the parameter's position within the vector of parameters associated with the ODE system.
Definition at line 117 of file AbstractUntemplatedParameterisedSystem.cpp.
References GetSystemInformation().
Referenced by AbstractParameterisedSystem< VECTOR >::GetParameter(), and AbstractParameterisedSystem< VECTOR >::SetParameter().
std::string AbstractUntemplatedParameterisedSystem::GetParameterUnits (unsigned index) const
Returns
the units of a parameter given its index in the ODE system.
Parameters
index a state variable's position within the vector of state variables associated with the ODE system.
Returns
the units of the state variable.
Definition at line 127 of file AbstractUntemplatedParameterisedSystem.cpp.
References GetSystemInformation().
unsigned AbstractUntemplatedParameterisedSystem::GetStateVariableIndex (const std::string & rName) const
This method is used to establish a state variable's position within the vector of state variables of an ODE system. This number can then be used with the methods GetStateVariable and GetStateVariableUnits.
Parameters
rName the name of a state variable.
Returns
the state variable's position within the vector of state variables associated with the ODE system.
Definition at line 83 of file AbstractUntemplatedParameterisedSystem.cpp.
References GetSystemInformation().
Referenced by AbstractParameterisedSystem< VECTOR >::GetStateVariable(), and AbstractParameterisedSystem< VECTOR >::SetStateVariable().
std::string AbstractUntemplatedParameterisedSystem::GetStateVariableUnits (unsigned index) const
Returns
the units of a state variable given its index in the ODE system.
Parameters
index a state variable's position within the vector of state variables associated with the ODE system.
Returns
the units of the state variable.
Definition at line 93 of file AbstractUntemplatedParameterisedSystem.cpp.
References GetSystemInformation().
boost::shared_ptr< const AbstractOdeSystemInformation > AbstractUntemplatedParameterisedSystem::GetSystemInformation () const
Returns
the object which provides information about this ODE system.
Definition at line 52 of file AbstractUntemplatedParameterisedSystem.cpp.
References mpSystemInfo.
Referenced by OdeSolution::CalculateDerivedQuantitiesAndParameters(), GetAnyVariableIndex(), GetAnyVariableUnits(), GetAttribute(), GetDerivedQuantityIndex(), GetDerivedQuantityUnits(), GetNumberOfAttributes(), GetNumberOfDerivedQuantities(), GetNumberOfParameters(), GetParameterIndex(), GetParameterUnits(), GetStateVariableIndex(), GetStateVariableUnits(), GetSystemName(), HasAnyVariable(), HasAttribute(), HasDerivedQuantity(), HasParameter(), HasStateVariable(), rGetDerivedQuantityNames(), rGetDerivedQuantityUnits(), rGetParameterNames(), rGetParameterUnits(), rGetStateVariableNames(), rGetStateVariableUnits(), AbstractOneStepIvpOdeSolver::Solve(), and CvodeAdaptor::Solve().
std::string AbstractUntemplatedParameterisedSystem::GetSystemName () const
Returns
the name of this system.
Definition at line 59 of file AbstractUntemplatedParameterisedSystem.cpp.
References GetSystemInformation().
bool AbstractUntemplatedParameterisedSystem::HasAnyVariable (const std::string & rName) const
This method is used to establish whether a variable is in an ODE system's state vars, parameters or derived quantitites. You can then safely call GetAnyVariableIndex without a try...catch statement.
Parameters
rName the name of a variable
Returns
whether the variable is in this ODE system
Definition at line 141 of file AbstractUntemplatedParameterisedSystem.cpp.
References GetSystemInformation().
bool AbstractUntemplatedParameterisedSystem::HasAttribute (const std::string & rName) const
Returns
true if this system has a particular named attribute.
Parameters
rName the attribute name.
Definition at line 196 of file AbstractUntemplatedParameterisedSystem.cpp.
References GetSystemInformation().
bool AbstractUntemplatedParameterisedSystem::HasDerivedQuantity (const std::string & rName) const
This method is used to establish whether a derived quantity is in an ODE system. You can then safely call GetDerivedQuantityIndex without a try...catch statement.
Parameters
rName the name of a derived quantity
Returns
whether the derived quantity is in this ODE system
Definition at line 180 of file AbstractUntemplatedParameterisedSystem.cpp.
References GetSystemInformation().
bool AbstractUntemplatedParameterisedSystem::HasParameter (const std::string & rName) const
This method is used to establish whether a parameter is in an ODE system. You can then safely call GetParameterIndex without a try...catch statement.
Parameters
rName the name of a parameter
Returns
whether the parameter is in this ODE system
Definition at line 122 of file AbstractUntemplatedParameterisedSystem.cpp.
References GetSystemInformation().
bool AbstractUntemplatedParameterisedSystem::HasStateVariable (const std::string & rName) const
This method is used to establish whether a state variable is in an ODE system. You can then safely call GetStateVariableIndex without a try...catch statement.
Parameters
rName the name of a state variable
Returns
whether the state variable is in this ODE system
Definition at line 88 of file AbstractUntemplatedParameterisedSystem.cpp.
References GetSystemInformation().
virtual void AbstractUntemplatedParameterisedSystem::ResetToInitialConditions () pure virtual
Reset the system's state variables to the default initial conditions.
Implemented in AbstractParameterisedSystem< VECTOR >, AbstractParameterisedSystem< N_Vector >, and AbstractParameterisedSystem< std::vector< double > >.
const std::vector< std::string > & AbstractUntemplatedParameterisedSystem::rGetDerivedQuantityNames () const
Returns
the vector of derived quantity names.
Definition at line 165 of file AbstractUntemplatedParameterisedSystem.cpp.
References GetSystemInformation().
const std::vector< std::string > & AbstractUntemplatedParameterisedSystem::rGetDerivedQuantityUnits () const
Returns
the vector of derived quantity units.
Definition at line 170 of file AbstractUntemplatedParameterisedSystem.cpp.
References GetSystemInformation().
const std::vector< std::string > & AbstractUntemplatedParameterisedSystem::rGetParameterNames () const
Returns
the names of the parameters in the ODE system.
Definition at line 107 of file AbstractUntemplatedParameterisedSystem.cpp.
References GetSystemInformation().
Referenced by AbstractParameterisedSystem< VECTOR >::CheckParametersOnLoad(), AbstractCardiacCell::Init(), AbstractCvodeSystem::Init(), AbstractOdeSystem::save(), AbstractCvodeSystem::save(), and AbstractCardiacCell::serialize().
const std::vector< std::string > & AbstractUntemplatedParameterisedSystem::rGetParameterUnits () const
Returns
the units of the parameters in the ODE system.
Definition at line 112 of file AbstractUntemplatedParameterisedSystem.cpp.
References GetSystemInformation().
const std::vector< std::string > & AbstractUntemplatedParameterisedSystem::rGetStateVariableNames () const
Returns
the names of the state variables in the ODE system.
Definition at line 73 of file AbstractUntemplatedParameterisedSystem.cpp.
References GetSystemInformation().
Referenced by AbstractCvodeSystem::CvodeError(), AbstractParameterisedSystem< VECTOR >::GetStateMessage(), AbstractCvodeCell::rGetStateVariableNames(), and AbstractCardiacCell::rGetStateVariableNames().
const std::vector< std::string > & AbstractUntemplatedParameterisedSystem::rGetStateVariableUnits () const
Returns
the units of the state variables in the ODE system.
Definition at line 78 of file AbstractUntemplatedParameterisedSystem.cpp.
References GetSystemInformation().
Referenced by AbstractParameterisedSystem< VECTOR >::GetStateMessage().
Member Data Documentation
unsigned AbstractUntemplatedParameterisedSystem::mNumberOfStateVariables protected
The number of state variables in the system.
Definition at line 293 of file AbstractUntemplatedParameterisedSystem.hpp.
Referenced by AbstractCardiacCell::AbstractCardiacCell(), CombinedOdeSystem::CombinedOdeSystem(), AbstractRushLarsenCardiacCell::Compute(), AbstractRushLarsenCardiacCell::ComputeExceptVoltage(), AbstractParameterisedSystem< VECTOR >::GetAnyVariable(), AbstractParameterisedSystem< VECTOR >::GetInitialConditions(), GetNumberOfStateVariables(), AbstractParameterisedSystem< VECTOR >::GetStateVariable(), AbstractOdeSystem::load(), AbstractCvodeSystem::load(), AbstractOdeSystem::save(), AbstractCvodeSystem::save(), FakeBathCell::serialize(), AbstractParameterisedSystem< VECTOR >::SetAnyVariable(), AbstractParameterisedSystem< VECTOR >::SetDefaultInitialCondition(), AbstractParameterisedSystem< VECTOR >::SetDefaultInitialConditions(), AbstractParameterisedSystem< VECTOR >::SetStateVariable(), AbstractParameterisedSystem< VECTOR >::SetStateVariables(), and AbstractRushLarsenCardiacCell::SolveAndUpdateState().
boost::shared_ptr<AbstractOdeSystemInformation> AbstractUntemplatedParameterisedSystem::mpSystemInfo protected
Information about the concrete ODE system class.
Subclasses need to set this in their constructor to point to an instance of a suitable class. See for example the OdeSystemInformation class.
Definition at line 301 of file AbstractUntemplatedParameterisedSystem.hpp.
Referenced by Alarcon2004OxygenBasedCellCycleOdeSystem::Alarcon2004OxygenBasedCellCycleOdeSystem(), CML_noble_varghese_kohl_noble_1998_basic_with_sac::CML_noble_varghese_kohl_noble_1998_basic_with_sac(), CombinedOdeSystem::CombinedOdeSystem(), AbstractGeneralizedRushLarsenCardiacCell::Compute(), AbstractRushLarsenCardiacCell::Compute(), AbstractBackwardEulerCardiacCell< SIZE >::Compute(), AbstractBackwardEulerCardiacCell< 0u >::Compute(), CorriasBuistICCModified::CorriasBuistICCModified(), CorriasBuistSMCModified::CorriasBuistSMCModified(), DeltaNotchOdeSystem::DeltaNotchOdeSystem(), FakeBathCell::FakeBathCell(), FitzHughNagumo1961OdeSystem::FitzHughNagumo1961OdeSystem(), AbstractParameterisedSystem< VECTOR >::GetInitialConditions(), GetSystemInformation(), Goldbeter1991OdeSystem::Goldbeter1991OdeSystem(), Kerchoffs2003ContractionModel::Kerchoffs2003ContractionModel(), Mirams2010WntOdeSystem::Mirams2010WntOdeSystem(), Nash2004ContractionModel::Nash2004ContractionModel(), NhsContractionModel::NhsContractionModel(), OdeSystemForCoupledHeatEquation::OdeSystemForCoupledHeatEquation(), OdeSystemForCoupledHeatEquationWithSource::OdeSystemForCoupledHeatEquationWithSource(), AbstractParameterisedSystem< VECTOR >::SetDefaultInitialCondition(), AbstractParameterisedSystem< VECTOR >::SetDefaultInitialConditions(), AbstractCvodeSystem::Solve(), TysonNovak2001OdeSystem::TysonNovak2001OdeSystem(), VanLeeuwen2009WntSwatCellCycleOdeSystem::VanLeeuwen2009WntSwatCellCycleOdeSystem(), and WntCellCycleOdeSystem::WntCellCycleOdeSystem().
The documentation for this class was generated from the following files:
ode/src/common/AbstractUntemplatedParameterisedSystem.hpp
ode/src/common/AbstractUntemplatedParameterisedSystem.cpp