Chaste: AbstractStimulusFunction Class Reference
AbstractStimulusFunction Class Reference abstract
#include <AbstractStimulusFunction.hpp>
Public Member Functions
virtual double GetStimulus (double time)=0
virtual ~AbstractStimulusFunction ()
virtual void Clear ()
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Friends
class boost::serialization::access
Detailed Description
Represents an abstract stimulus function. Sub-classes will implement the GetStimulus() function to represent the various type of stimuli to the cardiac cell.
Definition at line 52 of file AbstractStimulusFunction.hpp.
Constructor & Destructor Documentation
AbstractStimulusFunction::~AbstractStimulusFunction () virtual
Destructor.
Definition at line 41 of file AbstractStimulusFunction.cpp.
Referenced by serialize().
Member Function Documentation
void AbstractStimulusFunction::Clear () virtual
Clear is used to managed memory in subclasses where the destructor may or may not need to clean up.
Reimplemented in MultiStimulus.
Definition at line 46 of file AbstractStimulusFunction.cpp.
References NEVER_REACHED.
Referenced by serialize().
virtual double AbstractStimulusFunction::GetStimulus (double time) pure virtual
Returns
the stimulus at a given time.
Parameters
time time at which to return the stimulus
Implemented in PurkinjeVentricularJunctionStimulus, S1S2Stimulus, SimpleStimulus, RegularStimulus, MultiStimulus, RegularStimulusZeroNetCharge, and ZeroStimulus.
Referenced by serialize().
template<class Archive > void AbstractStimulusFunction::serialize (Archive & archive, const unsigned int version) inline private
Archive the member variables.
Parameters
archive
version
Definition at line 63 of file AbstractStimulusFunction.hpp.
References CLASS_IS_ABSTRACT, Clear(), GetStimulus(), and ~AbstractStimulusFunction().
Friends And Related Function Documentation
friend class boost::serialization::access friend
Needed for serialization.
Definition at line 55 of file AbstractStimulusFunction.hpp.
The documentation for this class was generated from the following files:
heart/src/stimulus/AbstractStimulusFunction.hpp
heart/src/stimulus/AbstractStimulusFunction.cpp