Chaste: CellPopulationAreaWriter< ELEMENT_DIM, SPACE_DIM > Class Template Reference
CellPopulationAreaWriter< ELEMENT_DIM, SPACE_DIM > Class Template Reference
#include <CellPopulationAreaWriter.hpp>
Public Member Functions
CellPopulationAreaWriter ()
virtual void Visit (MeshBasedCellPopulation< ELEMENT_DIM, SPACE_DIM > *pCellPopulation)
virtual void Visit (CaBasedCellPopulation< SPACE_DIM > *pCellPopulation)
virtual void Visit (NodeBasedCellPopulation< SPACE_DIM > *pCellPopulation)
virtual void Visit (PottsBasedCellPopulation< SPACE_DIM > *pCellPopulation)
virtual void Visit (VertexBasedCellPopulation< SPACE_DIM > *pCellPopulation)
Public Member Functions inherited from AbstractCellPopulationWriter< ELEMENT_DIM, SPACE_DIM >
AbstractCellPopulationWriter (const std::string &rFileName)
virtual void WriteHeader (AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM > *pCellPopulation)
Public Member Functions inherited from AbstractCellBasedWriter< ELEMENT_DIM, SPACE_DIM >
AbstractCellBasedWriter (const std::string &rFileName)
virtual ~AbstractCellBasedWriter ()
void CloseFile ()
virtual void OpenOutputFile (OutputFileHandler &rOutputFileHandler)
void OpenOutputFileForAppend (OutputFileHandler &rOutputFileHandler)
virtual void WriteTimeStamp ()
virtual void WriteNewline ()
void SetFileName (std::string fileName)
std::string GetFileName ()
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Friends
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from AbstractCellBasedWriter< ELEMENT_DIM, SPACE_DIM >
std::string mFileName
out_stream mpOutStream
Detailed Description
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM>
class CellPopulationAreaWriter< ELEMENT_DIM, SPACE_DIM >
A class written using the visitor pattern for writing cell population volume data to file. Used by MeshBasedCellPopulation.
The output file is called cellpopulationareas.dat by default.
Definition at line 50 of file CellPopulationAreaWriter.hpp.
Constructor & Destructor Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> CellPopulationAreaWriter< ELEMENT_DIM, SPACE_DIM >::CellPopulationAreaWriter ()
Default constructor.
Definition at line 46 of file CellPopulationAreaWriter.cpp.
Referenced by CellPopulationAreaWriter< ELEMENT_DIM, SPACE_DIM >::serialize().
Member Function Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> template<class Archive > void CellPopulationAreaWriter< ELEMENT_DIM, SPACE_DIM >::serialize (Archive & archive, const unsigned int version) inline private
Serialize the object and its member variables.
Parameters
archive the archive
version the current version of this class
Definition at line 62 of file CellPopulationAreaWriter.hpp.
References CellPopulationAreaWriter< ELEMENT_DIM, SPACE_DIM >::CellPopulationAreaWriter(), EXPORT_TEMPLATE_CLASS_ALL_DIMS, and CellPopulationAreaWriter< ELEMENT_DIM, SPACE_DIM >::Visit().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void CellPopulationAreaWriter< ELEMENT_DIM, SPACE_DIM >::Visit (MeshBasedCellPopulation< ELEMENT_DIM, SPACE_DIM > * pCellPopulation) virtual
Visit the population and write the areas (or volume, in 3D) occupied by the entire cell population and by apoptotic cells. Any ghost nodes present in the population are neglected from these areas.
Outputs a line of space-separated values of the form: [total area] [apoptotic area]
This line is appended to the output written by AbstractCellBasedWriter, which is a single value [present simulation time], followed by a tab.
Parameters
pCellPopulation a pointer to the MeshBasedCellPopulation to visit.
Implements AbstractCellPopulationWriter< ELEMENT_DIM, SPACE_DIM >.
Definition at line 52 of file CellPopulationAreaWriter.cpp.
References AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::GetCellUsingLocationIndex(), VertexMesh< ELEMENT_DIM, SPACE_DIM >::GetDelaunayNodeIndexCorrespondingToVoronoiElementIndex(), VertexMesh< ELEMENT_DIM, SPACE_DIM >::GetElementIteratorBegin(), VertexMesh< ELEMENT_DIM, SPACE_DIM >::GetElementIteratorEnd(), TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::GetVolume(), VertexMesh< ELEMENT_DIM, SPACE_DIM >::GetVolumeOfElement(), MeshBasedCellPopulation< ELEMENT_DIM, SPACE_DIM >::GetVoronoiTessellation(), AbstractCentreBasedCellPopulation< ELEMENT_DIM, SPACE_DIM >::IsGhostNode(), AbstractCellBasedWriter< ELEMENT_DIM, SPACE_DIM >::mpOutStream, and MeshBasedCellPopulation< ELEMENT_DIM, SPACE_DIM >::rGetMesh().
Referenced by CellPopulationAreaWriter< ELEMENT_DIM, SPACE_DIM >::serialize().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void CellPopulationAreaWriter< ELEMENT_DIM, SPACE_DIM >::Visit (CaBasedCellPopulation< SPACE_DIM > * pCellPopulation) virtual
Visit the population and write the areas (or volume, in 3D) occupied by the entire cell population and by apoptotic cells. Any ghost nodes present in the population are neglected from these areas.
Outputs a line of space-separated values of the form: [total area] [apoptotic area]
This line is appended to the output written by AbstractCellBasedWriter, which is a single value [present simulation time], followed by a tab.
Parameters
pCellPopulation a pointer to the CaBasedCellPopulation to visit.
Implements AbstractCellPopulationWriter< ELEMENT_DIM, SPACE_DIM >.
Definition at line 94 of file CellPopulationAreaWriter.cpp.
References EXCEPTION.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void CellPopulationAreaWriter< ELEMENT_DIM, SPACE_DIM >::Visit (NodeBasedCellPopulation< SPACE_DIM > * pCellPopulation) virtual
Visit the population and write the areas (or volume, in 3D) occupied by the entire cell population and by apoptotic cells. Any ghost nodes present in the population are neglected from these areas.
Outputs a line of space-separated values of the form: [total area] [apoptotic area]
This line is appended to the output written by AbstractCellBasedWriter, which is a single value [present simulation time], followed by a tab.
Parameters
pCellPopulation a pointer to the NodeBasedCellPopulation to visit.
Implements AbstractCellPopulationWriter< ELEMENT_DIM, SPACE_DIM >.
Definition at line 100 of file CellPopulationAreaWriter.cpp.
References EXCEPTION.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void CellPopulationAreaWriter< ELEMENT_DIM, SPACE_DIM >::Visit (PottsBasedCellPopulation< SPACE_DIM > * pCellPopulation) virtual
Visit the population and write the areas (or volume, in 3D) occupied by the entire cell population and by apoptotic cells. Any ghost nodes present in the population are neglected from these areas.
Outputs a line of space-separated values of the form: [total area] [apoptotic area]
This line is appended to the output written by AbstractCellBasedWriter, which is a single value [present simulation time], followed by a tab.
Parameters
pCellPopulation a pointer to the PottsBasedCellPopulation to visit.
Implements AbstractCellPopulationWriter< ELEMENT_DIM, SPACE_DIM >.
Definition at line 106 of file CellPopulationAreaWriter.cpp.
References EXCEPTION.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void CellPopulationAreaWriter< ELEMENT_DIM, SPACE_DIM >::Visit (VertexBasedCellPopulation< SPACE_DIM > * pCellPopulation) virtual
Visit the population and write the areas (or volume, in 3D) occupied by the entire cell population and by apoptotic cells. Any ghost nodes present in the population are neglected from these areas.
Outputs a line of space-separated values of the form: [total area] [apoptotic area]
This line is appended to the output written by AbstractCellBasedWriter, which is a single value [present simulation time], followed by a tab.
Parameters
pCellPopulation a pointer to the VertexBasedCellPopulation to visit.
Implements AbstractCellPopulationWriter< ELEMENT_DIM, SPACE_DIM >.
Definition at line 112 of file CellPopulationAreaWriter.cpp.
References EXCEPTION, and EXPORT_TEMPLATE_CLASS_ALL_DIMS.
Friends And Related Function Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> friend class boost::serialization::access friend
Needed for serialization.
Definition at line 54 of file CellPopulationAreaWriter.hpp.
The documentation for this class was generated from the following files:
cell_based/src/writers/population_writers/CellPopulationAreaWriter.hpp
cell_based/src/writers/population_writers/CellPopulationAreaWriter.cpp