Chaste: NoCellCycleModel Class Reference
NoCellCycleModel Class Reference
#include <NoCellCycleModel.hpp>
Public Member Functions
NoCellCycleModel ()
bool ReadyToDivide ()
AbstractCellCycleModel * CreateCellCycleModel ()
double GetAverageTransitCellCycleTime ()
double GetAverageStemCellCycleTime ()
void OutputCellCycleModelParameters (out_stream &rParamsFile)
Public Member Functions inherited from AbstractCellCycleModel
AbstractCellCycleModel ()
virtual ~AbstractCellCycleModel ()
void SetCell (CellPtr pCell)
virtual void Initialise ()
virtual void InitialiseDaughterCell ()
CellPtr GetCell ()
virtual void SetBirthTime (double birthTime)
void SetDimension (unsigned dimension)
unsigned GetDimension () const
double GetBirthTime () const
double GetAge ()
virtual void ResetForDivision ()
virtual bool CanCellTerminallyDifferentiate ()
void OutputCellCycleModelInfo (out_stream &rParamsFile)
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Friends
class TestSimpleCellCycleModels
class boost::serialization::access
Additional Inherited Members
Protected Member Functions inherited from AbstractCellCycleModel
AbstractCellCycleModel (const AbstractCellCycleModel &rModel)
Protected Attributes inherited from AbstractCellCycleModel
CellPtr mpCell
double mBirthTime
bool mReadyToDivide
unsigned mDimension
Detailed Description
A 'dummy' cell-cycle model class that can be used in simulations featuring no cell proliferation.
Definition at line 45 of file NoCellCycleModel.hpp.
Constructor & Destructor Documentation
NoCellCycleModel::NoCellCycleModel ()
Default constructor.
Definition at line 38 of file NoCellCycleModel.cpp.
Referenced by serialize().
Member Function Documentation
AbstractCellCycleModel * NoCellCycleModel::CreateCellCycleModel () virtual
Overridden builder method to create new copies of this cell-cycle model.
Returns
new cell-cycle model
Implements AbstractCellCycleModel.
Definition at line 49 of file NoCellCycleModel.cpp.
References NEVER_REACHED.
Referenced by serialize().
double NoCellCycleModel::GetAverageStemCellCycleTime () virtual
Overridden GetAverageStemCellCycleTime() method.
Returns
DBL_MAX
Implements AbstractCellCycleModel.
Definition at line 61 of file NoCellCycleModel.cpp.
Referenced by serialize().
double NoCellCycleModel::GetAverageTransitCellCycleTime () virtual
Overridden GetAverageTransitCellCycleTime() method.
Returns
DBL_MAX
Implements AbstractCellCycleModel.
Definition at line 56 of file NoCellCycleModel.cpp.
Referenced by serialize().
void NoCellCycleModel::OutputCellCycleModelParameters (out_stream & rParamsFile) virtual
Overridden OutputCellCycleModelParameters() method.
Parameters
rParamsFile the file stream to which the parameters are output
Implements AbstractCellCycleModel.
Definition at line 66 of file NoCellCycleModel.cpp.
References CHASTE_CLASS_EXPORT, and AbstractCellCycleModel::OutputCellCycleModelParameters().
Referenced by serialize().
bool NoCellCycleModel::ReadyToDivide () virtual
Overridden ReadyToDivide() method.
Returns
false
Implements AbstractCellCycleModel.
Definition at line 43 of file NoCellCycleModel.cpp.
Referenced by serialize().
template<class Archive > void NoCellCycleModel::serialize (Archive & archive, const unsigned int version) inline private
Archive the cell-cycle model.
Parameters
archive the archive
version the current version of this class
Definition at line 60 of file NoCellCycleModel.hpp.
References CHASTE_CLASS_EXPORT, CreateCellCycleModel(), GetAverageStemCellCycleTime(), GetAverageTransitCellCycleTime(), NoCellCycleModel(), OutputCellCycleModelParameters(), and ReadyToDivide().
Friends And Related Function Documentation
friend class boost::serialization::access friend
Needed for serialization.
Definition at line 52 of file NoCellCycleModel.hpp.
The documentation for this class was generated from the following files:
cell_based/src/cell/cycle/NoCellCycleModel.hpp
cell_based/src/cell/cycle/NoCellCycleModel.cpp