Chaste: ChemotacticForce< DIM > Class Template Reference
ChemotacticForce< DIM > Class Template Reference
#include <ChemotacticForce.hpp>
Public Member Functions
ChemotacticForce ()
~ChemotacticForce ()
void AddForceContribution (AbstractCellPopulation< DIM > &rCellPopulation)
void OutputForceParameters (out_stream &rParamsFile)
Public Member Functions inherited from AbstractForce< DIM >
AbstractForce ()
virtual ~AbstractForce ()
virtual void AddForceContribution (AbstractCellPopulation< ELEMENT_DIM, ELEMENT_DIM > &rCellPopulation)=0
void OutputForceInfo (out_stream &rParamsFile)
virtual void WriteDataToVisualizerSetupFile (out_stream &pVizSetupFile)
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Private Member Functions
double GetChemotacticForceMagnitude (const double concentration, const double concentrationGradientMagnitude)
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Friends
class TestForces
class boost::serialization::access
Detailed Description
template<unsigned DIM>
class ChemotacticForce< DIM >
A chemotactic force class.
Definition at line 48 of file ChemotacticForce.hpp.
Constructor & Destructor Documentation
template<unsigned DIM> ChemotacticForce< DIM >::ChemotacticForce ()
Constructor.
Definition at line 42 of file ChemotacticForce.cpp.
Referenced by ChemotacticForce< DIM >::serialize().
template<unsigned DIM> ChemotacticForce< DIM >::~ChemotacticForce ()
Destructor.
Definition at line 48 of file ChemotacticForce.cpp.
Referenced by ChemotacticForce< DIM >::serialize().
Member Function Documentation
template<unsigned DIM> void ChemotacticForce< DIM >::AddForceContribution (AbstractCellPopulation< DIM > & rCellPopulation)
Overridden AddForceContribution() method.
Parameters
rCellPopulation reference to the cell population
Fc = chi(C,|gradC|) gradC/|gradC| (if |gradC|>0, else Fc = 0)
Definition at line 60 of file ChemotacticForce.cpp.
References AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::Begin(), AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::End(), ChemotacticForce< DIM >::GetChemotacticForceMagnitude(), AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::GetLocationIndexUsingCell(), AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::GetNode(), CellwiseDataGradient< DIM >::rGetGradient(), and CellwiseDataGradient< DIM >::SetupGradients().
Referenced by ChemotacticForce< DIM >::serialize().
template<unsigned DIM> double ChemotacticForce< DIM >::GetChemotacticForceMagnitude (const double concentration, const double concentrationGradientMagnitude) private
Returns
the magnitude of the chemotactic force.
Parameters
concentration the local nutrient concentration
concentrationGradientMagnitude the magnitude of the local nutrient concentration gradient
Definition at line 53 of file ChemotacticForce.cpp.
Referenced by ChemotacticForce< DIM >::AddForceContribution().
template<unsigned DIM> void ChemotacticForce< DIM >::OutputForceParameters (out_stream & rParamsFile) virtual
Overridden OutputForceParameters() method.
Parameters
rParamsFile the file stream to which the parameters are output
Implements AbstractForce< DIM >.
Definition at line 92 of file ChemotacticForce.cpp.
References EXPORT_TEMPLATE_CLASS_SAME_DIMS, and AbstractForce< ELEMENT_DIM, SPACE_DIM >::OutputForceParameters().
Referenced by ChemotacticForce< DIM >::serialize().
template<unsigned DIM> template<class Archive > void ChemotacticForce< DIM >::serialize (Archive & archive, const unsigned int version) inline private
Boost Serialization method for archiving/checkpointing. Archives the object and its member variables.
Parameters
archive The boost archive.
version The current version of this class.
Definition at line 71 of file ChemotacticForce.hpp.
References ChemotacticForce< DIM >::AddForceContribution(), ChemotacticForce< DIM >::ChemotacticForce(), EXPORT_TEMPLATE_CLASS_SAME_DIMS, ChemotacticForce< DIM >::OutputForceParameters(), and ChemotacticForce< DIM >::~ChemotacticForce().
The documentation for this class was generated from the following files:
cell_based/src/population/forces/ChemotacticForce.hpp
cell_based/src/population/forces/ChemotacticForce.cpp