Chaste: global/src/ChasteBuildRoot.hpp File Reference
ChasteBuildRoot.hpp File Reference
#include <string>
Functions
const char * ChasteBuildRootDir ()
const char * ChasteSourceRootDir ()
std::string ChasteComponentBuildDir (const std::string &rComponent)
std::string ChasteBuildDirName ()
std::string ChasteBuildType ()
Detailed Description
A collection of functions providing information about the filesystem layout of this Chaste source tree.
Definition in file ChasteBuildRoot.hpp.
Function Documentation
ChasteBuildDirName()
std::string ChasteBuildDirName ()
Returns
the name of the folder within the 'build' dir of a component that contains the compiled files.
Referenced by CellMLToSharedLibraryConverter::ConvertCellmlToSo().
ChasteBuildRootDir()
const char * ChasteBuildRootDir ()
Returns
the path to the root directory of the Chaste build tree. Will always give you the absolute path with a trailing slash.
Referenced by FileFinder::SetPath().
ChasteBuildType()
std::string ChasteBuildType ()
Returns
the build type string used in building Chaste.
Referenced by CellMLToSharedLibraryConverter::ConvertCellmlToSo().
ChasteComponentBuildDir()
std::string ChasteComponentBuildDir (const std::string & rComponent)
Returns
the folder in which compiled files are placed for the given Chaste component. Will always give you the absolute path with a trailing slash.
Parameters
rComponent e.g. global, heart, pde, ...
ChasteSourceRootDir()
const char * ChasteSourceRootDir ()
Returns
the path to the root directory of the Chaste source tree. Will always give you the absolute path with a trailing slash.
Referenced by PetscSetupUtils::CommonSetup(), Exception::SetMessage(), and FileFinder::SetPath().