Chaste: ImmersedBoundaryLinearDifferentialAdhesionForce< DIM > Class Template Reference
ImmersedBoundaryLinearDifferentialAdhesionForce< DIM > Class Template Reference
#include <ImmersedBoundaryLinearDifferentialAdhesionForce.hpp>
Public Member Functions
ImmersedBoundaryLinearDifferentialAdhesionForce ()
virtual ~ImmersedBoundaryLinearDifferentialAdhesionForce ()=default
void AddImmersedBoundaryForceContribution (std::vector< std::pair< Node< DIM > *, Node< DIM > * > > &rNodePairs, ImmersedBoundaryCellPopulation< DIM > &rCellPopulation)
void OutputImmersedBoundaryForceParameters (out_stream &rParamsFile)
double GetLabelledCellToLabelledCellSpringConst () const
void SetLabelledCellToLabelledCellSpringConst (double labelledCellToLabelledCellSpringConst)
double GetLabelledCellToCellSpringConst () const
void SetLabelledCellToCellSpringConst (double labelledCellToCellSpringConst)
double GetCellToCellSpringConst () const
void SetCellToCellSpringConst (double cellToCellSpringConst)
double GetRestLength () const
void SetRestLength (double restLength)
Public Member Functions inherited from AbstractImmersedBoundaryForce< DIM >
AbstractImmersedBoundaryForce ()
virtual ~AbstractImmersedBoundaryForce ()
bool GetAdditiveNormalNoise () const
void SetAdditiveNormalNoise (bool additiveNormalNoise)
double GetNormalNoiseMean () const
void SetNormalNoiseMean (double normalNoiseMean)
double GetNormalNoiseStdDev () const
void SetNormalNoiseStdDev (double normalNoiseStdDev)
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Private Attributes
double mLabelledCellToLabelledCellSpringConst
double mLabelledCellToCellSpringConst
double mCellToCellSpringConst
double mRestLength
Friends
class boost::serialization::access
Additional Inherited Members
Protected Member Functions inherited from AbstractImmersedBoundaryForce< DIM >
void AddNormalNoiseToNodes (ImmersedBoundaryCellPopulation< DIM > &rCellPopulation)
Protected Attributes inherited from AbstractImmersedBoundaryForce< DIM >
bool mAdditiveNormalNoise
double mNormalNoiseMean
double mNormalNoiseStdDev
Detailed Description
template<unsigned DIM>
class ImmersedBoundaryLinearDifferentialAdhesionForce< DIM >
A force class for use in immersed boundary simulations. This force implements elastic links between nodes in adjacent immersed boundaries.
Definition at line 54 of file ImmersedBoundaryLinearDifferentialAdhesionForce.hpp.
Constructor & Destructor Documentation
ImmersedBoundaryLinearDifferentialAdhesionForce()
template<unsigned DIM> ImmersedBoundaryLinearDifferentialAdhesionForce< DIM >::ImmersedBoundaryLinearDifferentialAdhesionForce ()
Constructor.
Definition at line 41 of file ImmersedBoundaryLinearDifferentialAdhesionForce.cpp.
~ImmersedBoundaryLinearDifferentialAdhesionForce()
template<unsigned DIM> virtual ImmersedBoundaryLinearDifferentialAdhesionForce< DIM >::~ImmersedBoundaryLinearDifferentialAdhesionForce () virtual default
Destructor.
Member Function Documentation
AddImmersedBoundaryForceContribution()
template<unsigned DIM> void ImmersedBoundaryLinearDifferentialAdhesionForce< DIM >::AddImmersedBoundaryForceContribution (std::vector< std::pair< Node< DIM > *, Node< DIM > * > > & rNodePairs, ImmersedBoundaryCellPopulation< DIM > & rCellPopulation) virtual
Overridden AddImmersedBoundaryForceContribution() method. Calculates the force on each node in the immersed boundary cell population as a result of cell-cell interactions.
Parameters
rNodePairs reference to a vector set of node pairs between which to contribute the force
rCellPopulation reference to the cell population
Implements AbstractImmersedBoundaryForce< DIM >.
Definition at line 51 of file ImmersedBoundaryLinearDifferentialAdhesionForce.cpp.
References Node< SPACE_DIM >::AddAppliedForceContribution(), Node< SPACE_DIM >::ContainingElementsBegin(), EXCEPTION, ImmersedBoundaryMesh< ELEMENT_DIM, SPACE_DIM >::GetAverageNodeSpacingOfElement(), AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::GetCellUsingLocationIndex(), ImmersedBoundaryCellPopulation< DIM >::GetInteractionDistance(), ImmersedBoundaryCellPopulation< DIM >::GetIntrinsicSpacing(), ImmersedBoundaryMesh< ELEMENT_DIM, SPACE_DIM >::GetNumLaminas(), ImmersedBoundaryMesh< ELEMENT_DIM, SPACE_DIM >::GetVectorFromAtoB(), ImmersedBoundaryMesh< ELEMENT_DIM, SPACE_DIM >::NodesInDifferentElementOrLamina(), Node< SPACE_DIM >::rGetLocation(), and ImmersedBoundaryCellPopulation< DIM >::rGetMesh().
GetCellToCellSpringConst()
template<unsigned int DIM> double ImmersedBoundaryLinearDifferentialAdhesionForce< DIM >::GetCellToCellSpringConst () const
Returns
mCellToCellSpringConst
Definition at line 175 of file ImmersedBoundaryLinearDifferentialAdhesionForce.cpp.
GetLabelledCellToCellSpringConst()
template<unsigned int DIM> double ImmersedBoundaryLinearDifferentialAdhesionForce< DIM >::GetLabelledCellToCellSpringConst () const
Returns
mLabelledCellToCellSpringConst
Definition at line 162 of file ImmersedBoundaryLinearDifferentialAdhesionForce.cpp.
GetLabelledCellToLabelledCellSpringConst()
template<unsigned int DIM> double ImmersedBoundaryLinearDifferentialAdhesionForce< DIM >::GetLabelledCellToLabelledCellSpringConst () const
Returns
mLabelledCellToLabelledCellSpringConst
Definition at line 149 of file ImmersedBoundaryLinearDifferentialAdhesionForce.cpp.
GetRestLength()
template<unsigned DIM> double ImmersedBoundaryLinearDifferentialAdhesionForce< DIM >::GetRestLength () const
Returns
mRestLength
Definition at line 136 of file ImmersedBoundaryLinearDifferentialAdhesionForce.cpp.
OutputImmersedBoundaryForceParameters()
template<unsigned DIM> void ImmersedBoundaryLinearDifferentialAdhesionForce< DIM >::OutputImmersedBoundaryForceParameters (out_stream & rParamsFile) virtual
Overridden OutputImmersedBoundaryForceParameters() method.
Parameters
rParamsFile the file stream to which the parameters are output
Implements AbstractImmersedBoundaryForce< DIM >.
Definition at line 123 of file ImmersedBoundaryLinearDifferentialAdhesionForce.cpp.
References AbstractImmersedBoundaryForce< DIM >::OutputImmersedBoundaryForceParameters().
serialize()
template<unsigned DIM> template<class Archive > void ImmersedBoundaryLinearDifferentialAdhesionForce< DIM >::serialize (Archive & archive, const unsigned int version) inline private
Boost Serialization method for archiving/checkpointing. Archives the object and its member variables.
Parameters
archive The boost archive.
version The current version of this class.
Definition at line 67 of file ImmersedBoundaryLinearDifferentialAdhesionForce.hpp.
References ImmersedBoundaryLinearDifferentialAdhesionForce< DIM >::mCellToCellSpringConst, ImmersedBoundaryLinearDifferentialAdhesionForce< DIM >::mLabelledCellToCellSpringConst, ImmersedBoundaryLinearDifferentialAdhesionForce< DIM >::mLabelledCellToLabelledCellSpringConst, and ImmersedBoundaryLinearDifferentialAdhesionForce< DIM >::mRestLength.
SetCellToCellSpringConst()
template<unsigned int DIM> void ImmersedBoundaryLinearDifferentialAdhesionForce< DIM >::SetCellToCellSpringConst (double cellToCellSpringConst)
Set mCellToCellSpringConst.
Parameters
cellToCellSpringConst the new value of mCellToCellSpringConst
Definition at line 181 of file ImmersedBoundaryLinearDifferentialAdhesionForce.cpp.
SetLabelledCellToCellSpringConst()
template<unsigned int DIM> void ImmersedBoundaryLinearDifferentialAdhesionForce< DIM >::SetLabelledCellToCellSpringConst (double labelledCellToCellSpringConst)
Set mLabelledCellToCellSpringConst.
Parameters
labelledCellToCellSpringConst the new value of mLabelledCellToCellSpringConst
Definition at line 168 of file ImmersedBoundaryLinearDifferentialAdhesionForce.cpp.
SetLabelledCellToLabelledCellSpringConst()
template<unsigned int DIM> void ImmersedBoundaryLinearDifferentialAdhesionForce< DIM >::SetLabelledCellToLabelledCellSpringConst (double labelledCellToLabelledCellSpringConst)
Set mLabelledCellToLabelledCellSpringConst.
Parameters
labelledCellToLabelledCellSpringConst the new value of mLabelledCellToLabelledCellSpringConst
Definition at line 155 of file ImmersedBoundaryLinearDifferentialAdhesionForce.cpp.
SetRestLength()
template<unsigned DIM> void ImmersedBoundaryLinearDifferentialAdhesionForce< DIM >::SetRestLength (double restLength)
Set mRestLength.
Parameters
restLength the new value of mRestLength
Definition at line 142 of file ImmersedBoundaryLinearDifferentialAdhesionForce.cpp.
Friends And Related Symbol Documentation
boost::serialization::access
template<unsigned DIM> friend class boost::serialization::access friend
Definition at line 58 of file ImmersedBoundaryLinearDifferentialAdhesionForce.hpp.
Member Data Documentation
mCellToCellSpringConst
template<unsigned DIM> double ImmersedBoundaryLinearDifferentialAdhesionForce< DIM >::mCellToCellSpringConst private
The cell-cell spring constant between nodes in two regular cells. Initialised to 1e3 in constructor.
Definition at line 92 of file ImmersedBoundaryLinearDifferentialAdhesionForce.hpp.
Referenced by ImmersedBoundaryLinearDifferentialAdhesionForce< DIM >::serialize().
mLabelledCellToCellSpringConst
template<unsigned DIM> double ImmersedBoundaryLinearDifferentialAdhesionForce< DIM >::mLabelledCellToCellSpringConst private
The cell-cell spring constant between nodes in a labelled cell - regular cell pair. Initialised to 1e3 in constructor.
Definition at line 86 of file ImmersedBoundaryLinearDifferentialAdhesionForce.hpp.
Referenced by ImmersedBoundaryLinearDifferentialAdhesionForce< DIM >::serialize().
mLabelledCellToLabelledCellSpringConst
template<unsigned DIM> double ImmersedBoundaryLinearDifferentialAdhesionForce< DIM >::mLabelledCellToLabelledCellSpringConst private
The cell-cell spring constant between nodes in two labelled cells. Initialised to 1e3 in constructor.
Definition at line 80 of file ImmersedBoundaryLinearDifferentialAdhesionForce.hpp.
Referenced by ImmersedBoundaryLinearDifferentialAdhesionForce< DIM >::serialize().
mRestLength
template<unsigned DIM> double ImmersedBoundaryLinearDifferentialAdhesionForce< DIM >::mRestLength private
The basic rest length associated with interactions, as a fraction of cell population's interaction distance Initialised to 0.25 in constructor.
Definition at line 98 of file ImmersedBoundaryLinearDifferentialAdhesionForce.hpp.
Referenced by ImmersedBoundaryLinearDifferentialAdhesionForce< DIM >::serialize().
The documentation for this class was generated from the following files:
cell_based/src/population/forces/ImmersedBoundaryLinearDifferentialAdhesionForce.hpp
cell_based/src/population/forces/ImmersedBoundaryLinearDifferentialAdhesionForce.cpp