Chaste: StochasticOxygenBasedCellCycleModel Class Reference
StochasticOxygenBasedCellCycleModel Class Reference
#include <StochasticOxygenBasedCellCycleModel.hpp>
Public Member Functions
StochasticOxygenBasedCellCycleModel ()
void InitialiseDaughterCell ()
void Initialise ()
void ResetForDivision ()
double GetG2Duration () const
AbstractCellCycleModel * CreateCellCycleModel ()
virtual void OutputCellCycleModelParameters (out_stream &rParamsFile)
Public Member Functions inherited from SimpleOxygenBasedCellCycleModel
SimpleOxygenBasedCellCycleModel ()
void UpdateCellCyclePhase ()
void UpdateHypoxicDuration ()
double GetCurrentHypoxicDuration () const
double GetCurrentHypoxiaOnsetTime () const
double GetHypoxicConcentration () const
void SetHypoxicConcentration (double hypoxicConcentration)
double GetQuiescentConcentration () const
void SetQuiescentConcentration (double quiescentConcentration)
double GetCriticalHypoxicDuration () const
void SetCriticalHypoxicDuration (double criticalHypoxicDuration)
void SetCurrentHypoxiaOnsetTime (double currentHypoxiaOnsetTime)
Public Member Functions inherited from AbstractSimplePhaseBasedCellCycleModel
AbstractSimplePhaseBasedCellCycleModel ()
virtual ~AbstractSimplePhaseBasedCellCycleModel ()
Public Member Functions inherited from AbstractPhaseBasedCellCycleModel
AbstractPhaseBasedCellCycleModel ()
virtual ~AbstractPhaseBasedCellCycleModel ()
virtual bool ReadyToDivide ()
CellCyclePhase GetCurrentCellCyclePhase () const
virtual double GetG1Duration () const
double GetStemCellG1Duration () const
double GetTransitCellG1Duration () const
double GetSG2MDuration () const
virtual double GetSDuration () const
virtual double GetMDuration () const
virtual void SetStemCellG1Duration (double stemCellG1Duration)
virtual void SetTransitCellG1Duration (double transitCellG1Duration)
void SetSDuration (double sDuration)
void SetG2Duration (double g2Duration)
void SetMDuration (double mDuration)
virtual double GetAverageTransitCellCycleTime ()
virtual double GetAverageStemCellCycleTime ()
double GetMinimumGapDuration () const
void SetMinimumGapDuration (double minimumGapDuration)
Public Member Functions inherited from AbstractCellCycleModel
AbstractCellCycleModel ()
virtual ~AbstractCellCycleModel ()
void SetCell (CellPtr pCell)
CellPtr GetCell ()
virtual void SetBirthTime (double birthTime)
void SetDimension (unsigned dimension)
unsigned GetDimension () const
double GetBirthTime () const
double GetAge ()
virtual bool CanCellTerminallyDifferentiate ()
void OutputCellCycleModelInfo (out_stream &rParamsFile)
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Protected Member Functions
StochasticOxygenBasedCellCycleModel (const StochasticOxygenBasedCellCycleModel &rModel)
Protected Member Functions inherited from SimpleOxygenBasedCellCycleModel
SimpleOxygenBasedCellCycleModel (const SimpleOxygenBasedCellCycleModel &rModel)
Protected Member Functions inherited from AbstractSimplePhaseBasedCellCycleModel
virtual void SetG1Duration ()
AbstractSimplePhaseBasedCellCycleModel (const AbstractSimplePhaseBasedCellCycleModel &rModel)
Protected Member Functions inherited from AbstractPhaseBasedCellCycleModel
AbstractPhaseBasedCellCycleModel (const AbstractPhaseBasedCellCycleModel &rModel)
Protected Member Functions inherited from AbstractCellCycleModel
AbstractCellCycleModel (const AbstractCellCycleModel &rModel)
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
void GenerateStochasticG2Duration ()
Private Attributes
double mStochasticG2Duration
Friends
class TestSimpleCellCycleModels
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from SimpleOxygenBasedCellCycleModel
double mCurrentHypoxicDuration
double mCurrentHypoxiaOnsetTime
double mHypoxicConcentration
double mQuiescentConcentration
double mCriticalHypoxicDuration
Protected Attributes inherited from AbstractPhaseBasedCellCycleModel
CellCyclePhase mCurrentCellCyclePhase
double mG1Duration
double mMinimumGapDuration
double mStemCellG1Duration
double mTransitCellG1Duration
double mSDuration
double mG2Duration
double mMDuration
Protected Attributes inherited from AbstractCellCycleModel
CellPtr mpCell
double mBirthTime
bool mReadyToDivide
unsigned mDimension
Detailed Description
Stochastic oxygen-based cell-cycle model.
A simple oxygen-dependent cell-cycle model that inherits from SimpleOxygenBasedCellCycleModel and in addition spends a random duration in G2 phase.
Definition at line 49 of file StochasticOxygenBasedCellCycleModel.hpp.
Constructor & Destructor Documentation
StochasticOxygenBasedCellCycleModel() [1/2]
StochasticOxygenBasedCellCycleModel::StochasticOxygenBasedCellCycleModel (const StochasticOxygenBasedCellCycleModel & rModel) protected
Protected copy-constructor for use by CreateCellCycleModel. The only way for external code to create a copy of a cell cycle model is by calling that method, to ensure that a model of the correct subclass is created. This copy-constructor helps subclasses to ensure that all member variables are correctly copied when this happens.
This method is called by child classes to set member variables for a daughter cell upon cell division. Note that the parent cell cycle model will have had ResetForDivision() called just before CreateCellCycleModel() is called, so performing an exact copy of the parent is suitable behaviour. Any daughter-cell-specific initialisation can be done in InitialiseDaughterCell().
Parameters
rModel the cell cycle model to copy.
Definition at line 43 of file StochasticOxygenBasedCellCycleModel.cpp.
StochasticOxygenBasedCellCycleModel() [2/2]
StochasticOxygenBasedCellCycleModel::StochasticOxygenBasedCellCycleModel ()
Constructor.
Definition at line 38 of file StochasticOxygenBasedCellCycleModel.cpp.
Referenced by CreateCellCycleModel().
Member Function Documentation
CreateCellCycleModel()
AbstractCellCycleModel * StochasticOxygenBasedCellCycleModel::CreateCellCycleModel () virtual
Overridden builder method to create new copies of this cell-cycle model.
Returns
new cell-cycle model
Reimplemented from SimpleOxygenBasedCellCycleModel.
Definition at line 106 of file StochasticOxygenBasedCellCycleModel.cpp.
References StochasticOxygenBasedCellCycleModel().
GenerateStochasticG2Duration()
void StochasticOxygenBasedCellCycleModel::GenerateStochasticG2Duration () private
Stochastically set the G2 duration. Called on cell creation at the start of a simulation, and for both parent and daughter cells at cell division.
Definition at line 67 of file StochasticOxygenBasedCellCycleModel.cpp.
References AbstractPhaseBasedCellCycleModel::GetG2Duration(), RandomNumberGenerator::Instance(), AbstractPhaseBasedCellCycleModel::mMinimumGapDuration, mStochasticG2Duration, and RandomNumberGenerator::NormalRandomDeviate().
Referenced by Initialise(), InitialiseDaughterCell(), and ResetForDivision().
GetG2Duration()
double StochasticOxygenBasedCellCycleModel::GetG2Duration () const virtual
Returns
mStochasticG2Duration.
Reimplemented from AbstractPhaseBasedCellCycleModel.
Definition at line 101 of file StochasticOxygenBasedCellCycleModel.cpp.
References mStochasticG2Duration.
Initialise()
void StochasticOxygenBasedCellCycleModel::Initialise () virtual
Initialise the cell-cycle model at the start of a simulation.
Reimplemented from AbstractSimplePhaseBasedCellCycleModel.
Definition at line 89 of file StochasticOxygenBasedCellCycleModel.cpp.
References GenerateStochasticG2Duration(), and AbstractSimplePhaseBasedCellCycleModel::Initialise().
InitialiseDaughterCell()
void StochasticOxygenBasedCellCycleModel::InitialiseDaughterCell () virtual
Overridden InitialiseDaughterCell() method.
Reimplemented from AbstractSimplePhaseBasedCellCycleModel.
Definition at line 83 of file StochasticOxygenBasedCellCycleModel.cpp.
References GenerateStochasticG2Duration(), and AbstractCellCycleModel::InitialiseDaughterCell().
OutputCellCycleModelParameters()
void StochasticOxygenBasedCellCycleModel::OutputCellCycleModelParameters (out_stream & rParamsFile) virtual
Overridden OutputCellCycleModelParameters() method.
Parameters
rParamsFile the file stream to which the parameters are output
Reimplemented from SimpleOxygenBasedCellCycleModel.
Definition at line 111 of file StochasticOxygenBasedCellCycleModel.cpp.
References SimpleOxygenBasedCellCycleModel::OutputCellCycleModelParameters().
ResetForDivision()
void StochasticOxygenBasedCellCycleModel::ResetForDivision () virtual
Overridden ResetForDivision() method.
Reimplemented from AbstractSimplePhaseBasedCellCycleModel.
Definition at line 95 of file StochasticOxygenBasedCellCycleModel.cpp.
References GenerateStochasticG2Duration(), and AbstractCellCycleModel::ResetForDivision().
serialize()
template<class Archive > void StochasticOxygenBasedCellCycleModel::serialize (Archive & archive, const unsigned int version) inline private
Boost Serialization method for archiving/checkpointing
Parameters
archive The boost archive.
version The current version of this class.
Definition at line 63 of file StochasticOxygenBasedCellCycleModel.hpp.
References SerializableSingleton< SINGLETON_CLASS >::GetSerializationWrapper(), RandomNumberGenerator::Instance(), and mStochasticG2Duration.
Friends And Related Symbol Documentation
boost::serialization::access
friend class boost::serialization::access friend
Definition at line 55 of file StochasticOxygenBasedCellCycleModel.hpp.
TestSimpleCellCycleModels
friend class TestSimpleCellCycleModels friend
Definition at line 51 of file StochasticOxygenBasedCellCycleModel.hpp.
Member Data Documentation
mStochasticG2Duration
double StochasticOxygenBasedCellCycleModel::mStochasticG2Duration private
The duration of the G2 phase, set stochastically.
Definition at line 77 of file StochasticOxygenBasedCellCycleModel.hpp.
Referenced by GenerateStochasticG2Duration(), GetG2Duration(), and serialize().
The documentation for this class was generated from the following files:
cell_based/src/cell/cycle/StochasticOxygenBasedCellCycleModel.hpp
cell_based/src/cell/cycle/StochasticOxygenBasedCellCycleModel.cpp