Chaste: AbstractCellBasedTestSuite Class Reference
AbstractCellBasedTestSuite Class Reference
#include <AbstractCellBasedTestSuite.hpp>
Protected Member Functions
void setUp ()
void tearDown ()
Detailed Description
This class provides setUp and tearDown methods that are common to many cell_based test suites. Such suites may inherit from this class to avoid having to redefine them.
Note that the subclasses of CxxTest::TestSuite need to have names that end with the characters "TestSuite", due to our hack of cxxtest (see r3168 and #593).
Definition at line 58 of file AbstractCellBasedTestSuite.hpp.
Member Function Documentation
setUp()
void AbstractCellBasedTestSuite::setUp () inline protected
Overridden setUp() method. Initialises singleton classes.
Definition at line 64 of file AbstractCellBasedTestSuite.hpp.
References SimulationTime::Instance(), RandomNumberGenerator::Instance(), RandomNumberGenerator::Reseed(), CellId::ResetMaxCellId(), and SimulationTime::SetStartTime().
Referenced by AbstractCellBasedWithTimingsTestSuite::setUp().
tearDown()
void AbstractCellBasedTestSuite::tearDown () inline protected
Overridden teardown() method. Clears up singleton classes.
Definition at line 76 of file AbstractCellBasedTestSuite.hpp.
References CellPropertyRegistry::Clear(), SimulationTime::Destroy(), RandomNumberGenerator::Destroy(), and CellPropertyRegistry::Instance().
Referenced by AbstractCellBasedWithTimingsTestSuite::tearDown().
The documentation for this class was generated from the following file:
cell_based/src/fortests/AbstractCellBasedTestSuite.hpp