Chaste: AbstractCryptStatistics Class Reference
AbstractCryptStatistics Class Reference
#include <AbstractCryptStatistics.hpp>
Public Member Functions
AbstractCryptStatistics (MeshBasedCellPopulation< 2 > &rCrypt)
virtual ~AbstractCryptStatistics ()
void LabelSPhaseCells ()
void LabelAllCellsAsHealthy ()
std::vector< bool > AreCryptSectionCellsLabelled (std::vector< CellPtr > &rCryptSection)
Protected Attributes
MeshBasedCellPopulation< 2 > & mrCrypt
Detailed Description
Abstract crypt statistics class.
Definition at line 44 of file AbstractCryptStatistics.hpp.
Constructor & Destructor Documentation
AbstractCryptStatistics()
AbstractCryptStatistics::AbstractCryptStatistics (MeshBasedCellPopulation< 2 > & rCrypt)
Constructor.
Parameters
rCrypt The crypt
Definition at line 41 of file AbstractCryptStatistics.cpp.
~AbstractCryptStatistics()
AbstractCryptStatistics::~AbstractCryptStatistics () virtual
Destructor.
Definition at line 46 of file AbstractCryptStatistics.cpp.
Member Function Documentation
AreCryptSectionCellsLabelled()
std::vector< bool > AbstractCryptStatistics::AreCryptSectionCellsLabelled (std::vector< CellPtr > & rCryptSection)
Get all cells within a cell width of the section defined as the line between points (xBottom,0) and (xTop,yTop). If a patricular cell is labelled then the boolean true is returned.
Periodicity can be taken into account (if xTop and xBottom are more than half a crypt width apart then a more realistic section will be across the periodic boundary), using the final parameter. This obviously requires the mesh to be cylindrical.
Parameters
rCryptSection vector of cells in the section (from a call to GetCryptSection in the concrete class)
Returns
a standard vector of booleans which states whether a labelled cell is present at a corresponding position.
Definition at line 87 of file AbstractCryptStatistics.cpp.
LabelAllCellsAsHealthy()
void AbstractCryptStatistics::LabelAllCellsAsHealthy ()
Set all the cells in the crypt to have the mutation state WildTypeCellMutationState.
Definition at line 76 of file AbstractCryptStatistics.cpp.
References AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::Begin(), AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::End(), AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::GetCellPropertyRegistry(), and mrCrypt.
LabelSPhaseCells()
void AbstractCryptStatistics::LabelSPhaseCells ()
To recreate the virtual labelling experiments performed by Meineke et al (2001) in their off-lattice model of the intestinal crypt (doi:10.1046/j.0960-7722.2001.00216.x).
Cells which are in S phase are labelled using the CellLabel cell property.
In Owen Sansom's experiments this is called twice; once at the beginning and once at the end of an hour to simulate uptake of the label over an hour, so some cells will already be labelled when this is called the second time.
(assumption that S phase lasts longer than one hour is pretty sound)
Definition at line 50 of file AbstractCryptStatistics.cpp.
References AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::Begin(), AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::End(), AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::GetCellPropertyRegistry(), AbstractPhaseBasedCellCycleModel::GetCurrentCellCyclePhase(), and mrCrypt.
Member Data Documentation
mrCrypt
MeshBasedCellPopulation<2>& AbstractCryptStatistics::mrCrypt protected
The crypt.
Definition at line 49 of file AbstractCryptStatistics.hpp.
Referenced by CryptStatistics::CellIsInSection(), CryptStatistics::CellIsInSectionPeriodic(), CryptProjectionStatistics::GetCryptSection(), CryptStatistics::GetCryptSection(), LabelAllCellsAsHealthy(), and LabelSPhaseCells().
The documentation for this class was generated from the following files:
crypt/src/statistics/AbstractCryptStatistics.hpp
crypt/src/statistics/AbstractCryptStatistics.cpp