Chaste: DeltaNotchEdgeInteriorTrackingModifier< DIM > Class Template Reference
DeltaNotchEdgeInteriorTrackingModifier< DIM > Class Template Reference
#include <DeltaNotchEdgeInteriorTrackingModifier.hpp>
Public Member Functions
DeltaNotchEdgeInteriorTrackingModifier ()
virtual ~DeltaNotchEdgeInteriorTrackingModifier ()
virtual void UpdateAtEndOfTimeStep (AbstractCellPopulation< DIM, DIM > &rCellPopulation)
virtual void SetupSolve (AbstractCellPopulation< DIM, DIM > &rCellPopulation, std::string outputDirectory)
void UpdateCellData (AbstractCellPopulation< DIM, DIM > &rCellPopulation)
void OutputSimulationModifierParameters (out_stream &rParamsFile)
Public Member Functions inherited from AbstractCellBasedSimulationModifier< DIM, DIM >
AbstractCellBasedSimulationModifier ()
virtual ~AbstractCellBasedSimulationModifier ()
virtual void UpdateAtEndOfTimeStep (AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM > &rCellPopulation)=0
virtual void UpdateAtEndOfOutputTimeStep (AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM > &rCellPopulation)
virtual void SetupSolve (AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM > &rCellPopulation, std::string outputDirectory)=0
virtual void UpdateAtEndOfSolve (AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM > &rCellPopulation)
void OutputSimulationModifierInfo (out_stream &rParamsFile)
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Friends
class boost::serialization::access
Detailed Description
template<unsigned DIM>
class DeltaNotchEdgeInteriorTrackingModifier< DIM >
A modifier class in which the mean levels of Delta in neighbouring cells are computed and stored in CellData. To be used in conjunction with Delta Notch cell cycle models.
Definition at line 51 of file DeltaNotchEdgeInteriorTrackingModifier.hpp.
Constructor & Destructor Documentation
DeltaNotchEdgeInteriorTrackingModifier()
template<unsigned DIM> DeltaNotchEdgeInteriorTrackingModifier< DIM >::DeltaNotchEdgeInteriorTrackingModifier ()
Default constructor.
Definition at line 42 of file DeltaNotchEdgeInteriorTrackingModifier.cpp.
~DeltaNotchEdgeInteriorTrackingModifier()
template<unsigned DIM> DeltaNotchEdgeInteriorTrackingModifier< DIM >::~DeltaNotchEdgeInteriorTrackingModifier () virtual
Destructor.
Definition at line 48 of file DeltaNotchEdgeInteriorTrackingModifier.cpp.
Member Function Documentation
OutputSimulationModifierParameters()
template<unsigned DIM> void DeltaNotchEdgeInteriorTrackingModifier< DIM >::OutputSimulationModifierParameters (out_stream & rParamsFile) virtual
Overridden OutputSimulationModifierParameters() method. Output any simulation modifier parameters to file.
Parameters
rParamsFile the file stream to which the parameters are output
Implements AbstractCellBasedSimulationModifier< DIM, DIM >.
Definition at line 157 of file DeltaNotchEdgeInteriorTrackingModifier.cpp.
References AbstractCellBasedSimulationModifier< ELEMENT_DIM, SPACE_DIM >::OutputSimulationModifierParameters().
serialize()
template<unsigned DIM> template<class Archive > void DeltaNotchEdgeInteriorTrackingModifier< DIM >::serialize (Archive & archive, const unsigned int version) inline private
Boost Serialization method for archiving/checkpointing. Archives the object and its member variables.
Parameters
archive The boost archive.
version The current version of this class.
Definition at line 63 of file DeltaNotchEdgeInteriorTrackingModifier.hpp.
SetupSolve()
template<unsigned DIM> void DeltaNotchEdgeInteriorTrackingModifier< DIM >::SetupSolve (AbstractCellPopulation< DIM, DIM > & rCellPopulation, std::string outputDirectory) virtual
Overridden SetupSolve() method.
Specifies what to do in the simulation before the start of the time loop.
Parameters
rCellPopulation reference to the cell population
outputDirectory the output directory, relative to where Chaste output is stored
Definition at line 59 of file DeltaNotchEdgeInteriorTrackingModifier.cpp.
UpdateAtEndOfTimeStep()
template<unsigned DIM> void DeltaNotchEdgeInteriorTrackingModifier< DIM >::UpdateAtEndOfTimeStep (AbstractCellPopulation< DIM, DIM > & rCellPopulation) virtual
Overridden UpdateAtEndOfTimeStep() method.
Specifies what to do in the simulation at the end of each time step.
Parameters
rCellPopulation reference to the cell population
Definition at line 53 of file DeltaNotchEdgeInteriorTrackingModifier.cpp.
UpdateCellData()
template<unsigned DIM> void DeltaNotchEdgeInteriorTrackingModifier< DIM >::UpdateCellData (AbstractCellPopulation< DIM, DIM > & rCellPopulation)
Helper method to compute the mean level of Delta in each cell's neighbours and store these in the CellData.
Note: If using a CaBasedCellPopulation, we assume a Moore neighbourhood and unit carrying capacity. If a cell has no neighbours (such as an isolated cell in a CaBasedCellPopulation), we store the value -1 in the CellData.
Parameters
rCellPopulation reference to the cell population
Definition at line 69 of file DeltaNotchEdgeInteriorTrackingModifier.cpp.
References AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::Begin(), AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::End(), AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::GetCellUsingLocationIndex(), AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::GetNeighbouringEdgeIndices(), and CellSrnModel::GetNumEdgeSrn().
Friends And Related Symbol Documentation
boost::serialization::access
template<unsigned DIM> friend class boost::serialization::access friend
Needed for serialization.
Definition at line 54 of file DeltaNotchEdgeInteriorTrackingModifier.hpp.
The documentation for this class was generated from the following files:
cell_based/src/simulation/modifiers/DeltaNotchEdgeInteriorTrackingModifier.hpp
cell_based/src/simulation/modifiers/DeltaNotchEdgeInteriorTrackingModifier.cpp