Chaste: ImmersedBoundaryKinematicFeedbackForce< DIM > Class Template Reference
ImmersedBoundaryKinematicFeedbackForce< DIM > Class Template Reference
#include <ImmersedBoundaryKinematicFeedbackForce.hpp>
Public Member Functions
ImmersedBoundaryKinematicFeedbackForce ()
virtual ~ImmersedBoundaryKinematicFeedbackForce ()=default
void AddImmersedBoundaryForceContribution (std::vector< std::pair< Node< DIM > *, Node< DIM > * > > &rNodePairs, ImmersedBoundaryCellPopulation< DIM > &rCellPopulation)
void OutputImmersedBoundaryForceParameters (out_stream &rParamsFile)
double GetSpringConst () const
void SetSpringConst (double springConst)
Public Member Functions inherited from AbstractImmersedBoundaryForce< DIM >
AbstractImmersedBoundaryForce ()
virtual ~AbstractImmersedBoundaryForce ()
bool GetAdditiveNormalNoise () const
void SetAdditiveNormalNoise (bool additiveNormalNoise)
double GetNormalNoiseMean () const
void SetNormalNoiseMean (double normalNoiseMean)
double GetNormalNoiseStdDev () const
void SetNormalNoiseStdDev (double normalNoiseStdDev)
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
void UpdatePreviousLocations (ImmersedBoundaryCellPopulation< DIM > &rCellPopulation)
double CalculateRelativeVelocityComponent (const c_vector< double, DIM > &rPreviousDisp, const c_vector< double, DIM > &rCurrentDisp, c_vector< double, DIM > &rUnitPerp)
Private Attributes
double mSpringConst
std::vector< c_vector< double, DIM > > mPreviousLocations
Friends
class TestImmersedBoundaryForces
class boost::serialization::access
Additional Inherited Members
Protected Member Functions inherited from AbstractImmersedBoundaryForce< DIM >
void AddNormalNoiseToNodes (ImmersedBoundaryCellPopulation< DIM > &rCellPopulation)
Protected Attributes inherited from AbstractImmersedBoundaryForce< DIM >
bool mAdditiveNormalNoise
double mNormalNoiseMean
double mNormalNoiseStdDev
Detailed Description
template<unsigned DIM>
class ImmersedBoundaryKinematicFeedbackForce< DIM >
A force class for use in immersed boundary simulations. This force implements kinematic feedback; amplification of relative motion of cells sliding past one another.
Definition at line 54 of file ImmersedBoundaryKinematicFeedbackForce.hpp.
Constructor & Destructor Documentation
ImmersedBoundaryKinematicFeedbackForce()
template<unsigned DIM> ImmersedBoundaryKinematicFeedbackForce< DIM >::ImmersedBoundaryKinematicFeedbackForce ()
Constructor.
Definition at line 41 of file ImmersedBoundaryKinematicFeedbackForce.cpp.
~ImmersedBoundaryKinematicFeedbackForce()
template<unsigned DIM> virtual ImmersedBoundaryKinematicFeedbackForce< DIM >::~ImmersedBoundaryKinematicFeedbackForce () virtual default
Destructor.
Member Function Documentation
AddImmersedBoundaryForceContribution()
template<unsigned DIM> void ImmersedBoundaryKinematicFeedbackForce< DIM >::AddImmersedBoundaryForceContribution (std::vector< std::pair< Node< DIM > *, Node< DIM > * > > & rNodePairs, ImmersedBoundaryCellPopulation< DIM > & rCellPopulation) virtual
Overridden AddImmersedBoundaryForceContribution() method. Calculates the force on each node in the immersed boundary cell population as a result of kinematic feedback.
Parameters
rNodePairs reference to a vector set of node pairs between which to contribute the force
rCellPopulation reference to the cell population
Implements AbstractImmersedBoundaryForce< DIM >.
Definition at line 49 of file ImmersedBoundaryKinematicFeedbackForce.cpp.
References Node< SPACE_DIM >::AddAppliedForceContribution(), Node< SPACE_DIM >::ContainingElementsBegin(), ImmersedBoundaryMesh< ELEMENT_DIM, SPACE_DIM >::GetAverageNodeSpacingOfElement(), Node< SPACE_DIM >::GetIndex(), ImmersedBoundaryCellPopulation< DIM >::GetInteractionDistance(), ImmersedBoundaryCellPopulation< DIM >::GetIntrinsicSpacing(), ImmersedBoundaryCellPopulation< DIM >::GetNumNodes(), ImmersedBoundaryMesh< ELEMENT_DIM, SPACE_DIM >::GetVectorFromAtoB(), Node< SPACE_DIM >::rGetLocation(), and ImmersedBoundaryCellPopulation< DIM >::rGetMesh().
CalculateRelativeVelocityComponent()
template<unsigned DIM> double ImmersedBoundaryKinematicFeedbackForce< DIM >::CalculateRelativeVelocityComponent (const c_vector< double, DIM > & rPreviousDisp, const c_vector< double, DIM > & rCurrentDisp, c_vector< double, DIM > & rUnitPerp) private
Helper function for AddImmersedBoundaryForceContribution(). Calculates the component of their relative velocity in the direction perpendicular to the line joining the two nodes at the previous time step.
This relative velocity is a measure of shear between two boundaries, which this force class amplifies.
Parameters
rPreviousDisp displacement between a pair of interacting nodes at the previous time step
rCurrentDisp displacement between the same pair of interacting nodes at the current time step
rUnitPerp filled in as a unit vector perpendicular to previousDisp
Returns
the component of the relative velocity of the nodes in the direction of unitPerp
Definition at line 132 of file ImmersedBoundaryKinematicFeedbackForce.cpp.
References SimulationTime::Instance().
GetSpringConst()
template<unsigned DIM> double ImmersedBoundaryKinematicFeedbackForce< DIM >::GetSpringConst () const
Returns
mSpringConst
Definition at line 178 of file ImmersedBoundaryKinematicFeedbackForce.cpp.
OutputImmersedBoundaryForceParameters()
template<unsigned DIM> void ImmersedBoundaryKinematicFeedbackForce< DIM >::OutputImmersedBoundaryForceParameters (out_stream & rParamsFile) virtual
Overridden OutputImmersedBoundaryForceParameters() method.
Parameters
rParamsFile the file stream to which the parameters are output
Implements AbstractImmersedBoundaryForce< DIM >.
Definition at line 168 of file ImmersedBoundaryKinematicFeedbackForce.cpp.
References AbstractImmersedBoundaryForce< DIM >::OutputImmersedBoundaryForceParameters().
serialize()
template<unsigned DIM> template<class Archive > void ImmersedBoundaryKinematicFeedbackForce< DIM >::serialize (Archive & archive, const unsigned int version) inline private
Boost Serialization method for archiving/checkpointing. Archives the object and its member variables.
Parameters
archive The boost archive.
version The current version of this class.
Definition at line 69 of file ImmersedBoundaryKinematicFeedbackForce.hpp.
References ImmersedBoundaryKinematicFeedbackForce< DIM >::mSpringConst.
SetSpringConst()
template<unsigned DIM> void ImmersedBoundaryKinematicFeedbackForce< DIM >::SetSpringConst (double springConst)
Set mSpringConst.
Parameters
springConst the new value of mSpringConst
Definition at line 184 of file ImmersedBoundaryKinematicFeedbackForce.cpp.
UpdatePreviousLocations()
template<unsigned DIM> void ImmersedBoundaryKinematicFeedbackForce< DIM >::UpdatePreviousLocations (ImmersedBoundaryCellPopulation< DIM > & rCellPopulation) private
Helper function for AddImmersedBoundaryForceContribution(). Repopulate mPreviousLocations with new values.
Parameters
rCellPopulation the cell population
Definition at line 146 of file ImmersedBoundaryKinematicFeedbackForce.cpp.
References ImmersedBoundaryCellPopulation< DIM >::rGetMesh(), and ImmersedBoundaryMesh< ELEMENT_DIM, SPACE_DIM >::rGetNodes().
Friends And Related Symbol Documentation
boost::serialization::access
template<unsigned DIM> friend class boost::serialization::access friend
Definition at line 60 of file ImmersedBoundaryKinematicFeedbackForce.hpp.
TestImmersedBoundaryForces
template<unsigned DIM> friend class TestImmersedBoundaryForces friend
Definition at line 58 of file ImmersedBoundaryKinematicFeedbackForce.hpp.
Member Data Documentation
mPreviousLocations
template<unsigned DIM> std::vector<c_vector<double, DIM> > ImmersedBoundaryKinematicFeedbackForce< DIM >::mPreviousLocations private
Vector to contain the location of each node at the previous time step.
Definition at line 84 of file ImmersedBoundaryKinematicFeedbackForce.hpp.
mSpringConst
template<unsigned DIM> double ImmersedBoundaryKinematicFeedbackForce< DIM >::mSpringConst private
The basic spring constant associated with interactions. Initialised to 1e3 in constructor.
Definition at line 79 of file ImmersedBoundaryKinematicFeedbackForce.hpp.
Referenced by ImmersedBoundaryKinematicFeedbackForce< DIM >::serialize().
The documentation for this class was generated from the following files:
cell_based/src/population/forces/ImmersedBoundaryKinematicFeedbackForce.hpp
cell_based/src/population/forces/ImmersedBoundaryKinematicFeedbackForce.cpp