Chaste: AbstractLinearParabolicPdeSystemForCoupledOdeSystem< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM > Class Template Reference
AbstractLinearParabolicPdeSystemForCoupledOdeSystem< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM > Class Template Reference abstract
#include <AbstractLinearParabolicPdeSystemForCoupledOdeSystem.hpp>
Public Member Functions
virtual double ComputeDuDtCoefficientFunction (const ChastePoint< SPACE_DIM > &rX, unsigned pdeIndex)=0
virtual double ComputeSourceTerm (const ChastePoint< SPACE_DIM > &rX, c_vector< double, PROBLEM_DIM > &rU, std::vector< double > &rOdeSolution, unsigned pdeIndex)=0
virtual double ComputeSourceTermAtNode (const Node< SPACE_DIM > &rNode, c_vector< double, PROBLEM_DIM > &rU, std::vector< double > &rOdeSolution, unsigned pdeIndex)
virtual c_matrix< double, SPACE_DIM, SPACE_DIM > ComputeDiffusionTerm (const ChastePoint< SPACE_DIM > &rX, unsigned pdeIndex, Element< ELEMENT_DIM, SPACE_DIM > *pElement=NULL)=0
virtual ~AbstractLinearParabolicPdeSystemForCoupledOdeSystem ()
Detailed Description
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM = ELEMENT_DIM, unsigned PROBLEM_DIM = 1>
class AbstractLinearParabolicPdeSystemForCoupledOdeSystem< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >
AbstractLinearParabolicPdeSystemForCoupledOdeSystem class.
A system of parabolic PDEs, which may be coupled via their source terms:
d/dt (u_i) = div (D(x) grad (u_i)) + f_i (x, u_0, ..., u_{p-1}, v_0, ..., v_{q-1}), i=0,...,p-1.
Here p denotes the size of the PDE system and each source term f_i may be nonlinear. The variables v_0, ..., v_{q-1} are assumed to satisfy a coupled ODE system of the form
d/dt (v_j) = g_j(x, u_0, ..., u_{p-1}, v_0, ..., v_{q-1}), j=0,...,q-1.
Such systems may be solved using LinearParabolicPdeSystemWithCoupledOdeSystemSolver.
Definition at line 60 of file AbstractLinearParabolicPdeSystemForCoupledOdeSystem.hpp.
Constructor & Destructor Documentation
~AbstractLinearParabolicPdeSystemForCoupledOdeSystem()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM = ELEMENT_DIM, unsigned PROBLEM_DIM = 1> virtual AbstractLinearParabolicPdeSystemForCoupledOdeSystem< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::~AbstractLinearParabolicPdeSystemForCoupledOdeSystem () inline virtual
Destructor.
Definition at line 111 of file AbstractLinearParabolicPdeSystemForCoupledOdeSystem.hpp.
Member Function Documentation
ComputeDiffusionTerm()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM = ELEMENT_DIM, unsigned PROBLEM_DIM = 1> virtual c_matrix< double, SPACE_DIM, SPACE_DIM > AbstractLinearParabolicPdeSystemForCoupledOdeSystem< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::ComputeDiffusionTerm (const ChastePoint< SPACE_DIM > & rX, unsigned pdeIndex, Element< ELEMENT_DIM, SPACE_DIM > * pElement = NULL) pure virtual
Returns
computed diffusion term D_i(x) at a point in space. The diffusion tensor should be symmetric and positive definite.
Parameters
rX The point x at which the diffusion term D_i is computed
pdeIndex the index of the PDE, denoted by i above
pElement The mesh element that x is contained in (optional)
Referenced by LinearParabolicPdeSystemWithCoupledOdeSystemSolver< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::ComputeMatrixTerm().
ComputeDuDtCoefficientFunction()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM = ELEMENT_DIM, unsigned PROBLEM_DIM = 1> virtual double AbstractLinearParabolicPdeSystemForCoupledOdeSystem< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::ComputeDuDtCoefficientFunction (const ChastePoint< SPACE_DIM > & rX, unsigned pdeIndex) pure virtual
Returns
computed function c_i(x).
Parameters
rX the point x at which the function c_i is computed
pdeIndex the index of the PDE, denoted by i above
Referenced by LinearParabolicPdeSystemWithCoupledOdeSystemSolver< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::ComputeMatrixTerm(), and LinearParabolicPdeSystemWithCoupledOdeSystemSolver< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::ComputeVectorTerm().
ComputeSourceTerm()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM = ELEMENT_DIM, unsigned PROBLEM_DIM = 1> virtual double AbstractLinearParabolicPdeSystemForCoupledOdeSystem< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::ComputeSourceTerm (const ChastePoint< SPACE_DIM > & rX, c_vector< double, PROBLEM_DIM > & rU, std::vector< double > & rOdeSolution, unsigned pdeIndex) pure virtual
Returns
computed source term f_i(x, u_1, u_2, ..., u_p) at a point in space.
Parameters
rX the point x at which the nonlinear source term is computed
rU the vector of dependent variables (u_1, u_2, ..., u_p) at the point x
rOdeSolution the ODE system state vector (v_1, ..., v_q) at the point x (if an ODE system is present)
pdeIndex the index of the PDE, denoted by i above
Referenced by LinearParabolicPdeSystemWithCoupledOdeSystemSolver< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::ComputeVectorTerm().
ComputeSourceTermAtNode()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM, unsigned PROBLEM_DIM> double AbstractLinearParabolicPdeSystemForCoupledOdeSystem< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::ComputeSourceTermAtNode (const Node< SPACE_DIM > & rNode, c_vector< double, PROBLEM_DIM > & rU, std::vector< double > & rOdeSolution, unsigned pdeIndex) virtual
Returns
computed source term f_i(x, u_1, u_2, ..., u_p) at a node.
Parameters
rNode the node at which the nonlinear source term f_i is computed
rU the vector of dependent variables (u_1, u_2, ..., u_p) at the node
rOdeSolution the ODE system state vector (v_1, ..., v_q) at the node (if an ODE system is present)
pdeIndex the index of the PDE, denoted by i above
Definition at line 120 of file AbstractLinearParabolicPdeSystemForCoupledOdeSystem.hpp.
References Node< SPACE_DIM >::GetPoint().
The documentation for this class was generated from the following file:
pde/src/problem/AbstractLinearParabolicPdeSystemForCoupledOdeSystem.hpp