Chaste: ImmersedBoundarySvgWriter< DIM > Class Template Reference
ImmersedBoundarySvgWriter< DIM > Class Template Reference
#include <ImmersedBoundarySvgWriter.hpp>
Public Member Functions
ImmersedBoundarySvgWriter ()
virtual ~ImmersedBoundarySvgWriter ()
virtual void UpdateAtEndOfTimeStep (AbstractCellPopulation< DIM, DIM > &rCellPopulation)
virtual void SetupSolve (AbstractCellPopulation< DIM, DIM > &rCellPopulation, std::string outputDirectory)
void AddPointToSvgFile (out_stream &rSvgFile, c_vector< double, DIM > location, unsigned region, double rad)
void OutputSimulationModifierParameters (out_stream &rParamsFile)
unsigned GetSamplingMultiple () const
void SetSamplingMultiple (unsigned samplingMultiple)
double GetSvgSize () const
void SetSvgSize (double svgSize)
Public Member Functions inherited from AbstractCellBasedSimulationModifier< DIM, DIM >
AbstractCellBasedSimulationModifier ()
virtual ~AbstractCellBasedSimulationModifier ()
virtual void UpdateAtEndOfTimeStep (AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM > &rCellPopulation)=0
virtual void UpdateAtEndOfOutputTimeStep (AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM > &rCellPopulation)
virtual void SetupSolve (AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM > &rCellPopulation, std::string outputDirectory)=0
virtual void UpdateAtEndOfSolve (AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM > &rCellPopulation)
void OutputSimulationModifierInfo (out_stream &rParamsFile)
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Private Attributes
unsigned mSamplingMultiple
double mSvgSize
std::string mOutputDirectory
std::string mSvgHeader
std::string mSvgFooter
Friends
class TestImmersedBoundarySvgWriter
class boost::serialization::access
Detailed Description
template<unsigned DIM>
class ImmersedBoundarySvgWriter< DIM >
A modifier class which after each simulation time step exports the simulation geometry to a scalable vector graphic (SVG) file.
Definition at line 50 of file ImmersedBoundarySvgWriter.hpp.
Constructor & Destructor Documentation
ImmersedBoundarySvgWriter()
template<unsigned DIM> ImmersedBoundarySvgWriter< DIM >::ImmersedBoundarySvgWriter ()
Default constructor.
Definition at line 40 of file ImmersedBoundarySvgWriter.cpp.
~ImmersedBoundarySvgWriter()
template<unsigned DIM> ImmersedBoundarySvgWriter< DIM >::~ImmersedBoundarySvgWriter () virtual
Destructor.
Definition at line 51 of file ImmersedBoundarySvgWriter.cpp.
Member Function Documentation
AddPointToSvgFile()
template<unsigned DIM> void ImmersedBoundarySvgWriter< DIM >::AddPointToSvgFile (out_stream & rSvgFile, c_vector< double, DIM > location, unsigned region, double rad)
Helper method for UpdateAtEndOfTimeStep().
Add a circle representing a point location to the svg file.
Parameters
rSvgFile the svg file stream to add to
location the location of the point
region metadata to allow different colouring for points
rad the radius of circle representing the point
Definition at line 147 of file ImmersedBoundarySvgWriter.cpp.
GetSamplingMultiple()
template<unsigned DIM> unsigned ImmersedBoundarySvgWriter< DIM >::GetSamplingMultiple () const
Returns
mSamplingMultiple
Definition at line 203 of file ImmersedBoundarySvgWriter.cpp.
GetSvgSize()
template<unsigned DIM> double ImmersedBoundarySvgWriter< DIM >::GetSvgSize () const
Returns
mSvgSize
Definition at line 216 of file ImmersedBoundarySvgWriter.cpp.
OutputSimulationModifierParameters()
template<unsigned DIM> void ImmersedBoundarySvgWriter< DIM >::OutputSimulationModifierParameters (out_stream & rParamsFile) virtual
Overridden OutputSimulationModifierParameters() method. Output any simulation modifier parameters to file.
Parameters
rParamsFile the file stream to which the parameters are output
Implements AbstractCellBasedSimulationModifier< DIM, DIM >.
Definition at line 195 of file ImmersedBoundarySvgWriter.cpp.
References AbstractCellBasedSimulationModifier< ELEMENT_DIM, SPACE_DIM >::OutputSimulationModifierParameters().
serialize()
template<unsigned DIM> template<class Archive > void ImmersedBoundarySvgWriter< DIM >::serialize (Archive & archive, const unsigned int version) inline private
Boost Serialization method for archiving/checkpointing. Archives the object and its member variables.
Parameters
archive The boost archive.
version The current version of this class.
Definition at line 79 of file ImmersedBoundarySvgWriter.hpp.
References ImmersedBoundarySvgWriter< DIM >::mOutputDirectory, ImmersedBoundarySvgWriter< DIM >::mSamplingMultiple, ImmersedBoundarySvgWriter< DIM >::mSvgFooter, ImmersedBoundarySvgWriter< DIM >::mSvgHeader, and ImmersedBoundarySvgWriter< DIM >::mSvgSize.
SetSamplingMultiple()
template<unsigned DIM> void ImmersedBoundarySvgWriter< DIM >::SetSamplingMultiple (unsigned samplingMultiple)
Parameters
samplingMultiple the new value of mSamplingMultiple
Definition at line 209 of file ImmersedBoundarySvgWriter.cpp.
SetSvgSize()
template<unsigned DIM> void ImmersedBoundarySvgWriter< DIM >::SetSvgSize (double svgSize)
Parameters
svgSize the new value of mSvgSize
Definition at line 222 of file ImmersedBoundarySvgWriter.cpp.
SetupSolve()
template<unsigned DIM> void ImmersedBoundarySvgWriter< DIM >::SetupSolve (AbstractCellPopulation< DIM, DIM > & rCellPopulation, std::string outputDirectory) virtual
Overridden SetupSolve() method.
Specify what to do in the simulation before the start of the time loop.
Parameters
rCellPopulation reference to the cell population
outputDirectory the output directory, relative to where Chaste output is stored
Definition at line 90 of file ImmersedBoundarySvgWriter.cpp.
UpdateAtEndOfTimeStep()
template<unsigned DIM> void ImmersedBoundarySvgWriter< DIM >::UpdateAtEndOfTimeStep (AbstractCellPopulation< DIM, DIM > & rCellPopulation) virtual
Overridden UpdateAtEndOfTimeStep() method.
Specify what to do in the simulation at the end of each time step.
Parameters
rCellPopulation reference to the cell population
Definition at line 56 of file ImmersedBoundarySvgWriter.cpp.
References ImmersedBoundaryMesh< ELEMENT_DIM, SPACE_DIM >::GetAverageNodeSpacingOfElement(), AbstractMesh< ELEMENT_DIM, SPACE_DIM >::GetNodeIteratorBegin(), AbstractMesh< ELEMENT_DIM, SPACE_DIM >::GetNodeIteratorEnd(), SimulationTime::GetTimeStepsElapsed(), SimulationTime::Instance(), OutputFileHandler::OpenOutputFile(), and AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::rGetMesh().
Friends And Related Symbol Documentation
boost::serialization::access
template<unsigned DIM> friend class boost::serialization::access friend
Needed for serialization.
Definition at line 70 of file ImmersedBoundarySvgWriter.hpp.
TestImmersedBoundarySvgWriter
template<unsigned DIM> friend class TestImmersedBoundarySvgWriter friend
Definition at line 67 of file ImmersedBoundarySvgWriter.hpp.
Member Data Documentation
mOutputDirectory
template<unsigned DIM> std::string ImmersedBoundarySvgWriter< DIM >::mOutputDirectory private
Set to the output directory during SetupSolve()
Definition at line 59 of file ImmersedBoundarySvgWriter.hpp.
Referenced by ImmersedBoundarySvgWriter< DIM >::serialize().
mSamplingMultiple
template<unsigned DIM> unsigned ImmersedBoundarySvgWriter< DIM >::mSamplingMultiple private
The sampling frequency for exporting svg frames
Definition at line 53 of file ImmersedBoundarySvgWriter.hpp.
Referenced by ImmersedBoundarySvgWriter< DIM >::serialize().
mSvgFooter
template<unsigned DIM> std::string ImmersedBoundarySvgWriter< DIM >::mSvgFooter private
The svg file footer, which will be constant for a given simulation
Definition at line 65 of file ImmersedBoundarySvgWriter.hpp.
Referenced by ImmersedBoundarySvgWriter< DIM >::serialize().
mSvgHeader
template<unsigned DIM> std::string ImmersedBoundarySvgWriter< DIM >::mSvgHeader private
The svg file header, which will be constant for a given simulation
Definition at line 62 of file ImmersedBoundarySvgWriter.hpp.
Referenced by ImmersedBoundarySvgWriter< DIM >::serialize().
mSvgSize
template<unsigned DIM> double ImmersedBoundarySvgWriter< DIM >::mSvgSize private
The width and height in pixels of the svg file
Definition at line 56 of file ImmersedBoundarySvgWriter.hpp.
Referenced by ImmersedBoundarySvgWriter< DIM >::serialize().
The documentation for this class was generated from the following files:
cell_based/src/simulation/modifiers/ImmersedBoundarySvgWriter.hpp
cell_based/src/simulation/modifiers/ImmersedBoundarySvgWriter.cpp