Chaste: FibreConverter Class Reference
FibreConverter Class Reference
#include <FibreConverter.hpp>
Public Member Functions
void Convert (const FileFinder &rSourceFile, const std::string &rOutputFolderName)
Detailed Description
A convenience wrapper around FibreReader and FibreWriter to convert .axi and .ortho fibres from ascii to binary.
Definition at line 46 of file FibreConverter.hpp.
Member Function Documentation
Convert()
void FibreConverter::Convert (const FileFinder & rSourceFile, const std::string & rOutputFolderName)
The method that converts fibre files from ascii to binary.
Parameters
rSourceFile a file finder to any mesh file - the base name minus extension is used
rOutputFolderName name of folder where converted fibre files will be written
Definition at line 40 of file FibreConverter.cpp.
References FileFinder::Exists(), FibreReader< DIM >::GetAllAxi(), FibreReader< DIM >::GetAllOrtho(), FileFinder::GetLeafNameNoExtension(), FileFinder::GetParent(), FibreWriter< DIM >::SetWriteFileAsBinary(), FibreWriter< DIM >::WriteAllAxi(), and FibreWriter< DIM >::WriteAllOrtho().
The documentation for this class was generated from the following files:
heart/src/io/FibreConverter.hpp
heart/src/io/FibreConverter.cpp