Chaste: ImmersedBoundaryMorseInteractionForce< DIM > Class Template Reference
ImmersedBoundaryMorseInteractionForce< DIM > Class Template Reference
#include <ImmersedBoundaryMorseInteractionForce.hpp>
Public Member Functions
ImmersedBoundaryMorseInteractionForce ()
virtual ~ImmersedBoundaryMorseInteractionForce ()
void AddImmersedBoundaryForceContribution (std::vector< std::pair< Node< DIM > *, Node< DIM > * > > &rNodePairs, ImmersedBoundaryCellPopulation< DIM > &rCellPopulation)
void OutputImmersedBoundaryForceParameters (out_stream &rParamsFile)
double GetWellDepth () const
void SetWellDepth (double wellDepth)
double GetRestLength () const
void SetRestLength (double restLength)
double GetLaminaWellDepthMult () const
void SetLaminaWellDepthMult (double laminaWellDepthMult)
double GetLaminaRestLengthMult () const
void SetLaminaRestLengthMult (double laminaRestLengthMult)
double GetWellWidth () const
void SetWellWidth (double wellWidth)
Public Member Functions inherited from AbstractImmersedBoundaryForce< DIM >
AbstractImmersedBoundaryForce ()
virtual ~AbstractImmersedBoundaryForce ()
bool GetAdditiveNormalNoise () const
void SetAdditiveNormalNoise (bool additiveNormalNoise)
double GetNormalNoiseMean () const
void SetNormalNoiseMean (double normalNoiseMean)
double GetNormalNoiseStdDev () const
void SetNormalNoiseStdDev (double normalNoiseStdDev)
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Private Attributes
double mWellDepth
double mRestLength
double mLaminaWellDepthMult
double mLaminaRestLengthMult
double mWellWidth
Friends
class boost::serialization::access
Additional Inherited Members
Protected Member Functions inherited from AbstractImmersedBoundaryForce< DIM >
void AddNormalNoiseToNodes (ImmersedBoundaryCellPopulation< DIM > &rCellPopulation)
Protected Attributes inherited from AbstractImmersedBoundaryForce< DIM >
bool mAdditiveNormalNoise
double mNormalNoiseMean
double mNormalNoiseStdDev
Detailed Description
template<unsigned DIM>
class ImmersedBoundaryMorseInteractionForce< DIM >
A force class for use in immersed boundary simulations. This force implements Morse-potential-like links between nodes in adjacent immersed boundaries (https://en.wikipedia.org/wiki/Morse_potential). The well width is a constant interaction strength, the rest length is an equilibrium bond distance, and the well width is a parameter governing the profile of the curve.
Definition at line 57 of file ImmersedBoundaryMorseInteractionForce.hpp.
Constructor & Destructor Documentation
ImmersedBoundaryMorseInteractionForce()
template<unsigned DIM> ImmersedBoundaryMorseInteractionForce< DIM >::ImmersedBoundaryMorseInteractionForce ()
Constructor.
Definition at line 40 of file ImmersedBoundaryMorseInteractionForce.cpp.
~ImmersedBoundaryMorseInteractionForce()
template<unsigned DIM> ImmersedBoundaryMorseInteractionForce< DIM >::~ImmersedBoundaryMorseInteractionForce () virtual
Destructor.
Definition at line 51 of file ImmersedBoundaryMorseInteractionForce.cpp.
Member Function Documentation
AddImmersedBoundaryForceContribution()
template<unsigned DIM> void ImmersedBoundaryMorseInteractionForce< DIM >::AddImmersedBoundaryForceContribution (std::vector< std::pair< Node< DIM > *, Node< DIM > * > > & rNodePairs, ImmersedBoundaryCellPopulation< DIM > & rCellPopulation) virtual
Overridden AddImmersedBoundaryForceContribution() method.
Calculates the force on each node in the immersed boundary cell population as a result of cell-cell interactions.
Parameters
rNodePairs reference to a vector set of node pairs between which to contribute the force
rCellPopulation reference to the cell population
Implements AbstractImmersedBoundaryForce< DIM >.
Definition at line 56 of file ImmersedBoundaryMorseInteractionForce.cpp.
References Node< SPACE_DIM >::AddAppliedForceContribution(), Node< SPACE_DIM >::ContainingElementsBegin(), ImmersedBoundaryMesh< ELEMENT_DIM, SPACE_DIM >::GetAverageNodeSpacingOfElement(), ImmersedBoundaryMesh< ELEMENT_DIM, SPACE_DIM >::GetAverageNodeSpacingOfLamina(), ImmersedBoundaryCellPopulation< DIM >::GetInteractionDistance(), ImmersedBoundaryCellPopulation< DIM >::GetIntrinsicSpacing(), Node< SPACE_DIM >::GetRegion(), ImmersedBoundaryMesh< ELEMENT_DIM, SPACE_DIM >::GetVectorFromAtoB(), ImmersedBoundaryMesh< ELEMENT_DIM, SPACE_DIM >::NodesInDifferentElementOrLamina(), Node< SPACE_DIM >::rGetLocation(), and ImmersedBoundaryCellPopulation< DIM >::rGetMesh().
GetLaminaRestLengthMult()
template<unsigned DIM> double ImmersedBoundaryMorseInteractionForce< DIM >::GetLaminaRestLengthMult () const
Returns
mLaminaRestLengthMult
Definition at line 184 of file ImmersedBoundaryMorseInteractionForce.cpp.
GetLaminaWellDepthMult()
template<unsigned DIM> double ImmersedBoundaryMorseInteractionForce< DIM >::GetLaminaWellDepthMult () const
Returns
mLaminaWellDepthMult
Definition at line 171 of file ImmersedBoundaryMorseInteractionForce.cpp.
GetRestLength()
template<unsigned DIM> double ImmersedBoundaryMorseInteractionForce< DIM >::GetRestLength () const
Returns
mRestLength
Definition at line 159 of file ImmersedBoundaryMorseInteractionForce.cpp.
GetWellDepth()
template<unsigned DIM> double ImmersedBoundaryMorseInteractionForce< DIM >::GetWellDepth () const
Returns
mWellDepth
Definition at line 147 of file ImmersedBoundaryMorseInteractionForce.cpp.
GetWellWidth()
template<unsigned DIM> double ImmersedBoundaryMorseInteractionForce< DIM >::GetWellWidth () const
Returns
mWellWidth
Definition at line 197 of file ImmersedBoundaryMorseInteractionForce.cpp.
OutputImmersedBoundaryForceParameters()
template<unsigned DIM> void ImmersedBoundaryMorseInteractionForce< DIM >::OutputImmersedBoundaryForceParameters (out_stream & rParamsFile) virtual
Overridden OutputImmersedBoundaryForceParameters() method.
Parameters
rParamsFile the file stream to which the parameters are output
Implements AbstractImmersedBoundaryForce< DIM >.
Definition at line 133 of file ImmersedBoundaryMorseInteractionForce.cpp.
References AbstractImmersedBoundaryForce< DIM >::OutputImmersedBoundaryForceParameters().
serialize()
template<unsigned DIM> template<class Archive > void ImmersedBoundaryMorseInteractionForce< DIM >::serialize (Archive & archive, const unsigned int version) inline private
Boost Serialization method for archiving/checkpointing. Archives the object and its member variables.
Parameters
archive The boost archive.
version The current version of this class.
Definition at line 69 of file ImmersedBoundaryMorseInteractionForce.hpp.
References ImmersedBoundaryMorseInteractionForce< DIM >::mLaminaRestLengthMult, ImmersedBoundaryMorseInteractionForce< DIM >::mLaminaWellDepthMult, ImmersedBoundaryMorseInteractionForce< DIM >::mRestLength, ImmersedBoundaryMorseInteractionForce< DIM >::mWellDepth, and ImmersedBoundaryMorseInteractionForce< DIM >::mWellWidth.
SetLaminaRestLengthMult()
template<unsigned DIM> void ImmersedBoundaryMorseInteractionForce< DIM >::SetLaminaRestLengthMult (double laminaRestLengthMult)
Set mLaminaRestLengthMult.
Parameters
laminaRestLengthMult the new value of mLaminaRestLengthMult
Definition at line 190 of file ImmersedBoundaryMorseInteractionForce.cpp.
SetLaminaWellDepthMult()
template<unsigned DIM> void ImmersedBoundaryMorseInteractionForce< DIM >::SetLaminaWellDepthMult (double laminaWellDepthMult)
Set mLaminaWellDepthMult.
Parameters
laminaWellDepthMult the new value of mLaminaWellDepthMult
Definition at line 177 of file ImmersedBoundaryMorseInteractionForce.cpp.
SetRestLength()
template<unsigned DIM> void ImmersedBoundaryMorseInteractionForce< DIM >::SetRestLength (double restLength)
Set mRestLength.
Parameters
restLength the new value of mRestLength
Definition at line 165 of file ImmersedBoundaryMorseInteractionForce.cpp.
SetWellDepth()
template<unsigned DIM> void ImmersedBoundaryMorseInteractionForce< DIM >::SetWellDepth (double wellDepth)
Set mWellDepth.
Parameters
wellDepth the new value of mWellDepth
Definition at line 153 of file ImmersedBoundaryMorseInteractionForce.cpp.
SetWellWidth()
template<unsigned DIM> void ImmersedBoundaryMorseInteractionForce< DIM >::SetWellWidth (double wellWidth)
Set mWellWidth.
Parameters
wellWidth the new value of mWellWidth
Definition at line 203 of file ImmersedBoundaryMorseInteractionForce.cpp.
Friends And Related Symbol Documentation
boost::serialization::access
template<unsigned DIM> friend class boost::serialization::access friend
Definition at line 60 of file ImmersedBoundaryMorseInteractionForce.hpp.
Member Data Documentation
mLaminaRestLengthMult
template<unsigned DIM> double ImmersedBoundaryMorseInteractionForce< DIM >::mLaminaRestLengthMult private
Multiplicative factor to change equilibrium length of interactions involving a lamina node. Initialised to 1.0 in constructor.
Definition at line 100 of file ImmersedBoundaryMorseInteractionForce.hpp.
Referenced by ImmersedBoundaryMorseInteractionForce< DIM >::serialize().
mLaminaWellDepthMult
template<unsigned DIM> double ImmersedBoundaryMorseInteractionForce< DIM >::mLaminaWellDepthMult private
Multiplicative factor to change strength of interactions involving a lamina node. Initialised to 1.0 in constructor.
Definition at line 94 of file ImmersedBoundaryMorseInteractionForce.hpp.
Referenced by ImmersedBoundaryMorseInteractionForce< DIM >::serialize().
mRestLength
template<unsigned DIM> double ImmersedBoundaryMorseInteractionForce< DIM >::mRestLength private
The basic rest length associated with interactions, as a fraction of cell population's interaction distance. Initialised to 0.25 in constructor.
Definition at line 88 of file ImmersedBoundaryMorseInteractionForce.hpp.
Referenced by ImmersedBoundaryMorseInteractionForce< DIM >::serialize().
mWellDepth
template<unsigned DIM> double ImmersedBoundaryMorseInteractionForce< DIM >::mWellDepth private
The basic interaction strength. Initialised to 1e3 in constructor.
Definition at line 82 of file ImmersedBoundaryMorseInteractionForce.hpp.
Referenced by ImmersedBoundaryMorseInteractionForce< DIM >::serialize().
mWellWidth
template<unsigned DIM> double ImmersedBoundaryMorseInteractionForce< DIM >::mWellWidth private
The well width as a fraction of the cell population's interaction distance. Initialised to 0.25 in constructor.
Definition at line 106 of file ImmersedBoundaryMorseInteractionForce.hpp.
Referenced by ImmersedBoundaryMorseInteractionForce< DIM >::serialize().
The documentation for this class was generated from the following files:
cell_based/src/population/forces/ImmersedBoundaryMorseInteractionForce.hpp
cell_based/src/population/forces/ImmersedBoundaryMorseInteractionForce.cpp