Chaste: ExtrinsicPullModifier< DIM > Class Template Reference
ExtrinsicPullModifier< DIM > Class Template Reference
#include <ExtrinsicPullModifier.hpp>
Public Member Functions
ExtrinsicPullModifier ()
virtual ~ExtrinsicPullModifier ()
virtual void UpdateAtEndOfTimeStep (AbstractCellPopulation< DIM, DIM > &rCellPopulation)
virtual void SetupSolve (AbstractCellPopulation< DIM, DIM > &rCellPopulation, std::string outputDirectory)
void SetApplyExtrinsicPullToAllNodes (bool applyExtrinsicPullToAllNodes)
void SetSpeed (double speed)
bool GetApplyExtrinsicPullToAllNodes ()
double GetSpeed ()
void OutputSimulationModifierParameters (out_stream &rParamsFile)
Public Member Functions inherited from AbstractCellBasedSimulationModifier< DIM, DIM >
AbstractCellBasedSimulationModifier ()
virtual ~AbstractCellBasedSimulationModifier ()
virtual void UpdateAtEndOfTimeStep (AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM > &rCellPopulation)=0
virtual void UpdateAtEndOfOutputTimeStep (AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM > &rCellPopulation)
virtual void SetupSolve (AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM > &rCellPopulation, std::string outputDirectory)=0
virtual void UpdateAtEndOfSolve (AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM > &rCellPopulation)
void OutputSimulationModifierInfo (out_stream &rParamsFile)
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Private Attributes
bool mApplyExtrinsicPullToAllNodes
double mSpeed
Friends
class boost::serialization::access
Detailed Description
template<unsigned DIM>
class ExtrinsicPullModifier< DIM >
A modifier class which at each simulation time step applies an extrinsic pull to the right at a specified speed, optionally applying this to all nodes or else just the right-most nodes.
Definition at line 50 of file ExtrinsicPullModifier.hpp.
Constructor & Destructor Documentation
ExtrinsicPullModifier()
template<unsigned DIM> ExtrinsicPullModifier< DIM >::ExtrinsicPullModifier ()
Default constructor.
Definition at line 39 of file ExtrinsicPullModifier.cpp.
~ExtrinsicPullModifier()
template<unsigned DIM> ExtrinsicPullModifier< DIM >::~ExtrinsicPullModifier () virtual
Destructor.
Definition at line 47 of file ExtrinsicPullModifier.cpp.
Member Function Documentation
GetApplyExtrinsicPullToAllNodes()
template<unsigned DIM> bool ExtrinsicPullModifier< DIM >::GetApplyExtrinsicPullToAllNodes ()
Returns
mApplyExtrinsicPullToAllNodes
Definition at line 109 of file ExtrinsicPullModifier.cpp.
GetSpeed()
template<unsigned DIM> double ExtrinsicPullModifier< DIM >::GetSpeed ()
Returns
mSpeed
Definition at line 115 of file ExtrinsicPullModifier.cpp.
OutputSimulationModifierParameters()
template<unsigned DIM> void ExtrinsicPullModifier< DIM >::OutputSimulationModifierParameters (out_stream & rParamsFile) virtual
Overridden OutputSimulationModifierParameters() method. Output any simulation modifier parameters to file.
Parameters
rParamsFile the file stream to which the parameters are output
Implements AbstractCellBasedSimulationModifier< DIM, DIM >.
Definition at line 121 of file ExtrinsicPullModifier.cpp.
References AbstractCellBasedSimulationModifier< ELEMENT_DIM, SPACE_DIM >::OutputSimulationModifierParameters().
serialize()
template<unsigned DIM> template<class Archive > void ExtrinsicPullModifier< DIM >::serialize (Archive & archive, const unsigned int version) inline private
Boost Serialization method for archiving/checkpointing. Archives the object and its member variables.
Parameters
archive The boost archive.
version The current version of this class.
Definition at line 64 of file ExtrinsicPullModifier.hpp.
References ExtrinsicPullModifier< DIM >::mApplyExtrinsicPullToAllNodes, and ExtrinsicPullModifier< DIM >::mSpeed.
SetApplyExtrinsicPullToAllNodes()
template<unsigned DIM> void ExtrinsicPullModifier< DIM >::SetApplyExtrinsicPullToAllNodes (bool applyExtrinsicPullToAllNodes)
Parameters
applyExtrinsicPullToAllNodes whether to apply the extrinsic pull to all nodes in the tissue
Definition at line 97 of file ExtrinsicPullModifier.cpp.
SetSpeed()
template<unsigned DIM> void ExtrinsicPullModifier< DIM >::SetSpeed (double speed)
Parameters
speed the speed of the extrinsic pull
Definition at line 103 of file ExtrinsicPullModifier.cpp.
SetupSolve()
template<unsigned DIM> void ExtrinsicPullModifier< DIM >::SetupSolve (AbstractCellPopulation< DIM, DIM > & rCellPopulation, std::string outputDirectory) virtual
Overridden SetupSolve() method.
Specifies what to do in the simulation before the start of the time loop.
Parameters
rCellPopulation reference to the cell population
outputDirectory the output directory, relative to where Chaste output is stored
Definition at line 92 of file ExtrinsicPullModifier.cpp.
UpdateAtEndOfTimeStep()
template<unsigned DIM> void ExtrinsicPullModifier< DIM >::UpdateAtEndOfTimeStep (AbstractCellPopulation< DIM, DIM > & rCellPopulation) virtual
Overridden UpdateAtEndOfTimeStep() method.
Specifies what to do in the simulation at the end of each time step.
Parameters
rCellPopulation reference to the cell population
Definition at line 52 of file ExtrinsicPullModifier.cpp.
References AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::GetNode(), AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::GetNumNodes(), SimulationTime::GetTimeStep(), SimulationTime::Instance(), Node< SPACE_DIM >::rGetLocation(), ChasteCuboid< SPACE_DIM >::rGetLowerCorner(), AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::rGetMesh(), Node< SPACE_DIM >::rGetModifiableLocation(), and ChasteCuboid< SPACE_DIM >::rGetUpperCorner().
Friends And Related Symbol Documentation
boost::serialization::access
template<unsigned DIM> friend class boost::serialization::access friend
Needed for serialization.
Definition at line 55 of file ExtrinsicPullModifier.hpp.
Member Data Documentation
mApplyExtrinsicPullToAllNodes
template<unsigned DIM> bool ExtrinsicPullModifier< DIM >::mApplyExtrinsicPullToAllNodes private
Whether to apply extrinsic pull on all nodes (or just the right-most nodes).
Definition at line 74 of file ExtrinsicPullModifier.hpp.
Referenced by ExtrinsicPullModifier< DIM >::serialize().
mSpeed
template<unsigned DIM> double ExtrinsicPullModifier< DIM >::mSpeed private
The speed of the extrinsic pull.
Definition at line 79 of file ExtrinsicPullModifier.hpp.
Referenced by ExtrinsicPullModifier< DIM >::serialize().
The documentation for this class was generated from the following files:
cell_based/src/simulation/modifiers/ExtrinsicPullModifier.hpp
cell_based/src/simulation/modifiers/ExtrinsicPullModifier.cpp