Chaste: ShortAxisImmersedBoundaryDivisionRule< SPACE_DIM > Class Template Reference
ShortAxisImmersedBoundaryDivisionRule< SPACE_DIM > Class Template Reference
#include <ShortAxisImmersedBoundaryDivisionRule.hpp>
Public Member Functions
ShortAxisImmersedBoundaryDivisionRule ()
virtual ~ShortAxisImmersedBoundaryDivisionRule ()
virtual c_vector< double, SPACE_DIM > CalculateCellDivisionVector (CellPtr pParentCell, ImmersedBoundaryCellPopulation< SPACE_DIM > &rCellPopulation)
Public Member Functions inherited from AbstractImmersedBoundaryDivisionRule< SPACE_DIM >
AbstractImmersedBoundaryDivisionRule ()
virtual ~AbstractImmersedBoundaryDivisionRule ()
void OutputCellImmersedBoundaryDivisionRuleInfo (out_stream &rParamsFile)
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Friends
class boost::serialization::access
Additional Inherited Members
Protected Member Functions inherited from AbstractImmersedBoundaryDivisionRule< SPACE_DIM >
virtual void OutputCellImmersedBoundaryDivisionRuleParameters (out_stream &rParamsFile)
Detailed Description
template<unsigned SPACE_DIM>
class ShortAxisImmersedBoundaryDivisionRule< SPACE_DIM >
A class to generate the short axis of a cell for immersed boundary cell populations, to be used in cell division. This is the default rule that is used in most immersed boundary simulations.
The short axis is the eigenvector associated with the largest eigenvalue of the matrix of second moments of the cell's polygon.
Definition at line 60 of file ShortAxisImmersedBoundaryDivisionRule.hpp.
Constructor & Destructor Documentation
ShortAxisImmersedBoundaryDivisionRule()
template<unsigned SPACE_DIM> ShortAxisImmersedBoundaryDivisionRule< SPACE_DIM >::ShortAxisImmersedBoundaryDivisionRule () inline
Default constructor.
Definition at line 80 of file ShortAxisImmersedBoundaryDivisionRule.hpp.
~ShortAxisImmersedBoundaryDivisionRule()
template<unsigned SPACE_DIM> virtual ShortAxisImmersedBoundaryDivisionRule< SPACE_DIM >::~ShortAxisImmersedBoundaryDivisionRule () inline virtual
Empty destructor.
Definition at line 87 of file ShortAxisImmersedBoundaryDivisionRule.hpp.
Member Function Documentation
CalculateCellDivisionVector()
template<unsigned SPACE_DIM> c_vector< double, SPACE_DIM > ShortAxisImmersedBoundaryDivisionRule< SPACE_DIM >::CalculateCellDivisionVector (CellPtr pParentCell, ImmersedBoundaryCellPopulation< SPACE_DIM > & rCellPopulation) virtual
Overridden CalculateCellDivisionVector() method. Return the short axis of the existing cell, which will be used to form the boundary between the daughter cells.
Parameters
pParentCell The cell to divide
rCellPopulation The immersed boundary cell population
Returns
the division vector.
Implements AbstractImmersedBoundaryDivisionRule< SPACE_DIM >.
Definition at line 39 of file ShortAxisImmersedBoundaryDivisionRule.cpp.
References AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::GetLocationIndexUsingCell(), ImmersedBoundaryMesh< ELEMENT_DIM, SPACE_DIM >::GetShortAxisOfElement(), and ImmersedBoundaryCellPopulation< DIM >::rGetMesh().
serialize()
template<unsigned SPACE_DIM> template<class Archive > void ShortAxisImmersedBoundaryDivisionRule< SPACE_DIM >::serialize (Archive & archive, const unsigned int version) inline private
Serialize the object and its member variables.
Parameters
archive the archive
version the current version of this class
Definition at line 71 of file ShortAxisImmersedBoundaryDivisionRule.hpp.
Friends And Related Symbol Documentation
boost::serialization::access
template<unsigned SPACE_DIM> friend class boost::serialization::access friend
Definition at line 63 of file ShortAxisImmersedBoundaryDivisionRule.hpp.
The documentation for this class was generated from the following files:
cell_based/src/population/division_rules/ShortAxisImmersedBoundaryDivisionRule.hpp
cell_based/src/population/division_rules/ShortAxisImmersedBoundaryDivisionRule.cpp