Chaste: PlanarPolarisedFarhadifarForce< DIM > Class Template Reference
PlanarPolarisedFarhadifarForce< DIM > Class Template Reference
#include <PlanarPolarisedFarhadifarForce.hpp>
Public Member Functions
PlanarPolarisedFarhadifarForce ()
virtual ~PlanarPolarisedFarhadifarForce ()
virtual double GetLineTensionParameter (Node< DIM > *pNodeA, Node< DIM > *pNodeB, VertexBasedCellPopulation< DIM > &rVertexCellPopulation)
double GetPlanarPolarisedLineTensionMultiplier ()
void SetPlanarPolarisedLineTensionMultiplier (double planarPolarisedLineTensionMultiplier)
double GetLineTensionParameter ()
double GetBoundaryLineTensionParameter ()
void OutputForceParameters (out_stream &rParamsFile)
Public Member Functions inherited from FarhadifarForce< DIM >
FarhadifarForce ()
virtual ~FarhadifarForce ()
virtual void AddForceContribution (AbstractCellPopulation< DIM > &rCellPopulation)
double GetAreaElasticityParameter ()
double GetPerimeterContractilityParameter ()
double GetLineTensionParameter ()
double GetBoundaryLineTensionParameter ()
double GetTargetAreaParameter ()
void SetAreaElasticityParameter (double areaElasticityParameter)
void SetPerimeterContractilityParameter (double perimeterContractilityParameter)
void SetLineTensionParameter (double lineTensionParameter)
void SetBoundaryLineTensionParameter (double boundaryLineTensionParameter)
void SetTargetAreaParameter (double targetAreaParameter)
Public Member Functions inherited from AbstractForce< DIM >
AbstractForce ()
virtual ~AbstractForce ()
virtual void AddForceContribution (AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM > &rCellPopulation)=0
void OutputForceInfo (out_stream &rParamsFile)
virtual void WriteDataToVisualizerSetupFile (out_stream &pVizSetupFile)
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Protected Attributes
double mPlanarPolarisedLineTensionMultiplier
Protected Attributes inherited from FarhadifarForce< DIM >
double mAreaElasticityParameter
double mPerimeterContractilityParameter
double mLineTensionParameter
double mBoundaryLineTensionParameter
double mTargetAreaParameter
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Friends
class TestForces
class boost::serialization::access
Detailed Description
template<unsigned DIM>
class PlanarPolarisedFarhadifarForce< DIM >
A force class for use in vertex-based simulations. This force is based on the energy function proposed by Farhadifar et al in Curr. Biol., 2007, 17, 2095-2104, but with a planar polarised line tension parameter, similar to that proposed by Rauzi et al in Nat. Cell Biol., 2008, 10, 1401-1410.
Definition at line 52 of file PlanarPolarisedFarhadifarForce.hpp.
Constructor & Destructor Documentation
PlanarPolarisedFarhadifarForce()
template<unsigned DIM> PlanarPolarisedFarhadifarForce< DIM >::PlanarPolarisedFarhadifarForce ()
Constructor.
Definition at line 39 of file PlanarPolarisedFarhadifarForce.cpp.
~PlanarPolarisedFarhadifarForce()
template<unsigned DIM> PlanarPolarisedFarhadifarForce< DIM >::~PlanarPolarisedFarhadifarForce () virtual
Destructor.
Definition at line 46 of file PlanarPolarisedFarhadifarForce.cpp.
Member Function Documentation
GetBoundaryLineTensionParameter()
template<unsigned DIM> double PlanarPolarisedFarhadifarForce< DIM >::GetBoundaryLineTensionParameter ()
Returns
mBoundaryLineTensionParameter
Definition at line 109 of file PlanarPolarisedFarhadifarForce.cpp.
GetLineTensionParameter() [1/2]
template<unsigned DIM> double PlanarPolarisedFarhadifarForce< DIM >::GetLineTensionParameter ()
Returns
mLineTensionParameter
Definition at line 103 of file PlanarPolarisedFarhadifarForce.cpp.
GetLineTensionParameter() [2/2]
template<unsigned DIM> double PlanarPolarisedFarhadifarForce< DIM >::GetLineTensionParameter (Node< DIM > * pNodeA, Node< DIM > * pNodeB, VertexBasedCellPopulation< DIM > & rVertexCellPopulation) virtual
Overridden GetLineTensionParameter() method.
Get the line tension parameter for the edge between two given nodes.
Parameters
pNodeA one node
pNodeB the other node
rVertexCellPopulation reference to the cell population
Returns
the line tension parameter for this edge.
Reimplemented from FarhadifarForce< DIM >.
Definition at line 63 of file PlanarPolarisedFarhadifarForce.cpp.
References Node< SPACE_DIM >::rGetContainingElementIndices(), and Node< SPACE_DIM >::rGetLocation().
GetPlanarPolarisedLineTensionMultiplier()
template<unsigned DIM> double PlanarPolarisedFarhadifarForce< DIM >::GetPlanarPolarisedLineTensionMultiplier ()
Returns
mPlanarPolarisedLineTensionMultiplier
Definition at line 51 of file PlanarPolarisedFarhadifarForce.cpp.
OutputForceParameters()
template<unsigned DIM> void PlanarPolarisedFarhadifarForce< DIM >::OutputForceParameters (out_stream & rParamsFile) virtual
Overridden OutputForceParameters() method.
Parameters
rParamsFile the file stream to which the parameters are output
Reimplemented from FarhadifarForce< DIM >.
Definition at line 116 of file PlanarPolarisedFarhadifarForce.cpp.
References FarhadifarForce< DIM >::OutputForceParameters().
serialize()
template<unsigned DIM> template<class Archive > void PlanarPolarisedFarhadifarForce< DIM >::serialize (Archive & archive, const unsigned int version) inline private
Boost Serialization method for archiving/checkpointing. Archives the object and its member variables.
Parameters
archive The boost archive.
version The current version of this class.
Definition at line 67 of file PlanarPolarisedFarhadifarForce.hpp.
References PlanarPolarisedFarhadifarForce< DIM >::mPlanarPolarisedLineTensionMultiplier.
SetPlanarPolarisedLineTensionMultiplier()
template<unsigned DIM> void PlanarPolarisedFarhadifarForce< DIM >::SetPlanarPolarisedLineTensionMultiplier (double planarPolarisedLineTensionMultiplier)
Set mPlanarPolarisedLineTensionMultiplier.
Parameters
planarPolarisedLineTensionMultiplier the new value of mPlanarPolarisedLineTensionMultiplier
Definition at line 57 of file PlanarPolarisedFarhadifarForce.cpp.
Friends And Related Symbol Documentation
boost::serialization::access
template<unsigned DIM> friend class boost::serialization::access friend
Definition at line 58 of file PlanarPolarisedFarhadifarForce.hpp.
TestForces
template<unsigned DIM> friend class TestForces friend
Definition at line 54 of file PlanarPolarisedFarhadifarForce.hpp.
Member Data Documentation
mPlanarPolarisedLineTensionMultiplier
template<unsigned DIM> double PlanarPolarisedFarhadifarForce< DIM >::mPlanarPolarisedLineTensionMultiplier protected
A scalar that multiplies the strength of the line tension term in the model for edges whose angle relative to the x axis are between 45 degrees and 135 degrees.
Definition at line 79 of file PlanarPolarisedFarhadifarForce.hpp.
Referenced by PlanarPolarisedFarhadifarForce< DIM >::serialize().
The documentation for this class was generated from the following files:
cell_based/src/population/forces/PlanarPolarisedFarhadifarForce.hpp
cell_based/src/population/forces/PlanarPolarisedFarhadifarForce.cpp