Chaste: ToroidalHoneycombMeshGenerator Class Reference
ToroidalHoneycombMeshGenerator Class Reference
#include <ToroidalHoneycombMeshGenerator.hpp>
Public Member Functions
ToroidalHoneycombMeshGenerator (unsigned numNodesAlongWidth, unsigned numNodesAlongDepth, double widthScaleFactor=1.0, double depthScaleFactor=1.0)
boost::shared_ptr< MutableMesh< 2, 2 > > GetMesh ()
boost::shared_ptr< Toroidal2dMesh > GetToroidalMesh ()
Public Member Functions inherited from HoneycombMeshGenerator
HoneycombMeshGenerator (unsigned numNodesAlongWidth, unsigned numNodesAlongLength, unsigned ghosts=0, double scaleFactor=1.0)
HoneycombMeshGenerator ()
virtual ~HoneycombMeshGenerator ()=default
std::vector< unsigned > GetCellLocationIndices ()
boost::shared_ptr< MutableMesh< 2, 2 > > GetCircularMesh (double radius)
double GetDomainDepth ()
double GetDomainWidth ()
Additional Inherited Members
Protected Attributes inherited from HoneycombMeshGenerator
boost::shared_ptr< MutableMesh< 2, 2 > > mpMesh
std::set< unsigned > mGhostNodeIndices
std::string mMeshFilename
double mDomainWidth
double mDomainDepth
double mBottom
double mTop
unsigned mNumCellWidth
unsigned mNumCellLength
Detailed Description
Honeycomb mesh generator that creates a 2D "Toroidal" mesh (one in which periodicity is imposed on the left and right boundaries) for use in cell-centre simulations.
NOTE: the user should delete the mesh after use to manage memory.
Definition at line 53 of file ToroidalHoneycombMeshGenerator.hpp.
Constructor & Destructor Documentation
ToroidalHoneycombMeshGenerator()
ToroidalHoneycombMeshGenerator::ToroidalHoneycombMeshGenerator (unsigned numNodesAlongWidth, unsigned numNodesAlongDepth, double widthScaleFactor = 1.0, double depthScaleFactor = 1.0)
Default constructor.
Parameters
numNodesAlongWidth The number of cells you want along the bottom of the domain
numNodesAlongDepth The number of cells you want sides of the domain
widthScaleFactor The scale factor for the width of the cells (defaults to 1.0)
depthScaleFactor The scale factor for the depth of the cells (defaults to 1.0)
Definition at line 45 of file ToroidalHoneycombMeshGenerator.cpp.
References OutputFileHandler::FindFile(), OutputFileHandler::GetOutputDirectoryFullPath(), PetscTools::IsSequential(), HoneycombMeshGenerator::mDomainDepth, HoneycombMeshGenerator::mDomainWidth, HoneycombMeshGenerator::mMeshFilename, HoneycombMeshGenerator::mNumCellLength, HoneycombMeshGenerator::mNumCellWidth, HoneycombMeshGenerator::mpMesh, OutputFileHandler::OpenOutputFile(), and FileFinder::Remove().
Member Function Documentation
GetMesh()
boost::shared_ptr< MutableMesh< 2, 2 > > ToroidalHoneycombMeshGenerator::GetMesh () virtual
Returns
a 2D honeycomb mesh
Reimplemented from HoneycombMeshGenerator.
Definition at line 212 of file ToroidalHoneycombMeshGenerator.cpp.
References EXCEPTION, and HoneycombMeshGenerator::mpMesh.
GetToroidalMesh()
boost::shared_ptr< Toroidal2dMesh > ToroidalHoneycombMeshGenerator::GetToroidalMesh ()
Returns
a 2D honeycomb mesh with periodic left/right and top/bottom boundaries
Definition at line 218 of file ToroidalHoneycombMeshGenerator.cpp.
References HoneycombMeshGenerator::mpMesh.
The documentation for this class was generated from the following files:
mesh/src/mutable/ToroidalHoneycombMeshGenerator.hpp
mesh/src/mutable/ToroidalHoneycombMeshGenerator.cpp