Chaste: Hdf5ToTxtConverter< ELEMENT_DIM, SPACE_DIM > Class Template Reference
Hdf5ToTxtConverter< ELEMENT_DIM, SPACE_DIM > Class Template Reference
#include <Hdf5ToTxtConverter.hpp>
Public Member Functions
Hdf5ToTxtConverter (const FileFinder &rInputDirectory, const std::string &rFileBaseName, AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM > *pMesh)
Public Member Functions inherited from AbstractHdf5Converter< ELEMENT_DIM, SPACE_DIM >
AbstractHdf5Converter (const FileFinder &rInputDirectory, const std::string &rFileBaseName, AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM > *pMesh, const std::string &rSubdirectoryName, unsigned precision)
void WriteInfoFile ()
~AbstractHdf5Converter ()
std::string GetSubdirectory ()
Additional Inherited Members
Protected Member Functions inherited from AbstractHdf5Converter< ELEMENT_DIM, SPACE_DIM >
bool MoveOntoNextDataset ()
Protected Attributes inherited from AbstractHdf5Converter< ELEMENT_DIM, SPACE_DIM >
const FileFinder & mrH5Folder
boost::shared_ptr< Hdf5DataReader > mpReader
unsigned mNumVariables
std::string mFileBaseName
std::vector< std::string > mDatasetNames
unsigned mOpenDatasetIndex
AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM > * mpMesh
OutputFileHandler * mpOutputFileHandler
std::string mRelativeSubdirectory
unsigned mPrecision
Detailed Description
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM>
class Hdf5ToTxtConverter< ELEMENT_DIM, SPACE_DIM >
This class converts from Hdf5 format to a .txt format that is readable by Matlab.
There is one output file per variable per timestep, giving the values of that variable at that time over each of the nodes.
Definition at line 49 of file Hdf5ToTxtConverter.hpp.
Constructor & Destructor Documentation
Hdf5ToTxtConverter()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> Hdf5ToTxtConverter< ELEMENT_DIM, SPACE_DIM >::Hdf5ToTxtConverter (const FileFinder & rInputDirectory, const std::string & rFileBaseName, AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM > * pMesh)
Constructor, which does the conversion and writes the .txt file.
Parameters
rInputDirectory The input directory, where the .h5 file has been written.
rFileBaseName The base name of the data file.
pMesh Pointer to the mesh.
Definition at line 47 of file Hdf5ToTxtConverter.cpp.
References PetscTools::AmMaster(), DistributedVectorFactory::CreateVec(), PetscTools::Destroy(), AbstractMesh< ELEMENT_DIM, SPACE_DIM >::GetDistributedVectorFactory(), AbstractMesh< ELEMENT_DIM, SPACE_DIM >::GetNumNodes(), ReplicatableVector::GetSize(), AbstractHdf5Converter< ELEMENT_DIM, SPACE_DIM >::mNumVariables, AbstractHdf5Converter< ELEMENT_DIM, SPACE_DIM >::mpReader, AbstractHdf5Converter< ELEMENT_DIM, SPACE_DIM >::mRelativeSubdirectory, OutputFileHandler::OpenOutputFile(), and ReplicatableVector::ReplicatePetscVector().
The documentation for this class was generated from the following files:
pde/src/postprocessing/Hdf5ToTxtConverter.hpp
pde/src/postprocessing/Hdf5ToTxtConverter.cpp