Chaste: CellProliferativePhasesCountWriter< ELEMENT_DIM, SPACE_DIM > Class Template Reference
CellProliferativePhasesCountWriter< ELEMENT_DIM, SPACE_DIM > Class Template Reference
#include <CellProliferativePhasesCountWriter.hpp>
Public Member Functions
CellProliferativePhasesCountWriter ()
void VisitAnyPopulation (AbstractCellPopulation< SPACE_DIM, SPACE_DIM > *pCellPopulation)
virtual void Visit (MeshBasedCellPopulation< ELEMENT_DIM, SPACE_DIM > *pCellPopulation)
virtual void Visit (CaBasedCellPopulation< SPACE_DIM > *pCellPopulation)
virtual void Visit (NodeBasedCellPopulation< SPACE_DIM > *pCellPopulation)
virtual void Visit (PottsBasedCellPopulation< SPACE_DIM > *pCellPopulation)
virtual void Visit (VertexBasedCellPopulation< SPACE_DIM > *pCellPopulation)
virtual void Visit (ImmersedBoundaryCellPopulation< SPACE_DIM > *pCellPopulation)
Public Member Functions inherited from AbstractCellPopulationCountWriter< ELEMENT_DIM, SPACE_DIM >
AbstractCellPopulationCountWriter (const std::string &rFileName)
virtual void WriteHeader (AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM > *pCellPopulation)
Public Member Functions inherited from AbstractCellBasedWriter< ELEMENT_DIM, SPACE_DIM >
AbstractCellBasedWriter (const std::string &rFileName)
virtual ~AbstractCellBasedWriter ()
void CloseFile ()
virtual void OpenOutputFile (OutputFileHandler &rOutputFileHandler)
void OpenOutputFileForAppend (OutputFileHandler &rOutputFileHandler)
virtual void WriteTimeStamp ()
virtual void WriteNewline ()
void SetFileName (std::string fileName)
std::string GetFileName ()
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Friends
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from AbstractCellBasedWriter< ELEMENT_DIM, SPACE_DIM >
std::string mFileName
out_stream mpOutStream
Detailed Description
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM>
class CellProliferativePhasesCountWriter< ELEMENT_DIM, SPACE_DIM >
A class written using the visitor pattern for writing the number of cells in each proliferative phase to file.
The output file is called cellcyclephases.dat by default.
Definition at line 49 of file CellProliferativePhasesCountWriter.hpp.
Constructor & Destructor Documentation
CellProliferativePhasesCountWriter()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> CellProliferativePhasesCountWriter< ELEMENT_DIM, SPACE_DIM >::CellProliferativePhasesCountWriter ()
Default constructor.
Definition at line 46 of file CellProliferativePhasesCountWriter.cpp.
Member Function Documentation
serialize()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> template<class Archive > void CellProliferativePhasesCountWriter< ELEMENT_DIM, SPACE_DIM >::serialize (Archive & archive, const unsigned int version) inline private
Serialize the object and its member variables.
Parameters
archive the archive
version the current version of this class
Definition at line 61 of file CellProliferativePhasesCountWriter.hpp.
Visit() [1/6]
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void CellProliferativePhasesCountWriter< ELEMENT_DIM, SPACE_DIM >::Visit (CaBasedCellPopulation< SPACE_DIM > * pCellPopulation) virtual
Visit the population and write the number of cells in the population that have each proliferative phase.
Outputs a line of tab-separated values of the form: [num G0 phase] [num G1 phase] [num S phase] [num G2 phase] [num M phase]
where [num G0 phase] denotes the number of cells in the population that are in G0 phase, and so on. These counts are computed through the cell population method GetCellCyclePhaseCount().
This line is appended to the output written by AbstractCellBasedWriter, which is a single value [present simulation time], followed by a tab.
Parameters
pCellPopulation a pointer to the CaBasedCellPopulation to visit.
Implements AbstractCellPopulationCountWriter< ELEMENT_DIM, SPACE_DIM >.
Definition at line 80 of file CellProliferativePhasesCountWriter.cpp.
Visit() [2/6]
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void CellProliferativePhasesCountWriter< ELEMENT_DIM, SPACE_DIM >::Visit (ImmersedBoundaryCellPopulation< SPACE_DIM > * pCellPopulation) virtual
Visit the population and write the data.
Just passes through to VisitAnyPopulation
Parameters
pCellPopulation a pointer to the ImmersedBoundaryCellPopulation to visit.
Implements AbstractCellPopulationCountWriter< ELEMENT_DIM, SPACE_DIM >.
Definition at line 104 of file CellProliferativePhasesCountWriter.cpp.
Visit() [3/6]
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void CellProliferativePhasesCountWriter< ELEMENT_DIM, SPACE_DIM >::Visit (MeshBasedCellPopulation< ELEMENT_DIM, SPACE_DIM > * pCellPopulation) virtual
Visit the population and write the number of cells in the population that have each proliferative phase.
Outputs a line of tab-separated values of the form: [num G0 phase] [num G1 phase] [num S phase] [num G2 phase] [num M phase]
where [num G0 phase] denotes the number of cells in the population that are in G0 phase, and so on. These counts are computed through the cell population method GetCellCyclePhaseCount().
This line is appended to the output written by AbstractCellBasedWriter, which is a single value [present simulation time], followed by a tab.
Parameters
pCellPopulation a pointer to the MeshBasedCellPopulation to visit.
Implements AbstractCellPopulationCountWriter< ELEMENT_DIM, SPACE_DIM >.
Definition at line 66 of file CellProliferativePhasesCountWriter.cpp.
References PetscTools::AmMaster(), and AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::GetCellCyclePhaseCount().
Visit() [4/6]
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void CellProliferativePhasesCountWriter< ELEMENT_DIM, SPACE_DIM >::Visit (NodeBasedCellPopulation< SPACE_DIM > * pCellPopulation) virtual
Visit the population and write the number of cells in the population that have each proliferative phase.
Outputs a line of tab-separated values of the form: [num G0 phase] [num G1 phase] [num S phase] [num G2 phase] [num M phase]
where [num G0 phase] denotes the number of cells in the population that are in G0 phase, and so on. These counts are computed through the cell population method GetCellCyclePhaseCount().
This line is appended to the output written by AbstractCellBasedWriter, which is a single value [present simulation time], followed by a tab.
Parameters
pCellPopulation a pointer to the NodeBasedCellPopulation to visit.
Implements AbstractCellPopulationCountWriter< ELEMENT_DIM, SPACE_DIM >.
Definition at line 86 of file CellProliferativePhasesCountWriter.cpp.
Visit() [5/6]
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void CellProliferativePhasesCountWriter< ELEMENT_DIM, SPACE_DIM >::Visit (PottsBasedCellPopulation< SPACE_DIM > * pCellPopulation) virtual
Visit the population and write the number of cells in the population that have each proliferative phase.
Outputs a line of tab-separated values of the form: [num G0 phase] [num G1 phase] [num S phase] [num G2 phase] [num M phase]
where [num G0 phase] denotes the number of cells in the population that are in G0 phase, and so on. These counts are computed through the cell population method GetCellCyclePhaseCount().
This line is appended to the output written by AbstractCellBasedWriter, which is a single value [present simulation time], followed by a tab.
Parameters
pCellPopulation a pointer to the PottsBasedCellPopulation to visit.
Implements AbstractCellPopulationCountWriter< ELEMENT_DIM, SPACE_DIM >.
Definition at line 92 of file CellProliferativePhasesCountWriter.cpp.
Visit() [6/6]
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void CellProliferativePhasesCountWriter< ELEMENT_DIM, SPACE_DIM >::Visit (VertexBasedCellPopulation< SPACE_DIM > * pCellPopulation) virtual
Visit the population and write the number of cells in the population that have each proliferative phase.
Outputs a line of tab-separated values of the form: [num G0 phase] [num G1 phase] [num S phase] [num G2 phase] [num M phase]
where [num G0 phase] denotes the number of cells in the population that are in G0 phase, and so on. These counts are computed through the cell population method GetCellCyclePhaseCount().
This line is appended to the output written by AbstractCellBasedWriter, which is a single value [present simulation time], followed by a tab.
Parameters
pCellPopulation a pointer to the VertexBasedCellPopulation to visit.
Implements AbstractCellPopulationCountWriter< ELEMENT_DIM, SPACE_DIM >.
Definition at line 98 of file CellProliferativePhasesCountWriter.cpp.
VisitAnyPopulation()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void CellProliferativePhasesCountWriter< ELEMENT_DIM, SPACE_DIM >::VisitAnyPopulation (AbstractCellPopulation< SPACE_DIM, SPACE_DIM > * pCellPopulation)
Visit the population and write the number of cells in the population that have each proliferative phase.
Outputs a line of tab-separated values of the form: [num G0 phase] [num G1 phase] [num S phase] [num G2 phase] [num M phase]
where [num G0 phase] denotes the number of cells in the population that are in G0 phase, and so on. These counts are computed through the cell population method GetCellCyclePhaseCount().
This line is appended to the output written by AbstractCellBasedWriter, which is a single value [present simulation time], followed by a tab.
Parameters
pCellPopulation the population to write.
Definition at line 52 of file CellProliferativePhasesCountWriter.cpp.
References PetscTools::AmMaster(), and AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::GetCellCyclePhaseCount().
Friends And Related Symbol Documentation
boost::serialization::access
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> friend class boost::serialization::access friend
Needed for serialization.
Definition at line 53 of file CellProliferativePhasesCountWriter.hpp.
The documentation for this class was generated from the following files:
cell_based/src/writers/population_count_writers/CellProliferativePhasesCountWriter.hpp
cell_based/src/writers/population_count_writers/CellProliferativePhasesCountWriter.cpp