Chaste: BidomainWithBathAssembler< ELEMENT_DIM, SPACE_DIM > Class Template Reference
BidomainWithBathAssembler< ELEMENT_DIM, SPACE_DIM > Class Template Reference
#include <BidomainWithBathAssembler.hpp>
Public Member Functions
BidomainWithBathAssembler (AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM > *pMesh, BidomainTissue< SPACE_DIM > *pTissue)
virtual ~BidomainWithBathAssembler ()
Public Member Functions inherited from BidomainAssembler< ELEMENT_DIM, SPACE_DIM >
BidomainAssembler (AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM > *pMesh, BidomainTissue< SPACE_DIM > *pTissue)
virtual ~BidomainAssembler ()
Public Member Functions inherited from AbstractCardiacFeVolumeIntegralAssembler< ELEMENT_DIM, SPACE_DIM, 2, false, true, CARDIAC >
AbstractCardiacFeVolumeIntegralAssembler (AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM > *pMesh, AbstractCardiacTissue< ELEMENT_DIM, SPACE_DIM > *pTissue)
Public Member Functions inherited from AbstractFeVolumeIntegralAssembler< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM, CAN_ASSEMBLE_VECTOR, CAN_ASSEMBLE_MATRIX, INTERPOLATION_LEVEL >
AbstractFeVolumeIntegralAssembler (AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM > *pMesh)
virtual ~AbstractFeVolumeIntegralAssembler ()
Public Member Functions inherited from AbstractFeAssemblerCommon< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM, CAN_ASSEMBLE_VECTOR, CAN_ASSEMBLE_MATRIX, INTERPOLATION_LEVEL >
AbstractFeAssemblerCommon ()
void SetCurrentSolution (Vec currentSolution)
virtual ~AbstractFeAssemblerCommon ()
Public Member Functions inherited from AbstractFeAssemblerInterface< CAN_ASSEMBLE_VECTOR, CAN_ASSEMBLE_MATRIX >
AbstractFeAssemblerInterface ()
void SetMatrixToAssemble (Mat &rMatToAssemble, bool zeroMatrixBeforeAssembly=true)
void SetVectorToAssemble (Vec &rVecToAssemble, bool zeroVectorBeforeAssembly)
void Assemble ()
void AssembleMatrix ()
void AssembleVector ()
virtual ~AbstractFeAssemblerInterface ()
Protected Member Functions
virtual c_matrix< double, 2 *(ELEMENT_DIM+1), 2 *(ELEMENT_DIM+1)> ComputeMatrixTerm (c_vector< double, ELEMENT_DIM+1 > &rPhi, c_matrix< double, SPACE_DIM, ELEMENT_DIM+1 > &rGradPhi, ChastePoint< SPACE_DIM > &rX, c_vector< double, 2 > &rU, c_matrix< double, 2, SPACE_DIM > &rGradU, Element< ELEMENT_DIM, SPACE_DIM > *pElement)
Protected Member Functions inherited from AbstractFeVolumeIntegralAssembler< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM, CAN_ASSEMBLE_VECTOR, CAN_ASSEMBLE_MATRIX, INTERPOLATION_LEVEL >
void ComputeTransformedBasisFunctionDerivatives (const ChastePoint< ELEMENT_DIM > &rPoint, const c_matrix< double, ELEMENT_DIM, SPACE_DIM > &rInverseJacobian, c_matrix< double, SPACE_DIM, ELEMENT_DIM+1 > &rReturnValue)
void DoAssemble ()
virtual c_matrix< double, PROBLEM_DIM *(ELEMENT_DIM+1), PROBLEM_DIM *(ELEMENT_DIM+1)> ComputeMatrixTerm (c_vector< double, ELEMENT_DIM+1 > &rPhi, c_matrix< double, SPACE_DIM, ELEMENT_DIM+1 > &rGradPhi, ChastePoint< SPACE_DIM > &rX, c_vector< double, PROBLEM_DIM > &rU, c_matrix< double, PROBLEM_DIM, SPACE_DIM > &rGradU, Element< ELEMENT_DIM, SPACE_DIM > *pElement)
virtual c_vector< double, PROBLEM_DIM *(ELEMENT_DIM+1)> ComputeVectorTerm (c_vector< double, ELEMENT_DIM+1 > &rPhi, c_matrix< double, SPACE_DIM, ELEMENT_DIM+1 > &rGradPhi, ChastePoint< SPACE_DIM > &rX, c_vector< double, PROBLEM_DIM > &rU, c_matrix< double, PROBLEM_DIM, SPACE_DIM > &rGradU, Element< ELEMENT_DIM, SPACE_DIM > *pElement)
virtual void AssembleOnElement (Element< ELEMENT_DIM, SPACE_DIM > &rElement, c_matrix< double, PROBLEM_DIM *(ELEMENT_DIM+1), PROBLEM_DIM *(ELEMENT_DIM+1) > &rAElem, c_vector< double, PROBLEM_DIM *(ELEMENT_DIM+1)> &rBElem)
virtual bool ElementAssemblyCriterion (Element< ELEMENT_DIM, SPACE_DIM > &rElement)
Protected Member Functions inherited from AbstractFeAssemblerCommon< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM, CAN_ASSEMBLE_VECTOR, CAN_ASSEMBLE_MATRIX, INTERPOLATION_LEVEL >
virtual double GetCurrentSolutionOrGuessValue (unsigned nodeIndex, unsigned indexOfUnknown)
virtual void ResetInterpolatedQuantities ()
virtual void IncrementInterpolatedQuantities (double phiI, const Node< SPACE_DIM > *pNode)
virtual void IncrementInterpolatedGradientQuantities (const c_matrix< double, SPACE_DIM, ELEMENT_DIM+1 > &rGradPhi, unsigned phiIndex, const Node< SPACE_DIM > *pNode)
Additional Inherited Members
Protected Types inherited from AbstractFeVolumeIntegralAssembler< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM, CAN_ASSEMBLE_VECTOR, CAN_ASSEMBLE_MATRIX, INTERPOLATION_LEVEL >
typedef LinearBasisFunction< ELEMENT_DIM > BasisFunction
Protected Attributes inherited from AbstractCardiacFeVolumeIntegralAssembler< ELEMENT_DIM, SPACE_DIM, 2, false, true, CARDIAC >
AbstractCardiacTissue< ELEMENT_DIM, SPACE_DIM > * mpCardiacTissue
HeartConfig * mpConfig
Protected Attributes inherited from AbstractFeVolumeIntegralAssembler< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM, CAN_ASSEMBLE_VECTOR, CAN_ASSEMBLE_MATRIX, INTERPOLATION_LEVEL >
AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM > * mpMesh
GaussianQuadratureRule< ELEMENT_DIM > * mpQuadRule
Protected Attributes inherited from AbstractFeAssemblerCommon< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM, CAN_ASSEMBLE_VECTOR, CAN_ASSEMBLE_MATRIX, INTERPOLATION_LEVEL >
ReplicatableVector mCurrentSolutionOrGuessReplicated
Protected Attributes inherited from AbstractFeAssemblerInterface< CAN_ASSEMBLE_VECTOR, CAN_ASSEMBLE_MATRIX >
Vec mVectorToAssemble
Mat mMatrixToAssemble
bool mAssembleMatrix
bool mAssembleVector
bool mZeroMatrixBeforeAssembly
bool mZeroVectorBeforeAssembly
PetscInt mOwnershipRangeLo
PetscInt mOwnershipRangeHi
Detailed Description
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM>
class BidomainWithBathAssembler< ELEMENT_DIM, SPACE_DIM >
Assembler for assembling the LHS matrix system solved in bidomain problems with a perfusing bath. See FEM implementations document for the exact definition of this.
Definition at line 50 of file BidomainWithBathAssembler.hpp.
Constructor & Destructor Documentation
BidomainWithBathAssembler()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> BidomainWithBathAssembler< ELEMENT_DIM, SPACE_DIM >::BidomainWithBathAssembler (AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM > * pMesh, BidomainTissue< SPACE_DIM > * pTissue) inline
Constructor.
Parameters
pMesh pointer to the mesh
pTissue pointer to the tissue
Definition at line 80 of file BidomainWithBathAssembler.hpp.
~BidomainWithBathAssembler()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> virtual BidomainWithBathAssembler< ELEMENT_DIM, SPACE_DIM >::~BidomainWithBathAssembler () inline virtual
Destructor.
Definition at line 89 of file BidomainWithBathAssembler.hpp.
Member Function Documentation
ComputeMatrixTerm()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> c_matrix< double, 2 *(ELEMENT_DIM+1), 2 *(ELEMENT_DIM+1)> BidomainWithBathAssembler< ELEMENT_DIM, SPACE_DIM >::ComputeMatrixTerm (c_vector< double, ELEMENT_DIM+1 > & rPhi, c_matrix< double, SPACE_DIM, ELEMENT_DIM+1 > & rGradPhi, ChastePoint< SPACE_DIM > & rX, c_vector< double, 2 > & rU, c_matrix< double, 2, SPACE_DIM > & rGradU, Element< ELEMENT_DIM, SPACE_DIM > * pElement) protected virtual
Overloaded ComputeMatrixTerm() - calls the base class version for tissue elements.
Parameters
rPhi The basis functions, rPhi(i) = phi_i, i=1..numBases
rGradPhi Basis gradients, rGradPhi(i,j) = d(phi_j)/d(X_i)
rX The point in space
rU The unknown as a vector, u(i) = u_i
rGradU The gradient of the unknown as a matrix, rGradU(i,j) = d(u_i)/d(X_j)
pElement Pointer to the element
Returns
stencil matrix
Reimplemented from BidomainAssembler< ELEMENT_DIM, SPACE_DIM >.
Definition at line 41 of file BidomainWithBathAssembler.cpp.
References BidomainAssembler< ELEMENT_DIM, SPACE_DIM >::ComputeMatrixTerm(), HeartConfig::GetBathConductivity(), AbstractElement< ELEMENT_DIM, SPACE_DIM >::GetUnsignedAttribute(), HeartConfig::Instance(), and HeartRegionCode::IsRegionBath().
The documentation for this class was generated from the following files:
heart/src/solver/electrics/bidomain/BidomainWithBathAssembler.hpp
heart/src/solver/electrics/bidomain/BidomainWithBathAssembler.cpp