Chaste: AbstractSimplePhaseBasedCellCycleModel Class Reference
AbstractSimplePhaseBasedCellCycleModel Class Reference
#include <AbstractSimplePhaseBasedCellCycleModel.hpp>
Public Member Functions
AbstractSimplePhaseBasedCellCycleModel ()
virtual ~AbstractSimplePhaseBasedCellCycleModel ()
virtual void ResetForDivision ()
virtual void UpdateCellCyclePhase ()
void InitialiseDaughterCell ()
virtual void Initialise ()
virtual void OutputCellCycleModelParameters (out_stream &rParamsFile)
Public Member Functions inherited from AbstractPhaseBasedCellCycleModel
AbstractPhaseBasedCellCycleModel ()
virtual ~AbstractPhaseBasedCellCycleModel ()
virtual bool ReadyToDivide ()
CellCyclePhase GetCurrentCellCyclePhase () const
virtual double GetG1Duration () const
double GetStemCellG1Duration () const
double GetTransitCellG1Duration () const
double GetSG2MDuration () const
virtual double GetSDuration () const
virtual double GetG2Duration () const
virtual double GetMDuration () const
virtual void SetStemCellG1Duration (double stemCellG1Duration)
virtual void SetTransitCellG1Duration (double transitCellG1Duration)
void SetSDuration (double sDuration)
void SetG2Duration (double g2Duration)
void SetMDuration (double mDuration)
virtual double GetAverageTransitCellCycleTime ()
virtual double GetAverageStemCellCycleTime ()
double GetMinimumGapDuration () const
void SetMinimumGapDuration (double minimumGapDuration)
Public Member Functions inherited from AbstractCellCycleModel
AbstractCellCycleModel ()
virtual ~AbstractCellCycleModel ()
void SetCell (CellPtr pCell)
CellPtr GetCell ()
virtual void SetBirthTime (double birthTime)
void SetDimension (unsigned dimension)
unsigned GetDimension () const
double GetBirthTime () const
double GetAge ()
virtual AbstractCellCycleModel * CreateCellCycleModel ()=0
virtual bool CanCellTerminallyDifferentiate ()
void OutputCellCycleModelInfo (out_stream &rParamsFile)
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Protected Member Functions
virtual void SetG1Duration ()
AbstractSimplePhaseBasedCellCycleModel (const AbstractSimplePhaseBasedCellCycleModel &rModel)
Protected Member Functions inherited from AbstractPhaseBasedCellCycleModel
AbstractPhaseBasedCellCycleModel (const AbstractPhaseBasedCellCycleModel &rModel)
Protected Member Functions inherited from AbstractCellCycleModel
AbstractCellCycleModel (const AbstractCellCycleModel &rModel)
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Friends
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from AbstractPhaseBasedCellCycleModel
CellCyclePhase mCurrentCellCyclePhase
double mG1Duration
double mMinimumGapDuration
double mStemCellG1Duration
double mTransitCellG1Duration
double mSDuration
double mG2Duration
double mMDuration
Protected Attributes inherited from AbstractCellCycleModel
CellPtr mpCell
double mBirthTime
bool mReadyToDivide
unsigned mDimension
Detailed Description
This class contains all the functionality shared by 'simple' cell-cycle models, where the duration of each cell cycle phase is determined when the cell-cycle model is created. Note that whether or not the cell should actually divide may still depend on further conditions in subclasses; for example, the cell may only divide if the local concentration of a signalling molecule is sufficiently high/
This class of cell-cycle models is distinct from 'ODE-based' cell-cycle models, where the duration of one or more cell cycle phases are evaluated 'on the fly' as the cell ages, according to a system of ordinary differential equations (ODEs) governing (for example) the concentrations of key intracellular proteins.
Definition at line 57 of file AbstractSimplePhaseBasedCellCycleModel.hpp.
Constructor & Destructor Documentation
AbstractSimplePhaseBasedCellCycleModel() [1/2]
AbstractSimplePhaseBasedCellCycleModel::AbstractSimplePhaseBasedCellCycleModel (const AbstractSimplePhaseBasedCellCycleModel & rModel) protected
Protected copy-constructor for use by CreateCellCycleModel. The only way for external code to create a copy of a cell cycle model is by calling that method, to ensure that a model of the correct subclass is created. This copy-constructor helps subclasses to ensure that all member variables are correctly copied when this happens.
This method is called by child classes to set member variables for a daughter cell upon cell division. Note that the parent cell cycle model will have had ResetForDivision() called just before CreateCellCycleModel() is called, so performing an exact copy of the parent is suitable behaviour. Any daughter-cell-specific initialisation can be done in InitialiseDaughterCell().
Parameters
rModel the cell cycle model to copy.
Definition at line 49 of file AbstractSimplePhaseBasedCellCycleModel.cpp.
AbstractSimplePhaseBasedCellCycleModel() [2/2]
AbstractSimplePhaseBasedCellCycleModel::AbstractSimplePhaseBasedCellCycleModel ()
Default constructor - creates an AbstractSimplePhaseBasedCellCycleModel.
Definition at line 41 of file AbstractSimplePhaseBasedCellCycleModel.cpp.
~AbstractSimplePhaseBasedCellCycleModel()
AbstractSimplePhaseBasedCellCycleModel::~AbstractSimplePhaseBasedCellCycleModel () virtual
Destructor.
Definition at line 45 of file AbstractSimplePhaseBasedCellCycleModel.cpp.
Member Function Documentation
Initialise()
void AbstractSimplePhaseBasedCellCycleModel::Initialise () virtual
See AbstractPhaseBasedCellCycleModel::Initialise()
Reimplemented from AbstractCellCycleModel.
Reimplemented in StochasticOxygenBasedCellCycleModel, and SingleOdeWntCellCycleModel.
Definition at line 66 of file AbstractSimplePhaseBasedCellCycleModel.cpp.
References SetG1Duration().
Referenced by StochasticOxygenBasedCellCycleModel::Initialise().
InitialiseDaughterCell()
void AbstractSimplePhaseBasedCellCycleModel::InitialiseDaughterCell () virtual
Set the new cell's G1 duration once it has been created after division. The duration will be based on cell type.
Reimplemented from AbstractCellCycleModel.
Reimplemented in StochasticOxygenBasedCellCycleModel, and SimpleWntCellCycleModel.
Definition at line 71 of file AbstractSimplePhaseBasedCellCycleModel.cpp.
References AbstractCellCycleModel::InitialiseDaughterCell(), and SetG1Duration().
Referenced by AbstractSimpleGenerationalCellCycleModel::InitialiseDaughterCell(), and SimpleWntCellCycleModel::InitialiseDaughterCell().
OutputCellCycleModelParameters()
void AbstractSimplePhaseBasedCellCycleModel::OutputCellCycleModelParameters (out_stream & rParamsFile) virtual
Overridden OutputCellCycleModelParameters() method.
Parameters
rParamsFile the file stream to which the parameters are output
Implements AbstractPhaseBasedCellCycleModel.
Reimplemented in AbstractSimpleGenerationalCellCycleModel, ContactInhibitionCellCycleModel, ExponentialG1GenerationalCellCycleModel, FixedG1GenerationalCellCycleModel, FixedSequenceCellCycleModel, GammaG1CellCycleModel, SimpleOxygenBasedCellCycleModel, StochasticOxygenBasedCellCycleModel, UniformG1GenerationalCellCycleModel, SimpleWntCellCycleModel, and SingleOdeWntCellCycleModel.
Definition at line 132 of file AbstractSimplePhaseBasedCellCycleModel.cpp.
References AbstractPhaseBasedCellCycleModel::OutputCellCycleModelParameters().
Referenced by AbstractSimpleGenerationalCellCycleModel::OutputCellCycleModelParameters(), ContactInhibitionCellCycleModel::OutputCellCycleModelParameters(), GammaG1CellCycleModel::OutputCellCycleModelParameters(), SimpleOxygenBasedCellCycleModel::OutputCellCycleModelParameters(), and SimpleWntCellCycleModel::OutputCellCycleModelParameters().
ResetForDivision()
void AbstractSimplePhaseBasedCellCycleModel::ResetForDivision () virtual
See AbstractPhaseBasedCellCycleModel::ResetForDivision()
Reimplemented from AbstractPhaseBasedCellCycleModel.
Reimplemented in AbstractSimpleGenerationalCellCycleModel, and StochasticOxygenBasedCellCycleModel.
Definition at line 99 of file AbstractSimplePhaseBasedCellCycleModel.cpp.
References AbstractPhaseBasedCellCycleModel::ResetForDivision(), and SetG1Duration().
Referenced by AbstractSimpleGenerationalCellCycleModel::ResetForDivision().
serialize()
template<class Archive > void AbstractSimplePhaseBasedCellCycleModel::serialize (Archive & archive, const unsigned int version) inline private
Archive the cell-cycle model.
Parameters
archive the archive
version the current version of this class
Definition at line 70 of file AbstractSimplePhaseBasedCellCycleModel.hpp.
SetG1Duration()
void AbstractSimplePhaseBasedCellCycleModel::SetG1Duration () protected virtual
Subclasses can override this function if they wish, this just allocates the default values for each of the different cell types' G1 durations as defined in AbstractPhaseBasedCellCycleModel.
Reimplemented in ExponentialG1GenerationalCellCycleModel, FixedSequenceCellCycleModel, GammaG1CellCycleModel, UniformG1GenerationalCellCycleModel, and SimpleWntCellCycleModel.
Definition at line 77 of file AbstractSimplePhaseBasedCellCycleModel.cpp.
References AbstractPhaseBasedCellCycleModel::GetStemCellG1Duration(), AbstractPhaseBasedCellCycleModel::GetTransitCellG1Duration(), AbstractPhaseBasedCellCycleModel::mG1Duration, AbstractCellCycleModel::mpCell, and NEVER_REACHED.
Referenced by Initialise(), InitialiseDaughterCell(), and ResetForDivision().
UpdateCellCyclePhase()
void AbstractSimplePhaseBasedCellCycleModel::UpdateCellCyclePhase () virtual
Default UpdateCellCyclePhase() method for a simple cell-cycle model.
Can be overridden if they should do something more subtle.
Implements AbstractPhaseBasedCellCycleModel.
Reimplemented in ContactInhibitionCellCycleModel, SimpleOxygenBasedCellCycleModel, SimpleWntCellCycleModel, and SingleOdeWntCellCycleModel.
Definition at line 105 of file AbstractSimplePhaseBasedCellCycleModel.cpp.
References AbstractCellCycleModel::GetAge(), AbstractPhaseBasedCellCycleModel::GetG2Duration(), AbstractPhaseBasedCellCycleModel::GetMDuration(), AbstractPhaseBasedCellCycleModel::GetSDuration(), AbstractPhaseBasedCellCycleModel::mCurrentCellCyclePhase, AbstractPhaseBasedCellCycleModel::mG1Duration, and AbstractCellCycleModel::mpCell.
Referenced by SimpleOxygenBasedCellCycleModel::UpdateCellCyclePhase(), SimpleWntCellCycleModel::UpdateCellCyclePhase(), and SingleOdeWntCellCycleModel::UpdateCellCyclePhase().
Friends And Related Symbol Documentation
boost::serialization::access
friend class boost::serialization::access friend
Needed for serialization.
Definition at line 62 of file AbstractSimplePhaseBasedCellCycleModel.hpp.
The documentation for this class was generated from the following files:
cell_based/src/cell/cycle/AbstractSimplePhaseBasedCellCycleModel.hpp
cell_based/src/cell/cycle/AbstractSimplePhaseBasedCellCycleModel.cpp