Chaste: ImmersedBoundaryHoneycombMeshGenerator Class Reference
ImmersedBoundaryHoneycombMeshGenerator Class Reference
#include <ImmersedBoundaryHoneycombMeshGenerator.hpp>
Public Member Functions
ImmersedBoundaryHoneycombMeshGenerator (unsigned numElementsX, unsigned numElementsY, unsigned numNodesPerEdge, double proportionalGap, double padding)
ImmersedBoundaryHoneycombMeshGenerator ()
virtual ~ImmersedBoundaryHoneycombMeshGenerator ()
ImmersedBoundaryMesh< 2, 2 > * GetMesh ()
std::vector< c_vector< double, 2 > > GetUnitHexagon (unsigned numPtsPerSide)
Private Attributes
ImmersedBoundaryMesh< 2, 2 > * mpMesh
Detailed Description
Creates a honeycomb of immersed boundary elements.
NOTE: the user should delete the mesh after use to manage memory.
Definition at line 49 of file ImmersedBoundaryHoneycombMeshGenerator.hpp.
Constructor & Destructor Documentation
ImmersedBoundaryHoneycombMeshGenerator() [1/2]
ImmersedBoundaryHoneycombMeshGenerator::ImmersedBoundaryHoneycombMeshGenerator (unsigned numElementsX, unsigned numElementsY, unsigned numNodesPerEdge, double proportionalGap, double padding)
Default constructor.
Parameters
numElementsX the number of cells from left to right along the domain
numElementsY the number of cells from top to bottom up the domain
numNodesPerEdge the number of nodes per cell (defaults to 100)
proportionalGap the proportion of space between elements
padding the minimum padding around the edge of the generated mesh
Definition at line 39 of file ImmersedBoundaryHoneycombMeshGenerator.cpp.
References GetUnitHexagon(), mpMesh, and ImmersedBoundaryElement< ELEMENT_DIM, SPACE_DIM >::SetIsBoundaryElement().
ImmersedBoundaryHoneycombMeshGenerator() [2/2]
ImmersedBoundaryHoneycombMeshGenerator::ImmersedBoundaryHoneycombMeshGenerator () inline
Null constructor for derived classes to call.
Definition at line 77 of file ImmersedBoundaryHoneycombMeshGenerator.hpp.
~ImmersedBoundaryHoneycombMeshGenerator()
ImmersedBoundaryHoneycombMeshGenerator::~ImmersedBoundaryHoneycombMeshGenerator () virtual
Destructor.
Deletes the mesh object and pointer.
Definition at line 136 of file ImmersedBoundaryHoneycombMeshGenerator.cpp.
References mpMesh.
Member Function Documentation
GetMesh()
ImmersedBoundaryMesh< 2, 2 > * ImmersedBoundaryHoneycombMeshGenerator::GetMesh ()
Returns
a 2D honeycomb mesh based on a 2D plane
Definition at line 141 of file ImmersedBoundaryHoneycombMeshGenerator.cpp.
References mpMesh.
GetUnitHexagon()
std::vector< c_vector< double, 2 > > ImmersedBoundaryHoneycombMeshGenerator::GetUnitHexagon (unsigned numPtsPerSide)
Helper method for the constructor that calculates locations around a unit hexagon centred at the origin.
Parameters
numPtsPerSide the number of locations along each of the six sides
Returns
a vector of locations around the unit hexagon
Definition at line 146 of file ImmersedBoundaryHoneycombMeshGenerator.cpp.
Referenced by ImmersedBoundaryHoneycombMeshGenerator().
Member Data Documentation
mpMesh
ImmersedBoundaryMesh<2,2>* ImmersedBoundaryHoneycombMeshGenerator::mpMesh private
A pointer to the mesh this class creates
Definition at line 55 of file ImmersedBoundaryHoneycombMeshGenerator.hpp.
Referenced by ImmersedBoundaryHoneycombMeshGenerator(), ~ImmersedBoundaryHoneycombMeshGenerator(), and GetMesh().
The documentation for this class was generated from the following files:
mesh/src/immersed_boundary/ImmersedBoundaryHoneycombMeshGenerator.hpp
mesh/src/immersed_boundary/ImmersedBoundaryHoneycombMeshGenerator.cpp