Chaste: SimpleWntCellCycleModel Class Reference
SimpleWntCellCycleModel Class Reference
#include <SimpleWntCellCycleModel.hpp>
Public Member Functions
SimpleWntCellCycleModel ()
virtual void UpdateCellCyclePhase ()
virtual void InitialiseDaughterCell ()
virtual AbstractCellCycleModel * CreateCellCycleModel ()
bool GetUseCellProliferativeTypeDependentG1Duration () const
void SetUseCellProliferativeTypeDependentG1Duration (bool useCellProliferativeTypeDependentG1Duration=true)
virtual bool CanCellTerminallyDifferentiate ()
double GetWntStemThreshold () const
void SetWntStemThreshold (double wntStemThreshold)
double GetWntTransitThreshold () const
void SetWntTransitThreshold (double wntTransitThreshold)
double GetWntLabelledThreshold () const
void SetWntLabelledThreshold (double wntLabelledThreshold)
virtual void OutputCellCycleModelParameters (out_stream &rParamsFile)
Public Member Functions inherited from AbstractSimplePhaseBasedCellCycleModel
AbstractSimplePhaseBasedCellCycleModel ()
virtual ~AbstractSimplePhaseBasedCellCycleModel ()
virtual void ResetForDivision ()
virtual void Initialise ()
Public Member Functions inherited from AbstractPhaseBasedCellCycleModel
AbstractPhaseBasedCellCycleModel ()
virtual ~AbstractPhaseBasedCellCycleModel ()
virtual bool ReadyToDivide ()
CellCyclePhase GetCurrentCellCyclePhase () const
virtual double GetG1Duration () const
double GetStemCellG1Duration () const
double GetTransitCellG1Duration () const
double GetSG2MDuration () const
virtual double GetSDuration () const
virtual double GetG2Duration () const
virtual double GetMDuration () const
virtual void SetStemCellG1Duration (double stemCellG1Duration)
virtual void SetTransitCellG1Duration (double transitCellG1Duration)
void SetSDuration (double sDuration)
void SetG2Duration (double g2Duration)
void SetMDuration (double mDuration)
virtual double GetAverageTransitCellCycleTime ()
virtual double GetAverageStemCellCycleTime ()
double GetMinimumGapDuration () const
void SetMinimumGapDuration (double minimumGapDuration)
Public Member Functions inherited from AbstractCellCycleModel
AbstractCellCycleModel ()
virtual ~AbstractCellCycleModel ()
void SetCell (CellPtr pCell)
CellPtr GetCell ()
virtual void SetBirthTime (double birthTime)
void SetDimension (unsigned dimension)
unsigned GetDimension () const
double GetBirthTime () const
double GetAge ()
void OutputCellCycleModelInfo (out_stream &rParamsFile)
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Protected Member Functions
double GetWntLevel () const
WntConcentrationType GetWntType ()
void SetG1Duration ()
SimpleWntCellCycleModel (const SimpleWntCellCycleModel &rModel)
Protected Member Functions inherited from AbstractSimplePhaseBasedCellCycleModel
AbstractSimplePhaseBasedCellCycleModel (const AbstractSimplePhaseBasedCellCycleModel &rModel)
Protected Member Functions inherited from AbstractPhaseBasedCellCycleModel
AbstractPhaseBasedCellCycleModel (const AbstractPhaseBasedCellCycleModel &rModel)
Protected Member Functions inherited from AbstractCellCycleModel
AbstractCellCycleModel (const AbstractCellCycleModel &rModel)
Protected Attributes
bool mUseCellProliferativeTypeDependentG1Duration
double mWntStemThreshold
double mWntTransitThreshold
double mWntLabelledThreshold
Protected Attributes inherited from AbstractPhaseBasedCellCycleModel
CellCyclePhase mCurrentCellCyclePhase
double mG1Duration
double mMinimumGapDuration
double mStemCellG1Duration
double mTransitCellG1Duration
double mSDuration
double mG2Duration
double mMDuration
Protected Attributes inherited from AbstractCellCycleModel
CellPtr mpCell
double mBirthTime
bool mReadyToDivide
unsigned mDimension
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Friends
class boost::serialization::access
Detailed Description
Simple Wnt-dependent cell-cycle model.
Definition at line 46 of file SimpleWntCellCycleModel.hpp.
Constructor & Destructor Documentation
SimpleWntCellCycleModel() [1/2]
SimpleWntCellCycleModel::SimpleWntCellCycleModel (const SimpleWntCellCycleModel & rModel) protected
Protected copy-constructor for use by CreateCellCycleModel. The only way for external code to create a copy of a cell cycle model is by calling that method, to ensure that a model of the correct subclass is created. This copy-constructor helps subclasses to ensure that all member variables are correctly copied when this happens.
This method is called by child classes to set member variables for a daughter cell upon cell division. Note that the parent cell cycle model will have had ResetForDivision() called just before CreateCellCycleModel() is called, so performing an exact copy of the parent is suitable behaviour. Any daughter-cell-specific initialisation can be done in InitialiseDaughterCell().
Parameters
rModel the cell cycle model to copy.
Definition at line 55 of file SimpleWntCellCycleModel.cpp.
SimpleWntCellCycleModel() [2/2]
SimpleWntCellCycleModel::SimpleWntCellCycleModel ()
Constructor - just a default, mBirthTime is now set in the AbstractPhaseBasedCellCycleModel class. mG1Duration is set very high, it is set for the individual cells when InitialiseDaughterCell is called.
Definition at line 47 of file SimpleWntCellCycleModel.cpp.
Referenced by CreateCellCycleModel().
Member Function Documentation
CanCellTerminallyDifferentiate()
bool SimpleWntCellCycleModel::CanCellTerminallyDifferentiate () virtual
Overridden CanCellTerminallyDifferentiate() method.
Returns
whether cell can terminally differentiate
Reimplemented from AbstractCellCycleModel.
Definition at line 285 of file SimpleWntCellCycleModel.cpp.
CreateCellCycleModel()
AbstractCellCycleModel * SimpleWntCellCycleModel::CreateCellCycleModel () virtual
Overridden builder method to create new copies of this cell-cycle model.
Returns
the new cell-cycle model
Implements AbstractCellCycleModel.
Reimplemented in SingleOdeWntCellCycleModel.
Definition at line 79 of file SimpleWntCellCycleModel.cpp.
References SimpleWntCellCycleModel().
GetUseCellProliferativeTypeDependentG1Duration()
bool SimpleWntCellCycleModel::GetUseCellProliferativeTypeDependentG1Duration () const
Returns
mUseCellProliferativeTypeDependentG1Duration
Definition at line 84 of file SimpleWntCellCycleModel.cpp.
References mUseCellProliferativeTypeDependentG1Duration.
GetWntLabelledThreshold()
double SimpleWntCellCycleModel::GetWntLabelledThreshold () const
Returns
mWntLabelledThreshold
Definition at line 314 of file SimpleWntCellCycleModel.cpp.
References mWntLabelledThreshold.
GetWntLevel()
double SimpleWntCellCycleModel::GetWntLevel () const protected
Returns
the Wnt level experienced by the cell.
Definition at line 132 of file SimpleWntCellCycleModel.cpp.
References WntConcentration< DIM >::GetWntLevel(), WntConcentration< DIM >::Instance(), AbstractCellCycleModel::mDimension, AbstractCellCycleModel::mpCell, and NEVER_REACHED.
Referenced by SingleOdeWntCellCycleModel::SingleOdeWntCellCycleModel(), SingleOdeWntCellCycleModel::AdjustOdeParameters(), SingleOdeWntCellCycleModel::Initialise(), and UpdateCellCyclePhase().
GetWntStemThreshold()
double SimpleWntCellCycleModel::GetWntStemThreshold () const
Returns
mWntStemThreshold
Definition at line 290 of file SimpleWntCellCycleModel.cpp.
References mWntStemThreshold.
GetWntTransitThreshold()
double SimpleWntCellCycleModel::GetWntTransitThreshold () const
Returns
mWntTransitThreshold
Definition at line 302 of file SimpleWntCellCycleModel.cpp.
References mWntTransitThreshold.
GetWntType()
WntConcentrationType SimpleWntCellCycleModel::GetWntType () protected
Returns
the type of Wnt concentration (LINEAR, RADIAL, EXPONENTIAL or NONE). This affects how the cell cycle phase is updated.
Definition at line 163 of file SimpleWntCellCycleModel.cpp.
References WntConcentration< DIM >::GetType(), WntConcentration< DIM >::Instance(), AbstractCellCycleModel::mDimension, NEVER_REACHED, and UNSIGNED_UNSET.
Referenced by InitialiseDaughterCell(), and UpdateCellCyclePhase().
InitialiseDaughterCell()
void SimpleWntCellCycleModel::InitialiseDaughterCell () virtual
Overridden InitialiseDaughterCell() method.
Reimplemented from AbstractSimplePhaseBasedCellCycleModel.
Definition at line 271 of file SimpleWntCellCycleModel.cpp.
References GetWntType(), AbstractSimplePhaseBasedCellCycleModel::InitialiseDaughterCell(), and AbstractCellCycleModel::mpCell.
OutputCellCycleModelParameters()
void SimpleWntCellCycleModel::OutputCellCycleModelParameters (out_stream & rParamsFile) virtual
Overridden OutputCellCycleModelParameters() method.
Parameters
rParamsFile the file stream to which the parameters are output
Reimplemented from AbstractSimplePhaseBasedCellCycleModel.
Reimplemented in SingleOdeWntCellCycleModel.
Definition at line 326 of file SimpleWntCellCycleModel.cpp.
References mUseCellProliferativeTypeDependentG1Duration, mWntLabelledThreshold, mWntStemThreshold, mWntTransitThreshold, and AbstractSimplePhaseBasedCellCycleModel::OutputCellCycleModelParameters().
Referenced by SingleOdeWntCellCycleModel::OutputCellCycleModelParameters().
serialize()
template<class Archive > void SimpleWntCellCycleModel::serialize (Archive & archive, const unsigned int version) inline private
Archive the cell-cycle model, never used directly - boost uses this.
Parameters
archive the archive
version the current version of this class
Definition at line 59 of file SimpleWntCellCycleModel.hpp.
References RandomNumberGenerator::Instance(), mUseCellProliferativeTypeDependentG1Duration, mWntLabelledThreshold, mWntStemThreshold, and mWntTransitThreshold.
SetG1Duration()
void SimpleWntCellCycleModel::SetG1Duration () protected virtual
Stochastically set the G1 duration. The G1 duration is taken from a normal distribution whose mean is the G1 duration given in AbstractPhaseBasedCellCycleModel, for the cell type, and whose standard deviation is 1.
Called on cell creation at the start of a simulation, and for both parent and daughter cells at cell division.
Reimplemented from AbstractSimplePhaseBasedCellCycleModel.
Definition at line 94 of file SimpleWntCellCycleModel.cpp.
References AbstractPhaseBasedCellCycleModel::GetStemCellG1Duration(), AbstractPhaseBasedCellCycleModel::GetTransitCellG1Duration(), RandomNumberGenerator::Instance(), AbstractPhaseBasedCellCycleModel::mG1Duration, AbstractPhaseBasedCellCycleModel::mMinimumGapDuration, AbstractCellCycleModel::mpCell, mUseCellProliferativeTypeDependentG1Duration, NEVER_REACHED, and RandomNumberGenerator::NormalRandomDeviate().
SetUseCellProliferativeTypeDependentG1Duration()
void SimpleWntCellCycleModel::SetUseCellProliferativeTypeDependentG1Duration (bool useCellProliferativeTypeDependentG1Duration = true)
Set whether Whether the duration of the G1 phase is dependent on cell type
Parameters
useCellProliferativeTypeDependentG1Duration - boolean, defaults to true.
Definition at line 89 of file SimpleWntCellCycleModel.cpp.
References mUseCellProliferativeTypeDependentG1Duration.
SetWntLabelledThreshold()
void SimpleWntCellCycleModel::SetWntLabelledThreshold (double wntLabelledThreshold)
Set mWntLabelledThreshold.
Parameters
wntLabelledThreshold the value of mWntLabelledThreshold
Definition at line 319 of file SimpleWntCellCycleModel.cpp.
References mWntLabelledThreshold.
SetWntStemThreshold()
void SimpleWntCellCycleModel::SetWntStemThreshold (double wntStemThreshold)
Set mWntStemThreshold.
Parameters
wntStemThreshold the value of mWntStemThreshold
Definition at line 295 of file SimpleWntCellCycleModel.cpp.
References mWntStemThreshold.
SetWntTransitThreshold()
void SimpleWntCellCycleModel::SetWntTransitThreshold (double wntTransitThreshold)
Set mWntTransitThreshold.
Parameters
wntTransitThreshold the value of mWntTransitThreshold
Definition at line 307 of file SimpleWntCellCycleModel.cpp.
References mWntTransitThreshold.
UpdateCellCyclePhase()
void SimpleWntCellCycleModel::UpdateCellCyclePhase () virtual
Overridden UpdateCellCyclePhase() method.
Reimplemented from AbstractSimplePhaseBasedCellCycleModel.
Reimplemented in SingleOdeWntCellCycleModel.
Definition at line 197 of file SimpleWntCellCycleModel.cpp.
References GetWntLevel(), GetWntType(), AbstractCellCycleModel::mpCell, mWntLabelledThreshold, mWntStemThreshold, mWntTransitThreshold, NEVER_REACHED, and AbstractSimplePhaseBasedCellCycleModel::UpdateCellCyclePhase().
Friends And Related Symbol Documentation
boost::serialization::access
friend class boost::serialization::access friend
Needed for serialization.
Definition at line 51 of file SimpleWntCellCycleModel.hpp.
Member Data Documentation
mUseCellProliferativeTypeDependentG1Duration
bool SimpleWntCellCycleModel::mUseCellProliferativeTypeDependentG1Duration protected
Whether to use different mean G1 durations for different cell types. For use in SetG1Duration().
Definition at line 78 of file SimpleWntCellCycleModel.hpp.
Referenced by GetUseCellProliferativeTypeDependentG1Duration(), OutputCellCycleModelParameters(), serialize(), SetG1Duration(), and SetUseCellProliferativeTypeDependentG1Duration().
mWntLabelledThreshold
double SimpleWntCellCycleModel::mWntLabelledThreshold protected
Non-dimensionalized Wnt threshold, above which labelled cells progress through the cell cycle.
Definition at line 93 of file SimpleWntCellCycleModel.hpp.
Referenced by GetWntLabelledThreshold(), OutputCellCycleModelParameters(), serialize(), SetWntLabelledThreshold(), and UpdateCellCyclePhase().
mWntStemThreshold
double SimpleWntCellCycleModel::mWntStemThreshold protected
Non-dimensionalized Wnt threshold, above which cells behave as stem cells.
Definition at line 83 of file SimpleWntCellCycleModel.hpp.
Referenced by GetWntStemThreshold(), OutputCellCycleModelParameters(), serialize(), SetWntStemThreshold(), and UpdateCellCyclePhase().
mWntTransitThreshold
double SimpleWntCellCycleModel::mWntTransitThreshold protected
Non-dimensionalized Wnt threshold, above which cells progress through the cell cycle.
Definition at line 88 of file SimpleWntCellCycleModel.hpp.
Referenced by GetWntTransitThreshold(), OutputCellCycleModelParameters(), serialize(), SetWntTransitThreshold(), and UpdateCellCyclePhase().
The documentation for this class was generated from the following files:
crypt/src/cell/cycle/SimpleWntCellCycleModel.hpp
crypt/src/cell/cycle/SimpleWntCellCycleModel.cpp