Chaste: PetscSetupUtils Class Reference
PetscSetupUtils Class Reference
#include <PetscSetupUtils.hpp>
Static Public Member Functions
static void CommonSetup ()
static void InitialisePetsc ()
static void ResetStatusCache ()
static void CommonFinalize ()
Detailed Description
Common code for setting up and tearing down tests. Used by PetscSetupAndFinalize.hpp and FakePetscSetup.hpp
Definition at line 43 of file PetscSetupUtils.hpp.
Member Function Documentation
CommonFinalize()
void PetscSetupUtils::CommonFinalize () static
The global finalize (prints citations).
Definition at line 122 of file PetscSetupUtils.cpp.
References Citations::Print().
Referenced by ExecutableSupport::FinalizePetsc(), and PetscSetup::tearDownWorld().
CommonSetup()
void PetscSetupUtils::CommonSetup () static
The global setup for Chaste tests.
Definition at line 86 of file PetscSetupUtils.cpp.
References ChasteSourceRootDir(), EXPECT0, InitialisePetsc(), and Citations::Register().
Referenced by PetscSetup::setUpWorld().
InitialisePetsc()
void PetscSetupUtils::InitialisePetsc () static
Just initialise PETSc without performing the rest of the common setup.
Definition at line 76 of file PetscSetupUtils.cpp.
References CommandLineArguments::Instance(), CommandLineArguments::p_argc, CommandLineArguments::p_argv, and PetscTools::ResetCache().
Referenced by CommonSetup().
ResetStatusCache()
void PetscSetupUtils::ResetStatusCache () static
Call PetscTools::ResetCache(). Used by FakePetscSetup.hpp to ensure the cache doesn't reflect being run in parallel.
Definition at line 130 of file PetscSetupUtils.cpp.
References PetscTools::ResetCache().
Referenced by PetscSetup::setUpWorld().
The documentation for this class was generated from the following files:
global/src/fortests/PetscSetupUtils.hpp
global/src/fortests/PetscSetupUtils.cpp