Chaste: CryptVertexBasedDivisionRule< SPACE_DIM > Class Template Reference
CryptVertexBasedDivisionRule< SPACE_DIM > Class Template Reference
#include <CryptVertexBasedDivisionRule.hpp>
Public Member Functions
CryptVertexBasedDivisionRule ()
virtual ~CryptVertexBasedDivisionRule ()
virtual c_vector< double, SPACE_DIM > CalculateCellDivisionVector (CellPtr pParentCell, VertexBasedCellPopulation< SPACE_DIM > &rCellPopulation)
Public Member Functions inherited from AbstractVertexBasedDivisionRule< SPACE_DIM >
AbstractVertexBasedDivisionRule ()
virtual ~AbstractVertexBasedDivisionRule ()
void OutputCellVertexBasedDivisionRuleInfo (out_stream &rParamsFile)
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Friends
class boost::serialization::access
Additional Inherited Members
Protected Member Functions inherited from AbstractVertexBasedDivisionRule< SPACE_DIM >
virtual void OutputCellVertexBasedDivisionRuleParameters (out_stream &rParamsFile)
Detailed Description
template<unsigned SPACE_DIM>
class CryptVertexBasedDivisionRule< SPACE_DIM >
A class to generate a division vector of unit lengths that points in a random direction, unless dealing with a 'stem' cell in the absence of a Wnt gradient. For use in CryptSimulation2d.
Definition at line 55 of file CryptVertexBasedDivisionRule.hpp.
Constructor & Destructor Documentation
CryptVertexBasedDivisionRule()
template<unsigned SPACE_DIM> CryptVertexBasedDivisionRule< SPACE_DIM >::CryptVertexBasedDivisionRule () inline
Default constructor.
Definition at line 75 of file CryptVertexBasedDivisionRule.hpp.
~CryptVertexBasedDivisionRule()
template<unsigned SPACE_DIM> virtual CryptVertexBasedDivisionRule< SPACE_DIM >::~CryptVertexBasedDivisionRule () inline virtual
Empty destructor.
Definition at line 82 of file CryptVertexBasedDivisionRule.hpp.
Member Function Documentation
CalculateCellDivisionVector()
template<unsigned SPACE_DIM> c_vector< double, SPACE_DIM > CryptVertexBasedDivisionRule< SPACE_DIM >::CalculateCellDivisionVector (CellPtr pParentCell, VertexBasedCellPopulation< SPACE_DIM > & rCellPopulation) virtual
Overridden CalculateCellDivisionVector() method.
Return a unit vector in a random direction, i.e the arguments are redundant for this division rule.
Parameters
pParentCell The cell to divide
rCellPopulation The vertex-based cell population
Returns
the division vector.
Implements AbstractVertexBasedDivisionRule< SPACE_DIM >.
Definition at line 41 of file CryptVertexBasedDivisionRule.cpp.
References WntConcentration< DIM >::Destroy(), WntConcentration< DIM >::Instance(), RandomNumberGenerator::Instance(), WntConcentration< DIM >::IsWntSetUp(), and RandomNumberGenerator::ranf().
serialize()
template<unsigned SPACE_DIM> template<class Archive > void CryptVertexBasedDivisionRule< SPACE_DIM >::serialize (Archive & archive, const unsigned int version) inline private
Serialize the object and its member variables.
Parameters
archive the archive
version the current version of this class
Definition at line 66 of file CryptVertexBasedDivisionRule.hpp.
Friends And Related Symbol Documentation
boost::serialization::access
template<unsigned SPACE_DIM> friend class boost::serialization::access friend
Definition at line 58 of file CryptVertexBasedDivisionRule.hpp.
The documentation for this class was generated from the following files:
crypt/src/division_rules/CryptVertexBasedDivisionRule.hpp
crypt/src/division_rules/CryptVertexBasedDivisionRule.cpp