Chaste: RadialSloughingCellKiller Class Reference
RadialSloughingCellKiller Class Reference
#include <RadialSloughingCellKiller.hpp>
Public Member Functions
RadialSloughingCellKiller (AbstractCellPopulation< 2 > *pCellPopulation, c_vector< double, 2 > centre, double radius)
c_vector< double, 2 > GetCentre () const
double GetRadius () const
virtual void CheckAndLabelCellsForApoptosisOrDeath ()
void OutputCellKillerParameters (out_stream &rParamsFile)
Public Member Functions inherited from AbstractCellKiller< 2 >
AbstractCellKiller (AbstractCellPopulation< SPACE_DIM > *pCellPopulation)
virtual ~AbstractCellKiller ()
const AbstractCellPopulation< SPACE_DIM > * GetCellPopulation () const
void OutputCellKillerInfo (out_stream &rParamsFile)
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Private Attributes
c_vector< double, 2 > mCentre
double mRadius
Friends
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from AbstractCellKiller< 2 >
AbstractCellPopulation< SPACE_DIM > * mpCellPopulation
Detailed Description
Radial sloughing cell killer for use with the crypt projection model.
Kills cells if they are outside a circle whose centre and radius can be passed in but are take default values.
Definition at line 50 of file RadialSloughingCellKiller.hpp.
Constructor & Destructor Documentation
RadialSloughingCellKiller()
RadialSloughingCellKiller::RadialSloughingCellKiller (AbstractCellPopulation< 2 > * pCellPopulation, c_vector< double, 2 > centre, double radius)
Constructor.
Parameters
pCellPopulation pointer to the cell population.
centre the centre of death.
radius the radius of death.
Definition at line 38 of file RadialSloughingCellKiller.cpp.
Member Function Documentation
CheckAndLabelCellsForApoptosisOrDeath()
void RadialSloughingCellKiller::CheckAndLabelCellsForApoptosisOrDeath () virtual
Loop over cells and kills cells outside boundary.
Implements AbstractCellKiller< 2 >.
Definition at line 55 of file RadialSloughingCellKiller.cpp.
References AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::Begin(), AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::End(), AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::GetLocationOfCellCentre(), AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::KillCell(), mCentre, AbstractCellKiller< 2 >::mpCellPopulation, and mRadius.
GetCentre()
c_vector< double, 2 > RadialSloughingCellKiller::GetCentre () const
Returns
mCentre.
Definition at line 45 of file RadialSloughingCellKiller.cpp.
References mCentre.
GetRadius()
double RadialSloughingCellKiller::GetRadius () const
Returns
mRadius.
Definition at line 50 of file RadialSloughingCellKiller.cpp.
References mRadius.
OutputCellKillerParameters()
void RadialSloughingCellKiller::OutputCellKillerParameters (out_stream & rParamsFile) virtual
Outputs cell killer parameters to file
As this method is pure virtual, it must be overridden in subclasses.
Parameters
rParamsFile the file stream to which the parameters are output
Implements AbstractCellKiller< 2 >.
Definition at line 72 of file RadialSloughingCellKiller.cpp.
References mCentre, mRadius, and AbstractCellKiller< SPACE_DIM >::OutputCellKillerParameters().
serialize()
template<class Archive > void RadialSloughingCellKiller::serialize (Archive & archive, const unsigned int version) inline private
Boost Serialization method for archiving/checkpointing. Archives the object and its member variables.
Parameters
archive The boost archive.
version The current version of this class.
Definition at line 69 of file RadialSloughingCellKiller.hpp.
Friends And Related Symbol Documentation
boost::serialization::access
friend class boost::serialization::access friend
Definition at line 60 of file RadialSloughingCellKiller.hpp.
Member Data Documentation
mCentre
c_vector<double,2> RadialSloughingCellKiller::mCentre private
Centre of death.
Definition at line 55 of file RadialSloughingCellKiller.hpp.
Referenced by CheckAndLabelCellsForApoptosisOrDeath(), GetCentre(), and OutputCellKillerParameters().
mRadius
double RadialSloughingCellKiller::mRadius private
Radius of death.
Definition at line 58 of file RadialSloughingCellKiller.hpp.
Referenced by CheckAndLabelCellsForApoptosisOrDeath(), GetRadius(), and OutputCellKillerParameters().
The documentation for this class was generated from the following files:
crypt/src/killers/RadialSloughingCellKiller.hpp
crypt/src/killers/RadialSloughingCellKiller.cpp