Chaste: ChasteBuildInfo Class Reference
ChasteBuildInfo Class Reference
#include <Version.hpp>
Static Public Member Functions
static std::string GetLicenceText ()
static const char * GetRootDir ()
static std::string GetVersionString ()
static unsigned GetMajorReleaseNumber ()
static unsigned GetMinorReleaseNumber ()
static unsigned long long GetRevisionNumber ()
static bool IsWorkingCopyModified ()
static const char * GetBuildTime ()
static const char * GetCurrentTime ()
static const char * GetBuilderUnameInfo ()
static const char * GetBuildInformation ()
static const char * GetCompilerType ()
static const char * GetCompilerVersion ()
static const char * GetCompilerFlags ()
static const char * GetXsdVersion ()
static const std::map< std::string, std::string > & rGetProjectVersions ()
static const std::map< std::string, std::string > & rGetIfProjectsModified ()
static std::string GetProvenanceString ()
static std::string GetChasteCodegenVersion ()
Detailed Description
A class with static methods providing various information about this build of Chaste.
Definition at line 47 of file Version.hpp.
Member Function Documentation
GetBuilderUnameInfo()
static const char * ChasteBuildInfo::GetBuilderUnameInfo () static
Returns
The output of "uname -a" on the machine that built Chaste.
Referenced by ExecutableSupport::GetBuildInfo(), ExecutableSupport::ShowCopyright(), and ExecutableSupport::WriteProvenanceInfoFile().
GetBuildInformation()
static const char * ChasteBuildInfo::GetBuildInformation () static
Returns
Information about this build of Chaste: the build type used, whether libraries were used, and if so what kind.
Referenced by ExecutableSupport::GetBuildInfo(), ExecutableSupport::ShowCopyright(), and ExecutableSupport::WriteProvenanceInfoFile().
GetBuildTime()
static const char * ChasteBuildInfo::GetBuildTime () static
Returns
The date and time at which Chaste was built.
Referenced by ExecutableSupport::GetBuildInfo(), ExecutableSupport::ShowCopyright(), and ExecutableSupport::WriteProvenanceInfoFile().
GetChasteCodegenVersion()
static std::string ChasteBuildInfo::GetChasteCodegenVersion () static
Returns
A single-line string representation the version of chaste_codegen being used.
Referenced by ExecutableSupport::GetBuildInfo().
GetCompilerFlags()
static const char * ChasteBuildInfo::GetCompilerFlags () static
Returns
The compiler flags.
Referenced by ExecutableSupport::GetBuildInfo().
GetCompilerType()
static const char * ChasteBuildInfo::GetCompilerType () static
Returns
The compiler type used to build (must be either 'intel' or 'gcc').
Referenced by ExecutableSupport::GetBuildInfo().
GetCompilerVersion()
static const char * ChasteBuildInfo::GetCompilerVersion () static
Returns
The compiler version number.
Referenced by ExecutableSupport::GetBuildInfo().
GetCurrentTime()
static const char * ChasteBuildInfo::GetCurrentTime () static
Returns
Get the current date and time, in the same format as GetBuildTime. The returned 'string' is statically allocated, so you don't need to free the memory. However, if you call this method again, the contents will be overwritten.
GetLicenceText()
static std::string ChasteBuildInfo::GetLicenceText () static
Returns
The licence notice for Chaste.
Referenced by ExecutableSupport::ShowCopyright().
GetMajorReleaseNumber()
static unsigned ChasteBuildInfo::GetMajorReleaseNumber () static
Returns
The major number of the "current" Chaste release. If this is a development build, this will be the number of the last release.
Note
This must be set manually by modifying CMakeLists.txt.
GetMinorReleaseNumber()
static unsigned ChasteBuildInfo::GetMinorReleaseNumber () static
Returns
The minor number of the "current" Chaste release. If this is a development build, this will be the number of the last release.
Note
This must be set manually by modifying CMakeLists.txt.
GetProvenanceString()
static std::string ChasteBuildInfo::GetProvenanceString () static
Returns
A single-line string representation of the provenance information to be attached to any files we generate. This includes the version of the Chaste code used, how and when it was built, and the current date and time.
Referenced by VtkMeshWriter< ELEMENT_DIM, SPACE_DIM >::AddProvenance(), ColumnDataWriter::CreateInfoFile(), Hdf5DataWriter::EndDefineMode(), Hdf5ToCmguiConverter< ELEMENT_DIM, SPACE_DIM >::Write(), Hdf5ToMeshalyzerConverter< ELEMENT_DIM, SPACE_DIM >::Write(), FibreWriter< DIM >::WriteAllAxi(), FibreWriter< DIM >::WriteAllOrtho(), Hdf5ToCmguiConverter< ELEMENT_DIM, SPACE_DIM >::WriteCmguiScript(), AbstractPerElementWriter< ELEMENT_DIM, SPACE_DIM, DATA_SIZE >::WriteData(), TrianglesMeshWriter< ELEMENT_DIM, SPACE_DIM >::WriteElementsAsFaces(), CmguiMeshWriter< ELEMENT_DIM, SPACE_DIM >::WriteElementsFileHeader(), TrianglesMeshWriter< ELEMENT_DIM, SPACE_DIM >::WriteFacesAsEdges(), PottsMeshWriter< SPACE_DIM >::WriteFiles(), ImmersedBoundaryMeshWriter< ELEMENT_DIM, SPACE_DIM >::WriteFiles(), VertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::WriteFiles(), MeshalyzerMeshWriter< ELEMENT_DIM, SPACE_DIM >::WriteFiles(), TrianglesMeshWriter< ELEMENT_DIM, SPACE_DIM >::WriteFiles(), XdmfMeshWriter< ELEMENT_DIM, SPACE_DIM >::WriteFiles(), MeshalyzerMeshWriter< ELEMENT_DIM, SPACE_DIM >::WriteFilesFooter(), XdmfMeshWriter< ELEMENT_DIM, SPACE_DIM >::WriteFilesUsingMesh(), PostProcessingWriter< ELEMENT_DIM, SPACE_DIM >::WriteGenericFileToMeshalyzer(), AbstractHdf5Converter< ELEMENT_DIM, SPACE_DIM >::WriteInfoFile(), MeshalyzerMeshWriter< ELEMENT_DIM, SPACE_DIM >::WriteMetaFile(), AbstractTetrahedralMeshWriter< ELEMENT_DIM, SPACE_DIM >::WriteNclFile(), CmguiMeshWriter< ELEMENT_DIM, SPACE_DIM >::WriteNodeFileHeader(), PseudoEcgCalculator< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::WritePseudoEcg(), and XdmfMeshWriter< ELEMENT_DIM, SPACE_DIM >::WriteXdmfMasterFile().
GetRevisionNumber()
static unsigned long long ChasteBuildInfo::GetRevisionNumber () static
Returns
Get the Git revision number of the Chaste source tree.
If the file ReleaseVersion.txt exists in the directory given by GetRootDir, then we assume this is not a working copy, and read the version information from there.
Otherwise, we assume this is a checked-out tree, and get Git revision info via CMake during the build. Whether the working copy is modified is ignored by this method; use IsWorkingCopyModified to test that.
Referenced by ExecutableSupport::ShowCopyright(), and ExecutableSupport::WriteProvenanceInfoFile().
GetRootDir()
static const char * ChasteBuildInfo::GetRootDir () static
Returns
The path to the root directory of the Chaste source tree.
Referenced by HeartConfig::SetDefaultSchemaLocations().
GetVersionString()
static std::string ChasteBuildInfo::GetVersionString () static
Returns
A string representation of the current Chaste version. This combines the information from GetMajorReleaseNumber, GetMinorReleaseNumber, and GetRevisionNumber.
Referenced by ExecutableSupport::GetBuildInfo().
GetXsdVersion()
static const char * ChasteBuildInfo::GetXsdVersion () static
Returns
The XSD binary version number.
Referenced by ExecutableSupport::GetBuildInfo().
IsWorkingCopyModified()
static bool ChasteBuildInfo::IsWorkingCopyModified () static
Returns
If this Chaste was built from a subversion working copy, then return whether there were local modifications. If it's not a working copy, return false.
Referenced by ExecutableSupport::GetBuildInfo().
rGetIfProjectsModified()
static const std::map< std::string, std::string > & ChasteBuildInfo::rGetIfProjectsModified () static
Returns
Whether any checked-out projects have uncommitted revisions.
Referenced by ExecutableSupport::GetBuildInfo().
rGetProjectVersions()
static const std::map< std::string, std::string > & ChasteBuildInfo::rGetProjectVersions () static
Returns
The version numbers (i.e. revisions) of any checked-out projects.
Referenced by ExecutableSupport::GetBuildInfo().
The documentation for this class was generated from the following file:
global/src/Version.hpp