Chaste: XmlTransforms Class Reference
XmlTransforms Class Reference
Static Public Member Functions
static void TransformIonicModelDefinitions (xercesc::DOMDocument *pDocument, xercesc::DOMElement *pRootElement)
static void TransformArchiveDirectory (xercesc::DOMDocument *pDocument, xercesc::DOMElement *pRootElement)
static void CheckForIluPreconditioner (xercesc::DOMDocument *pDocument, xercesc::DOMElement *pRootElement)
static void MoveConductivityHeterogeneities (xercesc::DOMDocument *pDocument, xercesc::DOMElement *pRootElement)
static void SetDefaultVisualizer (xercesc::DOMDocument *pDocument, xercesc::DOMElement *pRootElement)
Detailed Description
A class of utility methods for transforming parameters files from previous versions of the Chaste schema to the latest version.
Definition at line 139 of file HeartConfig.cpp.
Member Function Documentation
CheckForIluPreconditioner()
void XmlTransforms::CheckForIluPreconditioner (xercesc::DOMDocument * pDocument, xercesc::DOMElement * pRootElement) static
Release 2.1 removes the ilu preconditioner as an option, so throw an exception if it is used.
Parameters
pDocument the DOM document containing the tree to be transformed
pRootElement the root of the tree to be transformed
Definition at line 2998 of file HeartConfig.cpp.
References EXCEPTION, and XmlTools::FindElements().
Referenced by HeartConfig::ReadFile().
MoveConductivityHeterogeneities()
void XmlTransforms::MoveConductivityHeterogeneities (xercesc::DOMDocument * pDocument, xercesc::DOMElement * pRootElement) static
Release 3.1 moved the ConductivityHeterogeneities element from Simulation to Physiological, to be next to the default conductivity definitions.
Parameters
pDocument the DOM document containing the tree to be transformed
pRootElement the root of the tree to be transformed
Definition at line 3015 of file HeartConfig.cpp.
References XmlTools::FindElements().
Referenced by HeartConfig::ReadFile().
SetDefaultVisualizer()
void XmlTransforms::SetDefaultVisualizer (xercesc::DOMDocument * pDocument, xercesc::DOMElement * pRootElement) static
Release 3.3 changed the default setting for meshalyzer visualization from true to false. Older parameters files need to retain the original default.
Parameters
pDocument the DOM document containing the tree to be transformed
pRootElement the root of the tree to be transformed
Definition at line 3032 of file HeartConfig.cpp.
References XmlTools::FindElements().
Referenced by HeartConfig::ReadFile().
TransformArchiveDirectory()
void XmlTransforms::TransformArchiveDirectory (xercesc::DOMDocument * pDocument, xercesc::DOMElement * pRootElement) static
Edits the DOM tree to change the 'ArchiveDirectory' element from a simple string to a cp::path_type. This is used for 2.0 -> 2.1 migration. We assume that the path is relative to CHASTE_TEST_OUTPUT.
Parameters
pDocument the DOM document containing the tree to be transformed
pRootElement the root of the tree to be transformed
Definition at line 2963 of file HeartConfig.cpp.
References XmlTools::FindElements().
Referenced by HeartConfig::ReadFile().
TransformIonicModelDefinitions()
void XmlTransforms::TransformIonicModelDefinitions (xercesc::DOMDocument * pDocument, xercesc::DOMElement * pRootElement) static
Edits the DOM tree to wrap ionic model definitions from old (release 1 or 1.1) configuration files in a 'Hardcoded' element.
Parameters
pDocument the DOM document containing the tree to be transformed
pRootElement the root of the tree to be transformed
Definition at line 2978 of file HeartConfig.cpp.
References XmlTools::FindElements(), and XmlTools::WrapContentInElement().
Referenced by HeartConfig::ReadFile().
The documentation for this class was generated from the following file:
heart/src/problem/HeartConfig.cpp