Chaste: ImmersedBoundaryMesh< ELEMENT_DIM, SPACE_DIM >::ImmersedBoundaryElementIterator Class Reference
ImmersedBoundaryMesh< ELEMENT_DIM, SPACE_DIM >::ImmersedBoundaryElementIterator Class Reference
#include <ImmersedBoundaryMesh.hpp>
Public Member Functions
ImmersedBoundaryElement< ELEMENT_DIM, SPACE_DIM > & operator* ()
ImmersedBoundaryElement< ELEMENT_DIM, SPACE_DIM > * operator-> ()
bool operator!= (const typename ImmersedBoundaryMesh< ELEMENT_DIM, SPACE_DIM >::ImmersedBoundaryElementIterator &rOther)
ImmersedBoundaryElementIterator & operator++ ()
ImmersedBoundaryElementIterator (ImmersedBoundaryMesh< ELEMENT_DIM, SPACE_DIM > &rMesh, typename std::vector< ImmersedBoundaryElement< ELEMENT_DIM, SPACE_DIM > * >::iterator elementIter, bool skipDeletedElements=true)
Private Member Functions
bool IsAtEnd ()
bool IsAllowedElement ()
Private Attributes
ImmersedBoundaryMesh & mrMesh
std::vector< ImmersedBoundaryElement< ELEMENT_DIM, SPACE_DIM > * >::iterator mElementIter
bool mSkipDeletedElements
Detailed Description
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM>
class ImmersedBoundaryMesh< ELEMENT_DIM, SPACE_DIM >::ImmersedBoundaryElementIterator
A smart iterator over the elements in the mesh.
Definition at line 779 of file ImmersedBoundaryMesh.hpp.
Constructor & Destructor Documentation
ImmersedBoundaryElementIterator()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> ImmersedBoundaryMesh< ELEMENT_DIM, SPACE_DIM >::ImmersedBoundaryElementIterator::ImmersedBoundaryElementIterator (ImmersedBoundaryMesh< ELEMENT_DIM, SPACE_DIM > & rMesh, typename std::vector< ImmersedBoundaryElement< ELEMENT_DIM, SPACE_DIM > * >::iterator elementIter, bool skipDeletedElements = true)
Constructor for a new iterator.
This should not be called directly by user code; use the mesh methods ImmersedBoundaryMesh::GetElementIteratorBegin and ImmersedBoundaryMesh::GetElementIteratorEnd instead.
Parameters
rMesh the mesh to iterator over
elementIter where to start iterating
skipDeletedElements whether to include deleted elements
Definition at line 967 of file ImmersedBoundaryMesh.hpp.
References ImmersedBoundaryMesh< ELEMENT_DIM, SPACE_DIM >::ImmersedBoundaryElementIterator::IsAllowedElement(), ImmersedBoundaryMesh< ELEMENT_DIM, SPACE_DIM >::ImmersedBoundaryElementIterator::mElementIter, ImmersedBoundaryMesh< ELEMENT_DIM, SPACE_DIM >::mElements, and ImmersedBoundaryMesh< ELEMENT_DIM, SPACE_DIM >::ImmersedBoundaryElementIterator::mrMesh.
Member Function Documentation
IsAllowedElement()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> bool ImmersedBoundaryMesh< ELEMENT_DIM, SPACE_DIM >::ImmersedBoundaryElementIterator::IsAllowedElement () inline private
Helper method to say if we're allowed to point at this element.
Returns
true if allowed
Definition at line 997 of file ImmersedBoundaryMesh.hpp.
Referenced by ImmersedBoundaryMesh< ELEMENT_DIM, SPACE_DIM >::ImmersedBoundaryElementIterator::ImmersedBoundaryElementIterator().
IsAtEnd()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> bool ImmersedBoundaryMesh< ELEMENT_DIM, SPACE_DIM >::ImmersedBoundaryElementIterator::IsAtEnd () inline private
Helper method to say when we're at the end.
Returns
true if at end
Definition at line 991 of file ImmersedBoundaryMesh.hpp.
Referenced by ImmersedBoundaryMesh< ELEMENT_DIM, SPACE_DIM >::ImmersedBoundaryElementIterator::operator*().
operator!=()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> bool ImmersedBoundaryMesh< ELEMENT_DIM, SPACE_DIM >::ImmersedBoundaryElementIterator::operator!= (const typename ImmersedBoundaryMesh< ELEMENT_DIM, SPACE_DIM >::ImmersedBoundaryElementIterator & rOther) inline
Comparison not-equal-to.
Returns
true if not equal
Parameters
rOther iterator with which comparison is made
Definition at line 950 of file ImmersedBoundaryMesh.hpp.
References ImmersedBoundaryMesh< ELEMENT_DIM, SPACE_DIM >::ImmersedBoundaryElementIterator::mElementIter.
operator*()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> ImmersedBoundaryElement< ELEMENT_DIM, SPACE_DIM > & ImmersedBoundaryMesh< ELEMENT_DIM, SPACE_DIM >::ImmersedBoundaryElementIterator::operator* () inline
Dereference the iterator giving you a *reference* to the current element.
Returns
reference Make sure to use a reference for the result to avoid copying elements unnecessarily.
Definition at line 936 of file ImmersedBoundaryMesh.hpp.
References ImmersedBoundaryMesh< ELEMENT_DIM, SPACE_DIM >::ImmersedBoundaryElementIterator::IsAtEnd(), and ImmersedBoundaryMesh< ELEMENT_DIM, SPACE_DIM >::ImmersedBoundaryElementIterator::mElementIter.
operator++()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> ImmersedBoundaryMesh< ELEMENT_DIM, SPACE_DIM >::ImmersedBoundaryElementIterator & ImmersedBoundaryMesh< ELEMENT_DIM, SPACE_DIM >::ImmersedBoundaryElementIterator::operator++ () inline
Prefix increment operator.
Returns
reference to incremented object
Definition at line 956 of file ImmersedBoundaryMesh.hpp.
operator->()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> ImmersedBoundaryElement< ELEMENT_DIM, SPACE_DIM > * ImmersedBoundaryMesh< ELEMENT_DIM, SPACE_DIM >::ImmersedBoundaryElementIterator::operator-> () inline
Member access from a pointer.
Returns
pointer
Definition at line 943 of file ImmersedBoundaryMesh.hpp.
Member Data Documentation
mElementIter
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> std::vector<ImmersedBoundaryElement<ELEMENT_DIM,SPACE_DIM>*>::iterator ImmersedBoundaryMesh< ELEMENT_DIM, SPACE_DIM >::ImmersedBoundaryElementIterator::mElementIter private
The actual element iterator.
Definition at line 827 of file ImmersedBoundaryMesh.hpp.
Referenced by ImmersedBoundaryMesh< ELEMENT_DIM, SPACE_DIM >::ImmersedBoundaryElementIterator::ImmersedBoundaryElementIterator(), ImmersedBoundaryMesh< ELEMENT_DIM, SPACE_DIM >::ImmersedBoundaryElementIterator::operator!=(), and ImmersedBoundaryMesh< ELEMENT_DIM, SPACE_DIM >::ImmersedBoundaryElementIterator::operator*().
mrMesh
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> ImmersedBoundaryMesh& ImmersedBoundaryMesh< ELEMENT_DIM, SPACE_DIM >::ImmersedBoundaryElementIterator::mrMesh private
The mesh we're iterating over.
Definition at line 824 of file ImmersedBoundaryMesh.hpp.
Referenced by ImmersedBoundaryMesh< ELEMENT_DIM, SPACE_DIM >::ImmersedBoundaryElementIterator::ImmersedBoundaryElementIterator().
mSkipDeletedElements
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> bool ImmersedBoundaryMesh< ELEMENT_DIM, SPACE_DIM >::ImmersedBoundaryElementIterator::mSkipDeletedElements private
Whether to skip deleted elements.
Definition at line 830 of file ImmersedBoundaryMesh.hpp.
The documentation for this class was generated from the following file:
mesh/src/immersed_boundary/ImmersedBoundaryMesh.hpp