Chaste: CryptSimulation1d Class Reference
CryptSimulation1d Class Reference
#include <CryptSimulation1d.hpp>
Public Member Functions
CryptSimulation1d (AbstractCellPopulation< 1 > &rCellPopulation, bool deleteCellPopulationInDestructor=false, bool initialiseCells=true)
virtual ~CryptSimulation1d ()
void OutputSimulationParameters (out_stream &rParamsFile)
Public Member Functions inherited from OffLatticeSimulation< 1 >
OffLatticeSimulation (AbstractCellPopulation< ELEMENT_DIM, ELEMENT_DIM > &rCellPopulation, bool deleteCellPopulationInDestructor=false, bool initialiseCells=true)
void AddForce (boost::shared_ptr< AbstractForce< ELEMENT_DIM, ELEMENT_DIM > > pForce)
void RemoveAllForces ()
void AddCellPopulationBoundaryCondition (boost::shared_ptr< AbstractCellPopulationBoundaryCondition< ELEMENT_DIM, ELEMENT_DIM > > pBoundaryCondition)
void RemoveAllCellPopulationBoundaryConditions ()
void SetNumericalMethod (boost::shared_ptr< AbstractNumericalMethod< ELEMENT_DIM, ELEMENT_DIM > > pNumericalMethod)
const boost::shared_ptr< AbstractNumericalMethod< ELEMENT_DIM, ELEMENT_DIM > > GetNumericalMethod () const
void OutputAdditionalSimulationSetup (out_stream &rParamsFile)
const std::vector< boost::shared_ptr< AbstractForce< ELEMENT_DIM, ELEMENT_DIM > > > & rGetForceCollection () const
Public Member Functions inherited from AbstractCellBasedSimulation< ELEMENT_DIM, SPACE_DIM >
AbstractCellBasedSimulation (AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM > &rCellPopulation, bool deleteCellPopulationInDestructor=false, bool initialiseCells=true)
virtual ~AbstractCellBasedSimulation ()
std::vector< double > GetNodeLocation (const unsigned &rNodeIndex)
double GetDt ()
unsigned GetNumBirths ()
unsigned GetNumDeaths ()
std::string GetOutputDirectory ()
void SetDt (double dt)
void SetEndTime (double endTime)
void SetOutputDirectory (std::string outputDirectory)
void SetSamplingTimestepMultiple (unsigned samplingTimestepMultiple)
void SetUpdatingTimestepMultiple (unsigned updatingTimestepMultiple)
void SetNoBirth (bool noBirth)
void SetUpdateCellPopulationRule (bool updateCellPopulation)
bool GetUpdateCellPopulationRule ()
void AddCellKiller (boost::shared_ptr< AbstractCellKiller< SPACE_DIM > > pCellKiller)
void RemoveAllCellKillers ()
void AddSimulationModifier (boost::shared_ptr< AbstractCellBasedSimulationModifier< ELEMENT_DIM, SPACE_DIM > > pSimulationModifier)
std::vector< boost::shared_ptr< AbstractCellBasedSimulationModifier< ELEMENT_DIM, SPACE_DIM > > > * GetSimulationModifiers ()
void AddTopologyUpdateSimulationModifier (boost::shared_ptr< AbstractCellBasedSimulationModifier< ELEMENT_DIM, SPACE_DIM > > pSimulationModifier)
std::vector< boost::shared_ptr< AbstractCellBasedSimulationModifier< ELEMENT_DIM, SPACE_DIM > > > * GetTopologyUpdateSimulationModifiers ()
void Solve ()
AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM > & rGetCellPopulation ()
const AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM > & rGetCellPopulation () const
bool GetOutputDivisionLocations ()
void SetOutputDivisionLocations (bool outputDivisionLocations)
bool GetOutputCellVelocities ()
void SetOutputCellVelocities (bool outputCellVelocities)
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Private Attributes
MeshBasedCellPopulation< 1 > * mpStaticCastCellPopulation
Friends
class TestCryptSimulation1d
class boost::serialization::access
Additional Inherited Members
Protected Member Functions inherited from OffLatticeSimulation< 1 >
virtual void UpdateCellLocationsAndTopology ()
void RevertToOldLocations (std::map< Node< ELEMENT_DIM > *, c_vector< double, ELEMENT_DIM > > oldNodeLoctions)
void ApplyBoundaries (std::map< Node< ELEMENT_DIM > *, c_vector< double, ELEMENT_DIM > > oldNodeLoctions)
virtual void SetupSolve ()
virtual void WriteVisualizerSetupFile ()
Protected Member Functions inherited from AbstractCellBasedSimulation< ELEMENT_DIM, SPACE_DIM >
virtual unsigned DoCellBirth ()
unsigned DoCellRemoval ()
virtual bool StoppingEventHasOccurred ()
virtual void UpdateCellPopulation ()
void OutputSimulationSetup ()
Protected Attributes inherited from OffLatticeSimulation< 1 >
std::vector< boost::shared_ptr< AbstractForce< ELEMENT_DIM, ELEMENT_DIM > > > mForceCollection
std::vector< boost::shared_ptr< AbstractCellPopulationBoundaryCondition< ELEMENT_DIM, ELEMENT_DIM > > > mBoundaryConditions
boost::shared_ptr< AbstractNumericalMethod< ELEMENT_DIM, ELEMENT_DIM > > mpNumericalMethod
Protected Attributes inherited from AbstractCellBasedSimulation< ELEMENT_DIM, SPACE_DIM >
double mDt
double mEndTime
AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM > & mrCellPopulation
bool mDeleteCellPopulationInDestructor
bool mInitialiseCells
bool mNoBirth
bool mUpdateCellPopulation
std::string mOutputDirectory
std::string mSimulationOutputDirectory
out_stream mpVizSetupFile
unsigned mNumBirths
unsigned mNumDeaths
bool mOutputDivisionLocations
out_stream mpDivisionLocationFile
bool mOutputCellVelocities
out_stream mpCellVelocitiesFile
std::vector< boost::shared_ptr< AbstractCellKiller< SPACE_DIM > > > mCellKillers
std::vector< boost::shared_ptr< AbstractCellBasedSimulationModifier< ELEMENT_DIM, SPACE_DIM > > > mSimulationModifiers
std::vector< boost::shared_ptr< AbstractCellBasedSimulationModifier< ELEMENT_DIM, SPACE_DIM > > > mTopologyUpdateSimulationModifiers
unsigned mSamplingTimestepMultiple
unsigned mUpdatingTimestepMultiple
Detailed Description
A 1D crypt simulation object. The model is a simplified version of a 2D crypt model developed by Meineke et al (doi:10.1046/j.0960-7722.2001.00216.x).
Definition at line 55 of file CryptSimulation1d.hpp.
Constructor & Destructor Documentation
CryptSimulation1d()
CryptSimulation1d::CryptSimulation1d (AbstractCellPopulation< 1 > & rCellPopulation, bool deleteCellPopulationInDestructor = false, bool initialiseCells = true)
Constructor.
Parameters
rCellPopulation A cell population object
deleteCellPopulationInDestructor Whether to delete the cell population on destruction to free up memory (defaults to false)
initialiseCells whether to initialise cells (defaults to true, set to false when loading from an archive)
Definition at line 40 of file CryptSimulation1d.cpp.
References OffLatticeSimulation< 1 >::AddCellPopulationBoundaryCondition(), MAKE_PTR, MAKE_PTR_ARGS, AbstractCellBasedSimulation< ELEMENT_DIM, SPACE_DIM >::mDeleteCellPopulationInDestructor, mpStaticCastCellPopulation, AbstractCellBasedSimulation< ELEMENT_DIM, SPACE_DIM >::mrCellPopulation, and AbstractCentreBasedCellPopulation< ELEMENT_DIM, SPACE_DIM >::SetCentreBasedDivisionRule().
~CryptSimulation1d()
CryptSimulation1d::~CryptSimulation1d () virtual
Destructor.
This frees the CryptSimulationBoundaryCondition.
Definition at line 60 of file CryptSimulation1d.cpp.
Member Function Documentation
OutputSimulationParameters()
void CryptSimulation1d::OutputSimulationParameters (out_stream & rParamsFile) virtual
Outputs simulation parameters to file
As this method is pure virtual, it must be overridden in subclasses.
Parameters
rParamsFile the file stream to which the parameters are output
Reimplemented from OffLatticeSimulation< 1 >.
Definition at line 64 of file CryptSimulation1d.cpp.
References OffLatticeSimulation< ELEMENT_DIM, SPACE_DIM >::OutputSimulationParameters().
serialize()
template<class Archive > void CryptSimulation1d::serialize (Archive & archive, const unsigned int version) inline private
Archive the simulation and member variables.
Parameters
archive the archive
version the current version of this class
Definition at line 71 of file CryptSimulation1d.hpp.
References SerializableSingleton< SINGLETON_CLASS >::GetSerializationWrapper(), and WntConcentration< DIM >::Instance().
Friends And Related Symbol Documentation
boost::serialization::access
friend class boost::serialization::access friend
Needed for serialization.
Definition at line 63 of file CryptSimulation1d.hpp.
TestCryptSimulation1d
friend class TestCryptSimulation1d friend
Definition at line 58 of file CryptSimulation1d.hpp.
Member Data Documentation
mpStaticCastCellPopulation
MeshBasedCellPopulation<1>* CryptSimulation1d::mpStaticCastCellPopulation private
Helper member that is a static cast of the cell population.
Definition at line 80 of file CryptSimulation1d.hpp.
Referenced by CryptSimulation1d().
The documentation for this class was generated from the following files:
crypt/src/simulation/CryptSimulation1d.hpp
crypt/src/simulation/CryptSimulation1d.cpp