Chaste: CryptCentreBasedDivisionRule< ELEMENT_DIM, SPACE_DIM > Class Template Reference
CryptCentreBasedDivisionRule< ELEMENT_DIM, SPACE_DIM > Class Template Reference
#include <CryptCentreBasedDivisionRule.hpp>
Public Member Functions
CryptCentreBasedDivisionRule ()
virtual ~CryptCentreBasedDivisionRule ()
virtual std::pair< c_vector< double, SPACE_DIM >, c_vector< double, SPACE_DIM > > CalculateCellDivisionVector (CellPtr pParentCell, AbstractCentreBasedCellPopulation< ELEMENT_DIM, SPACE_DIM > &rCellPopulation)
Public Member Functions inherited from AbstractCentreBasedDivisionRule< ELEMENT_DIM, SPACE_DIM >
AbstractCentreBasedDivisionRule ()
virtual ~AbstractCentreBasedDivisionRule ()
void OutputCellCentreBasedDivisionRuleInfo (out_stream &rParamsFile)
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Friends
class boost::serialization::access
Additional Inherited Members
Protected Member Functions inherited from AbstractCentreBasedDivisionRule< ELEMENT_DIM, SPACE_DIM >
virtual void OutputCellCentreBasedDivisionRuleParameters (out_stream &rParamsFile)
Detailed Description
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM = ELEMENT_DIM>
class CryptCentreBasedDivisionRule< ELEMENT_DIM, SPACE_DIM >
A class to generate a division vector of length AbstractCentreBasedCellPopulation::mMeinekeDivisionSeparation that points in a random direction.
Definition at line 55 of file CryptCentreBasedDivisionRule.hpp.
Constructor & Destructor Documentation
CryptCentreBasedDivisionRule()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM = ELEMENT_DIM> CryptCentreBasedDivisionRule< ELEMENT_DIM, SPACE_DIM >::CryptCentreBasedDivisionRule () inline
Default constructor.
Definition at line 75 of file CryptCentreBasedDivisionRule.hpp.
~CryptCentreBasedDivisionRule()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM = ELEMENT_DIM> virtual CryptCentreBasedDivisionRule< ELEMENT_DIM, SPACE_DIM >::~CryptCentreBasedDivisionRule () inline virtual
Empty destructor.
Definition at line 82 of file CryptCentreBasedDivisionRule.hpp.
Member Function Documentation
CalculateCellDivisionVector()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> std::pair< c_vector< double, SPACE_DIM >, c_vector< double, SPACE_DIM > > CryptCentreBasedDivisionRule< ELEMENT_DIM, SPACE_DIM >::CalculateCellDivisionVector (CellPtr pParentCell, AbstractCentreBasedCellPopulation< ELEMENT_DIM, SPACE_DIM > & rCellPopulation) virtual
Overridden CalculateCellDivisionVector() method.
Parameters
pParentCell The cell to divide
rCellPopulation The centre-based cell population
Returns
the division vector.
Implements AbstractCentreBasedDivisionRule< ELEMENT_DIM, SPACE_DIM >.
Definition at line 41 of file CryptCentreBasedDivisionRule.cpp.
References EXCEPTION, AbstractCentreBasedCellPopulation< ELEMENT_DIM, SPACE_DIM >::GetLocationOfCellCentre(), AbstractCentreBasedCellPopulation< ELEMENT_DIM, SPACE_DIM >::GetMeinekeDivisionSeparation(), RandomNumberGenerator::Instance(), NEVER_REACHED, and RandomNumberGenerator::ranf().
serialize()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM = ELEMENT_DIM> template<class Archive > void CryptCentreBasedDivisionRule< ELEMENT_DIM, SPACE_DIM >::serialize (Archive & archive, const unsigned int version) inline private
Serialize the object and its member variables.
Parameters
archive the archive
version the current version of this class
Definition at line 66 of file CryptCentreBasedDivisionRule.hpp.
Friends And Related Symbol Documentation
boost::serialization::access
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM = ELEMENT_DIM> friend class boost::serialization::access friend
Definition at line 58 of file CryptCentreBasedDivisionRule.hpp.
The documentation for this class was generated from the following files:
crypt/src/division_rules/CryptCentreBasedDivisionRule.hpp
crypt/src/division_rules/CryptCentreBasedDivisionRule.cpp