Chaste: VertexBasedPopulationSrn< DIM > Class Template Reference
VertexBasedPopulationSrn< DIM > Class Template Reference
#include <VertexBasedPopulationSrn.hpp>
Public Member Functions
VertexBasedPopulationSrn ()
~VertexBasedPopulationSrn ()
void SetVertexCellPopulation (VertexBasedCellPopulation< DIM > *pCellPopulation)
void UpdateSrnAfterBirthOrDeath (VertexElementMap &rElementMap)
void RemapCellSrn (std::vector< AbstractSrnModelPtr > parentSrnEdges, CellSrnModel *pCellSrn, const EdgeRemapInfo &rEdgeChange)
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Private Attributes
VertexBasedCellPopulation< DIM > * mpCellPopulation
Friends
class boost::serialization::access
Detailed Description
template<unsigned DIM>
class VertexBasedPopulationSrn< DIM >
After topological rearrangments, e.g. T1-3, node merges, or edge splits due to mitosis, junctional SRNs must be updated accordingly. For example, after edge split due to mitosis a new SRN must be created that inherits modified model variables. This class deals with Cell SRN update after a topological change occurs to the cell.
Definition at line 59 of file VertexBasedPopulationSrn.hpp.
Constructor & Destructor Documentation
VertexBasedPopulationSrn()
template<unsigned DIM> VertexBasedPopulationSrn< DIM >::VertexBasedPopulationSrn ()
Default constructor.
Definition at line 40 of file VertexBasedPopulationSrn.cpp.
~VertexBasedPopulationSrn()
template<unsigned DIM> VertexBasedPopulationSrn< DIM >::~VertexBasedPopulationSrn ()
Destructor.
Definition at line 46 of file VertexBasedPopulationSrn.cpp.
Member Function Documentation
RemapCellSrn()
template<unsigned DIM> void VertexBasedPopulationSrn< DIM >::RemapCellSrn (std::vector< AbstractSrnModelPtr > parentSrnEdges, CellSrnModel * pCellSrn, const EdgeRemapInfo & rEdgeChange)
Remaps cell SRN. If an edge has not been modified, the old edge SRN is mapped to its junction. Otherwise, edge SRNs are updated according to the operation performed.
Parameters
parentSrnEdges Edge SRNs before topology is changed
pCellSrn pointer to CellSrnModel
rEdgeChange Contains information about which edge changes occurred
Definition at line 133 of file VertexBasedPopulationSrn.cpp.
References CellSrnModel::AddEdgeSrn(), AbstractSrnModel::GetCell(), EdgeRemapInfo::GetEdgesMapping(), EdgeRemapInfo::GetEdgesStatus(), CellSrnModel::GetInteriorSrn(), CellSrnModel::GetNumEdgeSrn(), and EdgeRemapInfo::GetSplitProportions().
serialize()
template<unsigned DIM> template<class Archive > void VertexBasedPopulationSrn< DIM >::serialize (Archive & archive, const unsigned int version) inline private
Serialize the object and its member variables.
Note that serialization of the mesh and cells is handled by load/save_construct_data.
Note also that member data related to writers is not saved - output must be set up again by the caller after a restart.
Parameters
archive the archive
version the current version of this class
Definition at line 79 of file VertexBasedPopulationSrn.hpp.
SetVertexCellPopulation()
template<unsigned DIM> void VertexBasedPopulationSrn< DIM >::SetVertexCellPopulation (VertexBasedCellPopulation< DIM > * pCellPopulation)
Set the cell population.
Parameters
pCellPopulation pointer to a VertexBasedCellPopulation
Definition at line 51 of file VertexBasedPopulationSrn.cpp.
UpdateSrnAfterBirthOrDeath()
template<unsigned DIM> void VertexBasedPopulationSrn< DIM >::UpdateSrnAfterBirthOrDeath (VertexElementMap & rElementMap)
This method iterates over edge operations performed on the mesh and calls on RemapCellSrn() with appropriate arguments
Parameters
rElementMap the element map to take into account that some elements are deleted after an edge operation is recorded
Definition at line 57 of file VertexBasedPopulationSrn.cpp.
References CellSrnModel::GetEdges(), VertexElementMap::GetNewIndex(), MutableVertexMesh< ELEMENT_DIM, SPACE_DIM >::GetOperationRecorder(), VertexElementMap::IsDeleted(), and VertexBasedCellPopulation< DIM >::rGetMesh().
Friends And Related Symbol Documentation
boost::serialization::access
template<unsigned DIM> friend class boost::serialization::access friend
Definition at line 66 of file VertexBasedPopulationSrn.hpp.
Member Data Documentation
mpCellPopulation
template<unsigned DIM> VertexBasedCellPopulation<DIM>* VertexBasedPopulationSrn< DIM >::mpCellPopulation private
Pointer to a VertexBasedCellPopulation.
Definition at line 64 of file VertexBasedPopulationSrn.hpp.
The documentation for this class was generated from the following files:
cell_based/src/population/srn_update/VertexBasedPopulationSrn.hpp
cell_based/src/population/srn_update/VertexBasedPopulationSrn.cpp