Chaste: ImmersedBoundaryPalisadeMeshGenerator Class Reference
ImmersedBoundaryPalisadeMeshGenerator Class Reference
#include <ImmersedBoundaryPalisadeMeshGenerator.hpp>
Public Member Functions
ImmersedBoundaryPalisadeMeshGenerator (unsigned numCellsWide, unsigned numNodesPerCell=100, double ellipseExponent=0.2, double cellAspectRatio=2.0, double randomYMult=0.0, bool basalLamina=false, bool apicalLamina=false, bool leakyLaminas=false, unsigned numFluidMeshPoints=UINT_MAX, double absoluteGap=DOUBLE_UNSET)
ImmersedBoundaryPalisadeMeshGenerator ()
virtual ~ImmersedBoundaryPalisadeMeshGenerator ()
ImmersedBoundaryMesh< 2, 2 > * GetMesh ()
Protected Attributes
ImmersedBoundaryMesh< 2, 2 > * mpMesh
Detailed Description
Creates a palisade of immersed boundary elements.
NOTE: the user should delete the mesh after use to manage memory. NOTE: the user should change mesh parameters like fluid grid spacing, as these are not altered from defaults here.
Definition at line 51 of file ImmersedBoundaryPalisadeMeshGenerator.hpp.
Constructor & Destructor Documentation
ImmersedBoundaryPalisadeMeshGenerator() [1/2]
ImmersedBoundaryPalisadeMeshGenerator::ImmersedBoundaryPalisadeMeshGenerator (unsigned numCellsWide, unsigned numNodesPerCell = 100, double ellipseExponent = 0.2, double cellAspectRatio = 2.0, double randomYMult = 0.0, bool basalLamina = false, bool apicalLamina = false, bool leakyLaminas = false, unsigned numFluidMeshPoints = UINT_MAX, double absoluteGap = DOUBLE_UNSET)
Default constructor.
Parameters
numCellsWide the number of cells from left to right along the domain
numNodesPerCell the number of nodes per cell (defaults to 100). Overridden by numFluidMeshPoints
ellipseExponent the exponent of the superellipse (defaults to 0.2)
cellAspectRatio the aspect ratio of each cell (defaults to 2)
randomYMult the random variation in y_pos (defaults to 0)
basalLamina whether the palisade has a basal lamina (defaults to false)
apicalLamina whether the palisade has an apical lamina (defaults to false)
leakyLaminas whether the laminas should have a deliberately course node-spacing (defaults to false)
numFluidMeshPoints number of fluid mesh points (X and Y). Overrides numNodesPerCell (defaults to UINT_MAX)
absoluteGap the required gap between cells (defaults to DOUBLE_UNSET)
Definition at line 41 of file ImmersedBoundaryPalisadeMeshGenerator.cpp.
References DOUBLE_UNSET, EXCEPTION, RandomNumberGenerator::Instance(), mpMesh, RandomNumberGenerator::ranf(), and Node< SPACE_DIM >::SetRegion().
ImmersedBoundaryPalisadeMeshGenerator() [2/2]
ImmersedBoundaryPalisadeMeshGenerator::ImmersedBoundaryPalisadeMeshGenerator () inline
Null constructor for derived classes to call.
Definition at line 88 of file ImmersedBoundaryPalisadeMeshGenerator.hpp.
~ImmersedBoundaryPalisadeMeshGenerator()
ImmersedBoundaryPalisadeMeshGenerator::~ImmersedBoundaryPalisadeMeshGenerator () virtual
Destructor.
Deletes the mesh object and pointer.
Definition at line 354 of file ImmersedBoundaryPalisadeMeshGenerator.cpp.
References mpMesh.
Member Function Documentation
GetMesh()
ImmersedBoundaryMesh< 2, 2 > * ImmersedBoundaryPalisadeMeshGenerator::GetMesh ()
Returns
a 2D honeycomb mesh based on a 2D plane
Definition at line 359 of file ImmersedBoundaryPalisadeMeshGenerator.cpp.
References mpMesh.
Member Data Documentation
mpMesh
ImmersedBoundaryMesh<2,2>* ImmersedBoundaryPalisadeMeshGenerator::mpMesh protected
A pointer to the mesh this class creates.
Definition at line 56 of file ImmersedBoundaryPalisadeMeshGenerator.hpp.
Referenced by ImmersedBoundaryPalisadeMeshGenerator(), ~ImmersedBoundaryPalisadeMeshGenerator(), and GetMesh().
The documentation for this class was generated from the following files:
mesh/src/immersed_boundary/ImmersedBoundaryPalisadeMeshGenerator.hpp
mesh/src/immersed_boundary/ImmersedBoundaryPalisadeMeshGenerator.cpp