Chaste: CryptCellsGenerator< CELL_CYCLE_MODEL > Class Template Reference
CryptCellsGenerator< CELL_CYCLE_MODEL > Class Template Reference
#include <CryptCellsGenerator.hpp>
Public Member Functions
void Generate (std::vector< CellPtr > &rCells, AbstractMesh< 2, 2 > *pMesh, const std::vector< unsigned > locationIndices, bool randomBirthTimes, double y0=0.3, double y1=2.0, double y2=3.0, double y3=4.0, bool initialiseCells=false)
Public Member Functions inherited from CellsGenerator< CELL_CYCLE_MODEL, 2 >
void GenerateBasic (std::vector< CellPtr > &rCells, unsigned numCells, const std::vector< unsigned > locationIndices=std::vector< unsigned >(), boost::shared_ptr< AbstractCellProperty > pCellProliferativeType=boost::shared_ptr< AbstractCellProperty >())
void GenerateBasicRandom (std::vector< CellPtr > &rCells, unsigned numCells, boost::shared_ptr< AbstractCellProperty > pCellProliferativeType=boost::shared_ptr< AbstractCellProperty >())
void GenerateGivenLocationIndices (std::vector< CellPtr > &rCells, const std::vector< unsigned > locationIndices, boost::shared_ptr< AbstractCellProperty > pCellProliferativeType=boost::shared_ptr< AbstractCellProperty >())
Detailed Description
template<class CELL_CYCLE_MODEL>
class CryptCellsGenerator< CELL_CYCLE_MODEL >
A subclass of CellsGenerator that generates cells for crypt simulations.
It is templated over types of cell-cycle model.
Definition at line 83 of file CryptCellsGenerator.hpp.
Member Function Documentation
Generate()
template<class CELL_CYCLE_MODEL > void CryptCellsGenerator< CELL_CYCLE_MODEL >::Generate (std::vector< CellPtr > & rCells, AbstractMesh< 2, 2 > * pMesh, const std::vector< unsigned > locationIndices, bool randomBirthTimes, double y0 = 0.3, double y1 = 2.0, double y2 = 3.0, double y3 = 4.0, bool initialiseCells = false)
Generates cells of a specified cell cycle type under the correct crypt conditions and gives random ages if required, or gives them an age of 0.0 - creates least work for solver startup.
Parameters
rCells An empty cells vector for this function to fill up
pMesh The crypt mesh (can be cylindrical)
locationIndices the node indices corresponding to real cells
randomBirthTimes Whether to assign the cells random birth times (this can be expensive computationally with ODE models)
y0 below this line cells are generation 0 (defaults to 0.3)
y1 below this line cells are generation 1 (defaults to 2.0)
y2 below this line cells are generation 2 (defaults to 3.0)
y3 below this line cells are generation 3 (defaults to 4.0)
initialiseCells whether to initialise the cell-cycle models as each cell is created
Definition at line 116 of file CryptCellsGenerator.hpp.
References AbstractMesh< ELEMENT_DIM, SPACE_DIM >::GetNode(), AbstractMesh< ELEMENT_DIM, SPACE_DIM >::GetNumNodes(), CellPropertyRegistry::Instance(), RandomNumberGenerator::Instance(), and RandomNumberGenerator::ranf().
The documentation for this class was generated from the following file:
crypt/src/cell/CryptCellsGenerator.hpp