Chaste: TrapezoidEdgeVertexMeshWriter< ELEMENT_DIM, SPACE_DIM > Class Template Reference
TrapezoidEdgeVertexMeshWriter< ELEMENT_DIM, SPACE_DIM > Class Template Reference
#include <TrapezoidEdgeVertexMeshWriter.hpp>
Public Member Functions
TrapezoidEdgeVertexMeshWriter (const std::string &rDirectory, const std::string &rBaseName, const bool clearOutputDir=true)
void WriteVtkUsingMesh (VertexMesh< ELEMENT_DIM, SPACE_DIM > &rMesh, const std::string &stamp="")
void MakeVtkMesh (VertexMesh< ELEMENT_DIM, SPACE_DIM > &rMesh)
void AddCellData (std::string dataName, std::vector< double > dataPayload)
~TrapezoidEdgeVertexMeshWriter ()
void WriteFiles ()
Public Member Functions inherited from AbstractMeshWriter< ELEMENT_DIM, SPACE_DIM >
AbstractMeshWriter (const std::string &rDirectory, const std::string &rBaseName, const bool clearOutputDir=true)
virtual ~AbstractMeshWriter ()
std::string GetOutputDirectory ()
virtual unsigned GetNumNodes ()
unsigned GetNumElements ()
unsigned GetNumBoundaryFaces ()
unsigned GetNumCableElements ()
virtual std::vector< double > GetNextNode ()
virtual ElementData GetNextElement ()
virtual ElementData GetNextBoundaryElement ()
virtual ElementData GetNextCableElement ()
void WriteFilesUsingMeshReader (AbstractMeshReader< ELEMENT_DIM, SPACE_DIM > &rMeshReader)
Private Attributes
VertexMesh< ELEMENT_DIM, SPACE_DIM > * mpMesh = nullptr
vtkUnstructuredGrid * mpVtkUnstructedMesh = nullptr
Additional Inherited Members
Protected Attributes inherited from AbstractMeshWriter< ELEMENT_DIM, SPACE_DIM >
OutputFileHandler * mpOutputFileHandler
std::string mBaseName
AbstractMeshReader< ELEMENT_DIM, SPACE_DIM > * mpMeshReader
unsigned mNumNodes
unsigned mNumElements
unsigned mNumBoundaryElements
unsigned mNumCableElements
Detailed Description
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM>
class TrapezoidEdgeVertexMeshWriter< ELEMENT_DIM, SPACE_DIM >
A mesh writer class for vertex-based meshes with edge representation. Each edge is associated with trapezoid such that the base is the edge and the sides are parallel to the line joining the cell's centroid and the nodes. __ __ / \ / \ / \ / \ | | |\ /| | | | | | | | | ==> |/ | \ / \ / \ __ / \ __ /
Definition at line 83 of file TrapezoidEdgeVertexMeshWriter.hpp.
Constructor & Destructor Documentation
TrapezoidEdgeVertexMeshWriter()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> TrapezoidEdgeVertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::TrapezoidEdgeVertexMeshWriter (const std::string & rDirectory, const std::string & rBaseName, const bool clearOutputDir = true)
Constructor.
Parameters
rDirectory reference to the output directory, relative to where Chaste output is stored
rBaseName reference to the base name for results files
clearOutputDir whether to clear the output directory prior to writing files
Definition at line 39 of file TrapezoidEdgeVertexMeshWriter.cpp.
References TrapezoidEdgeVertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::mpVtkUnstructedMesh.
~TrapezoidEdgeVertexMeshWriter()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> TrapezoidEdgeVertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::~TrapezoidEdgeVertexMeshWriter ()
Destructor.
Definition at line 51 of file TrapezoidEdgeVertexMeshWriter.cpp.
Member Function Documentation
AddCellData()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void TrapezoidEdgeVertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::AddCellData (std::string dataName, std::vector< double > dataPayload)
Add data to a future VTK file.
Parameters
dataName a tag to go into the VTK file
dataPayload a pay-load of length (number of elements)
Definition at line 200 of file TrapezoidEdgeVertexMeshWriter.cpp.
Referenced by VertexBasedCellPopulation< DIM >::WriteCellEdgeVtkResultsToFile().
MakeVtkMesh()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void TrapezoidEdgeVertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::MakeVtkMesh (VertexMesh< ELEMENT_DIM, SPACE_DIM > & rMesh)
Populate mpVtkUnstructedMesh using a vertex-based mesh. Called by WriteVtkUsingMesh().
Parameters
rMesh reference to the vertex-based mesh
Definition at line 96 of file TrapezoidEdgeVertexMeshWriter.cpp.
References VertexMesh< ELEMENT_DIM, SPACE_DIM >::GetCentroidOfElement(), VertexMesh< ELEMENT_DIM, SPACE_DIM >::GetElement(), VertexMesh< ELEMENT_DIM, SPACE_DIM >::GetElementIteratorBegin(), VertexMesh< ELEMENT_DIM, SPACE_DIM >::GetElementIteratorEnd(), AbstractMesh< ELEMENT_DIM, SPACE_DIM >::GetNode(), VertexMesh< ELEMENT_DIM, SPACE_DIM >::GetNumElements(), and VertexMesh< ELEMENT_DIM, SPACE_DIM >::GetNumNodes().
WriteFiles()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void TrapezoidEdgeVertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::WriteFiles () virtual
Write mesh data to files. This method must be overridden in concrete classes.
Implements AbstractMeshWriter< ELEMENT_DIM, SPACE_DIM >.
Definition at line 217 of file TrapezoidEdgeVertexMeshWriter.cpp.
WriteVtkUsingMesh()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void TrapezoidEdgeVertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::WriteVtkUsingMesh (VertexMesh< ELEMENT_DIM, SPACE_DIM > & rMesh, const std::string & stamp = "")
Write VTK file using a mesh.
Parameters
rMesh reference to the vertex-based mesh
stamp is an optional stamp (like a time-stamp) to put into the name of the file
Definition at line 59 of file TrapezoidEdgeVertexMeshWriter.cpp.
Referenced by VertexBasedCellPopulation< DIM >::WriteCellEdgeVtkResultsToFile().
Member Data Documentation
mpMesh
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> VertexMesh<ELEMENT_DIM, SPACE_DIM>* TrapezoidEdgeVertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::mpMesh = nullptr private
If writing from a mesh object, the mesh to write to disk. Otherwise NULL.
Definition at line 90 of file TrapezoidEdgeVertexMeshWriter.hpp.
mpVtkUnstructedMesh
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> vtkUnstructuredGrid* TrapezoidEdgeVertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::mpVtkUnstructedMesh = nullptr private
Todo:
Merge into VtkMeshWriter (#1076)
Definition at line 95 of file TrapezoidEdgeVertexMeshWriter.hpp.
Referenced by TrapezoidEdgeVertexMeshWriter< ELEMENT_DIM, SPACE_DIM >::TrapezoidEdgeVertexMeshWriter().
The documentation for this class was generated from the following files:
mesh/src/vertex/TrapezoidEdgeVertexMeshWriter.hpp
mesh/src/vertex/TrapezoidEdgeVertexMeshWriter.cpp