Chaste: RepulsionForce< DIM > Class Template Reference
RepulsionForce< DIM > Class Template Reference
#include <RepulsionForce.hpp>
Public Member Functions
RepulsionForce ()
void AddForceContribution (AbstractCellPopulation< DIM > &rCellPopulation)
virtual void OutputForceParameters (out_stream &rParamsFile)
Public Member Functions inherited from GeneralisedLinearSpringForce< DIM >
GeneralisedLinearSpringForce ()
virtual ~GeneralisedLinearSpringForce ()
virtual double VariableSpringConstantMultiplicationFactor (unsigned nodeAGlobalIndex, unsigned nodeBGlobalIndex, AbstractCellPopulation< ELEMENT_DIM, ELEMENT_DIM > &rCellPopulation, bool isCloserThanRestLength)
c_vector< double, ELEMENT_DIM > CalculateForceBetweenNodes (unsigned nodeAGlobalIndex, unsigned nodeBGlobalIndex, AbstractCellPopulation< ELEMENT_DIM, ELEMENT_DIM > &rCellPopulation)
double GetMeinekeSpringStiffness ()
double GetMeinekeDivisionRestingSpringLength ()
double GetMeinekeSpringGrowthDuration ()
void SetMeinekeSpringStiffness (double springStiffness)
void SetMeinekeDivisionRestingSpringLength (double divisionRestingSpringLength)
void SetMeinekeSpringGrowthDuration (double springGrowthDuration)
Public Member Functions inherited from AbstractTwoBodyInteractionForce< ELEMENT_DIM, SPACE_DIM >
AbstractTwoBodyInteractionForce ()
bool GetUseCutOffLength ()
void SetCutOffLength (double cutOffLength)
double GetCutOffLength ()
void AddForceContribution (AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM > &rCellPopulation)
virtual void WriteDataToVisualizerSetupFile (out_stream &pVizSetupFile)
Public Member Functions inherited from AbstractForce< ELEMENT_DIM, SPACE_DIM >
AbstractForce ()
virtual ~AbstractForce ()
void OutputForceInfo (out_stream &rParamsFile)
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Friends
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from GeneralisedLinearSpringForce< DIM >
double mMeinekeSpringStiffness
double mMeinekeDivisionRestingSpringLength
double mMeinekeSpringGrowthDuration
Protected Attributes inherited from AbstractTwoBodyInteractionForce< ELEMENT_DIM, SPACE_DIM >
bool mUseCutOffLength
double mMechanicsCutOffLength
Detailed Description
template<unsigned DIM>
class RepulsionForce< DIM >
A class for a simple two-body repulsion force law. Designed for use in node-based simulations
The force just creates a linear repulsive force between cells with a nonlinear separation less than 2. This force does not take a cell's age or cell cycle phase into account.
Definition at line 51 of file RepulsionForce.hpp.
Constructor & Destructor Documentation
RepulsionForce()
template<unsigned DIM> RepulsionForce< DIM >::RepulsionForce ()
Constructor.
Definition at line 39 of file RepulsionForce.cpp.
Member Function Documentation
AddForceContribution()
template<unsigned DIM> void RepulsionForce< DIM >::AddForceContribution (AbstractCellPopulation< DIM > & rCellPopulation)
Overridden AddForceContribution() method.
Parameters
rCellPopulation reference to the CellPopulation
Definition at line 45 of file RepulsionForce.cpp.
References Node< SPACE_DIM >::AddAppliedForceContribution(), EXCEPTION, Node< SPACE_DIM >::GetIndex(), Node< SPACE_DIM >::GetRadius(), and Node< SPACE_DIM >::rGetLocation().
OutputForceParameters()
template<unsigned DIM> void RepulsionForce< DIM >::OutputForceParameters (out_stream & rParamsFile) virtual
Outputs force Parameters to file
As this method is pure virtual, it must be overridden in subclasses.
Parameters
rParamsFile the file stream to which the parameters are output
Reimplemented from GeneralisedLinearSpringForce< DIM >.
Definition at line 97 of file RepulsionForce.cpp.
References GeneralisedLinearSpringForce< ELEMENT_DIM, SPACE_DIM >::OutputForceParameters().
serialize()
template<unsigned DIM> template<class Archive > void RepulsionForce< DIM >::serialize (Archive & archive, const unsigned int version) inline private
Archive the object and its member variables.
Parameters
archive the archive
version the current version of this class
Definition at line 64 of file RepulsionForce.hpp.
Friends And Related Symbol Documentation
boost::serialization::access
template<unsigned DIM> friend class boost::serialization::access friend
Needed for serialization.
Definition at line 56 of file RepulsionForce.hpp.
The documentation for this class was generated from the following files:
cell_based/src/population/forces/RepulsionForce.hpp
cell_based/src/population/forces/RepulsionForce.cpp