Chaste: BuskeCompressionForce< DIM > Class Template Reference
BuskeCompressionForce< DIM > Class Template Reference
#include <BuskeCompressionForce.hpp>
Public Member Functions
BuskeCompressionForce ()
double GetCompressionEnergyParameter ()
void SetCompressionEnergyParameter (double compressionEnergyParameter)
void AddForceContribution (AbstractCellPopulation< DIM > &rCellPopulation)
void OutputForceParameters (out_stream &rParamsFile)
Public Member Functions inherited from AbstractForce< DIM >
AbstractForce ()
virtual ~AbstractForce ()
virtual void AddForceContribution (AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM > &rCellPopulation)=0
void OutputForceInfo (out_stream &rParamsFile)
virtual void WriteDataToVisualizerSetupFile (out_stream &pVizSetupFile)
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Private Attributes
double mCompressionEnergyParameter
Friends
class TestForcesNotForRelease
class boost::serialization::access
Detailed Description
template<unsigned DIM>
class BuskeCompressionForce< DIM >
A force law employed by Buske et al (2011) in their overlapping spheres model of the intestinal crypt (doi:10.1371/journal.pcbi.1001045).
Length is scaled by natural length.
Todo:
does this mean natural radius of a cell? If so at what age? (#1764) Time is in hours.
This class specifically calculates the compression force which forms part of equation (A6) in the Buske paper.
Definition at line 55 of file BuskeCompressionForce.hpp.
Constructor & Destructor Documentation
BuskeCompressionForce()
template<unsigned DIM> BuskeCompressionForce< DIM >::BuskeCompressionForce ()
Constructor.
Definition at line 40 of file BuskeCompressionForce.cpp.
Member Function Documentation
AddForceContribution()
template<unsigned DIM> void BuskeCompressionForce< DIM >::AddForceContribution (AbstractCellPopulation< DIM > & rCellPopulation)
Overridden AddForceContribution() method.
Parameters
rCellPopulation a cell population object
Target volume of the cell
Todo:
Doesn't say in the Buske paper how they calculate this, so we need to look at this to be sure it's what we want (#1764)
Definition at line 59 of file BuskeCompressionForce.cpp.
References Node< SPACE_DIM >::AddAppliedForceContribution(), AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::Begin(), AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::End(), AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::GetLocationIndexUsingCell(), NodeBasedCellPopulation< DIM >::GetNeighbouringNodeIndices(), AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::GetNode(), Node< SPACE_DIM >::GetRadius(), and Node< SPACE_DIM >::rGetLocation().
GetCompressionEnergyParameter()
template<unsigned DIM> double BuskeCompressionForce< DIM >::GetCompressionEnergyParameter ()
Returns
mCompressionEnergyParameter.
Definition at line 47 of file BuskeCompressionForce.cpp.
OutputForceParameters()
template<unsigned DIM> void BuskeCompressionForce< DIM >::OutputForceParameters (out_stream & rParamsFile) virtual
Overridden OutputForceParameters() method.
Parameters
rParamsFile the file stream to which the parameters are output
Implements AbstractForce< DIM >.
Definition at line 142 of file BuskeCompressionForce.cpp.
References AbstractForce< ELEMENT_DIM, SPACE_DIM >::OutputForceParameters().
serialize()
template<unsigned DIM> template<class Archive > void BuskeCompressionForce< DIM >::serialize (Archive & archive, const unsigned int version) inline private
Boost Serialization method for archiving/checkpointing. Archives the object and its member variables.
Parameters
archive The boost archive.
version The current version of this class.
Definition at line 69 of file BuskeCompressionForce.hpp.
References BuskeCompressionForce< DIM >::mCompressionEnergyParameter.
SetCompressionEnergyParameter()
template<unsigned DIM> void BuskeCompressionForce< DIM >::SetCompressionEnergyParameter (double compressionEnergyParameter)
Set mCompressionEnergyParameter.
Parameters
compressionEnergyParameter the new value of mCompressionEnergyParameter
Definition at line 53 of file BuskeCompressionForce.cpp.
Friends And Related Symbol Documentation
boost::serialization::access
template<unsigned DIM> friend class boost::serialization::access friend
Definition at line 60 of file BuskeCompressionForce.hpp.
TestForcesNotForRelease
template<unsigned DIM> friend class TestForcesNotForRelease friend
Definition at line 57 of file BuskeCompressionForce.hpp.
Member Data Documentation
mCompressionEnergyParameter
template<unsigned DIM> double BuskeCompressionForce< DIM >::mCompressionEnergyParameter private
Returns
Compression energy parameter.
Represented by the parameter K in the model by Buske et al (2011) in their off-lattice model of the intestinal crypt (doi:10.1371/journal.pcbi.1001045).
Note: K is the bulk modulus of the spheres.
Definition at line 84 of file BuskeCompressionForce.hpp.
Referenced by BuskeCompressionForce< DIM >::serialize().
The documentation for this class was generated from the following files:
cell_based/src/population/forces/BuskeCompressionForce.hpp
cell_based/src/population/forces/BuskeCompressionForce.cpp