Chaste: AbstractParameterisedSystem< VECTOR > Class Template Reference
AbstractParameterisedSystem< VECTOR > Class Template Reference
#include <AbstractParameterisedSystem.hpp>
Public Member Functions
AbstractParameterisedSystem (unsigned numberOfStateVariables)
virtual ~AbstractParameterisedSystem ()
boost::shared_ptr< const
AbstractOdeSystemInformation > GetSystemInformation () const
std::string GetSystemName () const
unsigned GetNumberOfStateVariables () const
VECTOR & rGetStateVariables ()
VECTOR GetStateVariables ()
double GetStateVariable (unsigned index) const
double GetStateVariable (const std::string &rName) const
void SetStateVariable (unsigned index, double newValue)
void SetStateVariable (const std::string &rName, double newValue)
const std::vector< std::string > & rGetStateVariableNames () const
const std::vector< std::string > & rGetStateVariableUnits () const
unsigned GetStateVariableIndex (const std::string &rName) const
bool HasStateVariable (const std::string &rName) const
std::string GetStateVariableUnits (unsigned index) const
unsigned GetNumberOfParameters () const
double GetParameter (unsigned index) const
double GetParameter (const std::string &rName) const
void SetParameter (const std::string &rName, double value)
void SetParameter (unsigned index, double value)
const std::vector< std::string > & rGetParameterNames () const
const std::vector< std::string > & rGetParameterUnits () const
unsigned GetParameterIndex (const std::string &rName) const
bool HasParameter (const std::string &rName) const
std::string GetParameterUnits (unsigned index) const
double GetAnyVariable (unsigned index, double time=0.0, VECTOR *pDerivedQuantities=NULL)
double GetAnyVariable (const std::string &rName, double time=0.0, VECTOR *pDerivedQuantities=NULL)
unsigned GetAnyVariableIndex (const std::string &rName) const
bool HasAnyVariable (const std::string &rName) const
void SetAnyVariable (unsigned index, double value)
void SetAnyVariable (const std::string &rName, double value)
std::string GetAnyVariableUnits (unsigned index) const
std::string GetAnyVariableUnits (const std::string &rName) const
unsigned GetNumberOfDerivedQuantities () const
virtual VECTOR ComputeDerivedQuantities (double time, const VECTOR &rState)
VECTOR ComputeDerivedQuantitiesFromCurrentState (double time)
const std::vector< std::string > & rGetDerivedQuantityNames () const
const std::vector< std::string > & rGetDerivedQuantityUnits () const
unsigned GetDerivedQuantityIndex (const std::string &rName) const
bool HasDerivedQuantity (const std::string &rName) const
std::string GetDerivedQuantityUnits (unsigned index) const
unsigned GetNumberOfAttributes () const
bool HasAttribute (const std::string &rName) const
double GetAttribute (const std::string &rName) const
Protected Attributes
unsigned mNumberOfStateVariables
VECTOR mStateVariables
VECTOR mParameters
boost::shared_ptr
< AbstractOdeSystemInformation > mpSystemInfo
Detailed Description
template<typename VECTOR>
class AbstractParameterisedSystem< VECTOR >
This class contains the state variable and parameter vectors for an ODE system, along with methods to access these. It also holds the AbstractOdeSystemInformation pointer, and methods to access this object to provide information about the ODE system, such as state variable/parameter names and units.
Its main purpose is to be a common base class for both AbstractOdeSystem and AbstractCvodeCell, which require similar functionality but use different vector types.
Definition at line 49 of file AbstractParameterisedSystem.hpp.
Constructor & Destructor Documentation
template<typename VECTOR> AbstractParameterisedSystem< VECTOR >::AbstractParameterisedSystem (unsigned numberOfStateVariables) [inline]
Constructor.
Parameters:
numberOfStateVariables the number of state variables in the ODE system
Definition at line 42 of file AbstractParameterisedSystem.cpp.
References InitialiseEmptyVector(), AbstractParameterisedSystem< VECTOR >::mParameters, and AbstractParameterisedSystem< VECTOR >::mStateVariables.
template<typename VECTOR> AbstractParameterisedSystem< VECTOR >::~AbstractParameterisedSystem () [inline, virtual]
Virtual destructor.
Definition at line 50 of file AbstractParameterisedSystem.cpp.
Member Function Documentation
template<typename VECTOR> boost::shared_ptr< const AbstractOdeSystemInformation > AbstractParameterisedSystem< VECTOR >::GetSystemInformation () const [inline]
Get the object which provides information about this ODE system.
Definition at line 55 of file AbstractParameterisedSystem.cpp.
References AbstractParameterisedSystem< VECTOR >::mpSystemInfo.
Referenced by OdeSolution::CalculateDerivedQuantitiesAndParameters(), CvodeAdaptor::Solve(), and AbstractOneStepIvpOdeSolver::Solve().
template<typename VECTOR> std::string AbstractParameterisedSystem< VECTOR >::GetSystemName () const [inline]
Get the name of this system.
Definition at line 63 of file AbstractParameterisedSystem.cpp.
References AbstractParameterisedSystem< VECTOR >::mpSystemInfo.
template<typename VECTOR> unsigned AbstractParameterisedSystem< VECTOR >::GetNumberOfStateVariables () const [inline]
Get the number of state variables in the ODE system.
Returns:
mNumberOfStateVariables
Definition at line 74 of file AbstractParameterisedSystem.cpp.
References AbstractParameterisedSystem< VECTOR >::mNumberOfStateVariables.
Referenced by RungeKuttaFehlbergIvpOdeSolver::CalculateNextYValue(), RungeKutta4IvpOdeSolver::CalculateNextYValue(), RungeKutta2IvpOdeSolver::CalculateNextYValue(), HeunIvpOdeSolver::CalculateNextYValue(), EulerIvpOdeSolver::CalculateNextYValue(), BackwardEulerIvpOdeSolver::CalculateNextYValue(), RungeKuttaFehlbergIvpOdeSolver::InternalSolve(), CvodeAdaptor::SetupCvode(), RungeKuttaFehlbergIvpOdeSolver::Solve(), AbstractOneStepIvpOdeSolver::Solve(), AbstractIvpOdeSolver::SolveAndUpdateStateVariable(), AbstractCardiacTissue< ELEMENT_DIM, SPACE_DIM >::SolveCellSystems(), and AbstractOdeBasedCellCycleModel::UpdateCellCyclePhase().
template<typename VECTOR> VECTOR & AbstractParameterisedSystem< VECTOR >::rGetStateVariables () [inline]
Get the values of the state variables in the ODE system.
Definition at line 80 of file AbstractParameterisedSystem.cpp.
References AbstractParameterisedSystem< VECTOR >::mStateVariables.
Referenced by WntCellCycleModel::AdjustOdeParameters(), SingleOdeWntCellCycleModel::AdjustOdeParameters(), AbstractVanLeeuwen2009WntSwatCellCycleModel::AdjustOdeParameters(), Alarcon2004OxygenBasedCellCycleModel::AdjustOdeParameters(), WntCellCycleModel::ChangeCellProliferativeTypeDueToCurrentBetaCateninLevel(), AbstractVanLeeuwen2009WntSwatCellCycleModel::ChangeCellProliferativeTypeDueToCurrentBetaCateninLevel(), WntCellCycleModel::CreateCellCycleModel(), VanLeeuwen2009WntSwatCellCycleModelHypothesisTwo::CreateCellCycleModel(), VanLeeuwen2009WntSwatCellCycleModelHypothesisOne::CreateCellCycleModel(), StochasticWntCellCycleModel::CreateCellCycleModel(), SingleOdeWntCellCycleModel::CreateCellCycleModel(), TysonNovakCellCycleModel::CreateCellCycleModel(), Alarcon2004OxygenBasedCellCycleModel::CreateCellCycleModel(), SingleOdeWntCellCycleModel::GetBetaCateninConcentration(), AbstractVanLeeuwen2009WntSwatCellCycleModel::GetCytoplasmicBetaCateninLevel(), AbstractVanLeeuwen2009WntSwatCellCycleModel::GetMembraneBoundBetaCateninLevel(), AbstractVanLeeuwen2009WntSwatCellCycleModel::GetNuclearBetaCateninLevel(), AbstractOdeBasedCellCycleModel::GetProteinConcentrations(), AbstractWntOdeBasedCellCycleModel::ResetForDivision(), TysonNovakCellCycleModel::ResetForDivision(), Alarcon2004OxygenBasedCellCycleModel::ResetForDivision(), AbstractOdeBasedCellCycleModel::SetProteinConcentrationsForTestsOnly(), AbstractIvpOdeSolver::SolveAndUpdateStateVariable(), AbstractCardiacTissue< ELEMENT_DIM, SPACE_DIM >::SolveCellSystems(), and AbstractOdeBasedCellCycleModel::UpdateCellCyclePhase().
template<typename VECTOR> VECTOR AbstractParameterisedSystem< VECTOR >::GetStateVariables () [inline]
Get a copy of the state variable vector. Caller takes responsibility for freeing the vector.
Definition at line 86 of file AbstractParameterisedSystem.cpp.
References CopyVector(), and AbstractParameterisedSystem< VECTOR >::mStateVariables.
template<typename VECTOR> double AbstractParameterisedSystem< VECTOR >::GetStateVariable (unsigned index) const [inline]
Get the value of a given state variable.
Parameters:
index the index of the state variable
Definition at line 92 of file AbstractParameterisedSystem.cpp.
References EXCEPTION, GetVectorComponent(), AbstractParameterisedSystem< VECTOR >::mNumberOfStateVariables, and AbstractParameterisedSystem< VECTOR >::mStateVariables.
Referenced by AbstractParameterisedSystem< VECTOR >::GetStateVariable().
template<typename VECTOR> double AbstractParameterisedSystem< VECTOR >::GetStateVariable (const std::string & rName) const [inline]
Get the value of a given state variable.
Parameters:
rName the name of the state variable
Definition at line 102 of file AbstractParameterisedSystem.cpp.
References AbstractParameterisedSystem< VECTOR >::GetStateVariable(), and AbstractParameterisedSystem< VECTOR >::GetStateVariableIndex().
template<typename VECTOR> void AbstractParameterisedSystem< VECTOR >::SetStateVariable (unsigned index, double newValue) [inline]
Set the value of a single state variable in the ODE system.
Parameters:
index index of the state variable to be set
newValue new value of the state variable
Definition at line 108 of file AbstractParameterisedSystem.cpp.
References EXCEPTION, AbstractParameterisedSystem< VECTOR >::mNumberOfStateVariables, AbstractParameterisedSystem< VECTOR >::mStateVariables, and SetVectorComponent().
Referenced by AbstractParameterisedSystem< VECTOR >::SetStateVariable().
template<typename VECTOR> void AbstractParameterisedSystem< VECTOR >::SetStateVariable (const std::string & rName, double newValue) [inline]
Set the value of a single state variable in the ODE system.
Parameters:
rName name of the state variable to be set
newValue new value of the state variable
Definition at line 118 of file AbstractParameterisedSystem.cpp.
References AbstractParameterisedSystem< VECTOR >::GetStateVariableIndex(), and AbstractParameterisedSystem< VECTOR >::SetStateVariable().
template<typename VECTOR> const std::vector< std::string > & AbstractParameterisedSystem< VECTOR >::rGetStateVariableNames () const [inline]
Get the names of the state variables in the ODE system.
Definition at line 124 of file AbstractParameterisedSystem.cpp.
References AbstractParameterisedSystem< VECTOR >::mpSystemInfo.
template<typename VECTOR> const std::vector< std::string > & AbstractParameterisedSystem< VECTOR >::rGetStateVariableUnits () const [inline]
Get the units of the state variables in the ODE system.
Definition at line 131 of file AbstractParameterisedSystem.cpp.
References AbstractParameterisedSystem< VECTOR >::mpSystemInfo.
template<typename VECTOR> unsigned AbstractParameterisedSystem< VECTOR >::GetStateVariableIndex (const std::string & rName) const [inline]
This method is used to establish a state variable's position within the vector of state variables of an ODE system. This number can then be used with the methods GetStateVariable and GetStateVariableUnits.
Parameters:
rName the name of a state variable.
Returns:
the state variable's position within the vector of state variables associated with the ODE system.
Definition at line 138 of file AbstractParameterisedSystem.cpp.
References AbstractParameterisedSystem< VECTOR >::mpSystemInfo.
Referenced by AbstractParameterisedSystem< VECTOR >::GetStateVariable(), and AbstractParameterisedSystem< VECTOR >::SetStateVariable().
template<typename VECTOR> bool AbstractParameterisedSystem< VECTOR >::HasStateVariable (const std::string & rName) const [inline]
This method is used to establish whether a state variable is in an ODE system. You can then safely call GetStateVariableIndex without a try...catch statement.
Parameters:
rName the name of a state variable
Returns:
whether the state variable is in this ODE system
Definition at line 145 of file AbstractParameterisedSystem.cpp.
References AbstractParameterisedSystem< VECTOR >::mpSystemInfo.
template<typename VECTOR> std::string AbstractParameterisedSystem< VECTOR >::GetStateVariableUnits (unsigned index) const [inline]
Get the units of a state variable given its index in the ODE system.
Parameters:
index a state variable's position within the vector of state variables associated with the ODE system.
Returns:
the units of the state variable.
Definition at line 152 of file AbstractParameterisedSystem.cpp.
References AbstractParameterisedSystem< VECTOR >::mpSystemInfo.
template<typename VECTOR> unsigned AbstractParameterisedSystem< VECTOR >::GetNumberOfParameters () const [inline]
Get the number of parameters.
Definition at line 163 of file AbstractParameterisedSystem.cpp.
References GetVectorSize(), and AbstractParameterisedSystem< VECTOR >::mParameters.
Referenced by OdeSolution::rGetParameters().
template<typename VECTOR> double AbstractParameterisedSystem< VECTOR >::GetParameter (unsigned index) const [inline]
Get the value of a given parameter.
Parameters:
index the index of the parameter
Definition at line 169 of file AbstractParameterisedSystem.cpp.
References EXCEPTION, GetVectorComponent(), GetVectorSize(), and AbstractParameterisedSystem< VECTOR >::mParameters.
Referenced by AbstractParameterisedSystem< VECTOR >::GetParameter(), and OdeSolution::rGetParameters().
template<typename VECTOR> double AbstractParameterisedSystem< VECTOR >::GetParameter (const std::string & rName) const [inline]
Get the value of a given parameter.
Parameters:
rName the name of the parameter
Definition at line 195 of file AbstractParameterisedSystem.cpp.
References AbstractParameterisedSystem< VECTOR >::GetParameter(), and AbstractParameterisedSystem< VECTOR >::GetParameterIndex().
template<typename VECTOR> void AbstractParameterisedSystem< VECTOR >::SetParameter (const std::string & rName, double value) [inline]
Set the value of a given parameter.
Parameters:
rName the name of the parameter
value the value
Definition at line 189 of file AbstractParameterisedSystem.cpp.
References AbstractParameterisedSystem< VECTOR >::GetParameterIndex(), AbstractParameterisedSystem< VECTOR >::mParameters, and SetVectorComponent().
Referenced by HeartConfigRelatedCellFactory< SPACE_DIM >::SetCellParameters().
template<typename VECTOR> void AbstractParameterisedSystem< VECTOR >::SetParameter (unsigned index, double value) [inline]
Set the value of a given parameter.
Parameters:
index the index of the parameter
value the value
Definition at line 179 of file AbstractParameterisedSystem.cpp.
References EXCEPTION, GetVectorSize(), AbstractParameterisedSystem< VECTOR >::mParameters, and SetVectorComponent().
template<typename VECTOR> const std::vector< std::string > & AbstractParameterisedSystem< VECTOR >::rGetParameterNames () const [inline]
Get the names of the parameters in the ODE system.
Definition at line 201 of file AbstractParameterisedSystem.cpp.
References AbstractParameterisedSystem< VECTOR >::mpSystemInfo.
template<typename VECTOR> const std::vector< std::string > & AbstractParameterisedSystem< VECTOR >::rGetParameterUnits () const [inline]
Get the units of the parameters in the ODE system.
Definition at line 208 of file AbstractParameterisedSystem.cpp.
References AbstractParameterisedSystem< VECTOR >::mpSystemInfo.
template<typename VECTOR> unsigned AbstractParameterisedSystem< VECTOR >::GetParameterIndex (const std::string & rName) const [inline]
This method is used to establish a parameter's position within the vector of parameters of an ODE system. This number can then be used with the methods GetParameterUnits and GetParameter.
Parameters:
rName the name of a parameter
Returns:
the parameter's position within the vector of parameters associated with the ODE system.
Definition at line 215 of file AbstractParameterisedSystem.cpp.
References AbstractParameterisedSystem< VECTOR >::mpSystemInfo.
Referenced by AbstractParameterisedSystem< VECTOR >::GetParameter(), HeartConfigRelatedCellFactory< SPACE_DIM >::SetCellParameters(), and AbstractParameterisedSystem< VECTOR >::SetParameter().
template<typename VECTOR> bool AbstractParameterisedSystem< VECTOR >::HasParameter (const std::string & rName) const [inline]
This method is used to establish whether a parameter is in an ODE system. You can then safely call GetParameterIndex without a try...catch statement.
Parameters:
rName the name of a parameter
Returns:
whether the parameter is in this ODE system
Definition at line 222 of file AbstractParameterisedSystem.cpp.
References AbstractParameterisedSystem< VECTOR >::mpSystemInfo.
template<typename VECTOR> std::string AbstractParameterisedSystem< VECTOR >::GetParameterUnits (unsigned index) const [inline]
Get the units of a parameter given its index in the ODE system.
Parameters:
index a state variable's position within the vector of state variables associated with the ODE system.
Returns:
the units of the state variable.
Definition at line 229 of file AbstractParameterisedSystem.cpp.
References AbstractParameterisedSystem< VECTOR >::mpSystemInfo.
template<typename VECTOR> double AbstractParameterisedSystem< VECTOR >::GetAnyVariable (unsigned index, double time = 0.0, VECTOR * pDerivedQuantities = NULL) [inline]
Get the value of a variable, whether a state variable, parameter, or derived quantity.
Note that if the variable is a derived quantity, this method will compute all derived quantities, so may not be very efficient. To avoid this, pass a pre-computed vector of derived quantities as the optional third argument.
Parameters:
index the index of the variable, as given by GetAnyVariableIndex.
time the current simulation time, possibly needed if the variable is a derived quantity.
pDerivedQuantities optional vector of pre-computed derived quantity values.
Definition at line 240 of file AbstractParameterisedSystem.cpp.
References AbstractParameterisedSystem< VECTOR >::ComputeDerivedQuantitiesFromCurrentState(), DeleteVector(), EXCEPTION, AbstractParameterisedSystem< VECTOR >::GetNumberOfDerivedQuantities(), GetVectorComponent(), GetVectorSize(), AbstractParameterisedSystem< VECTOR >::mNumberOfStateVariables, AbstractParameterisedSystem< VECTOR >::mParameters, and AbstractParameterisedSystem< VECTOR >::mStateVariables.
Referenced by AbstractParameterisedSystem< VECTOR >::GetAnyVariable(), and AbstractCardiacProblem< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::WriteExtraVariablesOneStep().
template<typename VECTOR> double AbstractParameterisedSystem< VECTOR >::GetAnyVariable (const std::string & rName, double time = 0.0, VECTOR * pDerivedQuantities = NULL) [inline]
Get the value of a variable, whether a state variable, parameter, or derived quantity.
Note that if the variable is a derived quantity, this method will compute all derived quantities, so may not be very efficient. To avoid this, pass a pre-computed vector of derived quantities as the optional third argument.
Parameters:
rName the name of the variable, (this method is the same as doing GetAnyVariableIndex(rName) and then calling the method above).
time the current simulation time, possibly needed if the variable is a derived quantity.
pDerivedQuantities optional vector of pre-computed derived quantity values.
Definition at line 277 of file AbstractParameterisedSystem.cpp.
References AbstractParameterisedSystem< VECTOR >::GetAnyVariable(), and AbstractParameterisedSystem< VECTOR >::GetAnyVariableIndex().
template<typename VECTOR> unsigned AbstractParameterisedSystem< VECTOR >::GetAnyVariableIndex (const std::string & rName) const [inline]
Get the index of a variable, whether a state variable, parameter, or derived quantity, with the given name. The returned index is suitable for use with GetAnyVariableUnits, GetAnyVariable, etc.
Parameters:
rName the name of a variable
Definition at line 285 of file AbstractParameterisedSystem.cpp.
References AbstractParameterisedSystem< VECTOR >::mpSystemInfo.
Referenced by AbstractParameterisedSystem< VECTOR >::GetAnyVariable(), AbstractParameterisedSystem< VECTOR >::GetAnyVariableUnits(), AbstractParameterisedSystem< VECTOR >::SetAnyVariable(), and AbstractCardiacProblem< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::WriteExtraVariablesOneStep().
template<typename VECTOR> bool AbstractParameterisedSystem< VECTOR >::HasAnyVariable (const std::string & rName) const [inline]
This method is used to establish whether a variable is in an ODE system's state vars, parameters or derived quantitites. You can then safely call GetAnyVariableIndex without a try...catch statement.
Parameters:
rName the name of a variable
Returns:
whether the variable is in this ODE system
Definition at line 292 of file AbstractParameterisedSystem.cpp.
References AbstractParameterisedSystem< VECTOR >::mpSystemInfo.
template<typename VECTOR> void AbstractParameterisedSystem< VECTOR >::SetAnyVariable (unsigned index, double value) [inline]
Set the value of a variable, whether a state variable or parameter. Attempting to set the value of a derived quantity will raise an exception.
Parameters:
index the index of the variable, as given by GetAnyVariableIndex.
value the value to give the variable.
Definition at line 299 of file AbstractParameterisedSystem.cpp.
References EXCEPTION, GetVectorSize(), AbstractParameterisedSystem< VECTOR >::mNumberOfStateVariables, AbstractParameterisedSystem< VECTOR >::mParameters, AbstractParameterisedSystem< VECTOR >::mStateVariables, and SetVectorComponent().
Referenced by AbstractParameterisedSystem< VECTOR >::SetAnyVariable().
template<typename VECTOR> void AbstractParameterisedSystem< VECTOR >::SetAnyVariable (const std::string & rName, double value) [inline]
Set the value of a variable, whether a state variable or parameter. Attempting to set the value of a derived quantity will raise an exception.
Parameters:
rName the name of the variable.
value the value to give the variable.
Definition at line 316 of file AbstractParameterisedSystem.cpp.
References AbstractParameterisedSystem< VECTOR >::GetAnyVariableIndex(), and AbstractParameterisedSystem< VECTOR >::SetAnyVariable().
template<typename VECTOR> std::string AbstractParameterisedSystem< VECTOR >::GetAnyVariableUnits (unsigned index) const [inline]
Get the units of a variable, whether a state variable, parameter, or derived quantity, given its index as returned by GetAnyVariableIndex.
Parameters:
index an index from GetAnyVariableIndex.
Returns:
the units of the variable.
Definition at line 322 of file AbstractParameterisedSystem.cpp.
References AbstractParameterisedSystem< VECTOR >::mpSystemInfo.
Referenced by AbstractParameterisedSystem< VECTOR >::GetAnyVariableUnits().
template<typename VECTOR> std::string AbstractParameterisedSystem< VECTOR >::GetAnyVariableUnits (const std::string & rName) const [inline]
Get the units of a variable, whether a state variable, parameter, or derived quantity, given its index as returned by GetAnyVariableIndex.
Parameters:
rName the name of any variable in the model.
Returns:
the units of the variable.
Definition at line 329 of file AbstractParameterisedSystem.cpp.
References AbstractParameterisedSystem< VECTOR >::GetAnyVariableIndex(), and AbstractParameterisedSystem< VECTOR >::GetAnyVariableUnits().
template<typename VECTOR> unsigned AbstractParameterisedSystem< VECTOR >::GetNumberOfDerivedQuantities () const [inline]
Get the number of derived quantities.
Definition at line 339 of file AbstractParameterisedSystem.cpp.
References AbstractParameterisedSystem< VECTOR >::mpSystemInfo.
Referenced by AbstractParameterisedSystem< VECTOR >::GetAnyVariable(), and OdeSolution::rGetDerivedQuantities().
template<typename VECTOR> VECTOR AbstractParameterisedSystem< VECTOR >::ComputeDerivedQuantities (double time, const VECTOR & rState) [inline, virtual]
Compute the derived quantities from the given system state. Uses the current values for the parameters.
Parameters:
time the time at which to compute the derived quantities
rState values for the state variables
Definition at line 346 of file AbstractParameterisedSystem.cpp.
References EXCEPTION.
Referenced by AbstractParameterisedSystem< VECTOR >::ComputeDerivedQuantitiesFromCurrentState(), and OdeSolution::rGetDerivedQuantities().
template<typename VECTOR> VECTOR AbstractParameterisedSystem< VECTOR >::ComputeDerivedQuantitiesFromCurrentState (double time) [inline]
Compute the derived quantities based on the current system state.
Parameters:
time the time at which to compute the derived quantities
Definition at line 353 of file AbstractParameterisedSystem.cpp.
References AbstractParameterisedSystem< VECTOR >::ComputeDerivedQuantities(), and AbstractParameterisedSystem< VECTOR >::mStateVariables.
Referenced by AbstractParameterisedSystem< VECTOR >::GetAnyVariable().
template<typename VECTOR> const std::vector< std::string > & AbstractParameterisedSystem< VECTOR >::rGetDerivedQuantityNames () const [inline]
Get the vector of derived quantity names.
Definition at line 359 of file AbstractParameterisedSystem.cpp.
References AbstractParameterisedSystem< VECTOR >::mpSystemInfo.
template<typename VECTOR> const std::vector< std::string > & AbstractParameterisedSystem< VECTOR >::rGetDerivedQuantityUnits () const [inline]
Get the vector of derived quantity units.
Definition at line 366 of file AbstractParameterisedSystem.cpp.
References AbstractParameterisedSystem< VECTOR >::mpSystemInfo.
template<typename VECTOR> unsigned AbstractParameterisedSystem< VECTOR >::GetDerivedQuantityIndex (const std::string & rName) const [inline]
Get the index of a derived quantity, given its name.
Parameters:
rName the name of a derived quantity.
Definition at line 373 of file AbstractParameterisedSystem.cpp.
References AbstractParameterisedSystem< VECTOR >::mpSystemInfo.
template<typename VECTOR> bool AbstractParameterisedSystem< VECTOR >::HasDerivedQuantity (const std::string & rName) const [inline]
This method is used to establish whether a derived quantity is in an ODE system. You can then safely call GetDerivedQuantityIndex without a try...catch statement.
Parameters:
rName the name of a derived quantity
Returns:
whether the derived quantity is in this ODE system
Definition at line 380 of file AbstractParameterisedSystem.cpp.
References AbstractParameterisedSystem< VECTOR >::mpSystemInfo.
template<typename VECTOR> std::string AbstractParameterisedSystem< VECTOR >::GetDerivedQuantityUnits (unsigned index) const [inline]
Get the units of a derived quantity.
Parameters:
index an index from GetDerivedQuantityIndex.
Returns:
the units of the variable.
Definition at line 387 of file AbstractParameterisedSystem.cpp.
References AbstractParameterisedSystem< VECTOR >::mpSystemInfo.
template<typename VECTOR> unsigned AbstractParameterisedSystem< VECTOR >::GetNumberOfAttributes () const [inline]
Return the number of named attributes that this system has.
Definition at line 395 of file AbstractParameterisedSystem.cpp.
References AbstractParameterisedSystem< VECTOR >::mpSystemInfo.
template<typename VECTOR> bool AbstractParameterisedSystem< VECTOR >::HasAttribute (const std::string & rName) const [inline]
Test whether this system has a particular named attribute.
Parameters:
rName the attribute name.
Definition at line 402 of file AbstractParameterisedSystem.cpp.
References AbstractParameterisedSystem< VECTOR >::mpSystemInfo.
template<typename VECTOR> double AbstractParameterisedSystem< VECTOR >::GetAttribute (const std::string & rName) const [inline]
Get the value of a named attribute.
Parameters:
rName the attribute name.
Definition at line 409 of file AbstractParameterisedSystem.cpp.
References AbstractParameterisedSystem< VECTOR >::mpSystemInfo.
Member Data Documentation
template<typename VECTOR> unsigned AbstractParameterisedSystem< VECTOR >::mNumberOfStateVariables [protected]
The number of state variables in the system.
Definition at line 53 of file AbstractParameterisedSystem.hpp.
Referenced by AbstractParameterisedSystem< VECTOR >::GetAnyVariable(), AbstractParameterisedSystem< VECTOR >::GetNumberOfStateVariables(), AbstractParameterisedSystem< VECTOR >::GetStateVariable(), AbstractParameterisedSystem< VECTOR >::SetAnyVariable(), and AbstractParameterisedSystem< VECTOR >::SetStateVariable().
template<typename VECTOR> VECTOR AbstractParameterisedSystem< VECTOR >::mStateVariables [protected]
Vector containing the current values of the state variables.
Definition at line 56 of file AbstractParameterisedSystem.hpp.
Referenced by AbstractParameterisedSystem< VECTOR >::AbstractParameterisedSystem(), AbstractParameterisedSystem< VECTOR >::ComputeDerivedQuantitiesFromCurrentState(), AbstractParameterisedSystem< VECTOR >::GetAnyVariable(), AbstractParameterisedSystem< VECTOR >::GetStateVariable(), AbstractParameterisedSystem< VECTOR >::GetStateVariables(), AbstractParameterisedSystem< VECTOR >::rGetStateVariables(), AbstractParameterisedSystem< VECTOR >::SetAnyVariable(), and AbstractParameterisedSystem< VECTOR >::SetStateVariable().
template<typename VECTOR> VECTOR AbstractParameterisedSystem< VECTOR >::mParameters [protected]
Vector containing parameter values.
Definition at line 59 of file AbstractParameterisedSystem.hpp.
Referenced by AbstractParameterisedSystem< VECTOR >::AbstractParameterisedSystem(), AbstractParameterisedSystem< VECTOR >::GetAnyVariable(), AbstractParameterisedSystem< VECTOR >::GetNumberOfParameters(), AbstractParameterisedSystem< VECTOR >::GetParameter(), AbstractParameterisedSystem< VECTOR >::SetAnyVariable(), and AbstractParameterisedSystem< VECTOR >::SetParameter().
template<typename VECTOR> boost::shared_ptr<AbstractOdeSystemInformation> AbstractParameterisedSystem< VECTOR >::mpSystemInfo [protected]
Information about the concrete ODE system class.
Subclasses need to set this in their constructor to point to an instance of a suitable class. See for example the OdeSystemInformation class.
Definition at line 67 of file AbstractParameterisedSystem.hpp.
Referenced by AbstractParameterisedSystem< VECTOR >::GetAnyVariableIndex(), AbstractParameterisedSystem< VECTOR >::GetAnyVariableUnits(), AbstractParameterisedSystem< VECTOR >::GetAttribute(), AbstractParameterisedSystem< VECTOR >::GetDerivedQuantityIndex(), AbstractParameterisedSystem< VECTOR >::GetDerivedQuantityUnits(), AbstractParameterisedSystem< VECTOR >::GetNumberOfAttributes(), AbstractParameterisedSystem< VECTOR >::GetNumberOfDerivedQuantities(), AbstractParameterisedSystem< VECTOR >::GetParameterIndex(), AbstractParameterisedSystem< VECTOR >::GetParameterUnits(), AbstractParameterisedSystem< VECTOR >::GetStateVariableIndex(), AbstractParameterisedSystem< VECTOR >::GetStateVariableUnits(), AbstractParameterisedSystem< VECTOR >::GetSystemInformation(), AbstractParameterisedSystem< VECTOR >::GetSystemName(), AbstractParameterisedSystem< VECTOR >::HasAnyVariable(), AbstractParameterisedSystem< VECTOR >::HasAttribute(), AbstractParameterisedSystem< VECTOR >::HasDerivedQuantity(), AbstractParameterisedSystem< VECTOR >::HasParameter(), AbstractParameterisedSystem< VECTOR >::HasStateVariable(), AbstractParameterisedSystem< VECTOR >::rGetDerivedQuantityNames(), AbstractParameterisedSystem< VECTOR >::rGetDerivedQuantityUnits(), AbstractParameterisedSystem< VECTOR >::rGetParameterNames(), AbstractParameterisedSystem< VECTOR >::rGetParameterUnits(), AbstractParameterisedSystem< VECTOR >::rGetStateVariableNames(), and AbstractParameterisedSystem< VECTOR >::rGetStateVariableUnits().
The documentation for this class was generated from the following files:
ode/src/common/AbstractParameterisedSystem.hpp
ode/src/common/AbstractParameterisedSystem.cpp