Chaste: MonodomainAssembler< ELEMENT_DIM, SPACE_DIM > Class Template Reference
MonodomainAssembler< ELEMENT_DIM, SPACE_DIM > Class Template Reference
#include <MonodomainAssembler.hpp>
Public Member Functions
MonodomainAssembler (AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM > *pMesh, MonodomainTissue< ELEMENT_DIM, SPACE_DIM > *pTissue, unsigned numQuadPoints=2)
Protected Member Functions
c_matrix< double,
1 *(ELEMENT_DIM+1),
1 *(ELEMENT_DIM+1)> ComputeMatrixTerm (c_vector< double, ELEMENT_DIM+1 > &rPhi, c_matrix< double, SPACE_DIM, ELEMENT_DIM+1 > &rGradPhi, ChastePoint< SPACE_DIM > &rX, c_vector< double, 1 > &rU, c_matrix< double, 1, SPACE_DIM > &rGradU, Element< ELEMENT_DIM, SPACE_DIM > *pElement)
c_vector< double,
1 *(ELEMENT_DIM+1)> ComputeVectorTerm (c_vector< double, ELEMENT_DIM+1 > &rPhi, c_matrix< double, SPACE_DIM, ELEMENT_DIM+1 > &rGradPhi, ChastePoint< SPACE_DIM > &rX, c_vector< double, 1 > &rU, c_matrix< double, 1, SPACE_DIM > &rGradU, Element< ELEMENT_DIM, SPACE_DIM > *pElement)
c_vector< double, ELEMENT_DIM > ComputeVectorSurfaceTerm (const BoundaryElement< ELEMENT_DIM-1, SPACE_DIM > &rSurfaceElement, c_vector< double, ELEMENT_DIM > &rPhi, ChastePoint< SPACE_DIM > &rX)
void ResetInterpolatedQuantities (void)
void IncrementInterpolatedQuantities (double phiI, const Node< SPACE_DIM > *pNode)
Protected Attributes
HeartConfig * mpConfig
double mIionic
double mIIntracellularStimulus
MassMatrixAssembler
< ELEMENT_DIM, SPACE_DIM > mMassMatrixAssembler
MonodomainStiffnessMatrixAssembler
< ELEMENT_DIM, SPACE_DIM > mStiffnessMatrixAssembler
Detailed Description
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM>
class MonodomainAssembler< ELEMENT_DIM, SPACE_DIM >
Assembler for assembling the LHS matrix and RHS vector of the linear systems solved in monodomain problems
Definition at line 43 of file MonodomainAssembler.hpp.
Constructor & Destructor Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> MonodomainAssembler< ELEMENT_DIM, SPACE_DIM >::MonodomainAssembler (AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM > * pMesh, MonodomainTissue< ELEMENT_DIM, SPACE_DIM > * pTissue, unsigned numQuadPoints = 2) [inline]
Constructor
Parameters:
pMesh pointer to the mesh
pTissue pointer to the tissue
numQuadPoints number of quadrature points (defaults to 2)
Definition at line 89 of file MonodomainAssembler.cpp.
References HeartConfig::Instance(), and MonodomainAssembler< ELEMENT_DIM, SPACE_DIM >::mpConfig.
Member Function Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> c_matrix< double, 1 *(ELEMENT_DIM+1), 1 *(ELEMENT_DIM+1)> MonodomainAssembler< ELEMENT_DIM, SPACE_DIM >::ComputeMatrixTerm (c_vector< double, ELEMENT_DIM+1 > & rPhi, c_matrix< double, SPACE_DIM, ELEMENT_DIM+1 > & rGradPhi, ChastePoint< SPACE_DIM > & rX, c_vector< double, 1 > & rU, c_matrix< double, 1, SPACE_DIM > & rGradU, Element< ELEMENT_DIM, SPACE_DIM > * pElement) [inline, protected]
ComputeMatrixTerm()
This method is called by AssembleOnElement() and tells the assembler the contribution to add to the element stiffness matrix.
Parameters:
rPhi The basis functions, rPhi(i) = phi_i, i=1..numBases
rGradPhi Basis gradients, rGradPhi(i,j) = d(phi_j)/d(X_i)
rX The point in space
rU The unknown as a vector, u(i) = u_i
rGradU The gradient of the unknown as a matrix, rGradU(i,j) = d(u_i)/d(X_j)
pElement Pointer to the element
Am and Cm are set as scaling factors for the mass matrix in its constructor.
Definition at line 36 of file MonodomainAssembler.cpp.
References PdeSimulationTime::GetPdeTimeStepInverse(), MonodomainAssembler< ELEMENT_DIM, SPACE_DIM >::mMassMatrixAssembler, and MonodomainAssembler< ELEMENT_DIM, SPACE_DIM >::mStiffnessMatrixAssembler.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> c_vector< double, 1 *(ELEMENT_DIM+1)> MonodomainAssembler< ELEMENT_DIM, SPACE_DIM >::ComputeVectorTerm (c_vector< double, ELEMENT_DIM+1 > & rPhi, c_matrix< double, SPACE_DIM, ELEMENT_DIM+1 > & rGradPhi, ChastePoint< SPACE_DIM > & rX, c_vector< double, 1 > & rU, c_matrix< double, 1, SPACE_DIM > & rGradU, Element< ELEMENT_DIM, SPACE_DIM > * pElement) [inline, protected]
ComputeVectorTerm()
This method is called by AssembleOnElement() and tells the assembler the contribution to add to the element stiffness vector.
Parameters:
rPhi The basis functions, rPhi(i) = phi_i, i=1..numBases
rGradPhi Basis gradients, rGradPhi(i,j) = d(phi_j)/d(X_i)
rX The point in space
rU The unknown as a vector, u(i) = u_i
rGradU The gradient of the unknown as a matrix, rGradU(i,j) = d(u_i)/d(X_j)
pElement Pointer to the element
Definition at line 52 of file MonodomainAssembler.cpp.
References HeartConfig::GetCapacitance(), PdeSimulationTime::GetPdeTimeStepInverse(), HeartConfig::GetSurfaceAreaToVolumeRatio(), MonodomainAssembler< ELEMENT_DIM, SPACE_DIM >::mIIntracellularStimulus, MonodomainAssembler< ELEMENT_DIM, SPACE_DIM >::mIionic, and MonodomainAssembler< ELEMENT_DIM, SPACE_DIM >::mpConfig.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> c_vector< double, ELEMENT_DIM > MonodomainAssembler< ELEMENT_DIM, SPACE_DIM >::ComputeVectorSurfaceTerm (const BoundaryElement< ELEMENT_DIM-1, SPACE_DIM > & rSurfaceElement, c_vector< double, ELEMENT_DIM > & rPhi, ChastePoint< SPACE_DIM > & rX) [inline, protected, virtual]
ComputeVectorSurfaceTerm()
This method is called by AssembleOnSurfaceElement() and tells the assembler what to add to the element stiffness matrix arising from surface element contributions.
Parameters:
rSurfaceElement the element which is being considered.
rPhi The basis functions, rPhi(i) = phi_i, i=1..numBases
rX The point in space
Reimplemented from AbstractFeObjectAssembler< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM, CAN_ASSEMBLE_VECTOR, CAN_ASSEMBLE_MATRIX, INTERPOLATION_LEVEL >.
Definition at line 69 of file MonodomainAssembler.cpp.
References AbstractFeObjectAssembler< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM, CAN_ASSEMBLE_VECTOR, CAN_ASSEMBLE_MATRIX, INTERPOLATION_LEVEL >::mpBoundaryConditions.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void MonodomainAssembler< ELEMENT_DIM, SPACE_DIM >::ResetInterpolatedQuantities (void) [inline, protected, virtual]
Overridden ResetInterpolatedQuantities() method.
Reimplemented from AbstractFeObjectAssembler< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM, CAN_ASSEMBLE_VECTOR, CAN_ASSEMBLE_MATRIX, INTERPOLATION_LEVEL >.
Definition at line 123 of file MonodomainAssembler.hpp.
References MonodomainAssembler< ELEMENT_DIM, SPACE_DIM >::mIIntracellularStimulus, and MonodomainAssembler< ELEMENT_DIM, SPACE_DIM >::mIionic.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void MonodomainAssembler< ELEMENT_DIM, SPACE_DIM >::IncrementInterpolatedQuantities (double phiI, const Node< SPACE_DIM > * pNode) [inline, protected, virtual]
Overridden IncrementInterpolatedQuantities() method.
Parameters:
phiI
pNode
Reimplemented from AbstractFeObjectAssembler< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM, CAN_ASSEMBLE_VECTOR, CAN_ASSEMBLE_MATRIX, INTERPOLATION_LEVEL >.
Definition at line 81 of file MonodomainAssembler.cpp.
References Node< SPACE_DIM >::GetIndex(), MonodomainAssembler< ELEMENT_DIM, SPACE_DIM >::mIIntracellularStimulus, MonodomainAssembler< ELEMENT_DIM, SPACE_DIM >::mIionic, and AbstractCardiacFeObjectAssembler< ELEMENT_DIM, SPACE_DIM, 1, true, true, CARDIAC >::mpCardiacTissue.
Member Data Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> HeartConfig* MonodomainAssembler< ELEMENT_DIM, SPACE_DIM >::mpConfig [protected]
Local cache of the configuration singleton instance
Definition at line 48 of file MonodomainAssembler.hpp.
Referenced by MonodomainAssembler< ELEMENT_DIM, SPACE_DIM >::ComputeVectorTerm(), and MonodomainAssembler< ELEMENT_DIM, SPACE_DIM >::MonodomainAssembler().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> double MonodomainAssembler< ELEMENT_DIM, SPACE_DIM >::mIionic [protected]
Ionic current to be interpolated from cache
Definition at line 51 of file MonodomainAssembler.hpp.
Referenced by MonodomainAssembler< ELEMENT_DIM, SPACE_DIM >::ComputeVectorTerm(), MonodomainAssembler< ELEMENT_DIM, SPACE_DIM >::IncrementInterpolatedQuantities(), and MonodomainAssembler< ELEMENT_DIM, SPACE_DIM >::ResetInterpolatedQuantities().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> double MonodomainAssembler< ELEMENT_DIM, SPACE_DIM >::mIIntracellularStimulus [protected]
Intracellular stimulus to be interpolated from cache
Definition at line 53 of file MonodomainAssembler.hpp.
Referenced by MonodomainAssembler< ELEMENT_DIM, SPACE_DIM >::ComputeVectorTerm(), MonodomainAssembler< ELEMENT_DIM, SPACE_DIM >::IncrementInterpolatedQuantities(), and MonodomainAssembler< ELEMENT_DIM, SPACE_DIM >::ResetInterpolatedQuantities().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> MassMatrixAssembler<ELEMENT_DIM, SPACE_DIM> MonodomainAssembler< ELEMENT_DIM, SPACE_DIM >::mMassMatrixAssembler [protected]
Assembler for the mass matrix
Definition at line 56 of file MonodomainAssembler.hpp.
Referenced by MonodomainAssembler< ELEMENT_DIM, SPACE_DIM >::ComputeMatrixTerm().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> MonodomainStiffnessMatrixAssembler<ELEMENT_DIM, SPACE_DIM> MonodomainAssembler< ELEMENT_DIM, SPACE_DIM >::mStiffnessMatrixAssembler [protected]
Assembler for the stiffness matrix
Definition at line 59 of file MonodomainAssembler.hpp.
Referenced by MonodomainAssembler< ELEMENT_DIM, SPACE_DIM >::ComputeMatrixTerm().
The documentation for this class was generated from the following files:
heart/src/solver/electrics/MonodomainAssembler.hpp
heart/src/solver/electrics/MonodomainAssembler.cpp