Chaste: BasicBidomainSolver< ELEMENT_DIM, SPACE_DIM > Class Template Reference
BasicBidomainSolver< ELEMENT_DIM, SPACE_DIM > Class Template Reference
#include <BasicBidomainSolver.hpp>
Public Member Functions
BasicBidomainSolver (bool bathSimulation, AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM > *pMesh, BidomainTissue< SPACE_DIM > *pTissue, BoundaryConditionsContainer< ELEMENT_DIM, SPACE_DIM, 2 > *pBcc, unsigned numQuadPoints=2)
virtual ~BasicBidomainSolver ()
Protected Member Functions
void SetupLinearSystem (Vec currentSolution, bool computeMatrix)
virtual void InitialiseAssembler ()
Detailed Description
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM>
class BasicBidomainSolver< ELEMENT_DIM, SPACE_DIM >
A simple bidomain solver, which uses assembly to set up the right-hand-side (RHS) vector of the linear system to be solved. Much slower than MatrixBasedBidomainSolver, which computes the RHS with a matrix-vector product.
Definition at line 55 of file BasicBidomainSolver.hpp.
Constructor & Destructor Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> BasicBidomainSolver< ELEMENT_DIM, SPACE_DIM >::BasicBidomainSolver (bool bathSimulation, AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM > * pMesh, BidomainTissue< SPACE_DIM > * pTissue, BoundaryConditionsContainer< ELEMENT_DIM, SPACE_DIM, 2 > * pBcc, unsigned numQuadPoints = 2) [inline]
Constructor
Parameters:
bathSimulation Whether the simulation involves a perfusing bath
pMesh pointer to the mesh
pTissue pointer to the tissue
pBcc pointer to the boundary conditions
numQuadPoints number of quadrature points (defaults to 2)
Definition at line 34 of file BasicBidomainSolver.cpp.
References EXCEPTION, HeartConfig::Instance(), and AbstractCardiacTissue< SPACE_DIM >::SetCacheReplication().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> virtual BasicBidomainSolver< ELEMENT_DIM, SPACE_DIM >::~BasicBidomainSolver () [inline, virtual]
Destructor.
Definition at line 96 of file BasicBidomainSolver.hpp.
Member Function Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void BasicBidomainSolver< ELEMENT_DIM, SPACE_DIM >::SetupLinearSystem (Vec currentSolution, bool computeMatrix) [inline, protected, virtual]
Implemented SetupLinearSystem() method, which uses the BidomainAssembler to assemble the LHS matrix if required, and uses the BidomainAssembler to *assemble* the RHS vector. Much slower than doing matrix-based RHS setup, which is done in MatrixBasedBidomainSolver
Parameters:
currentSolution Solution at current time
computeMatrix Whether to compute the matrix of the linear system
Implements AbstractLinearPdeSolver< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >.
Definition at line 52 of file BasicBidomainSolver.cpp.
References BoundaryConditionsContainer< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::ApplyDirichletToLinearProblem(), LinearSystem::AssembleFinalLhsMatrix(), LinearSystem::AssembleRhsVector(), AbstractBidomainSolver< ELEMENT_DIM, SPACE_DIM >::FinaliseForBath(), BasicBidomainSolver< ELEMENT_DIM, SPACE_DIM >::InitialiseAssembler(), AbstractBidomainSolver< ELEMENT_DIM, SPACE_DIM >::mBathSimulation, AbstractBidomainSolver< ELEMENT_DIM, SPACE_DIM >::mpBidomainAssembler, AbstractBidomainSolver< ELEMENT_DIM, SPACE_DIM >::mpBoundaryConditions, AbstractLinearPdeSolver< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::mpLinearSystem, LinearSystem::rGetLhsMatrix(), and LinearSystem::rGetRhsVector().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void BasicBidomainSolver< ELEMENT_DIM, SPACE_DIM >::InitialiseAssembler () [inline, protected, virtual]
Initialise the bidomain assembler. Can be overloaded
Definition at line 100 of file BasicBidomainSolver.cpp.
References AbstractBidomainSolver< ELEMENT_DIM, SPACE_DIM >::mBathSimulation, AbstractBidomainSolver< ELEMENT_DIM, SPACE_DIM >::mNumQuadPoints, AbstractBidomainSolver< ELEMENT_DIM, SPACE_DIM >::mpBidomainAssembler, AbstractBidomainSolver< ELEMENT_DIM, SPACE_DIM >::mpBidomainTissue, and AbstractLinearPdeSolver< ELEMENT_DIM, SPACE_DIM, PROBLEM_DIM >::mpMesh.
Referenced by BasicBidomainSolver< ELEMENT_DIM, SPACE_DIM >::SetupLinearSystem().
The documentation for this class was generated from the following files:
heart/src/solver/electrics/BasicBidomainSolver.hpp
heart/src/solver/electrics/BasicBidomainSolver.cpp