Chaste: FixedDurationGenerationBasedCellCycleModel Class Reference
FixedDurationGenerationBasedCellCycleModel Class Reference
#include <FixedDurationGenerationBasedCellCycleModel.hpp>
Public Member Functions
FixedDurationGenerationBasedCellCycleModel ()
AbstractCellCycleModel * CreateCellCycleModel ()
virtual void OutputCellCycleModelParameters (out_stream &rParamsFile)
Private Member Functions
template<class Archive>
void serialize (Archive &archive, const unsigned int version)
Friends
class boost::serialization::access
Detailed Description
Fixed cell-cycle model.
Cell cycle time is deterministic for stem and transit cells (with values StemCellG1Duration + SG2MDuration and TransitCellG1Duration + SG2MDuration (values found in AbstractCellCycleModel))
Definition at line 40 of file FixedDurationGenerationBasedCellCycleModel.hpp.
Constructor & Destructor Documentation
FixedDurationGenerationBasedCellCycleModel::FixedDurationGenerationBasedCellCycleModel ()
Default constructor. Note that mBirthTime is set in AbstractCellCycleModel() and mG1Duration is set in AbstractSimpleCellCycleModel().
Definition at line 30 of file FixedDurationGenerationBasedCellCycleModel.cpp.
Referenced by CreateCellCycleModel().
Member Function Documentation
template<class Archive> void FixedDurationGenerationBasedCellCycleModel::serialize (Archive & archive, const unsigned int version) [inline, private]
Archive the cell-cycle model, never used directly - boost uses this.
Parameters:
archive the archive
version the current version of this class
Reimplemented from AbstractSimpleGenerationBasedCellCycleModel.
Definition at line 53 of file FixedDurationGenerationBasedCellCycleModel.hpp.
AbstractCellCycleModel * FixedDurationGenerationBasedCellCycleModel::CreateCellCycleModel () [virtual]
Overridden builder method to create new copies of this cell-cycle model.
Implements AbstractCellCycleModel.
Definition at line 34 of file FixedDurationGenerationBasedCellCycleModel.cpp.
References FixedDurationGenerationBasedCellCycleModel(), AbstractCellCycleModel::mBirthTime, AbstractCellCycleModel::mCellProliferativeType, AbstractCellCycleModel::mG2Duration, AbstractSimpleGenerationBasedCellCycleModel::mGeneration, AbstractSimpleGenerationBasedCellCycleModel::mMaxTransitGenerations, AbstractCellCycleModel::mMDuration, AbstractCellCycleModel::mMinimumGapDuration, AbstractCellCycleModel::mSDuration, AbstractCellCycleModel::mStemCellG1Duration, AbstractCellCycleModel::mTransitCellG1Duration, AbstractCellCycleModel::SetBirthTime(), AbstractCellCycleModel::SetCellProliferativeType(), AbstractCellCycleModel::SetG2Duration(), AbstractSimpleGenerationBasedCellCycleModel::SetGeneration(), AbstractSimpleGenerationBasedCellCycleModel::SetMaxTransitGenerations(), AbstractCellCycleModel::SetMDuration(), AbstractCellCycleModel::SetMinimumGapDuration(), AbstractCellCycleModel::SetSDuration(), AbstractCellCycleModel::SetStemCellG1Duration(), and AbstractCellCycleModel::SetTransitCellG1Duration().
void FixedDurationGenerationBasedCellCycleModel::OutputCellCycleModelParameters (out_stream & rParamsFile) [virtual]
Outputs cell cycle model parameters to file.
Parameters:
rParamsFile the file stream to which the parameters are output
Reimplemented from AbstractSimpleGenerationBasedCellCycleModel.
Definition at line 70 of file FixedDurationGenerationBasedCellCycleModel.cpp.
References AbstractSimpleGenerationBasedCellCycleModel::OutputCellCycleModelParameters().
Friends And Related Function Documentation
friend class boost::serialization::access [friend]
Needed for serialization.
Reimplemented from AbstractSimpleGenerationBasedCellCycleModel.
Definition at line 45 of file FixedDurationGenerationBasedCellCycleModel.hpp.
The documentation for this class was generated from the following files:
cell_based/src/population/cell/cycle/FixedDurationGenerationBasedCellCycleModel.hpp
cell_based/src/population/cell/cycle/FixedDurationGenerationBasedCellCycleModel.cpp