Chaste: CellwiseData< DIM > Class Template Reference
CellwiseData< DIM > Class Template Reference
#include <CellwiseData.hpp>
Public Member Functions
virtual ~CellwiseData ()
double GetValue (CellPtr pCell, unsigned variableNumber=0)
void SetValue (double value, unsigned locationIndex, unsigned variableNumber=0)
void SetCellPopulation (AbstractCellPopulation< DIM > *pCellPopulation)
AbstractCellPopulation< DIM > & rGetCellPopulation ()
void SetNumCellsAndVars (unsigned numCells, unsigned numVars)
void SetConstantDataForTesting (std::vector< double > &rValues)
bool IsSetUp ()
void ReallocateMemory ()
unsigned GetNumVariables ()
Static Public Member Functions
static CellwiseData * Instance ()
static void Destroy ()
Protected Member Functions
CellwiseData ()
Private Member Functions
template<class Archive>
void serialize (Archive &archive, const unsigned int version)
Private Attributes
AbstractCellPopulation< DIM > * mpCellPopulation
bool mAllocatedMemory
unsigned mNumberOfVariables
std::vector< double > mData
std::vector< double > mConstantDataForTesting
bool mUseConstantDataForTesting
Static Private Attributes
static CellwiseData * mpInstance = NULL
Friends
class TestCellwiseData
class boost::serialization::access
Detailed Description
template<unsigned DIM>
class CellwiseData< DIM >
A singleton object for storing data that certain cell-cycle models need to know about, e.g. nutrient concentrations computed via some PDE for use in nutrient-based cell-cycle models.
Definition at line 43 of file CellwiseData.hpp.
Constructor & Destructor Documentation
template<unsigned DIM> CellwiseData< DIM >::CellwiseData () [inline, protected]
Protected constuctor. Not to be called, use Instance() instead.
Definition at line 48 of file CellwiseData.cpp.
References CellwiseData< DIM >::mpInstance.
template<unsigned DIM> CellwiseData< DIM >::~CellwiseData () [inline, virtual]
Destructor.
Definition at line 60 of file CellwiseData.cpp.
Member Function Documentation
template<unsigned DIM> template<class Archive> void CellwiseData< DIM >::serialize (Archive & archive, const unsigned int version) [inline, private]
Archive the object and its member variables.
Parameters:
archive the archive
version the current version of this class
Definition at line 79 of file CellwiseData.hpp.
References CellwiseData< DIM >::mAllocatedMemory, CellwiseData< DIM >::mConstantDataForTesting, CellwiseData< DIM >::mData, CellwiseData< DIM >::mNumberOfVariables, CellwiseData< DIM >::mpCellPopulation, and CellwiseData< DIM >::mUseConstantDataForTesting.
template<unsigned DIM> CellwiseData< DIM > * CellwiseData< DIM >::Instance () [inline, static]
Get an instance of the object
Definition at line 37 of file CellwiseData.cpp.
References CellwiseData< DIM >::mpInstance.
Referenced by ChemotacticForce< DIM >::AddForceContribution(), Alarcon2004OxygenBasedCellCycleModel::AdjustOdeParameters(), CellBasedSimulationArchiver< DIM, SIM >::Load(), CellBasedSimulationArchiver< DIM, SIM >::Save(), CellwiseDataGradient< DIM >::SetupGradients(), CellBasedSimulationWithPdes< DIM >::SolvePde(), CellBasedSimulationWithPdes< DIM >::SolvePdeUsingCoarseMesh(), SimpleOxygenBasedCellCycleModel::UpdateCellCyclePhase(), SimpleOxygenBasedCellCycleModel::UpdateHypoxicDuration(), CellBasedSimulationWithPdes< DIM >::WriteAverageRadialPdeSolution(), CellBasedSimulationWithPdes< DIM >::WritePdeSolution(), VertexBasedCellPopulation< DIM >::WriteVtkResultsToFile(), NodeBasedCellPopulation< DIM >::WriteVtkResultsToFile(), MeshBasedCellPopulationWithGhostNodes< DIM >::WriteVtkResultsToFile(), and MeshBasedCellPopulation< DIM >::WriteVtkResultsToFile().
template<unsigned DIM> void CellwiseData< DIM >::Destroy () [inline, static]
Destroy the current instance. Should be called at the end of a simulation.
Definition at line 66 of file CellwiseData.cpp.
References CellwiseData< DIM >::mpInstance.
template<unsigned DIM> double CellwiseData< DIM >::GetValue (CellPtr pCell, unsigned variableNumber = 0) [inline]
Get the value of CellwiseData for a given cell and variable number.
Parameters:
pCell the cell
variableNumber the index of CellwiseData whose value is required (defaults to zero)
Returns:
the value of CellwiseData.
Definition at line 77 of file CellwiseData.cpp.
References EXCEPTION, CellwiseData< DIM >::IsSetUp(), CellwiseData< DIM >::mAllocatedMemory, CellwiseData< DIM >::mConstantDataForTesting, CellwiseData< DIM >::mData, CellwiseData< DIM >::mNumberOfVariables, CellwiseData< DIM >::mpCellPopulation, and CellwiseData< DIM >::mUseConstantDataForTesting.
Referenced by ChemotacticForce< DIM >::AddForceContribution(), Alarcon2004OxygenBasedCellCycleModel::AdjustOdeParameters(), CellwiseDataGradient< DIM >::SetupGradients(), SimpleOxygenBasedCellCycleModel::UpdateCellCyclePhase(), SimpleOxygenBasedCellCycleModel::UpdateHypoxicDuration(), CellBasedSimulationWithPdes< DIM >::WriteAverageRadialPdeSolution(), CellBasedSimulationWithPdes< DIM >::WritePdeSolution(), VertexBasedCellPopulation< DIM >::WriteVtkResultsToFile(), NodeBasedCellPopulation< DIM >::WriteVtkResultsToFile(), MeshBasedCellPopulationWithGhostNodes< DIM >::WriteVtkResultsToFile(), and MeshBasedCellPopulation< DIM >::WriteVtkResultsToFile().
template<unsigned DIM> void CellwiseData< DIM >::SetValue (double value, unsigned locationIndex, unsigned variableNumber = 0) [inline]
Set the value for a given location index and variable number.
Parameters:
value the value to set
locationIndex the location index
variableNumber the index of CellwiseData whose value is set (defaults to zero)
Definition at line 101 of file CellwiseData.cpp.
References EXCEPTION, CellwiseData< DIM >::IsSetUp(), CellwiseData< DIM >::mData, and CellwiseData< DIM >::mNumberOfVariables.
Referenced by CellBasedSimulationWithPdes< DIM >::SolvePde(), and CellBasedSimulationWithPdes< DIM >::SolvePdeUsingCoarseMesh().
template<unsigned DIM> void CellwiseData< DIM >::SetCellPopulation (AbstractCellPopulation< DIM > * pCellPopulation) [inline]
Set the CellPopulation. Must be called before GetValue().
Parameters:
pCellPopulation pointer to the CellPopulation
Definition at line 115 of file CellwiseData.cpp.
References EXCEPTION, CellwiseData< DIM >::mAllocatedMemory, and CellwiseData< DIM >::mpCellPopulation.
template<unsigned DIM> AbstractCellPopulation< DIM > & CellwiseData< DIM >::rGetCellPopulation () [inline]
Returns:
reference to the CellPopulation.
Definition at line 127 of file CellwiseData.cpp.
References CellwiseData< DIM >::mpCellPopulation.
Referenced by CellwiseDataGradient< DIM >::SetupGradients().
template<unsigned DIM> void CellwiseData< DIM >::SetNumCellsAndVars (unsigned numCells, unsigned numVars) [inline]
Set the number of cells and number of variables to be stored per cell. The constructor assumes 1 variable so this method only really needs to be called if numVars > 1.
Parameters:
numCells number of cells in the cell population
numVars number of variables
Definition at line 134 of file CellwiseData.cpp.
References EXCEPTION, CellwiseData< DIM >::mAllocatedMemory, CellwiseData< DIM >::mData, CellwiseData< DIM >::mNumberOfVariables, and CellwiseData< DIM >::mpCellPopulation.
template<unsigned DIM> void CellwiseData< DIM >::SetConstantDataForTesting (std::vector< double > & rValues) [inline]
Force the data to return given values for all cells (only for testing).
Parameters:
rValues vector of CellwiseData values
Definition at line 175 of file CellwiseData.cpp.
References CellwiseData< DIM >::mConstantDataForTesting, CellwiseData< DIM >::mNumberOfVariables, and CellwiseData< DIM >::mUseConstantDataForTesting.
template<unsigned DIM> bool CellwiseData< DIM >::IsSetUp () [inline]
Is the instance in existence and fully set up
Definition at line 153 of file CellwiseData.cpp.
References CellwiseData< DIM >::mAllocatedMemory, CellwiseData< DIM >::mpCellPopulation, and CellwiseData< DIM >::mpInstance.
Referenced by CellwiseData< DIM >::GetValue(), CellBasedSimulationArchiver< DIM, SIM >::Save(), and CellwiseData< DIM >::SetValue().
template<unsigned DIM> void CellwiseData< DIM >::ReallocateMemory () [inline]
Reallocate size of mData. Needed because of growth/death. Reallocates according to the number of nodes in the mesh in the CellPopulation member variable
Definition at line 160 of file CellwiseData.cpp.
References CellwiseData< DIM >::mAllocatedMemory, CellwiseData< DIM >::mData, CellwiseData< DIM >::mNumberOfVariables, and CellwiseData< DIM >::mpCellPopulation.
Referenced by CellBasedSimulationWithPdes< DIM >::SolvePde(), and CellBasedSimulationWithPdes< DIM >::SolvePdeUsingCoarseMesh().
template<unsigned DIM> unsigned CellwiseData< DIM >::GetNumVariables () [inline]
Returns:
mNumberOfVariables
Definition at line 184 of file CellwiseData.cpp.
References CellwiseData< DIM >::mNumberOfVariables.
Referenced by VertexBasedCellPopulation< DIM >::WriteVtkResultsToFile(), NodeBasedCellPopulation< DIM >::WriteVtkResultsToFile(), MeshBasedCellPopulationWithGhostNodes< DIM >::WriteVtkResultsToFile(), and MeshBasedCellPopulation< DIM >::WriteVtkResultsToFile().
Friends And Related Function Documentation
template<unsigned DIM> friend class boost::serialization::access [friend]
Needed for serialization.
Definition at line 71 of file CellwiseData.hpp.
Member Data Documentation
template<unsigned DIM> CellwiseData< DIM > * CellwiseData< DIM >::mpInstance = NULL [inline, static, private]
The single instance of the singleton object
Definition at line 50 of file CellwiseData.hpp.
Referenced by CellwiseData< DIM >::CellwiseData(), CellwiseData< DIM >::Destroy(), CellwiseData< DIM >::Instance(), and CellwiseData< DIM >::IsSetUp().
template<unsigned DIM> AbstractCellPopulation<DIM>* CellwiseData< DIM >::mpCellPopulation [private]
A pointer to a CellPopulation so a cell's node can be found
Definition at line 53 of file CellwiseData.hpp.
Referenced by CellwiseData< DIM >::GetValue(), CellwiseData< DIM >::IsSetUp(), CellwiseData< DIM >::ReallocateMemory(), CellwiseData< DIM >::rGetCellPopulation(), CellwiseData< DIM >::serialize(), CellwiseData< DIM >::SetCellPopulation(), and CellwiseData< DIM >::SetNumCellsAndVars().
template<unsigned DIM> bool CellwiseData< DIM >::mAllocatedMemory [private]
Allocated memory for mData object
Definition at line 56 of file CellwiseData.hpp.
Referenced by CellwiseData< DIM >::GetValue(), CellwiseData< DIM >::IsSetUp(), CellwiseData< DIM >::ReallocateMemory(), CellwiseData< DIM >::serialize(), CellwiseData< DIM >::SetCellPopulation(), and CellwiseData< DIM >::SetNumCellsAndVars().
template<unsigned DIM> unsigned CellwiseData< DIM >::mNumberOfVariables [private]
Number of variables per node to be stored
Definition at line 59 of file CellwiseData.hpp.
Referenced by CellwiseData< DIM >::GetNumVariables(), CellwiseData< DIM >::GetValue(), CellwiseData< DIM >::ReallocateMemory(), CellwiseData< DIM >::serialize(), CellwiseData< DIM >::SetConstantDataForTesting(), CellwiseData< DIM >::SetNumCellsAndVars(), and CellwiseData< DIM >::SetValue().
template<unsigned DIM> std::vector<double> CellwiseData< DIM >::mData [private]
Store of the data
Definition at line 62 of file CellwiseData.hpp.
Referenced by CellwiseData< DIM >::GetValue(), CellwiseData< DIM >::ReallocateMemory(), CellwiseData< DIM >::serialize(), CellwiseData< DIM >::SetNumCellsAndVars(), and CellwiseData< DIM >::SetValue().
template<unsigned DIM> std::vector<double> CellwiseData< DIM >::mConstantDataForTesting [private]
Helper member storing constant data. Used in tests.
Definition at line 65 of file CellwiseData.hpp.
Referenced by CellwiseData< DIM >::GetValue(), CellwiseData< DIM >::serialize(), and CellwiseData< DIM >::SetConstantDataForTesting().
template<unsigned DIM> bool CellwiseData< DIM >::mUseConstantDataForTesting [private]
Helper member storing whether mConstantDataForTesting is used.
Definition at line 68 of file CellwiseData.hpp.
Referenced by CellwiseData< DIM >::GetValue(), CellwiseData< DIM >::serialize(), and CellwiseData< DIM >::SetConstantDataForTesting().
The documentation for this class was generated from the following files:
cell_based/src/population/CellwiseData.hpp
cell_based/src/population/CellwiseData.cpp