Chaste: TargetedCellKiller< DIM > Class Template Reference
TargetedCellKiller< DIM > Class Template Reference
#include <TargetedCellKiller.hpp>
Public Member Functions
TargetedCellKiller (AbstractCellPopulation< DIM > *pCellPopulation, unsigned targetedIndex, bool bloodLust=true)
unsigned GetTargetIndex () const
unsigned GetBloodLust () const
void TestAndLabelCellsForApoptosisOrDeath ()
void OutputCellKillerParameters (out_stream &rParamsFile)
Private Member Functions
template<class Archive>
void serialize (Archive &archive, const unsigned int version)
Private Attributes
unsigned mTargetIndex
bool mBloodLust
Friends
class boost::serialization::access
Detailed Description
template<unsigned DIM>
class TargetedCellKiller< DIM >
Simple cell killer which at the first timestep kills any cell whose corresponding location index is a given number.
Definition at line 41 of file TargetedCellKiller.hpp.
Constructor & Destructor Documentation
template<unsigned DIM> TargetedCellKiller< DIM >::TargetedCellKiller (AbstractCellPopulation< DIM > * pCellPopulation, unsigned targetedIndex, bool bloodLust = true) [inline]
Default constructor.
Parameters:
pCellPopulation pointer to the cell population
targetedIndex The index of the cell to kill
bloodLust Wether to kill cells or not defaults to true (used by load methods)
Definition at line 31 of file TargetedCellKiller.cpp.
Member Function Documentation
template<unsigned DIM> template<class Archive> void TargetedCellKiller< DIM >::serialize (Archive & archive, const unsigned int version) [inline, private]
Archive the object and its member variables.
Serialization of singleton objects must be done with care. Before the object is serialized via a pointer, it *MUST* be serialized directly, or an assertion will trip when a second instance of the class is created on de-serialization.
Parameters:
archive the archive
version the current version of this class
Reimplemented from AbstractCellKiller< DIM >.
Definition at line 72 of file TargetedCellKiller.hpp.
template<unsigned DIM> unsigned TargetedCellKiller< DIM >::GetTargetIndex () const [inline]
Returns:
mTargetIndex.
Definition at line 39 of file TargetedCellKiller.cpp.
References TargetedCellKiller< DIM >::mTargetIndex.
template<unsigned DIM> unsigned TargetedCellKiller< DIM >::GetBloodLust () const [inline]
Returns:
mBloodLust.
Definition at line 45 of file TargetedCellKiller.cpp.
References TargetedCellKiller< DIM >::mBloodLust.
template<unsigned DIM> void TargetedCellKiller< DIM >::TestAndLabelCellsForApoptosisOrDeath () [inline, virtual]
Loop over cells and start apoptosis randomly, based on the user-set probability
Implements AbstractCellKiller< DIM >.
Definition at line 51 of file TargetedCellKiller.cpp.
References AbstractCellPopulation< DIM >::GetCellUsingLocationIndex(), AbstractCellPopulation< DIM >::GetNumRealCells(), TargetedCellKiller< DIM >::mBloodLust, AbstractCellKiller< DIM >::mpCellPopulation, and TargetedCellKiller< DIM >::mTargetIndex.
template<unsigned DIM> void TargetedCellKiller< DIM >::OutputCellKillerParameters (out_stream & rParamsFile) [inline, virtual]
Outputs cell killer parameters to file
As this method is pure virtual, it must be overridden in subclasses.
Parameters:
rParamsFile the file stream to which the parameters are output
Implements AbstractCellKiller< DIM >.
Definition at line 62 of file TargetedCellKiller.cpp.
References TargetedCellKiller< DIM >::mBloodLust, TargetedCellKiller< DIM >::mTargetIndex, and AbstractCellKiller< SPACE_DIM >::OutputCellKillerParameters().
Friends And Related Function Documentation
template<unsigned DIM> friend class boost::serialization::access [friend]
Needed for serialization.
Reimplemented from AbstractCellKiller< DIM >.
Definition at line 59 of file TargetedCellKiller.hpp.
Member Data Documentation
template<unsigned DIM> unsigned TargetedCellKiller< DIM >::mTargetIndex [private]
The index of the cell to kill
Definition at line 48 of file TargetedCellKiller.hpp.
Referenced by TargetedCellKiller< DIM >::GetTargetIndex(), TargetedCellKiller< DIM >::OutputCellKillerParameters(), and TargetedCellKiller< DIM >::TestAndLabelCellsForApoptosisOrDeath().
template<unsigned DIM> bool TargetedCellKiller< DIM >::mBloodLust [private]
Variable to reack when the cell has been killed. Once the cell has been called mBloodLust will stop the killer killing more cells.
Definition at line 55 of file TargetedCellKiller.hpp.
Referenced by TargetedCellKiller< DIM >::GetBloodLust(), TargetedCellKiller< DIM >::OutputCellKillerParameters(), and TargetedCellKiller< DIM >::TestAndLabelCellsForApoptosisOrDeath().
The documentation for this class was generated from the following files:
cell_based/src/population/killers/TargetedCellKiller.hpp
cell_based/src/population/killers/TargetedCellKiller.cpp