Chaste: CellwiseDataGradient< DIM > Class Template Reference
CellwiseDataGradient< DIM > Class Template Reference
#include <CellwiseDataGradient.hpp>
Public Member Functions
void SetupGradients ()
c_vector< double, DIM > & rGetGradient (unsigned nodeIndex)
Private Attributes
std::vector< c_vector< double,
DIM > > mGradients
Detailed Description
template<unsigned DIM>
class CellwiseDataGradient< DIM >
A class for calculating the gradients of the CellwiseData.
Definition at line 37 of file CellwiseDataGradient.hpp.
Member Function Documentation
template<unsigned DIM> void CellwiseDataGradient< DIM >::SetupGradients () [inline]
Compute the gradients at the nodes.
This is done by averaging the gradients at all the containing (non-ghost) elements for that node. Note that the gradients are piecewise constant- constant in each element
Definition at line 39 of file CellwiseDataGradient.cpp.
References AbstractCellPopulation< DIM >::Begin(), LinearBasisFunction< ELEMENT_DIM >::ComputeTransformedBasisFunctionDerivatives(), Node< SPACE_DIM >::ContainingElementsBegin(), Node< SPACE_DIM >::ContainingElementsEnd(), AbstractCellPopulation< DIM >::End(), AbstractCellPopulation< DIM >::GetCellUsingLocationIndex(), AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::GetElement(), TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::GetInverseJacobianForElement(), AbstractCellPopulation< DIM >::GetLocationIndexUsingCell(), AbstractMesh< ELEMENT_DIM, SPACE_DIM >::GetNode(), AbstractCentreBasedCellPopulation< DIM >::GetNodeCorrespondingToCell(), AbstractElement< ELEMENT_DIM, SPACE_DIM >::GetNodeGlobalIndex(), AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::GetNumElements(), MeshBasedCellPopulation< DIM >::GetNumNodes(), CellwiseData< DIM >::GetValue(), AbstractMesh< ELEMENT_DIM, SPACE_DIM >::GetVectorFromAtoB(), CellwiseData< DIM >::Instance(), AbstractCentreBasedCellPopulation< DIM >::IsGhostNode(), CellwiseDataGradient< DIM >::mGradients, CellwiseData< DIM >::rGetCellPopulation(), Node< SPACE_DIM >::rGetLocation(), and MeshBasedCellPopulation< DIM >::rGetMesh().
Referenced by ChemotacticForce< DIM >::AddForceContribution().
template<unsigned DIM> c_vector< double, DIM > & CellwiseDataGradient< DIM >::rGetGradient (unsigned nodeIndex) [inline]
Get the gradient at a given node. Not set up for ghost nodes.
Parameters:
nodeIndex
Returns:
the gradient at the node.
Definition at line 32 of file CellwiseDataGradient.cpp.
References CellwiseDataGradient< DIM >::mGradients.
Referenced by ChemotacticForce< DIM >::AddForceContribution().
Member Data Documentation
template<unsigned DIM> std::vector<c_vector<double, DIM> > CellwiseDataGradient< DIM >::mGradients [private]
The final gradients at the nodes
Definition at line 44 of file CellwiseDataGradient.hpp.
Referenced by CellwiseDataGradient< DIM >::rGetGradient(), and CellwiseDataGradient< DIM >::SetupGradients().
The documentation for this class was generated from the following files:
cell_based/src/population/CellwiseDataGradient.hpp
cell_based/src/population/CellwiseDataGradient.cpp