Chaste: CylindricalHoneycombMeshGenerator Class Reference
CylindricalHoneycombMeshGenerator Class Reference
#include <CylindricalHoneycombMeshGenerator.hpp>
Public Member Functions
CylindricalHoneycombMeshGenerator (unsigned numNodesAlongWidth, unsigned numNodesAlongLength, unsigned ghosts=3, double scaleFactor=1.0)
MutableMesh< 2, 2 > * GetMesh ()
Cylindrical2dMesh * GetCylindricalMesh ()
Detailed Description
Honeycomb mesh generator that creates a 2D "cylindrical" mesh (one in which periodicity is imposed on the left and right boundaries) for use in cell-centre simulations.
NOTE: the user should delete the mesh after use to manage memory.
Definition at line 44 of file CylindricalHoneycombMeshGenerator.hpp.
Constructor & Destructor Documentation
CylindricalHoneycombMeshGenerator::CylindricalHoneycombMeshGenerator (unsigned numNodesAlongWidth, unsigned numNodesAlongLength, unsigned ghosts = 3, double scaleFactor = 1.0)
Default constructor.
Parameters:
numNodesAlongWidth The number of cells you want alopng the bottom of the domain
numNodesAlongLength The number of cells you want sides of the domain
ghosts The thickness of ghost nodes to put around the edge (defaults to 3)
scaleFactor The scale factor for the width (circumference) of the cells (defaults to 1.0)
Definition at line 33 of file CylindricalHoneycombMeshGenerator.cpp.
References PetscTools::AmMaster(), PetscTools::Barrier(), TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructFromMeshReader(), EXCEPTION, MutableMesh< ELEMENT_DIM, SPACE_DIM >::GetNumNodes(), OutputFileHandler::GetOutputDirectoryFullPath(), PetscTools::IsSequential(), HoneycombMeshGenerator::mBottom, HoneycombMeshGenerator::mDomainDepth, HoneycombMeshGenerator::mDomainWidth, HoneycombMeshGenerator::mGhostNodeIndices, HoneycombMeshGenerator::mMeshFilename, HoneycombMeshGenerator::mNumCellLength, HoneycombMeshGenerator::mNumCellWidth, HoneycombMeshGenerator::mpMesh, HoneycombMeshGenerator::mTop, OutputFileHandler::OpenOutputFile(), MutableMesh< ELEMENT_DIM, SPACE_DIM >::ReMesh(), and AbstractMesh< ELEMENT_DIM, SPACE_DIM >::SetMeshHasChangedSinceLoading().
Member Function Documentation
MutableMesh< 2, 2 > * CylindricalHoneycombMeshGenerator::GetMesh () [virtual]
Returns:
a 2D honeycomb mesh
Reimplemented from HoneycombMeshGenerator.
Definition at line 221 of file CylindricalHoneycombMeshGenerator.cpp.
References EXCEPTION, and HoneycombMeshGenerator::mpMesh.
Cylindrical2dMesh * CylindricalHoneycombMeshGenerator::GetCylindricalMesh ()
Returns:
a 2D honeycomb mesh with periodic left/right boundaries
Definition at line 227 of file CylindricalHoneycombMeshGenerator.cpp.
References HoneycombMeshGenerator::mpMesh.
The documentation for this class was generated from the following files:
cell_based/src/mesh/CylindricalHoneycombMeshGenerator.hpp
cell_based/src/mesh/CylindricalHoneycombMeshGenerator.cpp