Chaste: OdeSystemInformation< ODE_SYSTEM > Class Template Reference
OdeSystemInformation< ODE_SYSTEM > Class Template Reference
#include <OdeSystemInformation.hpp>
Public Member Functions
template<>
void Initialise (void)
template<>
void Initialise (void)
template<>
void Initialise (void)
template<>
void Initialise (void)
template<>
void Initialise (void)
template<>
void Initialise (void)
template<>
void Initialise (void)
template<>
void Initialise (void)
template<>
void Initialise (void)
template<>
void Initialise (void)
template<>
void Initialise (void)
template<>
void Initialise (void)
template<>
void Initialise (void)
template<>
void Initialise (void)
template<>
void Initialise (void)
template<>
void Initialise (void)
template<>
void Initialise (void)
template<>
void Initialise (void)
template<>
void Initialise ()
Static Public Member Functions
static boost::shared_ptr
< OdeSystemInformation
< ODE_SYSTEM > > Instance ()
Protected Member Functions
OdeSystemInformation ()
OdeSystemInformation (const OdeSystemInformation< ODE_SYSTEM > &)
OdeSystemInformation & operator= (const OdeSystemInformation< ODE_SYSTEM > &)
void Initialise ()
Static Private Attributes
static boost::shared_ptr
< OdeSystemInformation
< ODE_SYSTEM > > mpInstance
Detailed Description
template<class ODE_SYSTEM>
class OdeSystemInformation< ODE_SYSTEM >
A concrete implementation of AbstractOdeSystemInformation, that uses templates to provide an implementation for any ODE system class.
All ODE system developers need to do is provide a specialisation of the Initialise method of this class, and set mpSystemInfo in their constructor: mpSystemInfo = OdeSystemInformation<CLASS>::Instance();
This class contains all the machinery to make it a singleton, hence providing exactly one instance per value of the template parameter.
Definition at line 48 of file OdeSystemInformation.hpp.
Constructor & Destructor Documentation
template<class ODE_SYSTEM> OdeSystemInformation< ODE_SYSTEM >::OdeSystemInformation () [inline, protected]
Default constructor.
Not user accessible - to obtain an instance of this class use the Instance method.
Definition at line 119 of file OdeSystemInformation.hpp.
References OdeSystemInformation< ODE_SYSTEM >::mpInstance.
template<class ODE_SYSTEM> OdeSystemInformation< ODE_SYSTEM >::OdeSystemInformation (const OdeSystemInformation< ODE_SYSTEM > &) [protected]
Copy constructor.
Member Function Documentation
template<class ODE_SYSTEM> OdeSystemInformation& OdeSystemInformation< ODE_SYSTEM >::operator= (const OdeSystemInformation< ODE_SYSTEM > &) [protected]
Overloaded assignement operator.
template<class ODE_SYSTEM> void OdeSystemInformation< ODE_SYSTEM >::Initialise (void) [inline, protected, virtual]
Generic implementation of Initialise, which does nothing.
Developers should specialise this method to their ODE system. For example,
template<> void OdeSystemInformation<MyNewOdeSystem>::Initialise() { this->mVariableNames.push_back("Variable 1"); this->mVariableUnits.push_back("Units 1"); this->mInitialConditions.push_back(0.0);
this->mInitialised = true; }
Implements AbstractOdeSystemInformation.
Definition at line 126 of file OdeSystemInformation.hpp.
template<class ODE_SYSTEM> boost::shared_ptr< OdeSystemInformation< ODE_SYSTEM > > OdeSystemInformation< ODE_SYSTEM >::Instance () [inline, static]
Return a pointer to the singleton instance, creating it if necessary.
Definition at line 108 of file OdeSystemInformation.hpp.
References OdeSystemInformation< ODE_SYSTEM >::mpInstance.
Referenced by BackwardEulerFoxModel2002Modified::BackwardEulerFoxModel2002Modified(), DiFrancescoNoble1985OdeSystem::DiFrancescoNoble1985OdeSystem(), FakeBathCell::FakeBathCell(), FitzHughNagumo1961OdeSystem::FitzHughNagumo1961OdeSystem(), HodgkinHuxleySquidAxon1952OriginalOdeSystem::HodgkinHuxleySquidAxon1952OriginalOdeSystem(), BackwardEulerLuoRudyIModel1991::Init(), LuoRudyIModel1991OdeSystem::LuoRudyIModel1991OdeSystem(), Mahajan2008OdeSystem::Mahajan2008OdeSystem(), NhsCellularMechanicsOdeSystem::NhsCellularMechanicsOdeSystem(), TenTusscher2006OdeSystem::TenTusscher2006OdeSystem(), and TysonNovak2001OdeSystem::TysonNovak2001OdeSystem().
template<> void OdeSystemInformation< BackwardEulerFoxModel2002Modified >::Initialise (void) [inline, virtual]
Initialise the ODE system information.
This must be provided by subclasses.
Implements AbstractOdeSystemInformation.
Definition at line 674 of file BackwardEulerFoxModel2002Modified.hpp.
References AbstractOdeSystemInformation::mInitialConditions, AbstractOdeSystemInformation::mInitialised, AbstractOdeSystemInformation::mVariableNames, and AbstractOdeSystemInformation::mVariableUnits.
template<> void OdeSystemInformation< BackwardEulerLuoRudyIModel1991 >::Initialise (void) [inline, virtual]
Initialise the ODE system information.
This must be provided by subclasses.
Implements AbstractOdeSystemInformation.
Definition at line 88 of file BackwardEulerLuoRudyIModel1991.cpp.
References AbstractOdeSystemInformation::mInitialConditions, AbstractOdeSystemInformation::mInitialised, AbstractOdeSystemInformation::mVariableNames, and AbstractOdeSystemInformation::mVariableUnits.
template<> void OdeSystemInformation< BackwardEulerNobleVargheseKohlNoble1998 >::Initialise (void) [inline, virtual]
Initialise the ODE system information.
This must be provided by subclasses.
Implements AbstractOdeSystemInformation.
Definition at line 1095 of file BackwardEulerNobleVargheseKohlNoble1998.hpp.
References AbstractOdeSystemInformation::mInitialConditions, AbstractOdeSystemInformation::mInitialised, AbstractOdeSystemInformation::mVariableNames, and AbstractOdeSystemInformation::mVariableUnits.
template<> void OdeSystemInformation< Cellluo_rudy_1991FromCellML >::Initialise (void) [inline, virtual]
Initialise the ODE system information.
This must be provided by subclasses.
Implements AbstractOdeSystemInformation.
Definition at line 305 of file luo_rudy_1991.hpp.
References AbstractOdeSystemInformation::mInitialConditions, AbstractOdeSystemInformation::mInitialised, AbstractOdeSystemInformation::mVariableNames, and AbstractOdeSystemInformation::mVariableUnits.
template<> void OdeSystemInformation< Cellluo_rudy_1991FromCellMLOpt >::Initialise (void) [inline, virtual]
Initialise the ODE system information.
This must be provided by subclasses.
Implements AbstractOdeSystemInformation.
Definition at line 374 of file luo_rudy_1991Opt.hpp.
References AbstractOdeSystemInformation::mInitialConditions, AbstractOdeSystemInformation::mInitialised, AbstractOdeSystemInformation::mVariableNames, and AbstractOdeSystemInformation::mVariableUnits.
template<> void OdeSystemInformation< DiFrancescoNoble1985OdeSystem >::Initialise (void) [inline, virtual]
Initialise the ODE system information.
This must be provided by subclasses.
Implements AbstractOdeSystemInformation.
Definition at line 503 of file DiFrancescoNoble1985OdeSystem.cpp.
References AbstractOdeSystemInformation::mInitialConditions, AbstractOdeSystemInformation::mInitialised, AbstractOdeSystemInformation::mVariableNames, and AbstractOdeSystemInformation::mVariableUnits.
template<> void OdeSystemInformation< FaberRudy2000Version3 >::Initialise (void) [inline, virtual]
Initialise the ODE system information.
This must be provided by subclasses.
Implements AbstractOdeSystemInformation.
Definition at line 753 of file FaberRudy2000Version3.hpp.
References AbstractOdeSystemInformation::mInitialConditions, AbstractOdeSystemInformation::mInitialised, AbstractOdeSystemInformation::mVariableNames, and AbstractOdeSystemInformation::mVariableUnits.
template<> void OdeSystemInformation< FaberRudy2000Version3Optimised >::Initialise (void) [inline, virtual]
Initialise the ODE system information.
This must be provided by subclasses.
Implements AbstractOdeSystemInformation.
Definition at line 868 of file FaberRudy2000Version3Optimised.hpp.
References AbstractOdeSystemInformation::mInitialConditions, AbstractOdeSystemInformation::mInitialised, AbstractOdeSystemInformation::mVariableNames, and AbstractOdeSystemInformation::mVariableUnits.
template<> void OdeSystemInformation< FakeBathCell >::Initialise (void) [inline, virtual]
Initialise the ODE system information.
This must be provided by subclasses.
Implements AbstractOdeSystemInformation.
Definition at line 61 of file FakeBathCell.cpp.
References AbstractOdeSystemInformation::mInitialised.
template<> void OdeSystemInformation< FitzHughNagumo1961OdeSystem >::Initialise (void) [inline, virtual]
Initialise the ODE system information.
This must be provided by subclasses.
Implements AbstractOdeSystemInformation.
Definition at line 88 of file FitzHughNagumo1961OdeSystem.cpp.
References AbstractOdeSystemInformation::mInitialConditions, AbstractOdeSystemInformation::mInitialised, AbstractOdeSystemInformation::mVariableNames, and AbstractOdeSystemInformation::mVariableUnits.
template<> void OdeSystemInformation< FoxModel2002Modified >::Initialise (void) [inline, virtual]
Initialise the ODE system information.
This must be provided by subclasses.
Implements AbstractOdeSystemInformation.
Definition at line 520 of file FoxModel2002Modified.hpp.
References AbstractOdeSystemInformation::mInitialConditions, AbstractOdeSystemInformation::mInitialised, AbstractOdeSystemInformation::mVariableNames, and AbstractOdeSystemInformation::mVariableUnits.
template<> void OdeSystemInformation< HodgkinHuxleySquidAxon1952OriginalOdeSystem >::Initialise (void) [inline, virtual]
Initialise the ODE system information.
This must be provided by subclasses.
Implements AbstractOdeSystemInformation.
Definition at line 156 of file HodgkinHuxleySquidAxon1952OriginalOdeSystem.cpp.
References AbstractOdeSystemInformation::mInitialConditions, AbstractOdeSystemInformation::mInitialised, AbstractOdeSystemInformation::mVariableNames, and AbstractOdeSystemInformation::mVariableUnits.
template<> void OdeSystemInformation< LuoRudyIModel1991OdeSystem >::Initialise (void) [inline, virtual]
Initialise the ODE system information.
This must be provided by subclasses.
Implements AbstractOdeSystemInformation.
Definition at line 331 of file LuoRudyIModel1991OdeSystem.cpp.
References AbstractOdeSystemInformation::mInitialConditions, AbstractOdeSystemInformation::mInitialised, AbstractOdeSystemInformation::mVariableNames, and AbstractOdeSystemInformation::mVariableUnits.
template<> void OdeSystemInformation< Mahajan2008OdeSystem >::Initialise (void) [inline, virtual]
Initialise the ODE system information.
This must be provided by subclasses.
Implements AbstractOdeSystemInformation.
Definition at line 585 of file Mahajan2008OdeSystem.cpp.
References AbstractOdeSystemInformation::mInitialConditions, AbstractOdeSystemInformation::mInitialised, AbstractOdeSystemInformation::mVariableNames, and AbstractOdeSystemInformation::mVariableUnits.
template<> void OdeSystemInformation< NhsCellularMechanicsOdeSystem >::Initialise (void) [inline, virtual]
Initialise the ODE system information.
This must be provided by subclasses.
Implements AbstractOdeSystemInformation.
Definition at line 211 of file NhsCellularMechanicsOdeSystem.cpp.
References AbstractOdeSystemInformation::mInitialConditions, AbstractOdeSystemInformation::mInitialised, AbstractOdeSystemInformation::mVariableNames, and AbstractOdeSystemInformation::mVariableUnits.
template<> void OdeSystemInformation< CML_noble_varghese_kohl_noble_1998_basic >::Initialise (void) [inline, virtual]
Initialise the ODE system information.
This must be provided by subclasses.
Implements AbstractOdeSystemInformation.
Definition at line 595 of file NobleVargheseKohlNoble1998.hpp.
References AbstractOdeSystemInformation::mInitialConditions, AbstractOdeSystemInformation::mInitialised, AbstractOdeSystemInformation::mVariableNames, and AbstractOdeSystemInformation::mVariableUnits.
template<> void OdeSystemInformation< CML_noble_varghese_kohl_noble_1998_basic_pe_lut >::Initialise (void) [inline, virtual]
Initialise the ODE system information.
This must be provided by subclasses.
Implements AbstractOdeSystemInformation.
Definition at line 873 of file NobleVargheseKohlNoble1998Optimised.hpp.
References AbstractOdeSystemInformation::mInitialConditions, AbstractOdeSystemInformation::mInitialised, AbstractOdeSystemInformation::mVariableNames, and AbstractOdeSystemInformation::mVariableUnits.
template<> void OdeSystemInformation< TenTusscher2006OdeSystem >::Initialise (void) [inline, virtual]
Initialise the ODE system information.
This must be provided by subclasses.
Implements AbstractOdeSystemInformation.
Definition at line 479 of file TenTusscher2006OdeSystem.cpp.
References AbstractOdeSystemInformation::mInitialConditions, AbstractOdeSystemInformation::mInitialised, AbstractOdeSystemInformation::mVariableNames, and AbstractOdeSystemInformation::mVariableUnits.
template<> void OdeSystemInformation< TysonNovak2001OdeSystem >::Initialise () [inline, virtual]
Initialise the ODE system information.
This must be provided by subclasses.
Implements AbstractOdeSystemInformation.
Definition at line 240 of file TysonNovak2001OdeSystem.cpp.
References AbstractOdeSystemInformation::mInitialConditions, AbstractOdeSystemInformation::mInitialised, AbstractOdeSystemInformation::mVariableNames, and AbstractOdeSystemInformation::mVariableUnits.
Member Data Documentation
template<class ODE_SYSTEM> boost::shared_ptr< OdeSystemInformation< ODE_SYSTEM > > OdeSystemInformation< ODE_SYSTEM >::mpInstance [inline, static, private]
The single instance of this class, for this ODE_SYSTEM.
Todo:
see if using weak_ptr would work and give funkier semantics (automatically destroy the singleton when no ODE systems were using it)
Definition of the instance static member.
Definition at line 58 of file OdeSystemInformation.hpp.
Referenced by OdeSystemInformation< ODE_SYSTEM >::Instance(), and OdeSystemInformation< ODE_SYSTEM >::OdeSystemInformation().
The documentation for this class was generated from the following file:
/tmp/release_1.1/ode/src/common/OdeSystemInformation.hpp