Chaste: VertexAndAngle< DIM > Class Template Reference
VertexAndAngle< DIM > Class Template Reference
#include <VertexAndAngle.hpp>
Public Member Functions
void ComputeAndSetAngle (double x, double y)
void SetVertex (c_vector< double, DIM > *pVertex)
bool operator< (const VertexAndAngle &rOther) const
double GetAngle ()
c_vector< double, DIM > * GetVertex ()
Private Attributes
c_vector< double, DIM > * mpVertex
double mAngle
Detailed Description
template<unsigned DIM>
class VertexAndAngle< DIM >
Helper class containing a pointer to a vertex of the face and the polar angle from the centre of the face to this vertex.
Todo:
does this really need to be templated?
Definition at line 43 of file VertexAndAngle.hpp.
Member Function Documentation
template<unsigned DIM> void VertexAndAngle< DIM >::ComputeAndSetAngle (double x, double y) [inline]
Compute the polar angle of the point (x,y) in the interval (-PI, PI] and use this to set mAngle.
Parameters:
x x-coordinate
y y-coordinate
Definition at line 36 of file VertexAndAngle.cpp.
References VertexAndAngle< DIM >::mAngle.
Referenced by VoronoiTessellation< DIM >::Initialise(), and Face< DIM >::OrderVerticesAntiClockwise().
template<unsigned DIM> void VertexAndAngle< DIM >::SetVertex (c_vector< double, DIM > * pVertex) [inline]
Set mpVertex.
Parameters:
pVertex location of the vertex
Definition at line 70 of file VertexAndAngle.cpp.
References VertexAndAngle< DIM >::mpVertex.
Referenced by VoronoiTessellation< DIM >::Initialise(), and Face< DIM >::OrderVerticesAntiClockwise().
template<unsigned DIM> bool VertexAndAngle< DIM >::operator< (const VertexAndAngle< DIM > & rOther) const [inline]
Less-than angle comparison operator.
Parameters:
rOther the VertexAndAngle object to compare to
Definition at line 88 of file VertexAndAngle.cpp.
References VertexAndAngle< DIM >::mAngle.
template<unsigned DIM> double VertexAndAngle< DIM >::GetAngle () [inline]
Get method for mAngle.
Definition at line 76 of file VertexAndAngle.cpp.
References VertexAndAngle< DIM >::mAngle.
template<unsigned DIM> c_vector< double, DIM > * VertexAndAngle< DIM >::GetVertex () [inline]
Get method for mpVertex.
Definition at line 82 of file VertexAndAngle.cpp.
References VertexAndAngle< DIM >::mpVertex.
Member Data Documentation
template<unsigned DIM> c_vector<double, DIM>* VertexAndAngle< DIM >::mpVertex [private]
Pointer to a vertex.
Definition at line 48 of file VertexAndAngle.hpp.
Referenced by VertexAndAngle< DIM >::GetVertex(), and VertexAndAngle< DIM >::SetVertex().
template<unsigned DIM> double VertexAndAngle< DIM >::mAngle [private]
Polar angle.
Definition at line 51 of file VertexAndAngle.hpp.
Referenced by VertexAndAngle< DIM >::ComputeAndSetAngle(), VertexAndAngle< DIM >::GetAngle(), and VertexAndAngle< DIM >::operator<().
The documentation for this class was generated from the following files:
/tmp/release_1.1/mesh/src/voronoi/VertexAndAngle.hpp
/tmp/release_1.1/mesh/src/voronoi/VertexAndAngle.cpp