Chaste: AbstractCancerTestSuite Class Reference
AbstractCancerTestSuite Class Reference
#include <AbstractCancerTestSuite.hpp>
Protected Member Functions
void setUp ()
void tearDown ()
Detailed Description
This class provides setUp and tearDown methods that are common to many cancer test suites. Such suites may inherit from this class to avoid having to redefine them.
Definition at line 40 of file AbstractCancerTestSuite.hpp.
Member Function Documentation
void AbstractCancerTestSuite::setUp () [inline, protected]
Overridden setUp() method. Initialises singleton classes.
Definition at line 47 of file AbstractCancerTestSuite.hpp.
References TissueConfig::Instance(), RandomNumberGenerator::Instance(), SimulationTime::Instance(), RandomNumberGenerator::Reseed(), TissueConfig::Reset(), and SimulationTime::SetStartTime().
void AbstractCancerTestSuite::tearDown () [inline, protected]
Overridden teardown() method. Clears up singleton classes.
Definition at line 60 of file AbstractCancerTestSuite.hpp.
References RandomNumberGenerator::Destroy(), and SimulationTime::Destroy().
The documentation for this class was generated from the following file:
/tmp/release_1.1/cancer/src/fortests/AbstractCancerTestSuite.hpp