Chaste: AbstractLinearParabolicPde< ELEM_DIM, SPACE_DIM > Class Template Reference
AbstractLinearParabolicPde< ELEM_DIM, SPACE_DIM > Class Template Reference
#include <AbstractLinearParabolicPde.hpp>
Public Member Functions
virtual double ComputeDuDtCoefficientFunction (const ChastePoint< SPACE_DIM > &rX)=0
virtual double ComputeNonlinearSourceTerm (const ChastePoint< SPACE_DIM > &rX, double u)=0
virtual double ComputeNonlinearSourceTermAtNode (const Node< SPACE_DIM > &rNode, double u)
virtual double ComputeLinearSourceTerm (const ChastePoint< SPACE_DIM > &rX)=0
virtual c_matrix< double,
SPACE_DIM, SPACE_DIM > ComputeDiffusionTerm (const ChastePoint< SPACE_DIM > &rX, Element< ELEM_DIM, SPACE_DIM > *pElement=NULL)=0
virtual double ComputeLinearSourceTermAtNode (const Node< SPACE_DIM > &rNode)
virtual ~AbstractLinearParabolicPde ()
Detailed Description
template<unsigned ELEM_DIM, unsigned SPACE_DIM = ELEM_DIM>
class AbstractLinearParabolicPde< ELEM_DIM, SPACE_DIM >
AbstractLinearParabolicPde class.
A general PDE of the form: c(x) du/dt = Grad.(DiffusionTerm(x)*Grad(u))+LinearSourceTerm(x)+NonlinearSourceTerm(x, u)
Definition at line 46 of file AbstractLinearParabolicPde.hpp.
Constructor & Destructor Documentation
template<unsigned ELEM_DIM, unsigned SPACE_DIM = ELEM_DIM> virtual AbstractLinearParabolicPde< ELEM_DIM, SPACE_DIM >::~AbstractLinearParabolicPde () [inline, virtual]
Destructor.
Definition at line 99 of file AbstractLinearParabolicPde.hpp.
Member Function Documentation
template<unsigned ELEM_DIM, unsigned SPACE_DIM = ELEM_DIM> virtual double AbstractLinearParabolicPde< ELEM_DIM, SPACE_DIM >::ComputeDuDtCoefficientFunction (const ChastePoint< SPACE_DIM > & rX) [pure virtual]
The function c(x) in "c(x) du/dt = Grad.(DiffusionTerm(x)*Grad(u))+LinearSourceTerm(x)+NonlinearSourceTerm(x, u)"
Parameters:
rX the point in space at which the function c is computed
Implemented in MonodomainPde< ELEM_DIM, SPACE_DIM >, MonodomainPde< ELEM_DIM, ELEM_DIM >, and MonodomainPde< ELEMENT_DIM, SPACE_DIM >.
Referenced by SimpleDg0ParabolicAssembler< ELEMENT_DIM, SPACE_DIM, NON_HEART, CONCRETE >::ComputeMatrixTerm(), and SimpleDg0ParabolicAssembler< ELEMENT_DIM, SPACE_DIM, NON_HEART, CONCRETE >::ComputeVectorTerm().
template<unsigned ELEM_DIM, unsigned SPACE_DIM = ELEM_DIM> virtual double AbstractLinearParabolicPde< ELEM_DIM, SPACE_DIM >::ComputeNonlinearSourceTerm (const ChastePoint< SPACE_DIM > & rX, double u) [pure virtual]
Compute nonlinear source term.
Parameters:
rX the point in space at which the nonlinear source term is computed
u the value of the dependent variable at the point
Implemented in MonodomainPde< ELEM_DIM, SPACE_DIM >, MonodomainPde< ELEM_DIM, ELEM_DIM >, and MonodomainPde< ELEMENT_DIM, SPACE_DIM >.
Referenced by AbstractLinearParabolicPde< ELEM_DIM, SPACE_DIM >::ComputeNonlinearSourceTermAtNode(), and SimpleDg0ParabolicAssembler< ELEMENT_DIM, SPACE_DIM, NON_HEART, CONCRETE >::ComputeVectorTerm().
template<unsigned ELEM_DIM, unsigned SPACE_DIM> double AbstractLinearParabolicPde< ELEM_DIM, SPACE_DIM >::ComputeNonlinearSourceTermAtNode (const Node< SPACE_DIM > & rNode, double u) [inline, virtual]
Compute nonlinear source term at a node.
Parameters:
rNode the node at which the nonlinear source term is computed
u the value of the dependent variable at the node
Reimplemented in MonodomainPde< ELEM_DIM, SPACE_DIM >, MonodomainPde< ELEM_DIM, ELEM_DIM >, and MonodomainPde< ELEMENT_DIM, SPACE_DIM >.
Definition at line 116 of file AbstractLinearParabolicPde.hpp.
References AbstractLinearParabolicPde< ELEM_DIM, SPACE_DIM >::ComputeNonlinearSourceTerm(), and Node< SPACE_DIM >::GetPoint().
template<unsigned ELEM_DIM, unsigned SPACE_DIM = ELEM_DIM> virtual double AbstractLinearParabolicPde< ELEM_DIM, SPACE_DIM >::ComputeLinearSourceTerm (const ChastePoint< SPACE_DIM > & rX) [pure virtual]
Compute linear source term.
Parameters:
rX the point in space at which the linear source term is computed
Implemented in MonodomainPde< ELEM_DIM, SPACE_DIM >, MonodomainPde< ELEM_DIM, ELEM_DIM >, and MonodomainPde< ELEMENT_DIM, SPACE_DIM >.
Referenced by AbstractLinearParabolicPde< ELEM_DIM, SPACE_DIM >::ComputeLinearSourceTermAtNode(), and SimpleDg0ParabolicAssembler< ELEMENT_DIM, SPACE_DIM, NON_HEART, CONCRETE >::ComputeVectorTerm().
template<unsigned ELEM_DIM, unsigned SPACE_DIM = ELEM_DIM> virtual c_matrix<double, SPACE_DIM, SPACE_DIM> AbstractLinearParabolicPde< ELEM_DIM, SPACE_DIM >::ComputeDiffusionTerm (const ChastePoint< SPACE_DIM > & rX, Element< ELEM_DIM, SPACE_DIM > * pElement = NULL) [pure virtual]
Compute diffusion term.
Parameters:
rX The point in space at which the diffusion term is computed.
pElement The mesh element that x is contained in (optional).
Returns:
A matrix.
Implemented in MonodomainPde< ELEM_DIM, SPACE_DIM >, MonodomainPde< ELEM_DIM, ELEM_DIM >, and MonodomainPde< ELEMENT_DIM, SPACE_DIM >.
Referenced by SimpleDg0ParabolicAssembler< ELEMENT_DIM, SPACE_DIM, NON_HEART, CONCRETE >::ComputeMatrixTerm().
template<unsigned ELEM_DIM, unsigned SPACE_DIM> double AbstractLinearParabolicPde< ELEM_DIM, SPACE_DIM >::ComputeLinearSourceTermAtNode (const Node< SPACE_DIM > & rNode) [inline, virtual]
Compute linear source term at a node.
Parameters:
rNode the node at which the nonlinear source term is computed
Definition at line 110 of file AbstractLinearParabolicPde.hpp.
References AbstractLinearParabolicPde< ELEM_DIM, SPACE_DIM >::ComputeLinearSourceTerm(), and Node< SPACE_DIM >::GetPoint().
The documentation for this class was generated from the following file:
/tmp/release_1.1/pde/src/problem/common/AbstractLinearParabolicPde.hpp