Chaste: AxisymmetricConductivityTensors< SPACE_DIM > Class Template Reference
AxisymmetricConductivityTensors< SPACE_DIM > Class Template Reference
#include <AxisymmetricConductivityTensors.hpp>
Public Member Functions
AxisymmetricConductivityTensors ()
void SetConstantConductivities (c_vector< double, 3 > constantConductivities)
void Init () throw (Exception)
Private Member Functions
void ReadOrientationVectorFromFile (c_vector< double, SPACE_DIM > &rOrientVector)
Detailed Description
template<unsigned SPACE_DIM>
class AxisymmetricConductivityTensors< SPACE_DIM >
The class is templated over SPACE_DIM to keep compatibility with the abstract class. However axisymmetric conductivity only makes sense in 3D, so we check in the constructor for SPACE_DIM to be 3.
Todo:
is the compatibility argument above really worthwhile? We could just inherit from AbstractConductivityTensors<3>. This would however require changes to the constructors of AbstractCardiacPde and BidomainPde.
Definition at line 43 of file AxisymmetricConductivityTensors.hpp.
Constructor & Destructor Documentation
template<unsigned SPACE_DIM> AxisymmetricConductivityTensors< SPACE_DIM >::AxisymmetricConductivityTensors () [inline]
Constructor
Definition at line 54 of file AxisymmetricConductivityTensors.cpp.
Member Function Documentation
template<unsigned SPACE_DIM> void AxisymmetricConductivityTensors< SPACE_DIM >::ReadOrientationVectorFromFile (c_vector< double, SPACE_DIM > & rOrientVector) [inline, private]
Read from mDataFile with GetTokensAtNextLine
Parameters:
rOrientVector vector into which to read the orientation
Definition at line 35 of file AxisymmetricConductivityTensors.cpp.
References AbstractConductivityTensors< SPACE_DIM >::CloseFibreOrientationFile(), and AbstractConductivityTensors< SPACE_DIM >::GetTokensAtNextLine().
Referenced by AxisymmetricConductivityTensors< SPACE_DIM >::Init().
template<unsigned SPACE_DIM> void AxisymmetricConductivityTensors< SPACE_DIM >::SetConstantConductivities (c_vector< double, 3 > constantConductivities) [inline, virtual]
Sets constant conductivities for all the elements of the mesh.
Parameters:
constantConductivities Longitudinal, Transverse (y axis) and Normal conductivity (z axis)
Reimplemented from AbstractConductivityTensors< SPACE_DIM >.
Definition at line 63 of file AxisymmetricConductivityTensors.cpp.
References AbstractConductivityTensors< SPACE_DIM >::mConstantConductivities, and AbstractConductivityTensors< SPACE_DIM >::mUseNonConstantConductivities.
template<unsigned SPACE_DIM> void AxisymmetricConductivityTensors< SPACE_DIM >::Init () throw (Exception) [inline, virtual]
Set up the tensors.
See extensive comments within the implementation of this method.
Implements AbstractConductivityTensors< SPACE_DIM >.
Definition at line 76 of file AxisymmetricConductivityTensors.cpp.
References AbstractConductivityTensors< SPACE_DIM >::CloseFibreOrientationFile(), AbstractConductivityTensors< SPACE_DIM >::GetNumElementsFromFile(), AbstractConductivityTensors< SPACE_DIM >::mConstantConductivities, AbstractConductivityTensors< SPACE_DIM >::mInitialised, AbstractConductivityTensors< SPACE_DIM >::mNumElements, AbstractConductivityTensors< SPACE_DIM >::mpNonConstantConductivities, AbstractConductivityTensors< SPACE_DIM >::mTensors, AbstractConductivityTensors< SPACE_DIM >::mUseFibreOrientation, AbstractConductivityTensors< SPACE_DIM >::mUseNonConstantConductivities, AbstractConductivityTensors< SPACE_DIM >::OpenFibreOrientationFile(), and AxisymmetricConductivityTensors< SPACE_DIM >::ReadOrientationVectorFromFile().
The documentation for this class was generated from the following files:
/tmp/release_1.1/heart/src/problem/AxisymmetricConductivityTensors.hpp
/tmp/release_1.1/heart/src/problem/AxisymmetricConductivityTensors.cpp