Chaste: CardiacElectroMechProbRegularGeom< DIM > Class Template Reference
CardiacElectroMechProbRegularGeom< DIM > Class Template Reference
#include <CardiacElectroMechProbRegularGeom.hpp>
Public Member Functions
CardiacElectroMechProbRegularGeom (double width, unsigned numMechanicsElementsEachDir, unsigned numElectricsElementsEachDir, AbstractCardiacCellFactory< DIM > *pCellFactory, double endTime, unsigned numElecTimeStepsPerMechTimestep, double nhsOdeTimeStep, std::string outputDirectory="")
Detailed Description
template<unsigned DIM>
class CardiacElectroMechProbRegularGeom< DIM >
Child class of CardiacElectroMechanicsProblem for setting up cardiac electromechanics problems on a square (currently just 2d). The user just has to specify the number of elements in each direction. Note: the x=0 surface is fixed in the deformation.
Definition at line 40 of file CardiacElectroMechProbRegularGeom.hpp.
Constructor & Destructor Documentation
template<unsigned DIM> CardiacElectroMechProbRegularGeom< DIM >::CardiacElectroMechProbRegularGeom (double width, unsigned numMechanicsElementsEachDir, unsigned numElectricsElementsEachDir, AbstractCardiacCellFactory< DIM > * pCellFactory, double endTime, unsigned numElecTimeStepsPerMechTimestep, double nhsOdeTimeStep, std::string outputDirectory = "") [inline]
Constructor.
Parameters:
width Width and height of the square
numMechanicsElementsEachDir Number of elements in each direction in the mechanics mesh
numElectricsElementsEachDir Number of elements in each direction in the electrics mesh
pCellFactory factory to use to create cells
endTime the end time to use
numElecTimeStepsPerMechTimestep simple ratio
nhsOdeTimeStep Step size for NHS (Niederer, Hunter, Smith) model of active tension in cardiac cells.
outputDirectory the output directory
Definition at line 56 of file CardiacElectroMechProbRegularGeom.hpp.
References TetrahedralMesh< ELEMENT_DIM, SPACE_DIM >::ConstructRectangularMesh(), AbstractMesh< ELEMENT_DIM, SPACE_DIM >::GetNumNodes(), CardiacElectroMechanicsProblem< DIM >::mFixedNodes, CardiacElectroMechanicsProblem< DIM >::mpElectricsMesh, CardiacElectroMechanicsProblem< DIM >::mpMechanicsMesh, and AbstractMesh< ELEMENT_DIM, SPACE_DIM >::Scale().
The documentation for this class was generated from the following file:
/tmp/release_1.1/heart/src/problem/CardiacElectroMechProbRegularGeom.hpp