Chaste: CmguiWriter Class Reference
CmguiWriter Class Reference
#include <CmguiWriter.hpp>
Public Member Functions
CmguiWriter (const std::string &rDirectory, const std::string &rBaseName, const bool &rCleanDirectory=true)
void WriteFiles ()
virtual ~CmguiWriter ()
Detailed Description
CmguiWriter
Writes a mesh in Cmgui (the visualisation frontend of CMISS) format. Creates an exnode file and a exelem file. Note that the lines and faces are not written in the exelem file, so to load the data in Cmgui, you must use 'generate_faces_and_lines', i.e.
gfx read node base_file gfx read elem base_file generate_faces_and_lines gfx cr win
Definition at line 101 of file CmguiWriter.hpp.
Constructor & Destructor Documentation
CmguiWriter::CmguiWriter (const std::string & rDirectory, const std::string & rBaseName, const bool & rCleanDirectory = true)
Constructor.
Parameters:
rDirectory the directory in which to write the mesh to file
rBaseName the base name of the files in which to write the mesh data
rCleanDirectory whether to clean the directory (defaults to true)
Todo:
make this cleanDirectory to be consistent with other writers? (#991)
Definition at line 35 of file CmguiWriter.cpp.
References AbstractTetrahedralMeshWriter< 3, 3 >::mIndexFromZero.
virtual CmguiWriter::~CmguiWriter () [inline, virtual]
Destructor.
Definition at line 124 of file CmguiWriter.hpp.
Member Function Documentation
void CmguiWriter::WriteFiles () [virtual]
Write mesh data to files.
Implements AbstractTetrahedralMeshWriter< 3, 3 >.
Definition at line 43 of file CmguiWriter.cpp.
References AbstractTetrahedralMeshWriter< 3, 3 >::GetNumElements(), AbstractTetrahedralMeshWriter< 3, 3 >::GetNumNodes(), AbstractTetrahedralMeshWriter< 3, 3 >::mBaseName, AbstractTetrahedralMeshWriter< 3, 3 >::mElementData, AbstractTetrahedralMeshWriter< 3, 3 >::mNodeData, AbstractTetrahedralMeshWriter< 3, 3 >::mpOutputFileHandler, and OutputFileHandler::OpenOutputFile().
The documentation for this class was generated from the following files:
/tmp/release_1.1/mesh/src/writer/CmguiWriter.hpp
/tmp/release_1.1/mesh/src/writer/CmguiWriter.cpp