Chaste: AbstractCellPopulationBoundaryCondition< ELEMENT_DIM, SPACE_DIM > Class Template Reference
AbstractCellPopulationBoundaryCondition< ELEMENT_DIM, SPACE_DIM > Class Template Reference abstract
#include <AbstractCellPopulationBoundaryCondition.hpp>
Public Member Functions
AbstractCellPopulationBoundaryCondition (AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM > *pCellPopulation)
virtual ~AbstractCellPopulationBoundaryCondition ()
virtual void ImposeBoundaryCondition (const std::map< Node< SPACE_DIM > *, c_vector< double, SPACE_DIM > > &rOldLocations)=0
virtual bool VerifyBoundaryCondition ()=0
const AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM > * GetCellPopulation () const
void OutputCellPopulationBoundaryConditionInfo (out_stream &rParamsFile)
virtual void OutputCellPopulationBoundaryConditionParameters (out_stream &rParamsFile)=0
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Protected Attributes
AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM > * mpCellPopulation
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Friends
class TestCellPopulationBoundaryConditions
class boost::serialization::access
Detailed Description
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM = ELEMENT_DIM>
class AbstractCellPopulationBoundaryCondition< ELEMENT_DIM, SPACE_DIM >
An abstract cell population boundary condition class, for use in cell-based simulations.
Definition at line 48 of file AbstractCellPopulationBoundaryCondition.hpp.
Constructor & Destructor Documentation
AbstractCellPopulationBoundaryCondition()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> AbstractCellPopulationBoundaryCondition< ELEMENT_DIM, SPACE_DIM >::AbstractCellPopulationBoundaryCondition (AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM > * pCellPopulation)
Constructor.
Parameters
pCellPopulation pointer to the cell population.
Definition at line 39 of file AbstractCellPopulationBoundaryCondition.cpp.
~AbstractCellPopulationBoundaryCondition()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> AbstractCellPopulationBoundaryCondition< ELEMENT_DIM, SPACE_DIM >::~AbstractCellPopulationBoundaryCondition () virtual
Destructor.
Definition at line 45 of file AbstractCellPopulationBoundaryCondition.cpp.
Member Function Documentation
GetCellPopulation()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> const AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM > * AbstractCellPopulationBoundaryCondition< ELEMENT_DIM, SPACE_DIM >::GetCellPopulation () const
Get a pointer to the cell population.
Returns
A const pointer to the mpCellPopulation
Definition at line 50 of file AbstractCellPopulationBoundaryCondition.cpp.
ImposeBoundaryCondition()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM = ELEMENT_DIM> virtual void AbstractCellPopulationBoundaryCondition< ELEMENT_DIM, SPACE_DIM >::ImposeBoundaryCondition (const std::map< Node< SPACE_DIM > *, c_vector< double, SPACE_DIM > > & rOldLocations) pure virtual
Impose the boundary condition on each node.
As this method is pure virtual, it must be overridden in subclasses.
Parameters
rOldLocations the node locations prior to being updated in UpdateNodePositions()
Implemented in PlaneBoundaryCondition< ELEMENT_DIM, SPACE_DIM >.
OutputCellPopulationBoundaryConditionInfo()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void AbstractCellPopulationBoundaryCondition< ELEMENT_DIM, SPACE_DIM >::OutputCellPopulationBoundaryConditionInfo (out_stream & rParamsFile)
Output cell population boundary condition used in the simulation to file and then call OutputCellPopulationBoundaryConditionParameters() to output all relevant parameters.
Parameters
rParamsFile the file stream to which the parameters are output
Definition at line 56 of file AbstractCellPopulationBoundaryCondition.cpp.
OutputCellPopulationBoundaryConditionParameters()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void AbstractCellPopulationBoundaryCondition< ELEMENT_DIM, SPACE_DIM >::OutputCellPopulationBoundaryConditionParameters (out_stream & rParamsFile) pure virtual
Output cell population boundary condition parameters to file.
As this method is pure virtual, it must be overridden in subclasses.
Parameters
rParamsFile the file stream to which the parameters are output
Implemented in PlaneBoundaryCondition< ELEMENT_DIM, SPACE_DIM >, SlidingBoundaryCondition< DIM >, SphereGeometryBoundaryCondition< DIM >, and CryptSimulationBoundaryCondition< DIM >.
Definition at line 66 of file AbstractCellPopulationBoundaryCondition.cpp.
Referenced by PlaneBoundaryCondition< ELEMENT_DIM, SPACE_DIM >::OutputCellPopulationBoundaryConditionParameters(), SlidingBoundaryCondition< DIM >::OutputCellPopulationBoundaryConditionParameters(), SphereGeometryBoundaryCondition< DIM >::OutputCellPopulationBoundaryConditionParameters(), and CryptSimulationBoundaryCondition< DIM >::OutputCellPopulationBoundaryConditionParameters().
serialize()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM = ELEMENT_DIM> template<class Archive > void AbstractCellPopulationBoundaryCondition< ELEMENT_DIM, SPACE_DIM >::serialize (Archive & archive, const unsigned int version) inline private
Serialize the object and its member variables.
Parameters
archive the archive
version the current version of this class
Definition at line 62 of file AbstractCellPopulationBoundaryCondition.hpp.
VerifyBoundaryCondition()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM = ELEMENT_DIM> virtual bool AbstractCellPopulationBoundaryCondition< ELEMENT_DIM, SPACE_DIM >::VerifyBoundaryCondition () pure virtual
Pure method which should verify the boundary condition has been applied. This is called after ImposeBoundaryCondition() to ensure the condition is still satisfied.
As this method is pure virtual, it must be overridden in subclasses.
Returns
whether the boundary condition is satisfied.
Implemented in PlaneBoundaryCondition< ELEMENT_DIM, SPACE_DIM >, SlidingBoundaryCondition< DIM >, SphereGeometryBoundaryCondition< DIM >, and CryptSimulationBoundaryCondition< DIM >.
Friends And Related Symbol Documentation
boost::serialization::access
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM = ELEMENT_DIM> friend class boost::serialization::access friend
Needed for serialization.
Definition at line 54 of file AbstractCellPopulationBoundaryCondition.hpp.
TestCellPopulationBoundaryConditions
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM = ELEMENT_DIM> friend class TestCellPopulationBoundaryConditions friend
Definition at line 50 of file AbstractCellPopulationBoundaryCondition.hpp.
Member Data Documentation
mpCellPopulation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM = ELEMENT_DIM> AbstractCellPopulation<ELEMENT_DIM,SPACE_DIM>* AbstractCellPopulationBoundaryCondition< ELEMENT_DIM, SPACE_DIM >::mpCellPopulation protected
The cell population.
Definition at line 70 of file AbstractCellPopulationBoundaryCondition.hpp.
The documentation for this class was generated from the following files:
cell_based/src/population/boundary_conditions/AbstractCellPopulationBoundaryCondition.hpp
cell_based/src/population/boundary_conditions/AbstractCellPopulationBoundaryCondition.cpp