Chaste: CellRemovalLocationsWriter< ELEMENT_DIM, SPACE_DIM > Class Template Reference
CellRemovalLocationsWriter< ELEMENT_DIM, SPACE_DIM > Class Template Reference
#include <CellRemovalLocationsWriter.hpp>
Public Member Functions
CellRemovalLocationsWriter ()
void VisitAnyPopulation (AbstractCellPopulation< SPACE_DIM, SPACE_DIM > *pCellPopulation)
virtual void Visit (MeshBasedCellPopulation< ELEMENT_DIM, SPACE_DIM > *pCellPopulation)
virtual void Visit (CaBasedCellPopulation< SPACE_DIM > *pCellPopulation)
virtual void Visit (NodeBasedCellPopulation< SPACE_DIM > *pCellPopulation)
virtual void Visit (PottsBasedCellPopulation< SPACE_DIM > *pCellPopulation)
virtual void Visit (VertexBasedCellPopulation< SPACE_DIM > *pCellPopulation)
virtual void Visit (ImmersedBoundaryCellPopulation< SPACE_DIM > *pCellPopulation)
Public Member Functions inherited from AbstractCellPopulationEventWriter< ELEMENT_DIM, SPACE_DIM >
AbstractCellPopulationEventWriter (const std::string &rFileName)
virtual void WriteHeader (AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM > *pCellPopulation)
Public Member Functions inherited from AbstractCellBasedWriter< ELEMENT_DIM, SPACE_DIM >
AbstractCellBasedWriter (const std::string &rFileName)
virtual ~AbstractCellBasedWriter ()
void CloseFile ()
virtual void OpenOutputFile (OutputFileHandler &rOutputFileHandler)
void OpenOutputFileForAppend (OutputFileHandler &rOutputFileHandler)
virtual void WriteTimeStamp ()
virtual void WriteNewline ()
void SetFileName (std::string fileName)
std::string GetFileName ()
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Friends
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from AbstractCellBasedWriter< ELEMENT_DIM, SPACE_DIM >
std::string mFileName
out_stream mpOutStream
Detailed Description
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM>
class CellRemovalLocationsWriter< ELEMENT_DIM, SPACE_DIM >
A writer class to output the time, locations and cell id info of cell removals to a file.
The output file is called removals.dat by default.
Definition at line 49 of file CellRemovalLocationsWriter.hpp.
Constructor & Destructor Documentation
CellRemovalLocationsWriter()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> CellRemovalLocationsWriter< ELEMENT_DIM, SPACE_DIM >::CellRemovalLocationsWriter ()
Default constructor.
Definition at line 46 of file CellRemovalLocationsWriter.cpp.
Member Function Documentation
serialize()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> template<class Archive > void CellRemovalLocationsWriter< ELEMENT_DIM, SPACE_DIM >::serialize (Archive & archive, const unsigned int version) inline private
Serialize the object and its member variables.
Parameters
archive the archive
version the current version of this class
Definition at line 61 of file CellRemovalLocationsWriter.hpp.
Visit() [1/6]
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void CellRemovalLocationsWriter< ELEMENT_DIM, SPACE_DIM >::Visit (CaBasedCellPopulation< SPACE_DIM > * pCellPopulation) virtual
Visit the population and write the data.
Just passes through to VisitAnyPopulation
Parameters
pCellPopulation a pointer to the CaBasedCellPopulation to visit.
Implements AbstractCellPopulationEventWriter< ELEMENT_DIM, SPACE_DIM >.
Definition at line 80 of file CellRemovalLocationsWriter.cpp.
Visit() [2/6]
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void CellRemovalLocationsWriter< ELEMENT_DIM, SPACE_DIM >::Visit (ImmersedBoundaryCellPopulation< SPACE_DIM > * pCellPopulation) virtual
Visit the population and write the data.
Just passes through to VisitAnyPopulation
Parameters
pCellPopulation a pointer to the ImmersedBoundaryCellPopulation to visit.
Implements AbstractCellPopulationEventWriter< ELEMENT_DIM, SPACE_DIM >.
Definition at line 104 of file CellRemovalLocationsWriter.cpp.
Visit() [3/6]
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void CellRemovalLocationsWriter< ELEMENT_DIM, SPACE_DIM >::Visit (MeshBasedCellPopulation< ELEMENT_DIM, SPACE_DIM > * pCellPopulation) virtual
Visit the population and write the data.
Just passes through to VisitAnyPopulation
Parameters
pCellPopulation a pointer to the MeshBasedCellPopulation to visit.
Implements AbstractCellPopulationEventWriter< ELEMENT_DIM, SPACE_DIM >.
Definition at line 65 of file CellRemovalLocationsWriter.cpp.
References AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::ClearRemovalsInformation(), and AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::GetRemovalsInformation().
Visit() [4/6]
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void CellRemovalLocationsWriter< ELEMENT_DIM, SPACE_DIM >::Visit (NodeBasedCellPopulation< SPACE_DIM > * pCellPopulation) virtual
Visit the population and write the data.
Just passes through to VisitAnyPopulation
Parameters
pCellPopulation a pointer to the NodeBasedCellPopulation to visit.
Implements AbstractCellPopulationEventWriter< ELEMENT_DIM, SPACE_DIM >.
Definition at line 86 of file CellRemovalLocationsWriter.cpp.
Visit() [5/6]
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void CellRemovalLocationsWriter< ELEMENT_DIM, SPACE_DIM >::Visit (PottsBasedCellPopulation< SPACE_DIM > * pCellPopulation) virtual
Visit the population and write the data.
Just passes through to VisitAnyPopulation
Parameters
pCellPopulation a pointer to the PottsBasedCellPopulation to visit.
Implements AbstractCellPopulationEventWriter< ELEMENT_DIM, SPACE_DIM >.
Definition at line 92 of file CellRemovalLocationsWriter.cpp.
Visit() [6/6]
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void CellRemovalLocationsWriter< ELEMENT_DIM, SPACE_DIM >::Visit (VertexBasedCellPopulation< SPACE_DIM > * pCellPopulation) virtual
Visit the population and write the data.
Just passes through to VisitAnyPopulation
Parameters
pCellPopulation a pointer to the VertexBasedCellPopulation to visit.
Implements AbstractCellPopulationEventWriter< ELEMENT_DIM, SPACE_DIM >.
Definition at line 98 of file CellRemovalLocationsWriter.cpp.
VisitAnyPopulation()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void CellRemovalLocationsWriter< ELEMENT_DIM, SPACE_DIM >::VisitAnyPopulation (AbstractCellPopulation< SPACE_DIM, SPACE_DIM > * pCellPopulation)
Visit the population and write the data.
Outputs a line of tab-separated values of the form: [num divisions] [Div time 0] [Div 0 x-pos] [Div 0 y-pos] [Div 0 z-pos] [Parent 0 Age] [Parent 0 ID] [Child 0 ID] [Div time 1] [Div 1 x-pos] ...
where [num divisions] denotes the number of Divisions since the previous output step with other information about each division event.
This line is appended to the output written by AbstractCellBasedWriter, which is a single value [present simulation time], followed by a tab.
Parameters
pCellPopulation a pointer to the population to visit.
Definition at line 52 of file CellRemovalLocationsWriter.cpp.
References AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::ClearRemovalsInformation(), and AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::GetRemovalsInformation().
Friends And Related Symbol Documentation
boost::serialization::access
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> friend class boost::serialization::access friend
Needed for serialization.
Definition at line 53 of file CellRemovalLocationsWriter.hpp.
The documentation for this class was generated from the following files:
cell_based/src/writers/population_event_writers/CellRemovalLocationsWriter.hpp
cell_based/src/writers/population_event_writers/CellRemovalLocationsWriter.cpp