Chaste: EdgeRemapInfo Class Reference
EdgeRemapInfo Class Reference
#include <EdgeRemapInfo.hpp>
Public Member Functions
EdgeRemapInfo ()
~EdgeRemapInfo ()
EdgeRemapInfo (const std::vector< long > &rEdgesMapping, const std::vector< unsigned > &rEdgesStatus)
std::vector< long > GetEdgesMapping () const
std::vector< unsigned > GetEdgesStatus () const
std::vector< double > GetSplitProportions () const
void SetSplitProportions (const std::vector< double > proportions)
bool GetUnused () const
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Private Attributes
bool mUnused = true
std::vector< long > mEdgesMapping
std::vector< unsigned > mEdgeStatus
std::vector< double > mSplitProportions
Friends
class boost::serialization::access
Detailed Description
Storage class contains a mapping to the old local edge indices and status of the new edges.
Definition at line 50 of file EdgeRemapInfo.hpp.
Constructor & Destructor Documentation
EdgeRemapInfo() [1/2]
EdgeRemapInfo::EdgeRemapInfo ()
Default constructor. Does nothing.
Definition at line 38 of file EdgeRemapInfo.cpp.
~EdgeRemapInfo()
EdgeRemapInfo::~EdgeRemapInfo ()
Destructor.
Definition at line 42 of file EdgeRemapInfo.cpp.
EdgeRemapInfo() [2/2]
EdgeRemapInfo::EdgeRemapInfo (const std::vector< long > & rEdgesMapping, const std::vector< unsigned > & rEdgesStatus)
Constructor for edge remapping.
Parameters
rEdgesMapping the map between the new edge indices and their local index in the element prior to rearrangement
rEdgesStatus status of the edges in the element
Definition at line 46 of file EdgeRemapInfo.cpp.
Member Function Documentation
GetEdgesMapping()
std::vector< long > EdgeRemapInfo::GetEdgesMapping () const
Contains a mapping to the old local edges index. Negative value means a new edge
Returns
edge map
Definition at line 54 of file EdgeRemapInfo.cpp.
References mEdgesMapping.
Referenced by VertexBasedPopulationSrn< DIM >::RemapCellSrn().
GetEdgesStatus()
std::vector< unsigned > EdgeRemapInfo::GetEdgesStatus () const
Returns
vector containing the status of each edge
Definition at line 59 of file EdgeRemapInfo.cpp.
References mEdgeStatus.
Referenced by VertexBasedPopulationSrn< DIM >::RemapCellSrn().
GetSplitProportions()
std::vector< double > EdgeRemapInfo::GetSplitProportions () const
Returns
split proportions. Used in VertexBasedPopulationSrn class.
Definition at line 64 of file EdgeRemapInfo.cpp.
References mSplitProportions.
Referenced by VertexBasedPopulationSrn< DIM >::RemapCellSrn().
GetUnused()
bool EdgeRemapInfo::GetUnused () const
Returns
mUnused.
Definition at line 74 of file EdgeRemapInfo.cpp.
References mUnused.
serialize()
template<class Archive > void EdgeRemapInfo::serialize (Archive & archive, const unsigned int version) inline private
Archive the object.
Parameters
archive the archive
version the current version of this class
Definition at line 93 of file EdgeRemapInfo.hpp.
References mEdgesMapping, mEdgeStatus, mSplitProportions, and mUnused.
SetSplitProportions()
void EdgeRemapInfo::SetSplitProportions (const std::vector< double > proportions)
Set split proportions. Used in VertexMeshOperationRecorder class.
Parameters
proportions new split proportions
Definition at line 69 of file EdgeRemapInfo.cpp.
References mSplitProportions.
Referenced by VertexMeshOperationRecorder< ELEMENT_DIM, SPACE_DIM >::RecordCellDivideOperation(), and VertexMeshOperationRecorder< ELEMENT_DIM, SPACE_DIM >::RecordEdgeSplitOperation().
Friends And Related Symbol Documentation
boost::serialization::access
friend class boost::serialization::access friend
Needed for serialization.
Definition at line 85 of file EdgeRemapInfo.hpp.
Member Data Documentation
mEdgesMapping
std::vector<long> EdgeRemapInfo::mEdgesMapping private
Contains a mapping to the old local edge indices. Negative value means a new edge.
Definition at line 64 of file EdgeRemapInfo.hpp.
Referenced by GetEdgesMapping(), and serialize().
mEdgeStatus
std::vector<unsigned> EdgeRemapInfo::mEdgeStatus private
Status: 0 - Edge has not changed 1 - Edge has been split between two elements 2 - Completely new edge was created 3 - Edge above or below the current edge was deleted 4 - Edge above has been merged into the current one
Definition at line 74 of file EdgeRemapInfo.hpp.
Referenced by GetEdgesStatus(), and serialize().
mSplitProportions
std::vector<double> EdgeRemapInfo::mSplitProportions private
Determines how close the new node on the split edges is to the previous (lower) node. Value of 0 means the new node is at the same position as the lower node, and value of 1 means that its at the upper node of the edge to be split.
Definition at line 82 of file EdgeRemapInfo.hpp.
Referenced by GetSplitProportions(), serialize(), and SetSplitProportions().
mUnused
bool EdgeRemapInfo::mUnused = true private
Whether the EdgeMapInfor is unused. Initialised to false in the constructor.
Definition at line 58 of file EdgeRemapInfo.hpp.
Referenced by GetUnused(), and serialize().
The documentation for this class was generated from the following files:
mesh/src/common/EdgeRemapInfo.hpp
mesh/src/common/EdgeRemapInfo.cpp