Chaste: LuoRudySpiralWaveCellFactory Class Reference
LuoRudySpiralWaveCellFactory Class Reference
#include <LuoRudySpiralWaveCellFactory.hpp>
Public Member Functions
LuoRudySpiralWaveCellFactory (double xExtent, double yExtent)
AbstractCardiacCell * CreateCardiacCellForTissueNode (Node< 2 > *pNode)
Public Member Functions inherited from AbstractCardiacCellFactory< 2 >
virtual AbstractCardiacCellInterface * CreateCardiacCellForNode (Node< SPACE_DIM > *pNode)
virtual AbstractCardiacCellInterface * CreateCardiacCellForTissueNode (Node< SPACE_DIM > *pNode)=0
virtual void FinaliseCellCreation (std::vector< AbstractCardiacCellInterface * > *pCellsDistributed, unsigned lo, unsigned hi)
virtual void FillInCellularTransmuralAreas ()
virtual unsigned GetNumberOfCells ()
AbstractCardiacCellFactory (boost::shared_ptr< AbstractIvpOdeSolver > pSolver=boost::shared_ptr< AbstractIvpOdeSolver >(new EulerIvpOdeSolver))
virtual ~AbstractCardiacCellFactory ()
virtual void SetMesh (AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM > *pMesh)
AbstractTetrahedralMesh< ELEMENT_DIM, SPACE_DIM > * GetMesh ()
void SetHeartGeometryInformation (HeartGeometryInformation< SPACE_DIM > *pHeartGeometryInformation)
HeartGeometryInformation< SPACE_DIM > * GetHeartGeometryInformation ()
Private Attributes
boost::shared_ptr< SimpleStimulus > mpS1Stimulus
boost::shared_ptr< SimpleStimulus > mpS2Stimulus
boost::shared_ptr< MultiStimulus > mpBothStimulus
double mXExtent
double mYExtent
Additional Inherited Members
Protected Attributes inherited from AbstractCardiacCellFactory< 2 >
boost::shared_ptr< ZeroStimulus > mpZeroStimulus
boost::shared_ptr< AbstractIvpOdeSolver > mpSolver
Detailed Description
This class sets up Luo Rudy 1991 backward Euler cells with a change to parameters (G_si = 0) and S1-S2 stimulus pattern that together provoke spiral wave initiation.
Definition at line 49 of file LuoRudySpiralWaveCellFactory.hpp.
Constructor & Destructor Documentation
LuoRudySpiralWaveCellFactory()
LuoRudySpiralWaveCellFactory::LuoRudySpiralWaveCellFactory (double xExtent, double yExtent) inline
Constructor for spiral wave cell factory.
Parameters
xExtent The size of the domain (width)
yExtent The size of the domain (height)
Definition at line 69 of file LuoRudySpiralWaveCellFactory.hpp.
References mpBothStimulus, mpS1Stimulus, and mpS2Stimulus.
Member Function Documentation
CreateCardiacCellForTissueNode()
AbstractCardiacCell * LuoRudySpiralWaveCellFactory::CreateCardiacCellForTissueNode (Node< 2 > * pNode) inline
This method is provided by all factories, and returns an action potential model with the correct stimulus for that location. Here we set up some cells with S1 and S2, some with S1 and some with S2, to initiate a spiral wave. We also alter one of the conductances in the model to make the wave easier to initiate on this small domain.
Parameters
pNode the pointer to Node object we would like an action potential model for
Returns
a cardiac cell for this node
Definition at line 90 of file LuoRudySpiralWaveCellFactory.hpp.
References AbstractCardiacCell::GetAnyVariable(), Node< SPACE_DIM >::GetIndex(), mpBothStimulus, mpS1Stimulus, mpS2Stimulus, AbstractCardiacCellFactory< 2 >::mpSolver, AbstractCardiacCellFactory< 2 >::mpZeroStimulus, mXExtent, mYExtent, Node< SPACE_DIM >::rGetLocation(), and AbstractCardiacCell::SetParameter().
Member Data Documentation
mpBothStimulus
boost::shared_ptr<MultiStimulus> LuoRudySpiralWaveCellFactory::mpBothStimulus private
Both of the S1 and S2 stimuli.
Definition at line 57 of file LuoRudySpiralWaveCellFactory.hpp.
Referenced by LuoRudySpiralWaveCellFactory(), and CreateCardiacCellForTissueNode().
mpS1Stimulus
boost::shared_ptr<SimpleStimulus> LuoRudySpiralWaveCellFactory::mpS1Stimulus private
The stimulus to be applied at the S1 site (simple one-off stimulus).
Definition at line 53 of file LuoRudySpiralWaveCellFactory.hpp.
Referenced by LuoRudySpiralWaveCellFactory(), and CreateCardiacCellForTissueNode().
mpS2Stimulus
boost::shared_ptr<SimpleStimulus> LuoRudySpiralWaveCellFactory::mpS2Stimulus private
The stimulus to be applied at the S2 site (simple one-off stimulus).
Definition at line 55 of file LuoRudySpiralWaveCellFactory.hpp.
Referenced by LuoRudySpiralWaveCellFactory(), and CreateCardiacCellForTissueNode().
mXExtent
double LuoRudySpiralWaveCellFactory::mXExtent private
Width of the domain.
Definition at line 59 of file LuoRudySpiralWaveCellFactory.hpp.
Referenced by CreateCardiacCellForTissueNode().
mYExtent
double LuoRudySpiralWaveCellFactory::mYExtent private
Height of the domain.
Definition at line 61 of file LuoRudySpiralWaveCellFactory.hpp.
Referenced by CreateCardiacCellForTissueNode().
The documentation for this class was generated from the following file:
heart/src/fortests/LuoRudySpiralWaveCellFactory.hpp