Chaste: ImmersedBoundaryMorseMembraneForce< DIM > Class Template Reference
ImmersedBoundaryMorseMembraneForce< DIM > Class Template Reference
#include <ImmersedBoundaryMorseMembraneForce.hpp>
Public Member Functions
ImmersedBoundaryMorseMembraneForce ()
virtual ~ImmersedBoundaryMorseMembraneForce ()
void AddImmersedBoundaryForceContribution (std::vector< std::pair< Node< DIM > *, Node< DIM > * > > &rNodePairs, ImmersedBoundaryCellPopulation< DIM > &rCellPopulation)
void OutputImmersedBoundaryForceParameters (out_stream &rParamsFile)
double GetElementWellDepth () const
void SetElementWellDepth (double elementWellDepth)
double GetElementRestLength () const
void SetElementRestLength (double elementRestLength)
double GetLaminaWellDepth () const
void SetLaminaWellDepth (double laminaWellDepth)
double GetLaminaRestLength () const
void SetLaminaRestLength (double laminaRestLength)
double GetWellWidth () const
void SetWellWidth (double wellWidth)
Public Member Functions inherited from AbstractImmersedBoundaryForce< DIM >
AbstractImmersedBoundaryForce ()
virtual ~AbstractImmersedBoundaryForce ()
bool GetAdditiveNormalNoise () const
void SetAdditiveNormalNoise (bool additiveNormalNoise)
double GetNormalNoiseMean () const
void SetNormalNoiseMean (double normalNoiseMean)
double GetNormalNoiseStdDev () const
void SetNormalNoiseStdDev (double normalNoiseStdDev)
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
template<unsigned ELEMENT_DIM>
void CalculateForcesOnElement (ImmersedBoundaryElement< ELEMENT_DIM, DIM > &rElement, ImmersedBoundaryCellPopulation< DIM > &rCellPopulation, double intrinsicSpacingSquared)
Private Attributes
double mElementWellDepth
double mElementRestLength
double mLaminaWellDepth
double mLaminaRestLength
double mWellWidth
Friends
class boost::serialization::access
Additional Inherited Members
Protected Member Functions inherited from AbstractImmersedBoundaryForce< DIM >
void AddNormalNoiseToNodes (ImmersedBoundaryCellPopulation< DIM > &rCellPopulation)
Protected Attributes inherited from AbstractImmersedBoundaryForce< DIM >
bool mAdditiveNormalNoise
double mNormalNoiseMean
double mNormalNoiseStdDev
Detailed Description
template<unsigned DIM>
class ImmersedBoundaryMorseMembraneForce< DIM >
A force class for use in immersed boundary simulations. This force implements Morse-potential-like links between adjacent nodes in each immersed boundary (https://en.wikipedia.org/wiki/Morse_potential). The well width is a constant interaction strength, the rest length is an equilibrium bond distance, and the well width is a parameter governing the profile of the curve.
Definition at line 53 of file ImmersedBoundaryMorseMembraneForce.hpp.
Constructor & Destructor Documentation
ImmersedBoundaryMorseMembraneForce()
template<unsigned DIM> ImmersedBoundaryMorseMembraneForce< DIM >::ImmersedBoundaryMorseMembraneForce ()
Constructor
Definition at line 39 of file ImmersedBoundaryMorseMembraneForce.cpp.
~ImmersedBoundaryMorseMembraneForce()
template<unsigned DIM> ImmersedBoundaryMorseMembraneForce< DIM >::~ImmersedBoundaryMorseMembraneForce () virtual
Destructor
Definition at line 50 of file ImmersedBoundaryMorseMembraneForce.cpp.
Member Function Documentation
AddImmersedBoundaryForceContribution()
template<unsigned DIM> void ImmersedBoundaryMorseMembraneForce< DIM >::AddImmersedBoundaryForceContribution (std::vector< std::pair< Node< DIM > *, Node< DIM > * > > & rNodePairs, ImmersedBoundaryCellPopulation< DIM > & rCellPopulation) virtual
Overridden AddImmersedBoundaryForceContribution() method. Calculates basic elasticity in the membrane of each immersed boundary as a result of interactions.
Parameters
rNodePairs reference to a vector set of node pairs between which to contribute the force
rCellPopulation reference to the cell population
Implements AbstractImmersedBoundaryForce< DIM >.
Definition at line 55 of file ImmersedBoundaryMorseMembraneForce.cpp.
References ImmersedBoundaryMesh< ELEMENT_DIM, SPACE_DIM >::GetElementIteratorBegin(), ImmersedBoundaryMesh< ELEMENT_DIM, SPACE_DIM >::GetElementIteratorEnd(), ImmersedBoundaryCellPopulation< DIM >::GetIntrinsicSpacing(), ImmersedBoundaryMesh< ELEMENT_DIM, SPACE_DIM >::GetLaminaIteratorBegin(), ImmersedBoundaryMesh< ELEMENT_DIM, SPACE_DIM >::GetLaminaIteratorEnd(), and ImmersedBoundaryCellPopulation< DIM >::rGetMesh().
CalculateForcesOnElement()
template<unsigned DIM> template<unsigned ELEMENT_DIM> void ImmersedBoundaryMorseMembraneForce< DIM >::CalculateForcesOnElement (ImmersedBoundaryElement< ELEMENT_DIM, DIM > & rElement, ImmersedBoundaryCellPopulation< DIM > & rCellPopulation, double intrinsicSpacingSquared) private
Helper method for AddImmersedBoundaryForceContribution. Calculates forces, and can accept either an element or a lamina
Template Parameters
ELEMENT_DIM either DIM or DIM-1 depending on whether receiving an element or a lamina
Parameters
rElement the element or lamina add forces to
rCellPopulation the immersed boundary cell population
intrinsicSpacingSquared the square of the intrinsic spacing
Definition at line 86 of file ImmersedBoundaryMorseMembraneForce.cpp.
References ImmersedBoundaryMesh< ELEMENT_DIM, SPACE_DIM >::GetAverageNodeSpacingOfElement(), ImmersedBoundaryMesh< ELEMENT_DIM, SPACE_DIM >::GetAverageNodeSpacingOfLamina(), AbstractElement< ELEMENT_DIM, SPACE_DIM >::GetIndex(), AbstractElement< ELEMENT_DIM, SPACE_DIM >::GetNode(), AbstractElement< ELEMENT_DIM, SPACE_DIM >::GetNodeLocation(), AbstractElement< ELEMENT_DIM, SPACE_DIM >::GetNumNodes(), ImmersedBoundaryMesh< ELEMENT_DIM, SPACE_DIM >::GetVectorFromAtoB(), and ImmersedBoundaryCellPopulation< DIM >::rGetMesh().
GetElementRestLength()
template<unsigned DIM> double ImmersedBoundaryMorseMembraneForce< DIM >::GetElementRestLength () const
Returns
mElementRestLength
Definition at line 190 of file ImmersedBoundaryMorseMembraneForce.cpp.
GetElementWellDepth()
template<unsigned DIM> double ImmersedBoundaryMorseMembraneForce< DIM >::GetElementWellDepth () const
Returns
mElementWellDepth
Definition at line 177 of file ImmersedBoundaryMorseMembraneForce.cpp.
GetLaminaRestLength()
template<unsigned DIM> double ImmersedBoundaryMorseMembraneForce< DIM >::GetLaminaRestLength () const
Returns
mLaminaRestLength
Definition at line 216 of file ImmersedBoundaryMorseMembraneForce.cpp.
GetLaminaWellDepth()
template<unsigned DIM> double ImmersedBoundaryMorseMembraneForce< DIM >::GetLaminaWellDepth () const
Returns
mLaminaWellDepth
Definition at line 203 of file ImmersedBoundaryMorseMembraneForce.cpp.
GetWellWidth()
template<unsigned DIM> double ImmersedBoundaryMorseMembraneForce< DIM >::GetWellWidth () const
Returns
mWellWidth
Definition at line 229 of file ImmersedBoundaryMorseMembraneForce.cpp.
OutputImmersedBoundaryForceParameters()
template<unsigned DIM> void ImmersedBoundaryMorseMembraneForce< DIM >::OutputImmersedBoundaryForceParameters (out_stream & rParamsFile) virtual
Overridden OutputImmersedBoundaryForceParameters() method.
Parameters
rParamsFile the file stream to which the parameters are output
Implements AbstractImmersedBoundaryForce< DIM >.
Definition at line 163 of file ImmersedBoundaryMorseMembraneForce.cpp.
References AbstractImmersedBoundaryForce< DIM >::OutputImmersedBoundaryForceParameters().
serialize()
template<unsigned DIM> template<class Archive > void ImmersedBoundaryMorseMembraneForce< DIM >::serialize (Archive & archive, const unsigned int version) inline private
Boost Serialization method for archiving/checkpointing. Archives the object and its member variables.
Parameters
archive The boost archive.
version The current version of this class.
Definition at line 65 of file ImmersedBoundaryMorseMembraneForce.hpp.
References ImmersedBoundaryMorseMembraneForce< DIM >::mElementRestLength, ImmersedBoundaryMorseMembraneForce< DIM >::mElementWellDepth, ImmersedBoundaryMorseMembraneForce< DIM >::mLaminaRestLength, ImmersedBoundaryMorseMembraneForce< DIM >::mLaminaWellDepth, and ImmersedBoundaryMorseMembraneForce< DIM >::mWellWidth.
SetElementRestLength()
template<unsigned DIM> void ImmersedBoundaryMorseMembraneForce< DIM >::SetElementRestLength (double elementRestLength)
Set mElementRestLength/
Parameters
elementRestLength the new value of mElementRestLength
Definition at line 196 of file ImmersedBoundaryMorseMembraneForce.cpp.
SetElementWellDepth()
template<unsigned DIM> void ImmersedBoundaryMorseMembraneForce< DIM >::SetElementWellDepth (double elementWellDepth)
Set mElementWellDepth.
Parameters
elementWellDepth the new value of mElementWellDepth
Definition at line 183 of file ImmersedBoundaryMorseMembraneForce.cpp.
SetLaminaRestLength()
template<unsigned DIM> void ImmersedBoundaryMorseMembraneForce< DIM >::SetLaminaRestLength (double laminaRestLength)
Set mLaminaRestLength/
Parameters
laminaRestLength the new value of mLaminaRestLength
Definition at line 222 of file ImmersedBoundaryMorseMembraneForce.cpp.
SetLaminaWellDepth()
template<unsigned DIM> void ImmersedBoundaryMorseMembraneForce< DIM >::SetLaminaWellDepth (double laminaWellDepth)
Set mLaminaWellDepth.
Parameters
laminaWellDepth the new value of mLaminaWellDepth
Definition at line 209 of file ImmersedBoundaryMorseMembraneForce.cpp.
SetWellWidth()
template<unsigned DIM> void ImmersedBoundaryMorseMembraneForce< DIM >::SetWellWidth (double wellWidth)
Set mWellWidth.
Parameters
wellWidth the new value of mWellWidth
Definition at line 235 of file ImmersedBoundaryMorseMembraneForce.cpp.
Friends And Related Symbol Documentation
boost::serialization::access
template<unsigned DIM> friend class boost::serialization::access friend
Definition at line 56 of file ImmersedBoundaryMorseMembraneForce.hpp.
Member Data Documentation
mElementRestLength
template<unsigned DIM> double ImmersedBoundaryMorseMembraneForce< DIM >::mElementRestLength private
The rest length associated with each element as a fraction of the average node spacing. Initialised to 0.5 in constructor.
Definition at line 84 of file ImmersedBoundaryMorseMembraneForce.hpp.
Referenced by ImmersedBoundaryMorseMembraneForce< DIM >::serialize().
mElementWellDepth
template<unsigned DIM> double ImmersedBoundaryMorseMembraneForce< DIM >::mElementWellDepth private
The basic interaction strength. Initialised to 1e6 in constructor.
Definition at line 78 of file ImmersedBoundaryMorseMembraneForce.hpp.
Referenced by ImmersedBoundaryMorseMembraneForce< DIM >::serialize().
mLaminaRestLength
template<unsigned DIM> double ImmersedBoundaryMorseMembraneForce< DIM >::mLaminaRestLength private
The rest length associated with each lamina as a fraction of the average node spacing. Initialised to 0.5 in constructor.
Definition at line 96 of file ImmersedBoundaryMorseMembraneForce.hpp.
Referenced by ImmersedBoundaryMorseMembraneForce< DIM >::serialize().
mLaminaWellDepth
template<unsigned DIM> double ImmersedBoundaryMorseMembraneForce< DIM >::mLaminaWellDepth private
The spring constant associated with each lamina. Initialised to 1e6 in constructor.
Definition at line 90 of file ImmersedBoundaryMorseMembraneForce.hpp.
Referenced by ImmersedBoundaryMorseMembraneForce< DIM >::serialize().
mWellWidth
template<unsigned DIM> double ImmersedBoundaryMorseMembraneForce< DIM >::mWellWidth private
The well width as a fraction of the average node spacing in either an element or lamina. Initialised to 0.25 in constructor.
Definition at line 102 of file ImmersedBoundaryMorseMembraneForce.hpp.
Referenced by ImmersedBoundaryMorseMembraneForce< DIM >::serialize().
The documentation for this class was generated from the following files:
cell_based/src/population/forces/ImmersedBoundaryMorseMembraneForce.hpp
cell_based/src/population/forces/ImmersedBoundaryMorseMembraneForce.cpp