Chaste: Goldbeter1991SrnModel Class Reference
Goldbeter1991SrnModel Class Reference
#include <Goldbeter1991SrnModel.hpp>
Public Member Functions
Goldbeter1991SrnModel (boost::shared_ptr< AbstractCellCycleModelOdeSolver > pOdeSolver=boost::shared_ptr< AbstractCellCycleModelOdeSolver >())
AbstractSrnModel * CreateSrnModel ()
void Initialise ()
void SimulateToCurrentTime ()
void OutputSrnModelParameters (out_stream &rParamsFile)
double GetC ()
double GetM ()
double GetX ()
Public Member Functions inherited from AbstractOdeSrnModel
AbstractOdeSrnModel (unsigned stateSize, boost::shared_ptr< AbstractCellCycleModelOdeSolver > pOdeSolver=boost::shared_ptr< AbstractCellCycleModelOdeSolver >())
virtual ~AbstractOdeSrnModel ()
virtual void ResetForDivision ()
void SetInitialConditions (std::vector< double > initialConditions)
virtual void ScaleSrnVariables (const double theta)
Public Member Functions inherited from AbstractSrnModel
AbstractSrnModel ()
virtual ~AbstractSrnModel ()
virtual void SetCell (CellPtr pCell)
virtual void InitialiseDaughterCell ()
CellPtr GetCell ()
void SetSimulatedToTime (double simulatedToTime)
double GetSimulatedToTime () const
void OutputSrnModelInfo (out_stream &rParamsFile)
void SetEdgeLocalIndex (unsigned index)
unsigned GetEdgeLocalIndex ()
bool HasEdgeModel () const
void SetEdgeModelIndicator (const bool isEdgeModel)
virtual void AddSrnQuantities (AbstractSrnModel *pOtherSrn, const double scale=1.0)
virtual void AddShrunkEdgeSrn (AbstractSrnModel *pShrunkEdgeSrn)
virtual void AddMergedEdgeSrn (AbstractSrnModel *pMergedEdgeSrn)
virtual void AddShrunkEdgeToInterior (AbstractSrnModel *pShrunkEdgeSrn)
virtual void SplitEdgeSrn (const double relativePosition)
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Public Member Functions inherited from CellCycleModelOdeHandler
CellCycleModelOdeHandler (double lastTime=SimulationTime::Instance() ->GetTime(), boost::shared_ptr< AbstractCellCycleModelOdeSolver > pOdeSolver=boost::shared_ptr< AbstractCellCycleModelOdeSolver >())
virtual ~CellCycleModelOdeHandler ()
AbstractOdeSystem * GetOdeSystem () const
void SetOdeSystem (AbstractOdeSystem *pOdeSystem)
const boost::shared_ptr< AbstractCellCycleModelOdeSolver > GetOdeSolver () const
void SetLastTime (double lastTime)
double GetDt ()
void SetDt (double timeStep)
void SetStateVariables (const std::vector< double > &rStateVariables)
std::vector< double > GetProteinConcentrations () const
void SetProteinConcentrationsForTestsOnly (double lastTime, std::vector< double > proteinConcentrations)
Protected Member Functions
Goldbeter1991SrnModel (const Goldbeter1991SrnModel &rModel)
Protected Member Functions inherited from AbstractOdeSrnModel
void Initialise (AbstractOdeSystem *pOdeSystem)
AbstractOdeSrnModel (const AbstractOdeSrnModel &rModel)
Protected Member Functions inherited from AbstractSrnModel
AbstractSrnModel (const AbstractSrnModel &rModel)
Protected Member Functions inherited from CellCycleModelOdeHandler
CellCycleModelOdeHandler (const CellCycleModelOdeHandler &rHandler)
bool SolveOdeToTime (double currentTime)
virtual void AdjustOdeParameters (double currentTime)
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Friends
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from AbstractOdeSrnModel
std::vector< double > mInitialConditions
unsigned mStateSize
Protected Attributes inherited from AbstractSrnModel
CellPtr mpCell
double mSimulatedToTime
unsigned mEdgeLocalIndex = UNSIGNED_UNSET
bool mIsEdgeBasedModel = false
Protected Attributes inherited from CellCycleModelOdeHandler
double mDt
AbstractOdeSystem * mpOdeSystem
boost::shared_ptr< AbstractCellCycleModelOdeSolver > mpOdeSolver
double mLastTime
bool mFinishedRunningOdes
Detailed Description
A Subcellular Reaction Network Model that includes a Goldbeter1991 ODE system in the sub-cellular reaction network.
Todo:
#2752 give reference for this ODE system
Definition at line 51 of file Goldbeter1991SrnModel.hpp.
Constructor & Destructor Documentation
Goldbeter1991SrnModel() [1/2]
Goldbeter1991SrnModel::Goldbeter1991SrnModel (const Goldbeter1991SrnModel & rModel) protected
Protected copy-constructor for use by CreateSrnModel(). The only way for external code to create a copy of a SRN model is by calling that method, to ensure that a model of the correct subclass is created.
This copy-constructor helps subclasses to ensure that all member variables are correctly copied when this happens.
This method is called by child classes to set member variables for a daughter cell upon cell division. Note that the parent SRN model will have had ResetForDivision() called just before CreateSrnModel() is called, so performing an exact copy of the parent is suitable behaviour. Any daughter-cell-specific initialisation can be done in InitialiseDaughterCell().
Parameters
rModel the SRN model to copy.
Definition at line 51 of file Goldbeter1991SrnModel.cpp.
References CellCycleModelOdeHandler::GetOdeSystem(), AbstractParameterisedSystem< VECTOR >::rGetStateVariables(), and CellCycleModelOdeHandler::SetOdeSystem().
Goldbeter1991SrnModel() [2/2]
Goldbeter1991SrnModel::Goldbeter1991SrnModel (boost::shared_ptr< AbstractCellCycleModelOdeSolver > pOdeSolver = boost::shared_ptr<AbstractCellCycleModelOdeSolver>())
Default constructor calls base class.
Parameters
pOdeSolver An optional pointer to a cell-cycle model ODE solver object (allows the use of different ODE solvers)
Definition at line 38 of file Goldbeter1991SrnModel.cpp.
References CellCycleModelOdeSolver< CELL_CYCLE_MODEL, ODE_SOLVER >::Instance(), CellCycleModelOdeHandler::mpOdeSolver, and CellCycleModelOdeHandler::SetDt().
Member Function Documentation
CreateSrnModel()
AbstractSrnModel * Goldbeter1991SrnModel::CreateSrnModel () virtual
Overridden builder method to create new copies of this SRN model.
Returns
Returns a copy of the current SRN model.
Implements AbstractSrnModel.
Definition at line 73 of file Goldbeter1991SrnModel.cpp.
GetC()
double Goldbeter1991SrnModel::GetC ()
Returns
the value of the state variable C in the ODE system.
Definition at line 95 of file Goldbeter1991SrnModel.cpp.
References CellCycleModelOdeHandler::mpOdeSystem, and AbstractParameterisedSystem< VECTOR >::rGetStateVariables().
GetM()
double Goldbeter1991SrnModel::GetM ()
Returns
the value of the state variable M in the ODE system.
Definition at line 102 of file Goldbeter1991SrnModel.cpp.
References CellCycleModelOdeHandler::mpOdeSystem, and AbstractParameterisedSystem< VECTOR >::rGetStateVariables().
GetX()
double Goldbeter1991SrnModel::GetX ()
Returns
the value of the state variable X in the ODE system.
Definition at line 109 of file Goldbeter1991SrnModel.cpp.
References CellCycleModelOdeHandler::mpOdeSystem, and AbstractParameterisedSystem< VECTOR >::rGetStateVariables().
Initialise()
void Goldbeter1991SrnModel::Initialise () virtual
Initialise the SRN model at the start of a simulation.
This overridden method sets up a new Delta-Notch ODE system.
Reimplemented from AbstractOdeSrnModel.
Definition at line 84 of file Goldbeter1991SrnModel.cpp.
References AbstractOdeSrnModel::Initialise().
OutputSrnModelParameters()
void Goldbeter1991SrnModel::OutputSrnModelParameters (out_stream & rParamsFile) virtual
Output SRN model parameters to file.
Parameters
rParamsFile the file stream to which the parameters are output
Reimplemented from AbstractOdeSrnModel.
Definition at line 89 of file Goldbeter1991SrnModel.cpp.
References AbstractOdeSrnModel::OutputSrnModelParameters().
serialize()
template<class Archive > void Goldbeter1991SrnModel::serialize (Archive & archive, const unsigned int version) inline private
Archive the SRN model and member variables.
Parameters
archive the archive
version the current version of this class
Definition at line 64 of file Goldbeter1991SrnModel.hpp.
SimulateToCurrentTime()
void Goldbeter1991SrnModel::SimulateToCurrentTime () virtual
Overridden SimulateToTime() method for custom behaviour.
Todo:
#2752 say what it does in this class
Reimplemented from AbstractOdeSrnModel.
Definition at line 78 of file Goldbeter1991SrnModel.cpp.
References AbstractOdeSrnModel::SimulateToCurrentTime().
Friends And Related Symbol Documentation
boost::serialization::access
friend class boost::serialization::access friend
Needed for serialization.
Definition at line 56 of file Goldbeter1991SrnModel.hpp.
The documentation for this class was generated from the following files:
cell_based/src/cell/srn/Goldbeter1991SrnModel.hpp
cell_based/src/cell/srn/Goldbeter1991SrnModel.cpp