Chaste: AbstractCellKiller< SPACE_DIM > Class Template Reference
AbstractCellKiller< SPACE_DIM > Class Template Reference abstract
#include <AbstractCellKiller.hpp>
Public Member Functions
AbstractCellKiller (AbstractCellPopulation< SPACE_DIM > *pCellPopulation)
virtual ~AbstractCellKiller ()
virtual void CheckAndLabelCellsForApoptosisOrDeath ()=0
const AbstractCellPopulation< SPACE_DIM > * GetCellPopulation () const
void OutputCellKillerInfo (out_stream &rParamsFile)
virtual void OutputCellKillerParameters (out_stream &rParamsFile)=0
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Protected Attributes
AbstractCellPopulation< SPACE_DIM > * mpCellPopulation
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Friends
class boost::serialization::access
Detailed Description
template<unsigned SPACE_DIM>
class AbstractCellKiller< SPACE_DIM >
An abstract cell killer class, for use in cell-based simulations.
Definition at line 50 of file AbstractCellKiller.hpp.
Constructor & Destructor Documentation
AbstractCellKiller()
template<unsigned SPACE_DIM> AbstractCellKiller< SPACE_DIM >::AbstractCellKiller (AbstractCellPopulation< SPACE_DIM > * pCellPopulation)
Constructor.
Parameters
pCellPopulation pointer to the cell population.
Definition at line 39 of file AbstractCellKiller.cpp.
~AbstractCellKiller()
template<unsigned SPACE_DIM> AbstractCellKiller< SPACE_DIM >::~AbstractCellKiller () virtual
Destructor.
Definition at line 45 of file AbstractCellKiller.cpp.
Member Function Documentation
CheckAndLabelCellsForApoptosisOrDeath()
template<unsigned SPACE_DIM> virtual void AbstractCellKiller< SPACE_DIM >::CheckAndLabelCellsForApoptosisOrDeath () pure virtual
Pure virtual; method which should call StartApoptosisOnCell() on the population passing the cell which should be about to undergo programmed death, or KillCell() on the population passing the cell which should die immediately.
As this method is pure virtual, it must be overridden in subclasses.
Implemented in ApoptoticCellKiller< SPACE_DIM >, IsolatedLabelledCellKiller< DIM >, PlaneBasedCellKiller< DIM >, RandomCellKiller< DIM >, T2SwapCellKiller< DIM >, TargetedCellKiller< DIM >, RadialSloughingCellKiller, and SloughingCellKiller< DIM >.
GetCellPopulation()
template<unsigned SPACE_DIM> const AbstractCellPopulation< SPACE_DIM > * AbstractCellKiller< SPACE_DIM >::GetCellPopulation () const
Get a pointer to the cell population.
Returns
A const pointer to the mpCellPopulation
Definition at line 50 of file AbstractCellKiller.cpp.
OutputCellKillerInfo()
template<unsigned SPACE_DIM> void AbstractCellKiller< SPACE_DIM >::OutputCellKillerInfo (out_stream & rParamsFile)
Outputs cell killer used in the simulation to file and then calls OutputCellKillerParameters to output all relevant parameters.
Parameters
rParamsFile the file stream to which the parameters are output
Definition at line 56 of file AbstractCellKiller.cpp.
OutputCellKillerParameters()
template<unsigned SPACE_DIM> void AbstractCellKiller< SPACE_DIM >::OutputCellKillerParameters (out_stream & rParamsFile) pure virtual
Outputs cell killer parameters to file
As this method is pure virtual, it must be overridden in subclasses.
Parameters
rParamsFile the file stream to which the parameters are output
Implemented in ApoptoticCellKiller< SPACE_DIM >, IsolatedLabelledCellKiller< DIM >, PlaneBasedCellKiller< DIM >, RandomCellKiller< DIM >, T2SwapCellKiller< DIM >, TargetedCellKiller< DIM >, RadialSloughingCellKiller, and SloughingCellKiller< DIM >.
Definition at line 66 of file AbstractCellKiller.cpp.
Referenced by ApoptoticCellKiller< SPACE_DIM >::OutputCellKillerParameters(), IsolatedLabelledCellKiller< DIM >::OutputCellKillerParameters(), PlaneBasedCellKiller< DIM >::OutputCellKillerParameters(), RandomCellKiller< DIM >::OutputCellKillerParameters(), T2SwapCellKiller< DIM >::OutputCellKillerParameters(), TargetedCellKiller< DIM >::OutputCellKillerParameters(), RadialSloughingCellKiller::OutputCellKillerParameters(), and SloughingCellKiller< DIM >::OutputCellKillerParameters().
serialize()
template<unsigned SPACE_DIM> template<class Archive > void AbstractCellKiller< SPACE_DIM >::serialize (Archive & archive, const unsigned int version) inline private
Serialize the object and its member variables.
Parameters
archive the archive
version the current version of this class
Definition at line 62 of file AbstractCellKiller.hpp.
Friends And Related Symbol Documentation
boost::serialization::access
template<unsigned SPACE_DIM> friend class boost::serialization::access friend
Needed for serialization.
Definition at line 54 of file AbstractCellKiller.hpp.
Member Data Documentation
mpCellPopulation
template<unsigned SPACE_DIM> AbstractCellPopulation<SPACE_DIM>* AbstractCellKiller< SPACE_DIM >::mpCellPopulation protected
The cell population.
Definition at line 70 of file AbstractCellKiller.hpp.
The documentation for this class was generated from the following files:
cell_based/src/population/killers/AbstractCellKiller.hpp
cell_based/src/population/killers/AbstractCellKiller.cpp