Chaste: WntConcentration< DIM > Class Template Reference
WntConcentration< DIM > Class Template Reference
#include <WntConcentration.hpp>
Public Member Functions
virtual ~WntConcentration ()
double GetWntLevel (double height)
double GetWntLevel (CellPtr pCell)
c_vector< double, DIM > GetWntGradient (c_vector< double, DIM > &rLocation)
c_vector< double, DIM > GetWntGradient (CellPtr pCell)
void SetCellPopulation (AbstractCellPopulation< DIM > &rCellPopulation)
AbstractCellPopulation< DIM > & rGetCellPopulation ()
double GetCryptLength ()
void SetCryptLength (double cryptLength)
WntConcentrationType GetType ()
void SetType (WntConcentrationType type)
void SetConstantWntValueForTesting (double value)
bool IsWntSetUp ()
double GetWntConcentrationParameter ()
void SetWntConcentrationParameter (double wntConcentrationParameter)
double GetCryptProjectionParameterA ()
double GetCryptProjectionParameterB ()
void SetCryptProjectionParameterA (double cryptProjectionParameterA)
void SetCryptProjectionParameterB (double cryptProjectionParameterB)
Public Member Functions inherited from SerializableSingleton< WntConcentration< DIM > >
SerializableSingleton< WntConcentration< DIM > > * GetSerializationWrapper () const
Static Public Member Functions
static WntConcentration * Instance ()
static void Destroy ()
Protected Member Functions
WntConcentration ()
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Private Attributes
double mCryptLength
bool mLengthSet
WntConcentrationType mWntType
AbstractCellPopulation< DIM > * mpCellPopulation
bool mTypeSet
double mConstantWntValueForTesting
bool mUseConstantWntValueForTesting
double mWntConcentrationParameter
double mCryptProjectionParameterA
double mCryptProjectionParameterB
Static Private Attributes
static WntConcentration * mpInstance = nullptr
Friends
class boost::serialization::access
Detailed Description
template<unsigned DIM>
class WntConcentration< DIM >
Singleton Wnt concentration object.
Definition at line 66 of file WntConcentration.hpp.
Constructor & Destructor Documentation
WntConcentration()
template<unsigned DIM> WntConcentration< DIM >::WntConcentration () protected
Protected constuctor. Not to be called, use Instance() instead.
Definition at line 52 of file WntConcentration.cpp.
References WntConcentration< DIM >::mpInstance.
Referenced by WntConcentration< DIM >::serialize().
~WntConcentration()
template<unsigned DIM> WntConcentration< DIM >::~WntConcentration () virtual
Destructor - frees up the singleton instance.
Definition at line 69 of file WntConcentration.cpp.
Referenced by WntConcentration< DIM >::serialize().
Member Function Documentation
Destroy()
template<unsigned DIM> void WntConcentration< DIM >::Destroy () static
Destroy the current WntConcentration instance. Should be called at the end of a simulation.
Definition at line 74 of file WntConcentration.cpp.
References WntConcentration< DIM >::mpInstance.
Referenced by CryptVertexBasedDivisionRule< SPACE_DIM >::CalculateCellDivisionVector(), CryptSimulationBoundaryCondition< DIM >::ImposeBoundaryCondition(), and WntConcentration< DIM >::serialize().
GetCryptLength()
template<unsigned DIM> double WntConcentration< DIM >::GetCryptLength ()
Returns
mCryptLength
Definition at line 140 of file WntConcentration.cpp.
References WntConcentration< DIM >::mCryptLength.
Referenced by WntConcentration< DIM >::serialize().
GetCryptProjectionParameterA()
template<unsigned DIM> double WntConcentration< DIM >::GetCryptProjectionParameterA ()
Returns
mCryptProjectionParameterA
Definition at line 299 of file WntConcentration.cpp.
References WntConcentration< DIM >::mCryptProjectionParameterA.
Referenced by CryptProjectionForce::CryptProjectionForce(), WntConcentration< DIM >::GetWntLevel(), and WntConcentration< DIM >::serialize().
GetCryptProjectionParameterB()
template<unsigned DIM> double WntConcentration< DIM >::GetCryptProjectionParameterB ()
Returns
mCryptProjectionParameterB
Definition at line 305 of file WntConcentration.cpp.
References WntConcentration< DIM >::mCryptProjectionParameterB.
Referenced by CryptProjectionForce::CryptProjectionForce(), and WntConcentration< DIM >::serialize().
GetType()
template<unsigned DIM> WntConcentrationType WntConcentration< DIM >::GetType ()
Returns
the type of Wnt concentration.
Definition at line 159 of file WntConcentration.cpp.
References WntConcentration< DIM >::mWntType.
Referenced by SimpleWntCellCycleModel::GetWntType(), and WntConcentration< DIM >::serialize().
GetWntConcentrationParameter()
template<unsigned DIM> double WntConcentration< DIM >::GetWntConcentrationParameter ()
Returns
mWntConcentrationParameter
Definition at line 286 of file WntConcentration.cpp.
References WntConcentration< DIM >::mWntConcentrationParameter.
Referenced by WntConcentration< DIM >::serialize().
GetWntGradient() [1/2]
template<unsigned DIM> c_vector< double, DIM > WntConcentration< DIM >::GetWntGradient (c_vector< double, DIM > & rLocation)
Returns
the Wnt gradient at a given location in the crypt.
Parameters
rLocation the location at which we want the Wnt gradient
Definition at line 219 of file WntConcentration.cpp.
References WntConcentration< DIM >::mWntType.
Referenced by CryptProjectionForce::AddForceContribution(), WntConcentration< DIM >::GetWntGradient(), and WntConcentration< DIM >::serialize().
GetWntGradient() [2/2]
template<unsigned DIM> c_vector< double, DIM > WntConcentration< DIM >::GetWntGradient (CellPtr pCell)
Returns
the Wnt gradient at a given cell in the crypt.
Parameters
pCell the cell at which we want the Wnt gradient
Definition at line 112 of file WntConcentration.cpp.
References AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::GetLocationOfCellCentre(), WntConcentration< DIM >::GetWntGradient(), WntConcentration< DIM >::mLengthSet, WntConcentration< DIM >::mpCellPopulation, WntConcentration< DIM >::mTypeSet, and WntConcentration< DIM >::mUseConstantWntValueForTesting.
GetWntLevel() [1/2]
template<unsigned DIM> double WntConcentration< DIM >::GetWntLevel (double height)
Get the Wnt level at a given height in the crypt.
Parameters
height the height of the cell at which we want the Wnt concentration
Returns
the Wnt concentration at this height in the crypt (dimensionless)
Definition at line 176 of file WntConcentration.cpp.
References WntConcentration< DIM >::mLengthSet, and WntConcentration< DIM >::mWntType.
Referenced by AbstractWntOdeBasedCellCycleModel::GetWntLevel(), SimpleWntCellCycleModel::GetWntLevel(), and WntConcentration< DIM >::serialize().
GetWntLevel() [2/2]
template<unsigned DIM> double WntConcentration< DIM >::GetWntLevel (CellPtr pCell)
Get the Wnt level at a given cell in the crypt. The crypt must be set for this.
Parameters
pCell the cell at which we want the Wnt concentration
Returns
the Wnt concentration at this cell
Definition at line 84 of file WntConcentration.cpp.
References WntConcentration< DIM >::GetCryptProjectionParameterA(), WntConcentration< DIM >::mConstantWntValueForTesting, WntConcentration< DIM >::mLengthSet, WntConcentration< DIM >::mpCellPopulation, WntConcentration< DIM >::mTypeSet, WntConcentration< DIM >::mUseConstantWntValueForTesting, and WntConcentration< DIM >::mWntType.
Instance()
template<unsigned DIM> WntConcentration< DIM > * WntConcentration< DIM >::Instance () static
Return a pointer to the WntConcentration object. The first time this is called, the object is created.
Returns
A pointer to the singleton WntConcentration object.
Definition at line 42 of file WntConcentration.cpp.
Referenced by CryptProjectionForce::AddForceContribution(), CryptVertexBasedDivisionRule< SPACE_DIM >::CalculateCellDivisionVector(), CryptProjectionForce::CryptProjectionForce(), AbstractWntOdeBasedCellCycleModel::GetWntLevel(), SimpleWntCellCycleModel::GetWntLevel(), SimpleWntCellCycleModel::GetWntType(), CryptSimulationBoundaryCondition< DIM >::ImposeBoundaryCondition(), CryptSimulation2d::serialize(), CryptSimulation1d::serialize(), and WntConcentration< DIM >::serialize().
IsWntSetUp()
template<unsigned DIM> bool WntConcentration< DIM >::IsWntSetUp ()
Whether a Wnt concentration has been set up.
For archiving, and to let a CellBasedSimulation find out whether whether a WntConcentration has been set up or not, i.e. whether stem cells should be motile.
Returns
whether the Wnt concentration is set up
Definition at line 260 of file WntConcentration.cpp.
Referenced by CryptVertexBasedDivisionRule< SPACE_DIM >::CalculateCellDivisionVector(), CryptSimulationBoundaryCondition< DIM >::ImposeBoundaryCondition(), and WntConcentration< DIM >::serialize().
rGetCellPopulation()
template<unsigned DIM> AbstractCellPopulation< DIM > & WntConcentration< DIM >::rGetCellPopulation ()
Returns
reference to the CellPopulation.
Definition at line 134 of file WntConcentration.cpp.
References WntConcentration< DIM >::mpCellPopulation.
Referenced by WntConcentration< DIM >::serialize().
serialize()
template<unsigned DIM> template<class Archive > void WntConcentration< DIM >::serialize (Archive & archive, const unsigned int version) inline private
Archive the object and its member variables.
Parameters
archive the archive
version the current version of this class
Definition at line 146 of file WntConcentration.hpp.
References WntConcentration< DIM >::Destroy(), WntConcentration< DIM >::GetCryptLength(), WntConcentration< DIM >::GetCryptProjectionParameterA(), WntConcentration< DIM >::GetCryptProjectionParameterB(), WntConcentration< DIM >::GetType(), WntConcentration< DIM >::GetWntConcentrationParameter(), WntConcentration< DIM >::GetWntGradient(), WntConcentration< DIM >::GetWntLevel(), WntConcentration< DIM >::Instance(), WntConcentration< DIM >::IsWntSetUp(), WntConcentration< DIM >::mConstantWntValueForTesting, WntConcentration< DIM >::mCryptLength, WntConcentration< DIM >::mCryptProjectionParameterA, WntConcentration< DIM >::mCryptProjectionParameterB, WntConcentration< DIM >::mLengthSet, WntConcentration< DIM >::mpCellPopulation, WntConcentration< DIM >::mTypeSet, WntConcentration< DIM >::mUseConstantWntValueForTesting, WntConcentration< DIM >::mWntConcentrationParameter, WntConcentration< DIM >::mWntType, WntConcentration< DIM >::rGetCellPopulation(), WntConcentration< DIM >::SetCellPopulation(), WntConcentration< DIM >::SetConstantWntValueForTesting(), WntConcentration< DIM >::SetCryptLength(), WntConcentration< DIM >::SetCryptProjectionParameterA(), WntConcentration< DIM >::SetCryptProjectionParameterB(), WntConcentration< DIM >::SetType(), WntConcentration< DIM >::SetWntConcentrationParameter(), WntConcentration< DIM >::WntConcentration(), and WntConcentration< DIM >::~WntConcentration().
SetCellPopulation()
template<unsigned DIM> void WntConcentration< DIM >::SetCellPopulation (AbstractCellPopulation< DIM > & rCellPopulation)
Set the crypt. Must be called before GetWntLevel().
Parameters
rCellPopulation reference to the cell population
Definition at line 128 of file WntConcentration.cpp.
References WntConcentration< DIM >::mpCellPopulation.
Referenced by WntConcentration< DIM >::serialize().
SetConstantWntValueForTesting()
template<unsigned DIM> void WntConcentration< DIM >::SetConstantWntValueForTesting (double value)
Force the Wnt concentration to return a given value for all cells. Only for testing.
Parameters
value the constant value to set the Wnt concentration to be
Definition at line 271 of file WntConcentration.cpp.
References EXCEPTION, WntConcentration< DIM >::mConstantWntValueForTesting, WntConcentration< DIM >::mTypeSet, WntConcentration< DIM >::mUseConstantWntValueForTesting, and WntConcentration< DIM >::mWntType.
Referenced by WntConcentration< DIM >::serialize().
SetCryptLength()
template<unsigned DIM> void WntConcentration< DIM >::SetCryptLength (double cryptLength)
Set mCryptLength. Must be called before GetWntLevel().
Parameters
cryptLength the new value of mCryptLength
Definition at line 146 of file WntConcentration.cpp.
References EXCEPTION, WntConcentration< DIM >::mCryptLength, and WntConcentration< DIM >::mLengthSet.
Referenced by WntConcentration< DIM >::serialize().
SetCryptProjectionParameterA()
template<unsigned DIM> void WntConcentration< DIM >::SetCryptProjectionParameterA (double cryptProjectionParameterA)
Set mCryptProjectionParameterA.
Parameters
cryptProjectionParameterA the new value of mCryptProjectionParameterA
Definition at line 311 of file WntConcentration.cpp.
References WntConcentration< DIM >::mCryptProjectionParameterA.
Referenced by WntConcentration< DIM >::serialize().
SetCryptProjectionParameterB()
template<unsigned DIM> void WntConcentration< DIM >::SetCryptProjectionParameterB (double cryptProjectionParameterB)
Set mCryptProjectionParameterB.
Parameters
cryptProjectionParameterB the new value of mCryptProjectionParameterB
Definition at line 318 of file WntConcentration.cpp.
References WntConcentration< DIM >::mCryptProjectionParameterB.
Referenced by WntConcentration< DIM >::serialize().
SetType()
template<unsigned DIM> void WntConcentration< DIM >::SetType (WntConcentrationType type)
Set the type of Wnt concentration. Must be called before GetWntLevel().
Parameters
type the type of Wnt concentration
Definition at line 165 of file WntConcentration.cpp.
References EXCEPTION, WntConcentration< DIM >::mTypeSet, and WntConcentration< DIM >::mWntType.
Referenced by WntConcentration< DIM >::serialize().
SetWntConcentrationParameter()
template<unsigned DIM> void WntConcentration< DIM >::SetWntConcentrationParameter (double wntConcentrationParameter)
Set mWntConcentrationParameter.
Parameters
wntConcentrationParameter the new value of mWntConcentrationParameter
Definition at line 292 of file WntConcentration.cpp.
References WntConcentration< DIM >::mWntConcentrationParameter.
Referenced by WntConcentration< DIM >::serialize().
Friends And Related Function Documentation
boost::serialization::access
template<unsigned DIM> friend class boost::serialization::access friend
Needed for serialization.
Definition at line 138 of file WntConcentration.hpp.
Member Data Documentation
mConstantWntValueForTesting
template<unsigned DIM> double WntConcentration< DIM >::mConstantWntValueForTesting private
A value to return for testing purposes.
Definition at line 104 of file WntConcentration.hpp.
Referenced by WntConcentration< DIM >::GetWntLevel(), WntConcentration< DIM >::serialize(), and WntConcentration< DIM >::SetConstantWntValueForTesting().
mCryptLength
template<unsigned DIM> double WntConcentration< DIM >::mCryptLength private
The length of the crypt.
Definition at line 76 of file WntConcentration.hpp.
Referenced by WntConcentration< DIM >::GetCryptLength(), WntConcentration< DIM >::serialize(), and WntConcentration< DIM >::SetCryptLength().
mCryptProjectionParameterA
template<unsigned DIM> double WntConcentration< DIM >::mCryptProjectionParameterA private
Parameter a, for use in crypt projection simulations, in which the crypt surface is given in cylindrical polar coordinates by z = a*r^b. mCryptProjectionParameterA has no units
Definition at line 128 of file WntConcentration.hpp.
Referenced by WntConcentration< DIM >::GetCryptProjectionParameterA(), WntConcentration< DIM >::serialize(), and WntConcentration< DIM >::SetCryptProjectionParameterA().
mCryptProjectionParameterB
template<unsigned DIM> double WntConcentration< DIM >::mCryptProjectionParameterB private
Parameter b, for use in crypt projection simulations, in which the crypt surface is given in cylindrical polar coordinates by z = a*r^b. mCryptProjectionParameterB has no units
Definition at line 135 of file WntConcentration.hpp.
Referenced by WntConcentration< DIM >::GetCryptProjectionParameterB(), WntConcentration< DIM >::serialize(), and WntConcentration< DIM >::SetCryptProjectionParameterB().
mLengthSet
template<unsigned DIM> bool WntConcentration< DIM >::mLengthSet private
Whether this WntConcentration object has had its crypt length set.
Definition at line 81 of file WntConcentration.hpp.
Referenced by WntConcentration< DIM >::GetWntGradient(), WntConcentration< DIM >::GetWntLevel(), WntConcentration< DIM >::serialize(), and WntConcentration< DIM >::SetCryptLength().
mpCellPopulation
template<unsigned DIM> AbstractCellPopulation<DIM>* WntConcentration< DIM >::mpCellPopulation private
The cell population in which the WntConcentration occurs.
Definition at line 94 of file WntConcentration.hpp.
Referenced by WntConcentration< DIM >::GetWntGradient(), WntConcentration< DIM >::GetWntLevel(), WntConcentration< DIM >::rGetCellPopulation(), WntConcentration< DIM >::serialize(), and WntConcentration< DIM >::SetCellPopulation().
mpInstance
template<unsigned DIM> WntConcentration< DIM > * WntConcentration< DIM >::mpInstance = nullptr static private
Pointer to the singleton instance of WntConcentration
Pointer to the single instance
Definition at line 71 of file WntConcentration.hpp.
Referenced by WntConcentration< DIM >::Destroy(), and WntConcentration< DIM >::WntConcentration().
mTypeSet
template<unsigned DIM> bool WntConcentration< DIM >::mTypeSet private
Whether this WntConcentration object has had its type set.
Definition at line 99 of file WntConcentration.hpp.
Referenced by WntConcentration< DIM >::GetWntGradient(), WntConcentration< DIM >::GetWntLevel(), WntConcentration< DIM >::serialize(), WntConcentration< DIM >::SetConstantWntValueForTesting(), and WntConcentration< DIM >::SetType().
mUseConstantWntValueForTesting
template<unsigned DIM> bool WntConcentration< DIM >::mUseConstantWntValueForTesting private
Whether to return the testing value (when false WntConcentration works with CellPopulation).
Definition at line 110 of file WntConcentration.hpp.
Referenced by WntConcentration< DIM >::GetWntGradient(), WntConcentration< DIM >::GetWntLevel(), WntConcentration< DIM >::serialize(), and WntConcentration< DIM >::SetConstantWntValueForTesting().
mWntConcentrationParameter
template<unsigned DIM> double WntConcentration< DIM >::mWntConcentrationParameter private
For LINEAR or RADIAL Wnt type: The proportion of the crypt that has a Wnt gradient. The Wnt concentration goes from one at the base to zero at this height up the crypt.
For EXPONENTIAL Wnt type: The parameter lambda in the Wnt concentration Wnt = exp(-height/lambda)
Definition at line 121 of file WntConcentration.hpp.
Referenced by WntConcentration< DIM >::GetWntConcentrationParameter(), WntConcentration< DIM >::serialize(), and WntConcentration< DIM >::SetWntConcentrationParameter().
mWntType
template<unsigned DIM> WntConcentrationType WntConcentration< DIM >::mWntType private
The type of WntConcentration current options are NONE - returns zero everywhere LINEAR - decreases from 1 to zero at height specified by mWntConcentrationParameter RADIAL - decreases from 1 to zero at height specified by mWntConcentrationParameter
Definition at line 89 of file WntConcentration.hpp.
Referenced by WntConcentration< DIM >::GetType(), WntConcentration< DIM >::GetWntGradient(), WntConcentration< DIM >::GetWntLevel(), WntConcentration< DIM >::serialize(), WntConcentration< DIM >::SetConstantWntValueForTesting(), and WntConcentration< DIM >::SetType().
The documentation for this class was generated from the following files:
crypt/src/cell/cycle/WntConcentration.hpp
crypt/src/cell/cycle/WntConcentration.cpp