Chaste: VertexT3SwapLocationsWriter< ELEMENT_DIM, SPACE_DIM > Class Template Reference
VertexT3SwapLocationsWriter< ELEMENT_DIM, SPACE_DIM > Class Template Reference
#include <VertexT3SwapLocationsWriter.hpp>
Public Member Functions
VertexT3SwapLocationsWriter ()
virtual void Visit (MeshBasedCellPopulation< ELEMENT_DIM, SPACE_DIM > *pCellPopulation)
virtual void Visit (CaBasedCellPopulation< SPACE_DIM > *pCellPopulation)
virtual void Visit (NodeBasedCellPopulation< SPACE_DIM > *pCellPopulation)
virtual void Visit (PottsBasedCellPopulation< SPACE_DIM > *pCellPopulation)
virtual void Visit (VertexBasedCellPopulation< SPACE_DIM > *pCellPopulation)
Public Member Functions inherited from AbstractCellPopulationWriter< ELEMENT_DIM, SPACE_DIM >
AbstractCellPopulationWriter (const std::string &rFileName)
virtual void WriteHeader (AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM > *pCellPopulation)
Public Member Functions inherited from AbstractCellBasedWriter< ELEMENT_DIM, SPACE_DIM >
AbstractCellBasedWriter (const std::string &rFileName)
virtual ~AbstractCellBasedWriter ()
void CloseFile ()
virtual void OpenOutputFile (OutputFileHandler &rOutputFileHandler)
void OpenOutputFileForAppend (OutputFileHandler &rOutputFileHandler)
virtual void WriteTimeStamp ()
virtual void WriteNewline ()
void SetFileName (std::string fileName)
std::string GetFileName ()
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Friends
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from AbstractCellBasedWriter< ELEMENT_DIM, SPACE_DIM >
std::string mFileName
out_stream mpOutStream
Detailed Description
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM>
class VertexT3SwapLocationsWriter< ELEMENT_DIM, SPACE_DIM >
A class written using the visitor pattern for writing node location from a cell population to file.
The output file is called T3SwapLocations.dat by default.
Definition at line 49 of file VertexT3SwapLocationsWriter.hpp.
Constructor & Destructor Documentation
VertexT3SwapLocationsWriter()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> VertexT3SwapLocationsWriter< ELEMENT_DIM, SPACE_DIM >::VertexT3SwapLocationsWriter ()
Default constructor.
Definition at line 45 of file VertexT3SwapLocationsWriter.cpp.
Referenced by VertexT3SwapLocationsWriter< ELEMENT_DIM, SPACE_DIM >::serialize().
Member Function Documentation
serialize()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> template<class Archive > void VertexT3SwapLocationsWriter< ELEMENT_DIM, SPACE_DIM >::serialize (Archive & archive, const unsigned int version) inline private
Serialize the object and its member variables.
Parameters
archive the archive
version the current version of this class
Definition at line 61 of file VertexT3SwapLocationsWriter.hpp.
References EXPORT_TEMPLATE_CLASS_ALL_DIMS, VertexT3SwapLocationsWriter< ELEMENT_DIM, SPACE_DIM >::VertexT3SwapLocationsWriter(), and VertexT3SwapLocationsWriter< ELEMENT_DIM, SPACE_DIM >::Visit().
Visit() [1/5]
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void VertexT3SwapLocationsWriter< ELEMENT_DIM, SPACE_DIM >::Visit (MeshBasedCellPopulation< ELEMENT_DIM, SPACE_DIM > * pCellPopulation) virtual
Visit the population and write the data.
This is an empty dummy function, since this class is defined for use with a VertexBasedCellPopulation only.
Parameters
pCellPopulation a pointer to the MeshBasedCellPopulation to visit.
Implements AbstractCellPopulationWriter< ELEMENT_DIM, SPACE_DIM >.
Definition at line 51 of file VertexT3SwapLocationsWriter.cpp.
Referenced by VertexT3SwapLocationsWriter< ELEMENT_DIM, SPACE_DIM >::serialize().
Visit() [2/5]
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void VertexT3SwapLocationsWriter< ELEMENT_DIM, SPACE_DIM >::Visit (CaBasedCellPopulation< SPACE_DIM > * pCellPopulation) virtual
Visit the population and write the data.
This is an empty dummy function, since this class is defined for use with a VertexBasedCellPopulation only.
Parameters
pCellPopulation a pointer to the CaBasedCellPopulation to visit.
Implements AbstractCellPopulationWriter< ELEMENT_DIM, SPACE_DIM >.
Definition at line 56 of file VertexT3SwapLocationsWriter.cpp.
Visit() [3/5]
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void VertexT3SwapLocationsWriter< ELEMENT_DIM, SPACE_DIM >::Visit (NodeBasedCellPopulation< SPACE_DIM > * pCellPopulation) virtual
Visit the population and write the data.
This is an empty dummy function, since this class is defined for use with a VertexBasedCellPopulation only.
Parameters
pCellPopulation a pointer to the NodeBasedCellPopulation to visit.
Implements AbstractCellPopulationWriter< ELEMENT_DIM, SPACE_DIM >.
Definition at line 61 of file VertexT3SwapLocationsWriter.cpp.
Visit() [4/5]
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void VertexT3SwapLocationsWriter< ELEMENT_DIM, SPACE_DIM >::Visit (PottsBasedCellPopulation< SPACE_DIM > * pCellPopulation) virtual
Visit the population and write the data.
This is an empty dummy function, since this class is defined for use with a VertexBasedCellPopulation only.
Parameters
pCellPopulation a pointer to the PottsBasedCellPopulation to visit.
Implements AbstractCellPopulationWriter< ELEMENT_DIM, SPACE_DIM >.
Definition at line 66 of file VertexT3SwapLocationsWriter.cpp.
Visit() [5/5]
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void VertexT3SwapLocationsWriter< ELEMENT_DIM, SPACE_DIM >::Visit (VertexBasedCellPopulation< SPACE_DIM > * pCellPopulation) virtual
Visit the VertexBasedCellPopulation and write the location of any T3 swaps at the present simulation time.
Outputs a line of tab-separated values of the form: [num T3 swaps] [T3 swap 0 x-pos] [T3 swap 0 y-pos] [T3 swap 0 z-pos] [T3 swap 1 x-pos] [T3 swap 1 y-pos] [T3 swap 1 z-pos] ...
where [num T3 swaps] denotes the number of T3 swaps at the present time, and [T3 swap 0 x-pos] denotes the x-coordinate of the T3 swap with index 0 in the MutableVertexMesh member mLocationsOfT3Swaps, and so on, with [z-pos] included for 3-dimensional simulations.
This line is appended to the output written by AbstractCellBasedWriter, which is a single value [present simulation time], followed by a tab.
Parameters
pCellPopulation a pointer to the VertexBasedCellPopulation to visit.
Implements AbstractCellPopulationWriter< ELEMENT_DIM, SPACE_DIM >.
Definition at line 71 of file VertexT3SwapLocationsWriter.cpp.
References MutableVertexMesh< ELEMENT_DIM, SPACE_DIM >::GetLocationsOfT3Swaps(), AbstractCellBasedWriter< ELEMENT_DIM, SPACE_DIM >::mpOutStream, and VertexBasedCellPopulation< DIM >::rGetMesh().
Friends And Related Function Documentation
boost::serialization::access
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> friend class boost::serialization::access friend
Needed for serialization.
Definition at line 53 of file VertexT3SwapLocationsWriter.hpp.
The documentation for this class was generated from the following files:
cell_based/src/writers/population_writers/VertexT3SwapLocationsWriter.hpp
cell_based/src/writers/population_writers/VertexT3SwapLocationsWriter.cpp