Chaste: BathCellFactory< DIM, CELLTYPE > Class Template Reference
BathCellFactory< DIM, CELLTYPE > Class Template Reference
#include <SimpleBathProblemSetup.hpp>
Public Member Functions
BathCellFactory (double stimulusMagnitude, c_vector< double, DIM > stimulatedPoint)
AbstractCardiacCellInterface * CreateCardiacCellForTissueNode (Node< DIM > *pNode)
Public Member Functions inherited from AbstractCardiacCellFactory< DIM >
virtual AbstractCardiacCellInterface * CreateCardiacCellForNode (Node< ELEMENT_DIM > *pNode)
virtual AbstractCardiacCellInterface * CreateCardiacCellForTissueNode (Node< ELEMENT_DIM > *pNode)=0
virtual void FinaliseCellCreation (std::vector< AbstractCardiacCellInterface *> *pCellsDistributed, unsigned lo, unsigned hi)
virtual void FillInCellularTransmuralAreas ()
virtual unsigned GetNumberOfCells ()
AbstractCardiacCellFactory (boost::shared_ptr< AbstractIvpOdeSolver > pSolver=boost::shared_ptr< AbstractIvpOdeSolver >(new EulerIvpOdeSolver))
virtual ~AbstractCardiacCellFactory ()
virtual void SetMesh (AbstractTetrahedralMesh< ELEMENT_DIM, ELEMENT_DIM > *pMesh)
AbstractTetrahedralMesh< ELEMENT_DIM, ELEMENT_DIM > * GetMesh ()
void SetHeartGeometryInformation (HeartGeometryInformation< ELEMENT_DIM > *pHeartGeometryInformation)
HeartGeometryInformation< ELEMENT_DIM > * GetHeartGeometryInformation ()
Private Attributes
boost::shared_ptr< SimpleStimulus > mpStimulus
c_vector< double, DIM > mStimulatedPoint
Additional Inherited Members
Protected Attributes inherited from AbstractCardiacCellFactory< DIM >
boost::shared_ptr< ZeroStimulus > mpZeroStimulus
boost::shared_ptr< AbstractIvpOdeSolver > mpSolver
Detailed Description
template<unsigned DIM, class CELLTYPE = CellLuoRudy1991FromCellML>
class BathCellFactory< DIM, CELLTYPE >
A simple cell factory for bath problems, applying a SimpleStimulus for 0.5ms at a single point.
Definition at line 54 of file SimpleBathProblemSetup.hpp.
Constructor & Destructor Documentation
BathCellFactory()
template<unsigned DIM, class CELLTYPE = CellLuoRudy1991FromCellML> BathCellFactory< DIM, CELLTYPE >::BathCellFactory (double stimulusMagnitude, c_vector< double, DIM > stimulatedPoint) inline
Returns
a newly created cell factory.
Parameters
stimulusMagnitude
stimulatedPoint spatial co-ordinates of where to stimulate. Must correspond to a node location.
Definition at line 69 of file SimpleBathProblemSetup.hpp.
Member Function Documentation
CreateCardiacCellForTissueNode()
template<unsigned DIM, class CELLTYPE = CellLuoRudy1991FromCellML> AbstractCardiacCellInterface* BathCellFactory< DIM, CELLTYPE >::CreateCardiacCellForTissueNode (Node< DIM > * pNode) inline
Returns
a newly created new cell.
Parameters
pNode pointer to Node object for cell.
Definition at line 80 of file SimpleBathProblemSetup.hpp.
References Node< SPACE_DIM >::GetPoint(), Node< SPACE_DIM >::GetRegion(), HeartRegionCode::IsRegionTissue(), and BathCellFactory< DIM, CELLTYPE >::mStimulatedPoint.
Member Data Documentation
mpStimulus
template<unsigned DIM, class CELLTYPE = CellLuoRudy1991FromCellML> boost::shared_ptr<SimpleStimulus> BathCellFactory< DIM, CELLTYPE >::mpStimulus private
The stimulus to apply
Definition at line 58 of file SimpleBathProblemSetup.hpp.
mStimulatedPoint
template<unsigned DIM, class CELLTYPE = CellLuoRudy1991FromCellML> c_vector<double,DIM> BathCellFactory< DIM, CELLTYPE >::mStimulatedPoint private
and where to apply it
Definition at line 60 of file SimpleBathProblemSetup.hpp.
Referenced by BathCellFactory< DIM, CELLTYPE >::CreateCardiacCellForTissueNode().
The documentation for this class was generated from the following file:
heart/src/fortests/SimpleBathProblemSetup.hpp