Chaste: CryptSimulationBoundaryCondition< DIM > Class Template Reference
CryptSimulationBoundaryCondition< DIM > Class Template Reference
#include <CryptSimulationBoundaryCondition.hpp>
Public Member Functions
CryptSimulationBoundaryCondition (AbstractCellPopulation< DIM > *pCellPopulation)
void ImposeBoundaryCondition (const std::map< Node< DIM > *, c_vector< double, DIM > > &rOldLocations)
bool VerifyBoundaryCondition ()
void SetUseJiggledBottomCells (bool useJiggledBottomCells)
bool GetUseJiggledBottomCells ()
void OutputCellPopulationBoundaryConditionParameters (out_stream &rParamsFile)
Public Member Functions inherited from AbstractCellPopulationBoundaryCondition< DIM >
AbstractCellPopulationBoundaryCondition (AbstractCellPopulation< ELEMENT_DIM, ELEMENT_DIM > *pCellPopulation)
virtual ~AbstractCellPopulationBoundaryCondition ()
virtual void ImposeBoundaryCondition (const std::map< Node< ELEMENT_DIM > *, c_vector< double, ELEMENT_DIM > > &rOldLocations)=0
const AbstractCellPopulation< ELEMENT_DIM, ELEMENT_DIM > * GetCellPopulation () const
void OutputCellPopulationBoundaryConditionInfo (out_stream &rParamsFile)
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Private Attributes
bool mUseJiggledBottomCells
Friends
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from AbstractCellPopulationBoundaryCondition< DIM >
AbstractCellPopulation< ELEMENT_DIM, ELEMENT_DIM > * mpCellPopulation
Detailed Description
template<unsigned DIM>
class CryptSimulationBoundaryCondition< DIM >
A boundary condition class for use with CryptSimulation2d, which pins stem cells in the absence of a Wnt stimulus, and optionally prevents cells moving below the y=0 boundary via random jiggling.
Definition at line 51 of file CryptSimulationBoundaryCondition.hpp.
Constructor & Destructor Documentation
CryptSimulationBoundaryCondition()
template<unsigned DIM> CryptSimulationBoundaryCondition< DIM >::CryptSimulationBoundaryCondition (AbstractCellPopulation< DIM > * pCellPopulation)
Constructor.
Parameters
pCellPopulation pointer to the cell population
Definition at line 43 of file CryptSimulationBoundaryCondition.cpp.
Referenced by CryptSimulationBoundaryCondition< DIM >::serialize().
Member Function Documentation
GetUseJiggledBottomCells()
template<unsigned DIM> bool CryptSimulationBoundaryCondition< DIM >::GetUseJiggledBottomCells ()
Returns
mUseJiggledBottomCells.
Definition at line 194 of file CryptSimulationBoundaryCondition.cpp.
References CryptSimulationBoundaryCondition< DIM >::mUseJiggledBottomCells.
Referenced by CryptSimulationBoundaryCondition< DIM >::serialize().
ImposeBoundaryCondition()
template<unsigned DIM> void CryptSimulationBoundaryCondition< DIM >::ImposeBoundaryCondition (const std::map< Node< DIM > *, c_vector< double, DIM > > & rOldLocations)
Overridden ImposeBoundaryCondition() method.
Apply the cell population boundary conditions.
Parameters
rOldLocations the node locations before any boundary conditions are applied
Definition at line 50 of file CryptSimulationBoundaryCondition.cpp.
References AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::Begin(), WntConcentration< DIM >::Destroy(), AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::End(), AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::GetLocationIndexUsingCell(), AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::GetNode(), AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::GetNumNodes(), WntConcentration< DIM >::Instance(), RandomNumberGenerator::Instance(), WntConcentration< DIM >::IsWntSetUp(), AbstractCellPopulationBoundaryCondition< DIM >::mpCellPopulation, CryptSimulationBoundaryCondition< DIM >::mUseJiggledBottomCells, RandomNumberGenerator::ranf(), Node< SPACE_DIM >::rGetLocation(), and Node< SPACE_DIM >::rGetModifiableLocation().
Referenced by CryptSimulationBoundaryCondition< DIM >::serialize().
OutputCellPopulationBoundaryConditionParameters()
template<unsigned DIM> void CryptSimulationBoundaryCondition< DIM >::OutputCellPopulationBoundaryConditionParameters (out_stream & rParamsFile) virtual
Overridden OutputCellPopulationBoundaryConditionParameters() method. Output cell population boundary condition parameters to file.
Parameters
rParamsFile the file stream to which the parameters are output
Todo:
Can we abstract these XML out methods and do automatic indentation?
Implements AbstractCellPopulationBoundaryCondition< DIM >.
Definition at line 200 of file CryptSimulationBoundaryCondition.cpp.
References EXPORT_TEMPLATE_CLASS_SAME_DIMS, CryptSimulationBoundaryCondition< DIM >::mUseJiggledBottomCells, and AbstractCellPopulationBoundaryCondition< ELEMENT_DIM, SPACE_DIM >::OutputCellPopulationBoundaryConditionParameters().
Referenced by CryptSimulationBoundaryCondition< DIM >::serialize().
serialize()
template<unsigned DIM> template<class Archive > void CryptSimulationBoundaryCondition< DIM >::serialize (Archive & archive, const unsigned int version) inline private
Serialize the object and its member variables.
Parameters
archive the archive
version the current version of this class
Definition at line 70 of file CryptSimulationBoundaryCondition.hpp.
References CryptSimulationBoundaryCondition< DIM >::CryptSimulationBoundaryCondition(), EXPORT_TEMPLATE_CLASS_SAME_DIMS, CryptSimulationBoundaryCondition< DIM >::GetUseJiggledBottomCells(), CryptSimulationBoundaryCondition< DIM >::ImposeBoundaryCondition(), CryptSimulationBoundaryCondition< DIM >::mUseJiggledBottomCells, CryptSimulationBoundaryCondition< DIM >::OutputCellPopulationBoundaryConditionParameters(), CryptSimulationBoundaryCondition< DIM >::SetUseJiggledBottomCells(), and CryptSimulationBoundaryCondition< DIM >::VerifyBoundaryCondition().
SetUseJiggledBottomCells()
template<unsigned DIM> void CryptSimulationBoundaryCondition< DIM >::SetUseJiggledBottomCells (bool useJiggledBottomCells)
Set method for mUseJiggledBottomCells
Parameters
useJiggledBottomCells whether to jiggle the cells on the bottom surface
Definition at line 188 of file CryptSimulationBoundaryCondition.cpp.
References CryptSimulationBoundaryCondition< DIM >::mUseJiggledBottomCells.
Referenced by CryptSimulationBoundaryCondition< DIM >::serialize().
VerifyBoundaryCondition()
template<unsigned DIM> bool CryptSimulationBoundaryCondition< DIM >::VerifyBoundaryCondition () virtual
Overridden VerifyBoundaryCondition() method. Verify the boundary conditions have been applied. This is called after ImposeBoundaryCondition() to ensure the condition is still satisfied.
Returns
whether the boundary conditions are satisfied.
Implements AbstractCellPopulationBoundaryCondition< DIM >.
Definition at line 158 of file CryptSimulationBoundaryCondition.cpp.
References AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::Begin(), AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::End(), AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::GetLocationIndexUsingCell(), AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::GetNode(), AbstractCellPopulationBoundaryCondition< DIM >::mpCellPopulation, and Node< SPACE_DIM >::rGetLocation().
Referenced by CryptSimulationBoundaryCondition< DIM >::serialize().
Friends And Related Function Documentation
boost::serialization::access
template<unsigned DIM> friend class boost::serialization::access friend
Needed for serialization.
Definition at line 62 of file CryptSimulationBoundaryCondition.hpp.
Member Data Documentation
mUseJiggledBottomCells
template<unsigned DIM> bool CryptSimulationBoundaryCondition< DIM >::mUseJiggledBottomCells private
Whether to jiggle the cells on the bottom surface, initialised to false in the constructor.
Definition at line 59 of file CryptSimulationBoundaryCondition.hpp.
Referenced by CryptSimulationBoundaryCondition< DIM >::GetUseJiggledBottomCells(), CryptSimulationBoundaryCondition< DIM >::ImposeBoundaryCondition(), CryptSimulationBoundaryCondition< DIM >::OutputCellPopulationBoundaryConditionParameters(), CryptSimulationBoundaryCondition< DIM >::serialize(), and CryptSimulationBoundaryCondition< DIM >::SetUseJiggledBottomCells().
The documentation for this class was generated from the following files:
crypt/src/boundary_conditions/CryptSimulationBoundaryCondition.hpp
crypt/src/boundary_conditions/CryptSimulationBoundaryCondition.cpp