Chaste: VertexMesh< ELEMENT_DIM, SPACE_DIM >::VertexElementIterator Class Reference
VertexMesh< ELEMENT_DIM, SPACE_DIM >::VertexElementIterator Class Reference
#include <VertexMesh.hpp>
Public Member Functions
VertexElement< ELEMENT_DIM, SPACE_DIM > & operator* ()
VertexElement< ELEMENT_DIM, SPACE_DIM > * operator-> ()
bool operator!= (const typename VertexMesh< ELEMENT_DIM, SPACE_DIM >::VertexElementIterator &rOther)
VertexElementIterator & operator++ ()
VertexElementIterator (VertexMesh< ELEMENT_DIM, SPACE_DIM > &rMesh, typename std::vector< VertexElement< ELEMENT_DIM, SPACE_DIM > *>::iterator elementIter, bool skipDeletedElements=true)
Private Member Functions
bool IsAtEnd ()
bool IsAllowedElement ()
Private Attributes
VertexMesh & mrMesh
std::vector< VertexElement< ELEMENT_DIM, SPACE_DIM > * >::iterator mElementIter
bool mSkipDeletedElements
Detailed Description
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM>
class VertexMesh< ELEMENT_DIM, SPACE_DIM >::VertexElementIterator
A smart iterator over the elements in the mesh.
Todo:
This is the same as in AbstractTetrahedralMesh and PottsMesh - merge? (#1379)
Definition at line 604 of file VertexMesh.hpp.
Constructor & Destructor Documentation
VertexElementIterator()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> VertexMesh< ELEMENT_DIM, SPACE_DIM >::VertexElementIterator::VertexElementIterator (VertexMesh< ELEMENT_DIM, SPACE_DIM > & rMesh, typename std::vector< VertexElement< ELEMENT_DIM, SPACE_DIM > *>::iterator elementIter, bool skipDeletedElements = true)
Constructor for a new iterator.
This should not be called directly by user code; use the mesh methods VertexMesh::GetElementIteratorBegin and VertexMesh::GetElementIteratorEnd instead.
Parameters
rMesh the mesh to iterator over
elementIter where to start iterating
skipDeletedElements whether to include deleted elements
Definition at line 723 of file VertexMesh.hpp.
References VertexMesh< ELEMENT_DIM, SPACE_DIM >::VertexElementIterator::IsAllowedElement(), VertexMesh< ELEMENT_DIM, SPACE_DIM >::VertexElementIterator::mElementIter, VertexMesh< ELEMENT_DIM, SPACE_DIM >::mElements, and VertexMesh< ELEMENT_DIM, SPACE_DIM >::VertexElementIterator::mrMesh.
Referenced by VertexMesh< DIM, DIM >::GetElementIteratorBegin(), and VertexMesh< DIM, DIM >::GetElementIteratorEnd().
Member Function Documentation
IsAllowedElement()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> bool VertexMesh< ELEMENT_DIM, SPACE_DIM >::VertexElementIterator::IsAllowedElement () inline private
Helper method to say if we're allowed to point at this element.
Returns
true if allowed
Definition at line 753 of file VertexMesh.hpp.
References VertexMesh< ELEMENT_DIM, SPACE_DIM >::VertexElementIterator::mSkipDeletedElements.
Referenced by VertexMesh< ELEMENT_DIM, SPACE_DIM >::VertexElementIterator::operator++(), and VertexMesh< ELEMENT_DIM, SPACE_DIM >::VertexElementIterator::VertexElementIterator().
IsAtEnd()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> bool VertexMesh< ELEMENT_DIM, SPACE_DIM >::VertexElementIterator::IsAtEnd () inline private
Helper method to say when we're at the end.
Returns
true if at end
Definition at line 747 of file VertexMesh.hpp.
References VertexMesh< ELEMENT_DIM, SPACE_DIM >::VertexElementIterator::mElementIter, VertexMesh< ELEMENT_DIM, SPACE_DIM >::mElements, and VertexMesh< ELEMENT_DIM, SPACE_DIM >::VertexElementIterator::mrMesh.
Referenced by VertexMesh< ELEMENT_DIM, SPACE_DIM >::VertexElementIterator::operator*(), VertexMesh< ELEMENT_DIM, SPACE_DIM >::VertexElementIterator::operator++(), and VertexMesh< ELEMENT_DIM, SPACE_DIM >::VertexElementIterator::operator->().
operator!=()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> bool VertexMesh< ELEMENT_DIM, SPACE_DIM >::VertexElementIterator::operator!= (const typename VertexMesh< ELEMENT_DIM, SPACE_DIM >::VertexElementIterator & rOther) inline
Comparison not-equal-to.
Returns
true if not equal
Parameters
rOther iterator with which comparison is made
Definition at line 706 of file VertexMesh.hpp.
References VertexMesh< ELEMENT_DIM, SPACE_DIM >::VertexElementIterator::mElementIter.
operator*()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> VertexElement< ELEMENT_DIM, SPACE_DIM > & VertexMesh< ELEMENT_DIM, SPACE_DIM >::VertexElementIterator::operator* () inline
Dereference the iterator giving you a *reference* to the current element.
Returns
reference Make sure to use a reference for the result to avoid copying elements unnecessarily.
Definition at line 692 of file VertexMesh.hpp.
References VertexMesh< ELEMENT_DIM, SPACE_DIM >::VertexElementIterator::IsAtEnd(), and VertexMesh< ELEMENT_DIM, SPACE_DIM >::VertexElementIterator::mElementIter.
operator++()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> VertexMesh< ELEMENT_DIM, SPACE_DIM >::VertexElementIterator & VertexMesh< ELEMENT_DIM, SPACE_DIM >::VertexElementIterator::operator++ () inline
Prefix increment operator.
Returns
reference to incremented object
Definition at line 712 of file VertexMesh.hpp.
References VertexMesh< ELEMENT_DIM, SPACE_DIM >::VertexElementIterator::IsAllowedElement(), VertexMesh< ELEMENT_DIM, SPACE_DIM >::VertexElementIterator::IsAtEnd(), and VertexMesh< ELEMENT_DIM, SPACE_DIM >::VertexElementIterator::mElementIter.
operator->()
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> VertexElement< ELEMENT_DIM, SPACE_DIM > * VertexMesh< ELEMENT_DIM, SPACE_DIM >::VertexElementIterator::operator-> () inline
Member access from a pointer.
Returns
pointer
Definition at line 699 of file VertexMesh.hpp.
References VertexMesh< ELEMENT_DIM, SPACE_DIM >::VertexElementIterator::IsAtEnd(), and VertexMesh< ELEMENT_DIM, SPACE_DIM >::VertexElementIterator::mElementIter.
Member Data Documentation
mElementIter
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> std::vector<VertexElement<ELEMENT_DIM, SPACE_DIM>*>::iterator VertexMesh< ELEMENT_DIM, SPACE_DIM >::VertexElementIterator::mElementIter private
The actual element iterator.
Definition at line 652 of file VertexMesh.hpp.
Referenced by VertexMesh< ELEMENT_DIM, SPACE_DIM >::VertexElementIterator::IsAtEnd(), VertexMesh< ELEMENT_DIM, SPACE_DIM >::VertexElementIterator::operator!=(), VertexMesh< ELEMENT_DIM, SPACE_DIM >::VertexElementIterator::operator*(), VertexMesh< ELEMENT_DIM, SPACE_DIM >::VertexElementIterator::operator++(), VertexMesh< ELEMENT_DIM, SPACE_DIM >::VertexElementIterator::operator->(), and VertexMesh< ELEMENT_DIM, SPACE_DIM >::VertexElementIterator::VertexElementIterator().
mrMesh
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> VertexMesh& VertexMesh< ELEMENT_DIM, SPACE_DIM >::VertexElementIterator::mrMesh private
The mesh we're iterating over.
Definition at line 649 of file VertexMesh.hpp.
Referenced by VertexMesh< ELEMENT_DIM, SPACE_DIM >::VertexElementIterator::IsAtEnd(), and VertexMesh< ELEMENT_DIM, SPACE_DIM >::VertexElementIterator::VertexElementIterator().
mSkipDeletedElements
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> bool VertexMesh< ELEMENT_DIM, SPACE_DIM >::VertexElementIterator::mSkipDeletedElements private
Whether to skip deleted elements.
Definition at line 655 of file VertexMesh.hpp.
Referenced by VertexMesh< ELEMENT_DIM, SPACE_DIM >::VertexElementIterator::IsAllowedElement().
The documentation for this class was generated from the following file:
mesh/src/vertex/VertexMesh.hpp