Chaste: SimpleOxygenBasedCellCycleModel Class Reference
SimpleOxygenBasedCellCycleModel Class Reference
#include <SimpleOxygenBasedCellCycleModel.hpp>
Public Member Functions
SimpleOxygenBasedCellCycleModel ()
void UpdateCellCyclePhase ()
void UpdateHypoxicDuration ()
double GetCurrentHypoxicDuration () const
double GetCurrentHypoxiaOnsetTime () const
AbstractCellCycleModel * CreateCellCycleModel ()
double GetHypoxicConcentration () const
void SetHypoxicConcentration (double hypoxicConcentration)
double GetQuiescentConcentration () const
void SetQuiescentConcentration (double quiescentConcentration)
double GetCriticalHypoxicDuration () const
void SetCriticalHypoxicDuration (double criticalHypoxicDuration)
void SetCurrentHypoxiaOnsetTime (double currentHypoxiaOnsetTime)
virtual void OutputCellCycleModelParameters (out_stream &rParamsFile)
Public Member Functions inherited from AbstractSimplePhaseBasedCellCycleModel
AbstractSimplePhaseBasedCellCycleModel ()
virtual ~AbstractSimplePhaseBasedCellCycleModel ()
virtual void ResetForDivision ()
void InitialiseDaughterCell ()
virtual void Initialise ()
Public Member Functions inherited from AbstractPhaseBasedCellCycleModel
AbstractPhaseBasedCellCycleModel ()
virtual ~AbstractPhaseBasedCellCycleModel ()
virtual bool ReadyToDivide ()
CellCyclePhase GetCurrentCellCyclePhase () const
virtual double GetG1Duration () const
double GetStemCellG1Duration () const
double GetTransitCellG1Duration () const
double GetSG2MDuration () const
virtual double GetSDuration () const
virtual double GetG2Duration () const
virtual double GetMDuration () const
virtual void SetStemCellG1Duration (double stemCellG1Duration)
virtual void SetTransitCellG1Duration (double transitCellG1Duration)
void SetSDuration (double sDuration)
void SetG2Duration (double g2Duration)
void SetMDuration (double mDuration)
virtual double GetAverageTransitCellCycleTime ()
virtual double GetAverageStemCellCycleTime ()
double GetMinimumGapDuration () const
void SetMinimumGapDuration (double minimumGapDuration)
Public Member Functions inherited from AbstractCellCycleModel
AbstractCellCycleModel ()
virtual ~AbstractCellCycleModel ()
void SetCell (CellPtr pCell)
CellPtr GetCell ()
virtual void SetBirthTime (double birthTime)
void SetDimension (unsigned dimension)
unsigned GetDimension () const
double GetBirthTime () const
double GetAge ()
virtual bool CanCellTerminallyDifferentiate ()
void OutputCellCycleModelInfo (out_stream &rParamsFile)
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Protected Member Functions
SimpleOxygenBasedCellCycleModel (const SimpleOxygenBasedCellCycleModel &rModel)
Protected Member Functions inherited from AbstractSimplePhaseBasedCellCycleModel
virtual void SetG1Duration ()
AbstractSimplePhaseBasedCellCycleModel (const AbstractSimplePhaseBasedCellCycleModel &rModel)
Protected Member Functions inherited from AbstractPhaseBasedCellCycleModel
AbstractPhaseBasedCellCycleModel (const AbstractPhaseBasedCellCycleModel &rModel)
Protected Member Functions inherited from AbstractCellCycleModel
AbstractCellCycleModel (const AbstractCellCycleModel &rModel)
Protected Attributes
double mCurrentHypoxicDuration
double mCurrentHypoxiaOnsetTime
double mHypoxicConcentration
double mQuiescentConcentration
double mCriticalHypoxicDuration
Protected Attributes inherited from AbstractPhaseBasedCellCycleModel
CellCyclePhase mCurrentCellCyclePhase
double mG1Duration
double mMinimumGapDuration
double mStemCellG1Duration
double mTransitCellG1Duration
double mSDuration
double mG2Duration
double mMDuration
Protected Attributes inherited from AbstractCellCycleModel
CellPtr mpCell
double mBirthTime
bool mReadyToDivide
unsigned mDimension
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Friends
class boost::serialization::access
Detailed Description
Simple oxygen-based cell-cycle model.
A simple oxygen-dependent cell-cycle model that inherits from AbstractSimplePhaseBasedCellCycleModel. The duration of G1 phase depends on the local oxygen concentration. A prolonged period of acute hypoxia leads to the cell being labelled as apoptotic. This model allows for quiescence imposed by transient periods of hypoxia, followed by reoxygenation.
Definition at line 51 of file SimpleOxygenBasedCellCycleModel.hpp.
Constructor & Destructor Documentation
SimpleOxygenBasedCellCycleModel() [1/2]
SimpleOxygenBasedCellCycleModel::SimpleOxygenBasedCellCycleModel (const SimpleOxygenBasedCellCycleModel & rModel) protected
Protected copy-constructor for use by CreateCellCycleModel. The only way for external code to create a copy of a cell cycle model is by calling that method, to ensure that a model of the correct subclass is created. This copy-constructor helps subclasses to ensure that all member variables are correctly copied when this happens.
This method is called by child classes to set member variables for a daughter cell upon cell division. Note that the parent cell cycle model will have had ResetForDivision() called just before CreateCellCycleModel() is called, so performing an exact copy of the parent is suitable behaviour. Any daughter-cell-specific initialisation can be done in InitialiseDaughterCell().
Parameters
rModel the cell cycle model to copy.
Definition at line 87 of file SimpleOxygenBasedCellCycleModel.cpp.
SimpleOxygenBasedCellCycleModel() [2/2]
SimpleOxygenBasedCellCycleModel::SimpleOxygenBasedCellCycleModel ()
Constructor.
Definition at line 40 of file SimpleOxygenBasedCellCycleModel.cpp.
References SimulationTime::GetTime(), SimulationTime::Instance(), and mCurrentHypoxiaOnsetTime.
Referenced by CreateCellCycleModel().
Member Function Documentation
CreateCellCycleModel()
AbstractCellCycleModel * SimpleOxygenBasedCellCycleModel::CreateCellCycleModel () virtual
Overridden builder method to create new copies of this cell-cycle model.
Returns
new cell-cycle model
Implements AbstractCellCycleModel.
Reimplemented in StochasticOxygenBasedCellCycleModel.
Definition at line 111 of file SimpleOxygenBasedCellCycleModel.cpp.
References SimpleOxygenBasedCellCycleModel().
GetCriticalHypoxicDuration()
double SimpleOxygenBasedCellCycleModel::GetCriticalHypoxicDuration () const
Returns
mCriticalHypoxicDuration
Definition at line 178 of file SimpleOxygenBasedCellCycleModel.cpp.
References mCriticalHypoxicDuration.
GetCurrentHypoxiaOnsetTime()
double SimpleOxygenBasedCellCycleModel::GetCurrentHypoxiaOnsetTime () const
Returns
mCurrentHypoxiaOnsetTime
Definition at line 54 of file SimpleOxygenBasedCellCycleModel.cpp.
References mCurrentHypoxiaOnsetTime.
GetCurrentHypoxicDuration()
double SimpleOxygenBasedCellCycleModel::GetCurrentHypoxicDuration () const
Returns
mCurrentHypoxicDuration
Definition at line 49 of file SimpleOxygenBasedCellCycleModel.cpp.
References mCurrentHypoxicDuration.
GetHypoxicConcentration()
double SimpleOxygenBasedCellCycleModel::GetHypoxicConcentration () const
Returns
mHypoxicConcentration
Definition at line 154 of file SimpleOxygenBasedCellCycleModel.cpp.
References mHypoxicConcentration.
GetQuiescentConcentration()
double SimpleOxygenBasedCellCycleModel::GetQuiescentConcentration () const
Returns
mQuiescentConcentration
Definition at line 166 of file SimpleOxygenBasedCellCycleModel.cpp.
References mQuiescentConcentration.
OutputCellCycleModelParameters()
void SimpleOxygenBasedCellCycleModel::OutputCellCycleModelParameters (out_stream & rParamsFile) virtual
Overridden OutputCellCycleModelParameters() method.
Parameters
rParamsFile the file stream to which the parameters are output
Reimplemented from AbstractSimplePhaseBasedCellCycleModel.
Reimplemented in StochasticOxygenBasedCellCycleModel.
Definition at line 195 of file SimpleOxygenBasedCellCycleModel.cpp.
References CHASTE_CLASS_EXPORT, mCriticalHypoxicDuration, mHypoxicConcentration, mQuiescentConcentration, and AbstractSimplePhaseBasedCellCycleModel::OutputCellCycleModelParameters().
Referenced by StochasticOxygenBasedCellCycleModel::OutputCellCycleModelParameters().
serialize()
template<class Archive > void SimpleOxygenBasedCellCycleModel::serialize (Archive & archive, const unsigned int version) inline private
Boost Serialization method for archiving/checkpointing
Parameters
archive The boost archive.
version The current version of this class.
Definition at line 62 of file SimpleOxygenBasedCellCycleModel.hpp.
References mCriticalHypoxicDuration, mCurrentHypoxiaOnsetTime, mCurrentHypoxicDuration, mHypoxicConcentration, and mQuiescentConcentration.
SetCriticalHypoxicDuration()
void SimpleOxygenBasedCellCycleModel::SetCriticalHypoxicDuration (double criticalHypoxicDuration)
Set method for mCriticalHypoxicDuration.
Parameters
criticalHypoxicDuration the new value of mCriticalHypoxicDuration
Definition at line 183 of file SimpleOxygenBasedCellCycleModel.cpp.
References mCriticalHypoxicDuration.
SetCurrentHypoxiaOnsetTime()
void SimpleOxygenBasedCellCycleModel::SetCurrentHypoxiaOnsetTime (double currentHypoxiaOnsetTime)
Set method for mCurrentHypoxiaOnsetTime.
Parameters
currentHypoxiaOnsetTime the new value of mCurrentHypoxiaOnsetTime
Definition at line 189 of file SimpleOxygenBasedCellCycleModel.cpp.
References mCurrentHypoxiaOnsetTime.
SetHypoxicConcentration()
void SimpleOxygenBasedCellCycleModel::SetHypoxicConcentration (double hypoxicConcentration)
Set method for mHypoxicConcentration.
Parameters
hypoxicConcentration the new value of mHypoxicConcentration
Definition at line 159 of file SimpleOxygenBasedCellCycleModel.cpp.
References mHypoxicConcentration.
SetQuiescentConcentration()
void SimpleOxygenBasedCellCycleModel::SetQuiescentConcentration (double quiescentConcentration)
Set method for mQuiescentConcentration.
Parameters
quiescentConcentration the new value of mQuiescentConcentration
Definition at line 171 of file SimpleOxygenBasedCellCycleModel.cpp.
References mQuiescentConcentration.
UpdateCellCyclePhase()
void SimpleOxygenBasedCellCycleModel::UpdateCellCyclePhase () virtual
Overridden UpdateCellCyclePhase() method.
Reimplemented from AbstractSimplePhaseBasedCellCycleModel.
Definition at line 59 of file SimpleOxygenBasedCellCycleModel.cpp.
References SimulationTime::GetTimeStep(), SimulationTime::Instance(), AbstractPhaseBasedCellCycleModel::mCurrentCellCyclePhase, AbstractPhaseBasedCellCycleModel::mG1Duration, AbstractCellCycleModel::mpCell, mQuiescentConcentration, AbstractSimplePhaseBasedCellCycleModel::UpdateCellCyclePhase(), and UpdateHypoxicDuration().
UpdateHypoxicDuration()
void SimpleOxygenBasedCellCycleModel::UpdateHypoxicDuration ()
Method for updating mCurrentHypoxicDuration, called at the start of ReadyToDivide().
Definition at line 116 of file SimpleOxygenBasedCellCycleModel.cpp.
References SimulationTime::GetTime(), SimulationTime::Instance(), RandomNumberGenerator::Instance(), mCriticalHypoxicDuration, mCurrentHypoxiaOnsetTime, mCurrentHypoxicDuration, mHypoxicConcentration, AbstractCellCycleModel::mpCell, and RandomNumberGenerator::ranf().
Referenced by UpdateCellCyclePhase().
Member Data Documentation
mCriticalHypoxicDuration
double SimpleOxygenBasedCellCycleModel::mCriticalHypoxicDuration protected
Non-dimensionalized critical hypoxic duration. Has units of hours.
Definition at line 103 of file SimpleOxygenBasedCellCycleModel.hpp.
Referenced by GetCriticalHypoxicDuration(), OutputCellCycleModelParameters(), serialize(), SetCriticalHypoxicDuration(), and UpdateHypoxicDuration().
mCurrentHypoxiaOnsetTime
double SimpleOxygenBasedCellCycleModel::mCurrentHypoxiaOnsetTime protected
The time when the current period of hypoxia began.
Definition at line 83 of file SimpleOxygenBasedCellCycleModel.hpp.
Referenced by GetCurrentHypoxiaOnsetTime(), serialize(), SetCurrentHypoxiaOnsetTime(), SimpleOxygenBasedCellCycleModel(), and UpdateHypoxicDuration().
mCurrentHypoxicDuration
double SimpleOxygenBasedCellCycleModel::mCurrentHypoxicDuration protected
How long the current period of hypoxia has lasted. Has units of hours.
Definition at line 78 of file SimpleOxygenBasedCellCycleModel.hpp.
Referenced by GetCurrentHypoxicDuration(), serialize(), and UpdateHypoxicDuration().
mHypoxicConcentration
double SimpleOxygenBasedCellCycleModel::mHypoxicConcentration protected
Non-dimensionalized oxygen concentration below which cells are considered to be hypoxic. A prolonged period of hypoxia causes the cell to become apoptotic.
Definition at line 90 of file SimpleOxygenBasedCellCycleModel.hpp.
Referenced by GetHypoxicConcentration(), OutputCellCycleModelParameters(), serialize(), SetHypoxicConcentration(), and UpdateHypoxicDuration().
mQuiescentConcentration
double SimpleOxygenBasedCellCycleModel::mQuiescentConcentration protected
Non-dimensionalized oxygen concentration below which cells are considered to be quiescent and slow their progress through the G1 phase of the cell cycle.
Definition at line 97 of file SimpleOxygenBasedCellCycleModel.hpp.
Referenced by GetQuiescentConcentration(), OutputCellCycleModelParameters(), serialize(), SetQuiescentConcentration(), and UpdateCellCyclePhase().
The documentation for this class was generated from the following files:
cell_based/src/cell/cycle/SimpleOxygenBasedCellCycleModel.hpp
cell_based/src/cell/cycle/SimpleOxygenBasedCellCycleModel.cpp