Chaste: Mirams2010WntOdeSystem Class Reference
Mirams2010WntOdeSystem Class Reference
#include <Mirams2010WntOdeSystem.hpp>
Public Member Functions
Mirams2010WntOdeSystem (double wntLevel=0.0, boost::shared_ptr< AbstractCellMutationState > pMutationState=boost::shared_ptr< AbstractCellMutationState >(), std::vector< double > stateVariables=std::vector< double >())
~Mirams2010WntOdeSystem ()
void Init ()
void SetMutationState (boost::shared_ptr< AbstractCellMutationState > pMutationState)
const boost::shared_ptr< AbstractCellMutationState > GetMutationState () const
void EvaluateYDerivatives (double time, const std::vector< double > &rY, std::vector< double > &rDY)
double GetWntLevel () const
Public Member Functions inherited from AbstractOdeSystem
AbstractOdeSystem (unsigned numberOfStateVariables)
virtual ~AbstractOdeSystem ()
virtual bool CalculateStoppingEvent (double time, const std::vector< double > &rY)
virtual double CalculateRootFunction (double time, const std::vector< double > &rY)
bool GetUseAnalyticJacobian ()
const std::vector< double > & rGetConstStateVariables () const
Public Member Functions inherited from AbstractParameterisedSystem< std::vector< double > >
AbstractParameterisedSystem (unsigned numberOfStateVariables)
std::vector< double > & rGetStateVariables ()
std::vector< double > GetStateVariables ()
void SetStateVariables (const std::vector< double > &rStateVariables)
double GetStateVariable (unsigned index) const
double GetStateVariable (const std::string &rName) const
void SetStateVariable (unsigned index, double newValue)
void SetStateVariable (const std::string &rName, double newValue)
virtual void VerifyStateVariables ()
void SetDefaultInitialConditions (const std::vector< double > &rInitialConditions)
void SetDefaultInitialCondition (unsigned index, double initialCondition)
std::vector< double > GetInitialConditions () const
void ResetToInitialConditions ()
double GetParameter (unsigned index) const
double GetParameter (const std::string &rName) const
void SetParameter (const std::string &rName, double value)
void SetParameter (unsigned index, double value)
double GetAnyVariable (unsigned index, double time=0.0, std::vector< double > *pDerivedQuantities=NULL)
double GetAnyVariable (const std::string &rName, double time=0.0, std::vector< double > *pDerivedQuantities=NULL)
void SetAnyVariable (unsigned index, double value)
void SetAnyVariable (const std::string &rName, double value)
virtual std::vector< double > ComputeDerivedQuantities (double time, const std::vector< double > &rState)
std::vector< double > ComputeDerivedQuantitiesFromCurrentState (double time)
Public Member Functions inherited from AbstractUntemplatedParameterisedSystem
AbstractUntemplatedParameterisedSystem (unsigned numberOfStateVariables)
virtual ~AbstractUntemplatedParameterisedSystem ()
boost::shared_ptr< const AbstractOdeSystemInformation > GetSystemInformation () const
std::string GetSystemName () const
unsigned GetNumberOfAttributes () const
bool HasAttribute (const std::string &rName) const
double GetAttribute (const std::string &rName) const
unsigned GetNumberOfStateVariables () const
const std::vector< std::string > & rGetStateVariableNames () const
const std::vector< std::string > & rGetStateVariableUnits () const
unsigned GetStateVariableIndex (const std::string &rName) const
bool HasStateVariable (const std::string &rName) const
std::string GetStateVariableUnits (unsigned index) const
unsigned GetNumberOfParameters () const
const std::vector< std::string > & rGetParameterNames () const
const std::vector< std::string > & rGetParameterUnits () const
unsigned GetParameterIndex (const std::string &rName) const
bool HasParameter (const std::string &rName) const
std::string GetParameterUnits (unsigned index) const
unsigned GetNumberOfDerivedQuantities () const
const std::vector< std::string > & rGetDerivedQuantityNames () const
const std::vector< std::string > & rGetDerivedQuantityUnits () const
unsigned GetDerivedQuantityIndex (const std::string &rName) const
bool HasDerivedQuantity (const std::string &rName) const
std::string GetDerivedQuantityUnits (unsigned index) const
unsigned GetAnyVariableIndex (const std::string &rName) const
bool HasAnyVariable (const std::string &rName) const
std::string GetAnyVariableUnits (unsigned index) const
std::string GetAnyVariableUnits (const std::string &rName) const
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Private Attributes
double mA
double mB
double mC
double mD
double mE
double mF
boost::shared_ptr< AbstractCellMutationState > mpMutationState
double mWntLevel
Friends
class boost::serialization::access
Additional Inherited Members
Protected Member Functions inherited from AbstractParameterisedSystem< std::vector< double > >
std::string DumpState (const std::string &rMessage)
std::string DumpState (const std::string &rMessage, std::vector< double > Y)
std::string DumpState (const std::string &rMessage, std::vector< double > Y, double time)
void CheckParametersOnLoad (const std::vector< double > &rParameters, const std::vector< std::string > &rParameterNames)
Protected Attributes inherited from AbstractOdeSystem
bool mUseAnalyticJacobian
Protected Attributes inherited from AbstractParameterisedSystem< std::vector< double > >
std::vector< double > mStateVariables
std::vector< double > mParameters
Protected Attributes inherited from AbstractUntemplatedParameterisedSystem
unsigned mNumberOfStateVariables
boost::shared_ptr< AbstractOdeSystemInformation > mpSystemInfo
Detailed Description
Represents the Mirams et al. system of ODEs, based on Swat et al. (2004) [doi:10.1093/bioinformatics/bth110] and a simple Wnt model (unpublished)
The variables are
6. b1 = Beta-Catenin (from 1st allele) 7. b2 = Beta-Catenin (from 1st allele) 8. WntLevel
Definition at line 60 of file Mirams2010WntOdeSystem.hpp.
Constructor & Destructor Documentation
Mirams2010WntOdeSystem()
Mirams2010WntOdeSystem::Mirams2010WntOdeSystem (double wntLevel = 0.0, boost::shared_ptr< AbstractCellMutationState > pMutationState = boost::shared_ptr<AbstractCellMutationState>(), std::vector< double > stateVariables = std::vector<double>())
Constructor.
Parameters
wntLevel is a non-dimensional Wnt value between 0 and 1. This sets up the Wnt pathway in its steady state.
pMutationState optional mutation state (affects the ODE system)
stateVariables optional initial conditions for state variables (only used in archiving)
State variables.
0. b1 = Beta-Catenin (1st allele's copy) 1. b2 = Beta-Catenin (2nd allele's copy) 2. wntLevel
Definition at line 45 of file Mirams2010WntOdeSystem.cpp.
References Init(), mA, mB, mC, mD, mF, mpMutationState, AbstractUntemplatedParameterisedSystem::mpSystemInfo, AbstractParameterisedSystem< std::vector< double > >::SetDefaultInitialCondition(), and AbstractParameterisedSystem< std::vector< double > >::SetStateVariables().
Referenced by serialize().
~Mirams2010WntOdeSystem()
Mirams2010WntOdeSystem::~Mirams2010WntOdeSystem ()
Destructor.
Definition at line 96 of file Mirams2010WntOdeSystem.cpp.
Referenced by serialize().
Member Function Documentation
EvaluateYDerivatives()
void Mirams2010WntOdeSystem::EvaluateYDerivatives (double time, const std::vector< double > & rY, std::vector< double > & rDY) virtual
Compute the RHS of the WntCellCycle system of ODEs.
Returns a vector representing the RHS of the ODEs at each time step, y' = [y1' ... yn']. An ODE solver will call this function repeatedly to solve for y = [y1 ... yn].
Parameters
time used to evaluate the RHS.
rY value of the solution vector used to evaluate the RHS.
rDY filled in with the resulting derivatives (using Alarcons et al. (2004) system of equations).
Implements AbstractOdeSystem.
Definition at line 112 of file Mirams2010WntOdeSystem.cpp.
Referenced by serialize().
GetMutationState()
const boost::shared_ptr< AbstractCellMutationState > Mirams2010WntOdeSystem::GetMutationState () const
Called by the archive function on the Wnt cell-cycle model.
Returns
mpMutationState
Definition at line 157 of file Mirams2010WntOdeSystem.cpp.
References mpMutationState.
Referenced by serialize().
GetWntLevel()
double Mirams2010WntOdeSystem::GetWntLevel () const
Returns
mWntLevel.
Definition at line 180 of file Mirams2010WntOdeSystem.cpp.
References CHASTE_CLASS_EXPORT, and mWntLevel.
Referenced by serialize().
Init()
void Mirams2010WntOdeSystem::Init ()
Initialise parameter values.
Definition at line 101 of file Mirams2010WntOdeSystem.cpp.
References mA, mB, mC, mD, mE, and mF.
Referenced by Mirams2010WntOdeSystem(), and serialize().
serialize()
template<class Archive > void Mirams2010WntOdeSystem::serialize (Archive & archive, const unsigned int version) inline private
Serialize the object and its member variables.
Parameters
archive the archive
version the current version of this class
Definition at line 95 of file Mirams2010WntOdeSystem.hpp.
References CHASTE_CLASS_EXPORT, EvaluateYDerivatives(), GetMutationState(), GetWntLevel(), Init(), Mirams2010WntOdeSystem(), SetMutationState(), and ~Mirams2010WntOdeSystem().
SetMutationState()
void Mirams2010WntOdeSystem::SetMutationState (boost::shared_ptr< AbstractCellMutationState > pMutationState)
Set the mutation state of the cell.
This should be called by the relevant cell-cycle model before any solving of the ODE system (as it is used to evaluate the Y derivatives).
Parameters
pMutationState the mutation state.
Definition at line 91 of file Mirams2010WntOdeSystem.cpp.
References mpMutationState.
Referenced by serialize().
Member Data Documentation
mA
double Mirams2010WntOdeSystem::mA private
Parameters for the Mirams et al. (2010) modelDimensional parameter a.
Definition at line 69 of file Mirams2010WntOdeSystem.hpp.
Referenced by Init(), and Mirams2010WntOdeSystem().
mB
double Mirams2010WntOdeSystem::mB private
Dimensional parameter b.
Definition at line 71 of file Mirams2010WntOdeSystem.hpp.
Referenced by Init(), and Mirams2010WntOdeSystem().
mC
double Mirams2010WntOdeSystem::mC private
Dimensional parameter c.
Definition at line 73 of file Mirams2010WntOdeSystem.hpp.
Referenced by Init(), and Mirams2010WntOdeSystem().
mD
double Mirams2010WntOdeSystem::mD private
Dimensional parameter d.
Definition at line 75 of file Mirams2010WntOdeSystem.hpp.
Referenced by Init(), and Mirams2010WntOdeSystem().
mE
double Mirams2010WntOdeSystem::mE private
Dimensional parameter e.
Definition at line 77 of file Mirams2010WntOdeSystem.hpp.
Referenced by Init().
mF
double Mirams2010WntOdeSystem::mF private
Dimensional parameter f.
Definition at line 79 of file Mirams2010WntOdeSystem.hpp.
Referenced by Init(), and Mirams2010WntOdeSystem().
mpMutationState
boost::shared_ptr<AbstractCellMutationState> Mirams2010WntOdeSystem::mpMutationState private
The mutation state of the cell (this affects the ODE system).
Definition at line 82 of file Mirams2010WntOdeSystem.hpp.
Referenced by GetMutationState(), Mirams2010WntOdeSystem(), and SetMutationState().
mWntLevel
double Mirams2010WntOdeSystem::mWntLevel private
The Wnt level (this affects the ODE system).
Definition at line 85 of file Mirams2010WntOdeSystem.hpp.
Referenced by GetWntLevel().
The documentation for this class was generated from the following files:
crypt/src/odes/Mirams2010WntOdeSystem.hpp
crypt/src/odes/Mirams2010WntOdeSystem.cpp