Chaste: RandomDirectionVertexBasedDivisionRule< SPACE_DIM > Class Template Reference
RandomDirectionVertexBasedDivisionRule< SPACE_DIM > Class Template Reference
#include <RandomDirectionVertexBasedDivisionRule.hpp>
Public Member Functions
RandomDirectionVertexBasedDivisionRule ()
virtual ~RandomDirectionVertexBasedDivisionRule ()
virtual c_vector< double, SPACE_DIM > CalculateCellDivisionVector (CellPtr pParentCell, VertexBasedCellPopulation< SPACE_DIM > &rCellPopulation)
Public Member Functions inherited from AbstractVertexBasedDivisionRule< SPACE_DIM >
AbstractVertexBasedDivisionRule ()
virtual ~AbstractVertexBasedDivisionRule ()
void OutputCellVertexBasedDivisionRuleInfo (out_stream &rParamsFile)
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Friends
class boost::serialization::access
Additional Inherited Members
Protected Member Functions inherited from AbstractVertexBasedDivisionRule< SPACE_DIM >
virtual void OutputCellVertexBasedDivisionRuleParameters (out_stream &rParamsFile)
Detailed Description
template<unsigned SPACE_DIM>
class RandomDirectionVertexBasedDivisionRule< SPACE_DIM >
A class to generate a division vector of unit length that points in a random direction.
Definition at line 52 of file RandomDirectionVertexBasedDivisionRule.hpp.
Constructor & Destructor Documentation
RandomDirectionVertexBasedDivisionRule()
template<unsigned SPACE_DIM> RandomDirectionVertexBasedDivisionRule< SPACE_DIM >::RandomDirectionVertexBasedDivisionRule () inline
Default constructor.
Definition at line 72 of file RandomDirectionVertexBasedDivisionRule.hpp.
~RandomDirectionVertexBasedDivisionRule()
template<unsigned SPACE_DIM> virtual RandomDirectionVertexBasedDivisionRule< SPACE_DIM >::~RandomDirectionVertexBasedDivisionRule () inline virtual
Empty destructor.
Definition at line 79 of file RandomDirectionVertexBasedDivisionRule.hpp.
References RandomDirectionVertexBasedDivisionRule< SPACE_DIM >::CalculateCellDivisionVector(), and EXPORT_TEMPLATE_CLASS_SAME_DIMS.
Member Function Documentation
CalculateCellDivisionVector()
template<unsigned SPACE_DIM> c_vector< double, SPACE_DIM > RandomDirectionVertexBasedDivisionRule< SPACE_DIM >::CalculateCellDivisionVector (CellPtr pParentCell, VertexBasedCellPopulation< SPACE_DIM > & rCellPopulation) virtual
Overridden CalculateCellDivisionVector() method.
Return a unit vector in a random direction, i.e the arguments are redundant for this division rule.
Parameters
pParentCell The cell to divide
rCellPopulation The vertex-based cell population
Returns
the division vector.
Implements AbstractVertexBasedDivisionRule< SPACE_DIM >.
Definition at line 39 of file RandomDirectionVertexBasedDivisionRule.cpp.
References EXPORT_TEMPLATE_CLASS_SAME_DIMS, RandomNumberGenerator::Instance(), and RandomNumberGenerator::ranf().
Referenced by RandomDirectionVertexBasedDivisionRule< SPACE_DIM >::~RandomDirectionVertexBasedDivisionRule().
serialize()
template<unsigned SPACE_DIM> template<class Archive > void RandomDirectionVertexBasedDivisionRule< SPACE_DIM >::serialize (Archive & archive, const unsigned int version) inline private
Serialize the object and its member variables.
Parameters
archive the archive
version the current version of this class
Definition at line 63 of file RandomDirectionVertexBasedDivisionRule.hpp.
The documentation for this class was generated from the following files:
cell_based/src/population/division_rules/RandomDirectionVertexBasedDivisionRule.hpp
cell_based/src/population/division_rules/RandomDirectionVertexBasedDivisionRule.cpp