Chaste: AbstractChasteRegion< SPACE_DIM > Class Template Reference
AbstractChasteRegion< SPACE_DIM > Class Template Reference abstract
#include <AbstractChasteRegion.hpp>
Public Member Functions
AbstractChasteRegion ()
virtual void Destroy ()
virtual ~AbstractChasteRegion ()
virtual bool DoesContain (const ChastePoint< SPACE_DIM > &rPointToCheck) const =0
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Friends
class boost::serialization::access
Detailed Description
template<unsigned SPACE_DIM>
class AbstractChasteRegion< SPACE_DIM >
Abstract base class for Chaste regions.
Definition at line 53 of file AbstractChasteRegion.hpp.
Constructor & Destructor Documentation
AbstractChasteRegion()
template<unsigned SPACE_DIM> AbstractChasteRegion< SPACE_DIM >::AbstractChasteRegion () inline
Constructor
Definition at line 73 of file AbstractChasteRegion.hpp.
~AbstractChasteRegion()
template<unsigned SPACE_DIM> virtual AbstractChasteRegion< SPACE_DIM >::~AbstractChasteRegion () inline virtual
Virtual functions, so virtual destructor.
Definition at line 87 of file AbstractChasteRegion.hpp.
References AbstractChasteRegion< SPACE_DIM >::DoesContain(), and TEMPLATED_CLASS_IS_ABSTRACT_1_UNSIGNED.
Member Function Documentation
Destroy()
template<unsigned SPACE_DIM> virtual void AbstractChasteRegion< SPACE_DIM >::Destroy () inline virtual
Todo:
Proper memory management Cleans any data which the concrete class may have created (archiving)
Definition at line 80 of file AbstractChasteRegion.hpp.
DoesContain()
template<unsigned SPACE_DIM> virtual bool AbstractChasteRegion< SPACE_DIM >::DoesContain (const ChastePoint< SPACE_DIM > & rPointToCheck) const pure virtual
Checks whether the Chaste point is contained in the region. implemented in the concrete classes
Parameters
rPointToCheck Point to be checked to be contained in the region
Returns
true if the point is contained, false otherwise
Implemented in ChasteNodesList< SPACE_DIM >, ChasteEllipsoid< SPACE_DIM >, and ChasteCuboid< SPACE_DIM >.
Referenced by ElectrodesStimulusFactory< DIM >::ComputeElectrodeTotalFlux(), and AbstractChasteRegion< SPACE_DIM >::~AbstractChasteRegion().
serialize()
template<unsigned SPACE_DIM> template<class Archive > void AbstractChasteRegion< SPACE_DIM >::serialize (Archive & archive, const unsigned int version) inline private
Archive the member variables.
Parameters
archive
version
Definition at line 64 of file AbstractChasteRegion.hpp.
Friends And Related Function Documentation
boost::serialization::access
template<unsigned SPACE_DIM> friend class boost::serialization::access friend
Needed for serialization.
Definition at line 56 of file AbstractChasteRegion.hpp.
The documentation for this class was generated from the following file:
mesh/src/common/AbstractChasteRegion.hpp