Chaste: ContactInhibitionCellCycleModel Class Reference
ContactInhibitionCellCycleModel Class Reference
#include <ContactInhibitionCellCycleModel.hpp>
Public Member Functions
ContactInhibitionCellCycleModel ()
void UpdateCellCyclePhase ()
AbstractCellCycleModel * CreateCellCycleModel ()
void SetQuiescentVolumeFraction (double quiescentVolumeFraction)
double GetQuiescentVolumeFraction () const
void SetEquilibriumVolume (double equilibriumVolume)
double GetEquilibriumVolume () const
double GetCurrentQuiescentDuration () const
double GetCurrentQuiescentOnsetTime () const
virtual void OutputCellCycleModelParameters (out_stream &rParamsFile)
Public Member Functions inherited from AbstractSimplePhaseBasedCellCycleModel
AbstractSimplePhaseBasedCellCycleModel ()
virtual ~AbstractSimplePhaseBasedCellCycleModel ()
virtual void ResetForDivision ()
void InitialiseDaughterCell ()
virtual void Initialise ()
Public Member Functions inherited from AbstractPhaseBasedCellCycleModel
AbstractPhaseBasedCellCycleModel ()
virtual ~AbstractPhaseBasedCellCycleModel ()
virtual bool ReadyToDivide ()
CellCyclePhase GetCurrentCellCyclePhase () const
virtual double GetG1Duration () const
double GetStemCellG1Duration () const
double GetTransitCellG1Duration () const
double GetSG2MDuration () const
virtual double GetSDuration () const
virtual double GetG2Duration () const
virtual double GetMDuration () const
virtual void SetStemCellG1Duration (double stemCellG1Duration)
virtual void SetTransitCellG1Duration (double transitCellG1Duration)
void SetSDuration (double sDuration)
void SetG2Duration (double g2Duration)
void SetMDuration (double mDuration)
virtual double GetAverageTransitCellCycleTime ()
virtual double GetAverageStemCellCycleTime ()
double GetMinimumGapDuration () const
void SetMinimumGapDuration (double minimumGapDuration)
Public Member Functions inherited from AbstractCellCycleModel
AbstractCellCycleModel ()
virtual ~AbstractCellCycleModel ()
void SetCell (CellPtr pCell)
CellPtr GetCell ()
virtual void SetBirthTime (double birthTime)
void SetDimension (unsigned dimension)
unsigned GetDimension () const
double GetBirthTime () const
double GetAge ()
virtual bool CanCellTerminallyDifferentiate ()
void OutputCellCycleModelInfo (out_stream &rParamsFile)
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Protected Member Functions
ContactInhibitionCellCycleModel (const ContactInhibitionCellCycleModel &rModel)
Protected Member Functions inherited from AbstractSimplePhaseBasedCellCycleModel
virtual void SetG1Duration ()
AbstractSimplePhaseBasedCellCycleModel (const AbstractSimplePhaseBasedCellCycleModel &rModel)
Protected Member Functions inherited from AbstractPhaseBasedCellCycleModel
AbstractPhaseBasedCellCycleModel (const AbstractPhaseBasedCellCycleModel &rModel)
Protected Member Functions inherited from AbstractCellCycleModel
AbstractCellCycleModel (const AbstractCellCycleModel &rModel)
Protected Attributes
double mQuiescentVolumeFraction
double mEquilibriumVolume
double mCurrentQuiescentOnsetTime
double mCurrentQuiescentDuration
Protected Attributes inherited from AbstractPhaseBasedCellCycleModel
CellCyclePhase mCurrentCellCyclePhase
double mG1Duration
double mMinimumGapDuration
double mStemCellG1Duration
double mTransitCellG1Duration
double mSDuration
double mG2Duration
double mMDuration
Protected Attributes inherited from AbstractCellCycleModel
CellPtr mpCell
double mBirthTime
bool mReadyToDivide
unsigned mDimension
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Friends
class boost::serialization::access
Detailed Description
Simple stress-based cell-cycle model.
A simple stress-dependent cell-cycle model that inherits from AbstractSimplePhaseBasedCellCycleModel. The duration of G1 phase depends on the local stress, interpreted here as deviation from target volume (or area/length in 2D/1D).
This model allows for quiescence imposed by transient periods of high stress, followed by relaxation.
Note that in this cell cycle model, quiescence is implemented by extending the G1 phase. If a cell is compressed during G2 or S phases then it will still divide, and thus cells whose volumes are smaller than the given threshold may still divide.
Definition at line 57 of file ContactInhibitionCellCycleModel.hpp.
Constructor & Destructor Documentation
ContactInhibitionCellCycleModel() [1/2]
ContactInhibitionCellCycleModel::ContactInhibitionCellCycleModel (const ContactInhibitionCellCycleModel & rModel) protected
Protected copy-constructor for use by CreateCellCycleModel. The only way for external code to create a copy of a cell cycle model is by calling that method, to ensure that a model of the correct subclass is created. This copy-constructor helps subclasses to ensure that all member variables are correctly copied when this happens.
This method is called by child classes to set member variables for a daughter cell upon cell division. Note that the parent cell cycle model will have had ResetForDivision() called just before CreateCellCycleModel() is called, so performing an exact copy of the parent is suitable behaviour. Any daughter-cell-specific initialisation can be done in InitialiseDaughterCell().
Parameters
rModel the cell cycle model to copy.
Definition at line 49 of file ContactInhibitionCellCycleModel.cpp.
ContactInhibitionCellCycleModel() [2/2]
ContactInhibitionCellCycleModel::ContactInhibitionCellCycleModel ()
Constructor.
Definition at line 40 of file ContactInhibitionCellCycleModel.cpp.
Referenced by CreateCellCycleModel().
Member Function Documentation
CreateCellCycleModel()
AbstractCellCycleModel * ContactInhibitionCellCycleModel::CreateCellCycleModel () virtual
Overridden builder method to create new instances of the cell-cycle model.
Returns
new cell-cycle model
Implements AbstractCellCycleModel.
Definition at line 141 of file ContactInhibitionCellCycleModel.cpp.
References ContactInhibitionCellCycleModel().
GetCurrentQuiescentDuration()
double ContactInhibitionCellCycleModel::GetCurrentQuiescentDuration () const
Returns
mCurrentQuiescentDuration
Definition at line 166 of file ContactInhibitionCellCycleModel.cpp.
References mCurrentQuiescentDuration.
GetCurrentQuiescentOnsetTime()
double ContactInhibitionCellCycleModel::GetCurrentQuiescentOnsetTime () const
Returns
mCurrentQuiescentOnsetTime
Definition at line 171 of file ContactInhibitionCellCycleModel.cpp.
References mCurrentQuiescentOnsetTime.
GetEquilibriumVolume()
double ContactInhibitionCellCycleModel::GetEquilibriumVolume () const
Returns
mEquilibriumVolume
Definition at line 161 of file ContactInhibitionCellCycleModel.cpp.
References mEquilibriumVolume.
GetQuiescentVolumeFraction()
double ContactInhibitionCellCycleModel::GetQuiescentVolumeFraction () const
Returns
mQuiescentVolumeFraction
Definition at line 151 of file ContactInhibitionCellCycleModel.cpp.
References mQuiescentVolumeFraction.
OutputCellCycleModelParameters()
void ContactInhibitionCellCycleModel::OutputCellCycleModelParameters (out_stream & rParamsFile) virtual
Overridden OutputCellCycleModelParameters() method.
Parameters
rParamsFile the file stream to which the parameters are output
Reimplemented from AbstractSimplePhaseBasedCellCycleModel.
Definition at line 176 of file ContactInhibitionCellCycleModel.cpp.
References CHASTE_CLASS_EXPORT, mEquilibriumVolume, mQuiescentVolumeFraction, and AbstractSimplePhaseBasedCellCycleModel::OutputCellCycleModelParameters().
serialize()
template<class Archive > void ContactInhibitionCellCycleModel::serialize (Archive & archive, const unsigned int version) inline private
Boost Serialization method for archiving/checkpointing
Parameters
archive The boost archive.
version The current version of this class.
Definition at line 69 of file ContactInhibitionCellCycleModel.hpp.
References mCurrentQuiescentDuration, mCurrentQuiescentOnsetTime, mEquilibriumVolume, and mQuiescentVolumeFraction.
SetEquilibriumVolume()
void ContactInhibitionCellCycleModel::SetEquilibriumVolume (double equilibriumVolume)
Parameters
equilibriumVolume
Definition at line 156 of file ContactInhibitionCellCycleModel.cpp.
References mEquilibriumVolume.
SetQuiescentVolumeFraction()
void ContactInhibitionCellCycleModel::SetQuiescentVolumeFraction (double quiescentVolumeFraction)
Parameters
quiescentVolumeFraction
Definition at line 146 of file ContactInhibitionCellCycleModel.cpp.
References mQuiescentVolumeFraction.
UpdateCellCyclePhase()
void ContactInhibitionCellCycleModel::UpdateCellCyclePhase () virtual
Overridden UpdateCellCyclePhase() method.
Reimplemented from AbstractSimplePhaseBasedCellCycleModel.
Definition at line 72 of file ContactInhibitionCellCycleModel.cpp.
References DOUBLE_UNSET, EXCEPTION, AbstractCellCycleModel::GetAge(), AbstractPhaseBasedCellCycleModel::GetG2Duration(), AbstractPhaseBasedCellCycleModel::GetMDuration(), AbstractPhaseBasedCellCycleModel::GetSDuration(), SimulationTime::GetTime(), SimulationTime::GetTimeStep(), SimulationTime::Instance(), AbstractPhaseBasedCellCycleModel::mCurrentCellCyclePhase, mCurrentQuiescentDuration, mCurrentQuiescentOnsetTime, mEquilibriumVolume, AbstractPhaseBasedCellCycleModel::mG1Duration, AbstractCellCycleModel::mpCell, and mQuiescentVolumeFraction.
Member Data Documentation
mCurrentQuiescentDuration
double ContactInhibitionCellCycleModel::mCurrentQuiescentDuration protected
How long the current period of quiescence has lasted. Has units of hours.
Definition at line 99 of file ContactInhibitionCellCycleModel.hpp.
Referenced by GetCurrentQuiescentDuration(), serialize(), and UpdateCellCyclePhase().
mCurrentQuiescentOnsetTime
double ContactInhibitionCellCycleModel::mCurrentQuiescentOnsetTime protected
The time when the current period of quiescence began.
Definition at line 93 of file ContactInhibitionCellCycleModel.hpp.
Referenced by GetCurrentQuiescentOnsetTime(), serialize(), and UpdateCellCyclePhase().
mEquilibriumVolume
double ContactInhibitionCellCycleModel::mEquilibriumVolume protected
The cell equilibrium volume while in G1 phase.
Definition at line 88 of file ContactInhibitionCellCycleModel.hpp.
Referenced by GetEquilibriumVolume(), OutputCellCycleModelParameters(), serialize(), SetEquilibriumVolume(), and UpdateCellCyclePhase().
mQuiescentVolumeFraction
double ContactInhibitionCellCycleModel::mQuiescentVolumeFraction protected
The fraction of the cells' equilibrium volume in G1 phase below which these cells are quiescent.
Definition at line 83 of file ContactInhibitionCellCycleModel.hpp.
Referenced by GetQuiescentVolumeFraction(), OutputCellCycleModelParameters(), serialize(), SetQuiescentVolumeFraction(), and UpdateCellCyclePhase().
The documentation for this class was generated from the following files:
cell_based/src/cell/cycle/ContactInhibitionCellCycleModel.hpp
cell_based/src/cell/cycle/ContactInhibitionCellCycleModel.cpp