Chaste: FarhadifarForce< DIM > Class Template Reference
FarhadifarForce< DIM > Class Template Reference
#include <FarhadifarForce.hpp>
Public Member Functions
FarhadifarForce ()
virtual ~FarhadifarForce ()
virtual void AddForceContribution (AbstractCellPopulation< DIM > &rCellPopulation)
virtual double GetLineTensionParameter (Node< DIM > *pNodeA, Node< DIM > *pNodeB, VertexBasedCellPopulation< DIM > &rVertexCellPopulation)
double GetAreaElasticityParameter ()
double GetPerimeterContractilityParameter ()
double GetLineTensionParameter ()
double GetBoundaryLineTensionParameter ()
void SetAreaElasticityParameter (double areaElasticityParameter)
void SetPerimeterContractilityParameter (double perimeterContractilityParameter)
void SetLineTensionParameter (double lineTensionParameter)
void SetBoundaryLineTensionParameter (double boundaryLineTensionParameter)
void OutputForceParameters (out_stream &rParamsFile)
Public Member Functions inherited from AbstractForce< DIM >
AbstractForce ()
virtual ~AbstractForce ()
virtual void AddForceContribution (AbstractCellPopulation< ELEMENT_DIM, ELEMENT_DIM > &rCellPopulation)=0
void OutputForceInfo (out_stream &rParamsFile)
virtual void WriteDataToVisualizerSetupFile (out_stream &pVizSetupFile)
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Protected Attributes
double mAreaElasticityParameter
double mPerimeterContractilityParameter
double mLineTensionParameter
double mBoundaryLineTensionParameter
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Friends
class TestForces
class boost::serialization::access
Detailed Description
template<unsigned DIM>
class FarhadifarForce< DIM >
A force class for use in Vertex-based simulations. This force is based on the Energy function proposed by Farhadifar et al in Curr. Biol., 2007, 17, 2095-2104.
Definition at line 55 of file FarhadifarForce.hpp.
Constructor & Destructor Documentation
FarhadifarForce()
template<unsigned DIM> FarhadifarForce< DIM >::FarhadifarForce ()
Constructor.
Definition at line 39 of file FarhadifarForce.cpp.
~FarhadifarForce()
template<unsigned DIM> FarhadifarForce< DIM >::~FarhadifarForce () virtual
Destructor.
Definition at line 49 of file FarhadifarForce.cpp.
Member Function Documentation
AddForceContribution()
template<unsigned DIM> void FarhadifarForce< DIM >::AddForceContribution (AbstractCellPopulation< DIM > & rCellPopulation) virtual
Overridden AddForceContribution() method.
Calculates the force on each node in the vertex-based cell population based on the energy function Farhadifar's model.
Parameters
rCellPopulation reference to the cell population
Todo:
: check whether this line influences profiling tests - if so, we should remove it.
Definition at line 54 of file FarhadifarForce.cpp.
References EXCEPTION, FarhadifarForce< DIM >::GetAreaElasticityParameter(), VertexMesh< ELEMENT_DIM, SPACE_DIM >::GetAreaGradientOfElementAtNode(), AbstractCellPopulation< ELEMENT_DIM, ELEMENT_DIM >::GetCellUsingLocationIndex(), VertexBasedCellPopulation< DIM >::GetElement(), VertexMesh< ELEMENT_DIM, SPACE_DIM >::GetElementIteratorBegin(), VertexMesh< ELEMENT_DIM, SPACE_DIM >::GetElementIteratorEnd(), AbstractElement< ELEMENT_DIM, SPACE_DIM >::GetIndex(), FarhadifarForce< DIM >::GetLineTensionParameter(), VertexMesh< ELEMENT_DIM, SPACE_DIM >::GetNextEdgeGradientOfElementAtNode(), AbstractElement< ELEMENT_DIM, SPACE_DIM >::GetNode(), VertexBasedCellPopulation< DIM >::GetNode(), MutableElement< ELEMENT_DIM, SPACE_DIM >::GetNodeLocalIndex(), VertexBasedCellPopulation< DIM >::GetNumElements(), AbstractElement< ELEMENT_DIM, SPACE_DIM >::GetNumNodes(), VertexBasedCellPopulation< DIM >::GetNumNodes(), FarhadifarForce< DIM >::GetPerimeterContractilityParameter(), VertexMesh< ELEMENT_DIM, SPACE_DIM >::GetSurfaceAreaOfElement(), VertexMesh< ELEMENT_DIM, SPACE_DIM >::GetVolumeOfElement(), and VertexBasedCellPopulation< DIM >::rGetMesh().
GetAreaElasticityParameter()
template<unsigned DIM> double FarhadifarForce< DIM >::GetAreaElasticityParameter ()
Returns
mAreaElasticityParameter
Definition at line 200 of file FarhadifarForce.cpp.
References FarhadifarForce< DIM >::mAreaElasticityParameter.
Referenced by FarhadifarForce< DIM >::AddForceContribution().
GetBoundaryLineTensionParameter()
template<unsigned DIM> double FarhadifarForce< DIM >::GetBoundaryLineTensionParameter ()
Returns
mBoundaryLineTensionParameter
Definition at line 218 of file FarhadifarForce.cpp.
References FarhadifarForce< DIM >::mBoundaryLineTensionParameter.
Referenced by FarhadifarForce< DIM >::GetLineTensionParameter().
GetLineTensionParameter() [1/2]
template<unsigned DIM> double FarhadifarForce< DIM >::GetLineTensionParameter (Node< DIM > * pNodeA, Node< DIM > * pNodeB, VertexBasedCellPopulation< DIM > & rVertexCellPopulation) virtual
Get the line tension parameter for the edge between two given nodes.
Parameters
pNodeA one node
pNodeB the other node
rVertexCellPopulation reference to the cell population
Returns
the line tension parameter for this edge.
Definition at line 169 of file FarhadifarForce.cpp.
References FarhadifarForce< DIM >::GetBoundaryLineTensionParameter(), FarhadifarForce< DIM >::GetLineTensionParameter(), and Node< SPACE_DIM >::rGetContainingElementIndices().
GetLineTensionParameter() [2/2]
template<unsigned DIM> double FarhadifarForce< DIM >::GetLineTensionParameter ()
Returns
mLineTensionParameter
Definition at line 212 of file FarhadifarForce.cpp.
References FarhadifarForce< DIM >::mLineTensionParameter.
Referenced by FarhadifarForce< DIM >::AddForceContribution(), and FarhadifarForce< DIM >::GetLineTensionParameter().
GetPerimeterContractilityParameter()
template<unsigned DIM> double FarhadifarForce< DIM >::GetPerimeterContractilityParameter ()
Returns
mPerimeterContractilityParameter
Definition at line 206 of file FarhadifarForce.cpp.
References FarhadifarForce< DIM >::mPerimeterContractilityParameter.
Referenced by FarhadifarForce< DIM >::AddForceContribution().
OutputForceParameters()
template<unsigned DIM> void FarhadifarForce< DIM >::OutputForceParameters (out_stream & rParamsFile) virtual
Overridden OutputForceParameters() method.
Parameters
rParamsFile the file stream to which the parameters are output
Implements AbstractForce< DIM >.
Definition at line 248 of file FarhadifarForce.cpp.
References EXPORT_TEMPLATE_CLASS_SAME_DIMS, FarhadifarForce< DIM >::mAreaElasticityParameter, FarhadifarForce< DIM >::mBoundaryLineTensionParameter, FarhadifarForce< DIM >::mLineTensionParameter, FarhadifarForce< DIM >::mPerimeterContractilityParameter, and AbstractForce< ELEMENT_DIM, SPACE_DIM >::OutputForceParameters().
serialize()
template<unsigned DIM> template<class Archive > void FarhadifarForce< DIM >::serialize (Archive & archive, const unsigned int version) inline private
Boost Serialization method for archiving/checkpointing. Archives the object and its member variables.
Parameters
archive The boost archive.
version The current version of this class.
Definition at line 70 of file FarhadifarForce.hpp.
References FarhadifarForce< DIM >::mAreaElasticityParameter, FarhadifarForce< DIM >::mBoundaryLineTensionParameter, FarhadifarForce< DIM >::mLineTensionParameter, and FarhadifarForce< DIM >::mPerimeterContractilityParameter.
SetAreaElasticityParameter()
template<unsigned DIM> void FarhadifarForce< DIM >::SetAreaElasticityParameter (double areaElasticityParameter)
Set mAreaElasticityParameter.
Parameters
areaElasticityParameter the new value of mAreaElasticityParameter
Definition at line 224 of file FarhadifarForce.cpp.
References FarhadifarForce< DIM >::mAreaElasticityParameter.
SetBoundaryLineTensionParameter()
template<unsigned DIM> void FarhadifarForce< DIM >::SetBoundaryLineTensionParameter (double boundaryLineTensionParameter)
Set mBoundaryLineTensionParameter.
Parameters
boundaryLineTensionParameter the new value of mBoundaryLineTensionParameter
Definition at line 242 of file FarhadifarForce.cpp.
References FarhadifarForce< DIM >::mBoundaryLineTensionParameter.
SetLineTensionParameter()
template<unsigned DIM> void FarhadifarForce< DIM >::SetLineTensionParameter (double lineTensionParameter)
Set mLineTensionParameter.
Parameters
lineTensionParameter the new value of mLineTensionParameter
Definition at line 236 of file FarhadifarForce.cpp.
References FarhadifarForce< DIM >::mLineTensionParameter.
SetPerimeterContractilityParameter()
template<unsigned DIM> void FarhadifarForce< DIM >::SetPerimeterContractilityParameter (double perimeterContractilityParameter)
Set mPerimeterContractilityParameter.
Parameters
perimeterContractilityParameter the new value of perimterContractilityParameter
Definition at line 230 of file FarhadifarForce.cpp.
References FarhadifarForce< DIM >::mPerimeterContractilityParameter.
Member Data Documentation
mAreaElasticityParameter
template<unsigned DIM> double FarhadifarForce< DIM >::mAreaElasticityParameter protected
The strength of the area term in the model. Corresponds to K_alpha in Farhadifar's paper.
Definition at line 84 of file FarhadifarForce.hpp.
Referenced by FarhadifarForce< DIM >::GetAreaElasticityParameter(), FarhadifarForce< DIM >::OutputForceParameters(), FarhadifarForce< DIM >::serialize(), and FarhadifarForce< DIM >::SetAreaElasticityParameter().
mBoundaryLineTensionParameter
template<unsigned DIM> double FarhadifarForce< DIM >::mBoundaryLineTensionParameter protected
The strength of the line tension at the boundary. This term does correspond to Lambda_{i,j} in Farhadifar's paper.
Definition at line 99 of file FarhadifarForce.hpp.
Referenced by FarhadifarForce< DIM >::GetBoundaryLineTensionParameter(), FarhadifarForce< DIM >::OutputForceParameters(), FarhadifarForce< DIM >::serialize(), and FarhadifarForce< DIM >::SetBoundaryLineTensionParameter().
mLineTensionParameter
template<unsigned DIM> double FarhadifarForce< DIM >::mLineTensionParameter protected
The strength of the line tension term in the model. Lambda_{i,j} in Farhadifar's paper.
Definition at line 94 of file FarhadifarForce.hpp.
Referenced by FarhadifarForce< DIM >::GetLineTensionParameter(), FarhadifarForce< DIM >::OutputForceParameters(), FarhadifarForce< DIM >::serialize(), and FarhadifarForce< DIM >::SetLineTensionParameter().
mPerimeterContractilityParameter
template<unsigned DIM> double FarhadifarForce< DIM >::mPerimeterContractilityParameter protected
The strength of the perimeter term in the model. Corresponds to Gamma_alpha in Farhadifar's paper.
Definition at line 89 of file FarhadifarForce.hpp.
Referenced by FarhadifarForce< DIM >::GetPerimeterContractilityParameter(), FarhadifarForce< DIM >::OutputForceParameters(), FarhadifarForce< DIM >::serialize(), and FarhadifarForce< DIM >::SetPerimeterContractilityParameter().
The documentation for this class was generated from the following files:
cell_based/src/population/forces/FarhadifarForce.hpp
cell_based/src/population/forces/FarhadifarForce.cpp