Chaste: SphereGeometryBoundaryCondition< DIM > Class Template Reference
SphereGeometryBoundaryCondition< DIM > Class Template Reference
#include <SphereGeometryBoundaryCondition.hpp>
Public Member Functions
SphereGeometryBoundaryCondition (AbstractCellPopulation< DIM > *pCellPopulation, c_vector< double, DIM > centre, double radius, double distance=1e-5)
const c_vector< double, DIM > & rGetCentreOfSphere () const
double GetRadiusOfSphere () const
void ImposeBoundaryCondition (const std::map< Node< DIM > *, c_vector< double, DIM > > &rOldLocations)
bool VerifyBoundaryCondition ()
void OutputCellPopulationBoundaryConditionParameters (out_stream &rParamsFile)
Public Member Functions inherited from AbstractCellPopulationBoundaryCondition< DIM >
AbstractCellPopulationBoundaryCondition (AbstractCellPopulation< ELEMENT_DIM, ELEMENT_DIM > *pCellPopulation)
virtual ~AbstractCellPopulationBoundaryCondition ()
virtual void ImposeBoundaryCondition (const std::map< Node< ELEMENT_DIM > *, c_vector< double, ELEMENT_DIM > > &rOldLocations)=0
const AbstractCellPopulation< ELEMENT_DIM, ELEMENT_DIM > * GetCellPopulation () const
void OutputCellPopulationBoundaryConditionInfo (out_stream &rParamsFile)
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Private Attributes
c_vector< double, DIM > mCentreOfSphere
double mRadiusOfSphere
double mMaximumDistance
Friends
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from AbstractCellPopulationBoundaryCondition< DIM >
AbstractCellPopulation< ELEMENT_DIM, ELEMENT_DIM > * mpCellPopulation
Detailed Description
template<unsigned DIM>
class SphereGeometryBoundaryCondition< DIM >
A spherical cell population boundary condition class, which restricts nodes to lie on the surface of a sphere in the domain. Although the name of this class suggests it is specific to 3D, it is actually also implemented in 2D, for which it is really a circle geometry boundary condition.
Definition at line 52 of file SphereGeometryBoundaryCondition.hpp.
Constructor & Destructor Documentation
SphereGeometryBoundaryCondition()
template<unsigned DIM> SphereGeometryBoundaryCondition< DIM >::SphereGeometryBoundaryCondition (AbstractCellPopulation< DIM > * pCellPopulation, c_vector< double, DIM > centre, double radius, double distance = 1e-5)
Constructor.
Parameters
pCellPopulation pointer to the cell population
centre the centre of the sphere
radius the radius of the sphere
distance the maximum distance from the surface of the sphere that cells may be (defaults to 1e-5)
Definition at line 40 of file SphereGeometryBoundaryCondition.cpp.
References EXCEPTION, SphereGeometryBoundaryCondition< DIM >::mMaximumDistance, AbstractCellPopulationBoundaryCondition< DIM >::mpCellPopulation, and SphereGeometryBoundaryCondition< DIM >::mRadiusOfSphere.
Referenced by SphereGeometryBoundaryCondition< DIM >::serialize().
Member Function Documentation
GetRadiusOfSphere()
template<unsigned DIM> double SphereGeometryBoundaryCondition< DIM >::GetRadiusOfSphere () const
Returns
mRadiusOfSphere.
Definition at line 69 of file SphereGeometryBoundaryCondition.cpp.
References SphereGeometryBoundaryCondition< DIM >::mRadiusOfSphere.
ImposeBoundaryCondition()
template<unsigned DIM> void SphereGeometryBoundaryCondition< DIM >::ImposeBoundaryCondition (const std::map< Node< DIM > *, c_vector< double, DIM > > & rOldLocations)
Overridden ImposeBoundaryCondition() method.
Apply the cell population boundary conditions.
Parameters
rOldLocations the node locations before any boundary conditions are applied
Definition at line 75 of file SphereGeometryBoundaryCondition.cpp.
References AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::Begin(), AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::End(), AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::GetLocationIndexUsingCell(), AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::GetLocationOfCellCentre(), AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::GetNode(), SphereGeometryBoundaryCondition< DIM >::mCentreOfSphere, SphereGeometryBoundaryCondition< DIM >::mMaximumDistance, AbstractCellPopulationBoundaryCondition< DIM >::mpCellPopulation, SphereGeometryBoundaryCondition< DIM >::mRadiusOfSphere, and Node< SPACE_DIM >::rGetModifiableLocation().
OutputCellPopulationBoundaryConditionParameters()
template<unsigned DIM> void SphereGeometryBoundaryCondition< DIM >::OutputCellPopulationBoundaryConditionParameters (out_stream & rParamsFile) virtual
Overridden OutputCellPopulationBoundaryConditionParameters() method. Output cell population boundary condition parameters to file.
Parameters
rParamsFile the file stream to which the parameters are output
Implements AbstractCellPopulationBoundaryCondition< DIM >.
Definition at line 128 of file SphereGeometryBoundaryCondition.cpp.
rGetCentreOfSphere()
template<unsigned DIM> const c_vector< double, DIM > & SphereGeometryBoundaryCondition< DIM >::rGetCentreOfSphere () const
Returns
mCentreOfSphere.
Definition at line 63 of file SphereGeometryBoundaryCondition.cpp.
References SphereGeometryBoundaryCondition< DIM >::mCentreOfSphere.
serialize()
template<unsigned DIM> template<class Archive > void SphereGeometryBoundaryCondition< DIM >::serialize (Archive & archive, const unsigned int version) inline private
Serialize the object.
Parameters
archive the archive
version the current version of this class
Definition at line 74 of file SphereGeometryBoundaryCondition.hpp.
References SphereGeometryBoundaryCondition< DIM >::mMaximumDistance, and SphereGeometryBoundaryCondition< DIM >::SphereGeometryBoundaryCondition().
VerifyBoundaryCondition()
template<unsigned DIM> bool SphereGeometryBoundaryCondition< DIM >::VerifyBoundaryCondition () virtual
Overridden VerifyBoundaryCondition() method. Verify the boundary conditions have been applied. This is called after ImposeBoundaryCondition() to ensure the condition is still satisfied.
Returns
whether the boundary conditions are satisfied.
Implements AbstractCellPopulationBoundaryCondition< DIM >.
Definition at line 103 of file SphereGeometryBoundaryCondition.cpp.
References AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::Begin(), AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::End(), AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::GetLocationOfCellCentre(), SphereGeometryBoundaryCondition< DIM >::mCentreOfSphere, SphereGeometryBoundaryCondition< DIM >::mMaximumDistance, AbstractCellPopulationBoundaryCondition< DIM >::mpCellPopulation, and SphereGeometryBoundaryCondition< DIM >::mRadiusOfSphere.
Friends And Related Function Documentation
boost::serialization::access
template<unsigned DIM> friend class boost::serialization::access friend
Needed for serialization.
Definition at line 66 of file SphereGeometryBoundaryCondition.hpp.
Member Data Documentation
mCentreOfSphere
template<unsigned DIM> c_vector<double, DIM> SphereGeometryBoundaryCondition< DIM >::mCentreOfSphere private
The centre of the sphere.
Definition at line 57 of file SphereGeometryBoundaryCondition.hpp.
Referenced by SphereGeometryBoundaryCondition< DIM >::ImposeBoundaryCondition(), SphereGeometryBoundaryCondition< DIM >::rGetCentreOfSphere(), and SphereGeometryBoundaryCondition< DIM >::VerifyBoundaryCondition().
mMaximumDistance
template<unsigned DIM> double SphereGeometryBoundaryCondition< DIM >::mMaximumDistance private
The maximum distance from the surface of the sphere that cells may be.
Definition at line 63 of file SphereGeometryBoundaryCondition.hpp.
Referenced by SphereGeometryBoundaryCondition< DIM >::ImposeBoundaryCondition(), SphereGeometryBoundaryCondition< DIM >::serialize(), SphereGeometryBoundaryCondition< DIM >::SphereGeometryBoundaryCondition(), and SphereGeometryBoundaryCondition< DIM >::VerifyBoundaryCondition().
mRadiusOfSphere
template<unsigned DIM> double SphereGeometryBoundaryCondition< DIM >::mRadiusOfSphere private
The radius of the sphere.
Definition at line 60 of file SphereGeometryBoundaryCondition.hpp.
Referenced by SphereGeometryBoundaryCondition< DIM >::GetRadiusOfSphere(), SphereGeometryBoundaryCondition< DIM >::ImposeBoundaryCondition(), SphereGeometryBoundaryCondition< DIM >::SphereGeometryBoundaryCondition(), and SphereGeometryBoundaryCondition< DIM >::VerifyBoundaryCondition().
The documentation for this class was generated from the following files:
cell_based/src/population/boundary_conditions/SphereGeometryBoundaryCondition.hpp
cell_based/src/population/boundary_conditions/SphereGeometryBoundaryCondition.cpp