Chaste: CellProliferativeTypesCountWriter< ELEMENT_DIM, SPACE_DIM > Class Template Reference
CellProliferativeTypesCountWriter< ELEMENT_DIM, SPACE_DIM > Class Template Reference
#include <CellProliferativeTypesCountWriter.hpp>
Public Member Functions
CellProliferativeTypesCountWriter ()
void VisitAnyPopulation (AbstractCellPopulation< SPACE_DIM, SPACE_DIM > *pCellPopulation)
virtual void Visit (MeshBasedCellPopulation< ELEMENT_DIM, SPACE_DIM > *pCellPopulation)
virtual void Visit (CaBasedCellPopulation< SPACE_DIM > *pCellPopulation)
virtual void Visit (NodeBasedCellPopulation< SPACE_DIM > *pCellPopulation)
virtual void Visit (PottsBasedCellPopulation< SPACE_DIM > *pCellPopulation)
virtual void Visit (VertexBasedCellPopulation< SPACE_DIM > *pCellPopulation)
Public Member Functions inherited from AbstractCellPopulationCountWriter< ELEMENT_DIM, SPACE_DIM >
AbstractCellPopulationCountWriter (const std::string &rFileName)
virtual void WriteHeader (AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM > *pCellPopulation)
Public Member Functions inherited from AbstractCellBasedWriter< ELEMENT_DIM, SPACE_DIM >
AbstractCellBasedWriter (const std::string &rFileName)
virtual ~AbstractCellBasedWriter ()
void CloseFile ()
virtual void OpenOutputFile (OutputFileHandler &rOutputFileHandler)
void OpenOutputFileForAppend (OutputFileHandler &rOutputFileHandler)
virtual void WriteTimeStamp ()
virtual void WriteNewline ()
void SetFileName (std::string fileName)
std::string GetFileName ()
Public Member Functions inherited from Identifiable
virtual ~Identifiable ()
std::string GetIdentifier () const
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Friends
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from AbstractCellBasedWriter< ELEMENT_DIM, SPACE_DIM >
std::string mFileName
out_stream mpOutStream
Detailed Description
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM>
class CellProliferativeTypesCountWriter< ELEMENT_DIM, SPACE_DIM >
A class written using the visitor pattern for writing the number of cells of each proliferative type to file.
The output file is called celltypes.dat by default.
Definition at line 49 of file CellProliferativeTypesCountWriter.hpp.
Constructor & Destructor Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> CellProliferativeTypesCountWriter< ELEMENT_DIM, SPACE_DIM >::CellProliferativeTypesCountWriter ()
Default constructor.
Definition at line 45 of file CellProliferativeTypesCountWriter.cpp.
Member Function Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> template<class Archive > void CellProliferativeTypesCountWriter< ELEMENT_DIM, SPACE_DIM >::serialize (Archive & archive, const unsigned int version) inline private
Serialize the object and its member variables.
Parameters
archive the archive
version the current version of this class
Definition at line 61 of file CellProliferativeTypesCountWriter.hpp.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void CellProliferativeTypesCountWriter< ELEMENT_DIM, SPACE_DIM >::Visit (MeshBasedCellPopulation< ELEMENT_DIM, SPACE_DIM > * pCellPopulation) virtual
Visit the population and write the number of cells in the population that have each proliferative type.
Outputs a line of tab-separated values of the form: [num stem] [num transit] [num differentiated] [num default]
where [num stem] denotes the number of cells in the population that have a StemCellProliferativeType, and so on. These counts are computed through the cell population method GetCellProliferativeTypeCount().
This line is appended to the output written by AbstractCellBasedWriter, which is a single value [present simulation time], followed by a tab.
Parameters
pCellPopulation a pointer to the MeshBasedCellPopulation to visit.
Implements AbstractCellPopulationCountWriter< ELEMENT_DIM, SPACE_DIM >.
Definition at line 65 of file CellProliferativeTypesCountWriter.cpp.
References PetscTools::AmMaster(), and AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::GetCellProliferativeTypeCount().
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void CellProliferativeTypesCountWriter< ELEMENT_DIM, SPACE_DIM >::Visit (CaBasedCellPopulation< SPACE_DIM > * pCellPopulation) virtual
Visit the population and write the number of cells in the population that have each proliferative type.
Outputs a line of tab-separated values of the form: [num stem] [num transit] [num differentiated] [num default]
where [num stem] denotes the number of cells in the population that have a StemCellProliferativeType, and so on. These counts are computed through the cell population method GetCellProliferativeTypeCount().
This line is appended to the output written by AbstractCellBasedWriter, which is a single value [present simulation time], followed by a tab.
Parameters
pCellPopulation a pointer to the CaBasedCellPopulation to visit.
Implements AbstractCellPopulationCountWriter< ELEMENT_DIM, SPACE_DIM >.
Definition at line 78 of file CellProliferativeTypesCountWriter.cpp.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void CellProliferativeTypesCountWriter< ELEMENT_DIM, SPACE_DIM >::Visit (NodeBasedCellPopulation< SPACE_DIM > * pCellPopulation) virtual
Visit the population and write the number of cells in the population that have each proliferative type.
Outputs a line of tab-separated values of the form: [num stem] [num transit] [num differentiated] [num default]
where [num stem] denotes the number of cells in the population that have a StemCellProliferativeType, and so on. These counts are computed through the cell population method GetCellProliferativeTypeCount().
This line is appended to the output written by AbstractCellBasedWriter, which is a single value [present simulation time], followed by a tab.
Parameters
pCellPopulation a pointer to the NodeBasedCellPopulation to visit.
Implements AbstractCellPopulationCountWriter< ELEMENT_DIM, SPACE_DIM >.
Definition at line 84 of file CellProliferativeTypesCountWriter.cpp.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void CellProliferativeTypesCountWriter< ELEMENT_DIM, SPACE_DIM >::Visit (PottsBasedCellPopulation< SPACE_DIM > * pCellPopulation) virtual
Visit the population and write the number of cells in the population that have each proliferative type.
Outputs a line of tab-separated values of the form: [num stem] [num transit] [num differentiated] [num default]
where [num stem] denotes the number of cells in the population that have a StemCellProliferativeType, and so on. These counts are computed through the cell population method GetCellProliferativeTypeCount().
This line is appended to the output written by AbstractCellBasedWriter, which is a single value [present simulation time], followed by a tab.
Parameters
pCellPopulation a pointer to the PottsBasedCellPopulation to visit.
Implements AbstractCellPopulationCountWriter< ELEMENT_DIM, SPACE_DIM >.
Definition at line 90 of file CellProliferativeTypesCountWriter.cpp.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void CellProliferativeTypesCountWriter< ELEMENT_DIM, SPACE_DIM >::Visit (VertexBasedCellPopulation< SPACE_DIM > * pCellPopulation) virtual
Visit the population and write the number of cells in the population that have each proliferative type.
Outputs a line of tab-separated values of the form: [num stem] [num transit] [num differentiated] [num default]
where [num stem] denotes the number of cells in the population that have a StemCellProliferativeType, and so on. These counts are computed through the cell population method GetCellProliferativeTypeCount().
This line is appended to the output written by AbstractCellBasedWriter, which is a single value [present simulation time], followed by a tab.
Parameters
pCellPopulation a pointer to the VertexBasedCellPopulation to visit.
Implements AbstractCellPopulationCountWriter< ELEMENT_DIM, SPACE_DIM >.
Definition at line 96 of file CellProliferativeTypesCountWriter.cpp.
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> void CellProliferativeTypesCountWriter< ELEMENT_DIM, SPACE_DIM >::VisitAnyPopulation (AbstractCellPopulation< SPACE_DIM, SPACE_DIM > * pCellPopulation)
A general method for writing to any population.
Parameters
pCellPopulation the population to write.
Definition at line 51 of file CellProliferativeTypesCountWriter.cpp.
References PetscTools::AmMaster(), and AbstractCellPopulation< ELEMENT_DIM, SPACE_DIM >::GetCellProliferativeTypeCount().
Friends And Related Function Documentation
template<unsigned ELEMENT_DIM, unsigned SPACE_DIM> friend class boost::serialization::access friend
Needed for serialization.
Definition at line 53 of file CellProliferativeTypesCountWriter.hpp.
The documentation for this class was generated from the following files:
cell_based/src/writers/population_count_writers/CellProliferativeTypesCountWriter.hpp
cell_based/src/writers/population_count_writers/CellProliferativeTypesCountWriter.cpp