Chaste: CombinedOdeSystemInformation Class Reference
CombinedOdeSystemInformation Class Reference
#include <CombinedOdeSystemInformation.hpp>
Classes
struct InstancePointers
Static Public Member Functions
static boost::shared_ptr
< CombinedOdeSystemInformation > Instance (const std::vector< AbstractOdeSystem * > &rSubsystems)
Protected Member Functions
CombinedOdeSystemInformation (const std::vector< boost::shared_ptr< const AbstractOdeSystemInformation > > &rSubsystemInfo)
CombinedOdeSystemInformation (const CombinedOdeSystemInformation &)
CombinedOdeSystemInformation & operator= (const CombinedOdeSystemInformation &)
void Initialise ()
Static Private Attributes
static std::vector< struct
InstancePointers > msInstances
Additional Inherited Members
Public Member Functions inherited from AbstractOdeSystemInformation
AbstractOdeSystemInformation ()
virtual ~AbstractOdeSystemInformation ()
std::string GetSystemName () const
std::string GetFreeVariableName () const
std::string GetFreeVariableUnits () const
void SetDefaultInitialConditions (const std::vector< double > &rInitialConditions)
void SetDefaultInitialCondition (unsigned index, double initialCondition)
std::vector< double > GetInitialConditions () const
const std::vector< std::string > & rGetStateVariableNames () const
const std::vector< std::string > & rGetStateVariableUnits () const
unsigned GetStateVariableIndex (const std::string &rName) const
bool HasStateVariable (const std::string &rName) const
std::string GetStateVariableUnits (unsigned index) const
const std::vector< std::string > & rGetParameterNames () const
const std::vector< std::string > & rGetParameterUnits () const
unsigned GetParameterIndex (const std::string &rName) const
bool HasParameter (const std::string &rName) const
std::string GetParameterUnits (unsigned index) const
unsigned GetNumberOfParameters () const
unsigned GetAnyVariableIndex (const std::string &rName) const
bool HasAnyVariable (const std::string &rName) const
std::string GetAnyVariableUnits (unsigned index) const
const std::vector< std::string > & rGetDerivedQuantityNames () const
const std::vector< std::string > & rGetDerivedQuantityUnits () const
unsigned GetDerivedQuantityIndex (const std::string &rName) const
bool HasDerivedQuantity (const std::string &rName) const
std::string GetDerivedQuantityUnits (unsigned index) const
unsigned GetNumberOfDerivedQuantities () const
unsigned GetNumberOfAttributes () const
bool HasAttribute (const std::string &rName) const
double GetAttribute (const std::string &rName) const
Protected Attributes inherited from AbstractOdeSystemInformation
std::string mSystemName
std::string mFreeVariableName
std::string mFreeVariableUnits
std::vector< std::string > mVariableNames
std::vector< std::string > mVariableUnits
std::vector< std::string > mParameterNames
std::vector< std::string > mParameterUnits
std::vector< std::string > mDerivedQuantityNames
std::vector< std::string > mDerivedQuantityUnits
std::map< std::string, double > mAttributes
std::vector< double > mInitialConditions
bool mInitialised
Detailed Description
Provide information about a CombinedOdeSystem, by combining the information provided by the subsystems.
Definition at line 50 of file CombinedOdeSystemInformation.hpp.
Constructor & Destructor Documentation
CombinedOdeSystemInformation::CombinedOdeSystemInformation (const std::vector< boost::shared_ptr< const AbstractOdeSystemInformation > > & rSubsystemInfo) protected
Main constructor.
Not user accessible - to obtain an instance of this class use the Instance method.
Parameters
rSubsystemInfo the information objects of the ODE systems used to construct the system we are providing information about.
Definition at line 89 of file CombinedOdeSystemInformation.cpp.
References AbstractOdeSystemInformation::mInitialConditions, AbstractOdeSystemInformation::mInitialised, AbstractOdeSystemInformation::mVariableNames, and AbstractOdeSystemInformation::mVariableUnits.
Referenced by Instance().
CombinedOdeSystemInformation::CombinedOdeSystemInformation (const CombinedOdeSystemInformation &) protected
Copy constructor. Not defined.
Member Function Documentation
void CombinedOdeSystemInformation::Initialise (void) protected virtual
We need to provide an Initialise method, but in this case all the work is done by our constructor, so this method does nothing.
Implements AbstractOdeSystemInformation.
Definition at line 123 of file CombinedOdeSystemInformation.cpp.
boost::shared_ptr< CombinedOdeSystemInformation > CombinedOdeSystemInformation::Instance (const std::vector< AbstractOdeSystem * > & rSubsystems) static
Returns
a pointer to the singleton instance, creating it if necessary.
Parameters
rSubsystems the ODE systems used to construct the system we are providing information about.
Definition at line 41 of file CombinedOdeSystemInformation.cpp.
References CombinedOdeSystemInformation(), msInstances, CombinedOdeSystemInformation::InstancePointers::pInfoInstance, and CombinedOdeSystemInformation::InstancePointers::subsystemInformation.
Referenced by CombinedOdeSystem::CombinedOdeSystem().
CombinedOdeSystemInformation& CombinedOdeSystemInformation::operator= (const CombinedOdeSystemInformation &) protected
Overloaded assignment operator. Not defined.
Returns
reference to this object (as language convention)
Member Data Documentation
std::vector< struct CombinedOdeSystemInformation::InstancePointers > CombinedOdeSystemInformation::msInstances static private
The single instance of this class for each vector of sub-systems.
Definition of the instance static member.
Definition at line 68 of file CombinedOdeSystemInformation.hpp.
Referenced by Instance().
The documentation for this class was generated from the following files:
ode/src/common/CombinedOdeSystemInformation.hpp
ode/src/common/CombinedOdeSystemInformation.cpp