Chaste: Cell Class Reference
Cell Class Reference
#include <Cell.hpp>
Public Member Functions
Cell (boost::shared_ptr< AbstractCellProperty > pMutationState, AbstractCellCycleModel *pCellCycleModel, AbstractSrnModel *pSrnModel=nullptr, bool archiving=false, CellPropertyCollection cellPropertyCollection=CellPropertyCollection())
~Cell ()
boost::shared_ptr
< AbstractCellProliferativeType > GetCellProliferativeType () const
void SetCellProliferativeType (boost::shared_ptr< AbstractCellProperty > pProliferativeType)
void SetBirthTime (double birthTime)
void SetCellCycleModel (AbstractCellCycleModel *pCellCycleModel)
AbstractCellCycleModel * GetCellCycleModel () const
void InitialiseCellCycleModel ()
void SetSrnModel (AbstractSrnModel *pSrnModel)
AbstractSrnModel * GetSrnModel () const
void InitialiseSrnModel ()
double GetAge () const
double GetBirthTime () const
double GetStartOfApoptosisTime () const
double GetApoptosisTime () const
void SetApoptosisTime (double apoptosisTime)
boost::shared_ptr
< AbstractCellMutationState > GetMutationState () const
boost::shared_ptr< CellData > GetCellData () const
bool HasCellVecData () const
boost::shared_ptr< CellVecData > GetCellVecData () const
void SetMutationState (boost::shared_ptr< AbstractCellProperty > pMutationState)
CellPropertyCollection & rGetCellPropertyCollection ()
const CellPropertyCollection & rGetCellPropertyCollection () const
void AddCellProperty (const boost::shared_ptr< AbstractCellProperty > &rProperty)
template<typename CLASS >
void RemoveCellProperty ()
template<typename CLASS >
bool HasCellProperty () const
bool ReadyToDivide ()
CellPtr Divide ()
void StartApoptosis (bool setDeathTime=true)
void Kill ()
bool HasApoptosisBegun () const
double GetTimeUntilDeath () const
bool IsDead ()
void SetLogged ()
bool IsLogged ()
void SetAncestor (boost::shared_ptr< AbstractCellProperty > pCellAncestor)
unsigned GetAncestor () const
unsigned GetCellId () const
Protected Attributes
CellPropertyCollection mCellPropertyCollection
AbstractCellCycleModel * mpCellCycleModel
AbstractSrnModel * mpSrnModel
double mDeathTime
double mStartOfApoptosisTime
double mApoptosisTime
bool mUndergoingApoptosis
bool mIsDead
bool mIsLogged
Private Member Functions
template<class Archive >
void serialize (Archive &archive, const unsigned int version)
Private Attributes
bool mCanDivide
Friends
class boost::serialization::access
Detailed Description
Cell is the basic container for all the biological information about a cell. It contains the cell-cycle model and all other biological properties such as mutation state, cell type, whether it is undergoing apoptosis or not.
This class should not store any spatial information - cells are linked to space by the AbstractCellPopulation subclasses.
Definition at line 89 of file Cell.hpp.
Constructor & Destructor Documentation
Cell::Cell (boost::shared_ptr< AbstractCellProperty > pMutationState, AbstractCellCycleModel * pCellCycleModel, AbstractSrnModel * pSrnModel = nullptr, bool archiving = false, CellPropertyCollection cellPropertyCollection = CellPropertyCollection())
Create a new cell.
Parameters
pMutationState the mutation state of the cell
pCellCycleModel the cell-cycle model to use to decide when the cell divides. This MUST be allocated using new, and will be deleted when the cell is destroyed.
pSrnModel the sub-cellular reaction network model. This MUST be allocated using new, and will be deleted when the cell is destroyed. (Defaults to NULL and is replcaed by a new NullSrnModel in the constructr)
archiving whether this constructor is being called by the archiver - do things slightly differently! (defaults to false)
cellPropertyCollection the cell property collection (defaults to NULL)
Definition at line 46 of file Cell.cpp.
References CellPropertyCollection::AddProperty(), CellPropertyCollection::Begin(), CellPropertyCollection::End(), EXCEPTION, CellPropertyCollection::HasProperty(), CellPropertyCollection::HasPropertyType(), SimulationTime::Instance(), CellPropertyRegistry::Instance(), MAKE_PTR, mCellPropertyCollection, mpCellCycleModel, mpSrnModel, AbstractSrnModel::SetCell(), and AbstractCellCycleModel::SetCell().
Referenced by Divide().
Cell::~Cell ()
Destructor, which frees the memory allocated for our cell-cycle model.
Definition at line 133 of file Cell.cpp.
References Kill(), mIsDead, mpCellCycleModel, and mpSrnModel.
Member Function Documentation
void Cell::AddCellProperty (const boost::shared_ptr< AbstractCellProperty > & rProperty)
Add a cell property to the cell. Use this method instead of calling rGetCellPropertyCollection().AddProperty() directly, to ensure that the cell property keeps correct track of the number of cells with it (if this is done).
Parameters
rProperty the property to add
Definition at line 300 of file Cell.cpp.
References CellPropertyCollection::AddProperty(), CellPropertyCollection::HasProperty(), and mCellPropertyCollection.
Referenced by SetAncestor(), SetCellProliferativeType(), SetMutationState(), and StartApoptosis().
CellPtr Cell::Divide ()
Divide this cell to produce a daughter cell. ReadyToDivide MUST have been called at the current time, and returned true.
Returns
the new daughter cell
Definition at line 460 of file Cell.cpp.
References CellPropertyCollection::AddProperty(), Cell(), AbstractCellCycleModel::CreateCellCycleModel(), AbstractSrnModel::CreateSrnModel(), GetCellData(), GetCellVecData(), GetMutationState(), CellPropertyCollection::HasPropertyType(), IsDead(), MAKE_PTR_ARGS, mApoptosisTime, mCanDivide, mCellPropertyCollection, mpCellCycleModel, mpSrnModel, CellPropertyCollection::RemoveProperty(), AbstractSrnModel::ResetForDivision(), and AbstractCellCycleModel::ResetForDivision().
double Cell::GetAge () const
Returns
the cell's age from its cell-cycle model.
Definition at line 213 of file Cell.cpp.
References AbstractCellCycleModel::GetAge(), and mpCellCycleModel.
unsigned Cell::GetAncestor () const
Returns
The ancestor object, inherited from parents or set using the method above, used for monoclonality experiments.
Definition at line 418 of file Cell.cpp.
References CellAncestor::GetAncestor(), CellPropertyCollection::GetPropertiesType(), CellPropertyCollection::GetProperty(), CellPropertyCollection::GetSize(), mCellPropertyCollection, and UNSIGNED_UNSET.
double Cell::GetApoptosisTime () const
Returns
mApoptosisTime
Definition at line 351 of file Cell.cpp.
References mApoptosisTime.
double Cell::GetBirthTime () const
Returns
the cell's birth time from its cell-cycle model.
Definition at line 218 of file Cell.cpp.
References AbstractCellCycleModel::GetBirthTime(), and mpCellCycleModel.
AbstractCellCycleModel * Cell::GetCellCycleModel () const
Returns
a pointer to the Cell's cell-cycle model.
Definition at line 183 of file Cell.cpp.
References mpCellCycleModel.
boost::shared_ptr< CellData > Cell::GetCellData () const
Get the CellData associated with the cell.
Returns
a pointer to the cell data
Definition at line 257 of file Cell.cpp.
References CellPropertyCollection::GetPropertiesType(), CellPropertyCollection::GetProperty(), CellPropertyCollection::GetSize(), and mCellPropertyCollection.
Referenced by Divide().
unsigned Cell::GetCellId () const
Returns
The cell identifier.
Definition at line 433 of file Cell.cpp.
References CellId::GetCellId(), CellPropertyCollection::GetPropertiesType(), CellPropertyCollection::GetProperty(), CellPropertyCollection::GetSize(), and mCellPropertyCollection.
boost::shared_ptr< AbstractCellProliferativeType > Cell::GetCellProliferativeType () const
Returns
the cell's proliferative type.
Definition at line 158 of file Cell.cpp.
References CellPropertyCollection::GetPropertiesType(), CellPropertyCollection::GetProperty(), CellPropertyCollection::GetSize(), and mCellPropertyCollection.
Referenced by SetCellProliferativeType().
boost::shared_ptr< CellVecData > Cell::GetCellVecData () const
Get the CellVecData associated with the cell.
Returns
a pointer to the cell Vec data
Definition at line 275 of file Cell.cpp.
References CellPropertyCollection::GetPropertiesType(), CellPropertyCollection::GetProperty(), CellPropertyCollection::GetSize(), HasCellVecData(), and mCellPropertyCollection.
Referenced by Divide().
boost::shared_ptr< AbstractCellMutationState > Cell::GetMutationState () const
Returns
the cell's current mutation state.
Definition at line 242 of file Cell.cpp.
References CellPropertyCollection::GetPropertiesType(), CellPropertyCollection::GetProperty(), CellPropertyCollection::GetSize(), and mCellPropertyCollection.
Referenced by Divide(), and SetMutationState().
AbstractSrnModel * Cell::GetSrnModel () const
Returns
a pointer to the Cell's SRN model.
Definition at line 203 of file Cell.cpp.
References mpSrnModel.
double Cell::GetStartOfApoptosisTime () const
Returns
the time at which apoptosis was commanded to start.
Definition at line 346 of file Cell.cpp.
References mStartOfApoptosisTime.
double Cell::GetTimeUntilDeath () const
Returns
How long until the cell dies (if it is in apoptosis, throws an exception if not)
Definition at line 362 of file Cell.cpp.
References EXCEPTION, SimulationTime::GetTime(), SimulationTime::Instance(), mDeathTime, and mUndergoingApoptosis.
bool Cell::HasApoptosisBegun () const
Returns
whether the cell is undergoing apoptosis or not.
Definition at line 341 of file Cell.cpp.
References mUndergoingApoptosis.
template<typename CLASS > bool Cell::HasCellProperty () const inline
Returns
whether the cell property collection contains a property that has the exact type CLASS. Just calls mCellPropertyCollection.HasProperty().
Definition at line 344 of file Cell.hpp.
References CellPropertyCollection::HasProperty(), and mCellPropertyCollection.
bool Cell::HasCellVecData () const
Checks whether there is CellVecData associated with this cell
Returns
whether the current cell stores CellVecData
Definition at line 270 of file Cell.cpp.
References CellPropertyCollection::HasPropertyType(), and mCellPropertyCollection.
Referenced by GetCellVecData().
void Cell::InitialiseCellCycleModel ()
Calls Initialise on the cell-cycle model associated with this cell.
Definition at line 188 of file Cell.cpp.
References AbstractCellCycleModel::Initialise(), and mpCellCycleModel.
void Cell::InitialiseSrnModel ()
Calls Initialise on the SRN model associated with this cell.
Definition at line 208 of file Cell.cpp.
References AbstractSrnModel::Initialise(), and mpSrnModel.
bool Cell::IsDead ()
Returns
whether the cell is dead or undergoing apoptosis.
Definition at line 372 of file Cell.cpp.
References SimulationTime::Instance(), Kill(), mApoptosisTime, mDeathTime, mIsDead, and mUndergoingApoptosis.
Referenced by Divide(), ReadyToDivide(), and StartApoptosis().
bool Cell::IsLogged ()
Returns
Whether the cell is being tracked.
Definition at line 315 of file Cell.cpp.
References mIsLogged.
void Cell::Kill ()
This labels the cell as dead, it does not delete the cell, it remains in the CellPopulation until AbstractCellPopulation::RemoveDeadCells() is called.
Definition at line 385 of file Cell.cpp.
References CellPropertyCollection::Begin(), CellPropertyCollection::End(), mCellPropertyCollection, and mIsDead.
Referenced by IsDead(), and ~Cell().
bool Cell::ReadyToDivide ()
Returns
whether this cell is ready to divide at the present simulation time. MUST be called before calling Divide().
Definition at line 444 of file Cell.cpp.
References IsDead(), mCanDivide, mpCellCycleModel, mpSrnModel, mUndergoingApoptosis, AbstractCellCycleModel::ReadyToDivide(), and AbstractSrnModel::SimulateToCurrentTime().
template<typename CLASS > void Cell::RemoveCellProperty () inline
Remove a cell property of the given type. Use this method instead of calling rGetCellPropertyCollection().AddProperty() directly, to ensure that the cell property keeps correct track of the number of cells with it (if this is done).
Definition at line 317 of file Cell.hpp.
References CellPropertyCollection::Begin(), CellPropertyCollection::End(), mCellPropertyCollection, and CellPropertyCollection::RemoveProperty().
CellPropertyCollection & Cell::rGetCellPropertyCollection ()
Returns
reference to mCellPropertyCollection.
Definition at line 290 of file Cell.cpp.
References mCellPropertyCollection.
const CellPropertyCollection & Cell::rGetCellPropertyCollection () const
Returns
reference to mCellPropertyCollection (used in archiving).
Definition at line 295 of file Cell.cpp.
References mCellPropertyCollection.
template<class Archive > void Cell::serialize (Archive & archive, const unsigned int version) inline private
Archive the member variables.
Parameters
archive the archive
version the current version of this class
Definition at line 105 of file Cell.hpp.
References mApoptosisTime, mCanDivide, mDeathTime, mIsDead, mIsLogged, mpCellCycleModel, mpSrnModel, mStartOfApoptosisTime, and mUndergoingApoptosis.
void Cell::SetAncestor (boost::shared_ptr< AbstractCellProperty > pCellAncestor)
Give the Cell an index which it passes to its children.
Parameters
pCellAncestor the cell's ancestor
Definition at line 397 of file Cell.cpp.
References AddCellProperty(), EXCEPTION, CellPropertyCollection::GetPropertiesType(), CellPropertyCollection::GetSize(), and mCellPropertyCollection.
void Cell::SetApoptosisTime (double apoptosisTime)
Set mApoptosisTime.
Parameters
apoptosisTime the new value of mApoptosisTime
Definition at line 356 of file Cell.cpp.
References mApoptosisTime.
void Cell::SetBirthTime (double birthTime)
Set the birth time of the cell - can be negative so that your cells have an age when a simulation begins
Parameters
birthTime The time the cell was born (in hours)
Definition at line 223 of file Cell.cpp.
References mpCellCycleModel, and AbstractCellCycleModel::SetBirthTime().
void Cell::SetCellCycleModel (AbstractCellCycleModel * pCellCycleModel)
Change the cell-cycle model used. This takes effect immediately.
Parameters
pCellCycleModel pointer to the cell-cycle model to use
Definition at line 173 of file Cell.cpp.
References mpCellCycleModel, and AbstractCellCycleModel::SetCell().
void Cell::SetCellProliferativeType (boost::shared_ptr< AbstractCellProperty > pProliferativeType)
Set the cell's proliferative type.
Parameters
pProliferativeType the cell's new proliferative type
Definition at line 143 of file Cell.cpp.
References AddCellProperty(), EXCEPTION, GetCellProliferativeType(), mCellPropertyCollection, and CellPropertyCollection::RemoveProperty().
void Cell::SetLogged ()
Sets a flag to perform special output on this cell only.
Definition at line 310 of file Cell.cpp.
References mIsLogged.
void Cell::SetMutationState (boost::shared_ptr< AbstractCellProperty > pMutationState)
Set the cell's mutation state.
Parameters
pMutationState the cell's new mutation state
Definition at line 228 of file Cell.cpp.
References AddCellProperty(), EXCEPTION, GetMutationState(), mCellPropertyCollection, and CellPropertyCollection::RemoveProperty().
void Cell::SetSrnModel (AbstractSrnModel * pSrnModel)
Change the SRN model used. This takes effect immediately.
Parameters
pSrnModel pointer to the SRN model to use
Definition at line 193 of file Cell.cpp.
References mpSrnModel, and AbstractSrnModel::SetCell().
void Cell::StartApoptosis (bool setDeathTime = true)
Make the cell enter apoptosis and sets mDeathTime using the apoptosis time as defined by mApoptosisTime.
Parameters
setDeathTime whether we tell the cell exactly when to die (defaults to true)
Definition at line 320 of file Cell.cpp.
References AddCellProperty(), EXCEPTION, CellPropertyRegistry::Get(), CellPropertyCollection::GetCellPropertyRegistry(), SimulationTime::GetTime(), SimulationTime::Instance(), IsDead(), mApoptosisTime, mCellPropertyCollection, mDeathTime, mStartOfApoptosisTime, and mUndergoingApoptosis.
Friends And Related Function Documentation
friend class boost::serialization::access friend
Needed for serialization.
Definition at line 97 of file Cell.hpp.
Member Data Documentation
double Cell::mApoptosisTime protected
The time it takes for a cell to fully undergo apoptosis. Has units of hours.
Definition at line 137 of file Cell.hpp.
Referenced by Divide(), GetApoptosisTime(), IsDead(), serialize(), SetApoptosisTime(), and StartApoptosis().
bool Cell::mCanDivide private
Caches the result of ReadyToDivide() so Divide() can look at it.
Definition at line 94 of file Cell.hpp.
Referenced by Divide(), ReadyToDivide(), and serialize().
CellPropertyCollection Cell::mCellPropertyCollection protected
The cell's property collection.
Definition at line 122 of file Cell.hpp.
Referenced by AddCellProperty(), Cell(), Divide(), GetAncestor(), GetCellData(), GetCellId(), GetCellProliferativeType(), GetCellVecData(), GetMutationState(), HasCellProperty(), HasCellVecData(), Kill(), RemoveCellProperty(), rGetCellPropertyCollection(), SetAncestor(), SetCellProliferativeType(), SetMutationState(), and StartApoptosis().
double Cell::mDeathTime protected
When the cell will/did die.
Definition at line 131 of file Cell.hpp.
Referenced by GetTimeUntilDeath(), IsDead(), serialize(), and StartApoptosis().
bool Cell::mIsDead protected
Whether the cell is dead or not (they exist in the CellPopulation until they are removed by AbstractCellPopulation::RemoveDeadCells().
Definition at line 146 of file Cell.hpp.
Referenced by IsDead(), Kill(), serialize(), and ~Cell().
bool Cell::mIsLogged protected
Whether the cell is being tracked specially.
Definition at line 149 of file Cell.hpp.
Referenced by IsLogged(), serialize(), and SetLogged().
AbstractCellCycleModel* Cell::mpCellCycleModel protected
The cell's cell-cycle model.
Definition at line 125 of file Cell.hpp.
Referenced by Cell(), Divide(), GetAge(), GetBirthTime(), GetCellCycleModel(), InitialiseCellCycleModel(), ReadyToDivide(), serialize(), SetBirthTime(), SetCellCycleModel(), and ~Cell().
AbstractSrnModel* Cell::mpSrnModel protected
The cell's sub-cellular reaction network (SRN) model.
Definition at line 128 of file Cell.hpp.
Referenced by Cell(), Divide(), GetSrnModel(), InitialiseSrnModel(), ReadyToDivide(), serialize(), SetSrnModel(), and ~Cell().
double Cell::mStartOfApoptosisTime protected
When the cell was commanded to start apoptosis.
Definition at line 134 of file Cell.hpp.
Referenced by GetStartOfApoptosisTime(), serialize(), and StartApoptosis().
bool Cell::mUndergoingApoptosis protected
Whether the cell is currently in apoptosis - don't divide.
Definition at line 140 of file Cell.hpp.
Referenced by GetTimeUntilDeath(), HasApoptosisBegun(), IsDead(), ReadyToDivide(), serialize(), and StartApoptosis().
The documentation for this class was generated from the following files:
cell_based/src/cell/Cell.hpp
cell_based/src/cell/Cell.cpp